### ISSUE TITLE
Create alias for std::ranges::views::iota_view

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10000]
We have started to use `boost::irange` in a number of places. For example, #9990 and #9987 add members to `FEValues`. `GeometryInfo` gained some uses in #9415 and #9622.

But I think of `boost::irange` as only a temporary solution -- C++20 has `std::ranges::views::iota_view`. I wonder whether we should do as we've done in other cases: Put a header file into `include/deal.II/base/std_cxx20` that either imports `std::ranges::views::iota_view` or defines it in terms of `boost::irange`. This way, we would get to use the new class as we've done with `std::shared_ptr` and `std::unique_ptr` before.

Opinions?

**Comment by bangerth** [comment]
I gave you all every chance to get the 10,000. Looks like you're all just hanging out at home watching TV or something!

**Comment by kronbichler** [comment]
I like this setup - `std` is the way to go as it is available.

**Comment by masterleinad** [comment]
Since there are no releases that support `ranges`, I would at least wait for after the release to do this.

**Comment by tjhei** [comment]
> I gave you all every chance to get the 10,000.

... and you wasted it for this?!? :-)

**Comment by bangerth** [comment]
On 5/1/20 8:17 AM, Timo Heister wrote:
> ... and you wasted it for this?!? :-)

Did you think I have an epic re-implementation of the Triangulation class in 
my pocket? I'm an opportunist -- every petty issue is good enough for me to 
claim that #10000!

**Comment by tjhei** [comment]
> an epic re-implementation of the Triangulation class in my pocket?

implementation of triangle support maybe? :-)

**Comment by bangerth** [comment]
On 5/1/20 9:30 AM, Timo Heister wrote:
> implementation of triangle support maybe? :-)

That would have been worth the number. #2000 was also a good one in this regard.
