### ISSUE TITLE
Compilation failure with current development version of ginkgo

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10008]
https://cdash.43-1.org/viewBuildError.php?buildid=5961

**Comment by tamiko** [comment]
@ginkgo-project *ping*

**Comment by nabw** [comment]
Hello everyone, (first comment!) 

I am currently interested in interfacing Ginkgo. Has there been any progress? If not, I will take a look at the problem and let you know if I find anything. The build error has been deleted, but apparently the problem regards linking the raw_copy_to(...) methods from the HIP and OMP executors.

**Comment by drwells** [comment]
I don't think we have made progress on this. If you want to use Ginkgo with deal.II can you just use an older release of ginkgo?

>  If not, I will take a look at the problem and let you know if I find anything.

Any help you can provide would be great so we can update the wrappers!

**Comment by nabw** [comment]
I believe I found the problem, for which I created a small pull request (request N. #11393 https://github.com/dealii/dealii/pull/11393). 

Best!

**Comment by pratikvn** [comment]
I am sorry for the tardiness. I was notified of this issue by github. I need to re-check the notification settings. I will try to resolve this as soon as possible. 

Better late than never, I guess. ¯\_(ツ)_/¯
