### ISSUE TITLE
Some improvements for project_onto_orthogonal_tensors

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#10009]
I looked into the function [project_onto_orthogonal_tensors](https://dealii.org/developer/doxygen/deal.II/classTensor.html#af4119f350cc384d64433dd9d325dc412), introduced in #9580, and I like the functionality it provides. It is a great addition to the new release of dealii.

However, I found areas that can be improved:
 - [x] It is tested within `tests/tensors/constexpr_tensor.cc` but this function is unrelated to constexpr things. *solution: move test to a new test file*
 - [x] It assumes `lapack` is available, which leads to test failure if there is no `lapack`. see [this](https://cdash.43-1.org/testDetails.php?test=41922973&build=5871) and [this](https://cdash.43-1.org/testDetails.php?test=42405948&build=5920). *solution: add `with_lapack=true`*
 - [x] It creates a dependency where `tensor.h` has to include  both `lapack_full_matrix.h` and `full_matrix.h`. This might increase compile times for all source files that need `tensor.h`. *solution: write it without `LAPACKFullMatrix`*.
 - [x] `full_matrix.h` is not included in `tensor.h` creating a broken dependency if we instantiate this function.
 - [x] The function does not work with `float`, it only works with `double`. *solution: write it in a more generic way.*
 - [x] The function assumes a tensor is already orthogonal if its determinant is 1. However, many non-orthogonal tensors have unit determinants. *solution: remove the if statement at the beginning of the function and remove the tolerance parameter altogether.*
 - [x] Copying the underlying tensor data into a matrix and back requires extra copying and dynamic allocation. *solution: improve algorithm*
 - [ ] The name could be improved too. In particular, the `s` at the end can be removed, because we are working with one tensor and not multiple tensors.

I am working on a number of PRs to fix these items one by one. I created this issue here so that we can keep track of the progress. Hopefully we can fix these before release.

For more context, here is the source code for this function.
https://github.com/dealii/dealii/blob/6309a80b94301577bc57e9ee12e17b611abdb803/include/deal.II/base/tensor.h#L2648-L2676

**Comment by bangerth** [comment]
Let's bring @MFraters into the picture :-)

**Comment by MFraters** [comment]
@bangerth Thanks for involving me :)

@rezarastak, these are great proposals and I think you are correct that it is best done incrementally. This code can certainly use improvement and I will be following this with interest!

Point 5: Yes, that was something we left open.

Point 6: Like I said in #10033, I don't think it is correct to just remove the tolerance parameters, but let's discuss it in that pull request.

Point 7: That would be great :)

Point 8: hmm, you are right, the plural form is not correct here.

**Comment by masterleinad** [comment]
>     * The name could be improved too. In particular, the `s` at the end can be removed, because we are working with one tensor and not multiple tensors.

This function is projecting a tensor onto the space of orthogonal tensors and I am pretty sure that is the reason for @bangerth suggesting the name.

**Comment by bangerth** [comment]
Yep, like @masterleinad says. (Except it's not a space but just a set -- think of it like the surface of a ball.)

**Comment by rezarastak** [comment]
Okay, now I understand the name better. The current name is reasonable and we can keep it. We can also think of alternative names such as `closest_orthogonal_tensor` or `orthogonal_projection`

**Comment by rezarastak** [comment]
I am satisfied with the changes we did here. No need to keep this issue open.
