### ISSUE TITLE
Error when Using deal.II on native Windows

### ISSUE THREAD

**Issue by iiamdone** [dealii/dealii#10023]
Dear all:
i meet a problem when i try to complier dealii on Windows, i follow exactly the way: 
```
set PreferredToolArchitecture=x64
cd c:\dealii
mkdir build
cd c:\dealii\build
cmake -G "Visual Studio 15 2017 Win64"
```
But there turn out an error:
```
c:\dealii\build>cmake -G "Visual Studio 15 2017 Win64"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- This is CMake 3.17.2
--
-- Include C:/dealii/build/cmake/setup_external_macros.cmake
CMake Error at CMakeLists.txt:60 (INCLUDE):
  INCLUDE could not find load file:

    C:/dealii/build/cmake/setup_external_macros.cmake


CMake Error at CMakeLists.txt:69 (SET_IF_EMPTY):
  Unknown CMake command "SET_IF_EMPTY".


-- Configuring incomplete, errors occurred!
```
i am sorry for if this is a basic question. can you give me some advice to deal with this problem.
Many thanks

**Comment by masterleinad** [comment]
> c:\dealii\build>cmake -G "Visual Studio 15 2017 Win64"

It looks like you missed the two dots at the end. It should be
```
cmake -G "Visual Studio 15 2017 Win64" ..
```
if you have a newer version you would do
```
cmake -G "Visual Studio 16 2019" ..
```

**Comment by iiamdone** [comment]
Thanks  masterleinad

As your advice i add up two dots and new error comes up,

the command i input:
`d:\dealii\build>cmake -G"Visual Studio 15 2017 Win64"..`

error shows:
`CMake Error: Could not create named generator Visual Studio 15 2017 Win64..`

And my CMAKE version is 3.17.2 , Visual studio version is 2017

many thanks，

**Comment by masterleinad** [comment]
It's hard to diagnose the problem here remotely. You might get away with omitting to specify the generator and just do
```
cmake ..
```

**Comment by jppelteret** [comment]
> d:\dealii\build>cmake -G "Visual Studio 15 2017 Win64".. 

Could it be that there's no space between the last `"` and `..`?

**Comment by iiamdone** [comment]
Thanks masterleinad and jppelteret.

The problem have solved by i edit  `CMAKE - Tools - generate and set the default generator to "Visual Studio 15 2017" `and it was success to build.
and i try  `d:\dealii\build>cmake -G "Visual Studio 15 2017 Win64" ..`again it was success too.

it is a very basic question and thanks again for both of you for the time.

**Comment by tamiko** [comment]
@iiamdone You're welcome. Closing now :smile:
