### ISSUE TITLE
Test failures when compiling without zlib

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#1005]
Here is an example of a `failing_diff` file:

```
----------------
##18      #:6   <== compressor
##18      #:6   ==> byte_order
@                                                     @@
##18      #:7   <== "vtkZLibDataCompressor"
##18      #:7   ==> "LittleEndian"
@                                                     @@
##18      #>8   <== byte_order="LittleEndian">
##18            ==>
@ Line 18 in file "output" is shorter than expected!

+++  File "/home/drwells/Documents/Code/CPP/dealii-dev-no-zlib/tests/mpi/p4est_data_out_01.with_trilinos=true.mpirun=10.output" differs from file "output"
```

Tests fail in other places because with zlib the output is in base64 and without it the output is unencoded.

**Comment by bangerth** [comment]
These tests should then only be run if zlib was found, by adding the appropriate selector to the name of the output file. Do you have a list of tests for which this is relevant?

**Comment by drwells** [comment]
I generated this list yesterday while working on something else so it may be missing some entries (I will double check). These tests pass when I compile with zlib and fail when I compile without zlib:

```
1085 - base/boost_iostreams_01.debug
1086 - base/boost_iostreams_01.release
2268 - bits/max_n_cells_01.debug
2269 - bits/max_n_cells_01.release
2485 - bits/max_n_cells_02.debug
2486 - bits/max_n_cells_02.release
3269 - deal.II/grid_out_08.debug
3270 - deal.II/grid_out_08.release
3357 - deal.II/grid_out_07.debug
3358 - deal.II/grid_out_07.release
4089 - fe/mapping_fe_field_01.debug
4875 - hp/hp_constraints_dgq.debug
4876 - hp/hp_constraints_dgq.release
5791 - mpi/parallel_vtu_01.mpirun=3.debug
5792 - mpi/parallel_vtu_01.mpirun=3.release
6221 - mpi/p4est_data_out_01.mpirun=10.debug
6222 - mpi/p4est_data_out_01.mpirun=10.release
6342 - mpi/codim_01.mpirun=3.debug
6361 - mpi/parallel_vtu_01.mpirun=1.debug
6362 - mpi/parallel_vtu_01.mpirun=1.release
6515 - mpi/p4est_data_out_01.mpirun=4.debug
6516 - mpi/p4est_data_out_01.mpirun=4.release
6672 - opencascade/plane_intersection_01.debug
6673 - opencascade/plane_intersection_01.release
6700 - opencascade/arclength_boundary_02.debug
6701 - opencascade/arclength_boundary_02.release
```

These tests fail either way (and I think that is because I am using opencascade 6.9 (so issues unrelated to this one), but I did not investigate):
```
6682 - opencascade/step_write.debug
6683 - opencascade/step_write.release
6692 - opencascade/step_create.debug
6693 - opencascade/step_create.release
```

**Comment by bangerth** [comment]
Hm, some of these clearly do need libz, and I have marked those as such in #1007. Some others I'm not quite sure. For example, `opencascade/plane_intersection` and `opencascade/arclength_boundary` don't seem to put anything compressed into their output files. The same is true for `bits/max_n_cells_0{1,2}` and `hp/hp_constraints_dgq` as well as `fe/mapping_fe_field_01`. Any insight why they would fail without libz?

**Comment by drwells** [comment]
I just reran those tests and they currently fail for both my no-libz and plain copies, so I probably did something wrong yesterday when compiling that list.

**Comment by bangerth** [comment]
OK, so is this issue fixed then?

**Comment by drwells** [comment]
Yes.
