### ISSUE TITLE
opencascade/stl_* failing

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#10086]
The opencascade/stl_* tests are all failing on all configurations in the CI, but locally it works for me with oce 6.9.1. The CI is using `OPENCASCADE_VERSION: 6.8.0`. We might want to restrict the version for that feature.

**Comment by tamiko** [comment]
The testsuite (bob) usess opencascade version 7.4.0 (the non-oce version) - that's also the same version bundled in Debian/Ubuntu and Debian/Ubuntu recently moved away from oce altogether.

**Comment by masterleinad** [comment]
@luca-heltai What are you using?

**Comment by luca-heltai** [comment]
@nicola-giuliani , I thought we solved this. Would you mind taking a look?

I'm using OCE 0.18.3 (through spack).

**Comment by nicola-giuliani** [comment]
@luca-heltai  we should have solved this, in fact the CI was running fine after @tamiko took a look at it.
