### ISSUE TITLE
p::f::t crash with a multi-level mesh

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#10085]
I try to construct a p::f::t like that

```
        Triangulation<dim> basetria;
        basetria.load(ia, 1);

        tria_pft->set_partitioner(
            [](dealii::Triangulation<dim> &tria, const unsigned int n_partitions) {
              GridTools::partition_triangulation(n_partitions, tria, SparsityTools::Partitioner::metis);
            },
            TriangulationDescription::Settings::default_
setting);

        tria_pft->copy_triangulation(basetria);
```

And I get:

```
An error occurred in line <1014> of file </dealii/include/deal.II/grid/tria_iterator.h> in function
    Accessor& dealii::TriaRawIterator<Accessor>::operator*() [with Accessor = dealii::CellAccessor<3, 3>]
The violated condition was: 
    Accessor::structure_dimension != Accessor::dimension || state() == IteratorState::valid
Additional information: 
    You tried to dereference a cell iterator for which this is not possible. More information on this iterator: level=-1, index=-1, state=past_the_end

```

Here is a callstack:
```

3  dealii::deal_II_exceptions::internals::abort                                                                                                exceptions.cc              448  
4  dealii::deal_II_exceptions::internals::issue_error_noreturn<dealii::TriaRawIterator<dealii::CellAccessor<3, 3>>::ExcDereferenceInvalidCell> exceptions.h               1321 
5  dealii::TriaRawIterator<dealii::CellAccessor<3, 3>>::operator *                                                                             tria_iterator.h            1012 
6  dealii::TriaRawIterator<dealii::CellAccessor<3, 3>>::operator->                                                                             tria_iterator.h            1044 
7  dealii::parallel::fullydistributed::Triangulation<3, 3>::create_triangulation                                                               fully_distributed_tria.cc  163  
8  dealii::parallel::fullydistributed::Triangulation<3, 3>::copy_triangulation                                                                 fully_distributed_tria.cc  251  
```

I attach the triangulation file (17k cells). 
[tria.zip](https://github.com/dealii/dealii/files/4599129/tria.zip)

**Comment by peterrum** [comment]
Thanks for the bug report! I will try to fix this asap.

**Comment by peterrum** [comment]
@agrayver Do you have any info how the base triangulation was created?

**Comment by peterrum** [comment]
@agrayver I have create a patch (see PR). Thanks for reporting the bug! Please keep on reporting the remaining `p:f:t` bugs! Only by using in by me unexpected circumstances, we will be able fix all remaining bugs!

**Comment by agrayver** [comment]
Thanks for addressing this so quickly.

**Comment by peterrum** [comment]
@agrayver You are welcome! Could you nevertheless answer the question how you have created the file? Are you running adaptive simulations, in which you adapt the serial mesh, and then copy the result to p:f:T? I am curios, what the source of this huge mesh and the last one was!

Maybe that gives me also a hint why the mesh was not accepted. I know there was a bug, but it has accepted other meshes without problem. What is the difference?

**Comment by agrayver** [comment]
This was a hyper_cube with two global refinements and adaptive refinement at a material interface. The mesh was created in python, saved and then loaded within a C++ program.

**Comment by peterrum** [comment]
> This was a hyper_cube with two global refinements and adaptive refinement at a material interface.

Have you done the same steps in C++? Maybe there s.th. I am missing... Could you share your Python code here. If not, could you send me it per mail? I am honestly puzzled by this issue since. I would like to understand it better, since I have the feeling that I have somewhere a faulty assumption.

**Comment by agrayver** [comment]
Here is the code that reproduces the mesh:

```
dx = np.ones(shape=4) * 25000
dy = dx.copy()
dz = np.array([40000, 30000, 20000, 20000, 30000, 40000])
mesh_size = np.array([np.sum(dx), np.sum(dy), np.sum(dz)])

p_origin = dealii.Point((-mesh_size / 2.).tolist())
p_end = dealii.Point((mesh_size / 2.).tolist())

triangulation = dealii.Triangulation('3D')
triangulation.generate_subdivided_steps_hyper_rectangle([dx.tolist(), dy.tolist(), dz.tolist()], p_origin, p_end, False)
triangulation.refine_global(2)

for cell in triangulation.active_cells():
    if cell.center().z < 0:
        cell.material_id = 1
    else:
        cell.material_id = 2

for i in range(2):
    for cell in triangulation.active_cells():
        if cell.material_id == 1:
            continue
            
        faces = cell.faces()
        for n in range(len(faces)):
            if not faces[n].at_boundary():
                neighbor = cell.neighbor(n)
                if neighbor.material_id == 1:
                    cell.refine_flag = 'isotropic'
                        
    triangulation.execute_coarsening_and_refinement()
```

**Comment by peterrum** [comment]
@agrayver I am currently implementing your code in C++ and reading through your code. One suggestion to it:
```python
        faces = cell.faces()
        for n, face in enumerate(faces):
            if not face.at_boundary():
                neighbor = cell.neighbor(n)
                if neighbor.material_id == 1:
                    cell.refine_flag = 'isotropic'
```
I'd wish there would be s.t. like this also in C++ ;)

**Comment by agrayver** [comment]
indeed, this is better! 

> I'd wish there would be s.t. like this also in C++ ;)

Well, [ boost::adaptors::indexed](https://www.boost.org/doc/libs/1_73_0/libs/range/doc/html/range/reference/adaptors/reference/indexed.html) :)

**Comment by peterrum** [comment]
OK. Now I understand it. It is not guaranteed that `tria.cell_iterators_on_level (level)` iterates through the cells in the right order. The reason is that there are two types of level cells on level l+1. 
- Type 1) created by refinement of cells on levels l
- Type 2) created by indirectly by smoothing condition

The first category of cells is created first (put first in the internal arrays) and as a consequence iterated over first.

**Comment by bangerth** [comment]
C++20 std::ranges offers these sorts of facilities. It would probably not be very difficult to convert what `triangulation.active_cell_iterators()` returns to something that could be used with `boost::adaptors::indexed` and similar things.
