### ISSUE TITLE
Compilation issue in mapping_info.templates.h (version 9.2.0-pre)

### ISSUE THREAD

**Issue by dsambit** [dealii/dealii#10105]
I am trying to compile the current master branch (pulled in an hour back) using intel 18 compiler and cmake/3.13.2 (see attached [detailed.log](https://github.com/dealii/dealii/files/4603943/detailed.log)), but I get the following error

> [ 61%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/fe_bernardi_raugel.cc.o
> /home/vikramg/DFT-FE-softwares/dealiinew/dealiimaster/include/deal.II/matrix_free/mapping_info.templates.h(848): error: no instance of function template "dealii::internal::MatrixFreeFunctions::ExtractCellHelper::evaluate_on_cell" matches the argument list
>             argument types are: (const dealii::Triangulation<1, 1>, const std::pair<unsigned int, unsigned int> *, unsigned int, dealii::internal::MatrixFreeFunctions::GeometryType, dealii::internal::MatrixFreeFunctions::GeometryType [1], dealii::FEValues<1, 1>, dealii::internal::MatrixFreeFunctions::ExtractCellHelper::LocalData<1, double, dealii::VectorizedArray<double, 1UL>>)
>                 evaluate_on_cell<dim, Number, VectorizedArrayType>(
>                 ^

I used the following cmake line:
cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpif90 ../dealii

**Comment by peterrum** [comment]
@dsambit May I ask you to attach the complete error output. Thanks.

**Comment by dsambit** [comment]
@peterrum Sure!

> 
> Scanning dependencies of target obj_fe_release
> [ 61%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/block_mask.cc.o
> [ 61%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/component_mask.cc.o
> [ 61%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/fe_abf.cc.o
> [ 61%] Building CXX object source/matrix_free/CMakeFiles/obj_matrix_free_debug.dir/mapping_info.cc.o
> [ 61%] Building CXX object source/matrix_free/CMakeFiles/obj_matrix_free_debug.dir/mapping_info_inst2.cc.o
> [ 61%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/fe_bernardi_raugel.cc.o
> /home/vikramg/DFT-FE-softwares/dealiinew/dealiimaster/include/deal.II/matrix_free/mapping_info.templates.h(848): error: no instance of function template "dealii::internal::MatrixFreeFunctions::ExtractCellHelper::evaluate_on_cell" matches the argument list
>             argument types are: (const dealii::Triangulation<1, 1>, const std::pair<unsigned int, unsigned int> *, unsigned int, dealii::internal::MatrixFreeFunctions::GeometryType, dealii::internal::MatrixFreeFunctions::GeometryType [1], dealii::FEValues<1, 1>, dealii::internal::MatrixFreeFunctions::ExtractCellHelper::LocalData<1, double, dealii::VectorizedArray<double, 1UL>>)
>                 evaluate_on_cell<dim, Number, VectorizedArrayType>(
>                 ^
> /home/vikramg/DFT-FE-softwares/dealiinew/dealiimaster/include/deal.II/matrix_free/mapping_info.templates.h(570): note: this candidate was rejected because arguments do not match
>         evaluate_on_cell(const dealii::Triangulation<dim> &           tria,
>         ^
>           detected during:
>             instantiation of "void dealii::internal::MatrixFreeFunctions::ExtractCellHelper::initialize_cell_range(std::pair<unsigned int, unsigned int>, const dealii::Triangulation<dim, dim> &, const std::vector<std::pair<unsigned int, unsigned int>, std::allocator<std::pair<unsigned int, unsigned int>>> &, const std::vector<std::seed_seq::result_type={uint_least32_t={unsigned int}}, std::allocator<std::seed_seq::result_type={uint_least32_t={unsigned int}}>> &, const dealii::Mapping<dim, dim>
>                       &, dealii::internal::MatrixFreeFunctions::MappingInfo<dim, Number, VectorizedArrayType> &, std::pair<std::vector<dealii::internal::MatrixFreeFunctions::MappingInfoStorage<dim, dim, Number, VectorizedArrayType>, std::allocator<dealii::internal::MatrixFreeFunctions::MappingInfoStorage<dim, dim, Number, VectorizedArrayType>>>, dealii::internal::MatrixFreeFunctions::ExtractCellHelper::CompressedCellData<dim, Number, VectorizedArrayType>> &) [with dim=1, Number=double,
>                       VectorizedArrayType=dealii::VectorizedArray<double, 1UL>]" at line 1320
>             instantiation of "void dealii::internal::MatrixFreeFunctions::MappingInfo<dim, Number, VectorizedArrayType>::initialize_cells(const dealii::Triangulation<dim, dim> &, const std::vector<std::pair<unsigned int, unsigned int>, std::allocator<std::pair<unsigned int, unsigned int>>> &, const std::vector<std::seed_seq::result_type={uint_least32_t={unsigned int}}, std::allocator<std::seed_seq::result_type={uint_least32_t={unsigned int}}>> &, const dealii::Mapping<dim, dim> &) [with dim=1,
>                       Number=double, VectorizedArrayType=dealii::VectorizedArray<double, 1UL>]" at line 365
> 
>

**Comment by peterrum** [comment]
I must admit I don't see the problem. Maybe you could try out this diff:
```diff
diff --git a/include/deal.II/matrix_free/mapping_info.templates.h b/include/deal.II/matrix_free/mapping_info.templates.h
index 00b2f3f..8f523ba 100644
--- a/include/deal.II/matrix_free/mapping_info.templates.h
+++ b/include/deal.II/matrix_free/mapping_info.templates.h
@@ -565,7 +565,7 @@ namespace internal
       /**
        * Helper function called internally during the initialize function.
        */
-      template <int dim, typename Number, typename VectorizedArrayType>
+      template <int dim, typename VectorizedArrayType>
       void
       evaluate_on_cell(const dealii::Triangulation<dim> &           tria,
                        const std::pair<unsigned int, unsigned int> *cells,
@@ -573,7 +573,7 @@ namespace internal
                        GeometryType &                               cell_t_prev,
                        GeometryType (&cell_t)[VectorizedArrayType::size()],
                        dealii::FEValues<dim, dim> &                 fe_val,
-                       LocalData<dim, Number, VectorizedArrayType> &cell_data)
+                       LocalData<dim, typename VectorizedArrayType::value_type, VectorizedArrayType> &cell_data)
       {
         const unsigned int n_q_points   = fe_val.n_quadrature_points;
         const UpdateFlags  update_flags = fe_val.get_update_flags();
@@ -845,7 +845,7 @@ namespace internal
                        active_fe_index[cell] != active_fe_index[cell - 1])
                 cell_t_prev = general;
 
-              evaluate_on_cell<dim, Number, VectorizedArrayType>(
+              evaluate_on_cell(
                 tria,
                 &cells[cell * VectorizedArrayType::size()],
                 my_q,

```

**Comment by tjhei** [comment]
I will look at intel compilation in the next few days.
