### ISSUE TITLE
Order of arguments in GridTools::compute_aspect_ratio_of_cells

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10109]
When looking at #10108 I realized that we place the `Mapping` argument either first, like for `find_closest_vertex` or the various `find_active_cell_around_point` functions, or last to support a default argument of type `MappingQ1`. The one function that sticks out are the newly added `compute_aspect_ratio_of_cells` and `compute_maximum_aspect_ratio` that place the `mapping` argument after the `triangulation` argument. Given the interface of other functions and that have not yet had a release with this function, I would lean towards making the interface consistent and switch the order now before the release. Opinions?

FYI @nfehn

**Comment by peterrum** [comment]
I think it is more common to have mapping in the first place: e.g. `MatrixFree` and `VectorTools`.

**Comment by nfehn** [comment]
changes probably make sense if this is the deal.II standard

**Comment by tjhei** [comment]
> I would lean towards making the interface consistent and switch the order now before the release. Opinions?

yes, sounds good!
