### ISSUE TITLE
New feature: VectorNorm for fixed_fraction refinement.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#10115]
For fixed fraction refinement, we concatenate refinement criteria of multiple cells to decide which ones will be refined.

Right now, we invoke the `l1`-norm to estimate the total error and the error on subsets of cells. This is sufficient for refinement heuristics, however users may invoke a different norm in this context, especially the `l2`-norm to reconstruct results from the original paper of Kelly et al. (1983) and Melenk and Wohlmuth (2001).

I would suggest to add a new parameter `VectorNorm` to decide which norm will be used. What do you think? I'd provide a patch in the near future.

**Comment by bangerth** [comment]
Good plan!

**Comment by marcfehling** [comment]
I came up with a quick implementation and was surprised to see that the choice of norm is irrelevant here. My guess is that by changing the norm on both sides of the equation, i.e., on subsets and the whole vector, we end up with the same condition.

So for entries `c_i` of a vector `c`, we could use the `l1`-norm:
`c_0 + c_1 + ... < fraction * l1-norm(c)`
or the `l2-norm`:
`sqrt(c_0^2 + c_1^2 + ...) < fraction * l2-norm(c)`
or equivalently:
`c_0^2 + c_1^2 + ... < fraction^2 * l1-norm(c*c)`
and we would always end up with the same number of cells marked.

I think I'll scrap the idea and let's stick to the `l1`-norm.

**Comment by marcfehling** [comment]
Before I gave up the idea, I double checked my tests and forgot to reinitialize the refinement flags. Sorry.

My bad. This remains relevant. I'll open a PR soon.
