### ISSUE TITLE
[step-50] Missing references in introduction

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10114]
I observed that there are (at least) two spots in the introduction of the new step-50 tutorial program where a proper reference is missing (I overlooked that in the final review), marked `CITE EST PAPER` and `CITE MG PAPER`. I think the former is Karakashian and Pascal. Furthermore, the tutorial needs to be re-classified:
https://github.com/dealii/dealii/blob/c263c822384df26821c770e92f36fc93799547ab/examples/step-50/doc/kind#L1

I need to rush away now so I can't fix it at the moment, but it should be fixed before the release.

**Comment by tjhei** [comment]
Will fix that.
