### ISSUE TITLE
dealii.org Certificate Expired

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#10137]
It seems that the certificate of the website has expired. Trying to reach it gives the following error:

![image](https://user-images.githubusercontent.com/9609727/81572604-b2fb7e00-93a3-11ea-807d-c6f902fa27c6.png)

**Comment by jppelteret** [comment]
Thanks for the report. I [noted](https://github.com/dealii/dealii/pull/10134#issuecomment-626726252) the same as well. Hopefully we'll get this fixed promptly!

**Comment by tamiko** [comment]
@guidokanschat *ping*

**Comment by tjhei** [comment]
Guido fixed it.
