### ISSUE TITLE
Cylinder mesh should not have nonstandard face orientation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1013]
The mesh for the cylinder is an extruded 2d mesh, so it should not have nonstandard face orientations. But it does, as shown by #1009. A separate testcase comes from @rosskynch and is copied below.

```
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_reordering.h>
#include <deal.II/grid/grid_refinement.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>


#include <fstream>
#include <iostream>

using namespace dealii;

void check_grid()
{
  const unsigned int dim = 3;
  Triangulation<dim> triangulation;
  // List of meshes to test on:
  // Cube: WORKS
  //     GridGenerator::hyper_cube (triangulation, -1, 1);
  //     triangulation.refine_global (2); // WORKS
  //     GridTools::distort_random (0.2, triangulation, false); //WORKS
  
  // Rectangle: WORKS
  //     GridGenerator::hyper_rectangle (triangulation,
  //                                     Point<dim> (-1.0, -1.0, -1.0),
  //                                     Point<dim> (2.0, 1.0, 1.0));
  //     triangulation.refine_global (1); //WORKS    
  //     GridTools::distort_random (0.2, triangulation, false); //WORKS
  
  // Paralelepiped: WORKS
  //     Point<dim> corners[dim];
  //     corners[0]=Point<dim> (1.0,0.0,0.0);
  //     corners[1]=Point<dim> (0.5,1.0,0.0);
  //     corners[2]=Point<dim> (0.0,0.0,1.0);
  //     GridGenerator::parallelepiped(triangulation, corners);
  //     triangulation.refine_global(1); //WORKS
  //     GridTools::distort_random (0.2, triangulation, false); //WORKS
  
  // BREAKS HERE:
  //     Cylinder
  GridGenerator::cylinder (triangulation, 0.5, 1.0);
  //     GridReordering<dim>::reorder_cells(triangulation);
  //     static const CylinderBoundary<dim> cyl_boundary (0.5);// ALSO BREAKS WITHOUT CORRECT BOUNDARY:
  //     triangulation.set_boundary (0, cyl_boundary);
  //     triangulation.refine_global(1); // ALSO BREAKS WITHOUT REFINEMENT
  
  typename Triangulation<dim>::active_cell_iterator
  cell = triangulation.begin (),
  endc = triangulation.end();
  for (; cell!=endc; ++cell)
  {
    std::cout << cell << std::endl;
    for (unsigned int face=0;face<GeometryInfo<dim>::faces_per_cell;++face)
    {
      std::cout << face << ", " << cell->face_orientation(face) << std::endl;
    }
  }
}

int main ()
{  
  check_grid();
}
```

**Comment by bangerth** [comment]
After roughly 6 hours of debugging, I have come to conclude that even for extruded meshes, it is not always possible to find both a consistent face and edge orientation. There are simple examples of just 3 2d cells touching in one point that when extruded can either produce a consistent face orientation or a consistent edge orientation, but not both. 

Who knew. This shatters a belief of mine that I held as a fact for several years :-(

**Comment by bangerth** [comment]
![2015-06-16-115011](https://cloud.githubusercontent.com/assets/7504421/8188797/96056ca8-141d-11e5-866d-d335a54681c4.jpg)

Here is the proof. Left is a top-down view on 3 cubes that result from extruding 3 quadrilaterals. Arrows present a consistent face orientation (into the cell on one side, out of the cell on the opposite). The origin of the cell then needs to lie at the vertex where two inflow faces meet. This origin is marked by a cross.

But the origin is also where all edges are outgoing. Opposite edges then also have their directions determined. In the right drawing these edges are shown for the bottom two cells, given where the left picture has identified the origin. But these edge directions are not consistent with how we'd like to choose them for the top cell given where its origin is. So, no consistent edge orientation possible for this set of face orientations.

There is a complete set of 8 possible face orientations that are all consistent. The picture above only shows one, and shows that there is no consistent edge orientation for this one set of face orientations. One should verify that the same is true for the other 7 face orientations, but I'm pretty sure it is.

**Comment by rosskynch** [comment]
Have quickly tried the other 7 orientations and come to the same conclusion. Thanks for spending the time on this!

**Comment by bangerth** [comment]
I am no longer certain that we really want the origin to be in the place where three inbound faces come together. I suppose this is how deal.II currently handles it, but the case is really so underspecified that it is hard to tell what is correct and what is not. Someone really needs to write up what the intent is.

**Comment by guidokanschat** [comment]
The theorem you proved could have two forms:

1. The way we currently define orientations, such a thing is impossible

2. There is no way to define local face and edge numbering with orientation, such that the extruded mesh you used can be consistently oriented

Which one do you think is true?

**Comment by bangerth** [comment]
Part 1 is true: with our current definitions, no orientation is possible for the cylinder mesh.

Part 2, somewhat: I can come up with face orientations for which the cylinder mesh is orientable. The way this works goes like this: on each face, consider the restriction of the cell's xyz-coordinate system to that face; that gives you a local xi-eta coordinate system where xi is the first of the restricted xyz coordinates, and eta is the second. Then define the face direction by creating a right hand coordinate system out of xi and eta. This leads to the same face directions for the first and third pair of faces (parallel to the x and z directions), but the opposite of what we currently use for the second pair (pointing in the negative y direction for both front and back face of the cube).

Of course, this assumes that we can always correctly orient edges, because the face issue is moot if we can't orient edges. And there are plenty of meshes for which edges can't be oriented.
