### ISSUE TITLE
step-50 question: what is n_p?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10188]
@tjhei @tcclevenger : I'm trying to work through step-50 for some edits and in the section on the workload, https://dealii.org/developer/doxygen/deal.II/step_50.html#Workloadimbalance, the formula contains a symbol `n_p`. It's not explained, and I'm not sure what it's supposed to be.

If you tell me what it stands for, I'll include that into my changes.

**Comment by tcclevenger** [comment]
Yes, good catch. This represents the total number of mpi processes used to distribute the mesh.

**Comment by bangerth** [comment]
Great, thanks! Would you have grave objections if I just renamed this `P`?

**Comment by tcclevenger** [comment]
Not at all!

**Comment by bangerth** [comment]
(Because lower-case `p` is already used to denote a particular processor's index.)

**Comment by bangerth** [comment]
Separately, while I have your attention: The introduction talks about adaptively refined meshes. But the results section only shows globally refined results. I haven't looked at the code yet, but I guess this is on purpose?

**Comment by tcclevenger** [comment]
The results are also on adaptively refined meshes. We use the estimator from the intro for the number of cycles listed in the table.The number of DoFs increases by roughly 2x per cycle.

**Comment by bangerth** [comment]
Oh, I hadn't realized that. The numbers seemed so nice :-)

**Comment by tjhei** [comment]
It looks like you opened #10198. Closing this.

**Comment by bangerth** [comment]
Yes, this is fixed by #10198.
