### ISSUE TITLE
Introduce cell->child_iterators()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10206]
In the same way as we already have `cell->face_iterators()`.

**Comment by marcfehling** [comment]
Feel free to assign this to me!

**Comment by peterrum** [comment]
@marcfehling You might want to checkout #8569.

**Comment by bangerth** [comment]
@marcfehling -- are you in need of projects? ;-)

**Comment by marcfehling** [comment]
@bangerth Ha! Not necessarily, but there are so many iterations over children in the library that writing it out started to bug me (along with finding the most dominant finite element among siblings). We need more elegant ways to deal with that :-)
