### ISSUE TITLE
Bug in ParticleHandler.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#10211]
It looks like we inherited this bug: 

https://github.com/geodynamics/aspect/issues/3354

**Comment by luca-heltai** [comment]
This is high priority if we want step-70 in 9.2, otherwise it can wait for 9.3

**Comment by marcfehling** [comment]
I remember rewriting parts of the `ParticleHandler` class when I refactored the data transfer in parallel distributed applications back in 2018.

These two PRs changed the crucial parts of the `ParticleHandler` class:
#6864 -  Refactored data transfer across distributed meshes.
#7002 - Applies variable size transfer to 'ParticleHandler'.
This bug must be part of 9.1 as well if one of these PRs is responsible for it. Testsuite was fine at the time. :(

Maybe those are a good starting point to find the cause of the bug. Can you reproduce it if you fall back before/after one of these PRs?

**Comment by marcfehling** [comment]
https://github.com/dealii/dealii/blob/32e187ae4afd9027d4ad33de075c3df231beed2d/source/distributed/tria.cc#L1621-L1623
Reading over these lines again, I think that this assertion is not necessary. We will always receive fixed size data (i.e. `CellStatus` information), but not necessarily variable size data (i.e. if a cell does not own any particle at all). Thus we should be able to simply skip it.

Do step-70 and the ASPECT case finish successfully when executed in release mode? If so, we can simply skip this assertion. I'll try to reproduce this with a failing test.

**Comment by luca-heltai** [comment]
I agree. @gassmoeller was suggesting the same. They have not fixed this either in aspect. I'm now creating a minimal test that fails, will remove the assert, and see what else breaks down.

**Comment by gassmoeller** [comment]
I suggested a solution in #10219. Sorry Luca I did not see this conversation before starting to work on a fix, I hope we did not duplicate too much work.

**Comment by gassmoeller** [comment]
And yes @marcfehling: I removed the Assert and everything still works nicely.
