### ISSUE TITLE
boundingbox_6 and dim==0 errors

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#10221]
as discussed on slack with @luca-heltai and @drwells a few days ago but I don't think the fix has landed yet. @drwells did you want to look at it?

I think we need to:
1. static_ssert dim>=1 in BoundingBox.
2. Adapt the test (and anything else that breaks afterwards)

Also see:
https://cdash.43-1.org/testDetails.php?test=44333311&build=6387

**Comment by drwells** [comment]
I thought we agreed to not put the fix in 9.2. Nevertheless I did write a patch - I'll put it up in a moment.

**Comment by tjhei** [comment]
Oh, I must have forgotten. We do see test failures right now, though. If we just want to fix this test for now, that could go into 9.2.

**Comment by drwells** [comment]
I got GCC 10.1 last night and now I need to recompile everything, so this is taking a little longer than planned.
