### ISSUE TITLE
step-70: Reclassify as a "fluids" kind of tutorial

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10234]
@luca-heltai @blaisb @gassmoeller : Any objection to reclassifying step-70 as a fluid dynamics kind of tutorial? It sure demonstrates techniques, but I think it actually fits more into the fluids category.

If yes, then I'll integrate that into my list of changes I'm working on.

**Comment by tjhei** [comment]
> It sure demonstrates techniques, but I think it actually fits more into the fluids category.

I think it is fine either way, but I would think the coupling and particles are the more important aspect in step-70?

**Comment by bangerth** [comment]
I'm thinking forward to when we have other particle tutorials. And the introduction spends several pages on immersed boundary methods and barely any on particles :-)

**Comment by luca-heltai** [comment]
I'm perfectly ok with whatever you think is more appropriate. :-)
