### ISSUE TITLE
void cast in Assert

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#10239]
Maybe this is more of a question than an issue, but anyway...

Often when there is an `Assert` in the code there is also a void cast to suppress the "unused variable warning" in release mode. For example:

```c++
  Assert(numbers::value_is_zero(d),
         ExcMessage("Only assignment with zero is allowed"));
  (void)d;
```

Is there any reason why the void-cast isn't in the release version of the Assert-macro? :thinking: If it were, the void cast wouldn't be needed. Something like this:

```c++
#ifdef DEBUG
#  define Assert(cond, exc) \
    {                       \
      Actual check \
    }
#else
#  define Assert(cond, exc) \
    {                       \
      (void)(cond);         \
    }
#endif
```

**Comment by drwells** [comment]
I think that we want to avoid the second case because it will evaluate `cond`. In principle, one could write
```cpp
Assert(extremely_expensive_check(grid), ExcMessage("grid has a problem"));
```
and, if we have `(void)(cond)`, we end up evaluating the check outside of debug mode. Does this make sense?

**Comment by simonsticko** [comment]
Yeah, okey that makes sense. :+1:
