### ISSUE TITLE
complex number product type deduction is wrong

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10246]
I have some code that due to some design decisions does a rather interesting tensor product:

```
#include <deal.II/base/tensor.h>
int main()
{
  typedef std::complex<double> rank0_type;
  typedef dealii::Tensor<1, 1, rank0_type> curl_type;
  typedef dealii::Tensor<0, 2, rank0_type> permeability_type;
  permeability_type mu_inv;
  curl_type u;
  rank0_type result = u * mu_inv * u;
  return 0;
}
```

This code fails now (and compiled in December 2019):
```
/home/tamiko/workspace/step/step.cc:13:14: error: no viable conversion from 'complex<std::complex<double>>' to 'complex<double>'
  rank0_type result = u * mu_inv * u;
             ^        ~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/complex:1221:12: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'typename Tensor<1 + 1 - 2, 1, typename ProductType<complex<complex<double> >, complex<double> >::type>::tensor_type' (aka 'std::complex<std::complex<double> >') to 'const std::complex<double> &' for 1st argument
    struct complex<double>
           ^
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/complex:1226:26: note: candidate constructor not viable: no known conversion from 'typename Tensor<1 + 1 - 2, 1, typename ProductType<complex<complex<double> >, complex<double> >::type>::tensor_type' (aka 'std::complex<std::complex<double> >') to 'std::complex<double>::_ComplexT' (aka '_Complex double') for 1st argument
      _GLIBCXX_CONSTEXPR complex(_ComplexT __z) : _M_value(__z) { }
                         ^
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/complex:1228:26: note: candidate constructor not viable: no known conversion from 'typename Tensor<1 + 1 - 2, 1, typename ProductType<complex<complex<double> >, complex<double> >::type>::tensor_type' (aka 'std::complex<std::complex<double> >') to 'double' for 1st argument
      _GLIBCXX_CONSTEXPR complex(double __r = 0.0, double __i = 0.0)
                         ^
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/complex:1238:26: note: candidate constructor not viable: no known conversion from 'typename Tensor<1 + 1 - 2, 1, typename ProductType<complex<complex<double> >, complex<double> >::type>::tensor_type' (aka 'std::complex<std::complex<double> >') to 'const complex<float> &' for 1st argument
      _GLIBCXX_CONSTEXPR complex(const complex<float>& __z)
```
Note that no matter what, we should never deduce a type ` 'complex<std::complex<double>>'.
Note the the corresponding snippet of code works for `typedef double rank0_type;`

I have no time right now to bisect. But this clearly has to be fixed.

**Comment by bangerth** [comment]
```
 typedef dealii::Tensor<1, 1, rank0_type> curl_type;
 typedef dealii::Tensor<0, 2, rank0_type> permeability_type;
```
It's a bit funny to define `permeability_type` as a `Tensor<0,2>`. That's a scalar. But I think if you want to multiply with a `Tensor<1,1>`, it needs to either be a `Tensor<0,1>` or a `Tensor<2,1>`. The latter seems like the appropriate type to begin with, the former could possibly work, but `Tensor<0,2>` just seems wrong.

**Comment by tamiko** [comment]
@bangerth Yes, it is a bit funny. It was a very pragmatic way of implementing `curl * mu_inv * curl - vec * epsilon * vec` in a dimenationally independent way (and working around the unfortunate design decision that `FEValuesViews::Vector::curl` returns a `Tensor<1, 1>` instead of a scalar...

In any case. The following code fails as well (with the 2 replaced by a 1):

```
#include <deal.II/base/tensor.h>
int main()
{
  typedef std::complex<double> rank0_type;
  typedef dealii::Tensor<1, 1, rank0_type> curl_type;
  typedef dealii::Tensor<0, 1, rank0_type> permeability_type;
  permeability_type mu_inv;
  curl_type u;
  rank0_type result = u * mu_inv * u;
  return 0;
}
```

**Comment by tamiko** [comment]
Also, for the record: `mu_inv * u * u` and `mu_inv * u` fail to produce the right tensor.

**Comment by bangerth** [comment]
Yes, this code looks better. I think it should compile.

`curl_type` -- yes, that might have been an unfortunate choice. At the same time, there is genuinely not a good way to use it in a dimension-independent way...

**Comment by drwells** [comment]
I was curious so I bisected - it looks like the problem started in 32ecab6f7ffd314b45f4a6682b583482eff79850.

**Comment by masterleinad** [comment]
Also, see https://godbolt.org/z/9393R6.

**Comment by masterleinad** [comment]
This patch fixes it for me:
```diff
diff --git a/include/deal.II/base/tensor.h b/include/deal.II/base/tensor.h
index 12877fa925..ac605435c5 100644
--- a/include/deal.II/base/tensor.h
+++ b/include/deal.II/base/tensor.h
@@ -796,6 +796,12 @@ namespace internal
       Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;
   };
 
+  template <int rank, int dim, typename T, typename U>
+  struct ProductTypeImpl<Tensor<rank, dim, std::complex<T>>, std::complex<U>>
+  {
+    using type = Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;
+  };
+
   template <typename T, int rank, int dim, typename U>
   struct ProductTypeImpl<std::complex<T>, Tensor<rank, dim, U>>
   {
@@ -803,6 +809,12 @@ namespace internal
       Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;
   };
 
+  template <int rank, int dim, typename T, typename U>
+  struct ProductTypeImpl<std::complex<T>, Tensor<rank, dim, std::complex<U>>>
+  {
+    using type = Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;
+  };
+
   /**
    * The structs below are needed to initialize nested Tensor objects.
    * Also see numbers.h for another specialization.
```

**Comment by drwells** [comment]
We should definitely add a test for this and also for the original case that prompted https://github.com/dealii/dealii/commit/32ecab6f7ffd314b45f4a6682b583482eff79850.

**Comment by masterleinad** [comment]
Yes, I don't have time right now to finish this, though. I could maybe do it this night. Otherwise, just go ahead!

**Comment by tamiko** [comment]
@drwells @masterleinad Thanks for bisecting this so quickly! (Sorry for having been offline - my better half did confiscate my laptop ^^).

One quick thought: The code in question was introduced as a workaround for an old compiler, see https://github.com/dealii/dealii/pull/9456.

What about we also add a guard around the code in question with the corresponding compiler version? That way we avoid keeping these bogus `ProductTypeImpl` instantiations forever. 

Alternatively, I would rather like to see this workaround removed instead of adding more glue code...
@jppelteret how old was that compiler? Do you still have access?

**Comment by bangerth** [comment]
@jppelteret states that it was Apple Clang 8.0.0. I don't know what clang version that corresponds to.

But the changes suggested above by @masterleinad aren't wrong. The question is, though, why the existing `ProductType` specializations in that file aren't triggering.

**Comment by tamiko** [comment]
@bangerth 
> But the changes suggested above by @masterleinad aren't wrong.

I am not saying that the changes are wrong :smiley:
But I think that the original workaround:
```
 792   template <int rank, int dim, typename T, typename U>                           
 793   struct ProductTypeImpl<Tensor<rank, dim, T>, std::complex<U>>                  
 794   {                                                                              
 795     using type =                                                                 
 796       Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;         
 797   };                                                                             
 798                                                                                  
 799   template <typename T, int rank, int dim, typename U>                           
 800   struct ProductTypeImpl<std::complex<T>, Tensor<rank, dim, U>>                   
 801   {                                                                              
 802     using type =                                                                 
 803       Tensor<rank, dim, std::complex<typename ProductType<T, U>::type>>;         
 804   };
```
are unnecessary (for anything newer than clang-3.2) and indeed now let the compiler use
```
1706 template <int dim, typename Number, typename Other>                              
1707 DEAL_II_CONSTEXPR DEAL_II_CUDA_HOST_DEV inline DEAL_II_ALWAYS_INLINE             
1708   typename ProductType<Number, Other>::type                                      
1709   operator*(const Tensor<0, dim, Number> &t, const Other &object)                
1710 {                                                                                
1711   return static_cast<const Number &>(t) * object;                                
1712 } 
```
determining the wrong product.

**Comment by bangerth** [comment]
What other `ProductType` rule will then be used?

That said, I don't care one way or the other as long as we only put any patch into 9.3 :-)

**Comment by tamiko** [comment]
@bangerth Otherwise it still uses the same product (for `mu_inv * u`) but now the more general
```
363   template <typename T, typename U>                                              
364   struct ProductTypeImpl                                                         
365   {                                                                              
366     using type = decltype(std::declval<T>() * std::declval<U>());                
367   }; 
```
(in `template_constraints.h`) is used to resolve the underlying number type to `std::complex<double>`.

What about we add @masterleinad fix and add an `#if` clause around the whole thing explaining that we only need that for apple clang...
