### ISSUE TITLE
step-70: Missing viz file

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10243]
The results section references https://www.dealii.org/images/steps/developer/step-70.2d_tracing.gif, but this file does not exist.

**Comment by bangerth** [comment]
That's also true for the images further down in the results section -- see https://dealii.org/developer/doxygen/deal.II/step_70.html#Results

**Comment by bangerth** [comment]
We need to address this before the release. @luca-heltai @blaisb -- what's your plan?

**Comment by luca-heltai** [comment]
I have no longer access to the svn server. These are all available in the gist that @blaisb published at the end of the step-70 PR, and someone with svn access should upload them on the webserver.

**Comment by blaisb** [comment]
> We need to address this before the release. @luca-heltai @blaisb -- what's your plan?

All files are under the right name in the gist :  https://gist.github.com/blaisb/a211c601067bb853a23c5beae3af0d9c
I do not have access to the svn to upload the files. Ping me if there is anything you need.

**Comment by bangerth** [comment]
@blaisb The results section also references a 3d gif file that's not in the gist. Do you happen to still have the vtk files for that? I could do the same as for the 2d video.

**Comment by tamiko** [comment]
All files referenced by step-70 are now in place.
