### ISSUE TITLE
improve docu of MatrixFree::get_cell_iterator()

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#10255]
The documentation of MatrixFree::get_cell_iterator() (and similar functions) does not explain the parameters, especially `vector_number`.

**Comment by peterrum** [comment]
The variables have been renamed in the mean time and the names should be more self speaking now. I am closing this issue. @nfehn Feel free to reopen this issue if you disagree. I am trying to reduce the TODO till the new release (which is soon).
