### ISSUE TITLE
[C++17] step-70: Create output directory if necessary

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10281]
See this comment: 
https://github.com/dealii/dealii/pull/10274/files#diff-5e19932b9e815b576e4bb4f4bacac9ca

There may be other steps to which this applies as well.

**Comment by bangerth** [comment]
This can not actually be portably done with C++14, but C++17 has `std::filesystem` for which this is easy. I'll post a patch for the future and delay this issue until such a time as when we use C++17.

**Comment by blaisb** [comment]
> This can not actually be portably done with C++14, but C++17 has `std::filesystem` for which this is easy. I'll post a patch for the future and delay this issue until such a time as when we use C++17.

When you say it cannot be done portably, it is because mkdir is not portable to windows and OS X, or it's a C++ version issue?

**Comment by bangerth** [comment]
`mkdir` works, but there is no portable way to test whether a directory already exists. The poor man's way of doing this is to use `system("mkdir -p dirname");` but that's not pretty and it doesn't work if someone already has a *file* of the name when a *directory* is required. (Though I'd probably accept a patch that did that anyway.)

**Comment by bangerth** [comment]
Let's postpone this to 10.1 for when we might be able to rely on C++17.
