### ISSUE TITLE
Too many deprecation in TrilinosWrappers.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#1029]
`LinearOperator`s require that an object which only knows a matrix be able to generate temporary vectors which are consistent with the matrix parallel structure.

This used to work fine, but now

`Trilinos::MPI::Vector::reinit(const Epetra_Map &parallel_partitioning, bool fast)`

and many more like this have been deprecated. 

Since the alternatives require user input (i.e., for the moment our Trilinos Wrappers can only produce Epetra_Maps, and not IndexSets) this is not a good idea, until a viable alternative is provided for matrices, i.e., we can only deprecate those if we also replace

const Epetra_Map & 	domain_partitioner () const
const Epetra_Map & 	range_partitioner () const
const Epetra_Map & 	row_partitioner () const
const Epetra_Map & 	col_partitioner () const

with something returning the corresponding IndexSet (in our Matrix wrappers). 

A quick fix would be to provide converters from `Epetra_Map` to `IndexSet`  (the opposite is already available), but the current deprecations generate warnings for all code using `linear_operator.h` and their companions (these are include only files, so you don't see this when compiling the library, only when running tests/user programs).

**Comment by bangerth** [comment]
On 06/20/2015 04:34 AM, Luca Heltai wrote:
> Since the alternatives require user input (i.e., for the moment our Trilinos
> Wrappers can only produce Epetra_Maps, and not IndexSets) this is not a good
> idea, until a viable alternative is provided for matrices, i.e., we can only
> deprecate those if we also replace
>
> const Epetra_Map & domain_partitioner () const
> const Epetra_Map & range_partitioner () const
> const Epetra_Map & row_partitioner () const
> const Epetra_Map & col_partitioner () const
>
> with something returning the corresponding IndexSet.

Or make these functions return an IndexSet. That's an incompatible change, but 
IndexSet has the ability to convert to Epetra_Map.

The idea of these deprecations was that we wanted to get rid of using Epetra 
data types in our public interfaces. We cannot be compatible between the PETSc 
and Trilinos wrappers if we use the internal classes of these libraries.

**Comment by luca-heltai** [comment]
Yes, I understand the concern, and I agree with it. I don't mind about what solution we choose... 

Or we could just deprecate those and introduce 

~~~
domain_index_set() const;
range_index_set() const;
row_index_set() const;
col_index_set() const;
~~~

for all our matrices types.

**Comment by bangerth** [comment]
These names do not reflect that it is about the subdivision of elements onto processors. Maybe
```
domain_partition() const;
range_partition() const;
row_partition() const;
col_partition() const;
```
or
```
locally_owned_domain_indices() const;
locally_owned_range_indices() const;
locally_owned_row_indices() const;
locally_owned_col_indices() const;
```
? I think I like these last ones best, also because the prefix is a good way to have them grouped mentally. 

On a separate note, aren't the last two of these duplicative of the first two? The documentation doesn't seem to make a difference, so I'd suggest to only use the `row` and `column` names.

**Comment by bangerth** [comment]
Oh, on second look, the row/range are the same but the documentation says that the col/domain are not the same.

I think we don't actually care how exactly the matrix is partitioned. What we care about is what the vectors we multiply by and into are partitioned. So I would suggest only having functions for range and domain partitioning, in contrast to my previous comment.
