### ISSUE TITLE
code gallery: broken internal hyperlinks

### ISSUE THREAD

**Issue by stmcgovern** [dealii/dealii#10295]
Hi, 
I was doing some browsing of the code gallery today and I noticed that the "(click to inspect):" links were not returning pages, while the main descriptions pages of codes are fine. 
Example:
https://dealii.org/developer/doxygen/code-gallery/time_dependent_navier_stokes/Readme.md

Just feedback. 
Best, 
Sean

**Comment by drwells** [comment]
Thanks for the report. @jppelteret do you have time to take a look?

**Comment by jppelteret** [comment]
I don't think that I'm the right person for the job @drwells. The can confirm that the generated links point to some non-existent place on the website, and since I don't have access to the website data I cannot infer where it should be pointing to! Or am I missing something obvious?

**Comment by drwells** [comment]
The issue is a result of how we generate the code gallery programs - we create links to all the files in the repository, if I recall correctly. It's not directly related to what is on the website.

**Comment by jppelteret** [comment]
@bangerth I'm not sure if you're aware of this issue, but the internal links in the code-gallery are all broken. Any tips on where I can look to fix them? I've got zero familiarity with how this all is set up, but I guess I can make an attempt to fix it.

**Comment by bangerth** [comment]
Curiously, if I generate this on my own machine, it works. I wonder what difference that makes -- do they just not get *installed*? I'm looking at my build directory, where these files are present. I need to check what happens upon installation next, but first need to get myself to a (virtual) happy hour.

**Comment by bangerth** [comment]
I confirmed that it now all seems to work. Thanks, @stmcgovern for reporting the issue!
