### ISSUE TITLE
switch to c++ 14

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#10296]
I would propose moving to requiring c++ 14 for the dev version. As a consequence, we would require:
- clang 4.0
- gcc 5
- visual studio 15 2017 (?)

which, I don't think is a big issue.

As a consequence, we need to retire older cuda support: https://github.com/dealii/dealii/blob/4532d87a1a7f4893c8090321442a8c70e3c72e40/cmake/configure/configure_1_cuda.cmake#L79
but I don't think this is a problem. Right, @Rombur ?

Any other issues that I am not aware of?

**Comment by tamiko** [comment]
I will make a tentative pull request for the necessary cmake changes in a minute.

**Comment by masterleinad** [comment]
Disabling support for `CUDA 8` is not an issue for us.

**Comment by masterleinad** [comment]
> visual studio 15 2017 (?)

According to https://en.cppreference.com/w/cpp/compiler_support#cpp14 it's more MSVC 2019 but it's enabled in https://github.com/dealii/dealii/runs/697804125 so at least the subset of features we currently require is supported.

**Comment by bangerth** [comment]
As mentioned today, we greatly benefit from having good CI checkers. Do we have MSVC versions we can check that support C++14?

**Comment by tjhei** [comment]
> Do we have MSVC versions we can check that support C++14?

both MSVC version we run support CXX14.

**Comment by masterleinad** [comment]
I am not quite sure that I understand the question. We are already testing with `Visual Studio 16 2019` and `Visual Studio 15 2017` (and the latter also has `DEAL_WITH_CXX14=ON`).

**Comment by tamiko** [comment]
The only configuration on the tester that we lose is `gcc-4.9.4`.

**Comment by masterleinad** [comment]
> The only configuration on the tester that we lose is `gcc-4.9.4`.

which is a terrible compiler anyway.

**Comment by Rombur** [comment]
> According to en.cppreference.com/w/cpp/compiler_support#cpp14 it's more MSVC 2019 but it's enabled in dealii/dealii/runs/697804125 so at least the subset of features we currently require is supported.

If you put your mouse over 19.0, you will see that it is VS 2015 and 19.10 is VS 2017. So we should be good.

**Comment by masterleinad** [comment]
> If you put your mouse over 19.0, you will see that it is VS 2015 and 19.10 is VS 2017. So we should be good.

Thanks! MSVC and their versioning...
