### ISSUE TITLE
Replace the TBB pipeline with C++14 or TaskFlow features

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10311]
That's a precondition for getting rid of the TBB.

**Comment by bangerth** [comment]
The `pipeline.h` file has ~600 lines of code. The `pipeline.cpp` file has another ~700.

The code is difficult to read, and likely has a lot of stuff that results from supporting different configurations, so one might suspect that it could be possible to implement the whole thing with less code. On the other hand, it has rather little commentary, so it would probably not be particularly easy to understand what they are doing.

**Comment by bangerth** [comment]
Their current implementation is here: https://github.com/oneapi-src/oneTBB/blob/tbb_2020/include/tbb/pipeline.h and https://github.com/oneapi-src/oneTBB/blob/tbb_2020/src/tbb/pipeline.cpp .

**Comment by bangerth** [comment]
Here's some literature: 
* https://onlinelibrary.wiley.com/doi/full/10.1002/cpe.4175 What we need is their `MapReduce` algorithm. Our "worker" is the "map" phase, the "copier" is the "reduce" phase. They use a library called GRPPI: https://github.com/arcosuc3m/grppi and I believe their MapReduce implementation is here: https://github.com/arcosuc3m/grppi/blob/master/include/grppi/native/parallel_execution_native.h#L760-L797

* There is an interesting paper on a parallel MapReduce implementation that was proposed for some C++ standard: https://isocpp.org/files/papers/n3563.pdf On p. 17 they link to an implementation, but the link is dead. It is here now: https://code.google.com/archive/p/google-concurrency-library/wikis/PipelineExecutionFramework.wiki . It is licensed under the Apache license, so maybe we can import it.

**Comment by bangerth** [comment]
Here's a code example from the Google Concurrency Library for their MapReduce:
```
class BucketizingMapper {
 public:
  typedef int input_type;
  typedef int key_type;
  typedef float value_type;

  void start() {}

  template <typename OutIter>
  void map(const int& input,
           OutIter output) {
    output = std::pair<int, float>(input % 10, static_cast<float>(input));
  }

  void flush() {}
};

class AveragingReducer {
 public:
  typedef int key_type;
  typedef float value_type;
  typedef float output_value_type;

  void start(unsigned int shard_id) {}

  template <typename InIter, typename OutIter>
  void reduce(
      const int& key,
      InIter* value_start,
      InIter* value_end,
      OutIter output) {
    double value_sum = 0.0;
    int num_values = 0;
    for (InIter* value_iter = value_start;
         (*value_iter) != (*value_end); ++(*value_iter)) {
      value_sum += *(*value_iter);
      ++num_values;
    }

    std::cout << "reduce output " << key << " " << value_sum / num_values << std::endl;
    output = std::pair<int, float>(key, value_sum / num_values);
  }
  void flush() {}
};

class MapReduceTest : public testing::Test {
};

TEST_F(MapReduceTest, TestMR) {

  typedef gcl::blocking_map<std::map<int, float> > blocking_output_map;
  typedef gcl::map_output_iter<blocking_output_map> output_iter;
  typedef queue_front_iter<queue_base<int> > input_iter;

  blocking_output_map out_map;
  map_reduce_options<int, int, float, float, output_iter> opts;
  opts.num_mappers = 3;
  opts.num_reduce_shards = 19;
  opts.num_reducers = 5;
  opts.thread_pool = new simple_thread_pool;

  output_iter out_iter(&out_map);
  opts.out = out_iter;

  map_reduce<input_iter, output_iter,
             BucketizingMapper,
             AveragingReducer> mr(opts);
  buffer_queue<int> input_queue(1000);
  input_queue.push(10); // avg = 10.0

  input_queue.push(12);
  input_queue.push(12);
  input_queue.push(22);
  input_queue.push(22); // avg = 17.0

  // avg = 103.0
  for (int i = 0; i < 20; ++i) input_queue.push(103);

  // avg = 2754.0
  for (int i = 0; i < 20; ++i) input_queue.push(1004);
  for (int i = 0; i < 20; ++i) input_queue.push(2004);
  for (int i = 0; i < 40; ++i) input_queue.push(4004);

  // avg = 1025
  for (int i = 0; i < 40; ++i) input_queue.push(1005);
  for (int i = 0; i < 40; ++i) input_queue.push(1015);
  for (int i = 0; i < 40; ++i) input_queue.push(1025);
  for (int i = 0; i < 40; ++i) input_queue.push(1035);
  for (int i = 0; i < 40; ++i) input_queue.push(1045);
  input_queue.close();
  queue_wrapper<buffer_queue<int> > input_wrap(input_queue);
  mr.run(input_wrap.begin(), input_wrap.end());
```

**Comment by bangerth** [comment]
The way to ensure the ordering of the reduce stage (the "copier") in `WorkStream` in a DAG is to create tasks as follows:
```
W1  W2  W3  W4  W5  W6 ... Wn
|   |   |   |   |   |       |
C1  |   |   |   |   |       |
   \C2   |   |   |   |       |
      \C3 |   |   |   |
```
etc. In other words, copier Cn depends on worker Wn and copier Cn-1. The workers Wn are all independent of each other.

This DAG should be relatively easy to implement in any DAG language with a `for` loop. It also shouldn't be very difficult to append to each task Cn an operation that schedules another Wn and Cn operation.

**Comment by bangerth** [comment]
You'll note that this DAG automatically sequentializes the copier operations.

**Comment by tjhei** [comment]
@bangerth with the taskflow PRs in place, can we close this issue or is there anything else we still need to do?
