### ISSUE TITLE
Remove `Threads::Thread` and associated `Threads::new_thread`

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10321]
Dear all. I have a thorough look at all the code in `thread_management.h` and I would like to put a slightly more radical cleanup up for discussion: I would like to remove the `Threads::Thread` class and associated `Threads::new_thread` functions entirely. The rationale is that this mechanism is only used in `deal.II/lac/sparse_vanka.templates.h` and in `step-28/step-28.cc` and a couple of tests. The former should be a task anyway (as we uniformly use for everthing else in the library), step-28 I have not investigated and the tests can be easily ported.

That would reduce the redundant footprint of our custom threading code significantly.

**Comment by bangerth** [comment]
You have my blessing. Do the deprecations.

**Comment by tamiko** [comment]
Closed in favor of a new issue

**Comment by bangerth** [comment]
What's the other issue?
