### ISSUE TITLE
Merge DoFHandler and hp::DoFHandler - follow up tasks

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#10333]
Following tasks need to done after PR #10328 has been merged (and before release 9.4):
- [x] remove template parameter `DoFHandlerType` (EDIT @marcfehling #13808)
- [x] do not instantiate `hp::DoFHandler` in `templates-arguments.in`
- [x] go through documentation
- [x] update tests so that they don't use `hp::DoFHandler`
- [x] deprecated `hp::DoFHandler`
- [ ] compress indices
- [x] how to determine normal or hp mode: construction time with enum/bool or dynamic?

**Comment by peterrum** [comment]
Let's collect here places, where it is not trivial to remove `DoFHandlerType`. Maybe someone has a good workaround :)

https://github.com/dealii/dealii/blob/787848f09ac650e91530684647ea4cf98903acd4/include/deal.II/distributed/solution_transfer.h#L231-L234

https://github.com/dealii/dealii/blob/787848f09ac650e91530684647ea4cf98903acd4/include/deal.II/dofs/dof_accessor.h#L206-L207

**Comment by peterrum** [comment]
I think we made good progress here. The open points are, as far as I see, relevant for release 10.0.

**Comment by peterrum** [comment]
I think we can close this one after the release after the deprecated classes have been removed!

**Comment by marcfehling** [comment]
> I think we can close this one after the release after the deprecated classes have been removed!

Indeed! However, there is still "compress indices" left in the original list of things to do.
