### ISSUE TITLE
Fix compilation with -std=c++20 and gcc-10

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10349]
It is currently not possible to compile deal.II with `-std=c++20` due to new rules regarding operator overloading as evidenced here: https://cdash.43-1.org/viewBuildError.php?buildid=6688

As a temporary workaround it is enough to remove `LinearIndexIterator::operator!=()` which allows the compiler to resolve the overload in some compatibility mode (that simply emits a warning instead).

A proper fix for this issue might be to remove all `operator@@()` variants (in case `DEAL_II_HAVE_CXX20` is true) and replace them by a single `operator<=>()`.

**Comment by bangerth** [comment]
There ought to be a way to make this work with C++17 facilities by just adding a sufficient number of overloads, without resorting to `operator <=>`.

**Comment by tamiko** [comment]
Minimal testcase:
```
template <typename Derived> class Iterator {
public:
  bool operator==(const Derived &other) { return true; }
  bool operator!=(const Derived &other) { return false; }
};

class MyIterator : public Iterator<MyIterator> {};

int main() {
  MyIterator it1, it2;
  it1 == it2;
}
```
This emits a warning:
```
test.cc:11:7: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'MyIterator' and 'MyIterator') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
  it1 == it2;
  ~~~ ^  ~~~
test.cc:3:8: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
  bool operator==(const Derived &other) { return true; }
       ^
```
Now changing `==` to `!=`  as follows:
```
// ...
int main() {
  MyIterator it1, it2;
  it1 != it2;
}
```
emits an error:
```
test.cc:11:7: error: use of overloaded operator '!=' is ambiguous (with operand types 'MyIterator' and 'MyIterator')
  it1 != it2;
  ~~~ ^  ~~~
test.cc:4:8: note: candidate function
  bool operator!=(const Derived &other) { return false; }
       ^
test.cc:3:8: note: candidate function
  bool operator==(const Derived &other) { return true; }
       ^
test.cc:3:8: note: candidate function (with reversed parameter order)
```

**Comment by tamiko** [comment]
The issue at hand is that we should probably not have such "unmatched" operands in the first place but should define `operator@(const Derived &, const Derived &)` instead.

**Comment by bangerth** [comment]
Ugh, what a disaster. What happens if you add operators to the base class whose arguments are of type `Iterator` (not `Derived`)?

**Comment by bangerth** [comment]
The matched version you state has the disadvantage that it needs to be a global operator, and you really don't want to introduce
```
  template <typename T>
  bool operator == (T,T);
```
without restricting what `T` actually is :-)

**Comment by tamiko** [comment]
A symmetric global variant aka
```
template <class DerivedIterator, class AccessorType>
inline bool
operator==(
  const LinearIndexIterator<DerivedIterator, AccessorType> &first,
  const LinearIndexIterator<DerivedIterator, AccessorType> &second);
```
seems to be promising. Let's see whether I can get that to compile.

**Comment by drwells** [comment]
That symmetric variant doesn't work when we compare const and non-const `LinearIndexIterator`s since those have different accessor types.

**Comment by tamiko** [comment]
We're almost there (clang is now fine - more or less) - gcc is still a bit unhappy:
  https://cdash.43-1.org/viewBuildError.php?buildid=6866

**Comment by bangerth** [comment]
Do we need to address this for the next release?

**Comment by masterleinad** [comment]
It looks like this is OK now: https://cdash.43-1.org/build/266
