### ISSUE TITLE
step-69: Need videos on youtube

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10358]
@tamiko Can you give me links to the 2d and 3d videos (the latter the one you have at https://tamiko.43-1.org/developer/mach-3-cylinder-3D-1817M.mp4 ) on youtube? Then I will hook them into the results section of step-69.

**Comment by tamiko** [comment]
@bangerth Here you go: https://www.youtube.com/channel/UCIuee-M5TX35L7cfjkch6aA/

In particular:
 - https://www.youtube.com/watch?v=vBCRAF_c8m8
 - https://www.youtube.com/watch?v=xIwJZlsXpZ4
