### ISSUE TITLE
Remove the redundant edge (40->67) in the tutorial dependency graph

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#10365]
In the current `dev` version of the tutorial [dependency graph](https://dealii.org/developer/doxygen/deal.II/Tutorial.html), the directed link 40->67 is redundant, and can be removed. 

This will allow a cleaner and better layout of the dot diagram.

**Comment by bangerth** [comment]
But it isn't redundant. There is no other path from step-40 to step-67...

**Comment by bangerth** [comment]
Oh, not quite: 40->37->59->67.

So yes, maybe we should remove it. Want to write a patch? It's in `examples/step-67/doc/builds-on`.
