### ISSUE TITLE
Code gallery isn't linked into the documentation any more

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10381]
No code gallery little circles here: https://dealii.org/developer/doxygen/deal.II/Tutorial.html
Also no codes listed here: https://dealii.org/developer/doxygen/deal.II/CodeGallery.html

Anyone has an idea what happened?

**Comment by bangerth** [comment]
The same is true for the 9.2.0 documentation here: https://dealii.org/current/doxygen/deal.II/Tutorial.html

We ought to fix that pronto :-(

**Comment by drwells** [comment]
That's weird - I verified that we can build it correctly as part of the release step. Perhaps the website isn't configured to pull it in?

**Comment by tjhei** [comment]
On it. I am discussing the fix with Guido.

> The same is true for the 9.2.0 documentation here: https://dealii.org/current/doxygen/deal.II/Tutorial.html

I think we only should have it in the /developer/ version so that it is always up to date. Otherwise the version under current/ or 9.2.0/ will be out-of-date (or would require rebuilding). Let me know if you disagree.

**Comment by bangerth** [comment]
I don't know where people look up their documentation, but I think it would be nice to have a frozen version also for the releases. It's not really any different than the tutorials we have -- their also shown in their frozen versions.

**Comment by guidokanschat** [comment]
Sorry guys, when I did the 9.2 documentation, I accidentally deleted the development clone.

Currently recompiling the documentation after fixing the directory.

**Comment by tjhei** [comment]
looks good, thank you Guido. :+1:

**Comment by guidokanschat** [comment]
Might be a good idea to check after the next change in the gallery

**Comment by jppelteret** [comment]
Thank you very much for the fix @guidokanschat! Much appreciated :-)

**Comment by bangerth** [comment]
Thanks, indeed, @guidokanschat !

It works now on the dev page, but I had hoped that we could also do that on the 9.2 page at https://dealii.org/current/doxygen/deal.II/Tutorial.html . What would it take to get the code gallery on there as well?

**Comment by bangerth** [comment]
Seems fixed.
