### ISSUE TITLE
source/distributed/tria.cc does not follow API for p*est_connectivity_load

### ISSUE THREAD

**Issue by bavier** [dealii/dealii#1041]
source/distributed/tria.cc uses `long unsigned int` as the second argument for the p*est_connectivity_load routines for versions after 0.3.4.3, while the actual declaration in the p4est header uses `size_t`.

This leads to build failures on 32-bit/i686 architectures, where `long unsigned int` and `size_t` are incompatible.

**Comment by bangerth** [comment]
Are you using the current development sources or the 8.2 release? I think I fixed this a while back.

**Comment by bavier** [comment]
Yes, I'm using the 8.2.1 release.  My apologies for not checking the development source first.  Thanks for pointing out the fix; I see it's in f764598c.

**Comment by bangerth** [comment]
Already fixed by #749.
