### ISSUE TITLE
Rename TriaAccessor::set() to TriaAccessor::set_bounding_object_indices()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10438]
Follow-up to #10434: There is the awkwardly named function `TriaAccessor::set()` that just takes a bunch of integers. Its name really doesn't give away much. We should rename it to `TriaAccessor::set_bounding_object_indices()` because that's what it does: For cells, it sets the indices of the faces, for quads those of lines, for lines those of vertices.

@peterrum -- FYI. I'll let you beat me to it, or you can leave it to me.

**Comment by bangerth** [comment]
By the way, all uses of this function are in `tria.cc` and are of the form `->set(`. It should be easy to find-replace.

**Comment by peterrum** [comment]
> FYI. I'll let you beat me to it, or you can leave it to me.

I can do it if you want; shouldn't take too long. However, I would be happy if all open PRs related to triangulation could be merged till the morning (CET). I am going through the whole `tria.cc` file and analyzing which function is limited to one type of meshes. I will probably tomorrow move these functions to a single place as a preparation for generalization.
