### ISSUE TITLE
Document binary incompatibility of the Triangulation post 9.2

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#10447]
The changes done in https://github.com/dealii/dealii/pull/10326 led to binary incompatibility of the serialized triangulations. 

This concerns both triangulations saved via `tria.save` as well as those saved by using `GridOut::write_vtu` (with the GridOutFlags::Vtu::serialize_triangulation flag).

Should be this be properly documented by adding an incompatibility item? 

I've just hit this issue and it took me two hours to understand the issue...

**Comment by bangerth** [comment]
Yes, I think that is legitimate. In reality, this is by far not the first time this has happened, and we don't think that there should ever be an expectation that you can read anything that was serialized with anything other than the exact version you saved it with. But we should probably be clearer about that.

@peterrum -- FYI.

**Comment by agrayver** [comment]
Well, apart from my personal frustration of debugging this, there is a positive side -- new triangulations became lighter and faster to read :)

**Comment by peterrum** [comment]
I can write an incompatibility entry tomorrow! But, for me the binary output should be readable by the same program version (as normally done during restart). Everything else would prevent adding new features (or at least would make it very difficult).

**Comment by peterrum** [comment]
> Well, apart from my personal frustration from debugging this, 

I can understand that. Sorry about this!

> there is a positive side -- new triangulations became lighter and faster to read :)

Is that actually noticeable!?

**Comment by agrayver** [comment]
>> we don't think that there should ever be an expectation that you can read anything that was serialized with anything other than the exact version you saved it with

If only I knew about this expectation! ;)

Anyway, this is minor, but it could be easily handled through the boost::serialization [versioning](https://www.boost.org/doc/libs/1_73_0/libs/serialization/doc/tutorial.html#versioning) mechanism. In the end, there is no other mechanism to save a deal.II triangulation for a later use than serialize it. Versioning this `file format` would not harm.

**Comment by bangerth** [comment]
I'm not sure it is practical to read older formats of a triangulation. But it is definitely reasonable that we just write out a version number and throw an exception of the file we're trying to read is from an older version.
