### ISSUE TITLE
Possible bug with Particles::DataOut in parallel for particle with properties

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#10443]
While finalizing the development of step-68 I am facing some sort of issue with the Particles::DataOut. I attach dim+1 properties to my particles, the first dim are a vector and the following one is a scalar.
When running on 1, 2 or 3 processor, everything works perfectly fine as expected. When running on 4 processor, I an error at a seemingly random moment (see below).

The problem appears to be related to the data out of the particles. Indeed, if I comment the data out part with the properties, I do not get my error.
```

    particle_output.build_patches(particle_handler);

    //    particle_output.build_patches(particle_handler,
    //                                  solution_names,
    //                                  data_component_interpretation);
```

I will try to look deeper and find the root cause of this issue, but in case i am unable to, I prefer to open a pull request. @gassmoeller , I think you wrote this part so maybe you will have an idea?
I suspect the problem is related to DataOut and not to the properties themselves since they are accessed outside of the output function without any errors.

The code can be pulled directly from the step-68 pull request (https://github.com/dealii/dealii/pull/10308). You just need to comment line 654 and uncomment 656-657-658. On my machine, running with 4 mpi processes leads to the crash I mentioned. I also added the code in a tarball below.

[step-68.tar.gz](https://github.com/dealii/dealii/files/4718180/step-68.tar.gz)

```
--------------------------------------------------------
An error occurred in line <185> of file </home/blab/soft/dealii/dealii/dealii/source/particles/particle_accessor.cc> in function
    const dealii::ArrayView<double> dealii::Particles::ParticleAccessor<dim, spacedim>::get_properties() [with int dim = 2; int spacedim = 2]
The violated condition was: 
    particle != map->end()
Additional information: 
    This exception -- which is used in many places in the library -- usually indicates that some condition which the author of the code thought must be satisfied at a certain point in an algorithm, is not fulfilled. An example would be that the first part of an algorithm sorts elements of an array in ascending order, and a second part of the algorithm later encounters an element that is not larger than the previous one.

There is usually not very much you can do if you encounter such an exception since it indicates an error in deal.II, not in your own program. Try to come up with the smallest possible program that still demonstrates the error and contact the deal.II mailing lists with it to obtain help.

Stacktrace:
-----------
#0  /home/blab/soft/dealii/dealii/build/lib/libdeal_II.g.so.9.3.0-pre: dealii::Particles::ParticleAccessor<2, 2>::get_properties()
#1  /home/blab/soft/dealii/dealii/build/lib/libdeal_II.g.so.9.3.0-pre: dealii::Particles::DataOut<2, 2>::build_patches(dealii::Particles::ParticleHandler<2, 2> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<dealii::DataComponentInterpretation::DataComponentInterpretation, std::allocator<dealii::DataComponentInterpretation::DataComponentInterpretation> > const&)
#2  ./step-68: Step68::ParticleTracking<2>::output_particles(unsigned int)
#3  ./step-68: Step68::ParticleTracking<2>::run()
#4  ./step-68: main
--------------------------------------------------------
```

**Comment by bangerth** [comment]
I wonder whether that processor simply has not particles.

**Comment by blaisb** [comment]
> I wonder whether that processor simply has not particles.

That is absolutely possible. I will check it out.

**Comment by gassmoeller** [comment]
Repost of my message on slack:

Yes, I think I know whats happening. I did not test the particles property output if a process has no particles. In that case one of the asserts calls particles.begin()->get_properties().size(), but if there are no particles particles.begin() == particles.end() and we can not ask for the properties of a particle that does not exist. Can you check if the error goes away in release mode?

**Comment by blaisb** [comment]
Yes, it works just fine if you compile in release mode! Seems like your instinct is spot-on

**Comment by blaisb** [comment]
Yes! It works perfectly fine in release mode. Your instinct is spot-on. Do you want to make a pull request or I take care of it?

**Comment by gassmoeller** [comment]
See #10444.
