### ISSUE TITLE
Clarify expected behavior of GridTools::find_active_cell_around_point()

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#10459]
The documentation of ``GridTools::find_active_cell_around_point()`` says that the cell returned may be an artificial cell, but it is unclear whether this makes sense or whether this is possible, see PR #10456. 

This issue should clarify the expected behavior.

**Comment by nfehn** [comment]
There are other points that are not clear to me: There are several issues on the topic of fixing bugs for find_active_cell_around_point(), issues #10175, #7930, #7576. And other issues deal with the unclear aspect of how to deal with artificial cells for GridTools functions as well. Especially #7576 seems to be closely related to the recent issue #10459. The documentation of find_active_cells_around_point() is highly contradictory, here is a summary of some statements

>   If, however, the function throws an exception, then that would imply that the point lies outside locally owned active cells.

 >  If the point requested does not lie in any of the cells of the mesh given, then this function throws an exception

> the cell returned may in fact be a ghost or artificial cell

>  One of them will then return a locally owned cell and the other one a ghost cell.

**Comment by tamiko** [comment]
I have opened #10514 in the meantime to fix all failing tests (see also #10506). We will have to update these tests again in case we decide to adapt the behavior of `GridTools::find_active_cell_around_point` again.

**Comment by kronbichler** [comment]
Thanks @tamiko.
