### ISSUE TITLE
DEAL_II_COMPILER_HAS_DIAGNOSTIC_PRAGMA is set with clang 3.4

### ISSUE THREAD

**Issue by guidokanschat** [dealii/dealii#1046]
DEAL_II_COMPILER_HAS_DIAGNOSTIC_PRAGMA is set with clang 3.4 and causes tons of warnings.

Switching it off by hand in the build directory let's clang compile without complaints.

It seems like it should not be on with clang 3.4

**Comment by tjhei** [comment]
We have changed a couple of things. What is the status of this, Guido?

**Comment by bangerth** [comment]
@guidokanschat : Can you try again?

**Comment by guidokanschat** [comment]
I removed the -w option from the tests. But they are still running, so I do not want to restart

**Comment by tamiko** [comment]
This and two further configuration problems that resulted in a ton of warnings are now fixed.
