### ISSUE TITLE
ThreadLocalStorage needs a move operator=

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10462]
For #10284, it turns out that I need a move `operator=` for `AffineConstraints`, but that's not so easy because that class will have a `ThreadLocalStorage` which does not have a move version of `operator=`. (It doesn't have one because it has a `std::mutex` member, which makes the compiler-generated move `operator=` `=delete`d.)

@tamiko -- do you see a good reason not to add one?

**Comment by bangerth** [comment]
(I'm not sure whether `ThreadLocalStorage` had such an operator before #10285, but that's not an important thought anyway.)

**Comment by tamiko** [comment]
@bangerth I simply copied the interface from the old class and added move variants for the existing operations. We subsequently removed the copy constructor in #10184 .

Providing a move constructor and a move assignment operator is a good idea. I originally didn't do it because I didn't want to think about the correct locking policy and mutex handling in this case.

But I guess the semantics are pretty clear: simply move the `std::map` (either racy or while taking the reader lock from the to be moved thread local object) and default initialize the mutex.

**Comment by bangerth** [comment]
I'm confused. The `ThreadLocalStorage` class has a move `operator=` and move constructors alright. And `AffineConstraints` has its move constructor `=default`ed, yet this is the error I get:
```
2303: /raid/bangerth/p/deal.II/1/dealii/tests/bits/periodicity_06.cc:117:10: error: use of deleted function ‘dealii::AffineConstraints<number>::AffineConstraints(dealii::AffineConstraints<number>&&) [with number = double]’
2303:    return constraints;
2303:           ^~~~~~~~~~~
2303: In file included from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_accessor.templates.h:34,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_accessor.h:2085,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_handler.h:33,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/tests/bits/periodicity_06.cc:24:
2303: /raid/bangerth/p/deal.II/1/dealii/include/deal.II/lac/affine_constraints.h:581:3: note: ‘dealii::AffineConstraints<number>::AffineConstraints(dealii::AffineConstraints<number>&&) [with number = double]’ is implicitly deleted because the default definition would be ill-formed:
2303:    AffineConstraints(AffineConstraints &&affine_constraints) = default; // NOLINT
2303:    ^~~~~~~~~~~~~~~~~
2303: /raid/bangerth/p/deal.II/1/dealii/include/deal.II/lac/affine_constraints.h:581:3: error: use of deleted function ‘dealii::Threads::ThreadLocalStorage<T>::ThreadLocalStorage(const dealii::Threads::ThreadLocalStorage<T>&) [with T = dealii::internal::AffineConstraints::ScratchData<double>]’
```
Note how `AffineConstraints(AffineConstraints &&)` is calling `ThreadLocalStorage(const ThreadLocalStorage &)` despite the fact that there is `ThreadLocalStorage(ThreadLocalStorage&&)`.

Similarly:
```
2303: /raid/bangerth/p/deal.II/1/dealii/tests/bits/periodicity_06.cc:252:61: error: use of deleted function ‘dealii::AffineConstraints<number>& dealii::AffineConstraints<number>::operator=(dealii::AffineConstraints<number>&&) [with number = double]’
2303:        constraints[i] = make_constraint_matrix(dof_handler, i);
2303:                                                              ^
2303: In file included from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_accessor.templates.h:34,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_accessor.h:2085,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/include/deal.II/dofs/dof_handler.h:33,
2303:                  from /raid/bangerth/p/deal.II/1/dealii/tests/bits/periodicity_06.cc:24:
2303: /raid/bangerth/p/deal.II/1/dealii/include/deal.II/lac/affine_constraints.h:599:3: note: ‘dealii::AffineConstraints<number>& dealii::AffineConstraints<number>::operator=(dealii::AffineConstraints<number>&&) [with number = double]’ is implicitly deleted because the default definition would be ill-formed:
2303:    operator=(AffineConstraints &&affine_constraints) = default; // NOLINT
2303:    ^~~~~~~~
2303: /raid/bangerth/p/deal.II/1/dealii/include/deal.II/lac/affine_constraints.h:599:3: error: use of deleted function ‘dealii::Threads::ThreadLocalStorage<dealii::internal::AffineConstraints::ScratchData<double> >& dealii::Threads::ThreadLocalStorage<dealii::internal::AffineConstraints::ScratchData<double> >::operator=(const dealii::Threads::ThreadLocalStorage<dealii::internal::AffineConstraints::ScratchData<double> >&)’
```

So are the compiler-generated move-operations supposed to call copy-operations of member variables? Why don't they call move-operations of members?

**Comment by masterleinad** [comment]
It's easier to help if there is a pull request or a branch to share. :slightly_smiling_face:

**Comment by bangerth** [comment]
Good point -- see #10473. To reproduce the issue that gives me the error message above, do
```
  ninja deal_II.g
  ninja setup_tests
  ctest -V -R bits/periodicity_06.debug
```

**Comment by masterleinad** [comment]
> So are the compiler-generated move-operations supposed to call copy-operations of member variables? Why don't they call move-operations of members?

Because they don't exist. You also get:
```
note: ‘dealii::AffineConstraints<number>::AffineConstraints(dealii::AffineConstraints<number>&&) [with number = double]’ is implicitly deleted because the default definition would be ill-formed:
1171:    AffineConstraints(AffineConstraints &&affine_constraints) = default; // NOLINT
```
The copy assignment for `std::shared_timed_mutex` is explicitly deleted and hence user-defined. Thus, no implicit move assignment operator is defined. Similarly, for the copy constructor/move constructor.

Copy constructor, move constructor, copy assignment operator, and move assignment operator for `ThreadLocalStorage` must be defined explicitly because of the `mutex` member variable.

**Comment by masterleinad** [comment]
It's probably a good idea to use both the locks of the source and the target object when implementing these functions.

**Comment by bangerth** [comment]
Locks: I think it makes no difference -- when you move, the state of the old and new objects irrevocably change: Whoever is accessing the data stored in these objects at the time is going to be screwed anyway. In other words, any other thread's use of these objects creates a race condition with or without lock: it can only start using the new object once it has been moved to, and must stop using the old object at that point. But a mutex doesn't enforce these semantics.

**Comment by bangerth** [comment]
As for the error message: I think you didn't read that right. `AffineConstraints (AffineConstraints &&)` is deleted because it wants to use the deleted constructor `ThreadLocalStorage(const ThreadLocalStorage<T>&)`. But I would have expected that is uses `ThreadLocalStorage(ThreadLocalStorage<T>&&)` instead, which exists alright.

**Comment by bangerth** [comment]
Oh, I think now I get it: `ThreadLocalStorage(ThreadLocalStorage<T>&&)` is declared as `=default`, but that here implies `=delete` because one of the members can't be moved. It would have been nice if the compiler told me that...

So long story short, we do need the move constructors and operators after all, and need to implement them rather than `=default` them.

**Comment by masterleinad** [comment]
> Oh, I think now I get it: `ThreadLocalStorage(ThreadLocalStorage<T>&&)` is declared as `=default`, but that here implies `=delete` because one of the members can't be moved. It would have been nice if the compiler told me that...
> 
> So long story short, we do need the move constructors and operators after all, and need to implement them rather than `=default` them.

Yes. :slightly_smiling_face: 

> Locks: I think it makes no difference -- when you move, the state of the old and new objects irrevocably change:

Yes, but for the copy constructor, the old object can still be used. I wasn't sure if you also wanted to implement that or not in the end.

**Comment by bangerth** [comment]
I'm stuck again. I can't seem to figure this out. Above I convinced myself that I need `ThreadLocalStorage(ThreadLocalStorage<T>&&)` but that I don't have it because is declared as `=default`.

I don't know what I was looking at, though. That function is there and not `=default`: https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L127 And so is the move operator: https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L195

So that goes back to the question: Why is it trying to use `operator=(const ThreadLocalStorage &)` when synthesizing `AffineConstraints (AffineConstraints &&)`? I think I need help... (#10473 is updated to master.)

**Comment by tamiko** [comment]
@bangerth I took the liberaty to push a quick implementation of the missing copy and move constructor and assignment operators to your affine-2 branch. This seems to compile :-)
