### ISSUE TITLE
[Step-52 doc] Consider using a different mathematical variable for one time-step increment

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#10476]
In Step-52 for deal.ii v9.2 release, we currently use `h` for the local time-step difference. However, this is confusing for someone coming to step-52 solve a diffusion equation after reading Step-6 (which talks about adaptive mesh refinement), wherein `h` (and its variants with subscripts) is used for the local mesh size/cell diameter etc.

Can we instead use `$\Delta t$` instead for the time-step increment, to keep the notation consistent across the whole library?

**Comment by bangerth** [comment]
That's a reasonable suggestion. Want to write a patch?

**Comment by krishnakumarg1984** [comment]
Yes!

**Comment by bangerth** [comment]
The introduction also overloads h(t,y) to denote another function.
