### ISSUE TITLE
CXX11 and CXX14 detection don't work any more on Apple clang.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#1049]
Setting them on manually using cmake `-DDEAL_II_WITH_CXX11=TRUE -DDEAL_II_WITH_CXX14=TRUE ` works, but autodetection is now broken.

**Comment by davydden** [comment]
as far as i can tell, the auto-detection for CXX14 is still broken, whereas CXX11 works fine for me on the current HEAD with 'Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)'

**Comment by drwells** [comment]
That is surprising (and disturbing) to hear since things seem fine on my mac with `clang-600.0.56` (it detects `-std=c++1y` without problems). If you have time, could you please post (or send me) both your CMake version and the complete output from CMake?

**Comment by davydden** [comment]
nevermind, my bad. The wrong value was cached, when I did a clean cmake init, it all worked good and picked up CXX14 nicely!

**Comment by drwells** [comment]
That is a relief to hear.

**Comment by drwells** [comment]
It looks like this has been resolved. Is there anything else needed so that this issue may be closed?

**Comment by tjhei** [comment]
@luca-heltai ?
