### ISSUE TITLE
Detangle DEAL_II_WITH_ZLIB and boost::iostreams

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10500]
We currently try to find and link against an external zlib library which is controlled by `DEAL_II_WITH_ZLIB`. However, we mainly use `DEAL_II_WITH_ZLIB` as a heuristic whether boost has gzip compression/decompression capabilities. This is wrong because
 - we might accidentally pick up the wrong zlib library, see #10499,
 - finding zlib doesn't actually guarantee that boost has enabled zlib support (this is a configure option for boost that might be disabled).

Ideally we should
 - [ ] query the boost library directly for zlib support and enable the corresponding `boost::iostreams` code paths accordingly
 - [ ] If possible, port `write_compressed_block` to use some boost facilities instead of using zlib directly
 - [ ] remove `DEAL_II_WITH_ZLIB`

@luca-heltai *ping* Opinions?

**Comment by bangerth** [comment]
Just as a side remark: Whenever we use the bundled boost, we compile the `boost::iostreams` library ourselves and for that, we need to know whether we can link against `libz`.

**Comment by tamiko** [comment]
Ah. I forgot about that.
