### ISSUE TITLE
Boost signals overkill for particle_lost()?

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#10537]
Discussing with Prof. Michael Westdickenberg, he pointed out that boost::signals2 may be an overkill for particles (especially in the cases where we have many particles). 

The discussion he pointed me to was this one:

https://stackoverflow.com/questions/22416860/is-boostsignals2-overkill-for-simple-applications

What are your opinion on this? @gassmoeller @blaisb , @bangerth.

**Comment by bangerth** [comment]
The very first comment on the question is this: 

> so what did your profiler tell you about the amount of CPU/memory usage from Boost.Signals2? is it even a bottleneck? 

I think that in practice, the action one would perform in the function called in the signal is likely vastly more expensive than triggering the signal. The same is almost certainly true for the cost of moving particles around. So my take on these signals is: They're pretty convenient in practice and offer nice functionality; they're not a performance bottleneck unless someone can prove me wrong.

**Comment by gassmoeller** [comment]
I agree with Wolfgang. We benchmarked the whole algorithm for the initial particle paper and moving particles and potentially updating their properties was always the main cost (even after numerous optimizations). In particular I would expect the calls to any higher order mapping and evaluating finite element solutions at particle locations to be more expensive than any signal call could be, but as Wolfgang said, the only way to evaluate those assumptions is to measure things not in comparison to other options than signals, but in comparison to the other work that has to be done on the particles.

**Comment by luca-heltai** [comment]
I agree with your analysis. :) I'll close this.

**Comment by blaisb** [comment]
> I agree with your analysis. :) I'll close this.

I think it was an interesting discussion nonetheless :)!

**Comment by bangerth** [comment]
I got a small kick out of the fact that the stackexchange discussion linked to says "you've got to benchmark to know" in about a dozen different ways in various comments and answers :-)
