### ISSUE TITLE
Improve support of cell-data vectors in MatrixFree

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#10561]
Currently, the `MatrixFree` infrastructure supports to read cell-data vectors:
```cpp
VectorizedArrayType FEEvaluationBase::read_cell_data() const;
```

however, users are responsible to allocate memory for the vector (with the right size) and to fill the vectors (at the right position). Furthermore, no support for ghost-value update and compression is supported. 

For allocating the vector, following function could be introduced:
```cpp
void
initialize_cell_data_vector(VectorType & vec, const unsigned int dh_index = 0) const;
```
This vector could be amended with a partitioner or alternatively  `MatrixFree` could be amended with ghost-value update/compression functions.

For writing values,
```cpp
void FEEvaluationBase::set_cell_data(const VectorizedArrayType & data) const;
void FEEvaluationBase::distributed_cell_data(const VectorizedArrayType & data) const;
```

Any opinions?

This issue depends on PR #10490.

**Comment by kronbichler** [comment]
I like this direction. It seems like we simply want to use a `LA::distributed::Vector` for the cell data, which then automatically inherits the functionality to exchange ghost data, given that we provide a suitable partitioner. We could keep the original `AlignedVector<VectorizedArrayType>` if we want to because we can fill the infrastructure on top of it, but it feels like the basic vector is the way to move forward.

**Comment by peterrum** [comment]
> I like this direction. It seems like we simply want to use a LA::distributed::Vector for the cell data, which then automatically inherits the functionality to exchange ghost data, given that we provide a suitable partitioner. We could keep the original AlignedVector<VectorizedArrayType> if we want to because we can fill the infrastructure on top of it, but it feels like the basic vector is the way to move forward.

That sound good! But how do we intend to handle empty lanes with `LA::distributed::Vector`?

**Comment by kronbichler** [comment]
Fill them up with 1, consistent to what we do on the faces without valid data. While here, I think duplicating the entry from lane 0 is even better. Whether it's 1 or the result of lane 0, one always has to be careful when adding things up across lanes and skip "artificial" lanes.

So this would mean the implemented policy on empty lanes is to use "0" for the solution vectors handled via `read_dof_values`  whereas it is "v[lane0]" for the cell data. Looks like the best we could do.

**Comment by peterrum** [comment]
Maybe at the moment the more important question is how the new `active_cell_index()`/`global_active_cell_index()` fits into this discussion. Are we planing to sort the entries in the vector according to the active cell index? Since it is not guaranteed that this index matches to the matrix-free macro cell index, we will need to gather and scatter every time the vector is accessed. Is this something we would accept?

**Comment by kronbichler** [comment]
Intuitively, I would say that the matrix-free loop ordering is the one that should dictate the data ordering, so cell data is access contiguously (via SIMD load in the regular case) and face data with gather/scatter. I see the (global) active cell index more as a mechanism to be able to allows to identify those numbers. I would also let myself get convinced for a different solution, but right now I see little use in supporting a different numbering. In that case, we would need `FEEvaluation::read_cell_data` or `set_cell_data` to translate an index without any other benefit. Well, maybe compatibility with non-matrix-free code where data is filled by the global active cell index, but in that case it would be easier to translate them in the matrix-free code.
