### ISSUE TITLE
Parallel::Distributed::SolutionTransfer with hp::DoFHandler<dim> and FENothing<dim>

### ISSUE THREAD

**Issue by DominicSoldner** [dealii/dealii#10570]
I have created an example (extension of step-4 and already solved issue 8993) using both the hp::DoFHandler and the distributed Triangulation to illustrate the problem.

As soon as I use solution transfer in addition to local refinement, the following assertion is thrown:

An error occurred in line <1165> of file </calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/include/deal.II/lac/vector.h> in function
    Number& dealii::Vector<Number>::operator()(dealii::Vector<Number>::size_type) [with Number = double; dealii::Vector<Number>::size_type = unsigned int]
The violated condition was: 
    static_cast<typename ::dealii::internal::argument_type<void( typename std::common_type<decltype(i), decltype(size())>::type)>:: type>(i) < static_cast<typename ::dealii::internal::argument_type<void( typename std::common_type<decltype(i), decltype(size())>::type)>:: type>(size())
Additional information: 
    Index 0 is not in the half-open range [0,0). In the current case, this half-open range is in fact empty, suggesting that you are accessing an element of an empty collection such as a vector that has not been set to the correct size.

Stacktrace:
-----------
#0  step-4: dealii::Vector<double>::operator()(unsigned int)
#1  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: 
#2  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: dealii::parallel::distributed::SolutionTransfer<2, dealii::TrilinosWrappers::MPI::Vector, dealii::hp::DoFHandler<2, 2> >::pack_callback(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus)
#3  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: dealii::parallel::distributed::SolutionTransfer<2, dealii::TrilinosWrappers::MPI::Vector, dealii::hp::DoFHandler<2, 2> >::register_data_attach()::{lambda(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus)#1}::operator()(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus) const
#4  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: std::_Function_handler<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus), dealii::parallel::distributed::SolutionTransfer<2, dealii::TrilinosWrappers::MPI::Vector, dealii::hp::DoFHandler<2, 2> >::register_data_attach()::{lambda(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus)#1}>::_M_invoke(std::_Any_data const&, dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus&&)
#5  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus)>::operator()(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus) const
#6  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: std::_Function_handler<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus), std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::Triangulation<2, 2>::CellStatus)> >::_M_invoke(std::_Any_data const&, dealii::TriaIterator<dealii::CellAccessor<2, 2> >&&, dealii::Triangulation<2, 2>::CellStatus&&)
#7  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus)>::operator()(dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus) const
#8  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: dealii::parallel::distributed::Triangulation<2, 2>::DataTransfer::pack_data(std::vector<std::tuple<p4est_quadrant*, dealii::Triangulation<2, 2>::CellStatus, dealii::TriaIterator<dealii::CellAccessor<2, 2> > >, std::allocator<std::tuple<p4est_quadrant*, dealii::Triangulation<2, 2>::CellStatus, dealii::TriaIterator<dealii::CellAccessor<2, 2> > > > > const&, std::vector<std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus)>, std::allocator<std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus)> > > const&, std::vector<std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus)>, std::allocator<std::function<std::vector<char, std::allocator<char> > (dealii::TriaIterator<dealii::CellAccessor<2, 2> >, dealii::Triangulation<2, 2>::CellStatus)> > > const&)
#9  /calculate/dealii_9_2_0/spack/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/dealii-master-5v44cxta3v27y33fj4jm4v4qjbypxvvr/lib/libdeal_II.g.so.9.3.0-pre: dealii::parallel::distributed::Triangulation<2, 2>::execute_coarsening_and_refinement()
#10  step-4: Step4<2>::local_refinement()
#11  step-4: Step4<2>::run()
#12  step-4: main

Am I missing something? I attached a small example that I ran against deal 9.2.0 and the current master branch. If you comment out the SolutionTransfer everyting seems to work fine. I guess some difficulty using FENothing in parallel? 

Thank you very much
Dominic

[dealii920test.zip](https://github.com/dealii/dealii/files/4813193/dealii920test.zip)

**Comment by peterrum** [comment]
Apparently, `SolutionTransfer` is not checking if `dofs_per_cell == 0`. Could you try out the following modification:

```diff
diff --git a/source/distributed/solution_transfer.cc b/source/distributed/solution_transfer.cc
index 52ca51e..e603c33 100644
--- a/source/distributed/solution_transfer.cc
+++ b/source/distributed/solution_transfer.cc
@@ -364,6 +364,9 @@ namespace parallel
 
       const unsigned int dofs_per_cell =
         dof_handler->get_fe(fe_index).dofs_per_cell;
+      
+      if(dofs_per_cell == 0)
+          return std::vector<char>();
 
       auto it_input  = input_vectors.cbegin();
       auto it_output = dof_values.begin();
@@ -436,12 +439,15 @@ namespace parallel
 
       const unsigned int dofs_per_cell =
         dof_handler->get_fe(fe_index).dofs_per_cell;
+      
+      if(dofs_per_cell == 0)
+          return;
 
       const std::vector<::dealii::Vector<typename VectorType::value_type>>
         dof_values =
           unpack_dof_values<typename VectorType::value_type>(data_range,
                                                              dofs_per_cell);
-
+          
       // check if sizes match
       Assert(dof_values.size() == all_out.size(), ExcInternalError());
```

For me, it crashes now in the solver because I have configured deal.II without `Amesos_Mumps`.

**Comment by DominicSoldner** [comment]
@peterrum Thank you very much. That did solve the problem.

**Comment by peterrum** [comment]
Happy that I could help! I'll create a PR and add a smaller test.

Did you reopen the issue intentionally?

**Comment by DominicSoldner** [comment]
Yes just wasn't sure if I could close it or leave it open until it is merged :).
