### ISSUE TITLE
UML diagram about the internal data structures of Triangulation

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#10582]
Since PR #10329, we have done some big changes within the `Triangulation` class (and there some coming). I think we should document the current state with a picture.

For me, the following (bit outdated) picture helped a lot to understand the relationships:

![](https://user-images.githubusercontent.com/15707929/82732172-d4495c00-9d0b-11ea-9633-5f40f76fc716.png)

In principle, it is nothing more then the UML diagram generated by Doxygen, however, with the possibility emphasize  certain aspects. 

What do others think?

**Comment by bangerth** [comment]
I think this is useful. I didn't know doxygen can get generate UML diagrams, though I probably shouldn't be surprised. The question I guess is where this should go?

(You might want to fix the typo in `TriaFaces`: `reseve_space` -> `reserve_space`.)
