### ISSUE TITLE
Fix property pool in ParticleHandler::insert_(global_)particles()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10590]
#10584 and the fix in #10589 show that we forgot to set the particle property pool pointer when bulk inserting multiple particles at once in `ParticleHandler::insert_particles()`. On closer inspection, the functions immediately following the one that was fixed have the same problem.

@luca-heltai @gassmoeller -- FYI.

**Comment by bangerth** [comment]
#10845 takes care of another function.

@gassmoeller -- did we cover all relevant `insert*()` functions now?

**Comment by gassmoeller** [comment]
Yes as far as I can tell all insert functions now set the property pool (the `insert_global...` functions call the `insert_particle...` functions so they do it indirectly). This can be closed.
