### ISSUE TITLE
New non-templated version of DoFTools::make_periodicity_constraints lead to Trilinos Matrix error code 2

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#10638]
Dear all,
I hope you are well.
In a recent commit (I could not find the pull request), the DoFTools::make_periodicity_constraints has been changed from a templated function to a non-templated one. I believe this comes in the move to unify the DoFHandler classes.

However, since that change, our code has been not working when we have periodic BCs, we get an error of type:

```
Exception on processing: 

--------------------------------------------------------
An error occurred in line <1682> of file </home/blaisb/work/dealii/dealii/dealii/source/lac/trilinos_sparse_matrix.cc> in function
    void dealii::TrilinosWrappers::SparseMatrix::add(dealii::TrilinosWrappers::SparseMatrix::size_type, dealii::TrilinosWrappers::SparseMatrix::size_type, const size_type*, const TrilinosScalar*, bool, bool)
The violated condition was: 
    ierr == 0
Additional information: 
    An error with error number 2 occurred while calling a Trilinos function
--------------------------------------------------------
```

This only occurs in our test bench for cases that contain a periodic boundary condition. However, these tests pass perfectly fine on 9.2.0, but also used to pass up to very recently (like 10 days or so ago).

Does anybody have an idea of what could be happening? If not I will try to bissect the thing, but this will most probably take some time.

**Comment by peterrum** [comment]
@blaisb, could you send me a link to the failing test. Thanks!

**Comment by blaisb** [comment]
> @blaisb, could you send me a link to the failing test. Thanks!

Sure thing. Regretfully they are within lethe.
So if you use Lethe master branch:
https://github.com/lethe-cfd/lethe
and you compile and use ctest, all the tests should pass. The test that include periodic bcs are 
1 - gls_navier_stokes_2d/poiseuille_gls.release (Failed)
13 - gls_navier_stokes_2d/taylor-green-vortex_gls_bdf1.mpirun=2.release (Failed)
14 - gls_navier_stokes_2d/taylor-green-vortex_gls_sdirk2.mpirun=2.release (Failed)
15 - gls_navier_stokes_2d/taylor-green-vortex_gls_sdirk3.mpirun=2.release (Failed)
22 - gls_navier_stokes_3d/poiseuille3d_gls.release (Failed)
26 - gd_navier_stokes_2d/poiseuille_gd.mpirun=2.release (Failed)
27 - gd_navier_stokes_2d/taylor-green-vortex_gd_bdf1.release (Failed)
28 - gd_navier_stokes_2d/taylor-green-vortex_gd_bdf2.release (Failed)
32 - gd_navier_stokes_3d/poiseuille3d_gd.release (Failed)

I have made a branch on the lethe repo that is called **periodicity_fix.** This branch compiles with the latest commit on the master version of deal.II. On this branch, everything compiles well, but all test fail due to the aforementioned error.
Feel free to reach out to me on slack or anywhere if you need anything and if I can help you !

Regretfully, I do not have a smaller simpler executable where this occur. But 2d cases are very small (like few hundred cells).
