### ISSUE TITLE
bits/max_n_cells_01/02 are failing

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1064]
For the past several weeks, bits/max_n_cells_01/02 have been failing on all platforms. I suspect that this may have something to do with @QiaoLei-88 's patch in #979 but didn't pay attention at the time whether the tests really started failing back then.

@QiaoLei-88 is going to take a look.

**Comment by bangerth** [comment]
Excellent, #1066 fixed it indeed. Thanks very much, @QiaoLei-88 !

**Comment by QiaoLei-88** [comment]
You are welcome. I just fixed what I have broken :-]

But how do know it is fixed. The dashboard is still not updated.

**Comment by bangerth** [comment]
I ran it on one of our workstations. The test works again correctly. The dashboard should also be updated in an hour or two (I.e., tomorrow morning).

**Comment by QiaoLei-88** [comment]
WoW, you are so impatient :-)
Actually I have run the test before I submit the PR.

**Comment by bangerth** [comment]
> WoW, you are so impatient :-)

Don't you know yet?


> Actually I have run the test before I submit the PR.

As you should have! :-)
