### ISSUE TITLE
Deal.II thinks that clang 7.0 is not C++17 compatible

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#10652]
I use clang 7.0 and deal.II thinks that it is not C++17 compatible.
Deal.II compiles fine with clang 7.0, but I get

```
-- C++14 support is enabled.    
-- C++17 support is disabled.   
-- C++20 support is disabled.
```

When I try to use `if constexpr` in my own code I get many warnings such as:

```
 warning: constexpr if is a C++17 extension [-Wc++17-extensions]
```

Do you plan to enable/disable the whole C++17 or C++20 as indivisible packages? `if constexpr` is available since clang 3.9, and clang 7 has some C++20 features. Wouldn't it be better to enable/disable individual features?

@tamiko, I think that this is related to #10307

**Comment by masterleinad** [comment]
You can try to set `CMAKE_CXX_FLAGS=-std=c++17`.

**Comment by dangars** [comment]
> You can try to set `CMAKE_CXX_FLAGS=-std=c++17`.

Thanks @masterleinad That works!

I close the issue.

**Comment by dangars** [comment]
After some digging I found out the origin of the problem. It has nothing to do with clang-7.

In the code of #10307 @tamiko used the header "optional.h" to check the C++17 features. Clang-7 is C++17 compatible, but clang uses the default gcc toolchain which in my machine is very old (Debian stretch)

The problem is in my machine not not in Deal.II :)
