### ISSUE TITLE
Error using deal.II 9.2.0 on Mac OS Catalina (10.15.5)

### ISSUE THREAD

**Issue by XieJChris** [dealii/dealii#10656]
It seems that the newest version of deal.II is easy to hit a limit in Catalina's dynamic linker. 
Exceptions like dyld: malformed mach-o: load commands size (38712) > 32768, so far, is there any useful solutions to this annoying problem?

**Comment by drwells** [comment]
@XieJChris We recently fixed this problem (see #10330). Can you duplicate this problem when you download the revised mac bundle?

**Comment by XieJChris** [comment]
Sorry for replying late, however, the solution mentioned in #10330 does not work for my Mac. I end up using deal.II 9.1 version though it is not convenient to install on Mac. Anyway, thanks for replying.
BTW, I tried to install deal.ii 9.2 on my another Ubuntu 20.04 machine, I still got a annoying problem, which is about scalapack, the default download links wrote in pest-lite-3.13.1/config/BuildSystem/config/packages/scalapack.py were un accessible or the pulling speeding is too late, I modified this file and tried a new link: https://github.com/Reference-ScaLAPACK/scalapack/archive/v2.1.0, it worked fine. After downloading the package successfully, something wrong, I got a error message: Error runing making on SCALAPACK. 
But I am not familiar with Python, so any ideas?

**Comment by fmilicchio** [comment]
I can confirm the issue with `dyld: malformed mach-o: load commands size (33848) > 32768`.

**Comment by drwells** [comment]
I'm not sure how to debug this since the mac bundle works for @luca-heltai and myself. @luca-heltai any ideas?

**Comment by luca-heltai** [comment]
Can you remove the deal.II app, remove the dmg image, and download this one:

https://github.com/dealii/dealii/releases/download/v9.2.0/dealii-9.2.0.dmg

The error above was present in the previous package (with the same name) but should not be present here.

**Comment by fmilicchio** [comment]
Of course. It "works" now, there is only a misconfiguration of `metis` (library not found):

```
bash-3.2$ ls
CMakeLists.txt	step-17.cc

bash-3.2$ mkdir tmp

bash-3.2$ cd tmp/

bash-3.2$ cmake ..
-- The C compiler identification is AppleClang 11.0.3.11030032
[...]
-- Build files have been written to: /Users/sensei/Desktop/step-17/tmp

bash-3.2$ make
Scanning dependencies of target step-17
[ 50%] Building CXX object CMakeFiles/step-17.dir/step-17.cc.o
[100%] Linking CXX executable step-17
ld: warning: directory not found for option '-L/Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/zlib-1.2.11-rqiqrujgg5aemhk7eqjk3asbaukff'
[100%] Built target step-17

bash-3.2$ ls
CMakeCache.txt		CMakeFiles		Makefile		cmake_install.cmake	step-17

bash-3.2$ ./step-17 
dyld: Library not loaded: libmetis.dylib
  Referenced from: /Users/sensei/Desktop/step-17/tmp/./step-17
  Reason: image not found
Abort trap: 6
```

And forcing the export works with both serial and MPI:

```
bash-3.2$ otool -L step-17 |grep metis
	/Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/parmetis-4.0.3-gnjha6gpp2bnbpydshvgzzoo4owm6cno/lib/libparmetis.dylib (compatibility version 0.0.0, current version 0.0.0)
	libmetis.dylib (compatibility version 0.0.0, current version 0.0.0)

bash-3.2$ ls /Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/metis-5.1.0-rfst34i3ua6lpci7tk2tztxm6tjcusxr/
.spack/  bin/     include/ lib/     

bash-3.2$ export DYLD_LIBRARY_PATH=/Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/metis-5.1.0-rfst34i3ua6lpci7tk2tztxm6tjcusxr/lib/

bash-3.2$ ./step-17 
Cycle 0:
   Number of active cells:       64
   Number of degrees of freedom: 162 (by partition: 162)
   Solver converged in 9 iterations.
Cycle 1:
   Number of active cells:       121
   Number of degrees of freedom: 298 (by partition: 298)
   Solver converged in 17 iterations.
Cycle 2:
   Number of active cells:       229
   Number of degrees of freedom: 550 (by partition: 550)
   Solver converged in 26 iterations.
Cycle 3:
   Number of active cells:       433
   Number of degrees of freedom: 1004 (by partition: 1004)
   Solver converged in 36 iterations.
Cycle 4:
   Number of active cells:       820
   Number of degrees of freedom: 1826 (by partition: 1826)
   Solver converged in 51 iterations.
Cycle 5:
   Number of active cells:       1558
   Number of degrees of freedom: 3348 (by partition: 3348)
   Solver converged in 67 iterations.
Cycle 6:
   Number of active cells:       2953
   Number of degrees of freedom: 6318 (by partition: 6318)
   Solver converged in 93 iterations.
Cycle 7:
   Number of active cells:       5596
   Number of degrees of freedom: 11706 (by partition: 11706)
   Solver converged in 122 iterations.
Cycle 8:
   Number of active cells:       10612
   Number of degrees of freedom: 22130 (by partition: 22130)
^C

bash-3.2$ mpirun --host localhost:4 -np 4 ./step-17 
Cycle 0:
   Number of active cells:       64
   Number of degrees of freedom: 162 (by partition: 52+42+38+30)
   Solver converged in 21 iterations.
Cycle 1:
   Number of active cells:       124
   Number of degrees of freedom: 302 (by partition: 100+68+82+52)
   Solver converged in 29 iterations.
Cycle 2:
   Number of active cells:       238
   Number of degrees of freedom: 570 (by partition: 176+134+160+100)
^C^Cbash-3.2$ 
```

**Comment by luca-heltai** [comment]
again, there is no misconfiguration. You must choose how to run your codes (either with modules, or with DYLD_LIBRARY_PATH exported). If you do `module load dealii` this should fix all misconfigurations this was the comment above, showing how to workaround the limitations).

**Comment by fmilicchio** [comment]
> again, there is no misconfiguration. You must choose how to run your codes (either with modules, or with DYLD_LIBRARY_PATH exported). If you do `module load dealii` this should fix all misconfigurations this was the comment above, showing how to workaround the limitations).

Uh ok, sorry for the misunderstanding: I never use the environment, I hand-fix everything in my IDE.

I confirm the DMG works flawlessly.

**Comment by drwells** [comment]
@XieJChris Does this fix work for you?

**Comment by XieJChris** [comment]
@drwells yep, it works now, thanks a lot :)

**Comment by tjhei** [comment]
@luca-heltai I have an ASPECT user who just downloaded the new .dmg and also has a problem with ``lib-1.2.11-rqiqrujgg5aemhk7eqjk3asbaukff``. What is going on here, there seem to be part of the path missing?

**Comment by luca-heltai** [comment]
Is it a warning or an error?

If it’s a warming, it has been answered already in the mailing list. It is enough to make a simlink between zlib and the searched path (Which lacks three or four letters). 

Btw, this does not happen to everyone. I think it is the same issue as the malformed binary, related to the fact that zlib is the last library loaded, and on some systems, there is not enough room for its full path, and it gets truncated. 

Luca

**Comment by tjhei** [comment]
> Is it a warning or an error?

I think it is a warning only, as far as I can tell. But who knows what the consequences of this are.

> Btw, this does not happen to everyone. I think it is the same issue as the malformed binary, related to the fact that zlib is the last library loaded, and on some systems, there is not enough room for its full path, and it gets truncated.

It would be worth fixing that, as it is quite confusing to me. Can you force spack to generate shorter directory names for example?

**Comment by anne-glerum** [comment]
I realise this issue is closed, but could my linker error be related to the directory name lengths? If not, please let me know whether I should open another issue.
With the current dealii image on Catalina, after `module load dealii`, I try to install ASPECT and get the following linker error:
`[114/114] Linking CXX executable aspect`
`FAILED: aspect `
`: && /Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/openmpi-3.1.6-ch3xlssbdriiio4hygk3xhnxclncjvze/bin/mpic++` + ...a very long list...
`clang: error: unable to execute command: posix_spawn failed: Argument list too long`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`ninja: build stopped: subcommand failed.`
