### ISSUE TITLE
Re-instate ZeroFunction

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10677]
We had a previous patch a couple of weeks ago that removed a deprecated `using` directive that imported `dealii::Functions::ZeroFunction` into `namespace dealii`. This is going to cause us headaches because we had used `dealii::ZeroFunction` all over the tutorials. I also didn't get any deprecation warnings in one of my projects :-(

As a consequence, I'm foreseeing that we will get a good number of complaints about having removed a class for which people never saw a deprecation warning. How should we deal with this? Re-instate this class for one more release and make sure that we actually do warn on use?

**Comment by blaisb** [comment]
The same thing happened on our side and it came off as a surprise because there were no previous warning. I think your idea of re-instating for one release and warning on use would be a very good one.

**Comment by peterrum** [comment]
I have re-instatiated the functions `ConstantFunction` and `ZeroFunction` on this branch (as it was before #10565):

https://github.com/peterrum/dealii/tree/function_dep

However, I do get warnings for the following test program:

```cpp
#include <deal.II/base/function.h>

using namespace dealii;

int
main()
{
    ConstantFunction<3> a(1);
    ZeroFunction<3> b(1);
}
```

@bangerth and @blaisb could you try this branch out and verify that you actually don't get any warnings.

**Comment by tjhei** [comment]
We also did get a compile error once it was removed (and no warning beforehand, but I think this was because we had a ``using namespace Functions`` in place. See https://github.com/geodynamics/aspect/pull/3550

**Comment by masterleinad** [comment]
I am still a bit puzzled about what's going here. https://godbolt.org/z/qKqa5e shows that you get deprecation warnings when you don't import the class into the current namespace, that the warnings vanish when you import the class, and that nothing breaks when you remove the deprecated `using`-declaration.

**Comment by peterrum** [comment]
How do want to proceed here?

**Comment by masterleinad** [comment]
Let's just re-instantiate using an alias. I'll do that.
