### ISSUE TITLE
ParticleHandler does not work properly with parallel::shared::Triangulation

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#10731]
ParticleHandler checks if a Triangulation is parallel::distributed to decide whether to use MPI communication or not. 

This fails miserably with parallel::shared::Triangulation objects, since the dynamic cast in this case fails, and the Triangulation is treated as serial.

@gassmoeller @fmilicchio

**Comment by peterrum** [comment]
Can you cast it to `parallel::TriangulationBase`?

**Comment by drwells** [comment]
This seems like a good chance to clean up the way we do parallel detection. Why not add `Triangulation::get_communicator()` (which always returns `MPI_COMM_SELF` and make the communication check both for particles and elsewhere "does this object use MPI_COMM_SELF"?

**Comment by peterrum** [comment]
> Why not add Triangulation::get_communicator()

You have my support here. My workaround in many places is like this:
https://github.com/dealii/dealii/blob/3a9d086947af2f028476e3288fcc8d0e9c6a7965/include/deal.II/multigrid/mg_transfer_interface_util.templates.h#L52-L63

**Comment by drwells** [comment]
We should definitely have a solution that doesn't require `dynamic_cast`. I'll put up a PR a little later today.

**Comment by drwells** [comment]
Now that we have a proper fix can someone go back and fix these for particles?

**Comment by blaisb** [comment]
> Now that we have a proper fix can someone go back and fix these for particles?

@drwells Actually particle_handler now work with shared triangulation. There is even a test for it:
https://github.com/dealii/dealii/blob/master/tests/particles/particle_handler_shared_01.cc

I wrote it a few months ago...

**Comment by drwells** [comment]
Oh, even better. Since this is fixed we can close the issue.
