### ISSUE TITLE
In all tutorial programs, consider using standard return codes upon encountering exceptions

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#10735]
In all tutorial programs with exception handling, `return 1` is used to inform the operating system that the program did not terminate successfully.  However, this is non-standard (and not portable) according to the best practices described [here](https://www.learncpp.com/cpp-tutorial/function-return-values/) which says

>A non-zero status code is often used to indicate failure (and while this works fine on most operating systems, strictly speaking, it’s not guaranteed to be portable).

And the recommendation is the following:

>The C++ standard only defines the meaning of 3 status codes: 0, EXIT_SUCCESS, and EXIT_FAILURE. 0 and EXIT_SUCCESS both mean the program executed successfully. EXIT_FAILURE means the program did not execute successfully.

Should deal.ii consider this, atleast for the tutorial programs (since we aim to promote best practices), if not throughout the library?

**Comment by masterleinad** [comment]
> Should deal.ii consider this, atleast for the tutorial programs (since we aim to promote best practices), if not throughout the library?

Sure, if you want to give it a shot, go for it. This really only applies to `main()` since we otherwise rely on exceptions for error handling.

**Comment by drwells** [comment]
I would prefer that we not fix this - we don't support any platforms where this is a meaningful distinction and this keeps the library consistent in checking that `0` is the successful return code (e.g., from LAPACK, PETSc, etc).
