### ISSUE TITLE
Find a better way to determine what needs to be communicated with Triangulation classes

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#10733]
Spin-off from #10731: I think we should first discuss this before implementing a solution.

There are two categories of problems that keep popping up from time to time related to communication in `Triangulation`s:
1. Its not clear if we need to communicate data if we only have a `dealii::Triangulation &`
2. Its not clear what kind of communication needs to happen at all since the parallel Triangulation classes lie on a spectrum from `shared` to `fullydistributed`

Our usual technique for figuring out which type of `Triangulation` we have is to use `dynamic_cast`. In particular, we usually assume a Triangulation needs to communicate (category 1) if it inherits from `parallel::TriangulationBase` (exceptions include `minimal_cell_diameter`, which arguably does the wrong thing for `parallel::shared::Triangulation` as a result).

`dynamic_cast` is problematic because we now have three parallel Triangulation classes and there are still some problems with things being supported for `p:d:t` and not `p:f:t`, or some things working for both and `dynamic_cast` being overly restrictive (category 2). @peterrum mentioned to me that ideally these problems would only occur in the DoFHandler policy classes: to me, that indicates that we should improve the API elsewhere to get rid of some casts.

We could fix some problems in the first category by adding `Triangulation::get_communicator()`, which would always return `MPI_COMM_SELF`: calling code could then check if communication is necessary by testing `tria.get_communicator() != MPI_COMM_SELF`. One problem with this solution is that it doesn't make sense to add MPI functions to a purely serial class. It also doesn't address the second category at all.

I don't know the answer, but I think its worth discussing some possible fixes because of the number of PRs opened recently related to these two categories of problems.

**Comment by luca-heltai** [comment]
>We could fix some problems in the first category by adding Triangulation::get_communicator(), which would always return MPI_COMM_SELF: calling code could then check if communication is necessary by testing tria.get_communicator() != MPI_COMM_SELF. One problem with this solution is that it doesn't make sense to add MPI functions to a purely serial class. It also doesn't address the second category at all.

I think this solution is the correct one. Triangulation::get_mpi_communicator() should be a virtual function, returning MPI_COMM_SELF. All the utilities in Utilities::MPI::xxx that take a communicator should do the right thing when the communicator is an MPI_COMM_SELF, and we should try to use only those utilities in our code base. 

This, for example, would eliminate all if clauses in particle handler.
