### ISSUE TITLE
v9.2.0 is incompatible with CUDA-11

### ISSUE THREAD

**Issue by my2coins** [dealii/dealii#10749]
[ 46%] Building CUDA object source/lac/CMakeFiles/obj_lac_release.dir/vector_memory.cu.o
cd /BUILD/dealii-9.2.0/build/source/lac && /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/lib64/mpich/bin/mpicxx -DBOOST_NO_AUTO_PTR -I/BUILD/dealii-9.2.0/build/source/lac -I/BUILD/dealii-9.2.0/build/include -I/BUILD/dealii-9.2.0/include -I/BUILD/dealii-9.2.0/bundled/tbb-2018_U2/include -I/dealii-9.2.0/bundled/umfpack/UMFPACK/Include -I/BUILD/dealii-9.2.0/bundled/umfpack/AMD/Include -I/BUILD/dealii-9.2.0/bundled/muparser_v2_2_4/include -isystem=/usr/local/cuda/include -Xcompiler "-fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-class-memaccess -fopenmp-simd -std=c++14 -O2 -g -pipe -Wall -Werror=format-security   -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wformat -march=icelake-server -Wno-parentheses -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs -DNDEBUG" -arch=sm_70 -std=c++14 -std=c++14 -x cu -c /BUILD/dealii-9.2.0/source/lac/vector_memory.cu -o CMakeFiles/obj_lac_release.dir/vector_memory.cu.o

/BUILD/dealii-9.2.0/include/deal.II/base/table_indices.h(118): warning: type qualifier is meaningless on cast type

/BUILD/dealii-9.2.0/include/deal.II/base/array_view.h(323): error: class "cudaPointerAttributes" has no member "memoryType"

/BUILD/dealii-9.2.0/include/deal.II/base/array_view.h(325): error: class "cudaPointerAttributes" has no member "memoryType"

 
2 errors detected in the compilation of "/BUILD/dealii-9.2.0/source/lac/vector_memory.cu".
make[2]: *** [source/lac/CMakeFiles/obj_lac_release.dir/build.make:553: source/lac/CMakeFiles/obj_lac_release.dir/vector_memory.cu.o] Error 2

**Comment by Rombur** [comment]
CUDA 11 was released after deal.II 9.2. This should be fixed in master.

**Comment by drwells** [comment]
@Rombur do you think that this is worth patching?

**Comment by drwells** [comment]
(i.e., 9.2.1)

**Comment by masterleinad** [comment]
We are using `cusparse` functions that have been removed in CUDA 11 so there is more work to do anyway.

**Comment by Rombur** [comment]
NVidia tends to be pretty aggressive in deprecating/removing capabilities so we would have to see that we don't lose support of some CUDA version between 9.2.0 and 9.2.1. We don't have enough testing machines for CUDA, so it's not realistic to support different code paths for different CUDA version.
