### ISSUE TITLE
doxygen is confused by simplex namespace

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#10765]
subdivided_hyper_rectangle now also contains the documentation for Simplex::GridGenerator::subdivided_hyper_rectangle at the bottom:
https://www.dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#ac76417d7404b75cf53c732f456e6e971
(grep for "tetrahedral")
I am not sure why that happens. Maybe we can change use a different namespace for simplex stuff?

Also, shouldn't simplex/grid_generator.h also be guarded by the simplex define?

**Comment by peterrum** [comment]
This is odd. Doxygen is merging the documentation. 

> Maybe we can change use a different namespace for simplex stuff?

I find other names really unintuitive? Does anyone know any other solutions?

**Comment by tjhei** [comment]
I think using the same namespace name nested in a different namespace is not a good idea. It is problematic for doxygen. It is also confusing for lookup rules and ``using`` by the way. Either just put it in the same namespace GridGenerator or call it differently. If you envision Tets and quads to be treated the same way at some point in the future, it would be weird to have the namespaces set up like you have them now or not?
