### ISSUE TITLE
simplex support comments

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#10797]
After @peterrum 's presentation yesterday, I have a few comments worth discussing. I would propose that we have an API round-table via video chat at some point soon. My notes so that I don't forget:

- [x] I would think ``cell->cell_type() `` might be neater than ``cell->reference_cell_type()`` (#11688)
- [x] Should we deprecate static info in GeometryInfo? Con: a lot of changes for users. Pro: consistency, bug finding. 
- [x] Should we consider deprecating the default mapping arguments? This needs a longer conversation, but I think I am in favor.
- [x] Change default mapping to something that is Q1 or P1 depending on the cells used and call is something like ``MappingLinear`` (I know that it is not strictly correct)?
- [x] Detect functions inside the library that rely on quads and either fix or add an ``Assert(tria->is_quads_only())``. This would involve (temporarily) removing GeometryInfo, MappingQ, etc..

**Comment by bangerth** [comment]
Here's another thing I'd like to see: In classes like `QGauss` and `QTrapez`, the `Q` doesn't actually indicate a quad/hex style quadrature, but that it's a *q*uadrature.

So I don't think we should introduce `PGauss` and `PTrapez`. Rather, I'd suggest giving the constructor an argument of type `ReferenceCellType` (or whatever that should be) and by that either let it construct a tensor product rule or use whatever is the appropriate choice for that reference cell kind.

**Comment by bangerth** [comment]
I can't seem to find any evidence of the `PTrapez` name mentioned above and assume that I just never looked it up.

**Comment by drwells** [comment]
I think we have addressed all of these problems in various ways - we have `ReferenceCell`, many functions assert that the mesh is all hypercube elements, #10310, etc.
