### ISSUE TITLE
Can't compile p::d::T class when p4est not detected

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10807]
We have a sham class for `p::d::T` that is selected when p4est was not detected: It doesn't do anything useful, but allows codes to compile. But that doesn't work right now because there are unimplemented virtual functions:
```
/home/shyaan/dealii/include/deal.II/distributed/tria.h:1402:11: note:   because the following virtual functions are pure within ‘dealii::parallel::distributed::Triangulation<3, 3>’:
     class Triangulation
           ^~~~~~~~~~~~~
In file included from /home/shyaan/dealii/include/deal.II/dofs/dof_handler.h:29:0,
                 from /home/shyaan/dealii/include/deal.II/numerics/vector_tools_boundary.h:22,
                 from /home/shyaan/dealii/include/deal.II/numerics/vector_tools.h:22,
                 from /home/shyaan/thm/./include/boundaryvalues.h:8,
                 from /home/shyaan/thm/src/main.cc:1:
/home/shyaan/dealii/include/deal.II/distributed/tria_base.h:105:5: note:        bool dealii::parallel::TriangulationBase<dim, spacedim>::is_multilevel_hierarchy_constructed() const [with int dim = 3; int spacedim = 3]
     is_multilevel_hierarchy_constructed() const = 0;
```

**Comment by peterrum** [comment]
I cannot come up with an instance where actually it would be a problem that `is_multilevel_hierarchy_constructed` is not implemented. Anyway there will be a compiler error because the constructor is deleted...

**Comment by peterrum** [comment]
Any instance you can come up, @bangerth?

**Comment by masterleinad** [comment]
@bangerth You deleted the constructor in https://github.com/dealii/dealii/commit/5fda355fca748752f935b461e27a57a71b4ffe6d.
@peterrum Just try to compile step-40 with deal.II configuration that has p4est support disabled.

**Comment by peterrum** [comment]
> Just try to compile step-40 with deal.II configuration that has p4est support disabled.

@masterleinad Yes, that "worked". Thanks!

At the moment there are four non-implemented functions: `is_multilevel_hierarchy_constructed()`, `save()`, `load()`, and `update_cell_relations()`. We could add dummy implementations. But do we want to do with the constructor? Without one that takes a communicator the code will nevertheless not compile...
