### ISSUE TITLE
Homepage certificate expired

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#10812]
The certificate for https://www.dealii.org/ has expired again.

**Comment by simonsticko** [comment]
Maybe @guidokanschat knows how to fix this?

**Comment by tjhei** [comment]
I am in contact with him and we are working on it. The 9.2 documentation is available here: https://dealii.43-1.org/documentation/9.2.0/doxygen/deal.II/index.html

**Comment by tjhei** [comment]
we are back online! :-)
