### ISSUE TITLE
Compilation failure on Intel

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10826]
See https://cdash.43-1.org/viewBuildError.php?buildid=9731
This is related to #10816.

**Comment by peterrum** [comment]
> /.../dealii/include/deal.II/matrix_free/evaluation_kernels.h(2783): internal error: assertion failed: find_assoc_pragma: pragma not found (shared/cfe/edgcpfe/il.c, line 24734)

This does not make sense. It is pointing to a line which does not have a pragma. The closes pragma is for the line above...

**Comment by peterrum** [comment]
I'll take a look at this later today. SuperMUC-NG should be back online so that I can use ICC there.

**Comment by kronbichler** [comment]
Closed by #10944.
