### ISSUE TITLE
error: step-67 and gcc 7.2 and omp simd

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#10823]
I got the following report from one of the ASPECT users trying to install 9.2 (but I think this is the same on master):
```
/deal.II-v9.2.0/examples/step-67/step-67.cc:1519:9: sorry, unimplemented: unexpected sorry, unimplemented: unexpected AST of kind omp_simd
```
This is with gcc 7.2.0:
```
#        CMAKE_CXX_COMPILER:     GNU 7.2.0 on platform Linux x86_64
#                                /cluster/openmpi/gcc-7.2.0/openmpi-4.0.1/bin/mpicxx
#        CMAKE_C_COMPILER:       /cluster/openmpi/gcc-7.2.0/openmpi-4.0.1/bin/mpicc
#        CMAKE_Fortran_COMPILER: /cluster/openmpi/gcc-7.2.0/openmpi-4.0.1/bin/mpif90
#        CMAKE_GENERATOR:        Unix Makefiles
#
#  Base configuration (prior to feature configuration):
#        DEAL_II_CXX_FLAGS:            -pedantic -fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++17 -Wl,-rpath=/cluster/gcc/gcc-7.2.0/lib64/
#        DEAL_II_CXX_FLAGS_RELEASE:    -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs
#        DEAL_II_CXX_FLAGS_DEBUG:      -O0 -ggdb -Wa,--compress-debug-sections
#        DEAL_II_LINKER_FLAGS:         -Wl,--as-needed -rdynamic -fuse-ld=gold -L/usr/lib64/ -llapack -Wl,-rpath=/usr/lib64/
```

It looks like gcc 7.2 doesn't support openmp pragmas inside lambda functions? Also see https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg564488.html

@tamiko ?

**Comment by kronbichler** [comment]
The strange thing is that this does work for me on gcc-7.3, but I wouldn't expect a feature (rather than bug fix) in a dot release. Not sure how to proceed - should we just disable the pragma in that code or fix up the pragma?

**Comment by tjhei** [comment]
> should we just disable the pragma in that code or fix up the pragma?

Not sure. We could also change the lambda to a normal function.

I think it is an important enough thing to fix, as this stops people from installing deal.II on their machines unless they turn off compilation of the examples.

**Comment by bangerth** [comment]
A lambda function *is* a normal function. Its the `operator()` member function of a regular structure. That it doesn't work is a compiler bug, and the compiler error message also makes that clear.

We've worked around many compiler bugs in the past. In many cases, we've had `#ifdef DEAL_II_XXX_BUG` around the code, based on a cmake check, but that's of course more awkward in a tutorial program...

**Comment by tjhei** [comment]
Any other suggestions? I don't feel like adding a compiler bug check here (but I had at least two people unfamiliar with deal.II run into this issue while compiling the library).

**Comment by tamiko** [comment]
*mhm* I It looks like a prime candidate for a compiler bug check, though.

**Comment by tjhei** [comment]
What do we do about this? gcc 7.2 is quite popular and this bug means that we can not compile the library as examples are enabled by default without errors. This bug also happens with 9.2.0 by the way.

**Comment by kronbichler** [comment]
We could disable the OpenMP SIMD pragma on this loop. It is a tutorial program so one could move the part to the possibilities for extensions section.

> This bug also happens with 9.2.0 by the way.

Can you elaborate here on the type of error message? I am surprised by this because I believe I have used gcc 9.2 quite a lot during development, even though most of my machines have now switched to gcc-9.3 and 10.2. At least the error message `unexpected AST of kind omp_simd` seems unlikely, as gcc-7.3 (a dot release) does not have this any more.

**Comment by bangerth** [comment]
My vote would be to just remove the `DEAL_II_OPENMP_SIMD_PRAGMA` and to mention in the documentation somewhere around that place that one could add it  for performance but that we don't because not all compilers are happy with it. (In fact, we already comment on the pragma a page or two up.)

It's a tutorial program/teaching tool -- we don't need to get all performance out of it.

**Comment by tjhei** [comment]
> Can you elaborate here on the type of error message?

```
/home/bob/test_v9.2.0_candi/tmp/unpack/deal.II-v9.2.0/examples/step-67/step-67.cc: In lambda function:
/home/bob/test_v9.2.0_candi/tmp/unpack/deal.II-v9.2.0/examples/step-67/step-67.cc:1516:9: sorry, unimplemented: unexpected AST of kind omp_simd
});
```
(this is with gcc 7.1)
