### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by Tread84** [dealii/dealii#10832]
I am trying to install Dealii on my cluster, and I keep getting the following error during the install. Not sure if there is a linkage problem or if I am missing a library that Dealii needs.... Any thoughts, help, or solutions to this are greatly appreciated!

[ 76%] Built target obj_simplex_release
In file included from /home/tad/dealii/source/lac/sparsity_tools.cc:39:0:
/usr/local/include/metis.h:175:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartGraphRecursive(idx_t *nvtxs, idx_t *ncon, idx_t *xadj,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:180:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartGraphKway(idx_t *nvtxs, idx_t *ncon, idx_t *xadj,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:185:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_MeshToDual(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:188:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_MeshToNodal(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:191:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartMeshNodal(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:195:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartMeshDual(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:200:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeND(idx_t *nvtxs, idx_t *xadj, idx_t *adjncy, idx_t *vwgt,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:203:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_Free(void *ptr);
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:205:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_SetDefaultOptions(idx_t *options);
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:210:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeNDP(idx_t nvtxs, idx_t *xadj, idx_t *adjncy, idx_t *vwgt,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:214:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_ComputeVertexSeparator(idx_t *nvtxs, idx_t *xadj, idx_t *adjncy,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:217:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeRefine(idx_t nvtxs, idx_t *xadj, idx_t *vwgt, idx_t *adjncy,
 ^~~~~~~~~~~~
 ETIMEDOUT
/home/tad/dealii/source/lac/sparsity_tools.cc: In function ‘void dealii::SparsityTools::{anonymous}::partition_metis(const dealii::SparsityPattern&, const std::vector<unsigned int>&, unsigned int, std::vector<unsigned int>&)’:
/home/tad/dealii/source/lac/sparsity_tools.cc:93:7: error: ‘METIS_SetDefaultOptions’ was not declared in this scope
       METIS_SetDefaultOptions(options);
       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/tad/dealii/source/lac/sparsity_tools.cc:39:0:
/usr/local/include/metis.h:175:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartGraphRecursive(idx_t *nvtxs, idx_t *ncon, idx_t *xadj,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:180:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartGraphKway(idx_t *nvtxs, idx_t *ncon, idx_t *xadj,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:185:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_MeshToDual(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:188:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_MeshToNodal(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/home/tad/dealii/source/lac/sparsity_tools.cc:138:16: error: ‘METIS_PartGraphRecursive’ was not declared in this scope
         ierr = METIS_PartGraphRecursive(&n,
                ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/metis.h:191:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartMeshNodal(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:195:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_PartMeshDual(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:200:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeND(idx_t *nvtxs, idx_t *xadj, idx_t *adjncy, idx_t *vwgt,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:203:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_Free(void *ptr);
 ^~~~~~~~~~~~
 ETIMEDOUT
/home/tad/dealii/source/lac/sparsity_tools.cc:154:16: error: ‘METIS_PartGraphKway’ was not declared in this scope
         ierr = METIS_PartGraphKway(&n,
                ^~~~~~~~~~~~~~~~~~~
/usr/local/include/metis.h:205:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_SetDefaultOptions(idx_t *options);
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:210:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeNDP(idx_t nvtxs, idx_t *xadj, idx_t *adjncy, idx_t *vwgt,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:214:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_ComputeVertexSeparator(idx_t *nvtxs, idx_t *xadj, idx_t *adjncy,
 ^~~~~~~~~~~~
 ETIMEDOUT
/usr/local/include/metis.h:217:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
 METIS_EXPORT int METIS_NodeRefine(idx_t nvtxs, idx_t *xadj, idx_t *vwgt, idx_t *adjncy,
 ^~~~~~~~~~~~
 ETIMEDOUT
/home/tad/dealii/source/lac/sparsity_tools.cc: In function ‘void dealii::SparsityTools::{anonymous}::partition_metis(const dealii::SparsityPattern&, const std::vector<unsigned int>&, unsigned int, std::vector<unsigned int>&)’:
/home/tad/dealii/source/lac/sparsity_tools.cc:93:7: error: ‘METIS_SetDefaultOptions’ was not declared in this scope
       METIS_SetDefaultOptions(options);
       ^~~~~~~~~~~~~~~~~~~~~~~
/home/tad/dealii/source/lac/sparsity_tools.cc:138:16: error: ‘METIS_PartGraphRecursive’ was not declared in this scope
         ierr = METIS_PartGraphRecursive(&n,
                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/tad/dealii/source/lac/sparsity_tools.cc:154:16: error: ‘METIS_PartGraphKway’ was not declared in this scope
         ierr = METIS_PartGraphKway(&n,
                ^~~~~~~~~~~~~~~~~~~
source/lac/CMakeFiles/obj_lac_release.dir/build.make:446: recipe for target 'source/lac/CMakeFiles/obj_lac_release.dir/sparsity_tools.cc.o' failed
make[2]: *** [source/lac/CMakeFiles/obj_lac_release.dir/sparsity_tools.cc.o] Error 1
CMakeFiles/Makefile2:2267: recipe for target 'source/lac/CMakeFiles/obj_lac_release.dir/all' failed
make[1]: *** [source/lac/CMakeFiles/obj_lac_release.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
source/lac/CMakeFiles/obj_lac_debug.dir/build.make:446: recipe for target 'source/lac/CMakeFiles/obj_lac_debug.dir/sparsity_tools.cc.o' failed
make[2]: *** [source/lac/CMakeFiles/obj_lac_debug.dir/sparsity_tools.cc.o] Error 1
CMakeFiles/Makefile2:2213: recipe for target 'source/lac/CMakeFiles/obj_lac_debug.dir/all' failed
make[1]: *** [source/lac/CMakeFiles/obj_lac_debug.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by drwells** [comment]
I will try to answer your question here, but I recommend also posting it to the mailing list - there are a lot more users there than here who can help with this sort of installation issue.

This looks like a problem with METIS, not with deal.II. In particular:
```
In file included from /home/tad/dealii/source/lac/sparsity_tools.cc:39:0:
/usr/local/include/metis.h:175:1: error: ‘METIS_EXPORT’ does not name a type; did you mean ‘ETIMEDOUT’?
METIS_EXPORT int METIS_PartGraphRecursive(idx_t *nvtxs, idx_t *ncon, idx_t *xadj,
^~~~~~~~~~~~
```
I'm not a METIS expert but it looks like there is something wrong with your METIS installation - `METIS_EXPORT` should be a preprocessor macro defined by a configuration file but it clearly is not. How did you install metis?

**Comment by Tread84** [comment]
I installed METIS via http://glaros.dtc.umn.edu/gkhome/metis/metis/download and followed the build and make instructions. I will look at mailing the user group now. Thank you
