### ISSUE TITLE
Wrong rank for converted type when contracting a SymmetricTensor with a Tensor of different ranks.

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#10848]
On [this line](https://github.com/dealii/dealii/blob/master/include/deal.II/base/symmetric_tensor.h#L4035)
```
  operator*(const SymmetricTensor<rank_1, dim, Number> &src1,
            const Tensor<rank_2, dim, OtherNumber> &    src2)
{
  return Tensor<rank_2, dim, OtherNumber>(src1) * src2;
}
```
the tensor `src1` is converted to a tensor of the wrong rank. It should read `Tensor<rank_1, dim, Number>(src1)`. This bug can be triggered by premultiplying (using `operator*`) a `Tensor<3,dim>` with a `SymmetricTensor<2,dim>`.

**Comment by rezarastak** [comment]
Can we write it as `Tensor<rank_1, dim, Number>(src1)`? I mean, can we keep the number type of src1 as `Number`?

**Comment by jppelteret** [comment]
Good catch. Thanks for pointing that out. I'll update my comment.

I've got a patch lined up for this, so I'll open a PR with the fix and a test later today.
