### ISSUE TITLE
Template argument n_components in FEFaceEvaluationImpl

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10862]
PR #10820 removed the `n_components` template arguments from the evaluation implementation of cell integrals. We should do something similar for the face evaluators https://github.com/dealii/dealii/blob/13dd68ff4b4ed16ccfd7a3b335279bde2b774a95/include/deal.II/matrix_free/evaluation_kernels.h#L1324-L1331 and the implicit dependence of `CellwiseInverseMassMatrixImpl` on the argument via the call to https://github.com/dealii/dealii/blob/13dd68ff4b4ed16ccfd7a3b335279bde2b774a95/include/deal.II/matrix_free/evaluation_kernels.h#L3126-L3132 where the `FEEvaluationBase` has an `n_components` template argument. For the latter, we probably need to restructure `FEEvaluationBase` somewhat into the part that does not depend on the number of components like the functions querying the geometry as used by the inverse mass matrix here
https://github.com/dealii/dealii/blob/13dd68ff4b4ed16ccfd7a3b335279bde2b774a95/include/deal.II/matrix_free/evaluation_kernels.h#L3163-L3168 and the other parts like reading from vectors or returning the `get_value` part that do indeed depend on the components.

Works towards #9794.

**Comment by drwells** [comment]
A lot of other code is templated on the number of components (like MassOperator). Should those also ultimately lose their template argument?

**Comment by kronbichler** [comment]
You need the template arguments on the user-visible side of the evaluators because the components determine the type of tensor you get (e.g., the value is a `Number` for `n_components=1` but `Tensor<1,n_components,Number>` if it is larger than 1). So right now I aim to look at the implementation side that needs the template on the degree - that part should just have a loop over the components. With that in place, we should in the end be able to get rid of the `fe_degree` and `n_q_points_1d` template parameters (at >98% of the speed of the current templated version) and only have `dim, n_components, Number` as the remaining arguments.
