### ISSUE TITLE
Build failure using deal.II in macOS 11.0 Big Sur, unable to find libdl.dylib

### ISSUE THREAD

**Issue by zhiyuanzhai** [dealii/dealii#10917]
After `make run` command:
```
[ 33%] Building CXX object CMakeFiles/main1.dir/main1.cc.o
make[3]: *** No rule to make target `/usr/lib/libdl.dylib', needed by `main1'.  Stop.
make[2]: *** [CMakeFiles/main1.dir/all] Error 2
make[1]: *** [CMakeFiles/run.dir/rule] Error 2
make: *** [run] Error 2
```

There's a ton of change in this new version of macOS Big Sur. I think this might be one of them.

**Comment by roman-frolov** [comment]
I also have this problem after updating to Big Sur. Any way to fix this? Thank you!

**Comment by zhiyuanzhai** [comment]
@roman-frolov Update with the latest dmg file, i.e., the 9.2.0-v3 file. That one is rebuilt for Big Sur.
