### ISSUE TITLE
Interfaces to `FEEvaluationImpl` & co

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10928]
Given the endless argument lists in the current code of the implementation of `FEEvaluationImpl` and `FEFaceEvaluationImpl`, we should really get some better structure there. I suggest to use a common interface with 3 arguments for all functions implementing tensor products, taking `EvaluationFlags, InternalData, vector_ptr`, where `InternalData` collects most of the arguments we pass around. Since most of the variables are members of `FEEvaluation`, this will also help with #10921.

**Comment by peterrum** [comment]
@kronbichler I am happy to help here. I would suggest that you come up with a suggestion of `InternalData` and from there I can take over to pass it to all relevant functions.

**Comment by peterrum** [comment]
Since this is internal, we can simply adjust the interface later one. Posponing.

**Comment by peterrum** [comment]
@kronbichler What is missing here? I think you made a lot of progress here last year by introducing `FEEvaluationData`.

**Comment by kronbichler** [comment]
Fixed by #13056.
