### ISSUE TITLE
[step-59] Extend section on possibilities for extensions

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10939]
In the step-59 tutorial program, the section on possibilities for extensions, https://github.com/dealii/dealii/blob/1885cee63454f3daf5e437fdeee5fe1dcfb113c3/examples/step-59/doc/results.dox#L334-L344
is very short. We could help users interested in these methods more by saying how we would use a Chebyshev smoother in the DGQ basis (like step-37) and with DGHermite (using a transformation). These things are said in a preprint on "Hermite-like basis functions" by me and some co-workers; we should extract some parts to this tutorial.

**Comment by peterrum** [comment]
Postponing.

**Comment by kronbichler** [comment]
I think this can be done for the release. Let us keep it on schedule.
