### ISSUE TITLE
step-19: Revise discussion about time stepping + update movie

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10945]
As discussed in https://github.com/dealii/dealii/pull/10942#discussion_r492507782 , the tutorial program is a bit inconsistent in the convention for the time step. In particular, I believe that the result section should not call the method "forward Euler" because the formula is indeed using the end-of-step electrical potential/field, but it might be that something else was intended anyway. Given #10942, at least the formulas in the introduction and in-code comments should be consistent with what is implemented.

**Comment by kronbichler** [comment]
Furthermore, I get a different motion of particles with #10942, so I believe the movie needs to be updated as well.

**Comment by peterrum** [comment]
This does not seem urgent.

**Comment by bangerth** [comment]
I'd like to get this done, given that step-19 is new in this release.

**Comment by peterrum** [comment]
> I'd like to get this done, given that step-19 is new in this release.

@bangerth It would be nice if the documentation would be updated. The movie is not that important.

**Comment by kronbichler** [comment]
I guess this is a very minor topic and does not distract from the main innovation of the tutorial, so I simply adjust the milestone for now. If we have a last-minute fix, I will be fine with it as well.

**Comment by kronbichler** [comment]
@bangerth do you see a chance to get this done for the release? I do not think this is super urgent, so we might also remove the target milestone and/or close the issue.
