### ISSUE TITLE
Document pre-compiled polynomial degrees with FEEvaluation

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#10947]
#10927 introduces pre-compiled polynomial degrees to the matrix-free evaluators in `FEEvaluation` and `FEFaceEvaluation`. However, from a user perspective it is not clear which degrees get the fast code path and which do not. We should introduce a function that prints the chosen degrees to a stream for information purposes. The function could pass a function to print to the instantiation mechanisms of the class that then gets available to the user.

Furthermore, the documentation in the FEEvaluation class should be looked over once some follow-up PRs after #10927 are merged, such as the ones fixing #10928 or #10946.

**Comment by peterrum** [comment]
I will add a short paragraph in the matrix-free module page.

**Comment by peterrum** [comment]
Is there anything more here we should do till the release. Else we could move the milestone!

**Comment by kronbichler** [comment]
This has now been fixed by the code https://github.com/dealii/dealii/blob/ddcce6ffcb19f65bac07d01626d3e84e89099613/include/deal.II/matrix_free/fe_evaluation.h#L2153-L2158

Compared to #6039, we now also do not bail out in case we do not support a particular degree pre-compiled, but switch to a slower algorithm. Hence, I'm closing this PR.
