### ISSUE TITLE
mac test failures

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1095]
We have a bunch of tests failing on the new mac tester. I would like to discuss how to fix them:

1. fixed with #1094 hopefully:
base/functions_12
flag base/number_traits_complex

2. because GridTools::distort_random works differently:
bits/refine_and_coarsen_for_active_cell_index_05
bits/rt_2
deal.II/distort_random
deal.II/nedelec_non_rect_2d
deal.II/nedelec_non_rect_face
fe/rt_normal_02
This is weird, because boost::random::mt19937 should not be machine dependent. Ideas?

2. I will look into it (probably long double conversion):
base/quadrature_chebyshev

3. Failing on other testers:
fe/mapping_fe_field_real_to_unit_b2_mask

4. harmless? 
http://cdash.kyomu.43-1.org/testDetails.php?test=16233035&build=9743
matrix_free/estimate_condition_number_mass

5. metis (harmless):
metis/metis_01
metis/metis_01a
metis/metis_02
metis/metis_03

6. serialization:
http://cdash.kyomu.43-1.org/testDetails.php?test=16233291&build=9743
serialization/table_handler
serialization/triangulation_01
serialization/triangulation_02
This is a problem. Anyone got an idea what might be the problem here?

**Comment by bangerth** [comment]
>  2.
>
>     because GridTools::distort_random works differently:
>     bits/refine_and_coarsen_for_active_cell_index_05
>     bits/rt_2
>     deal.II/distort_random
>     deal.II/nedelec_non_rect_2d
>     deal.II/nedelec_non_rect_face
>     fe/rt_normal_02
>     This is weird, because boost::random::mt19937 should not be machine
>     dependent. Ideas?

We only use mt19937 for parallel::distributed::Triangulation. Maybe its time 
to change this.


>  7.
>
>     serialization:
>     http://cdash.kyomu.43-1.org/testDetails.php?test=16233291&build=9743
>     serialization/table_handler
>     serialization/triangulation_01
>     serialization/triangulation_02
>     This is a problem. Anyone got an idea what might be the problem here?

The error message says that
```
remove_cv.hpp:50:66: fatal error: recursive template instantiation exceeded 
maximum depth of 128
```
I'm willing to believe that we need to increase the limit. The standard 
suggests that compilers allow up to 1024 template instantiations, not just 
128. Are you able to try with `-ftemplate-depth-1024`?

**Comment by tjhei** [comment]
> We only use mt19937 for parallel::distributed::Triangulation. Maybe its time to change this.

okay, see #1097.

> 'm willing to believe that we need to increase the limit. The standard suggests that compilers allow up to 1024 template instantiations, not just 128. Are you able to try with `-ftemplate-depth-1024`?

I don't have access to the machine. @guidokanschat can you please take a look?

**Comment by guidokanschat** [comment]
Will try with the next run: -ftemplate-depth=1024.

As for the distort random: I suggest to replace it by a reasonably odd mesh.

**Comment by tjhei** [comment]
Guido,

the distort_random is already fixed to be deterministic now.

It seems the mac tester didn't run the last 2-3 days. Can you check please?

**Comment by tjhei** [comment]
Okay, it looks like we are down to the template-depth related errors. Yay! :+1:

**Comment by tjhei** [comment]
@guidokanschat You can remove the -ftemplate-depth switch because #1133 does this automatically now.

Closing this issue because tests are working well now.
