### ISSUE TITLE
MemorySpaceData questions

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10986]
@peterrum -- FYI.

I'm coming late to the party but am looking at #10873 and the follow-up #10879, and I don't think that was the right decision. These patches make the `copy_to()` function virtual (and the subsequently also the destructors). The reason is #10872, which derives a new class `LinearAlgebra::SharedMPI::MemorySpaceData` from the specialization `MemorySpace::MemorySpaceData<Number, MemorySpace::Host>` and overloads the now `virtual` functions.

But this really isn't how we thought about the `MemorySpaceData` classes. I think the better approach would be to revert #10873 and #10879 and instead create another specialization of `MemorySpace::MemorySpaceData<Number, MemorySpace::SharedMPI>` that handles the transfer into shared memory. This avoids the overhead of the virtual functions and, more importantly, it matches the current design in which different memory spaces are handled by way of template specializations instead of inheritance. The current approach in #10872 muddles this kind of design: Now 3 different memory spaces are handled by template specialization, and one by inheritance. That seems suboptimal to me.

@peterrum -- what are your thoughts?

**Comment by peterrum** [comment]
I see your point. But introducing `MemorySpace::SharedMPI` has the disadvantage that functions in https://github.com/dealii/dealii/blob/master/include/deal.II/lac/vector_operations_internal.h would have to specialized although they would be identical to the specialization for `MemorySpace::Host`.

I my opinion it would be an option to merge `SharedMPI::MemorySpaceData<Number>` and `MemorySpaceData<Number, Host>` to a single struct. However, do not think this an elegant solution.
