### ISSUE TITLE
Import TaskFlow 2.7.0

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10989]
TaskFlow 2.7.0 is out, and it contains the new `async` call we will want to use in `Threads::new_task`. We should import this new version.

**Comment by peterrum** [comment]
Adjusting milestone, since we plan to drop taskflow for now.

**Comment by peterrum** [comment]
@bangerth  Can we close this PR? We decided on dropping TaskFlow, didn't we?

**Comment by bangerth** [comment]
Yes, if we decided to drop taskflow, then we can close.
