### ISSUE TITLE
3 Minor Typos in Documentation

### ISSUE THREAD

**Issue by Arpit-Babbar** [dealii/dealii#11019]
### **1) Explanation of Destructor of Step-7 missing**
[https://www.dealii.org/9.2.0/doxygen/deal.II/step_7.html#HelmholtzProblemHelmholtzProblemdestructor](https://www.dealii.org/9.2.0/doxygen/deal.II/step_7.html#HelmholtzProblemHelmholtzProblemdestructor)

Here's what the documentation says -

_This is no different than before:_
```c++
template <int dim>
HelmholtzProblem<dim>::~HelmholtzProblem()
{
  dof_handler.clear();
}
```

**Why I believe there's info missing**

In Version 9.0.0, [there used to be a detailed explanation of the destructor, in step-6](https://www.dealii.org/9.0.0/doxygen/deal.II/step_6.html#Step6Step6). In 9.2.0, destructor is not mentioned anywhere in Steps 1-6. 

### **2) Mentioned to have left empty angle brackets for default argument, but not done so (Step-3)**

[https://www.dealii.org/9.2.0/doxygen/deal.II/step_3.html#Step3solve](https://www.dealii.org/9.2.0/doxygen/deal.II/step_3.html#Step3solve)
 
Here's what the documentation says -

_Then we need the solver itself. The template parameter to the SolverCG class is the type of the vectors, but the empty angle brackets indicate that we simply take the default argument (which is Vector<double>):_
```c++
SolverCG<Vector<double>> solver(solver_control);
```
**Suggested edit -** 
```c++
SolverCG<> solver(solver_control);
```

### 3) Indicating that object would be declared as const, when it wasn't(Step-7)

[https://www.dealii.org/9.2.0/doxygen/deal.II/step_7.html#HelmholtzProblemassemble_system](https://www.dealii.org/9.2.0/doxygen/deal.II/step_7.html#HelmholtzProblemassemble_system)

Here's what the documentation says -

_Note that the operations we will do with the right hand side object are only querying data, never changing the object. We can therefore declare it `const`:_

```c++
RightHandSide<dim>  right_hand_side;
std::vector<double> rhs_values(n_q_points);
```

**Suggested edit**
```c++
const RightHandSide<dim>  right_hand_side;
std::vector<double> rhs_values(n_q_points);
```

**Comment by masterleinad** [comment]
1) We don't need the destructor anymore. It can be deleted.
2) This was last changed in https://github.com/dealii/dealii/pull/9926. Apparently, we forgot update the documentation.
3) Sure.

Do you want to create a pull request to address all of this?

**Comment by Arpit-Babbar** [comment]
Hi, I could understand what to do for the third change, but not the rest. I have made a pull request [here](https://github.com/dealii/dealii/pull/11025) because I wanted to try it. Please tell me what I need to change. In summary, this is what I did

1. I actually deleted the destructor.
2. I edited the documentation to mention that we are could leave the brackets empty, but are explicitly specifying the template arguments anyway.
3. Just added `const`.


 By the way, the tutorial link here [https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#i-found-a-typo-or-a-bug-and-fixed-it-on-my-machine-how-do-i-get-it-included-in-dealii](https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#i-found-a-typo-or-a-bug-and-fixed-it-on-my-machine-how-do-i-get-it-included-in-dealii) that says [read this online tutorial](https://www.atlassian.com/git/tutorial) doesn't seem to be working for me.

**Comment by peterrum** [comment]
> By the way, the tutorial link here https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#i-found-a-typo-or-a-bug-and-fixed-it-on-my-machine-how-do-i-get-it-included-in-dealii that says read this online tutorial doesn't seem to be working for me.

Thanks for reporting the outdated link. We will fix!
