### ISSUE TITLE
Cannot build with CUDA enabled and C++17

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#11013]
Hey all,

I can't compile the library with CUDA enabled and C++17. Somehow it looks like we inject `-std=c++14` in the cuda flags and `nvcc` does not like to have both c++14 and c++17. Unfortunately, I can't find where the `-std=c++14` flag is added. You can see in the [detailed.log](https://github.com/dealii/dealii/files/5335799/detailed.log) that the CUDA flags are correct:
```
#            DEAL_II_CUDA_FLAGS = -arch=sm_70 -std=c++17
#            DEAL_II_CUDA_FLAGS_RELEASE = 
#            DEAL_II_CUDA_FLAGS_DEBUG = -G
```
but the CUDA flags that are used are different (from [source/lac/CMakeFiles/obj_lac_debug.dir/flags.make](https://github.com/dealii/dealii/files/5335828/source-lac-CMakeFiles-obj_lac_debug.dir-flags.make.txt))
```
-arch=sm_70 -std=c++17 -G -std=c++14
```

I obviously tried to grep for `-std=c++14` but I couldn't find it. Looking at [this](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_1_cuda.cmake#L151) I would expect `-G` to be the last flag. Any idea how to debug this?

**Comment by masterleinad** [comment]
Hmmm... I can't quite reproduce. Configuring with `CMAKE_CXX_STANDARD=17` and `DEAL_II_CUDA_FLAGS= -arch=sm_70 -std=c++17` gives me
```
CUDA_FLAGS =   -Xcompiler "-fPIC -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -pthread -Wno-parentheses -Wno-unused-local-typedefs -O0 -ggdb " -arch=sm_70 -std=c++17 -G
```
The only place I could think of that adds a `-std=c++14` flag is https://github.com/dealii/dealii/blob/b95669156f1ce4add03b95ab3a6bd5c22a2058d9/cmake/checks/check_01_cxx_features.cmake#L307-L312.

**Comment by Rombur** [comment]
Thanks that's true it works with `CMAKE_CXX_STANDARD=17`. I was setting the flag through `CMAKE_CXX_FLAGS`. The reason I didn't use `CMAKE_CXX_STANDARD=17` is because the `std=c++17` flag is not passed to our C++17 compatibility check. If you set `CMAKE_CXX_STANDARD=17` alone, our C++17 check will fail and you will see that deal.II disables C++17. You can see in your `CUDA_FLAGS` that the `std=c++17` flag is not sent to the host compiler. I guess we need to set the flag explicitly for the host and the device compiler and set the CXX standard.

**Comment by masterleinad** [comment]
Fair enough. Still, if I set `DEAL_II_CXX_FLAGS=-std=c++17` and `DEAL_II_CUDA_FLAGS=-arch=sm_70 -std=c++17` (and don't specify `CMAKE_CXX_STANDARD`), I get
```
CUDA_FLAGS =   -Xcompiler "-fPIC -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++17 -pthread -Wno-parentheses -Wno-unused-local-typedefs -O0 -ggdb " -arch=sm_70 -std=c++17 -G
```

**Comment by Rombur** [comment]
That's so strange. I tried two different versions of CMake (3.17 and 3.18) but I always get the same problem.

**Comment by tamiko** [comment]
@Rombur Is this still an issue?

**Comment by Rombur** [comment]
I haven't tried in  a while but since we are moving to Kokkos anyway this is irrelevant. I'm closing
