### ISSUE TITLE
Build process ignores CUDA_HOST_COMPILER setting

### ISSUE THREAD

**Issue by frobnitzem** [dealii/dealii#11026]
When building with MPI and Cuda 11, the build system inserts "-ccbin=/usr/bin/g++-7" into nvcc calls like so:

```
cd /tmp/spack-stage/spack-stage-dealii-9.2.0-qpwj4tqyq57gms5ihstpvbtyclvbdr2f/spack-build-qpwj4tq/source/lac && /home/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/cuda-11.1.0-rqxazeubhvbpj42ozgiol5ephl3zny27/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/g++-7 -DBOOST_NO_AUTO_PTR ...
```

This results in the build crashing because the cu file can't include <mpi.h>.

Deal.ii's spack package uses the following logic to setup the mpi compilers:
if '+mpi' in spec:
            options.extend([
                '-DDEAL_II_WITH_MPI:BOOL=ON',
                '-DCMAKE_C_COMPILER=%s' % spec['mpi'].mpicc,
                '-DCMAKE_CXX_COMPILER=%s' % spec['mpi'].mpicxx,
                '-DCMAKE_Fortran_COMPILER=%s' % spec['mpi'].mpifc,
            ])

I tried extending this with '-DCUDA_HOST_COMPILER=%s' % spec['mpi'].mpicxx, but the attempt was unsuccessful (resulting in the same generated nvcc invocation above).  I also tried "spack_env.set('CUDA_HOST_COMPILER', spec['mpi'].mpicxx)" - same issue.  For completeness, I tried '-DCUDA_NVCC_FLAGS="-ccbin %s"' % spec['mpi'].mpicxx, same issue.  Only CUDA source files have trouble building.

I think this is a bad interaction between `FindCUDA.cmake` and `configure_1_cuda.cmake`, or maybe the `CMAKE_CXX_COMPILER` gets changed due autodetection or something cuda-config does but I can't tell.  Is there another way to set the CUDA_HOST_COMPILER properly?

**Comment by frobnitzem** [comment]
I now think this may be a problem with they way spack sets up its environment.  By default spack had set CUDAHOSTCXX to MPI's underlying c++ compiler, which the FindCUDA module picks up.  When I export CUDAHOSTCXX=mpic++, then the build succeeded.

The spack team is discussing it here: https://github.com/spack/spack/pull/19254

**Comment by masterleinad** [comment]
I would normally just not set `CMAKE_CXX_COMPILER` to an MPI wrapper.
