### ISSUE TITLE
Environment variable CUDAHOSTCXX causes issues.

### ISSUE THREAD

**Issue by frobnitzem** [dealii/dealii#11032]
I had originally filed bug report (#11026), but the issue I have is less severe.

When CUDAHOSTCXX=/usr/bin/g+-6, then something in deal.II or cmake-3.17 causes the flag "-ccbin=/usr/bin/g++-6" to get passed to nvcc.  This happens regardless of the CUDA_HOST_COMPILER or CMAKE_CUDA_HOST_COMPILER cmake options, which I have verified were set to `/usr/bin/mpic++` by my cmake options.

The spack team is discussing how to handle setting CUDAHOSTCXX here: spack/spack#19254

However, deal.II's compile process should be fixed so that CUDA_HOST_COMPILER has precedence.

**Comment by masterleinad** [comment]
Could you provide the `CUDA` and `CMake` version you are using?

**Comment by frobnitzem** [comment]
I tried several versions, but the one I ran last was cuda 11.1.0 with cmake 3.17.0-rc1. 
These are using gcc 6.5.0, system provided from Ubuntu 18.04.1.
This has to be centered around odd cmake behavior, since it's responsible for adding the -ccbin flag.  Maybe it's just my cmake version.
