### ISSUE TITLE
Trilions-help

### ISSUE THREAD

**Issue by xueno6** [dealii/dealii#11072]
"sudo cmake -DTRILIONS_DIR=/usr/local/Trilions/pacages"
But still "Could not find the trilions libray"
Why ? what should I do?

I am new to deal.II, please help!

**Comment by drwells** [comment]
Did you mean to use Trilinos? Are you sure that the installation directory is `/usr/local/Trilinos/pacages` and not something else? I think you may have also spelt `pacages` incorrectly.

Regardless of that - would you be willing to also post this message to the mailing list? More people check the mailing list and you are more likely to get help with this sort of question there.
