### ISSUE TITLE
Document all our new shapes.

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#11084]
The node numberings for the new elements (in particular prisms and wedges) are currently only available in some of @peterrum's slides. We should move this into the official documentation.

**Comment by peterrum** [comment]
![ref0](https://user-images.githubusercontent.com/15707929/97069777-c8bbd300-15d2-11eb-9058-d93b7627fb68.png)
![ref1](https://user-images.githubusercontent.com/15707929/97069779-c8bbd300-15d2-11eb-92b5-086ae2933435.png)
![ref2](https://user-images.githubusercontent.com/15707929/97069780-c9546980-15d2-11eb-8d02-4c8919a53733.png)
![ref3](https://user-images.githubusercontent.com/15707929/97069781-c9546980-15d2-11eb-9932-0c7b55cfc03a.png)
![ref4](https://user-images.githubusercontent.com/15707929/97069782-c9ed0000-15d2-11eb-8340-44518782a0e8.png)
![ref5](https://user-images.githubusercontent.com/15707929/97069783-c9ed0000-15d2-11eb-8ff1-21a0a8030310.png)
