### ISSUE TITLE
clang-format version

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#11106]
Given that clang-format 6 that we use for indentation is now around 2.5 years old (March 2018), I wonder at which point we want to upgrade to a newer version.

I have not checked myself how much of a difference the new clang-format 11 (release this month) would make in terms of code. We have a few things that are annoying, like https://github.com/dealii/dealii/pull/11081#issuecomment-714435660 or #8437 or certainly other places I don't remember, and it would be interesting to see if those are also present with the new version. I recall @masterleinad at some point said to have tried a newer version, but I do not remember what the conclusion was.

**Comment by Rombur** [comment]
Is astyle still maintained? The last commit is over a year old.

**Comment by bangerth** [comment]
I wasn't entirely serious. Last I looked, astyle hadn't been updated very much and I don't think it ever learned how to deal with lambda functions, for example. I do continue to think that the fact that clang-format re-arranges things between lines leads to worse outcomes. I am happy with how it indents each line individually.

**Comment by tamiko** [comment]
I think we should find a consensus first on whether we want to update to `clang-format-11` and what options we want to enable.

Honestly, I think the final set of options we chose for clang-format when we switched away from astyle wasn't particularly good. clang-format has some problems with styles that deviate from the glorious one and only `LLVM` and `Google` styles.
`clang-format` actually recently learned the `GNU` style.

So I *strongly* suggest that this time with a possible (!!) switch to clang-format-11 we nuke our entire `.clang-format` file and we start with:
```
#
# The clang-format (Clang 11) style file used by deal.II. 
#
BasedOnStyle: "GNU"
```

and *then* we have a look at the result and identify behavior we don't like. We can then iterate on configuration options addressing this.

@masterleinad Shall we hijack your pull request and simply reindent everything just with this one command line option? :-)

**Comment by masterleinad** [comment]
I believe that it will be quite impossible to review a pull request/style that implies so many changes so I would rather change options gradually based on the currents settings. That being said, I still have no clear preference for whether we should update or not.

**Comment by tamiko** [comment]
@masterleinad Roger - let me start with the current version and adjust the two most crucial parameters then.

**Comment by bangerth** [comment]
I'm ok if we figure out how to do this now, but could I suggest that we really only apply the patch in a quiet period? That could be during the winter break if we make a concerted effort to merge everything else first, or maybe right after the release?

There is no way we can actually *review* such a large change, but I think that in practice if several people just look at random places, we will find what we dislike.

**Comment by tjhei** [comment]
> I'm ok if we figure out how to do this now, but could I suggest that we really only apply the patch in a quiet period?

Agreed. I would go further and say that I am against a switch if a large number of places in the code change. Last time that caused numerous pull requests and private branches to be impossible to repair/rebase without extra effort.

**Comment by masterleinad** [comment]
@bangerth @tjhei Does #11108 look that bad? 3k lines is not impossible to review.

**Comment by tjhei** [comment]
> 3k lines is not impossible to review.

For me it is less about being able to review it.

**Comment by mwichro** [comment]
I have clang-format 13 that is the default version on the newest Ubuntu. It looks like they have fixed the "bug" I was considering a feature: https://stackoverflow.com/questions/38392889/clang-format-align-asterisk-of-pointer-declaration-with-variable-name

`PointerAlignment: Right` now will have a different effect, i.e. it will move * and & close to the variable.  The behaviour closest to the one used in deal.II would be `PointerAlignment: Middle`. Unfortunately, that also changes the code structure, I have not yet figured out a way to avoid reindenting all my codes.

**Comment by masterleinad** [comment]
I think we settled on using `clang-format 11` for a while.
