### ISSUE TITLE
Documentation : use of cell->face_iterators() in step 7 in run function

### ISSUE THREAD

**Issue by DulcetMech** [dealii/dealii#11142]
Hello,

Although the actual step 7 file in the examples folder is correct, the documentation of the step 7 file seems to have not been changed. 

present documentation : 
              for (const auto &face : cell->face_iterators())
                {
                  const auto center = face->center();
                  if ((std::fabs(center(0) - (-1)) < 1e-12) ||
                      (std::fabs(center(1) - (-1)) < 1e-12))
                    face->set_boundary_id(1);
                }

new code:
              for (unsigned int face_number = 0;
                   face_number < GeometryInfo<dim>::faces_per_cell;
                   ++face_number)
                {
                  const auto center = cell->face(face_number)->center();
                  if ((std::fabs(center(0) - (-1)) < 1e-12) ||
                      (std::fabs(center(1) - (-1)) < 1e-12))
                    cell->face(face_number)->set_boundary_id(1);
                }

regards,
Kartik

**Comment by tjhei** [comment]
Kartik,

as far as I can see, both the code and the documentation use the newer face_iterators(). Are you by any chance looking at an older version of the documentation (the 9.2 release)?
See https://www.dealii.org/developer/doxygen/deal.II/step_7.html

If not, please explain in more detail what you think is incorrect.

**Comment by DulcetMech** [comment]
Hello Timo, 

I believe it is mistake. I have an older version of the library (9.1.1) installed but was referring to the newer documentation (9.2.0). 
I will close this issue as invalid. Excuse me for the mix up.

Regards,
Kartik
