### ISSUE TITLE
Add some checks for silly mistakes with simplices

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#11211]
I've made a couple of dumb errors that could have been caught faster if we had, in place, some assertion checks:
1. Mixing up `FE_Q` with a simplex mesh or `FE_P` with a quad/hex mesh
2. Using a simplex quadrature formula with `FE_Q` or vice versa
3. Providing a 1D quadrature formula to simplices with matrixfree
4. Correctly fail if we get a non-hypercube cell in `MappingQ`

I'm assigning myself so I remember to go and write these.

**Comment by drwells** [comment]
We should store the reference cell type in the mapping.

**Comment by peterrum** [comment]
I think most of these points are already tackled. If not, there is issue #11352. Closing for now.
