### ISSUE TITLE
Enable periodicity_03.cc when p4est 1.2 is released

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#1128]
The test periodicity_03.cc relies on a fix in p4est 1.1. Due to the fact that there is no release in which this is fixed, this test is disabled.
Add the output files when there is a new p4est release.

**Comment by bangerth** [comment]
For reference, the test was added through #1090.

**Comment by tamiko** [comment]
@masterleinad You can resolve this now by using a version constraint of the form
```
periodicity_03.with_p4est>=1.2.output
```
(Don't forget to escape the ```>``` on the command line with ```\>```.)

**Comment by bangerth** [comment]
(Or enclose filenames on the command line in `"..."` or `'...'`.)

**Comment by masterleinad** [comment]
Fixed in #1455
