### ISSUE TITLE
Change ReferenceCell::Type to ReferenceCell::Kind

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11300]
Also, `FiniteElement::reference_cell_type()` to `FiniteElement::reference_cell_kind()`. The point being that we're not actually returning a *type* but an element of a list. I think that we've found in other contexts in the past that we wanted to use the word "kind" for this, because "type" doesn't express this correctly given how the C++ language already uses the word "type".

If this is something we want to change, we should do that now.

@peterrum -- FYI.

**Comment by peterrum** [comment]
I am fine with the renaming. However, would appreciate if we could do it when it is more quiet on the PR front.

**Comment by bangerth** [comment]
What would be a good time frame?

**Comment by peterrum** [comment]
I think this has been tackled already. Closing.
