### ISSUE TITLE
step-43 uses MPI vectors but doesn't support >1 rank

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#11320]
I was looking at step-43 and realized that it uses TrilinosWrappers::MPI vectors, but main() contains
```
     AssertThrow(Utilities::MPI::n_mpi_processes(MPI_COMM_WORLD) == 1,
                  ExcMessage(
                    "This program can only be run in serial, use ./step-43"));
 ```
This is not explained in the text (as far as I can tell) and is quite weird to me. It might be worth addressing that. Additionally, I found the line
```
   Amg_preconditioner = std::make_shared<TrilinosWrappers::PreconditionIC>();
```
which seems a little bit misleading (I know this is taken from step-31/32, but still).

**Comment by peterrum** [comment]
This does not look like an urgent issue. Postponing.
