### ISSUE TITLE
step-26 forgets to reset some variables upon restarting the time iteration

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11349]
As reported by Kaushik Das here: https://groups.google.com/g/dealii/c/IYeaNcpjlHk

**Comment by cpraveen** [comment]
seems similar to https://github.com/dealii/dealii/issues/10715

**Comment by bangerth** [comment]
Oh, doh! We should get better at just fixing stuff right away. If only there were 2 more hours in a day...

Do you want to write a patch (or your student, maybe?)?

**Comment by peterrum** [comment]
Has this issue been fixed in the meantime?

**Comment by bangerth** [comment]
This was fixed by #11460.
