### ISSUE TITLE
CellId::get_cell() should have been a member function of the Triangulation class

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11362]
It requires access to internal data structures of the triangulations, and I think that just doesn't sound quite right. It is also a place that's easy to forget needs to be updated when adding new triangulation classes.

We should move this function and deprecate it where it currently is.

(@marcfehling FYI)

**Comment by marcfehling** [comment]
On second thought, we could also create a new constructor for the `TriaIterator` class instead which takes `Triangulation` and `CellId` objects. What do you think?
