### ISSUE TITLE
Compress test output files?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11375]
My `tests/` directory currently has ~275 MB. If I bzip2 all of the output files, it only has 90 MB. This would sound like a win, but one has to balance that against the time it takes to decompress every time a test is run and the output is compared. The latter only takes ~3 seconds on my laptop, which is certainly negligible compared to the overall run time of the test suite.

What do people think about compressing the data?

**Comment by tjhei** [comment]
> What do people think about compressing the data?

What would be the advantage except saving <200MB on your disk? There are a lot of complications to deal with when handling compressed data (including PRs, diffing, storage inside the git repo, etc.).

**Comment by tamiko** [comment]
A massive disadvantage of storing files in `tests/` compressed is that we would check them into git as binary blobs that cannot be compressed efficiently and, worse, where a one line change in an output file will lead to a completely different compressed binary blob. This does not play well with the delta compression git is using. For reference, the `.git` directory for our archive on my computer is only 231MB large - storing all of our archive history from the beginning of time.

**Comment by tamiko** [comment]
Actually two more comments:

1/ (unhelpful remark:) That's one of the reasons why I am a huge fan of filesystems with transparent compression (like btrfs or zfs). I use it all the time on my computers/servers.

2/ Actually, there might be a way to achieve this by declaring a checkout/checkin filter for git. This would alleviate the problems I pointed out. It is still up to debate whether the added complexity and increased test time (necessity to compress/decompress) is worth it. But just for educational purposes I will investigate how to hack together such a filter.

**Comment by tjhei** [comment]
> It is still up to debate whether the added complexity and increased test time (necessity to compress/decompress) is worth it.

I would vote no. We are talking saving less than 200MB here. 

I can think of many other useful problems to spend engineer time on. :-)

**Comment by bangerth** [comment]
Well, that was a resounding answer :-)
