### ISSUE TITLE
SUNDIALS: replace copy with N_Vector module

### ISSUE THREAD

**Issue by sebproell** [dealii/dealii#11380]
With #11278 new SUNDIALS versions will be supported. After this is merged the copy operations between dealii and SUNDIALS vectors should be replaced by "teaching" dealii's vector operations to SUNDIALS.

I already described the N_Vector module briefly here: https://github.com/dealii/dealii/pull/11278#issuecomment-737395285 and the documentation can be found here: https://computing.llnl.gov/sites/default/files/public/ark_guide-4.5.0_0.pdf starting on page 307.

A very simple first implementation with some tests can be found here: https://github.com/sebproell/dealii/pull/1/files. I will improve a little on this work and open a draft PR soon.

**Comment by peterrum** [comment]
Is this issue resolved?

**Comment by sebproell** [comment]
Nope, I want to at least replace the `copy` functions in the ARKode integrator. PR almost ready, I just need some backwards-compatibility adaptations.
