### ISSUE TITLE
Missing picture for step-74

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11466]
In the results section of step-74, there is a reference to a picture `https://www.dealii.org/images/steps/developer/step-74-log-log-plot.png`, but this picture is not in the repository yet.

@zjiaqi2018 -- can you please send it to me by email?

Following up on #10932.

**Comment by bangerth** [comment]
Separately, is it correct that the plot only shows results for the smooth test case? If so, I'll move the discussion of the picture above the place where you start discussing the output for the L-domain.

**Comment by tjhei** [comment]
I uploaded the png to https://www.dealii.org/images/steps/developer/step-74-log-log-plot.png and I will let Jiaqi answer the question.

**Comment by zjiaqi2018** [comment]
The plot only shows results for the singular case in L-domain and I have sent you the picture by email.
