### ISSUE TITLE
Issues with step-74

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11465]
Following up to #10932.

@zjiaqi2018: Can you take another look at the `compute_energy_norm_error()` function in step-74? I don't think you ever describe how the energy norm is defined (please add to the function description). But, in particular, none of the terms you implement include the diffusion factor nu. I think it needs to be added to the appropriate terms.

**Comment by zjiaqi2018** [comment]
I forgot to add this.
![image](https://user-images.githubusercontent.com/36655731/103595326-25881380-4ec9-11eb-92ce-56b05054c7d2.png)

If we need to include nu, I guess we can add it to the first term on the right-hand side
and it will become this
![image](https://user-images.githubusercontent.com/36655731/103596112-28840380-4ecb-11eb-9735-6f8846cd1260.png)

**Comment by bangerth** [comment]
@zjiaqi2018 Can you add this formula to the current version of the tutorial program on the master branch? 

For reference, for the continuous discretization of the Laplace equation, the appropriate "energy norm" is
```
  \|  \sqrt{\nu} \nabla (u-u_h) \|
```
which corresponds with your first term if `nu` is constant. Whether or not `nu` also has to appear in the other terms I don't know off the top of my head, but we can find out with dimensional analysis. In fact, if I look at the weak formulation of your problem, the energy norm should be defined as
```
  \|u-u_h\|_{energy} = sqrt{ a(u-u_h,u-u_h) } plus potentially other terms
```
and because you have `nu` appear in the jump terms of your bilinear form, I would expect them to also appear in the energy norm definition.

**Comment by zjiaqi2018** [comment]
Sure I would like to do that, and yes your are right, the one I showed should be the square of the energy norm.

My only question is how to edit the current version of the tutorial program on the master branch.
I am not so familiar with git. Would you mind giving some instructions on how to do that?
Thanks!

**Comment by tjhei** [comment]
> My only question is how to edit the current version of the tutorial program on the master branch.
> I am not so familiar with git. Would you mind giving some instructions on how to do that?

Jiaqi, let's do this together later this week.

**Comment by peterrum** [comment]
I think this has been tackled by now. So closing this issue. If this is not the case, feel free to reopen the issue.
