### ISSUE TITLE
Successful build Ubuntu 20.04

### ISSUE THREAD

**Issue by branch171** [dealii/dealii#11489]
Not an issue but a clean build. This is how I did it.

Note:
I have openmpi and build-essentials already installed by another package. You will need these before you do the following.
also -j4 below assumes you have 4 cores for the installation, change to suit your processor

You need to do the following in this order:
```
sudo apt update
sudo apt install git
sudo apt install cmake libblas-dev liblapack-dev
```
I install from ~/apps
```
mkdir apps
```
and install to ~apps/bin so 
```
cd apps
mkdir bin
```
Then install trilinos
I did not need to make the changes to packages/epetra/src/Epetra_LAPACK_wrappers.h
```
cd ~/apps
git clone https://github.com/trilinos/Trilinos.git
cd Trilinos
mkdir build
cd build
```
I made this bash script in the build directory, the install goes in ~/apps/bin:

put the below in trilinos_install.sh
```
#!/bin/bash
clear
cmake                                              \
-DTrilinos_ENABLE_Amesos=ON                        \
-DTrilinos_ENABLE_Epetra=ON                        \
-DTrilinos_ENABLE_EpetraExt=ON                     \
-DTrilinos_ENABLE_Ifpack=ON                        \
-DTrilinos_ENABLE_AztecOO=ON                       \
-DTrilinos_ENABLE_Sacado=ON                        \
-DTrilinos_ENABLE_Teuchos=ON                       \
-DTrilinos_ENABLE_MueLu=ON                         \
-DTrilinos_ENABLE_ML=ON                            \
-DTrilinos_ENABLE_ROL=ON                           \
-DTrilinos_ENABLE_Tpetra=ON                        \
-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON                \
-DTrilinos_ENABLE_COMPLEX_FLOAT=ON                 \
-DTrilinos_ENABLE_Zoltan=ON                        \
-DTrilinos_VERBOSE_CONFIGURE=OFF                   \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON        \
-DTPL_ENABLE_MPI=ON                                \
-DBUILD_SHARED_LIBS=ON                             \
-DCMAKE_VERBOSE_MAKEFILE=OFF                       \
-DCMAKE_BUILD_TYPE=RELEASE                         \
-DCMAKE_INSTALL_PREFIX:PATH=~/apps/bin/trilinos    \
../
sudo make -j4 install
```
use chmod +x trilinos_install.sh to make executable then run with ./trilinos_install.sh

Then install dealii:
```
cd ~/apps
git clone https://github.com/dealii/dealii
cd dealii
mkdir build
cd build
```
I made this bash script in the build directory,, the install goes in ~/apps/bin:

put the below in dealii_install.sh
```
#!/bin/bash
clear
cmake                                    \
-DTRILINOS_DIR=~/apps/bin/trilinos       \
-DCMAKE_INSTALL_PREFIX=~/apps/bin/dealii \
../
sudo make -j4 install
```
use chmod +x dealii_install.sh to make executable then run with ./dealii_install.sh

Then from the terminal
```
make test
````
I get:
```
Running quicktests...
Test project /home/cbranch/apps/dealii/build/tests/quick_tests
    Start 1: step.debug
    Start 2: step.release
    Start 3: affinity.debug
    Start 4: tbb.debug
    Start 5: taskflow.debug
    Start 6: lapack.debug
    Start 7: umfpack.debug
    Start 8: boost_zlib.debug
    Start 9: gmsh.debug
1/9 Test #6: lapack.debug .....................   Passed    6.76 sec
2/9 Test #5: taskflow.debug ...................   Passed    6.90 sec
3/9 Test #4: tbb.debug ........................   Passed    7.89 sec
4/9 Test #8: boost_zlib.debug .................   Passed    8.49 sec
5/9 Test #3: affinity.debug ...................   Passed    8.54 sec
6/9 Test #9: gmsh.debug .......................   Passed    8.70 sec
7/9 Test #7: umfpack.debug ....................   Passed   10.67 sec
8/9 Test #2: step.release .....................   Passed   12.23 sec
9/9 Test #1: step.debug .......................   Passed   14.43 sec

100% tests passed, 0 tests failed out of 9

Total Test time (real) =  14.43 sec
Built target test
```
Hope this helps.

**Comment by masterleinad** [comment]
Is there anything that was unclear in the build instructions, say in https://dealii.org/developer/readme.html?

**Comment by branch171** [comment]
Hi Daniel

 

I think the observation I would make is if you just followed the instructions in the readme file a novice to linux would struggle.

 

The build instructions are complete but difficult to get all the information required to hand. This makes it a scary process for the person new to linux and dealii.

 

You need to gather and read from a number of places. Like the trilinos readme page if you want that. Also, many linux systems when installed don’t have all the libraries pre-packaged, cmake, git, blas and lapack, openmpi, g++. For a novice there is no one place to give you the order and commands to get a clean and comprehensive install. An experienced linux user would just go … “ahhh the  library xxx is missing let me find the apt install command for that” and try again. Screens of errors throw a novice into a blind panic.

 

I think an example script that is distilled from the readme pages, as I have I done, would help a novice get a working system that can make use of the majority of the tutorials.

 

Craig

**Comment by masterleinad** [comment]
Well, we also have https://github.com/dealii/dealii/wiki/Getting-deal.II.

**Comment by branch171** [comment]
I think my script helps with point 6 for a novice:

 

5.	If you need additional dependencies (MPI, Trilinos, p4est, PETSC, ...) it is easier to use a source-based installer like candi <https://github.com/dealii/dealii/wiki/Getting-deal.II#candi>  or spack. Otherwise, go to the next point.
6.	Get the source code to deal.II by downloading the .tar.gz file from the latest release at https://github.com/dealii/dealii/releases and go to Installation from source <https://github.com/dealii/dealii/wiki/Getting-deal.II#installation-from-source> .

I didn’t try candi so maybe that works out of the box.

 

Craig

**Comment by masterleinad** [comment]
You're welcome to improve https://github.com/dealii/dealii/blob/master/doc/readme.html with a pull request. :slightly_smiling_face: 
Otherwise, let's close this.

**Comment by branch171** [comment]
Sure all best Craig
