### ISSUE TITLE
Incompatibility between petsc and Trilinos Wrappers for Sparsematix and Vector (MPI)

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#11480]
Hi Everyone,

I notice that the ```Sparsematrix``` and ```Vector``` interfaces have small incompatibility issues when switching between the ```Petsc``` and ```Trilinos``` Wrappers.
Specifically, ```Trilinos::Sparsematrix``` does not allow multiplication with a ```MPI``` vector which has indexset set as ```locally_relevant_dofs``` => mat.vmult(dst, src) gives error when src is not completely distributed. dst and mat are completely distributed.
Similarly, completely distributed ```Trilinos::MPI::Vector```  does not allow ```add``` operation with a ghosted vector.
These both operations throw error (in debug mode). Error from matrix multiplication looks like ```Assert(in.trilinos_partitioner().SameAs(m.DomainMap()) == true,
               ExcMessage(
                 "Column map of matrix does not fit with vector map!"));```

However, when using ```PETSc``` wrappers, no such check is made and the calls are just forwarded to ```PETSc``` internal functions.

Do you suggest adding similar checks in ```PETSc``` interface to ensure the compatibility?

**Comment by bangerth** [comment]
The question is: (i) what kinds of operations can the two libraries perform, (ii) for which operations are the results correct?

If PETSc supports a particular operation, and implements it correctly, then there is no need to add an assertion even if the Trilinos wrapper has such an assertion. Of course, if the result is wrong, then we should add the assertion.

**Comment by sairajat** [comment]
Hello Professor,

The calculations aren't wrong. I just wanted to point out that because of these incompatibilities changing namespaces in the code to switch to the other library may not always work.

For example, switching from ```dealii::LinearAlgebraPetsc``` to ```dealii::LinearAlgebraTrilinos``` may not always work if you are using one of the functions above. (There could be more). I understand that it also depends on whether the underlying library supports such operations. May be it would be good to mention these subtle differences in the documentation somewhere. 

Please feel free to close the issue..

**Comment by bangerth** [comment]
Yes, there unfortunately are incompatibilities. Some have to do with the fact that the two libraries sometimes implement different functionalities. For example, with PETSc, the locally owned elements need to form a single contiguous range whereas Trilinos doesn't require this.

I think we all wished we had had a better design that made these classes more alike. But they were written several years apart, with different levels of expertise, and reflect what we knew about these two libraries at the time. We've made some effort at unifying the interfaces -- for example, deprecating the `local_range()` functions. More work is necessary but time is limited. As always, help would be very much appreciated!
