### ISSUE TITLE
Ubuntu/Debian: Document better how to use the deal.II package

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#11529]
Currently we do a somewhat mediocre job at clearly documenting how to install deal.II on Ubuntu/Debian via the package manager.

Todo:
 - [ ] Document how to install the current deal.II version on current debian stable via backports https://backports.debian.org/
 - [ ] Document how to install the current deal.II version on Ubuntu LTS via a PPA: https://launchpad.net/~ginggs/+archive/ubuntu/deal.ii-9.2.0-backports
 - [ ] Document what packages need to be installed:
```
$ sudo apt install libdeal.ii-dev libdeal.ii-doc cmake make g++
``` 
 - [ ] Document where to find the example steps
```
$ cp -r /usr/share/doc/libdeal.ii-doc/examples/step-1
$ cd step-1
$ cmake .
$ make run
```

**Comment by peterrum** [comment]
This does not seem to be urgent. Postponing.

**Comment by Darth-Veidim** [comment]
Hello there,

it seems to me that most of the tasks here have already been solved:

- the installation procedures via backports and via PPA are already documented in [wiki](https://github.com/dealii/dealii/wiki/Debian-and-Ubuntu), aren't they?
- required packages are listed on the [README](https://www.dealii.org/developer/readme.html) page.

I didn't find the realization of the last task, so I can add it. Should the instruction to find examples be found in the [README.md](https://github.com/dealii/dealii#readme)?

**Comment by bangerth** [comment]
I think what @tamiko had in mind for that last task is to explain where users would find the tutorial programs if the library was installed in `/usr` via a package manager. I don't actually know where the tutorial programs end up (maybe `/usr/share`?) but it would be useful to document that on the wiki page where the Debian/Ubuntu package is describe.

Any help will as always be gratefully accepted!

**Comment by Darth-Veidim** [comment]
I wasn't able to fork dealii.wiki, so, I cloned it locally via ssh indicated at the end of the [page](https://github.com/dealii/dealii/wiki). Then, after adding the discussed changes, I wasn't able to push without having permission to push directly to the repo. Then how can I contribute to the wiki?

**Comment by Darth-Veidim** [comment]
I suggest making the following additions to the `Debian_and_Ubuntu.md`:

---
## Installing the tutorial steps

To install the tutorial steps, proceed with an installation of a documentation library:

```
apt-get install libdeal.ii-doc
```

The tutorial steps are in the `/usr/share/doc/libdeal.ii-doc` directory. To copy a particular tutorial step into the current folder and run it, proceed with the following commands (for example, step-1):

```
$ cp -r /usr/share/doc/libdeal.ii-doc/examples/step-1 .
$ cd step-1
$ cmake .
$ make run
```
---

However, I would like to add the changes myself since I want to practice the contribution mechanics.

**Comment by tamiko** [comment]
@Darth-Veidim Thanks a lot! Do you by chance have a link to your version of the wiki repository? I am happy to apply these changes directly.

We had to restrict wiki editing sometime earlier last year due to attempted malicious edits.

**Comment by Darth-Veidim** [comment]
Hello @tamiko.
Do you mean that I need to push the updated wiki to my repositories first and then provide you with a link?

**Comment by tamiko** [comment]
@Darth-Veidim Yup, if you don't mind, simply push the wiki repo to your github account and tell me the URL.

**Comment by Darth-Veidim** [comment]
@tamiko, pushed the wiki [here](https://github.com/Darth-Veidim/deal.ii_wiki.git).

**Comment by Darth-Veidim** [comment]
I would like to ask you, if there are other not complicated tasks that I can work on? I need more practice in contributing for my Simulation Software Engineering class.

**Comment by Rombur** [comment]
You could run a spell checker on the code. I am sure there are typos.

**Comment by bangerth** [comment]
@Darth-Veidim There is also this page https://dealii.org/participate.html and in particular its link to "Starter projects".

**Comment by Darth-Veidim** [comment]
Thank you for your suggestions.

@tamiko, is everything alright with my repository?

**Comment by tamiko** [comment]
@Darth-Veidim Looks good. I have added your commit.
