### ISSUE TITLE
set_all_manifold_ids does not work in simplices

### ISSUE THREAD

**Issue by lwy5515** [dealii/dealii#11535]
I am testing Step-6 using global refinement on simplices. Here I use `GridGenerator::convert_hypercube_to_simplex_mesh` to generate the triangular mesh. For example,

```
Triangulation<dim> tria, temp;
GridGenerator::hyper_ball(temp);
GridGenerator::convert_hypercube_to_simplex_mesh(temp, tria);
```

Note that `GridGenerator::convert_hypercube_to_simplex_mesh` would not copy the manifold_id to the output grid. So I need assign the manifold id again like

```
tria.set_all_manifold_ids(0);
tria.set_manifold(0, SphericalManifold<dim>());
```
It seems that this will produce exceptions. The problem is at line 1964 at tria_accessor.template.h
```
      case 2:
        // for quads also set manifold_id of bounding lines
        for (unsigned int i = 0; i < 4; ++i)
          this->line(i)->set_manifold_id(manifold_ind);
        break;
```
where the number 4 in the loop should be replaced by the number of bounding lines for the polygon.  Does anybody know how to fix that?

**Comment by bangerth** [comment]
You will want to use `this->n_faces()` instead of the hard-coded `4`. Want to give this a try?

**Comment by lwy5515** [comment]
Sure. Let me give it a try.

**Comment by peterrum** [comment]
This is indeed an issue. @bangerth As a side remark:  we should merge #11389, since this will copy the manifold ids.

**Comment by lwy5515** [comment]
I just tried as @bangerth suggested. Now I do not have any problems in the code but the output grid is not what I expect
<img width="413" alt="Capture" src="https://user-images.githubusercontent.com/13604144/104630608-3f7cdf80-569b-11eb-94a4-6119345ff520.PNG">

**Comment by peterrum** [comment]
Similarly to #11484, you need to do the following:

https://github.com/dealii/dealii/blob/8562cf6f23c0ded6504fcabc4e79b3b77fa9a66b/tests/simplex/step-01.cc#L64-L67

This is not exactly a simplex mesh issue but an issue generally if we make copies of triangulations. Could you have a try by adding these lines?

**Comment by bangerth** [comment]
@lwy5515  How does this look without further refinement? Just the coarse mesh?

**Comment by lwy5515** [comment]
@bangerth  The above grid is obtained from a 4-time-global refinement of the coarse mesh. The red part has the manifold id 0 and the blue is `flat_manifold_id`.

I also try to test step-2 with the code @peterrum provided. Here is the plot:
<img width="338" alt="Capture" src="https://user-images.githubusercontent.com/13604144/104634595-1f501f00-56a1-11eb-9cd7-2a23459a8a7d.PNG">
It seems that inner cells are not refined along the circle since each segment along the inner circle has 4 faces (exactly 2 refinements performed).

**Comment by eliasstudiert** [comment]
I think this problem will be fixed soon. In the current version of convert_hypercube...() the inheritance of the manifold_ids is not implemented correctly yet.

**Comment by peterrum** [comment]
FYI: https://github.com/dealii/dealii/pull/11484#issuecomment-761524652

**Comment by lwy5515** [comment]
@peterrum I think now it works. Just note that this also works for a grid on the co-dim 1 surface. As an example, here is a plot from step-38 on a simplex mesh.
<img width="444" alt="Screen Shot 2021-01-16 at 5 05 04 PM" src="https://user-images.githubusercontent.com/13604144/104816769-695e0f80-581d-11eb-9ef1-f544e49050c3.png">
It only works for the linear element together with the linear mapping. I will create a PR for this.

**Comment by peterrum** [comment]
Excellent! Thank you for letting me know!
