### ISSUE TITLE
intel bug

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1154]
I am investigating the weird bug in http://cdash.kyomu.43-1.org/testDetails.php?test=16888618&build=10183

It turns out 
```
TableIndices<2> ti=SymmetricTensor<2,2,double>::unrolled_to_component_indices(1);
```
is returning [0,0] instead of [1,1] because the static variable ```table[3]``` in symmetric_tensor.h:1903 is not initialized correctly. It looks like an optimization bug (even though we are in debug mode with all optimizations turned off), because rearranging statements in the _23.cc test makes the bug disappear (it depends where I insert the code above).

Does anybody have a suggestion on what to do here?

**Comment by bangerth** [comment]
Does it work if you make these local tables non-static? I suspect that in many cases that will yield code that is no worse (and in some actually better).

**Comment by tjhei** [comment]
Thanks for the good idea, seems to work! :-) It is probably related to the function being inlined in some branch and not inlined in another...

**Comment by tjhei** [comment]
See #1158
