### ISSUE TITLE
Arpack interface broken and insufficient

### ISSUE THREAD

**Issue by guidokanschat** [dealii/dealii#1156]
The class ArpackSolver is pretty much broken and does not utilize Arpack well. An easy fix does not seem possible until we know what Arpack does and what its options are. In #759, it was fixed at least so that it would output eigenvectors instead of Schur vectors. Here, I would like to start a list of requirements on the new interface.
- Allow for symmetric and nonsymmetric EVP as well as SVD. Currently, we must compute imaginary parts even if we know everything is real
- Find out the relation of the matrix and the shifted inverse. Is the matrix ever used? The current interface ignores it.
- Some of the Arpack modes fail to compute eigenvalues. We have to investigate in more detail. The mode "largest magnitude" has worked for me so far and produces the eigenvalues with smallest magnitude.
- Find out relations to Parpack and why we should need it

This also relates to #1146.

**Comment by guidokanschat** [comment]
Just before Christmas I learned more about Arpack again: as long as the number of Arnoldi vectors does not exceed the number of eigenvalues, the two letter codes for choosing eigenvalues do not make any sense, since they choose from the Ritz values. And if you choose n out of n, there is not much of a choice.

We will need somebody who knows more to fix this. I am willing to participate, but I need more expertise. Possibly, I can work on this in August with Chen Greif.

**Comment by tjhei** [comment]
So is there anything else that can/should be done for 8.4.0?

**Comment by guidokanschat** [comment]
Currently, it does more or less what you expect. It approximates the number of eigenvalues and eigenvectors requested. There is no guarantee, as for any other nonsymmetric method, that these are the lowest ones.

Thus, I would say it is safe to leave it as it is with the restrictions imposed by the interface.

**Comment by drwells** [comment]
This would be good to have but lets close this for now - if anyone is interested we can pick it up again.
