### ISSUE TITLE
Make gmsh format store manifold ids.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#11583]
msh version > 4 allows to store arbitrary tags along with each mesh object. It would be pretty straight forward to allow saving (and loading) manifold ids with msh using those tags.

**Comment by blaisb** [comment]
This would be an amazing feature

**Comment by bangerth** [comment]
I so so wished that the gmsh people had come up with a self-describing file format. The way attributes are attached to objects is just so completely opaque: There is no place to *describe* what an attribute actually means...

**Comment by luca-heltai** [comment]
> I so so wished that the gmsh people had come up with a self-describing file format. The way attributes are attached to objects is just so completely opaque: There is no place to describe what an attribute actually means...

Digging into their documentation, from version 2.0 onwards, one can actually give a name to physical entities. In #11592 I'm using this to read and write Material, Manifold, and Boundary ids. It's a bit of a hack, I admit, but it's the best I could come up with.

**Comment by luca-heltai** [comment]
> This would be an amazing feature

@blaisb : here it is. :)
