### ISSUE TITLE
Potential bug in ThreadLocalStorage

### ISSUE THREAD

**Issue by at-vuong** [dealii/dealii#11587]
We are using `dealii::ThreadLocalStorage<T>` in our project and have had some issues with this class recently.

I think there might be a bug in `dealii::ThreadLocalStorage`. The copy assignment https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L330 and  and the move assignment https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L344 both do not copy/move the `exemplar` member, which is used for constructing new copies for other threads. Additionally, the copy and move constructors do copy/move `exemplar`. I would assume that constructor and assign should "do the same thing".

I am missing something or is this really a bug? Thanks for your help!

**Comment by bangerth** [comment]
It sounds like a bug. Thanks for investigating the issue already! @nmuch was kind enough to address this in #11596 already!
