### ISSUE TITLE
Use a more efficient container for p::DistributedTriangulationBase::local_cell_relations 

### ISSUE THREAD

**Issue by elauksap** [dealii/dealii#11589]
Related to #11515.

I suggest to use a more efficient container for the `local_cell_relations` member of `parallel::DistributedBase::local_cell_relations`.

Now we have:
```
using cell_relation_t = typename std::tuple<CellStatus, cell_iterator>;
std::vector<cell_relation_t> local_cell_relations;
```

I would suggest to investigate the possibility to use, *e.g.*
```
std::map<cell_iterator, CellStatus> local_cell_relations;
```

~For consistency, the callback methods implemented in the `parallel::distributed::SolutionTransfer` class would better swap some input arguments (from `method(..., CellStatus, cell_iterator, ...)` to `method(..., cell_iterator, CellStatus, ...)`).~

**Comment by drwells** [comment]
This was discussed in #11913 and we decided to keep the arrays. In particular, we serialize and unserialize the array, loop over it to do consistency checks, and directly index it (with indices calculated by p4est) - it's unlikely that a map is going to be a better choice.
