### ISSUE TITLE
minimum cmake version?

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#11615]
It seems as if PR  #11384 breaks compatibility with e.g. cmake version 2.8. 

Discuss whether this is intended and how to fix this.

**Comment by tamiko** [comment]
Interesting. I originally tested down to CMake-3.1.

I now tested with CMake-3.0, which seems to be the first failing version.
In summary, CMake versions older than 3.1 seem to not support the `\[...\]` regular expression part.

CMake-3.1 was released early 2015. We currently require as minimum compiler version gcc-5.1 (released April 2015), or clang-4.0.0 (which was released July 2017).

So I suggest we simply increase the minimum required version to 3.1. This is long overdue.

**Comment by nfehn** [comment]
Sounds reasonable

**Comment by bangerth** [comment]
@tamiko What do the typical ~2016 distros ship with? I'm having second thoughts whether requiring 3.1 was the right choice or whether we could have required something higher already. I don't know whether that makes much of a difference, but if these distros all already have, say, 3.5, then maybe it would have been good to actually require that.
