### ISSUE TITLE
Robustness of ParameterHandler::parse_input()

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#11628]
It seems as if ``ParameterHandler::parse_input()``, see https://www.dealii.org/developer/doxygen/deal.II/parameter__handler_8cc_source.html#l00532, does not work for an input.json file that is empty. An input file with content ``{}`` seems to be fine.

**Comment by nfehn** [comment]
@peterrum what do you think? Is this a bug and do you think we should fix this before the next release?

**Comment by bangerth** [comment]
What does the JSON specification say? Is an empty file valid?
