### ISSUE TITLE
Implement Simplex::QGauss(4) without copying and pasting

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#11636]
We can generate a lot of simplex quadrature rules by doing permutations with barycentric coordinates. This issue is a reminder that I should investigate this and implement the actual algorithmic description of this family of rules (which is implemented in quadpy as the Witherden Vincent formulas).

In particular - quadpy implements a lot of simplex formulas with JSON as
```json
{
  "name": "Witherden-Vincent 3",
  "domain": "T3",
  "degree": 3,
  "test_tolerance": 2.379e-17,
  "data": {
    "s31": [
      [
        1.362178425370874e-01,
        1.137821574629126e-01
      ],
      [
        3.281633025163817e-01,
        1.080472498984286e-01
      ]
    ]
  }
}

```
where `s31` is a barycentric permutation function. This is a lot better than copying and pasting tables.

**Comment by bangerth** [comment]
Have you thought about either just importing quadpy or linking to it, and then getting information from there rather than re-implementing (in whatever form) these formulas? Or at least reading these formulas with a JSON parser (available through BOOST and already used).

**Comment by drwells** [comment]
I don't think we can easily link against quadpy - its a python library. Even if it were in C++ I'd still prefer to reimplement these quadrature formulae to avoid adding an external dependency for something as fundamental as quadratures.

The difficulty with reading these in in JSON is that the format includes keys like `"s31"` that indicate some permutation function should be applied - we would still need to implement these ourselves.

The other difficulty with storing JSON is that we would need to somehow incorporate this data into the library - should we just encode the strings, for example, into the library itself? If so we are back to where we started.

**Comment by bangerth** [comment]
We could just store these as static C-style strings. That requires little memory. We can also store them in separate files that we read when necessary, but that has overhead with regards to having to install them in specific places.

**Comment by drwells** [comment]
I like the idea of not having to write these all out but I'm concerned any benefits we get from storing these as JSON will be outweighed by the extra ceremony required to parse the JSON and convert it into a quadrature. It doesn't help that quadpy uses slightly incompatible notation between 2D and 3D for permutations. Regardless of which way we go we will have to implement our own 

We could also implement our own classes
```cpp
class BarycentricQuadratureData
{
  int dim;  

  enum PermutationFunction
  {
    s31,
    s22,
    s211
  };
  
  struct Permutation
  {
    std::vector<double> b_points;

    double weight;

    PermutationFunction pf;
  };

  std::vector<Permutation> permutations;
};
```
rather than JSON, and have a method for parsing those and turning them into `Quadrature` objects.

**Comment by bangerth** [comment]
I the end, I'm agnostic about it. Simply wanted to raise the possibility of importing things in a way that makes it easier to import more and/or to deal with updates quadpy might put out at some point. There are ways to do the parsing only once, the first time a class is instantiated, for example, which might amortize the parsing cost. 

But then I don't know quadpy, and so will be happy to defer to you for whatever you think is the most expedient way to move forward!

**Comment by drwells** [comment]
It's worth thinking about. We definitely need the permutation functions I added in #11685. We should come up with a better data format if we want to implement lots of quadrature rules for simplices.
