### ISSUE TITLE
Flag -ansi incompatible with intel compiler

### ISSUE THREAD

**Issue by nabw** [dealii/dealii#11667]
Hello deal.II-ers, 
I would like to know if anyone is currently working with intel compilers. I am trying to use the Xe 2019 and noted that this line:
https://github.com/dealii/dealii/blob/5d12c8cf10d6f9ab8c7dd2893786129423f9c187/cmake/setup_compiler_flags_intel.cmake#L51
conflicts with the requirement of c++14 standard (or any standard after c++03 really https://stackoverflow.com/a/17480842). 
I just finished compiling the entire library by commenting it, so maybe it can be safely removed?
**Of course, with that line uncommented I cannot finish cmake configuration as "the compiler does not have c++14 features".

**Comment by tamiko** [comment]
Good point. Yes, the `-ansi` flag is a remnant of the past and should be removed.

I have reproduced the issue with icc 19.1.1.217 (XE 2020 Update 1).

**Comment by nabw** [comment]
I think this should suffice: https://github.com/dealii/dealii/pull/11669
Let me know if I can do anything else. 
Best!
