### ISSUE TITLE
#1155 breaks non-C++11 code

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#1168]
If deal.II is compiled without C++11, the patch #1155 makes compilation fail (see http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=10278). The reason is that the compiler does not seem to recognize `&FESystem<dim,spacedim>::template compute_fill_one_base<dim_1>` as first argument to boost::bind. @bangerth could you please take a look? I tried to fix it but error messages for boost::bind are so tricky to understand so I gave up after a few attempts (I worked on such things some five years ago but I don't remember what the correct syntax should be).

**Comment by bangerth** [comment]
Can you copy the entire error message here? From the text shown at cdash, namely
```
/.../dealii/source/fe/fe_system.cc:1045:3: note: in instantiation of function template specialization 'dealii::FESystem<1, 2>::compute_fill<1>' requested here
  compute_fill(mapping, cell, invalid_face_number, invalid_face_number,
  ^
/.../dealii/bundled/boost-1.56.0/include/boost/bind/bind.hpp:1298:5: note: candidate function template not viable: requires single argument 'f', but 12 arguments were provided
    BOOST_BIND(F f)
    ^
/.../dealii/bundled/boost-1.56.0/include/boost/bind/bind.hpp:1291:20: note: expanded from macro 'BOOST_BIND'
#define BOOST_BIND bind
                   ^
/.../dealii/bundled/boost-1.56.0/include/boost/bind/bind.hpp:1306:5: note: candidate function template not viable: requires 2 arguments, but 12 were provided
    BOOST_BIND(F f, A1 a1)
    ^
/.../dealii/bundled/boost-1.56.0/include/boost/bind/bind.hpp:1291:20: note: expanded from macro 'BOOST_BIND'
#define BOOST_BIND bind
                   ^
/.../dealii/bundled/boost-1.56.0/include/boost/bind/bind.hpp:1314:5: note: candidate function template not viable: requires 3 arguments, but 12 were provided
    BOOST_BIND(F f, A1 a1, A2 a2)
    ^
```
it looks to me that it can take the address just fine, and that there are corresponding functions `boost::bind`, just not ones with 12 arguments. It may be that for reasons of efficiency, they limited the number of arguments one can provide to `boost::bind` to ten, or so. But I'd like to see the entire error message for that.

**Comment by bangerth** [comment]
Indeed, looking at the boost code, this is how it looks like. We do the same with `Threads::new_task` which is why I chose to package things up into a `std::function` first. What one needs to do is combine several of the arguments into one, e.g., using `std::pair` or `std_cxx11::tuple` and then unpack again in the called function. 

Do you want to try, or should I see if I can come up with something without access to this old a compiler?

**Comment by kronbichler** [comment]
Good point. I can reduce the function arguments to 10 and try...

**Comment by kronbichler** [comment]
Give me an hour or two, must finish some other work first...
