### ISSUE TITLE
Fix test multigrid/transfer_matrix_free_06.mpirun=15.debug

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11726]
The test `multigrid/transfer_matrix_free_06.mpirun=15.debug` keeps on timeouting for some time now:
```
The following tests FAILED:
	3320 - multigrid/transfer_matrix_free_06.mpirun=15.debug (Timeout)
```

**Comment by kronbichler** [comment]
I think we should reduce the size of these tests. Apparently it takes too much time to build a matrix for the reference result. I think the 3D case is to blame and we should remove some of the adaptive refinement steps there.

**Comment by peterrum** [comment]
I'll open a PR later today.
