### ISSUE TITLE
AffineConstraints loosing contraints on close in 3D

### ISSUE THREAD

**Issue by mwichro** [dealii/dealii#11725]
Dear all
I'm using AffineConstraints to impose Dirichlet boundary conditions on the faces that are on interface between two materials. The faces are marked by setting user flag, so the code that generates constraints is:
```c++
for (auto cell : dof_handler_u.active_cell_iterators())
    for (unsigned int face = 0; face < GeometryInfo<dim>::faces_per_cell;
         ++face)
      if (cell->is_locally_owned() && cell->face(face)->user_flag_set())
        {
          cell->face(face)->get_dof_indices(dof_indices);
          for (unsigned int i = 0; i < dof_indices.size(); ++i)
            {
              types::global_dof_index &dof = dof_indices[i];
              constraints_homogeneous.add_line(dof);
              constraints_inhomogenities.add_line(dof);
            }
        }
```
The problem appears in 3D if
1. Process with lower rank  owns DoFs at the edge of material
2. Process of lower rank does not know anything about the constraints

The grey block is subdomain owned by process 84, the meshed faces should be constrained:
![issue_constraints](https://user-images.githubusercontent.com/32612987/107539311-1f224100-6bc5-11eb-9a89-8b59cea2459e.jpeg)
veritical and horizontal slice through the problematic area. The colour field was generated by using  zero vector and then distributing constraints on it:
![image](https://user-images.githubusercontent.com/32612987/107539893-b9828480-6bc5-11eb-8edd-7f48dfd2178f.png)

In my case the issue appears when using 96MPI ranks on a problem with 30M DoF.

**Comment by bangerth** [comment]
> The problem appears in 3D if
>
> * Process with lower rank owns DoFs at the edge of material
> * Process of lower rank does not know anything about the constraints

The owner of that DoF is then probably the processor with the lower rank. You somehow have to make sure that every process that has this DoF as a locally relevant DoF learns about the constraint. A first step is to make sure that your constraints are *consistent* across processors. Have you tried calling `AffineConstraints::is_consistent_in_parallel()` to check for that?

**Comment by mwichro** [comment]
I'll try that in a while, but I think it will return false since the constraint is only pressent on the MPI process with higher rank.
I've assumed close() does the  parallel communication to synchronize the constraints.

**Comment by bangerth** [comment]
I don't think `close()` actually knows anything about the parallel universe. It doesn't have access to a communicator, for example.

**Comment by mwichro** [comment]
Right. So I should  resolve that issue inside my code or implement a new method to AffineConstraints that does synchronization.

**Comment by bangerth** [comment]
I thought that we had code somewhere to exchange constraints between processors, but I'm not entirely sure. The code in `is_consistent_in_parallel()` might actually be the closest example to draw on.

In the end, the assumption I believe has always been that every processor is able to compute the constraints it needs for those rows of the matrix and vector it might write into. These are generally the locally active DoFs (a superset of the locally owned ones). Out of curiosity, why is it that you can't determine the constraints from both sides of the processor boundary? That would solve your problem.

**Comment by mwichro** [comment]
The proces 84 does not own any cell or face inside the meshed domain, however is does own some of dofs at the interface because it owns an edge. This way it is not aware the the edge it owns are on the face marked as internal boundary. 
The solution for that would be marking both faces and edges in 3D, but I am sure how to impose boundary condition on edges (or points in 2D).

I think I've solved the problem by synchronizing the constraints. It is an ugly hack: I'm using ghosted vector, adding ones to the constrained dofs, updating ghost values and setting constraints wherever that vector is > 0. But it's simple and seems to work. 
BTW: I'm using this kind of tricks in other places, some years ago I've even built coupling between mesh and boundary mesh (codim 1) using it (via encoding trees of cells in doubles bit by bit ), I think it would be useful to add parallel vector that works on int (or a general type if possible).

This is a part of a FSI solver,  mesh deformation  solver for ALE.  The meshed brick is solid, I have deformation that has to be extrapolated on the fluid part of domain.

**Comment by bangerth** [comment]
I think the approach you use seems correct to me.

We don't have integer vectors because we like to think of our vector classes as elements of a vector space, and integer vectors are not. But you can achieve the same with `std::vector<int>` and using `Utilities::MPI::max/min` and maybe couple of other functions to do a parallel exchange. In your case, what you are really asking is the following: Let's say, you have built some constraints on your local processor. For each constraint, you need to figure out whether it is for a DoF that is locally relevant somewhere else, and if so, send information about that constraint around to those processors where it is needed. You can do that with the approach you have taken, but it is really a more general problem: You have some information that may be of interest to other processors, but you don't know who needs to know about it. I believe that this is what `Utilities::MPI::ConsensusAlgorithm` does, though I have to admit that I have never quite understood what that set of classes do. But I would suggest you take a look at `tests/mpi/compute_index_owner_01.cc` and `tests/base/consensus_algorithm_01.cc`.

**Comment by peterrum** [comment]
If I understand it correctly, the issue is that a process wants to constrain a DoF owned by another process? If that is so `Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmsPayload` can be used for that. I can post a simple example later today.

@bangerth I will try to improve the documentation of the consensus-algorithm infrastructure in the next days. There is even an open issue for that #9363.

> That's a shame because I have the feeling that these classes can be central to a lot of work,

Indeed it is (in the partitioner class and in practically all of my projects).

**Comment by drwells** [comment]
For what its worth I also really wanted to use `LinearAlgebra::distributed::Vector<unsigned char>` to move cell data around in a weird way recently and could not. Having something like this could be really useful.

**Comment by peterrum** [comment]
> For what its worth I also really wanted to use LinearAlgebra::distributed::Vector<unsigned char> to move cell data around in a weird way recently and could not. Having something like this could be really useful.

I regard this as a separate problem. But what is the issue here? Only the instantiation?

**Comment by mwichro** [comment]
@bangerth 
A functionality that I've meant is  container similar to std::vector<constant_size_object> of constant size that is 
1. distributed 
2. has locally owned and ghosted elements that is defined by IndexSet
3. Is able to do compress(VectorOperation::insert) and update_ghost_values()
Using that functionality in Vector I've always managed to  get away without calling MPI functions directly.
@drwells use  reinterpret_cast<float> and use only compress(insert).

**Comment by peterrum** [comment]
The following code could be used to determine all locally-owned constrained indices (not tested, indices are not filled but assumed to be in an index set):

```cpp
#include <deal.II/base/mpi.h>
#include <deal.II/base/mpi_compute_index_owner_internal.h>
#include <deal.II/base/partitioner.h>

using namespace dealii;

IndexSet
compute_locally_contrained_indices(
  const IndexSet &locally_owned_indices,
  const IndexSet &definetly_locally_constrained_indices,
  const MPI_Comm &comm)
{
  const auto locally_constrained_indices_by_ranks = [&]() {
    std::vector<unsigned int> definetly_locally_constrained_indices_owners(
      definetly_locally_constrained_indices.n_elements());
    Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmsPayload
      process(locally_owned_indices,
              definetly_locally_constrained_indices,
              comm,
              definetly_locally_constrained_indices_owners,
              true);

    Utilities::MPI::ConsensusAlgorithms::Selector<
      std::pair<types::global_dof_index, types::global_dof_index>,
      unsigned int>
      consensus_algorithm(process, comm);
    consensus_algorithm.run();
    return process.get_requesters();
  }();

  IndexSet locally_constrained_indices;

  for (const auto &rank_and_indices : locally_constrained_indices_by_ranks)
    locally_constrained_indices.add_indices(rank_and_indices.second);

  return locally_constrained_indices;
}

int
main(int argc, char **argv)
{
  Utilities::MPI::MPI_InitFinalize mpi(argc, argv, 1);

  MPI_Comm comm = MPI_COMM_WORLD;

  // TODO: fill with help of DoFHandler & AffineConstraints
  IndexSet locally_owned_indices;
  IndexSet definetly_locally_constrained_indices;

  const auto locally_constrained_indices =
    compute_locally_contrained_indices(locally_owned_indices,
                                       definetly_locally_constrained_indices,
                                       comm);
}
```

If there are questions, I am happy to give more details. However, I have to leave now. In an essence this (`Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmsPayload` and `Utilities::MPI::ConsensusAlgorithms::Selector`) are the heart of `Partioner`/`LinearAlgebra::distributed::Vector`.

**Comment by bangerth** [comment]
@drwells @mwichro I can see a use for this class, but it's not a *vector* in the mathematical sense -- just an array. It doesn't have to have all of the linear algebra functions. It would be easy enough to build a vector *on top of* such an array, and I would imagine you can easily get what you want by taking the existing vector class, stripping everything numeric out of it, and making it into its own class. It would then simply deal with memory and communication. You could then easily build the existing class on top of it.

**Comment by drwells** [comment]
True - I essentially just want something that can scatter integers in a similar way without having to write it myself (i.e., I don't care about linear algebra, just the communication). This could probably be accomplished with the `Partitioner` - I'll take a look.

**Comment by peterrum** [comment]
BTW. You might also want to check out the class `Utilities::MPI::NoncontiguousPartitioner`. Here it is used in a test:

https://github.com/dealii/dealii/blob/a9d7fa361eea1b8f3276bad9507a8f2c0c2f85e0/tests/base/mpi_noncontiguous_partitioner_01.cc#L43-L54

See also the other tests. The class is a generalized version of the `Utilities::MPI::Partitioner` class (build around CA) able to exchange data on any arrays (fixed size).

**Comment by peterrum** [comment]
@mwichro Would you mind to add a test. I am thinking about adding a function `AffineConstraints::make_consistent_in_parallel()` that would solve your problem directly in the library. What do others thinks about such a function?

**Comment by bangerth** [comment]
Sure -- since we know how to test for consistency, the same algorithm should be applicable to *make* constraints consistent.

**Comment by mwichro** [comment]
@peterrum 
I'll think about that, but it won't be easy to replicate that problem. Moreover, I no longer have access to the big enough cluster to test it on the original problem.
You can also produce an artificial test, just set some random constraints on the relevant DoFs.

**Comment by peterrum** [comment]
> I'll think about that,

A very simple artificial test would be great so that we know that your problem would be fixed.
