### ISSUE TITLE
Add orientation flags to ReferenceCell::child_cell_on_face()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11749]
So we don't forget: https://github.com/dealii/dealii/pull/11734#discussion_r575056062 brings up the issue that `ReferenceCell::child_cell_on_face()` can not simply forward to `GeometryInfo` because it lacks the orientation flags the function in `GeometryInfo` takes. That's a bug.

**Comment by peterrum** [comment]
@marcfehling Could you take a look at this issue. Thanks.

**Comment by bangerth** [comment]
To be clear, the fix consists of adding the arguments that the `GeometryInfo` function has also to the corresponding `ReferenceCell` function.
