### ISSUE TITLE
Drop TaskFlow from 9.3 release branch

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11740]
Mainly for @tjhei : At the developer call just now, we talked about the fact that we're not making progress with replacing TBB by TaskFlow. We would need to import TaskFlow 2.7 for support to start individual tasks (#10990 #10989) but we're stuck with not getting this to run properly on all platforms we support. We also don't have the conversion of `WorkStream` ready (#10691) and we have not started to think about how to support `parallel_for` with TaskFlow.

Other concerns are that TaskFlow's most recent release has already moved to C++17 and that we might be stranded with 2.7 even if we can get that to run.

The conclusion was that we can leave it in the library for now, but that we remove the `bundled/` folder for TaskFlow from the release.

**Comment by tamiko** [comment]
Addendum: As well as the CMake bits configuring taskflow on the release branch.

**Comment by tjhei** [comment]
If we don't support it adequately in 9.3, we should hide/not bundle, I agree. I guess is it okay to wait a bit to see if we make progress until then.

I am a bit frustrated with the current situation. I have been thinking about our options:
1. Modify 2.7 to be a shared library and bundle it. Hopefully that fixes the issues.
2. Switch to the latest 3.x release and as such require c++17. Keep TBB around for c++14.
3. Give up on using taskflow altogether.

Maybe we can bundle a modified 2.7 and require 3.x and as such c++17 if used externally?

**Comment by bangerth** [comment]
To me the question of `parallel_for` is the most relevant one, mostly because we have no plan or idea to address this. It's possible that TaskFlow has facilities for this, but I don't know -- and without addressing this issue, we can not get rid of TBB at this point.

**Comment by tjhei** [comment]
> To me the question of `parallel_for` is the most relevant one

I am not sure I know what problem you refer to. Can you elaborate? Is this just about implementing ``parallel_for``(begin, end, functor, grainsize)``? There is ``TF::for_each()`` that should work, see [1].

[1]: https://taskflow.github.io/taskflow/classtf_1_1FlowBuilder.html#a1a294c4fa23d74b82e581b8cfd33acdf

**Comment by tjhei** [comment]
@bangerth do you mind expanding on parallel_for? I would also be curious what your thoughts on how to proceed are (see my list of options).

**Comment by bangerth** [comment]
I had somehow not realized that there are these `for_each_*()` functions. Yes, that would do. The documentation doesn't give it away, but do you know what the difference between `for_each_static()` and `for_each_dynamic()` is? Also `for_each_guided()`?

TBB has a work-stealing implementation of parallel for that we use. It also can keep track of which elements which core touched, and I believe that we store this information as well so that next time we do, for example, a vector-vector operation, the same core (=cache) gets the same elements again. It's not clear to me whether TaskFlow does either of these two things, nor how important this is in practice. I believe @kronbichler at some point did experiments with the partitioner that made sure stuff ends up on the same core.

**Comment by tjhei** [comment]
> Yes, that would do. The documentation doesn't give it away

I have no idea. Does https://taskflow.github.io/taskflow/ParallelIterations.html#A1PartitionAlgorithms help?

**Comment by tjhei** [comment]
@bangerth any thoughts on how to proceed for 9.3 and beyond?

**Comment by bangerth** [comment]
@tjhei Yes, that helps, thanks! In the end, we probably need to benchmark whether we get the same performance as with the TBB given that the TBB probably leads to better cache-locality.

That said, the key step still unanswered is why the tester fails. The patch in #10990 avoids the issue with `thread_local` variables, but it still fails one of the quicktests. I can't reproduce this on my machines. It would require someone to be able to reproduce this on the actual machine that is used in the tester and figure out why the quicktest doesn't work. I'm ok with moving to TaskFlow once we have understood that issue, but we haven't made progress with it in a while :-( I think you are correct that the rest is relatively straightforward. You have most of a draft of a conversion of `WorkStream`, and I have the conversion of the `Task` class ready to go and tested. The only other places I know of are for `for_each` and something in the matrix-free space. So we're mostly there, but that one quicktest is a mystery that we need to address.

**Comment by peterrum** [comment]
@tjhei @bangerth I guess you are the right persons to know what to do here in the next two weeks?

**Comment by bangerth** [comment]
@tjhei was more adamant about this, so I'll let him make the call.

**Comment by tjhei** [comment]
I will create a PR to the release branch, once created, to remove everything related to taskfkow for the release. We can then decide what to do on master later.

**Comment by peterrum** [comment]
Sounds reasonable to me! Thanks, @tjhei!
