### ISSUE TITLE
Superfluous words in the readme page

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#11752]
In the "nanoflann" section of the deal.ii readme page [[1]](https://www.dealii.org/current/readme.html), the words "scale eigenvalue problems. "  should be abnormally placed.

**Comment by drwells** [comment]
Nice catch - however, this has already been fixed: see #10386.

**Comment by QiaoLei-88** [comment]
Oops, I should check the developer version of readme page before creating an issue.
