### ISSUE TITLE
Problem with SparsityPattern::copy_from

### ISSUE THREAD

**Issue by l-korous** [dealii/dealii#1175]
We are having a problem with this method on Windows (using MSVC). Here is the code including the export of entities (exports are available via the Dropbox link below), DoFHandler and Triangulation(= Agros2D::problem()->calculationMesh()) are exported to "doFHandler" and "triangulation" files respectively:

``` C++
std::ofstream ofsT("C:/util/triangulation");
boost::archive::text_oarchive toT(ofsT);
Agros2D::problem()->calculationMesh().save(toT, 0);

std::ofstream ofsDH("C:/util/doFHandler");
boost::archive::text_oarchive toDH(ofsDH);
doFHandler.save(toDH, 0);

dealii::DynamicSparsityPattern csp(doFHandler.n_dofs());
dealii::DoFTools::make_sparsity_pattern(doFHandler, csp);
parsityPattern.copy_from(csp);
```

Constraints are left out, the issue appears without them as well as with.

Upon executing the last line, I am receiving an error from STL, that vector iterators are incompatible right here:

https://github.com/dealii/dealii/blob/master/source/lac/sparsity_pattern.cc#L511

Dropbox link where the exports are: https://www.dropbox.com/sh/0u8vp0dfob7fmoe/AACjefSz8KGh26xbofkr1moWa?dl=0

**Comment by tjhei** [comment]
Can you post the compiler errors please?

**Comment by l-korous** [comment]
There are no compiler errors, sorry if this was not clear -> there is a runtime error (executing the last line). The error says iterators not compatible, and it comes from vector.h (from STL implementation).

**Comment by tjhei** [comment]
Well, can you post the exact error and stack trace then?

**Comment by l-korous** [comment]
I uploaded error and call stack to Dropbox (same link), I am afraid it will not be of much help though 
(only one call - the one on the top of stack - is inside deal.ii, calls below are from our application, plus the error is not particularly verbose).

You can see the exact line where it fails (it is the #511 I sent a link to).

I sent the exported DoFHandler and Triangulation for potential replication of the issue.

**Comment by tjhei** [comment]
It is not showing inline functions, sadly. I think I understand what is going on though. Can you try the following changes:
```
--- a/include/deal.II/lac/dynamic_sparsity_pattern.h
+++ b/include/deal.II/lac/dynamic_sparsity_pattern.h
@@ -739,9 +739,8 @@ namespace DynamicSparsityPatternIterators
     // current_entry field may not point to a deterministic location
     return (sparsity_pattern == other.sparsity_pattern &&
             current_row == other.current_row &&
-            ((current_entry == other.current_entry)
-             ||
-             (current_row == numbers::invalid_unsigned_int)));
+            ((current_row == numbers::invalid_unsigned_int)
+             || (current_entry == other.current_entry)));
   }
```

**Comment by tjhei** [comment]
If that doesn't work, please inspect the local variables (row, col_num, end_row and their members).

**Comment by tjhei** [comment]
see #1176.

**Comment by l-korous** [comment]
Thank you, this solves the problem.
