### ISSUE TITLE
Does icc 19.1 still work?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11766]
I am trying to revive #11066 and part of that is wanting to see whether there is a workaround for icc 19. So I found myself a system where that compiler exists, but it turns out that I can't even get through the `cmake` run. It reports that C++14 is not supported, and that's because it fails with this little program we check...
```
   #include <memory>
    #include <algorithm>

    // Check the version language macro, but skip MSVC because
    // MSVC reports 199711 even in MSVC 2017.
    #if __cplusplus < 201402L && !defined(_MSC_VER) && !defined(__INTEL_COMPILER)
    #  error "insufficient support for C++14"
    #endif

    int main()
    {
      auto ptr = std::make_unique<int>(42);
      constexpr int max = std::max(0, 1);
      (void) ptr;
      (void) max;
      return 0;
    }
```
and the following error message:
```
$ icpc -std=c++14 -c x.cc
x.cc(12): error: namespace "std" has no member "make_unique"
        auto ptr = std::make_unique<int>(42);
                        ^

x.cc(12): error: type name is not allowed
        auto ptr = std::make_unique<int>(42);
                                    ^

x.cc(13): error: expression must have a constant value
        constexpr int max = std::max(0, 1);
                            ^
x.cc(13): note: cannot call non-constexpr function "std::max(const _Tp &, const _Tp &) [with _Tp=int]" (declared at line 216 of "/usr/include/c++/4.8.5/bits/stl_algobase.h")
        constexpr int max = std::max(0, 1);
                            ^
```

I *think* that one of the problems is that it uses the GCC 4.8 header files.

I suspect that people who use this compiler will use a newer version of the GCC header files, and that that is what is done on the supercomputing sites that still use this compiler. But how does one achieve that? Is there a way for me to redirect icc to use another compiler's header files?

**Comment by masterleinad** [comment]
ICC uses the GCC in your path by default but you can set -gcc-name and -gxx-name to provide another toolchain, see https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compatibility-and-portability/gcc-compatibility-and-interoperability.html.

**Comment by bangerth** [comment]
That does it, thanks @masterleinad !

For my own recollection, this is all it took:
```
export CXX="icpc -cxxlib=/tmp/bangerth/gcc-8.1.0"
export LD_LIBRARY_PATH=/tmp/bangerth/gcc-8.1.0/lib64:$LD_LIBRARY_PATH
```

**Comment by tamiko** [comment]
@bangerth There should be something like
`/opt/intel/compilers_and_libraries_???/linux/bin/intel64/(icc/icpc).cfg` (or where you installed icc) where you could set the `-cxxlib=` flag and the `LD_LIBRARY_PATH` as default arguments for icc/icpc.
