### ISSUE TITLE
Exception in find_active_cell_around_point for parallel runs

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#11773]
The following examples runs with one process, but throws for two processes:

> An error occurred in line <554> of file <dealii/source/grid/grid_tools_dof_handlers.cc> in function
>     std::pair<typename MeshType<dim, spacedim>::active_cell_iterator, dealii::Point<dim> > dealii::GridTools::find_active_cell_around_point(const dealii::Mapping<dim, spacedim>&, const MeshType<dim, spacedim>&, const dealii::Point<spacedim>&, const std::vector<bool>&, double) [with int dim = 3; MeshType = dealii::parallel::shared::Triangulation; int spacedim = 3; typename MeshType<dim, spacedim>::active_cell_iterator = dealii::TriaActiveIterator<dealii::CellAccessor<3, 3> >]
> The violated condition was: 
>     best_cell.first.state() == IteratorState::valid
> Additional information: 
>     The point <-2.63344e+06 -4.3027e+06 3.88956e+06> could not be found
>     inside any of the subcells of a coarse grid cell.

The mesh has no refined cells. When I use allow_artificial_cells = false, it runs. 

```
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/distributed/shared_tria.h>
void test_find_cell()
{
  parallel::shared::Triangulation<3> triangulation (MPI_COMM_WORLD,
                 Triangulation<3>::limit_level_difference_at_vertices, true,
                 parallel::shared::Triangulation<3>::Settings::partition_metis);

  std::ifstream is("mesh_test.vtk");
  GridIn<3> grid_in;
  grid_in.attach_triangulation(triangulation);
  grid_in.read_vtk(is);
  is.close();

  Point<3> p(-2.63344e+06, -4.3027e+06, 3.88956e+06);

  try
  {
    auto cell_point = GridTools::find_active_cell_around_point (triangulation, p);
  }
  catch(std::exception &e)
  {
    std::cout << e.what() << std::endl;
  }
}
```

**Comment by agrayver** [comment]
Ok, so this is a documented behavior: 

>  If, however, the function throws an exception, then that would imply that the point lies outside locally owned active cells.

I probably just need to handle this exception within the code...

**Comment by bangerth** [comment]
Right. But I think that that behavior has recently changed -- see #10535 .

**Comment by bangerth** [comment]
Actually, it has not changed so far, but it will once @luca-heltai 's patch is merged.
