### ISSUE TITLE
Some tests in debug configuration take too long

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#11789]
The CI fails reproducibly with the following test:
```
The following tests FAILED:
	3329 - multigrid/transfer_matrix_free_06.mpirun=15.debug (Timeout)
```

I think it is time to benchmark the execution time of all tests again and trim down some bad offenders.

**Comment by peterrum** [comment]
Still? See also: #11732.

**Comment by tjhei** [comment]
This is most likely due to the fact that is uses more MPI ranks than my CI machines are configured with (12).

**Comment by peterrum** [comment]
Was there a reason for using 15 ranks. If not, we could reduce the number to 12?

**Comment by kronbichler** [comment]
I think we wanted to trigger the NBX consensus algorithm part, https://github.com/dealii/dealii/blob/efbc5408546d878952ce8ae37697323c863be643/include/deal.II/base/mpi_consensus_algorithms.templates.h#L597-L609 - but that's a bad reason. We could also switch that threshold in debug mode to 10 MPI ranks; the algorithms should work and still be reasonably efficient - we're talking something that could take 1e-5 seconds with an Allgather (or whatever the PEX variant does internally) to now take 1e-4 seconds with the unstructured one.

**Comment by peterrum** [comment]
> I think we wanted to trigger the NBX consensus algorithm part,

First, I was wondering if my memory is so bad and I don't remember what I did less than two years ago. But actually the test is older than NBX and debug flag was introduced that this code path is tested by at least one test (which happened to be this one).
