### ISSUE TITLE
FESeries::Fourier/Legendre do not work with non-primitive FEs

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#11791]
It seems that `FESeries::Fourier/Legendre` do not work with non-primitive FEs that derived from `FE_PolyTensor`.

Both Fourier and Legendre called `shape_value`,
https://github.com/dealii/dealii/blob/4cfd36de738c221932d741866d5fe62ba114c476/source/fe/fe_series_fourier.cc#L75
https://github.com/dealii/dealii/blob/4cfd36de738c221932d741866d5fe62ba114c476/source/fe/fe_series_legendre.cc#L84
but the `shape_value` in `FE_PolyTensor` is not implemented.
https://github.com/dealii/dealii/blob/4cfd36de738c221932d741866d5fe62ba114c476/source/fe/fe_poly_tensor.cc#L233

The following MWE will run into assertion failure.
```
#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_series.h>
#include <deal.II/fe/fe_nedelec.h>

#include <deal.II/hp/fe_collection.h>

#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>

#include <deal.II/lac/vector.h>

#include <deal.II/numerics/smoothness_estimator.h>

int main() {
  dealii::hp::FECollection<3> fe_collection;
  fe_collection.push_back(dealii::FE_Nedelec<3>(0));
  fe_collection.push_back(dealii::FE_Nedelec<3>(1));

  dealii::Triangulation<3> tria;
  dealii::GridGenerator::subdivided_hyper_cube(tria, 2);

  dealii::DoFHandler<3> dh(tria);
  dh.distribute_dofs(fe_collection);

  dealii::Vector<double> solution(dh.n_dofs());
  dealii::Vector<float> smoothness(tria.n_active_cells());

  dealii::FESeries::Fourier<3> fourier = dealii::SmoothnessEstimator::Fourier::default_fe_series(fe_collection);
  dealii::SmoothnessEstimator::Fourier::coefficient_decay(fourier, dh, solution, smoothness);

  return 0;
}
```

```
--------------------------------------------------------
An error occurred in line <233> of file </.../source/fe/fe_poly_tensor.cc> in function
    virtual double dealii::FE_PolyTensor<3, 3>::shape_value(const unsigned int, const Point<dim> &) const [dim = 3, spacedim = 3]
The violated condition was: 
    false
Additional information: 
    (none)

Stacktrace:
-----------
#0  2   libdeal_II.g.9.3.0-pre.dylib        0x00000001156d2a24 _ZNK6dealii13FE_PolyTensorILi3ELi3EE11shape_valueEjRKNS_5PointILi3EdEE + 84: 2   libdeal_II.g.9.3.0-pre.dylib        0x00000001156d2a24 _ZNK6dealii13FE_PolyTensorILi3ELi3EE11shape_valueEjRKNS_5PointILi3EdEE 
#1  3   libdeal_II.g.9.3.0-pre.dylib        0x00000001157c402a _ZN6dealii12_GLOBAL__N_19integrateILi3ELi3EEENSt3__17complexIdEERKNS_13FiniteElementIXT_EXT0_EEERKNS_10QuadratureIXT_EEERKNS_6TensorILi1EXT_EdEEj + 266: 3   libdeal_II.g.9.3.0-pre.dylib        0x00000001157c402a _ZN6dealii12_GLOBAL__N_19integrateILi3ELi3EEENSt3__17complexIdEERKNS_13FiniteElementIXT_EXT0_EEERKNS_10QuadratureIXT_EEERKNS_6TensorILi1EXT_EdEEj 
#2  4   libdeal_II.g.9.3.0-pre.dylib        0x00000001157b9302 _ZN6dealii12_GLOBAL__N_116ensure_existenceILi3EEEvRKNSt3__16vectorIjNS2_9allocatorIjEEEERKNS_2hp12FECollectionILi3EXT_EEERKNS9_11QCollectionILi3EEERKNS_5TableILi3ENS_6TensorILi1ELi3EdEEEEjRNS3_INS_10FullMatrixINS2_7complexIdEEEENS4_ISR_EEEE + 498: 4   libdeal_II.g.9.3.0-pre.dylib        0x00000001157b9302 _ZN6dealii12_GLOBAL__N_116ensure_existenceILi3EEEvRKNSt3__16vectorIjNS2_9allocatorIjEEEERKNS_2hp12FECollectionILi3EXT_EEERKNS9_11QCollectionILi3EEERKNS_5TableILi3ENS_6TensorILi1ELi3EdEEEEjRNS3_INS_10FullMatrixINS2_7complexIdEEEENS4_ISR_EEEE 
#3  5   libdeal_II.g.9.3.0-pre.dylib        0x00000001157b8dfe _ZN6dealii8FESeries7FourierILi3ELi3EE9calculateIdEEvRKNS_6VectorIT_EEjRNS_5TableILi3ENSt3__17complexIdEEEE + 142: 5   libdeal_II.g.9.3.0-pre.dylib        0x00000001157b8dfe _ZN6dealii8FESeries7FourierILi3ELi3EE9calculateIdEEvRKNS_6VectorIT_EEjRNS_5TableILi3ENSt3__17complexIdEEEE 
#4  6   libdeal_II.g.9.3.0-pre.dylib        0x0000000114ac4dae _ZN6dealii19SmoothnessEstimator7Fourier17coefficient_decayILi3ELi3ENS_6VectorIdEEEEvRNS_8FESeries7FourierIXT_EXT0_EEERKNS_10DoFHandlerIXT_EXT0_EEERKT1_RNS3_IfEENS_11VectorTools8NormTypeEdb + 542: 6   libdeal_II.g.9.3.0-pre.dylib        0x0000000114ac4dae _ZN6dealii19SmoothnessEstimator7Fourier17coefficient_decayILi3ELi3ENS_6VectorIdEEEEvRNS_8FESeries7FourierIXT_EXT0_EEERKNS_10DoFHandlerIXT_EXT0_EEERKT1_RNS3_IfEENS_11VectorTools8NormTypeEdb 
#5  7   feseries-test                       0x0000000108a54310 main + 336: 7   feseries-test                       0x0000000108a54310 main 
#6  8   libdyld.dylib                       0x00007fff72da5cc9 start + 1: 8   libdyld.dylib                       0x00007fff72da5cc9 start 
```

Maybe we should call `shape_value_component` instead of `shape_value`?

**Comment by peterrum** [comment]
The documentation states:

> A class to calculate expansion of a scalar FE field into Fourier series on a reference element.

So everything is fine. We can think about generalizing the class (or adding a parameter) to support vectorial FEs, although I don't know if it make sense in the context of RT or Nedele.

**Comment by adamqc** [comment]
I'm sorry, I did not noticed that the documentation already states the usage of these classes. But I still want to know whether there is any possibility to extend `FESeries` to non-primitive FEs. Let's see what Marc says. @marcfehling

**Comment by marcfehling** [comment]
Since Legendre and Fourier series expansions work with scalar base functions, i.e., Legendre polynomials and sinusoids, respectively, these classes are designed to work on scalar finite elements.

If working with vector-valued finite elements, you could expand each component of your vector-valued finite element solutions into an individual series expansion. This doesn't work right now, but we could provide an optional `component` argument to the `FESeries` class constructor, and exchange all `shape_value` calls by `shape_value_component`. The `SmoothnessEstimator` functions could grab the registered `component` from the corresponding `FESeries` object, so that they know on which component they need to work on.

If you want to have decision indicators, you could create indicators for each individual component with a separate `FESeries` object. You could combine this set of indicators to one by, e.g., taking the maximum of them for each cell.

Different question: What exactly is the application you have in mind? Maybe you can elaborate on your use case? It may make sense to get decision indicators for just one of the components, instead of all of them. For example as in solving the Stokes problem in [step-22](https://www.dealii.org/current/doxygen/deal.II/step_22.html), only the pressure solution will be taken into account to calculate refinement indicators.

**Comment by adamqc** [comment]
I would like to solve Maxwell's equation using Nedelec element. I am not quite familiar with the underlying theory of FESeries, could you please provide some suggestions?

**Comment by marcfehling** [comment]
I don't have any experience with non-primitive finite elements, especially in terms of error and smoothness estimation. So maybe there are other users and developers who could provide a second opinion.

So far to my understanding, and from what I tried to explain in my previous comment, I would suggest the following: You can treat each component of your finite element solution as an individual scalar field, and apply the current workflow on each of them. You will end up with multiple decision indicators, that you would need to reduce to one (for example, by taking the maximum among all indicators on each cell).

This, however, does not work out of the box, as you pointed out. You would need to introduce a component parameter for your `FESeries` object as well as the `SmoothnessEstimator` functions. I can imagine that this would be useful for other users of the library as well. Would you be interested in writing a patch to make it work?

PS: There may exist decision strategies for hp-adaptation that are specifically made for non-primitive finite elements, but I am not aware of any.

**Comment by adamqc** [comment]
Thank you very much. I will create a PR soon.
