### ISSUE TITLE
Make KINSOL interfaces work for newer SUNDIALS versions

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11829]
I woke up today and wanted to write a SUNDIALS KINSOL tutorial program. So I spent a few hours on a couple of pull requests, but in the end found that the current KINSOL interfaces only work for SUNDIALS 3.x whereas SUNDIALS is already at version 5.7 right now. Problem is that the SUNDIALS interfaces have changed substantially, and to be quite honest I can't for the life of me not figure out how KINSOL is now supposed to be driven.

The code we have right now makes use of KINSOL's feature that we can attach a custom linear solver for the Jacobian matrix. That makes sense in the FEM context since we know how to solve linearized problems. Specifically, our interfaces have a function `t_kinsol_solve_jacobian` and corresponding "setup" function, and we then do this:
```
        auto KIN_mem        = static_cast<KINMem>(kinsol_mem);
        KIN_mem->kin_lsolve = t_kinsol_solve_jacobian<VectorType>;
        if (setup_jacobian)
          KIN_mem->kin_lsetup = t_kinsol_setup_jacobian<VectorType>;
```
But KINSOL 5.7 no longer exposes these function pointers on the lhs of the assignments -- in fact, the whole `KINMem` structure no longer exists. I believe that there are setter functions one needs to use now, but I can't figure out how this is supposed to work. The question is what these setter functions are and what their arguments relate to. In the `kinsol_ls.h` (ls=linear solve) file, the only exposed functions are `KINSetPreconditioner`, but I think that what that does is only set a preconditioner for one of the built-in matrices. More promising would be to call `KINSetLinearSolver` which allows setting an `SUNLinearSolver` object. The corresponding functions are then in `sundials/sundials_linear_solver.h`, but I'm having a very hard time navigating that file and the corresponding section in the manual: The fundamental difficulty I have is that the only documented ways to use these functions is to create a `SUNLinearSolver` object that corresponds to one of the pre-defined solvers (of which there are many, both direct and iterative), but not a custom solver. The examples that come with SUNDIALS also don't appear to cover that case...

Are there examples for building linear solver objects that use a custom solver?

@luca-heltai @sebproell Any insight?

**Comment by sebproell** [comment]
> Problem is that the SUNDIALS interfaces have changed substantially, and to be quite honest I can't for the life of me not figure out how KINSOL is now supposed to be driven.

It took me a while to understand the way SUNDIALS modularizes certain aspects. In the end, I think I understood it and think I can help here. Disclaimer: I just opened the KINSOL guide for the first time and mostly rely on my SUNDIALS knowledge;)

> in fact, the whole KINMem structure no longer exists

It is no longer exported, we need to use a void* to this structure for all calls like `KINSetLinearSolver`.

> More promising would be to call KINSetLinearSolver which allows setting an SUNLinearSolver object
> Are there examples for building linear solver objects that use a custom solver?

I think you identified that correctly. SUNDIALS defines an interface for (non)linear solvers, matrices and vectors. I already wrote a [wrapper for a SUNLinearSolver](https://github.com/dealii/dealii/blob/master/include/deal.II/sundials/sunlinsol_wrapper.h), which is extracted from ARKode as of #11724. My hope is that you can either take it as is or need to extend its interface only slightly to use it for KINSOL. Its design needs to be improved -- it isn't really a C++ class but rather a collection of free functions -- but it should work for now.

As for examples: [Here](https://github.com/dealii/dealii/blob/master/source/sundials/arkode.cc#L652) I create a wrapper from a `LinearSolveFunction` (type defined in sunlinsol_wrapper.h). I don't know of any examples int the SUNDIALS docs.

>  but I'm having a very hard time navigating that file and the corresponding section in the manual

In case you haven't noticed: the sections in the manual on N_Vector, SUNMatrix and SUNLinearSolver are the same for all packages like IDA, ARKODE, KINSOL. They describe the general interface and are completely decoupled from your actual problem. It took me a while to realize that e.g. `SUNLinSolSetATimes` in the SUNLinearSolver is **not** meant as a way to directly pass the Jacobian for a given problem. Instead, KINSOL itself will use this function to interface with the solver. The problem-specific Jacobian operator is passed to KINSOL with `KINSetJacTimesVecFn`

**Comment by bangerth** [comment]
Ah yes, that was really helpful. Thanks, @sebproell , for the links to the ARKode wrappers!

**Comment by bangerth** [comment]
Hm, the disappointments continue :-( In the existing interfaces, we allow to attach two functions for setting up a linear system and actually solving it. We do this using the following two signatures:
```
    std::function<int(const VectorType &current_u, const VectorType &current_f)>   setup_jacobian;

    std::function<int(const VectorType &ycur,
                      const VectorType &fcur,
                      const VectorType &rhs,
                      VectorType &      dst)>      solve_jacobian_system;
```
We can call these two functions because the callbacks from KINSOL look like this:
```
    int t_kinsol_setup_jacobian(KINMem kinsol_mem);

    int t_kinsol_solve_jacobian(KINMem    kinsol_mem,
                            N_Vector  x,
                            N_Vector  b,
                            realtype *sJpnorm,
                            realtype *sFdotJp);
```
and because the `kinsol_mem` object allows us to extract certain other vectors. For example, in the setup function, we do
```
      copy(*src_ycur, kinsol_mem->kin_uu);
      copy(*src_fcur, kinsol_mem->kin_fval);
```
to get the two arguments of the `setup_jacobian` function.

But, now, in SUNDIALS 5.x, the SUNDIALS callbacks look like this:
```
    int t_kinsol_setup_jacobian(SUNLinearSolver LS, SUNMatrix /*ignored*/);

    int t_kinsol_solve_jacobian(SUNLinearSolver LS,
                            SUNMatrix /*ignored*/,
                            N_Vector x,
                            N_Vector b,
                            realtype tol);
```
So, for example in the case of the setup function, all we get is the `LS` argument (of type `SUNLinearSolver`), and we need to extract from that the `current_u` and `current_f` objects. But I can't find out how to do that -- the `SUNLinearSolver` interface doesn't appear to have functions to extract that, or at least I can't find any. More to the point, there are no examples in the SUNDIALS documentation that set the `ops->setup` or `ops->solve` functions in the `SUNLinearSolver` class :-(

**Comment by sebproell** [comment]
The trick is, that SUNDIALS strongly separates the question how to create the matrix (or how to apply it as an operator) vs. what to do with the matrix. Let's look at the matrix-free operator version, I find that one simpler. The first problem, creating the matrix, is handled by `KINSetJacTimesVecFn` which takes a function of type `int (*KINLsJacTimesVecFn)(N Vector v, N Vector Jv,
N Vector u, booleantype *new u,
void *user data)`. These are the arguments you are looking for, I think? Internally, KINSOL will now possibly enhance this function, e.g. wrap it in another function to apply a pre-factor and convert it to a modified `int (*ATimesFn)(void *A_data, N_Vector v, N_Vector z)` function which is able to evaluate the correct Jacobian-times-vector product (not how this function lost all problem-specific information, it is just an abstraction of the matrix-vector product). This modified function is passed to the linear solver module with the `SetATimes()` function. Our custom linear solver wrapper stores that here: https://github.com/dealii/dealii/blob/master/source/sundials/sunlinsol_wrapper.cc#L150 and, when the actual solve happens, creates an operator from it here: https://github.com/dealii/dealii/blob/master/source/sundials/sunlinsol_wrapper.cc#L116 which is finally returned to a user-specified function that does the actual solve.

Btw. Don't be mislead by the prefix `arkode_` in the wrapper, that's a left-over and needs to be cleaned up. Should work for KINSOL as well.

**Comment by bangerth** [comment]
@sebproell Thanks for your insights on how this works with ARKode!

It's not quite what I want for KINSOL, though :-( The thing is that I don't ever want to build a matrix explicitly, nor do I want to be able to do matrix-vector products with it. The old interface did exactly what I wanted: It requires me to write a function that solves a linear system with the Jacobian for a given rhs, and then return the solution. *How* it does that didn't matter to KINSOL at the time -- maybe I built the actual matrix and solved with it, or maybe not. Who knows, who cares. That's what this code did: https://github.com/dealii/dealii/blob/master/source/sundials/kinsol.cc#L113-L141 It completely left the choice of how to do the linear solve up to the user: The matrix, if it even existed, was stored in user space, so was any preconditioner, and the solver function could be as complicated as the user wanted.

That's what I want to re-create. In other words, I don't want to set `KINLsJacTimesVecFn` because I don't know whether I will even have a Jacobian matrix that one could multiply with, and even if I did, I have no intention of offering this operation to KINSOL because I don't want to use their internal iterative linear solvers anyway.

What confounds me is that the functionality I'm looking for existed in the previous SUNDIALS versions, but appears to have disappeared. But surely that's something that people still want. I just can't seem to figure out how it works :-)

**Comment by luca-heltai** [comment]
Well, that functionality existed, but was very well hidden inside the code... :) I think it is possible to recreate it, but it will take a bit of working around. The new interface is cleaner, as it instantiate always the same objects. A SUNLinearSolver, and a SUNMatrix. Providing our own SUNLinearSolver (that takes a fake SUNMatrix) should be enough, provided that we attach the correct behaviour to the various function pointers. This is exactly what was done previously, but without the new interfaces.

**Comment by sebproell** [comment]
@bangerth I tried what you want to achieve with ARKode in my initial attempts to update the wrapper. I couldn't come up with a way to do it, which doesn't misuse SUNDIALS' functions (you can do a lot of "custom things" with `void*` :laughing: ). All my tries failed at some point, since ARKode does a lot of internal checking and doesn't let you do those things. I agree with @luca-heltai that the new interface is cleaner and introduces some general abstractions with a documented contract that are reusable throughout the whole SUNDIALS package.

> In other words, I don't want to set KINLsJacTimesVecFn because I don't know whether I will even have a Jacobian matrix

I don't get this. Sure, it doesn't have to be an actual matrix but don't you need to have the concept of a derivative if you want to solve with a Newton method? It could be a finite difference approximation or a constant scaling of all vector entries. But in the end you can always say how to apply it to a vector, or not?

**Comment by bangerth** [comment]
On 3/3/21 10:05 AM, Sebastian Pröll wrote:
> I don't get this. Sure, it doesn't have to be an actual matrix but don't
> you need to have the concept of a derivative if you want to solve with a
> Newton method? It could be a finite difference approximation or a constant
> scaling of all vector entries. But in the end you can always say how to
> apply it to a vector, or not?

Maybe, maybe not. What if I only know the action of the inverse of the 
Jacobian? (Say, if I want to find the solution of A^-1 x-b=0 and only know A 
but not A^-1. That's a contrived example, but one could come up with others.) 
In the end, that's enough for what KINSOL really wants.

The point is that the previous, quite useful interface we had to KINSOL only 
required the user to provide a function that solves a linear system with the 
Jacobian, and I would like to keep it that way. I don't see a reason why 
KINSOL might ever want to multiply with the Jacobian matrix because I don't 
intend to use the KINSOL iterative solvers. So I don't want to come up with a 
way to ask the user to provide this functionality.

**Comment by bangerth** [comment]
I posed this question on the SUNDIALS forum, but it hasn't been approved for their mailing list yet at this point:

All:
I'm trying to update the KINSOL 3.x interfaces in deal.II to what's now in SUNDIALS 5.7, but find myself thoroughly stuck

Fundamentally, I would like to model the workflow we had with KINSOL 3.x, namely:
- There was a "setup Jacobian" function pointer in the KINSOL data structure
  that would alert us that now would be a good time to build a Jacobian
  and store it, in whatever form, in user code. It gets the current iterate
  as an argument.
- There was a "solve with your Jacobian" function pointer that takes (in
  some form) a rhs 'b' and returns the solution 'x' of the system
    J x = b

We had implemented the first of these operations here:
https://github.com/dealii/dealii/blob/master/source/sundials/kinsol.cc#L90-L107
The code lacks comments But what it does is copy get pointers to N_Vectors for the current 'y' and 'f(y)' vectors out of the KINMem objects, copy these
input vectors into user data structures, and call the user setup function (line 105). The "do the solve" implementation is a few lines below.


I can't seem to figure out what this workflow in 5.7 corresponds to, specifically for the first of these functions. There is still the
  sun_linear_solver->ops->setup
function pointer that I can set for a linear solver object that I can then attach to KINSOL. But it's not clear how I need to implement it, and I'm afraid I also can't find a place in the examples where that would be done: I don't think there is an example program that sets 'ops->setup' or 'ops->solve' to anything other than NULL.

So here is my current attempt:
https://github.com/bangerth/dealii/blob/kinsol-2/source/sundials/kinsol.cc#L154-L176
The question is how I'm supposed to get the 'y' and 'f(y)' vectors out of the 'SUNLinearSolver' object that the setup function gets.

Any suggestions where to look for an example?

Best & many thanks in advance!
 Wolfgang

**Comment by bangerth** [comment]
In other words, my current attempt is here: 
https://github.com/bangerth/dealii/blob/kinsol-2/source/sundials/kinsol.cc#L154-L176

**Comment by bangerth** [comment]
Forum post now here: http://sundials.2283335.n4.nabble.com/Setting-up-custom-solvers-in-KINSOL-td4655970.html

**Comment by bangerth** [comment]
The main part of what was necessary to do has been fixed in #11908 . The steps that are left are the following:

- [ ] The KINSOL interfaces copy vectors around. This can be done more efficiently with the help of `N_Vector`s, see #11395 
- [ ] The signature of the `solve_jacobian_system` callback has changed. The current interface still uses the old interface but can't provide all of the information necessary with newer SUNDIALS versions. It does, however, provide a solver tolerance. We should either change the signature of `solve_jacobian_system`, or introduce a new callback that matches what new SUNDIALS versions provide.
- [ ] The new KINSOL interfaces are enabled for SUNDIALS 5.0 and later, but I was told that the change actually happened in SUNDIALS 4.1 already. We should adjust the preprocessor guards accordingly.

**Comment by bangerth** [comment]
Related to #5027.

**Comment by bangerth** [comment]
Closing in favor of #12066.
