### ISSUE TITLE
Use different syntax when declaring std::function objects

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11826]
Reading through #11759, I realize again how ugly and non-intuitive the function syntax is in C++: `std::function<T(const X &)>`. That `T(const X&)` would indicate a function that takes a `const X&` as argument and returns a `T` is just not obvious unless you happen to know.

But we could write this different: C++11 allows us to write
```
  std::function<auto (const X&) -> T>
```
now. I'm not sure whether that's easier to understand -- maybe marginally. Probably in this more complicated context:
```
    using cell_iterator_function = std::function<const Function<spacedim> *(
      const typename Triangulation<dim, spacedim>::cell_iterator &)>;
```
which would become
```
    using cell_iterator_function = std::function<auto (
      const typename Triangulation<dim, spacedim>::cell_iterator &) -> const Function<spacedim> *>;
```

Anyway, opinions?

**Comment by masterleinad** [comment]
I find the current syntax easier to understanding and more concise. It's not an issue I would worry about anyway (and the current syntax has been around for a longer time anyway; it's just the way `std::function` has always worked).

**Comment by bangerth** [comment]
Seems like everyone is happy with the current way -- let's close this then.

I'm curious where the C++ community is going to go in the coming years. I wished the committee had introduced a new keyword `deffun` or something like this so that what we currently awkwardly write as
```
  auto f(int) -> int;
```
could have been written as
```
  deffun f(int) -> int;
```
instead. The `auto` just doesn't make any sense here...
