### ISSUE TITLE
Inconsistent FE class hierarchy (simplex, pyramid, wedge)

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11864]
The class hierarchy currently looks like this:
```
FE_Poly +-> FE_Pyramid +-> FEPyramidP 
        |              |
        |              +-> FEPyamidDGP
        |
        +-> FE_SimplexPoly +-> FESimplexP 
        |                  |
        |                  +-> FESimplexDGP
        |
        +-> FE_SimplexPBubbles
        |
        +-> FE_Wedge +-> FE_WedgeP
                     |
                     +-> FE_WedgeDGP 
```

The question here is if we should have one base class for all simplex FEs (with which name) and should we rename `FE_Pyramid` -> `FE_PyramidPoly` and `FE_Wedge` -> `FE_WedgePoly` consistently to `FE_SimplexPoly`?

**Comment by bangerth** [comment]
I'm always in favor of consistent naming conventions.

**Comment by peterrum** [comment]
Any suggestions here?

**Comment by jppelteret** [comment]
I've got no opinion on the single simplex base class idea, but `FE_Pyramid` -> `FE_PyramidPoly` and `FE_Wedge` -> `FE_WedgePoly` seems like a good idea to me. Not sure what to make of `FE_SimplexPBubbles` though. I guess that's where having a simplex base class might be useful to categorise it with the other simplex types.

**Comment by peterrum** [comment]
I would like to make this change before the release. Are there any further opinions/suggestions?
