### ISSUE TITLE
Test sharedtria/hp_choose_p_over_h.mpirun=2.debug fails

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11902]
Due to #11868, `sharedtria/hp_choose_p_over_h.mpirun=2.debug` fails. The reason is that in:
https://github.com/dealii/dealii/blob/30e53a956acf8bce3c2a0b70f15e4fae81a148e8/source/hp/refinement.cc#L660-L680
`GridTools::exchange_cell_data_to_ghosts()` is called even for `p:s:T` without artificial cells. However, `GridTools::exchange_cell_data_to_ghosts()` might deadlock for `p:s:T`, which was the reason for introducing the assert, and this test passed only by chance. 

We need a fall-back solution here. I am not sure what the right approach is. But I could image that we switch for more data structures in `DoFHandler` to `LA::d::V` (which would make such "ghost updates" potentially easier).

**Comment by marcfehling** [comment]
I just stumbled over this failing test while running my test suite :)

I introduced that ghost exchange back in #10309, and I agree that this choice was not the right one for shared Triangulations as I had the distributed one in mind.

`LA:d:V` would be the right choice, or rather its potential distributed array counterpart that we discussed in #11875. I'll think of a solution tomorrow.
