### ISSUE TITLE
Jupyter notebook in step-62 not working

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11949]
@dangars Any ideas why?

**Comment by dangars** [comment]
How is it not working?

step-62 is in a broken state. The PR #11310 fixes step-62, but I have to wait until #11276 is in master.

I think that the I should provide the option to run step-62 without the jupyter notebook. Not everybody has jupyter installed.

**Comment by dangars** [comment]
I submitted the PR #11971 to give the option to use step-62 without the jupyter notebook.

**Comment by dangars** [comment]
@peterrum #11971 and #11310 have been merged, therefore I think that we can close this issue.

I checked the jupyter notebook of step62 and it works correctly.
