### ISSUE TITLE
Optimize Utilities::MPI::broadcast()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11955]
#11940 introduces an MPI broadcast function, which packs up the argument, determines the size, sends around the size, on all processors allocates a sufficiently large buffer, and then in a second `MPI_Bcast` sends the actual data.

This could be optimized: If the argument is a built-in type or fixed-size array thereof, we don't need to call `pack()` but can just send the data and the receiving end will know what the buffer size needs to be because it can just stack-allocate the output object.

@bergbauer -- FYI.

**Comment by fAndreuzzi** [comment]
Hi @bangerth, I would like to work on this starter project. What do you recommend to use in order to detect if the template type `T` is built-in? I found `is_fundamental` ([reference](https://en.cppreference.com/w/cpp/types/is_fundamental)) but I do not know whether it is the optimal choice.

**Comment by masterleinad** [comment]
I think it makes sense to add the optimization for MPI data types. For everything else, you would likely need to serialize or create a custom MPI data type to get the padding right.

In https://github.com/dealii/dealii/blob/9d8c8e932003df38d23d251a4ee660613eb78775/include/deal.II/base/mpi.templates.h#L46-L174, you can see that we already have functionality to convert C++ data types to the corresponding MPI data types.

**Comment by fAndreuzzi** [comment]
Thank you @masterleinad, this is exactly what I was looking for. Am I allowed to use [concept](https://en.cppreference.com/w/cpp/language/constraints) from C++20?

I would like to define a `concept` like the following:
```cpp
template<typename T>
      concept BuiltIn_MPI_DataType = requires(T a) {
        { mpi_type_id(a) };
      };
```

and then provide two versions of `broadcast`, where the one meant to be used with built-in types is defined in the following way:
```cpp
template <BuiltIn_MPI_DataType T>
    T
    broadcast(const MPI_Comm    &comm,
              const T           &object_to_send,
              const unsigned int root_process)
    {
```

**Comment by peterrum** [comment]
> Am I allowed to use concept from C++20?

Unfortunately not. We are still at C++14.

**Comment by bangerth** [comment]
Ah, that would be nice if we could already use C++20 :-) Fortunately, MPI's list of data types is fixed, and you could use something like this to find out whether a type in question is in a specific list (encoded in the form of a `std::tuple<...list of MPI data types...>`): https://stackoverflow.com/questions/25958259/how-do-i-find-out-if-a-tuple-contains-a-type

A small amount of `std::enable_if` will then allow you to write the specialization you are looking for.
