### ISSUE TITLE
False error for METIS in CMake

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#11982]
When I configure deal.II with these options

`-DDEAL_II_WITH_METIS=ON -DMETIS_INCLUDE_DIRS=/path/to/metis/include -DMETIS_LIBRARIES=/path/to/metis/lib/libmetis.so`

I get this error:

> Could not find the metis library!
> 
>   Could not find a sufficiently modern metis installation: Version 5.x
>   required!

The error comes from 

https://github.com/dealii/dealii/blob/648732e9a05f7f3085c823563c2fe25892f3b552/cmake/configure/configure_2_metis.cmake#L28-L37

Removing this check 'fixes' the problem and library compiles. 

Obvisouly, I have the METIS library and it is new, but it does not get detected.

FYI here is excerpt from the metis.h:

> /*------------------------------------------------------------------------
> * Constant definitions 
> *-------------------------------------------------------------------------*/
> /* Metis's version number */
> #define METIS_VER_MAJOR         5
> #define METIS_VER_MINOR         1
> #define METIS_VER_SUBMINOR      0

**Comment by drwells** [comment]
I'm not sure we really support configuring libraries this way - `FindMETIS.cmake` expects to find the include directories and libraries itself starting from `METIS_DIR`. Is there a situation where you cannot provide `METIS_DIR` and instead have to provide these arguments directly?

**Comment by marcfehling** [comment]
I just looked in the [Readme](https://www.dealii.org/current/readme.html#optional-software) on how to use the deal.II interface to METIS. Could you try to pass `-DMETIS_DIR=/path/to/metis` to your cmake call instead?

**Comment by jppelteret** [comment]
> Could you try to pass -DMETIS_DIR=/path/to/metis to your cmake call instead?

Indeed, this is the way that we do things in both [spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py#L494-L497) and [candi](https://github.com/dealii/candi/blob/dealii-9.2/deal.II-toolchain/packages/dealii.package#L92-L98).

**Comment by agrayver** [comment]
I do use -DMETIS_DIR normally, but now I git a case (on a cluster) where include and lib directories are not under the same root directory, thus I have to specify these paths explicitly. I am also fine to 'fix' it by removing the check myself...

**Comment by drwells** [comment]
I figured that might be the case - we have poor support for handling dependencies where headers and libraries are not installed under the same root directory.

Could you try passing `-DMETIS_VERSION_MAJOR=5` to cmake? If that works then its preferrable to deleting checks.

**Comment by tamiko** [comment]
With the current development version the way how to reliable override our `find*` modules is to configure as follows:
```
-DDEAL_II_WITH_METIS=ON
-DFEATURE_METIS_EXTERNAL_FOUND=true
-DMETIS_INCLUDE_DIRS=/path/to/metis/include
-DMETIS_LIBRARIES=/path/to/metis/lib/libmetis.so
```
This will sidestep the call to `feature_metis_find_external` entirely.
