### ISSUE TITLE
Rewrite FEValues/FiniteElement/Mapping interfaces

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1198]
Fixing #1152, I realized again that I do not understand (and have never really understood) the way FEValues, FiniteElement and Mapping classes interact. Looking at how all of this works I find that much isn't well documented, some of the interfaces could be improved, etc.

This issue is simply a catch-all for all of the patches I'm doing to improve the situation.

**Comment by guidokanschat** [comment]
I do not believe we should invest heavily in `FEValues` anymore. It is inherently memory bound and does not support tensor product integration like it is used in `MatrixFree`. Let's rather focus on replacing it and while we are doing so, separate `Mapping` in a way consistent with manifold descriptions.

**Comment by bangerth** [comment]
Fortunately, ours is a project big enough so that different people can work on different parts :-) (I'm not implementing new functionality, just cleaning up interfaces.)

**Comment by tamiko** [comment]
I have no idea what a "Meta" issue should be. But now it is one.

**Comment by bangerth** [comment]
Meta-Issue: An issue that is a placeholder for a sequence of other ones. E.g., an issue that is referenced from every pull request or issue related to getting the next release out of the door.

**Comment by bangerth** [comment]
This is as far as I intend to take it for now.
