### ISSUE TITLE
Migrate issues from google code?

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#12]
There is a script that seems to do a decent job in migrating all issues from google code:

https://github.com/arthur-debert/google-code-issues-migrator

what do people think about this?

L.

**Comment by davydden** [comment]
probably we should have migrated issues somewhere, there are comments in the code like

> // Alas, this scheme does not work as evidenced by the disaster of bug #51,
>      // see http://code.google.com/p/dealii/issues/detail?id=51 and the
>      // reversion of one attempt that implements this in r29662.

but the links are dead now... 😢

**Comment by bangerth** [comment]
Nothing we can do about that now. The same is true for sourceforge-related links. The same will happen in a few years when we move on from github.

**Comment by davydden** [comment]
sure, i guess the takeaway message is not to use any links within the code and try to make sure that comments are self-explanatory and it's not required to visit some links to understand it.
