### ISSUE TITLE
AlignedVector does not run constructor on its elements

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12007]
`AlignedVector<T>` carefully makes sure that if the type `T` is nontrivial, that destructors are run when the object is deallocated. For example, it has this piece of code:
```
AlignedVector<T>::clear()
{
  if (data_begin != nullptr)
    {
      if (std::is_trivial<T>::value == false)
        while (data_end != data_begin)
          (--data_end)->~T();

      free(data_begin);
    }
  data_begin    = nullptr;
  data_end      = nullptr;
  allocated_end = nullptr;
}
```
Similar code is located in `resize_fast()` and the two versions of `resize()`

But it does not actually make sure that *con*structors are run. All memory allocation is routed through the `reserve()` function, which currently looks like this:
```
  const size_type allocated_size = allocated_end - data_begin;
  if (size_alloc > allocated_size)
    {
      // if we continuously increase the size of the vector, we might be
      // reallocating a lot of times. therefore, try to increase the size more
      // aggressively
      size_type new_size = size_alloc;
      if (size_alloc < (2 * allocated_size))
        new_size = 2 * allocated_size;

      const size_type size_actual_allocate = new_size * sizeof(T);

      // allocate and align along 64-byte boundaries (this is enough for all
      // levels of vectorization currently supported by deal.II)
      T *new_data;
      Utilities::System::posix_memalign(reinterpret_cast<void **>(&new_data),
                                        64,
                                        size_actual_allocate);

      // copy data in case there was some content before and release the old
      // memory with the function corresponding to the one used for allocating
      std::swap(data_begin, new_data);
      data_end      = data_begin + old_size;
      allocated_end = data_begin + new_size;
      if (data_end != data_begin)
        {
          dealii::internal::AlignedVectorMove<T>(new_data,
                                                 new_data + old_size,
                                                 data_begin);
          free(new_data);
        }
      else
        Assert(new_data == nullptr, ExcInternalError());
    }
```
First, there is the issue that here that the name `AlignedVectorMove` does not convey that the source elements are actually destroyed (they are), but regardless, the function here only calls this move constructor on the *old* objects, not the ones that are created if one makes the array larger. 

(The function never shrinks the memory region. So it does not have to call destructors anywhere.)

**Comment by kronbichler** [comment]
The `reserve` function does not know what kind of exemplar of the class we are using (we want to support both classes `T` which have no empty constructor and those with no copy constructor), so we cannot call the constructor there. But we do call constructors in `resize` or `resize_fast`, see https://github.com/dealii/dealii/blob/09b93afd2f490bb6c517fe4e20f1e02108837905/include/deal.II/base/aligned_vector.h#L814-L818 and https://github.com/dealii/dealii/blob/09b93afd2f490bb6c517fe4e20f1e02108837905/include/deal.II/base/aligned_vector.h#L839-L842 and https://github.com/dealii/dealii/blob/09b93afd2f490bb6c517fe4e20f1e02108837905/include/deal.II/base/aligned_vector.h#L863-L867 and the `push_back` function https://github.com/dealii/dealii/blob/09b93afd2f490bb6c517fe4e20f1e02108837905/include/deal.II/base/aligned_vector.h#L943-L944
I think we cover all cases for what we want to do with the `AlignedVector` class, but I'd be happy to learn in case there are scenarios where we do things wrong or work with uninitialized memory.

**Comment by bangerth** [comment]
I think you are right. I had not looked into the `resize()` functions and failed to take into account that `reserve()` does not actually change the number of elements stored, just how much memory is allocated.
