### ISSUE TITLE
Allow sharing of data across MPI processes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12008]
@tjhei and I were talking about sharing large data chunks across MPI processes that live on the same machine and, consequently, can use shmem. We were specifically interested in making this possible with `InterpolatedTensorProductFunction` and friends. For ASPECT, we will probably have some quite large data tables for initial conditions that require this kind of thing -- think 100s of MB or even a few GB; small enough that they can fit into memory, but large enough that it will be quite inefficient if the data is replicated 64 times on a single machine.

Here's how I think we should address this:
* Underlying all relevant classes is `AlignedVector`. If we could get that class to share its data with others, that would already be a big step forward. My plan is to give this class a function `share_data_across_communicator(MPI_Comm)` in which one creates an `AlignedVector` object on one processor and then calls this function collectively on a sub-communicator of processes that can participate via shared memory. The data is then moved into a shmem arena that can be accessed by all other processes.
* The next level up is `TableBase` that under the hood uses `AlignedVector`. It will get the same function and just pass it on to its underlying aligned vector plus exchange minimal amount of information for the size of the table.
* `InterpolatedTensorProductGridData` currently copies its `Table` of data from the calling site, but it would actually make sense to give this class a separate constructor that *moves* the data. In most cases, one is happy to get rid of the table with which this class was constructed, because it is used only in this one context. Once the class is able to move the data, it should also be able to deal with data that lives in a shmem arena.

**Comment by peterrum** [comment]
The description sounds reasonable. This implies that the user needs to know that the user knows which process has rank 0 in the subcommunicator. 

Regarding the subcommunicator, you might want to take a look at: https://github.com/dealii/dealii/pull/11158#discussion_r549487431

You might also want to have a look at the implementation in `LA:d:V`: 

https://github.com/dealii/dealii/blob/09b93afd2f490bb6c517fe4e20f1e02108837905/include/deal.II/lac/la_parallel_vector.templates.h#L135-L246

I guess in your use case `alloc_shared_noncontig=true` has to be set to `alloc_shared_noncontig=false`, which might limit the maximum size of the array.

**Comment by tjhei** [comment]
This makes sense to me and is roughly what @bangerth and I talked about before. My thought was to leave the MPI logic outside of AlignedVector and only give a new reinit()/constructor to AlignedVector that points to an existing piece of memory.

We need to be careful when modifying AlignedVector and Table to not introduce performance regressions, as they are used in performance critical areas.

**Comment by tjhei** [comment]
> I guess in your use case `alloc_shared_noncontig=true` has to be set to `alloc_shared_noncontig=false`, which might limit the maximum size of the array.

I don't think that is true, as we are only allocating memory on rank 0 (of the node). Or am I misunderstanding what the parameter does?

**Comment by bangerth** [comment]
On 4/3/21 10:07 AM, Timo Heister wrote:
> This makes sense to me and is roughly what @bangerth 
> <https://github.com/bangerth> and I talked about before. My thought was to
>  leave the MPI logic outside of AlignedVector and only give a new 
> reinit()/constructor to AlignedVector that points to an existing piece of
> memory.

I had thought about this: In that case, you'd have to pass a pointer to memory
externally owned to AlignedVector, which would then no longer be the owner. 
You'd have to route this pointer through Table as well. That seemed quite 
complicated, and furthermore you'd essentially expose the internals of both 
classes and restrict how they store data. It seemed like a better choice to 
just hide these details, but I still have to figure out how one allocates 
shared memory via MPI. Let me take a look at how that works and go from there.

**Comment by peterrum** [comment]
> I don't think that is true, as we are only allocating memory on rank 0 (of the node). Or am I misunderstanding what the parameter does?

This is true. I just wanted to point out that you might be able to allocate more memory with `alloc_shared_noncontig=true`.

> but I still have to figure out how one allocates
shared memory via MPI. Let me take a look at how that works and go from there.

It is in the code snippet above ;)

**Comment by tjhei** [comment]
> It seemed like a better choice to just hide these details

I don't mind, but you will need to either have a custom unique_ptr deleter or store some additional state inside the AlignedVector or not? I did not like those options (and then gave up :man_shrugging: ).

**Comment by peterrum** [comment]
> I don't mind, but you will need to either have a custom unique_ptr

I think this will be the follow-up of #12009, won't it?

**Comment by tjhei** [comment]
> I think this will be the follow-up of #12009, won't it?

Yes, but a custom deleter would become part of the type. Curious how bangerth will solve this. Maybe always using a custom deleter that does a noop for the default case?

**Comment by kronbichler** [comment]
I think this looks like a good step and useful in a number of context - I agree with the comments by @peterrum that we have already code that does similar things in the distributed vector class. I would also be happy to see everything managed inside the class as @bangerth suggests, let's see if this works out.

**Comment by bangerth** [comment]
On 4/4/21 9:44 AM, Timo Heister wrote:
> I don't mind, but you will need to either have a custom unique_ptr deleter or 
> store some additional state inside the AlignedVector or not? I did not like 
> those options (and then gave up 🤷‍♂️ ).

We've used this approach elsewhere: You use void(*)(T*) as the type of a 
custom deleter, and then attach a lambda to it. That lambda can do whatever 
you darn well please it to do, including calling 'free' (which is what I do in 
#12009) or do something more complicated with MPI :-)

**Comment by tjhei** [comment]
Except that you can not capture a value like the MPI_Win and convert to a function pointer. Maybe you know a way around that? Watching curiously. 😉

**Comment by bangerth** [comment]
Yes, the solution is to make the type of the deleter not `void (*)(T*)` but `std::function<void (T*)>`. Then you can use any lambda, including ones that capture. I have not proceeded to that point in #12009 but may have to change things as necessary. Stay tuned to this very channel to learn more ;-)

**Comment by tjhei** [comment]
> Yes, the solution is to make the type of the deleter not `void (*)(T*)` but `std::function<void (T*)>`

But that increases the size of the unique_ptr significantly* and everybody pays for that even if they don't care about this MPI stuff.

*: 40 instead of 8 bytes, https://godbolt.org/z/rYr11aPKs

**Comment by bangerth** [comment]
Hm, that's an interesting observation. Is that something we are concerned about? 8 vs 40 bytes is a difference of 3 `double`s. Looking through where `AlignedVector` is used, I would assume that we generally use this class in contexts where we store far more than that, and that the extra 32 bytes would not matter very much. But I may also just not be seeing the contexts you have mind.

**Comment by drwells** [comment]
One place where we want to consider the size of `AlignedVector` is in `Vector`, since a lot of code still creates `std::vector<Vector<double>>` or similar to handle multi-component FEs.

**Comment by tjhei** [comment]
> Is that something we are concerned about?

We do use AlignedVector and Table for relatively small data inside matrix free routines. I let @kronbichler comment on if the memory and/or additional cycles are a problem. I am hesitant to comment without measuring.

**Comment by bangerth** [comment]
Here is another thought about this whole complex: I'm putting all of this into `AlignedVector` because `Table` builds on `AlignedVector`. But what I'm really interested in is `Table`, not `AlignedVector`. Does anyone remember why `Table` uses `AlignedVector`? I think I could alleviate most of your concerns if I let `Table` just put its stuff into a regular (non-aligned) `std::vector`. What do you all think about that?

**Comment by kronbichler** [comment]
> I think I could alleviate most of your concerns if I let Table just put its stuff into a regular (non-aligned) std::vector. What do you all think about that?

That is a bad idea, because then we can't use the tables any more which get `VectorizedArray` types. This would break many codes, and we would lose first-touch memory page allocation (for those you use threads), and maybe a few more downsides I can't remember.

> We do use AlignedVector and Table for relatively small data inside matrix free routines. I let @kronbichler comment on if the memory and/or additional cycles are a problem. I am hesitant to comment without measuring.

I don't think they should be critical, as long as the access into an aligned vector does not get more expensive in terms of instructions. I don't have the time right now to investigate, but I would see the risk as low. If anything, we need to pass along a few more raw pointers in internal interfaces rather than the aligned vector, but that should be it.

**Comment by bangerth** [comment]
Oh, right, `Table` is also the base class of `FullMatrix` :-(

Nothing about how the data is stored in the "normal" case is going to change. I'm just adding the possibility of moving data into shared space.

**Comment by tjhei** [comment]
I would store the MPI_Win directly instead of the much heavier std:: function if you want to continue this way. My original suggestion to keep the MPI stuff out of a low-level class doesn't look that bad in comparison now...

**Comment by bangerth** [comment]
@tjhei There are two pieces of information that need to persist beyond the call of this function: (i) the `MPI_Win` data structure, (ii) the `shmem_group_communicator`. Right now, I put them into the capture set of a lambda function and so it ends up being stored somewhere on the heap with the pointer to the lambda stored in `AlignedVector`.

Here are the alternatives I can see:
* User creates these objects, passes them to this function, and hangs on to them until after the the `AlignedVector` object is destroyed. I don't see that as a viable option because the creation of these functions is difficult and requires specific knowledge of what precisely the function does -- for example, how much memory it actually wants to allocate.
* The function creates these objects these objects itself, like it does now, but then returns a `std::function` object that encapsulates the destruction of the `MPI_Win` and `MPI_Comm` objects. The user then hangs on to this `std::function` object until destruction time of the `AlignedVector` object and then calls this "cleanup function" themselves. This has the advantage that we don't need to increase the size of `AlignedVector` by 32 bytes as discussed above, but it encourages memory leaks (e.g., if a user does not actually catch the returned object) and encourages sequencing problems where the user executes the cleanup function at the end of the block where the `replicate_across_communicator()` function was called, rather than after the lifetime of the `AlignedVector` object. I see this option as "viable", but hardly pretty.

Of course, there is always the option of just not having this function in `AlignedVector`, but then we will also not have it in `Table` and not in `InterpolatedTensorProductData` and not in ASPECT in a way that would allow us to share large data tables with relative ease.

Opinions?

**Comment by tjhei** [comment]
> (ii) the `shmem_group_communicator`

Does the communicator need to persist until the shmem is released?

> Here are the alternatives I can see:

I am not super happy about either of those options.

> Of course, there is always the option of just not having this function in `AlignedVector`, but then we will also not have it in `Table` and not in `InterpolatedTensorProductData` and not in ASPECT in a way that would allow us to share large data tables with relative ease.

One other option is to use something other than ``Table`` in ``InterpolatedTensorProductData``. The only thing we use is array access, or not? We could use anything really (``FullMatrix`` or a simple new class for shmem storage). To me, ``AlignedVector`` is a very low-level class with a specific use case where MPI stuff doesn't really fit into.

**Comment by bangerth** [comment]
On 4/9/21 1:40 PM, Timo Heister wrote:
> (ii) the |shmem_group_communicator|
> 
> Does the communicator need to persist until the shmem is released?

I don't actually know. The MPI spec does not say one way or the other. I erred 
on the side of safety: Since we need to hang on to the MPI_Win, I thought I 
might as well hang on to the MPI_Comm as well.

**Comment by bangerth** [comment]
I could roll my own underlying container for `InterpolatedTensorProductFunction` and would have to re-use it for `InterpolatedUniformGridData`. I can't use `FullMatrix` because (i) I actually need an `n`-dimensional table, (ii) `FullMatrix` is derived from `Table` which uses `AlignedVector` :-) In other words, I basically have to copy the `Table` class.

Before I do this, let me try to understand what the main "point de resistance" actually is:
* Is it that people are opposed to putting anything MPI/shared memory-related into `AlignedVector` for software-design reasons? If that is so, how would this concern be addressed if I introduced a `SharableAlignedVector` class that does exactly the same as `AlignedVector` except that it allows for shared memory support? That would seem conceptually muddled because if it is software-design-related wrong to do for `AlignedVector`, it would be unclear why it could be right for another class that is all but equivalent except for its name.
* Is it because of the extra 32 bytes? I could imagine a scheme by which one uses a `bool` template parameter (or some other scheme) so that by default `AlignedVector` uses no extra memory for the deleter, and this version is then used `Vector`. In the non-default case, we eat the 32 extra bytes and in return allow for parallel shmem sharing; this version would be used in `Table` where, presumably, data is large enough that we don't care very much about the extra 32 bytes. 

Would appreciate feedback of where people's pain point lies and how we can address this best.

**Comment by tjhei** [comment]
> Would appreciate feedback of where people's pain point lies and how we can address this best.

I think I have voiced my concerns about performance loud enough. As @kronbichler seems to indicate that this is unlikely a problem, I don't mind if we proceed with @bangerth 's proposed solution.
