### ISSUE TITLE
Actually implement PETScWrappers::Vector::import.

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#12001]
I am going to try to find time to finish the conversion of the PETSc vector wrapper to use the common interface, but minimally we do need this function (especially if we deprecate `set`, like I did in #10398.

We need to either un-deprecate `set` or finish this by 9.3.

**Comment by peterrum** [comment]
> We need to either un-deprecate set or finish this by 9.3.

"un-deprecate set" sounds like the way to go if you don't have time to work on `PETScWrappers::Vector::import()`.
