### ISSUE TITLE
FEPointEvaluation does not support `FE_DGQHermite`

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#12014]
In the current code for the point evaluation, we currently construct a 1D polynomial here: https://github.com/dealii/dealii/blob/357d079338e5526a7fe8d07896934104873aa0e0/include/deal.II/fe/fe_point_evaluation.h#L581-L582
However, this hardcodes the type of `FE_DGQ` or `FE_Q`, and misses other tensor product finite elements. We should find a way to handle this properly before the release - the difficulty is that `FE_Poly` hides the polynomial class.

**Comment by peterrum** [comment]
@kronbichler  This would be nice, but not now ;)

**Comment by kronbichler** [comment]
Some action is high priority, because it gives wrong results, no warning, no other sign. I will try to look at a simple solution, maybe by just switching to the slow part.
