### ISSUE TITLE
On reading grid file in step-5

### ISSUE THREAD

**Issue by tyc1998** [dealii/dealii#12023]
When I was running step-5, there was an error reading InP format. I checked based on the saved information. First, the read permission of the InP file is guaranteed. Secondly, I think there should be no problem with the format of the file. So I hope to get your help to solve this problem.

The error information is as follows:

An error occurred in line <785> of file </home/wjs/dealii-9.2.0/source/grid/grid_ in.cc > in function

void dealii::GridIn<dim, spacedim>::read_ ucd(std::istream&, bool) [with int dim = 2; int spacedim = 2; std::istream = std::basic_ istream<char>]

The violated condition was:

in

Additional information:

An input/output error has occurred. There are a number of reasons why this may be happening, both for reading and writing operations.

Best regards!

**Comment by bangerth** [comment]
I think you have to show us the input file you are using, and the code you are using to read it with. Otherwise we can only speculate.

**Comment by tyc1998** [comment]
> I think you have to show us the input file you are using, and the code you are using to read it with. Otherwise we can only speculate.

The code is step-5 in deali9.2.0.
The command I enter is very simple. First, I enter the path of step-5, and then I enter it in turn
cmake ..
make
make run

**Comment by tyc1998** [comment]
> I think you have to show us the input file you are using, and the code you are using to read it with. Otherwise we can only speculate.

The code is step-5 in deali9.2.0.
The command I enter is very simple. First, I enter the path of step-5, and then I enter it in turn
mkdir build
cd build
cmake ..
make
make run

**Comment by bangerth** [comment]
So is the `circle_grid.inp` file available in this directory?

**Comment by tyc1998** [comment]
> So is the `circle_grid.inp` file available in this directory?

I have checked according to the error message. The InP file exists and has read permission

**Comment by tyc1998** [comment]
Problem has been solved, thanks!

**Comment by bangerth** [comment]
What was the problem in the end?

**Comment by tyc1998** [comment]
> What was the problem in the end?

I created a new build folder, and the InP file is in the folder one level above build. My bad!
