### ISSUE TITLE
Use N_Vector wrappers in KINSOL interfaces

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12066]
The only thing that is left for #11829 is that we should be using `N_Vector` wrappers for our own vector types, rather than copy data back and forth. #11395 is the way to go with this, and @sebproell might have more insight into how this could work.

Regardless, since it works for now, let us close #11829 and keep the `N_Vector` discussion here, unattached to a particular release milestone.

**Comment by peterrum** [comment]
This is done. Closing.

**Comment by bangerth** [comment]
Uh no, it's not done :-)

**Comment by sebproell** [comment]
fyi: I am currently working on this since the `copy` style does not actually work for me when using KINSOL with vectors created by `MatrixFree` (proably due to different layout?).

**Comment by bangerth** [comment]
@sebproell Nice! You know about @luca-heltai 's patch that we ended up reverting, right?

**Comment by sebproell** [comment]
@bangerth I heard that, yes. I just made the change and all tests pass. Let me check the old change again.

**Comment by sebproell** [comment]
And here is a problem we had with step 77: https://github.com/dealii/dealii/issues/12594

I'll check if this works.
