### ISSUE TITLE
Quick way to calculate scalar solution gradient for postprocessing

### ISSUE THREAD

**Issue by RichardYCJ** [dealii/dealii#12092]
Does the library have a function to quickly calculate the gradient of a given scalar? (what i mean scalar here is a `Vector<double>` defined on the scalar FE) Theoretically speaking, it is easy to achieve this once you got the shape function gradient at each support vertex (cell dofs). Considering the scalar:

<a href="https://www.codecogs.com/eqnedit.php?latex=u_h&space;=&space;\sum_{i=0}^{N-1}&space;U_i&space;\varphi_i" target="_blank"><img src="https://latex.codecogs.com/png.latex?u_h&space;=&space;\sum_{i=0}^{N-1}&space;U_i&space;\varphi_i" title="u_h = \sum_{i=0}^{N-1} U_i \varphi_i" /></a>

and since the parameter is fixed on given position, the gradient of the scalar is simple:
![](https://latex.codecogs.com/png.latex?\nabla&space;u_h&space;=&space;\sum_{i=0}^{N-1}&space;U_i&space;\nabla\varphi_i)

The implementation is also simple, if we have `get_shape_grad(cell)` which could give the shape function gradient at each cell dof, then the assemble of gradient would be:
```C++
std::vector gradient(dim, Vector<double>(tria.n_active_cells()));
for (auto & cell : dof_handler.active_cell_iterators()){
  if (cell->is_locally_owned()){
    fe_values.reinit(cell);
    std::vector cell_grad(dim, Vector<double>(fe_values.dofs_per_cell));
    auto shape_grad = get_shape_grad(cell);
    for (unsigned i : fe_values.dof_indices())
      for (unsigned j : fe_values.dof_indices())
        for (unsigned int d =0; d<dim; ++dim)
          cell_grad[d](i) += val[j] * shape_grad(j, i)(d); // d-th component of j-th shape function gradient at i-th dof
    cell->distribute_local_to_global(cell_grad, gradient);
  }
}
```

However, I didn't find any functions like this in `FEValues` and `DofHandler`. The only way I could think is to get `shape_gradient` in `FE` and map it from unit cell to real cell.

Another possible way is using `VectorTools::point_gradient` but is too expensive if I want the whole domain gradient.

**Comment by masterleinad** [comment]
What should the entries of the output Vector represent? Note that the solution vector you are normally dealing with is U_i, only for nodal elements these represent also the values in the support points. In the end, you need to know in which points you want to evaluate the gradient.

**Comment by RichardYCJ** [comment]
> What should the entries of the output Vector represent? Note that the solution vector you are normally dealing with is U_i, only for nodal elements these represent also the values in the support points. In the end, you need to know in which points you want to evaluate the gradient.

The output would be a `std::vector` containing gradient components for each dimension, say **du/dx** and **du/dy** if in 2D.

It's true that the solution only equals exactly to the finite element interpolant on support points. However, u_h is still the interpolant of u and specially if you use a high-order FE, say bi-linear Lagrange, then the solution would be in H^1 space, meaning the interpolant gradient would also be continuous and its difference to real gradient could be controlled by finite element error.

**Comment by jppelteret** [comment]
Hi @RichardYCJ,

This functionality does not directly exist in deal.II, but it really isn't difficult to implement. The basic strategy would be to use a second DoF handler that uses, say, a `FESystem<dim>(FE_Q<dim>(degree), dim)` to discretise the (continuous approximation to the) solution gradient. You could then solve the least-squares fit of the solution gradient computed from your primary problem onto the continuous FE space. This basically means computing a mass matrix using the second DoF Handler and then a normal RHS vector that you'd get from any "source" term, but with the source term itself being the solution gradients that come from the primary problem. You can use [this method](https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-convert-triangulation-cell-iterators-to-dofhandler-cell-iterators) to traverse the cells for both DoFHandlers in lock step. In the end, you'd have a new "solution_gradient_vector" that can be visualised using DataOut, or you can point-wise extract values if you wish.

> However, u_h is still close to u within the domain and specially if you use a high-order FE, say bi-linear Lagrange, then the solution would be in H^1 space, meaning the interpolant gradient would also be continuous

No, I don't think that this is correct. The finite element would have to be C^1 continuous for the gradient to be continuous. We do not have such elements yet.

To conclude, I should mention that the google group/forum is a more appropriate place for these types of questions. There they're appreciated by a wider audience, so anyone who might have a similar query could easily access the knowledge and conversation at some later stage. Perhaps next time you'd be willing to post your questions there :-)

**Comment by bangerth** [comment]
On 4/24/21 11:40 AM, RichardYCJ wrote:
> It's true that the solution only equals exactly to the finite element 
> interpolant on support points. However, u_h is still the interpolant of u and 
> specially if you use a high-order FE, say bi-linear Lagrange, then the 
> solution would be in H^1 space, meaning the interpolant gradient would also be 
> continuous

That's not true: Even for higher order elements, the solution is only 
piecewise smooth and the gradient is not continuous. In particular, that means 
that you will not be able to take the gradient of the discrete function at 
node points at the interfaces between cells (on vertices, on edges, and on faces).

**Comment by RichardYCJ** [comment]
Thanks for the comments! @jppelteret @bangerth are right. The interpolant gradient would be piecewise continuous and discontinuous while crossing cells even using higher order Lagrange FE, unless C^1 continuous FE, say **Argyris element**, is considered. I'm not sure if it has definition on quad cells. :rofl:

We are now trying to use `VectorTools::point_gradient` within our desired region, though it will cost some time.

**Comment by RichardYCJ** [comment]
> To conclude, I should mention that the google group/forum is a more appropriate place for these types of questions. There they're appreciated by a wider audience, so anyone who might have a similar query could easily access the knowledge and conversation at some later stage. Perhaps next time you'd be willing to post your questions there :-)

Sure, good to know there's a better place to discuss stuffs like this. This issue can be closed.

**Comment by RichardYCJ** [comment]
> The basic strategy would be to use a second DoF handler that uses, say, a `FESystem<dim>(FE_Q<dim>(degree), dim)` to discretise the (continuous approximation to the) solution gradient. You could then solve the least-squares fit of the solution gradient computed from your primary problem onto the continuous FE space. This basically means computing a mass matrix using the second DoF Handler and then a normal RHS vector that you'd get from any "source" term, but with the source term itself being the solution gradients that come from the primary problem. You can use [this method](https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-convert-triangulation-cell-iterators-to-dofhandler-cell-iterators) to traverse the cells for both DoFHandlers in lock step. In the end, you'd have a new "solution_gradient_vector" that can be visualised using DataOut, or you can point-wise extract values if you wish.

Finally figure out what does this mean...

If we treat the gradient definition equation as a new vector-valued problem, it can then be solved by vector FEM. The only thing we need is the **vector FE shape function** (defined on new vector FE) value and **interpolated scalar gradient** (defined on old FE) at quadrature point. Luckily, the quad number only depends on `quadrature formula` and could be the same via different FEs. We could use the method mentioned above to traverse two dof_handler via one iteration. The only thing is to solve a mass Matrix.

And since the vector FE is C^0, our solved solution, which is the gradient, is also C^0 on calculation domain. Thanks to  @jppelteret, this issue can be really closed. :heavy_check_mark:
