### ISSUE TITLE
Redo step-35 pictures

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#12114]
We should do this in time for the release. The pictures use rainbow which makes the vorticity plots hard to read - additionally, the plots are low-res and different sizes.

**Comment by peterrum** [comment]
@drwells  I would suggest to adjust the milestone here. These are just colorful pictures...

**Comment by drwells** [comment]
@brynbarker emailed out the pictures to someone with web site access.

If we are just updating the pictures there really isn't any need to change something in the repo itself so I will close this issue. In retrospect, I should have been doing that all along.
