### ISSUE TITLE
Check some failing tests for generalized interpolation

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#12189]
Recent changes in find_active_cell_around_point have introduced failure in some tests. #11276

The output have been updated, but the tests should be investigated more: some of the output seems to suggest either that the tests are not robust, or that there is a bug in the current implementation that only shows up in corner cases.

We need to investigate this ASAP.

**Comment by kronbichler** [comment]
Here is a list of failures we need to address: https://cdash.43-1.org/viewTest.php?onlydelta&buildid=1046

**Comment by kronbichler** [comment]
For the record, in #12221 I removed some higher order Raviart-Thomas and Nedelec elements, so those changes might be worth cross-checking.

**Comment by kronbichler** [comment]
Do we still have anything to do for the release? I think we addressed the testers and can postpone the closer look at say FERaviartThomas(2).

**Comment by luca-heltai** [comment]
I think we are good with this.
