### ISSUE TITLE
KINSOL not working

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#12223]
#12216 introduced a bug that only shows on some versions of sundials. 

I'm working on it now.

**Comment by luca-heltai** [comment]
The new interface actually uncovered a bug in our existing implementation. According to the documentation of Sundials `SUNDenseLinearSolver`:

> This routine will perform consistency checks to ensure that it is called with consistent N_Vector and SUNMatrix implementations. These are currently limited to the SUNMATRIX_DENSE matrix type and the NVECTOR_SERIAL, NVECTOR_OPENMP, and NVECTOR_PTHREADS vector types. As additional compatible matrix and vector implementations are added to SUNDIALS, these will be included within this compatibility check.

This means that our current implementation won't work in parallel. I'm preparing a fix.

**Comment by luca-heltai** [comment]
From bad to worse... another serious bug found while looking for a solution to our problem with KINSOL. 

Our KINSOL interface claims it works also using `picard` iteration and `fixed_point` iteration. These are not tested, and with the current master, they simply segfault.

**Comment by luca-heltai** [comment]
This is the current situation:

- fixed_point iteration is not working
- picard iteration is not working
- newton and line_search are not working if you do not set the jacobian function

tests kinsol_01 and kinsol_02 were working (third case in the list above) because they were only tested for the serial case. Unfortunately, our N_Vector implementation is NOT compatible with N_Vector serial.

I attempted (unsuccessfully) to limit the cases in which we do not provide a jacobian to the fixed point iteration, but this now segfaults, and I cannot find a version of the library where this does not happen. Somehow it has been broken for a long time (always?) and was never tested. 

picard iteration, with jacobian supported, should work, but it does not

For the release, I'd suggest we remove support for non-working stuff. I'll open a PR later tonight, where I remove all unsupported methods.

**Comment by nicola-giuliani** [comment]
@luca-heltai  I have added a KINSOL version of kinsol_01 that should use fixed_point iterations, with only the SUNDIALS native functions and types it works. unwrap vector triggers an assertion.
