### ISSUE TITLE
Test opencascade/iges_write not robust under roundoff errors

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1222]
With clang-3.6.2 the test opencascade/iges_write fails because a formerly exact zero value "0." becomes "almost zero": 6.216106406E-18 [1]. This leads to a line break in the output format.

[1] http://cdash.kyomu.43-1.org/testDetails.php?test=17603943&build=10490

**Comment by bangerth** [comment]
Ugh :-( And the output is produced by a function in OpenCascade over which we have no control, right?

**Comment by tamiko** [comment]
> Ugh :-( And the output is produced by a function in OpenCascade over
> which we have no control, right?

Yes. Line 222 in opencascade/utilities.cc:

  Standard_Boolean OK = ICW.Write (filename.c_str());

**Comment by bangerth** [comment]
Damn :-(

Can we control what we give that function? Like set everything that's less than 1e-12 times the largest element to zero?
