### ISSUE TITLE
GCC 11.1 compilation issues

### ISSUE THREAD

**Issue by mathsen** [dealii/dealii#12244]
Hello,

I recently updated to GCC 11.1 and with this deal.ii compilation fails - basically because the implicitly created Tensor<> default move assignment operator gets implicitly deleted:

```
dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >& dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >::operator=(dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >&&)' is implicitly deleted because the default definition would be ill-formed:

[...]

include/deal.II/base/tensor.h:92:7: error: cannot bind non-const lvalue reference of type 'Sacado::Rad::ADvar<double>&' to an rvalue of type 'Sacado::Rad::ADvar<double>'
```

I have attached a longer extract of my build log here in this post.
This was not a problem even with GCC 10.3 - and at least as I see it the default constructor should not be implicitly deleted, but I suspect that we get this problem because of the overloaded assignment operators (which are already existent).

I could handle the issue by implementing some default construct / move operators by hand. With these changes deal.ii compiles and runs fine on GCC 11.1. You can see the changes in [this branch of my fork](https://github.com/mathsen/dealii/commit/8577359e44ae8cf02eea24f54358161c612f9d0f).

Some remarks: the for loop in the copy constructors is necessary because std::copy is not constexpr.
I deleted the ICC workaround because it isn't necessary anymore if we have to use the same workaround for GCC, too and implement them manually.

Maybe anybody has another idea how to cope with this issue?
Otherwise maybe the changes should be merged?

Greetings

Mathias

[log.txt](https://github.com/dealii/dealii/files/6503666/log.txt)

**Comment by masterleinad** [comment]
Just open a pull request. :slightly_smiling_face:

**Comment by mathsen** [comment]
Done, [issue is here](https://github.com/dealii/dealii/pull/12246)
