### ISSUE TITLE
Compilation bug using Windows Visual Studio 2017

### ISSUE THREAD

**Issue by nicola-giuliani** [dealii/dealii#12263]
I have just installed the latest version of the library on a windows machine using Visual Studio 2017, MSVC 19.16.27034.0. The installation was smooth but I can't compile the test grid_tools_03. The problem lies in the volume function that has changed since release 9.2 (which was working fine).

The error is the following

grid_tools.h(185): error C2059: syntax error: 'template'

**Comment by bangerth** [comment]
For reference, this is related to #11604.

**Comment by nicola-giuliani** [comment]
With the patch since _MSC_VER is not defined the error changes
error 2039: 'dealii::get_default_linear_mapping': is not a member of 'dealii::ReferenceCell'

**Comment by nicola-giuliani** [comment]
const dealii::Mapping<dim, spacedim>& mapping =
   (dealii::ReferenceCells::get_hypercube<dim>().template get_default_linear_mapping<dim, spacedim>());
   dealii::Triangulation<dim, spacedim> tria;
   dealii::GridGenerator::hyper_cube(tria);
   const double volume1 = dealii::GridTools::volume<dim, spacedim>(tria, mapping); //OK
   const double volume2 = dealii::GridTools::volume<dim, spacedim>(tria); //ERROR

**Comment by nicola-giuliani** [comment]
This is done with the original implementation of volume.

**Comment by marcfehling** [comment]
@DaneilSun found a solution to the problem in #13593.

The patch just covers a small part of the library. I guess we need to adjust all other occurrences of `.template get_default_linear_mapping` accordingly.

**Comment by drwells** [comment]
This is now fixed - further changes are tracked in #13596.
