### ISSUE TITLE
Interface updates to SUNDIALS/IDA

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12267]
I come late to #12200 but would like to see if we could address two things before the 9.3 release that have interface implications:

* As mentioned in https://github.com/dealii/dealii/pull/12200/files?w=1#r636262915, #12200 introduces a function similar to the one I introduced in #12031, but with a different name. I would like to make sure that we use the same name `solve_with_jacobian()` or similar in both places. 

* #12200 also introduces the `get_n_iterations()` and `set_n_iterations()` functions, along with the `n_iterations` member variable. This is only used to funnel information from the IDA wrapper to the outside world (IDA never gets to see this information, and doesn't care):
```
 if (solver.solve_jacobian_system_up_to_tolerance)
￼        {
￼          int n_iter = 0;
￼
￼          err = solver.solve_jacobian_system_up_to_tolerance(*src_b,
￼                                                             *dst_x,
￼                                                             n_iter,
￼                                                             tol);
￼          solver.set_n_iterations(n_iter > 0 ? n_iter : 1);
￼        }
```
But it seems funny to do it this way: There is a potentially much larger amount of information one might want to report from one's `solve_jacobian_system_up_to_tolerance()` function to the surrounding code base. And there is a good way to do this: Attach whatever function (possibly a lambda) to that signal and store whatever you want in variables that you can access from your own function. There is no need to route this information from the user function to `t_dae_solve_jacobian_system` to the `IDA` class and back out via `get_n_iterations()`. In other words, I would like to get rid of the `get_n_iterations()` and `set_n_iterations()` functions, along with the `n_iterations` member variable and the third argument to `solve_jacobian_system_up_to_tolerance`.

@luca-heltai @nicola-giuliani Opinions? Both should be relatively easy to address.

**Comment by luca-heltai** [comment]
Actually, IDA does use this information in its LinearSolver interface. We have not yet come to an agreement on how to address that, and if we want to address that, so I agree we should remove these functions for now, since we are not using them.

Should we use `solve_jacobian_system_up_to_tolerance`  or `solve_with_jacobian`?

I find `solve_with_jacobian` too close to `solve_jacobian_system`. In a month from now, we'd be asking ourselves why one should use one or the other, and I think the name `solve_with_jacobian` is not descriptive of what the function does...

**Comment by bangerth** [comment]
I had in mind of removing the `solve_jacobian_system` at some point because that is an old SUNDIALS interface. At least in the KINSOL case, `solve_jacobian_system` takes a number of arguments that newer SUNDIALS versions simply don't provide. So I think of `solve_jacobian_system` as deprecated (and documented it that way), and as a consequence the similarity in name did not bother me too much.

(Separately, I didn't particular like `solve_jacobian_system` because "Jacobian system" is not a technical term in itself and so we are not actually solving *such a system*, nor are we actually solving *for* some kind of system. We are solving a linear system *with the matrix being the Jacobian*.)

**Comment by luca-heltai** [comment]
Shouldn't we deprecate the old ones then, or better, deprecate old sundials versions altogether, and in the next release simply remove support for sundials <5.0.0?

**Comment by bangerth** [comment]
Yes to all. Indeed that's what I did with the KINSOL interfaces:
```
    /**
     * @deprecated Versions of SUNDIALS after 4.0 no longer provide all
     *   of the information necessary for this callback (see below). Use the
     *   `solve_with_jacobian` callback described below.
     *
     * A function object that users may supply and that is intended to solve
     * a linear system with the Jacobian matrix. This function will be called by
     * KINSOL (possibly several times) after setup_jacobian() has been called at
     * least once. KINSOL tries to do its best to call setup_jacobian() the
     * minimum number of times. If convergence can be achieved without updating
     * the Jacobian, then KINSOL does not call setup_jacobian() again. If, on
     * the contrary, internal KINSOL convergence tests fail, then KINSOL calls
     * setup_jacobian() again with updated vectors and coefficients so that
     * successive calls to solve_jacobian_systems() lead to better convergence
     * in the Newton process.
     *
     * If you do not specify a `solve_jacobian_system` or `solve_with_jacobian`
     * function, then only a fixed point iteration strategy can be used. Notice
     * that this may not converge, or may converge very slowly.
     *
     * A call to this function should store in `dst` the result of $J^{-1}$
     * applied to `rhs`, i.e., `J*dst = rhs`. It is the user's responsibility
     * to set up proper solvers and preconditioners inside this function
     * (or in the `setup_jacobian` callback above).
     *
     *
     * Arguments to the function are:
     *
     * @param[in] ycur The current $y$ vector for the current KINSOL
     * internal step. In the documentation above, this $y$ vector is generally
     * denoted by $u$.
     * @param[in] fcur The current value of the implicit right-hand side at
     * `ycur`, $f_I (t_n, ypred)$.
     * @param[in] rhs The system right hand side to solve for
     * @param[out] dst The solution of $J^{-1} * src$
     *
     * This function should return:
     * - 0: Success
     * - >0: Recoverable error (KINSOL will try to change its internal
     * parameters and attempt a new solution step)
     * - <0: Unrecoverable error the computation will be aborted and an
     * assertion will be thrown.
     *
     * @warning Starting with SUNDIALS 4.1, SUNDIALS no longer provides the
     *   `ycur` and `fcur` variables -- only `rhs` is provided and `dst`
     *   needs to be returned. The first two arguments will therefore be
     *   empty vectors in that case. In practice, that means that one
     *   can no longer compute a Jacobian matrix for the current iterate
     *   within this function. Rather, this has to happen inside the
     *   `setup_jacobian` function above that receives this information.
     *   If it is important that the Jacobian corresponds to the *current*
     *   iterate (rather than a re-used Jacobian matrix that had been
     *   computed in a previous iteration and that therefore corresponds
     *   to a *previous* iterate), then you will also have to set the
     *   AdditionalData::maximum_newton_step variable to one, indicating
     *   that the Jacobian should be re-computed in every iteration.
     */
    DEAL_II_DEPRECATED_EARLY
    std::function<int(const VectorType &ycur,
                      const VectorType &fcur,
                      const VectorType &rhs,
                      VectorType &      dst)>
      solve_jacobian_system;
```

**Comment by luca-heltai** [comment]
Let's DEAL_II_DEPRECATED_EARLY `solve_jacobian_system` in IDA, then, and rename `solve_jacobian_system_up_to_tolerance` to `solve_with_jacobian`, with the same note you have here.

**Comment by bangerth** [comment]
OK. Would you be willing to do it? I have a seminar to give in 38 minutes and then need to head to the airport...
