### ISSUE TITLE
Operator| for p::d::Tria::Settings

### ISSUE THREAD

**Issue by gfcas** [dealii/dealii#12271]
Recently I wanted to combine two setting (construct_multigrid_... | no_automatic_repartition), therefore a dedicated function (as for UpdateFlags or EvaluationsFlags) for the p::d::Tria::Settings would be nice to avoid the static_cast.

I implemented for my personal purposes and would like to share it, however, dont know which ordering of the function in distributed/tria.h is preferred. Any suggestions in which place to add this function?

**Comment by bangerth** [comment]
I think such a function would be useful. What do you mean with "which ordering of the function"?

**Comment by gfcas** [comment]
The question means, where to add this function. I assume as inline function in the dsitributed/tria.h header, but at which line, such that the documentation looks well structured.

**Comment by gfcas** [comment]
Maybe this is not so important, so let me close this.
