### ISSUE TITLE
Triangulation policy are lost when a tria is returned by a function

### ISSUE THREAD

**Issue by nicola-giuliani** [dealii/dealii#12274]
@luca-heltai this is what we have been talking about...

I have the following snippet

dealii::Triangulation<2>
createDummyTria()
{
   dealii::Triangulation<2, 2> patch;
   dealii::GridGenerator::hyper_cube<2>(patch);
   dealii::Triangulation<2> tria;
   tria.copy_triangulation(patch); //here the policies are copied (just a check)
   return patch; // patch has the policies
}

int main()
{
   dealii::Triangulation<2> tria;
   tria.copy_triangulation(createDummyTria()); //here the policies are not copied because the returned tria does not have them
}

I am using Visual Studio 2017, I don't know if this happens also on UNIX.

**Comment by peterrum** [comment]
I think we might need to add here:

https://github.com/dealii/dealii/blob/f17695ac29b77015c8665c37ab664cf072edcbce/source/grid/tria.cc#L10064-L10068

a clone of the policy:

https://github.com/dealii/dealii/blob/f17695ac29b77015c8665c37ab664cf072edcbce/source/grid/tria.cc#L10378-L10379

@nicola-giuliani Could you try this out. If this works, may I ask you submit a patch and convert the code you have posted to a test. Thanks!
