### ISSUE TITLE
Memory usage of DoFHandle based on p::s::T

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#12317]
I construct a p::s::T with allow_artificial_cells = true and then pass it to a DH. 

I anticipated that the memory consumption of the DH object per process will decrease with the number of MPI processes because artificial cells should be ignored, much like for the p::d::T case.

Apparently, this does not happen and memory consumption is constant regardles of how many MPI processes I use. Is there no way to mimic p::d::T for the case with allow_artificial_cells = true?

**Comment by marcfehling** [comment]
As far as I know, `allow_artificial_cells` only affects the `subdomain_id` flags for cells and sets them to an invalid value for artificial cells. The internal data structures remain the same. You really just *mimic* what `p::d::T` does.

**Comment by marcfehling** [comment]
To be more precise: We still enumerate degrees of freedom on *all* cells, even with the `allow_artificial_cells` flag.
https://github.com/dealii/dealii/blob/d5faea2876dc6f35670e7446167d08229755b274/source/dofs/dof_handler.cc#L2695-L2719

**Comment by agrayver** [comment]
Thanks @marcfehling. I realize it is probably easier to implement it this way, but I wonder if there is any real need to allocate space (and spend other time) for all dofs? If allow_artificial_cells=true, this information will never be used, will it?

**Comment by peterrum** [comment]
You are right one would not need to allocate memory for these cells but currently the `DoFHandler` in the case of `p:s:T` is setup the same way independently whether artificial cell are enabled or not. The following code:

https://github.com/dealii/dealii/blob/a31b86c803ea2973ed424a42314f5bf97b4799e9/source/dofs/dof_handler_policy.cc#L3032-L3034

shows that the setup policy simply activates the artificial cells and distributes the dofs just like in the serial case. A better approach would be to use the policy also used for `p:d:T` or `p:f:T`. But this is currently not the case.

**Comment by agrayver** [comment]
Would the ParallelDistributed policy be readily applicable to p::s::T with allow_artificial_cells=true? If it is a matter of adding one more switch, it might be worth it.

**Comment by peterrum** [comment]
> Would the ParallelDistributed policy be readily applicable to p::s::T with allow_artificial_cells=true? If it is a matter of adding one more switch, it might be worth it.

Not completely. 

... but than one would also need to use the distributed solution transfer. `p:s:T` is just not a fully adequate alternative to `p:d:T`. Why are you using `p:s:T`? Is there a special reason?

**Comment by agrayver** [comment]
I need to know the mesh geometry everywhere, but the rest can be distributed -- these are just specifics of the problem at hand. In any case, thank you both for clarifying the issue: I guess we have to leave it as it is.
