### ISSUE TITLE
Simplify declaration of DataOutStack

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12327]
#12322 made me look up the `DataOutStack` class, which has this beautiful declaration:
```
/**
 * @deprecated Use DataOutStack<dim, spacedim> instead.
 */
template <int dim, int spacedim = dim, typename DoFHandlerType = void>
class DataOutStack;


template <int dim, int spacedim, typename DoFHandlerType>
class DataOutStack : public DataOutStack<dim, spacedim, void>
{
public:
  DEAL_II_DEPRECATED
  DataOutStack()
    : DataOutStack<dim, spacedim, void>()
  {}
};


template <int dim, int spacedim>
class DataOutStack<dim, spacedim, void> : public DataOutInterface<dim + 1>
{
  ...
```
It is certainly innovative to derive `X<T>` from `X<void>` -- but also confusing :-)

I think we can remove this now.

**Comment by marcfehling** [comment]
We should agree on a point up to which we want to be backwards compatible to the old `hp::DoFHandler` formalism and the `DoFHandlerType` templates. `Release 10.0` might be a bit early -- but I have no strong opinion on that.

**Comment by bangerth** [comment]
The old declaration was already deprecated, so I think it's fair to remove it.

**Comment by marcfehling** [comment]
We just deprecated the `Legacy::` namespace with the transition classes in that regard.

I would prefer if we remove anything related to `DoFHandlerType` at once (`Legacy` classes and others). So maybe wait until `Release 10.1`...?

**Comment by bangerth** [comment]
OK.

**Comment by marcfehling** [comment]
Related to #10333.
