### ISSUE TITLE
Need to convert DEAL_II_DEPRECATE_EARLY to DEAL_II_DEPRECATE right after branching

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12339]
We may have already missed our window of opportunity for this, but we need to add a step to the release task list that converts `DEAL_II_DEPRECATE_EARLY` to `DEAL_II_DEPRECATE` right after branching, before merging any patches that might add additional early deprecation notices.

Would someone want to propose a patch that makes this switch to the current list of early deprecations in the library? I've added the step to the release task list in the release papers repo already.

**Comment by drwells** [comment]
We should definitely add the release step but I tackled this in #12289, which was right after we branched.

**Comment by drwells** [comment]
Even if I didn't - a quick change to the `print_deprecated.py` script makes it easy to see which things were marked for early deprecation in 9.3 vs 10.0.

**Comment by drwells** [comment]
I added a release task so we don't forget.

I think that addresses everything - shall we close?

**Comment by bangerth** [comment]
I thought I had already added the task, but apparently forgot to commit. Turns out that I had added it in the exact same place as you :-)

**Comment by drwells** [comment]
We should renumber those at some point unless everyone else is as amused as I am by release step -3b and what not.

**Comment by bangerth** [comment]
Now would be a good time for it. Feel free to go ahead!
