### ISSUE TITLE
Introduce a second Docker image of master?

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#12349]
... with `-D DEAL_II_EARLY_DEPRECATIONS=ON`?

I really love our Docker image of the master branch, since it allows us to run easily CI on GitHub in application codes without needing recompile all deal.II. In some of these I would like to update the code as soon as features are (early) deprecated to get a feeling what will break as soon as possible. In others I am fine with waiting till the actual deprecation and I guess this is the solution most users will prefer. That's why I would like to suggest to have two Docker images. Any opinions?

**Comment by tjhei** [comment]
Do we actually need to recompile deal.ii if we are only interested in user code warnings? Maybe we can tweak the macro so that it can be toggled by a preprocessor define.
