### ISSUE TITLE
Many new 64-bit Trilinos failures

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1240]
Something broke the 64-bit Trilinos SparseMatrix tests:

http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=10578

This seems to have started before revision 8730696 . Could someone take a look?

**Comment by kronbichler** [comment]
It looks like it was one of my patches (unfortunately, tester seems to have missed the 64 bit tests for a while, so I'll need to look at it on my machine).

**Comment by bangerth** [comment]
Yes, tester first ran out of disk space on its ramdisk, and then the cdash database stopped accepting test submissions and results got lost. Poor timing.

All the failing tests throw an exception. You should be able to easily find it by running one in gdb and saying 'catch throw'.
