### ISSUE TITLE
lapack include variable

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#12435]
What is the cmake macro to specify the location of `mkl.h`? My guess

```
-D LAPACK_INCLUDE=${MKLROOT}/include \
```

did not have the wanted effect.

PS my notes say that cmake options are documented at

https://www.dealii.org/developer/users/cmake.html

but that link has gone away. Is there a replacement?

**Comment by tjhei** [comment]
> my notes say that cmake options are documented at
> 
> https://www.dealii.org/developer/users/cmake.html
> 
> but that link has gone away. Is there a replacement?

I let somebody else comment on your first question, but the document you are looking for is https://www.dealii.org/developer/users/cmake_dealii.html

**Comment by drwells** [comment]
I believe the correct variable is `LAPACK_INCLUDE_DIRS` but this is totally undocumented (and I have no way to test it).

**Comment by marcfehling** [comment]
Are you using the `Intel oneAPI` suite? You can have a look at our [`github actions` script](https://github.com/dealii/dealii/blob/7c44053f6c264aecc0cd40c5bf29ea449087bda5/.github/workflows/linux.yml#L186-L196) in which we specified the locations of lapack, blas, and mpi. Let us know if that helped!
