### ISSUE TITLE
Question: what does this command in fe_tools.cc do?

### ISSUE THREAD

**Issue by guidokanschat** [dealii/dealii#1244]
In the current version in fe_tools.cc around line 744, 

https://github.com/dealii/dealii/blob/master/source/fe/fe_tools.cc#L744

We have this code:
```
      const double result = H.least_squares (v_fine, v_coarse);
      (void)result;
      Assert (result < 1.e-12, ExcLeastSquaresError (result));
```

What does the middle line do?

**Comment by tjhei** [comment]
In release mode the ```Assert``` line will be defined to nothing so ```result``` is a variable that is assigned to but never used. That would generate a compiler warning and the middle line suppresses it.

**Comment by bangerth** [comment]
Not sure what to do about this. It's clearly not pretty, but I also don't know any way around it. I vote for closing, absent other suggestions.

**Comment by tjhei** [comment]
I don't have a problem with the current code. You could do
```
#ifdef DEBUG
      const double result =
#endif
           H.least_squares (v_fine, v_coarse);
      Assert (result < 1.e-12, ExcLeastSquaresError (result));
```
but that is not better. :-)

**Comment by kronbichler** [comment]
The alternative would be to not warn about unused variables in release mode (at least not for building the library).

**Comment by guidokanschat** [comment]
I was just not sure how to read this. I put a comment explaining it into the FE_BDM pull request
