### ISSUE TITLE
Latex representation of the enumeration of the reference cells 

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#12456]
see: https://gist.github.com/peterrum/09924dbac0454f3e9afbd0fd2bb285fd

FYI @bangerth

**Comment by bangerth** [comment]
I tried this out, and it works "in principle". Specifically, I tried the following:
```
  /**
   * Return the location of the `v`th vertex of the reference
   * cell that corresponds to the current object.
   *
   * Because the ReferenceCell class does not have a `dim` argument,
   * it has to be explicitly specified in the call to this function.
   * @f[
   *  \fbox{
\begin{tikzpicture}[scale=2.5]

\coordinate (0) at (0,0);
\coordinate (1) at (1,0);
\coordinate (2) at (0.5,0.86603);

\foreach \i in {0,1}
    \fill (\i) circle (1pt) node [below] {\i};

\foreach \i in {2}
    \fill (\i) circle (1pt) node [above] {\i};

\draw (0) --(1) -- (2) -- (0);


\draw (0.5,  0.0)  node [fill=white, text=black] {$0_0^1$};
\draw (0.75000,   0.43301)  node [fill=white, text=black] {$1_1^2$};
\draw (0.25000,   0.43301)  node [fill=white, text=black] {$2_2^0$};

\end{tikzpicture}
\qquad
\begin{tikzpicture}[scale=2.2]

\coordinate (0) at (0,0);
\coordinate (1) at (1,0);
\coordinate (2) at (0,1);
\coordinate (3) at (1,1);

\foreach \i in {0,1}
    \fill  [text=black]  (\i) circle (1pt) node [below] {\i};

\foreach \i in {2,3}
    \fill  [text=black]  (\i) circle (1pt) node [above] {\i};

\draw (0) --(1) -- (3) -- (2) -- (0);



\draw (0.0,  0.5)  node [fill=white, text=black] {$0_0^2$};
\draw (1.0,  0.5)  node [fill=white, text=black] {$1_1^3$};
\draw (0.5,  0.0)  node [fill=white, text=black] {$2_0^1$};
\draw (0.5,  1.0)  node [fill=white, text=black] {$3_2^3$};

\end{tikzpicture}
   *  } % \fbox
   * @f]
   */
  template <int dim>
  Point<dim>
  vertex(const unsigned int v) const;
```
Which then provides the following:
![image](https://user-images.githubusercontent.com/7504421/137966028-309aa1fd-0405-4c3e-864a-5ca837e4d610.png)

So this works, though we would have to undo the escaping of `$` signs in the filter script. The bigger problem, however, is that this only works if we run all latex commands through -- well -- latex. Except we don't: We use MathJAX instead. The picture above was generated by switching off MathJAX, which is I think not quite what we want to do. 

An alternative solution would be to pre-process all input files where we check for special markers for tikz pictures and then:
* use the tikz picture description to create a special latex file that we then run through latex to generate a picture
* replace the tikz picture description by a reference to the image

**Comment by bangerth** [comment]
@peterrum -- out of curiosity, did you close this because it's hard to do and we won't do it, or because there is a specific PR that was merged that addressed this?
