### ISSUE TITLE
ParameterHandler::add_parameter fails for map<int,pair<int,int>> with custom separators

### ISSUE THREAD

**Issue by sebproell** [dealii/dealii#12477]
I wanted to add a parameter of type `std::map<int, std::pair<int,int>>` with `ParameterHandler::add_parameter`. This works as long as I use the default separators. However, if I use (prettier) custom separators, the verfication of the default value fails. A subsequent read also fails. I added a test here: https://github.com/sebproell/dealii/blob/add-parameter-map-tuple/tests/parameter_handler/patterns_17.cc#L55-L75

Is this a bug or am I not using the function properly? As you can see in the test, the custom pattern clearly works and matches the string. The error seems to indicate that the custom separator gets lost somewhere. I can spend some time to hunt this down, if it really is a bug. WDYT?

**Comment by drwells** [comment]
@sebproell this is closed, but would you mind putting up a PR with the change to the test? I don't think that was in #12600.

**Comment by sebproell** [comment]
@drwells I can do this but probably not before mid August.

**Comment by drwells** [comment]
Lets keep this open for now and we can close again once the test is in too.
