### ISSUE TITLE
LAPACKFullMatrix instantiation

### ISSUE THREAD

**Issue by anuvyklack** [dealii/dealii#12475]
I have just compiled 9.3.0 and get the next error in my header file:
```
error: implicit instantiation of undefined template 'dealii::LAPACKFullMatrix<double>'
```
However, I have the file
```
dealii-9.3.0/build/source/lac/lapack_full_matrix.inst
```
with next lines in it:
```
#if (SPLIT_INSTANTIATIONS_CHECK(0))
template class LAPACKFullMatrix< double >;
 template class PreconditionLU< double >;
 
#endif
```

**Comment by anuvyklack** [comment]
I fix this problem: you need to include the next header:
```
#include <deal.II/lac/lapack_full_matrix.h>
```
but not this one
```
#include <deal.II/base/array_view.h>
```
how it written in [documentation](https://www.dealii.org/current/doxygen/deal.II/classLAPACKFullMatrix.html).

**Comment by peterrum** [comment]
What you describe is a known issue. Unfortunately, Doxygen picks up sometimes the wrong header files. I am not sure how one can fix this.

**Comment by drwells** [comment]
I am not sure I understand the description of this issue. Is the library failing to compile?

**Comment by masterleinad** [comment]
> What you describe is a known issue. Unfortunately, Doxygen picks up sometimes the wrong header files. I am not sure how one can fix this.

Don't let `Doxygen` see any forward-declarations. :slightly_smiling_face:

**Comment by drwells** [comment]
Without more information I don't think we can fix this one. Lets reopen if we get more information.
