### ISSUE TITLE
A piece of TrilinosWrappers::SparseMatrix::set() documentation is not very clear

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1251]
In documentation of function 
```
void TrilinosWrappers::SparseMatrix::set	(	const size_type 	i,
const size_type 	j,
const TrilinosScalar 	value 
)	
```
There is a sentence 
```
... it is mandatory that elements are inserted only once. Otherwise, the elements will actually be added in the end .
```

I can't figure out it is "in the end" of what.  Does the set() function has a queue or cache so that "the elements will actually be added in the end" and finally go into the matrix? Or "the elements will actually be added in the end" of the row of compressed matrix and destroy the sparsity pattern?

I know that the documentation wants to told me never set an element more than once.
But Who to over write a specify element of the matrix without knowing it is exist or not?

**Comment by bangerth** [comment]
Good question :-) 

@kronbichler -- you wrote that text in Dec 2013. Do you recall?

**Comment by kronbichler** [comment]
The sentence concerns the case when you set off-processor entries, i.e., into rows that are owned by another processor. I think there was the case that Trilinos did not respect the Epetra_CombineMode (aka dealii::VectorOperation) when setting off-processor entries if I remember things correctly. I will try to improve the documentation and check if we have a test case.

**Comment by QiaoLei-88** [comment]
Thank you for working on this.
I think I'd better use SparseMatrixEZ for a dynamic matrix.
