### ISSUE TITLE
9.3 MacOS image is 9.2?

### ISSUE THREAD

**Issue by anne-glerum** [dealii/dealii#12512]
I've downloaded the dealii-9.3.0-bigsur-intel.dmg from the mirror link. However, when I open the app, it seems to be 9.2 from last year. This is what /Applications/deal.II.app/Contents/MacOS/summary.log says:
```
#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       DebugRelease
#        BUILD_SHARED_LIBS:      ON
#        CMAKE_INSTALL_PREFIX:   /Applications/deal.II.app/Contents/Resources/spack/opt/spack/dealii-9.2.0-747m
#        CMAKE_SOURCE_DIR:       /var/folders/8z/hlb6vc015qjggytkxn84m6_c0000gn/T/heltai/spack-stage/spack-stage-dealii-9.2.0-747mf54t7nef2iff4la5ab3qxlrpd2jb/spack-src
#                                (version 9.2.0)
#        CMAKE_BINARY_DIR:       /private/var/folders/8z/hlb6vc015qjggytkxn84m6_c0000gn/T/heltai/spack-stage/spack-stage-dealii-9.2.0-747mf54t7nef2iff4la5ab3qxlrpd2jb/spack-build-747mf54
#        CMAKE_CXX_COMPILER:     AppleClang 12.0.0.12000032 on platform Darwin x86_64
#                                /Applications/deal.II.app/Contents/Resources/spack/opt/spack/openmpi-3.1.6-pvpk/bin/mpic++
```
The timestamp in Finder is also the same as last year (9 November 2020).

According to Finder, I downloaded the image from: https://www.dealii.org/download.html
https://dealii.43-1.org/downloads/darwin-images/dealii-9.3.0-bigsur-intel.dmg

The checksum is the same as listed.

**Comment by tjhei** [comment]
@tamiko ?

**Comment by tjhei** [comment]
Can you check if the "GitHub" link is the same file?

**Comment by anne-glerum** [comment]
It seems to be the same file.

**Comment by tamiko** [comment]
Let me check.

**Comment by tjhei** [comment]
Anne, did you uninstall/delete any old packages?

**Comment by luca-heltai** [comment]
Can you run `spack find` and print the output? I get  ***@***.***

The true summary.log is in 

spack cd -i ***@***.***

that is:

/Applications/deal.II.app/Contents/Resources/spack/opt/spack/dealii-9.3.0-zy7k/share/deal.II/summary.log

The summary log in Contents/MacOS/summary.log is a leftover of the old installation I had.

L. 

--
Luca Heltai ***@***.***>
http://people.sissa.it/~heltai/
Scuola Internazionale Superiore di Studi Avanzati
Phone:  +39 040 3787 449, Office: 608
--
There are no answers, only cross references.

**Comment by luca-heltai** [comment]
In other words: the `summary.log` there has nothing to do with the installed packages. It should have been replaced (my bad), but the library is definitely 9.3.0.

**Comment by anne-glerum** [comment]
Thank you all for the quick replies! I can confirm that `spack find` returns v9.3 and ASPECT installation was successful against this 9.3. Apologies for the confusion, I'll close the issue.
