### ISSUE TITLE
OSX: 'shared_timed_mutex' is unavailable

### ISSUE THREAD

**Issue by xywei** [dealii/dealii#12549]
```
/Users/runner/miniforge3/conda-bld/dealii_1625605635799/work/include/deal.II/base/thread_local_storage.h:254:18: error: 'shared_timed_mutex' is unavailable: introduced in macOS 10.12
    mutable std::shared_timed_mutex insertion_mutex;
                 ^
/Users/runner/miniforge3/conda-bld/dealii_1625605635799/_build_env/bin/../include/c++/v1/shared_mutex:205:58: note: 'shared_timed_mutex' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_timed_mutex
```

The issue was revealed by https://github.com/conda-forge/dealii-feedstock/pull/22
```
OS version: Mac OS X 10.15.7 19H1217
Compiler version: clangxx_osx-64 11.1.0
```

Detailed build log [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=347871&view=logs&jobId=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=63fa899e-c160-5185-75c4-c5fd30c90374)

**Comment by drwells** [comment]
This is a very weird error message - it says this feature was introduced in macOS 10.12 yet we are compiling on 10.15: i.e., I don't understand why it isn't available. Do you have any idea?

**Comment by jppelteret** [comment]
I had the same (or a very similar) problem to @xywei . I tried a lot of different things to fix it, but ultimately ended up upgrading my machine to 10.15. I actually added a check for this here:
https://github.com/dealii/dealii/blob/master/cmake/setup_compiler_flags_gnu.cmake#L31-L37
Maybe its not sufficiently robust, or the minimal apple-clang version needs to be adjusted again.

**Comment by jppelteret** [comment]
https://github.com/dealii/dealii/issues/10531 is the original issue, which this one duplicates.

**Comment by jppelteret** [comment]
Sorry, I've just read the description and I see that you are compiling on MacOS 10.15. Now I'm confused as to why you are hitting this issue :-/

**Comment by jppelteret** [comment]
Googling "macos 10.15, error: 'shared_timed_mutex' is unavailable: introduced in macOS 10.12" reveals that this is a somewhat pervasive issue. If I have correctly understand the various threads that I read, explicitly setting the C++ standard to 14 and disabling C++17 support might be the key to fixing the problem. See [here](https://dealii.org/developer/users/cmake_dealii.html#configure) for how to do this the "correct" way; you might also be able to get away with adding `-DDEAL_II_WITH_CXX14=ON -DDEAL_II_WITH_CXX17=OFF` to the configure options. It *might* also help to call `env MACOSX_DEPLOYMENT_TARGET=10.15 cmake ...`, but I'm not completely sure.

Refs.
https://gitlab.kitware.com/cmake/cmake/-/issues/20054
https://bugzilla.mozilla.org/show_bug.cgi?id=1573733

**Comment by isuruf** [comment]
@xywei, since you are building for an older target (10.9) with a newer libcxx, you need to add `-D_LIBCPP_DISABLE_AVAILABILITY` to `CXXFLAGS`. That should make the error go away.

**Comment by xywei** [comment]
@isuruf Not sure what you mean here. The [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=347871&view=logs&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=2d60abc3-1b6d-4cd3-820b-625ae8ac55cc&l=5) shows that it was building on 10.15.

**Comment by isuruf** [comment]
It's building on 10.15, but targeting 10.9 so that the conda package works on older OS even though the build machine is newer.

**Comment by xywei** [comment]
Thanks for the clarification. I will try that. In the meanwhile, I saw a similar issue https://github.com/laverdet/isolated-vm/issues/200 and tried to apply a patch to replace `std::shared_timed_mutex` with `boost::shared_mutex`. Will see if that fixes it.

**Comment by xywei** [comment]
Adding `-D_LIBCPP_DISABLE_AVAILABILITY` works, thanks @isuruf! FWIW, using `boost::shared_mutex` also works using [this patch](https://github.com/conda-forge/dealii-feedstock/blob/c52964c3049434098a7ebc584ce6a50bdb157968/recipe/shared_mutex.patch).
