### ISSUE TITLE
Include HDF5 support in cmake 

### ISSUE THREAD

**Issue by tckosvic** [dealii/dealii#12569]
I try turning hdf5 on in cmake.  I get unclear messages as to what is missing and what to do.  I can either add more hdf5 files or add other items to the cmake commandline.  Here are the messages I am getting.

`-- 
-- Include /home/tom/dealii/cmake/configure/configure_hdf5.cmake
-- Found HDF5_INCLUDE_DIR
-- Found HDF5_LIBRARY
-- Found HDF5_HL_LIBRARY
-- Found HDF5_PUBCONF
--   HDF5_LIBRARIES: /usr/lib64/libhdf5_hl.so;/usr/lib64/libhdf5.so;/usr/lib64/mpi/gcc/mpich/lib64/libmpi.so
--   HDF5_INCLUDE_DIRS: /usr/include
--   HDF5_USER_INCLUDE_DIRS: /usr/include
-- Found HDF5
-- Insufficient hdf5 installation found: hdf5 has to be configured with the same MPI configuration as deal.II.
-- DEAL_II_WITH_HDF5 has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):
  

  Could not find the hdf5 library!

  Insufficient hdf5 installation found!

  hdf5 has to be configured with the same MPI configuration as deal.II, but
  found:

    DEAL_II_WITH_MPI = ON
    HDF5_WITH_MPI    = FALSE

  Please ensure that a suitable hdf5 library is installed on your computer.

  If the library is not at a default location, either provide some hints for
  autodetection,

      $ HDF5_DIR="..." cmake <...>
      $ cmake -DHDF5_DIR="..." <...>

  or set the relevant variables by hand in ccmake.

Call Stack (most recent call first):
  cmake/macros/macro_configure_feature.cmake:269 (FEATURE_ERROR_MESSAGE)
  cmake/configure/configure_hdf5.cmake:48 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/tom/dealii/build/CMakeFiles/CMakeOutput.log".
See also "/home/tom/dealii/build/CMakeFiles/CMakeError.log".
tom@localhost:~/dealii/build> ccmake
Usage

  ccmake <path-to-source>
  ccmake <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'ccmake --help' for more information.

tom@localhost:~/dealii/build> `

It says it found libraries then it says it didn't find libraries.   I've tried a myriad of -DHDF5_DIR=**** in trying to help it find the one it wants.
Right now I have about 80 hdf5 files (and libhdf5) installed.  There are more than 200 more hdf5/hdf5-mpi/libhdf5 files yet to be installed.  From the messages, what might I be looking for??

thanks,      tom kosvic

**Comment by drwells** [comment]
CMake is finding the installation just fine. The critical line is

> Insufficient hdf5 installation found: hdf5 has to be configured with the same MPI configuration as deal.II.

Make sure you install `hdf5-openmpi` or some similarly named package that enables the HDF5 bindings to the same MPI library you want to use elsewhere.

**Comment by marcfehling** [comment]
The error message of interest is this one
```
-- Insufficient hdf5 installation found: hdf5 has to be configured with the same MPI configuration as deal.II.
```

So it seems you try to build `deal.II` with `MPI` and `HDF5` enabled. The error message states, that the `HDF5` library you installed has not been configured with `MPI`.

How did you install `HDF5`? I assume you are using linux. If you are using a repository manager, make sure that your `libhdf5` package provides `MPI` support. For ubuntu, try a package `libhdf5-mpi-dev`.

**Comment by drwells** [comment]
This was easy enough to answer so I believe we both wrote something up at the same time :)

**Comment by tckosvic** [comment]
Brief comments on what is installed.  I have installed (from opensuse leap 15.3),
hdf5-openmpi, hdf5-openmpi2, hdf5-openmpi3, hdf5-openmpi4
hdf5-openmpi-devel, hdf5-openmpi2-devel, hdf5-openmpi3-devel, hdf5-openmpi4-devel
libhdf5-101, libhdf5-103, etc

Additionally a bunch of hdf5-gnu files a bunch of hdf5-fortran files, and a bunch of hdf5-cpp files

Plus another 70 or so files.

I still do not get any idea of what to do from cryptical and indescriptive message
"insufficient hdf5 installation found: hdf5 has to be configured with the same MPI configuration as dealii"
 How do I match an hdf5 configuration with an mpi configuration?  Same version number?

thanks,  tom kosvic

**Comment by marcfehling** [comment]
From your log it looks like you have configured deal.II with `MPICH` and not `OpenMPI`. Your `HDF5` installation uses `OpenMPI` (at least according to the name).

Could you try to install [`hdf-mvapich2`](https://software.opensuse.org/package/hdf-mvapich2) instead of `hdf5-openmpi`?

**Comment by marcfehling** [comment]
I just noticed that `hdf-mvapich2` contains `HDF4` and not `HDF5`.

I guess at this point you have two options:
- Install `openmpi`, configure deal.II with it, and use `hdf5-openmpi`.
- Build `hdf5` yourself with `MPICH` and link deal.II against your custom `HDF5` installation.

**Comment by tckosvic** [comment]
I installed hdf-mvapich2 and configuration was successful.   I already had 15 files with names that included mvapich2 installed.
I left hdf5-openmpi installed.  If it should be removed let me know.

I have no idea what I did to "configure deal.II with MPICH and not OpenMPI".  Could someone let me know where/how that was done?

thanks again,    tom kosvic

**Comment by tckosvic** [comment]
I got past hdf5 config.  
Issue now is petsc config.  I have 15 libpetsc files installed with probably 50 more that are available in opensuse.  
All installed ones are in /use/lib  or usr/lib64;  standard locations.  But I get error messages below:

`-- Include /home/tom/dealii/cmake/configure/configure_3_petsc.cmake
-- PETSC_LIBRARY not found! Call:
--     FIND_LIBRARY(PETSC_LIBRARY NAMES petsc libpetsc HINTS / PATH_SUFFIXES lib lib64 lib)
-- PETSC_INCLUDE_DIR_ARCH not found! Call:
--     FIND_PATH(PETSC_INCLUDE_DIR_ARCH petscconf.h HINTS / PATH_SUFFIXES petsc include include/petsc)
-- PETSC_INCLUDE_DIR_COMMON not found! Call:
--     FIND_PATH(PETSC_INCLUDE_DIR_COMMON petscversion.h HINTS / PATH_SUFFIXES petsc include include/petsc)
-- PETSC_PETSCVARIABLES not found! Call:
--     FIND_FILE(PETSC_PETSCVARIABLES NAMES petscvariables HINTS / PATH_SUFFIXES conf lib/petsc/conf)
--   PETSC_LIBRARIES: *** Required variable "PETSC_LIBRARY" set to NOTFOUND ***
--   PETSC_INCLUDE_DIRS: *** Required variable "PETSC_INCLUDE_DIR_COMMON" set to NOTFOUND ***
--   PETSC_USER_INCLUDE_DIRS: *** Required variable "PETSC_INCLUDE_DIR_COMMON" set to NOTFOUND ***
-- Could NOT find PETSC
-- DEAL_II_WITH_PETSC has unmet external dependencies.
`
Any advice as to what to install additionally.

It would be helpful if the cmake system said what files it is looking for rather than that it can't find some unknown (to the user) file.  Saying it can't find some unknown file gives no information to the user.  This whole system looks backwards to me.

tom kosvic

**Comment by tckosvic** [comment]
I will move any future discussions to https://groups.google.com/g/dealii.  I will close this issue thread

thanks all,  tom kosvic
