### ISSUE TITLE
Some simplex face values are not scaled correctly

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#12580]
I need to come up with a minimum working example to be absolutely sure that this is an issue, but in brief - we assume that all faces of the reference cell have measure 1 at least inside `MappingFEField`, which causes the jacobians on the second face to be off by a factor of `sqrt(2)`.

I found this out when I wrote some general code to compute face integrals - the `JxW` values are wrong on the longer face.

**Comment by peterrum** [comment]
To me the culprit line looks like: 

https://github.com/dealii/dealii/blob/168904fa146d85a65c037c7e09292b436c99a6d4/source/fe/mapping_fe_field.cc#L646-L648

see also: 

https://github.com/dealii/dealii/blob/168904fa146d85a65c037c7e09292b436c99a6d4/source/fe/mapping_fe.cc#L1074-L1089

`QProjector<dim>::project_to_all_faces()` is responsible for the scaling you are describing:

https://github.com/dealii/dealii/blob/168904fa146d85a65c037c7e09292b436c99a6d4/source/base/qprojector.cc#L616-L619

**Comment by drwells** [comment]
Thanks - I'll start working on this today.
