### ISSUE TITLE
symmetric_tensor.templates.h

### ISSUE THREAD

**Issue by hjh878** [dealii/dealii#12621]
I got a problem while compile the source file after run the make install          
```make
[ 76%] Building CXX object source/base/CMakeFiles/obj_base_release.dir/symmetric_tensor.cc.o
In file included from /home/jiahua/Downloads/dealii/source/base/symmetric_tensor.cc:20:0:
/home/jiahua/Downloads/dealii/include/deal.II/base/symmetric_tensor.templates.h: In instantiation of ‘std::array<Number, 3ul> dealii::eigenvalues(const dealii::SymmetricTensor<2, 3, Number>&) [with Number = float]’:
/home/jiahua/Downloads/dealii/build/source/base/symmetric_tensor.inst:85:42:   required from here
/home/jiahua/Downloads/dealii/include/deal.II/base/symmetric_tensor.templates.h:113:39:   in constexpr expansion of ‘dealii::determinant<3, float>(B)’
/home/jiahua/Downloads/dealii/include/deal.II/base/symmetric_tensor.templates.h:113:43: internal compiler error: segment fault
       const Number tmp_2 = determinant(B) / 2.0;
                                           ^
```         
Am I missing something? My computer environment is Ubuntu16.04, GNU version is 5.4.0, cmake version is 3.21.1 and GNU make version 4.1

**Comment by drwells** [comment]
This looks like a problem on our end. Is this the most recent release (9.3.0) or the development version?

**Comment by hjh878** [comment]
> This looks like a problem on our end. Is this the most recent release (9.3.0) or the development version?

I download it from this site one day ago and the version is 10.0.0-pre, which is mentioned in the VERSION file

**Comment by drwells** [comment]
I cannot reproduce this with GCC 5.5 on my machine. Could you post the `detail.log` file from the build directory here?

**Comment by hjh878** [comment]
> I cannot reproduce this with GCC 5.5 on my machine. Could you post the `detail.log` file from the build directory here?

[detailed.log](https://github.com/dealii/dealii/files/6935569/detailed.log)

**Comment by hjh878** [comment]
> I cannot reproduce this with GCC 5.5 on my machine. Could you post the `detail.log` file from the build directory here?

I have upload the detail.log file, thank you for your patient~

**Comment by drwells** [comment]
Thanks. You are not using any of the automatic differentiation libraries so we can rule out a lot of problems.

Does anyone else have an installation of 5.4 handy so they can confirm?

**Comment by richardschu** [comment]
Hi! 
I am stuck with the same issue, here is my detailed.log:
[detailed.log](https://github.com/dealii/dealii/files/6941209/detailed.log)
Maybe our compilers are now finally too old? Oh no ...
Also, I tried it with the current candi, where it even gave me something like:
"
Fetching dealii v9.3.0
Cloning into 'deal.II-v9.3.0'...
fatal: Unable to find remote helper for 'https'
Failure with exit status: 128
Exit message: candi: git clone https://github.com/dealii/dealii.git deal.II-v9.3.0 failed
" 
So I did it manually (packages still through candi) and got the identical error as stated above.
Using an older version of candi, I also got that error, so that is at least consistent.

In case I get this running on my machine I will post it here!
Kind regards
Richard

**Comment by richardschu** [comment]
Hi again,
so the hint with GCC5.5 was crucial: on a machine with GCC5.5 I had access to it was running through like a charm (manual deal.II install, not through candi)!
Therefore I updated the GCC version following this
[tutorial](https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91)
which solved the problem for me.
Hope this helps!
Best regards
Richard

**Comment by hjh878** [comment]
> Hi again,
> so the hint with GCC5.5 was crucial: on a machine with GCC5.5 I had access to it was running through like a charm (manual deal.II install, not through candi)!
> Therefore I updated the GCC version following this
> [tutorial](https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91)
> which solved the problem for me.
> Hope this helps!
> Best regards
> Richard

I have update my gcc version to 5.5,and now it works, thank you~
