### ISSUE TITLE
`GridGenerator::subdivided_cyclinder()` should not use absolute thresholds.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#12668]
The function `GridGenerator::subdivided_cyclinder()` sets boundary and manifold IDs based on absolute thresholds (`1e-5`) which causes problems on geometries with small dimensions. https://github.com/dealii/dealii/blob/4ae089691e3d3c361f38974c96628df49353f80e/source/grid/grid_generator.cc#L5609-L5643

We should use either relative thresholds or an absolute threshold determined by `std::numeric_limits` instead.

Reported and discussed in [this post in deal.II user group](https://groups.google.com/g/dealii/c/HRb7iILFsfI).

**Comment by blaisb** [comment]
I'll take care of it. I wrote this grid generator, so I might as well fix my mistakes :). PR should come up later today.
