### ISSUE TITLE
deadlock in `ParticleHandler::insert_particles(const std::vector<Point<spacedim>> &positions)` when no particles inserted on some processors

### ISSUE THREAD

**Issue by slfuchs** [dealii/dealii#12724]
Dear all,

when calling `void ParticleHandler<dim, spacedim>::insert_particles(const std::vector<Point<spacedim>> &positions)` in parallel with some processor not inserting particles (i.e., the vector `positions` is empty) a deadlock occurs.

The method returns on those processors with the return statement in [line 594](https://github.com/dealii/dealii/blob/master/source/particles/particle_handler.cc#L594) before calling `update_cached_numbers()` in [line 603](https://github.com/dealii/dealii/blob/master/source/particles/particle_handler.cc#L603). However, `update_cached_numbers()` contains collective communication and should thus be called over all processors (of the communicator).

Is it okay to call `insert_particles(...)` even though some processors actually don't insert particles? This would be an important feature for my application. If this is the case, I think one could simply remove the return statement in [line 594](https://github.com/dealii/dealii/blob/master/source/particles/particle_handler.cc#L594). Thus it would be ensured that `update_cached_numbers()` is called over all processors.

**Comment by peterrum** [comment]
That is bad. I guess the code should read:
```cpp
    if (cells.size() != 0)
      {
        for (unsigned int i = 0; i < cells.size(); ++i)
          for (unsigned int p = 0; p < local_positions[i].size(); ++p)
            insert_particle(positions[index_map[i][p]],
                            local_positions[i][p],
                            local_start_index + index_map[i][p],
                            cells[i]);
       }
    update_cached_numbers();
```

@gassmoeller What do you think?

**Comment by gassmoeller** [comment]
Yes, this is a bug and @peterrum your suggestion is the fix. @slfuchs do you want to make a pull request using @peterrum's suggestion? It would be a nice first PR and would give you some credit for tracking down the bug. If you need help or would prefer one of us to do it let us know.

**Comment by slfuchs** [comment]
@gassmoeller: Yes, I can take over! Thanks for the fast response.

**Comment by gassmoeller** [comment]
:+1: 
Actually reading through this again your suggestion to remove the return was already better (somehow I skipped that when reading the issue). The if-condition is not needed since the first for-loop only loops over cells anyway. I think that is cleaner.
