### ISSUE TITLE
inverse_operator() objects should not be stored or reused

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12737]
I *think* that we have identified an issue with the `inverse_operator()` function and resulting object in a code by @juleoc02 . If I see this right, then the `inverse_operator()` object stores references to a linear solver object, and that linear solver will generally store a reference to a `SolverControl` object. The problem is that linear solvers generally do not reset the iteration counter to zero every time you call a `solve()` function. As a consequence, if you allow yourself 1,000 iterations in the `SolverControl` object, and if each invokation of the inverse operator requires 100 iterations, then after the tenth invokation of the inverse operator you get a convergence failure simply because you've exhausted the total number of iterations.

We should at the very least document this, but it would probably also be good if we made sure that our iterative solvers *reset* the control object every time they start a linear solve.

Ideas?

**Comment by peterrum** [comment]
>  The problem is that linear solvers generally do not reset the iteration counter to zero every time you call a solve() function.

But they should. `SolverCG` does it if I am not mistaken:

https://github.com/dealii/dealii/blob/608928eb318e52c371612f5036900c99287e9b2d/include/deal.II/lac/solver_cg.h#L373

**Comment by bangerth** [comment]
You are right. I had neglected the fact that we pass down the number of the iteration when calling `iteration_status`.
