### ISSUE TITLE
No warning/error a non-conforming mesh with FE_NedelecSZ

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#12775]
As reported by @Sebastian-47 on the mailing [list](https://groups.google.com/g/dealii/c/_10WdR72sek), FE_NedelecSZ, which does not support hanging nodes yet, does however run on a non-conforming mesh without any error even in debug mode, producing wrong results.

I think it should throw a ExcNotImplemented if hanging nodes are encountered.

**Comment by kronbichler** [comment]
I think we made progress on this topic with the recent work by #16304 and #16644. Let us close this for now, we can always revisit in case there are other open topics.
