### ISSUE TITLE
Reevaluate MF::AdditionalData::use_fast_hanging_node_algorithm

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#12780]
as commented in https://github.com/dealii/dealii/pull/12779#pullrequestreview-765482572

**Comment by peterrum** [comment]
@kronbichler Are we confident enough with the new code so that we can remove the flag?

**Comment by kronbichler** [comment]
Yes, let us disable this flag. Anything not working can be considered a bug, and we have good coverage of hanging node cases.
