### ISSUE TITLE
Compilation with boost-1.77 fails due to "Operation not implemented" in geometry

### ISSUE THREAD

**Issue by anates** [dealii/dealii#12817]
Hei,
when compiling deal.II (latest version) with boost-1.77.0 compilation fails with the attached message below (had to attach it as file due to char limit):
[make_error.log](https://github.com/dealii/dealii/files/7328169/make_error.log)
detailed.log is attached.
[detailed.log](https://github.com/dealii/dealii/files/7328159/detailed.log)

**Comment by anates** [comment]
I can take a look as soon as I have more time again, but atm. I just needed a working deal.II-Installation, thus I'll run with 1.76 for the upcoming weeks…

**Comment by tamiko** [comment]
@drwells Good point, let's do that.

**Comment by zerothi** [comment]
I still get this error on `boost-1.78` and dealii 9.3.2

```shell
/opt/gnu/11.2.0/boost/1.78.0/include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp:122:21: error: ‘apply’ is not a member of ‘boost::geometry::dispatch::distance<dealii::Point<3, double>, dealii::BoundingBox<3, double>, boost::geometry::strategies::distance::detail::comparable<boost::geometry::strategies::distance::cartesian<> >, boost::geometry::point_tag, boost::geometry::box_tag, boost::geometry::strategy_tag_distance_point_box, false>’
```

FYI.

**Comment by drwells** [comment]
Unfortunately we banned this version of boost after the point release. Since we still don't have a workaround I believe 9.3 will not be compatible with that version of boost, ever.
