### ISSUE TITLE
MPI::BOOL compilation error - missing header

### ISSUE THREAD

**Issue by spco** [dealii/dealii#1282]
When compiling 8.3.0 from source, upon calling 'make' I get

`[ 77%] Building CXX object source/distributed/CMakeFiles/obj_distributed.release.dir/tria.cc.o
/home/s/spc29/dealii-8.3.0/source/distributed/tria.cc: In member function ‘virtual bool dealii::parallel::distributed::Triangulation<dim, spacedim>::has_hanging_nodes() const’:
/home/s/spc29/dealii-8.3.0/source/distributed/tria.cc:2477:42: error: ‘MPI’ has not been declared
       MPI_Allreduce(&res_local, &res, 1, MPI::BOOL, MPI_LOR, mpi_communicator);
                                          ^
make[2]: *** [source/distributed/CMakeFiles/obj_distributed.release.dir/tria.cc.o] Error 1
make[1]: *** [source/distributed/CMakeFiles/obj_distributed.release.dir/all] Error 2
make: *** [all] Error 2`

This is fixed by including mpicxx.h in source/distributed/tria.cc

Cmake command called:
`cmake -DCMAKE_CXX_COMPILER="/cm/shared/apps/ics/impi/4.1.3.048/intel64/bin/mpicxx" -DDEAL_II_CXX_FLAGS="-DMPICH_IGNORE_CXX_SEEK -DMPICH_SKIP_MPICXX -O3" -DWITH_MPI=ON -DWITH_P4EST=ON -DP4EST_DIR=~/p4est/FAST -DWITH_LAPACK=ON -DLAPACK_DIR="/cm/shared/apps/lapack/intel/3.4.2/lib64" -DBUILD_SHARED_LIBS=ON -DWITH_TRILINOS=ON -DTRILINOS_DIR=~/trilinos/12.0.1 -DWITH_METIS=OFF -DBLAS_DIR="/cm/shared/apps/blas/intel/1" -DTBB_LIBRARY="/cm/shared/apps/ics/composer_xe_2013.1.117/tbb/lib/intel64/libtbb.so" -DCMAKE_INSTALL_PREFIX=~/deal.II ..`

gcc 4.8.1
Intel MPI 4.1.3
cmake 3.2.3
Scientific Linux 6.4 (Carbon)

**Comment by bangerth** [comment]
Bummer. Alternatively, does it help if you replace `MPI::BOOL` by `MPI_BOOL`?

**Comment by spco** [comment]
No, I get the same error. I haven't tried MPI_BOOL and the added header include, but I imagine that would work.
