### ISSUE TITLE
Names of FEInterfaceValues functions

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13103]
Related to #8884. @jppelteret: FYI

#12411 renamed `FEInterfaceValues::jump()` into `FEInterfaceValues::jump_in_shape_values()` and similarly for related functions. But I find these names awkward since they have a plural *values* when they really only return a single value: the jump in the value of a single shape function. We also only have `FEValues::shape_value()` and `FEValues::shape_gradient()`, for example.

We should rename these functions a second time, I believe, and remove the plural.

**Comment by tjhei** [comment]
One can argue that it is a singular jump between two shape functions and as such accurate.

What do you propose for ``FEValuesViews::Scalar::average_of_values``?

**Comment by bangerth** [comment]
Ah, I see. One could read it that way. `jump_in_values()` still sounds plural-y to me because I would write that as "the jump in the value of the function at a point x" -- the function does not have multiple values at a point. But I agree that one could interpret it the way you say.

What do others think?

**Comment by tjhei** [comment]
> What do others think?

We could always go back to ``jump``, which is what I prefer. ;-)

**Comment by jppelteret** [comment]
> One can argue that it is a singular jump between two shape functions and as such accurate.

This was how I understood it as well, and why I chose that naming scheme.
