### ISSUE TITLE
Problem with BOOST_SERIALIZATION_USABLE

### ISSUE THREAD

**Issue by jonathonmckay** [dealii/dealii#13104]
I am having a problem compiling deal.ii for our cluster using an external version of Boost. During the compile process for deal.ii, the following messages are show regarding boost:
`-- Performing Test BOOST_IOSTREAMS_USABLE
-- Performing Test BOOST_IOSTREAMS_USABLE - Success
-- Performing Test BOOST_SERIALIZATION_USABLE
-- Performing Test BOOST_SERIALIZATION_USABLE - Failed
-- The externally provided Boost.Serialization library failed to pass a crucial test.
Therefore, the bundled boost package is used.
The configured testing project can be found at
/[redacted]/source/dealii-9.3.2/build/cmake/configure/TestBoostBugWorkdir
-- DEAL_II_WITH_BOOST has unmet external dependencies.
`

If I visit the directory listed (dealii-9.3.2/build/cmake/configure/TestBoostBugWorkdir) and run _make_ here, I get message about boost::archive:
`[ 75%] Linking CXX executable test_boost
CMakeFiles/test_boost.dir/test_dll_exported.cpp.o:test_dll_exported.cpp:function void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&): error: undefined reference to 'boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
CMakeFiles/test_boost.dir/test_dll_exported.cpp.o:test_dll_exported.cpp:function boost::archive::text_iarchive& boost::archive::detail::interface_iarchive<boost::archive::text_iarchive>::operator>><boost::archive::class_name_type>(boost::archive::class_name_type&): error: undefined reference to 'boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&)'
CMakeFiles/test_boost.dir/test_dll_exported.cpp.o:test_dll_exported.cpp:function void boost::archive::save_access::save_primitive<boost::archive::text_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::text_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
`

The Boost version we're using is a brand new 1.78.0, compiled for use with deal.ii. As far as I can tell the compile for Boost worked correctly.
OS is CentOS 7.5
GCC is 10.1.0

This is my first time posting here; apologies if I've not followed some guideline correctly.

Thank you for any help

**Comment by marcfehling** [comment]
We have issues with `boost` versions 1.77 and 1.78 currently.

Until we found a solution, please configure deal.II with the option `DEAL_II_FORCE_BUNDLED_BOOST` as described [here](https://www.dealii.org/current/users/cmake_dealii.html#configurefeature).

See also #13037.

**Comment by marcfehling** [comment]
`cmake` configuration on my machine succeeds with `boost 1.78.0` and `gcc 11.1.0` on the `master` branch, as well as with the official `dealii 9.3.3` tarball. I can not produce your problem.

You said you "compiled" boost yourself to be used with `deal.II`. You need to build the `iostreams` part for serialization separately [as the documentation suggests](https://www.boost.org/doc/libs/1_78_0/more/getting_started/unix-variants.html#header-only-libraries). I guess something might went wrong here.

I would suggest to use either the bundled version of boost, or the one that your cluster provides. There is no need to use the most recent version.

**Comment by jonathonmckay** [comment]
Thank you for the quick replies. I'll try making sure IOStreams is built, or perhaps try an older version.
Also, I guess I forgot to mention yesterday when posting (it was the end of the day), but I am actually the administrator of the cluster, so the "one that the cluster provides" is whatever I feel needs to be provided to get things done 😃 .

I'll comment again when I've had chance to try these things (Getting close to holidays, so my hours are getting weird.)

Thanks again

**Comment by jonathonmckay** [comment]
So, it turns out I was needing Deal.II to compile another application, which was giving me no end of grief. I was mistakenly lead to believe the problem was the relationship between how I had Boost and Deal.II configured and built. However, after some more digging with the other application, I discovered that it was actually a different problem, and have found the solution. Thank you for you time.

**Comment by jonathonmckay** [comment]
For reference: [https://github.com/prisms-center/plasticity/issues/38](url)
