### ISSUE TITLE
CMake custom target command contains `rm`, which is not available under windows.

### ISSUE THREAD

**Issue by metorm** [dealii/dealii#13122]
Hi all, I noticed that in CMake file `dealii-9.3.2\tests\quick_tests\CMakeLists.txt` line 70, there is a custom target command:

```
  # this is a hack to make sure the -OK file is deleted
  # even if compilation fails.
  ADD_CUSTOM_TARGET(kill-${_target}-OK
        COMMAND rm -f ${_target}-OK
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )
  ADD_DEPENDENCIES(${_target} kill-${_target}-OK)
```

There is no `rm` under windows so the command causes an error during compile time, some how like this:

```
错误	MSB8066	“C:\dev\lib\dealii-9.3.2\build\CMakeFiles\fefbd9a78064f122d16a257bb6e50851\kill-tbb.release-OK.rule”的自定义生成已退出，代码为 9009。	kill-tbb.release-OK	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	242	
```

Maybe using `file(REMOVE [<files>...])` or `file(REMOVE_RECURSE [<files>...])` instead would make thing more portable,

**Comment by marcfehling** [comment]
> Maybe using `file(REMOVE [<files>...])` or `file(REMOVE_RECURSE [<files>...])` instead would make thing more portable,

That sounds reasonable to me.

Do you want to give it a try and fix it? For more information, follow our [contributing](https://github.com/dealii/dealii/blob/master/CONTRIBUTING.md) guidelines. We would welcome your patch!

**Comment by tamiko** [comment]
@metorm Good catch - we have a number of left overs like this in the code base. Would you mind giving the following a try:
```
ADD_CUSTOM_TARGET(reset-${_target}-OK
  COMMAND ${CMAKE_COMMAND} -E rm -f ${_target}-OK
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )
  ADD_DEPENDENCIES(${_target} removel-${_target}-OK)
```
I'd also prefer to rename the target to `reset-${_target}-OK`...

**Comment by metorm** [comment]
@tamiko Yes, the new code is running smoothly, though I didn't quite get why the new code also has an 'rm' but still runs with windows ...

**Comment by bangerth** [comment]
`cmake -E rm` tells `cmake` to execute whatever command it is on a given platform that removes a file. `cmake` does the translation itself.

@tamiko did it this way because when you say `FILE(REMOVE ...)`, then this is executed at the time when you run the `cmake` script. But you want it to be executed at the time when you run `make`, so you have to hook it into the `COMMAND` part of the target.

**Comment by metorm** [comment]
@bangerth Got it, thanks a lot.
