### ISSUE TITLE
Code Gallery

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1314]
As discussed during the workshop, we would like to introduce a place where people can contribute code examples with less strict requirements than the tutorial steps (introduce a new feature, long description, etc.). The idea is to set the bar as low as possible, while still being useful. To not turn into a code dump, we would have to update them with each deal.II release so they still compile, but we won't clean/improve the code further. 

Part of a submission would be:
- a name
- the source code including a CMakeLists.txt ("cmake .; make run" should do something useful)
- list of authors with email addresses
- a one sentence description
- a ~1 page description that contains the problem, equations, setup
- a few pictures of solutions if possible
- a list of tutorial steps you built on or are recommended for understanding
- a list of references (papers, URLs, youtube links, ...)
- Changes section: short list of initial submission and each update with date
- accept to put all of this under the GPL 2+ (can we allow other licenses?)

This we still need to decide on:
- Should we require a test suite? We need at least some kind of checkable output when you do "make run" so we can make sure the code still works if we do a new release.
- Hosting: I vote for a separate git repo under the dealii organization. Contributions/updates can be done using pull requests.
- How to display the individual projects: we need formula typesetting, so maybe Doxygen? Or a pdf?
- Provide a way to give feedback or a place for discussion: github wiki? One github issue for each program? Just use the mailinglist?
- Can we figure out a way to make the individual programs citable and include this in the description? zenodo? figshare? Other options? With zenodo you get a doi to a git repo/commit, but sadly not to the description and not to an individual folder inside a repo. A unique URL to the description would also be useful so we can link from say the deal.II steps to this.

**Comment by bangerth** [comment]
>   * Should we require a test suite? We need at least some kind of checkable
>     output when you do "make run" so we can make sure the code still works if
>     we do a new release.

Let's keep the requirements low. It doesn't happen very often that we break 
the *correctness* of code in ways not caught by the testsuite. Let's simply 
strive to keep things compiling.


>   * Hosting: I vote for a separate git repo under the dealii organization.
>     Contributions/updates can be done using pull requests.

Yes.


>   * How to display the individual projects: we need formula typesetting, so
>     maybe Doxygen? Or a pdf?

The github wiki doesn't allow formulas, right? If not, let's for the moment 
just ask for either an HTML or PDF document. If people want to, they can use 
MathML for the former.


>   * Provide a way to give feedback or a place for discussion: github wiki? One
>     github issue for each program? Just use the mailinglist?

Dunno. Do we allow people to edit the github wiki?
	

>   * Can we figure out a way to make the individual programs citable and
>     include this in the description? zenodo? figshare? Other options? With
>     zenodo you get a doi to a git repo/commit, but sadly not to the
>     description and not to an individual folder inside a repo. A unique URL to
>     the description would also be useful so we can link from say the deal.II
>     steps to this.

I don't feel strongly about this, but I think that if you want something that 
is citable (with tracked reference metrics), submit to ANS. I have written 
plenty of papers in which I have referenced tutorial steps, and that seems to 
have worked.

We'll have to have a script that puts all of this onto the deal.II website 
anyway, so linking from deal.II itself shouldn't be a problem.

**Comment by tamiko** [comment]
> Let's keep the requirements low.

Submitted modules must be certified according to FIPS 140-2 Level 4.


>>   * Hosting: I vote for a separate git repo under the dealii organization.
>>     Contributions/updates can be done using pull requests.
>
> Yes.

Seconded.


> Do we allow people to edit the github wiki?

I'm not sure. I think we do.

**Comment by bangerth** [comment]
> Submitted modules must be certified according to FIPS 140-2 Level 4.

Submitting organizations also have to be ISO 9000 certified.

**Comment by drwells** [comment]
I would like to propose a program (well, four of them) for the gallery. I wrote a sequence of convection-diffusion-reaction solvers a few months ago to better understand the Trilinos bindings and AMR. A few people at the workshop asked questions that I was able to answer by referring them to this, so I think putting it somewhere official would be valuable.

Is there a submission process for this? I need to write some more documentation (and include pictures) but the code is pretty clean and I think it is close. It is available at

https://github.com/drwells/dealii-cdr/

**Comment by bangerth** [comment]
@drwells -- I will need to draw up a page that describes the gallery and what we require for this. It would actually be easiest if I had something that I could use to already test some of the scripts I intend to write, so why don't we just go ahead with your programs :-)

Do you plan to submit these as four different code gallery steps (which can reference each other) or one? In either case, please clone https://github.com/dealii/code-gallery and submit one or more pull requests that contain your codes. For now, let's propose the following top-level structure for the directories and files you will submit (in the one directory, if all four programs will simply be part of one code gallery piece; or in each of the four directories if you have multiple submissions):

1. Top level directory is simply a number, starting at `1` (because you're the first)
2. In each directory, you need a subdirectory `doc` that contains:
    * a file `builds-on` that contains a list of "step-x step-y" with whitespace separation; it can also contain "gallery-x" where "x" is the number of an existing gallery program
    * a file `tooltip` that contains a one-line description of your program
    * a file `author` that contains your name (and that of other authors) in the form "David R. Wells <drwells@email.com>", one per line
    * a file `dependencies` that contains a whitespace separated list of cmake names that need to be set for this program to be usable; for example, if your program requires PETSc, then this list needs to include `DEAL_II_WITH_PETSC`.
3. A top-level `CMakeLists.txt` that can be called via
```
  cmake -DDEAL_II_DIR=...  .
```
4. Whatever else you think you want to throw into this directory (including the source files) is left up to you.

I imagine that we need a few more steps later, but let's get this started and see what else I need

**Comment by drwells** [comment]
Got it. Most of this should be easy, but cleaning up the build configuration (I have four executables that share some common files) might take a few days.

**Comment by bangerth** [comment]
OK. It may simply be easiest in that case to leave it all as part of the same code gallery directory.

**Comment by bangerth** [comment]
I've hooked the code gallery into the websites now, both for the doxygen generated pages and for the front page http://www.dealii.org.

**Comment by bangerth** [comment]
I think all of the big steps necessary for this are now done.
