### ISSUE TITLE
We are not yet compatible with SUNDIALS 6.0

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#13166]
I installed it yesterday and it looks like SUNDIALS is now thread-safe and requires that we attach a context object `SUNContext` to each object - as such every constructor function is now different.

See

https://github.com/LLNL/sundials/blob/74b6be71f3d733cc93a2bcbefd6c37b7b0db3341/doc/shared/sundials/SUNContext.rst

for more information.

**Comment by bangerth** [comment]
See also here: https://github.com/LLNL/sundials/issues/109

**Comment by bangerth** [comment]
Working on this.

**Comment by bangerth** [comment]
It compiles now, but it isn't fixed yet.

**Comment by kronbichler** [comment]
@drwells @bangerth has this been addressed by #13793 or is this still on our todo list for the release?

**Comment by drwells** [comment]
This is fixed by #13903 and #13918.
