### ISSUE TITLE
Extend MeshWorker::ScratchData to support hp

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#13171]
I'm wanting to extend `MeshWorker::ScratchData` so that it is compatible with the hp data structures (so, `hp::MappingCollection`, `hp::FECollection`, `hp::QuadratureCollection`). I can see at least three ways to do this:
1. Simply add the an hp variant of all `reinit()` functions to the existing `MeshWorker::ScratchData`, and add  pointers to the `hp::FEValues`-type objects. This way, both the hp and non-hp FEValues object will share the pointers to the _active_ FEValues objects (what we call `current_fe_values` in the implementation).
2. Split the current `MeshWorker::ScratchData` implementation into a base class and derive a non-hp variant and implemented a newly derived `hp::ScratchData`. The base class would hold the `GeneralDataStorage`s, DoF indices, update flags and pointers to the _active_ FEValues objects. The derived classes would then have pointers to the global FEValues objects.
3. Write a brand new `hp::ScratchData` that mirrors `MeshWorker::ScratchData`. (not a practical solution, in my opinion)

Note that there is not yet an hp variant of `FEInterfaceValues`. Maybe this causes some complications...

I'm leaning towards option 1 at this point, but I thought I'd gather more opinions before moving on with a prototype implementation. @luca-heltai, have you ever thought about doing this, and if so then did you have any solid ideas on how you'd have wanted to accomplish this?

**Comment by luca-heltai** [comment]
I would go for 1), in the spirit of the existing implementation.
:)

**Comment by luca-heltai** [comment]
> Note that there is not yet an hp variant of FEInterfaceValues. Maybe this causes some complications...

This should not be a problem for the first round. It would not be possible at this moment to have the FEInterfaceValues stuff, but we could still have FEFaceValues, and FESubfaceValues.
