### ISSUE TITLE
Linker problem when compiling step-20

### ISSUE THREAD

**Issue by lihanyu234** [dealii/dealii#13193]
Hi,

I recently try to compile step-20 on MacOS Monterey but it gave me the following linker problem. Can you help me solve it?

Regards,
<img width="1431" alt="Screen Shot 2022-01-07 at 1 30 08 PM" src="https://user-images.githubusercontent.com/31542034/148598409-13c3ac3f-4414-413f-9884-244df37d40b6.png">

**Comment by bangerth** [comment]
I believe that this is a result of the warning about the directory not found at the vert top. Did you forget to properly load the deal.II package?

**Comment by bangerth** [comment]
@lihanyu234 Any news?

**Comment by drwells** [comment]
I don't think there's anything we can do here - I'm closing as stale.
