### ISSUE TITLE
`Patterns::Tools::Convert::to_value()` does not work with `std::array`.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#13218]
Reported in https://github.com/dealii/dealii/pull/13028#discussion_r781463862.

When using a `std::array` as an argument for a `GridGenerator` function to be used with [`GridGenerator::generate_from_name_and_arguments()`](https://www.dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#a1e6c4dcc63863449f08a78a22ec73747), compilation errors like the following occur
```
.../dealii/include/deal.II/base/patterns.h:1823:13: error: ‘struct std::array<std::pair<dealii::Point<1, double>, double>, 3>’ has no member named ‘insert’
 1823 |           t.insert(t.end(),
      |           ~~^~~~~~
```
which refer to these lines
https://github.com/dealii/dealii/blob/caa4cced40ae951345fe4367b764599ce9851444/include/deal.II/base/patterns.h#L1821-L1824

Compilation succeeds when using a `std::vector` instead.

Is there a different operation than `insert` we can use which is also available for `std::array` and other container types?

---

Once this has been resolved, we can turn the `openings` parameters of `GridGenerator::pipe_junction()` from a `std::vector<T>` to a `std::array<T, 3>`.

**Comment by bangerth** [comment]
Would be nice to get this fixed before 10.0 so that we don't have to change the interface in a backward incompatible way.

@luca-heltai ?
