### ISSUE TITLE
The 9.3.3 release

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#13228]
Now that we have the oneAPI TBB, Boost.Geometry, and SUNDIALS + MPICH fixes in we should put together another point release. A bunch of OSs (including [FreeBSD](https://github.com/dealii/dealii/issues/11561), [openSUSE](https://github.com/bmwiedemann/openSUSE/commit/bf7747643df6c67e11c881b76cd5484b7e8b5401), and [Arch Linux](https://aur.archlinux.org/packages/deal-ii/)) already need these patches - I am sure there are others that I don't now about too.

Are there any other fixes we have done which are worth porting? Those three are already in the 9.3 branch.

**Comment by tamiko** [comment]
I am happy to tag a release on Friday (or so) after we merged some remaining compatibility fixes :smiley:

**Comment by marcfehling** [comment]
I would also like to compile the library again with `Intel 18` and `Intel 19`, just to make sure that everything is in shape.

**Comment by marcfehling** [comment]
> I would also like to compile the library again with `Intel 18` and `Intel 19`, just to make sure that everything is in shape.

Successfully compiled deal.II with `Intel 18/TBB 18` and `Intel 19/TBB 20` on `stampede2`.

Our build system has trouble locating `Intel MPI` and `Intel MKL` on that machine, so I only verified compilation with the `Intel` compilers and `TBB`.

**Comment by drwells** [comment]
See also #13284.

**Comment by tamiko** [comment]
@drwells Release tomorrow?

**Comment by drwells** [comment]
Lets do it :)

**Comment by tamiko** [comment]
\o/

**Comment by drwells** [comment]
I don't see, on cdash, that we actually ran tests for 8c474271f5ca09dc8f030c6de5fa5f73397f9298: see https://cdash.43-1.org/build/9676 et al. Was that deliberate?

**Comment by tamiko** [comment]
@drwells We are running the testsuite on 8c47427 as we speak, see https://cdash.43-1.org/index.php?project=deal.II (and sort by Start time). It is just that we haven't made it past the build tests yet :smile:

**Comment by tamiko** [comment]
Build tests:

| Host | Configuration | Commit | Build errors | Build warnings | Failing tests | Passing tests |
| - | - | - | :-: | :-: | :-: | :-: |
| tester | [Clang-12.0.0-dealii-9.3-unity_build](https://cdash.43-1.org/buildSummary.php?buildid=9673) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9673) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9673) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9673) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9673) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9673) |
| tester | [Clang-12.0.0-dealii-9.3-all_components](https://cdash.43-1.org/buildSummary.php?buildid=9674) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9674) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9674) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9674) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9674) | [6](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9674) |
| tester | [Clang-12.0.0-dealii-9.3-no_mpi](https://cdash.43-1.org/buildSummary.php?buildid=9675) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9675) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9675) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9675) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9675) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9675) |
| tester | [Clang-12.0.0-dealii-9.3-cpp20](https://cdash.43-1.org/buildSummary.php?buildid=9676) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9676) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9676) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9676) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9676) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9676) |
| tester | [Clang-12.0.0-dealii-9.3-cpp17](https://cdash.43-1.org/buildSummary.php?buildid=9677) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9677) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9677) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9677) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9677) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9677) |
| tester | [Clang-12.0.0-dealii-9.3-cpp14](https://cdash.43-1.org/buildSummary.php?buildid=9678) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9678) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9678) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9678) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9678) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9678) |
| tester | [Clang-11.1.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9679) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9679) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9679) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9679) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9679) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9679) |
| tester | [Clang-10.0.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9680) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9680) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9680) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9680) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9680) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9680) |
| tester | [Clang-9.0.1-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9681) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9681) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9681) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9681) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9681) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9681) |
| tester | [Clang-8.0.1-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9682) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9682) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9682) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9682) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9682) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9682) |
| tester | [Clang-7.1.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9683) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9683) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9683) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9683) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9683) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9683) |
| tester | [Clang-6.0.1-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9684) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9684) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9684) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9684) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9684) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9684) |
| tester | [Clang-5.0.2-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9685) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9685) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9685) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9685) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9685) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9685) |
| tester | [GNU-10.3.0-dealii-9.3-cpp20](https://cdash.43-1.org/buildSummary.php?buildid=9686) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9686) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9686) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9686) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9686) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9686) |
| tester | [GNU-9.3.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9687) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9687) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9687) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9687) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9687) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9687) |
| tester | [GNU-8.4.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9688) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9688) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9688) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9688) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9688) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9688) |
| tester | [GNU-7.4.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9689) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9689) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9689) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9689) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9689) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9689) |
| tester | [GNU-6.5.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=9690) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9690) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9690) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9690) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9690) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9690) |
| tester | [GNU-8.3.0-dealii-9.3-debian-10](https://cdash.43-1.org/buildSummary.php?buildid=9691) | [8c4742](https://cdash.43-1.org/viewUpdate.php?buildid=9691) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=9691) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=9691) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=9691) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=9691) |

**Comment by tamiko** [comment]
Still waiting for the rest of the testsuite...
