### ISSUE TITLE
Compilation error in Boost when compiling application using Deal.II, CUDA & C++11

### ISSUE THREAD

**Issue by kalj** [dealii/dealii#1323]
I'm trying to compile a code that uses Deal.II together with CUDA, using the nvcc compiler. It works fine as long as I have c++11 shut off (DEAL_II_WITH_CXX11=OFF), but if I enable it, and configure nvcc to allow for c++11, I get a compilation error inside Boost.

Here is the error message:

    /home/kalle/sw/deal.II/include/deal.II/bundled/boost/utility/detail/result_of_iterate.hpp:148:75:
    error: invalid use of qualified-name
    ‘std::allocator_traits<_Alloc>::propagate_on_container_swap’
       ) type;

And then 16 more identical errors on the same line of code. The code that is referred to is the following,

    template<typename F BOOST_PP_ENUM_TRAILING_PARAMS(BOOST_PP_ITERATION(),typename T)>
    struct cpp0x_result_of_impl<F(BOOST_PP_ENUM_PARAMS(BOOST_PP_ITERATION(),T)),
                                typename result_of_always_void<decltype(
                                    boost::declval<F>()(
                                        BOOST_PP_ENUM_BINARY_PARAMS(BOOST_PP_ITERATION(), boost::declval<T, >() BOOST_PP_INTERCEPT)
                                    )
                                )>::type> {
      typedef decltype(
        boost::declval<F>()(
          BOOST_PP_ENUM_BINARY_PARAMS(BOOST_PP_ITERATION(), boost::declval<T, >() BOOST_PP_INTERCEPT)
        )
      ) type; // < Here I get the error
    };

What could be the cause of this? I have difficulties even understanding the code and the connection to the error message.

**Comment by Rombur** [comment]
Which version of CUDA are you using? I have also had some cryptic errors with BOOST::uBLAS and CUDA 7 It seems that they are some compatibility problems between CUDA and BOOST :/

**Comment by kalj** [comment]
I am using cuda 7 specifically since that is where c++11 support was introduced. Are your errors similar or similar in nature to this? It would be interesting to try to find a minimal failing example.

**Comment by Rombur** [comment]
This is the error that I got:
http://sourceforge.net/p/viennacl/mailman/viennacl-support/thread/55B6900A.9010301%40gmail.com/#msg34323060

There is nothing that we can do about it except wait for Nvidia to make a better compiler.

**Comment by kalj** [comment]
Okay, that looks somewhat different.

I managed to find a minimal example without Boost clearly showing that it is indeed a compiler bug:

http://stackoverflow.com/questions/31969644/compilation-error-with-nvcc-and-c11-need-minimal-failing-example

As suggested, it is fixed in the nvcc 7.5 RC.

Also, a quick fix for compiling with boost / deal.ii is to define the macro BOOST_RESULT_OF_USE_TR1. 

Are your problems also fixed in 7.5 RC?

**Comment by Rombur** [comment]
In my case it was easy to get ride of BOOST. I haven't tried with nvcc7.5 yet.
