### ISSUE TITLE
Cannot find the header files when compiling with WSL Linux distributive in VS code

### ISSUE THREAD

**Issue by keassyguang** [dealii/dealii#13242]
Hi, everyone. I'm not sure if I can ask a question here, but I did have trouble configuring the deal.ii.

I am trying to compile the program for Linux in VS code (version 1.63.2) using WSL (Windows Subsystem for Linux) ubuntu 20.04.3. I successfully compile the "Hello, World!" program, but when I try to compile the tutorial programs shown in dell.ii documentation, such as the step-1,  the compilation terminated with an error message "No such file or directory". Then, the system includePath in VS code has been set to "/usr/include/**" and other libs as shown in the below figures, however, it dosenot work.  

![image](https://user-images.githubusercontent.com/95268913/149619238-05af667c-be69-4e4b-b114-8f21a95d2517.png)
![image](https://user-images.githubusercontent.com/95268913/149619306-8c83f4d6-a820-45ad-baac-8c5cc9bffbc1.png)

Later, I manually edit some head files. For example, as shown in the below figure, I know the "Kokkos_MasterLock.hpp" file is in the directory of "/usr/include/trilinos", so I modified the 55th line of "Kokkos_Core_fwd.hpp" file by adding the "trilions" directory into the path "#include <trilinos/Kokkos_MasterLock.hpp>" (the original is "#include <Kokkos_MasterLock.hpp>"). After that, the compiler can find the "Kokkos_MasterLock.hpp" file, however, the compilation terminated with another new file named "Kokkos_Macros.hpp". Truly, I can edit the path as the aforementioned method, it is impossible to edit all the files using this way. So, can someone tell me how to compile the program for Linux in VS code using WSL? It will be of great help to me.

![image](https://user-images.githubusercontent.com/95268913/149527915-a4ba165b-0401-4d74-b919-0ba40683ff76.png)
![image](https://user-images.githubusercontent.com/95268913/149618722-a531aa1c-0f29-4f71-9e01-ae0f79ad34c9.png)
![image](https://user-images.githubusercontent.com/95268913/149618877-ba433b45-c563-4ce9-ac83-99b031c3a169.png)

**Comment by drwells** [comment]
There's a lot of things in here that don't pertain to deal.II - in particular, the way Trilinos gets installed under WSL is outside of our control. Could you post this again to the deal.II mailing list? That's a better fit for a question like this.

**Comment by tamiko** [comment]
@keassyguang Did you install all dev packages of all dependencies? (easiest to run `sudo apt install libdeal.ii-dev` on the ubuntu console)

**Comment by keassyguang** [comment]
> There's a lot of things in here that don't pertain to deal.II - in particular, the way Trilinos gets installed under WSL is outside of our control. Could you post this again to the deal.II mailing list? That's a better fit for a question like this.

 I am really sorry for posting this problem here. And thanks for your advice, I will post it to the deal.II mailing lists.

**Comment by keassyguang** [comment]
> @keassyguang Did you install all dev packages of all dependencies? (easiest to run `sudo apt install libdeal.ii-dev` on the ubuntu console)

@tamiko It seems that all dev packages of all dependencies have been installed.
![image](https://user-images.githubusercontent.com/95268913/149651587-2ff331f0-3392-4f47-a573-ef4d5c3d5e6f.png)

**Comment by drwells** [comment]
Update: this moved to the mailing list

https://groups.google.com/g/dealii/c/EJKGT-rfnZw/m/qt_rsgkQCAAJ

and a solution was posted. @keassyguang the more important thing is that your issue gets fixed - more people use VS code on the mailing list than here so its a better place to discuss this topic.

Since this is on the mailing list I'll close this issue - we will continue the discussion there.
