### ISSUE TITLE
Make autocompletion of "cell->" work

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1325]
We should figure out which part of our (complicated) inheritance structure obstructs eclipse (and other IDEs) from offering useful autocompletion.

**Comment by tjhei** [comment]
works for Triangulation using clang autocomplete in qtcreator: https://plus.google.com/+TimoHeister/posts/GefH5Gq1qxp but not for DoFHandler

**Comment by tjhei** [comment]
crying a little inside:

![vs_autocomplete](https://cloud.githubusercontent.com/assets/1531285/11451917/d00861be-95a3-11e5-854e-7efdf74fa10d.png)

**Comment by bangerth** [comment]
:+1:

**Comment by drwells** [comment]
It sounds like this is IDE-dependent - it's outside our control.
