### ISSUE TITLE
Follow-ups to the introduction of `is_detected`

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13295]
#13291 introduces the `is_detected` type trait. I think that name is not particularly good and would see what people think about renaming it. In essence, you use that trait as in
```
  template <typename T>
  using get_mpi_communicator_t = decltype(std::declval<T>().get_mpi_communicator());

  template <typename T>
  void foo () {
    if constexpr (is_detected<get_mpi_communicator_t, T>::value) { ... }
  }
```
that is, it figures out whether one can call a member function `get_mpi_communicator()` on an object of type `T`.

Two questions about this:
* `is_detected` is the name originally chosen in the project from which the code was copied, but we do not need to remain bound to that name. Would people favor `is_supported_operation` better, for example? I think `is_detected` is just a bit too generic.
* The name `is_detected` suggests a predicate that is either `true` or `false`, but it is really a class with a member variable `value` of type `bool` that one can query. Since we can now have templated variables, this change would not be difficult to make: instead of
```
template <template <class...> class Op, class... Args>
  using is_detected = typename detected_or<nonesuch, Op, Args...>::value_t;
```
we would have
```
template <template <class...> class Op, class... Args>
  bool is_detected = detected_or<nonesuch, Op, Args...>::value_t::value;
```
or whatever name we choose for `is_detected`. The same could be done to the other predicates introduced in #13291.

@masterleinad -- for your special attention, given that you wrote #13291.

**Comment by masterleinad** [comment]
`is_detected` is part of the C++ technical specifications, see https://en.cppreference.com/w/cpp/experimental/is_detected and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4617.pdf, and thus recognized by its name. Given that we are implementing exactly that, I think there is value in keeping the name and the interface.
We could of course build on top of that interface to say
```
template <template <class...> class Op, class... Args>
bool is_supported_operation = is_detected<Op, Args....>::value;
```
or similar.

**Comment by bangerth** [comment]
OK. Maybe I will move `is_detected` into the namespace introduced in #13296 and make `is_supported_operation` the operation available in the place of the current `is_detected`. The use of a boolean predicate is also much closer to how concepts are used, and will be easily replaceable by a concept once we have C++20.

**Comment by masterleinad** [comment]
That's fine with me. I think finding a good name to replace `is_detected` is difficult since its use can cover a wide range. You can check for the existence of certain types or functions within a given class and optionally evaluate them if they exist. 
Maybe, rather something like `has_type_or_function`? Honestly, I don't think that the existing name is too bad.

**Comment by bangerth** [comment]
You're right that it all depends on what `Op<Args...>` actually represents, that is, what kind of operation the template alias `Op` actually tests. My choice of name was based on the fact that `Op` encodes some kind of operation.
