### ISSUE TITLE
Compilation problem with MS Visual Studio

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1329]
As originally reported by @l-korous in #1321: 

1 more thing - MSVC is unhappy about FE_PolyFace class template - I believe it may be because the instantiations of this template are not explicitely specified. I wonder why it is so, I can try to debug it, but this is my first guess.

```
14>C:\hpfem\dealii\include\deal.II/fe/fe_poly_face.templates.h(95): error C2244: 'dealii::FE_PolyFace::get_data' : unable to match function definition to an existing declaration
14> definition:
14> 'dealii::FiniteElement::InternalDataBase *dealii::FE_PolyFace::get_data(const dealii::UpdateFlags,const dealii::Mapping &,const dealii::Quadrature &) const'
14> existing declarations:
14> 'dealii::FiniteElement::InternalDataBase *dealii::FE_PolyFace::get_data(const dealii::UpdateFlags,const dealii::Mapping &,const dealii::Quadrature &) const'
```

-->> the definition and declaration are identical, this is what I meant by not making much sense, and it is why I deemed it may be an instantiation issue :-)

**Comment by bangerth** [comment]
Yes, this makes no sense. I see no reason for the error, but I think this is not related to instantiations. My best guess would be that the compiler issues the error message already when it first reads through the code top to bottom and finds this function (i.e., before the function is ever used). Are there any error messages *above* this? Any context that shows how the compiler got there (such as "instantiated from..., instantiated from..., etc")?

**Comment by l-korous** [comment]
I tried to look for any more messages. This is all there is to it though.
If I were to try to explicitly specify the instantiations, what should they
be?

**Comment by bangerth** [comment]
That's exactly the problem -- you don't know which polynomial space this class is going to be instantiated with.

The functions are all relatively small. Can you try to attach the definition inline to the declaration in the header file? That's not our preferred style, but it may at least get around the problem...

**Comment by l-korous** [comment]
I tried what you suggested - it compiles - I only had to add #include <... quadrature.h> to fe_poly.h in order to get rid of an "use of undefined type" error. I will send a pull request in a minute.
