### ISSUE TITLE
automated performance tester

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1333]
The automated benchmarking server I ran died with our switch to git last year. I need to get it running again.

I have an initial version here: http://www.math.clemson.edu/~heister/bench.html (not automated completely yet). You probably need to hide "test_assembly:create matrix and vectors" by clicking on it in the legend. You can zoom into the graph to see the recently merged pull requests. I still need to pick better reference times for each output.

I am looking for some feedback on how I can make the output more reliable and more useful.

**Comment by bangerth** [comment]
I think the reference times are making it hard to compare right now because they're clearly not reliable. Other than that, how is "slowdown" defined? As the ratio of new over old run time? I would have thought slowdown would also subtract 100% from the ratio.

**Comment by Rombur** [comment]
I think it would be easier to read if you just output the time in seconds. Maybe you could take a look at what Cray does with Chapel: http://chapel.sourceforge.net/perf/chap04/?suite=performancetracking and here is the program that they are using http://chapel.sourceforge.net/perf/dygraphs-readme.html I don't know if it is easier or harder to use than what you currently have.

**Comment by tjhei** [comment]
> reference times are making it hard to compare

Yes. It is a bit surprising to me that the times vary a lot even though the machine is idle, I disabled multithreading, and I am running each program 5 times and take the minimum time. I wonder if it would be be better to increase the output accuracy of TimerOutput. Another reason is certainly that some of the timed sections are too short to be reliable. 

> Other than that, how is "slowdown" defined? As the ratio of new over old run time?
yes, wrong wording on my end.

>  if you just output the time in seconds
That requires being smarter with the test programs, I think. Here it is: http://www.math.clemson.edu/~heister/bench2.html (ignore the tooltips and y axis labels, everything is in seconds now)

**Comment by bangerth** [comment]
On 08/12/2015 09:18 PM, Timo Heister wrote:
>     reference times are making it hard to compare
>
> Yes. It is a bit surprising to me that the times vary a lot even though the
> machine is idle, I disabled multithreading, and I am running each program 5
> times and take the minimum time. I wonder if it would be be better to increase
> the output accuracy of TimerOutput. Another reason is certainly that some of
> the timed sections are too short to be reliable.

I meant the fact that you had set the "reference time" to a date somewhere in 
2014 but the data points at that time seemed off with regard to both the 
previous data point and to current data. Why don't you just declare "now" your 
reference time?

**Comment by tjhei** [comment]
The reference time was the 8.2.1 release (but using 8.3 doesn't make a difference).

**Comment by bangerth** [comment]
> The reference time was the 8.2.1 release (but using 8.3 doesn't make a
> difference).

So are we really consistently slower in *all* operations? Or are your 
baselines simply a fluke? I recall that the earliest picture I saw in this 
thread also had results for an even earlier version of deal.II (8.1?) which 
was pretty much exactly on par with 8.3 for all timings, but that 8.2.1 was 
the outlier. That led me to suspect that the 8.2.1 baselines were off, whereas 
in reality all versions are about equal in performance.

**Comment by tjhei** [comment]
I switched back to show relative speed, see http://www.math.clemson.edu/~heister/bench.html

I think all tests that appear to be slower are within tolerance.

**Comment by bangerth** [comment]
But at least the red curve for TableHandler::write seems wrong in 8.2.1. It is back to the same speed now as it was for 8.1. I think if you manually adapt the timing of this one data point for 8.2.1, we'd have a much cleaner graph. That operation is so short that I think the data point for 8.2.1 is simply a fluke.

I do like that assembly got 50% faster in early August. I wonder what caused that...

**Comment by bangerth** [comment]
Or just remove that one line -- it's wildly unreliable anyway...

**Comment by bangerth** [comment]
Hm, I'm trying to figure out what caused the speedup, but the August 1 revision (03d9ec9) doesn't seem to exist. Where did that revision come from?

**Comment by tjhei** [comment]
I am only testing a few revisions back and I manually added the releases. The revision you are looking at is the 8.3 release. So the change happened somewhere between 8.3 and August 6.

Let me just rerun the older versions so we can pinpoint it easily.

**Comment by bangerth** [comment]
That would be awesome. I see a learning opportunity to find something that actually worked!

**Comment by tjhei** [comment]
Well, I changed the problems to report wall_time instead of CPU_time and rerun everything from around 8.3 here: http://www.math.clemson.edu/~heister/bench.html I also moved back to seconds, because relative timings are just too confusing.

Sadly it looks like timings are not very reliable, for example it is impossible that #3c0b904 or #eb2631e introduced some change in performance.

**Comment by bangerth** [comment]
Yes, I tried to figure this out as well -- too bad it is not as informative as one would hope. But I think it's still useful.

Walltime makes sense because it allows us to measure the effects of parallelizing stuff.

**Comment by tamiko** [comment]
@thei - have you tried to use the median out of X runs (for individual measurements)?

**Comment by tamiko** [comment]
@tjhei - Further, if individual operations are too fast, why not slow them down artificially by repeating the operation multiple times?

**Comment by tjhei** [comment]
1. I disable all multithreading because I would think it makes things more deterministic. That means we won't see improvements when we parallelize things. @bangerth, do you want me to undo this?
2. I am running each program 5 times and take the minimum wall time for each section reported by TimerOutput. I think the minimum is better than an average.
3. Yes, repeating or slowing down (by increasing the problem size) individual segments is a good idea. Maybe we need to sit down and define better tests altogether.

See https://github.com/tjhei/gitautotester/tree/dealii-benchmark for the tests.

**Comment by bangerth** [comment]
I can live with single-threaded tests, though I plan on doing a lot more multithreading.

**Comment by kronbichler** [comment]
I think it would make sense to do some multithreading performance tests to reward progress in that direction, but in my opinion it could be limited to a few tests with 'initialize' and 'assembly' components.

Regarding the quality of tests:
- Listing the details in several graphs would be nice, one "test" at a time. Interesting components would be step-22-2d, step-22-3d (based on test_assembly or step-22, depending on which one we find more convenient), test_sparse_matrix (the current test_poisson, augmented with a few SparseMatrix::SSOR). The other two tests (tablehandler and test_hp) are more specific and probably less valuable.
- Aiming for similar timings (on the order of 2-10 seconds) for each test in a graph would be helpful. This is what test_poisson aims at. I'd agree with @tamiko to repeating fast components.
- Besides the general workflow of our programs (tested in test_assembly), I'd like to test for other important components. Candidates are VectorTools::project, SolutionTransfer, KellyErrorEstimator. step-22 would be an interesting place to insert them. If you agree, I can have a look at that.

One more comment on the test results we currently have: I see a regression since 8.2, namely the access of DynamicSparsityPattern by the new iterations introduced in #790 and follow-ups. But that was on purpose. :-)

**Comment by tjhei** [comment]
I now pushed the source to https://github.com/dealii/performance-benchmarks so that it doesn't get lost. The deal.II website now links to the up-to-date results.

My todolist:
- clean up tests
- repeat certain operations that are too fast
- ithreading ni  asensible way
- rerun all revisions

**Comment by bangerth** [comment]
Is this issue at all still current? @tjhei links to a repo that hasn't seen activity in several years. I suspect that the action must be happening elsewhere these days, right?

**Comment by bangerth** [comment]
Related to #8852.
