### ISSUE TITLE
GMSH quad mesh with some cells with negative weight

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#13347]
I have a valid 2d mesh from GMSH that consists of two parts and GMSH decided to export half of the cells with a negative and half with a positive measure.

Reading it currently fails, but it works fine if we remove the AssertThrow:
https://github.com/dealii/dealii/blob/9df2fdc07c3d2c5f0f4ff700f9bbe6f5c65d58ab/source/grid/grid_tools.cc#L912

@singima is working on a patch with a test case.

**Comment by bangerth** [comment]
That is probably relatively easy to fix for a 2d mesh in 2d space. I don't know what to do about it for a 2d mesh in 3d, or in general a 3d mesh in 3d, though.

**Comment by tjhei** [comment]
> 3d mesh in 3d

For that case we also flip all cells with negative measure already. Why do you think that is an issue?

> I don't know what to do about it for a 2d mesh in 3d,

Same. The code for checking/changing measures currently only runs for dim=spacedim. For other cases we probably fail if we encounter negative cell measures, see #13346

**Comment by bangerth** [comment]
What do we do in 3d? Just swap the upper and lower four vertices? If we already do that, much the better of course!

**Comment by tjhei** [comment]
> Just swap the upper and lower four vertices?

https://github.com/dealii/dealii/blob/9df2fdc07c3d2c5f0f4ff700f9bbe6f5c65d58ab/source/grid/grid_tools.cc#L889-L896

**Comment by agrayver** [comment]
Maybe related #3201

**Comment by tjhei** [comment]
Indeed, thank you! @singima here you have a simple test case!

**Comment by tjhei** [comment]
fixed by #13444
