### ISSUE TITLE
Negative det in MappingFE on some simplex mesh

### ISSUE THREAD

**Issue by zjiaqi2018** [dealii/dealii#13346]
I imported a triangular mesh using `read_msh()`, but got negative det:
```
--------------------------------------------------------
An error occurred in line <1236> of file </home/jiaqi2/dealii/dealii/source/fe/mapping_fe.cc> in function
    dealii::CellSimilarity::Similarity dealii::MappingFE<dim, spacedim>::fill_fe_values(const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, dealii::CellSimilarity::Similarity, const dealii::Quadrature<dim>&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, dealii::internal::FEValuesImplementation::MappingRelatedData<dim, spacedim>&) const [with int dim = 2; int spacedim = 2; typename dealii::Triangulation<dim, spacedim>::cell_iterator = dealii::TriaIterator<dealii::CellAccessor<2, 2> >; typename dealii::Mapping<dim, spacedim>::InternalDataBase = dealii::Mapping<2, 2>::InternalDataBase]
The violated condition was: 
    det > 1e-12 * Utilities::fixed_power<dim>( cell->diameter() / std::sqrt(double(dim)))
Additional information: 
    The image of the mapping applied to cell with center [0.119706
    0.189866] is distorted. The cell geometry or the mapping are invalid,
    giving a non-positive volume fraction of -0.00946307 in quadrature
    point 0.

Stacktrace:
-----------
#0  /home/jiaqi2/dealii/installed/lib/libdeal_II.g.so.10.0.0-pre: dealii::MappingFE<2, 2>::fill_fe_values(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::CellSimilarity::Similarity, dealii::Quadrature<2> const&, dealii::Mapping<2, 2>::InternalDataBase const&, dealii::internal::FEValuesImplementation::MappingRelatedData<2, 2>&) const
#1  /home/jiaqi2/dealii/installed/lib/libdeal_II.g.so.10.0.0-pre: dealii::FEValues<2, 2>::do_reinit()
#2  /home/jiaqi2/dealii/installed/lib/libdeal_II.g.so.10.0.0-pre: void dealii::FEValues<2, 2>::reinit<false>(dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> > const&)
#3  /home/jiaqi2/dealii/installed/lib/libdeal_II.g.so.10.0.0-pre: void dealii::hp::FEValues<2, 2>::reinit<false>(dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> > const&, unsigned int, unsigned int, unsigned int)
#4  ./hptest: test(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#5  ./hptest: main
--------------------------------------------------------

```
@peterrum said that the mesh has normal showing in the negative z direction, which leads to the negative determinant. The mesh has to be reoriented, which should be simple in 2D, but complicated in 3D. 

This is the mesh
![image](https://user-images.githubusercontent.com/36655731/152249297-8450b7e9-e934-40e4-9bcb-b0ad3c664a76.png)

This is a test that reproduces this
https://github.com/zjiaqi2018/read-msh

**Comment by drwells** [comment]
This is a known bug (or rather, something we have not implemented yet):

https://github.com/dealii/dealii/blob/9df2fdc07c3d2c5f0f4ff700f9bbe6f5c65d58ab/source/grid/grid_in.cc#L562-L565

**Comment by peterrum** [comment]
> This is a known bug (or rather, something we have not implemented yet):

I would have hoped that the mesh-generation tools are doing this themselves...

**Comment by drwells** [comment]
I recall seeing a gmsh example once that set all the cells to have (in our opinion) negative measure: in this particular case I suspect that by changing two columns of vertex numbers in the input file we can use the file without problems.

I'm not sure how GMSH sets the orientation convention but I think it is consistent between elements.

**Comment by tjhei** [comment]
> I'm not sure how GMSH sets the orientation convention but I think it is consistent between elements.

It is not. Even with quads in 2d GMSH sometimes produces meshes with all negative or all positive measure. If you mesh a mesh with two pieces, this can also happen in the same file. We fail to read it right now. My student will open a PR with a fix soon. Maybe I should create an issue now...

**Comment by drwells** [comment]
The previous PRs fixed this so lets close the issue.
