### ISSUE TITLE
Test fe_nedelec_sz_hessian_divergence_theorem.debug times out

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13348]
#12771 adds a test that runs quite a long time and times out on my system. Running the test by itself, I get this for the run time:
```
time ./fe_nedelec_sz_hessian_divergence_theorem.debug 

real    45m12.124s
user    45m5.834s
sys     0m6.253s
```
That's just a tad over the 600 seconds the test suite allows for each test :-)

@kinnewig Do you think the test could be made smaller, for example by using a less refined mesh, so that it doesn't run as long? It would be nice to get the run time below a minute at most.

**Comment by bangerth** [comment]
Want to give this a try and implement a patch?

**Comment by kinnewig** [comment]
> Want to give this a try and implement a patch?

Yes,
I would just use the unrefined disk/sphere.

Or do you have any other suggestions?

**Comment by bangerth** [comment]
Give that a try. If that's not good enough, how high a polynomial degree do you go to in the test?

**Comment by kinnewig** [comment]
I just opened a pull request with the changes I suggested above #13349





> Give that a try. If that's not good enough, how high a polynomial degree do you go to in the test?

The test is already performed with the lowest order possible, which is in this case p=1. We can't use p=0 for the test, because in this case the test would not cover everything necessary.

**Comment by bangerth** [comment]
This brought the test down to 5min43s. That's still quite close to the threshold, and probably exceeds the threshold if the machine is under load. We'll just see how it goes.
