### ISSUE TITLE
Thoughts about the interface to query MPI data types?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13377]
#13367 moves the `mpi_type_id()` functions into the public headers. @tjhei beat me to it, but while doing this in an unsubmitted patch myself (which ended up being #13376) I was also thinking about whether the current interface is the best possible. We have in essence this:
```
    inline MPI_Datatype
    mpi_type_id(const char *)
    {
      return MPI_CHAR;
    }
```
with specializations for all data types supported by MPI. We originally wrote these as functions, but they are really type-translation mechanisms because we don't actually care what the argument points to -- all that matters is the *type*.

The traditional way to do this would actually have been using traits classes:
```
  template <typename T> struct MpiDataType;

  template <> struct MpiDataType<char> {
    static const MPI_DataType value = MPI_CHAR;
  };
```
and similar. A more modern approach would be with `constexpr` template variables:
```
  template <typename T> 
  constexpr MPI_DataType mpi_data_type = delete;

  template <> 
  constexpr MPI_DataType mpi_data_type<char> = MPI_CHAR;
```

Since we've only now made these things public, this would also be the time to pick the interface we want to use going forward. Thoughts? @tjhei ?

**Comment by tjhei** [comment]
I agree that the current interface is a bit awkward, especially because it requires passing a T*.
Feel free to change it to one of the two versions.

**Comment by tjhei** [comment]
@bangerth I am learning that ``internal::mpi_type_id`` has been in use in several projects, https://github.com/hyperdeal/hyperdeal/pull/94/files for example.
Maybe we should 
a) deprecate internal::mpi_type_id?
b) also keep the old style interface intact to make the transition easier?
