### ISSUE TITLE
VtkFlags - why only time and cycle?

### ISSUE THREAD

**Issue by kbzowski** [dealii/dealii#1338]
Hi,
I am wondering why dealii only allows to add two types of flags - time and cycle? I understand that VisIt supports that particular flags somehow automatically. But Paraview allows for more flags with different names also (using Annotate Global Data Filter) . Can I try to add support for more generic flags? Like std::map<std::string, double> ?

**Comment by bangerth** [comment]
Absolutely. I didn't realize that one can use other flags as well. If you see a use for them, feel free to implement this functionality!

**Comment by bangerth** [comment]
@kbzowski -- do you have a link to a document that explains how to describe additional attributes in the VTK or VTU files?

**Comment by bangerth** [comment]
@kbzowski -- asking again whether you have a document that explains how to describe additional attributes in VTK/VTU files?

I think this would be a nice little project, but I don't know a place where one could read up on the specs of how these attributes are supposed to be represented in VTK or VTU files.

**Comment by kbzowski** [comment]
@bangerth Sorry, somehow I totally forget about your request. In principle my observation was based on: https://www.visitusers.org/index.php?title=Time_and_Cycle_in_VTK_files where in VTK C++ code TIME and CYCLE were just an ordinary strings. I made some experiments based on VTK format and it works with any captions. Then it can be shown in ParaView using Annotate Global Data filter.

**Comment by bangerth** [comment]
@kbzowski -- I checked, and both the VTK and the VTU writer in deal.II support the time and cycle annotations. The document you link to doesn't describe any other fields, as far as I can see. What piece of functionality are you missing?

(Am I reading your comment correctly that you want these fields to be arbitrary *strings*, rather than integers of floating point numbers? That doesn't match the data type of the fields in the VTK or VTU formats, and the C++ code also has them as `int` and `double`.)

**Comment by kbzowski** [comment]
@bangerth What I am trying to say, that we are not only limited to time and cycle. I believe, that any number of individual values can be saved under any name. Check attached file as an example.
[debug1.vtk.txt](https://github.com/dealii/dealii/files/1234944/debug1.vtk.txt)

**Comment by jppelteret** [comment]
I must admit that I also didn't understand what you were asking, but I see what you've added to the sample VTK file that you've provided and have verified that this works. Yes, I would say that having a feature where we can append arbitrary field data might be useful. Would you like to open a pull request with a proposal for its implementation?

**Comment by bangerth** [comment]
@kbzowski -- do both Visit and Paraview read this file correctly? What do they do with the information?

**Comment by kbzowski** [comment]
@bangerth ParaView supports showing additional data using Annotate Global Data filter
![paraview_2017-08-21_08-15-22](https://user-images.githubusercontent.com/2268743/29506652-2fc910c6-864d-11e7-863a-b34ea20f2af7.png)
In case of VisIt - I am not familiar with this software so much. I was able to open my vtk file, but VisIt shows only Time and Cycle annotations. I was not able to find a method to show additional values.

**Comment by bangerth** [comment]
Interesting. I imagine that we could just add an addition `std::vector<std::pair<std::string,double>>` to the `VtuFlags` and/or `VtkFlags` that stores a list of pairs of name and value that we could output that way. I think that would actually be quite easy to do. Do you want to give this a go with a patch?

**Comment by kbzowski** [comment]
@bangerth I will try to implement this. I was thinking about simple std::map<std::string, double> instead. Are there  any advantages of using std::vector in this case?

**Comment by bangerth** [comment]
I think a map is even better :-)

**Comment by drwells** [comment]
This would be nice to have but we haven't made any progress in four years so lets close.
