### ISSUE TITLE
tests/submit_results.cmake is not mentioned

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1342]
In the testsuite documentation at http://dealii.org/developer/developers/testsuite.html#submit, there is no mention of the `tests/submit_results.cmake` script. Do we not need this script any more?

**Comment by tamiko** [comment]
@bangerth This script is used on your very own testing site to submit test results...

**Comment by tamiko** [comment]
It is not mentioned because it is usually not needed by users.

**Comment by bangerth** [comment]
I think we wrote it back when the tester was behind a firewall and couldn't access the internet, but this is no longer the case. We may be able to get rid of it. Should we?

I currently have these lines in my test script:
```
ctest -DTRACK="Regression Tests" -DDESCRIPTION="$special" -j36 -S ../dealii/tests/run_testsuite.cmake -V
```
I only use a `submit_testresults.cmake` for ASPECT.

**Comment by tamiko** [comment]
On Thu, Aug 20, 2015, at 15:33 CDT, Wolfgang Bangerth <notifications@github.com> wrote:

> We may be able to get rid of it. Should we?

Let's keep it in place. It is useful at times for low level submission
testing.

Best,
Matthias
