### ISSUE TITLE
drop MPI 2.x support

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#13447]
I would like to suggest that we drop MPI 2.0 support. The 3.0 standard was released in 2012.

I have the following reasons:
- We are not testing MPI 2.0 (I am not even sure if we compile)
- It is difficult to go back that far (OpenMPI 1.8.x and MPICH 3.0.x are both MPI 3.0 and from 2015/2016)
- I would like to support big messages and large IO and that does not work correctly with MPI 2.0 (``create_mpi_data_type_n_bytes``)
- OpenMPI devs already call 1.10 and older "ancient" on their website :-)

Thoughts?

**Comment by bangerth** [comment]
I am stuck on a system that has OpenMPI 1.10.7, but that still reports that it provides MPI 3.0.

**Comment by tjhei** [comment]
Yes, OpenMPI 1.8 and above are MPI 3.0 (that includes 1.10)

**Comment by tjhei** [comment]
I see 4 :+1: and no complaints, which makes me think we can move forward with this.

**Comment by tjhei** [comment]
todo list:
- [ ] update documentation
- [ ] changelog entry
- [ ] remove MPI 2.x logic

**Comment by tjhei** [comment]
This is all I can think of right now...
