### ISSUE TITLE
failure in tests/base/aligned_vector_replicate_04.cc

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#13460]
On my machine and the tester (see https://github.com/dealii/dealii/pull/13458) the test in the subject line fails with
```
n error occurred in line <1735> of file </jenkins/workspace/dealii_PR-13458/include/deal.II/base/aligned_vector.h> in function
    void dealii::AlignedVector<T>::replicate_across_communicator(const MPI_Comm&, unsigned int) [with T = int; MPI_Comm = int]
The violated condition was: 
    ierr == MPI_SUCCESS
Additional information: 
    deal.II encountered an error while calling an MPI function.
    The description of the error provided by MPI is "Invalid argument".
    The numerical value of the original error code is 873088524.
```
This is probably because I am using MPICH as my MPI implementation. It fails on the root process with alloc_size=63, align_by=64, disp_unit=0. Maybe ``disp_unit=0`` is considered invalid?

@bangerth ?

**Comment by bangerth** [comment]
`disp_unit` is defined as
```
    const int disp_unit = (is_shmem_root ? size() : 1);
```
Indeed, the test checks what happens for empty objects. I guess we could just skip all of the sharing if the object is empty -- nothing is to be gained from that.

That said, has anyone ever understood what the purpose of `disp_unit` actually is? I remember struggling with what this argument is supposed to indicate at all given that the *size* of the shmem window is passed as a separate argument. For reference the whole code block is here:
```
  MPI_Win        shmem_window;
  void *         base_ptr;
  const MPI_Aint align_by = 64;
  const MPI_Aint alloc_size =
    Utilities::MPI::broadcast(shmem_group_communicator,
                              (size() * sizeof(T) + (align_by - 1)),
                              0);

  {
    const int disp_unit = (is_shmem_root ? size() : 1);

    int ierr;

    MPI_Info mpi_info;
    ierr = MPI_Info_create(&mpi_info);
    AssertThrowMPI(ierr);
    ierr = MPI_Info_set(mpi_info,
                        "mpi_minimum_memory_alignment",
                        std::to_string(align_by).c_str());
    AssertThrowMPI(ierr);
    ierr = MPI_Win_allocate_shared((is_shmem_root ? alloc_size : 0),
                                   disp_unit,
                                   mpi_info,
                                   shmem_group_communicator,
                                   &base_ptr,
                                   &shmem_window);
    AssertThrowMPI(ierr);

    ierr = MPI_Info_free(&mpi_info);
    AssertThrowMPI(ierr);
  }
```

**Comment by tjhei** [comment]
First, I don't think sharing an empty vector is useful. I would consider that an error.

Regarding the unit, did you see https://www.open-mpi.org/doc/v3.0/man3/MPI_Win_allocate_shared.3.php#toc8 ?
We don't do RMA calls like MPI_Put so it doesn't matter for us.

**Comment by bangerth** [comment]
Yes, I had read text like that, but it didn't make any sense to me and still doesn't. Maybe it's because I don't know how RMA works. I should just always set it to one and see whether that works.

**Comment by bangerth** [comment]
Actually, no, I need to leave it as is:
```
  // There is one final piece we can already take care of here. At the beginning
  // of all of this, only the shmem_root knows how many elements there are in
  // the array. But at the end of it, all processes of course need to know. We
  // could put this information somewhere into the shmem area, along with the
  // other data, but that seems clumsy. It turns out that when calling
  // MPI_Win_allocate_shared, we are asked for the value of a parameter called
  // 'disp_unit' whose meaning is difficult to determine from the MPI
  // documentation, and that we do not actually need. So we "abuse" it a bit: On
  // the shmem root, we put the array size into it. Later on, the remaining
  // processes can query the shmem root's value of 'disp_unit', and so will be
  // able to learn about the array size that way.
  MPI_Win        shmem_window;
  void *         base_ptr;
  const MPI_Aint align_by = 64;
  const MPI_Aint alloc_size =
    Utilities::MPI::broadcast(shmem_group_communicator,
                              (size() * sizeof(T) + (align_by - 1)),
                              0);

  {
    const int disp_unit = (is_shmem_root ? size() : 1);
```

**Comment by bangerth** [comment]
About the error: it's not useful, but I think it shouldn't be illegal. I'll write a patch that in that case just resets all non-root objects to empty vectors. Does that seem reasonable?

**Comment by tjhei** [comment]
> Does that seem reasonable?

I am okay with that, but I have to admit that I don't see a reason to allow it to work for empty vectors. I think it is more likely that this indicates a bug in the user code (but maybe there is a reason to do this?).

**Comment by tjhei** [comment]
> Yes, I had read text like that, but it didn't make any sense to me and still doesn't. Maybe it's because I don't know how RMA works.

My understanding: If you use ``MPI_Put`` then the ``disp_unit`` matters. We are not using it, so it doesn't matter.

**Comment by bangerth** [comment]
On 2/28/22 15:10, Timo Heister wrote:
> I am okay with that, but I have to admit that I don't see a reason to 
> allow it to work for empty vectors. I think it is more likely that this 
> indicates a bug in the user code (but maybe there is a reason to do this?).

I'm thinking of code where you just share each of 17 different data 
tables. But depending on input parameters, some may not actually be used 
and so process 0 doesn't read it from disk and the other processes don't 
care. At the end of the operation, everyone should have an empty table. 
(The empty table may not be shared between processes, it just has to be 
empty.)

**Comment by tjhei** [comment]
Alright, that seems reasonable.
