### ISSUE TITLE
Remove DEAL_II_MPI_CONST_CAST

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13474]
Following up on #13465 (see also #13447), we can also remove the `DEAL_II_MPI_CONST_CAST`, which with MPI 3+ is simply defined as
```
#  define DEAL_II_MPI_CONST_CAST(expr) (expr)
```

We should probably retain the macro for a release or two, but we can remove all of its uses.

**Comment by tjhei** [comment]
@pengfej Can you remove all usages of the ``DEAL_II_MPI_CONST_CAST`` in the code base? The macro is no longer necessary because it doesn't do anything. Keep the definition (``#define DEAL_II_MPI_CONST_CAST``) for now.
For example
```
DEAL_II_MPI_CONST_CAST(filename.c_str())
```
becomes
```
filename.c_str()
```
etc.

**Comment by pengfej** [comment]
Sure, I'll work on it.

**Comment by tjhei** [comment]
done by #13488
