### ISSUE TITLE
Quicktests fail with Intel oneAPI suite.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#13477]
We've added quicktests to the github actions workers in #13467.

When running all quicktests on the Intel oneAPI worker, the following errors occur on all 8 quicktests:
```
step.debug: RUN failed. Output:
/home/runner/work/dealii/dealii/tests/quick_tests/step.debug: symbol lookup error: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_gf_lp64.so.2: undefined symbol: mkl_blas_dgemm
tests/quick_tests/CMakeFiles/step.debug.run.dir/build.make:70: recipe for target 'tests/quick_tests/CMakeFiles/step.debug.run' failed
```

Compiling the dummy file as well as all quicktests succeed. These errors only occur at runtime.

**Comment by marcfehling** [comment]
Might be related: https://gitlab.opengeosys.org/ogs/ogs/-/issues/3259

**Comment by marcfehling** [comment]
See also:
- https://gitlab.kitware.com/cmake/cmake/-/issues/22831

**Comment by marcfehling** [comment]
As only the quick tests are affected and the rest of the testsuite is fine, I would say it's safe to postpone this until the next release.

**Comment by tamiko** [comment]
*mhm* I have no issues with the tbb quicktests on my machines (Gentoo and Debian).

**Comment by drwells** [comment]
This also works just fine for me under Arch with both MKL and the oneAPI TBB - does it still fail on ubuntu?
