### ISSUE TITLE
Remove Utilities::MPI::create_group()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#13475]
Following #13465 (see also #13447) , we can remove the `Utilities::MPI::create_group()` function, which then simply wraps the call
```
return MPI_Comm_create_group(comm, group, tag, new_comm);
```
It currently does something non-trivial only in the case that we have MPI <3. 

Alternatively, maybe better, we can keep the function and make sure we check the return type rather than passing on the error code as we currently do. An even better idea would be to make the function similar to `duplicate_communicator()`, which would imply checking the MPI error code and then returning the actual communicator.

**Comment by tjhei** [comment]
I would deprecate the function and use ``MPI_Comm_create_group`` directly. It is used maybe 5 times in the library.
