### ISSUE TITLE
The commit https://github.com/dealii/dealii/commit/173c8243d0cade2f1ef3febfcf5875dd45c347bf breaks MSVC compilation

### ISSUE THREAD

**Issue by l-korous** [dealii/dealii#1350]
1) Errors from the current master:

https://www.dropbox.com/s/yf5p9rvdhlbwgx5/currentMaster.txt?dl=0

2) Errors when manually defined DEAL_II_CONST_MEMBER_DEDUCTION_BUG:
( I tried this just because I thought the bug detection method might produce a false positive on windows )

https://www.dropbox.com/s/qbvgxeq1f39hxky/currentMasterWithMacro.txt?dl=0

**Comment by bangerth** [comment]
It's another silly MSVC bug :-(

I'll come up with a patch shortly.

**Comment by bangerth** [comment]
Please check #1354.
