### ISSUE TITLE
affinity.cc quick test success depends on environment variables

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#1351]
I set `DEAL_II_NUM_THREADS=4` in my shell configuration files and that causes the quick test `affinity.cc` to fail (non-zero exit status). I don't think it used to fail for this reason. Here is a way to reproduce this:

```
[drwells@archway quick_tests]$ export DEAL_II_NUM_THREADS=7;./affinity.debug;echo $?
aff_ncpus=8, mask=000000FF, nprocs=8, tbb_threads=7
Warning: for some reason TBB only wants to use 7 out of 8 CPUs.
3
[drwells@archway quick_tests]$ export DEAL_II_NUM_THREADS=8;./affinity.debug;echo $?
aff_ncpus=8, mask=000000FF, nprocs=8, tbb_threads=8
0
```

**Comment by tjhei** [comment]
Yes, we started parsing DEAL_II_NUM_THREADS unconditionally in #1d9c44a0c. Not sure what to do about this test. Maybe we can unset this variable if you run ```make test```.

**Comment by tjhei** [comment]
Not sure what problem we detect with this test anyways. We might as well delete it, I guess.

**Comment by bangerth** [comment]
I don't recall either what the test was supposed to test. Feel free to nuke it if nobody else speaks up.

**Comment by bangerth** [comment]
(Also, 'git log' is not helpful in finding out...)

**Comment by tamiko** [comment]
> (Also, 'git log' is not helpful in finding out...)

Normally
  $ git log tests/quick_tests/affinity.cc
would tell you all commits touching this specific file - except it is
not helpful in this case :-/

The test seems to be introduced with 721fbd8 - the author is... me. No
idea... maybe as a response to some scheduling problems with tbb?
