### ISSUE TITLE
Shift "coding conventions" to Wiki?

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#13532]
Since github is the place for code contributions, I think it would make sense to find information on coding conventions (currently here:  https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html) on github in the Wiki (https://github.com/dealii/dealii/wiki). dealii.org could contain a link to the respective wiki page.

**Comment by nfehn** [comment]
I have found other places in the wiki that refer to https://www.dealii.org. So I am not sure right now and I now think one would need to discuss a common strategy before starting with "coding conventions". It does not look like the wiki is maintained a lot (?), so it could make sense to keep information at https://www.dealii.org (while I don't know whether these pages are maintained more regularly, they make a better impression than the wiki in my opinion).

I modified the "home" page of deal.II's wiki (https://github.com/dealii/dealii/wiki) with many links to other pages (in order to bring more structure into the wiki), or to https://www.dealii.org. I hope this proposal is considered useful.

Regarding the page "home", it was not clear to me what the note https://github.com/dealii/dealii/wiki#a-word-of-caution-for-contributors means? Is it relevant for all wiki pages, or just for the FAQs page? Maybe @tjhei is the person to ask this? If it is related to FAQs only, it should be shifted to that page in my opinion.

**Comment by tjhei** [comment]
> ? If it is related to FAQs only, it should be shifted to that page in my opinion.

It can be used on any page to automatically generate the table of contents with links at the top of the page, but I think we only use this for the FAQ. Feel free to move it.

**Comment by bangerth** [comment]
Coding conventions tend to be contentious, so it makes sense to keep these in the repository where changes need to be peer-reviewed. My vote would be to keep them there.

Thanks for updating the front page of the wiki! I've renamed the last section about the table of contents to make it clearer what it is about. Are there other things that ought to be done for this issue, or can it be closed?

**Comment by nfehn** [comment]
@bangerth, I agree regarding the need for peer-review.
