### ISSUE TITLE
Why does "coding conventions" contain information on "indentation"?

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#13531]
see https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html

Indentation seems to be described already in the wiki:
https://github.com/dealii/dealii/wiki/Contributing
https://github.com/dealii/dealii/wiki/Indentation

Wouldn't it make sense to have this information only once (in the Wiki)?

**Comment by bangerth** [comment]
Because history :-) Feel free to remove it from one place and point to the other place instead.

**Comment by nfehn** [comment]
As a first step, I created a separate wiki page for "commit authorship" (see https://github.com/dealii/dealii/wiki/Commit-authorship), which has previously been part of https://github.com/dealii/dealii/wiki/Indentation.

Up to now, I "merged" the information on indentation from  https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html into https://github.com/dealii/dealii/wiki/Indentation.

I would suggest to then delete the information on indentation from  https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html.

**Comment by tjhei** [comment]
Thanks for improving things!

> Up to now, I "merged" the information on indentation from

Two comments:
- I don't think it make sense to teach "clang-format -i", especially before talking about "make indent" or "contrib/utilities/indent". The indent scripts do more than clang-format as well.
- This is not longer up to date: "Check for valid authorship of your commits (see below)."
