### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13575]
Dear all,

we are in the process of migrating the website to a new (cloud based) server instance. Doing so will open up a number of opportunities to:
 - [ ] modernize our website (and base everything on markdown?)
 - [ ] merge the wiki into the website
 - [ ] merge the non-doxygen html part of the documentation into the website (leaving only the doxygen part in the development repository)
 - [ ] make the source code for the website available under https://github.com/dealii/website and introduce our usual pull request + review workflow for everything.

Before we proceed I would quickly discuss these points. :smiley:

**Comment by tjhei** [comment]
I would suggest to just do the last point: get everything running, and then consider working on any of the other suggestions. I like small, incremental steps.

**Comment by marcfehling** [comment]
In addition to what @tjhei said, I think we should start by copying the website to a new repository in the dealii github group. We can keep it private at first.

This way we can open issues in the new repository right away, and avoid any overlap with the main repository. To keep them separate right from the beginning.

**Comment by tamiko** [comment]
Moving the old website to a new place and <i>then</i> throwing everything away to replace it by a new markdown system is significantly more work than to just start with the new website in the first place in a fresh repository.

So my suggestion would be, as @tjhei suggested, to first set up the infrastructure for the new website (complete with a temporary domain) and then start working on the other bullet points. After that we can simply switch our TLD to the new website server.

If it turns out that this doesn't work as planned and we simply want to put the old website in place - well that can be accomplished in about 10 minutes: https://dealii.43-1.org/website/ (maintained in a git repository and initially cloned 3 years ago...)

**Comment by tamiko** [comment]
Change of plans: We're putting the old website in place and crowd-source writing up the new one under an alternative TLD. Thanks for the input, @marcfehling and @tjhei

**Comment by blaisb** [comment]
@tamiko Do you need any help with that? Are there technical jobs that could be outsourced at large in the deal.II community? I'd be glad to be of help :)!

**Comment by tamiko** [comment]
@blaisb Absolutely! I hope that I can make the https://github.com/dealii/website repo public in a day or two and that we can crowdsource the technical development and content migration :-)

**Comment by tamiko** [comment]
Short status update: The new webserver is spun up and now hosts the old deal.II website https://dealii.43-1.org/ , a gitweb mirror of our main repositories at https://gitweb.dealii.43-1.org/, and the CDash instance at https://cdash.dealii.43-1.org (the domain will change to `dealii.org` soon).

**Comment by tjhei** [comment]
I clicked around a bit and everything looks good (and fast). Thank you!

**Comment by marcfehling** [comment]
The `doxygen` bibliography is not available for the continuous builds:
https://www.dealii.org/developer/doxygen/deal.II/citelist.html

The one of the 9.3 release is available though:
https://www.dealii.org/current/doxygen/deal.II/citelist.html

**Comment by tamiko** [comment]
@marcfehling fixed.

**Comment by tamiko** [comment]
moving to website repository
