### ISSUE TITLE
Triangulation::has_hanging_nodes() logic is wrong in case of anisotropic refinement

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13623]
I am currently triggering this assert:
```
7519     Assert(in_tria.has_hanging_nodes() == false,                                 
7520            ExcMessage("This function does not work for meshes that have "        
7521                       "hanging nodes."));
```
in `flatten_triangulation` (in `source/grid/grid_generator.cc`) with the following code: https://github.com/conservation-laws/ryujin/blob/master/source/grid_airfoil.h#L1224

The problem is that in the above code `coarse_triangulation` (that gets flattened) is an locally anisotropically refined mesh (i.e. it contains different cell levels). But it is refined in a way that it does not contain hanging nodes [1, 2].

The following heuristic seems to be questionable (`distributed/tria_base.cc`):
```
 732   template <int dim, int spacedim>                                                
 733   bool                                                                            
 734   DistributedTriangulationBase<dim, spacedim>::has_hanging_nodes() const          
 735   {                                                                               
 736     if (this->n_global_levels() <= 1)                                             
 737       return false; // can not have hanging nodes without refined cells           
 738                                                                                   
 739     // if there are any active cells with level less than n_global_levels()-1,    
 740     // then there is obviously also one with level n_global_levels()-1, and       
 741     // consequently there must be a hanging node somewhere.                       
 742     //                                                                            
 743     // The problem is that we cannot just ask for the first active cell, but      
 744     // instead need to filter over locally owned cells.                           
 745     const bool have_coarser_cell =                                                
 746       std::any_of(this->begin_active(this->n_global_levels() - 2),                
 747                   this->end_active(this->n_global_levels() - 2),                  
 748                   [](const CellAccessor<dim, spacedim> &cell) {                   
 749                     return cell.is_locally_owned();                               
 750                   });                                                             
 751                                                                                   
 752     // return true if at least one process has a coarser cell                     
 753     return Utilities::MPI::max(have_coarser_cell ? 1 : 0,                         
 754                                this->mpi_communicator) != 0;                      
 755   } 
```

[1] I need this feature to create a coarse mesh with good refinement characteristics, see https://github.com/conservation-laws/ryujin/blob/master/source/grid_airfoil.h#L1190-L1210

[2] I need to flatten the coarse manifold because our distributed manifold uses p4est which does not support anisotropically refined meshes.

**Comment by tamiko** [comment]
Here is the coarse mesh in question:

![](https://tamiko.43-1.org/temp/zoom-1.png)

![](https://tamiko.43-1.org/temp/zoom-2.png)

**Comment by tjhei** [comment]
Makes sense. I think the logic is only correct for isotropic refinement and with a connected domain.

How do you propose we do this correctly? Even letting each process iterate over all owned cells and check if all neighbors are the same level won't work in your case, correct?

**Comment by tamiko** [comment]
@peterrum That's correct.

**Comment by tamiko** [comment]
@tjhei For the case of anisotropic refinement: what would work is to iterate over all faces of active cells and ask whether the face has children, i.e., whether there is a hanging node.
