### ISSUE TITLE
hdf5 tests fail

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#13638]
The following tests fail for me:
```
$ ctest -R hdf5
76% tests passed, 8 tests failed out of 34

The following tests FAILED:
        1566 - base/hdf5_03.mpirun=1.debug (Failed)
        1567 - base/hdf5_03.mpirun=1.release (Failed)
        1568 - base/hdf5_03.mpirun=4.debug (Failed)
        1569 - base/hdf5_03.mpirun=4.release (Failed)
        1572 - base/hdf5_05.mpirun=1.debug (Failed)
        1573 - base/hdf5_05.mpirun=1.release (Failed)
        1574 - base/hdf5_05.mpirun=4.debug (Failed)
        1575 - base/hdf5_05.mpirun=4.release (Failed)
```

It looks like the test hdf5_05 does not fill all values for ``dataset_4`` when running with one MPI rank. On my machine the default values are "nan", while they are "0" in the blessed output:
```
DEAL::Data dataset_4<float> (Read): [0, 1, 2, 3, -nan, -nan, -nan, -nan, 4, 5, 6, 7, -nan, -nan, -nan, -nan, 8, 9, 10, 11, 0, 0, 0, 0]
vs
DEAL::Data dataset_4<float> (Read): [0, 1, 2, 3, 0, 0, 0, 0, 4, 5, 6, 7, 0, 0, 0, 0, 8, 9, 10, 11, 0, 0, 0, 0]
```

I am a bit confused because hdf5 is supposed to use 0 as the default: https://docs.hdfgroup.org/hdf5/develop/group___d_c_p_l.html#ga4335bb45b35386daa837b4ff1b9cd4a4

Options:
a) add an additional alternative output
b) always write all data in the test
c) figure out how to use H5Pset_fill_value

**Comment by drwells** [comment]
Related to #12247.

**Comment by kronbichler** [comment]
> Options: [...]

I would be fine with another output variant. We have a clear understanding of the problem. I guess everything else would be too much work at this stage.
