### ISSUE TITLE
A bug in particles class

### ISSUE THREAD

**Issue by shahabgol** [dealii/dealii#13643]
There is a bug in the particles class (probably in exchange_ghost_particles() function)  that I reproduced using step-68. In the following code, I have only added the line: **particle_handler.exchange_ghost_particles(false);** after calling **sort_particles_into_subdomains_and_cells()** function (**line 745**). If you run this example on **two cores in parallel**, in **Debug** mode it breaks because of the error:

``
An error occurred in line <222> of file </home/shahab/dealii_NEW/dealii/source/particles/property_pool.cc> in function
    void dealii::Particles::PropertyPool<dim, spacedim>::sort_memory_slots(const std::vector<unsigned int>&) [with int dim = 2; int spacedim = 2]
The violated condition was: 
    sorted_locations.size() == locations.size() - currently_available_handles.size()
Additional information: 
    Number of sorted property handles is not equal to number of currently
    registered handles: 216 vs 341 - 1
``

Modified step-68:

        particle_handler.sort_particles_into_subdomains_and_cells();
        particle_handler.exchange_ghost_particles(false);

**Comment by bangerth** [comment]
Do you think you could come up with a minimal test case?

**Comment by blaisb** [comment]
I have a feeling that adding 
`particle_handler.exchange_ghost_particles(false)` 
to any MPI test will break them if you have particles moving around. I think  I can cook one up by modifying [this test ](https://github.com/dealii/dealii/blob/master/tests/particles/particle_handler_21.cc)

Let me do this tonight and I'll open a PR with a test that breaks. Should make the work easier.

**Comment by blaisb** [comment]
I created a test in a PR that reproduces this exact bug. Hopefully this can help us move forward.
We need more of these tests anyway. Sounds like  a good Hackathon goal :)!

**Comment by blaisb** [comment]
@shahabgol I think you can close this issue now. This has been solved by @gassmoeller last PR :)

**Comment by shahabgol** [comment]
@gassmoeller @blaisb @bangerth Thank you all :)

**Comment by gassmoeller** [comment]
Just for future reference the PR was #13654
