### ISSUE TITLE
add hp::DoFHandler support to parallel::shared::Triangulation

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1366]
https://github.com/dealii/dealii/pull/212 introduced parallel::shared::Triangulation. Currenlty hp::DoFHandler is not supported. Modifications are to be done around this line: https://github.com/dealii/dealii/blob/master/source/hp/dof_handler.cc#L2762

**Comment by bangerth** [comment]
Yes, supporting parallel triangulations in hp::DoFHandler is on my list once I'm through with rewriting everything FEValues-related.

**Comment by davydden** [comment]
I think another reason to make it work is to support `ConstraintMatrix.reinit(locally_relevant_set)`. My understanding is that currently for standard DoFHandler one has to build constraints for all dofs, even if most of them are irrelevant in the MPI case. 

One could probably also add support for `p::s::Tria` in `distributed::SolutionTransfer()`.

**Comment by bangerth** [comment]
For anyone interested in the history of this issue later on: I have been posting lots of patches referenced to #3511 that prepare for using `hp::DoFHandler` with parallel triangulations. They are all equally applicable to using `hp::DoFHandler` with shared triangulations, and making that work is in fact my first goal given that that is so much simpler to do.
