### ISSUE TITLE
Allow attaching cell weights to parallel::shared::Triangulation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1367]
Something along the same lines as was done in #1131 for parallel::distributed::Triangulation would be useful also in parallel::shared::Triangulation. In fact, maybe we can even use the same function signatures.

@davydden, what do you think ?

**Comment by davydden** [comment]
That's surely very useful for hp-FEM in a hope to have a better partition according to number of dofs on each cell.

**Comment by bangerth** [comment]
The method by which the regular `parallel::distributed::Triangulation` allows to read weights has recently been changed by a patch by @gassmoeller .

**Comment by bangerth** [comment]
@davydden -- I don't recall the details, but haven't we done what's requested here?

**Comment by davydden** [comment]
I actually don't know, it must be through `cell_weight` signals https://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1Signals.html#af58294e40c64257c9de55e78b6443e36 but it's not stated anywhere whether shared Tria supports it, although I have a feeling that it does as @vishalkenchan wanted to use this eventually in his project.

**Comment by marcfehling** [comment]
I don't know exactly what you originally wanted to accomplish 5 years ago, but I added some tests assigning cell weights to a parallel::shared::Triangulation some time ago in the hp-adaptive context.
https://github.com/dealii/dealii/blob/master/tests/mpi/hp_cell_weights_03.cc
https://github.com/dealii/dealii/blob/master/tests/mpi/hp_cell_weights_04.cc

If you think this is sufficient, I'd suggest to close this issue.

**Comment by bangerth** [comment]
Let's close this one as well.
