### ISSUE TITLE
Compilation fails for opencascade 7.6.1

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13822]
See https://cdash.dealii.43-1.org/viewBuildError.php?buildid=1948

```
[source/opencascade/utilities.cc:47](https://github.com/dealii/dealii/blob/master/source/opencascade/utilities.cc#L47):12: fatal error: BRepAdaptor_HCompCurve.hxx: No such file or directory

   47 | #  include <BRepAdaptor_HCompCurve.hxx>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by tamiko** [comment]
I am downgrading the testsuite to 7.5.3 for the time being and will upgrade back to 7.6.1 once we have resolved this.

**Comment by marcfehling** [comment]
Maybe we can do something like these guys: https://github.com/IfcOpenShell/IfcOpenShell/commit/461b78665a726e91954cfea4e2658213b0da4161

**Comment by marcfehling** [comment]
Do we need the `<BRepAdaptor_HCompCurve.hxx>` header at all?

**Comment by marcfehling** [comment]
I can compile deal.II with opencascade 7.4.0 and run the opencascade tests successfully if I remove the `<BRepAdaptor_HCompCurve.hxx>` header.

**Comment by marcfehling** [comment]
Upgrade instructions:
https://dev.opencascade.org/doc/overview/html/occt__upgrade.html
