### ISSUE TITLE
Unity build is broken

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13881]
For the upcoming 9.4 release we should fix our unity build again :-)

https://cdash.dealii.43-1.org/viewBuildError.php?buildid=2195

**Comment by drwells** [comment]
I can reproduce this - I am working on a fix.

**Comment by drwells** [comment]
https://github.com/petsc/petsc/blob/27c9ef7be839ca1f58a90cb820253679fac370b3/include/petsclog.h#L460-L462

defines
```c

#define MPI_Send_c(buf,count,datatype,dest,tag,comm) \
  ((petsc_send_ct++,0) || PetscMPITypeSize((count),(datatype),(&petsc_send_len)) || MPI_Send_c((buf),(count),(datatype),(dest),(tag),(comm)))
```

so its not possible to define a function with that name after including a PETSc header - we will always get errors resulting from macros. More generally, the big mpi library is not compatible with PETSc for this reason so this problem extends past the issue of unity builds.

This snippet always fails to compile:
```cpp
#include <petsclog.h>

#include <deal.II/base/mpi_large_count.h>

int main() {}
```

**Comment by bangerth** [comment]
Ugh, what a moronic system for them to use...
