### ISSUE TITLE
Documentation of FRenumbering::cell_wise() is not clear

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1388]
What is the parameter
```
	const std::vector< typename DH::active_cell_iterator > & 	cell_order 
```
used for?

A vector contains beginning active_cell_iterator for each processor like the ``` starting_indices``` for ```void DoFRenumbering::Cuthill_McKee()```?

**Comment by bangerth** [comment]
See #1392.

**Comment by QiaoLei-88** [comment]
Just an off topic question, does ```DoFRenumbering::Cuthill_McKee``` implies that the dofs are ordered cell wise?

**Comment by bangerth** [comment]
No, the order of DoFs is determined based on the connectivity of DoFs, not of cells.

**Comment by QiaoLei-88** [comment]
Well, then how about almost cell wise?  Because when cells are not connected, DoFs in side them are also not connected. But DoFs in neighbering cells can connect with each other thus may destroy the
"cell wise" order.

**Comment by bangerth** [comment]
Is your question whether DoFs are "almost cellwise sorted" after Cuthill-McKee? I think one would need to define what "almost" means in this case. I would say the answer is "no", though, and I'll be happy to draw you a picture tomorrow.

Or is the question whether one could define a cellwise Cuthill-McKee algorithm? Here, the obvious answer is "yes", but that's not what the function currently does.

**Comment by QiaoLei-88** [comment]
I am looking forward to see that picture :-]
