### ISSUE TITLE
Fix compile warnings

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13910]
We still emit a (massive) number of warnings on certain configurations. Most notably:
 - [x] Two unused warnings with clang (various configurations): `Clang-8.0.1-master-autodetection ` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2317) -> #13911
 - [x] Array bounds warnings with tets: `GNU-12.1.0-master-tets` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2339)
 - [x] An array of warnings with GCC 12: (examples)
         - [ ] `GNU-12.1.0-master-64bit_indices` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2336)
         - [ ] `GNU-12.1.0-master-autodetection` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2322)
 - [x] An array of warnings with Clang 14: (example)
         - [ ] `Clang-14.0.1-master-cpp20` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2308)
 - [x] Uninitialized warnings with avx2+: `GNU-12.1.0-master-avx2-O3` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2335)
 - [x] Deprecated `Threads::thread` on debian: `GNU-10.2.1-master-debian-11 ` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2331) (#14036)

Annoying but I don't have a good idea what to do:
 - [x] Boost in Ubuntu LTS 22 is difficult: `GNU-11.2.0-master-ubuntu-lts-22` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2328)

**Comment by peterrum** [comment]
@NiklasWik Could you take a look at https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2339, where there some warnings regarding `interpolate_generic_raviart_thomas` (1D).

**Comment by kronbichler** [comment]
I looked into the warning `Uninitialized warnings with avx2+: GNU-12.1.0-master-avx2-O3` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2335) and if I understand things correctly, it warns because of the variable declared `_mm256_undefined_pd` in this code:
```c++
extern __inline __m256d
__attribute__ ((__gnu_inline__, __always_inline__, __artificial__))
_mm256_i32gather_pd (double const *__base, __m128i __index, const int __scale)
{
  __v4df __zero = _mm256_setzero_pd ();
  __v4df __mask = _mm256_cmp_pd (__zero, __zero, _CMP_EQ_OQ);

  return (__m256d) __builtin_ia32_gathersiv4df (_mm256_undefined_pd (),
                                                __base,
                                                (__v4si)__index,
                                                __mask,
                                                __scale);
}
```
where the variable `undefined` is in turn coming from
```c++
extern __inline __m256d __attribute__((__gnu_inline__, __always_inline__, __artificial__))
_mm256_undefined_pd (void)
{
  __m256d __Y = __Y;
  return __Y;
}
```

In other words, gcc warns about its own definitions?

**Comment by kronbichler** [comment]
What do we want to do about the avx2 warning? I could work around it in a way that pleases gcc (by adding a suitable initial state and choosing the masked load), but I am not sure it will not regress on other compilers. In any case, this is a bug in the compiler in my opinion.

**Comment by tamiko** [comment]
@kronbichler I think we have to address the avx2 warning - because this compiler version might end up somewhere in Ubuntu or Debian and it is highly annoying. Would it be possible to make your workaround dependent on a preprocessor macro `DEAL_II_GCC_WITH_BOGUS_AVX_WARNINGS` or something like this and we only enable it if we encounter the warning? (or for precisely gcc-12)?

**Comment by kronbichler** [comment]
What should we do about the warning left for gcc-12: https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2832
The problem:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/array:61:36: warning: array subscript 3 is above array bounds of ‘std::__array_traits<std::array<unsigned int, 2>, 3>::_Type’ {aka ‘const std::array<unsigned int, 2> [3]’} [-Warray-bounds]

note: while referencing ‘table’

 1325 |       static const ndarray<unsigned int, 3, 2> table = {
      |                                                ^~~~~
In static member function ‘static constexpr _Tp& std::__array_traits<_Tp, _Nm>::_S_ref(const _Tp (&)[_Nm], std::size_t) [with _Tp = std::array<unsigned int, 2>; long unsigned int _Nm = 3]’,
    inlined from ‘constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = std::array<unsigned int, 2>; long unsigned int _Nm = 3]’ at /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/array:219:25,
    inlined from ‘std::array<unsigned int, 2> dealii::ReferenceCell::standard_vertex_to_face_and_vertex_index(unsigned int) const’ at [include/deal.II/grid/reference_cell.h:1328](https://github.com/dealii/dealii/blob/master/include/deal.II/grid/reference_cell.h#L1328):26,
    inlined from ‘static unsigned int dealii::internal::TriaAccessorImplementation::Implementation::vertex_index(const dealii::TriaAccessor<2, dim, spacedim>&, unsigned int) [with int dim = 3; int spacedim = 3]’ at [include/deal.II/grid/tria_accessor.templates.h:1024](https://github.com/dealii/dealii/blob/master/include/deal.II/grid/tria_accessor.templates.h#L1024):77,
    inlined from ‘unsigned int dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >::vertex_index(unsigned int) const [with int structdim = 2; int dim = 3; int spacedim = 3]’ at [include/deal.II/grid/tria_accessor.templates.h:1131](https://github.com/dealii/dealii/blob/master/include/deal.II/grid/tria_accessor.templates.h#L1131):19,
    inlined from ‘dealii::types::global_dof_index dealii::DoFAccessor<structdim, dim, spacedim, lda>::vertex_dof_index(unsigned int, unsigned int, unsigned int) const [with int structdim = 2; int dim = 3; int spacedim = 3; bool level_dof_access = false]’ at [include/deal.II/dofs/dof_accessor.templates.h:1643](https://github.com/dealii/dealii/blob/master/include/deal.II/dofs/dof_accessor.templates.h#L1643):18,
    inlined from ‘void dealii::DoFTools::internal::make_oldstyle_hanging_node_constraints(const dealii::DoFHandler<dim, spacedim>&, dealii::AffineConstraints<number>&, std::integral_constant<int, 3>) [with int dim_ = 3; int spacedim = 3; number = float]’ at [source/dofs/dof_tools_constraints.cc:944](https://github.com/dealii/dealii/blob/master/source/dofs/dof_tools_constraints.cc#L944):58:
```
This is likely because we keep various static arrays and the compiler can't determine that we end up in the `if` case where we do not exceed the bounds. This is annoying. Any ideas?

**Comment by peterrum** [comment]
Cannot we convert those to constant expressions?
