### ISSUE TITLE
matrix_free/ecl_01: fails with different l2 norm

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13942]
In `matrix_free/ecl_01` currently fails on a number of configurations where a matrix-vector product is computed slightly differently (for one test vector). More precisely, configurations with avx512 pass the test while everything else (independent of avx2, sse, optimization level, compiler) fail with pretty much the same vector [1].

If this would be more random I would have just added an output variant and called it a day. But this is suspiciously reproducible: I get *the same numbers* for all configurations except avx512. Which leads me to believe that there must be some odd behavior or a bug somewhere.

[1] https://cdash.dealii.43-1.org/testSummary.php?project=1&name=matrix_free%2Fecl_01.mpirun%3D1.debug&date=2022-06-08

In reference to #13703

**Comment by tamiko** [comment]
@kronbichler @peterrum *ping*

**Comment by kronbichler** [comment]
Yes, it is a bug. See https://github.com/dealii/dealii/issues/13703#issuecomment-1133978999 as an answer to https://github.com/dealii/dealii/issues/13703#issuecomment-1132564790. And regarding the question

> Do you have an idea how to address this? I would say that we need MappingInfo::neighbor_cell_type.

I think this makes sense @peterrum.

**Comment by kronbichler** [comment]
I am on this problem and hope to have a solution soon.
