### ISSUE TITLE
Delete trailing whitespace in the changes.h file

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#13997]
This is mildly annoying - we should modify the cmake script to delete trailing whitespace.

**Comment by CodyGirl** [comment]
Hello Team,

I was trying to replicate this issue in order to contribute to deal.ii but can't seem to replicate it. The changes.h file did not have any trailing white spaces. If you're still able to see those trailing white spaces please let me know how to replicate it.

**Comment by drwells** [comment]
Perhaps we are looking at different files - I see trailing whitespace in `build/doc/news/changes.h` (where `build` is my build directory). Independently of that, we should still add code to trim trailing whitespace into the CMake script which creates this file - can you give that a try?

**Comment by drwells** [comment]
Fixed by #16419.
