### ISSUE TITLE
Test grid/grid_in_abaqus_01 fails

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1409]
This test fails at least since #1334 when the mesh converted was integrated into GridIn. The underlying cause is that `read_in_abaqus()` has this piece of code:
```
           // There are two possibilities of storing cells numbers in ELSET:
            // 1. If the header contains the 'GENERATE' keyword, then the next line describes range of cells as:
            //    cell_id_start, cell_id_end, cell_step
            // 2. If the header does not contain the 'GENERATE' keyword, then the next lines contain cells numbers
            std::vector<int> elements;
            const std::size_t generate_idx = line.find("GENERATE");
            if (generate_idx != std::string::npos)
              {
                // Option (1)
                std::getline (input_stream, line);
                std::istringstream iss (line);
                char comma;
                int elid_start;
                int elid_end;
                int elis_step;
                iss >> elid_start >> comma >> elid_end >> comma >> elis_step;
                for (int i = elid_start; i <= elid_end; i+= elis_step)
                  {
                    elements.push_back(i);
                  }
```
It gets hung up on the input file which reads like this:
```
*ELSET, ELSET=e, GENERATE
1, 1
```
In other words, the code tries to read three integers, but only two are given. The `elis_step` variable then doesn't get set, and remains at zero -- which consequently leads to an infinite loop in the following  line. No way to recover from that.

What isn't clear to me is whether the input file is actually conforming to the specification (e.g.: if the third number is omitted, then it is implied to be one) or whether it is broken. In the former case, we'd need to adjust the code. In the latter, we'd need to adjust the input file.

Does anyone have a reference to the ABAQUS file format? @jppelteret?

**Comment by bangerth** [comment]
This page http://www.egr.msu.edu/software/abaqus/Documentation/docs/v6.7/books/key/default.htm?startat=ch05abk11.html#usb-kws-melset and this page http://www.egr.msu.edu/software/abaqus/Documentation/docs/v6.7/books/usb/default.htm?startat=pt01ch02s02aus10.html#usb-int-ielement both seem to suggest that there is a default value for the third number has a default argument. I can only imagine that that means that it can be omitted.

**Comment by jppelteret** [comment]
Sorry, I had corrected this problem in my working copy of the offline version of the mesh_converter program but clearly forgot to include it here. Funnily enough all of the test cases still worked for me without this fix.
