### ISSUE TITLE
Implement `ReferenceCell::project_to_unit_cell()`

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#14260]
See the comment in #14259:

https://github.com/dealii/dealii/blob/c3b9c68c4bc3d12e8184102f34ec466130867902/source/grid/grid_tools.cc#L6096-L6101

**Comment by bangerth** [comment]
Can I suggest that we call this `project_to_reference_cell()`? The notation that is widely used in the FE community is "reference cell", and I have for decades regretted that we used "unit cell" instead.
