### ISSUE TITLE
dealii&openfoam:when i use Gmsh to generate .msh file, Number of coupling nodes:     0

### ISSUE THREAD

**Issue by codeplayerpk** [dealii/dealii#14358]
Hi,guys,when i used Gmeh to generate .msh file, something is wrong here. console message: Number of coupling nodes: 0, I dont know how to do .
when i use openfoam&dealii to simulate FSI case
Grid:
Reference volume: 0.5
Triangulation:
Number of active cells: 32
Polynomial degree: 4
Number of degrees of freedom: 7,803
Setting up quadrature point data…
Output written to solution-000.vtk

 Number of coupling nodes:     0

—[precice] Setting up master communication to coupling partner/s

**Comment by codeplayerpk** [comment]
[Grid:
Reference volume: 0.5
Triangulation:
Number of active cells: 32
Polynomial degree: 4
Number of degrees of freedom: 7,803
Setting up quadrature point data…
Output written to solution-000.vtk

Number of coupling nodes: 0

—[precice] Setting up master communication to coupling partner/s](url)

**Comment by drwells** [comment]
It looks like you are using precice - while a couple of people here also use precice I don't think that any of us are going to be able to answer this question. In particular, deal.II itself does not have any notion of a 'coupling node' so we cannot address that problem from this side.

Can you instead post your question to precice's mailing list (or whatever equivalent help channel they provide)? Thanks!

**Comment by drwells** [comment]
This is really a precice question so, unless there is a deal.II issue to address, lets close this.
