### ISSUE TITLE
grid_in  unv file error

### ISSUE THREAD

**Issue by ztdepztdep** [dealii/dealii#14379]
`terminate called after throwing an instance of 'dealii::StandardExceptions::ExcIO'
  what():  
--------------------------------------------------------
An error occurred in line <864> of file </home/ztdep/Downloads/dealii-9.4.0/source/grid/grid_in.cc> in function
    void dealii::GridIn<dim, spacedim>::read_unv(std::istream&) [with int dim = 2; int spacedim = 2; std::istream = std::basic_istream<char>]
The violated condition was: 
    in.fail() == false
`
[3x3.unv.txt](https://github.com/dealii/dealii/files/9893007/3x3.unv.txt)

**Comment by drwells** [comment]
Thanks for the report - the precise problem with that input file is that the boundary ids are set to `L`, `R`, `B`, and `T`, whereas we require integer values.
