### ISSUE TITLE
Does dealii support 1D problem.

### ISSUE THREAD

**Issue by ztdepztdep** [dealii/dealii#14382]
I want to develop a code for the DNS of turbulent flow in a channel based on dealii package. The channel has two periodic directions which can be treated with fft and the wall-normal direction need te be resolved with the dealii package. 
So does dealii support the 1D problems.

**Comment by blaisb** [comment]
Dear @ztdepztdep, those questions are more adequate on the deal.II google group since they do not constitute issues per se.
https://groups.google.com/g/dealii

However, to answer your question, deal.II supports 1D, 2D and 3D elements.

**Comment by drwells** [comment]
Indeed, this is more suitable for the mailing list - lets continue the discussion there.
