### ISSUE TITLE
compile error  when i enable the p4est .

### ISSUE THREAD

**Issue by ztdepztdep** [dealii/dealii#14399]
When enabling the p4est, the cmake configure gives me the following error. if i turn the p4est off, everything is ok . Could you pleae give me some sugesstions. 

Performing Test DEAL_II_HAVE_USABLE_FLAGS_RELEASE - Failed
CMake Error at cmake/setup_finalize.cmake:137 (MESSAGE):
      Configuration error: Cannot compile a test program with the final set of
    compiler and linker flags:
      CXX flags (RELEASE): -pedantic -fPIC -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -fmessage-length=0 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs
      LD flags  (RELEASE): -rdynamic -lpthread 
      LIBRARIES (RELEASE): /usr/local/lib/libz.so;rt;/home/ztdep/lib/Trilinos-13.2/lib/libmuelu-adapters.so;/home/ztdep/lib/Trilinos-13.2/lib/libmuelu-interface.so;/home/ztdep/lib/Trilinos-13.2/lib/libmuelu.so;/home/ztdep/lib/Trilinos-13.2/lib/libifpack2-adapters.so;/home/ztdep/lib/Trilinos-13.2/lib/libifpack2.so;/home/ztdep/lib/Trilinos-13.2/lib/libkomplex.so;/home/ztdep/lib/Trilinos-13.2/lib/libamesos2.so;/home/ztdep/lib/Trilinos-13.2/lib/libbelosxpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libbelostpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libbelosepetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libbelos.so;/home/ztdep/lib/Trilinos-13.2/lib/libml.so;/home/ztdep/lib/Trilinos-13.2/lib/libifpack.so;/home/ztdep/lib/Trilinos-13.2/lib/libzoltan2.so;/home/ztdep/lib/Trilinos-13.2/lib/libamesos.so;/home/ztdep/lib/Trilinos-13.2/lib/libgaleri-xpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libgaleri-epetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libaztecoo.so;/home/ztdep/lib/Trilinos-13.2/lib/libxpetra-sup.so;/home/ztdep/lib/Trilinos-13.2/lib/libxpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libthyratpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libthyraepetraext.so;/home/ztdep/lib/Trilinos-13.2/lib/libthyraepetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libthyracore.so;/home/ztdep/lib/Trilinos-13.2/lib/libtrilinosss.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetraext.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetrainout.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetra.so;/home/ztdep/lib/Trilinos-13.2/lib/libkokkostsqr.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetraclassiclinalg.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetraclassicnodeapi.so;/home/ztdep/lib/Trilinos-13.2/lib/libtpetraclassic.so;/home/ztdep/lib/Trilinos-13.2/lib/libepetraext.so;/home/ztdep/lib/Trilinos-13.2/lib/libtriutils.so;/home/ztdep/lib/Trilinos-13.2/lib/libzoltan.so;/home/ztdep/lib/Trilinos-13.2/lib/libepetra.so;/home/ztdep/lib/Trilinos-13.2/lib/librtop.so;/home/ztdep/lib/Trilinos-13.2/lib/libkokkoskernels.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchoskokkoscomm.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchoskokkoscompat.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchosremainder.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchosnumerics.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchoscomm.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchosparameterlist.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchosparser.so;/home/ztdep/lib/Trilinos-13.2/lib/libteuchoscore.so;/home/ztdep/lib/Trilinos-13.2/lib/libkokkosalgorithms.so;/home/ztdep/lib/Trilinos-13.2/lib/libkokkoscontainers.so;/home/ztdep/lib/Trilinos-13.2/lib/libkokkoscore.so;/usr/lib64/liblapack.so;/usr/lib64/libblas.so;/usr/lib/hpc/gnu7/mpi/mpich/3.3.2/lib64/libmpicxx.so;/usr/lib/hpc/gnu7/mpich/petsc/3.14.5/lib64/libpetsc.so;/usr/lib/hpc/gnu7/mpich/scalapack/2.1.0/lib64/libscalapack.so;/usr/lib/hpc/gnu7/openblas/0.3.13/lib64/libopenblas.so;/usr/lib/hpc/gnu7/mpich/hdf5/1.10.7/lib64/libhdf5.so;gfortran;m;quadmath;dl;/home/ztdep/lib/p4est-2.8/lib/libp4est.a;/home/ztdep/lib/p4est-2.8/lib/libsc.a;/usr/local/lib64/libscalapack.so;-lm;-ldl;/usr/lib64/libopenblas.so;/usr/lib/hpc/gnu7/mpi/mpich/3.3.2/lib64/libmpifort.so;/usr/lib/hpc/gnu7/mpi/mpich/3.3.2/lib64/libmpi.so;
    

  

Call Stack (most recent call first):
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:136 (VERBOSE_INCLUDE)

**Comment by drwells** [comment]
This is much more likely to be an issue with the way these libraries were installed than an issue with deal.II itself - can you post this message as well as `CMakeFiles/CMakeError.txt` and `CMakeFiles/CMakeOutput.txt` to the mailing list instead? Thanks!

**Comment by ztdepztdep** [comment]
[CMakeError.log](https://github.com/dealii/dealii/files/9969785/CMakeError.log)
[CMakeOutput.log](https://github.com/dealii/dealii/files/9969786/CMakeOutput.log)

**Comment by drwells** [comment]
Lets continue this discussion on the mailing list.
