### ISSUE TITLE
Documentation of VectorTools::interpolate_boundary_values()

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1443]
I think there might be something wrong in the following sentence.
```
If the boundary_values object contained values before, the new ones are added, or the old ones overwritten if a node of the boundary part to be used was already in the map of boundary values.
```
But I am not sure, neither about its meaning nor grammar.

According to my understanding, the sentence wants to say that new boundary values will be added and existing  boundary values will be updated, just like the effect of [] operator of std::map.

If my understanding is correct, I'd like to update this piece of documentation.

**Comment by tjhei** [comment]
yes, existing values remain in there but will be updated to the new values if dof indices coincide.

**Comment by bangerth** [comment]
Your interpretation is correct. Feel free to propose a patch.
