### ISSUE TITLE
Allow multiple comparison files in the testsuite

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1459]
In reference to #1458, and #

We have some tests that result in entirely different output depending on platform, compiler, userland.
Unfortunately, those situations cannot be solved by using numdiff; and it is not always possible to rewrite those tests to be more robust in a meaningful way...

Therefore, I suggest that we allow for multiple comparison files for a test.

There are some design and policy decisions we have to agree upon:

 - Multiple comparison files should only be used if absolutely necessary.

 - I can give the following layout a try:
    ```
    test.[...].output
    test.[...].variant=2.output
    test.[...].variatn=3.output
    ```
   The logic in ```DEAL_II_PICKUP_TESTS``` would be to short-circuit on every file with ```variant=[something]```
  - the driver ```run_test.sh``` will try to match against the "blessed" master output file and all variants.

  - If the test successfully compares against a variant this is shown in the output. (Default behavior if a successful match against the "blessed" master output file is made).

  - on failure a diff against ```test.[...].output``` is shown.

**Comment by bangerth** [comment]
The missing reference in the first line above is for #1412, for completeness.
