### ISSUE TITLE
which configuration errors are fatal?

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#14606]
Some errors are so fatal that cmake stops completely. But now:

```
-- Configuring incomplete, errors occurred!
See also "/work2/00434/eijkhout/dealii/build-9.4.1-frontera-oneapi-impi/CMakeFiles/CMakeOutput.log".
See also "/work2/00434/eijkhout/dealii/build-9.4.1-frontera-oneapi-impi/CMakeFiles/CMakeError.log".
```

The terminal log shows messages such as

```
-- Could NOT find SYMENGINE
-- DEAL_II_WITH_SYMENGINE has unmet external dependencies.
```

which I doubt are fatal. So how do I find what actually went wrong? I'm finding this:

```
CMake Error at /work2/00434/eijkhout/trilinos/installation-13-0-1-frontera-oneapi-impi/lib/cmake/ShyLU/ShyLUConfig.cmake:156 (INCLUDE):
  INCLUDE could not find requested file:

    /work2/00434/eijkhout/trilinos/installation-13-0-1-frontera-oneapi-impi/lib/cmake/ShyLU/../ShyLU_Node/ShyLU_NodeConfig.cmake
```

which looks a little more serious, but cmake apparentely took it in stride. 
[deallog.zip](https://github.com/dealii/dealii/files/10281006/deallog.zip)
So?

**Comment by Rombur** [comment]
The problem is from ShyLU. I have had similar experience a few times with Trilinos. If there is a problem with one of the Trilinos package that deal.II does **not** use, the configuration will keep going and won't report anything until the very end when CMake errors out. It looks like one configuration file was not installed correctly when you built Trilinos.

**Comment by tamiko** [comment]
@VictorEijkhout We have decided to make all configuration errors within deal.II fatal for that reason. The `CMake Error` reported from `/work2/00434/eijkhout/trilinos/installation-13-0-1-frontera-oneapi-impi/lib/cmake/ShyLU/ShyLUConfig.cmake` is indeed the reason why the configuration failed. 

Related upstream discussion: https://gitlab.kitware.com/cmake/cmake/-/issues/19351
