### ISSUE TITLE
Tests stop running in parallel after a certain number of tests have been carried out

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#14648]
Dear all,
I hope you are well.
In the last week, it seems like some changes were made to the default behavior of deal.II tests (and also the tests of user projects which are derived from the deal.II testing framework).
When running in parallel, tests will run in parallel until a certain fraction of the tests (say 75% of the tests) are completed, then they will start running one by one.
This is only a minor annoyance, but I was wondering if this was intended or, if not, what causes this?

**Comment by tamiko** [comment]
@blaisb How is your testsuite organized? Are these tests that you trigger with a common `.prm` file?
If so, then 3e5ca655adbe8b9110ecfb5dc9f9dc28a34dd1ff is the issue.

**Comment by blaisb** [comment]
> @blaisb How is your testsuite organized? Are these tests that you trigger with a common `.prm` file? If so, then [3e5ca65](https://github.com/dealii/dealii/commit/3e5ca655adbe8b9110ecfb5dc9f9dc28a34dd1ff) is the issue.

Ohh I did not notice that but yes! I think this starts when we have the first tests where we run the same case with mpirun=1 and mpirun=2. If so that would make perfect sense!

**Comment by bangerth** [comment]
Wouldn't that be easier to solve by breaking tests into more individual targets (one for the executable, one for running the test, etc), and then making sure that multiple tests don't set up the same target more than once?

**Comment by blaisb** [comment]
> Can you try ctest --schedule-random?

Sure I will give it a try as soon as I have access to my main machine :)!

**Comment by blaisb** [comment]
@tjhei I tried with the --schedule-random argument and it did not change much. At teh end tests ended up running one by one after a certain time. I guess when the test that is with both mpirun=2 and mpirun=1 ran.

I mean this is not a major issue, but it's a bit weird. Is there anything i can do to help fix this @tamiko ?

**Comment by tamiko** [comment]
@blaisb Testing a pull request that I will (hopefully) push tonight :smile:

**Comment by blaisb** [comment]
@tamiko  God you guys are awesome....
