### ISSUE TITLE
Misprinted equation

### ISSUE THREAD

**Issue by kostyfisik** [dealii/dealii#1469]
The equation do not render due to possible misprint 
at https://www.dealii.org/developer/doxygen/deal.II/group__UpdateFlags.html
screenshot attached (reproduced in Chrome and Firefox)

![screenshot from 2015-08-30 13 50 44](https://cloud.githubusercontent.com/assets/5239997/9566852/781a1fc2-4f1e-11e5-8449-e21f974048e4.png)

**Comment by bangerth** [comment]
Indeed. Patch is in #1472. Thanks for pointing it out!

**Comment by kostyfisik** [comment]
Thank you for the deal.ii !
