### ISSUE TITLE
mapping_collection not defined

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#14695]
```
/work/00434/eijkhout/dealii/dealii-9.4.1/include/deal.II/numerics/vector_tools_project.templates.h:1020:49: warning: instantiation of variable 'dealii::hp::StaticMappingQ1<1>::mapping_collection'
required here, but no definition is available [-Wundefined-var-template]
    project(hp::StaticMappingQ1<dim, spacedim>::mapping_collection,
                                                ^
/work/00434/eijkhout/dealii/dealii-9.4.1/include/deal.II/hp/mapping_collection.h:150:45: note: forward declaration of template entity is here
    static MappingCollection<dim, spacedim> mapping_collection;
```

Logs attached.
[deal94.zip](https://github.com/dealii/dealii/files/10438367/deal94.zip)

**Comment by bangerth** [comment]
@VictorEijkhout What compiler is this using? Perhaps clang 3.9?

This sounds related to #3705.

**Comment by VictorEijkhout** [comment]
Intel OneAPI. See the configure log for the exact version.

**Comment by bangerth** [comment]
I see, yes, this is an LLVM-based compiler, so I assume the warning is the same. Patch forthcoming.

**Comment by bangerth** [comment]
The patch in #14698 didn't quite seem to fix it all. So I'm reopening it -- maybe #14701 does it.

@VictorEijkhout Would you mind trying out #14701?
