### ISSUE TITLE
find_all_active_cells_around_point issue with simplex

### ISSUE THREAD

**Issue by necioglu** [dealii/dealii#14704]
I am trying to use 3D simplex elements (for an application in the project ExaDG https://github.com/exadg/exadg) and the dealii function `find_all_active_cells_around_point
` https://github.com/dealii/dealii/blob/6aa4b37c1c490fd5f3d0a0633d871976515df8c9/source/grid/grid_tools_dof_handlers.cc#L597-L603
leads me to the Assert:
https://github.com/necioglu/dealii/blob/c1ef6fab04853405c037b3eb759482b4d30e5aac/include/deal.II/grid/tria_accessor.templates.h#L1371

@peterrum mentioned to me that the following lines are written for quad/hex elements and might be the reason for the error:

https://github.com/dealii/dealii/blob/6aa4b37c1c490fd5f3d0a0633d871976515df8c9/source/grid/grid_tools_dof_handlers.cc#L644-L649

https://github.com/dealii/dealii/blob/6aa4b37c1c490fd5f3d0a0633d871976515df8c9/source/grid/grid_tools_dof_handlers.cc#L686-L688

FYI @bergbauer @nfehn

**Comment by necioglu** [comment]
The following lines in the function `extrude_triangulation` leads me to the same error. But I don't know if `extrude_triangulation` has simplex support.
https://github.com/necioglu/dealii/blob/c1ef6fab04853405c037b3eb759482b4d30e5aac/source/grid/grid_generator.cc#L7093-L7094

**Comment by peterrum** [comment]
> The following lines in the function extrude_triangulation leads me to the same error. But I don't know if extrude_triangulation has simplex support.
https://github.com/necioglu/dealii/blob/c1ef6fab04853405c037b3eb759482b4d30e5aac/source/grid/grid_generator.cc#L7093-L7094

The assert you get only means that in 2D the fourth vertex is queried; the is possible for quads but not for triangles. It is normally a sign that the function has not been generalized yet. In this case, `extrude_triangulation()` has not been generalized yet. One would need to use wedges, which is already implemented.

**Comment by necioglu** [comment]
> > The following lines in the function extrude_triangulation leads me to the same error. But I don't know if extrude_triangulation has simplex support.
> > https://github.com/necioglu/dealii/blob/c1ef6fab04853405c037b3eb759482b4d30e5aac/source/grid/grid_generator.cc#L7093-L7094
> 
> The assert you get only means that in 2D the fourth vertex is queried; the is possible for quads but not for triangles. It is normally a sign that the function has not been generalized yet. In this case, `extrude_triangulation()` has not been generalized yet. One would need to use wedges, which is already implemented.

I see. Thank you.

**Comment by drwells** [comment]
Fixed by #15328 etc.
