### ISSUE TITLE
Use -flto when available

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1477]
GCC has this link-time-optimization thing, using the -flto flag. This has the advantage that it can do optimization across object file boundaries, without the need to make a lot of functions inline. Among the other interesting features is that it can run many of the optimizations using multiple threads/processes. This would allow us to use more of the processors we don't currently use very well during the link stage.

See for example http://stackoverflow.com/questions/31355692/cmake-support-for-gccs-link-time-optimization-lto (which may or may not actually be related to what I'd like to do).

As a caution, when I tried -flto last by hand (with gcc 4.6? 4.7?) it crashed on our files. We'd need to have a GCC version check in addition to a check that tests that the flag is actually available.

**Comment by tamiko** [comment]
A big issue for enabling "-flto" is the resulting memory usage for linkage.
So I'm a bit hesitant in enabling it per default.

Related to this, there are also optimization options that we currently don't enable per default (with very good reason), e.g., ```-march=native```, or ```-march=cpu```. I'd say ```-flto``` is part of this category.

**Comment by bangerth** [comment]
Yes, good point. `-march=native` helps a lot in release mode performance.

I think with `-flto`, I simply need to try again one of these days.

**Comment by tamiko** [comment]
```
diff --git a/cmake/checks/check_01_compiler_features.cmake b/cmake/checks/check_01_compiler_features.cmake
index d26a2f2..1bb7dde 100644
--- a/cmake/checks/check_01_compiler_features.cmake
+++ b/cmake/checks/check_01_compiler_features.cmake
@@ -360,3 +360,22 @@ IF(DEAL_II_COMPILER_HAS_FUSE_LD_GOLD)
   ADD_FLAGS(DEAL_II_LINKER_FLAGS "-fuse-ld=gold")
 ENDIF()
 
+
+#
+# Link time optimization:
+#
+
+PUSH_CMAKE_REQUIRED("-Werror")
+PUSH_CMAKE_REQUIRED("-flto -fuse-ld=gold")
+CHECK_CXX_SOURCE_COMPILES(
+  "
+  int main() { return 0; }
+  "
+  DEAL_II_COMPILER_HAS_FLTO)
+RESET_CMAKE_REQUIRED()
+
+IF(DEAL_II_COMPILER_HAS_FLTO AND DEAL_II_COMPILER_HAS_FUSE_LD_GOLD)
+  ADD_FLAGS(DEAL_II_CXX_FLAGS_RELEASE "-flto")
+  ADD_FLAGS(DEAL_II_LINKER_FLAGS_RELEASE "-flto")
+ENDIF()
+
```

**Comment by tamiko** [comment]
Clink needs roughly half an hour for linking...

**Comment by bangerth** [comment]
It takes half an hour to link a one-line piece of code? Seriously?

What is the corresponding time for GCC?

**Comment by tamiko** [comment]
On Mon, Sep 14, 2015, at 11:02 CDT, Wolfgang Bangerth <notifications@github.com> wrote:

> It takes half an hour to link a one-line piece of code? Seriously?

No, to initially link the library.

**Comment by bangerth** [comment]
Ouch. That's too much :-( What's the order of magnitude for GCC?

**Comment by tamiko** [comment]
With a static archive (LLVM IR for later -flto linkage) linking step-3 requires:
```
make release  381.08s user 1.73s system 100% cpu 6:22.52 total
```
(compared to roughly 15 sec. for debug linkage with a traditional archive without lto).

**Comment by tamiko** [comment]
Recalling some further discussion from last week, I'll close this issue. (All required flags can be easily set during configure).
