### ISSUE TITLE
Final library compilation stage takes forever

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#14804]
My installation is stuck at
```
[ 98%] Built target deal_II.g
```
or whatever comes after.  I have a fairly powerful Cascade Lake, and it's been sitting there for an hour. Is that normal?

**Comment by tjhei** [comment]
Linking can be fairly slow if we can not detect one of the faster linkers (lld, mold) and fall back to gold or bfd. I am talking 2-3 minutes with the build directory on a local SSD. I have not seen something take an hour.

Are you building locally or on a network drive?

You can check the linker being used by showing us ``grep FLAGS detailed.log`` (and we can check for presence of ``--use-ld=XXX``.

**Comment by VictorEijkhout** [comment]
Timed out after 2 hours.

```
[staff dealii:5] grep FLAGS build-9.4.1-clx-oneapi-impi/detailed.log
#        DEAL_II_CXX_FLAGS:            -fpic -diag-disable=remark -qopenmp-simd -march=native
#        DEAL_II_CXX_FLAGS_RELEASE:    -O2 -no-ansi-alias -funroll-loops
#        DEAL_II_CXX_FLAGS_DEBUG:      -O0 -g -gdwarf-2 -grecord-gcc-switches
#        DEAL_II_LINKER_FLAGS:         -shared-intel -qopenmp -rdynamic
#        DEAL_II_LINKER_FLAGS_RELEASE:
#        DEAL_II_LINKER_FLAGS_DEBUG:
#            BOOST_CXX_FLAGS = -Wno-unused-local-typedefs
#            TBB_CXX_FLAGS = -Wno-parentheses
```

Oh, this is the Intel oneapi compiler. Let me see how it goes with other compilers. Will take a while to build all the prerequisites.

**Comment by VictorEijkhout** [comment]
Man, it's impossible to find a combination of packages and compilers that works together.

https://github.com/dealii/dealii/issues/14870

**Comment by VictorEijkhout** [comment]
Anyway, using the latest Intel classic is still hangs forever. Here is the top output:
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
141396 eijkhout  20   0   13.8g   4.7g  36752 R 100.0  2.5 382:02.53 ld.gold
```
Six hours linking?

**Comment by masterleinad** [comment]
> Six hours linking?

If I were you I would try to use a different (better?) linker like `lld`(https://lld.llvm.org/) or `mold`(https://github.com/rui314/mold).

**Comment by tjhei** [comment]
> Six hours linking?

Victor, I recall having issues with ``ld.gold`` on Frontera and/or Stampede2. Not sure if it was hanging indefinitely or if I got errors, but my Frontera guide explicitly lists using a different linker, see https://github.com/geodynamics/aspect/wiki/Installation-on-Frontera

> ``ld.gold`` seems to have issues linking deal.II, we use ``ld.bfd`` instead, by setting ``-D DEAL_II_LINKER_FLAGS='-fuse-ld=bfd'``

**Comment by VictorEijkhout** [comment]
Thanks. That worked.
