### ISSUE TITLE
Docker image has issues linking with Trilinos

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#14815]
It seems the latest docker image crashes when linking to Trilinos regarding functions that concern block vectors.
You can find the full error log here:
https://github.com/lethe-cfd/lethe/actions/runs/4232353570/jobs/7351986000

Here's an excerpt:

> `usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<std::complex<float>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doExport(Tpetra::SrcDistObject const&, Tpetra::Classes::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doExport(Tpetra::SrcDistObject const&, Tpetra::Classes::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doImport(Tpetra::SrcDistObject const&, Tpetra::Classes::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::operator=(Tpetra::Classes::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::Vector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Vector(Tpetra::Classes::Vector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)'`

And so on and so forth.
I have tested the latest master version of deal.II on my machine and I don't have this issue. Maybe it means that the Trilinos version on the Docker image is too old now?

**Comment by peterrum** [comment]
@masterleinad I don't think it is related to `std::complex`, since the issue also appears with `float`. I think it is related to the change in index type: https://github.com/dealii/dealii/pull/14811. May I ask you to revert the commit https://github.com/dealii/dealii/commit/202c63dd744946d0eeba1b0df75b65f9660bada6 to see if this is the cause. If it is we need a way to detect and configure deal.II the correct way.
