### ISSUE TITLE
Failed assertion with hanging nodes and solution transfer

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#14859]
This was reported on the mailing list - I also have a student who ran into the very same issue last week (hello @labdala). This is definitely a bug on our end since step-33 used to work. Here's the error:
```
Scanning dependencies of target run
[100%] Run step-33 with Debug configuration
T=0
   Number of active cells:       1702
   Number of degrees of freedom: 7288

   NonLin Res     Lin Iter       Lin Res
   _____________________________________
   5.144e-02        0008        5.74e-13
   4.356e-04        0008        1.18e-14
   2.155e-07        0008        7.05e-18
   2.494e-13        (converged)


--------------------------------------------------------
An error occurred in line <155> of file <dealii/source/dofs/dof_accessor_set.cc> in function
    void dealii::internal::set_dof_values(const dealii::DoFCellAccessor<dim, spacedim, level_dof_access>&, 
                                          const dealii::Vector<number>&,
 OutputVector&, bool) [with int dim = 2; int spacedim = 2; bool lda = false; 
                            OutputVector = dealii::Vector<double>; number = double]    
The violated condition was: 
    local_values_old[i] == number() || 
    get_abs(local_values_old[i] - local_values[i]) <= get_abs(local_values_old[i] + local_values[i]) *
 100000. * std::numeric_limits<typename numbers::NumberTraits< number>::real_type>::epsilon()
Additional information: 
    Called set_dof_values_by_interpolation(), but the element to be set,
    value 0.003281728677180363, does not match with the non-zero value
    0.001134142479972379 already set before.
```

**Comment by peterrum** [comment]
Enable averaging in https://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1SolutionTransfer.html#aebd38d82f946a96118f73e4e26defd61.

**Comment by drwells** [comment]
This tutorial uses the plain serial `SolutionTransfer`, not `p::d::SolutionTransfer`, which doesn't have that option.

**Comment by bangerth** [comment]
Could we identify which patch broke this? It should be possible via a `git bisect` approach.

Separately, I disagree with the approach of averaging. The two values 0.003281728677180363 and 0.001134142479972379 are clearly very different. Just averaging them is papering over what must be a real problem.

**Comment by bangerth** [comment]
For reference, this is triggered by stock step-33 without modifications. As always, a simplified testcase would also be good...

**Comment by kronbichler** [comment]
The assertion was introduced last year by #12463. Do we know that the code still worked after that PR? This would be a starting point to look for. I believe this is due to the way this tutorial program handles hanging nodes: It actually allows the solution to be discontinuous, and uses flux terms to make the scheme consistent, so I do not think that the usual assumptions we make on the solution when applying the solution transfer hold.

**Comment by bangerth** [comment]
Ah, I see now. Stupid decision back then to use flux terms.

We could run a check in `SolutionTransfer` at the beginning to see whether the assumption of continuity at hanging nodes is satisfied. If so, we enable the assertion. If not, we do the averaging or something else.

**Comment by bangerth** [comment]
What do we want to do about this? One of our tutorial programs does not currently run. Can we fix this before the relase?

**Comment by bangerth** [comment]
I think I know how to deal with this -- I just needed to get dropped from yesterday evening's race ride and have a blank mind to figure it out.

Will deal with it after doing some yard work.

**Comment by drwells** [comment]
@labdala I regret not taking more notes when we ran into this - do you remember where we encountered this in your application? If you have this information available we should use it to double-check that we don't need to adjust anything inside deal.II to fix this issue.

**Comment by bangerth** [comment]
I've come to conclude that the assertion is reasonable and that the place where we call `SolutionTransfer` is not.

**Comment by labdala** [comment]
@drwells I am pretty sure I ran into this when I was modifying Step 23 simplex cells and AMR. I am sending you more info over slack.
