### ISSUE TITLE
Question: batched FE_Values reinit?

### ISSUE THREAD

**Issue by GrahamBenHarper** [dealii/dealii#14872]
I have a brief question related to `FE_Values` and GPUs. Usually there is some notion of "worksets" or batched computations, but when I look at [step-64](https://www.dealii.org/current/doxygen/deal.II/step_64.html), it seems the main assembly routine consists of doing a reinit on each cell
```cpp
for (const auto &cell : dof_handler.active_cell_iterators)
    if (cell->is_locally_owned())
      {
        cell_rhs = 0;
 
        fe_values.reinit(cell);
...
```
Have things like worksets or batched cell reinits been considered, or are these technical details hidden away under the interface? Thanks for your time :)

**Comment by masterleinad** [comment]
The point of `step-64` is the matrix-free interface on GPUs and assembling the right-hand side is not the focus but we could likely also use a matrix-free approach for that similar to what `step-37` is doing, see https://www.dealii.org/current/doxygen/deal.II/step_37.html#LaplaceProblemassemble_rhs.

**Comment by GrahamBenHarper** [comment]
Ah, that's exactly what I had in mind! Is that capability on GPUs currently possible, but not currently demonstrated in a tutorial program?

**Comment by masterleinad** [comment]
> Ah, that's exactly what I had in mind! Is that capability on GPUs currently possible, but not currently demonstrated in a tutorial program?

In the actual matrix-free operator, the cells are batched (avoiding write conflicts between dofs) internally already.

**Comment by GrahamBenHarper** [comment]
Got it; that's what I assumed, but wanted to double-check. Thanks @masterleinad!
