### ISSUE TITLE
Remove CMake test for `MPI_SEEK_SET` or make it more portable

### ISSUE THREAD

**Issue by sloede** [dealii/dealii#14922]
The FindMPI module for CMake includes a test for the presence of `MPI_SEEK_SET`:
https://github.com/dealii/dealii/blob/e8e4301323e57105750592280404d1468d08a915/cmake/modules/FindDEAL_II_MPI.cmake#L65-L74

The test requires `MPI_SEEK_SET` to be a preprocessor definition, which is more restrictive than what the MPI standard mandates. This causes problems with MPI implementations such as [MPItrampoline](https://github.com/eschnett/MPItrampoline), which defines it as
```c
extern int MPI_SEEK_SET;
```

A quick grep on the sources for deal.II v9.4.1 shows that `MPI_SEEK_SET` does not seem to be used (and neither are `MPI_SEEK_CUR` or `MPI_SEEK_END`). Thus my question is: Would it be possible to remove this test altogether? Or, if it is still needed, could it be changed to something that would work for MPItrampoline, e.g.,
```cmake
CHECK_CXX_SOURCE_COMPILES(
  "
  #include <mpi.h>
  int main() {
    MPI_SEEK_SET;
  }
  "
  MPI_HAVE_MPI_SEEK_SET
  )
```

cc @eschnett

**Comment by masterleinad** [comment]
The last occurrence was removed in https://github.com/dealii/dealii/commit/abbca7729de0bd6704a7c18a4f2507bccc082b0a. I would think it's OK to remove the check now.
