### ISSUE TITLE
CXX11 thread test fails if forcing mpic++

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1493]
when configuring with
```
CXX=mpic++ cmake -D DEAL_II_WITH_MPI=ON .
```
I am getting DEAL_II_WITH_CXX11 = OFF with gcc 4.8 because
```
/usr/bin/mpic++    -DDEAL_II_HAVE_CXX11_THREAD -std=c++11 -pthread    CMakeFiles/cmTryCompileExec3306332637.dir/src.cxx.o  -o cmTryCompileExec3306332637 -rdynamic 
make[1]: Leaving directory `/scratch/deal-build/build-temp/CMakeFiles/CMakeTmp'

Return value: FAILED_TO_RUN
Source file was:

        #include <thread>
        void f(int){}
        int main(){ std::thread t(f,1); t.join(); return 0; }
```
while 
```
cmake -D DEAL_II_WITH_MPI=ON .
```
succeeds with c++11 support. I think this is because -Wl,--no-as-needed is handled differently (or -pthread is not at the end).

**Comment by tjhei** [comment]
Any ideas?

**Comment by Rombur** [comment]
That's very strange. Marek apparently got the same problem on the mailing list: https://groups.google.com/forum/#!topic/dealii/jAjWXD9vOb4 (CANDI forces to export CXX=mpic++) Apparently it works with gcc 4.9

**Comment by Rombur** [comment]
I wonder if the problem comes from the mpi library itself. It seems that several distribution compiles openmpi without thread support, could this be the problem?

**Comment by tamiko** [comment]
I cannot reproduce with gcc-4.8.5 and
```
[I] sys-cluster/openmpi
     Installed versions:  1.4.3(08:37:53 09/01/15)(cxx fortran ipv6 -heterogeneous -mpi-threads -pbs -romio -threads -vt ELIBC="-FreeBSD")

```

This is a minimal lxc container with just openmpi and a toolchain installed.

**Comment by tamiko** [comment]
@tjhei What is the full gcc version, openmpi version and the userland?

**Comment by tjhei** [comment]
Has to do with -as-needed:
```
heister@t530 ~/temp $ cat c.cc
  #include <thread>
        void f(int){}
        int main(){ std::thread t(f,1); t.join(); return 0; }
heister@t530 ~/temp $ g++ -pthread -std=c++11 c.cc && ./a.out
heister@t530 ~/temp $ mpic++ -pthread -std=c++11 c.cc && ./a.out 
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)
heister@t530 ~/temp $ mpic++ -pthread -std=c++11 -Wl,--no-as-needed c.cc && ./a.out 
heister@t530 ~/temp $
```
here is my system info:
```
heister@t530 ~/temp $ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
heister@t530 ~/temp $ apt-cache show libopenmpi-dev
Package: libopenmpi-dev
Priority: extra
Section: universe/libdevel
Installed-Size: 3147
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Open MPI Maintainers <pkg-openmpi-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: openmpi
Version: 1.6.5-8
Depends: libc6 (>= 2.8), libopenmpi1.6 (= 1.6.5-8), openmpi-common (= 1.6.5-8), libibverbs-dev, libhwloc-dev
Conflicts: libopenmpi-dev, openmpi-bin (<= 1.2.4-0), openmpi-dev
Filename: pool/universe/o/openmpi/libopenmpi-dev_1.6.5-8_amd64.deb
Size: 379422
MD5sum: f500358ae1badfa1baa2b7bb856c4460
SHA1: 328f4d38c7b1845a801f1e085a987e647960322a
SHA256: 6af2e5979d2d3b16ee0b2af2aa0573302649cd58f6d0ba0bef56a6199c13cb36
Description-en: high performance message passing library -- header files
 Open MPI is a project combining technologies and resources from several other
 projects (FT-MPI, LA-MPI, LAM/MPI, and PACX-MPI) in order to build the best
 MPI library available. A completely new MPI-2 compliant implementation, Open
 MPI offers advantages for system and software vendors, application developers
 and computer science researchers.
 .
 This package contains the header files and compiler wrappers which are needed
 to compile and link programs against libopenmpi.
Description-md5: 8e5ff602ff3f7813a4a4cf41dfc27331
Homepage: http://www.open-mpi.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m

heister@t530 ~/temp $ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
Linux t530 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Rombur** [comment]
I was also able to reproduce the problem. I found this link https://root.cern.ch/phpBB3/viewtopic.php?t=19124 that says that the order of the flags matter when using -as-needed but I wasn't able to get the code to work unless I added -Wl,-no-as-needed :-(

**Comment by Rombur** [comment]
This is an ugly bug because it means that we cannot use deal.II with Trilinos 12 unless we turn off most packages of Trilinos (I just tried and it crashes during linking). Is there a good reason why we can't add -Wl,-no-as-needed to our flags.

**Comment by tamiko** [comment]
> This is an ugly bug because it means that we cannot use deal.II with
> Trilinos 12 unless we turn off most packages of Trilinos (I just tried
> and it crashes during linking). Is there a good reason why we can't
> add -Wl,-no-as-needed to our flags.

Yes, there is. First of all, -Wl,-as-needed is nowadays the defacto
standard and accepted way to do linkage.

Secondly, we do not have this under control. There are Linux
distributions out there that set -Wl,-as-needed in their spec files.

And last, but not least, it is a "brutal" fix for an otherwise unrelated
problem.


Is it necessary to link with -Wl,-no-as-needed? Or is it only necessary
to run the test with it?


I see the following possibility to circumvent this mess:


 * Provide -Wl,-no-as-needed as fallback (provided that it is indeed
   necessary to use the compiler wrappers): We check for
   DEAL_II_CXX11_WITH_THREADS, if it falls, check again with
   -Wl,-no-as-needed, if this succeeds
    * enable C++11 support
    * register -Wl,-no-as-needed in DEAL_II_LINKER_FLAGS

And, there is always:

 * Educate to not use the compiler wrappers in this case - it is
   perfectly fine to hint for the wrapper and just link against mpi
   libraries directly.

**Comment by Rombur** [comment]
So I commented the CXX11 threads test and I was able to compile deal.II and run step-32. To reproduce the bug I have to use a virtual machine on my laptop so I can't run the full testsuite but it seems that we can just run the test with -Wl,-no-as-needed.

**Comment by tamiko** [comment]
On Thu, Sep  3, 2015, at 08:35 CDT, Bruno Turcksin <notifications@github.com> wrote:

> So I commented the CXX11 threads test and I was able to compile
> deal.II and run step-32. To reproduce the bug I have to use a virtual
> machine on my laptop so I can't run the full testsuite but it seems
> that we can just run the test with -Wl,-no-as-needed.

Ah, perfect.
