### ISSUE TITLE
Test tutorials

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#15016]
in reference to https://github.com/dealii/dealii/issues/14844

**Comment by tjhei** [comment]
I have a working implementation of that, but it is a few years old. I can revive that with @tamiko 's help.
I basically apply a patch to the tutorials to make them run in reasonable time to turn them into tests. The modified files are not stored in git, just the patches.

**Comment by bangerth** [comment]
What if we stored this patch somewhere in the git repository under `tests/` and thereby auto-create a whole category of tests that can be run along with all of the other tests? With a bit of cmake magic, it shouldn't be too hard to auto-create tests that we can pick up with `make setup_tests`.

**Comment by tamiko** [comment]
I think we are almost done here and are tracking progress on a different issue/pull request. Closing.
