### ISSUE TITLE
Improve documentation of reference cells, orientation, ...

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#15017]
see: https://www.dealii.org/developer/doxygen/deal.II/group__simplex.html

**Comment by drwells** [comment]
See also #14667.

**Comment by bangerth** [comment]
Did you close this on purpose?

**Comment by peterrum** [comment]
@bangerth Yes. I consider this as a duplicate of https://github.com/dealii/dealii/issues/14667.
