### ISSUE TITLE
Where to put pictures of the documentation?

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#15036]
We have different places to position pictures, e.g.,
- https://github.com/dealii/dealii/tree/master/doc/doxygen/images -> https://github.com/dealii/dealii/pull/15033
- https://github.com/dealii/old-website/tree/main/images -> https://github.com/dealii/dealii/pull/14818

These places are used a bit inconsistently.

I am not particular fond of putting figures into the main code repo. That's why I would suggest to only add pictures to the webside repo.

Any opinions?

**Comment by tjhei** [comment]
> I am not particular fond of putting figures into the main code repo. That's why I would suggest to only add pictures to the webside repo.

Agreed.

**Comment by peterrum** [comment]
> That's why I would suggest to only add pictures to the webside repo.

I just noticed this repo is private... That is suboptimal...

**Comment by tjhei** [comment]
@tamiko ?

**Comment by tamiko** [comment]
@peterrum @tjhei Let's add all images to `old-website` for the time being. We will migrate the contents over to the `website` soon when the replacement website is somewhat up and running (and made public).
