### ISSUE TITLE
Sort vertices by the order in which we traverse them

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15044]
I came across this paper https://dl.acm.org/doi/full/10.1145/3503925: "On Memory Traffic and Optimisations for Low-order Finite Element Assembly Algorithms on Multi-core CPUs". @kronbichler and @peterrum might be interested in it as well.

In any case, the paper shows that if one sorts the array of vertex locations by the order in which vertices are accessed during assembly, that that dramatically reduces cache misses and off-chip memory traffic. We're generally quite good at storing data in the order in which it is accessed, but we make no attempt at doing so for the vertices array.

It would not be very difficult to order vertices at the end of `create_triangulation()` and `execute_coarsening_and_refinement()` by the order one accesses them in loops over all cells. I imagine that we'd get a fair bit of breakage, or maybe not so much after all given that codes generally work on DoF indices, not vertex indices -- it might be worth trying that out.

**Comment by peterrum** [comment]
@bangerth Thank you for pointing out the paper. I'll take a look at it later.

Within the matrix-free infrastructure, we have been working on optimizing data access via renumbering DoFs. If you are interested, you can take a look at https://journals.sagepub.com/doi/abs/10.1177/10943420221107880 and the implementation within https://www.dealii.org/developer/doxygen/deal.II/namespaceDoFRenumbering.html#a0d8946e3a249c853976a4f7f48587f55.

**Comment by bangerth** [comment]
Right, ordering DoFs was another recommendation in the paper, but not one I wanted to put into the default path of deal.II :-) But it occurs to me that calling this reordering function might be useful in ASPECT -- @tjhei?

**Comment by tjhei** [comment]
I would think reordering DoFs or the cell traversal makes more sense than reordering vertices.
The DoF reordering in ASPECT might be worth trying...

**Comment by kronbichler** [comment]
I know the paper. It's a pretty nice writeup, and when I first read it I regretted that I never picked up the developments I had done on the addition of entries into sparse matrices (that you found in #15048) and wrote a paper about it. In 2010/2011, it would have been pretty interesting. Anyway, I'm happy someone has done that work now, because it shows that the process can be done much better than what one would try out-of-the-box.

**Comment by bangerth** [comment]
Yes, it was interesting to read through `AffineMatrix::distribute_local_to_global()` and see all the stuff you optimized :-)

I was surprised that they never picked up on the issue of the bisection search. My only explanation is that they didn't see the need because they only have low-order, scalar elements. In that case, there are never many entries per row and so the bisection search is not inefficient. But we often have 100s of entries per row, and walking linearly clearly makes more sense in that case, assuming we already get a sorted array of indices.

**Comment by bangerth** [comment]
We decided in #15689 that this isn't worth it.
