### ISSUE TITLE
Should we have a 'timestepping' folder?

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#15089]
Not our most pressing issue, but I noticed with the recent support for PETSc TS objects that we now have time-stepping classes in `sundials/`, `lac/`, `numerics/`, and `algorithms/`.

We should have a discussion on whether we should continue putting wrappers in folders named for the dependency or, alternatively, put them in folders named for topics. I think sorting things by topic would improve discoverability.

**Comment by bangerth** [comment]
I think a common subdirectory might make sense.

**Comment by bangerth** [comment]
I think that train has left the station with step-86. It is what it is.
