### ISSUE TITLE
Do not return error codes via int return values in external interfaces

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15112]
As discussed in https://github.com/dealii/dealii/pull/15065#issuecomment-1514297500, the SUNDIALS IDA/KINSOL/... interfaces but now also the PETSc ODE solver interfaces and possibly SNES interfaces ask user callbacks to indicate error states via `int` return values. I have not looked into the NOX interfaces, but if they're like the KINSOLS ones, then they do the same. This is decidedly not the C++ way, and we may want to change this while several of these interfaces are still new.

The question, fundamentally, is whether any of these libraries can actually do something useful if a user function returns something nonzero. For example, is there a case where PETSc could actually recover if a user function returns something nonzero? Because if that were not so, then perhaps it would be a better design if we let user functions throw exceptions as we always do, and let user codes catch these exceptions after letting them propagate through all of PETSc until we come back out in our interfaces again.

(I *suspect* that upon getting a nonzero error code, PETSc doesn't just give up but instead does cleanup actions such as releasing temporary vectors etc. We would shortcut this if we let exceptions propagate through PETSc because PETSc is written in C and can't automatically run destructors when exceptions are processed. To enable this, we may have to catch the user-thrown exception in the wrappers, return a nonzero error code to PETSc, let things propagate backward from there, and when the outermost function returns an error code, reinstate and rethrow the exception.)

@stefanozampini Do you have thoughts on this?
@sebproell For the SUNDIALS interfaces?
@peterrum For the NOX interfaces?

**Comment by bangerth** [comment]
Saving and later re-throwing exceptions works as described here: https://stackoverflow.com/questions/2960554/correct-way-to-store-an-exception-in-a-variable

**Comment by tamiko** [comment]
Or simply use a RAII wrapper for the resource allocation. Then, during stack unwinding due to the exception, the guard object goes out of scope and the destructor of the guard object frees all objects.

**Comment by sebproell** [comment]
In principle, I am very much in favor of not returning error codes. Whenever I have to write functions e.g. for NOX I tend to forget the "useless" `return 0;` before being reminded by the compiler. 

However, for SUNDIALS I don't know if this will work. Just one example:

> Return value: An ARKRhsFn should return 0 if successful, a positive value if a recoverable error occurred (in
which case ARKStep will attempt to correct), or a negative value if it failed unrecoverably (in which case the
integration is halted and ARK_RHSFUNC_FAIL is returned).

So they at least claim to support non-zero exit codes.

**Comment by tamiko** [comment]
@sebproell But this sounds like that we want to do something with the error code internally, not that we necessarily want to expose the error code to the user (as a return value).

For example, for most of the Trilinos interfaces we simply do something of the form `Assert(ierr == 0, ExcTrilinosError(ierr));` We do not return the value itself to the user (other than being part of the error message).

**Comment by sebproell** [comment]
@tamiko The function I mentioned above is a user-supplied function, which SUNDIALS calls internally! Sorry, didn't state that clearly.  Essentially, they expect a SUNDIALS user to write a function that returns an exit code to the SUNDIALS internals. If we don't allow that through the signatures in deal.II wrapper classes we take this option away from users.

What you mentioned for Trilinos is already done for all calls to SUNDIALS.

**Comment by bangerth** [comment]
I would appreciate if all of you would take a look at #15146 and see whether that would be a workable proposal to deal with the situation. If so, I could start implementing this approach.

**Comment by tjhei** [comment]
Looks good to me.

**Comment by stefanozampini** [comment]
Ok for me to

**Comment by sebproell** [comment]
@bangerth Sounds reasonable.
