### ISSUE TITLE
Require C++11

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1519]
So when do we want to finally pull the plug for C++98/03 support?

The advantages we would gain are obvious:
- C++ language feature in the library. My current workflow is to develop on C++11 and then backport to C++98... And given the fact how C++98/03 support looks like at the moment [1], how much I've cleaned up in the last weeks, and how much got approved and merged that clearly broke C++98 support - I'd guess that this is also the workflow for pretty much everyone else.
- We could clean up quite a bunch of the library:
  - the majority of our custom type traits stuff can be purged
  - `LinearOperator` supersedes a sizable number of custom wrapper classes
- More and more external dependencies will force us to do so anyway...
- Our defacto lowest supported version is gcc-4.6'ish, clang-3.3'ish and icc-15'ish (and probably already no 14\* support any more). All of those support C++11 to the extend we need.

A good time could be for example as soon as the gcc-5\* variants hit stable distributions. They ship a new (ABI incompatible) C++ library that allows to mix all supported language variants (C++11 introduced an ABI change, fun...)

[1] http://cdash.kyomu.43-1.org/buildSummary.php?buildid=11991

**Comment by bangerth** [comment]
I think new distributions with GCC 5.x seem like a good criterion. How about we roll out another 2 releases that don't require C++11? That would mean making the switch in about a year.

FEniCS just released their first release that requires C++11. We could also ask them in a few months what their experience was in retrospect regarding their user base.

**Comment by bangerth** [comment]
@kronbichler -- most of the failing tests @tamiko links to seem to all fail in one of the matrixfree headers:
http://cdash.kyomu.43-1.org/testDetails.php?test=20689718&build=11991
Want to take a look?

**Comment by kronbichler** [comment]
Another point of reference: Trilinos requires C++11 support since this spring, see also here:
https://trilinos.org/about/cxx11/

**Comment by kronbichler** [comment]
@bangerth I'm already looking into it.

**Comment by kronbichler** [comment]
See #1521

**Comment by Rombur** [comment]
Do we need to wait for 2 releases?  Ubuntu and openSUSE will switch to gcc 5 for the next release (before the end of the year). Fedora has already switched. If we make one more release around the end of the year, the following one should be after april. At time, everybody who is on ubuntu 12.04 will have to switch to a newer LTS release with at least gcc 4.8 which support C++11.

**Comment by bangerth** [comment]
People don't always upgrade, or don't upgrade themselves. For example, we here have no control over what compiler we get. That simply makes me a bit conservative on what we expect or don't.

But how about we revisit the issue after the next release and see where everyone stands?

**Comment by tamiko** [comment]
A year sounds like a reasonable timeline.

**Comment by danshapero** [comment]
It's coming up on a year since this was last discussed. There are a few issues that can only be cleared after deal.II abandons C++98 compatibility, e.g. #2372 , #2647, and #2934 . In which release will C++98 support be deprecated? Removed?

**Comment by drwells** [comment]
I don't think there is a clear consensus on this yet. I am personally in favor of releasing 8.5 some time this fall with C++98 support and then requiring C++11 with a 9.0 release in the spring.

**Comment by drwells** [comment]
It looks like someone removed the 8.5 milestone from this so I think it is safe to say that we will do at least one more release without requiring C++11.

**Comment by bangerth** [comment]
I like this plan as well. My big machines in Texas still run with old compilers. Not sure when/it they will be updated, but for note I'm in favor of keeping it the way it is. There are not many things we can't easily work around so far.

**Comment by tamiko** [comment]
Jup, I remember that the current consensus is to do one more release with C++98 support and then jump to version 9.0 with mandatory C++11.

**Comment by drwells** [comment]
We seem to have reached a consensus on requiring either partial or full support in the 9.0 release. I am closing this in favor of the poll in #4106.
