### ISSUE TITLE
Documentation not showing up correctly - issue with DEAL_II_CXX20_REQUIRES

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#15234]
https://dealii.org/developer/doxygen/deal.II/group__PETScWrappers.html#ga29dc7b19e28e7f5fd4e22e9d5144c2b4

The documentation for the new `TimeStepper` class is no longer visible as it should, since it is wrapped by `DEAL_II_CXX20_REQUIRES` which doxygen fails to interpret.

@bangerth

**Comment by bangerth** [comment]
I verified that this is a bug in doxygen 1.9.1 that is apparently fixed in newer versions of doxygen:  It works at least in the doxygen 1.9.7 I have installed locally. I'll think of a workaround.

**Comment by luca-heltai** [comment]
Reopened: 

https://github.com/dealii/dealii/pull/15264#issuecomment-1566266325
