### ISSUE TITLE
Linker fails due to missing -rpath

### ISSUE THREAD

**Issue by jh66637** [dealii/dealii#15232]
I've been trying to find the problem myself for quite a while, but I can't get to the bottom of it. If someone could take a look, I would be very grateful. 

I encounter linking issues on a cluster with `Spack` using `GCC` and `OpenMPI`. After `deal.II` compiled successfully, I get the linker error:
```
fatal error: /gpfs/opt/sw/zen/spack-0.19.0/opt/spack/linux-almalinux8-zen2/gcc-9.5.0/hwloc-2.8.0-s7uap66oudz2vyjwxvjnyo46zahht3x/lib:pread failed: Is a directory
```
I attached the log file for the minimal set of dependencies, and I am happy to provide any additional information that might be helpful.
While the log is produced with `GCC9`, I encounter the same problems with `GCC12`. I tried on `Intel Skylake` as well as `AMD Zen` architecture and observe the same behavior. 

What stands out to me is that I am loading `openmpi-4.1.4` and the recognized `MPI_VERSION = 3.1`. However, I don't know if this is related.

[detailed.log](https://github.com/dealii/dealii/files/11499543/detailed.log)

**Comment by tamiko** [comment]
@drwells This looks like a `-Wl,--rpath` being stripped from a `-Wl,--rpath -Wl,.../pread`.
We should detect such occurences and escape them correctly by now, but somehow this doesn't seem to happen.

**Comment by drwells** [comment]
I must be missing something. The message is `fatal error: /gpfs/[...]/hwloc-2.8.0-[...]/lib:pread failed: Is a directory`. Doesn't that indicate a failure in calling `pread()`, not that `pread` is a directory we failed to read from?

**Comment by jh66637** [comment]
@tamiko @drwells Tanks you for the big help. 
I can test the behavior of https://github.com/dealii/dealii/pull/15257 on mentioned system, tomorrow.

**Comment by jh66637** [comment]
Fixes the issue for me. Thank you for the help.
