### ISSUE TITLE
fe_rannacher_turek.cc interpolate warnings

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1527]
I am getting the following warnings using intel 15:
```
In file included from /ssd/deal-git/source/fe/fe_rannacher_turek.cc(132):
/ssd/deal-git/include/deal.II/fe/fe_rannacher_turek.h(54): warning #654: overloaded virtual function "dealii::FiniteElement<dim, spacedim>::interpolate [with dim=1, spacedim=1]" is only partially overridden in class "dealii::FE_RannacherTurek<1>"
  class FE_RannacherTurek : public FE_Poly<PolynomialsRannacherTurek<dim>, dim>
        ^
```

Worth fixing in my opinion. Is it intentional that the base class version is called for all but one of the interpolate() functions?

**Comment by bangerth** [comment]
@pesser -- you wrote this element and probably know the implementation better than anyone else. Do you have a suggestion how to deal with this?

**Comment by pesser** [comment]
I'm cell phone only right now but I'll look into it later this week.
(Element is not implemented in 1d, though...)

**Comment by bangerth** [comment]
Fixed by @1614.
