### ISSUE TITLE
Document backward incompatibilities in IDA/KINSOL, etc.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#15279]
Recent PRs have introduced incompatible changes in the user interfaces of IDA, ARKODE, KINSOL, etc. 

These should be documented as incomptabilities in our changelogs.

**Comment by bangerth** [comment]
There is already a changelog entry in the incompatibilities section. I need to complete that.

**Comment by bangerth** [comment]
Related to #15112.

**Comment by bangerth** [comment]
I was wrong, there wasn't a half-finished changelog entry, so I wrote one in #15291. 

The matter only affects KINSOL/ARKode/IDA. The PETSc and NOX interfaces are new to the upcoming release.
