### ISSUE TITLE
Failed test is reported as success

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1528]
This issue relates to both the test suit and PR  #1520.

If I run the this test, everything seems going nicely.
```
charm:build$ ctest -R bits/parameter_handler_backslash_04.debug
Test project /u/qiaolei/devel/deal.II/build_withoutDocExample/build
    Start 1646: bits/parameter_handler_backslash_04.debug
1/1 Test #1646: bits/parameter_handler_backslash_04.debug ...   Passed    3.15 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   6.50 sec
```

But, what really happened is
```
bloc201a:parameter_handler_backslash_04.debug$ ls -1
failing_diff
failing_diff.*
interrupt_guard.cc_bck
output
parameter_handler_backslash_04.debug
stdout
```

```
bloc201a:parameter_handler_backslash_04.debug$ cat failing_diff
----------------
##2       #>3   <== b, c
##2             ==>
@ Line 2 in file "output" is shorter than expected!

+++  File "/u/qiaolei/devel/deal.II/dealii/tests/bits/parameter_handler_backslash_04.expect=diff.output" differs from file "output"

```
```
bloc201a:parameter_handler_backslash_04.debug$ cat stdout 
Line <4> of file <input string>:
    The entry value
        a,\ b,
    for the entry named
        Function
    does not match the given pattern
        [List list of <[Selection a|b|c|d|e|f|g|h ]> of length 0...4294967295 (inclusive)]
Line <5> of file <input string>: This line matched nothing known ('set' or 'subsection' missing!?):
    c 
```

And, I guess, the file ```failing_diff.*``` hits the problem may relate to the ```VERBATIM``` option in some CMakeList.txt file.

**Comment by QiaoLei-88** [comment]
Or something in test script is looking for ```failing_diff.*``` but the actual output file is ```failing_diff``` without '.' in file name.

**Comment by luca-heltai** [comment]
This is not an issue, since the output file is named using **expect=diff**. See the documentation here: 

https://www.dealii.org/developer/developers/testsuite.html#expect

this test makes sure that you don't get the right result using the wrong method. In other words, it tests that the actual output *is not* what the previous test was. The test is supposed to fail during the diff phase (which it does), and only then it is considered a *passed* test (exactly because it failed to diff).

**Comment by bangerth** [comment]
The new tests also succeed: http://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12070

**Comment by bangerth** [comment]
However, #1529 shows that some old tests now fail :-(
