### ISSUE TITLE
New failing test multiple_parameter_loop_01/02

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1529]
@asartori86 : #1520 leads to a failure of tests multiple_parameter_loop_01/02, see
http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=12070 . Can you take a look at what the issue is?

**Comment by asartori86** [comment]
@bangerth, sure

**Comment by asartori86** [comment]
look at #1530. I run `ctest -j4 -R 'parameter'` and got `100% tests passed, 0 tests failed out of 105` on my laptop
