### ISSUE TITLE
Fields are not reset during MappingInfo().reinit_*()

### ISSUE THREAD

**Issue by jh66637** [dealii/dealii#15305]
@bergbauer 

During adding the test in https://github.com/dealii/dealii/pull/15292 I found that some fields are not cleared before they are filled again in `reinint_*()`. Therefore, having a sequence of `reinits` leads to unwanted behavior.

In my case, I called `reinit_faces()` and `reinit_cells()` on the same `MappingInfo` object and got the wrong `JxW` due to a mismatch of quadrature indices. Using a new object works. In this particular case, e.g., `n_q_points_unvectorized` is not cleared in `reinit_cells()`. I can fix that, but I am not as familiar with all the code and will probably forget some fields which should be cleared. Would you mind taking a look?

**Comment by bergbauer** [comment]
I will have a look!
