### ISSUE TITLE
github-actions: Switch to Intel ICX compiler.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#15301]
We need to switch to the new Intel ICX compilers in our github-actions worker later this year.

```
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
```

Useful resources for porting:

- [Porting Guide for ICC Users to DPCPP or ICX](https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-icc-users-to-dpcpp-or-icx.html)
- [Compile and Run MPI Programs Using C++ with SYCL](https://www.intel.com/content/www/us/en/developer/articles/technical/compile-and-run-mpi-programs-using-dpcpp-language.html)
- [Build googletest with IntelLLVM compilers. ](https://github.com/google/googletest/commit/e032d57642d2a042b9445b2199277bb24fee2eb5)

**Comment by marcfehling** [comment]
I adjusted the github-worker and got deal.II configured with the IntelLLVM `icpx` compiler. Excerpt from `detailed.log`:
```
#        CMAKE_CXX_COMPILER:     IntelLLVM 2023.1.0 on platform Linux x86_64
#                                /opt/intel/oneapi/compiler/2023.1.0/linux/bin/icpx
```

However, compilation fails on the bundled package `muparser` with the following warning (treated as error):
```
/dealii/bundled/muparser_v2_3_3/src/muParserTest.cpp:1558:38: error: explicit comparison with infinity in fast floating point mode [-Werror,-Wtautological-constant-compare]
                                                bCloseEnough &= (fabs(fVal[i]) != numeric_limits<value_type>::infinity());
                                                                 ~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

In a different context, this issue has been discussed in https://github.com/intel/compute-benchmarks/issues/13. So what we could also try here is to either disable the `tautological-constant-compare` warning, or disable fast math for this particular file. If there is a workaround, we could also propose a patch for muparser.

@tamiko -- What do you think?

**Comment by masterleinad** [comment]
@marcfehling I am pretty much doing the same and found some issues to fix, see https://github.com/masterleinad/dealii/actions/runs/5180254064/jobs/9334204577 and https://github.com/masterleinad/dealii/tree/test_icpx.
I think `-fno-finite-math-only` is the way to go but wouldn't shy away from `-fp-model=precise` if we care about running tests and run into issues.

**Comment by marcfehling** [comment]
@masterleinad You made more progress than me on the topic :-)

I would vote for `-fno-finite-math-only` right now. We can switch to `-fp-model=precise` if we encounter problems in the (quick)tests. I mean this only affects the github-worker for now.

I will also add this to the Release 9.5 milestone, considering that icpc most probably will be removed in the period where 9.5 is going to be the most recent release.

**Comment by marcfehling** [comment]
> In this particular context, use `std::isinf` to avoid the warning/error.

I will check and propose a patch for `muparser`. If they follow-up with a release, we might want to consider updating the bundled version.

**Comment by masterleinad** [comment]
> However, other warnings pop up later. I guess we need to go through them one by one if we want to decide to drop `-fno-finite-math-only`

You basically can't use `std::isinf` if you allow finite math optimizations since it will always return `false`.

**Comment by bangerth** [comment]
That doesn't make any sense. My understanding of these flags is that they assume that inputs to math functions are valid (=finite numbers, in some cases within the bounds of the domain of the function) and that as a consequence the outputs are also. But something like `std::isinf(std::numeric_limits<double>::infinity())` should always be allowed. But perhaps those who wrote the compiler don't agree...

**Comment by masterleinad** [comment]
Mea culpa, it's `-fp-model=fast` (default for `icpx`) that causes `std::isinf` to always be `false`, see https://godbolt.org/z/9zP5oPY1K (but `-fno-finite-math-only` changes that again).

**Comment by marcfehling** [comment]
On my branch I temporarily disabled the `-Werror` flag to catch all warnings caused by the default `icpx` compiler. You can find the log [here](https://github.com/marcfehling/dealii/actions/runs/5182233223/jobs/9338776880).

---

We basically have three types of code snippets that we need to find a workaround for.

1. `icpx` complains about `std::isnan` and our [`numbers::is_nan()`](https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/include/deal.II/base/numbers.h#L529-L533) function:
```
dealii/include/deal.II/base/numbers.h:532:12: warning: explicit comparison with NaN in fast floating point mode [-Wtautological-constant-compare]
     return std::isnan(x);
            ^~~~~~~~~~~~~
```
Maybe we can solve it with something like the following, and replace all occurences of `std::isnan` with `numbers::is_nan`.
```
 inline bool 
 is_nan(const double x) 
 {
#ifdef SOME_INDICATOR_THAT_FINITE_MATH_IS_ON
    return false;
#else 
    return std::isnan(x); 
#endif
 } 
```

2. We check if something is infinity, e.g.
```
dealii/source/fe/mapping_q.cc:583:17: warning: explicit comparison with infinity in fast floating point mode [-Wtautological-constant-compare]
  if (p_unit[0] == std::numeric_limits<double>::infinity())
      ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Since `std::isinf` doesn't seem to please `icpx`, we could try `!std::isfinite` (or `!numbers::is_finite).

Or we could write our own `numbers::is_inf` function with the same trick as above.

3. We check if something is smaller than infinity, e.g.
```
dealii/include/deal.II/lac/utilities.h:435:31: warning: explicit comparison with infinity in fast floating point mode [-Wtautological-constant-compare]
      const bool scale = (a_L < std::numeric_limits<double>::infinity());
                          ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
We can use `std::isfinite` or (`numbers::is_finite`) here.


---

Here is a collection of code references that triggered warnings:

1. `is_nan`
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/include/deal.II/base/numbers.h#L529-L533
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/lac/solver_control.cc#L92
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/include/deal.II/lac/full_matrix.templates.h#L1729
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/lac/lapack_full_matrix.cc#L2464
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/distributed/tria_base.cc#L616

2. `== infinity`
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/fe/mapping_q.cc#L583
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/fe/mapping_q.cc#L649
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/source/particles/particle_handler.cc#L1264

3. `< infinity`
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/include/deal.II/lac/utilities.h#L435

**Comment by marcfehling** [comment]
#15314 gets rid of the `infinity` comparisons.

Now we only have to deal with `isnan`.

**Comment by marcfehling** [comment]
> Maybe we can solve it with something like the following, and replace all occurences of `std::isnan` with `numbers::is_nan`.
> 
> ```
>  inline bool 
>  is_nan(const double x) 
>  {
> #ifdef SOME_INDICATOR_THAT_FINITE_MATH_IS_ON
>     return false;
> #else 
>     return std::isnan(x); 
> #endif
>  } 
> ```

Maybe some check like `#if defined(__FINITE_MATH_ONLY__) && (__FINITE_MATH_ONLY__ == 1)` would silence the warning? I am not sure if all compilers provide this macro.

**Comment by masterleinad** [comment]
In my opinion, it's not our responsibility to deal with those warnings. I find it helpful for users to see that the compiler flags might lead to wrong results in some cases and might need to be adapted by them (rather than us suppressing the warning and returning something wrong).
