### ISSUE TITLE
Deprecate FEEval::get_normal_vector() after the next release

### ISSUE THREAD

**Issue by jh66637** [dealii/dealii#15302]
I am templating over `FEEval` objects, i.e. I am using e.g. `FEPointEval` and `FEFaceEval`. In `FEPointEval` there is the function `normal()` which returns the normal vector, in `FEFaceEval` the same function is named `get_normal()`. There might be similar cases, which can be addressed at the same time. I would like to generalize the interface, but I am not sure how to proceed with this. There are two options I can think of:

1) Simply renaming `normal()` to `get_normal()`
2) Renaming + keeping `normal()` which internally calls `get_normal()` for backward compatibility and adding a `[[deprecated]]` attribute to `normal()` to be able to get rid of it in the future.

Normally I would go for option 2) but since there have been breaking changes in `FEPointEval` recently I think also option 1) would be OK. 

What do you think?
@bergbauer @kronbichler @peterrum 

---------------------------------------------------------------------------
Edit: To be consistent with `FEValues`, `FEPointEval::get_normal()` should be renamed to `FEPointEval::normal()` instead (see the discussion below). Therefore, `FEPointEval::get_normal()` is early deprecated with the next release (deprecation warnings are printed from summer 2024 and the function will pre removed in 2025).

**Comment by kronbichler** [comment]
That's a good point. I would intuitively go for 2, but I think 1 is also possible. Not sure how much that feature is used (apart from the use case of @bergbauer), so I suggest we let @bergbauer decide.

**Comment by bergbauer** [comment]
I have only introduced `normal_vector()` in January so I think simply renaming is fine. Our goal should be to make the `FEPointEvaluation` interfaces as similar as possible to `FEEvaluation`. Thanks for tackling this @jh66637 !

**Comment by jh66637** [comment]
I see the point. However, I think this has to be discussed in detail since it will presumably break a lot of user code. While `FEPEval::normal_vector()` was only introduced recently, `FEEval::get_normal_vector()` and `FEValues::normal_vector()` exist as long as I can think of.

**Comment by kronbichler** [comment]
@bangerth that is a good point. We tried to make the interface of `FEEvaluation` close to `FEValues` where possible, e.g. `quadrature_point(q_index)`, `inverse_jacobian(q_index)` or `JxW(q_index)`. I don't know how this could slip through when we added `FEEvaluationBase::get_normal_vector()` back in 2018. I think it would make sense to add `normal_vector` to both `FEEvaluationData` (where this function is located today) and `FEPointEvaluation`, alongside the `get_normal_vector` function. (And early-deprecate it, or early-early-deprecate it because it will break many codes.)

**Comment by jh66637** [comment]
Just to clarify: this means we should use `normal_vector()` in `FEEval`, correct?
@kronbichler How does an early-deprecate or early-early-deprecate differ? Is it necessary to add this to a list that is updated before a release besides using the `[[deprecated]]` attribute?

**Comment by peterrum** [comment]
https://github.com/dealii/dealii/blob/00e6fe71c9c8cf0ce0ba1cab3bc069022e444889/doc/news/9.2.0-vs-9.3.0.h#L1143-L1156

**Comment by jh66637** [comment]
@peterrum Thank you :)
