### ISSUE TITLE
Add assertion to distribute_local_to_global().

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15332]
#15318 changed code that will let things compile that won't work. We should fix this, as outlined in https://github.com/dealii/dealii/pull/15318#issuecomment-1582955920

This issue is simply to remind us that that should happen before the release.

@jh66637 FYI

**Comment by drwells** [comment]
Fortunately we already have a utility function for checking that an iterator range is contiguous in memory:

https://github.com/dealii/dealii/blob/b617cbcc968964f748d5b04c846227e3de733f8f/include/deal.II/base/array_view.h#L649-L659

**Comment by bangerth** [comment]
Ah yes, great! The hive mind has good memory!
