### ISSUE TITLE
CXX11 thread detection fails on OSX

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1535]
as of 4862b3b
```
-- Performing Test DEAL_II_HAVE_CXX11_THREAD
-- Performing Test DEAL_II_HAVE_CXX11_THREAD - Failed
```

i don't know since when did it start happening, but I had CXX11 and CXX14 enabled at the very end of configure before with `AppleClang 6.1.0.6020053`. 
(i did not upgrade MPI nor XCode).

**Comment by tamiko** [comment]
On Sun, Sep  6, 2015, at 02:45 CDT, Denis Davydov <notifications@github.com> wrote:

> as of 4862b3b
> ```
> -- Performing Test DEAL_II_HAVE_CXX11_THREAD
> -- Performing Test DEAL_II_HAVE_CXX11_THREAD - Failed
> ```

I guess that -Wl,-no-as-needed is not understood, see pull request #1524

**Comment by davydden** [comment]
correct! If I comment `PUSH_CMAKE_REQUIRED("-Wl,-no-as-needed")` it is all good! Can you do some ifs to check if it's Clang?

**Comment by tamiko** [comment]
Yes, I'll fix it.
