### ISSUE TITLE
Get rid of MappingQ1

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1537]
As part of the discussion of #1522 (which is part of addressing #1429, which is itself part of #1198), @kronbichler raised the following question:
...........................
I have a more fundamental question: Now that you spend a significant amount of work at separating MappingQ/MappingQ, why not get rid of the historical 'mistake' of having separate classes and simply make MappingQ1 part of MappingQ (with StaticMappingQ1 that is used in many places defined as Mapping(1))? Does this move us closer to removing MappingQ1? I realize that MappingQ adds new points whereas MappingQ1 simply takes the vertices of the triangulation, but I see that my students struggle with having two separate classes for something that is conceptually the same. And I don't see how performance could be affected if we implement MappingQ well.

I agree with @luca-heltai that the mapping interfaces are way too complicated and we should not need more than
-    MappingCartesian
-    MappingQ
-    MappingFEField If the topology is separated from the geometry, MappingQ could really be a wrapper to MappingFEField based on FESystem(FE_Q,dim), such that all code is in one single place for MappingFEField.

**Comment by bangerth** [comment]
@luca-heltai then replied:
..........................
@bangerth , let's say that I drunk the whole iso-parametric first, and think of iso-geometric just as a fancy name for something that has been around for three decades now...

;)

I fully agree with @kronbichler . With one difference: the default base class Mapping, should be tied much closer to Manifold, as it truly is a local chart of an atlas (the Triangulation as we intend it now) which describes the Manifold...

**Comment by bangerth** [comment]
I think these are excellent points. For the moment, the patches I have written were simply intended to preserve the current status in terms of functionality while making things as outlined above easier to do -- classical maintenance programming.

I think the goal of getting rid of MappingQ1 makes sense. There is currently some code that takes shortcuts when `p=1`, but that might as well be moved to the base class. Removing MappingQ1 was not possible in the past because MappingQ derived from it and, internally, decided for each cell whether it wanted to use its own facilities or simply call the corresponding function for the base class. In other words, MappingQ had (and currently still has) this awkward status where it didn't actually satisfy the is-a relationship with its base class because it was neither a Q1 mapping (it used a Qp mapping for boundary cells) nor a Qp mapping (it used a Q1 mapping in the interior, under some circumstances). This chimera character made everything difficult, and my goal for the moment is to implement in a way so that the MappingQ does not use an is-a relationship via inheritance from MappingQ1, but a has-a relationship via a member variable of type MappingQ1. When we're at this point, I could try to remove MappingQ1 in favor of `MappingQ(1)`. I'll give this a try.

**Comment by bangerth** [comment]
Re @luca-heltai 's point: very interesting with regard to the atlas! I never thought of it that way. Is your suggestion that we equip, for example, `ChartManifold` with functions that can compute Jacobians and higher derivatives of their mappings, and thereby enable completely generic, non-parametric mappings?

**Comment by luca-heltai** [comment]
Yes. I've discussed a little with @tjhei , @kronbichler , @guidokanschat and @tamiko in Heidelberg, and we have some ideas on how to proceed. I think the two of us spoke about this a long time ago... 

The roadmap should be: 

- Make `Manifold` capable of computing **tangential vectors**, i.e., from a differential geometry point of view, a `Manifold` should know about geodesic curves connecting two arbitrary points on the manifold (think of the vertices of a cell) and tangential vectors to these geodesics. 
- At each Point on M, the manifold should be able to return all fundamental forms, **given an arbitrary local basis**. Note that:

  - the local basis, for us, is always a transformation of the euclidean basis on a reference element with dimension equal to the intrinsic dimension of the Manifold
  - the manifold should know how these local basis transform into basis in real space (the information on tangential vectors is enough if we also give meaning to their **length**)

- Make `Mapping` compute its own magic (normals, jacobians, etc.) using such information from the manifold

- The behavior of such a `Mapping`, if we use a `FlatManifold` description and the definitions above, should coincide **exactly** with MappingQ1

- Get rid of MappingQ1, since it is a special case of a special case...

**Comment by bangerth** [comment]
#1725 removes the use of `MappingQ1` from the `source/` directory to the extent possible, and #1726 from the `include/` directory, including the documentation. What is still missing is converting the `examples/` directory.

**Comment by bangerth** [comment]
The previous patches have gotten us to the point where we are almost there with getting rid of MappingQ1. Right now, all I really need to do is replace its use in `tests/` and `examples/`. What I would like to ask is about the name for its replacement. In the current version of the library, we have:

* MappingQGeneric is a class that uses a Qp mapping everywhere
* MappingQ1 is derived from it and sets p=1
* MappingQ is a (misnamed) class that decides on each cell whether to use a Qp or a Q1 mapping. It is derived from MappingQGeneric, but in reality it is neither a Qp nor a Q1 mapping.

The last two names are grandfathered. I am asking whether you like the name MappingQGeneric? Does anyone have a better suggestion for the name of this class?

**Comment by drwells** [comment]
@bangerth My apologies if you have already noticed these and have a patch coming up. 

One holdover of `MappingQ1` is that there are two copies of the exact transforms in `source/fe/mapping_q_generic.cc` : one under `internal::MappingQGeneric` (which is the older set that does not throw exceptions) and another under `internal::MappingQ1`. Is there any reason to keep these?

Another is on line `680`:
```cpp
  if ((polynomial_degree == 1)
      &&
      (dim == spacedim))
    internal::MappingQGeneric::compute_shape_function_values<spacedim> (n_shape_functions,
        unit_points, *this);
  ```

Should this function be in `internal::MappingQ1` instead?

**Comment by bangerth** [comment]
@drwells -- My work on moving functionality down to the base class has been largely mechanical. I suspected that there is now some duplication, but my primary goal was to ensure that the testsuite continues to work as it did previously. I think you actually have some better insight into what all of these functions do. You should feel welcome to remove duplication as you see it.

**Comment by bangerth** [comment]
This issue has strayed a bit in its scope over time, but the origin question was: "Should we get rid of the class `MappingQ1`?"

@luca-heltai -- you felt most strongly about this. The state right now is that `MappingQ1` has no additional functionality over `MappingQGeneric`. It's no longer used in `source/` or `tests/`, but there are still uses in `examples/`. In other words, we could easily remove it if we replaced it in the examples.

I don't feel strongly one way or the other. What do you think about this, @luca-heltai ?

**Comment by bangerth** [comment]
@luca-heltai ?

**Comment by luca-heltai** [comment]
@bangerth, sorry, I completely lost the question you posted 20 days ago... 

I think we should 

- remove `MappingQ1`, 
- rename `MappingQGeneric` to `MappingQ`, 
- move the current `MappingQ` to `MappingQonBoundary` or some other explicit name which is more descriptive of what `MappingQ` currently really does...

This is not backward compatible, but at this point I really think we should do the right thing (tm)...

The next natural step should be to tie much more closely the `Mapping`  and  `Manifold` classes. I have some ideas on what should be done here, but this is a major project, which we could address when you come over here...

**Comment by bangerth** [comment]
OK. This is indeed not backward compatible. I will think about how to do that. Thanks for your feedback.

@tjhei and I were thinking about getting out another release sometime over the winter break. I think so far we don't have a lot of compatibility breakage, so maybe I will leave this until after the release, and we'll roll it into the next release after that for which we are thinking about integrating other incompatible changes as well (such as maybe @Rombur 's vector overhaul).

**Comment by drwells** [comment]
The original goal of this issue was to discuss the removal of `MappingQ1` which is now gone. If we are all okay with the status quo (implementing MappingQ1 in terms of MappingQGeneric) then I believe that this issue should be closed.

**Comment by drwells** [comment]
No one seems to mind so lets close this.
