### ISSUE TITLE
Check for hits in IndexSet::add

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#15398]
In https://github.com/dealii/dealii/pull/15366#issuecomment-1594227405, we remarked that the addition of elements to an `IndexSet` is really slow, and we found much better run times for when we add the indices to a vector, sort it, and then add the vector all at once. We then suspected that there might be a bug hidden in `IndexSet`:

> However, I do not see where in IndexSet we would actually catch the case of an index or range that is already present and hence skip adding it. I guess that might then be a long-standing bug and the reason why we often avoided the IndexSet.

This issue is to remind us that we should look into the code again, and in https://github.com/dealii/dealii/blob/c03ccfab612106a51f8d052c2b69355eac756c21/source/base/index_set.cc#L391-L392 check whether the range or index is already present, and only otherwise insert the new element, to avoid duplicates.

**Comment by bangerth** [comment]
In the best of cases, we can avoid `add_range()` that has the code you show above: We should simply optimize the following function:
```
void
IndexSet::add_ranges_internal(
  boost::container::small_vector<std::pair<size_type, size_type>, 200>
    &        tmp_ranges,
  const bool ranges_are_sorted)
{
  if (!ranges_are_sorted)
    std::sort(tmp_ranges.begin(), tmp_ranges.end());

  // if we have many ranges, we first construct a temporary index set (where
  // we add ranges in a consecutive way, so fast), otherwise, we work with
  // add_range(). the number 9 is chosen heuristically given the fact that
  // there are typically up to 8 independent ranges when adding the degrees of
  // freedom on a 3d cell or 9 when adding degrees of freedom of faces. if
  // doing cell-by-cell additions, we want to avoid repeated calls to
  // IndexSet::compress() which gets called upon merging two index sets, so we
  // want to be in the other branch then.
  if (tmp_ranges.size() > 9)
    {
      IndexSet tmp_set(size());
      tmp_set.ranges.reserve(tmp_ranges.size());
      for (const auto &i : tmp_ranges)
        tmp_set.add_range(i.first, i.second);

      // Case if we have zero or just one range: Add into the other set with
      // its indices, as that is cheaper
      if (this->ranges.size() <= 1)
        {
          if (this->ranges.size() == 1)
            tmp_set.add_range(ranges[0].begin, ranges[0].end);
          std::swap(*this, tmp_set);
        }
      else
        this->add_indices(tmp_set);
    }
  else
    for (const auto &i : tmp_ranges)
      add_range(i.first, i.second);
}
```
The way to do this is to avoid inserting ranges to begin with. We know that both the ranges to be added, and the ones of the current object, are sorted. We should be able to come up with some kind of zip algorithm that merges the two sorted ranges into a single sorted range.

**Comment by kronbichler** [comment]
Let me add this to the developer workshop, I plan to look at the duplicate entry problem. Regarding the zip algorithm, I will look for what we already have and what we ought to do.

**Comment by bangerth** [comment]
It turns out that the function I show above already uses the zip algorithm. It just isn't obvious. It's hidden in the `this->add_indices(tmp_set)` call, which is about as good as I think one can do things.

As for the duplicate entry thing, I had that ready already: #15525.
