### ISSUE TITLE
Can't visualize step-67 output

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15421]
I would love it if someone could see if they can confirm this before the release:

When I run step-67, I end up with .vtu files that I cannot visualize in Visit, both with visit 2.12 and visit 3.3. The program opens the file, but then simply says "The plot did not yield any data" regardless of whether I try to plot the mesh or a pseudocolor representation of any of the solution variables. Do others see this as well?

**Comment by kronbichler** [comment]
I checked the output with ParaView (version 5.11.0) and it looks fine on my machine. This program outputs higher-order information, https://github.com/dealii/dealii/blob/7be92682a504566ef310541c17c52d61344cb5ac/examples/step-67/step-67.cc#L2104-L2106 I'm not sure of Visit supports high-order output - @bangerth could you please check if this is the case by commenting out the last of this line and try again. If that is the case, I would suggest to add this to the in-code comments (and probably the results section), as other users might have the same experience.

**Comment by bangerth** [comment]
Yes, that's it. Thanks for pointing it out!
