### ISSUE TITLE
step-57 stalls

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#15433]
I've been running step-57 for about 15 minutes in release mode and it isn't converging - its stuck trying to do a line search with `alpha = 1`. Here's a picture of the last computed pressure:

![visit0000](https://github.com/dealii/dealii/assets/3917035/017c4ecd-fc7b-4cb3-b17e-57e7dd52675d)

this is definitely not converging to the lid-driven cavity solution.

**Comment by bangerth** [comment]
@tjhei ?

**Comment by bangerth** [comment]
I had a student use it this spring, so the program worked in the last release.

The program does have a bad habit of not converging (without any further error message) when the setup is changed (different boundary conditions, geometry, object sizes, etc.) but at least the default setup should work.

**Comment by tjhei** [comment]
I will take a look.

**Comment by tjhei** [comment]
The commit 3f479583c209077dacd7684f223cc62d3bf991f7 seem to have broken steo-57.

**Comment by bangerth** [comment]
That's #15127.

**Comment by bangerth** [comment]
@drwells ?

**Comment by tjhei** [comment]
Exactly. I am trying to figure out exactly why...
