### ISSUE TITLE
Move GridTools::internal::distributed_compute_intersection_locations out of the internal namespace.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15463]
The release paper has this code snippet:
```
// compute intersections on distributed triangulation  
auto intersection_data =
       GridTools::internal::distributed_compute_intersection_locations(
         cache, intersection_requests, global_bboxes, marked_vertices,
         tolerance);
```

The issue is that we should really not advertise functions that are in the `internal` namespace. Could this function be moved to the `GridTools` namespace instead? Why is it in `internal` to begin with?

@fdrmrc

**Comment by bangerth** [comment]
I would really like to get this function moved before the release, unless there is a particularly good reason why it resides in the `internal` namespace.

**Comment by peterrum** [comment]
We could move this into an `experimental` namespace, as done here:

https://github.com/dealii/dealii/blob/c934630ee36dde61b72d403eee01657e84837792/include/deal.II/distributed/field_transfer.h#L37

I am not comfortable in making this non-experimental/non-internal, since the interfaces might still change depending on some use cases.

Btw.: this feature was contributed by @jh66637.

**Comment by jh66637** [comment]
I agree with @peterrum. @bangerth Is it OK for you to put it into namespace experimental? If so, I will open a PR here and for the release paper.

**Comment by bangerth** [comment]
Ah, sorry for tagging the wrong person. I should have looked up who wrote it.

`experimental` is slightly better. The alternative would be if the release paper only explained the functionality, but didn't show a concrete function name. Would that work? My objection isn't so much where the function is, but that we advertise functions whose final interface (including their location) we don't know . If you think you still want to tinker with it some more, maybe we should just not mention it in the paper. Would that be ok with you too?

**Comment by jh66637** [comment]
I am fine with this. I still would like to mention the function names (without the actual input) so it is easy to find the functions needed to use the feature. I will place a corresponding PR.

**Comment by bangerth** [comment]
Huh, one can close an issue by committing a PR in another repo. That's wild! :-)
