### ISSUE TITLE
Many new failures after Tensor changes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1547]
#1517 introduced many new failures:
  http://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12184

@tamiko -- can you take a look?

**Comment by tamiko** [comment]
"Many", C'mon! :-D

**Comment by tamiko** [comment]
The majority looks harmless. The biggest issue is that the serialization changed with the change of ```Tensor<1,dim,Number>```s internal storage.

**Comment by tamiko** [comment]
@bangerth My favorite [1] - so much for the ```explicit``` keyword :-D

[1] http://cdash.kyomu.43-1.org/testDetails.php?test=21174413&build=12184

**Comment by tamiko** [comment]
With #1549 the only regression left should be ```base/symmetric_tensor_25```.

**Comment by bangerth** [comment]
On 09/07/2015 05:15 PM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth> My favorite [1] - so much for the
> |explicit| keyword :-D
>
> [1] http://cdash.kyomu.43-1.org/testDetails.php?test=21174413&build=12184

Yes, this looks like a bug in the testcase indeed. I can't figure out what the 
'dim' would represent here, other than (judging by the name of the variable) 
being a leftover from the time when the variable used to be a list and the 
argument its length...

**Comment by tjhei** [comment]
We also have a bunch of warnings with Intel [1] now. I played with it a bit but I can not work out how to remove the warnings because they get triggered even if I add a "if (dim==0) return;" before the offending lines.

[1] http://cdash.kyomu.43-1.org/viewBuildError.php?type=1&buildid=12198

**Comment by bangerth** [comment]
In such cases, you probably want to simply add a (partial) specialization of the template. You expect the compiler to elide warnings by looking through control flow, but this only sometimes works. You want to instead avoid the compiler instantiating the function in question for dim==0 to begin with.

**Comment by tamiko** [comment]
@tjhei @bangerth Or we could just disable this warning. Because, in fact, we actually want to do such "pointless comparisons".

**Comment by tamiko** [comment]
On second thought - intel might just do a poor job in not discarding those constructor variants prior to diagnostic emission. I will go with those three specializations - pull request incoming.

**Comment by bangerth** [comment]
Only the one pointed out in #1556 is left now, so I'll close this one.
