### ISSUE TITLE
Tensor = Tensor * scalar + SymmetricTensor does not work

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1556]
something was changed very recently (a day or two) which prevents this from working:
```
error: invalid operands to binary expression ('Tensor<2, 1, typename ProductType<double, typename EnableIfScalar<double>::type>::type>' and 'SymmetricTensor<2, 1, double>')
```

**Comment by davydden** [comment]
i think it could be related to https://github.com/dealii/dealii/pull/1517

**Comment by bangerth** [comment]
@tamiko would probably appreciate a minimal testcase :-)

**Comment by davydden** [comment]
if I am not mistaken this should currently fail:
```
#include <deal.II/base/logstream.h>
#include <deal.II/base/symmetric_tensor.h>

#include <fstream>
#include <iostream>

using namespace dealii;

template<int dim>
void test()
{

  Tensor<2, dim> grad_grad;
  SymmetricTensor<2,dim,double> sym_grad_grad;
      
  grad_grad = grad_grad * 0.1 + sym_grad_grad;
              
  deallog<<"OK"<<std::endl;

}

int main (int argc,char **argv)
{
  std::ofstream logfile("output");
  dealii::deallog.attach(logfile,/*do not print job id*/false);
  dealii::deallog.depth_console(0);
  dealii::deallog.threshold_double(1e-5);
  
  test<2>();
  test<3>();
}
```

**Comment by tamiko** [comment]
> i think it could be related to https://github.com/dealii/dealii/pull/1517

Yes, I know. This is the one open issue I mentioned
(base/symmetric_tensor_25).

**Comment by davydden** [comment]
i guess this is still an issue?

**Comment by bangerth** [comment]
@tamiko : What's the status of this?

**Comment by tamiko** [comment]
> @tamiko : What's the status of this?

"-ENOTIME"

Give me a week, please.

The fix is pretty straightforward, though. We need an explicit
operator+(Tensor, SymmetricTensor) variant (+ switched arguments).

**Comment by bangerth** [comment]
No worries. I just didn't want this to get forgotten given that it shows up in all of our test results.
