### ISSUE TITLE
Small doxygen problem of SolverControl

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1563]
https://www.dealii.org/developer/doxygen/deal.II/classSolverControl.html#aad89c2cee7974455e2c15752c1fa1d93

There is an extra ```DEAL_II_NAMESPACE_OPEN``` before constructor.

**Comment by bangerth** [comment]
Fascinating. I have no idea how this gets there. Someone will have to play around a bit with the ordering of things in this file to see where this comes from.
