### ISSUE TITLE
Invalid cell connection generated between child cells

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15685]
This little code, extracted from something @cedrict and @danieldouglas92 are working on, is clearly not doing things:
```
#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>
#include <fstream>

using namespace dealii;

int main()
{
  Triangulation<2> coarse_grid;
      
  std::vector<Point<2>> vertices = {
        {+0, 1}, {+0, 0}, {1, 0}, {2, 0}, //
        {1, 1}, {2, 1}}; //

  const std::vector<std::array<int, 4>>
    cell_vertices = {
        {{0, 1, 4, 2}},
        {{2, 3, 4, 5}},
  };

  const unsigned int n_cells = cell_vertices.size();

  std::vector<CellData<2>> cells(n_cells);
  for (unsigned int i = 0; i < n_cells; ++i)
    {
      for (unsigned int j = 0; j < cell_vertices[i].size(); ++j)
        cells[i].vertices[j] = cell_vertices[i][j];
      cells[i].material_id = 0;
    }
  coarse_grid.create_triangulation(vertices, cells, {});

  coarse_grid.refine_global(2);

  GridOut go;
  std::ofstream o("coarse_mesh.gnuplot");
  go.write_gnuplot (coarse_grid, o);  
}
```
It yields the following mesh: 
![image](https://github.com/dealii/dealii/assets/7504421/df66502d-d1c3-4629-9bc0-6dc66b3bce6d)

If I reverse the order of the two cells in the `cell_vertices` array, I get the following: 
![image](https://github.com/dealii/dealii/assets/7504421/191d4021-ab28-4302-aa1e-47009fe0464d)

What I imagine happens is that during the first global refinement, we do not correctly connect the child cells to their proper neighbors. During the second refinement, we then end up creating homunculus children. If this hypothesis is correct, it's fascinating that we've never run into this in 20+ years of allowing these kinds of meshes.

**Comment by bangerth** [comment]
It turns out that all that is missing is a call to `GridTools::consistently_order_cells()`. I'm going to see whether I can write a few assertions that lets us catch these sorts of things.

**Comment by bangerth** [comment]
Separately, the code was originally copied from step-14, which did not call `GridTools::consistently_order_cells()`. I'll write a patch to fix this.

**Comment by tamiko** [comment]
@bangerth How much would it hurt to simply call `GridTools::consistently_order_cells()` whenever we are about to create a mesh?

**Comment by bangerth** [comment]
It would lead to different vertex numbers :-( I plan on doing this anyway for #15044 but I think I can generate a decent error message already now.

**Comment by tamiko** [comment]
@bangerth Fair point. Let's add the quality of life feature (automatic reordering for consistency) when we do the reordering anyway :-)
