### ISSUE TITLE
libdeal_II.so links with libX11.so?

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#15693]
In the version 9.5.0 libdeal_II.so now links with libX11.so
Is this expected?
It looks to me that this shouldn't be the case based on deal.II functionality.

```
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/libdeal_II.so.9.5.0 is linked to /usr/local/lib/libX11.so.6 from x11/libX11 but it is not declared as a dependency
Warning: you need USE_XORG+=x11
```

FreeBSD 13.2

**Comment by bangerth** [comment]
I bet this comes in via one or multiple of PETSc, OpenCascade, or gmsh. PETSc has an X11 viewer for matrices.

**Comment by tamiko** [comment]
@bangerth is correct. Unfortunately, some of our dependencies pull in `libX11.so` through their link interface.

@yurivict There is really not much we can do on our side here - you will need to correctly annotate this transitive dependency in FreeBSD's ports system. My bet is that one of the dependencies does not annotate a dependency on xorg/x11 and the warning shows up for the deal.II package.

**Comment by tamiko** [comment]
@yurivict The `detailed.log` might tell you what pulled in `libX11.so`.

**Comment by yurivict** [comment]
I found from the ```detailed.log``` file that both petsc and slepc introduce this dependency.


Thank you.
