### ISSUE TITLE
Fixing the display problems of member functions of some classes in documentation

### ISSUE THREAD

**Issue by RichardYCJ** [dealii/dealii#15691]
There are some problems in displaying member functions of some classes in our doc, say `Triangulation`, `DofHandler` and `MatrixFree`.

After digging into the header files, I found some **missing bracket pairs** and **incorrect use of doxygen-style brackets** (should be `/** @} */`).

```bash
find ../include/ -type f | xargs grep -Pzo -n '/\*\n +\* @\}\n +\*/\n'
../include/deal.II/grid/tria.h:1:/*
   * @}
   */
# SOME MORE OUTPUT ...
../include/deal.II/dofs/dof_handler.h:1:/*
   * @}
   */
```

Furthermore, the `Triangulation` class contains **8 overloads** of `n_quads` (and some other functions) including the specializations which are not supposed to be parsed by doxygen (the header file uses the `#ifndef DOXYGEN` macro).

I solve this by **deleting the source path** in the `INPUT` field of the generated `options.dox`. But this also eliminate the `source` directory in the [**File List tab**](https://www.dealii.org/current/doxygen/deal.II/files.html).

https://github.com/dealii/dealii/blob/01b805b00b621143e6ca89ff13dfde00807e0e31/doc/doxygen/CMakeLists.txt#L189-L196

I'm wondering if adding the source path into the doxygen input is necessary since functions only defined in the source file should not show up in the doc like [`DataOutBase::get_node_positions`](https://www.dealii.org/current/doxygen/deal.II/namespaceDataOutBase.html#ac50a84c928a2d6bb906815f2ffe255d7).

**Comment by RichardYCJ** [comment]
Besides, pages like class [`MatrixFree`](https://www.dealii.org/current/doxygen/deal.II/classMatrixFree.html#:~:text=4%3A%20General%20information) have incorrect subtitle level. This is because the name group contains **two or more different types of members** according to the [doxygen doc](https://www.doxygen.nl/manual/grouping.html#memgroup:~:text=is%20not%20allowed.-,If,-all%20members%20of) (say `static MatrixFree::is_supported()` in this case).

Should we simply remove the title number and leave it or just move `is_supported` out? 

I personally dislike the `\nosubgrouping` command since this would mix the private and public members

**Comment by bangerth** [comment]
Many good points, but no easy answers :-( We let doxygen munch the source files because it then shows the location of the implementation for each function; that's at least marginally useful, but I also wouldn't be opposed to removing this feature.

As for mismatched group tags, if you have an automated way to detect where they are, we'd love to take patches to fix those!

**Comment by RichardYCJ** [comment]
> As for mismatched group tags, if you have an automated way to detect where they are, we'd love to take patches to fix those!

Unfortunately I have no automatic way to detect this.😢 A coarse method is to print all brackets and check them by eyes `find ../include/ -type f | xargs grep -C1 -n --color=auto '@}'` and luckily there aren't many.

As to the incorrect subtitle level, the work around that makes minimal changes is to remove the subtitle numbers, since most of these groups are a mixture of public member and public static member, I think that would not cause too much trouble.
