### ISSUE TITLE
Performance regression: timing-navier_stokes/setup_matrix_free

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#15741]
This is a bit of an odd one and we might have just gotten unlucky with minor changes in code layout resulting in a statistically significant performance regression.

More precisely, the `setup_matrix_free` variant shows a regression for clang-16:
  https://dealii.org/performance_tests//reports/render.html?#!0c4cd39c04f09a8c2ee8b17c3b8cb8ac61b59e04.md#clang-16/timing-navier_stokes

It does not trigger for gcc-10 yet because the noise floor is mor pronounced so that the comparison stays barely within acceptable limits:

measurement | A1000 ±σ (r𝛘²) | A100 ±σ (r𝛘²) | A20 ±σ (r𝛘²) | A4 ±σ (r𝛘²) | Stability | Status
-- | -- | -- | -- | -- | -- | --
gcc-10 | 0.850 ± 0.00451 (8.000) | 0.759 ± 0.00310 (0.497) | 0.751 ± 0.00800 (0.442) | 0.765 ± 0.01799 (0.472) | u.f. | OK
clang-16 | 0.778 ± 0.00470 (26.901) | 0.688 ± 0.00147 (0.361) | 0.702 ± 0.00238 (0.151) | 0.710 ± 0.00478 (0.153) | u.f. | REG

What is odd is the "slope" I am seeing in the "minimum of last 1000 merge commits":
  ![](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/timing-navier_stokes.png)
  ![](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/timing-navier_stokes.png)
(Warning the two images above are regenerated with each merge commit and will evolve over time. The report, however, is for 0c4cd39c04f09a8c2ee8b17c3b8cb8ac61b59e04 and will not change)

@kronbichler *ping*

**Comment by tamiko** [comment]
Merges around regression:
- '-43' #15672 
- '-44' #15010 
- '-45' #15675 
- '-46' #15666 <------
- '-47' #15665 
- '-48' #15668 
- '-49' #15674

**Comment by bangerth** [comment]
I assume you are looking at the small step from about 0.65 to 0.68 in the black curve? There's enough noise that I don't think your patch identification is accurate. Do you have the corresponding picture that looks at the number of instructions obtained from valgrind?

**Comment by tamiko** [comment]
@bangerth I actually looked this up here on the "A100" plot. For example from the most recent one here [1] at position -47, where 0 corresponds to the commit mentioned in the title. This commit -47 is cb786b5e7996e4e0dfa7764cfbbdd4af8d4c9ecf. Because this is incredibly noisy I actually plotted the data in question [2] by hand and concluded that the same range is affected.

No, I do not have any instrumentation set up with valgrind. In fact, I have removed the two instrumentation tests from the performance testsuite that I am running: mainly because: (a) valgrind is incompatible with compiling the code with avx2, avx512 instructions, (b) instruction counts differ wildly for essentially the same performance (timing). I think that Intel performance counters are much faster and significantly more reliable for the matter.

But now, what does this mean with respect to the commits I mentioned above?

In my opinion and looking at the history of the measurement timings none of the commits in this range are at fault. (I posted it as a reminder what commits I should compare if we decide to do some proper instrumentation to identify some potential issue.) Now a wild guess on my side would be that some hot path in the matrix free setup is very sensitive to cache misses, or might be at the boundary of the cache line size.

For context: I have opened this issue because (a) this is about the only measurement with a recent "performance regression" (admittedly with a very sensitive trigger), (b) I know that @kronbichler cares a lot about performance in the matrix free part of the library, (c) I want to have input whether I should treat this case as a regression or not. I will then adjust the trigger accordingly.

**Comment by tamiko** [comment]
I think I made up my mind on this matter.

 I have added a sigma_sys groundfloor to the triggers and will base the decision whether we have regression on either a 4+ sigma deviation of a single configurations, or a consensus 3+ sigma deviation of both configurations. (Note that sigma has a slightly different meaning in this context, it is an estimate for the "asymptotic standard error" of a fit parameter and as such significantly smaller than the typical statistical standard deviation of a measurement.)
