### ISSUE TITLE
Performance regression: various grid and particle operations with p4est-2.8 versus p4est-2.3

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#15742]
This is a bit startling. I am running performance tests on two different userlands
 - host system with Debian bullseye and gcc-10 system compiler
 - container with a Gentoo userland compiled with `-march=native -O2` with clang-16 and basically most recent dependencies.

Most of our performance measurements lead to very comparable timings. Sometimes clang is considerably faster, sometimes it is 5% slower, give or take.

But there is one exception: everything that has to do with grid generation/setup is significantly slower with my "gentoo clang-16" userland. In particular:

 - `step-3/output_results`: [bullseye gcc-10](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/timing-step-3.png) vs [gentoo clang-16](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/timing-step-3.png), 10% slower
 - `step-37/grid`: [bullseye gcc-10](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-step_37.average.png) vs [gentoo clang-16](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-step_37.average.png), 700% slower
 - `mg_glob_coarsen/setup_grid` [bullseye gcc-10](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-mg_glob_coarsen.average.png) vs [gentoo clang-16](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-mg_glob_coarsen.average.png)
 - `navier_stokes/setup_grid` [bullseye gcc-10](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-navier_stokes.average.png) vs [gentoo clang-16](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-navier_stokes.average.png)
 - `step-68/generate_particles` [bullseye gcc-10](https://dealii.org/performance_tests/graphs//whistler-bullseye-gcc-10/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-step_68.average.png) vs [gentoo clang-16](https://dealii.org/performance_tests/graphs//whistler-gentoo-clang-16/231bf04ccc9a8e2948c5c0972af3f78a3543bd0f-timing-step_68.average.png), 600% slower

This might very well be an external dependency that shows significant performance differences. Does anyone have a good guess?

@kronbichler *ping*

**Comment by blaisb** [comment]
@tamiko In step-68 the particles are generated using a grid. So it is also a use of grid/setup-grid... Seems like that's the direction we should look into.

**Comment by kronbichler** [comment]
The `grid` functions of your gentoo clang-16 system are unusually slow, so I would expect primarily a third-party library. The grid creation does some special communication, so a different MPI library could also be a cause.

**Comment by tamiko** [comment]
@blaisb @kronbichler *mhm* comparing performance of gcc-13 versus clang-16 on my laptop I definitely don't see such a regression in the grid routines.

**Comment by tamiko** [comment]
*HOLY SMOKES*

`p4est-2.8.5`

```
tamiko@peregrine dealii/build-clang % cat tests/performance/timing_step_37.release/mpirun=8/threads=1/output | column -t
timing
name                  min        max        mean       std_dev     samples
setup_grid            12.7531    13.6763    13.3272    0.427717    4
setup_dofs            2.9924     3.18769    3.04653    0.0944205   4
setup_matrix_free     2.14975    2.19313    2.16486    0.0197905   4
assemble_rhs          0.0814235  0.0879942  0.0851097  0.00276091  4
setup_transfer        1.07764    1.10877    1.09169    0.0149747   4
setup_smoother        2.12918    2.31216    2.19818    0.0798112   4
solve                 14.0887    14.3523    14.1908    0.113541    4
matvec_double         5.24734    5.33851    5.30072    0.0387602   4
matvec_float          2.9012     2.99812    2.95018    0.0498404   4
matvec_float_coarser  0.381412   0.390132   0.384615   0.00380989  4

tamiko@peregrine dealii/build-gcc % cat tests/performance/timing_step_37.release/mpirun=8/threads=1/output | column -t
timing
name                  min        max        mean       std_dev     samples
setup_grid            13.2606    13.9571    13.6638    0.298721    4
setup_dofs            2.99354    3.04845    3.02463    0.0241298   4
setup_matrix_free     2.15753    2.18712    2.17533    0.0128973   4
assemble_rhs          0.0792937  0.0838796  0.0816007  0.00193016  4
setup_transfer        1.08746    1.0984     1.09281    0.00606938  4
setup_smoother        3.07234    3.15993    3.12896    0.0387034   4
solve                 14.5055    14.5827    14.5431    0.0342055   4
matvec_double         6.16524    6.23172    6.19914    0.029226    4
matvec_float          3.35873    3.43527    3.39276    0.0341397   4
matvec_float_coarser  0.44319    0.449816   0.447822   0.00311488  4
```

`p4est-2.3.3`
```
% cat tests/performance/timing_step_37.release/mpirun=8/threads=1/output | column -t
timing
name                  min        max        mean       std_dev     samples
setup_grid            1.39987    1.41624    1.40541    0.00745234  4
setup_dofs            2.97545    3.06268    3.0227     0.037366    4
setup_matrix_free     2.15865    2.2251     2.18008    0.0309156   4
assemble_rhs          0.0831045  0.0859065  0.0846741  0.00132597  4
setup_transfer        1.07943    1.11955    1.09594    0.0181854   4
setup_smoother        2.11511    2.30173    2.21928    0.083884    4
solve                 14.1543    14.2678    14.207     0.0544955   4
matvec_double         5.3473     5.48306    5.40156    0.0581128   4
matvec_float          2.92912    2.97982    2.94915    0.0234954   4
matvec_float_coarser  0.378448   0.403745   0.38544    0.0122255   4

% cat tests/performance/timing_step_37.release/mpirun=8/threads=1/output | column -t
timing
name                  min        max        mean       std_dev     samples
setup_grid            1.38541    1.43338    1.40829    0.0235613   4
setup_dofs            2.99058    3.03815    3.01701    0.0240761   4
setup_matrix_free     2.17864    2.24111    2.19993    0.0291614   4
assemble_rhs          0.0781197  0.0842339  0.0810891  0.00301202  4
setup_transfer        1.08661    1.09047    1.08861    0.0017927   4
setup_smoother        2.88402    3.07868    2.99655    0.0845785   4
solve                 14.6204    14.9328    14.8038    0.131378    4
matvec_double         6.19909    6.47593    6.32095    0.125681    4
matvec_float          3.41285    3.46159    3.43355    0.0204454   4
matvec_float_coarser  0.443751   0.453888   0.448662   0.00416623  4
```

**Comment by tamiko** [comment]
Alright. Reported upstream and I have to bite the bullet and rerun the entire clang-16 performance measurements.
