### ISSUE TITLE
CMake error when configuring with `P4EST`

### ISSUE THREAD

**Issue by davidscn** [dealii/dealii#15759]
While trying to update my deal.II version to the latest release (9.5.1), cmake reported the following error:

```bash
CMake Error in CMakeLists.txt:
  Target "interface_p4est" INTERFACE_INCLUDE_DIRECTORIES property contains
  path:

    "~/dealii/doc/external-libs/p4est-install/FAST/include"

  which is prefixed in the source directory.
```

I'm using CMake version 3.22.1 and the latest p4est release (`p4est-2.8.5.5-9ddbb`). To build p4est, I used the setup script provided in the repository ([`doc/external-libs/p4est-setup.sh`](https://github.com/dealii/dealii/blob/master/doc/external-libs/p4est-setup.sh)) and tell CMake about the installation via

```
cmake   -D DEAL_II_WITH_P4EST="ON"  \
        -D P4EST_DIR="$HOME/doc/external-libs/p4est-install"  \
        <more-options> ..
```

This worked out pretty well until the latest release and I'm a bit puzzled on how to fix it without looking into CMake details. Of course, I can provide more CMake logging details, if necessary.

**Comment by marcfehling** [comment]
You have installed `p4est` in the source directory of `dealii`, and tried to configure `dealii` with it. CMake complains about that
```
... which is prefixed in the source directory
```
After the rework of our CMake configuration with the latest release, this is no longer allowed. I believe if you install `p4est` in a separate folder unrelated to `dealii`, this should no longer be a problem.

**Comment by davidscn** [comment]
Ah ok. Installing it in a different directory works, thanks a lot. The missing piece of information (from CMake) was that the in-source installation is not allowed.

Having said that, it might a good idea to make the install location in the setup script mandatory `p4est-setup.sh <p4est_tar.gz_file> [<install location>]`, as the default usage might lead to an invalid p4est installation. Will close here as the issue is on the user side.
