### ISSUE TITLE
issue in building deal.ll

### ISSUE THREAD

**Issue by garadeaniket** [dealii/dealii#15763]
I an facing issue while building deal.ll. After the make install command the below error has been occured.
Please help to rectify the issue .

[  5%] Built target bundled_boost_serialization_release
make: *** [Makefile:149: all] Error 2

**Comment by blaisb** [comment]
Dear @garadeaniket , can you post the entire error message? With the current line you have given it is impossible to assess what went wrong.

**Comment by garadeaniket** [comment]
ld.lld: error: undefined symbol: std::__throw_bad_array_new_length()
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate(unsigned long, void const*))
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_List_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::allocate(unsigned long, void const*))
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::allocate(unsigned long, void const*))
collect2: error: ld returned 1 exit status
make[2]: *** [cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/build.make:103: bin/expand_instantiations] Error 1
make[1]: *** [CMakeFiles/Makefile2:1989: cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:149: all] Error 2

This is the complete error message i got during installation

**Comment by blaisb** [comment]
Which compiler are you using and does it support CXX17?
Are you using the system boost or are you using the one bundled by deal.II?

**Comment by masterleinad** [comment]
Please also post your `detailed.log`.

**Comment by tamiko** [comment]
Probably related to https://gcc.gnu.org/pipermail/gcc-help/2021-June/140487.html

@garadeaniket In order to help further we would need the full `detailed.log` and would also need to know on what distribution you're trying to compile. (Ubuntu 22.04?)

**Comment by garadeaniket** [comment]
> Which compiler are you using and does it support CXX17? Are you using the system boost or are you using the one bundled by deal.II?

we are using gcc 12.2.0 and we are using boost 1.70.0 found in bundled .

**Comment by garadeaniket** [comment]
> Probably related to https://gcc.gnu.org/pipermail/gcc-help/2021-June/140487.html
> 
> @garadeaniket In order to help further we would need the full `detailed.log` and would also need to know on what distribution you're trying to compile. (Ubuntu 22.04?)

[
[detailed log.txt](https://github.com/dealii/dealii/files/12116524/detailed.log.txt)

**Comment by garadeaniket** [comment]
> Please also post your `detailed.log`.

[detailed log.txt](https://github.com/dealii/dealii/files/12116534/detailed.log.txt)

**Comment by pcafrica** [comment]
Hi @garadeaniket!

Could you please provide us with the output of `compgen -abck g++`?

I suspect that you may have multiple versions of GCC installed, and for some reason, the compiler may not match the linker version. However, I might be wrong :)

**Comment by garadeaniket** [comment]
> Hi @garadeaniket!
> 
> Could you please provide us with the output of `compgen -abck g++`?
> 
> I suspect that you may have multiple versions of GCC installed, and for some reason, the compiler may not match the linker version. However, I might be wrong :)

 ld -v
GNU ld (GNU Binutils) 2.34
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/user/gccv12.2_inst_dir/libexec/gcc/aarch64-unknown-linux-gnu/12.2.0/lto-wrapper
Target: aarch64-unknown-linux-gnu
Configured with: ./configure --prefix=/home/user/gccv12.2_inst_dir/ CC=gcc CXX=g++ FC=gfortran --with-gmp=/home/user/gmpv6.2.1_inst_dir/ --with-mpfr=/home/user/mpfrv4.1.0_inst_dir/ --with-mpc=/home/user/mpcv1.2.1_inst_dir/
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (GCC)

**Comment by garadeaniket** [comment]
I tried building with gcc 9.2.0 and got the below mentioned error. Please help to rectify

 In file included from /home/usr/dealii/bundled/tbb-2018_U2/src/tbb/tools_api/ittnotify_static.c:21,
                  from /home/usr/dealii/bundled/tbb-2018_U2/src/tbb/itt_notify.cpp:47:
 /home/usr/dealii/bundled/tbb-2018_U2/src/tbb/tools_api/ittnotify_config.h: In function <91>long int __itt_interlocked_increment(volatil    e long int*)<92>:
 /home/usr/dealii/bundled/tbb-2018_U2/src/tbb/tools_api/ittnotify_config.h:329:12: error: <91>__TBB_machine_fetchadd4<92> was not declar    ed in this scope
   329 |     return __TBB_machine_fetchadd4(ptr, 1) + 1L;
 
 make[2]: *** [bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/build.make:225: bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_d    ebug.dir/tbb/itt_notify.cpp.o] Error 1
 make[1]: *** [CMakeFiles/Makefile2:2428: bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/all] Error 2

**Comment by bangerth** [comment]
@garadeaniket Did you ever figure out how to address your build issues?
