### ISSUE TITLE
Unify interface of p::d::SolutionTransfer and SolutionTransfer

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#15760]
In particular, the serial version accepts `std::vector<VectorType>`, while the p::d version accepts only `std::vector<VectorType *>`.

**Comment by marcfehling** [comment]
Part of #15280 :)

**Comment by pcafrica** [comment]
Also related: #15703, #15706.

**Comment by pcafrica** [comment]
I guess this issue can be safely closed as #15706 got merged!
