### ISSUE TITLE
Failed test with p4est

### ISSUE THREAD

**Issue by IntrepidNomad** [dealii/dealii#15786]
I was building dealii with p4est support when this test failed. Disabling the inclusion of p4est led to successful build. Does anyone with more experience have an idea of what the source of the test failure could be? For reference, I am compiling out of the AUR using standard libraries from the arch repository. All other tests were successful. Output from the failed test is below.

```
Start testing: Jul 24 02:39 CDT
----------------------------------------------------------
21/44 Testing: test_dependency/quick_tests.p4est.debug.executable
21/44 Test: test_dependency/quick_tests.p4est.debug.executable
Command: "/usr/bin/cmake" "-DTRGT=test_dependency.quick_tests.p4est.debug.executable" "-DTEST=test_dependency/quick_tests.p4est.debug.executable" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/***/AUR/deal-ii/src/build/tests/quick_tests" "-P" "/home/***/AUR/deal-ii/src/build/share/deal-ii//scripts/run_test.cmake"
Directory: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/mpirun=10
"test_dependency/quick_tests.p4est.debug.executable" start time: Jul 24 02:39 CDT
Output:
----------------------------------------------------------
Test test_dependency/quick_tests.p4est.debug.executable: PASSED
===============================   OUTPUT BEGIN  ===============================
test_dependency/quick_tests.p4est.debug.executable: PASSED.
===============================    OUTPUT END   ===============================
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Passed.
"test_dependency/quick_tests.p4est.debug.executable" end time: Jul 24 02:39 CDT
"test_dependency/quick_tests.p4est.debug.executable" time elapsed: 00:00:00
----------------------------------------------------------

22/44 Testing: quick_tests/p4est.mpirun=10.debug
22/44 Test: quick_tests/p4est.mpirun=10.debug
Command: "/usr/bin/cmake" "-DTRGT=quick_tests.p4est.mpirun10.debug.test" "-DTEST=quick_tests/p4est.mpirun=10.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/***/AUR/deal-ii/src/build/tests/quick_tests" "-P" "/home/***/AUR/deal-ii/src/build/share/deal-ii//scripts/run_test.cmake"
Directory: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/mpirun=10
"quick_tests/p4est.mpirun=10.debug" start time: Jul 24 02:39 CDT
Output:
----------------------------------------------------------
make[3]: *** [CMakeFiles/quick_tests.p4est.mpirun10.debug.test.dir/build.make:78: p4est.debug/mpirun=10/output] Error 1
make[2]: *** [CMakeFiles/Makefile2:1295: CMakeFiles/quick_tests.p4est.mpirun10.debug.test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1302: CMakeFiles/quick_tests.p4est.mpirun10.debug.test.dir/rule] Error 2
make: *** [Makefile:680: quick_tests.p4est.mpirun10.debug.test] Error 2
Test quick_tests/p4est.mpirun=10.debug: RUN
===============================   OUTPUT BEGIN  ===============================
[ 66%] Built target quick_tests.p4est.debug
[100%] Generating p4est.debug/mpirun=10/output
quick_tests/p4est.mpirun=10.debug: BUILD successful.
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Return code 127
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Result: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/mpirun=10/failing_output
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Partial output:
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4044,1],6]
  Exit code:    127
--------------------------------------------------------------------------


quick_tests/p4est.mpirun=10.debug: ******    RUN failed    *******

===============================    OUTPUT END   ===============================
Expected stage PASSED - aborting
CMake Error at /home/***/AUR/deal-ii/src/build/share/deal-ii/scripts/run_test.cmake:116 (message):
  *** abort


<end of output>
Test time =   7.67 sec
----------------------------------------------------------
Test Failed.
"quick_tests/p4est.mpirun=10.debug" end time: Jul 24 02:40 CDT
"quick_tests/p4est.mpirun=10.debug" time elapsed: 00:00:07
----------------------------------------------------------

End testing: Jul 24 02:40 CDT
```

**Comment by marcfehling** [comment]
How did you install `p4est`? Did you use the [`p4est-deal-ii`](https://aur.archlinux.org/packages/p4est-deal-ii) package?

**Comment by IntrepidNomad** [comment]
> How did you install `p4est`? Did you use the [`p4est-deal-ii`](https://aur.archlinux.org/packages/p4est-deal-ii) package?

Yes, I used the p4est-deal-ii package from the AUR.

**Comment by marcfehling** [comment]
It looks like the quick tests compile, but when running them they can't find the `MeshSmoothing` enum of the Triangulation class. That's odd.

```
quick_tests/p4est.mpirun=10.debug: BUILD successful.
[...]
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
```

**Comment by IntrepidNomad** [comment]
> It looks like the quick tests compile, but when running them they can't find the `MeshSmoothing` enum of the Triangulation class. That's odd, especially since the other quick tests work if you remove p4est.
> 
> ```
> quick_tests/p4est.mpirun=10.debug: BUILD successful.
> [...]
> /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
> /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
> /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
> ```
The PKGBUILD from the AUR adds these options to the configuration:

`disabled_packages=" --without-petsc --without-metis --without-blas"
    disabled_packages+=" --without-lint"
    options=" --enable-mpi --enable-shared --disable-vtk-binary"
    options+=" --disable-mpithread --with-gnu-ld --enable-static=no"
    cpp_flags=" -DSC_LOG_PRIORITY=SC_LP_ESSENTIAL"
` 
I believe a few of those options diverge from what is specified in [https://dealii.org/developer/external-libs/p4est-setup.sh](url)

Could this be a source of the issue?

**Comment by drwells** [comment]
No, I don't think those flags are part of the problem: the issue has to be with deal.II since part of the configuration thinks p4est is available (so that constructor is declared) and part thinks it is not (so it is not defined). Things work on the machine I wrote both `PKGBUILD`s on so I will need some help to debug this.

Can you post `detailed.log` here and also run `ldd /opt/p4est-deal-ii/DBUG/lib/libp4est.so`?

**Comment by IntrepidNomad** [comment]
Here is the output of ldd libp4est.so 

`linux-vdso.so.1 (0x00007ffc119b3000)
	libsc.so.2 => /opt/p4est-deal-ii//DEBUG/lib/libsc.so.2 (0x00007f9e5edae000)
	libjansson.so.4 => /usr/lib/libjansson.so.4 (0x00007f9e5ed9e000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f9e5ed84000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f9e5ec97000)
	libmpi.so.40 => /usr/lib/libmpi.so.40 (0x00007f9e5eb6c000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9e5e982000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f9e5ef05000)
	libopen-rte.so.40 => /usr/lib/libopen-rte.so.40 (0x00007f9e5e882000)
	libopen-pal.so.40 => /usr/lib/libopen-pal.so.40 (0x00007f9e5e7d6000)
	libhwloc.so.15 => /usr/lib/libhwloc.so.15 (0x00007f9e5e779000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9e5e754000)
	libevent_core-2.1.so.7 => /usr/lib/libevent_core-2.1.so.7 (0x00007f9e5e722000)
	libevent_pthreads-2.1.so.7 => /usr/lib/libevent_pthreads-2.1.so.7 (0x00007f9e5e71b000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f9e5e6e7000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f9e5e6db000)
`

**Comment by IntrepidNomad** [comment]
And the detailed log.
[detailed.log](https://github.com/dealii/dealii/files/12174685/detailed.log)

**Comment by drwells** [comment]
Thanks. I don't see anything off in either setup - you're definitely using openmpi and p4est but those symbols are missing.

My next best guess is that you ran out of memory when compiling. Can you recompile the library to confirm with fewer processors and double-check that you have enough free disk space?

**Comment by IntrepidNomad** [comment]
I deleted the build directory for p4est and dea-ii and rebuilt both. I got the same error unfortunately. `[0mTest quick_tests/p4est.mpirun=10.debug: RUN[0m
[0m===============================   OUTPUT BEGIN  ===============================[0m
[0m[ 66%] Built target quick_tests.p4est.debug
[100%] [34m[1mGenerating p4est.debug/mpirun=10/output[0m
quick_tests/p4est.mpirun=10.debug: BUILD successful.
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Return code 127
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Result: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/mpirun=10/failing_output
quick_tests/p4est.mpirun=10.debug: RUN failed. ------ Partial output:
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
/home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: symbol lookup error: /home/***/AUR/deal-ii/src/build/tests/quick_tests/p4est.debug/p4est.debug: undefined symbol: _ZN6dealii8parallel11distributed13TriangulationILi2ELi2EEC1EP19ompi_communicator_tNS_13TriangulationILi2ELi2EE13MeshSmoothingENS3_8SettingsE
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60316,1],3]
  Exit code:    127
--------------------------------------------------------------------------
[0m
[0m[0m
[0mquick_tests/p4est.mpirun=10.debug: ******    RUN failed    *******[0m
[0m[0m
[0m===============================    OUTPUT END   ===============================[0m
[0mExpected stage PASSED - aborting[0m
[31mCMake Error at /home/***/AUR/deal-ii/src/build/share/deal-ii/scripts/run_test.cmake:116 (message):
  *** abort
`

**Comment by carlosal1015** [comment]
I can confirm the issue, _but in setup stage_, [appending in the line 101](https://raw.githubusercontent.com/cpp-review-dune/introductory-review/main/src/Docker/0001-Enable-python-bindings.patch)

```bash
cmake_configuration_flags+=" -DDEAL_II_WITH_UMFPACK=ON -DDEAL_II_COMPONENT_EXAMPLES=ON -DDEAL_II_COMPONENT_PYTHON_BINDINGS=ON -DDEAL_II_WITH_PETSC=OFF -DDEAL_II_WITH_P4EST=ON"
```

```
Error: leb128 operand is an undefined symbol: .LFE
c++: fatal error: Killed signal terminated program cc1plus
```

- [makepkg compilation log](https://gist.githubusercontent.com/carlosal1015/bbc040b2467b60ec7abaa8c438ca22f9/raw/7f035ba19dc77910093593fdea5512348b38cb7b/deal-ii-9.5.1.txt)

I will do further investigations.

**Comment by IntrepidNomad** [comment]
[config.h.txt](https://github.com/dealii/dealii/files/12226383/config.h.txt)

Here it is.

**Comment by drwells** [comment]
Thanks.

Both of my personal Arch Linux machines can compile deal.II with p4est (via AUR scripts) - I'll set up a completely clean test environment to see if I can reproduce this. @IntrepidNomad did you also use `yay` or some other AUR wrapper?

**Comment by IntrepidNomad** [comment]
No, I haven't used an AUR wrapper, just makepkg.

**Comment by carlosal1015** [comment]
From my side, [in the second attempt without changes there is no issues](https://gist.githubusercontent.com/carlosal1015/bbc040b2467b60ec7abaa8c438ca22f9/raw/6467e376af6256b7f29435409caddf3d90f1d4c9/deal-ii-9.5.1-second-attempt.txt). Great 😄 .

**Comment by drwells** [comment]
I rebuilt everything in a docker container and it works - I'm at a loss to explain the p4est problem.

**Comment by IntrepidNomad** [comment]
I performed a system update and redownloaded and rebuilt all dependencies, after which deal-ii compiled successfuly.
