### ISSUE TITLE
setup_tests takes too long

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1581]
Calling `make setup_tests` is simply too slow to do regularly, so I use `ninja` instead, but even that is slow. Do we have any idea what makes it so slow? Could the work be split up into more sub-targets that could run in parallel (there are currently 32 steps to be done for `ninja setup_tests`, whereas I could accommodate twice as many)?

This all wouldn't matter that much if one had to call it only infrequently. But, I have found that in many situations (the criteria are not clear to me) if I don't call `setup_tests` but proceed straight from `ninja` to `ctest -j60`, then my system will spend an incredible amount of time running `cmake` instances. It certainly looks to me like it's going to call `cmake` on every test. This adds 20-30 seconds per test, making running the entire testsuite much slower than necessary. In other words, the problem could also be addressed by making sure that `ctest` does not internally run `cmake`.

**Comment by tamiko** [comment]
You call it with ```make -jN setup_tests```, don't you? setup_tests calls cmake for every test subproject, this is for every category.

What you hit is a bug in ninja that is simply not capable of being called reentrantly. I.e., if it messes up its log file, it thinks that it needs to reconfigure for every test.

**Comment by tamiko** [comment]
If you want to split up the categories further, please do so. Just relocate tests into a new subdirectory, e.g,

base1, base2, etc.

**Comment by bangerth** [comment]
Yes, `ninja` automatically parallelizes, so saying `ninja setup_tests` is the same as `ninja -jN setup_tests` for some `N` that is appropriately chosen (in ways I don't know).

As for splitting -- I may try this. There was a file that stored how long `ninja` took to execute a particular target. Do you recall how that file was called for the timing of the 32 targets that are part of `ninja setup_tests`? This might help me figure out which subdirectory needs to be split (likely `bits/`).

**Comment by Rombur** [comment]
@bangerth no @tamiko said ```make -jN setup_tests``` make is a lot faster than ninja to setup the tests

**Comment by bangerth** [comment]
Reply to myself: `.ninja_log`.

**Comment by bangerth** [comment]
`make -jN` may be faster, but running the testsuite is a lot slower later on. So I think using `ninja` is still a win.

**Comment by bangerth** [comment]
Here's the breakdown between directories (run time is the difference between first and second column, in milliseconds):
```
9       348     0       tests/CMakeFiles/setup_tests_opencascade        99d8c003b0f9ba7a
12      456     0       tests/CMakeFiles/setup_tests_arpack     e9109abd9ab2c683
17      579     0       tests/CMakeFiles/setup_tests_metis      6cd5acfb2c2f92b6
2       599     0       tests/CMakeFiles/setup_tests_slepc      4712e7e73911d85c
18      691     0       tests/CMakeFiles/setup_tests_sharedtria ee1d440d8529c0b4
15      1333    0       tests/CMakeFiles/setup_tests_vector_tools       281b7e3a0d3175c9
4       1683    0       tests/CMakeFiles/setup_tests_algorithms a880f67b2cdc1516
18      1847    0       tests/CMakeFiles/setup_tests_a-framework        b8e294e623b2daab
20      2823    0       tests/CMakeFiles/setup_tests_aniso      924e3d6fdcdfd7c2
22      3187    0       tests/CMakeFiles/setup_tests_umfpack    bbaba47d069622d5
21      4037    0       tests/CMakeFiles/setup_tests_lapack     6feca7270260fe5a
6       5785    0       tests/CMakeFiles/setup_tests_build_tests        d0b1887e97038b9f
7       5901    0       tests/CMakeFiles/setup_tests_integrators        10d218adc538c50d
10      6380    0       tests/CMakeFiles/setup_tests_gla        6c6824dd0d1940a6
19      6597    0       tests/CMakeFiles/setup_tests_manifold   1a7ab1097fffc984
11      8021    0       tests/CMakeFiles/setup_tests_serialization      71e67936f873ab0f
3       8700    0       tests/CMakeFiles/setup_tests_distributed_grids  b6f40c45babcda5f
5       10475   0       tests/CMakeFiles/setup_tests_multigrid  b6cd56c158d5a62f
13      12626   0       tests/CMakeFiles/setup_tests_dofs       29d9c1d23bb6cc55
11      12779   0       tests/CMakeFiles/setup_tests_codim_one  97d4397073b08c93
23      13592   0       tests/CMakeFiles/setup_tests_all-headers        ba5aa9b0b7239985
8       13685   0       tests/CMakeFiles/setup_tests_matrix_free        49f1062eee135220
14      25221   0       tests/CMakeFiles/setup_tests_numerics   c9d6f9d6bb3e1c44
2       26917   0       tests/CMakeFiles/setup_tests_petsc      88d01305e3d321b9
17      33456   0       tests/CMakeFiles/setup_tests_grid       3c1c8f6046a262c3
16      33748   0       tests/CMakeFiles/setup_tests_trilinos   ca0c48c77ef334f1
21      44116   0       tests/CMakeFiles/setup_tests_hp 27adc3f90d18364c
1       44575   0       tests/CMakeFiles/setup_tests_lac        33f9c0f83eff6ae7
6       52569   0       tests/CMakeFiles/setup_tests_base       280c31acbb82b47d
8       58087   0       tests/CMakeFiles/setup_tests_mpi        697fcd6a9d5d608f
4       67324   0       tests/CMakeFiles/setup_tests_fe 602c2037e2721a43
20      194404  0       tests/CMakeFiles/setup_tests_bits       ed5cd6fd96f258ec
```

**Comment by tjhei** [comment]
I guess splitting up bits/ might be a good start.

**Comment by bangerth** [comment]
I thought for a while about just making multiple targets for each directory, but one would need to break the logic of the existing macro up and I'm only moderately confident I can do that :-(

**Comment by tamiko** [comment]
> I thought for a while about just making multiple targets for each directory, but one would need to break the logic of the existing macro up and I'm only moderately confident I can do that :-(

This would be a lot of logic that has to be added... Personally, I would very much prefer the pragmatic approach of splitting up bits into related topics.

**Comment by tamiko** [comment]
@bangerth: You configure on a network file system, or a slow harddrive?
```
tamiko@jackdaw build % time ninja setup_tests
[32/32] Processing tests/bits
ninja setup_tests  83.04s user 30.48s system 386% cpu 29.347 total
```

**Comment by bangerth** [comment]
On 09/11/2015 01:47 PM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth>: You configure on a network file
> system, or a slow harddrive?

Both is the case (at the same time). I primarily test on my 64-core server 
attached to an NFS-mounted file system held on rotating disks.

**Comment by tamiko** [comment]
> Both is the case (at the same time). I primarily test on my 64-core server attached to an NFS-mounted file system held on rotating disks.

Why don't you relocate the ```build``` directory on a tmpfs (or local storage)? Usually, those machines have enough main memory to hold another 10GB of build directory completely in RAM.

**Comment by bangerth** [comment]
On 09/11/2015 02:08 PM, Matthias Maier wrote:
> Why don't you relocate the |build| directory on a tmpfs (or local storage)?
> Usually, those machines have enough main memory to hold another 10GB of build
> directory completely in RAM.

I have a whole farm of machines, and I build on whatever machine happens to be 
empty that day. The build directory, I suppose, really needs to be on the 
shared file system :-(

**Comment by tamiko** [comment]
Can we close this issue?

**Comment by bangerth** [comment]
I suppose given that there is no action, this makes sense.

**Comment by bangerth** [comment]
For reference, here the current number of `.output` files for each directory:
```
4 algorithms
4 slepc
5 metis
6 arpack
6 sharedtria
6 vector_tools
10 aniso
11 umfpack
15 lapack
27 opencascade
28 integrators
36 petsc_complex
36 serialization
39 gla
48 mappings
53 distributed_grids
56 manifold
60 parameter_handler
67 codim_one
79 matrix_free
88 multigrid
137 dofs
141 petsc
158 numerics
189 trilinos
204 grid
234 hp
266 lac
327 fe
338 base
511 mpi
594 bits
```

**Comment by bangerth** [comment]
And here are current runtimes (run time is the difference between first and second column, in milliseconds):
```
11      3202    0       tests/CMakeFiles/setup_tests_umfpack    5f7c153634d917d7
12      3291    0       tests/CMakeFiles/setup_tests_mpi        82c11d090d42e1c2
10      3302    0       tests/CMakeFiles/setup_tests_petsc_complex      58d9d75250271874
9       3304    0       tests/CMakeFiles/setup_tests_slepc      3258c99f8b8db701
12      3304    0       tests/CMakeFiles/setup_tests_distributed_grids  ff02f1656ae2c129
12      4002    0       tests/CMakeFiles/setup_tests_algorithms c9a5422d3c6f844d
3203    5392    0       tests/CMakeFiles/setup_tests_gla        b6eac1b2812ff273
3302    5536    0       tests/CMakeFiles/setup_tests_metis      116d9b2cc8df9f69
3304    5539    0       tests/CMakeFiles/setup_tests_arpack     1c0baa660046d6a5
3304    5556    0       tests/CMakeFiles/setup_tests_trilinos   cf35615f9c1c5678
4002    6134    0       tests/CMakeFiles/setup_tests_opencascade        f7513244e533ebf8
10      7302    0       tests/CMakeFiles/setup_tests_integrators        1a110e9384bcb75b
6134    8478    0       tests/CMakeFiles/setup_tests_vector_tools       97efd55628aacc21
7302    9772    0       tests/CMakeFiles/setup_tests_a-framework        1f41174b033f69af
13      11294   0       tests/CMakeFiles/setup_tests_manifold   89c66782aec3a5b7
9772    11594   0       tests/CMakeFiles/setup_tests_lapack     a3c16fb00718db7b
11      12729   0       tests/CMakeFiles/setup_tests_codim_one  95207170da354928
3291    12753   0       tests/CMakeFiles/setup_tests_multigrid  b8ac859cebc551c1
8478    13435   0       tests/CMakeFiles/setup_tests_build_tests        892e80bb67448602
12753   14563   0       tests/CMakeFiles/setup_tests_slepc_complex      9a0d5c646f77b450
12729   14601   0       tests/CMakeFiles/setup_tests_sharedtria 9a4c6a925ad4d640
5536    15575   0       tests/CMakeFiles/setup_tests_parameter_handler  18555e5f03733326
13435   19524   0       tests/CMakeFiles/setup_tests_serialization      4e669e3aa9a535dc
11594   20893   0       tests/CMakeFiles/setup_tests_matrix_free        8bd9f756b04eedf1
15575   23548   0       tests/CMakeFiles/setup_tests_mappings   af75acfa2b4df76b
23548   25454   0       tests/CMakeFiles/setup_tests_petsc      543799530790d83e
25454   28562   0       tests/CMakeFiles/setup_tests_aniso      63c140a37fe4e1e1
5392    28975   0       tests/CMakeFiles/setup_tests_numerics   75dae4390cd6b9b
20894   39758   0       tests/CMakeFiles/setup_tests_dofs       49db44305a928677
5556    40327   0       tests/CMakeFiles/setup_tests_hp 6151fb237b224b5c
14601   42817   0       tests/CMakeFiles/setup_tests_grid       22462833dbed5c52
19524   53085   0       tests/CMakeFiles/setup_tests_lac        db78dcfb660c55a0
5539    54621   0       tests/CMakeFiles/setup_tests_fe c15f5fa57dacfef3
11294   54899   0       tests/CMakeFiles/setup_tests_all-headers        a582ba3e3efcdfdc
14563   61884   0       tests/CMakeFiles/setup_tests_base       6b219945cd4c372a
10      102908  0       tests/CMakeFiles/setup_tests_bits       31530ad7951fab32
```
So `bits/` is still by far the most expensive one.

**Comment by bangerth** [comment]
And because it's a bit hard to read the last list, here are actual milliseconds for the worst directories:
```
10039 0 tests/CMakeFiles/setup_tests_parameter_handler
11281 0 tests/CMakeFiles/setup_tests_manifold
12718 0 tests/CMakeFiles/setup_tests_codim_one
18864 0 tests/CMakeFiles/setup_tests_dofs
23583 0 tests/CMakeFiles/setup_tests_numerics
28216 0 tests/CMakeFiles/setup_tests_grid
33561 0 tests/CMakeFiles/setup_tests_lac
34771 0 tests/CMakeFiles/setup_tests_hp
43605 0 tests/CMakeFiles/setup_tests_all-headers
47321 0 tests/CMakeFiles/setup_tests_base
49082 0 tests/CMakeFiles/setup_tests_fe
102898 0 tests/CMakeFiles/setup_tests_bits
```

**Comment by bangerth** [comment]
For the kicks: We have added 566 new `.output` files since August of last year. That's about 1.2 new `.output` files per day, every day :-)

**Comment by bangerth** [comment]
New biggest directories:
```
1 non_matching
1 slepc_complex
1 zoltan
2 fail
4 algorithms
5 metis
6 a-framework
6 rol
6 slepc
7 cuda
8 meshworker
8 sundials
9 adolc
10 aniso
10 arpack
11 umfpack
13 physics
13 vector_tools
15 particles
22 sacado
24 lapack
25 opencascade
29 integrators
31 sharedtria
36 petsc_complex
38 serialization
39 gla
58 sparsity
62 mappings
67 distributed_grids
68 codim_one
69 manifold
69 tensors
77 data_out
90 vector
98 parameter_handler
106 multigrid
121 matrix_free
143 petsc
145 dofs
148 numerics
178 full_matrix
204 trilinos
238 grid
242 lac
244 hp
301 bits
306 base
368 fe
567 mpi
```
