### ISSUE TITLE
Tensor interface cleanup

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1583]
Hi all,

I'd like to discuss the last bits of the ```tensor.h``` cleanup a bit.

First of all, my cleanup fell a bit short in expectation. All in all it will only be a -1070 lines change :-/ (If only ```tensor.h``` and ```tensor-base.h``` is regarded it would be a -1900 lines change, so a but down to half).

(Give me some time to prepare my comments - I'll let you know when I'm done :-) )

**Comment by tamiko** [comment]
First of all, I will introduce the following general variants as replacements for our previous specializations - those are API compatible changes. Comments and implementation omitted for brevity:
```
// contract last index of src1 with first index of src2
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber>
inline
void contract (Tensor<rank_1 + rank_2 - 2, dim, typename ProductType<Number, OtherNumber>::type> &dest,
               const Tensor<rank_1, dim, Number> &src1,
               const Tensor<rank_2, dim, OtherNumber> &src2);

// same as above in operator notation
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber,
          typename = typename std::enable_if<rank_1 != 0>::type, // FIXME: Port to C++98
          typename = typename std::enable_if<rank_2 != 0>::type>
inline
typename Tensor<rank_1 + rank_2 - 2, dim, typename ProductType<Number, OtherNumber>::type>::tensor_type
operator * (const Tensor<rank_1, dim, Number> &src1,
            const Tensor<rank_2, dim, OtherNumber> &src2);

// contract the last two indices of src1 with the first two of src2
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber>
inline
void double_contract
  (Tensor<rank_1 + rank_2 - 4, dim, typename ProductType<Number, OtherNumber>::type> &dest,
   const Tensor<rank_1, dim, Number> &src1,
   const Tensor<rank_2, dim, OtherNumber> &src2);

// full contraction of three tensor objects
template <int rank_1, int rank_2, int rank_3, int dim,
          typename Number1, typename Number2, typename Number3>
inline
typename ProductType<Number1, typename ProductType<Number2, Number3>::type>::type
contract3 (const Tensor<rank_1, dim, Number1> &left,
           const Tensor<rank_1 + rank_2, dim, Number2> &middle,
           const Tensor<rank_2, dim, Number3> &right);

// outer product
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber>
inline
void outer_product
  (Tensor<rank_1 + rank_2, dim, typename ProductType<Number, OtherNumber>::type> &dest,
   const Tensor<rank_1, dim, Number> &src1,
   const Tensor<rank_2, dim, OtherNumber> &src2);
// + two specializations for Number type instead of Tensor<0, dim, Number>
```

**Comment by tamiko** [comment]
<h1>Question1</h1>

Now it gets messy. We have the following signatures that correspond to a <b>full contraction</b> and return a ```Number```:
```
template <int dim, typename Number, typename OtherNumber>
inline
typename ProductType<Number,OtherNumber>::type
contract (const Tensor<1,dim,Number> &src1,
          const Tensor<1,dim,OtherNumber> &src2);

template <int dim, typename Number>
inline
Number
scalar_product (const Tensor<2,dim,Number> &t1,
                const Tensor<2,dim,Number> &t2);
```

 * I dislike this ```contract``` variant - this is what ```operator*``` is for.
 * The term "scalar product" is a bit of a "minefield". I would like to avoid when talking about general tensors and just go with "single contraction", "double contraction", "full contraction" instead.

Therefore, I would like to immediately nuke those variants and replace them with a signature like
```
// Perform a full contraction
template <int rank, int dim,
          typename Number, typename OtherNumber>
inline
typename ProductType<Number,OtherNumber>::type
full_contract (const Tensor<rank, dim, Number> &src1, // FIXME: Name?
               const Tensor<rank, dim, OtherNumber> &src2);
```
(Naming up to debate, but somehow it has to be compatible with ```contract``` and ```double_contract```.)

**Comment by tamiko** [comment]
(Done for now, rest follows)

**Comment by bangerth** [comment]
Here my notes:
1/ Where do you actually need `contract3`? I think writing `a*B*c` should do as well, at least if `a,b` are rank-1 tensors.

2/ I think that the contract functions that return the product as first argument are an accident of history. They go against our usual convention of putting input arguments first (and did so in reference to our `vmult` functions that make the same mistake). Given that the memory of `Tensor` objects is all statically allocated, I think that a more elegant design would actually simply return the result. I would be in favor of deprecating the 3-argument forms in favor of two argument forms.

3/ For the full contraction forms, can't you return rank-0 tensors and allow for implicit conversion of a rank-0 tensor to a scalar? This way, everything would remain nice and symmetric and you may not even need the specializations.

4/ As for `scalar_product` -- removing the signature would unfortunately break backward compatibility. I think it's also not wrong: it is the scalar product that matches the norm we use for tensors.

**Comment by tamiko** [comment]
> 1/ Where do you actually need contract3? I think writing a*B*c should do as well, at least if a,b are rank-1 tensors.

It was probably written well before the introduction of ```operator*```, and we have signatures for 1 x 3 x 2, 2 x 3 x 1, 2 x 4 x 2 at the moment.

**Comment by tamiko** [comment]
> 2/ I think that the contract functions that return the product as first argument are an accident of history. ... (and did so in reference to our ```vmult``` functions that make the same mistake).

We can just deprecate them ```operator*``` is a nicer convention in my opinion.

**Comment by bangerth** [comment]
On 09/11/2015 07:08 PM, Matthias Maier wrote:
>     1/ Where do you actually need contract3? I think writing a/B/c should do
>     as well, at least if a,b are rank-1 tensors.
>
> It was probably written well before the introduction of |operator*|, and we
> have signatures for 1 x 3 x 2, 2 x 3 x 1, 2 x 4 x 2 at the moment.
Ha, who knew. Do we use `contract3` anywhere? Maybe also deprecate these? 
(That would avoid having to update their implementations.)

**Comment by bangerth** [comment]
On 09/11/2015 07:16 PM, Matthias Maier wrote:
> We can just deprecate them |operator*| is a nicer convention in my opinion.
I agree. (But careful: `operator*` between SymmetricTensors does not yield the 
contraction, but the double-contraction :-( )

**Comment by tamiko** [comment]
> Do we use `contract3` anywhere? Maybe also deprecate these? (That would avoid having to update their implementations.)

Well, it is an operation that cannot be expressed with the other functions (only by using ```TensorAccessors::...``` directly.

**Comment by bangerth** [comment]
On 09/11/2015 07:22 PM, Matthias Maier wrote:
> Well, it is an operation that cannot be expressed with the other functions
> (only by using |TensorAccessors::...| directly.

What I meant is: if you deprecate the function, then there is no need to even 
touch the implementation. Or did you mean to say that the functions can't be 
deprecated because there is no other way to achieve what the functions do? I 
think `a*B*c == contract3(a,B,c)`, no?

**Comment by tamiko** [comment]
> I think `a*B*c == contract3(a,B,c)`, no?

Only for 1 x 2 x 1, we also have <code>a_{ij}b_{ijk}c_k</code> (einstein convention), <code>a_ib_{ijk}c_{jk}</code>, and <code>a_{ij}b_{ijkl}c_{kl}</code>.

**Comment by tamiko** [comment]
> What I meant is: if you deprecate the function, then there is no need to even touch the implementation.

You will not deprive me of the satisfaction to remove those stuff. ;-)

**Comment by bangerth** [comment]
On 09/11/2015 07:38 PM, Matthias Maier wrote:
> You will not deprive me of the satisfaction to remove those stuff. ;-)

Then go right about it :-) `contract3` may not be expressible in terms of 
`operator*` then, but it is expressible using the existing functions. I think 
it's an obscure enough issue to not worry too much about it.

As far as I can see, none of these functions are actually used anywhere 
outside the testsuite.

**Comment by tamiko** [comment]
<h1>Question 2</h1>

Further, we have special cases of the following function signature:

```
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber>
inline
void contract (Tensor<rank_1 + rank_2 - 2, dim, typename ProductType<Number, OtherNumber>::type> &dest,
               const Tensor<rank_1, dim, Number> &src1,
               const unsigned int index1,
               const Tensor<rank_2, dim, OtherNumber> &src2,
               const unsigned int index2)
{
}
```

I dislike this signature due to multiple reasons:
 * The parameters ```index1```, ```index2``` have to be converted to a template signature - there is no nice way of doing that.
 * This is a special use case remedy for a general lack of contraction syntax. [1]

But for the moment I probably just go with implementing this thing.

[1] A nice feature would be for example to allow the following syntax:
```
  left[b][a][c] * middle[c][d][e] * right[e][d][f][g];
```
To express a tensor of fourth order with index ordering ```[a][b][f][g]```. But implementing such a thing is a highly non trivial task. (Maybe as ambitious as writing a dedicated tensor template expression library - maybe we should just use one - if a decent one exists...).

**Comment by bangerth** [comment]
Agreed. Find out whether these functions are actually used anywhere. If not, deprecate them.

In all places I can imagine, `index1` and `index2` will be compile-time constants. In such cases, a more appropriate syntax would have been to indicate the indices as a template argument. Think of
```
template <int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber,
          int index1,
          int index2>
inline
void contract (Tensor<rank_1 + rank_2 - 2, dim, typename ProductType<Number, OtherNumber>::type> &dest,
               const Tensor<rank_1, dim, Number> &src1,
               const internal::int2type<index1>,
               const Tensor<rank_2, dim, OtherNumber> &src2,
               const internal::int2type<index2>)
```
or something similar. Maybe also
```
template <
          int index1,
          int index2,
          int rank_1, int rank_2, int dim,
          typename Number, typename OtherNumber>
inline
void indexed_contract (Tensor<rank_1 + rank_2 - 2, dim, typename ProductType<Number, OtherNumber>::type> &dest,
               const Tensor<rank_1, dim, Number> &src1,
               const Tensor<rank_2, dim, OtherNumber> &src2)
```
which would require you to specify the indices explicitly as a template argument.

(If we had C++11, we could put this into `contract` itself and default the first two arguments to `rank1-1` and `0`, respectively.)

**Comment by tamiko** [comment]
@bangerth: What about I refactor all things that shall be deprecated into an extra header ```tensor_compatibility.h```  - we can decide to either include it at the end of ```tensor.h``` automatically, or let the user make this conscious decision.

**Comment by tamiko** [comment]
Anyway, I'll refactor in small steps. First part incoming.

**Comment by bangerth** [comment]
On 09/11/2015 09:33 PM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth>: What about I refactor all things that
> shall be deprecated into an extra header |tensor_compatibility.h| - we can
> decide to either include it at the end of |tensor.h| automatically, or let the
> user make this conscious decision.

That will make it easy to eventually throw it all away. I'd say do it, but 
automatically #include it.

**Comment by tamiko** [comment]
I will name the full contraction ```scalar product``` to keep compatibility:
```
/**                                                                                  
 * The scalar product, or (generalized) Frobenius inner product of two               
 * tensors of equal rank: Return a scalar number that is the result of a             
 * full contraction of a tensor @p left and @p right:                                
 * @f[                                                                               
 *   \sum_{i_1,..,i_{r}                                                              
 *   \text{left}_{i_1,..,i_r}                                                        
 *   \text{right}_{i_1,..,i_r}                                                       
 * @f]                                                                               
 *                                                                                   
 * @relates Tensor                                                                   
 * @author Matthias Maier, 2015                                                      
 */                                                                                  
template <int rank, int dim, typename Number, typename OtherNumber>                  
inline                                                                               
typename ProductType<Number, OtherNumber>::type                                      
scalar_product (const Tensor<rank, dim, Number> &left,                               
                const Tensor<rank, dim, OtherNumber> &right);
```

**Comment by tamiko** [comment]
Further, I will deprecate all other contraction functions for a generic 2 argument ```contract``` that lets you specify pairs of indices that shall be contracted. (Due to lack of motivation to refactor yet another time, just a single and double contraction variant - this can be readily expanded to a generic variants with variadic templates).

Just one question: <b>How to number indices</b>?
 - from ```0``` to ```rank-1```
 - from ```1``` to ```rank```?

**Comment by tamiko** [comment]
> that lets you specify pairs of indices that shall be contracted.
as template parameters:
```
contract<1, 2>(t1, t2); // index 1 from t1 with index 2 from t2
contract<1, 2, 2, 1>(t1, t2); // index 1 from t1 with index 2 from t2 and index 2 from t1 with index 1 from t2.
```

**Comment by bangerth** [comment]
I think you made your choice with the numbering of indices. I'm with that.

**Comment by bangerth** [comment]
@tamiko -- is there anything else you intended to do for this?

**Comment by tamiko** [comment]
@bangerth Nope.
