### ISSUE TITLE
serialization/* - failures with boost-1.58

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1591]
I haven't pinned down exactly what is amiss but serialization/quadrature already fails.

http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=12415

**Comment by tamiko** [comment]
Ah, the new pretty printers do a nice job :-] (@drwells)
```
(gdb) info frame
Stack level 7, frame at 0x7fffffffdae0:
 rip = 0x43c6e3 in verify<dealii::Quadrature<2> > (/home/tamiko/workspace/dealii/tests/serialization/serialization.h:67); saved rip = 0x43ba4c
 called by frame at 0x7fffffffdde0, caller of frame at 0x7fffffffd4f0
 source language c++.
 Arglist at 0x7fffffffdad0, args: t1={
  quadrature_points = std::vector of length 4, capacity 4 = {{0, 0}, {0, 1}, {1, 1}, {1, 0}},
  weights = std::vector of length 4, capacity 4 = {0.20000000000000001, 0.29999999999999999, 0.14999999999999999, 0.34999999999999998}
}, t2={
  quadrature_points = std::vector of length 8, capacity 8 = {{1, 1}, {1, 0}, {0, 0}, {0, 1}, {0, 0}, {0, 1}, {1, 1}, {1, 0}},
  weights = std::vector of length 4, capacity 4 = {0.20000000000000001, 0.29999999999999999, 0.14999999999999999, 0.34999999999999998}
}
```
Observe how the ```std::vector``` of ```t2``` got appended and not replaced...

**Comment by tamiko** [comment]
I found an upstream bug report: https://svn.boost.org/trac/boost/ticket/11612

**Comment by tamiko** [comment]
And a second bug report: https://svn.boost.org/trac/boost/ticket/11498 (The former will likely become a duplicate)

**Comment by bangerth** [comment]
Bummer. Do we need to blacklist 1.58 and fall back to the bundled version if we find it?

**Comment by tamiko** [comment]
On Sun, Sep 13, 2015, at 20:13 CDT, Wolfgang Bangerth <notifications@github.com> wrote:

> Bummer. Do we need to blacklist 1.58 and fall back to the bundled version if we find it?

I don't see any other option. We tend to serialize a std::vector quite
frequently...

**Comment by drwells** [comment]
@tamiko thanks!

**Comment by bangerth** [comment]
:-( I agree with the resolution -- it's simply not feasible for us to go through all serialization functions and clear all std::vector variable. In particular because that would require breaking apart all of those functions that do both serialization and deserialization.

**Comment by bangerth** [comment]
We should resolve this before the next release. Blacklist 1.58 from the possible list of external versions?

**Comment by tjhei** [comment]
So it seems like 1.56 (bundled) and 1.59 work correctly? Then blacklisting 1.58 is a good idea.

**Comment by tamiko** [comment]
> So it seems like 1.56 (bundled) and 1.59 work correctly? Then blacklisting 1.58 is a good idea.

I will address this together with the other improvement for external
boost detection we discussed some time ago later today in a pull
request.

**Comment by gassmoeller** [comment]
We made the observation that 1.54 also causes serialization to fail. Should we blacklist 1.54 as well?

**Comment by tjhei** [comment]
I tested version 1.54 (works), 1.56 (works), 1.58 (failed), 1.59 (works). @gassmoeller what test is failing for you?

**Comment by gassmoeller** [comment]
There was a segmentation fault during serialization with the ubuntu packaged boost 1.54 reported by Maxwell Rudolph to me. I will give it a try on my machine, and if I can not reproduce it, lets assume it is something related to his machine (he solved the problem by enforcing the deal.ii bundled boost).

**Comment by tamiko** [comment]
> I will address this together with the other improvement for external
boost detection we discussed some time ago later today in a pull
request.

Can someone remind me what I had in mind with "improvement for external boost detection"? :-/

**Comment by tjhei** [comment]
Just take a look at #2132 and we call it a day. ;-)

**Comment by tamiko** [comment]
Yup.

**Comment by gassmoeller** [comment]
Ok, I can not reproduce the issues with 1.54. The Ubunut-Packaged 1.54 works on my machine, so no need to worry about that anymore.
