### ISSUE TITLE
Proposal: set DEAL_II_DOXYGEN_USE_MATHJAX to ON by default

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#15994]
Trying to build documentation with formulas it did not set them by default 
even though I had mathjax installed on my system.
I had to set -DDEAL_II_DOXYGEN_USE_MATHJAX=ON additionally.

Talking to @peterrum I seem to be not alone with this confusion
of having working doxygen + mathjax but not getting formulas.

Looking at the CMake the checks to find Mathjax are already built in,
so I would propose the following change:

Add DEAL_II_DOXYGEN_USE_MATHJAX=ON as the default option.
Now behaviour depends on DEAL_II_COMPONENT_DOCUMENTATION
- For OFF, the option would be ignored as it is queried inside the doc/doxygen/CMakeLists.txt
- For ON, CMake searches for the mathjax.js file
      * If found, doxygen will be configured with USE_MATHJAX
      * If not, a message or warning will be displayed that mathjax is not found and should be installed and USE_MATHJAX 
         will be set to no

I'd be happy to add these changes in a PR if you think this new default behaviour would be useful.

**Comment by blaisb** [comment]
I agree with this idea. It prevents confusion when trying to compile the documentation the first time.

**Comment by tamiko** [comment]
As the one responsible for this option being off I vaguely recall that the option was relatively new when we introduced it. Hence we never considered enabling it by default.

Another point is the fact why I probably chose to set the default to off is the fact that using online mathjax is a "privacy breach", meaning you are telling the online mathjax website what you are looking at locally.

But all of this considered, I have no problem enabling this by default. I would, however, try to keep the amount of autodetection at a minimum. Meaning we can search for a local mathjax and use it when found. But I wouldn't issue a warning when no local mathjax is found, simply fall back to using the online version hosted by cloudflare.

**Comment by jpthiele** [comment]
The "privacy breach" part was why I was thinking of hinting the user at either installing mathjax or enabling online mathjax. 
But I'm also fine with then using online mathjax so the documentation always builds correctly with formulas.

**Comment by jpthiele** [comment]
superseced by #17472

**Comment by bangerth** [comment]
Oh, oops. I should have searched for this one first before opening #17472...
