### ISSUE TITLE
Provide a TOC in our Wiki for the FAQ section and related pages

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1599]
As now reported multiple times on the mailing list...

Unfortunately, we lost our automatically generated TOCs during the migration from google code to github.

**Comment by drwells** [comment]
This was pretty easy. Major +1 to the heroes at 

https://github.com/ekalinin/github-markdown-toc

for providing a workaround for this issue. I deleted some of the link data (it puts github.com data and versioning information in the link, which seems to both be unneeded and break the actual links on our wiki for reasons I do not really understand).

For posterity: at some point in the future, github flavored markdown should support syntax like

```
{:toc}
```

to generate a table of contents at the beginning of a file, but this is not the case not.

**Comment by tamiko** [comment]
*wow* Perfect!

This project wasn't around when I briefly looked for a solution a year ago..

**Comment by bangerth** [comment]
Ah, awesome! Indeed, last I checked there was apparently no good solution to getting a toc.

**Comment by drwells** [comment]
There still does not seem to be a good solution for this, and it is a known problem with Github flavored markdown. The shell script provided by @ekalinin is quite impressive.

**Comment by bangerth** [comment]
By the way, I suppose we have to run this everytime we change something 
in the wiki now, right? Not that that happens very often...

**Comment by drwells** [comment]
Yes, and I manually adjusted that output. I do not believe anyone has added a section to the FAQ since it was put on Github so I do not anticipate this will be a problem. I will add a warning for our future selves.

**Comment by ekalinin** [comment]
> The shell script provided by @ekalinin is quite impressive.

Glad that it was useful for you, guys. 
Btw, there's a golang based version of this script:
  * https://github.com/ekalinin/github-markdown-toc.go
It's cross-platform and able to process several documents in parallel mode.
