### ISSUE TITLE
Doxygen site: forced dark mode has bright white dot graphsin Firefox

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#16001]
This is basically related to #14873 but for the dot graphs.

Since doxygen 1.9.5 a transparent background for dot graphs should be the default,
but the svgs are definitely with a white background. 
Maybe we can manually specify a background with very low to 0 opacity. 

Then I would suggest we change the border color of all object to some grey that is both visible 
with black and white backgrounds. And maybe we have to look how visible the tutorial category colors are on a black background.
The nodes should not be a problem with the border, but the arrows could be more difficult.

I'd be happy to play around a bit and try to find some settings. 
If you have any clear preferences for colors or color schemes let me know!

**Comment by bangerth** [comment]
If you have ideas how to achieve what you want, please go ahead with what you think looks best!

**Comment by jpthiele** [comment]
The transparency issue gets resolved with switching from svg format to png.
However, in the current settings some things basically vanish, so I will continue to try to configure doxygen.
As the tutorial graph uses the most colors I started around with finding a color set it.
On http://magjac.com/graphviz-visual-editor/ you can quickly try and iterate color schemes.
The set I came up with is the following, let me know what you think!
(The hard coded color is the value of html links in the documentation, which looks good on both 
white and black background, so I would use it as border and edge color everywhere)

```
digraph {
   bgcolor = black
   #bgcolor = white
   node [fillcolor= white color="#719AED" style = filled]
   edge [color="#719AED"]
   basic [fillcolor=green]
   tech [fillcolor = orange]
   fluid [fillcolor = yellow2]
   solids [fillcolor = coral]
   timedep [fillcolor = darkolivegreen1]
   abc -> def
   def -> basic [color = green]
   basic -> tech [color = orange]
   tech -> fluid [color = yellow2]
   basic -> solids [color = coral]
   solids -> timedep [color = darkolivegreen1]
}
```

**Comment by jpthiele** [comment]
Looks like you can not change the default color scheme for class graphs but it looks decent enough, see
![Screenshot_QSimplex](https://github.com/dealii/dealii/assets/54978337/b0f3031e-4cc7-4438-b8a5-9b293dbd1af0)

The self constructed graphs in some Perl scripts are under full control of course.

For other things like directory graphs the options apply. 
If you know of a subpage with a large group graph it would be good if you can point me to it,
so I can check that it looks good in both dark and light mode.

**Comment by bangerth** [comment]
If you think things look good, I see no reason to second-guess that :-) Submit a pull request, we'll merge and look at the result and if someone finds it unbearable, we can always iterate/improve!
