### ISSUE TITLE
Misprint in step-16

### ISSUE THREAD

**Issue by kostyfisik** [dealii/dealii#1603]
https://www.dealii.org/developer/doxygen/deal.II/step_16.html#Possibleextensions

Double use of word "that that" in first paragraph of extension section.

**Comment by bangerth** [comment]
Indeed. Want to write a patch for it? The text from which this line comes is in `examples/step-16/doc/results.dox`.

**Comment by bangerth** [comment]
Well, I guess @drwells beat you to it :)

**Comment by kostyfisik** [comment]
Good! May be I can be better next time :)

пн, 14 сент. 2015 г. в 21:33, Wolfgang Bangerth <notifications@github.com>:

**Comment by drwells** [comment]
What can I say... my struggle against the typos continues.

**Comment by bangerth** [comment]
Do you feel like Don Quixote?

**Comment by drwells** [comment]
I think 90% of my windmills have been toppled by this point, so only a little. I actually never checked the examples for typos.

**Comment by tamiko** [comment]
@drwells And all this ignorant Germans [sət] [wrīt] [sə] [hôrəblə] [eNGɡliSH].

**Comment by drwells** [comment]
Well, I still do not have a good explanation for why 'somehow', 'somewhere', and 'somewhat' are English words but 'somewhen' is not (that might be my favorite spelling issue so far). Sometimes I think C++ is really the 'English of programming languages'.

I think people of all nationalities are equally capable of making fat fingered mistakes. As far as Germans go, I suspect starting a sentence with "Here comes the" might be uniquely yours. If you are interested I could try to compile a list of things that look to me like German idioms :)

**Comment by bangerth** [comment]
I think that could actually be quite a lot of fun for us Germans. As well as help us avoid these idiosyncrasies in the future :-)
