### ISSUE TITLE
Fatal Error during Compile, open CFI at end of file

### ISSUE THREAD

**Issue by IntrepidNomad** [dealii/dealii#16148]
[ 33%] Building CXX object source/fe/CMakeFiles/object_fe_release.dir/fe_values_inst5.cc.o
{standard input}: Assembler messages:
{standard input}:901963: Warning: end of file not at end of a line; newline inserted
{standard input}:902872: Error: bad register name `%rb'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [source/fe/CMakeFiles/object_fe_release.dir/build.make:174: source/fe/CMakeFiles/object_fe_release.dir/fe_values_inst3.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[detailed.log](https://github.com/dealii/dealii/files/12910526/detailed.log)

**Comment by drwells** [comment]
It looks like you ran out of memory. Could you try this again but use fewer parallel build jobs?

**Comment by drwells** [comment]
@IntrepidNomad any news?

**Comment by IntrepidNomad** [comment]
@drwells No news so far. Unfortunately I have been busy lately, I just attempted to rebuild but ran into a different issue while building related to arb.h not being found while compiling.

**Comment by IntrepidNomad** [comment]
@drwells Managed to successfully compile after updating packages and recompiling with -j1
