### ISSUE TITLE
Discrepancy in Periodicity Handling with Serial and Distributed Triangulations

### ISSUE THREAD

**Issue by KParas** [dealii/dealii#16170]
For certain meshes (having periodic boundaries) generated with external meshing programs such ash Gmsh, the `dealii::parallel::distributed::Triangulations::add_periodicity()` seems to throw an assertion, while there is not issue in detecting the periodic faces with the serial Triangulation.

A minimal working example, with detailed output logs, error messages and some example mesh files can be found [on this mailing list thread](https://groups.google.com/d/msgid/dealii/6fa10380-8535-4f29-b5cf-7cd40fd62e21n%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by KParas** [comment]
@bangerth Could you please have a look at this one?

**Comment by bangerth** [comment]
@KParas  I don't actually have any expertise in how we are handling periodicity. Someone else has to handle this case.

**Comment by bangerth** [comment]
A good starting point would be to make the testcase smaller. The `.cc` file contains a lot of other things (it handles 2d and 3d, has debug output, etc). Reduce it to the absolute minimum of what it takes to get to the point where the exception is thrown. Nothing else.
