### ISSUE TITLE
Multithreading in Dealii

### ISSUE THREAD

**Issue by Jai-40** [dealii/dealii#16193]
<!--
Thanks for reporting an issue with deal.II! This HTML comment won't be visible
in the issue tracker but is present here to help you write a better description
of the problem you encountered.

If you have questions about deal.II, please post them on the mailing list:

   https://groups.google.com/g/dealii

Otherwise:
- Do you encounter a compilation failure? Please attach the detailed.log file
  present in the build directory here. Any additional compiler messages will also
  be helpful!

- Does something crash (e.g., an example) that shouldn't? Please include any relevant
  terminal output as well as the detailed.log file generated in your build
  directory (should you have one).

- Is there a missing feature you want to implement? Please briefly describe it and
  the problem it ### 

1. > `_solves._`

- Did you find some other issue with deal.II? Summarize the problem here.
Is multithreading enabled in dealii?  if yes, does running any example using (cmake . -> make run) uses multithreading or not. If not please specify how can we run using multithreading.

**Comment by Jai-40** [comment]
Is multithreading enabled in dealii?  if yes, does running any example using (cmake . -> make run) uses multithreading or not. If not please specify how can we run using multithreading.

**Comment by drwells** [comment]
Yes, see https://www.dealii.org/developer/doxygen/deal.II/group__threads.html#MTTaskThreads for documentation on how to enable multithreading. By default deal.II is compiled with support for threads via Intel's Thread Building-Blocks library (TBB).

This is a question more suited for the mailing list than the issue tracker - if you still have questions could you post them there? Thanks!

**Comment by Jai-40** [comment]
Thanks for replying.
Could you mention about the multithreading in ARM.
