### ISSUE TITLE
Email Id for general queries.

### ISSUE THREAD

**Issue by Jai-40** [dealii/dealii#16214]
Can I get the correct email id to get my queries resolved. I mailed to <dealii@googlegroups.com> this email id but did not get the answer. Please provide me the email through which I can get answer to my queries.

**Comment by masterleinad** [comment]
If your question shows up at https://groups.google.com/g/dealii, everything is OK. It might take awhile for us to answer all the questions. If it doesn't show up there, could just use the web interface.

**Comment by Jai-40** [comment]
OK, Thanks.
