### ISSUE TITLE
Issue in installation of deal.ii on arm

### ISSUE THREAD

**Issue by Jai-40** [dealii/dealii#16220]
I downloaded deal.ii 9.5.0 . After extracting the files I gave the following following camke commands : 
I used gcc version 12.2.0 . cmake version 3.26.1 , openmpi/4.1.1
**cmake -DCMAKE_INSTALL_PREFIX=/path to install dealii/,  -DKOKKOS_DIR=/path to kokkos/ , -DPETSC_DIR=/path to petsc/ , -DDEAL_II_WITH_MPI=ON**

It got executed successfully. But after this while executing make -j command I am getting the following errors:

/dealii-9.5.0/bundled/tbb-2018_U2/src/tbb/tools_api/ittnotify_config.h: In function ‘long int __itt_interlocked_increment(volatile long int*)’:
/**dealii-9.5.0/bundled/tbb-2018_U2/src/tbb/tools_api/ittnotify_config.h:329:12: error: ‘__TBB_machine_fetchadd4’ was not declared in this scope
  329 |     return __TBB_machine_fetchadd4(ptr, 1) + 1L;**
      |            ^~~~~~~~~~~~~~~~~~~~~~~
[ 17%] Building CXX object bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_release.dir/tbb/governor.cpp.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_DL_TSOLVE_release.dir/umf_utsolve.cc.o
[ 17%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_debug.dir/amd_preprocess.cc.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_L_UMF_release.dir/umf_grow_front.cc.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_GENERIC_release.dir/umfpack_global.cc.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_Z_UMF_debug.dir/umf_usolve.cc.o
make[2]: *** [bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/build.make:230: bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/tbb/itt_notify.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_release.dir/tbb/spin_mutex.cpp.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_L_UMFPACK_debug.dir/umf_report_perm.cc.o
[ 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/b
 17%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_Z_UMF_release.dir/umfpack_transpose.cc.o
[ 17%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_debug.dir/amd_postorder.cc.o
make[2]: *** [bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_release.dir/build.make:230: bundled/tbb-2018_**U2/src/CMakeFiles/bundled_tbb_release.dir/tbb/itt_notify.cpp.o] Error 1**
make[2]: *** Waiting for unfinished jobs....
[ 19%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_release.dir/amd_valid.cc.o
[ 19%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_L_UMF_release.dir/umfpack_save_symbolic.cc.o
[ 19%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_debug.dir/amd_dump.cc.o
[ 19%] Built target bundled_umfpack_ZL_TRIPLET_NOMAP_NOX_release
[ 19%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_DL_SOLVE_debug.dir/umfpack_solve.cc.o
tats.cc.o
[ 26%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_Z_UMF_debug.dir/umf_valid_symbolic.cc.o
[ 26%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_release.dir/amd_post_tree.cc.o
**ld.lld: error: undefined symbol: std::__throw_bad_array_new_length()
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate(unsigned long, void const*))
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_List_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::allocate(unsigned long, void const*))
>>> referenced by expand_instantiations.cc
>>>               CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o:(std::__new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::allocate(unsigned long, void const*))
collect2: error: ld returned 1 exit status
make[2]: *** [cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/build.make:97: bin/expand_instantiations] Error 1
make[1]: *** [CMakeFiles/Makefile2:1718: cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....**
[ 26%] Building CXX object bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/tbb/tbb_thread.cpp.o
[ 26%] Building CXX object bundled/umfpack/UMFPACK/Source/CMakeFiles/bundled_umfpack_Z_UMF_debug.dir/umf_store_lu.cc.o
 32%] Building CXX object bundled/umfpack/AMD/Source/CMakeFiles/bundled_amd_long_debug.dir/amd_aat.cc.o
[ 32%] Building CXX object bundled/muparser_v2_3_3/CMakeFiles/bundled_muparser_release.dir/src/muParserError.cpp.o
[ 32%] Built target bundled_umfpack_L_UMFPACK_debug
[ 32%] Built target object_rol_inst
[ 32%] Built target bundled_umfpack_ZL_TSOLVE_debug
[ 32%] Built target bundled_umfpack_ZL_TRIPLET_NOMAP_NOX_debug
[ 32%] Built target bundled_umfpack_ZL_ASSEMBLE_release
[ 32%] Built target bundled_umfpack_L_UMFPACK_release
[ 32%] Built target bundled_umfpack_ZL_SOLVE_debug
[ 32%] Built target bundled_umfpack_DL_STORE_release
[ 32%] Built target bundled_amd_long_release
[ 32%] Built target bundled_umfpack_DL_TRIPLET_NOMAP_NOX_debug
[ 32%] Built target bundled_amd_int_debug
[ 32%] Built target bundled_amd_int_release
[ 32%] Built target bundled_umfpack_GENERIC_debug
[ 32%] Built target bundled_amd_long_debug
[ 32%] Built target bundled_umfpack_GENERIC_release
[ 32%] Built target bundled_umfpack_ZL_SOLVE_release
[ 32%] Built target bundled_umfpack_Z_UMF_debug
[ 32%] Built target bundled_umfpack_L_UMF_debug
make[1]: *** [CMakeFiles/Makefile2:1978: bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_debug.dir/all] Error 2
[ 32%] Built target bundled_umfpack_Z_UMF_release
[ 32%] Built target bundled_umfpack_L_UMF_release
make[1]: *** [CMakeFiles/Makefile2:2004: bundled/tbb-2018_U2/src/CMakeFiles/bundled_tbb_release.dir/all] Error 2
[ 32%] Built target bundled_boost_iostreams_debug
[ 32%] Built target bundled_muparser_debug
[ 32%] Built target bundled_boost_iostreams_release
[ 32%] Built target bundled_boost_serialization_debug
[ 32%] Built target bundled_muparser_release
[ 32%] Built target bundled_kokkos_debug
[ 32%] Built target bundled_boost_serialization_release
[ 32%] Built target bundled_kokkos_release
**make: *** [Makefile:136: all] Error2**
Please specify where am i doing wrong.

**Comment by bangerth** [comment]
@Jai-40 Getting things to work on ARM platforms is probably easiest if you download the .dmg package that has all of these issues worked out.

**Comment by Jai-40** [comment]
could you provide the link to download the same.

**Comment by bangerth** [comment]
@Jai-40 It's on the download page for deal.II, to be found from https://www.dealii.org

**Comment by Jai-40** [comment]
I have downloaded the .dmg package from (https://github.com/dealii/dealii/releases/download/v9.5.0/dealii-9.5.0-ventura-arm64.dmg). I did'n find the documentation for the .dmg package how to use it . I am using aarch64. Please guide me for the same.

**Comment by bangerth** [comment]
https://www.google.com/search?q=install+a+dmg+file+on+mac&oq=install+a+dmg+&gs_lcrp=EgZjaHJvbWUqBwgBEAAYgAQyBggAEEUYOTIHCAEQABiABDIICAIQABgWGB4yCAgDEAAYFhgeMggIBBAAGBYYHjIICAUQABgWGB4yCggGEAAYDxgWGB4yCAgHEAAYFhgeMggICBAAGBYYHjIICAkQABgWGB7SAQg1NDgxajBqN6gCALACAA&sourceid=chrome&ie=UTF-8
