### ISSUE TITLE
Doxygen version for developer documentation too old

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#16238]
I'm guessing the [developer documentation](https://www.dealii.org/developer/doxygen/deal.II/Tutorial.html) is build automatically after new merges or at fixed intervals. 
However, compared to the [current stable version (9.5.0)](https://www.dealii.org/current/doxygen/deal.II/Tutorial.html)
the documentation is build with doxygen v1.9.1 instead of 1.9.7,
so some of the new fixes e.g. for darkmode will not be active until the next major release.

As the indent action is now on a new version it must be running on some other machine that would need an update.

**Comment by bangerth** [comment]
Yes, @tamiko (who runs out website) builds the developer documentation with a script every 20 minutes or so. You'll have to bug him to update his doxygen version :-)

**Comment by tamiko** [comment]
I have upgraded the doxygen version to 1.9.8
