### ISSUE TITLE
Modernize Tensor and Point

### ISSUE THREAD

**Issue by RichardYCJ** [dealii/dealii#16243]
It all begins when I want a constexpr Point in my project. I felt it strange that dealii does not support constexpr `Point<dim>` while `Tensor` does.

### Modernize some member functions
Since we require C++14 nowadays (btw the README did not list c++14 **as mandatory** but only in the changes #13665), we could remove some outdated workarounds in these antiques.
- add as many constexpr as possible to `Point<dim>`
- use `= default` instead of explicit define Point::Point()
- use `std::array` instead of c-style array for `Tensor::values`
- The Point ctors that accepts one, two, three Number for 1,2,3D points only is weird, should we consider a better way for it?
  - `std::initializer_list` and check for size
  - use `Point(const Number = {}, const Number = {}, const Number = {})` and define them explicitly with different dim

In addition, there is a strange macro if in `Tensor::operator[]`, do we have an unexpected `#endif` here?
![image](https://github.com/dealii/dealii/assets/30151967/185cc840-8a99-432e-be3a-dcc30302a351)

### Opinions about Point<0>
Though it is a workaround for `Quadrature<1>` to accept sub quadrature. I think it is better to add a specialization for Quadrature<0> that deletes certain ctor than to allow `dim == 0` for Tensor and Point.

**Comment by masterleinad** [comment]
> Since we require C++14 nowadays (btw the README did not list c++14 **as mandatory** but only in the changes #13665), we could remove some outdated workarounds in these antiques.

We are actually requiring C++17 now.

> use `= default` instead of explicit define Point::Point()

Sure.

> use `std::array` instead of c-style array for `Tensor::values`

We want to able to use this class on GPUs as well so you can't use `std::array`.

> The Point ctors that accepts one, two, three Number for 1,2,3D points only is weird, should we consider a better way for it?

We  are happy to have a look if you have better idea that follows the same semantics we have right now.

> In addition, there is a strange macro if in Tensor::operator[], do we have an unexpected #endif here?

The line you pointed out belongs to `#ifdef KOKKOS_ACTIVE_MEMORY_SPACE_HOST`.

**Comment by RichardYCJ** [comment]
Hi @masterleinad, so glad to hear C++17 becomes a requirement! I'll try if I could make the Point ctor better. Any comments on `Point<0>`?

>We want to able to use this class on GPUs as well so you can't use std::array.

According to NVIDIA/libcudacxx#51 and NVIDIA/libcudacxx#243, cuda actually has supported static array but with its name `cuda::std::array` in `<cuda/std/array>`. I tried with simple code and it works:
```cuda
#include <stdio.h>
#include <cuda/std/array>

__global__ auto kernel() -> void {
    cuda::std::array<double,3> arr{};
    printf("arr: %f, %f, %f\n", arr[0], arr[1], arr[2]);
    arr[0] = 1.5;
    arr[1] = 2.1;
    arr[2] = 3.;
    printf("arr: %f, %f, %f\n", arr[0], arr[1], arr[2]);
}

auto main() -> int{
    kernel<<<1,1>>>();
    cudaDeviceSynchronize();
    return 0;
}
```

Though it is still a problem how we combine `std::array` and `cuda::std::array` together

> The line you pointed out belongs to `#ifdef KOKKOS_ACTIVE_MEMORY_SPACE_HOST`

If so then there will be no boundary check in this case (gray one will be omitted during compiling)

**Comment by masterleinad** [comment]
> According to [NVIDIA/libcudacxx#51](https://github.com/NVIDIA/libcudacxx/issues/51) and [NVIDIA/libcudacxx#243](https://github.com/NVIDIA/libcudacxx/pull/243), cuda actually has supported static array but with its name `cuda::std::array` in `<cuda/std/array>`. I tried with simple code and it works (cuda 11.8):

That's not quite enough, we also want to support `AMD` and `Intel` GPUs. You could use `Kokkos::Array` but it's not quite clear to me if that has significant advantages over a C-style array.

> Any comments on Point<0>?

Ideally, we don't allow `Quadrature<0>` or `Point<0>`. If you want to propose some improvements go ahead and justify why your suggestions is better than what we have already. 🙂

**Comment by bangerth** [comment]
@RichardYCJ `Tensor` and `Point` were some of the very first classes written for deal.II, in around 1997 or 1998. You are completely right that they could see improvements, and we will be very happy to accept patches for, say adding `constexpr` to many of the member functions -- feel free to submit such patches.

In practice, it is often easier to review and merge small patches that address individual points, rather than one big patch that does it all.

**Comment by RichardYCJ** [comment]
Also found a subtle problem. The operator overload may not run as we expected. When using auto type deduction:

```cpp
constexpr Point<3> p{1., 2., 3.};
constexpr auto x = 2. * p;  // Tensor<1, 3, double>, invoke dealii::operator*
constexpr auto y = p * 2.;  // Point<3>, invoke Point<3>::operator*
```

From this perspective, do we really need `Point::operator+*/` overloaded in this context since the order matters.
Actually, they just do the same thing but return a more specific type, `operator-` can be preserved since it is order dependent.

**Comment by bangerth** [comment]
Yes, this looks like a mistake. `2*p` and `p*2` should return the same type. If it doesn't, that seems like a bug worth fixing. As before, patches are gladly accepted!
