### ISSUE TITLE
arb.h not found

### ISSUE THREAD

**Issue by IntrepidNomad** [dealii/dealii#16241]
I am getting the following error while building. Arch provides arb via flint, and I checked to ensure that arb.h exists in the include directory directory on my system. It is located at /usr/include/flint/arb.h. The package build for symengine contains commands for cmake to find arb.h in the flint directory. I am unsure precisely what changed recently to break this. I am using a beta version of suitesparse since the latest release was broken at time of build, but I don't know how it would connect with this issue.

```
[ 25%] Building CXX object source/base/CMakeFiles/object_base_debug.dir/unity_2.cc.o
In file included from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/include/deal.II/differentiation/sd/symengine_number_types.h:44,
                 from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/include/deal.II/differentiation/sd/symengine_math.h:23,
                 from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/include/deal.II/differentiation/sd.h:23,
                 from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/include/deal.II/base/symbolic_function.h:28,
                 from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/include/deal.II/base/symbolic_function.templates.h:21,
                 from /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/source/base/symbolic_function.cc:16,
                 from /home/intrepidnomad/AUR/deal-ii/src/build/source/base/unity_2.cc:17:
/usr/include/symengine/eval_arb.h:15:10: fatal error: arb.h: No such file or directory
   15 | #include <arb.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [source/base/CMakeFiles/object_base_debug.dir/build.make:104: source/base/CMakeFiles/object_base_debug.dir/unity_2.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2255: source/base/CMakeFiles/object_base_debug.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by IntrepidNomad** [comment]
Here is the relevant part of the configuration output for symengine.

`-- Include /home/intrepidnomad/AUR/deal-ii/src/dealii-9.5.1/cmake/configure/configure_50_symengine.cmake
CMake Deprecation Warning at /usr/lib/cmake/symengine/SymEngineConfig.cmake:34 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  cmake/modules/FindDEAL_II_SYMENGINE.cmake:38 (find_package)
  cmake/configure/configure_50_symengine.cmake:22 (find_package)
  /home/intrepidnomad/AUR/deal-ii/src/build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (feature_SYMENGINE_find_external)
  cmake/macros/macro_evaluate_expression.cmake:30 (include)
  cmake/macros/macro_configure_feature.cmake:239 (evaluate_expression)
  cmake/configure/configure_50_symengine.cmake:63 (configure_feature)
  cmake/macros/macro_verbose_include.cmake:19 (include)
  CMakeLists.txt:120 (verbose_include)


-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libtinfo.so  
-- Found zstd: /usr/lib/libzstd.so  
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.11.5") 
-- Found SYMENGINE_SETTINGS_H
-- Processing SYMENGINE variables and targets
-- Processing SYMENGINE variables and targets - Done
-- Configured with SymEngine LLVM capabilities.
-- 
-- Defining target: interface_symengine
--     VERSION:             0.11.1
--     LINK_LIBRARIES:      /usr/lib/libsymengine.so.0.11.1;/usr/lib/libLLVM-16.so;/usr/lib/libecm.so;/usr/lib/libprimesieve.so;/usr/lib/libflint.so;/usr/lib/libmpc.so;/usr/lib/libmpfr.so;/usr/lib/libgmp.so;/usr/lib/libtcmalloc.so
--     INCLUDE_DIRECTORIES: /usr/include
-- 
-- DEAL_II_WITH_SYMENGINE successfully set up with external dependencies.
`

**Comment by bangerth** [comment]
So the wrong `#include` command is in `/usr/include/symengine/eval_arb.h` where it appears to do
```
#include <arb.h>
```
where it should do
```
#include <flint/arb.h>
```
?

**Comment by drwells** [comment]
I think this is a bug in the way symengine is packaged on Arch Linux. Arch uses flint as a replacement for arb:
```
[drwells@archway ~]$ pacman -Qi flint                     
Name            : flint
Version         : 3.0.0-3
Description     : A C library for doing number theory
Architecture    : x86_64
URL             : http://www.flintlib.org
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : cblas  glibc  gmp  mpfr
Optional Deps   : None
Required By     : eclib  sagemath  singular  symengine
Optional For    : None
Conflicts With  : None
Replaces        : antic  arb
Installed Size  : 18.59 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Fri Oct 20 18:08:35 2023
Install Date    : Tue Oct 31 20:37:27 2023
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

At the same time `SymEngineConfig.cmake` doesn't add `/usr/include/flint/` to its list of include directories:

```
set(SYMENGINE_FLINT_LIBRARIES /usr/lib/libflint.so)
set(SYMENGINE_FLINT_INCLUDE_DIRS /usr/include)
set(HAVE_SYMENGINE_FLINT True)
set(SYMENGINE_ARB_LIBRARIES /usr/lib/libflint.so)
set(SYMENGINE_ARB_INCLUDE_DIRS /usr/include)
set(HAVE_SYMENGINE_ARB True)
```

Can you report this bug upstream?

**Comment by IntrepidNomad** [comment]
bug filed in arch bug reports here [symengine](https://bugs.archlinux.org/task/80206?project=1&string=symengine)
