### ISSUE TITLE
Error:  Symbol clash between the ADOL-C library and Trilinos' SEACASChaco

### ISSUE THREAD

**Issue by ajithperera** [dealii/dealii#16273]
Hello: I am trying to install deal-ii with candi installer (gcc/12.2.0 and openmpi/4.1.5) and running into an error

 --Found ADOLC_INCLUDE_DIR
-- Found ADOLC_LIBRARY
-- Found ADOLC_SETTINGS_H
-- Processing ADOLC variables and targets
-- Processing ADOLC variables and targets - Done
-- Could not find a sufficient ADOL-C installation: Possible symbol clash between the ADOL-C library and Trilinos' SEACASChaco detected
-- Performing Test ADOLC_DOUBLE_CAST_CHECK
-- Performing Test ADOLC_DOUBLE_CAST_CHECK - Success
-- Performing Test ADOLC_ADOUBLE_OSTREAM_CHECK
-- Performing Test ADOLC_ADOUBLE_OSTREAM_CHECK - Success
-- DEAL_II_WITH_ADOLC has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (message):

I installed adolc-2.7.2 (with candi). I do not think that error is necessarily deal-ii, but any suggestion to get around this error is very much appreciated.

Regards, Ajith
Univ. Florida

**Comment by masterleinad** [comment]
You should also get 
> If you want to use ADOL-C, please configure deal.II to use a Trilinos library with disabled SEACASChaco.

which is what you should do. Do you really need `ADOLC`? If not, I would just disable that instead.

**Comment by masterleinad** [comment]
In any case, this is more of a `candi` question than a `deal.II` question.

**Comment by ajithperera** [comment]
Thank you. I saw the additional messages, but I am installing the software
for our computer
center and do not know what the users need beforehand. I was thinking that
someone else
ran into the same issue. I gather that your feeling is that it the error is
from the build process.
I will do some reading and see whether I can find a workaround.

Thanks again, Ajith
