### ISSUE TITLE
Tests failing when compiling with "-Ofast -march=native"

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1628]
Roughly 18 tests do not like aggressive optimization [1].

[1] http://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12506

**Comment by kronbichler** [comment]
@tamiko should we do anything about this? I don't think there is much we can do here anyway (except for adding 'approved' result files).

BTW: When adding additional flags such as `-Ofast` or `-O3`, we currently only append it to the default setting `-O2`. I always feel uncomfortable when they both appear on the compile line. Even though `-Ofast` if you add it through `CMAKE_CXX_FLAGS_RELEASE` will come later and thus have prevalence.  Is there anything to be done here?

If your answer is no the both questions, please close this one.

**Comment by tamiko** [comment]
> [...]

I'm not very tempted anymore to fix this "problem" :-D

> When adding additional flags [...] Is there anything to be done here?

We could add some magic to net set up "-O*" flags if the saved flags (that will be appended at the end) do not already provide an override. Maybe we can fix a bit of an ambiguous behavior alongside:

Shall we also respect overrides in ```DEAL_II_CXX_FLAGS``` as well, i.e. not setting any release/debug specific optimization level because the user set an explicit general flag? More precisely how shall the following behave?

  - ```CXXFLAGS="-Ofast -march=native" cmake ...```
  - (or ```cmake DEAL_II_CXX_FLAGS="-Ofast -march=native" ...```)

**Comment by kronbichler** [comment]
If a user really sets '-Ofast' as CXX_FLAGS, I think he should get a '-Ofast' build also for the debug version. I guess that is most consistent. I realize that we use DEAL_II_CXX_FLAGS (_RELEASE) rather than the defaults in CMAKE_CXX_FLAGS (_RELEASE). I wonder if CMAKE has any built-in feature for that (or why we need to have a different name here; I stumbled over this a few times already).

**Comment by tamiko** [comment]
@kronbichler We should pick up ```CMAKE_CXX_*``` variables and translate them to ```DEAL_II_CXX_*``` at the beginning of the configuration run.

I will close this issue for now.
