### ISSUE TITLE
libpetsc.so.3.019 not found.

### ISSUE THREAD

**Issue by Jai-40** [dealii/dealii#16308]
The exeuctable got generated without error and while running step-5 and 15.  I am getting the following error.  ./step-5: error while loading shared libraries: libpetsc.so.3.019: cannot open shared object file: No such file or directory. How to resolve it.
Thanks.

**Comment by blaisb** [comment]
Could you give us more information about the platform you used to install Deal.II?
Did the cmake configuration of step-5 and step-15 throw any error?
