### ISSUE TITLE
Missing header file grid_reordering.h

### ISSUE THREAD

**Issue by AlexQuinlan** [dealii/dealii#16321]
It seems that grid_reordering.h has disappeared from /include/deal.II/grid/ .  The doxygen pages are still up and the corresponding '.cc' files are in /source/grid.  Is it possible that this was accidentally deleted?

**Comment by masterleinad** [comment]
Removed in https://github.com/dealii/dealii/commit/fd0c356263d7115ebf58fcea15d0412a32da199e since all classes had been deprecated for two releases.

**Comment by drwells** [comment]
You're right that they are still present in the doxygen pages since the ones under 'current' are for the current release of deal.II (9.5). However, they are not present on GitHub or under the 'Dev' section on the website since (as @masterleinad noted) they were removed after that release.

**Comment by bangerth** [comment]
Specifically, the pull request that removed this file is #15611. The functions in the `.h` file had been deprecated since #12082.
