### ISSUE TITLE
step-32 seems to assign vectors the wrong way around.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16333]
In investigating #16332 , I also found this piece of code:
```
    {
      TimerOutput::Scope timer_section(computing_timer,
                                       "   Assemble temperature rhs");

      old_time_step = time_step;

      const double scaling = (dim == 3 ? 0.25 : 1.0);
      time_step            = (scaling / (2.1 * dim * std::sqrt(1. * dim)) /
                   (parameters.temperature_degree * get_cfl_number()));

      const double maximal_velocity = get_maximal_velocity();
      pcout << "   Maximal velocity: "
            << maximal_velocity * EquationData::year_in_seconds * 100
            << " cm/year" << std::endl;
      pcout << "   "
            << "Time step: " << time_step / EquationData::year_in_seconds
            << " years" << std::endl;

      temperature_solution = old_temperature_solution;
```
This last assignment seems fishy to me: We should never be assigning the *old* temperature to the *current* solution vector. I have no idea what is going on here. We ought to investigate.

**Comment by tjhei** [comment]
I would think this is to set the initial guess for the linear solver. I checked and ``temperature_solution`` is not used in the assembly.

So, one could move this assignment right before the solve (around line 2915) or, even better, just use ``old_temperature_solution`` in the assignment:
https://github.com/dealii/dealii/blob/e7f6e8417c13ded9cf744a316cbeecdd1ce9fcf5/examples/step-32/step-32.cc#L2915

**Comment by kronbichler** [comment]
Yes, this is definitely to use as an initial guess (albeit not a very good one, it would get better by an extrapolation of more old solutions, or even a least squares fit). I agree with @tjhei in that we should make the assignment at the place where the system gets solved, to clearly indicate the purpose.
