### ISSUE TITLE
dealii fails to build against Trilinos with OpenMP=ON

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1634]
subj:

```
[ 70%] Building CXX object source/base/CMakeFiles/obj_base.release.dir/thread_management.cc.o
In file included from /home/davydden/.linuxbrew/include/KokkosCompat_View.hpp:58:0,
                 from /home/davydden/.linuxbrew/include/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:6,
                 from /home/davydden/.linuxbrew/include/Kokkos_DefaultNode.hpp:63,
                 from /home/davydden/.linuxbrew/include/MueLu_ConfigDefs.hpp:52,
                 from /home/davydden/.linuxbrew/include/MueLu.hpp:51,
                 from /home/davydden/Library/Temp/dealii20150918-21751-c9v0iv/source/lac/trilinos_precondition_muelu.cc:32:
/home/davydden/.linuxbrew/include/Kokkos_Core.hpp:179:65: error: 'memory_space' in 'Kokkos::DefaultExecutionSpace {aka class Kokkos::OpenMP}' does not name a type
 template< class Space = typename Kokkos::DefaultExecutionSpace::memory_space >
                                                                 ^
/home/davydden/.linuxbrew/include/Kokkos_Core.hpp:194:65: error: 'memory_space' in 'Kokkos::DefaultExecutionSpace {aka class Kokkos::OpenMP}' does not name a type
 template< class Space = typename Kokkos::DefaultExecutionSpace::memory_space >
                                                                 ^
/home/davydden/.linuxbrew/include/Kokkos_Core.hpp:207:65: error: 'memory_space' in 'Kokkos::DefaultExecutionSpace {aka class Kokkos::OpenMP}' does not name a type
 template< class Space = typename Kokkos::DefaultExecutionSpace::memory_space >
                                                                 ^
In file included from /home/davydden/.linuxbrew/include/Kokkos_DefaultNode.hpp:63:0,
                 from /home/davydden/.linuxbrew/include/MueLu_ConfigDefs.hpp:52,
                 from /home/davydden/.linuxbrew/include/MueLu.hpp:51,
                 from /home/davydden/Library/Temp/dealii20150918-21751-c9v0iv/source/lac/trilinos_precondition_muelu.cc:32:
/home/davydden/.linuxbrew/include/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:382:49: error: invalid use of incomplete type 'class Kokkos::OpenMP'
   typedef KokkosDeviceWrapperNode<Kokkos::OpenMP> KokkosOpenMPWrapperNode;
                                                 ^
```

of course, i am not sure if it's a correct way to build Trilinos with `-DTrilinos_ENABLE_OpenMP:BOOL=ON` and `-DTPL_ENABLE_MPI:BOOL=ON` at the same time, but it does compile.

**Comment by davydden** [comment]
it may also be the issue with trilinos not writing correct list of linker flags in output config file.

**Comment by bangerth** [comment]
Where is `Kokkos::OpenMP` declared? It looks to me more like a case of a missed `#include` somewhere (in Trilinos, that is, but visible when you try to use it).

**Comment by davydden** [comment]
it's declared in '/packages/kokkos/core/src/Kokkos_OpenMP.hpp` of source folder which got installed to `target/include/Kokkos_OpenMP.hpp`. 

Inside that `Kokkos_Core` there is
```
#if defined( KOKKOS_HAVE_OPENMP )
#include <Kokkos_OpenMP.hpp>
#endif
```
Strangely enough i don't have this error with `clang`.

**Comment by Rombur** [comment]
It could be a problem with the flags. For now, there is no point in compiling in compiling Trilinos with OpenMP because deal.II does not support the Tpetra interface.

Only ```clang-3.7``` supports OpenMP. Previous version will just ignore it.

**Comment by davydden** [comment]
I am not say there is a point of having trilinos with OpenMP :smile: , I am just saying that something is broken (likely in Trilinos) when one tries to compile deal.II.

**Comment by bangerth** [comment]
What happens if you explicitly do
```
  #include <Kokkos_OpenMP.hpp>
```
in `source/lac/trilinos_precondition_muelu.cc` just before you `#include` any of the other Trilinos headers? Does that fix the problem?

Of course, Trilinos should be doing this itself. This begs the question why Trilinos doesn't seem to `#define` the `KOKKOS_HAVE_OPENMP` flag.

**Comment by davydden** [comment]
trilinos is compiled, i can't add it to `.cc`. I tried adding `#include <Kokkos_OpenMP.hpp>` to `MueLu_ConfigDefs.hpp` but no luck...

**Comment by davydden** [comment]
i will try including it in `Kokkos_Core.hpp` irrespectively of the `#define`...

**Comment by davydden** [comment]
It's trilinos issue as this can be fixed by hacking:
```
1) add #include <Kokkos_OpenMP.hpp> to Kokkos_OpenMP.hpp
2) comment out #if defined (KoKKOS_HAVE_OPENMP ) && defiened (_OPENMP ) in Kokkos_OpenMP.hpp and the closing #endif
```

**Comment by bangerth** [comment]
You should file a bug report with the Trilinos people then.

**Comment by davydden** [comment]
Did that already
