### ISSUE TITLE
Merge triangulation duplicate_vertex_tolerance

### ISSUE THREAD

**Issue by vinayakvijay** [dealii/dealii#16356]
This is somewhat related to #16326. In [GridGenerator::merge_triangulations](https://www.dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#ae6b11dc96dd9165e25495f74def3655d), the argument duplicated_vertex_tolerance is used to merge the vertices, that are too close, according to the user-specified value. However, for the use case when one wants to merge triangulations having overlapping vertices (only differentiated by the floating point error) **and** wants to keep the duplication, specifying duplicated_vertex_tolerance criteria by the user becomes difficult and unnecessary. (Note: In #16326 the triangulations were separated intentionally to facilitate merging with duplicated vertices)

Currently, there are two work-arounds to this problem:

1. Specify duplicated_vertex_tolerance to be very small. For eg. 1e-1000. But this may not be robust because we'll eventually be comparing floating point numbers that are very close to each other.
2. Initially move the triangulations away from each other by a _specified-translation_ -> merge them -> move each vertex back by (-)_specified-translation_  but this becomes computationally expensive very quickly.

I think it could be useful to have the option to turn on duplicating vertices for such cases without having the user specify any tolerance whatsoever.

**Comment by masterleinad** [comment]
The documentation states that 
> [...]  If the tolerance is set to zero, vertices are not merged.

and we check that internally.

**Comment by vinayakvijay** [comment]
Perfect! I missed it completely. Apologies!
