### ISSUE TITLE
Boost: special functions are unavailable on ppc64el

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#16390]
See [1]:
```
/usr/include/boost/math/tools/promotion.hpp:267:27: error: static assertion failed: Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.
```

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059349

**Comment by tamiko** [comment]
```
In file included from /usr/include/boost/math/special_functions/detail/round_fwd.hpp:12,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:29,
                 from /usr/include/boost/math/special_functions/legendre.hpp:16,
                 from /<<PKGBUILDDIR>>/include/deal.II/base/std_cxx17/cmath.h:32,
                 from /<<PKGBUILDDIR>>/source/base/function_lib.cc:20:
```

Judging from `cmath.h` the easiest course of action would be to simply override `DEAL_II_HAVE_CXX17_BESSEL_FUNCTIONS` and `DEAL_II_HAVE_CXX17_LEGENDRE_FUNCTIONS` to true and live with the fact that the functions are unavailable on ppc64el.

Opinions?

**Comment by bangerth** [comment]
We don't actually need the `long double` overload. The only place where we use the `legendre` function is in `fe_series_legendre.cc` where we use it with a `double` argument. The right approach might be to just remove the non-C++17 `legendrel()` function in our own `cmath.h`. I would be greatly surprised if anyone used it.

**Comment by bangerth** [comment]
Separately, though -- in the current dev sources, we're using C++17. How come we fall back to the BOOST versions? Is this with a compiler that doesn't have these implemented, even though they claim to support C++17?

**Comment by masterleinad** [comment]
https://en.cppreference.com/w/cpp/17 shows that support for mathematical special functions is pretty limited.
You either need
- libstdc++ >= 7, or
- MSVC STL >= 19.14 (VS 2017)

E.g., libc++ hasn't implement them yet.

**Comment by tamiko** [comment]
Roger. Let's just remove the long double overloads. I'll also prepare a patch for 9.5.1 and update the debian package.
