### ISSUE TITLE
Parpack test failures if WITH_ARPACK=ON, but parpack is disabled

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1640]
@davydden Have a look at [1]. Can you add a guard around the whole test program that justs outputs the expected result if ```DEAL_II_ARPACK_WITH_PARPACK``` is not defined?

[1] http://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12606

**Comment by davydden** [comment]
should there not be something like `with_parpack=on` in the test filename?

**Comment by tamiko** [comment]
No, there is no such thing as ```with_parpack=on```. This is only available if parpack would have its own ```DEAL_II_WITH_PARPACK``` variable.

**Comment by davydden** [comment]
i see. Will fix it...
