### ISSUE TITLE
Trilinos sparsity pattern: end iterator raises assertion for some locally owned rows

### ISSUE THREAD

**Issue by swiesheier** [dealii/dealii#16414]
[Iterator_TrilinosSparsityPattern.cc.tar.gz](https://github.com/dealii/dealii/files/13835583/Iterator_TrilinosSparsityPattern.cc.tar.gz)

Attached is an example (~30 lines of code) where the assertion 
https://github.com/dealii/dealii/blob/c03f51671b0d04ede557bf9a0a1a893c470d5150/source/lac/trilinos_sparse_matrix.cc#L183
is raised. I run this program with two MPI processes -- processor 0 owns the DoFs 0-74, while processor 1 owns the DoFs 75-125. In total, there are 125 DoFs.
In this specific example, the assertion is triggered by processor 0 when calling `auto itend = sparsityPattern.end(74)`, which calls 
https://github.com/dealii/dealii/blob/c03f51671b0d04ede557bf9a0a1a893c470d5150/source/lac/trilinos_sparse_matrix.cc#L142
with row 75, hence, raising the assertion, as row 75 is not locally owned on processor 0. 

I reported this bug also on the mailing list [here](https://groups.google.com/g/dealii/c/GezJk9KOhHg?hl=en)

**Comment by bangerth** [comment]
For reference, I bet that the same problem exists with the sparse matrix iterators, see also the changes made in #16416.

**Comment by peterrum** [comment]
I have fixed the issue in #16420 by copying the logic from the sparse matrix :+1:
