### ISSUE TITLE
Indent script messes up permissions.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16427]
#16419 results in mayhem on my system because it changes the permissions of the source directory to 644 -- which is bad for a directory, because you can't access that directory any more and everything that's running inside it seriously freaks out.

@drwells FYI

**Comment by peterrum** [comment]
@bangerth Could you check https://github.com/dealii/dealii/pull/16428? Thanks!

**Comment by bangerth** [comment]
The issue, at its core, rests here:
```
process_changed()
{
  LAST_MERGE_COMMIT="$(git log --format="%H" --merges --max-count=1 master)"
  COMMON_ANCESTOR_WITH_MASTER="$(git merge-base "${LAST_MERGE_COMMIT}" HEAD)"

  case "${OSTYPE}" in
    darwin*)
      XARGS="xargs -E"
      ;;
    *)
      XARGS="xargs --no-run-if-empty -d"
      ;;
  esac

  ( git ls-files --others --exclude-standard -- ${1};
    git diff --name-only $COMMON_ANCESTOR_WITH_MASTER -- ${1} )|      # **1
      sort -u |
      xargs -n 1 ls -d 2>/dev/null |
      grep -E "^${2}$" |
      ${XARGS} '\n' -P 10 -I {} bash -c "${3} {}"
}
```
If no file is changed, but you call the indent script anyway, the command at `# **1` returns an empty list, which sort leaves as an empty list, but then `xargs` returns just `.` (the current directory) because `echo | xargs -n 1 ls -d 2>/dev/null` returns `.`. We then execute the `chmod` on this directory.

**Comment by bangerth** [comment]
We really shouldn't be passing "*" as second argument of `process_changed`.

**Comment by drwells** [comment]
Whoops. I definitely missed that line in the original PR. My mistake!
