### ISSUE TITLE
investigate Trilinos_ENABLE_EXPLICIT_INSTANTIATION

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1643]
see https://trilinos.org/pipermail/trilinos-users/2015-September/005146.html

This might avoid the problem with long compile times and high memory usage when compiling the muelu preconditioner.

**Comment by davydden** [comment]
unfortunately:
```
/tmp/trilinos20150923-73149-1af8slz/trilinos-12.2.1-Source/packages/amesos2/src/Amesos2_Superludist.cpp:111:5: error: duplicate explicit instantiation of 'Superludist<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false>, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>, false> >'
    AMESOS2_SUPERLUDIST_LOCAL_INSTANT(double, int, int, NODETYPE)
    ^
/tmp/trilinos20150923-73149-1af8slz/trilinos-12.2.1-Source/packages/amesos2/src/Amesos2_Superludist.cpp:92:27: note: expanded from macro 'AMESOS2_SUPERLUDIST_LOCAL_INSTANT'
  template class Amesos2::Superludist<Tpetra::CrsMatrix<S, LO, GO, N>,      \
                          ^
/tmp/trilinos20150923-73149-1af8slz/trilinos-12.2.1-Source/packages/amesos2/src/Amesos2_Superludist.cpp:67:30: note: previous explicit instantiation is here
  AMESOS2_SOLVER_TPETRA_INST(Superludist,double,int,int);
                             ^
/tmp/trilinos20150923-73149-1af8slz/trilinos-12.2.1-Source/packages/amesos2/src/Amesos2_ExplicitInstantiationHelpers.hpp:58:18: note: expanded from macro 'AMESOS2_SOLVER_TPETRA_INST'
  template class SOLVERNAME<Tpetra::CrsMatrix<S, LO, GO>, Tpetra::MultiVector<S, LO, GO> >
                 ^
```

**Comment by Rombur** [comment]
Not many people need amesos2 with superlu_dist. Personally, I always turn on the explicit instantiation. I only had a problem once and it was with an experimental package.

**Comment by davydden** [comment]
i do like to have an extra option of the direct solver. Especially when you do hp.

**Comment by Rombur** [comment]
But you don't need amesos2 for that. You can do it through amesos and that worked last time I tried (~6 months ago).

**Comment by davydden** [comment]
i stand corrected, apparently i also used `Amesos_Superludist` for solver, so no Amesos2.

**Comment by kronbichler** [comment]
I can also only support using the EXPLICIT_INSTANTIATION mechanism. I have used it many times and they seem to work pretty well (I don't know if Amesos2 improved on the issue reported by @davydden but I would hope so since this is an issue inside Trilinos). What is left to do for this one? Should we recommend it in the build options in `doc/external-libs/trilinos.html`?

**Comment by tjhei** [comment]
Did you try that it reduces memory usage when compiling deal.II?

**Comment by kronbichler** [comment]
Yes, for me it does. The muelu file compiles in 4 minutes and several GB of RAM without it and in less than 10 seconds and <0.7GB with it included.

**Comment by tjhei** [comment]
okay! see #2538
