### ISSUE TITLE
regression: cross_product(Tensor&, Tensor)

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1644]
Due to the recent tensor changes the function
```
void cross_product (Tensor<1,2> &dst,
               const Tensor<1,2> &src);
```
no longer exists breaking applications (like ASPECT). The problem is that the code compiles, but the compiler now picks up
```
Tensor<1,dim> cross_product (const Tensor<1,dim> &src1,
               const Tensor<1,dim> &src2);
```
which fails with an Assert at runtime (dim==3).

Matthias, do you have a suggestion on how we can work around this?

**Comment by tjhei** [comment]
My suggestion would be to call the new functions ```cross``` and leave the old functions there as ```cross_product```.

**Comment by tamiko** [comment]
@tjhei Yes, and I clearly stated this change in #1608.

Before introducing yet another name, I just revert.

**Comment by bangerth** [comment]
How about changing the assertion to point to theIncompatible change?

**Comment by bangerth** [comment]
There's also the wedge product function somewhere.

**Comment by tamiko** [comment]
@bangerth ? I do not see a wedge product (or an alternative form) in the library. Do you mean to rename the ```cross_product``` to ```wedge_product```? If yes, no - this would be a huge misnomer.

**Comment by tjhei** [comment]
> Before introducing yet another name, I just revert.

I think there is value in having a function that returns a cross product. Why don't you simply rename the new functions to avoid confusion?

**Comment by tamiko** [comment]
> Why don't you simply rename the new functions to avoid confusion?

Because then we would have scalar_product, outer_product and "cross". :-/

**Comment by tjhei** [comment]
Args, okay.

**Comment by bangerth** [comment]
On 09/21/2015 10:49 AM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth> ? I do not see a wedge product (or an
> alternative form) in the library. Do you mean to rename the |cross_product| to
> |wedge_product|? If yes, no - this would be a huge misnomer.

The function was called `GeometryInfo::alternating_form_at_vertices`, but upon 
looking up what it does, it really has a different purpose.

**Comment by tjhei** [comment]
Another thought I had is that ```Tensor cross_product(Tensor, Tensor)``` only makes sense in 3d while ```Tensor cross_product(Tensor)``` only makes sense in 2d, so we could add the 2d/3d to the name of the new function.

**Comment by tjhei** [comment]
While not ideal, it actually makes code using the cross product more readable (the 2d cross product is somewhat special anyways):
```
           if ( dim == 2)
             return cross_product_2d(p);
           else
             return cross_product_3d(axis, p);
```

**Comment by bangerth** [comment]
I like this suggestion.

**Comment by tamiko** [comment]
@tjhei I like it. I'll refactor. Pull request incoming (tomorrow).
