### ISSUE TITLE
Audit and fix missing codimension-one instantiations

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#16493]
We have a number of missing codimension-one instantiations throughout the codebase.

On Linux platforms this is typically hidden because the compiler/linker happily exports whatever symbol it created implicitly. This is not the case on Mac OS X where the toolchain (even though it is clang based) is much more conservative in emitting symbols for implicitly instantiated code. This means that while everything is compiling fine on Linux it fails miserably on Mac [1].

[1] Working around these issues is particularly frustrating because (a) deal.II is typically installed with the Mac bundle, which makes recompiling deal.II harder for the average user; (b) by the fact that we tend to have affected template definitions in *.cc files instead of easily accessible *.templates.h files.

**Comment by bangerth** [comment]
Do you have an idea how such an audit could be performed, short of looking at individual functions by hand?

**Comment by tamiko** [comment]
@bangerth I do not :-( I am currently looking through gcc and clang documentation about symbol visibility and linker plugins. Let's see whether I do uncover something helpful.

For the time being I will resort to trying to compile a specific application of a collague that makes heavy use of codimension-one and afterwards try to grab an M2 Mac from a student or a colleague to do a full testsuite run.
