### ISSUE TITLE
Physics::Elasticity::Kinematics::w uses wrong type?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16517]
We have this function:
```
template <int dim, typename Number>
inline Tensor<2, dim, Number>
Physics::Elasticity::Kinematics::w(const Tensor<2, dim, Number> &F,
                                   const Tensor<2, dim, Number> &dF_dt)
{
  // This could be implemented as w = l-d, but that would mean computing "l"
  // a second time.
  const Tensor<2, dim> grad_v = l(F, dF_dt);
  return internal::NumberType<Number>::value(0.5) *
         (grad_v - transpose(grad_v));
}
```
I *think* that the type of `grad_v` should actually be `Tensor<2,dim,Number>`, rather than `Tensor<2,dim>`. The `l` function returns the former, which must then be implicitly converted to the latter (this is what causes our troubles with #16506 and #16511). I also think that the type is wrong because we cannot currently differentiate through if `Number` is an AD type.

@jppelteret FYI

**Comment by tamiko** [comment]
@bangerth Yes, I am looking at this at the moment as well and I think this is wrong. What about we switch to an `auto`?

**Comment by bangerth** [comment]
Thou shallst open github issue so that others shall fix them for you!
