### ISSUE TITLE
MappingQ1 throws floating point exception for point outside of cell

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#1652]
I am experiencing floating point exceptions in the recent development version of deal.II within MappingQ1:transform_real_to_unit_cell() that have not shown in 8.2 (last version I checked). The exception is triggered for some (but not all) points that lie outside of a cell. In my application I know that I will test (many) points that lie outside of a cell, but I only catch exceptions of type ExcTransformationFailed, that is why I noticed the floating point exception.

More precisely, the exception is triggered in line 124 of source/fe/mapping_q1.cc, because (-b + sqrt(discriminant)) is equal to zero. The special cases above this `else` should catch such situations, but I think it is not working for my case because of a round-off error. Let me explain by an example:

For the following values none of the special cases gets triggered (these are not values of an actual point, but the one that triggered the exception are very close, I rounded them for readability):
b = 1e-4
c = 1e-7
a = 1e-18

But still, due to round-off error (at least here on my machine):

sqrt(discriminant) = sqrt(b*b - 4*a*c) == b,
which results in a division-by-zero.

Should there be another special case for this? Or am I missing something and such cases should not happen at all, and I need to look for the reason why I get to this situation?

**Comment by drwells** [comment]
Hmm, I see the problem (I am the original author of this function): I think this code needs to be made a bit more robust (it should either check if the determinant is zero or use the trick with two different quadratic formulas). Could you help me by sending me whatever torture cases you have (i.e., did you use a particular Triangulation to generate those values)?

**Comment by gassmoeller** [comment]
The case itself is relatively simple, it is just hard to put it into a deal.II only test code, because I use it via aspect. In essence the test uses a Q1 mapping with a parallel::distributed::Triangulation (but only run on one process, so should also happen for a serial case) for a subdivided hyper rectangle in 2D with 7 global refinements, and then I create random points and check, if they lie in a certain cell by mapping their position and checking if they lie within the unit cell. I think it should be possible to simplify it just to a single cell and then create thousands of random points around it. I can try to set something up tomorrow (it is way too late here in Europe).

**Comment by gassmoeller** [comment]
The following test should fail in debug mode (and create undefined behaviour in release mode):

https://gist.github.com/gassmoeller/34a0ec1a074f4cff77fc

It was harder than I expected, because the problem does not show for a coarse Triangulation, and also not for a hyper cube, but only for a hyper rectangle, which gets refined several times (I could not provoke the problem with refinements < 5). It seems like the refinements are causing some small vertex displacements due to rounding errors, which cause `a` to be very small, but non-zero.

**Comment by gassmoeller** [comment]
Fixed by #1669
