### ISSUE TITLE
Create DEAL_II_UNREACHABLE

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16536]
The discussion in https://github.com/dealii/dealii/pull/16457#pullrequestreview-1840400637 points out that all of the places where we have
```
  Assert (false, ExcABC());
```
are troublesome if we expose this to the compiler also in release mode. But these places all have in common that they indicate that the place we're in is really unreachable -- or if we happen to get there, something terrible must have happened. I think we should express this in the error message somehow, which suggests something like a
```
  DEAL_II_UNREACHABLE(ExcABC());
```
which in debug mode produces a good error message, and in release mode translates to a call to `std::unreachable()`.

**Comment by bangerth** [comment]
To wit:
```
> grep -r 'Assert(false,' include/ source/ examples/ | wc -l
1461
```

**Comment by tamiko** [comment]
Wouldn't it actually be much better to replace most of those `Assert(false, ...)` in release mode with something like `__builtin_trap()`?

I mean sure, replacing such an assert by a `std::unreachable()` would optimize away the last comparison in a switch statement...

But simply stopping the program in case we encounter such a condition sounds like a much safer option.
At least from a quick glance,
 - most of the `Assert(false, ...)` statements are in places that can actually be reached (particularly the tried and true `Assert(false, ExcNotImplemented());`)
 - are the last `default:` statement in a switch statement (or a similar `if` `else` construct) and that switch statement is not performance critical.

**Comment by bangerth** [comment]
Yes, I think any kind of trap is preferable to what we currently have, namely just continue running in release mode.
