### ISSUE TITLE
Modules page disappears in online doc

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16535]
As pointed out on the mailing list by Chengjiang Yin:

> I notice that the modules page has disappeared from the recent online documentation for a while and the module tab on the top bar is also missing. Does this on purpose or by mistake? The second level pages (like Mapping, Matrix Free) are still available.

Indeed, the current developer documentation at https://www.dealii.org/developer/doxygen/deal.II/ does not have the "Modules" tab, whereas the documentation of the last release at https://www.dealii.org/current/doxygen/deal.II/ does. 

I will note that the modules themselves still exist, for example at https://www.dealii.org/developer/doxygen/deal.II/group__vector__valued.html

@tamiko Do you see an error in your build logs? The dev pages use a newer doxygen (1.9.8) than the last release (1.9.7). Perhaps that is a reason?

**Comment by tamiko** [comment]
@bangerth The modules tab seems to have disappeared with our current configuration with doxygen 1.9.8 onwards. (reproduced with 1.10.* as well).

**Comment by bangerth** [comment]
Related: https://github.com/doxygen/doxygen/issues/10562, https://stackoverflow.com/questions/77416946/after-doxygen-update-modules-in-tree-view-disapeared.

In short, I believe that the underlying issue is that doxygen implemented support for C++20 modules, and so renamed the tab "Topics". Alas, that doesn't show up for us.

**Comment by bangerth** [comment]
I have a patch.
