### ISSUE TITLE
operator* overloads in <deal.II/base/sacado_product_type.h> broken

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1656]
As reported by Mauro on the mailing list. In reference to #1631 

A simple multiplication now leads to a segmentation fault:
```
#include <deal.II/base/sacado_product_type.h>
int main()
{
  Sacado::Fad::DFad<double> b;
  b * b;
}
```

**Comment by tamiko** [comment]
I would suggest to just scrap those ```operator*``` overloads completely. Sacado builds up a full expression syntax. Above ```b * b``` has for example the type
```
Sacado::Fad::Expr<Sacado::Fad::MultiplicationOp<Sacado::Fad::DFad<double>,
      Sacado::Fad::DFad<double> >, Sacado::Fad::ExprSpecDefault>
```

This for example implies that it is not a good idea to ```static_cast``` a left/right operand of a multiplication to its final type.

**Comment by tamiko** [comment]
Further, ```DFad``` already absorbs every other scalar type. So the following product type specializations should be enough - no need to overload ```operator*```:

```
template <typename T, typename U>                                                  
struct ProductType<Sacado::Fad::DFad<T>, typename EnableIfScalar<U>::type>         
{                                                                                  
  // DFad absorbs every scalar type                                                
  typedef Sacado::Fad::DFad<T> type;                                               
};                                                                                 
                                                                                   
template <typename T, typename U>                                                  
struct ProductType<typename EnableIfScalar<U>::type, Sacado::Fad::DFad<T>>         
{                                                                                  
  // DFad absorbs every scalar type                                                
  typedef Sacado::Fad::DFad<T> type;                                               
};                                                                                 
                                                                                   
template <typename T1, typename T2>                                                
struct ProductType<Sacado::Fad::DFad<T1>, Sacado::Fad::DFad<T2>>                   
{                                                                                  
  typedef Sacado::Fad::DFad<typename ProductType<T1, T2>::type> type;              
};  
```

**Comment by tamiko** [comment]
@asartori86 Can you please test that everything still works for you if you replace the contents of ```sacado_product_type.h``` with just the includes and above overloads?

If not, what exactly does not work?

**Comment by tamiko** [comment]
Ah, ****. Non-deducable type overloads. We go with:
```
template <typename T>
struct ProductType<Sacado::Fad::DFad<T>, double>
{
  // DFad absorbs every scalar type
  typedef Sacado::Fad::DFad<T> type;                                               
};                                                                                 

template <typename T>                                                  
struct ProductType<double, Sacado::Fad::DFad<T> >
{
  // DFad absorbs every scalar type
  typedef Sacado::Fad::DFad<T> type;                                               
};                                                                                 

template <typename T1, typename T2>                                                
struct ProductType<Sacado::Fad::DFad<T1>, Sacado::Fad::DFad<T2>>                   
{                                                                                  
  typedef Sacado::Fad::DFad<typename ProductType<T1, T2>::type> type;              
};  
```

**Comment by bangerth** [comment]
I agree that in hindsight, defining `operator*` for Sacado types is probably a bad idea. This is something the Sacado people need to define in a way that makes sense for their internal data structures.

**Comment by asartori86** [comment]
@tamiko, I wrote the overloads of `operator*` in order to satisfy the assert
```
AssertThrow (typeid(typename ProductType<T,U>::type) == typeid(T() * U()),
              ExcInternalError());
```

taken from the other tests on product_type.

**Comment by bangerth** [comment]
But then something is wrong about the fundamental approach. Conceptually, `ProductType<T,U>::type` should exactly be the type you get by forming the product `t*u` where `t` and `u` are variables of type `T,U`. If these types don't match, then you've encoded the wrong knowledge in `ProductType<T,U>::type`.

(In fact, in C++11, we define `ProductType<T,U>::type` exactly as `decltype(T()*U())`. In C++98 we don't have `decltype`, so we have to do it by hand, but the types that are defined should still be the same. If your assertion doesn't satisfy this property, then `ProductType<T,U>::type` is not correctly defined.)

**Comment by asartori86** [comment]
To do so, I guess we should go deeply inside the mechanism of sacado. As @tamiko  reported, the "simple" multiplication of two `Sacado::Fad::DFad<double>` returns 
```
Sacado::Fad::Expr<Sacado::Fad::MultiplicationOp<Sacado::Fad::DFad<double>,
      Sacado::Fad::DFad<double> >, Sacado::Fad::ExprSpecDefault>
```

**Comment by tamiko** [comment]
```
AssertThrow (typeid(typename ProductType<T,U>::type) == typeid(T() * U()),
              ExcInternalError());
```

This very assertion is not correct for Sacado types. The result of ```typeid(T()*U())``` is above expression monster. it is convertible to a ```DFad``` type.

@bangerth Those ```ProductType``` rules I have posted work around the issue that ```typeid(T()*U())``` [1] gives a expression syntax result that is not default constructible. Instead, the class ```DFad<T>``` is meant as the fronted class wrapper to use (it has a default constructor) - this is how I understood Sacado's documentation.

Now, there are two possibilities to fix that:
 - Go through all headers and fix all occurrences of

 ```
[ResultType] result();
...
return result;
```
And do so <b>by not making icc unhappy</b> as we learnt (i.e., not possible without writing a lot of boilerplate code).

 - Explicitly instantiate ```ProductType``` to use the frontend wrapper class

I originally suggested the latter approach to Mauro.


There is a fundamental ambiguity in ```ProductType```, namely:
 - shall it return the result of ```operator*```
 - shall it return the type in which we want to store  the rsult of ```operator*```

We use it with the latter interpretation in mind, but advertise it as the former.

[1] Further, do not expect ```typeid(T()*U())``` to work at all. It fails for a number of gcc versions if ```T``` or ```U``` are not default constructible. It should read ```decltype(std::declval<T>() * std::declval<U>())``` instead.

**Comment by bangerth** [comment]
> @bangerth <https://github.com/bangerth> Those |ProductType| rules I have
> posted work around the issue that |typeid(T()*U())| [1] gives a
> expression syntax result that is not default constructible.

Yes, the standard trick I guess is to use
  typeid ( (*(T*)0) * (*(U*)0) )
instead. (Hard to read, but doesn't require default constructible types; 
C++11 has declval<T>() for this, as you noted below.)


 > Instead, the
> class |DFad<T>| is meant as the fronted class wrapper to use (it has a
> default constructor) - this is how I understood Sacado's documentation.

OK, that sounds sensible.


> There is a fundamental ambiguity in |ProductType|, namely:
>
>   * shall it return the result of |operator*|
>   * shall it return the type in which we want to store the rsult of
>     |operator*|
>
> We use it with the latter interpretation in mind, but advertise it as
> the former.

Good point. The latter is what we want indeed.

**Comment by asartori86** [comment]
Sorry for my ignorance, but it is not clear to me what should I do.. If I correctly understood, the front end class `DFad` is the one that we used.
