### ISSUE TITLE
Regression tester: make failsafe less aggressive

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#16561]
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting an unclean regression run compared to the baseline.
- revision: 1b2b368784da419f4112105234d525c4daef28f1  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=1b2b36)

Summary:
- :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-10](https://cdash.dealii.org/build/1133) on site tester-tng
- :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-11](https://cdash.dealii.org/build/1132) on site tester-tng
- :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/1138) on site tester-tng
- :disappointed: build warnings for configuration [GNU-12.2.0-master-ubuntu-23.04](https://cdash.dealii.org/build/1137) on site tester-tng
- :disappointed: build warnings for configuration [GNU-12.3.0-master-debian-13](https://cdash.dealii.org/build/1139) on site tester-tng
- :disappointed: build warnings for configuration [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/build/1140) on site tester-tos
- :disappointed: build warnings for configuration [GNU-13.1.1-master-64bit_indices-20230507](https://cdash.dealii.org/build/1152) on site tester-tos
- :disappointed: build warnings for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/1135) on site tester-tos
- :disappointed: build warnings for configuration [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/build/1151) on site tester-tos
- :disappointed: build warnings for configuration [GNU-13.1.1-master-std=c++20-20230626](https://cdash.dealii.org/build/1143) on site tester-tos

Previous 5 testsuite runs:
- old revision: 1b2b368784da419f4112105234d525c4daef28f1  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=1b2b36)
- old revision: 1b2b368784da419f4112105234d525c4daef28f1  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=1b2b36)
- old revision: 1b2b368784da419f4112105234d525c4daef28f1  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=1b2b36)
- old revision: d6fcd98fac90352e7c0a614e0952246ea14d5785  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=d6fcd9)
- old revision: 2d482b27ea664466d818f3de4961415f6e0f9507  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=2d482b)

Last 5 regression test reports:
- #16557
- #16538
- #16508
- #16511
- #16507

Notes:
 - I have opened this issue because I encountered an unclean regression run compared to the baseline, but
 - I was unable to identify a regression between the **current** run and the **previous** run of the regression testsuite. This is likely due to one of the following two reasons:
   - The previous testsuite run is incomplete and I thus cannot infer that the regressions occurred between the current and previous run.
   - The previous testsuite run had configure or build failures for a configuration, and the current testsuite run shows configure, build warnings, or failing tests.
     In this case I cannot infer when those failures have been introduced exactly and resort to opening a less specific issue.
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.

[end automated regression testsuite report]

**Comment by bangerth** [comment]
This seems to be the same as #16557?

**Comment by tamiko** [comment]
@bangerth Correct.

Currently, I have configured two triggers:
 - regular trigger: if a new regression testsuite run is worse than a previous one (meaning new build warnings or failures are encountered) then the bot constructs an issue with the typical comparison and candidate list of pull requests.
 - failsafe: if it encounters an unclean testsuite run that (a) is not worse than the previous one, and (b) all regression tester bugs it opens a generic bug report (this one).

I originally added the failsafe so that we get an issue if a regression occurs while the testsuite is (partially) offline.

What I didn't factor in when writing this logic is that github aggressively closes issues whenever you write something like
"This should fix https://github.com/dealii/dealii/issues/16557". 

I will make the failsafe more strict by requiring an *incomplete* previous run.

**Comment by tamiko** [comment]
I have changed the trigger.
