### ISSUE TITLE
CMake: bundled directory included when bundled muparser is selected

### ISSUE THREAD

**Issue by jodlbauer** [dealii/dealii#16605]
It seems that the `include/deal.II/bundled` folder is not installed if no bundled library is used during configuration of deal.II.
However, the cmake `dealii::dealii_debug/release` targets still include this directory unconditionally.
I have currently fixed it by just creating that folder in the install directory and leave it empty.

Possible solutions:
- install `bundled` even if it is empty
- check if the directory exists before adding it to `dealii::dealii_debug`

(Related to https://groups.google.com/g/dealii/c/l1tWck3YnHs)

**Comment by tamiko** [comment]
@jodlbauer What CMake version are you running? And on what platform?

**Comment by jodlbauer** [comment]
cmake version is 3.28.1
I just realized my deal.II version is only 9.5.1, I thought I built the main branch. I'm rebuilding deal.II now to see if it makes a difference, but it may take a while.

**Comment by jodlbauer** [comment]
I retried with the master branch on an Almalinux 8.9 with cmake 3.26.4, but the same problem persists.
Interestingly, building deal.II uses the bundled muparser, but the headers do not get installed.

**Comment by drwells** [comment]
muParser is a special case - we decided that our function parsing code should not export its dependency on muParser, so we never install the headers and the symbols (when we use the bundled version) are hidden in our own namespace. That corner-case might be causing this problem.

**Comment by tamiko** [comment]
Yup.

In file `macros/macro_populate_target_properties.cmake`:
```
   85     foreach(_include ${DEAL_II_BUNDLED_INCLUDE_DIRS})                            
   86       list(APPEND _includes $<BUILD_INTERFACE:${_include}>)                      
   87     endforeach()                                                                 
   88     if(NOT "${DEAL_II_BUNDLED_INCLUDE_DIRS}" STREQUAL "")                        
   89       list(APPEND _includes "$<INSTALL_INTERFACE:${DEAL_II_INCLUDE_RELDIR}/deal.II/bundled>")
   90     endif() 
```
