### ISSUE TITLE
Compilation fails on `ReadWriteVector` with Kokkos complex datatypes

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#16678]
I am trying to build deal.II and Trilinos with clang 13.0.0 (aocc 3.2.0). Trilinos 15.0.0 was configured with `ENABLE_FLOAT=ON` and `ENABLE_COMPLEX=ON` and successfully compiled with said compiler.

Compiling deal.II with `DEAL_II_WITH_COMPLEX_VALUES=ON` yields errors of the following kind:
```
In file included from /dealii/source/lac/read_write_vector.cc:17:
/dealii/include/deal.II/lac/read_write_vector.templates.h:601:23: error: no viable overloaded '+='
            values[i] += new_values(i);
            ~~~~~~~~~ ^  ~~~~~~~~~~~~~
/dealii/include/deal.II/lac/read_write_vector.templates.h:825:5: note: in instantiation of function template specialization 'dealii::LinearAlgebra::ReadWriteVector<std::complex<float>>::import_elements<std::complex<float>>' requested here
    import_elements(trilinos_vec.trilinos_vector(),
    ^
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/complex:1132:7: note: candidate function not viable: no known conversion from 'const Kokkos::complex<float>' to 'float' for 1st argument
      operator+=(float __f)
      ^
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/complex:1174:9: note: candidate template ignored: could not match 'std::complex' against 'Kokkos::complex'
        operator+=(const complex<_Tp>& __z)
        ^
```

There are some additional errors of similar kind. The note I get consistently is `could not match 'std::complex' against 'Kokkos::complex'`.

Can you reproduce it?

**Comment by Rombur** [comment]
`std::complex` does not exist in CUDA instead they use `cuComplex` that's why `Kokkos::complex` (https://kokkos.org/kokkos-core-wiki/API/core/utilities/complex.html) was introduced.  I am guessing that Trilinos is using `Kokkos::complex` while we are using `std::complex`. We may need to cast the `Kokkos::complex` to a `std::complex` ourselves.
