### ISSUE TITLE
Help needed: hooking in the code gallery

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1668]
This is in relation to #1314 -- I'm trying to write the glue code that when we generate the documentation also creates documentation for all of the code gallery projects.

What I've found so far is that I can make cmake clone the code gallery into our build directory. To this end, I now have this command in `doc/doxygen/CMakeLists.txt`:
```
# Then check out a copy of the Code Gallery and see which of the
# directory therein contain directories we care about
#
# For reasons not quite clear to me, the command by itself
# clones the git repository, but if a clone already exists, it
# does not update it to the HEAD of the remote repository. We
# need to do this by hand using the UPDATE_COMMAND command.
ExternalProject_Add(code-gallery
  GIT_REPOSITORY https://github.com/bangerth/code-gallery.git
  UPDATE_COMMAND git pull origin master
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/code-gallery
)
```

After the addition ot the `UPDATE_COMMAND` part, this actually does what I wanted it to. I then set out collecting the code gallery subdirectories that actually contain programs we'd like to process:
```
FILE(GLOB _dirs
  ${CMAKE_CURRENT_BINARY_DIR}/code-gallery/src/code-gallery/*)
FOREACH(_dir ${_dirs})
  IF(IS_DIRECTORY ${_dir}
     AND
     EXISTS ${_dir}/doc/author)
    MESSAGE(STATUS "--- processing ${_dir}")
  ENDIF()
ENDFOREACH()
```
My intention was to do this in the same way as we process tutorials and then also pass them through to the targets that generate input for doxygen.

The problem with this is that the `EXTERNAL_PROJECT_ADD` command only does the clone operation at run time, and so I cannot already collect directories here and consequently don't know further down the road which targets to create for our scripts to process that then feed into doxygen input.

How does one do things like this?

**Comment by bangerth** [comment]
@tamiko ?

**Comment by bangerth** [comment]
I discovered `EXECUTE_COMMAND` to solve this problem.

**Comment by tamiko** [comment]
Wolfgang, I haven't answered yet because I was very busy lately.

I do not like external downloads (or git fetch), or any such calls to be part of the build system.

What about we use git submodules instead?

We can for example just recursively check out the code callery via git submodules and let the documentation pick those bits up if present. (This is also in line with our current philosophy of optional ```doc``` or ```bundled``` directories).

**Comment by tamiko** [comment]
There are several reasons why I want to refrain from downloading something during build - the most important one is that this is in fact considered an issue for packaging and our build system will need patching to fit privacy rules of distributions and build environments (e.g., network sandboxing).

**Comment by bangerth** [comment]
Hm. I think I have something that mostly works but that I didn't get to completely test last night. I have meetings this morning, but let me put forward a strawman patch this afternoon so we have something concrete to discuss.
