### ISSUE TITLE
Add ConditionalOStream status change after initialization

### ISSUE THREAD

**Issue by RichardYCJ** [dealii/dealii#16725]
We can not define a static `TimerOutput` variable and let it only print once. Since the status of `ConditionalOStream` can only be setup after `MPI_Init` in the main function and we have no interface to control the `ConditionalOStream` inside the timer at that time.

Therefore, we may also setup the ConditionalOStream status at `enable/disable_output`?

**Comment by bangerth** [comment]
@RichardYCJ I'm not sure I completely understand the question. Why can't you initialize the object with `std::cout` and a `true` condition, and later call `ConditionalOStream::set_condition()` to determine whether you really want to output anything?

**Comment by RichardYCJ** [comment]
Because the `out_stream` member within `TimerOutput` cannot be accessed after initialization. And if you use `ConditionalOStream pcout` to initialize `TimerOutput`, it calls the copy ctor and depends on the status input pcout, which can only be truly decided after MPI_Init.

Thus the static TimerOutput can only be all active or all inactive.

**Comment by bangerth** [comment]
Perhaps it would be easier if you showed your code and explain what you would like to do with it but can't?

**Comment by RichardYCJ** [comment]
If you run this with multiple processes, it will output multiple times even you call `disable_output` and setup the `pcout` condition.
```cpp
#include <deal.II/base/timer.h>
#include <iostream>

using namespace dealii;

static ConditionalOStream pcout{std::cout};
static TimerOutput timer{pcout, TimerOutput::never, TimerOutput::wall_times};
static TimerOutput timer_comm{
    MPI_COMM_WORLD, pcout, TimerOutput::never, TimerOutput::wall_times};

int main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_init(argc, argv, 1);
  pcout.set_condition(Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0);
  timer.print_wall_time_statistics(MPI_COMM_WORLD);

  if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) != 0) timer_comm.disable_output();
  timer_comm.print_summary();
}
```
The problem here is you can not control the timer's `out_stream` after init.

**Comment by bangerth** [comment]
In your example, which of the two objects prints output from all processes? I recognize that `timer` prints output from all processes because you only change `pcout`, but not the copy stored in `timer`. But `timer_comm` should only output from process 0, no?

**Comment by RichardYCJ** [comment]
> I recognize that `timer` prints output from all processes because you only change `pcout`, but not the copy stored in `timer`
That's the problem, we have no interface to change the timer's `out_stream`!

> But timer_comm should only output from process 0, no?
No it still have multiple output, because the `out_stream` is a copy and we can not change its status, `print_summary` does not check `output_is_enabled`

**Comment by RichardYCJ** [comment]
The current workaround is to use dirty ptr offset, this would trigger compiler warning and also the offset is different from different system layout.
```cpp
bool is_output_rank = Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0;
static_cast<ConditionalOStream *>(static_cast<void *>(&timer_comm) + std::ptrdiff_t{208})->set_condition(is_output_rank);
```

**Comment by RichardYCJ** [comment]
> > I recognize that `timer` prints output from all processes because you only change `pcout`, but not the copy stored in `timer`
> 
> That's the problem, we have no interface to change the timer's `out_stream`!
> 
> > But timer_comm should only output from process 0, no?
> 
> No they all have multiple output, because the `out_stream` is a copy and we can not change its status, `print_summary` does not check `output_is_enabled`

Hi @bangerth, does this make sense to you? The point is that `out_stream` is an independent `ConditionalOStream` and we can't control it after init.

**Comment by bangerth** [comment]
Yes, this is clearly not the solution :-)

I think I understand your problem now.
