### ISSUE TITLE
get appveyor for windows build testing to work

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1681]
appveyor.com has free hosting of windows CI builds for open source projects. I have been playing with this by setting up a repo https://bitbucket.org/tjhei/dealii/src with one new file https://bitbucket.org/tjhei/dealii/src/4815546d08a6cc3bc220613b3099ddda228bad3e/appveyor.yml?at=appveyor&fileviewer=file-view-default
You can see the output at https://ci.appveyor.com/project/tjhei/dealii-9v5eu
- Which versions of VS do we want to target (2015 will need adjustments to our build system I think)?
- BUILD_SHARED_LIBS ON/OFF or both?
- To set up continuous integration appveyor wants admin access to our deal.II organization - do we trust them enough to do this? (that is why I used bitbucket for testing so far)
- other thoughts?

**Comment by bangerth** [comment]
I'd say lets target the latest MS VC release given that historically their compilers were so terrible.

What do they need in terms of admin access (and to what kind of platform)? Is this necessary so that they can start builds automatically based on external triggers?

**Comment by tjhei** [comment]
> What do they need in terms of admin access
Permission to access github.com/dealii organization. I assume to trigger automatic builds and maybe set the status (similar to what we do in ASPECT). There should be a setting to stop it from doing pull requests.

"AppVeyor CI by @appveyor would like permission to access your account:
1. This application will have full access to repository webhooks and services (no direct code access).
2. This application will be able to read and write commit statuses (no direct code access).
3. This application will be able to read your organization and team membership."

If we don't want this we can still trigger builds manually (and get email notifications).

**Comment by tjhei** [comment]
> I'd say lets target the latest MS VC release given that historically their compilers were so terrible.

2015 doesn't seem to work, but 2013 does. Until we figure this out, we can just do both. See https://ci.appveyor.com/project/tjhei/dealii-9v5eu/build/1.0.15

**Comment by bangerth** [comment]
I don't think I understand *what account* it needs access to. On a machine under your or my control? To the github account?

**Comment by tamiko** [comment]
@tjhei What about we trigger builds manually (maybe with a cronjob) and focus on getting
```
ctest -S [...]/tests/run_buildtest.cmake
```
to work?

This way the result would also be part of our cdash instance and not handled separately.

**Comment by tjhei** [comment]
> I don't think I understand what account it needs access to. On a machine under your or my control? To the github account?

They want access to the github organization with the name dealii. I posted the blurb what they can do if I click "ok" above (they can not change our source code for example). This has nothing to do with a machine. Also see https://help.github.com/articles/connecting-with-third-party-applications/

**Comment by tjhei** [comment]
> What about we trigger builds manually

We could do that if we don't trust them (I don't think that is a problem). The easiest way is to use bitbucket and just regularly push the current master.

>  focus on getting ctest to work?

What is the current status?

**Comment by bangerth** [comment]
I don't know anything about appveyor, but if you believe that they can be trusted with our github account, then I'm ok with that as well.

My preference would be to go with @tamiko 's plan so we can have it all in one place.

**Comment by tamiko** [comment]
@tjhei I just checked the script: The first parts of a build test should just run fine (configure, build and submit results), the 108 build tests might bail out. Can you just give it a try?

**Comment by tjhei** [comment]
I did 
```
ctest -DCTEST_CMAKE_GENERATOR="Visual Studio 12 2013" -V -S ../tests/run_buildtest.cmake
 ```
and I am now getting
```
-- Running setup_tests 
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.
 
MSBUILD : error MSB1009: Project file does not exist.
Switch: setup_tests.vcxproj
CMake Error at C:/projects/dealii/tests/run_testsuite.cmake:488 (MESSAGE):
  
 
  "setup_tests" target exited with an error.  Bailing out.
```
see https://ci.appveyor.com/project/tjhei/dealii-9v5eu/build/1.0.22

Thoughts?

**Comment by tjhei** [comment]
I think this needs to be ```msbuild /target:setup_tests <project_file>```

**Comment by tjhei** [comment]
@tamiko anything I can try?

**Comment by tamiko** [comment]
On Fri, Oct  2, 2015, at 17:38 CDT, Timo Heister <notifications@github.com> wrote:

> @tamiko anything I can try?

You can remove the "setup_tests" call from run_testsuite.cmake to test
whether submission works.

Have agreed on any alternative syntax for ">=" etc. in output files?

**Comment by tjhei** [comment]
> You can remove the "setup_tests" call from run_testsuite.cmake to test whether submission works.

Looks better, submission worked: http://cdash.kyomu.43-1.org/buildSummary.php?buildid=13228

One problem I still see is
```
-- Running CTEST_SUBMIT() 
	Add file: C:/projects/dealii/build/revision.log
	Add file: C:/projects/dealii/build/summary.log
	Add file: C:/projects/dealii/build/detailed.log
	Add file: C:/projects/dealii/build/include/deal.II/base/config.h
Submit files (using http)
   Send to track: Build Tests
   Using HTTP submit method
   Drop site:http://cdash.kyomu.43-1.org/submit.php?project=deal.II
   Uploaded: C:/projects/dealii/build/Testing/20151003-1430/Build.xml
   Uploaded: C:/projects/dealii/build/Testing/20151003-1430/Configure.xml
   Uploaded: C:/projects/dealii/build/Testing/20151003-1430/Notes.xml
   Uploaded: C:/projects/dealii/build/Testing/20151003-1430/Test.xml
   Uploaded: C:/projects/dealii/build/Testing/20151003-1430/Update.xml
   Submission successful
-- Submission successful. Goodbye! 
Error in read script: C:/projects/dealii/tests/run_buildtest.cmake
Command exited with code -1
```
see https://ci.appveyor.com/project/tjhei/dealii-9v5eu/build/1.0.23

> Have agreed on any alternative syntax for ">=" etc. in output files?

My vote is for ```.ge.``` etc. Do you want me to try to hack this in?

**Comment by tamiko** [comment]
> Do you want me to try to hack this in?

Would be nice. This should be a self-contained change in ```macro_deal_ii_pickup_tests.cmake```:
The regular expressions in lines 171 and 174 ("." has to be escaped)
The string comparision ind lines 214 - 223.

**Comment by luca-heltai** [comment]
Could we also export the built libraries as artifacts in appveyor for master merges? This would allow us to distribute to Windows users also a prebuilt binary with the latest version of deal.II.

**Comment by drwells** [comment]
Is there anything else to do here now that we have the artifacts exported via appveyor? If not we should close.
