### ISSUE TITLE
test with > in their name

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1687]
It turns out git under windows doesn't like "<" or ">" in filenames:
```
git clone -q --depth=10 --branch=master https://github.com/dealii/dealii.git .
error: Invalid path 'tests/trilinos/precondition_muelu_dgp.with_trilinos>=11.14.with_64bit_indices=off.output'
error: Invalid path 'tests/trilinos/precondition_muelu_q_iso_q1.with_trilinos>=11.14.with_64bit_indices=off.output'
error: Invalid path 'tests/trilinos/precondition_muelu_smoother.with_trilinos>=11.14.with_64bit_indices=off.output'
```

Can we replace <,>,>=,<= with different characters? Maybe something like ".le.", ".ge.", ".leq.", ".geq."?

**Comment by tamiko** [comment]
I cannot find nice words to express my opinion on this matter.

**Comment by bangerth** [comment]
Is it really true that under windows this doesn't work, or does this simply indicate that these filenames are not adequately escaped where they are used? Can you give an example?

**Comment by agrayver** [comment]
Yes, these are reserved characters. 

see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions

**Comment by bangerth** [comment]
Bummer. What about using a pattern such as
```
  abc.with-trilinos=11.2.0.output            // =11.2.0
  abc.with-trilinos=11.2.0+.output          // >=11.2.0
```
This would easily allow encoding `=` and `>=` operations. I suspect that we probably don't need anything else.

**Comment by tjhei** [comment]
We would also need the negation of >= I think.

**Comment by bangerth** [comment]
I don't think so, at least if you provide an ordering so that the most specific (matching) output file is always chosen. For example, if you had
```
  abc.with-trilinos=true.output                // any version
  abc.with-trilinos=11.0.0+.output          // >=11.0.0
  abc.with-trilinos=11.2.0+.output          // >=11.2.0
```
Then if you had 11.1, it would match the first two, but the second one is *more specific* than the first and so it is chosen. Similarly, if you had Trilinos 12, then all three match but the last is more specific, so it should be chosen.

**Comment by tamiko** [comment]
> Can we replace <,>,>=,<= with different characters? Maybe something like ".le.", ".ge.", ".leq.", ".geq."?

We should probably go with that because it is the least intrusive "fix":
```
.with_trilinos.ge.12.7.4.
```

looks better than
```
.with_trilinos=ge.12.7.4.
.with_trilinos_ge.12.7.4.
.with_trilinos_g=.12.7.4.
.with_trilinos&gt;=12.7.4.
```
...

> I don't think so, at least if you provide an ordering so that the most specific (matching) output file is always chosen.

This is not about matching output files. :-) In fact, we agreed on
```
abc.output
abc.output.2
abc.output.3
```

for this situation.

**Comment by bangerth** [comment]
Oh yes. But so in what situations do you require the `<=` operator then?

**Comment by tjhei** [comment]
> Oh yes. But so in what situations do you require the <= operator then?

A library adds a feature (say MueLu in Trilinos ) then we need ">=X", library removes a feature (say Epetra in Trilinos version 17) and we need "<X".
