### ISSUE TITLE
`LinearAlgebra::EpetraWrappers::Vector` has no operator[]()

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#16877]
The `LinearAlgebra::EpetraWrappers::Vector` class has no member function `operator[]()`.

This limits using the class as a template parameter in structures and functions which require that a `VectorType` needs to be accessed via the bracket operator[].

For example, we cannot explicitly instantiate the `SolutionTransfer` class with `LinearAlgebra::EpetraWrappers::Vector`. See also https://github.com/dealii/dealii/pull/15706#discussion_r1523598990.

**Comment by bangerth** [comment]
I don't think we have such a list. In fact, this is the first time I heard that we have this issue, so it doesn't seem to be too widespread.
