### ISSUE TITLE
Collecting linear algebra operator header files

### ISSUE THREAD

**Issue by koecher** [dealii/dealii#1689]
@tamiko 
Regarding to the discussion on the maillist:
https://groups.google.com/forum/?hl=en#!topic/dealii/NKCI8sEe8Eo

> A remedy - at least for the inclusion files - would be to have a special 
> header file that just includes all relevant stuff (linear_operator.h, 
> package_operation.h, block_linear_operator.h). 
> 
> Do you have a nice name for such a header file? Suggestions and/or 
> pull-request are highly welcomed! 

What about "deal.II/lac/linear_algebra_expression.h" to collect all of these?
Do I simply have to put the include statements for above given header files,
or is there some more work to do in the first place?

**Comment by psiehr** [comment]
Hey, 
I just ran into the same problem as on the maillist, when I updated the deal.ii dev version.
In the old version everything worked fine, but I needed the block_linear_operator.h
The error thrown is not really helpful:
error: no match for ‘operator*’ (operand types are ‘const dealii::LinearOperator<dealii::Vector<double>, dealii::Vector<double> >’ and ‘dealii::Vector<double>’)
   Vector<double> v1=op_identity*a;


Is there a reason not to include "package_operation.h" directly in "linear_operator.h"  ? 
And in the same way include "linear_operator.h" in "block_linear_operator.h" ?

Then you only have to include one of these two h-files, depending on your needs.

Best 
Philipp

**Comment by koecher** [comment]
I think @tamiko wanted to keep both files as independent as possible. I'll set up a PR with my appoach tomorrow.

**Comment by davydden** [comment]
i think this is fixed in https://github.com/dealii/dealii/pull/2505. Please reopen if needed.

**Comment by davydden** [comment]
i think this is fixed in https://github.com/dealii/dealii/pull/2505
