### ISSUE TITLE
Changing Data types in Deal.ii examples

### ISSUE THREAD

**Issue by AjaySingh40** [dealii/dealii#16893]
Hello all,
I am trying to benchmark the wave equation step-23 with different data types. By default it uses double . I tried changing double to float in all the routines which uses templates but it gives error. Does changing data type is supported in deal.ii? if yes how can we do it, for example in step-23?
Thank You.

**Comment by masterleinad** [comment]
What do the errors you are seeing look like?

**Comment by AjaySingh40** [comment]
error: no matching function for call to ‘project(dealii::DoFHandler<2, 2>&, dealii::AffineConstraints<float>&, dealii::QGauss<2>, Step23::InitialValuesU<2>, dealii::Vector<float>&)’
  438 |     VectorTools::project(dof_handler,
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
  439 |                          constraints,
      |                          ~~~~~~~~~~~~
  440 |                          QGauss<dim>(fe.degree + 1),
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  441 |                          InitialValuesU<dim>(),
      |                          ~~~~~~~~~~~~~~~~~~~~~~
  442 |                          old_solution_u);
dealii-9.5.2/examples/step-23/step-23.cc:564:51: note:   ‘std::map<unsigned int, float>’ is not derived from ‘dealii::AffineConstraints<number>’
  564 |           VectorTools::interpolate_boundary_values(dof_handler,
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
  565 |                                                    0,
      |                                                    ~~
  566 |                                                    boundary_values_v_function,
      |                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  567 |                                                    boundary_values);
      |                                                    ~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/step-23.dir/build.make:76: CMakeFiles/step-23.dir/step-23.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/step-23.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by AjaySingh40** [comment]
When data type is changed the functions called are not matching . It may be the case that  function definition are not generic which accept all data types.

**Comment by masterleinad** [comment]
The value type for `InitialValuesU` is still the default (which is `double`) and so the call to `VectorTools::project` fails. You'll have to derive from `Function<dim, float>` instead.

**Comment by AjaySingh40** [comment]
Tried changing it but it's not working ,
changed Function<dim> to Function<dim, float> and return type of virtual functions  from double to float.
dealii-9.5.2/examples/step-23/step-23.cc:175:19: error: conflicting return type specified for ‘float Step23::InitialValuesV<dim>::value(const dealii::Point<dim>&, unsigned int) const [with int dim = 2]’
  175 |     virtual float value(const Point<dim> & /*p*/,

error: no matching function for call to ‘project(dealii::DoFHandler<2, 2>&, dealii::AffineConstraints<float>&, dealii::QGauss<2>, Step23::InitialValuesV<2>, dealii::Vector<float>&)’
  443 |     VectorTools::project(dof_handler,
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
  444 |                          constraints,
      |                          ~~~~~~~~~~~~
  445 |                          QGauss<dim>(fe.degree + 1),
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  446 |                          InitialValuesV<dim>(),
      |                          ~~~~~~~~~~~~~~~~~~~~~~
  447 |                          old_solution_v);
      |                          ~~~~~~~~~~~~~~~

**Comment by masterleinad** [comment]
It compiles for me with
```diff
diff --git a/examples/step-23/step-23.cc b/examples/step-23/step-23.cc
index c4e6a2d775..47d98a885a 100644
--- a/examples/step-23/step-23.cc
+++ b/examples/step-23/step-23.cc
@@ -72,7 +72,7 @@
 // result padded with leading zeros. We will use this to write output files
 // that have the form <code>solution-XXX.vtu</code> where <code>XXX</code>
 // denotes the number of the time step and always consists of three digits
-// even if we are still in the single or double digit time steps.
+// even if we are still in the single or float digit time steps.
 #include <deal.II/base/utilities.h>
 
 // The last step is as in all previous programs:
@@ -120,22 +120,22 @@ namespace Step23
     FE_Q<dim>          fe;
     DoFHandler<dim>    dof_handler;
 
-    AffineConstraints<double> constraints;
+    AffineConstraints<float> constraints;
 
     SparsityPattern      sparsity_pattern;
-    SparseMatrix<double> mass_matrix;
-    SparseMatrix<double> laplace_matrix;
-    SparseMatrix<double> matrix_u;
-    SparseMatrix<double> matrix_v;
+    SparseMatrix<float> mass_matrix;
+    SparseMatrix<float> laplace_matrix;
+    SparseMatrix<float> matrix_u;
+    SparseMatrix<float> matrix_v;
 
-    Vector<double> solution_u, solution_v;
-    Vector<double> old_solution_u, old_solution_v;
-    Vector<double> system_rhs;
+    Vector<float> solution_u, solution_v;
+    Vector<float> old_solution_u, old_solution_v;
+    Vector<float> system_rhs;
 
-    double       time_step;
-    double       time;
+    float       time_step;
+    float       time;
     unsigned int timestep_number;
-    const double theta;
+    const float theta;
   };
 
 
@@ -152,10 +152,10 @@ namespace Step23
   // Let's start with initial values and choose zero for both the value $u$ as
   // well as its time derivative, the velocity $v$:
   template <int dim>
-  class InitialValuesU : public Function<dim>
+  class InitialValuesU : public Function<dim, float>
   {
   public:
-    virtual double value(const Point<dim> & /*p*/,
+    virtual float value(const Point<dim> & /*p*/,
                          const unsigned int component = 0) const override
     {
       (void)component;
@@ -167,10 +167,10 @@ namespace Step23
 
 
   template <int dim>
-  class InitialValuesV : public Function<dim>
+  class InitialValuesV : public Function<dim, float>
   {
   public:
-    virtual double value(const Point<dim> & /*p*/,
+    virtual float value(const Point<dim> & /*p*/,
                          const unsigned int component = 0) const override
     {
       (void)component;
@@ -184,10 +184,10 @@ namespace Step23
   // Secondly, we have the right hand side forcing term. Boring as we are, we
   // choose zero here as well:
   template <int dim>
-  class RightHandSide : public Function<dim>
+  class RightHandSide : public Function<dim, float>
   {
   public:
-    virtual double value(const Point<dim> & /*p*/,
+    virtual float value(const Point<dim> & /*p*/,
                          const unsigned int component = 0) const override
     {
       (void)component;
@@ -201,10 +201,10 @@ namespace Step23
   // Finally, we have boundary values for $u$ and $v$. They are as described
   // in the introduction, one being the time derivative of the other:
   template <int dim>
-  class BoundaryValuesU : public Function<dim>
+  class BoundaryValuesU : public Function<dim, float>
   {
   public:
-    virtual double value(const Point<dim>  &p,
+    virtual float value(const Point<dim>  &p,
                          const unsigned int component = 0) const override
     {
       (void)component;
@@ -221,10 +221,10 @@ namespace Step23
 
 
   template <int dim>
-  class BoundaryValuesV : public Function<dim>
+  class BoundaryValuesV : public Function<dim, float>
   {
   public:
-    virtual double value(const Point<dim>  &p,
+    virtual float value(const Point<dim>  &p,
                          const unsigned int component = 0) const override
     {
       (void)component;
@@ -361,7 +361,7 @@ namespace Step23
   void WaveEquation<dim>::solve_u()
   {
     SolverControl            solver_control(1000, 1e-8 * system_rhs.l2_norm());
-    SolverCG<Vector<double>> cg(solver_control);
+    SolverCG<Vector<float>> cg(solver_control);
 
     cg.solve(matrix_u, solution_u, system_rhs, PreconditionIdentity());
 
@@ -375,7 +375,7 @@ namespace Step23
   void WaveEquation<dim>::solve_v()
   {
     SolverControl            solver_control(1000, 1e-8 * system_rhs.l2_norm());
-    SolverCG<Vector<double>> cg(solver_control);
+    SolverCG<Vector<float>> cg(solver_control);
 
     cg.solve(matrix_v, solution_v, system_rhs, PreconditionIdentity());
 
@@ -466,8 +466,8 @@ namespace Step23
     // we almost always work on a single time step at a time, and where it
     // never happens that, for example, one would like to evaluate a
     // space-time function for all times at any given spatial location.
-    Vector<double> tmp(solution_u.size());
-    Vector<double> forcing_terms(solution_u.size());
+    Vector<float> tmp(solution_u.size());
+    Vector<float> forcing_terms(solution_u.size());
 
     for (; time <= 5; time += time_step, ++timestep_number)
       {
@@ -512,7 +512,7 @@ namespace Step23
           BoundaryValuesU<dim> boundary_values_u_function;
           boundary_values_u_function.set_time(time);
 
-          std::map<types::global_dof_index, double> boundary_values;
+          std::map<types::global_dof_index, float> boundary_values;
           VectorTools::interpolate_boundary_values(dof_handler,
                                                    0,
                                                    boundary_values_u_function,
@@ -558,7 +558,7 @@ namespace Step23
           BoundaryValuesV<dim> boundary_values_v_function;
           boundary_values_v_function.set_time(time);
 
-          std::map<types::global_dof_index, double> boundary_values;
+          std::map<types::global_dof_index, float> boundary_values;
           VectorTools::interpolate_boundary_values(dof_handler,
                                                    0,
                                                    boundary_values_v_function,
```
that is blindly replacing `double` with `float` and changes `Function<dim>` to `Function<dim, float>`.
