### ISSUE TITLE
Use "mesh" instead of "grid" in step-1.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16938]
In various places in the documentation, we explain that "triangulation" = "mesh". In step-1, we use a third term, namely "grid" when outputting data into files and in screen messages. I suspect that this is due to the naming of `namespace GridGenerator`, but it is nonetheless unfortunate to use yet another term.

My vote would be to rename output files to `mesh-1/2.svg` and adjust the screen message accordingly. Opinions?

**Comment by tjhei** [comment]
There are several places where we use grid like GridOut, GridIn, GridGenerator so I don't think it is problematic to talk about grids. Do they have a different meaning for you?

**Comment by bangerth** [comment]
No, same meaning. Just slightly confusing that we'd use different words for the same thing.
