### ISSUE TITLE
Mention triangles/tets somewhere early on in the tutorials.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#16944]
The usual sequence of tutorials only uses quads. But we could mention triangles and tets already in step-1, for example in the "Possibilities for extensions" where we suggest things to change. We can also show triangular meshes there, so that people also have a visual impression of things. Perhaps mention them again in step-4 (also in the possibilities for extensions). In both cases, the changes to the actual program would be minimal, and easily mentioned in a few lines.

**Comment by peterrum** [comment]
We should make the codes in https://github.com/dealii/dealii/pull/11581 to tutorials!

**Comment by blaisb** [comment]
I second that. We should make #11581 into tutorials. I think it's a good idea.

**Comment by kronbichler** [comment]
I agree that presenting a program ready-to-use with simplices would be great. But I think the original request of @bangerth at https://github.com/dealii/dealii/pull/11581#pullrequestreview-625564689 has not lost its validity: How do we deal with the code duplication, both in terms of teaching perspective and in terms of maintenance? I guess this would be an ideal case for some of these modern website content concepts, where all elements remain the same except for the 10 or 15 lines that actually need to be changed. I realize we are not having any such infrastructure yet, but I would strongly argue for reason about what options we have for combining the variants without giving the user two separate web pages with almost the same code, and with focus on the relevant changes.

**Comment by blaisb** [comment]
@kronbichler Has a great idea. For sure it would be much more interesting to present step3 and the difference that arise when switching to simplices. A similar thing could eventually be to make a parallel version of step-6 and displaying the changes that arise. However, I am unsure how we could do this with the current web architecture. In all cases, I think it's better to temporarily have code duplication and strive for something better in the long term than to not show these features. In my opinion, features for which we do not have examples do not seem to exist in the eyes of most of our users and I understand them. Searching through Doxygen for a feature is a difficult endeavour.
