### ISSUE TITLE
Blocked on mailing list?

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#16962]
I replied to a question on the mailing list yesterday. I can see that the mail is sent, but does not seem to have reached anyone and it does not appear in [google groups](https://groups.google.com/g/dealii).

Is there a block on replying due to the recent spam? If so, how does one get unblocket?

**Comment by Rombur** [comment]
I just checked and there is nothing blocking you from sending a message on the mailing list. Maybe try again.

**Comment by simonsticko** [comment]
Weird. I resent the email 5 minutes ago, by replying to dealii@googlegroups.com, but still can not see it in the google group. Did you get an email on the list @Rombur ?

**Comment by Rombur** [comment]
No, there is nothing. Are you using a new email address?

**Comment by simonsticko** [comment]
No. I sent it from simonsticko@gmail.com, I have used it on the mailing list before.

**Comment by Rombur** [comment]
It's very strange. You are allowed to post from this email address. Try posting from the web-interface, maybe you'll get some kind of error message. I am not sure what else to do.

**Comment by simonsticko** [comment]
>Try posting from the web-interface

 I tried this and I can see that it worked. But it's a bit worrying that the emails just disappear. It's not a problem for me if I know that I should use the web interface. But if someone else has the same problem they might not notice if their email disappears.

**Comment by Rombur** [comment]
yes, hopefully it's just a temporary issue on Google side.

**Comment by Rombur** [comment]
It seems that google flagged your emails as potential spams. I am going to approved them both even though they are duplicate, so hopefully your messages are not considered as spam in the future.

**Comment by simonsticko** [comment]
Okey, thanks. I'm closing this then.

**Comment by tjhei** [comment]
The mailing list contains some moderation for posts that are potentially spam (I see two short messages by you that were flagged) and for new users (We had a lot of annoying spam so we had to enable it).
This means one of the mailing list admins needs to approve these messages manually.
