### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EKiranKumar** [dealii/dealii#1697]
In documentation about functions it is telling about that function usage but there is no information about accessibility of this program lines in the library so it is making lot of difficult in finding how it is actually implemented so tell us how to find program lines of function in library

**Comment by bangerth** [comment]
I don't think I quite understand the question. Can you point out a concrete page and location therein and what it is you are missing there?

**Comment by EKiranKumar** [comment]
for example when telling about what hypercube like function is doing  is given in documentation but how it is implemented that is  program code lines of function in library where it is written about its location of program code line is not given in documentation

**Comment by bangerth** [comment]
Can you provide a link to an example?

**Comment by EKiranKumar** [comment]
just go to search and type hyper_cube GridGenerator

**Comment by drwells** [comment]
@EKiranKumar I think I understand what you are looking for. This is definitely an issue with the current release (8.3). We added links to the source in #1356, and you can see them if you look in the development version (8.4) manual. For example,

https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#acea0cbcd68e52ce8113d1134b87de403

*does* contain a link to the underlying source implementation.

**Comment by EKiranKumar** [comment]
From when onwards version 8.4 will be available

**Comment by bangerth** [comment]
We don't know yet. Maybe in several months. But you can of course use the online documentation already that has the links you are looking for.

**Comment by EKiranKumar** [comment]
Now it would be helpful you atleast release documentation containing links upto functions using in tutorial step-3 which completes the basic steps

**Comment by tjhei** [comment]
We have the documentation online for the current development version which also includes the tutorial steps. See https://www.dealii.org/developer/doxygen/deal.II/step_3.html

I hope to have a release at the end of this year. Thanks for your feedback.

**Comment by EKiranKumar** [comment]
Thank you for all your responses
