### ISSUE TITLE
Linking against SUNDIALS 7.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#17037]
#16879 helped compile deal.II with SUNDIALS 7. Unfortunately, this was not enough to ensure compatibility.

Linking executables of user applications, tutorial examples or even tests against deal.II then fails with the following undefined references.
```
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNContext_Create'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNContext_Free'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNLinSolNewEmpty'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNMatNewEmpty'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNMatDestroy'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNLinSolFree'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'N_VNewEmpty'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'N_VCopyOps'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'N_VDestroy'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'N_VFreeEmpty'
[...]/dealii-9.6.0-pre/lib/libdeal_II.g.so.9.6.0-pre: error: undefined reference to 'SUNLinSolFreeEmpty'
collect2: error: ld returned 1 exit status
```

In the linking command in my user code I spot
```
[...]/sundials-7.0.0/lib
[...]/sundials-7.0.0/lib/libsundials_idas.so 
[...]/sundials-7.0.0/lib/libsundials_arkode.so
[...]/sundials-7.0.0/lib/libsundials_kinsol.so
[...]/sundials-7.0.0/lib/libsundials_nvecserial.so 
[...]/sundials-7.0.0/lib/libsundials_nvecparallel.so
```

The sundials folder contains more object files than that. Maybe that's the issue?
```
$ find [...]/sundials-7.0.0/lib -name "*.so"
./libsundials_arkode.so
./libsundials_nvecparallel.so
./libsundials_ida.so
./libsundials_sunnonlinsolfixedpoint.so
./libsundials_sunlinsolspfgmr.so
./libsundials_sunnonlinsolnewton.so
./libsundials_kinsol.so
./libsundials_cvode.so
./libsundials_nvecserial.so
./libsundials_sunlinsolpcg.so
./libsundials_sunmatrixdense.so
./libsundials_sunlinsolsptfqmr.so
./libsundials_sunlinsolspbcgs.so
./libsundials_sunmatrixband.so
./libsundials_sunlinsolspgmr.so
./libsundials_sunmatrixsparse.so
./libsundials_cvodes.so
./libsundials_core.so
./libsundials_sunlinsolband.so
./libsundials_sunlinsoldense.so
./libsundials_nvecmanyvector.so
./libsundials_idas.so
./libsundials_nvecmpiplusx.so
./libsundials_nvecmpimanyvector.so
```

Do you have an idea how to get around this? I didn't find anything related to linking in the changelog.

**Comment by marcfehling** [comment]
> In the linking command in my user code I spot [...]

In [`FindDEAL_II_SUNDIALS.cmake`](https://github.com/dealii/dealii/blob/8604e85ebc1e0292e4ee18a06ce04c720334cb1c/cmake/modules/FindDEAL_II_SUNDIALS.cmake) we specifically look for these object files. I believe we need to adjust this for version 7.0.0, while being backwards compatible.

**Comment by masterleinad** [comment]
https://sundials.readthedocs.io/en/latest/kinsol/Introduction_link.html#changes-from-previous-versions mentions that we have to link against `sundials_core` as well. We could also just use the `CMake` target, though.

**Comment by bangerth** [comment]
Good grief, why don't people just put everything into a single shared library? That would be so much faster loading too...

**Comment by masterleinad** [comment]
> Good grief, why don't people just put everything into a single shared library? That would be so much faster loading too...

Well, we can just use the `CMake` target. 🙂
