### ISSUE TITLE
Erroneous export of `bundled/` as an include path even if we don't install anything bundled.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17087]
This stumped me for a bit. I had previously installed deal.II into a directory where cmake had picked up the bundled boost, and so the bundled boost was installed into `$INSTALL_DIR/bundled/boost`. Later, I installed some packages on the machine which included boost, and so on some subsequent cmake invocation, we picked up the system boost. I compiled and installed into the same directory. The bundled boost was still there, but the installed version of deal.II now required the system boost.

Then I tried to compile ASPECT, and that went awry: the ASPECT cmake picks up the deal.II include paths, *which still include `$INSTALL_DIR/bundled/`, even though I'm not using anything bundled any more. The compiler line then looks like this:
```
/usr/bin/c++ -DDEBUG
-I/home/bangerth/p/deal.II/1/projects/aspect/include
-I/home/bangerth/p/deal.II/1/projects/build/include
-I/home/bangerth/p/deal.II/1/projects/aspect/contrib/catch
-I/home/bangerth/p/deal.II/1/projects/aspect/contrib/world_builder/include
-I/home/bangerth/p/deal.II/1/projects/build/world_builder/include
-isystem /home/bangerth/p/deal.II/1/install/include -isystem
/home/bangerth/p/deal.II/1/install/include/deal.II/bundled -isystem    <<<<<<<<<<<<<<<<<<<<<<<<<<<
/usr/lib/x86_64-linux-gnu/openmpi/include -isystem
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem
/home/bangerth/bin/candi-install/parmetis-4.0.3/include -isystem
/home/bangerth/bin/candi-install/petsc-3.16.4/include -isystem
/home/bangerth/bin/candi-install/trilinos-release-13-2-0/include
-isystem /home/bangerth/bin/candi-install/superlu_dist_5.1.2/include
-isystem /usr/include/suitesparse -isystem
/home/bangerth/bin/candi-install/hdf5-1.10.8/include -isystem
/home/bangerth/bin/candi-install/oce-OCE-0.18.3/include/oce -isystem
/home/bangerth/bin/candi-install/slepc-3.16.2/include -isystem
/home/bangerth/bin/candi-install/sundials-5.7.0/include -isystem
/home/bangerth/bin/candi-install/symengine-0.8.1/include -isystem
/home/bangerth/bin/candi-install/p4est-2.3.2/FAST/include -std=gnu++20
-pedantic -Wall -Wextra -Wmissing-braces -Woverloaded-virtual
-Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth
-Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations
-Wno-literal-suffix -Wno-psabi -Wno-unused-local-typedefs
-fopenmp-simd -march=native -std=c++20 -Wno-cast-function-type -O0
-ggdb -Wa,--compress-debug-sections -fdiagnostics-color=always
-Winvalid-pch -x c++-header -include
/home/bangerth/p/deal.II/1/projects/build/CMakeFiles/aspect.dir/cmake_pch.hxx
-MD -MT CMakeFiles/aspect.dir/cmake_pch.hxx.gch -MF
CMakeFiles/aspect.dir/cmake_pch.hxx.gch.d -o
CMakeFiles/aspect.dir/cmake_pch.hxx.gch -c
/home/bangerth/p/deal.II/1/projects/build/CMakeFiles/aspect.dir/cmake_pch.hxx.cxx
```
This still has the bundled directory in the `-I` path, and so the compiler picked up my previously installed BOOST version, which does not match the one deal.II was compiled with any more, and so triggers an error because apparently we have been bitten by this kind of thing before:
```
/home/bangerth/p/deal.II/1/install/include/deal.II/base/config.h:620:17: error: static assertion failed: The version number of boost that you are compiling with does not match the version number of boost found during deal.II's configuration step. This leads to difficult to understand bugs and is not supported. Please check that you have set up your application with the same version of boost as deal.II.
  620 |   BOOST_VERSION == 100000 * DEAL_II_BOOST_VERSION_MAJOR +
      |                 ^
```

Installing into an old directory was perhaps not my smartest move, but it would be nice if we didn't export the bundled/ directory as an include path if we don't have to. 

@tamiko Any thoughts?

**Comment by tjhei** [comment]
Do we not clean out the path added here?
https://github.com/dealii/dealii/blob/9843b6f42a20d017bb45eb096ee42d1865c2b4ed/bundled/setup_bundled.cmake#L62

**Comment by bangerth** [comment]
Not sure where this is from, but the command line switch is `/home/bangerth/p/deal.II/1/install/include/deal.II/bundled` which does not seem to come from the line `list(APPEND DEAL_II_BUNDLED_INCLUDE_DIRS ${BOOST_FOLDER}/include)`.

**Comment by tamiko** [comment]
@bangerth I don't immediately see where the erroneous "bundled" include path is coming from. We use the following logic in `macro_populate_target_properties.cmake`:
```
   84     foreach(_include ${DEAL_II_BUNDLED_INCLUDE_DIRS})                            
   85       list(APPEND _includes $<BUILD_INTERFACE:${_include}>)                      
   86     endforeach()                                                                 
   87     if(NOT "${DEAL_II_BUNDLED_INCLUDE_DIRS}" STREQUAL "")                        
   88       list(APPEND _includes "$<INSTALL_INTERFACE:${DEAL_II_INCLUDE_RELDIR}/deal.II/bundled>")
   89     endif()  
```
By toggling `DEAL_II_FORCE_BUNDLED_BOOST` on for instance make I do see these bundled include directories appear in `lib*/cmake/deal.II/deal.IITargets.cmake` (and disappear after toggling off again).


Would you mind to share your `detailed.log`?


In general, I am not sure what we can do here.

If your installation directory is unclean you can get all kinds of funny breakage - not just with our bundled directory. For instance, if you happen to install your own boost copy to `/usr/local` and then build deal.II against a different system-boost version and also install it into `/usr/local` it's going to be game over as well because `/usr/local/include` will take precedence over `/usr/include`.

**Comment by bangerth** [comment]
Let's not worry about it then. I've got it fixed, and it's unlikely a problem many others are going to have.
