### ISSUE TITLE
Deprecate and remove `PathSearch` class

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17120]
I am looking at our `PathSearch` class and I absolutely do not like this thing.

I think such functionality is best deferred to either `std::filesystem` [1] or the boost filesystem class [2]. There is absolutely no reason to reimplement such functionality again in deal.II. On top of that, the special `"MESH"` functionality has not been updated in years. It does not find half of our currently supported mesh files.

While at it, I think we should remove the use of this class from `GridIn::read()`. These functions should not search but simply trying to open the supplied filepath (or stream object) and fail if unsuccessful.

Quick vote and opinions?

[1] https://en.cppreference.com/w/cpp/filesystem
[2] https://www.boost.org/doc/libs/1_34_0/libs/filesystem/doc/index.htm

**Comment by kronbichler** [comment]
I agree, this is an old class that has not been used directly in years as far as I can see. I would not be unhappy if this were implemented with standard filesystem facilities.

**Comment by marcfehling** [comment]
I agree as well. Since we require C++17 which introduces `std::filesystem`, this is a sensible suggestion.

**Comment by Rombur** [comment]
I agree. There is no point in having this class since `std::filesystem` exists.

**Comment by bangerth** [comment]
One of the many bad ideas we had 20 years ago. Let's get rid of it.
