### ISSUE TITLE
Compiling errors in particles/property_pool.h and particles/particle_accessor.h when using nvcc_wrapper

### ISSUE THREAD

**Issue by YiminJin** [dealii/dealii#17148]
I ran into compiling errors when using the nvcc_wrapper of Kokkos as the c++ compiler. The functions causing compiling errors are Particles::PropertyPool::get_properties() and Particles::ParticleAccessor::get_properties(). The error messages are shown in error_message.txt. The versions of the dependent libraries are shown in config.sh. The gcc version is 13.2.1, and the CUDA version is 12.5. The dealii source code was pulled from the latest master branch.

I tried to move the definitions of the functions right behind their declarations to avoid ambiguity, and the errors were eliminated. I tried step-64 and it worked well (and really worked on the CUDA device, according to typeid(Kokkos::DefaultExecutionSpace).name()). The modified files are also attached (property_pool.h and particle_accessor.h).
However, I don't know why. Does anyone have any ideas about the problem?
[error_message.txt](https://github.com/user-attachments/files/15907831/error_message.txt)
[config.sh.txt](https://github.com/user-attachments/files/15907851/config.sh.txt)
[property_pool.h.txt](https://github.com/user-attachments/files/15907853/property_pool.h.txt)
[particle_accessor.h.txt](https://github.com/user-attachments/files/15907852/particle_accessor.h.txt)

**Comment by bangerth** [comment]
@YiminJin Why not make a patch out of your changes? That would make discussion of the particulars easier!

**Comment by YiminJin** [comment]
This is the patch of my changes:
[0001-fix-compiling-errors-for-nvcc.patch.txt](https://github.com/user-attachments/files/15910934/0001-fix-compiling-errors-for-nvcc.patch.txt)

**Comment by gassmoeller** [comment]
I do not know much about Kokkos or how it is integrated into deal.II, but I think the crucial part of your error message is:
```
/home/jinym/projects/github/dealii/include/deal.II/particles/property_pool.h:460:1: error: no declaration matches ‘dealii::ArrayView<__remove_cv(const double)> dealii::Particles::PropertyPool<dim, spacedim>::get_properties(Handle)’
  460 |   PropertyPool<dim, spacedim>::get_properties(const Handle handle)
      | ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jinym/projects/github/dealii/include/deal.II/particles/property_pool.h:206:79: note: candidate is: ‘dealii::ArrayView<double, dealii::MemorySpace::Host> dealii::Particles::PropertyPool<dim, spacedim>::get_properties(Handle)’
```

If you compare the arguments of the function declaration in line 460 and the function definition in line 206 they are different. For some reason the function definition adds another template argument to the returned ArrayView, while the declaration does not. I do not know if this expected behavior for deal.II with Kokkos. Maybe @masterleinad or @Rombur know more about why this happens?

**Comment by Rombur** [comment]
`ArrayView` has two template parameters the `ElementType` and the `MemorySpaceType`. The `MemorySpaceType` has a default value which is `MemorySpace::Host`. 

@YiminJin do you get this error when compiling deal.II or when you compile your own code?

**Comment by YiminJin** [comment]
@Rombur I got this error when compiling deal.II. I guess this is due to some limitations of nvcc, but I'm not sure.

**Comment by Rombur** [comment]
We have nightly testing with `nvcc` and I regularly compile with `nvcc` myself. So it should work. Let me try to reproduce the issue.

**Comment by YiminJin** [comment]
@Rombur Thank you for your help. I tried the configuration with gcc 11.4.0 and nvcc 12.5 and everything is fine. So I think the problem is caused by some new "features" of gcc 13 (or gcc 12).

**Comment by Rombur** [comment]
@YiminJin, I have tried to reproduce the error but I get the same error as [here](https://forums.developer.nvidia.com/t/builtin-ia32-ldtilecfg-and-builtin-ia32-sttilecfg-are-undefined/298516) (they try both nvcc 12.4 and 12.5 with g++ 13). Unless you need to use gcc 13, I would just downgrade to gcc 11.

**Comment by tjhei** [comment]
@Rombur the error you describe can be worked around by #17420.

I now have the same property_pool errors described in this issue (gcc 13, cuda 12.5).
