### ISSUE TITLE
Difficult-to-read part in the introduction of step-89.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17155]
See this comment: https://github.com/dealii/dealii/pull/16299#pullrequestreview-2012831623 I would very much like to see this addressed for the release.

@jh66637 @peterrum @fdrmrc @kronbichler FYI.

**Comment by jh66637** [comment]
Thanks for detailly going through the tutorial! I will not be able to do it this weekend, but I will look into it as soon as possible :)

**Comment by bangerth** [comment]
Good enough -- I just would like to see this addressed before the release :-) Thank you!
