### ISSUE TITLE
Mistake in formula in step-89?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17154]
In the introduction of step-89, the weak form is stated in the Section here: https://dealii.org/developer/doxygen/deal.II/step_89.html#step_89-Acousticconservationequations It shows boundary terms due to integration by parts, but only on \partial\Omega. Just before that, however, is a comment that the program uses a DG approach. Is that a mistake? That is, shouldn't the boundary terms be on *all* face boundaries, not just those on the boundary of the domain?

@jh66637 @peterrum @fdrmrc @kronbichler ?

**Comment by kronbichler** [comment]
I agree with this remark, we should make this clearer in the presentation. Reading the surrounding text, I think that we should state integrals over cells `K` and their boundary `\partial K`. @jh66637 do you agree?

**Comment by jh66637** [comment]
> I agree with this remark, we should make this clearer in the presentation. Reading the surrounding text, I think that we should state integrals over cells `K` and their boundary `\partial K`. @jh66637 do you agree?

Yes, the equations are thought on the element level. Using `K` makes this clear and is in sync with the pictures :)

I can fix this after the weekend :)

**Comment by bangerth** [comment]
Great, thank you!
