### ISSUE TITLE
Rename callbacks in PETScWrappers::TimeStepper.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17180]
@stefanozampini I'm (finally!) putting the finishing touches on step-86 (see #15540) and I'm coming by the `PETScWrappers::TimeStepper::distribute` callback. I know why you called it that way in #15066: Because all it does is call `AffineConstraints::distribute()`.

But `AffineConstraints::distribute()` is itself poorly named if you ask me. Would you object if I rename the callback to `PETScWrappers::TimeStepper::set_algebraic_components`, given that there is already a callback `PETScWrappers::TimeStepper::algebraic_components` that returns the index set of algebraic components?

**Comment by bangerth** [comment]
Similarly, the `PETScWrappers::TimeStepper::decide_for_coarsening_and_refinement` currently returns its answer via a reference-to-bool argument (the callback itself returns `void`). This is not the C++ way. The function should return the value as a `bool`. Would you be amenable to me changing the signature of this function (and rename it to something else, perhaps `do_coarsening_and_refinement_or_not` -- better names welcome!)?

**Comment by bangerth** [comment]
A third point: the `interpolate()` callback does not receive the time as argument. This is awkward, and in step-86 we end up with querying the time in some sort of round-about way. Can we query the current time from the `TS` object so that we can pass it to the `interpolate()` callback?

**Comment by bangerth** [comment]
@stefanozampini All questions for which I'd appreciate your input.

**Comment by stefanozampini** [comment]
> But AffineConstraints::distribute() is itself poorly named if you ask me. Would you object if I rename the callback to PETScWrappers::TimeStepper::set_algebraic_components, given that there is already a callback PETScWrappers::TimeStepper::algebraic_components that returns the index set of algebraic components?

What about `update_algebraic_components`?

**Comment by stefanozampini** [comment]
> Similarly, the PETScWrappers::TimeStepper::decide_for_coarsening_and_refinement currently returns its answer via a reference-to-bool argument (the callback itself returns void). This is not the C++ way. The function should return the value as a bool. Would you be amenable to me changing the signature of this function (and rename it to something else, perhaps do_coarsening_and_refinement_or_not -- better names welcome!)?

Fine with me, pick the name you prefer

Fine with me, pick the name you prefer

**Comment by stefanozampini** [comment]
> A third point: the interpolate() callback does not receive the time as argument. This is awkward, and in step-86 we end up with querying the time in some sort of round-about way. Can we query the current time from the TS object so that we can pass it to the interpolate() callback?

To inquire about the current time you can use `TSGetTime` or the `get_time` method of the `TimeStepper` class

The reason `time` is not listed as argument is because the `interpolate` callback  can transfer previous solutions also (like in multi-step methods as BDF). As a comment, the boundary values that are time dependent are not actually dofs of the problem, and thus they will be ignored by the ODE solver. In principle setting boundary values during interpolate should not be needed.
