### ISSUE TITLE
Cmake/CTest: Option to disable building of documentation for tests

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#17192]
Currently, 
whenever I rerun a test the documentation has to be rebuild,
which takes a considerable amount of time.

I tried setting `DEAL_II_COMPONENT=OFF` but then the test failed on the configure stage, so that is not an option.

Especially when searching for an error within the test itself this produces an annoying amount of waiting time and slows the process down, 
so an option to actively disable this would be good.

**Comment by tjhei** [comment]
I typically have a separate build directory only for building documentation. This way I can control exactly whenever I want it built.

**Comment by jpthiele** [comment]
It was a strange thing in VSCode, for some reason `documentation` was set as build target
so it ran for every click on a test run button...
