### ISSUE TITLE
Enhancement idea: Vector view

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#17219]
I have been learning Julia for a while now as it is becoming widespread at work. 
And one feature that is really great are non-owning/unmanaged [views](https://docs.julialang.org/en/v1/base/arrays/#Views-(SubArrays-and-other-view-types)) on data.

With these you can access a subrange of a (multidimensional) array and use it as if it was a smaller object, e.g. viewing elements 10-19 of a vector of length 50  reinterprets them as a vector of length 10. Changes to the view will affect the original vector, so you can do things like blocking quite easily while still having a continuous memory vector in the background.

Since I am doing tensor product space-time finite elements I have a large vector that contains one vector of spatial n_dots for each temporal DoF.
Many operations I have to do are on each of those subvectors 
and it would greatly improve performance if I would not need to do copies in both directions. 

I think `Kokkos::Views<MemoryUnmanaged>` would basically do what I need by getting a `Number*` to the first element of the subvector. 
But I am unsure which of the functions of `dealii::Vector` I'd have to definitely override and which copy constructors and assignments I could remove. 
Or if it would be better to have a separate class only derived from `Subscriptor`
and if that would require having the implementation in deal.II because of instantiations or if I could also integrate it into ideal.II to support older versions of deal.II.

**Comment by drwells** [comment]
Uh oh, here we go again :)

We used to support this - it was even called VectorView. We ultimately decided to get rid of it in #5278.

Maybe we should take another look at what we support with `ArrayView` (or even `std::span`). What kinds of things would you like to do that we can't do with normal FE vectors?

**Comment by jpthiele** [comment]
I basically have a space-time vector that consists of spatial vectors stacked on top of each other, each one related to one temporal DoF within a temporal subtriangulation (t_{m-1},t_m) of (0,T). 
For a dynamic grid each of these will be allowed its own spatial triangulation such that some form of interpolation between meshes is needed in the time marching.
Additionally, file output (VTK and the likes) is done per temporal DoF so that is a lot of copying into a temporal spatial vector.
And I am working on supporting interpolations from one fe space to another, for which I rely on deal.II's implementation instead of writing a dedicated space-time interpolation from scratch. So it's again exporting and interpolating. 

Those are the current use cases that come to mind from the top of my head.

**Comment by drwells** [comment]
One nice feature of `DataOut` (more precisely, its base class `DataOut_DoFData`) is that it uses vector template types - in theory, though I don't think anyone has done it, you should be able to use your own vector class for output by including `data_out_dof_data.templates.h` and making sure that vector class satisfies whatever implicit duck-typed requirements that class requires. For example - we copy vectors and set them up with updated ghost data, so your own vector class needs to know how to do that.

Can you give that a try? It might be possible to accomplish the graphical output tasks without modifying deal.II internals.
