### ISSUE TITLE
State of Regression Tester

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17213]
In reference to #17202 

I am a bit worried about the current state of our [regression testsuite](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=5f65ad).

Updating to the latest compiler version results in a number of build warnings (which should be relatively easy to fix). But the two variants also feature the latest version of external libraries and at least with P4est-2.8.6 something seems to be going wrong:

| Host | Configuration | Commit | Build errors | Build warnings | Failing tests | Passing tests |
| - | - | - | :-: | :-: | :-: | :-: |
| tester-tos | [Clang-18.1.8-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=102) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=102) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=102) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=102) | [72](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=102) | [15764](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=102) |
| tester-tos | [GNU-14.1.1-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=99) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=99) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=99) | [21](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=99) | [56](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=99) | [15788](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=99) |

All tests:

| Host | Configuration | Commit | Build errors | Build warnings | Failing tests | Passing tests |
| - | - | - | :-: | :-: | :-: | :-: |
| tester-tos | [GNU-14.1.1-master-std=c++20-20240704](https://cdash.dealii.org/buildSummary.php?buildid=77) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=77) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=77) | [32](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=77) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=77) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=77) |
| tester-tng | [GNU-10.2.1-master-debian-11](https://cdash.dealii.org/buildSummary.php?buildid=78) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=78) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=78) | [2](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=78) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=78) | [42](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=78) |
| tester-tng | [GNU-11.4.0-master-ubuntu-lts-22.04](https://cdash.dealii.org/buildSummary.php?buildid=79) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=79) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=79) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=79) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=79) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=79) |
| tester-tng | [GNU-9.4.0-master-ubuntu-lts-20.04](https://cdash.dealii.org/buildSummary.php?buildid=80) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=80) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=80) | [2](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=80) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=80) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=80) |
| tester-tos | [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/buildSummary.php?buildid=81) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=81) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=81) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=81) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=81) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=81) |
| tester-tos | [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/buildSummary.php?buildid=82) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=82) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=82) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=82) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=82) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=82) |
| tester-tos | [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=83) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=83) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=83) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=83) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=83) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=83) |
| tester-tos | [GNU-11.3.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=84) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=84) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=84) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=84) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=84) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=84) |
| tester-tos | [GNU-10.4.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=85) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=85) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=85) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=85) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=85) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=85) |
| tester-tos | [Clang-18.1.8-master-unity_build-20240704](https://cdash.dealii.org/buildSummary.php?buildid=86) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=86) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=86) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=86) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=86) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=86) |
| tester-tos | [Clang-18.1.8-master-std=c++20-20240704](https://cdash.dealii.org/buildSummary.php?buildid=87) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=87) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=87) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=87) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=87) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=87) |
| tester-tng | [GNU-13.3.0-master-debian-13](https://cdash.dealii.org/buildSummary.php?buildid=88) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=88) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=88) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=88) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=88) | [15656](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=88) |
| tester-tng | [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/buildSummary.php?buildid=89) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=89) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=89) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=89) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=89) | [15656](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=89) |
| tester-tos | [Clang-16.0.6-master-taskflow-20230708](https://cdash.dealii.org/buildSummary.php?buildid=90) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=90) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=90) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=90) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=90) | [50](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=90) |
| tester-tng | [GNU-13.2.0-master-ubuntu-lts-24.10](https://cdash.dealii.org/buildSummary.php?buildid=91) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=91) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=91) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=91) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=91) | [15656](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=91) |
| tester-tng | [GNU-13.2.0-master-avx256-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=92) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=92) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=92) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=92) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=92) | [15659](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=92) |
| tester-tng | [GNU-13.2.0-master-ubuntu-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=93) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=93) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=93) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=93) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=93) | [15656](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=93) |
| tester-tng | [GNU-13.2.0-master-avx512-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=94) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=94) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=94) | [4](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=94) | [2](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=94) | [15657](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=94) |
| tester-tos | [Clang-16.0.6-master-autodetection-20230507](https://cdash.dealii.org/buildSummary.php?buildid=95) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=95) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=95) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=95) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=95) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=95) |
| tester-tos | [Clang-15.0.6-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=96) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=96) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=96) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=96) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=96) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=96) |
| tester-tos | [Clang-14.0.6-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=97) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=97) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=97) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=97) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=97) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=97) |
| tester-tos | [Clang-13.0.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=98) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=98) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=98) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=98) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=98) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=98) |
| tester-tos | [GNU-14.1.1-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=99) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=99) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=99) | [21](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=99) | [56](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=99) | [15788](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=99) |
| tester-tos | [GNU-13.1.1-master-minimal-20230116](https://cdash.dealii.org/buildSummary.php?buildid=100) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=100) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=100) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=100) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=100) | [8048](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=100) |
| tester-tos | [GNU-13.1.1-master-64bit_indices-20230507](https://cdash.dealii.org/buildSummary.php?buildid=101) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=101) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=101) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=101) | [2](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=101) | [16052](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=101) |
| tester-tos | [Clang-18.1.8-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=102) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=102) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=102) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=102) | [72](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=102) | [15764](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=102) |
| 495bf87f8098 | [GNU-9.4.0-master-cuda-11.8](https://cdash.dealii.org/buildSummary.php?buildid=103) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=103) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=103) | [300](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=103) | [17](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=103) | [6690](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=103) |
| tester-tos | [Clang-16.0.6-master-sanitizer-20230622](https://cdash.dealii.org/buildSummary.php?buildid=104) | [5f65ad](https://cdash.dealii.org/viewUpdate.php?buildid=104) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=104) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=104) | [1](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=104) | [7881](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=104) |

**Comment by tjhei** [comment]
That seems to be mostly related to p4est...

**Comment by tamiko** [comment]
@tjhei Correct. This seems to be all coming from `Triangulation::get_checksum()`.

**Comment by tjhei** [comment]
Things look very good (green) now, can we close this, @tamiko ?
