### ISSUE TITLE
Make DiscreteTime serializable.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17250]
step-83 (see #12429) currently does not *perfectly* serialize because it does not save which time step it is in. It just starts again at time step 1, but with the correct time and time step size. This is because the `DiscreteTime` class does not know how to serialize itself. This should be easy to add.

I won't get to it today, but if @pcafrica or @blaisb want to beat me to it overnight, that would be great. I think that otherwise, step-83 is actually in really good shape now. I see this as the only currently missing prerequisite.

**Comment by pcafrica** [comment]
Hi @bangerth! Yes this was a super easy one: #17252.

**Comment by bangerth** [comment]
Fixed by #17252.
