### ISSUE TITLE
doubt in giving boundary conditions in step-3,4

### ISSUE THREAD

**Issue by EKiranKumar** [dealii/dealii#1727]
In step-3,4 while applying boundary conditions you are implementing it using   VectorTools::interpolate_boundary_values (dof_handler,
                                            0,
                                            BoundaryValues<dim>(),
                                            boundary_values); 
I amn't getting how you are selecting dof that present on the boundary and how you are getting its values and also arguments list of called function and function to which link is given is not matching.
Also the third parameter in above function is a class and you are writing it as function call.And also you didn't give link to the definition of that function in the library

**Comment by bangerth** [comment]
The function being called is the fourth one of the same name here: http://dealii.org/developer/doxygen/deal.II/namespaceVectorTools.html#a26d2d252a5288a045905b5dc19329d01
The arguments do match (or the program would not compile).

The syntax `BoundaryValues()` creates an unnamed object (using the constructor that takes no arguments) that is then passed to the function. The unnamed object is destroyed at the end of the call.

**Comment by EKiranKumar** [comment]
you can provide me link to the source code of function in the library without which you cannot understand the implementation

**Comment by bangerth** [comment]
The function you are looking for is at https://github.com/dealii/dealii/blob/master/include/deal.II/numerics/vector_tools.templates.h#L2038

It calls functions further up in the file.
