### ISSUE TITLE
remove maxversion limitation for PETSc?

### ISSUE THREAD

**Issue by stefanozampini** [dealii/dealii#17281]
@bangerth I'm not sure it is good to keep such kind of information around
According to https://www.dealii.org/developer/external-libs/petsc.html, the last PETSc version supported is 3.17.1, which is not true

**Comment by stefanozampini** [comment]
Do you want me to open a PR just to remove the note, or would you like to improve the text also?
Also, where from https://www.dealii.org/developer/ that doc is linked?

**Comment by bangerth** [comment]
Any help if appreciated. If you think the text can be improved, that much the better!

The information is linked to from the readme:
```
doc/readme.html:625:                    To disable the PETSc interfaces in cases where <code>cmake</code> automatically finds it, use <code>-DDEAL_II_WITH_PETSC=OFF</code>. More information on configuring and building PETSc can be found <a href="external-libs/petsc.html"
```

**Comment by stefanozampini** [comment]
What's the minimum PETSc version deal.II supports? 3.7.0? Did we write that information somewhere?

**Comment by masterleinad** [comment]
See https://www.dealii.org/developer/external-libs/petsc.html.

**Comment by stefanozampini** [comment]
oops, I missed that.
