### ISSUE TITLE
deal.II implementation of contact (2D, friction, large sliding, multi-body, deformable/rigid)

### ISSUE THREAD

**Issue by jfriedlein** [dealii/dealii#17304]
We try to simulate a metal forming process in deal.II, which also requires modelling contact between deformable solid bodies (possibly reducible to one deformable body and rigid tools). Developing a capable and somewhat robust contact formulation itself is challenging. Therefore, I would like to ask whether there is already experience, insights, or existing contact implementations available in deal.II that could be used or adapted.

I am aware of the following contact related implementations:

- deal.II step 41 (https://www.dealii.org/current/doxygen/deal.II/step_41.html) and 42 (https://www.dealii.org/current/doxygen/deal.II/step_42.html, https://wwwold.mathematik.tu-dortmund.de/papers/FrohneHeisterBangerth2014.pdf), which deal with contact. However, these formulations seem quite specialised and appear to be not easily extendable to the problem at hand (involving friction, large sliding, closing/reopening of contact surfaces, etc.), right?
- Further, I came across Maien Hamed's (@maieneuro) work on an ALE approach including contact (2022/2023: http://hdl.handle.net/11427/36777, https://doi.org/10.1007/s00466-023-02303-0). His contact formulation uses an augmented Lagrangian approach including friction and multi-body contact, appears very capable and seems to be one of the most advanced deal.II contact implementations so far. He was also active in the deal.II Google group and on GitHub. Unfortunately, I cannot get a hold of Maien to discuss the formulation and implementation. Maybe he receives a notification about this issue or if anyone is in contact with Maien, I would be delighted if they could make the connection. (my e-mail: johannes.friedlein@fau.de)
- Discussion on penalty method and convergence failure: (https://groups.google.com/g/dealii/c/uP8NgR0NKBc/m/t_asBiWvBwAJ)
- "Goal-oriented mesh adaptivity in elastoplasticity problems" code gallery program (https://www.dealii.org/current/doxygen/deal.II/code_gallery_goal_oriented_elastoplasticity.html): Here a reference is made to step 41 and the nonlinearity due to contact is mentioned, but I cannot find a contact implementation or usage.
- "A barrier method for frictional contact on embedded interfaces" (https://doi.org/10.1016/j.cma.2022.114820): Uses XFEM to mimic contact.
- "A phase-field method for modeling cracks with frictional contact" (https://doi.org/10.1002/nme.6242): Using a phase-field model to mimic frictional contact in deal.II.
- "Modelling and Simulation of Fluid-Structure Interactions with Contact and Multiple Scales in Time" (https://www.math.uni-konstanz.de/~frei/Habilitationsschrift.pdf): FSI with contact in deal.II 

On the other hand, for instance MOEFEM (http://mofem.eng.gla.ac.uk/mofem/html/) made great progress on contact approaches (e.g. including mortar contact). But I am not sure how much can be learned or taken from there into the deal.II world.
Contact seems to be a rarity in deal.II. But from the works above, I conclude that it is definitely possible in deal.II, it is just a hell of a lot of work. Further, my research focus is not on contact. So, being able to expand on existing works would be crucial and highly appreciated.

I certainly missed works on contact in deal.II above. Please feel free to extend and correct the above list of deal.II contact implementations to provide a summary and overview for the future.

I guess the deal.II mailing list is more suitable for this topic, so I could also divert there. I was just hoping to reach more users using GitHub and provide an extendable overview here.

**Comment by bangerth** [comment]
I think this is probably better asked on the mailing list -- we keep track of bugs and patches here, not open ended questions. That said, I don't think you missed anything that's part of deal.II itself (such as the tutorial or code gallery) in your list. I assume you looked through the list of publications at https://dealii.org/publications.html and filtered for contact problems?

**Comment by jfriedlein** [comment]
Yes, thank you. The topic is now in the mailing list/google group: https://groups.google.com/g/dealii/c/QUYzH2C8Xus
