### ISSUE TITLE
Fix blocking and recursive task calls in FE_DGQ (and perhaps other finite element classes).

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17317]
As shown in https://github.com/dealii/dealii/pull/17119#issuecomment-2224238549, `FE_DGQ::get_prolongation_matrix()` has a critical section guarded by a mutex, but within it calls more tasks. This is always a bug because it may lead to deadlocks. We need to fix this for #17119.

@tamiko Wanted to tackle rewriting these functions in #16204 using `Lazy<T>` anyway, but I'm not sure that's going to happen before the release.

**Comment by tamiko** [comment]
We fixed this with a "band aid" in #17358 and are tracking the tasking capabilities for `Lazy<T>` in #17318. Let's close this issue here for now.
