### ISSUE TITLE
Fix Lazy's approach to tasking.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17318]
As pointed out in https://github.com/dealii/dealii/pull/16204#issuecomment-2240353702 and as a consequence of the bug encountered in https://github.com/dealii/dealii/pull/17119#issuecomment-2224238549 and documented in #17317, I've come to conclude that the `Lazy` class implemented in #16182 cannot be used in a tasking context if the callable that generates the object itself creates tasks. That's because `Lazy::ensure_initialized(const Callable &creator)` executes the `creator()` under a mutex, and so of `N` concurrent tasks on a setup that allows `N` concurrent tasks, all accessing the lazy object at the same time, `N-1` will block without giving the scheduler the opportunity to schedule other tasks. If the one remaining task at some point gives control back to the schedule, and the scheduler decides to execute an `N+1`th task of the same kind, then that will block as well -- now all tasks are blocked and we're deadlocked. This is what @tjhei encounters in https://github.com/dealii/dealii/pull/17119#issuecomment-2224238549.

At its core, the issue is here:
```
template <typename T>
DEAL_II_CXX20_REQUIRES((std::is_move_constructible_v<T> &&
                        std::is_move_assignable_v<T>))
template <typename Callable>
inline DEAL_II_ALWAYS_INLINE
  void Lazy<T>::ensure_initialized(const Callable &creator) const
  DEAL_II_CXX20_REQUIRES((std::is_invocable_r_v<T, Callable>))
{
  //
  // Use Schmidt's double checking [1] for checking and initializing the
  // object.
  //
  // [1] https://en.wikipedia.org/wiki/Double-checked_locking
  //

  //
  // Check the object_is_initialized atomic with "acquire" semantics [1].
  //
  // This ensures that (a) all subsequent reads (of the object) are
  // ordered after this check, and that (b) all writes to the object
  // before the atomic bool was set to true with "release" semantics are
  // visible on this thread.
  //
  // [1]
  // https://en.cppreference.com/w/cpp/atomic/memory_order#Release-Acquire_ordering
  //
  if (!object_is_initialized.load(std::memory_order_acquire))
#ifdef DEAL_II_HAVE_CXX20
    [[unlikely]]
#endif
    {
      std::lock_guard<std::mutex> lock(initialization_mutex);                      ************************* we lock

      //
      // Check again. If this thread won the race to the lock then we
      // initialize the object. Otherwise another thread has already
      // initialized the object and flipped the object_is_initialized
      // bit. (Here, the initialization_mutex ensures consistent ordering
      // with a memory fence, so we will observe the updated bool without
      // acquire semantics.)
      //
      if (!object_is_initialized.load(std::memory_order_relaxed))
        {
          Assert(object.has_value() == false, ExcInternalError());
          object.emplace(std::move(creator()));                                                   ************************** we execute

          //
          // Flip the object_is_initialized boolean with "release"
          // semantics [1].
          //
          // This ensures that the above move is visible on all threads
          // before checking the atomic bool with acquire semantics.
          //
          object_is_initialized.store(true, std::memory_order_release);
        }
    }

  Assert(
    object.has_value(),
    dealii::ExcMessage(
      "The internal std::optional<T> object does not contain a valid object "
      "even though we have just initialized it."));
}
```

I see two options here:
* We simply let all threads that get to the lock execute the creator, then lock the mutex and let only one move its result into the final variable. This way, only the move operation itself is blocked. This assumes that the move operation itself cannot create tasks, which is likely but cannot be guaranteed.
* We extend `TaskResult` (see #16198) with an operation of the kind `TaskResult::try_emplace_task()` that, in a thread-safe manner, checks whether a `Callable` has already been assigned as a task and if not, creates such a task. Then, in `Lazy`, we can keep around such a `TaskResult` object, multiple threads can concurrently call `try_emplace_task()` and then wait for `TaskResult::join()` knowing that exactly one tasks has been assigned and for those that block in `join()`, know that this allows the scheduler to schedule more tasks.

Option 2 seems like the better approach.

**Comment by tamiko** [comment]
Let's go with Option 2.

**Comment by bangerth** [comment]
I have a candidate patch, but I first need to work through adding some things to `TaskResult` as you've been seeing.

**Comment by bangerth** [comment]
This is now fixed.
