### ISSUE TITLE
Remove step-52 and deal.II time steppers?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17386]
@Rombur added step-52 many years ago, showing how to use the deal.II time stepping classes. These abstract some of the work in writing time steppers, but the classes we have are not anywhere near to what we now have in interfaces to SUNDIALS and PETSc. @Rombur: How attached are you to this program? I feel like step-52 shows things that we now know we can do better, and that we don't want to advertise because we should really be steering users towards step-86 instead.

(There is also a long-open github issue about step-52, #7191, but that's a separate issue.)

**Comment by Rombur** [comment]
I am fine with removing the tutorial but I would like to keep the time stepping classes for now. I am using these classes on a Trilinos-based code, so I don't want to pull PETSc too and I have heard bad things about Kokkos support in SUNDIALS. I was told about SUNDIALS issues a couple of years ago so it hopefully works better now but I haven't heard of happy users yet.

**Comment by jpthiele** [comment]
If you have Trilinos based codes it might be worthwhile to explore [Trilinos/Tempus](https://docs.trilinos.org/dev/packages/tempus/doc/html/index.html) and whether we might want to wrap/interface that too. 

A similar example would be the autodiff classes for either ADOL-C or Trilinos/Sacado

**Comment by bangerth** [comment]
Tempus: We could mention that at the end of step-86, though I think that we are well served already with the PETSc and SUNDIALS interfaces. Either way, it might be fun to explore.

@Rombur How about we deprecate step-52 but leave the classes in place? We could still do that for this release, and then remove the program for the next release.

**Comment by Rombur** [comment]
> How about we deprecate step-52 but leave the classes in place? We could still do that for this release, and then remove the program for the next release.

Sounds good.

**Comment by cpraveen** [comment]
I am not able to use PetscWrappers::TimeStepper with LinearAlgebra::distributed::Vector. Is this something that needs to be implemented, or it is not possible to use them together ?

But dealii::TimeStepping will work with this vector type, so it would be good to keep this also.

**Comment by marcfehling** [comment]
PETScWrappers::TimeStepper has only been explicitly instantiated for the PETScWrappers Vectors:
https://github.com/dealii/dealii/blob/25495718f4bb6aa45a8f6c8cc4f2aedbe8d62231/source/lac/petsc_ts.cc#L82-L89

Will deal.II compile if you add the corresponding instantiations for the LinearAlgebra Vectors?

**Comment by jpthiele** [comment]
To be more precise, will it compile if you add 
`# include <deal.II/lac/petsc_ts.templates.h>`
to your application source code?

**Comment by cpraveen** [comment]
As I expected, it now complains of petsc_vector() missing

```
dealii@f2f823ec6e8e:~/shared/dg2d/system_lagrange_mpi$ make
Consolidate compiler generated dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cc.o
In file included from /home/dealii/shared/dg2d/system_lagrange_mpi/dg.h:34,
                 from /home/dealii/shared/dg2d/system_lagrange_mpi/main.cc:1:
/usr/local/include/deal.II/lac/petsc_ts.templates.h: In instantiation of ‘unsigned int dealii::PETScWrappers::TimeStepper<VectorType, PMatrixType, AMatrixType>::solve(VectorType&) [with VectorType = dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>; PMatrixType = dealii::PETScWrappers::MatrixBase; AMatrixType = dealii::PETScWrappers::MatrixBase]’:
/home/dealii/shared/dg2d/system_lagrange_mpi/dg.h:912:12:   required from ‘void DGSystem<dim>::run_with_petsc() [with int dim = 2]’
/home/dealii/shared/dg2d/system_lagrange_mpi/dg.h:931:4:   required from ‘void DGSystem<dim>::run() [with int dim = 2]’
/home/dealii/shared/dg2d/system_lagrange_mpi/main.cc:48:14:   required from here
/usr/local/include/deal.II/lac/petsc_ts.templates.h:1226:5: error: ‘class dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>’ has no member named ‘petsc_vector’
 1226 |     AssertPETSc(TSSetSolution(ts, y.petsc_vector()));
```

**Comment by bangerth** [comment]
As mentioned on the mailing list, the PETSc time steppers only work with PETSc vectors. But we have the SUNDIALS wrappers for all other cases.
