### ISSUE TITLE
Potential Issue with Pointer Traversal in `PETScWrappers::VectorBase`'s Functions

### ISSUE THREAD

**Issue by QY-Shi** [dealii/dealii#17405]
While learning the underlying mechanisms of the PETSc wrappers in deal.II, I have noticed some potential issue.

 In the `PETScWrappers::VectorBase::lp_norm()` and `PETScWrappers::VectorBase::mean_value()` functions, pointers retrieved through `VecGetArrayRead()` are iterated over the entire length of the distributed vector, as demonstrated in the following code snippet from `PETScWrappers::VectorBase::mean_value()`:

```c++
// use modern processors better by
// allowing pipelined commands to be
// executed in parallel
const PetscScalar *ptr  = start_ptr;
const PetscScalar *eptr = ptr + (size() / 4) * 4;
while (ptr != eptr)
{
  sum0 += *ptr++;
  sum1 += *ptr++;
  sum2 += *ptr++;
  sum3 += *ptr++;
}
```

Here, the length of the pointer iteration is [`size()`](https://www.dealii.org/current/doxygen/deal.II/classPETScWrappers_1_1VectorBase.html#a3875621a4c149265ca738d48614f053c) rather than [`locally_owned_size()`](https://www.dealii.org/current/doxygen/deal.II/classPETScWrappers_1_1VectorBase.html#acff4e7a74af91a2ab885cf10d0feb961). This confuses me because [PETSc's documentation](https://petsc.org/release/manualpages/Vec/VecGetArrayRead/) states that `VecGetArrayRead()` should only access "this processor's portion of the vector data."

Conversely, in the `PETScWrappers::VectorBase::all_zero()` function, pointer iteration is limited to `locally_owned_size()`, which seems to be the appropriate approach.

However, `tests/petsc/33.cc` in the test suite that tests for the `lp_norm()` function do not reveal any issues, adds to my confusion.

**Comment by jpthiele** [comment]
test 33 is only run sequentially so it can not detect an issue with the distributed interface.
It could (and possibly should) be rewritten to run both sequential and distributed.
I am only familiar with the Trilinos interface, so I can't say much for PETSc but I think you are correct.

**Comment by bangerth** [comment]
This definitely looks like a bug -- nice work finding this. We'd appreciate a patch!

**Comment by QY-Shi** [comment]
Got it, I'll write a patch.
