### ISSUE TITLE
Build failure with WITH_MPI=false

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1745]
http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=13541

Merge commit 30728c46c9dd96c03b1b0f057575b3e5c7a9c8d8

**Comment by bangerth** [comment]
@Rombur -- this is your recent addition. I think that in the non-MPI case, no communication is necessary at all. So one could just be able to skip the latter parts of the function. (Of course the whole point is a bit moot given that one can't even use `p::d::T` without MPI in any meaningful way.) Can you take a look at #1747?
