### ISSUE TITLE
Add option to deprecate ParameterHandler entries

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#17464]
It would be useful to be able to mark parameters inside the ParameterHandler as deprecated. This is needed for example if input parameters are no longer required, because algorithms have changed. We already have the option to declare an alias parameter (to say a parameter has been renamed) using the function `ParameterHandler::declare_alias`. This function also has the option to set an argument `alias_is_deprecated`, which marks the alias as deprecated and issues a warning if the parameter is still used. I essentially need the same functionality, but without declaring a new parameter.
The options to implement this would be:
- Add a new parameter to `ParameterHandler::declare_entry` similar to the `alias_is_deprecated` parameter of `declare_alias`
- Add a new function to the ParameterHandler class e.g. called `mark_as_deprecated` that marks an existing entry as deprecated

Ideally the parameter could also get a specific message ("This parameter is no longer used, because ...").  However I will first evaluate how complex this would be.

One complication is that we would need to decide if the deprecation information needs to be stored in the xml or json representation of the parameters. On first glance probably not, we also do not store the parameter `has_to_be_set`.

Any input is appreciated. I will work on this during the following days and open a PR for discussion.

**Comment by tjhei** [comment]
I Iike it. Something like ``declare_deprecated_entry(..., reason)`` might be another reasonable choice.

**Comment by gassmoeller** [comment]
I thought about adding a `reason` parameter, but then I thought it would make more sense for the user to include that in the regular parameter documentation. This way we do not have to change the internal data structure more than necessary, and it is the natural place to explain what happened to the parameter. I will open a PR with a suggestion soon.

**Comment by tjhei** [comment]
> I will open a PR with a suggestion soon.

You could also ask for the reason separately and append it to the description in a standardized format. Not sure if that makes sense to you.

**Comment by gassmoeller** [comment]
I could, but would it be better than expecting the parameter declaration to be changed? I could append the reason to the existing documentation, but that would not allow to change existing documentation. Would you be ok making the reason optional? Then the user could decide whether to just modify the parameter declaration, or to provide a reason in the `mark_as_deprecated` function.
