### ISSUE TITLE
compare_for_domination() assertion error when using FESystems with different number of base elements

### ISSUE THREAD

**Issue by mkghadban** [dealii/dealii#17521]
If multiple FESystems are used where each FESystem has a different number of base elements, the assertion in the compare_for_domination() fails throwing an error. For example, if using

**FESystem[FE_Q(1)^3]
FESystem[FE_Q(1)^2-FE_Nothing^1]**

the following assertion error is thrown
**An error occurred in line <2478> of file <../deal.II/src/source/fe/fe_system.cc> in function
    dealii::FiniteElementDomination::Domination dealii::FESystem<dim, spacedim>::compare_for_domination(const dealii::FiniteElement<dim, spacedim>&, unsigned int) const [with int dim = 2; int spacedim = 2]
The violated condition was:
    this->n_base_elements() == fe_sys_other->n_base_elements()
Additional information:
    You are trying to use functionality in deal.II that is currently not
    implemented. In many cases, this indicates that there simply didn't
    appear much of a need for it, or that the author of the original code
    did not have the time to implement a particular case. If you hit this
    exception, it is therefore worth the time to look into the code to
    find out whether you may be able to implement the missing
    functionality. If you do, please consider providing a patch to the
    deal.II development sources (see the deal.II website on how to
    contribute).**

**Comment by marcfehling** [comment]
You can match the base elements alternatively like this
```
FESystem[FE_Q(1)^2-FE_Q(1)^1]
FESystem[FE_Q(1)^2-FE_Nothing^1]
```

**Comment by bangerth** [comment]
Yes, that's the solution we found too, but it would still be nice to allow the more general case.

**Comment by mkghadban** [comment]
> You can match the base elements alternatively like this
> 
> ```
> FESystem[FE_Q(1)^2-FE_Q(1)^1]
> FESystem[FE_Q(1)^2-FE_Nothing^1]
> ```

Excatly! That's the workaround I used...but as @bangerth said, it's nice to keep it general.
