### ISSUE TITLE
Significant delay with deal.II exceptions on MacOS

### ISSUE THREAD

**Issue by harmonj** [dealii/dealii#17565]
On MacOS/Apple Clang, deal.II exceptions experience significant delay.

Our `git bisect`, which resulted in patch #17552, was truncated prematurely.

The actual issue was introduced in  #17208: https://github.com/dealii/dealii/blob/adbb1e237f38ec31fd2d23b5ce102ebdbe4149e6/source/base/exceptions.cc#L288C7-L288C42 with the change of
`stacktrace_entry = stacktrace_entry.substr(0, pos_start);` to `stacktrace_entry.resize(pos_start);` on `line 288`.

Reverting this change eliminates the delay, but will reintroduce CppCheck's complaint about this line.

@ejtovar @tamiko @Rombur @masterleinad

**Comment by tamiko** [comment]
Fascinating. I must admit I don't understand how this can possible cause these minute long hiccups.

@masterleinad What about we simply do the `substr(...)` and introduce a new string variable instead?

**Comment by masterleinad** [comment]
> @masterleinad What about we simply do the `substr(...)` and introduce a new string variable instead?

See #17567.
