### ISSUE TITLE
Bug in AffineConstraints::make_consistent_in_parallel().

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17599]
Investigating #17595 with @marcfehling has uncovered a problem with merging constraints from different processes in `AffineConstraints::make_consistent_in_parallel()`. In short, here is the situation:

* `DoFTools::make_hanging_node_constraints()` creates constraints for hanging nodes on different processes that *appear* different, because these constraints are created on faces between locally owned and ghost, or ghost and ghost, cells. On some processes, that means that we consider faces that we don't consider on others, and so the constraints we get are different at this stage.
* Specifically, with the short code I attached to #17595 (based on @marcfehling 's testcase), process 0 creates the following constraints among many others:
```
    63 3:  0.323607
    63 7:  -0.123607
    63 19:  0.8
    64 3:  -0.123607
    64 7:  0.323607
    64 19:  0.8
```
* On the other hand, on process 1 we have:
```
   64 3:  -0.447214
    64 7:  0.447214
    64 63:  1
```
* The constraints for 64 *appear* different, but they are not. If you resolve the constraint 64->63 with the constraint we have on process 0, you end up with the exact same constraint as shown for process 0. The issue is that when we merge constraints, we just *add* entries and that leads to substantial confusion.

**Comment by bangerth** [comment]
This all is related to #17175 (@marcfehling), #14905 (@bergbauer), #12430 (@peterrum), #11725 (@mwichro).

**Comment by bangerth** [comment]
Minimal testcase:
```
#include <deal.II/base/index_set.h>
#include <deal.II/lac/affine_constraints.h>

using namespace dealii;

void
test()
{
  IndexSet locally_owned_dofs(3);
  if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0)
    locally_owned_dofs.add_range(0,2);
  else if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 1)
    locally_owned_dofs.add_range(2,3);

  IndexSet locally_relevant_dofs = complete_index_set(3);
  AffineConstraints<double> constraints(locally_owned_dofs, locally_relevant_dofs);

  const auto show_constraints_1_2 = [&]()
    {
      for (unsigned int p=0; p<Utilities::MPI::n_mpi_processes(MPI_COMM_WORLD); ++p)
        {
          if (p == Utilities::MPI::this_mpi_process(MPI_COMM_WORLD))
            {
              std::cout << "On process " << p << std::endl;

              std::cout << "What process " << p << " believes about DoF 1:\n";
              for (const auto &c : constraints.get_lines())
                if (c.index == 1)
                  for (const auto &entry : c.entries)
                    std::cout << "    constrained against " << entry.first << " with weight "
                              << entry.second << '\n';
              std::cout << "What process " << p << " believes about DoF 2:\n";
              for (const auto &c : constraints.get_lines())
                if (c.index == 2)
                  for (const auto &entry : c.entries)
                    std::cout << "    constrained against " << entry.first << " with weight "
                              << entry.second << '\n';
            }
          MPI_Barrier(MPI_COMM_WORLD);
        }
    };


  std::cout << "------------- make_hanging_node_constraints():" << std::endl;
  if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0)
    {
      constraints.add_constraint(1, {{ 0, 0.5 }});
      constraints.add_constraint(2, {{ 0, 0.25 }});
    }
  else if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 1)
    {
      constraints.add_constraint(2, {{ 1, 0.5 }});
    }  
  show_constraints_1_2();

  std::cout << "------------- make_consistent_in_parallel():" << std::endl;
  constraints.make_consistent_in_parallel(locally_owned_dofs, locally_relevant_dofs,
                                          MPI_COMM_WORLD);  
  show_constraints_1_2();
}

int
main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  test();
}
```
With output:
```
------------- make_hanging_node_constraints():
------------- make_hanging_node_constraints():
On process 0
What process 0 believes about DoF 1:
    constrained against 0 with weight 0.5
What process 0 believes about DoF 2:
    constrained against 0 with weight 0.25
On process 1
What process 1 believes about DoF 1:
What process 1 believes about DoF 2:
    constrained against 1 with weight 0.5
------------- make_consistent_in_parallel():
------------- make_consistent_in_parallel():
On process 0
What process 0 believes about DoF 1:
    constrained against 0 with weight 0.5
What process 0 believes about DoF 2:
    constrained against 0 with weight 0.25
    constrained against 1 with weight 0.5         ************* wrong
On process 1
What process 1 believes about DoF 1:
    constrained against 0 with weight 0.5
What process 1 believes about DoF 2:
    constrained against 0 with weight 0.25
    constrained against 1 with weight 0.5         ************* wrong
```
Because DoF 1 is also constrained, the process should have resolved the dependency 2->1.

**Comment by marcfehling** [comment]
> Because DoF 1 is also constrained, the process should have resolved the dependency 2->1.

What happens after you call `AffineConstraints::close` after `AffineConstraints::make_consistent_in_parallel`?

**Comment by marcfehling** [comment]
The constraints in your example look consistent to me, i.e., each process has the exact same constraint lines. The usual workflow is:
```
constraints.reinit()
DoFTools::make_hanging_node_constraints()
constraints.make_consistent_in_parallel()
constraints.close()
```

**Comment by marcfehling** [comment]
I believe the "merge" algorithm needs the ability to accept constraint lines for the same DoF from different processes, regardless in which context they have been built. The current "merge" algorithm assumes that for a particular DoF, all processes produce the exact same `ConstraintLine`, or at least a part of the complete line.

This is a case that the [testcase](https://github.com/dealii/dealii/blob/master/tests/lac/constraints_make_consistent_in_parallel_03.cc) of #14905 did not cover. Here, the constraints for lines 0 and 2 are the same on all processes. We need a mechanism that also merges different constraints, i.e., scenarios like [the one from the top-message](https://github.com/dealii/dealii/issues/17599#issue-2483397390) or this one:
```
if (my_proc == 0)
  {
    constraints.add_entry(0, 1, 0.5);
    constraints.add_entry(0, 2, 0.5);
  }
else if (my_proc == 1)
  {
    constraints.add_entry(0, 1, 0.25);
    constraints.add_entry(0, 3, 0.75);
  }
```
Then we pray that `AffineConstraints::close` is capable of resolving all chains of constraints.

Of course we want to skip duplicates to prevent our `AffineConstraints` objects from needlessly growing in size. I believe that this is what #14905 essentially provides. But with [my test](https://github.com/marcfehling/merge-constraints), we ran into the case in which #14905 expected a duplicated `ConstraintLine`, but was essentially confronted with a whole new `ConstraintLine`. Thus the current implementation throws an exception that the two lines do not match. However, we need the context of both lines to resolve all constraints correctly.

@bergbauer @peterrum @kronbichler -- Does this description correspond to what `AffineConstraints::make_consistent_in_parallel` currently does?

**Comment by kronbichler** [comment]
Good detective work. I agree that upon exchanging constraints across MPI ranks, we need to resolve the constraints in the same way as the local part for consistent constraints. I understand the example in the top post (and agree with what it should be), but I need to admit that I do not yet fully understand the setup in the immediately preceding post by @marcfehling. I guess I'll wait for the failing test, and would be happy to then discuss a solution.

**Comment by marcfehling** [comment]
> [...], but I need to admit that I do not yet fully understand the setup in the immediately preceding post by @marcfehling. I guess I'll wait for the failing test, and would be happy to then discuss a solution.

The test scenario I had in mind last night doesn't work. The global collection of constraint entries do not work, as we don't allow that two different entries for the same two DoFs exist.

> The issue isn't that the constraints are different on different processes. It's that they are wrong on both processes.

Yes. I am now on the same page as you.

**Comment by marcfehling** [comment]
I have applied #17626 on #17611. Now only process 0 knows about the constraints on DoFs 63 and 64. They do not appear on process 1. I guess this is a result of the "just drop constraints" logic.
```
Process 0:
    ...
    63 3:  0.323607
    63 7:  -0.123607
    63 19:  0.800000
    64 3:  -0.123607
    64 7:  0.323607
    64 19:  0.800000
    ...

Process 1:
    ...
```

**Comment by bangerth** [comment]
Is this with the testcase at the top of this issue? It should be reporting things such as "What process XXX believes...".

**Comment by marcfehling** [comment]
> Is this with the testcase at the top of this issue? It should be reporting things such as "What process XXX believes...".

No, this was the testcase of #17611.

---

When I enhance the exchange over all locally _relevant_ DoFs in the testcase, the constraints on DoFs 63 and 64 appear on both processes.

So the user gets what they ask for. I consider this a success.

```
Process 0:
    ...
    63 3:  0.323607
    63 7:  -0.123607
    63 19:  0.800000
    64 3:  -0.123607
    64 7:  0.323607
    64 19:  0.800000
    ...

Process 1:
    63 3:  0.323607
    63 7:  -0.123607
    63 19:  0.800000
    64 3:  -0.123607
    64 7:  0.323607
    64 19:  0.800000
    ...
```

[output.txt](https://github.com/user-attachments/files/16788148/output.txt)
