### ISSUE TITLE
Bug in DoFTools::make_hanging_node_constraints().

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17595]
@marcfehling has been chasing a bug for quite a while already and I'm spending a bit of time on that this afternoon. Here's what I have so far. With the program below, we end up with two processes that have recorded constraints for the same DoF that are clearly contradictory. This leads to downstream issues when calling `make_consistent_in_parallel()`, but the problem exists before that. I will have to investigate how we get there.

Here's the program:
```
#include <deal.II/distributed/tria.h>

#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/filtered_iterator.h>
#include <deal.II/grid/grid_generator.h>

#include <deal.II/hp/fe_collection.h>

#include <deal.II/lac/affine_constraints.h>

using namespace dealii;

template <int dim, int spacedim>
void
test()
{
  parallel::distributed::Triangulation<dim, spacedim> triangulation(MPI_COMM_WORLD);
  DoFHandler<dim, spacedim>                           dof_handler(triangulation);

  hp::FECollection<dim, spacedim> fe_collection;

  IndexSet locally_active_dofs;
  IndexSet locally_relevant_dofs;

  AffineConstraints<double> constraints;

  std::vector<unsigned int> repetitions({4, 2, 1});
  Point<dim>                bottom_left(-2, -1, 0);
  Point<dim>                top_right(2, 1, 1);

  GridGenerator::subdivided_hyper_rectangle(triangulation,
                                            repetitions,
                                            bottom_left,
                                            top_right);

  // hp-refine center part
  for (const auto &cell : dof_handler.active_cell_iterators() |
         IteratorFilters::LocallyOwnedCell())
    {
      cell->set_active_fe_index(1);

      const auto &center = cell->center();
      if (std::abs(center[0]) < 1.)
        {
          if (center[1] > 0.)
            cell->set_active_fe_index(2);
          else
            cell->set_refine_flag();
        }
    }

  triangulation.execute_coarsening_and_refinement();

  // set dofs
  for (unsigned int degree = 1; degree <= 10; ++degree)
    fe_collection.push_back(FE_Q<dim>(degree));
  dof_handler.distribute_dofs(fe_collection);

  const IndexSet &locally_owned_dofs = dof_handler.locally_owned_dofs();
  locally_active_dofs   = DoFTools::extract_locally_active_dofs(dof_handler);
  locally_relevant_dofs = DoFTools::extract_locally_relevant_dofs(dof_handler);


  constraints.reinit(locally_owned_dofs, locally_relevant_dofs);
  DoFTools::make_hanging_node_constraints(dof_handler, constraints);

  for (unsigned int p=0; p<Utilities::MPI::n_mpi_processes(MPI_COMM_WORLD); ++p)
    {
      if (p == Utilities::MPI::this_mpi_process(dof_handler.get_communicator()))
        {
          std::cout << "On process " << p << std::endl;
          std::cout << "  Number of DoFs:  " << dof_handler.n_dofs() << std::endl;

          std::cout << "  What this process believes about DoF 64:\n";
          for (const auto &c : constraints.get_lines())
            if (c.index == 64)
              for (const auto &entry : c.entries)
                std::cout << "    constrained against " << entry.first << " with weight "
                          << entry.second << '\n';
        }
      MPI_Barrier(dof_handler.get_communicator());
    }
}

int
main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  test<3,3>();
}
```

And here's the output with 2 MPI processes:
```
On process 0
  Number of DoFs:  409
  What this process believes about DoF 64:
    constrained against 3 with weight -0.123607
    constrained against 7 with weight 0.323607
    constrained against 19 with weight 0.8
On process 1
  Number of DoFs:  409
  What this process believes about DoF 64:
    constrained against 3 with weight -0.447214
    constrained against 7 with weight 0.447214
    constrained against 63 with weight 1
```

**Comment by marcfehling** [comment]
After a call of DoFTools::make_hanging_node_constraints() I get the following constraint line for the problematic DoF 64:

DoF 64 is a locally owned DoF on process 0:

    {index = 64, entries = std::vector of length 3, capacity 3 = {{first = 3, second = -0.12360679774997897}, {first = 7, second = 0.32360679774997891}, {first = 19, second = 0.80000000000000004}}, inhomogeneity = 0}

DoF 64 is a locally relevant DoF on process 1:

    {index = 64, entries = std::vector of length 3, capacity 3 = {{first = 3, second = -0.44721359549995798}, {first = 7, second = 0.44721359549995787}, {first = 63, second = 1}}, inhomogeneity = 0}

**Comment by bangerth** [comment]
Some more information:

* On process 0, the constraint is computed while processing a locally owned cell centered at `{-1.5, 0.5, 0.5}` whose 9 face DoFs are `{3, 28, 7, 30, 19, 38, 32, 35, 40}`.
* On process 1, the constraint is computed while processing a ghost cell centered at a different location, namely `{-0.5, 0.5, 0.5}`, whose face DoFs are `{3, 7, 164, 216, 51, 59, 63, 65, 79}`

That is suspicious, but perhaps not wrong -- DoF 64 is an edge DoF in 3d, and we can encounter it in different ways.

**Comment by bangerth** [comment]
I also checked that for a Q3 constrained against a Q2 element, the right weights are these:
```
  What this process believes about DoF 64:
    constrained against 3 with weight -0.123607
    constrained against 7 with weight 0.323607
    constrained against 19 with weight 0.8
```

**Comment by marcfehling** [comment]
> On process 1, the constraint is computed while processing a ghost cell centered at a different location, namely {-0.5, 0.5, 0.5}, whose face DoFs are {3, 7, 164, 216, 51, 59, 63, 65, 79}

For process 1, the cell at `{-0.5, 0.5, 0.5}` is the p-refined Q3 ghost cell. The face DoFs you mentioned must be on the face to the h-refined Q2 ghost cells in negative y-direction. However, only two of these cells are ghost cells themselves, the other two are _artificial_ cells.

How do we deal with this situation in `make_hanging_node_constraints()`?

**Comment by bangerth** [comment]
This must be a bug in the computation of constraints from a large Q3 cell to the DoFs of a neighboring refined cell with Q2 elements. This is the "difficult" case in the hp paper. We seem to be running into it in line 2697 in dof_tools_constraints.cc.

Let's see whether we can set up a test case for this situation alone.

**Comment by bangerth** [comment]
I think I've come to the conclusion that the code to compute the constraints is correct after all, but that we merge them incorrectly. Two MPI processes can legitimately compute different constraints for the same DoF, but after resolving chains, they must be the same. The merge process just gets this wrong. I know how to handle this, I think, but it will take a few days before I get to it.
