### ISSUE TITLE
Inconsistency in Tpetra Distributed Vector's `add()` function

### ISSUE THREAD

**Issue by QY-Shi** [dealii/dealii#17615]
**Description:**

While migrating from Epetra stack to Tpetra stack in my project, I encountered an issue related to distributed vectors.

**Problem:**

After assembling a non-ghost distributed vector (which allows writing to non-local entries), the program hangs when I call `my_vector.compress(VectorOperation::add)`.

**Potential Cause:**

I discovered that the inconsistency stems from `my_vector.compressed` across different processes. Specifically:

- On processes with only locally owned entries, the `Vector<Number, MemorySpace>::add()` function does not modify the internal `compressed` state.
- However, on processes with non-locally owned entries, `compressed` **is** modified, as in the [code snippet](https://github.com/dealii/dealii/blob/898bd72bf3a97852cf77f3eb1810d995127c5c09/include/deal.II/lac/trilinos_tpetra_vector.h#L1162C1-L1223C10) below from function `Vector<Number, MemorySpace>::add()`.
- 

```c++
          // Check if the index is in the locally owned index set.
          // If so, we can write right into the locally owned
          // part of the vector.
          if (TrilinosWrappers::types::int_type local_row =
                vector->getMap()->getLocalElement(row);
              local_row != Teuchos::OrdinalTraits<int>::invalid())
            {
              vector_1d_local(local_row) += values[i];
              // maybe missed a `compressed = false;` here?
            }
          else
            {
              // If the element was not in the locally owned part,
              // we need to figure out whether it is in the nonlocal
              // part. It better be:
              Assert(nonlocal_vector.get() != nullptr, ExcInternalError());
              TrilinosWrappers::types::int_type nonlocal_row =
                nonlocal_vector->getMap()->getLocalElement(row);


#  if DEAL_II_TRILINOS_VERSION_GTE(14, 0, 0)
              Assert(nonlocal_row != Teuchos::OrdinalTraits<int>::invalid(),
                     ExcAccessToNonLocalElement(
                       row,
                       vector->getMap()->getLocalNumElements(),
                       vector->getMap()->getMinLocalIndex(),
                       vector->getMap()->getMaxLocalIndex()));
#  else
              Assert(nonlocal_row != Teuchos::OrdinalTraits<int>::invalid(),
                     ExcAccessToNonLocalElement(
                       row,
                       vector->getMap()->getNodeNumElements(),
                       vector->getMap()->getMinLocalIndex(),
                       vector->getMap()->getMaxLocalIndex()));


#  endif


              // Having asserted that it is, write into the nonlocal part.
              // To do so, we first need to make sure that we have a view
              // of the nonlocal part of the vectors, since we have
              // deferred creating this view previously:
              if (!vector_1d_nonlocal)
                {
#  if DEAL_II_TRILINOS_VERSION_GTE(13, 2, 0)
                  auto vector_2d_nonlocal =
                    nonlocal_vector->template getLocalView<Kokkos::HostSpace>(
                      Tpetra::Access::ReadWrite);
#  else
                  auto vector_2d_nonlocal =
                    nonlocal_vector->template getLocalView<Kokkos::HostSpace>();
#  endif


                  vector_1d_nonlocal =
                    Kokkos::subview(vector_2d_nonlocal, Kokkos::ALL(), 0);


#  if !DEAL_II_TRILINOS_VERSION_GTE(13, 2, 0)
                  // Mark the nonlocal vector as to-be-modified as well.
                  nonlocal_vector->template modify<Kokkos::HostSpace>();
#  endif
                }
              (*vector_1d_nonlocal)(nonlocal_row) += values[i];
              compressed = false;
            }
```

This discrepancy leads to a hang during the vector compression, where an `if(!compressed)` condition seperate two different code paths on different processes.

**Comment by QY-Shi** [comment]
If this is indeed the case, I'll submit a PR ASAP.

**Comment by QY-Shi** [comment]
Additionally, I’ve noticed several [discussions about](https://github.com/dealii/dealii/pull/16290) ghost/read-only vectors, but it seems a unified solution hasn’t been reached yet. I’d like to first share my understanding of distributed vectors, and please correct me if I’m wrong. In my finite element application, I require three types of distributed vectors:

1. **Pure Locally Owned Distributed Vector** (read-write but only readable and writable to local entries): This can be used as the `x` and `b` in a linear system `Ax = b`.
2. **Pure Ghosted Distributed Vector** (read-only, cannot be written to, can be assigned from a pure locally owned distributed vector): Since I’m solving implicit problems, I need to extract the locally relevant part of the solution vector `x`on locally owned cells when assembling the Jacobian matrix. Therefore, I need an `x_ghosted` vector to hold these values, which will be assigned from `x_locally_owned` using the `operator=`.
3. **Locally Owned Distributed Vector with the ability to write into non-locally-owned entries** (read-write, and writable to non-locally-owned entries): These vectors are typically used in finite element assembly, for example, when assembling the system RHS. They can also serve as `x` and `b` in `Ax = b`.

However, I’ve found that in the current PETSc wrapper, types 1 and 3 are actually used interchangeably. When I create a locally owned vector using `reinit(locally_owned_index_set, mpi_comm)`, it can satisfy the needs of both type 1 and type 3 vectors. The same applies to the Epetra vector wrapper.

But this is not the case for Tpetra vectors. For type 1 vectors, I only need to provide the locally owned index set. For type 2 and 3 vectors, I need to provide both the locally owned and locally relevant index sets and use a new boolean parameter `vector_writable` to determine whether it should behave as type 2 or type 3. Additionally, in the current Tpetra wrapper implementation, assigning from a type 1 vector to a type 2 vector using `operator=` works as expected. However, assigning from a type 1 vector to a type 3 vector is not possible because the current `operator=()` function does not modify the `nonlocal_vector` in any of the three scenarios it handles.

While I’m very satisfied with the current PETSc vector wrapper and Tpetra vector wrapper APIs, I believe it would be beneficial to unify them in the future.

Given this, I’m curious if there are any plans to change the Tpetra vector interface. With the introduction of `Tpetra::FEMultiVector` in #17196 , will the current approach of managing locally owned and locally relevant entries through two internal vectors (`vector` and `nonlocal_vector`) change? Maintaining and synchronizing two distributed vectors manually seems cumbersome and prone to errors : (

**Comment by bangerth** [comment]
@kinnewig and @jpthiele -- this may be a question for you.

**Comment by bangerth** [comment]
For the record, I think you're exactly right that we also need to clear the `compressed` member variable for vectors that happen to have no ghost elements. A patch would be appreciated, along with a test that shows that the issue is fixed. Let us know if you need help for either!

**Comment by kinnewig** [comment]
Thank you for the detailed problem description; although I already use the Tpetra wrappers a lot, I have not encountered that problem. However, I agree that the Issue needs to be fixed as soon as possible.

I am quite swamped at the moment, so would you like to give it a try? Otherwise, it could take a few days until I find the time to fix that.


And about the unification of the PETSc/Tpetra interface: This may not be as straightforward as it looks at first glance. I am not an expert on PETSc, but as far as I know, Tpetra has a different design philosophy from PETSc. The concept of ghosted (in Tpetra terms: [owned+shared](https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1FECrsGraph.html#details)) and non-ghosted (only owned) vectors, matrices, and index sets is directly implemented into Tpetra itself. The current state of the Tpetra Interface does not yet use its full potential. But this difference could make it quite cumbersome to unify the Tpetra and PETSc interface more.

**Comment by QY-Shi** [comment]
> I am quite swamped at the moment, so would you like to give it a try? Otherwise, it could take a few days until I find the time to fix that.

Sure, I’ll write a patch! It’s just a single line change, though. I’ll also add a test—but I need to familiarize myself with how the testing framework works, especially for multi-process tests.

> And about the unification of the PETSc/Tpetra interface: This may not be as straightforward as it looks at first glance. I am not an expert on PETSc, but as far as I know, Tpetra has a different design philosophy from PETSc. The concept of ghosted (in Tpetra terms: [owned+shared](https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1FECrsGraph.html#details)) and non-ghosted (only owned) vectors, matrices, and index sets is directly implemented into Tpetra itself. The current state of the Tpetra Interface does not yet use its full potential. But this difference could make it quite cumbersome to unify the Tpetra and PETSc interface more.

Got it, I’m fine with both paradigms, looking forward to the `FE-` version of matrix and vectors!
