### ISSUE TITLE
embrace semantic versioning and formalize deprecation

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1762]
I would like to start a discussion about software versioning and formalize how we handle deprecation.

I believe adhering closer to the semantic versioning standard (see http://semver.org/) would be a good idea. While I think you should read about it, the summary is:
- Version is "X.Y.Z" or "X.Y.Z-something", no exceptions.
- For a release, you have to increment Y if there are new features and X if there are backwards incompatible changes. Z is for bugfixes.

Things we would need to change:
- do not refer to an 8.3 release but always talk about 8.3.0
- call it 8.4.0-pre instead of 8.4.pre (and "8.4.0-rc1" etc.)
- go from 8.x to 9.0.0 if we remove (deprecated) functionality or break things

For deprecation I would like to suggest that we keep the deprecation markers around for one release (excluding bugfix releases) and then try to remove the functionality. I think we have been doing this already (except keeping things around for longer). I wonder if it makes sense to mark each deprecation in the future to make sure we won't remove it too early?

Thoughts?

**Comment by bangerth** [comment]
I think we have typically done the "deprecate, wait one release, remove for the second next release" in the past. Sometimes it has taken much longer, of course. I have frequently thought that we should implement `DEAL_II_DEPRECATED` with an argument that indicates the *first* release where the function was deprecated. This was too much work in the past, also because I didn't know when many functions were first marked for deprecation. But it should be more straightforward now, after the many functions and classes I removed earlier this year.

As for having to increase X if you remove deprecated features (or are otherwise incompatible), I think this is too rigid a rule. I believe that we need to take into account the *degree* of incompatibility. If we remove a rather obscure feature, I don't see a need to make this an X.0.0 release. If we change the semantics of parallel vectors, then I think there's a much better case to be had here.

**Comment by bangerth** [comment]
I'd also like to point out that "incompatible change" is a very broad category if considered at the API level. For example, adding a defaulted argument to an existing function is incompatible, as you will find when you try to take the address of a function and assign it to a variable of a specific type. Likewise, changing the order of kind of template arguments of a function, even if the function argument list remains the same, is also incompatible. We have traditionally been pretty liberal with such changes, though they are strictly speaking incompatible.

**Comment by tjhei** [comment]
> I'd also like to point out that "incompatible change" is a very broad category if considered at the API level. 

Yes and if you go with the strict definition, you would have an incompatible change if your output changes by +/- epsilon in some floating point value even if the API stays the same.

> As for having to increase X if you remove deprecated features (or are otherwise incompatible), I think this is too rigid a rule.

But is it really a big problem if every major release we currently do is a ++X release? It is just a different numbering after all. :-)

In general I agree, using good judgement about incompatible changes, etc. makes sense.

**Comment by bangerth** [comment]
On 10/18/2015 05:24 PM, Timo Heister wrote:
> But is it really a big problem if every major release we currently do is a ++X
> release? It is just a different numbering after all. :-)

No, it wouldn't be a problem. It would simply mean that we never do X.1.0 
releases. I also don't quite think that it addresses the problem in the 
correct sense. The document you link to after all is called "*semantic* 
versioning" which seems to imply a sense a "meaning", not just "rules".

I think that in practice, we have mostly been doing already what the document 
suggests. I'm not opposed to codifying this.

**Comment by tamiko** [comment]
The biggest problem with all of those API and ABI level versioning schemes is that you easily screw up with C++ - basically every release we do would be an increase of the major version number.

If we relax the requirements to be usable for us we are (a) back to our current versioning policy, and (b) we should not call it "semantic versioning" any more.

I am in favor of renaming our pre release versions and release candidates to X.Y.Z-[pr|rc?] independently of this discussion. This gives us way more flexibility.

**Comment by bangerth** [comment]
> I am in favor of renaming our pre release versions and release candidates to X.Y.Z-[pr|rc?] independently of this discussion. This gives us way more flexibility.

This makes good sense, regardless of all of the other points.

**Comment by bangerth** [comment]
I think we all agree with the principles stated herein, but nobody seems overly excited to formalize things beyond what we already do in practice.
