### ISSUE TITLE
Rename ReadWriteVector to ReadWriteVectorView

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1765]
The new `ReadWriteVector` class really represents a "view" of such a vector since it only stores a subset of elements. Does anyone feel strongly about making this part of the name of the class?

**Comment by kronbichler** [comment]
From my *semantic* point of view, 'View' refers to some lightweight-wrapper of a class around memory controlled by someone else as done by `VectorView`. `ReadWriteVector` does (at least in the base version) control the memory on its own, so modification in the `ReadWriteVector` does not translate to changes in the data structure the view was created from. This makes the term view used here inconsistent with `VectorView` (and the Epetra/Teuchos naming scheme in Trilinos). (But it would be consistent with our `IndexSet::get_view`.) Along those semantics, ReadWriteVector rather represents some form of a processor-related *local copy* of the data. Anyway, my interpretation of view might be overly biased by what a view represents in Trilinos.

Another point is the pure length of ReadWriteVectorView<Number>. It is a vector that is probably used in many places, so I would only add another four letters if we gain in readability/comprehension.

**Comment by bangerth** [comment]
All good points. Thanks for the feedback!

**Comment by bangerth** [comment]
Related to #745
