### ISSUE TITLE
Rename SmartPointer<T> to ObserverPointer<T>.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17657]
I have long thought that the name `SmartPointer` is poorly chosen because (i) the class is not actually smart, (ii) smart pointers are generally thought of as ones that manage the lifetime of objects, like `std::unique_ptr` and `std::shared_ptr`, (iii) "smart" is an adjective that does not actually convey *what* it is the class does.

What the class does is *observe* another object, without managing it. There was a proposal once to add a class `std::observer_ptr` (https://stackoverflow.com/questions/31862412/use-of-observer-ptr, added to the standard at one point but removed again after opposition from well-regarded people https://open-std.org/JTC1/SC22/WG21/docs/papers/2019/p1408r0.pdf). That class would simply have been an alias to `T*` that conveys what it does by way of its name. I don't like that approach. I think what `SmartPointer` does is better, using a reference counter in the base of `T`. I'm just looking for a better name that conveys what the class does -- namely, *observe*.

**Comment by kronbichler** [comment]
I like this name and hereby express my support to such a change.

**Comment by drwells** [comment]
We can definitely learn something from `std::observer_ptr`. The following compiles:

```cpp
#include <deal.II/base/subscriptor.h>
#include <deal.II/base/smartpointer.h>

int main()
{
    using namespace dealii;

    Subscriptor a;

    SmartPointer<Subscriptor> a_pointer(&a);
    delete a_pointer;
}
```
we should fix that!

**Comment by bangerth** [comment]
I'm definitely cool with different names. As for being able to `delete` objects through `SmartPointer` -- how does `std::observer_ptr` avoid that? I don't see it having a `=delete`d `operator delete` or some such at https://en.cppreference.com/w/cpp/experimental/observer_ptr,

If we're renaming things: How would we rename `Subscriptor`? Perhaps `EnableObserverPtrRefCounting` in light analogy to `std::enable_shared_from_this` (https://en.cppreference.com/w/cpp/memory/enable_shared_from_this)?

I will note that I have been toying with the idea of making the class work with class derived from `Subscriptor` and also for those not so derived. We can essentially do something like this:
```
  ObserverPointer::ObserverPointer (T *t) {
    if constexpr (T is derived from Subscriptor) {
      ...do as we do currently...
    } else {
      ...well, we can't track usage via a use counter, but at least the name of the class represents an observer...
    }
  }
```

**Comment by drwells** [comment]
Stroustrup's paper remarked that `std::observer_ptr` cannot be deleted but I suppose the implementation never made it that far. Here is a possible implementation for us:
```cpp
struct A
{
void operator delete(void*) noexcept = delete;
};


int main() {

    auto *a = new A;
    delete a; // fails to compile
}
```

It's mostly a matter of preference, but I'd prefer not to introduce that behavior into `Subscriptor` because it makes it appear as though it is doing error-checking in cases (when it points to a non-`Subscriptor`) where it is definitely not doing error-checking.

**Comment by drwells** [comment]
I fixed the typo.

Yes, we only support subscribing to things which inherit from `Subscriptor` - I'd prefer to keep it that way. Feel free to write such a patch!

**Comment by tamiko** [comment]
In order to avoid a second `AffineConstraints` incident we will need to keep an alias template around to make the name `SmartPointer` available again for quite a while.

**Comment by bangerth** [comment]
Yes, that should be easy to achieve. I suspect that these classes are not widely used in user codes, though.

**Comment by bangerth** [comment]
Regarding the issue of `operator delete()`, and as mentioned in #17676, this is not so easy. For example, this code does not compile:
```
#include <string>
#include <memory>

class Ptr
{
public:
  void operator delete(void *) noexcept = delete;
private:
  std::string id;
};

int main()
{
  std::unique_ptr<Ptr> u = std::make_unique<Ptr>();
}
```
Similarly, you can't put `Ptr` objects into `std::any`. In essence, I don't think we can `=delete` the `operator delete()` of the class without disallowing otherwise entirely legitimate uses of `SmartPointer` :-(

**Comment by bangerth** [comment]
Let me re-open this issue to remind myself that I want to rewrite the documentation of the `EnableObserverPointer` class.
