### ISSUE TITLE
SVG images in tutorials are broken on website

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#17667]
see https://www.dealii.org/developer/doxygen/deal.II/step_2.html#step_2-Results for example

**Comment by bangerth** [comment]
This seems to work for me: 
![image](https://github.com/user-attachments/assets/a204c121-670c-4d82-b403-704f67decc63)
How does it look for you?

**Comment by masterleinad** [comment]
It seems the sparsity pattern pictures are missing/invisible.
