### ISSUE TITLE
Improve implementation of TaskFlow-based implementation of WorkStream.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17694]
As mentioned in #17642, the current implementation of the colored `WorkStream` implementation uses the approach
```
  TaskGraph graph;
  for (color : colors)
    {
       build graph for this color / set up the parallel-for
    }
    execute the graph
```
This creates quite large graphs, and we also have to wait until the whole graph is built for it to execute its first task. A better scheme would break this into smaller portions:
```
  for (color : colors)
    {
       TaskGraph graph;
       build graph for this color / set up the parallel-for
       execute the graph
    }
```
An even better scheme might start to build the graph for the next color while the current color is running, wait for the current color to finish, and start the next color.

@RyanMoulday FYI

**Comment by RyanMoulday** [comment]
I will work on making these changes in the very near future. I think two valid approaches to achieving the desired result of working on the next task graph while executing the previous one are to:

1. Add the generation of the next task graph as a "high priority" task to the current color's task graph so it is worked on immediately when execution of the current color begins.

2. Call executor.run(tf) without yielding, then build the next task graph in the current thread and add a yield to the associated tf future after the next color's graph is constructed.

My initial preference is option 2 as it seems more natural. Though I think it may involve an extra active thread as the executor will spawn the desired multithreading concurrency number of threads plus the now non-yielded master thread.

**Comment by bangerth** [comment]
Yes, idea 2 seems more natural.

**Comment by bangerth** [comment]
The step with the `std::move(taskflow)` here https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ExecuteATaskflowWithTransferredOwnership seems like the right approach. You can re-use the same `taskflow` object for the next color this way.

The function is documented here: https://taskflow.github.io/taskflow/classtf_1_1Executor.html#a4bbef53618db1852003a0cd1e1e40c50

**Comment by tjhei** [comment]
Yes, approach 2 makes sense.
So, you the code would look like this:

For each i:
1. Create color i (without running)
2. Wait on future to finish color i-1 (if i>0)
3. run color i without blocking, creating a future

Finally wait for the future before exiting.
