### ISSUE TITLE
Make AffineConstraints::make_consistent_in_parallel() more efficient, part 2.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17692]
@marcfehling did some benchmarking and found that the `find_if()` calls in https://github.com/dealii/dealii/blob/4cf7a02c4f779398e4528a986a130c3dd9f11f27/include/deal.II/lac/affine_constraints.templates.h#L490-L495 are extraordinarily expensive. That's because for each index in an index set, we do a `find_if()` search through the `locally_relevant_constraints()` array, which implies a linear search.

This can be done better. First, we should make sure that `locally_relevant_constraints` is a sorted array. Then one could use `std::binary_search()` instead of `std::find_if()`. Second, the `index` we are searching for comes from a sorted set (an `IndexSet` object), so it is an increasing set of numbers and if `locally_relevant_constraints` is also sorted, we don't even have to start the binary search from the top every time, but can start from the point where it stopped previously.

Both of these things should bring the cost down from O(N*M) to O(N*log(M)) at most.

@peterrum @kronbichler @marcfehling FYI.

**Comment by peterrum** [comment]
> Both of these things should bring the cost down from O(NM) to O(Nlog(M)) at most.

No, it is O(N) or O(M).
