### ISSUE TITLE
Break out a part of the ComputeIndexOwner::ConsensusAlgorithmsPayload functionality.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17703]
The `Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmsPayload` forms the basis of what `Utilities::MPI::compute_index_owner()` does. For the latter function, one can specify a locally-owned index set `LO` and a different index set `A`, and it returns for each index in `A` which process owns it.

But the `ComputeIndexOwner::ConsensusAlgorithmsPayload` class also allows, as a side effect, to query who inquired. This is used in the algorithm we've been rewriting in consequence of #17599 where each process needs to figure out which other process has one of our own locally owned DoF in its locally-relevant set. The way this is done is by running the main "compute index owner" algorithm, and then querying the side effect. This works, but it is not particularly obvious what the code is in that context (for example because we, confusingly, don't even use the *main* function's result) -- thus the extensive commentary I'm adding in #17702.

A better approach would be to break this functionality out into a function of its own, alongside `Utilities::MPI::compute_index_owner()` so that we can give the approach a proper name. I just don't know what a good name would be. 

Perhaps `Utilities::MPI::compute_ghost_ranks_for_locally_owned_indices()`? Other suggestions?

@peterrum @kronbichler ?

**Comment by peterrum** [comment]
I guess we could have second version of `compute_index_owner` that returns a tuple. The code would look like

```cpp
    std::pair<std::vector<unsigned int>, std::map<..., ...>>
    compute_index_owner_and_requesters(const IndexSet &owned_indices,
                        const IndexSet &indices_to_look_up,
                        const MPI_Comm &comm)
    {
      Assert(owned_indices.size() == indices_to_look_up.size(),
             ExcMessage("IndexSets have to have the same sizes."));


      Assert(
        owned_indices.size() == Utilities::MPI::max(owned_indices.size(), comm),
        ExcMessage("IndexSets have to have the same size on all processes."));


      std::vector<unsigned int> owning_ranks(indices_to_look_up.n_elements());


      // Step 1: setup dictionary
      // The input owned_indices can be partitioned arbitrarily. In the
      // dictionary, the index set is statically repartitioned among the
      // processes again and extended with information with the actual owner
      // of that the index.
      internal::ComputeIndexOwner::ConsensusAlgorithmsPayload process(
        owned_indices, indices_to_look_up, comm, owning_ranks, true);


      // Step 2: read dictionary
      // Communicate with the process who owns the index in the static
      // partition (i.e. in the dictionary). This process returns the actual
      // owner of the index.
      ConsensusAlgorithms::Selector<
        std::pair<types::global_dof_index, types::global_dof_index>,
        unsigned int>
        consensus_algorithm(process, comm);
      consensus_algorithm.run();

      return {owning_ranks, process.get_requesters()};
    }
```

What do you think? I can create a PR?

**Comment by bangerth** [comment]
Yes, that too could work! If you wanted to write a patch, that would be appreciated!

**Comment by bangerth** [comment]
Is there anything that can be saved if one doesn't actually need the `owning_ranks`? The example in `AffineConstraints` does not need them. Nor does the use in `extract_remote_rows()` in `sparse_matrix_tools.h`. (Not arguing againt the patch mentioned above, since there are places where we use both return values. Just saying that there are places where we don't.)

**Comment by bangerth** [comment]
This is almost finished. After #17845, I will move everything that now lives in the header files into the `mpi.cc` file as that's the only place where the old interface is still used.
