### ISSUE TITLE
`SmartPointer` compatibility

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17713]
With the changes in #17689 we no longer (transitively) include `base/smartpointer.h` in our header files.

This poses a problem for older user codes based on deal.II that do not include the `base/smartpointer.h` header file directly but instead relied on the definition being already available after including just about any other deal.II header file...

In order to reproduce this issue just check out any example step using a `SmartPointer` / `ObserverPointer` from version 9.6.0 and try to compile it against current master.

We should really fix this... because it puts user codes into a very awkward spot. (It is too early to migrate to `ObserverPointer` because one loses backward compatibility and it is very annoying to add the missing include everywhere. Furthermore, it is not *obvious* that the include is missing).

We should really fix this.

**Comment by bangerth** [comment]
I know how to fix this. Patch coming soon.

**Comment by tamiko** [comment]
@bangerth Merci!

**Comment by bangerth** [comment]
It was a quick fix!
