### ISSUE TITLE
Set up master as a protected branch

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#1771]
@bangerth wrote, in an email:

Actually, the reason is that it's so easy to mess up a git repository if you allow people to directly push into it. Someone always seems to be behind the current master, can't seem to push, and then tries a "git push -f" -- which will then throw away all of the commits that had been merged in the meantime since that person last updated their local clone. Other scenarios are where patches would just be added to the top, instead of via a merge, confusing some of our scripts. Best not to get ourselves into such situations by only allowing merges via the web interface by policy.

I believe we can actually forbid this by going into `options -> branches -> protected branches` and setting up master as 'protected'. I see no reason not to do this since we want this behavior and are enforcing it by policy anyway. Thoughts?

**Comment by davydden** [comment]
+1. 

For the sake of convenience, here's a description:
```
Protect branches to disable force pushing, prevent branches from being deleted, and optionally require status checks before merging.
```

**Comment by tjhei** [comment]
Sensible. I just enabled it. (but not requiring the tests to pass)
