### ISSUE TITLE
deprecate/remove parallel::transform()

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#17811]
It looks like the ``parallel::transform`` function was added in 2009 (or earlier?) by @bangerth and is not used in the library or the examples. @gassmoeller noticed that the iterator type in the implementation is incorrect as well (the case without TBB):
https://github.com/dealii/dealii/blob/e390a5d41295f038cface07853107c0de7ca3a04/include/deal.II/base/parallel.h#L176C10-L176C24

My vote would be to deprecate and remove. I will open up a PR unless somebody disagrees.

**Comment by bangerth** [comment]
Yes, sounds good. I bet we used to use this somewhere but have found better ways of doing this. Let's get rid of it then.
