### ISSUE TITLE
Feature: pre-commit config

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#17860]
[pre-commit](https://pre-commit.com/) is a pretty nice tool to install git hooks through a simple YAML configuration file on the local repo.

The main use case would be to have it run `clang-format`
every time you call `git commit`.

The tool is completely opt-in, so no one will be forced to use or install it.
If not, the config yaml simply exists as a hidden file.

I would set it up locally for me anyways, so I'd be happy to do a PR for it
so other people can easily use it as well.

**Comment by bangerth** [comment]
Is this fixed with #17893?

**Comment by jpthiele** [comment]
yes, closing
