### ISSUE TITLE
GitHub tarballs don't contain testsuite which makes it difficult to test releases - please consider leaving testsuite in the release tarballs

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#17951]
Due to [these lines](https://github.com/dealii/dealii/blob/master/.gitattributes#L17) in .gitattributes the tests directory doesn't contain tests in release tarballs which makes it difficult to test releases.

Could you please consider removing these lines to allow release testing?

Thank you,
Yuri (maintainer of the FreeBSD port math/deal.ii)

**Comment by drwells** [comment]
The tests folder is huge (about 300 MB) and takes hours to run - as a compromise we ship the quick tests, which verify that dependencies and basic functions are linked and run correctly without checking for regressions.

Does that cover your use case?

**Comment by yurivict** [comment]
> Does that cover your use case?

Yes. How to run them?

**Comment by tamiko** [comment]
No, we do indeed have a problem: We accidentally removed `tests/CMakeLists.txt` as well. But we need that file for the top level target `test`. I need this for the debian package as well.

So, another point release it will be.

@yurivict Normally simply by running `make test`.

**Comment by drwells** [comment]
@yurivict Do things work correctly with 9.6.2?

**Comment by yurivict** [comment]
Quick tests run now, thanks!
