### ISSUE TITLE
Test pull requests before merge

### ISSUE THREAD

**Issue by guidokanschat** [dealii/dealii#1803]
The current testing workflow nicely attests that the library is broken, if things went wrong.

This is not a satisfactory method and we should test pull requests before the merge.

I will upload a python script accessing milestones and labels later. Seemingly, they can only be changed by people with write access, so we could use them as a way to approve running tests.

Suggestion for a workflow:
1. When one of the developers has checked the PR for sanity, set Milestone to "Run tests"
2. Test script detects this and runs the test. If we use a single tester, we could change the milestone to "Tests running". If we test on Mac as well, we should not and have to store tested versions on the test server.
3. Report on tests:
   - upload tests to CDash with PR identification
   - test server can leave comment to PR
4. Another option is running tests as part of the merge. Then, we would assign the milestone after the discussion is finished and the test server could merge (using rebase!) after the tests have finished successfully.

**Comment by davydden** [comment]
1-3 sounds good to me! 

I would would not go for 4. as there could be scenarios where some tests do not pass at the moment and those failures are not related to the PR anyhow. Therefore, i think it's better to leave the `merge` decision to a human, who can examine the test results in CDash and make a conscious judgment that the PR does not break anything.

**Comment by tjhei** [comment]
Guido,

good idea! I hope you have seen the work I have done for ASPECT, which is very similar. See the pull requests for example: https://github.com/geodynamics/aspect/pulls See the little commit markers?

I have a machine set up to automatically run on every pull request and set the continuous integration status. Merging is done manually, but you get a big warning in the UI if you try to merge even though tests fail. The tester currently runs in three configurations and uploads a summary and individual results. See http://www.math.clemson.edu/~heister/aspect-logs/b36ef1a89445ce003f8cd8e2295e225607a00f35/ for example (this is linked from the commit status). Results are also uploaded to cdash. Sadly there is no way to pull down a link automatically, but you can find them easily (see http://cdash.kyomu.43-1.org/index.php?project=aspect where the buildname contains the pullrequest number).

The tests are run inside a docker container, code from unknown users is only tested if a hot-word from trusted developers is set, and there are a bunch of other features.

The code is here: https://github.com/tjhei/gitautotester/tree/officialtester

You basically only replace a few settings inside config.py and create your own test.sh to run the tests. Everything else is handled by the script.

One thing worth noting is that I currently check out and test the pullrequest and not master with the pullrequest merged in (which is different!). I haven't bothered changing that though.

**Comment by bangerth** [comment]
I'd like it if we had a workflow where we don't have to go visit a pull request twice, once to review and once later to merge when the tests are finished. Most of the PRs we have are quite obvious and I'd like to merge it the same time I review, so either
* the tests need to start running more or less immediately the PR is created, or
* I can leave a comment of the form `/approve` or similar that starts a test script that immediately merges a pull request if tests have run and have succeeded.

Of course, all of this is moot if we merge patches that break BDM tests that then sit unfixed for months :-(

**Comment by bangerth** [comment]
(The same is true for patches that break symmetric_tensor_25.)

**Comment by tjhei** [comment]
It would take a few minutes to modify my tool to only act on PRs that got "/approved". If somebody gives me access to a spare machine with internet access and a cronjob, I can set something up like we do for ASPECT.

**Comment by tamiko** [comment]
> (The same is true for patches that break symmetric_tensor_25.)

Thanks for the reminder.

**Comment by asartori86** [comment]
do you think that compile the library on travis-ci could be useful even though the complete test suite cannot be run due to time limitation?

**Comment by davydden** [comment]
I would say yes, espetially if one can have bare-bones dealii (no petsc, slepc, trilinos, etc) and full suite.

**Comment by asartori86** [comment]
on travis we could compile the bare library with 2 different compilers (clang and gcc) with and without mpi so 4 different compilations in parallel (it takes almost 35 minutes)

**Comment by davydden** [comment]
i think that would be useful to catch up some minor bugs.
