### ISSUE TITLE
sharedtria tests fail

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1818]
@davydden -- the sharedtria tests currently fail, see for example http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=14040

I don't know whether that is a result of the artificial cell patches because the tester didn't run for a few days. Do you have any insights?

**Comment by davydden** [comment]
i could imaging the newly introduced tests (dof_03/dof_04/tria_02) could fail due to parmetis and its partition dependency on platform/etc, but the fact that dof_01/02 fail is indeed strange, especially with a segmentation fault.

I will try to run then locally....

**Comment by davydden** [comment]
current master (31b699d1e94bb42632b00ffe471a292e3a069840) locally leads to failing: tria-01, dof_03 (diff) whereas dof_01/02 are indeed SEGV... I'll check if it's related to the PR https://github.com/dealii/dealii/pull/1674

**Comment by davydden** [comment]
those SEGV are in `:ParallelShared<2, 2>::renumber_dofs`
```
-> 1245         number_cache.locally_owned_dofs =
   1246           number_cache.locally_owned_dofs_per_processor[dof_handler.get_tria ().locally_owned_subdomain ()];
```
when run with >1 processor...

**Comment by davydden** [comment]
i think i have an idea...

**Comment by davydden** [comment]
ok, i fixed SEGV errors. Given the fact that result of parmetis is quite unpredictable and currently on my mac i have the following tests failed due to diffs
```
The following tests FAILED:
	  1 - sharedtria/dof_01.mpirun=3.debug (Failed)
	  2 - sharedtria/dof_01.mpirun=3.release (Failed)
	  3 - sharedtria/dof_02.mpirun=3.debug (Failed)
	  4 - sharedtria/dof_02.mpirun=3.release (Failed)
	  5 - sharedtria/dof_03.mpirun=3.debug (Failed)
	  6 - sharedtria/dof_03.mpirun=3.release (Failed)
	  9 - sharedtria/tria_01.mpirun=3.debug (Failed)
	 10 - sharedtria/tria_01.mpirun=3.release (Failed)
```
I propose to get rid of that output and just check that it runs, plus some Asserts.

**Comment by bangerth** [comment]
It's the middle of the night in Germany. You should be sleeping and/or be with your family :-)

**Comment by davydden** [comment]
:-)

**Comment by bangerth** [comment]
I was actually kind of serious ;-)
