### ISSUE TITLE
Spawning tasks in FESystem::compute_fill results in slower code

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#1830]
FESystem::compute_fill spawns tasks when letting each individual element do the compute fill operation individually (line 1252 of source/fe/fe_system.cc). When nested inside a parallel assembly region (e.g. with WorkStream), the sub-tasks get deferred to different threads and reduce performance.

Here is some performance data from DataOut::build_patches (not the heaviest function but a context where it makes sense). The system is a 2x14 core Xeon processor.
```
n_cores   | generic  | less alloc  |  no tasks FESys | alloc + tasks
1         | 17.1s    | 15.3s       |  11.7s          |  8.18s
7         | 3.12s    | 2.55s       |  1.67s          |  1.20s
14        | 1.94s    | 1.96s       |  0.98s          |  0.69s
28        | 2.72s    | 1.93s       |  1.07s          |  0.68s
56        | 2.45s    | 1.96s       |  0.83s          |  0.51s
```
The interesting comparison is column 2 (generic) and column 4 (I disabled the tasks in FESystem). The performance is clearly better in the latter case. I must admit I was a bit surprised that it did matter quite a lot already in single-threaded mode. But more importantly scaling is much better. The speedup is more than twice better. (The third and fifth column will be reported separately.)

**Comment by bangerth** [comment]
Will take care of this. The same applies to `FESystem::get_data()`: using multiple tasks likely allocated memory in the `InternalData` object that is spread across multiple NUMA domains, when what we really wanted in contexts like `WorkStream` is to allocate things thread-locally.
