### ISSUE TITLE
Install issue with latest deal.II

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#1840]
Freshly downloaded, new build directory, cmake 3.3.1:
~~~
CMake Error at source/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/heltai/src/dealii/build-detached/source/CMakeFiles/CMakeRelink.dir/libdeal_II.g.so.8.4.0-pre".
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)
~~~

**Comment by luca-heltai** [comment]
This apparently only happens if one uses a particular combination of ninja, cmake, gcc and gentoo...

I went around the issue by using make...

**Comment by bangerth** [comment]
I hope it's not the `ninja` part of the combination -- I've really grown attached to that program...

**Comment by tamiko** [comment]
> This apparently only happens if one uses a particular combination of
> ninja, cmake, gcc and gentoo...
                    ~~~~~~~~~~

Mind to share some details (private mail)? [1] :-D

Best,
Matthias

[1] The Gentoo developer in me is curious.

**Comment by luca-heltai** [comment]
@tamiko , sure. What do you want to know?
