### ISSUE TITLE
Discussion: remove FiniteElement::shape_*

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1862]
Here's a question for everyone:

The `FiniteElement` class defines abstract virtual functions `shape_value`, `shape_value_component`, `shape_grad`, and higher order derivatives. These functions only return something that is defined on the reference cell, and so are not typically of much use, with the possible exception of the shape values themselves. On the other hand, for some elements, even the values are defined on a concrete cell rather than the reference cell (e.g., the `FE_DGP_Nonparametric` elements) and so all of these functions cannot possibly return useful values.

Should we remove them? Does anyone see value in these functions (as part of the public interface)?

**Comment by davydden** [comment]
i do use them to precompute Legendre trasform matrices on the reference element and then use this expansion for hp-estimation. I believe the same is done for Fourier expansion in the only hp-related tutorial.

**Comment by bangerth** [comment]
One of my recent patches documented the functions to indicate that they are only useful if the element is parametric. I think this closes the issue.
