### ISSUE TITLE
Guard clang test for -Wa,--compress-debug-sections with -Werror

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1876]
As reported on the mailing list, we use `-Wa,--compress-debug-sections` if clang allows it, but if a system has no zlib installed, then clang will produce a warning every time a file is compiled. That's annoying.

We should run the test for this flag with `-Werror` which makes sure that we test that clang doesn't just accept the flag, but in fact also uses it.

**Comment by bangerth** [comment]
The check for this flag resides in `cmake/checks/check_01_compiler_features.cmake` in line 281:
```
  ENABLE_IF_SUPPORTED(DEAL_II_CXX_FLAGS_DEBUG "-Wa,--compress-debug-sections")
```
Through the current interface, we can't actually make sure we pass `-Werror` when testing for flags. I think my preference would be if we added `-Werror` already in this macro -- where, upon closer look, it actually already resides since September 2015:
```

MACRO(ENABLE_IF_SUPPORTED _variable _flag)
  #
  # Clang is too conservative when reporting unsupported compiler flags.
  # Therefore, we promote all warnings for an unsupported compiler flag to
  # actual errors with the -Werror switch:
  #
  IF(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    SET(_werror_string "-Werror ")
  ELSE()
    SET(_werror_string "")
  ENDIF()
```
It's not clear to me why this didn't work for the bug reported here.

@tamiko -- do you see anything obvious?

**Comment by bobmyhill** [comment]
I've just installed deal.ii (8.3.0) on my Mac (OS X El Capitan), and I get this same problem with the home-brew install of deal.ii. *However*, my own build from the github source (8.4.0-pre) works fine. I have Xcode installed on top of the basic Mac install of all the command line tools - I don't know whether that has made a difference.

**Comment by davydden** [comment]
could that be that this test is not there in 8.3.0? in other words, if you install the `HEAD` version (`brew install dealii --HEAD`), then it should be equivalent to the self-compiled one.

**Comment by bobmyhill** [comment]
@davydden excellent point; you're quite right. Thanks!

**Comment by bangerth** [comment]
So do I see it right that the check with `-Werror` simply wasn't there with 8.3, consequently caused the warnings for the user, but has since been added, and should consequently no longer cause these warnings?

In that case, we should simply close this issue. I just have no way of testing to see whether the issue is really fixed.

**Comment by tamiko** [comment]
*ugh* I think we had ```-Werror``` already in place for the 8.3.0 release. I don't understand.

**Comment by bobmyhill** [comment]
@bangerth At least for me, 8.3.0 throws up loads of these errors, but 8.4.0 (homebrew or my own compile) is fine. So, issue solved? <shrugs>

**Comment by davydden** [comment]
indeed, `-Werror` is introduced in https://github.com/dealii/dealii/commit/50d09f5de342d515d9de22f2f07dbc8fe173d3d0 , which is in 8.3.0. But there is also this commit https://github.com/dealii/dealii/commit/6604061a09651f22a7d86b085c59e820d9c3f544 which has `PUSH_CMAKE_REQUIRED("-Werror")`. Could that be the reason? Otherwise, i see no relevant changes to `check_01_compiler_features.cmake` that could make a difference between 8.3.0 and current master...

**Comment by bangerth** [comment]
Even if we don't exactly understand *why* it may be fixed, let's just close the issue unless someone can unambiguously show that the problem still exists. Otherwise I think we're just poking in the dark.
