### ISSUE TITLE
build fails on Linux with icc-14.0.2 and Boost

### ISSUE THREAD

**Issue by danshapero** [dealii/dealii#1879]
I'm getting an error when compiling with Intel and using the bundled Boost. I'm invoking CMake with

```
cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icc \
  -DDEAL_II_ALLOW_BUNDLED:BOOL=False -DDEAL_II_WITH_THREADS:BOOL=False \
  -DDEAL_II_WITH_MPI:BOOL=False -DDEAL_II_FORCE_BUNDLED_BOOST:BOOL=True \
  -DDEAL_II_WITH_BOOST:BOOL=True -LAH ..
```

CMake generates the Makefile without errors. When I invoke `make` , I get the following error:

```
[ 11%] Building CXX object source/meshworker/CMakeFiles/obj_meshworker.release.dir/mesh_worker_info.cc.o
In file included from /home/shapero/programs/dealii-dev/source/meshworker/mesh_worker_info.cc(30):
/home/shapero/programs/dealii-dev/build-intel-w-boost/source/meshworker/mesh_worker_info.inst(1): error: right operand of "%" is zero
  #if !defined(SPLIT_INSTANTIATIONS_COUNT) || (0 % SPLIT_INSTANTIATIONS_COUNT == SPLIT_INSTANTIATIONS_INDEX)
                                                 ^
```

and several more errors of the same kind. The library compiles and tests fine with Boost disabled. I don't know what these macros are for, otherwise I would attempt a patch myself.

**Comment by danshapero** [comment]
I get the same error with boost-1.59.

**Comment by davydden** [comment]
do you have `intel-15`? I had no problems compiling with it and boost `1.59`.

**Comment by danshapero** [comment]
Nope, it's icc-14.0.2; are there known issues with this version?

**Comment by davydden** [comment]
not to me ;-)

**Comment by Rombur** [comment]
Actually this error has nothing to do with boost. The problem is that either icc-14 evaluates  ```==``` first and then ```%``` or ```SPLIT_INSTANTITIONS_COUNT=0```. @tjhei is the last one who has touch the instantiation files. Any idea how to solve this?

**Comment by danshapero** [comment]
@Rombur I only mention Boost because the error goes away when I disable it.

I added some parentheses, changing
```
0 % SPLIT_INSTANTIATIONS_COUNT == SPLIT_INSTANTIATIONS_INDEX
```
to
```
(0 % SPLIT_INSTANTIATIONS_COUNT) == SPLIT_INSTANTIATIONS_INDEX
```
and found the same error. So it's not an operator precedence thing.

My guess: if `SPLIT_INSTANTIATIONS_COUNT` is undefined when the preprocessor gets to
```
#if !defined(SPLIT_INSTANTIATIONS_COUNT) || ((0 % SPLIT_INSTANTIATIONS_COUNT) == SPLIT_INSTANTIATIONS_INDEX)
```
then the preprocessor might still try to evaluate `0 % SPLIT_INSTANTIATIONS_COUNT`.

**Comment by tjhei** [comment]
Yes, I implemented the logic and everything is as expected in ```mesh_worker_info.inst```: the condition reads
```
#if !defined(SPLIT_INSTANTIATIONS_COUNT) ||  (...)
```
and clang/g++ happily ignore the second part because the symbol is undefined. It looks like intel is parsing that differently. :-( I will work on a patch.

I can't see how this can be related to boost, though.
