### ISSUE TITLE
wrong assert (dim versus spacedim) in tria_boundary_lib.cc

### ISSUE THREAD

**Issue by barker29** [dealii/dealii#1883]
In dealii/source/grid/tria_boundary_lib.cc line 54, the line

 Assert (axis < dim, ExcIndexRange (axis, 0, dim));

should read

 Assert (axis < spacedim, ExcIndexRange (axis, 0, spacedim));

In case you want to build a CylinderBoundary<2,3>, as I do.

**Comment by bangerth** [comment]
Yes, correct. Would you like to make this an occasion to get your first patch to deal.II accepted? Let me know if you'd like me to walk you through writing such a patch!

**Comment by bangerth** [comment]
Fixed by #1884
