### ISSUE TITLE
Bug in GridGenerator::half_hyper_shell ?

### ISSUE THREAD

**Issue by krishnagarikipati** [dealii/dealii#1885]
GridGenerator::half_hyper_shell throws a run time error in debug mode. The code pasted below reproduces this error. It runs in release mode, but solvers report a null space on these meshes.

Thanks.

 ---Krishna

--------------------------------------------------------------------------------------------------------------------------
#include <base/quadrature_lib.h>
#include <base/logstream.h>
#include <base/function.h>
#include <lac/block_vector.h>
#include <lac/full_matrix.h>
#include <lac/block_sparse_matrix.h>
#include <lac/sparse_direct.h>
#include <lac/precondition.h>
#include <lac/constraint_matrix.h>
#include <lac/solver_gmres.h>
#include <grid/grid_generator.h>
#include <grid/tria_accessor.h>
#include <grid/tria_iterator.h>
#include <grid/tria_boundary_lib.h>
#include <grid/grid_tools.h>
#include <grid/grid_refinement.h>
#include <dofs/dof_handler.h>
#include <dofs/dof_renumbering.h>
#include <dofs/dof_accessor.h>
#include <dofs/dof_tools.h>
#include <fe/fe_dgq.h>
#include <fe/fe_nothing.h>
#include <fe/fe_system.h>
#include <fe/fe_values.h>
#include <hp/dof_handler.h>
#include <hp/q_collection.h>
#include <hp/fe_values.h>
#include <hp/fe_collection.h>
#include <numerics/vector_tools.h>
#include <numerics/matrix_tools.h>
#include <numerics/data_out.h>
#include <Sacado.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <math.h>
#include <base/tensor_function.h>
//
#include <base/conditional_ostream.h>
#include <base/utilities.h>
#include <lac/petsc_vector.h>
#include <lac/petsc_parallel_vector.h>
#include <lac/petsc_parallel_sparse_matrix.h>
#include <lac/petsc_solver.h>
#include <lac/petsc_precondition.h>
#include <deal.II/base/timer.h>
#define DIMS 3
#define totalDOF 5
using namespace dealii;

template <int dim>
class diffusionMechanics
{
public:
  diffusionMechanics (const unsigned int mech_degree, const unsigned int diff_degree);
  ~diffusionMechanics();
  void run ();
private:
  enum
    {omega1_domain_id,
     omega2_domain_id
    };

  const unsigned int   mech_degree;
  const unsigned int   diff_degree;

  Triangulation<dim>   triangulation;
  hp::DoFHandler<dim>      dof_handler;
  QGauss<dim>  	       quadrature_formula;
  QGauss<dim-1>	       face_quadrature_formula;
  SparsityPattern      sparsity_pattern;
  //  std::map<types::global_dof_index, double>    boundary_values;
  //  ConstraintMatrix hanging_node_constraints;

  MPI_Comm mpi_communicator;
  const unsigned int n_mpi_processes;
  const unsigned int this_mpi_process;
  //solution variables
  std::vector<std::string> nodal_solution_names; std::vector<DataComponentInterpretation::DataComponentInterpretation> nodal_data_component_interpretation;

  const double inner_radius = 10.0, outer_radius = 20.0;
  unsigned int n_cells;

  ConditionalOStream pcout;
  //parallel message stream                                                                                                                                                          
  TimerOutput computing_timer;
  
};

// Constructor
template <int dim>
diffusionMechanics<dim>::diffusionMechanics (const unsigned int mech_degree, const unsigned int diff_degree): 
  mech_degree (mech_degree), 
  diff_degree (diff_degree), 
  dof_handler (triangulation), quadrature_formula(3), face_quadrature_formula(2), mpi_communicator(MPI_COMM_WORLD),
  n_mpi_processes (Utilities::MPI::n_mpi_processes(mpi_communicator)), 
  this_mpi_process (Utilities::MPI::this_mpi_process(mpi_communicator)), pcout (std::cout, (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0)),
   computing_timer (pcout, TimerOutput::summary, TimerOutput::wall_times){		
  //Nodal Solution names
  for (unsigned int i=0; i<dim; ++i){
    nodal_solution_names.push_back("u"); nodal_data_component_interpretation.push_back(DataComponentInterpretation::component_is_part_of_vector);
  }
  nodal_solution_names.push_back("mu"); nodal_data_component_interpretation.push_back(DataComponentInterpretation::component_is_scalar);
  nodal_solution_names.push_back("c"); nodal_data_component_interpretation.push_back(DataComponentInterpretation::component_is_scalar);
}
template <int dim>
diffusionMechanics<dim>::~diffusionMechanics (){dof_handler.clear ();}

//Run
template <int dim>
void diffusionMechanics<dim>::run (){
  //Generate half hyper shell
  const Point<DIMS> center (0.0,0.0,0.0);    
  GridGenerator::half_hyper_shell(triangulation, center, inner_radius, outer_radius, n_cells = 0, false);
  const HalfHyperShellBoundary<dim> boundary_description(center, inner_radius, outer_radius);
  triangulation.set_boundary (0, boundary_description);
  triangulation.refine_global (3);
}

//Main
int main (int argc, char **argv){
  try{
    Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
    deallog.depth_console (0);
    diffusionMechanics<DIMS> problem(1,1);
    problem.run ();
  }
  catch (std::exception &exc){
    std::cerr << std::endl << std::endl
	      << "----------------------------------------------------"
	      << std::endl;
    std::cerr << "Exception on processing: " << std::endl
	      << exc.what() << std::endl
	      << "Aborting!" << std::endl
	      << "----------------------------------------------------"
	      << std::endl;

    return 1;
  }
  catch (...){
    std::cerr << std::endl << std::endl
	      << "----------------------------------------------------"
	      << std::endl;
    std::cerr << "Unknown exception!" << std::endl
	      << "Aborting!" << std::endl
	      << "----------------------------------------------------"
	      << std::endl;
    return 1;
  }

  return 0;
}

**Comment by bangerth** [comment]
Superseded by #1886
