### ISSUE TITLE
Lack of documentation in GridGenerator::extrude_triangulation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#1887]
When the input triangulation is refined, there are cells in the resulting extruded triangulation that should not be there (extrusion of coarse cells overlaid with extrusion of refined cells). An exception **is** raised in debug mode. However, the documentation of this function does not reflect that the input triangulation should have refinement level 0.

**Comment by bangerth** [comment]
Good point. Want to write a short patch, or do you want me to do it?

**Comment by jppelteret** [comment]
I'll do it :-)
