### ISSUE TITLE
Verification of boost headers

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#1917]
As discussed in #1895 we use boost headers without any checks. Here the observation by @drwells 

> In fact, looking over where we use `boost`, it looks like we do not perform any checks for the header-only parts, just the parts with source code (the math parts are header only). Should those be checked?

The code in `cmake/modules/FindBOOST.cmake` does not make any check regarding the available include directories in boost. This is only relevant for non-bundled boost because bundled boost is naturally checked by the testers. Does anybody know of a policy for boost installations regarding the completeness of headers? I checked my Ubuntu 15.10 and Fedora 22 installations and boost headers seem fairly complete on both machines.

I think this issue can be closed if there is confidence that external boost headers will be sane (unless somebody hacks his boost installation).

**Comment by bangerth** [comment]
If we wanted to add such a check, here's the list of files we include:
```
boost/any.hpp
boost/archive/text_iarchive.hpp
boost/archive/text_oarchive.hpp
boost/array.hpp
boost/bind.hpp
boost/concept_check.hpp
boost/config.hpp
boost/core/enable_if.hpp
boost/enable_shared_from_this.hpp
boost/function.hpp
boost/graph/adjacency_list.hpp
boost/graph/bandwidth.hpp
boost/graph/cuthill_mckee_ordering.hpp
boost/graph/king_ordering.hpp
boost/graph/minimum_degree_ordering.hpp
boost/graph/properties.hpp
boost/iostreams/device/file.hpp
boost/iostreams/filter/gzip.hpp
boost/iostreams/filtering_stream.hpp
boost/lambda/lambda.hpp
boost/lexical_cast.hpp
boost/math/special_functions/binomial.hpp
boost/math/special_functions/erf.hpp
boost/math/special_functions/round.hpp
boost/optional.hpp
boost/property_tree/json_parser.hpp
boost/property_tree/ptree_fwd.hpp
boost/property_tree/ptree.hpp
boost/property_tree/ptree_serialization.hpp
boost/property_tree/xml_parser.hpp
boost/random.hpp
boost/random/mersenne_twister.hpp
boost/random/uniform_int_distribution.hpp
boost/random/uniform_real_distribution.hpp
boost/range.hpp
boost/scoped_ptr.hpp
boost/serialization/array.hpp
boost/serialization/map.hpp
boost/serialization/split_member.hpp
boost/serialization/string.hpp
boost/serialization/utility.hpp
boost/serialization/vector.hpp
boost/shared_ptr.hpp
boost/signals2.hpp
boost/thread/condition_variable.hpp
boost/thread.hpp
boost/thread/mutex.hpp
boost/tuple/tuple.hpp
boost/type_traits.hpp
boost/unordered_map.hpp
boost/unordered_set.hpp
boost/variant.hpp
```

**Comment by tamiko** [comment]
Currently, we use ```FindBoost.cmake``` as bundled with CMake to detect boost. In detail, the following call is responsible to find boost within our ```FindBOOST.cmake``` file:
```
44 # temporarily disable ${CMAKE_SOURCE_DIR}/cmake/modules for module lookup        
45 LIST(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)           
46 FIND_PACKAGE(Boost 1.48 COMPONENTS iostreams serialization system thread)        
47 LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/) 
```

> The code in cmake/modules/FindBOOST.cmake does not make any check regarding the available include directories in boost. This is only relevant for non-bundled boost because bundled boost is naturally checked by the testers.

I suggest that we do not try to "solve" a problem that is none. If there were problems with broken, or incomplete boost installations (I am not aware of a single one), then
 - first of all, it should be the responsibility of CMake's bundled ```FIndBoost.cmake```, not our configuration to ensure that a boost installation is "complete".
 - Secondly, this is a situation we cannot sanely guard at all: Even if all header files are present, do they contain anything? Or, accidentally belong to a different version? Does another include file from a different external library accidentally export something that is incompatible with the current boost headers? Etc., etc.

And last, keep in mind that _all_ our checks for external dependencies are opportunistic.If it looks like a valid correct external "feature", we set it up. For example, Trilinos and PETSc are set up if around 2-5 files are present...

**Comment by tamiko** [comment]
Ah, forgot what I wanted to say: We could add ```math``` to the list of required submodules, but this is a far as I would go.

**Comment by bangerth** [comment]
Good point. I think the compromise of adding `math` to the list and then leaving it at that makes sense.

**Comment by kronbichler** [comment]
I am fine with that solution, too.

**Comment by bangerth** [comment]
The situation is more complicated, as discussed in #1971. Given that we intended to do this here only for consistency, not to fix a concrete problem, let's just abandon the idea.
