### ISSUE TITLE
Utilities::int_to_string for 64bit integers

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#1930]
The Utilities::int_to_string function is currently only implemented for `unsigned int`, but used for `unsigned int`, `int`, `unsigned long`, ... . I would need this functionality for `unsigned long long` but currently it returns bogus, because it implicitly casts to a `unsigned int`, I would like to ask for opinions on how to fix this best. I could:

- do not use int_to_string, but boost::lexical_cast directly (I do not need the functionality of zero padding)
- overload int_to_string for all necessary types (at least `int`, `unsigned long int` and `unsigned long long int`)
- make it a template function and explicitly instantiate it  for all of the above types
- create a new function long_unsigned_int_to_string

I am happy about suggestions.

**Comment by bangerth** [comment]
Could you get away with a single overload with `long long int`? The likelihood of actually encountering a number between 2^63 and 2^64-1 is, at least for the foreseeable future, relatively small...

**Comment by tjhei** [comment]
I don't really like the fact that the type is present in the name of the function (and that it doesn't match for long long). Maybe we should introduce a ```number_to_string<T>(const T& number)```?

**Comment by bangerth** [comment]
That's basically `boost::lexical_cast`.

**Comment by gassmoeller** [comment]
With one overload of long long int I get:

/home/rengas/Software/dealii/include/deal.II/lac/block_indices.h:364:56: error: call of overloaded ‘int_to_string(dealii::BlockIndices::size_type)’ is ambiguous
   result += "|" + Utilities::int_to_string(total_size()) + ']';

**Comment by davydden** [comment]
i recall i was confused once by the name as it's called `int_to_string` and was trying to use it with `int`, but actually does `unsigned_int_to_string`.

Maybe just `Utilities::to_string<T>(const T& number)` ?

**Comment by drwells** [comment]
@bangerth Now that #1933 has been merged in this issue may be closed, correct?

**Comment by bangerth** [comment]
I think so. @gassmoeller -- it was your report, are you happy with the new function?

**Comment by gassmoeller** [comment]
Yes, this can be closed. Thanks for reminding me.
