### ISSUE TITLE
play with llvm lld linker

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#1937]
see http://blog.llvm.org/2015/11/new-elf-linker-from-llvm-project.html

**Comment by bangerth** [comment]
Would anyone like to give this another try? How does it compare to the gold linker that we use since #1539 and #1492?

**Comment by masterleinad** [comment]
Some stats from `/usr/bin/time` for building a recent developer version (running make -j160):
> lld:
>11763.52user 389.02system 5:12.68elapsed 3886%CPU (0avgtext+0avgdata 3466180maxresident)k
2376inputs+5813176outputs (167225major+112192529minor)pagefaults 0swaps

> ld.gold:
> 12769.48user 401.65system 5:05.75elapsed 4307%CPU (0avgtext+0avgdata 3036252maxresident)k
0inputs+5940088outputs (193360major+119508939minor)pagefaults 0swaps

**Comment by bangerth** [comment]
Hm, so there is no advantage to lld then any more. Thanks for making the experiment, @masterleinad !

Should we just close this issue then?

**Comment by masterleinad** [comment]
If I just relink, I need something like 30s with ld.gold and 20s with lld. Still, I agree that the difference is not signifacant.
