### ISSUE TITLE
Disable deallog by default?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1947]
At the workshop last August, we asked what people don't like in deal.II. One of those issues was that people didn't understand the role of `deallog`. The suggestion at the workshop was to simply disable *by default* any output of deallog. This is, in essence, what we already do for almost all tutorial programs, but it requires code one needs to explicitly write and understand. It could be avoided by simply setting the *default* depth of `deallog` to zero, rather than a nonzero value where it currently is.

Opinions?

**Comment by oneliefleft** [comment]
I find dealiilog useful in some debug cases and I recommend/force my
students to use it. I have a suggestion, if the default dealiilog is set to
zero (and it can be), can its existence also be emphasized in one of the
early tutorial programs? Say, in step-6, where catching exceptions in
main() is introduced.

2015-12-04 23:54 GMT+01:00 Wolfgang Bangerth <notifications@github.com>:

**Comment by tjhei** [comment]
In favor of setting console depth to 0 by default.

**Comment by kronbichler** [comment]
I would also vote for setting the depth to 0.

**Comment by tjhei** [comment]
I will prepare a patch...

**Comment by tjhei** [comment]
see #1950

**Comment by bangerth** [comment]
Fixed by #1950.
