### ISSUE TITLE
Cleanup documentation for GridGenerator

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#1957]
The documentation for [GridGenerator](http://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html) is in a bit of a state. Specialisations of template functions have bubbled up to the top, are uncatagorised and appear to be duplicates of the general function. Some of the section headings are also not formatted correctly.

**Comment by bangerth** [comment]
Yes.

Related to #320.

**Comment by jppelteret** [comment]
Apologies for the duplication! I'll close the issue since its been noted already.

**Comment by bangerth** [comment]
No, I think these issues are complementary. Let's keep them both open.
