### ISSUE TITLE
Update bundled boost

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1963]
Long term, we should update the bundled boost again.

**Comment by bangerth** [comment]
On this occasion, also think whether we want to import the boost.filesystem package to make portability a bit easier.

**Comment by tjhei** [comment]
Agreed. Our current version is not supporting MSVC 2015 for example.

Would it be possible to also rip out certain parts we don't need? Like boost spirit.

**Comment by bangerth** [comment]
If you can separate it. I think we use everything that's currently bundled because it's referenced somewhere. Isn't spirit used by the xml parser we use for serialization?

**Comment by Rombur** [comment]
Or we could get ride of the bundled version of boost. It's already packaged in most (all ?) linux distributions and it can be easily installed through candi. Personally, I don't see the point of these bundled libraries. Why is tbb (which can be installed through a package manager) bundled but not p4est? Why do we bundle umfpack but not petsc?

**Comment by bangerth** [comment]
All good questions (for which my answer is: everything you *need* is bundled, because that's what makes our users' lives easier). In the specific case of p4est -- we had originally planned to bundle it but were asked by the p4est authors not to do it.

**Comment by Rombur** [comment]
But does it really make anyone's life easier? It's hard to say if the bundled libraries help anyone but they are definitely annoying when you want to install deal.II on systems where there is a file quota like ada. You either have to ask that they change your quota or do like @gassmoeller and remove the bundled libraries yourself. Maybe we should ask on the mailing list if people use them.

**Comment by gassmoeller** [comment]
Actually, I would opt for keeping them bundled. True, there are systems which cause problems because of the tens of thousands of files, but such a problem is often easy to figure out. But I remember how I felt when I started to use deal.II and how much trouble I had to install all of the dependencies. I was happy for every required library I did not had to install.
And package managers are no particular help if you are on a cluster without root access, but also without an experienced admin (which was my situation at that time).

**Comment by Rombur** [comment]
But now you can use candi to install everything for you. That's why I don't see what's the point in bundling libraries.

**Comment by drwells** [comment]
I am also in favor of keeping them bundled due to issues like #1591. I lost a few hours to that issue before I realized what was going on.

**Comment by bangerth** [comment]
Closing this one in favor of the more recent #3086.
