### ISSUE TITLE
Serializing a TableEntry with 64bit indices fails

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#1969]
Is there a reason that TableEntry in `deal.II/base/table_handler.h:save()` and `load()` only saves and loads explicit types (int, unsigned int, double, string), and does not use the template parameter T? This seems to crash for long long int entries while writing checkpoints.

**Comment by bangerth** [comment]
Clearly nobody has run into this problem so far. Patch gladly accepted!

**Comment by gassmoeller** [comment]
Ok, I will prepare something. Just wanted to be sure, I am not missing a hidden meaning.
