### ISSUE TITLE
Wrong year on a news item on the homepage 

### ISSUE THREAD

**Issue by KristofferC** [dealii/dealii#1983]
It feels a bit embarrassing to open an issue about such a small thing but on the front page of the deal.ii home page it says:

> The deal.II Users and Developers training will be held in Trieste (Italy) from the 21st to the 24th of March **2015**. 

I believe this should be 2016 instead of 2015.

**Comment by tjhei** [comment]
Fixed (should show up in a few minutes). Thanks for reporting!
