### ISSUE TITLE
ShiftedMatrixGeneralized::vmult, ::residual do not work

### ISSUE THREAD

**Issue by slazav** [dealii/dealii#1990]
Please, look here at implementation of vmult and residual in ShiftedMatrixGeneralized:
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/shifted_matrix.h#L242

There are two problems:

1) these functions are declared as const, but they try to modify aux vector in the object.
This can be solved by declaring VECTOR aux just before lines 251, 268. (and removing the declaration in the line 150.)

2) SmartPointer M should be called as M->, not M. in lines 252, 269.

**Comment by drwells** [comment]
@slazav Yes, I see the issues; thank you for reporting this. Perhaps unsurprisingly we do not have any tests for this class :(

**Comment by slazav** [comment]
Thank you for the reply! For me it was very strange to find this. I'm completely new in deal.ii and not very experienced in numerical calculations, but I came to this place in a very straightforward way:
I had a simple eigenvalue problem; I didn't want to install sleps+petsc+... and use strange wrappers; I looked at internal solver, namely EigenInverse; I realised that it is not usable on non-uniform grids where you have non-trivial mass matrix, but it is easy to modify it by changing ShiftedMatrix by ShiftedMatrixGeneralized and changing a few other small things. And then I found that ShiftedMatrixGeneralized is broken!
I was surprised, why this way have not been done by 100 people before me:)

**Comment by drwells** [comment]
@slazav I think most of the users use `SLEPc` (and I just spent three hours running something with `LAPACK`; I need to write a `dggev` support patch...) so, unfortunately, I think our built in eigenvalue solvers are not frequently used. If you look around the issues list you will see that there is a lot of work going into improving the `SLEPc` and `ARPack` interfaces, but nothing for the one without any external dependencies. That is my best answer for why we have code in the library that won't even compile.

**Comment by slazav** [comment]
I checked that the new shifted_matrix.h works for me. Thank you!

**Comment by drwells** [comment]
@slazav Thank you again for reporting the issue :)
