### ISSUE TITLE
Bug in step-26?

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#1992]
I just installed a freshly checked out version of deal.II, and tried running step-26. This is the output I get:

![image](https://cloud.githubusercontent.com/assets/2919756/11876167/82000432-a4e8-11e5-9ed5-c64874053356.png)

Anyone sees the same?

(@gpitton pointed this out to me, and he sees problems too...)

**Comment by drwells** [comment]
This is frightening: yes, I see the same problem.

**Comment by bangerth** [comment]
Bummer. I think we'll have to dissect the history to see where this started  :- (

**Comment by drwells** [comment]
I just ran `git bisect` in the background for a few hours while grading exams. It looks like the culprit is, amazingly, 84d426abb4 (also known as #1832), proving that one man's bugs really are another man's features.

**Comment by tamiko** [comment]
> proving that one man's bugs really are another man's features.

You can drop the "another" in above sentence :-D

Happy grading! (I finished for today.)

**Comment by tjhei** [comment]
fix incoming.

**Comment by bangerth** [comment]
Fixed by #1994.
