### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#203]
When compiling off source, if `DEAL_II_COMPONENT_DOCUMENTATION=ON`, at least with doxygen 1.6.1, we (@andreamola and I) get this error:

~~~
Warning: ignoring unsupported tag `PROJECT_LOGO           =' at line 6, file options.dox
Warning: ignoring unsupported tag `USE_MATHJAX            =' at line 113, file options.dox
Warning: ignoring unsupported tag `MATHJAX_RELPATH        =' at line 114, file options.dox
Warning: ignoring unsupported tag `MATHJAX_EXTENSIONS     =' at line 115, file options.dox
Warning: ignoring unsupported tag `HTML_COLORSTYLE_HUE    =' at line 116, file options.dox
Warning: ignoring unsupported tag `HTML_COLORSTYLE_SAT    =' at line 117, file options.dox
Warning: ignoring unsupported tag `HTML_EXTRA_STYLESHEET  =' at line 118, file options.dox
Warning: ignoring unsupported tag `SERVER_BASED_SEARCH    =' at line 217, file options.dox
Error: tag HTML_HEADER: header file `header.html' does not exist
make[3]: *** [doc/doxygen/header.html] Error 1
make[2]: *** [doc/doxygen/CMakeFiles/doxygen.dir/all] Error 2
make[1]: *** [CMakeFiles/documentation.dir/rule] Error 2
make: *** [documentation] Error 2
~~~

**Comment by cbcoutinho** [comment]
I am getting this error when trying to build the documentation along with dealii with the latest development repo and doxygen version 1.8.12

Without building the docs I don't get an error, but trying to build the docs produces the following result:

```
...
...
[ 23%] Building doxygen input file for tutorial program <step-47>
[ 23%] Built target tutorial_step-47
Scanning dependencies of target tutorial
[ 23%] Built target tutorial
Scanning dependencies of target doxygen
[ 23%] Generating header.html, footer.html
error: tag HTML_HEADER: header file `header.html' does not exist
make[2]: *** [doc/doxygen/CMakeFiles/doxygen.dir/build.make:610: doc/doxygen/header.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:446: doc/doxygen/CMakeFiles/doxygen.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Should I re-open this issue or create a new one?

**Comment by davydden** [comment]
@cbcoutinho which commit do you use? I just built docu a few days ago without any issues. Is it a clean build directory?

**Comment by bangerth** [comment]
I ran into this on Friday but didn't have the time to fix it properly. Is this with the newest version of doxygen? Can you say what version you are using? 

(I'm pretty sure it's a bug in doxygen, and I think I know how to fix it too. )

**Comment by cbcoutinho** [comment]
@davydden, the latest commit from earlier this afternoon, but I don't follow the development closely enough to give you an exact commit. Doxygen version is 1.8.12

**Comment by cbcoutinho** [comment]
@bangerth, should I create a new issue then to document it or reopen this one?

**Comment by bangerth** [comment]
Please open a new issue.

**Comment by cbcoutinho** [comment]
new issue #3131
