### ISSUE TITLE
Update website generation script for the code gallery

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2038]
The script that updates the web site needs to be updated so that there is a copy of the code gallery at the top level of the deal.II directory (i.e., alongside `examples/`, `contrib/`, `include/`, `source/`, etc.). The script that pulls commits for deal.II then also needs to pull the latest patches for the code gallery.

@tamiko -- do you have access to this script?

**Comment by bangerth** [comment]
Blocks #1314.

**Comment by bangerth** [comment]
@ping?

**Comment by bangerth** [comment]
All that is really necessary is, in essence, the following after cloning/updating the deal.II repository from which we generat the website documentation:
```
  cd dealii                # wherever you cloned the deal.II git repo into
  if test -d code-gallery ; then
    cd code-gallery
    git checkout master
    git pull origin master
  else
    git clone https://github.com/dealii/code-gallery.git
  fi
```
The point is that after this, we have an updated clone of the `code-gallery` repository parallel to the `examples/` directory. The existing scripts should do everything else that is necessary from there.


Who still has access to the website scripts? @guidokanschat -- I think you may actually be the only one left. Could you please add these lines to the appropriate scripts?

**Comment by tamiko** [comment]
@bangerth No. Only @guidokanschat has access to the homepage.

**Comment by guidokanschat** [comment]
It's checked out on the web page and I will set up an update script. Hourly or daily sufficient? I do not want to be caught again in a robot detector.

Since these pages will allow people to post executable files, I need help configuring that the web server does not execute anything. Is "NoExec" for dealii sufficient?

**Comment by tjhei** [comment]
> Hourly or daily sufficient?
Even daily is fine but it is probably easier to update it every time you build the documentation?

> Since these pages will allow people to post executable files, I need help configuring that the web server does not execute anything. Is "NoExec" for dealii sufficient?

None of the files need to be visible to the webserver and nothing needs to be executed. When doxygen is run inside deal.II it will process the gallery and generate the doxygen pages.

**Comment by bangerth** [comment]
On 02/02/2016 02:02 PM, Timo Heister wrote:
>     Since these pages will allow people to post executable files, I need
>     help configuring that the web server does not execute anything. Is
>     "NoExec" for dealii sufficient?
>
> None of the files need to be visible to the webserver and nothing needs
> to be executed. When doxygen is run inside deal.II it will process the
> gallery and generate the doxygen pages.

Correct. We also (at least cursorily) review contributions to the code 
gallery before we merge them.

Did you see the 8-line code snippet further up in this issue? This is 
really the only thing that needs to be added to the script you are 
already running to generate the website periodically. Everything else 
will continue to work.

**Comment by tjhei** [comment]
It looks like it did not work: https://www.dealii.org/developer/doxygen/deal.II/CodeGallery.html

**Comment by guidokanschat** [comment]
Oh, I got that totally wrong. I thought it should go to the web pages.

**Comment by guidokanschat** [comment]
The link Timo sent has contents now. Is that what you are looking for?

By the way, please be gentle to our web server and encourage movies on youtube!

**Comment by bangerth** [comment]
Excellent -- thanks, Guido!
