### ISSUE TITLE
Remove step-19

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2046]
step-19 was written at a time when visualization programs were not able to open multiple files written by a parallel program and combine their data into one image. This is clearly no longer the case, so there is no longer a rationale for step-19. It should simply be removed.

**Comment by drwells** [comment]
I think we tentatively agreed (in a past mailing list discussion) to write a new tutorial program, based on step 12, which shows how one can do DG without using MeshWorker. I already have some code that can do this:

https://github.com/drwells/dealii-step-12a

I am aiming at having this done by July so that we can, as usual, try to get the new release out in August.

**Comment by bangerth** [comment]
Good plan indeed!

**Comment by tamiko** [comment]
@drwells What's the status? Postpone to 9.0?

**Comment by drwells** [comment]
I talked about this with @tjhei during PDEsoft (wow, that was a long time ago) and I think our conclusion was that we should use this 'free' slot to do something more substantial than just redo step 12 without mesh worker. So, yes: postpone, probably with a different replacement.

**Comment by drwells** [comment]
This is marked as 9.0 but I do not yet have a replacement.

There are two elements which I would like to add to deal.II and I have been compiling a set of notes to turn into a 'how to write a finite element' tutorial program but I do not think it will be ready in time for 9.0, so (unless someone has a better idea for a step-19 replacement) I suggest we delay this for one more release.

**Comment by Rombur** [comment]
Agreed. I don't think that we have time to add a new tutorial unless someone has one ready to be merged. However, I assume that if it was the case, that person would have told us that she had a tutorial ready to be merged. So let's move this to the next release.

**Comment by drwells** [comment]
Well, its been a year and I might have forgotten about this. I should sign up to give a talk on 'how to write a finite element' at the workshop so that I actually get around to rewriting this program.

**Comment by drwells** [comment]
@GrahamBenHarper Would you be willing to help write this tutorial based on your presentation today?

**Comment by tjhei** [comment]
One thing that just came to my mind: reusing step-19 might be confusing (for example when searching for step-19 online you might find the old one, which I know many people do). Should we just delete step-19 and keep it empty instead?

**Comment by GrahamBenHarper** [comment]
@drwells Write a tutorial for implementing a finite element? I think that sounds interesting. @bangerth was also suggesting the possibility of recording a video tutorial on implementing a finite element. Could these two ideas be combined?

**Comment by drwells** [comment]
I think so: one way would be to write the tutorial and then record a lecture based on it.

**Comment by GrahamBenHarper** [comment]
Also #1973 would be a great issue to address prior to this. I will work on it now and see if I can make some progress.

My initial thoughts tell me most of it will be changing the polynomial classes to have a similar polymorphism structure to how `FE_PolyTensor` and `FE_Poly` derive from `FiniteElement`. Perhaps it would be an abstract class called `PolynomialsBase` with some pure virtual functions for the essential information such as `PolynomialsBase::compute`, `PolynomialsBase::degree`.

**Comment by drwells** [comment]
This has been floating around for awhile and, given discussions we've had elsewhere, I think we should not replace this with a new step-19 (i.e., @tjhei is right): its going to be too confusing in case anyone has cited this in the past. We should keep the tutorial as-is with a warning at the top explaining why its not so useful anymore.

**Comment by bangerth** [comment]
But is step-19 in itself useful? Could we just remove it, not use the number of a couple of years, and then replace it with something else?

**Comment by tjhei** [comment]
> But is step-19 in itself useful?

no.

> Could we just remove it,

Sure.

> , not use the number of a couple of years, and then replace it with something else?

I guess we can delay that fight for a few years. :-)
