### ISSUE TITLE
macos el capitan and "make run"

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2058]
I have heard from several student this week, that "make run" is not working correctly after updating to el capitan. Note that executing the example programs manually still works. Hitting "run" inside an eclipse project fails with the same error.

I didn't have enough time to investigate further, but it looks like the DYLIB path is ignored when executing the program indirectly. There are many hints online and I can see possible work-arounds: 1. play with System Integrity Protection (SIP) https://stackoverflow.com/questions/32905322/oserror-dlopenlibsystem-dylib-6-image-not-found 2. specify absolute paths.

Anybody willing to play with this?

**Comment by luca-heltai** [comment]
The recommendation is that you should not rely on DYLD_LIBRARY_PATH, and el capitain disables this by default.

Are you compiling libraries?

**Comment by luca-heltai** [comment]
Ps: make run works fine on the package I distribute. Are you compiling a project with a library?

If you are, then you should make sure the target for the library is specified in this way:

~~~
  SET_TARGET_PROPERTIES(${_lib} PROPERTIES MACOSX_RPATH OFF
    BUILD_WITH_INSTALL_RPATH OFF
    INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}"
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}"
   )
~~~

**Comment by tjhei** [comment]
I don't know. I don't have a mac, I just played with an installation for a few minutes trying to run the standard examples. I will ask them to update to the newest package and see if that fixes it.

**Comment by tjhei** [comment]
Ah, he was using the 8.3.0 package. Everything works with the newest one. Time to ship 8.4.0 soon. :-)
