### ISSUE TITLE
Set PARALLEL property of tests

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2061]
We have struggled in the past with parallel testsuite runs because ctest won't distinguish whether a test runs with `mpirun -np 10` or on only one processor. Consequently, on a 64-core machine, we can't run `ctest -j64` without causing excessive loads.

ctest seems to have acquired a new property `PROCESSORS` on tests, see https://cmake.org/cmake/help/v3.4/manual/cmake-properties.7.html#test-properties I believe that this was added in cmake 3.3. We should utilize this.

**Comment by tamiko** [comment]
The ```PROCESSORS``` property should already be part of cmake-2.8.9 if I recall correctly.

I remember a discussion we had whether this actually improves the situation and I remember that we settled on a compromise. And in fact, (according to ```git blame```) the author of the following 12 lines is you :-D

In ```macro_deal_ii_add_test.cmake```:
```
291       #                                                                          
292       # Limit concurrency of mpi tests. We can only set concurrency              
293       # for the entire test, which includes the compiling and linking            
294       # stages that are purely sequential. There is no good way to model         
295       # this without unnecessarily restricting concurrency. Consequently,        
296       # we just choose to model an "average" concurrency as one half of          
297       # the number of MPI jobs.                                                  
298       #                                                                          
299       IF(_n_cpu GREATER 2)                                                       
300         MATH(EXPR _slots "${_n_cpu} / 2")                                        
301         SET_TESTS_PROPERTIES(${_test_full} PROPERTIES PROCESSORS ${_slots})      
302       ENDIF()
```

**Comment by bangerth** [comment]
Ha, well, who knew :-)
