### ISSUE TITLE
generalize GridTools::build_triangulation_from_patch() to handle more general triangulations

### ISSUE THREAD

**Issue by srobertp** [dealii/dealii#2081]
It was noted that the current implementation of GridTools::build_triangulation_from_patch() in pull request #1934 has the deficiency that it requires the triangulation to be consistent with the dealii refinement strategy.  That is: 

 If we happen to have a grid that has had the vertices perturbed, for instance
 using the GridTools::distort_random() member function (which is useful for
 removing symmetries of a Grid for testing an algorithm convergence rate) The
 triangulation we construct by going back to the coarsest common level of the
 patch and then refining is in fact a different triangulation than the one we
 are trying to match. In particular, the assertions of cell centers being
 the same are triggered. What this means is that for this implementation, and
 invariant is that the triangulation needs to have been constructed under the
 exact same rules as the dealii refinement strategy of using midpoints. (This
 might be an issue say for an imported triangulation or one that has been
 smoothed, or one that has applied the random perturbation of vertices, and
 maybe others...)

@bangerth suggested the following course of action to resolve this problem.

"
I think the right way to address this is to, at the end
of the process where we have built the map between cells on the two
triangulation, to have a loop of the form`
```
   for (patch_cell=...)
     for (v=0...)
       patch_cell->vertex(v) = cell_map[patch_cell]->vertex(v)
```
"

The only other question is if we need to do something extra to handle say an isoperimetric boundary condition?

**Comment by bangerth** [comment]
I would ignore the issue of boundaries. The function is only intended to build the triangulation, which really only stores vertex locations and how they connect to cells. One could in principle attach to this triangulation also the boundary or manifold objects from the parent triangulation, but I would suggest to go one step at a time.

**Comment by bangerth** [comment]
@srobertp: Do I understand it right that this issue is now fixed? If so, feel free to close it.

**Comment by srobertp** [comment]
This issue is now resolved.
