### ISSUE TITLE
SparseVanka does not use second-order couplings

### ISSUE THREAD

**Issue by fsonner** [dealii/dealii#2118]
The `SparseVanka` solver is supposed to add contributions from second-order couplings to the right-hand side of the local systems. This never happens. The code loops, by accident, over the first-order couplings and immediately filters them out.

The culprit is [this for loop](https://github.com/dealii/dealii/blob/4bb930ae228c42b62495349f14e2ac3d99456e86/include/deal.II/lac/sparse_vanka.templates.h#L338) which iterates over the couplings of `row` (the Lagrange dof) instead of `irow` (the first-order coupling dof).

**Comment by drwells** [comment]
Closed by #2119.
