### ISSUE TITLE
Add locally_owned_active_cell_iterator ?

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#2124]
There are lots of code like
```
          typename DoFHandler<dim>::active_cell_iterator
          cell = dof_handler.begin_active(),
          endc = dof_handler.end();
          for (; cell!=endc; ++cell)
            if (cell->is_locally_owned())
              {
                local_sum_v += artificial_viscosity[cell->active_cell_index()];
              }
```

Is is possible and worth to hide ` if (cell->is_locally_owned())` inside `iterator`?

**Comment by Rombur** [comment]
It already exist look at http://dealii.org/developer/doxygen/deal.II/classFilteredIterator.html with http://dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedCell.html

**Comment by QiaoLei-88** [comment]
WoW, That's nice.

Thank you.

**Comment by bangerth** [comment]
There is also the function `Triangulation::cell_iterators()` (and variant `active_cell_iterators()` as well these functions for just one level) that allow you to get a range of all (active) iterators for use in a C++11 range-based for loop.

I would not be opposed to adding `locally_owned_active_cell_iterators()` to this list.

See https://www.dealii.org/developer/doxygen/deal.II/group__CPP11.html .
