### ISSUE TITLE
include directories not set properly in `Make.global_options`

### ISSUE THREAD

**Issue by danshapero** [dealii/dealii#2130]
In the generated `Make.global_options` I have, the include directories appear to not be set correctly:

    DEAL_II_INCLUDE_DIRS = ${DEAL_II_PATH}/include /include/deal.II/bundled /usr/include

This should be:

    DEAL_II_INCLUDE_DIRS = ${DEAL_II_PATH}/include ${DEAL_II_PATH}/include/deal.II/bundled /usr/include

When I try to compile an example program from a Makefile, I get an error because it looks in the wrong directory for e.g. the bundled Boost or TBB.

I think [this line](https://github.com/dealii/dealii/blob/43207def77c7fed8ecad722b45cfb298ecbe7233/cmake/config/Make.global_options.in#L130) is the cuprit:

    DEAL_II_INCLUDE_DIRS = ${DEAL_II_PATH}@MAKEFILE_INCLUDE_DIRS@

It's prepending `${DEAL_II_PATH}` to the text of all include directories, but not to each item in the list. However, it shouldn't be prepending it to `/usr/include`. I don't know enough about the deal.II's build system to fix this.

On the other hand, Makefile builds are only supported as legacy feature anyway, so if they're being phased out I can updated my project to use CMake.

**Comment by tamiko** [comment]
This is indeed a bug. I'll have a look.

**Comment by tamiko** [comment]
@danshapero I'm very tempted to finally get rid of ```Make.global_options``` altogether.

**Comment by danshapero** [comment]
@tamiko Suits me just fine. I was only using makefiles in example code because I find them more convenient for some tasks (invoking `wget` to download meshes/data, running a plotting script, etc.) than CMake. But one can easily work around this by e.g. using a shell script or top-level makefile.
