### ISSUE TITLE
Allow for code gallery entries to specify project names

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2180]
Right now we just use the folder name to generate the name of the project, so we have three different formats and it looks a bit odd.

We could probably fix this by allowing an optional file under `doc/` containing a printable name of the project.

**Comment by bangerth** [comment]
Good point. If you create a pull request for the existing code gallery programs, then I'll create the patch to make use of it in generating the pages and the connection graph.

**Comment by drwells** [comment]
Superceded by #2200 and implemented (on just the code gallery side) by dealii/code-gallery#16.

**Comment by bangerth** [comment]
Ah, didn't mean to step on you there. I just didn't remember we had this one.

**Comment by drwells** [comment]
It's not a problem (and I do not feel tepped on). #2200 is more specific.
