### ISSUE TITLE
boost 1.54 and enable_if

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2196]
It looks like boost 1.54 doesn't have core/enable_if.hpp but utility/enable_if.hpp, but we require the former in base/std_cxx11/type_traits.h (no cxx11 build).
Options:
1. require a newer version of boost (at least 1.56?)?
2. version specific ifdef in base/std_cxx11/type_traits.h

**Comment by bangerth** [comment]
Fixed by #2197.

**Comment by bangerth** [comment]
I think requiring a newer version of BOOST makes sense as well. What's the current minimum version?

**Comment by bangerth** [comment]
See also #2199 for a more general discussion.
