### ISSUE TITLE
update_once / update_each is still in documentation

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2198]
AFAIK, update_once() / update_each() are gone both from FE and Mapping classes, see https://github.com/dealii/dealii/pull/2113 https://github.com/dealii/dealii/pull/1838 https://github.com/dealii/dealii/issues/1198 .

These methods are still discussed in https://www.dealii.org/developer/doxygen/deal.II/group__UpdateFlags.html .

I only report the issue as i think @bangerth would be the best person to change the text according to new modifications.

**Comment by davydden** [comment]
btw, it seems there are two pages which discuss the same thing: https://www.dealii.org/developer/doxygen/deal.II/group__FE__vs__Mapping__vs__FEValues.html

**Comment by davydden** [comment]
maybe one just simply have to go?

**Comment by bangerth** [comment]
Indeed. Will get the outdated reference done before the next release.

I had noticed that there are two pages a good while after writing the second one. I may have to take a look at how they differ and if they could be made to discuss different issues (or should just be combined).

**Comment by tamiko** [comment]
@bangerth You're up for some last minute documentation updates? :-)

**Comment by bangerth** [comment]
No, I'm afraid not. This will have to wait.

**Comment by bangerth** [comment]
I've looked at the documentation modules, and they all seem to be correct now. I don't know what patch fixed this, but it looks like the transition is now complete.
