### ISSUE TITLE
Up the minimum acceptable version of BOOST

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2199]
#2196 (and the fix in #2197) reports a case where BOOST 1.54 is trouble because a header has moved location since then. We should consider upping the minimum acceptable version of BOOST.

**Comment by tamiko** [comment]
The current minimum version is 1.48. What new version minimal version do you have in mind?

**Comment by bangerth** [comment]
One past the last version we blacklist or for which we know for other reasons that it gives us trouble.

**Comment by tamiko** [comment]
It should be pretty save to update to 1.54. Will do a pr.

**Comment by Rombur** [comment]
I am fine with updating to 1.54 but the last version that we blacklist is 1.58 (because there is problem with the serialization)

**Comment by davydden** [comment]
maybe update to 1.59?

**Comment by tamiko** [comment]
No. 1.59 is way to modern. Currently, 1.54 is the last version universally available in stable distributions, we should stick to that.

Further, we currently bundle 1.56.
