### ISSUE TITLE
Use full name of code gallery programs

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2200]
We currently only use the directory name of code gallery examples for the list of code gallery programs, and in the connection graph. Since https://github.com/dealii/code-gallery/pull/16 there is now also a "real" name of each program in `doc/entry-name` that should be used.

This should also be added to the list of requirements at http://www.dealii.org/code-gallery.html .

**Comment by drwells** [comment]
Closed by #2204.

**Comment by bangerth** [comment]
I still have to change the top-level page, so I'll reopen for now.

**Comment by bangerth** [comment]
Related to #1314 .

**Comment by bangerth** [comment]
I added the the blurb to the code-gallery website.

The problem is that it doesn't come out right at https://dealii.org/developer/doxygen/deal.II/CodeGallery.html , presumably because the code gallery isn't updated. See #2208.
