### ISSUE TITLE
intel 16.0.1 issues

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2203]
Several tests are failing with intel 16 that were fine with intel 15, see http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1069

Especially scary are random floating point exceptions inside fe/curl_curl_01.debug (see http://cdash.kyomu.43-1.org/testDetails.php?test=1818226&build=1069) that are related to multithreading in the FE_Nedelec constructor. The test fails about 10% of the time inside the solver and I assume this is because the element construction has a race condition (or the compiler is broken?). 

Another scary thing is multigrid/transfer_03.release (http://cdash.kyomu.43-1.org/testDetails.php?test=1814456&build=1069) which gives wrong answers.

Most of the other tests look like they are minor issues.

**Comment by bangerth** [comment]
Can you get a backtrace on the curl_curl_01 testcase?

**Comment by tjhei** [comment]
Will try, but it only crashes inside solve so I think this is not particularly useful.

**Comment by tjhei** [comment]
No, because it is very hard to reproduce (only under heavy load and only one in hundreds of runs). I also couldn't get gdb to work with icc. Grr.
On a different note, Intel just released 16.0.2, which fixed this bug. :-/

Should we blacklist 16.0.1? Or just give up?

(please leave this bug open, I am retesting everything with 16.0.2 now)

**Comment by bangerth** [comment]
On 02/19/2016 03:38 PM, Timo Heister wrote:
> No, because it is very hard to reproduce (only under heavy load and only
> one in hundreds of runs). I also couldn't get gdb to work with icc. Grr.

They have their own debugger ('idb'?).


> On a different note, Intel just released 16.0.2, which fixed this bug. :-/
>
> Should we blacklist 16.0.1? Or just give up?
Let's just ignore it.

**Comment by tamiko** [comment]
On Fri, Feb 19, 2016, at 15:38 CST, Timo Heister <notifications@github.com> wrote:

> On a different note, Intel just released 16.0.2, which fixed this bug. :-/

I don't think it is feasible to provide elaborate workarounds for
serious compiler bugs (if at all possible).

> Should we blacklist 16.0.1? Or just give up?

Let's just FATAL_ERROR on this version in check_03_compiler_bugs.cmake
and call it a day. Everyone who has a license for 16.0.1 can upgrade to
16.0.2 anyway.

> (please leave this bug open, I am retesting everything with 16.0.2 now)

OK.

**Comment by tjhei** [comment]
Okay, updating to 16.0.2 leaves us with several other weird issues (only in release mode):
http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1290
If we ignore the direct solver, linear operator, and rounding issues, we still have
- optimization bugs: base/anisotropic_1.release, bits/chunk_sparse_matrix_vector_05.release, bits/chunk_sparse_matrix_vector_06.release
- multigrid bug: multigrid/transfer_03.release (and matrix_free/parallel_multigrid*)
- I am not sure: find_cell_*
