### ISSUE TITLE
[Meta] Removal of deprecated functions and classes for 8.5

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2210]
This issue is a catch-all to link to pull requests that remove deprecated functions and classes in the 8.5 release time frame.

**Comment by drwells** [comment]
Related to #2956.

**Comment by bangerth** [comment]
It's hard to tell at this point which functions had been deprecated for a long time already and that we should remove, and which have only recently been deprecated. So I guess not very much more is going to get removed before the next release.

We should remember to create an issue right after the release that just greps through the header files and attach the output to the issue so we know what was deprecated already at the time of the release.
