### ISSUE TITLE
periodicity handling in Triangulation

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2212]
The implementation of periodic domains is somewhat inconsistent and there is currently no easy way to find a neighboring cell across a periodic boundary. We should probably either support periodicity correctly in the Triangulation so that neighbor() works correctly or at least implement a nice way to query if a face is on a periodic boundary and allow getting at the neighbor.

**Comment by tjhei** [comment]
also see https://github.com/dealii/dealii/issues/2212

**Comment by bangerth** [comment]
@tjhei and @tamiko -- is there anything else that needed to be done for this issue? Or could it be closed?

**Comment by kronbichler** [comment]
I think we have a nice solution now. I'm closing.
