### ISSUE TITLE
invert mass matrix with complex-valued RHS 

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2252]
https://github.com/dealii/dealii/pull/2249 extended VectorTools projection functions to complex-valued vectors up to the step when the mass matrix has to be inverted with complex-valued RHS. What remains is either to extend CG solver to that case or write/use another solver.

In reference to https://github.com/dealii/dealii/issues/2033

**Comment by bangerth** [comment]
Or to solve twice, once for the real and once for the imaginary part. This may not be the most elegant approach, but maybe the simplest.

**Comment by drwells** [comment]
Since the mass matrix needs to be real I believe its fine if we let the official answer be 'solve twice'.
