### ISSUE TITLE
extend ConstraintMatrix to complex-valued case

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2253]
Constraint matrix has to be extended to at least templated inhomogeneity to allow complex-valued boundary conditions. Although one may come up with cases when values in the matrix could also be complex-valued (fancy periodic boundary conditions), let's ignore this case for now to keep things simple.

In reference to https://github.com/dealii/dealii/issues/2033

**Comment by bangerth** [comment]
This is a duplicate of #1760.
