### ISSUE TITLE
fix max_element() and min_element() in grid_refinement for complex-valued vectors

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2255]
Currently these are masked with `Assert(false, ExcNotImplemented())`. 

In reference to https://github.com/dealii/dealii/issues/2033

**Comment by bangerth** [comment]
I think this is the wrong way to go. The `GridRefinement` functions should only get real-valued vectors of refinement indicators. For refinement, one needs to be able to *compare* indicators, but the complex numbers are not comparable (and it wouldn't be clear in any case what that would mean).

**Comment by davydden** [comment]
you are right! i did not pay much attention to the context of the compilation error.
