### ISSUE TITLE
Make deal.II compile on FreeBSD

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#2265]
deal doesn't compile on FreeBSD. I get this weird error at linking (probably the same as @tamiko in #2261. I will look into this tomorrow

[100%] Linking CXX shared library ../lib/libdeal_II.g.so
numerics/CMakeFiles/obj_numerics.debug.dir/matrix_tools.cc.o: file not recognized: File format not recognized
CC: error: linker command failed with exit code 1 (use -v to see invocation)
--- lib/libdeal_II.g.so.8.5.0-pre ---
*** [lib/libdeal_II.g.so.8.5.0-pre] Error code 1

**Comment by tamiko** [comment]
> deal doesn't compile on FreeBSD. I get this weird error at linking
> (probably the same as @tamiko in #2261. I will look into this tomorrow
>
> [100%] Linking CXX shared library ../lib/libdeal_II.g.so
> numerics/CMakeFiles/obj_numerics.debug.dir/matrix_tools.cc.o: file not
> recognized: File format not recognized

Same here. :-/

**Comment by tamiko** [comment]
@Rombur Release mode compiles fine, it is only the debug library that has problems.

My guess is that with debug symbols and without optimization the ```matrix_tools.cc.o``` object hits some limits for the freebsd linker.

**Comment by bangerth** [comment]
I've seen this kind of error happen if a compile job is killed without the ability to recover (e.g., because it runs out of memory, or a kill -9). In that case, it leaves a written object file on disk that is newer than the source files, but the object file is not valid of course. The `make` job terminates, but if you restart it, the object file is not remade because it is newer than the source file -- leading to a later, unintelligible error about a corrupted object file during the link phase.

What happens if you remove this one object file and try compiling again, maybe with `-j1`? Same problem? If so, it really is a case of exceeding some internal limitation without the compiler or assembler realizing this. We could work around this by splitting the `.cc` or `.inst.in` files into two.

**Comment by Rombur** [comment]
I was doing a fresh install with only 1 processor. I will try to split the ```.cc``` and the ```.inst.in`` files tonight.

**Comment by tamiko** [comment]
@bangerth ```matrix_tools.cc.o``` is by far the largest object:
```
14717312 numerics/CMakeFiles/obj_numerics.release.dir/matrix_tools.cc.o
 7958248 numerics/CMakeFiles/obj_numerics.release.dir/data_out_dof_data.cc.o
 5114000 fe/CMakeFiles/obj_fe.release.dir/fe_values.cc.o
 4923096 numerics/CMakeFiles/obj_numerics.release.dir/derivative_approximation.cc.o
 4566408 fe/CMakeFiles/obj_fe.release.dir/fe_values_inst2.cc.o
```
(This is for release mode, but the same holds true for debug mode.)

**Comment by tjhei** [comment]
I am happy to make a PR for splitting the instantiations if you want. Let me know.

**Comment by tamiko** [comment]
@tjhei This would be perfect :-)

**Comment by tamiko** [comment]
Debug mode values:
```
  271874456 source/numerics/CMakeFiles/obj_numerics.debug.dir/matrix_tools.cc.o
   62688704 source/numerics/CMakeFiles/obj_numerics.debug.dir/error_estimator.cc.o
   61903264 source/numerics/CMakeFiles/obj_numerics.debug.dir/error_estimator_inst2.cc.o
   61637032 source/numerics/CMakeFiles/obj_numerics.debug.dir/derivative_approximation.cc.o
   60454824 source/grid/CMakeFiles/obj_grid.debug.dir/grid_tools.cc.o
   47108448 source/numerics/CMakeFiles/obj_numerics.debug.dir/data_out_dof_data.cc.o
   41921568 source/fe/CMakeFiles/obj_fe.debug.dir/fe_values.cc.o
```

@bangerth I recompiled everything once more. Just for you. Same result.

**Comment by bangerth** [comment]
Wow, 272 MB for a single file!

**Comment by davydden** [comment]
i contributed to the size in recent complex-value-related PRs. Unfortunately, all these instantiations (mostly mass matrix in volume or on boundary) are needed to support projection for different vector types.

**Comment by tjhei** [comment]
can you test if #2273 helps?

**Comment by tamiko** [comment]
It does.
```
#freebsd freebsd build # ldd lib/libdeal_II.g.so.8.5.0-pre 
lib/libdeal_II.g.so.8.5.0-pre:
        libm.so.5 => /lib/libm.so.5 (0x80c2d5000)
        libtbb.so => /usr/local/lib/libtbb.so (0x80c4fe000)
        libz.so.6 => /lib/libz.so.6 (0x80c732000)
        libboost_iostreams.so.1.55.0 => /usr/local/lib/libboost_iostreams.so.1.55.0 (0x80c948000)
        libboost_serialization.so.1.55.0 => /usr/local/lib/libboost_serialization.so.1.55.0 (0x80cb62000)
        libmuparser.so.2 => /usr/local/lib/libmuparser.so.2 (0x80cdd6000)
        libc++.so.1 => /usr/lib/libc++.so.1 (0x80d03d000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x80d2fc000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x80d518000)
        libc.so.7 => /lib/libc.so.7 (0x800821000)
        libthr.so.3 => /lib/libthr.so.3 (0x80d726000)
        libbz2.so.4 => /usr/lib/libbz2.so.4 (0x80d94a000)
```

**Comment by tamiko** [comment]
@tjhei I'll run a full build test for freebsd now.

**Comment by tamiko** [comment]
http://cdash.kyomu.43-1.org/buildSummary.php?buildid=1543

**Comment by tjhei** [comment]
Looks good! :+1:
