### ISSUE TITLE
Change type of 'dim' to 'unsigned int'?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2266]
I got an email with an interesting question: why are we consistent all throughout deal.II in using `unsigned int` for quantities that are logically non-negative, except in the type chosen for `dim`, `spacedim`, etc?

Ultimately, I think it really boils down to laziness back many years ago. Should we change this? It makes no actual difference, I believe, and the number of places that would become incompatible are likely going to be rather minimal.

Discuss!

**Comment by drwells** [comment]
I'll contribute to the bikeshedding.

I ran some simple tests and this does not seem to break things that might assume these classes were still templated on `int`s, so it should not break user codes.

I personally find
```cpp
template <unsigned int dim, unsigned int spacedim> DoFHandler;
```

approximately as beautiful as
```cpp
template <int dim, int spacedim> DoFHandler;
```

so I would not oppose this change.

While I do enjoy making dull, systematic changes to deal, this is not something I care about strongly, so I do not volunteer to change this.

**Comment by davydden** [comment]
`unsigned int` is longer to write :smile:

**Comment by QiaoLei-88** [comment]
But,  for quantities that are logically non-negative, if we represent it with `unsigned int` type,
then we just can't check whether it is "really" positive via `Assert(unsigned ui > 0, ...)`.

So I prefer to use `int` instead of `unsigned int` whenever `int` doesn't overflow.
And if positiveness is required, one should use `Assert` to assure this.

Anyway, `int` is shorter to write.

**Comment by bangerth** [comment]
Given the lack of enthusiasm on everyone's part, let's forget about this.

**Comment by drwells** [comment]
I think @QiaoLei-88's remark is sufficient reason for keeping it the way it is: this could avoid some weird bugs with someone doing `dim - 1` when `dim` is zero.
