### ISSUE TITLE
List pi-DoMUS under "Applications" at dealii.org

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2267]
@luca-heltai -- if you give me a web address, then I'll gladly list pi-DoMUS there.

**Comment by luca-heltai** [comment]
Here it is: 

http://github.com/mathLab/pi-DoMUS

**Comment by bangerth** [comment]
I added the link. You had a nice intro page for deal.2lkit that outlined what it is and what it provides. You may want to extend your current README.md a little bit by providing at least a paragraph describing the intention and extent of pi-DoMUS. Also, there is a link to the github.io homepage of the project at the top of the page we now link to, but that link is not present in the text generated from README.md where I was looking for it. You may want to copy it there as well.
