### ISSUE TITLE
Add action to ParameterHandler::declare_parameter

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2268]
@luca-heltai 's group has a nice feature in most of their classes where they don't split declaring and parsing parameters for `ParameterHandler` into two functions, but where it all happens in one function call. In their code, basically what happens is that they call a function of the kind

```
  add_parameter (prm, "Parameter name", &member_variable, "help text", pattern);
```

This declares a parameter in `prm` and stores a map between the so-declared parameter and the address of the member variable. Then, at a later time, a _single_ function reads the parameter file and then goes through the map and (i) reads the parameter's value, (ii) puts it into the stored address for the member variable (or a stack or global variable, as appropriate).

I don't particularly care about the address of a variable -- that just seems fragile, and if a parameter is stored as a string one later still has to often do some follow-up action, such as creating plug-ins based on the _value_ of that string. But the overall idea of connecting an _action_ to reading parameters is excellent.

So here's an idea: If we extended the list of arguments to `ParameterHandler::declare_parameter()` like this:

```
  void declare_entry (const std::string           &entry,
                      const std::string           &default_value,
                      const Patterns::PatternBase &pattern = Patterns::Anything(),
                      const std::string           &documentation = std::string(),
                      const std::function<void (...)> &action = [](...){});          // <----- this is new
```

then we could _execute_ the action upon reading a parameter. The case `add_parameter` currently covers, with the address of a variable, would in essence be covered by an overload of the following kind:

```
  void declare_entry (const std::string           &entry,
                      const std::string           &default_value,
                      const Patterns::PatternBase &pattern = Patterns::Anything(),
                      const std::string           &documentation = std::string(),
                      std::string *member_string)
  {
    this->declare_entry (entry, default_value, pattern, documentation,
                                     [=member_string,=entry](...) { *member_string = this->get(entry); });
  }
```

In other words, the action is simply the assignment to the member variable. For other types of variables (ints, doubles, etc) one would have to come up with other variations, but the general idea would be the same.

To make this work in practice, I think that the `std::function` argument should probably have type

```
  bool (const ParameterHandler &prm,
           const std::string               &entry_name);
```

This way, whatever function object you get would have the ability to read its own parameter, without having to duplicate information about the parameter handler or the parameter's name at the location where you set up the lambda. The function could also return an error code that the `ParameterHandler` would then convert into an error. (Or we could allow for these function objects to throw exceptions.)

**Comment by tjhei** [comment]
I like the idea of removing some of the duplication in declaring/parsing of parameters, but I think your suggestion is too complicated. I wonder if we can have the user define a function that will be called twice, first to declare and then later to parse. That would be in a way similar to boost::serialization where the same function can handle serialization and deserialization. Maybe something like:
```
struct MyParameters
{
    void operator()(ParameterHandler &prm, bool declaring)
      {
	// for one to one mapping between variables and parameters it is easy:
	refinement = prm.declare_int("refinement", "1", Patterns::Integer(), "documentation");
	bla = prm.declare("bla","",Patterns::Anything(), "...");

	// maybe something complicated?
	std::string expression = prm.declare("formula","0",Patterns::Anything(), "...");
	if (!declaring)
	  {
	    fp.initialize(expression);
	  }

      }

    unsigned int refinement;
    std::string bla;
    FunctionParser fp;
};
```
The functions would just return their default value when we are in declaration-mode.

**Comment by Rombur** [comment]
Personally, I have starting to switch from ParameterHandler to boost::property_tree (http://www.boost.org/doc/libs/1_60_0/doc/html/property_tree/tutorial.html). It's a lot easier to use. You just call one function to parse the input file and when you need a variable you just need to do ```get```.  You don't need to declare anything. ```get``` can deduce the type of the variable or you can tell it what it is. You can even read object. I don't thing that you can give it a documentation string but we could write a wrapper around the property tree.

**Comment by bangerth** [comment]
On 02/29/2016 08:13 AM, Timo Heister wrote:
> I like the idea of removing some of the duplication in declaring/parsing of
> parameters, but I think your suggestion is too complicated. I wonder if we can
> have the user define a function that will be called twice, first to declare
> and then later to parse. That would be in a way similar to
> boost::serialization where the same function can handle serialization and
> deserialization. Maybe something like:
>
> [...]
>
> The functions would just return their default value when we are in
> declaration-mode.

Well, I think that's not much clearer either. At the very least I find the 
code quite unreadable because the same function call does something very 
different in different contexts. In practice you would also often have to 
write something like
|
   my_var = Utilities::split_string (Utilities::split_string(
      prm.declare (...), ","), ";");
|
which I find rather obscure.

It works for the serialization context because it simply changes the meaning 
of a single operator; you almost never have to run through different code paths.

**Comment by bangerth** [comment]
> Personally, I have starting to switch from ParameterHandler to
> boost::property_tree
> (http://www.boost.org/doc/libs/1_60_0/doc/html/property_tree/tutorial.html).
> It's a lot easier to use. You just call one function to parse the input file
> and when you need a variable you just need to do |get|. You don't need to
> declare anything. |get| can deduce the type of the variable or you can tell it
> what it is. You can even read object. I don't thing that you can give it a
> documentation string but we could write a wrapper around the property tree.


You know that ParameterHandler internally uses boost::property_tree, right? ;-)

We've had the conversation on numerous occasions whether it is worthwhile 
declaring parameters or not, but I think that it keeps with the spirit of 
deal.II to have checks and assertions in many places so that if you have an 
input file in which you have misspelled a parameter, or in which you give a 
parameter a value that is nonsensical, that you get an error. If you don't 
declare parameters, you can't detect misspelled parameters. As for warnings, 
you could of course do this in user code, but the reality is that people 
rarely do error checking, and I think there is value in doing this in the library.

There is also the case that if you declare parameters, you can automatically 
generate a manual from it. A substantial part of the ASPECT manual is 
automatically generated this way. Imagine how incredibly hard it would be to 
keep these sections up to date if you had to do it by hand.

**Comment by tamiko** [comment]
@bangerth Just a very quick remark on one point:

> I don't particularly care about the address of a variable -- that just seems fragile

With a lambda-capture like this:
```
[=member_string,=entry](...) { *member_string = this->get(entry); });
```
You're essentially doing the same thing. If ```member_string```, or ```entry``` go out of scope calling the lambda function results in undefined behavior.

Luca's approach has the advantage that the class automatically de-registers upon destruction.

I agree that the approach with ```ParameterAcceptor``` is specialized and might not be generic enough. But in my opinion it is worth at least a short discussion whether we want to include it to deal.II nevertheless.

@luca-heltai I radically simplified the mechanism and this is the result [1]: In order to declare parameters for a class:

```
class Discretization : public ParameterAcceptor
{
public:
  Discretization()
  {
    set_subsection("A - Discretization");

    add_parameter(&refinement,
                  "initial refinement",
                  "5",
                  Patterns::Integer(),
                  "number of initial refinement steps applied to coarse mesh");

    add_parameter(&order_mapping,
                  "order mapping",
                  "1",
                  Patterns::Integer(),
                  "order of the mapping");

    add_parameter(&order_fe_primal,
                  "order of the primal fe ansatz",
                  "1",
                  Patterns::Integer(),
                  "order of the primal fe ansatz");
  }

  virtual parse_parameters_callback() override
  {
    // ...
  }

private:
  unsigned int refinement;
  unsigned int order_mapping;
  unsigned int order_fe_primal;
};
```

And later on:
```
Discretization my_discretization;
// ...
ParameterAcceptor::initialize(parameter_file_name, log_file_name);
```

I love the simplicity of this.


[1] https://gist.github.com/tamiko/4cf629f238ea9b7a49987012745585f8

**Comment by tamiko** [comment]
@asartori86 *ping*

**Comment by tamiko** [comment]
@bangerth 

I also thought a bit about callbacks. What one could do (in ```ParameterAcceptor```, or in our ```ParameterHandler```) is to give a bit more <i>convenient</i> type of callback:

```
template<typename T>
void add_callback(
  const std::string &entry,
  const std::string &default_value,
  Patterns::PatternBase &pattern,
  const std::string &documentation,
  std::function<void(T)> &callback);
```

This could be used as follows:
```
add_callback<unsigned int>(
  "initial refinement",
  "5",
  ...,
  "number of initial refinement steps",
  [&](unsigned int refinement){
  // ... set up triangulation and apply refinement
  })
```

This would avoid unnecessary variables that only act as temporaries.

*ugh* But while writing this, I just realized there is a fundamental flaw in this design. This approach cannot work if a task (for which we want to have a callback) depends on more than one parameter.
Thus, I tend to keep just keep it simple.

**Comment by bangerth** [comment]
On 04/05/2016 01:45 PM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth> Just a very quick remark on one
> point:
>
>     I don't particularly care about the address of a variable -- that
>     just seems fragile
>
> With a lambda-capture like this:
>
> |[=member_string,=entry](...) { *member_string = this->get(entry); }); |
>
> You're essentially doing the same thing. If |member_string|, or |entry|
> go out of scope calling the lambda function results in undefined behavior.

I agree. It just strikes me as more explicit and reminds the user that 
the address is not only taken but kept. And as I mentioned, with the 
lambda you're also not limited to just the basic data types for the 
variables you write into -- it can be of any type as long as the lambda 
does the necessary conversions.

**Comment by bangerth** [comment]
Regarding the callback idea: In code such as this
```
add_callback<unsigned int>(
  "initial refinement",
  "5",
  ...,
  "number of initial refinement steps",
  [&](unsigned int refinement){
  // ... set up triangulation and apply refinement
  })
```
how does the `ParameterHandler` class figure out what the `unsigned int` argument is going to be? The value of `prm.get_integer("initial refinement")`? For this to work, you have to have a way to convert the string the user provides in the input file to the template argument type you specify to the `add_callback()` function. This can work for a fixed and limited number of types, but it is not particularly convenient for a lot of other cases where the value of a parameter is not a basic type but something more complicated. That's why I proposed that the callback I had in mind always takes a `std::string` as argument.

**Comment by tamiko** [comment]
> Regarding the callback idea: In code such as this
> ```
> add_callback<unsigned int>(
>   "initial refinement",
>   "5",
>   ...,
>   "number of initial refinement steps",
>   [&](unsigned int refinement){
>   // ... set up triangulation and apply refinement
>   })
> ```
> how does the `ParameterHandler` class figure out what the `unsigned
> int` argument is going to be? The value of `prm.get_integer("initial
> refinement")`? For this to work, you have to have a way to convert the
> string the user provides in the input file to the template argument
> type you specify to the `add_callback()` function.

Yes. The type discrimination is done by the template argument <unsigned
int>. The parameter can be defaulted to std::string. In that case,
calling without the type annotation is exactly your generic callback
(with string).

> This can work for a fixed and limited number of types, but it is not
> particularly convenient for a lot of other cases where the value of a
> parameter is not a basic type but something more complicated.

Well, Luca's code can convert to integral and floating point numbers,
std::vector<double>, std::vector<unsigned int>, and to dealii::Point so
far. This is very convenient.

Independently of this discussion, I'm sure we could write a conversion
function from std::string to almost all deal.II specific types that can
be meaningfully expressed in a parameter file.

Further, we could use this conversion function to write a templated

  ParameterHandler::get<T>

instead of get, get_integer, get_double, get_bool, ...

With that above callback approach is only limited to the number of cases
ParameterHandler::get<T> covers.

**Comment by bangerth** [comment]
On 04/06/2016 01:28 PM, Matthias Maier wrote:
>
>  > This can work for a fixed and limited number of types, but it is not
>  > particularly convenient for a lot of other cases where the value of a
>  > parameter is not a basic type but something more complicated.
>
> Well, Luca's code can convert to integral and floating point numbers,
> std::vector<double>, std::vector<unsigned int>, and to dealii::Point so
> far. This is very convenient.

Well, maybe, or maybe not. If you want to convert to a `std::vector`, 
what do you assume the separator is? A space? A comma? A semicolon? My 
point is that we can draw up all sorts of conventions, but they all make 
assumptions that seem somewhat arbitrary (and consequently easy to get 
wrong).


> Further, we could use this conversion function to write a templated
>
> ParameterHandler::get<T>
>
> instead of get, get_integer, get_double, get_bool, ...

Yes, this would be of independent interest.

**Comment by luca-heltai** [comment]
I'd like to revive this conversation (after one year...).

https://github.com/mathLab/deal2lkit/pull/347

This pull request introduced a new simplified version of `add_parameter`. It allows the following to work *just right* for a lot of types:
~~~

class MyClass : public ParameterAcceptor
{
public:
  MyClass(const std::string &name = "My Class",
          const unsigned int &i=0):
    ParameterAcceptor(name),
    i(i),
    vec(3,1)
  {
    add_parameter(this->i, "An integer");
    add_parameter(this->vec, "A vector of integers", "Some optional documentation");
  };

  void run() {
    ...
  }

private:
  unsigned int i;
  std::vector<unsigned int> vec;
}


int main ()
{
  MyClass  f;
  ParameterAcceptor::initialize("parameters.prm");
  f.run();
}
~~~

Currently supported types are:

~~~
double
int
unsigned int
bool
Point<1> 
Point<2> 
Point<3> 
std::vector<std::string> 
std::vector<double> 
std::vector<int>
std::vector<unsigned int> 
std::vector<Point<1> > 
std::vector<Point<2> >
std::vector<Point<3> >
std::vector<std::vector<std::string> 
std::vector<std::vector<double> > 
std::vector<std::vector<int> > 
std::vector<std::vector<unsigned int> >
~~~

Vector like objects (Points and std::vector of elementary types) are generated and parsed as separated by commas, while matrix like objects use commas and semi-columns. 

The default value is taken from the variable itself, the Pattern is generated in a consistent way internally according to the type. I tried making it optional to the entry, but our PatternBase has too little functionality to allow for automatic extraction of a type from it (which I'm doing here arbitrarily fixing a Pattern that works for me).

std::map support is forthcoming. I think this is valuable even if not as elaborated as @bangerth suggested, and it is simpler than @tamiko's suggestion. :)

If you want, I can attempt a clean up and a minimal class that provides this functionality in deal.II, and then we can discuss about ways to improve things...

**Comment by bangerth** [comment]
Do you have code to show that we can review? :-)

I have to admit that I'm still skeptical because I don't know what we should write into a `.prm` file or the `.xml` file if we need to write the state of the `ParameterHandler` object. But in the end, what I see you want to do is simply (i) to do some automatic inference of types, which I'm ok with (although I'm still skeptical as far as what exactly separators in lists and maps will be), and (ii) add an action. The latter simply can't be expressed in the `.prm` and `.xml` files, but then one can be of the position that if you want to use this functionality, then the action will simply be lost when writing a file -- and that that is probably ok.

So since I'm in the minority, let's move forward with this.

**Comment by luca-heltai** [comment]
I did not see your answer to this post, sorry. 

The actual code is developed, tested, and deployed in deal2lkit (http://mathlab.github.io/deal2lkit/class_parameter_acceptor.html). 

In particular, the code allows the following:

~~~
// Again your own class, derived from ParameterAcceptor
class MyClass : public ParameterAcceptor {
// We now fill the parameters inside the constructor
MyClass(std::string name) :
  ParameterAcceptor(name)
{
 add_parameter(member_var, "A param",  "Documentation");

 // With default pattern (constructed according to a static member method 
 // that infers the Pattern from another_member_var, and with no doc.
 add_parameter(another_member_var, "Another param");
}
...
};
int main() {
 // Make sure you build your class BEFORE calling
 // ParameterAcceptor::initialize()
 MyClass class;
 ParameterAcceptor::initialize("file.prm");
 class.run();
}
~~~

and tested here:

https://github.com/mathLab/deal2lkit/blob/master/tests/parameter_acceptor/global_parameter_acceptor_02.cc

**Comment by bangerth** [comment]
In #4274, @luca-heltai makes some suggestions for the next steps towards implementing what he had in mind. Principally, it boils down to two functions:
```
template<class T>
PatternBase Patterns::default_pattern(T &t);

template<class T> 
bool Patterns::to_type(const std::string &value_as_string, const Patterns::PatternBase &pattern, T &t);
```
These would then be used in a new signature for `ParameterHandler::declare_parameter()`:
```
template<class T>
void add_parameter(T &t, 
                                 const std::string &name, 
                                 const std::string &documentation="", 
                                 const Patterns::PatternBase &pattern=Patterns::default_pattern(T());
```
But, because the two new functions are related (for example, on how a list is separated by commas/semicolons/etc -- the pattern and the `to_type` function need to agree on this), I'd actually like to propose to put them into one class, say `PatternTranslator`:
```
template <typename T>
class PatternTranslator {
  public:
    some_type get_pattern();
    T convert_from_string (const std::string &) const;
};
```
This class would be specialized for all of the usual types. For example, for all of the scalar types, the latter function could be implemented using `std::istringstream`.

We could then use this as follows:
```
template<class T, class Translator>
void add_parameter(T &t, 
                                 const std::string &name, 
                                 const std::string &documentation="", 
                                 const Translator &translator = PatternTranslator<T>())
{
  declare_parameter (name, translator.get_pattern(), documentation);
  add_action (name,
                      [t, =translator](const std::string &value) {
                        t = translator.convert_from_string(value);
                     });
}
```
The advantage would be that one can create objects (like `PatternTranslator<T>`, but either specialized for other types `T`, or just an entirely separate class that just happens to have the same interface) that both describes how to translate a type `T` to a pattern, as well as get back from the string to a value.

A separate idea would be to simply extend the *pattern* classes themselves by a function `convert_from_string()`. That may actually be simplest approach because the patterns already have all of that knowledge. We could then use them in place of the "translator" object.

**Comment by luca-heltai** [comment]
My suggestion would be to add the following functionality to PatternBase:

~~~
virtual void PatternBase::to_type(const std::string &value_string, boost::any &value);
virtual std::string PatternBase::to_string(const boost::any &value);
~~~

I'll make a PR for this later today, reusing what I have in deal2lkit.

**Comment by luca-heltai** [comment]
Minimal Working example:

~~~

#include <boost/any.hpp>


class PatternBase {
public:
    virtual void to_value(const std::string &s, boost::any &v) const{
        int * i = boost::any_cast<int *>(v);
        *i = Utilities::string_to_int(s);
    }

    virtual std::string to_string(const boost::any &v) const {
        return Utilities::int_to_string(*(boost::any_cast<int *>(v)));
    }
};

int main ()
{
  initlog();
  deallog << 0 << std::endl;

  PatternBase p;

  int a = 5;
  boost::any b = &a;
  deallog << "To string: " << p.to_string(b) << std::endl;
  p.to_value("6",b);
  deallog << "To value: " << a << std::endl;
}
~~~

**Comment by luca-heltai** [comment]
The output is:

~~~
DEAL::To string: 5
DEAL::To value: 6
~~~

**Comment by luca-heltai** [comment]
With this, then it should be possible to simply add the following:

~~~
template<class T>
void add_parameter(T &v, const std::string &entry, const std::string &documentation, const PatternBase &pattern=PatternBase::default_pattern<T>()) {

declare_entry(entry, pattern.to_string(v), pattern, doc);
auto action = [&pattern] (

add_action(entry, [&pattern] (

**Comment by drwells** [comment]
I believe we finished implementing this at the 2019 workshop.
