### ISSUE TITLE
Fallout from complex PETSc changes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2269]
Related to the patches recently merged for #2033, there are a couple of tests that now fail and/or produce different answers. See here: http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1526

@davydden -- would you be willing to take a look?

**Comment by davydden** [comment]
will do...

**Comment by bangerth** [comment]
Oh, that was quick! :-)

**Comment by davydden** [comment]
i locally made those pass but `hp/matrices_hp`. This one is tricky as it fails on diff stage
```
--- output	Mon Feb 29 19:02:11 2016
1971: ***************
1971: *** 329288,329294 ****
1971:   (52,59) -0.06
1971:   (52,60) 0.18
1971:   (52,61) 0.00
1971: ! (52,62) 3.37
1971:   (52,63) -1.32
1971:   (52,64) 0.00
1971:   (52,65) -0.41
1971: --- 329288,329294 ----
1971:   (52,59) -0.06
1971:   (52,60) 0.18
1971:   (52,61) 0.00
1971: ! (52,62) 3.38
1971:   (52,63) -1.32
1971:   (52,64) 0.00
1971:   (52,65) -0.41
```
Looks like a roundoff errors. I dig where it comes from...

**Comment by bangerth** [comment]
The correct number if likely 3.375 (=3+3/8). The solution is to increase the output precision by one digit. Will work on a patch.

**Comment by davydden** [comment]
i think it must be related to https://github.com/dealii/dealii/pull/2249 and/or https://github.com/dealii/dealii/pull/2254 where I changed the order of multiplications for assembly.
