### ISSUE TITLE
step 17 and 18 of the RC don't without c++11

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#2282]
step 17 and 18 of the RC don't work without c++11 :-(
http://cdash.kyomu.43-1.org/testDetails.php?test=2481362&build=1563

**Comment by bangerth** [comment]
I'm not sure what this has to do with C++11. Is looks like there is simply a missing instantiation.

**Comment by Rombur** [comment]
I know but when we compile with c++11 there is no problem...

**Comment by bangerth** [comment]
That might just be coincidence. I bet we forget an *explicit* instantiation, but the compiler does an *implicit* one. For some reason or other, it nevertheless decides to export the symbol in C++11, but not otherwise. In either case, providing the explicit instantiation is the correct solution.

**Comment by tjhei** [comment]
I might have messed that up in https://github.com/dealii/dealii/pull/2277 ...

**Comment by tjhei** [comment]
I can reproduce the error, but I am confused because this isn't a template function.

**Comment by tjhei** [comment]
okay, got it. Patch incoming.

**Comment by Rombur** [comment]
Fixed
