### ISSUE TITLE
1d instantiation of DoFTools::make_flux_sparsity_pattern missing

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2290]
As reported by Weixiong Zhang on the mailing list:
...................................

I extended my code from 2D to 1D. It is a vector hyperbolic system. The spatial discretization is DG1. When in 2D, I specified which component coupled to which and then:
DoFTools::make_flux_sparsity_pattern (dof_handler, dsp, cell_coupling, face_coupling);

It was perfectly fine and saved tons of memories for me in 2D. But when I tried in 1D case, I got the following problem:

```
Undefined symbols for architecture x86_64:
  "void dealii::DoFTools::make_flux_sparsity_pattern<dealii::DoFHandler<1, 1>, dealii::DynamicSparsityPattern>(dealii::DoFHandler<1, 1> const&, dealii::DynamicSparsityPattern&, dealii::Table<2, dealii::DoFTools::Coupling> const&, dealii::Table<2, dealii::DoFTools::Coupling> const&)", referenced from:
      NFPN_1D<1>::setup_system() in nfpn1d.cc.o
ld: symbol(s) not found for architecture x86_64
```

If I just use
DoFTools::make_flux_sparsity_pattern (dof_handler, dsp);

It will be fine.

So I am curious what's going on there.

Thanks in advance!
Weixiong

**Comment by bangerth** [comment]
@drwells already seems to have volunteered to look at the missing instantiation.

**Comment by drwells** [comment]
Yes, I should probably move the discussion on the mailing list here. Here is what I just posted there:

I don't have the error messages in front of me right now so my following description may be slightly wrong.

 The problem ultimately lies with the fact that a face in 1D resolves to something like TriaAccessor<0, 1, 1>, which does not have a user flag variable; make_flux_sparsity_pattern keeps track of its progress by setting user flags on faces. Additionally, the function only couples dofs with support on the shared face, not all dofs.

**Comment by bangerth** [comment]
> I don't have the error messages in front of me right now so my following
> description may be slightly wrong.
>
>   The problem ultimately lies with the fact that a face in 1D resolves to
> something like TriaAccessor<0, 1, 1>, which does not have a user flag
> variable; make_flux_sparsity_pattern keeps track of its progress by setting
> user flags on faces. Additionally, the function only couples dofs with support
> on the shared face, not all dofs.

Interesting. Aren't there methods where it is enough if a shape function has a nonzero *gradient* to couple to the neighbor?


> Nevertheless you are probably right and we should probably specialize this
> function in 1D since the refinement behavior is different; I will look at it
> some more this evening.

Yes, I think doing an explicit specialization for the 1d case would be simplest, given that the 1d situation is so much simpler to deal with.
