### ISSUE TITLE
Do not rely on user flags for logic

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2293]
There are several places in the library where we do this and I suspect they are all sources of subtle bugs: the issue with `make_flux_sparsity_pattern` (#2290) is a good example because if the user sets all the flags on the triangulation before calling that function then it will not generate a sparsity pattern. In other places we manipulate user flags while violating const correctness.

To this end, I propose that we eliminate the usage of `user_flags` for logic in the library.

**Comment by bangerth** [comment]
I think this is the correct approach. In many places, we save and later restore the user flags. That at least avoid the problem you describe. But it still doesn't allow the function to be called twice on different threads, even though it claims that it keeps the triangulation `const`. This has been a long-standing wart in many parts of the library.

**Comment by tjhei** [comment]
Agreed. I find the whole flags/pointer union approach annoying too. Ideally there would be a way to easily allocate a helper object that can contain arbitrary data per cell (maybe just a ``std::vector<T>`` indexed by ``cell_index``?). Than we could deprecate/remove all of the ``user_flags``.

**Comment by drwells** [comment]
I looked at `make_flux_sparsity_pattern` more closely; I misread which function was calling which before so the issue I stated does not exist (we use a `const_cast` to clear the flags and then restore them).

Regardless, it is not too hard to get rid of those `const_cast`s, and we can support 1D while we do it.

**Comment by bangerth** [comment]
The const cast is unpleasant but not wrong in general, but it becomes wrong code if one calls two functions that use user flags this way on different threads. The right thing to do is to replace this mechanism with something that keeps track of everything *on the side of the using function*, not *on the side of the used triangulation*.

**Comment by drwells** [comment]
Yes, I agree. It should be possible to do this in many cases (like in #2294) by using the total ordering of cells instead.

**Comment by drwells** [comment]
This has been open for a long time but the current approach has a few advantages:
1. We do it all over the place
2. It does not require allocating extra memory
3. It works when we have to do things indexed by lines, quads, or other weird things

Refactoring this isn't a priority so lets close the issue.
