### ISSUE TITLE
Expression template syntax to build FESystem

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2299]
The syntax to initialize FESystem objects is not bad, but it occurred to me that with relatively little effort, it should be possible to do something like

```
  FESystem<dim> stokes_fe = (FE_Q<dim>(2) ^ dim
                                                  +
                                                  FE_Q<dim>(1));
```

The only things that need to be overloaded are `operator +` and `operator ^` for finite elements and for an fe-composition-expression. A total of 4 operators should be enough.

**Comment by danshapero** [comment]
If you instead write `FE_Q<dim>(1) + FE_Q<dim>(2)^dim`, you'll get a different `FESystem` though, correct? If that's the case, the `+` notation could be considered misleading since the operation isn't actually commutative. It could also be considered perfectly fine and I'm just being pedantic.

Alternatively, one can define a variadic template constructor:
```
template <typename... Args>
FESystem<dim>::FESystem(Args&&... args);
```
where each argument is of some type `FiniteElementExpr` that would need to be defined. The variadic arguments would be unpacked into the vectors of, respectively, shared pointers to finite elements and their multiplicities. This should make it possible to use list-initialization, like so:

`FESystem<dim> stokes_fe = {FE_Q<dim>(2) ^ dim, FE_Q<dim>(1)};`

Depending on taste, that notation might be more to your liking.

**Comment by luca-heltai** [comment]
Well, we might have just found a place where `operator,()` could be interesting:

~~~
auto FE = FE_Q<2>(1), FE_Q<2>(2)
~~~

**Comment by davydden** [comment]
i like `operator,()` idea!

**Comment by bangerth** [comment]
Basically every binary operator seems to me to be an intuitive choice for combining things, including `operator &&`, `operator |`, and `operator,`.  I know you didn't propose the latter in seriousness, but for completeness: it leads  to awkward situations because
```
  int i = 1,2;
```
is a syntax error, whereas
```
  int i = (1,2);
```
is correct (and invokes `operator,` on two integers: it simply throws away the first of the two).

**Comment by davydden** [comment]
how about `operator *` as that's actually what we do - a tensor product of two spaces? It also does not imply any commutative properties and perhaps is less confusing for users.

**Comment by bangerth** [comment]
I still think that `operator+` is the most intuitive choice in the sense of "this and that together form a list".

**Comment by Rombur** [comment]
I don't like ```operator+``` because like @danshapero said the operation is not commutative. Is there anywhere else in the library where ```a+b``` is different than ```b+a```? I think people are so used to have ```a+b=b+a``` that this will create bugs that are hard to find.

**Comment by bangerth** [comment]
Hm. I don't particular care for `operator *`. That's not how I think of connecting two finite elements. What about `operator &&` then?

**Comment by tamiko** [comment]
Just about any ```operator▢``` is misleading.

Personally, I think ```{…, …}```, or ```(…, …)``` might be choices we should consider.
@danshapero proposal
```
FESystem<dim> stokes_fe = {FE_Q<dim>(2) ^ dim, FE_Q<dim>(1)};
```
is a pretty nice syntax, isn't it?

**Comment by danshapero** [comment]
@tamiko -- I should mention that the `{...}` syntax would require variadic templates and thus be a C++11-only solution. That said, having a variadic constructor could eliminate all the overloads for constructing an `FESystem` with 1...5 different finite elements when #1519 comes to pass.

Alternatively, if there is disagreement on which syntactic sugar to choose, it may be best to go with none at all.

**Comment by tamiko** [comment]
> [...] thus be a C++11-only solution.

Yes, I was aware of that. :-)
I don't see any necessity for a feature like this to be implemented in C++98.

**Comment by bangerth** [comment]
I'm reading through this again in the context of #11066. I agree that an `operator+` or `operator*` would be nice when building, say, the Taylor-Hood space:
```
  FE_Q<dim>(2)^dim * FE_Q<dim>(1)
```
Did we reject this idea, or did we just never got around implementing it?

(I really wished that one could overload `operator \times`. That's what mathematical notation uses...)

**Comment by masterleinad** [comment]
I think we just found one solution that everyone was fine with whereas `operator+` and `operator*` were thought to be misleading.
