### ISSUE TITLE
Update syntax in tutorials for C++11 in new_thread/new_task calls

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2300]
Once we require C++11 (see #1519), we should also see whether there are places in the tutorials where we could introduce a slightly different style. For example, #2289 should allow using a cleaner syntax in some places where we call `Threads::new_task` and `Threads::new_thread`. (There are also places in the library where we currently explicitly cast to a `std::function` object from something that uses `std::bind` that will no longer require the cast.)

**Comment by drwells** [comment]
We've made enough progress on tutorial modernization that I believe we can close this now.
