### ISSUE TITLE
Other FilteredIterator issues

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2319]
This generalizes #2311 (I now see that they are related). It looks like the tester does not like some of the forward declarations:

http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1701

**Comment by bangerth** [comment]
Is this before or after #2318? The issue in loop.h was that we were using `FilteredIterator` in functions inside `namespace internal`, but @Rombur's original test introduced a namespace `internal::FilteredIterator` which changes what name lookup finds in `loop.h`. I fixed this by referencing the correct class by prefixing it by `dealii::FilteredIterator`. I think it's the same problem in all of the compile failures you link to.

**Comment by drwells** [comment]
Good point. Let me check.

**Comment by drwells** [comment]
Yup, that fixed it.
