### ISSUE TITLE
strange error in solution_transfer

### ISSUE THREAD

**Issue by asartori86** [dealii/dealii#2334]
hi, I'am solving the Poisson problem with coarsening and refinement and, depending on the number of initial refinement and/or the combination of the top and bottom fractions in the refinement strategy, I may get this error

```
An error occurred in line <468> of file <../source/numerics/solution_transfer.cc> in function
    void dealii::SolutionTransfer<dim, VectorType, DoFHandlerType>::interpolate(const std::vector<index_type, std::allocator<_T2> >&, std::vector<index_type, std::allocator<_T2> >&) const [with int dim = 2; VectorType = dealii::BlockVector<double>; DoFHandlerType = dealii::DoFHandler<2>]
The violated condition was: 
    !cell->has_children()
The name and call sequence of the exception was:
    ExcInternalError()
Additional Information: 
This exception -- which is used in many places in the library -- usually indicates that some condition which the author of the code thought must be satisfied at a certain point in an algorithm, is not fulfilled. An example would be that the first part of an algorithm sorts elements of an array in ascending order, and a second part of the algorithm later encounters an an element that is not larger than the previous one.

There is usually not very much you can do if you encounter such an exception since it indicates an error in deal.II, not in your own program. Try to come up with the smallest possible program that still demonstrates the error and contact the deal.II mailing lists with it to obtain help.
```

any idea why this happens? thanks

**Comment by asartori86** [comment]
just for reference, this is the movie when every goes fine 
![poisson](https://cloud.githubusercontent.com/assets/10710861/13700827/ada2e75c-e783-11e5-8bd2-736b6d410c52.gif)

**Comment by bangerth** [comment]
A reproducible testcase would be helpful, I think.

**Comment by asartori86** [comment]
@bangerth, If you want I may provide a pi-DoMUS test, not sure I can provide a short one that triggers it

**Comment by bangerth** [comment]
I think anything would help.

I'm going to be traveling for most of the next 2 weeks. I can not say how much time I will have to help with anything that requires more than 10 minutes, but I will try.

**Comment by bangerth** [comment]
I don't think there is very much we can do about this issue without a way to reproduce it. @asartori86 -- is this still happening with current developer versions?

**Comment by davydden** [comment]
@asartori86 maybe you can do a serial version of Poisson problem with parameters which trigger the error? That can be done in a very concise way using deal.ii's matrices and `MatrixCreator::create_laplace_matrix`.

**Comment by drwells** [comment]
Without a minimum working example there is nothing for us to do here. We can always reopen the issue if we have a clear bug report.
