### ISSUE TITLE
Periodicity in ChartManifold

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#2335]
The test in 

https://github.com/luca-heltai/dealii/pull/90

fails. This is probably due to a bug in the periodicity handling of ChartManifold...

**Comment by bangerth** [comment]
@luca-heltai -- did we conclude that the test is actually doing the right thing? In that case, I think this can be closed.

**Comment by luca-heltai** [comment]
Yes. The test is actually right.
