### ISSUE TITLE
submitting tests results for an already installed library

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2360]
One can run unit tests for an already installed library. 
I don't know how difficult is this, but it would be cool to be able to also submit those results in such a case. Currently `ctest [...] -V -S ../tests/run_testsuite.cmake` fails when being used for an already installed library.

p.s. the usage scenario is when one would like to test multiple versions of deal.ii (say MKL and system blas), but deal.ii build folder is not available.

**Comment by tamiko** [comment]
This should do the trick:

```
mkdir build && cd build
cp $DEAL_II_SOURCE_DIR/CTestConfig.cmake .
ctest \
  -DCTEST_SOURCE_DIRECTORY=$DEAL_II_SOURCE_DIR/tests \
  -DDEAL_II_DIR=$DEAL_II_DIR \
  -DMAKEOPTS="-j8" -j8 -S $DEAL_II_SOURCE_DIR/tests/run_testsuite.cmake -V
```

**Comment by bangerth** [comment]
If you don't have the build directory around any more, where do you run the testsuite? As in @tamiko 's example in *any* directory?

**Comment by luca-heltai** [comment]
Yes. This has been working for me for quite some time now. I often use this strategy to figure out if the packages I pass around to my colleagues pass or not a specific test.

**Comment by davydden** [comment]
@bangerth yes, i run it from essentially arbitrary folder and just point to the cmake file in tests.

**Comment by davydden** [comment]
thanks @tamiko , that seemed to be working. Could you please update the documentation at https://www.dealii.org/developer/developers/testsuite.html to show this example?
