### ISSUE TITLE
Find a replacement for CDash

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#2369]
Seriously.

Suggestions?

**Comment by bangerth** [comment]
What are the problems you are trying to address?

**Comment by tamiko** [comment]
@bangerth I was very annoyed by upstream's new mandatory "installer" (```curl [untrusted source] | bash```) introduced in 2.2.3. Further, migrating to 2.2.3 with my custom changes is a lot more difficult than expected. The reason why I want to have the new version is a number of bugfixes for postgresql.

I will give this mess another try later, but in the long run I fear we need something more robust.

**Comment by tjhei** [comment]
Well, are there alternatives that parse ctest output to display changes in tests?

**Comment by tamiko** [comment]
> Well, are there alternatives that parse ctest output to display changes in tests?

After a bit of digging... out of the box, not really.

**Comment by tamiko** [comment]
We'll just keep it as it is for the moment.

**Comment by tjhei** [comment]
@tamiko cdash is not updating, do you know what is going on?
