### ISSUE TITLE
Several warnings when compiling using CUDAs nvcc

### ISSUE THREAD

**Issue by kalj** [dealii/dealii#2382]
When compiling code using Deal.II with the nvcc compiler of Nvidia CUDA, several new warnings appear.
1. Unreachable statements
2. Implicit type casts
3. Unused function parameters

1 and 2 are quite straightforward to fix, and the pull request #2380 does this.

On the other hand, 3 requires some way of hiding parameters at compile time depending on whether a DEBUG or RELEASE build is being done. I have a suggestion in pull request #2381 .

Of course, these are just the code lines which give warnings in my case, so I'm sure there are others of the same type, but this is a start.

PS. This is my first issue report / pull request, so if I should split the issue and/or pull request into several smaller ones, just tell me!

**Comment by tamiko** [comment]
For 3 we have used the sledgehammer approach of utilizing otherwise unused function parameters in a cast to void:
```
(void) vec;
(void) dof_info;
```
See comment on #2381

**Comment by tamiko** [comment]
> PS. This is my first issue report / pull request, so if I should split the issue and/or pull request into several smaller ones, just tell me!

That's fine :-)

**Comment by kalj** [comment]
Another, more severe problem is in the bundled TBB. When compiling with CUDA, this gives errors of the following type:

~/sw/deal.II/include/deal.II/bundled/tbb/concurrent_vector.h(667): error: ambiguous "?" operation: second operand of type "tbb::internal::concurrent_vector_base_v3::size_type" can be converted to third operand type "tbb::atomic<unsigned long>", and vice versa

~/sw/deal.II/include/deal.II/bundled/tbb/concurrent_vector.h(680): error: ambiguous "?" operation: second operand of type "tbb::internal::concurrent_vector_base_v3::size_type" can be converted to third operand type "tbb::atomic<unsigned long>", and vice versa

This is fixed in the most recent stable version (4.4), but maybe we want to do something about the situation in the meantime? If that is the case, then #2384 implements a fix.

**Comment by bangerth** [comment]
Please close if you think that the issues are addressed with the merged patches.

**Comment by kalj** [comment]
Not quite done yet. :)

Finally, there are several warning coming from within Boost.

They are all reported upstream, but, except for a simple one, not yet fixed:

https://svn.boost.org/trac/boost/ticket/11763 (fixed)
https://svn.boost.org/trac/boost/ticket/11933
https://svn.boost.org/trac/boost/ticket/11934
https://svn.boost.org/trac/boost/ticket/12078

I have a commit that fixes that first one, but since it is only a warning, maybe we can live with it and avoid patching another bundled package. Ok?

**Comment by bangerth** [comment]
These warnings only happen with a compiler few people use, and we don't know yet how they will be fixed upstream. This makes me hesitant.

How often do you get to see these warnings? Do they only happen when building the library, or also when compiling user code? Could we work around them using compiler flags that simply suppress the warnings?

**Comment by bangerth** [comment]
(But I'd be quite willing to accept patches for things that were already fixed upstream.)

**Comment by bangerth** [comment]
Alternatively, we could just update boost, see #1963.

**Comment by kalj** [comment]
@bangerth True, this is a very narrow scenario at the moment. And as I said, I can only fix one out of maybe 6-10 warnings. The others are too complicated for me to grasp, and upstream hasn't yet done anything about them. So I wouldn't object if we left it as is for now. Still, showing that we are aware of them might be comforting to users.

It does happen when compiling the user code though, as it is in headers. With nvcc, I think one can only disable *all* warnings, but that seems a bit too hefty to me.

**Comment by bangerth** [comment]
Feel free to propose patches for everything you find is already fixed upstream. We can reconsider things once we update boost.

**Comment by tamiko** [comment]
I suggest we leave the situation as it is at the moment. We can try to address compiler warnings as soon as the cuda stuff is more complete.
