### ISSUE TITLE
dyld error with version 8.4.0 on Mac OSX Yosemite

### ISSUE THREAD

**Issue by sunnie229** [dealii/dealii#2392]
Hi, 
I am trying to install dealii version 8.4.0 on Mac OSX Yosemite. I downloaded the .dmg file and when I try to compile one of the examples, I get the following error:

dyld: Library not loaded: /Applications/deal.II.app/Contents/Resources/opt/openmpi-1.10.2/lib/libmpi_cxx.1.dylib
  Referenced from: /Applications/deal.II.app/Contents/Resources/examples/step-2/./step-2
  Reason: Incompatible library version: step-2 requires version 3.0.0 or later, but libmpi_cxx.1.dylib provides version 2.0.0

Please help!

**Comment by tjhei** [comment]
I think we only support the newest OSX version with this binary installer. Right, @luca-heltai ?

**Comment by luca-heltai** [comment]
This may happen if you have another version of mpi installed. What is the output of the command `which mpicc`? And of the command `locate libmpi_cxx.1.dylib`?

**Comment by davydden** [comment]
@sunnie229 do you still have the issue? Can you please check what @luca-heltai asked?

**Comment by tamiko** [comment]
@sunnie229 Please reopen if you still have the issue.
