### ISSUE TITLE
deal.ii cannot be bundled as a CMake subproject to another project

### ISSUE THREAD

**Issue by DAlexis** [dealii/dealii#2393]
During development of another project we decided to bundle deal.ii. We are using CMake and git so we added git submodule to out project and used `add_subdirectory(3rdparty/dealii)` in our CMakeLists.txt

But this does not work because deal.ii's CMakeLists.txt "think" that deal.ii is always root cmake project, i.e. it use ${CMAKE_SOURCE_DIR} variable assuming it points to deal.ii source dir (right way is using ${deal.II_SOURCE_DIR}). The same is for ${CMAKE_HOME_DIRECTORY} and ${CMAKE_BINARY_DIR} cmake variables.

We used workaround: we fix these variables before calling `add_subdirectory(3rdparty/dealii)`. But with latest CMake 3.5 this hack does not work, ${CMAKE_SOURCE_DIR} are automatically set back in subprojects.

**Comment by drwells** [comment]
Thank you for reporting this. This does not look like it should be too difficult, in theory, to fix our handling of directories. @tamiko will this be easy to change with our current set up by just exchanging `CMAKE_SOURCE_DIR` for something specific to deal.II? If so I can try to fix this in the near future.

**Comment by tamiko** [comment]
@drwells I'm not compelled by this very idea.

We already provide multiple options to include a non-intrusive projection configuration for deal.II. This also includes the case of configuration and building deal.II as an external project of another one, have a look for example at ```deal.IITargets.cmake``` and the handling of this in ```deal.IIConfig.cmake```.

Further, I don't know of a single project of the size of deal.II that also tailors their build system to be compatible to just ```ADD_SUBDIRECTORY``` it.

**Comment by DAlexis** [comment]
I found that replacing some variables in cmake files is enough to fix this issue so I wrote simple patching bash script.

Can I make a pull-request with my changes?

**Comment by tamiko** [comment]
@DAlexis Yes, please go ahead.

**Comment by tamiko** [comment]
@DAlexis If time permits, I would still like to see the pull request - I am sorry that my first reply was several months apart.
