### ISSUE TITLE
GridRefinement -> GridMarking

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#2412]
We have always called our marking processes through the functions in the namespace `GridRefinement`. I think this is a big misnomer. 
- Estimate -> KellyErrorEstimator
- Mark -> refine_and_coarsen_fixed*
- Refine -> execute_refinement

Maybe we should rename things? GridMarking?

**Comment by bangerth** [comment]
It's a valid point. I've always thought of namespace `GridRefinement` as `GridRefinementTools`, in analogy to all of the other `*Tool` namespaces. I don't think it matters very much whether we call it one way or the other, but it might be worth stating something like this in the first sentence of the namespace description.
