### ISSUE TITLE
vector*symmetric tensor doesn't work

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2413]
This doesn't work:
```
  Tensor<1,dim> v;
  SymmetricTensor<2,dim> S;
  v*S*v;
```
whereas this works:
```
  Tensor<1,dim> v;
  SymmetricTensor<2,dim> S;
  v*(S*v);
```
Make the former happen as well.

(Or is this a bad idea, since we don't distinguish between row and column vectors this way?)

**Comment by davydden** [comment]
> (Or is this a bad idea, since we don't distinguish between row and column vectors this way?)

perhaps i don't see it, but i think it's ok as you wrote, we could also check `v*S*v=(v*S)*v=v*(S*v)` as this essentially just dot products.

In order to get something like `v^H S v` we would need some extra function, I think there is one already but for `v^T S v == v*S*v`.

**Comment by bangerth** [comment]
So you think that the product of a `Tensor<1,dim>` and a `Tensor<2,dim>` should just be a `Tensor<1,dim>`?

**Comment by davydden** [comment]
in the way we use it - yes. My perception is that Tensor algebra in deal.ii is all about dot products. So I would say it's fine.

Whereas for `v^H S v` we would actually need to have a `HermitianTensor<2,dim> H`, but IMHO this is an overkill to implement.

**Comment by davydden** [comment]
oh put it in another way, one of the definitions of a second order tensor is a linear operator which acts on a first order tensor to map it to first oder tensor. So i would say we are good here.

**Comment by davydden** [comment]
you might be right if one thinks about manifolds, though... hm...

**Comment by bangerth** [comment]
What do others think?

**Comment by KristofferC** [comment]
As someone new to deal.ii, I think that making  `v * S` behave as `v_i S_ij` would be totally what I expected it to do.

**Comment by bangerth** [comment]
For the record, this already works for regular tensors.
