### ISSUE TITLE
Better data structure for Mapping*::InternalDataBase::unit_tangentials

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2424]
As pointed out in a comment in #2272, the `Mapping*::InternalDataBase::unit_tangentials` fields are stored as vectors-of-vectors, but both dimensions are actually known at compile time. Use a better data structure for this that is cheaper to allocate and access.

In reference to #1198.

**Comment by drwells** [comment]
Closed by #2471.

**Comment by bangerth** [comment]
Actually, let's keep it open for the moment since #2272 is going to introduce the same issue for the `MappingManifold` class.
