### ISSUE TITLE
Move constructors for class Quadrature

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2425]

**Comment by bangerth** [comment]
We have started returning `Quadrature` objects from a number of functions. This could be made more efficient using move semantics, for which we would need move constructors for this class.

@danshapero -- you mentioned that you would be interested in looking at move constructors of a number of classes. This might be a simple candidate.

**Comment by bangerth** [comment]
See #898.

**Comment by danshapero** [comment]
I think if `Subscriptor` had a move constructor that did the correct error handling, several classes could have the default move constructor:

    Quadrature(Quadrature<dim>&&) = default;

Either way, I'll work on it this week.

**Comment by bangerth** [comment]
That would be fantastic. And I think you're right that giving `Subscriptor` a move constructor would make things a lot simpler, as one would then simply have to *declare* but not *implement* the move constructor of derived classes (just like you show). Excellent point!

**Comment by bangerth** [comment]
@danshapero -- now that the move constructor for the base class has been merged, want to add the move constructor for `Quadrature` as well, with a little test case?

**Comment by danshapero** [comment]
Sure thing, I [started this](https://github.com/danshapero/dealii/tree/move-ctors) the other day and just need to write the test.

Any class like Quadrature which doesn't explicitly manage heap memory can probably use the default move constructor. For classes like `Vector` and `SparseMatrix` the situation is more complicated, but I'll raise that in a separate issue. Are there other classes that you think would be good candidates?

**Comment by bangerth** [comment]
I can't think of anything that we typically return by value and where this would make a significant difference. I think the `Table` class might be the only other candidate.
