### ISSUE TITLE
Select well-conditioned basis for default FE_Q and FE_DGQ constructors

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#2438]
Given the recent discussion in #2436 and a number of similar discussions we had in the past, I think that we should change the default constructor of FE_Q and FE_DGQ to the support points of the Gauss-Lobatto quadrature formula (this was also suggested by @guidokanschat a few years ago). According to literature, those have proper scaling of condition numbers in terms of O(degree). I have also verified that the internal checks work up to degree 40 in 2D and degree 20 in 3D. Thus, we should promote the use of appropriate polynomials as a default.

If somebody wants to use equidistant points, that's still possible through QIterated<1>(QTrapez<1>(), degree). But I see little value in using the equidistant basis beyond degree 3 apart from teaching, so I don't think that's appropriate for the default constructor. The pictures for Q4 we show here https://www.dealii.org/8.4.0/doxygen/deal.II/classFE__Q.html already show that degree 4 oscillates quite a bit (by comparing to the Gauss-Lobatto support points one realizes that this is more than necessary). I had a different opinion a few years ago, but changed my mind given that this topic comes up quite frequently when people use the ill-conditioned equidistant basis way beyond the stable range and wonder why certain things in the library break.

**Comment by kronbichler** [comment]
For reference, here is a test where we check the condition number of a mass matrix on a 4^d uniform mesh for some polynomial degrees:
https://github.com/dealii/dealii/blob/master/tests/matrix_free/estimate_condition_number_mass.with_lapack%3Dtrue.output
At degree 6, the mass matrix with equidistant points has a condition number of 1600, whereas with Gauss-Lobatto points we have 140. At degree 10, it is 2.2e6 vs. 330.

**Comment by Rombur** [comment]
I am not a big fan of this change. When I use GaussLobatto points, the discretization error is larger than when I use GaussLegendre points (for low order FE). I am pretty sure that the huge majority of people use low-order elements, so I don't think we should make their code worse just to accommodate a tiny minority.

**Comment by tjhei** [comment]
One option would be to only switch to Gauss-Lobatto points when the order is "high" (something like 4 or so).

**Comment by kronbichler** [comment]
@Rombur Are you sure we are talking about the same thing here? I was only suggesting to change the support points of the polynomials to a different, more well-conditioned set of points. For a usual Galerkin discretization that takes the minimal distance of the polynomial space to the analytical solution, the support point location should not affect the discretization error because the polynomial space is the same. In other words, the only difference for the user would be
- that the points are non-equidistant for `degree >= 3`,
- that the condition number of linear systems, mass matrices, etc. would be vastly better, 
- that embedding and restriction have fewer points that coincide when going from mother to child, including hanging node constraints where the equidistant points have some identity constrained points in the equidistant case (but that is a very small price when looking at the overall picture).
(Besides this being an incompatible change.)

Of course, Gauss-Lobatto quadrature is less accurate than Gauss quadrature and I would definitely not propose to change to a less accurate quadrature. (For example, there is evidence that Gauss-Lobatto quadrature reduces the order of convergence on non-affine meshes.)

This also means that nothing would change for polynomial degrees 1 and 2 (or 0, 1, 2 for FE_DGQ) where most users are active. For higher degrees, the change would be incompatible but vastly better in almost any aspect. We would make a basis that is actually useful the default - **the** standard choice throughout the spectral element community on continuous elements. (As a side node, I also promise to write some documentation of the conditioning of the polynomial interpolation for FE_Q and FE_DGQ whatever the decision from this issue would be. The current state is a bit poor and it does not surprise me that this issue comes up from time to time.)

**Comment by bangerth** [comment]
On 03/31/2016 02:15 PM, Martin Kronbichler wrote:
> This also means that nothing would change for polynomial degrees 1 and 2
> (or 0, 1, 2 for FE_DGQ) where most users are active. For higher degrees,
> the change would be incompatible but vastly better in almost any aspect.

I think that's a useful compromise.

**Comment by Rombur** [comment]
@kronbichler Yes, you are right.

**Comment by davydden** [comment]
> One option would be to only switch to Gauss-Lobatto points when the order is "high" (something like 4 or so).

that might be confusing for usage in hp-dofhandlers with user code like
```
for (p=1; p < 10; p++)
   hp_doflandler.push_back(FE_Q<dim>(p))
```
leading to a mixture of different elements.

**Comment by Rombur** [comment]
I agree with @davydden mixing Gauss-Lobatto Gauss-Legendre is going to be weird when using hp-dofhandler.

**Comment by bangerth** [comment]
On 03/31/2016 02:59 PM, Denis Davydov wrote:
> that might be confusing for usage in hp-dofhandlers with user code like
>
> |for (p=1; p < 10; p++) hp_doflandler.push_back(FE_Q<dim>(p)) |
>
> leading to a mixture of different elements.

As @kronbichler explained, because Gauss-Lobatto == Gauss-Legendre for 
p=1,2, the reasonable suggestion would be to change the default for 
p>=3. This is equivalent to changing it for all p, of course, except 
that it makes no difference for p=1,2.

**Comment by davydden** [comment]
@bangerth I was not supporting the change from `something like 4 or so`, where that would make a difference. I think it should be Gauss-Lobatto or Gauss-Legendre for all p. The fact that they are the same for p=1,2 should be mentioned, of course.

**Comment by tamiko** [comment]
I support this change.

I have heard the comment that deal.II would not support finite elements with polynomials beyond degree 4 way too often.

**Comment by drwells** [comment]
I also support this change for the reasons @kronbichler outlined.
