### ISSUE TITLE
8.4.1 release

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#2443]
There is a stupid bug (extra typename) in source/grid/grid_tools.inst.in that makes it impossible to compile deal 8.4.0 with an old compiler like gcc 4.4 The bug is fixed in the development version but I wonder if we should patch 8.4.0.

**Comment by bangerth** [comment]
@tjhei -- you've done the packaging. How much effort would this be?

**Comment by tamiko** [comment]
@bangerth Not much.

**Comment by tamiko** [comment]
@Rombur What commits exactly?

**Comment by davydden** [comment]
@tamiko while we are at it, could you please cherry-pick the following two commits which improve unit tests:
a single commit from https://github.com/dealii/dealii/pull/2374 : b6fb0d2
and two commits from https://github.com/dealii/dealii/pull/2363 : 4ab7eec , 7b0b8bd
That will not change anything for users, but it will be more convenient to run tests on `deal.ii-8.4.1` branch (when it is created).

**Comment by tjhei** [comment]
I am happy to do the 8.4.1 release, or are you volunteering @tamiko ? It is probably an hour or so of work.

**Comment by tamiko** [comment]
@tjhei Please go ahead. :-) Otherwise, I can try to find some time for a release tomorrow.

**Comment by Rombur** [comment]
Here is the commit I was talking about #2364

**Comment by tjhei** [comment]
see #2452

**Comment by tjhei** [comment]
Quick question, do we need a separate changelog for 8.4.1? (that would probably only contain "make compile with old gcc"). I assume the answer is yes.

**Comment by Rombur** [comment]
Yes, otherwise a bunch of people will update their version of deal without any good reason.

**Comment by tjhei** [comment]
Okay, I tagged the release. Before announcing it on the website, can somebody else give the tarball a spin, please?

@luca-heltai can you please create the OSX release?

@guidokanschat can you please upload the 8.4.1 documentation to the webserver?

(documentation tarball will be ready in a few)

**Comment by tjhei** [comment]
see https://github.com/dealii/dealii/releases/tag/v8.4.1

**Comment by bangerth** [comment]
On 04/07/2016 10:37 AM, Timo Heister wrote:
> @luca-heltai <https://github.com/luca-heltai> can you please create the
> OSX release?

I don't think that's really *necessary* given that the only difference 
is to make things compile with older compilers. (I did, apparently, 
compile with the compilers @luca-heltai used.) But it won't hurt either.

**Comment by luca-heltai** [comment]
I'm creating the new package right now, just to be consistent in the releases.

**Comment by luca-heltai** [comment]
If the documentation is ok, we can close this issue. @guidokanschat ?

**Comment by tjhei** [comment]
It doesn't look like dealii.org/8.4.1/ is online yet.

**Comment by davydden** [comment]
i just checked it, the documentation is indeed not yet there

**Comment by bangerth** [comment]
@guidokanschat?

**Comment by tjhei** [comment]
we did this yesterday.
