### ISSUE TITLE
Step-36 some mistake in the doc

### ISSUE THREAD

**Issue by elasto** [dealii/dealii#2454]
Almost at the end of the section "Eigenvalues and Dirichlet boundary conditions" I think that the spurious eigenvalues are provided by:
 \epsilon_{h,j} = D_{A}_{jj} /  D_{M}_{jj} instead of \epsilon_{h,j} = D_{A}_{jj} /  D_{M}_{jj}

**Comment by davydden** [comment]
> \epsilon_{h,j} = D_{A}{jj} / D{M}{jj} instead of \epsilon{h,j} = D_{A}{jj} / D{M}_{jj}

this looks the same. Perhaps some typos?

**Comment by davydden** [comment]
oh, i see --  `\epsilon_{h,j}`

**Comment by elasto** [comment]
yeah sorry 

\epsilon_{h,j} = D_{A}_{jj} /  D_{M}_{jj}  \epsilon_{h,j} = {A}_{jj} / {M}_{jj}

**Comment by davydden** [comment]
in which paragraph is that? I see two places but both look the same.

**Comment by elasto** [comment]
it is in the section "Eigenvalues and Dirichlet boundary conditions". The doc says: 

"These eigenvalues are spurious since they result from an eigenvalue system that operates only on boundary nodes – nodes that are not real degrees of freedom. Of course, since the two matrices DA,DM are diagonal, we can exactly quantify these spurious eigenvalues: they are εh,j=Ajj/Mjj (where the indices j corresponds exactly to the degrees of freedom that are constrained by Dirichlet boundary values)." 

I think that instead of \epsilon{h,j} = A_{jj} / M_{jj}, as mentioned in the section, it should be \epsilon_{h,j} = D_{A}{jj} / D_{M}{jj}

**Comment by davydden** [comment]
oh, i see. You are right! Will fix it. I think this part of the paragraph was written before block-structure picture above, thus the typo.

**Comment by bangerth** [comment]
@elasto -- alternatively, the typo is in the file `examples/step-36/doc/intro.dox`. Feel free to submit a patch for this if you're familiar with git!

**Comment by davydden** [comment]
see https://github.com/dealii/dealii/pull/2455
