### ISSUE TITLE
Make periodicity in Manifolds a Tensor<1,dim>

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2468]
#2411 now exports the data type of the periodicity vector, which we store and now return as a `Point<dim>`. But, fundamentally, the periodicity is a difference between two vectors, and consequently should be represented as a `Tensor<1,dim>` rather than as a `Point<dim>`.

@luca-heltai -- do you agree? If so, I can change this.

**Comment by luca-heltai** [comment]
Yes, I think this is perfectly reasonable. I can do this in the open PR #2411, since I'm already changing the Periodicity there...

**Comment by bangerth** [comment]
OK, then I'll gladly leave this to you for now.

**Comment by luca-heltai** [comment]
Closed by #2411.
