### ISSUE TITLE
mesh refinement after a few merge operations

### ISSUE THREAD

**Issue by pasquinadeus** [dealii/dealii#2475]
Hi guys,

I'm new to deal.ii and I'm trying to create a volume with a hole in it. since it needs to be off-centered, I decided to use a 2x2 grid of subdivided_hyper_rectangles and a single hyper_cube_with_cylindrical_hole as in the code below. 

Immediately after, I refine the grid in the x and y directions only, but as the following figure shows, "something is not right" (some cells divide in one axis, others in another):

![image](https://cloud.githubusercontent.com/assets/5459217/14359212/59aa92b0-fce8-11e5-9f2f-01ff45ac39e9.png)

If all the cells are subdivided_hyper_rectangles, it works OK. If I only use the hyper_cube_with_cylindrical_hole, it works OK. When I merge the 2 in a single triangulation, it fails.

Any thoughts?

[edit] Forgot to say originally that I'm using version 8.4.0 compiled from source [edit]

Here's a trimmed down version of the code with only the essential:

```
#define dim 3	
int main()
{
	Triangulation<dim>   triangulation;
	
	// defines rectangle size
	Point<dim> p1(-.5, -.5, -.05);
	Point<dim> p2(.5, .5, .05);
	
	//build a 2x2 grid different elements
	for (unsigned int i=0; i<2; ++i)
	{
		for (unsigned int j=0; j<2; ++j)
		{
			Triangulation<dim> tmp_tria, join_tria;
			
			if( (i==0) && (j==0) ) //only the first is different
			{
				GridGenerator::hyper_cube_with_cylindrical_hole<dim>(tmp_tria, 
																	.075,	// inner radius
																	.5,		// half edge length 
																	.1,		// height
																	1		// repetitions
																	);
				
				Tensor<1,dim> v;
				v[0]=0;
				v[1]=0;
				v[2]=-.05;
				GridTools::shift( v , tmp_tria);   //align hyper_cube_with_cylindrical_hole with the other hyper_rectangles
			}
			else
			{
				std::vector<unsigned int> repetitions;
				repetitions.push_back(2);
				repetitions.push_back(2);
				repetitions.push_back(1);
				GridGenerator::subdivided_hyper_rectangle<dim>(tmp_tria, repetitions, p1, p2);   //use the subdivided_hyper_rectangle to ensure same vertexes for merge operation below
			}
			
			//plug block in appropriate grid space
			Tensor<1,dim> v;
			v[0]=i;
			v[1]=j;
			v[2]=0;
			GridTools::shift( v , tmp_tria);
			
			//merge if something already exists, otherwise just copy it.
			if( triangulation.n_active_cells() > 0 )
			{
				join_tria.copy_triangulation(triangulation);
				GridGenerator::merge_triangulations(join_tria, tmp_tria, triangulation);
			}
			else
				triangulation.copy_triangulation(tmp_tria);
		}
	}
	//subdivide in x,y coordinates
	for(int i=0; i<1; ++i)
	{
		
		typename Triangulation<dim>::active_cell_iterator	cell = triangulation.begin_active(),
															endc = triangulation.end();
		for(; cell!=endc; ++cell)
		{
			cell->set_refine_flag(RefinementCase<dim>(0x1 | 0x2)); //refine in x,y coordinates only so cells become closer to  cubic
		}
		triangulation.execute_coarsening_and_refinement();
	}
	
	//output
	std::ofstream out ("grid-2.eps");
	GridOut grid_out;
	grid_out.write_eps(triangulation,out);
	out.close();
}
```

Thanks for any input!

Regards,
Ricardo

**Comment by bangerth** [comment]
So if I understand you right, the mesh *before* refinement looks correct?

I believe that the issue comes down to the question "What are the x- and y-directions?". These are defined *within the local coordinate system* of the cell, but of course this coordinate system can be oriented in arbitrary ways with regards to the *global* coordinate system. (Think, for example, what it would mean to refine in the *global* x-direction if you had a 2d cell that is just rotated by 45 degrees?) So in your case, the *local* x or y-direction appears to point in the *global* z-direction for some of the cells. You need to find out about this alignment before you decide how you want to refine.

**Comment by segonpin** [comment]
Hi.

As Wolfgang said, the point is that you have to find the local coordinate for each cell to be refined. In this case, if you do not want to refine in z-axis, this do the trick

```
         //find "local" axis with zero z component
          cut_dir.clear();
          for (unsigned int d = 0; d < dim; ++d)
          {
              Tensor<1,dim> dir(cell->face(2*d)->center() - cell->face(2*d+1)->center());
              if (std::abs(dir[dim-1]) < 1.e-6)
                  cut_dir.push_back(d);
          }
          //refine in local x,y coordinates only so cells become closer to  cubic
          cell->set_refine_flag(RefinementCase<dim>::cut_axis (cut_dir[0])|
              RefinementCase<dim>::cut_axis (cut_dir[1])); 
```

You should report this things first to the users group, where more people can help you, because it is not an error of the library, but in the way you use it or understand it. Here is the picture I got


![mesh](https://cloud.githubusercontent.com/assets/15182222/14376442/dab4b6b6-fd69-11e5-9c95-0f9a57269ee4.png)

and here is the code (you must provide a compilable code next time, what means include the "includes")

```
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/tria_boundary_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/numerics/data_out.h>
#include <deal.II/grid/grid_tools.h>

// And this again is C++:
#include <iostream>
#include <fstream>

#define dim 3


using namespace dealii;

int main()
{
    Triangulation<dim>   triangulation;

    // defines rectangle size
    Point<dim> p1(-.5, -.5, -.05);
    Point<dim> p2(.5, .5, .05);

    //build a 2x2 grid different elements
    for (unsigned int i=0; i<2; ++i)
    {
        for (unsigned int j=0; j<2; ++j)
        {
            Triangulation<dim> tmp_tria, join_tria;

            if( (i==0) && (j==0) ) //only the first is different
            {
                GridGenerator::hyper_cube_with_cylindrical_hole<dim>(tmp_tria, 
                                                                    .075,   // inner radius
                                                                    .5,     // half edge length 
                                                                    .1,     // height
                                                                    1       // repetitions
                                                                    );

                Tensor<1,dim> v;
                v[0]=0;
                v[1]=0;
                v[2]=-.05;
                GridTools::shift( v , tmp_tria);   //align hyper_cube_with_cylindrical_hole with the other hyper_rectangles
            }
            else
            {
                std::vector<unsigned int> repetitions;
                repetitions.push_back(2);
                repetitions.push_back(2);
                repetitions.push_back(1);
                GridGenerator::subdivided_hyper_rectangle<dim>(tmp_tria, repetitions, p1, p2);   //use the subdivided_hyper_rectangle to ensure same vertexes for merge operation below
            }

            //plug block in appropriate grid space
            Tensor<1,dim> v;
            v[0]=i;
            v[1]=j;
            v[2]=0;
            GridTools::shift( v , tmp_tria);

            //merge if something already exists, otherwise just copy it.
            if( triangulation.n_active_cells() > 0 )
            {
                join_tria.copy_triangulation(triangulation);
                GridGenerator::merge_triangulations(join_tria, tmp_tria, triangulation);
            }
            else
                triangulation.copy_triangulation(tmp_tria);
        }
    }
    //subdivide in x,y coordinates
    std::vector<unsigned int> cut_dir;
    for(int i=0; i<1; ++i)
    {
        typename Triangulation<dim>::active_cell_iterator   cell = triangulation.begin_active(),
                                                            endc = triangulation.end();
        for(; cell!=endc; ++cell)
        {
          //find "local" axis with zero z component
          cut_dir.clear();
          for (unsigned int d = 0; d < dim; ++d)
          {
              Tensor<1,dim> dir(cell->face(2*d)->center() - cell->face(2*d+1)->center());
              if (std::abs(dir[dim-1]) < 1.e-6)
                  cut_dir.push_back(d);
          }
          //refine in local x,y coordinates only so cells become closer to  cubic
          cell->set_refine_flag(RefinementCase<dim>::cut_axis (cut_dir[0])|
              RefinementCase<dim>::cut_axis (cut_dir[1])); 
        }
        triangulation.execute_coarsening_and_refinement();
    }

    //output
    std::ofstream out ("grid-2.eps");
    GridOut grid_out;
    grid_out.write_eps(triangulation,out);
    out.close();
}
```

**Comment by pasquinadeus** [comment]
Thank you Wolfgang,
Thank you Sebastian,

Apologies for not considering this a user problem from the start, but if I'm honest I still think the library shares some of the "blame" (poor word, but nothing better comes up). Let me try to make a point, but again I'm still inexperienced in deal.ii so don't take me too seriously.

1. None of the operations I perform on the cells give any hint that they might mess up the local coordinate system in the cell. These are "shift", "merge_triangulations", "copy_triangulations", "execute_coarsening_and_refinement", "set_refine_flag" and the 2 grid generators.

2. If instead of using hyper_cube_with_cylindrical_hole for one of the "places" in the 2x2 grid I use subdivided_hyper_rectangle, everything works as originally expected (i.e. no cell local coordinates are changed). This evidences some "hidden" behavior, dependent on the actual triangulation. 

After reading Wolfgang's explanation I immediately thought the "problem" to be in the merge_triangulations() function - only one which makes sense. I had read the documentation for this function thoroughly (e.g. I discovered I had to take care of boundaries afterwards), but nothing hinting at the change in local coordinate system of cells. 

Looking at the code for this functino (grid/grid_generator.cc) it is also not immediate that this happens. The only hint is this:

    // reorder the cells to ensure that they satisfy the convention for
    // edge and face directions
    GridReordering<dim, spacedim>::reorder_cells(cells, true);
    result.clear (); 
    result.create_triangulation (vertices, cells, subcell_data);

So I am left assuming that cell orientation is attached to edge and face directions, and the merge operation is allowed to change these. 

I suggest an additional note in the merge_triangulation() documentation and perhaps a hint towards the solution Sebastian kindly provided. Something like:

    /** @note Cell orientations are allowed to change during a merge_triangulation operation. 
      * If directional  refinement is required after merging the coarse meshes, additional provisions need to be considered by hand. 
      * To refine all the cells in the triangulation in the global x and y directions the following example code can be used:
    
    std::vector<unsigned int> cut_dir;
    for(int i=0; i<1; ++i)
    {
        typename Triangulation<dim>::active_cell_iterator   cell = triangulation.begin_active(),
                                                            endc = triangulation.end();
        for(; cell!=endc; ++cell)
        {
          //find "local" axis with zero z component
          cut_dir.clear();
          for (unsigned int d = 0; d < dim; ++d)
          {
              Tensor<1,dim> dir(cell->face(2*d)->center() - cell->face(2*d+1)->center());
              if (std::abs(dir[dim-1]) < 1.e-6)
                  cut_dir.push_back(d);
          }
          //refine in local x,y coordinates only
          cell->set_refine_flag(RefinementCase<dim>::cut_axis (cut_dir[0])|
              RefinementCase<dim>::cut_axis (cut_dir[1])); 
        }
        triangulation.execute_coarsening_and_refinement();
    }
    **/

Thank you both for the help and thank you for the great library. I'm finding this project both reliable in terms of code and of great value in FE understanding.

Best regards,
Ricardo

**Comment by pasquinadeus** [comment]
OK, I now understand what you meant. This github issues list is for internal development and I should really be using the mailing lists described here:

https://www.dealii.org/mail.html

Will take care in the future.

Best,
Ricardo

**Comment by segonpin** [comment]
Yes, that is what I meant. 

I am sorry if I sound like rude, I just wanted to point you the the right forum. I am quite new here and I am trying to be kind and social :) , but I am nobody, so do not take too seriously what I said.

Best,
Sebas.

**Comment by bangerth** [comment]
@pasquinadeus -- you have a point that this may not be as well documented as could be. I've opened #2482 for this. At the same time, it's not the `merge_triangulation` function that gets you into trouble here, but one of the ones that create the individual parts. There really is nothing that can be done about it -- no convention for the orientation of cells would be consistent and make sense in all cases, and expecting the cells of a triangulation to be oriented in any particular way is just not going to work. You have to live with the fact that cells will, in general, be oriented in arbitrary ways. But, as I said, this ought to be documented better.

@segonpin -- great modification of the little test program. Many thanks for your help, much appreciated!
