### ISSUE TITLE
dealii homepage certificate outdated

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#2487]
Not related to deal.II code, but it seems the website is not reachable by Firefox users at the moment.
I get the following error message:

The owner of dealii.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

A click on 'Advanced' brings the following additional information:

dealii.org uses an invalid security certificate. The certificate expired on 04/08/2016 07:54 AM. The current time is 04/08/2016 03:59 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE 

It seems a certificate expired.

**Comment by tjhei** [comment]
Yes, same on chrome. :-(

Also see https://groups.google.com/d/topic/dealii-developers/g-qNmcDr2zk/discussion

**Comment by gassmoeller** [comment]
Ah, I did not see that. Ok then, I just wanted to let people know. I will close this issue once it is available again.

**Comment by tjhei** [comment]
@guidokanschat Fixed it a few minutes ago. Please report back if there are issues left.

**Comment by tamiko** [comment]
Perfect! I can confirm that the webpage is now reachable again even with an old HSTS entry in the browser.

**Comment by gassmoeller** [comment]
Same for me. Thanks.
