### ISSUE TITLE
LinearOperator * Trilinos::Vector does not work

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2504]
subj.
```
#include "../tests.h"

#include <deal.II/lac/linear_operator.h>
#include <deal.II/lac/trilinos_block_sparse_matrix.h>
#include <deal.II/lac/trilinos_sparse_matrix.h>
#include <deal.II/lac/trilinos_vector.h>

using namespace dealii;

int main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization (argc, argv, 1);

  initlog();
  deallog << std::setprecision(10);

  typedef TrilinosWrappers::MPI::Vector vector_t;
  typedef TrilinosWrappers::SparseMatrix matrix_t;

  matrix_t a;

  auto op_a  = linear_operator<vector_t>(a);
  vector_t u,res;
  res = op_a * u;
  // ^^ this was not working, whereas
  // op_a.vmult(res,u) did.

  deallog << "OK" << std::endl;

  return 0;
}
```
fails to compile with
```
287: /Users/davydden/libs-sources/deal.ii/davydden/tests/lac/linear_operator_04a.cc:42:14: error: invalid operands to binary expression ('dealii::LinearOperator<dealii::TrilinosWrappers::MPI::Vector, dealii::TrilinosWrappers::MPI::Vector>' and 'vector_t' (aka 'dealii::TrilinosWrappers::MPI::Vector'))
287:   res = op_a * u;
287:         ~~~~ ^ ~
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/lac/linear_operator.h:488:1: note: candidate function [with Range = dealii::TrilinosWrappers::MPI::Vector, Domain = dealii::TrilinosWrappers::MPI::Vector] not viable: no known conversion from 'vector_t' (aka 'dealii::TrilinosWrappers::MPI::Vector') to 'typename Vector::value_type' (aka 'double') for 2nd argument
287: operator*(const LinearOperator<Range, Domain> &op,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/complex_overloads.h:39:1: note: candidate template ignored: could not match 'complex' against 'LinearOperator'
287: operator*(const std::complex<T> &left, const std::complex<U> &right)
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/complex_overloads.h:57:1: note: candidate template ignored: could not match 'complex' against 'LinearOperator'
287: operator*(const std::complex<T> &left, const U &right)
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/complex_overloads.h:75:1: note: candidate template ignored: could not match 'complex<type-parameter-0-1>' against 'dealii::TrilinosWrappers::MPI::Vector'
287: operator*(const T &left, const std::complex<U> &right)
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/lac/linear_operator.h:418:1: note: candidate template ignored: could not match 'LinearOperator<type-parameter-0-0, type-parameter-0-1>' against 'dealii::TrilinosWrappers::MPI::Vector'
287: operator*(typename Range::value_type  number,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/lac/linear_operator.h:517:1: note: candidate template ignored: could not match 'LinearOperator<type-parameter-0-1, type-parameter-0-2>' against 'dealii::TrilinosWrappers::MPI::Vector'
287: operator*(const LinearOperator<Range, Intermediate> &first_op,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1232:1: note: candidate template ignored: could not match 'Tensor<0, dim, type-parameter-0-1>' against 'dealii::TrilinosWrappers::MPI::Vector'
287: operator * (const Other                 object,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1250:1: note: candidate template ignored: could not match 'Tensor' against 'LinearOperator'
287: operator * (const Tensor<0,dim,Number> &t,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1269:1: note: candidate template ignored: could not match 'Tensor' against 'LinearOperator'
287: operator * (const Tensor<0, dim, Number>      &src1,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1335:1: note: candidate template ignored: could not match 'Tensor' against 'LinearOperator'
287: operator * (const Tensor<rank,dim,Number> &t,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1361:1: note: candidate template ignored: could not match 'Tensor<rank, dim, type-parameter-0-3>' against 'dealii::TrilinosWrappers::MPI::Vector'
287: operator * (const Number                        factor,
287: ^
287: /Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor.h:1468:1: note: candidate template ignored: could not match 'Tensor' against 'LinearOperator'
287: operator * (const Tensor<rank_1, dim, Number> &src1,
287: ^
287: 1 error generated.
```

I will try to dig into LO class these days, but if @tamiko has some immediate ideas, i will be happy to know them :smile:

**Comment by luca-heltai** [comment]
This works. Just add the include:
~~~
#include <lac/packaged_operation.h>
~~~

**Comment by jppelteret** [comment]
Solution:
```C++
#include <deal.II/lac/packaged_operation.h>
```

May I ask, what is the rationale behind keeping these two headers completely separated when the two are so inextricably linked? I find it quite unintuitive and the compiler errors certainly don't give the user any guidance as to what might be the issue in these situations.

**Comment by luca-heltai** [comment]
The original reason was that @bangerth was opposed to the way packaged operators perform some automatic conversions for you, that give even more intricate error messages if you don't know what's appening behind the scenes...

~~~
auto v = A*b;
~~~
is **not** the same as 
~~~
VectorType v = A*b;
~~~
and this is confusing to new users. Keeping `packaged_operation` separat seemed like a good option at the time, but I think it is not such a good idea... 

I vote for putting all of them in a single include file:

~~~
dealii/lac/linear_operator_tools.h
~~~

**Comment by davydden** [comment]
i fully agree with @luca-heltai , it's very confusing the way it is now. I will create a PR and we can discuss it further there...

**Comment by jppelteret** [comment]
@luca-heltai Thanks for the explanation. I suppose I haven't been exposed to the errors that you mention, so I cannot appreciate that set of difficulties that one may encounter. Either way, I still think that it would be nice to have the option of bundling them all `LinearOperator` functionality under one umbrella header or, should one choose, cherry-picking the relevant headers as needed.

**Comment by bangerth** [comment]
I'll defer to your collective wisdom on the matter if you want to change the behavior in this area.

**Comment by davydden** [comment]
@bangerth the PR above does not change the behaviour, it provides an alternative which should be less confusing for new users.

**Comment by tamiko** [comment]
> May I ask, what is the rationale behind keeping these two headers completely separated 

```packaged_operation.h``` aggressively defines ```operator+``` (and others) for everything that remotely looks like a vector:
```
526 template <typename Range,                                                        
527           typename = typename std::enable_if<has_vector_interface<Range>::type::value>::type>
528 PackagedOperation<Range> operator+(const Range &u, const Range &v) 
```

This might not always be what you want. Further, it is simply cleaner to keep these header files separate.

**Comment by jppelteret** [comment]
@tamiko Thanks as well for the clarification on top of that from @luca-heltai . 

Unless I'm missing something, I think that the documentation doesn't really do anything to explain this (at least not at a sufficiently low level). May I suggest that we put together a few lines of additional documentation and perhaps a couple of very small and *complete* examples/use cases for the glossary entry of `LinearOperator` that clearly define when to include `linear_operator.h` alone and when its necessary to include both it and `packaged_operation.h`. I suspect that this would go a long way to clarify the usage and interplay of the classes. To me, its certainly not intuitive (imagine including `tensor.h` and not being able to immediately use a `Tensor`!). With this knowledge the user could better discern whether they can use the collective header (if that PR is merged) or whether they need to only include the one header.
