### ISSUE TITLE
PETSc Viewer Classes

### ISSUE THREAD

**Issue by PascalKraft** [dealii/dealii#2510]
PETSc has included Viewer classes for matrix types (showing the sparsity pattern in an X-window or Vector values as a line graph) which might be handy for users in diagnostic settings and which are not too difficult to set up. Maybe they could be made available in the PETSC::MPI::MatrixBase class. I currently use them. However I don't know how to check if all appropriate packages are included in deal and petsc installation to give sufficient error messages.

**Comment by PascalKraft** [comment]
I wanted to make this an enhancement proposal ... how do I do that?

**Comment by bangerth** [comment]
This is already possible. You can extract the underlying PETSc object from both the PETSc and Trilinos vector types, and then call the corresponding PETSc functions for visualization. I think that is the better approach, rather than adding one very specific piece of PETSc functionality to the existing classes.

@PascalKraft -- why would this not work for you?

**Comment by PascalKraft** [comment]
It is working fine for me and I was happy to have this functionality at my disposal. I thought people might be unaware and having a function PlotStructure in PETScWrappers::MPI::SparseMatrix might make them  aware. The inferior documentation as well as different style of PETSc compared to dealii made it more complicated to figure out the right way then I thought it has to be since effectively it's only 10 lines of code. However this is purely cosmetic in nature.

**Comment by bangerth** [comment]
There is a balance to strike between trying to wrap everything PETSc offers in our own classes, and only wrapping what is actually needed to implement a generic interface that looks the same for all matrix (or vector) classes. The former provides more things to our users using the interface they are familiar with, but there is of course the maintenance cost of having to deal with more functions, more documentation, and PETSc interfaces that constantly change.

My general assumption is that smaller interfaces are generally better, but I'm a pragmatist in that I see the value of convenience. Thus, I would not be opposed to a patch that implemented this particular call into PETSc. 

@PascalKraft -- want to give this a try? It's the first time in ~13 years of PETSc interfaces that someone requested this, so chances are that if *you* don't implement it, nobody will :-)

**Comment by drwells** [comment]
We can always view the PETSc objects from PETSc's own viewer code - lets leave that as the preferred solution.

**Comment by bangerth** [comment]
I agree. There is also `MatrixOut` to help.
