### ISSUE TITLE
Transforming between matrix types

### ISSUE THREAD

**Issue by PascalKraft** [dealii/dealii#2511]
For testing purposes a function transforming matrices from one library type to another would be nice. The same goes for vectors. This would give developers the option to try out solvers from other libraries without rewriting large parts of their code. This would not need to be efficient or even parallel but I guess sometimes it would be nice to just be able to quickly use solvers and preconditioners from Trilinos or PETSc (or SLEPc for that matter) without having to check every single line of code for changes.They could be made available as a part of the Utilities namespace. This could also be used to evaluate if an implementation with different datatypes will help or not or for internal usage for very small matrices.

**Comment by bangerth** [comment]
@PascalKraft -- that's a legitimate idea. Want to help in implementing it? I think it might be simplest to actually implement this in the PETSc and Trilinos matrix classes.

**Comment by PascalKraft** [comment]
I am currently working on a related problem in my code. If I am able to figure that out I will look into it. This would also make Solver comparison available as a test. 
Generate an invertible matrix and vector, transform them to deal/petsc/trilinos. Use same solvers (GMRES/CG whatever is available on multiple platforms) and compare convergence and result.

**Comment by drwells** [comment]
Our own linear algebra classes are generic enough that it's not that hard to switch between them (e.g., see step-40). I believe that should be the preferred solution instead of doing copies.
