### ISSUE TITLE
fix PETSc ReinitHelper for LinearOperator and MPI vectors

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2522]
just so that we don't forget, there are still some left-over issues (pointed out by @luca-heltai ) from PR https://github.com/dealii/dealii/pull/2502 which is authored by  @ESeNonFossiIo .

**Comment by bangerth** [comment]
Are you saying that you merged prematurely? ;-)

**Comment by davydden** [comment]
yes, i was too quick to merge 😄

**Comment by ESeNonFossiIo** [comment]
I got a PR...I need to check linear_operator tests and then I will push.

**Comment by davydden** [comment]
@ESeNonFossiIo : thanks a lot! :+1:

**Comment by ESeNonFossiIo** [comment]
It was my fault.. I confused some PETSc functions. :)
