### ISSUE TITLE
Definition of curl in "LocalIntegrators::Maxwell Namespace" has wrong sign

### ISSUE THREAD

**Issue by orlando-tian** [dealii/dealii#2525]
See the documentation [here](https://www.dealii.org/developer/doxygen/deal.II/namespaceLocalIntegrators_1_1Maxwell.html#details), the definition of curl in 3 dimension has wrong sign and should be negated. Code related to curl calculation in this module should be modified. For example, at line 249 of maxwell.h
`const double cu = fe.shape_grad_component(j,k,d1)[d2] - fe.shape_grad_component(j,k,d2)[d1];`
should be changed as:
`const double cu = fe.shape_grad_component(j,k,d2)[d1] - fe.shape_grad_component(j,k,d1)[d2];`

**Comment by bangerth** [comment]
@guidokanschat ?

@orlando-tian -- would you want to write a patch that fixes this in all places you can find?

**Comment by orlando-tian** [comment]
@bangerth Sure, with my pleasure!

**Comment by drwells** [comment]
It looks like #2540 fixed this issue but this was not closed at the time.
