### ISSUE TITLE
Annoying warning with gcc 4.6

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2527]
We have recently (see the patches listed under #898) acquired a bunch of move constructors and operators that look like this:
```
#ifdef DEAL_II_WITH_CXX11
  /**
   * Move constructor. Creates a new vector by stealing the internal data of
   * the vector @p v.
   *
   * @note This constructor is only available if deal.II is configured with
   * C++11 support.
   */
  BlockVector (BlockVector<Number> &&v) = default;
#endif
```
Unfortunately, with gcc 4.6.3, I get the following, really annoying warning:
```
/.../dealii/include/deal.II/lac/block_vector.h:115:3: warning: unused parameter ‘v’ [-Wunused-parameter]
```

I get a couple of pages of these. What to do with this? I am reluctant to just comment out the name, because we use the name in the documentation. On the other hand, the warnings completely obscure everything else. Suggestions?

**Comment by tjhei** [comment]
remove ``v`` and change the doc to say ``of the given vector``.

**Comment by kronbichler** [comment]
I agree with @tjhei
