### ISSUE TITLE
Cmake suggestions to improve usage in user projects

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2541]
There were a couple of improvement suggestions related to Cmake in this PR on Spack https://github.com/LLNL/spack/pull/816 

My interpretation of those suggestions is that with newer CMake (probably since 3.0.2) we can use more native Cmake functionality (including `target_compile_definitions` and `target_include_directories`) to avoid defining extra CMake commands, simplify the CMake code (including `deal.IIConfig.cmake`) and allow user to `target_link_libraries(tgt deal.ii)` instead of `deal_ii_setup_target(tgt)`.

There is an opinion that it much easier ask users to set `CMAKE_PREFIX_PATH` (needed to pickup deal.ii in find_package(deal.II), as far as i understand) because you can use one variable for everything, and users won't misspell or mis-capitalize package names in env vars.

**Comment by bangerth** [comment]
Do we want to require anything newer than the current cmake 2.8.9?

**Comment by Rombur** [comment]
Just for information, from the Trilinos mailing list "I would like to propose that we upgrade the minimum required version of CMake needed for Trilinos from 2.8.11 to 3.3.2.  The reason is that we have a minor patched version of CMake 3.3.2 [1] that runs 3x to 4x faster than CMake 2.8.11.  This will allow us to speed up our automated testing for Trilinos and make developers more productive." Here is the patch https://github.com/TriBITSDevTools/cmake-3.3.2-base/blob/master/remove_getrealpath.patch.

**Comment by tamiko** [comment]
@Rombur Well, given the fact that Trilinos has written its own meta-build system TPL on top of cmake it is no surprise that they want it to configure quite fast.

**Comment by tamiko** [comment]
@bangerth We can in principle support what was suggested without requiring a newer version of cmake.

@davydden I had a look at the interface properties of targets again. CMake has come a long way till 2.8.8:
 - It still doesn't support an ```INTERFACE_LINK_FLAGS``` property. This is a big show stopper.
 - Apart from that, to use ```TARGET_LINK_LIBRARIES(target ${DEAL_II_TARGET})``` to also populate include directories and compile definitions does not work for object libraries.

So, how exactly do you intend to obsolete ```DEAL_II_SETUP_TARGET```?

**Comment by tamiko** [comment]
I suggest we give the interface targets a try, see #2543.

**Comment by tamiko** [comment]
> There is an opinion that it much easier ask users to set CMAKE_PREFIX_PATH (needed to pickup deal.ii in find_package(deal.II), as far as i understand) because you can use one variable for everything, and users won't misspell or mis-capitalize package names in env vars.

I'm not a huge fan of our current handling of ```DEAL_II_DIR``` in the CMake scripts in our example steps (lines 26 to 35). But it solved a pragmatic problem: We introduced it (together with the ancient ```DEAL_II_DIR```) to generate the following error message:
```
CMake Error at CMakeLists.txt:30 (MESSAGE):
  

  *** Could not locate a (sufficiently recent) version of deal.II.  ***

  

  You may want to either pass a flag -DDEAL_II_DIR=/path/to/deal.II to cmake

  or set an environment variable "DEAL_II_DIR" that contains this path.
```
CMake's own error message is the following:
```
CMake Error at CMakeLists.txt:26 (FIND_PACKAGE):
  Could not find a package configuration file provided by "deal.II"
  (requested version 8.5.0) with any of the following names:

    deal.IIConfig.cmake
    deal.ii-config.cmake

  Add the installation prefix of "deal.III" to CMAKE_PREFIX_PATH or set
  "deal.II_DIR" to a directory containing one of the above files.  If
  "deal.II" provides a separate development package or SDK, be sure it has
  been installed.
```

If there is a majority for removing ```DEAL_II_DIR``` from the user cmake files and solely advocate ```CMAKE_PREFIX_PATH``` as a hint, I have no problem with that. But I doubt that the tradeoff between these two error messages is really worth the "simpler" usage of ```CMAKE_PREFIX_PATH``` instead of ```DEAL_II_DIR```.

**Comment by davydden** [comment]
@tamiko :

> does not work for object libraries.

are you saying that with your PR it would still not be possible to do `TARGET_LINK_LIBRARIES(target ${DEAL_II_TARGET})` for a library target in user projects?

> So, how exactly do you intend to obsolete DEAL_II_SETUP_TARGET?

I don't. Not until we can do exactly the same with the native CMake of what we are doing now with dealii's macros.


If/when Trilinos will require `3.3.2` one would have to use it anyway to build the suite. So i think in general it makes sense to use as much as possible of what CMake `3.3.2` (?) provides.

**Comment by tamiko** [comment]
@davydden 
> are you saying that with your PR it would still not be possible to do TARGET_LINK_LIBRARIES(target ${DEAL_II_TARGET}) for a library target in user projects?

No, I'm saying it is not possible to use this for an object library target (for a shared or static library it is fine). Therefore, it cannot be a full replacement for ```DEAL_II_SETUP_TARGET``` to add include paths and compiler flags and definitions.

**Comment by tamiko** [comment]
> [...] it makes sense to use as much as possible of what CMake 3.3.2 (?) provides.

Version 3.3.2 ist only 7 months old. Further, there is not much more functionality in 3.3.2 or later that would make it worthwhile. Version 3.0.2 is not even 2 years old. I don't see a point in requiring newer versions. For comparison, debian wheezy has 2.8.9, debian jessie 3.0.2, the old ubuntu lts has 2.8.12, ubuntu-15.04 3.0.2., etc.

That said, we can support the newer (and improved) interface targets and properties for our project configuration easiliy (see #2543).


It is a very different story whether it is worthwhile to rewrite our internal feature configuration such that we use interface targets internally. (At the moment we populate and maintain a number of variables for every feature: FEATURE_LIBRARIES, FEATURE_COMPILER_FLAGS, FEATURE_INCLUDE_DIRS, etc.)
These could in principle be replaced by interface targets. But what is it good for? My estimate:
 - this is roughly work for at least a week (fulltime)
 - needs the same amount of code in our ```FindXXX.cmake``` modules
 - we can get rid of roughly 50 lines of low level variable handling and a bit of "global variable" black magic
 - and will introduce more than 50 lines again in ```setup_write_config.cmake``` to still support ```detailed.log```

**Comment by davydden** [comment]
Given your estimate it certainly does not look worthwhile to rewrite anything now.
