### ISSUE TITLE
Quadrature point data manager (extension)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2555]
after https://github.com/dealii/dealii/pull/2552 is merged, here is the TODO list for future extensions:
- [ ] coarsening for parallel::distributed::ContinuousQuadratureDataTransfer, see https://github.com/dealii/dealii/pull/2552#discussion_r62321924
- [ ] shared triangulation and hp::DoFHandler
- [ ] coarsening
- [ ] serialisation for the QPManager
- [ ] memory consumption
- [ ] custom initializer  in the spirit of (i) `initialise(cell)` + (ii) `push_back<variadic templates>(const QData&)`
- [ ] selective projection of quadrature data (think of plasticity where only some points are not elastic). A way out is in addition to L2 projection do the following. Find the closest quadrature point in the parent's cell to the quadrature point in the child cell and assume its value (or more complex things like averaging). Make the two combinable using masking / enumerators.

**Comment by drwells** [comment]
These are all reasonable future extensions, but interest in these seems low so lets close.
