### ISSUE TITLE
Improve doxygen formatting of exceptions

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2571]
#2570 improves the display of exceptions in the doxygen module, but the formatting is not particularly good. This could be improved with some PERL magic, as explained there.

**Comment by tjhei** [comment]
some half-backed solution:
```
#define DeclException1(Exception1, type1, outsequence)                    \
  /** @note The error text is: <div class="fragment"> outsequence </div> */ \
  static ExceptionBase& Exception1 (type1 arg1)
```
in ``filter``:
```
s#<<#<BR><<#g;
```
but this needs to be guarded to only replace within lines like above and I couldn't make that work.

Another option might be to remove ``<<`` and ``"``, dunno.

**Comment by bangerth** [comment]
I'm going to send a patch that makes this a bit simpler next, but here's already part of the answer: It seems like the `filter` script runs *before*, not *after* doxygen does the expansion of C/C++ macros. This means that we can't process `outsequence` in any way, or at least can't do that in the `filter` script.

**Comment by bangerth** [comment]
For the record, here's the code I had in the new "Section 2" part of the filter script following #2659:
```

    # We already expend DeclException declarations into text that
    # contains the error text in a comment of the form
    #   @note The error text is: @code outsequence @endcode
    # (see include/deal.II/base/exceptions.h). Here, 'outsequence'
    # may or may not span multiple lines.
    #
    # This has to be further processed to make the 'outsequence'
    # easier to read. Do so here.
    if (m/The error text is: \@code ([^\@]*)( \@endcode .*)?/)
    {
        open (my $fh, ">>", "abcdef");

        print $fh "The error text is: \@code\n";
        my $outsequence = "$1";


        # while we haven't found the end of the sequence yet:
        while (! ($2 eq ""))
        {
            print $fh "continuation\n";

            # read next line
            <>;

            # split
            m/([^\@]*)( \@endcode .*)?/;
            $outsequence .= "\n $1";
        }

        # print the 'outsequence', plus the end token
        print $fh "$outsequence $2\n\@endcode\n";

        # clear the current line so it doesn't get printed
        # or processed twice
        $_ = "";
    }
```
This should output every processed exception, but all it does is output this:
```
The error text is: @code
defaulttext  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
defaulttext  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
The error text is: @code
outsequence  
@endcode
```
These are exactly the (unexpanded) macro argument names in `exceptions.h` where we *declare* the macros, but not where these macros are *used*.

**Comment by bangerth** [comment]
#2660 adds an alternative approach to this. It still doesn't allow us to do any processing, but at least it centralizes the place where one would need to do so to `options.dox.in`. In principle, this could allow us to expand the text `The error text is: outsequence` into something where `outsequence` is given as the argument to a previously defined javascript function that simply removes all of the `<<` characters and does, as appropriate, other processing. I don't recall how easy or difficult it would be to add a javascript function. I know that doxygen output pages do support running javascript.

**Comment by tjhei** [comment]
> I'm going to send a patch that makes this a bit simpler next, but here's already part of the answer: It seems like the filter script runs before, not after doxygen does the expansion of C/C++ macros. This means that we can't process outsequence in any way, or at least can't do that in the filter script.

I am confused. I thought it worked in my comment above, but maybe I just ended up replacing every single occurrence of "<<" in the code? :-)

Before we spend much more brain power on hacking around doxygen, I have some other suggestions:
1. Just copy and paste the exception error message into the documentation string manually. That way we can also remove quotes, ``<<``, string conversion calls, ...
2. Write a preprocessor that generates a header with additional documentation to parse for doxygen.

**Comment by bangerth** [comment]
> 1. Just copy and paste the exception error message into the documentation string manually. That way we can also remove quotes, <<, string conversion calls, ...

I'm not a fan of this. If you look at #610, you'll realize how incredibly many exception classes we have. No way we can convert a significant fraction of exceptions by hand.

> 2. Write a preprocessor that generates a header with additional documentation to parse for doxygen.

This has more promise, but I'm not sure how to do that. I suspect that it will be about as complicated as coming up with a short javascript snippet.
