### ISSUE TITLE
spherical coordinates

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2588]
I have self written functions to go from `Point<dim>` to spherical coordinates and back. `Aspect` also have `spherical_coordinates(const Point<dim> &position);` and `cartesian_coordinates(const std_cxx11::array<double,dim> &scoord);`. I suspect that other people may be self-writing those simple things as well. I think we should have them in `deal.ii` to simplify everyone's life.

If @tjhei @bangerth don't mind, i would take `Aspect`'s implementation and quickly create a PR. The question is if it should live in `dealii::Utilities` or somewhere else?

**Comment by bangerth** [comment]
Yes, I think `dealii::Utilities` is the right place.

**Comment by davydden** [comment]
there is circular include:
`base/utilities` would need `base/point` -> `base/tensor` -> `base/utilities`.
I think that must be resolvable, but I forgot how :smile:

**Comment by jppelteret** [comment]
@davydden Maybe this is a good time to add some of the other utility functions that I have lying around? Some also have to do with spherical / cylindrical coordinates, projections etc. I'll chat with you about it tomorrow.

**Comment by drwells** [comment]
This might not be the right time to do it, but the circular include hints at something that has been bothering me for awhile: we should consider splitting up `/base/utilities.h` into separate files.

Would you consider putting such functions in `/base/geometric_utilities.h` or something of that sort instead?

**Comment by davydden** [comment]
@drwells: `/base/geometric_utilities.h` sounds good to me! If @bangerth does not mind, i would put these functions there.

**Comment by bangerth** [comment]
That works for me.
