### ISSUE TITLE
c++11-dependent updates to the step-44 tutorial

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#2592]
Since @davydden and I have recently implemented the `CellDataStorage` class, I've been thinking about whether this should be integrated into a tutorial. One candidate for this is step-44, which along with step-18 are the only two tutorials that use a `PointHistory` class. I was hoping to get some opinions on this before following through with it:

**Advantages**
- Leaving step-18 as-is and integrating `CellDataStorage` into step-44 would give a contrast between manually handling the QPH data and using the built-in storage class.
- Step-44 solves a 3x3 block system using static condensation. As `c++11` would be enabled, one can then use the opportunity to offer an alternative method of solving the block system using the `LinearOperator` classes. I think that this would be a good advertisement for how they work, since I don't believe they're used in other tutorials yet. 
- For both of these points the alterations are minor, so it would be only a light adjustment to the current code.

**Disadvantages**
- Since `CellDataStorage` requires `deal.II` to be built with `c++11` enabled, doing so would effectively hide the tutorial from a minority of non-`c++11` users.

**Other points of consideration**
- The original version of the tutorial would of course still be accessible from the documentation for previous versions of `deal.II`.
- This could be left for a release that expects a `c++11`-compliant compiler.

**Comment by davydden** [comment]
:+1: for adding `LO` and `CellDataStorage` to step-44. I wouldn't hold until deal.ii requires `c++11`.

**Comment by luca-heltai** [comment]
We can still issue an error at cmake time if c++11 is not supported. We do this with other tutorials as well, for example when they need trilinos/petsc/opencascade.

**Comment by jppelteret** [comment]
Ah, ok. So the tutorial would be visible but cannot be compiled. That makes sense!

**Comment by bangerth** [comment]
Not allowing compilation without C++11 seems like a reasonable approach. 

I like the idea of leaving step-18 as is, to show how it can be done, but then to have a link to `CellDataStorage` and/or step-44 to make sure users know that they don't have to do it by hand.
