### ISSUE TITLE
gcc 6.1 and boost serialization

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2593]
The linking of serialization tests fail for me with gcc 6.1:
```
$ ctest -R serialize_dof_handler.debug
CMakeFiles/serialize_dof_handler.debug.dir/serialize_dof_handler.cc.o: In function `void boost::archive::save_access::save_primitive<boost::archive::text_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::text_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/ssd/deal-build/libs-gcc6/boost_1_60_0/include/boost/archive/detail/oserializer.hpp:88: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
...
```
even though libboost_serialization.so is present on the linker line.

This is the relevant part from detailed.log
```
$ grep BOOST detailed.log                                              #        DEAL_II_WITH_BOOST set up with external dependencies
#            BOOST_VERSION = 1.60.0
#            BOOST_CXX_FLAGS = -Wno-unused-local-typedefs
#            BOOST_INCLUDE_DIRS = /ssd/deal-build/libs-gcc6/boost_1_60_0/include
#            BOOST_USER_INCLUDE_DIRS = /ssd/deal-build/libs-gcc6/boost_1_60_0/include
#            BOOST_LIBRARIES = /ssd/deal-build/libs-gcc6/boost_1_60_0/lib/libboost_iostreams.so;/ssd/deal-build/libs-gcc6/boost_1_60_0/lib/libboost_serialization.so;/ssd/deal-build/libs-gcc6/boost_1_60_0/lib/libboost_system.so;/ssd/deal-build/libs-gcc6/boost_1_60_0/lib/libboost_thread.so
```

Any idea what is going on here?

**Comment by tjhei** [comment]
Arg, this is because boost is built with gcc4. Sigh.

**Comment by drwells** [comment]
Yes, in such cases (due to the GCC ABI change for `std::string` from 4 to 5) one cannot use libraries compiled in C++11 mode with gcc 4.* with libraries compiled in C++11 mode with gcc 5.* or 6.1. Put another way, gcc 4.* is not C++11 compliant in any case due to the ABI problem.

When Arch Linux upgraded to GCC 5 a year ago they rebuilt every single package for this reason.

I am surprised that you only reported failure for this case. I think every single test case should fail with this sort of combination. I regularly forget about this problem when testing things with my copy of g++-4.7 and always have to rebuild deal with the bundled copy of boost.

I am not a packaging expert, but to the best of my knowledge this problem is not possible to solve on our end. I really did fix all of the new GCC6 warnings, so try not to worry too much :)

**Comment by drwells** [comment]
@tjhei I do not think we should officially support compilers that are not supplied by the OS vendor: while one can use them successfully (and I do this sometimes for testing purposes on my desktop) it is rather brittle and one must remember to recompile all bundled C++ (not necessarily C) libraries. I frequently forget about that last step. I don't think we should bother supporting these sorts of ABI issues.

Hence, I do not think we need to take any action on this issue. What do you think we should do?

**Comment by Rombur** [comment]
Mixing compilers is usually OK. In this case, the problem is that the gcc 4.x compilers are not compatible with the newer gcc. There is nothing that we can do about it.

**Comment by tjhei** [comment]
The problem I have is that I can not convince boost.build to use g++-6.1 instead of g++. :-(

**Comment by kronbichler** [comment]
@tjhei Have you tried to use the guidelines explained here:
http://www.boost.org/build/doc/html/bbv2/overview/configuration.html

I remember that I compiled boost with non-default compilers at least once and remember to have looked at the instructions on that page (but I cannot remember what exactly I did).

**Comment by drwells** [comment]
@tjhei Whenever I do something like this (e.g., I went in reverse and built a copy of the library with `g++-4.7` a few days ago) I just force build with the bundled boost. Is there a reason that you cannot do this if all you need is the serialization part?

**Comment by Rombur** [comment]
I have compiled boost with gcc 6.1 on a system with gcc-4.7. I had no problem. Boost just picked up the compiler in my path. I did have to set gcc 6.1 in my PATH and my LD_LIBRARY_PATH.

**Comment by tjhei** [comment]
> @tjhei Have you tried to use the guidelines explained here:
> http://www.boost.org/build/doc/html/bbv2/overview/configuration.html

Thanks. I finally made it work by setting the g++ binary that way.

Closing.
