### ISSUE TITLE
Compilation of CUDA applications

### ISSUE THREAD

**Issue by kalj** [dealii/dealii#2594]
Currently, we only enable CUDA for code inside the Deal.II library, and not for the compilation of user applications. This prevents us from including CUDA code in headers, which is going to be necessary for some templated code.

[This branch](https://github.com/kalj/dealii/commits/cuda-application-compilation) tries to do that, but it is not working at the moment. Work in progress.

**Comment by tamiko** [comment]
@kalj Please ping me if I shall have a look at something.

**Comment by tamiko** [comment]
For the time being, I suggest to simply augment the final `CMakeLists.txt` file used in user programs/example steps.

**Comment by kalj** [comment]
I just saw this, which looks very promising: https://blog.kitware.com/cmake-ups-support-for-popular-programming-languages-in-version-3-8/
:D

**Comment by kalj** [comment]
I will take a look at it in a couple of weeks.
