### ISSUE TITLE
C++11 flags not passed to nvcc

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#2598]
I can compile deal.II with nvcc but when I add cuda code, I get an error for the c++11 functions. I have to add ```-DCUDA_NVCC_FLAGS="-std=c++11"``` during configuration. It seems the flags are not passed correctly to nvcc.

**Comment by kalj** [comment]
Yes, we need to set it manually based on DEAL_II_WITH_CXX11 .

**Comment by kalj** [comment]
New fix pushed. We now require C++11 to be enabled for CUDA.
