### ISSUE TITLE
CUDA compilation: Strange warning about whitespace after macro name

### ISSUE THREAD

**Issue by kalj** [dealii/dealii#2606]
This warning is obtained when compiling Deal.II with CUDA enabled. 

    <command-line>:0:8: warning: ISO C99 requires whitespace after the macro name

For some reason, the context of the warning, i.e. which file this is caused by, is missing. However, it appears after compilation of CUDA code so it is related to that.

**Comment by bangerth** [comment]
It complains about something that is given via `-D` on the command line.  What is the command line?

**Comment by kalj** [comment]
That is a good point! We set various macros using cmake so it might not necessarily be set explicitly on the command line. Still, this is valuable and I will look into it.

**Comment by kalj** [comment]
@Rombur: @bangerth is correct, compiling anything with nvcc or regular gcc and defining an invalid macro such as this:

    g++ -DFOO.4=1 hello.cc

gives

    <command-line>:0:4: warning: missing whitespace after the macro name

or if `--std=c++11` is used,

    <command-line>:0:4: warning: ISO C99 requires whitespace after the macro name

I will continuing investigating this.

**Comment by kalj** [comment]
Okay, I managed to track it down to some commands generated by CMake within FindCUDA. The problematic macro is `obj_lac.debug_EXPORTS` or the corresponding one for release. This is generated by CUDA_WRAP_SRCS from its first argument, which in this case happens to be obj_lac.debug , which is problematic due to the dot. If I understand it correctly, this name does not have to correspond to anything else, so we should be just fine just changing it. I have a fix prepared.
