### ISSUE TITLE
Trilinos random crash in compress()

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2613]
I am observing random crashes when calling compress() on a Trilinos BlockSparseMatrix after assembly. Trilinos version is 12.4.2. The assertion is one of the two (in a random timestep):

```
/home/heister/shared-dealii/deal-8.4.1/tmp/unpack/trilinos-12.4.2-Source/packages/epetra/src/Epetra_CrsMatrix.cpp:2809: int Epetra_CrsMatrix::TUnpackAndCombine(const Epetra_SrcDistObject&, int, int*, int, char*, int&, Epetra_Distributor&, Epet/ra_CombineMode, const Epetra_OffsetIndex*) [with int_type = int]: Assertion `(intptr[0])==ToRow' failed.
/home/heister/shared-dealii/deal-8.4.1/tmp/unpack/trilinos-12.4.2-Source/packages/epetra/src/Epetra_CrsGraph.cpp:2852: virtual int Epetra_CrsGraph::UnpackAndCombine(const Epetra_SrcDistObject&, int, int*, int, char*, int&, Epetra_Distributor&, Epetra_CombineMode, const Epetra_OffsetIndex*): Assertion `(intptr[0])==ToRow' failed.
```

This is within ASPECT, but it looks like a bug in our wrappers or inside Trilinos, so I am tracking this here.

Before I try to make a minimal working example: has anybody else seen something like this before? Any idea what is going on? I am especially confused because it only happens every ~100 timesteps or so. @kronbichler @Rombur ?

**Comment by Rombur** [comment]
I haven't seen that before. It seems like the data was sent to the wrong place. Does it happen right after the mesh is modified?

**Comment by tjhei** [comment]
> I haven't seen that before. It seems like the data was sent to the wrong place. Does it happen right after the mesh is modified?

I didn't realize this at first, but yes. It is the first time we assemble a block system after mesh refinement. Note the we assemble and solve a scalar system without any problems before. Maybe a race between the four blocks?

**Comment by Rombur** [comment]
I looked at the code but everything looks fine. Maybe check that the ```locally_owned_domain_indices``` IndexSet are updated correctly for every block.

**Comment by kronbichler** [comment]
If it is after the mesh is refined, it can be that we somewhere miss to reset something about the non-local matrix. I have not seen that in my codes but I have not used block matrices so there might be something related to that. I think it would be good to have a test for this.

**Comment by tjhei** [comment]
One problem is that I can only reproduce it if I use more than a single node. I'll see what I can do.

**Comment by kronbichler** [comment]
> One problem is that I can only reproduce it if I use more than a single node.

So the problem is not directly related to the number of MPI ranks but to some physical stuff like where the data is? That sounds complicated. I have some hope that we create some empty rows at some places and we can circumvent the problem if we do it the right way...

**Comment by tjhei** [comment]
I assume that it is just easier to trigger something timing sensitive with higher latencies.

**Comment by bangerth** [comment]
@tjhei -- without a way to reproduce, it's hard to fix anything. How do you suggest we proceed?

**Comment by tjhei** [comment]
I suggest we close until we encounter it again.
