### ISSUE TITLE
CUDA tries to turn on in C++03 mode

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2631]
My workstation has CUDA on it and the library correctly detects it. However, If I try to compile the library with `DEAL_II_CXX_VERSION_FLAG="-std=c++03"` and do not explicitly request CUDA, then CMake fails with a complaint that CUDA does not work without C++11 support. Put another way: I have to explicitly disable CUDA if I want to compile in C++03 mode.

I believe our usual strategy here is to only fail if the user requests feature support that doesn't work, i.e., split the logic between `DEAL_II_HAVE_CUDA` and `DEAL_II_WITH_CUDA`, and not fail if the feature cannot be used and it was not requested.

**Comment by Rombur** [comment]
@kalj Can you look into this? You need to change ```DEAL_II_WITH_CUDA``` to be ```OFF``` by default.

**Comment by kalj** [comment]
Thanks for noticing this. I will take a look.

**Comment by kalj** [comment]
PR #2633 fixes this, but don't know if it is the nicest way to do it. What do you think @tamiko?

**Comment by tamiko** [comment]
I'm sorry for not having reviewd this earlier.

There is a mechanism readily available to express inter-feature dependencies. Just set
```
  SET(FEATURE_CUDA_DEPENDS CXX11)
```
in ```configure_1_cuda.cmake```. I will make a pull request for this.

**Comment by drwells** [comment]
I did verify that this fixes the issue with my workstation, but @Rombur beat me to the merge.
