### ISSUE TITLE
Enable C++11-only tutorials once we switch to C++11

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2647]
As noted in #2646, we only have those tutorials in the list of build tests that don't require C++11. Once we finally make the switch to C++11, the tutorials that require C++11 but nothing else should be enabled again (specifically step-44). Alternatively, we could of course enable all build tests that can be built with the current configuration.

See #1519.

**Comment by drwells** [comment]
It looks like this was closed by #4229: I don't see any other such checks besides the one in step-44.
