### ISSUE TITLE
Slow DynamicSparsityPattern::begin(row)

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2656]
Iterating over entries of a DSP by row (as it is recommended), is quadratic in the number of rows if many/most are empty. This is because we are trying to find the first non-empty row (both in ``begin(row)`` and ``end(row)``).
This is even worse in parallel, because we iterative over all rows not only our own.

I have an idea how to fix the second point, but I am struggling to come up with a good solution for the first part. Would it be acceptable to change the semantics of ``begin(r)`` to return ``end()`` if the current row is empty, instead of returning an iterator to the first entry of the first non-empty row? This potentially breaks tests and user code.

Why do I care about this? It turns out that PETScWrappers::MPI::SparseMatrix iterates over the given DSP to preallocate entries and I have an empty block in a block system. It turns out this iteration dominates the whole computation. :-(

**Comment by kronbichler** [comment]
I've seen this in the Trilinos initialization of matrices as well (and it completely spoiled a performance test on 10k+ cores I did a year ago), so I resolved the issue by e0d8ca8. The right thing to do would be to loop over the locally relevant rows, not all rows of the matrix. But I admit that it would be difficult to do this with our current interface...

**Comment by tjhei** [comment]
Ahh, thanks. Do you think #2690 is reasonable?
