### ISSUE TITLE
PETSC

### ISSUE THREAD

**Issue by Esfahani120** [dealii/dealii#2658]
Hi,

Greetings. As a person who is trying to learn Deal-ii, I'm trying to change step-25 for parallel computation based on step-40, I have changed this step for my problem (I solved my problem by modifying this step previously without MPI). Unfortunately, I got several errors because there is no matching function for call to 'dealii::PETScWrappers::MPI::SparseMatrix::add...' and  'dealii::PETScWrappers::MPI::Vector::Vector(dealii::PETScWrappers::VectorBase::size_type)'
I find out that there is no "add" as a public member in PETScWrappers::MPI::SparseMatrix but there is an "add" public function for  PETScWrappers::MatrixBase.
It worth mentioning again that I am trying to change step-25 based on the method described in step-40 for MPI.

Thanks in advance for your help,
Ehsan

**Comment by bangerth** [comment]
Ehsan, it's hard to tell what your problem is without (i) seeing the text, and (ii) seeing the error message.

But in general, yes, when you say
```
  PETScWrappers::MPI::SparseMatrix A;
  A.add (1,2, 42.456);
```
then this will call the `add` function of the base class `PETScWrappers::MatrixBase`, and that is entirely correct.

**Comment by Esfahani120** [comment]
Thanks for your response. I have attached my modified code. Also, here are the first few errors in my code if it helps:

[step-25.TXT](https://github.com/dealii/dealii/files/292359/step-25.TXT)



/home/bruno/dealii/install_debug/examples/step-25/step-25.cc: In
member function ‘void
Step25::SineGordonProblem<dim>::right_hand_side()’:
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:357:79:
error: ‘dsp’ was not declared in this scope
     LA::MPI::SparseMatrix tmp_matrix (locally_owned_dofs,
locally_owned_dofs, dsp, mpi_communicator);

        ^~~
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc: In
member function ‘unsigned int
Step25::SineGordonProblem<dim>::solve()’:
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:508:6:
error: expected primary-expression before ‘/’ token
      / * Trilinos defaults are good * /
      ^
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:508:10:
error: ‘Trilinos’ was not declared in this scope
      / * Trilinos defaults are good * /
          ^~~~~~~~
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:508:10:
note: suggested alternative:
In file included from
/home/bt2/dealii/install_debug/include/deal.II/base/timer.h:22:0,
                 from
/home/bt2/dealii/install_debug/examples/step-25/step-25.cc:22:
/home/bruno/dealii/install_debug/include/deal.II/base/utilities.h:453:13:
note:   ‘dealii::Utilities::Trilinos’
   namespace Trilinos
             ^~~~~~~~
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc: In
instantiation of ‘void
Step25::SineGordonProblem<dim>::make_grid_and_dofs() [with int dim =
2]’:
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:562:24:
required from ‘void Step25::SineGordonProblem<dim>::run() [with int
dim = 2]’
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:641:23:
required from here
/home/bruno/dealii/install_debug/examples/step-25/step-25.cc:258:76:
error: no matching function for call to
‘dealii::DynamicSparsityPattern::DynamicSparsityPattern(dealii::IndexSet&,
dealii::IndexSet&)’
     DynamicSparsityPattern dsp(locally_relevant_dofs,
locally_relevant_dofs);//dof_handler.n_dofs() replaced by
locally_relevant_dofs

**Comment by Rombur** [comment]
@Esfahani120 your first problem has nothing to with MPI. ```dsp``` does not exist in ```void SineGordonProblem<dim>::right_hand_side ()``` It only exists in ```void SineGordonProblem<dim>::make_grid_and_dofs ()```

**Comment by Esfahani120** [comment]
@Rombur @bangerth 
Thanks for your response, yes the first error is not related to MPI but when I even solve this problem, there are still errors related to MPI like:
^no matching function for call to  dealii::PETScWrappers::MPI::SparseMatrix::add(__gnu_cxx::__promote_2<double, int, double, double>::__type, dealii::LinearAlgebraPETSc::MPI::SparseMatrix&)’	
^no matching function for call to ‘dealii::PETScWrappers::MPI::SparseMatrix::SparseMatrix(dealii::IndexSet&, dealii::IndexSet&, dealii::DynamicSparsityPattern&, ompi_communicator_t*&)’	
I think there is something wrong with type of arguments I'm using. :(

Best,

**Comment by Rombur** [comment]
@Esfahani120 The order of the arguments is wrong in lines 355 and 359 https://dealii.org/8.4.1/doxygen/deal.II/classPETScWrappers_1_1MatrixBase.html#a4c6dd3228481fd5424cd0b6c62fe9261 The first argument is the matrix and the second is the value.

For the second error, I am not sure which constructor you are trying to use.  One thing you need to be careful is that the PETSc interface and the Trilinos interface are different.

**Comment by Esfahani120** [comment]
@Rombur 
Thanks, Yes I have changed the arguments in a proper way. Problem is that, when I use the following line:
**LA::MPI::SparseMatrix tmp_matrix (locally_owned_dofs, locally_owned_dofs, dsp, mpi_communicator);**
I get this error: 
**no matching function for call to ‘dealii::PETScWrappers::MPI::SparseMatrix::SparseMatrix(dealii::IndexSet&, dealii::IndexSet&, dealii::DynamicSparsityPattern&, ompi_communicator_t*&)' line 302**
when I change the code to:
**LA::MPI::SparseMatrix tmp_matrix;
tmp_matrix.reinit (locally_owned_dofs, locally_owned_dofs, dsp, mpi_communicator);**
I get no error but I think there is something wrong.
I'm using the same order of the arguments in this particular case for mass_matrix and I got no error!! 
_What's more_, I'm getting an error:
**no match for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const dealii::IndexSet’)
step-25-Debug@step-25 (mine) line 153, external location: /home/ehsan/apps/candi/deal.II-toolchain/deal.II-v8.4.0/include/deal.II/base/conditional_ostream.h**
do you have any suggestion about these errors?

**Comment by Rombur** [comment]
2016-06-02 13:01 GMT-04:00 Esfahani120 <notifications@github.com>:

> @Rombur <https://github.com/Rombur>
> Thanks, Yes I have changed the arguments in a proper way. Problem is that,
> when I use the following line:
> *LA::MPI::SparseMatrix tmp_matrix (locally_owned_dofs, locally_owned_dofs,
> dsp, mpi_communicator);*
> I get this error:
> *no matching function for call to
> ‘dealii::PETScWrappers::MPI::SparseMatrix::SparseMatrix(dealii::IndexSet&,
> dealii::IndexSet&, dealii::DynamicSparsityPattern&, ompi_communicator_t*&)'
> line 302*
>
This constructor does not exist. You need to look at the doxygen to see
which function exists or not. If you look here
https://dealii.org/8.4.1/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1SparseMatrix.html,
you will see that this constructor does not exist.

>
> when I change the code to:
>
> *LA::MPI::SparseMatrix tmp_matrix; tmp_matrix.reinit (locally_owned_dofs,
> locally_owned_dofs, dsp, mpi_communicator);*
> I get no error but I think there is something wrong.
>
This function exists that's why it works
https://dealii.org/8.4.1/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1SparseMatrix.html#ada623c75b093257140547fae23a73b1e
Don't assume that the elements will always be needed in the same order. It
would be nice if it was like that but unfortunately it is not.

> I'm using the same order of the arguments in this particular case for
> mass_matrix and I got no error!!
> *What's more*, I'm getting an error:
>
> *no match for ‘operator<<’ (operand types are ‘std::ostream {aka
> std::basic_ostream}’ and ‘const dealii::IndexSet’) step-25-Debug@step-25
> (mine) line 153, external location:
> /home/ehsan/apps/candi/deal.II-toolchain/deal.II-v8.4.0/include/deal.II/base/conditional_ostream.h*
> do you have any suggestion about these errors?
>
An IndexSet is a complex object and so there no default function for
operator << We could have overloaded the operator but instead we have a
print function
https://dealii.org/8.4.1/doxygen/deal.II/classIndexSet.html#aafd07e605f3e7361175060f6f89edf18
So instead of doint std::cout<< locally_owned_dofs <<std::endl; You would
do locally_owned_dofs(std::cout);

**Comment by davydden** [comment]
@Esfahani120: did @Rombur 's answer resolve your problem? Can I close this issue now?

**Comment by Esfahani120** [comment]
@davydden 
Yes he did. 
Thanks,
