### ISSUE TITLE
Vertex position update leaves FEValues stale

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#2661]
Reference to this [forum post](https://groups.google.com/forum/#!topic/dealii/c8QfaMThBaQ):

When moving the mesh as is done in step-18, at least 1 global refinement must be performed in order for the geometry update to be propagated to any DoFHandlers that are attached to the triangulation. An MWE is located here: [mesh_movement.cc.zip](https://github.com/dealii/dealii/files/292744/mesh_movement.cc.zip)

**Comment by jppelteret** [comment]
Gist located [here](https://gist.github.com/jppelteret/54434358c08059d01b731868c60b0085)

**Comment by jppelteret** [comment]
Note: If an FEValues object is created after the (single cell) mesh is moved, then the result is correct. Perhaps the issue pertains to value caching in FEValues?

**Comment by jppelteret** [comment]
I think that this issue has appeared again in a [slightly different context](https://groups.google.com/forum/#!topic/dealii/e__LG6vdUBQ), namely with the triangulation alone.

**Comment by bangerth** [comment]
Interesting bug. This actually has nothing to do with DoFHandlers and similar, but simply with having a stale FEValues object (though I don't yet know why). Here's a simpler testcase:
```
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/fe/fe_dgq.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>

#include <iostream>
#include <fstream>

using namespace dealii;


template<int dim>
double
integral_volume (const Triangulation<dim> &triangulation,
                 FEValues<dim> &fe_values)
{
  // we have only one cell, and it is square, so the single JxW value
  // of the QMidpoint gives the volume of the cell
  fe_values.reinit(triangulation.begin_active());
  return fe_values.JxW(0);
}


int main()
{
  Triangulation<2> triangulation;
  FE_DGQ<2> fe(0);
  QMidpoint<2> qf_cell;

  GridGenerator::hyper_cube(triangulation, 0.0, 1.0);
  FEValues<2> fe_values (fe, qf_cell, update_JxW_values);

  // compute the volume of the mesh two ways
  std::cout << "Volume before mesh movement: " 
            << "  Using GridTools: " << GridTools::volume(triangulation)
            << "  Calculated: " << integral_volume(triangulation, fe_values) 
            << std::endl;

  // shrink the mesh
  GridTools::scale (0.5, triangulation);
		
  // Now we measure the volume again:
  std::cout << "Volume after mesh movement:  " 
            << "  Using GridTools: " << GridTools::volume(triangulation)
            << "  Calculated: " << integral_volume(triangulation, fe_values) 
            << std::endl;
}
```
It outputs this:
```
Volume before mesh movement:   Using GridTools: 1  Calculated: 1
Volume after mesh movement:    Using GridTools: 0.25  Calculated: 1
```
In other words, even though we do `FEValues.reinit()` in `integral_volume()`, we still get the old JxW value we got when we visited the cell first.

One can get the right result by creating a new `FEValues` object after the mesh shrinking step. In other words, don't keep them around across mesh modification steps. This is of course what we do in all tutorial programs.

I have no idea yet what causes the bug. I thought for a moment that it may be because of the `cell_similarity` caching of data. But we don't use `cell_similarity` in multithread mode, which is enabled on my machine. We also attach the `FEValues` object to the triangulation signals, but adding a call
```
  triangulation.signals.any_change();
```
(or to the `post_refinement` signal) that would trigger the invalidation of the `FEValues` cache makes no difference.

Does anyone have an idea what could be going on and where to look?

**Comment by bangerth** [comment]
The problem is here, in `mapping_q_generic.cc` around line 2559:
```
template<int dim, int spacedim>
CellSimilarity::Similarity
MappingQGeneric<dim,spacedim>::
fill_fe_values (const typename Triangulation<dim,spacedim>::cell_iterator &cell,
                const CellSimilarity::Similarity                           cell_similarity,
                const Quadrature<dim>                                     &quadrature,
                const typename Mapping<dim,spacedim>::InternalDataBase    &internal_data,
                internal::FEValues::MappingRelatedData<dim,spacedim>      &output_data) const
{
  // ensure that the following static_cast is really correct:
  Assert (dynamic_cast<const InternalData *>(&internal_data) != 0,
          ExcInternalError());
  const InternalData &data = static_cast<const InternalData &>(internal_data);

  const unsigned int n_q_points=quadrature.size();

  // if necessary, recompute the support points of the transformation of this cell
  // (note that we need to first check the triangulation pointer, since otherwise
  // the second test might trigger an exception if the triangulations are not the
  // same)
  if ((data.mapping_support_points.size() == 0)
      ||
      (&cell->get_triangulation() !=
       &data.cell_of_current_support_points->get_triangulation())
      ||
      (cell != data.cell_of_current_support_points))
    {
      data.mapping_support_points = this->compute_mapping_support_points(cell);
      data.cell_of_current_support_points = cell;
    }
```
The `if` doesn't trigger here because we end up on the same cell. Of course that's correct, it's just that the cell is no longer where we thought it is. Should we also store the vertex locations of the cell to compare with? Or should we just declare that this is a corner case that's not supported?

**Comment by jppelteret** [comment]
Cool, thanks @bangerth for pinpointing the source of the problem! 

What do you think about this: We could choose not to expose the underlying vertex to the user, but rather have `cell->vertex(v)` return a `const Point<dim> &`. We could then have a set of internal flags `std::vector<bool> vertex_touched` and move vertices with calls like `tria.move_vertex(global_vertex_id, displacement)` and `cell->move_vertex(v, displacement)`. These would in turn register that the vertex has been moved at some point since the cell was created and could be checked in the function that you've listed above.

**Comment by kronbichler** [comment]
> The `if` doesn't trigger here because we end up on the same cell.  Of course that's correct, it's just that the cell is no longer where we thought it is.

This looks like one of those caching bugs where we try to be smart and want to avoid re-computing things that are already present? We made the experience with the cell similarity that trying to be smart sometimes interferes with generality and exposes subtle issues. My question at this point would be how often the last check `cell != data.cell_of_current_support_points` actually triggers and whether we could simply skip it without a big performance penalty. As far as I can see, `MappingQGeneric::fill_fe_values` is called exactly once per reinit call of FEValues, no matter the context. This is opposed to the `FiniteElement::fill_fe_values` calls which can involve several sub-calls for an `FESystem` on each base element. Thus, to my understanding the optimization really only helps in case a user makes two `reinit` calls, in which case I have no problem to let the user pay for two calls. The other context that I could see a point in caching this is when two FEValues objects act on the same geometry and the geometry would be created just once. But we do not support that kind of data sharing over FEValues objects anyway (even though it would make some sense), so again I see no point in trying to be smart here.

**Comment by bangerth** [comment]
@kronbichler -- yes, I think I have come to the same conclusion, namely that the caching is simply not very useful. The number of cases where we call `reinit` with *exactly* the same cell are just negligible. 

I have toyed with the idea of not only storing the cell, but also the vertices, and adding them to the comparison. But then someone will come along and set a curved boundary between two different calls (same vertices, different geometry) and we will again spend a couple of hours debugging. I think I'd rather just removing the whole check.
