### ISSUE TITLE
Document required Trilinos libraries

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#2674]
When answering [this](https://groups.google.com/forum/#!topic/dealii/rwhHI4Ja-4E) question, I couldn't find anywhere in the documentation that explicitly stated which libraries Trilinos needs to be built with in order to successfully link to it. Judging from [this](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_2_trilinos.cmake) cmake file, I think that the list of prerequisite packages is

- Amesos 
- Epetra 
- Ifpack 
- AztecOO 
- Sacado 
- Teuchos
- ML 
- MueLu (if Trilinos version > 11.14)

Perhaps this should be added to [this](https://www.dealii.org/developer/external-libs/trilinos.html) page?

**Comment by bangerth** [comment]
That's a reasonable place to put such a list.
