### ISSUE TITLE
no doxygen for PArpack class

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2681]
It looks like no doxygen is generated for PArpack class in `lac/parpack_solver.h`.

**Comment by bangerth** [comment]
You probably need to set `DEAL_II_WITH_PARPACK=1` in `doc/doxygen/options.dox.in`, around line 165, like for all of the other packages. Want to try that?

**Comment by davydden** [comment]
will do now...

**Comment by bangerth** [comment]
Yes, whatever the appropriate preprocessor `#define` is that guards the visibility of these classes in the header files.
