### ISSUE TITLE
Fix links for documentation for parallel::distributed::GridRefinement

### ISSUE THREAD

**Issue by spco** [dealii/dealii#2713]
In the documentation for parallel::distributed::GridRefinement

https://www.dealii.org/developer/doxygen/deal.II/namespaceparallel_1_1distributed_1_1GridRefinement.html

both functions' explanations begin like
`Like GridRefinement::refine_and_coarsen_fixed_number, but for parallel distributed triangulation.` but the link in that sentence doesn't go to their serial partner, but back to themselves.

**Comment by bangerth** [comment]
I think that's a bug in doxygen :-( We have this in the original code:
```
     /**
       * Like dealii::GridRefinement::refine_and_coarsen_fixed_number, but for
       * parallel distributed triangulation.
```
and the `filter` scripts substitutes this:
```
    # We don't let doxygen put everything into a namespace
    # dealii. consequently, doxygen can't link references that contain an
    # explicit dealii:: qualification. remove it and replace it by the
    # global scope
    #
    # Now, as of doxygen 1.5, this still produces the wrong result, but
    # that's not our fault. This is reported here:
    #    http://bugzilla.gnome.org/show_bug.cgi?id=365053
    s/(::)?dealii::/::/g;
```

Ideas?

**Comment by bangerth** [comment]
It's only been 10 years since I opened that doxygen bug...

**Comment by bangerth** [comment]
I don't see a solution to fix this. @spco , unless you have a concrete idea how to address this, I don't see much of a point to keep this issue open, I'm afraid.

**Comment by spco** [comment]
No, I don't have a way to proceed on this - I'll close the issue. Perhaps Doxygen will get around to fixing it!
