### ISSUE TITLE
OSX binaries: force clang in OMP wrappers

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2730]
If users have g++ in the path (for example through macports), the MPI wrapper mpic++ is preferring g++ over the clang compiler we need. This can be fixed by exporting
```
export OMPI_CXX=clang++
export OMPI_CC=clang
```

Can we have this as part of the deal.II terminal in the future?

**Comment by tamiko** [comment]
Let's label packaging stuff with "Build system" as well :-)

**Comment by luca-heltai** [comment]
Ok. I'll make sure that the terminal also sets CC anx CXX variables to `which mpicc` and `which mpicxx`.

**Comment by luca-heltai** [comment]
Actually, I just checked the last image I released, and it already sets all the needed variables on the terminal. I think I addressed this when I read the comment, but never closed the issue.

@tjhei , can you confirm if the latest package I published is ok for you?

https://github.com/luca-heltai/dealii/releases/tag/v8.5.pre.2

**Comment by bangerth** [comment]
@tjhei -- can you confirm that this now works, as suggested by @luca-heltai ? If so, can this be closed?

**Comment by tjhei** [comment]
> @tjhei -- can you confirm that this now works,

No, I can not (this was a machine somebody showed me and I have no recollection who that was). I hope it is fixed now...
