### ISSUE TITLE
Serialize Triangulation

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#2735]
There is a paragraph in the Triangulation documentation that explains why the entire Triangulation cannot be serialized. This paragraph explains that pointers cannot be serialized. This is not true, boost automatically serializes and deserializes pointers correctly. Thus, the save and load functions can be extended to save the whole Triangulation object.

**Comment by bangerth** [comment]
For reference, this is the section:
```
 * <h3>Serializing (loading or storing) triangulations</h3>
 *
 * Like many other classes in deal.II, the Triangulation class can stream its
 * contents to an archive using BOOST's serialization facilities. The data so
 * stored can later be retrieved again from the archive to restore the
 * contents of this object. This facility is frequently used to save the state
 * of a program to disk for possible later resurrection, often in the context
 * of checkpoint/restart strategies for long running computations or on
 * computers that aren't very reliable (e.g. on very large clusters where
 * individual nodes occasionally fail and then bring down an entire MPI job).
 *
 * For technical reasons, writing and restoring a Triangulation object is not
 * trivial. The primary reason is that unlike many other objects,
 * triangulations rely on many other objects to which they store pointers or
 * with which they interface; for example, triangulations store pointers to
 * objects describing boundaries and manifolds, and they have signals that
 * store pointers to other objects so they can be notified of changes in the
 * triangulation (see the section on signals in this introduction). As objects
 * that are re-loaded at a later time do not usually end up at the same
 * location in memory as they were when they were saved, dealing with pointers
 * to other objects is difficult.
 *
 * For these reasons, saving a triangulation to an archive does not store all
 * information, but only certain parts. More specifically, the information
 * that is stored is everything that defines the mesh such as vertex
 * locations, vertex indices, how vertices are connected to cells, boundary
 * indicators, subdomain ids, material ids, etc. On the other hand, the
 * following information is not stored: - signals - pointers to boundary
 * objects previously set using Triangulation::set_boundary On the other hand,
 * since these are objects that are usually set in user code, they can
 * typically easily be set again in that part of your code in which you re-
 * load triangulations.
 *
 * In a sense, this approach to serialization means that re-loading a
 * triangulation is more akin to calling the
 * Triangulation::create_triangulation function and filling it with some
 * additional content, as that function also does not touch the signals and
 * boundary objects that belong to this triangulation. In keeping with this
 * analogy, the Triangulation::load function also triggers the same kinds of
 * signal as Triangulation::create_triangulation.
```

**Comment by bangerth** [comment]
I think the fundamental issue I wanted to express when I wrote this section is that we *don't know* whether the objects to which the triangulation has a pointer to will *also* be serialized. This is because they are objects owned by user space. A user may choose to do exactly what we recommend right now: only serialize the data that changes over time, and upon restart re-create the objects that do not change over time (objects describing boundaries, manifolds, etc). The reason for doing so would be that there is no point in saving them to a file because we know how to exactly re-create these objects. That's what we do in ASPECT, for example.

So in cases like this, boost::serialize can store a reference to an object instead of the pointer, but the reference will never be satisfied at write time because the object pointed to is not serialized. Clearly, at load time, boost::serialize will not know where to let the pointer point to because it never gets to re-create the object originally pointed to.

**Comment by Rombur** [comment]
I see. I think that we should make more clear that the problem is not the pointers per se but that the user code may or may not be serialized.

**Comment by bangerth** [comment]
Yes, I think that could use a better explanation. Volunteers welcome, using my description above.

**Comment by sairajat** [comment]
I think the documentation also needs some modification, not just better explaination.
As per a forum discussion and issue #2796  , saving a triangulation saves only the refinement flag.
From the documentation (above comment)

> "* For these reasons, saving a triangulation to an archive does not store all
>  * information, but only certain parts. More specifically, the information
>  * that is stored is everything that defines the mesh such as vertex
>  * locations, vertex indices, how vertices are connected to cells, boundary
>  * indicators, subdomain ids, material ids, etc"

This is contradictory.

**Comment by Rombur** [comment]
@sairajat No the documentation is correct. If you serialize a ```Triangulation```, all the information to reconstruct a serial ```Triangulation``` is saved. If you use the ```save``` function of a ```parallel::distributed::Triangulation``` only the refinement flags are saved. You can serialize a ```parallel::distributed::Triangulation``` but the p4est objects associated to it won't be serialized and you won't be able to deserialize it to a ```parallel::distributed::Triangulation```. However, you will be able to deserialize it to a serial ```Triangulation```.

**Comment by sairajat** [comment]
Thanks @Rombur. I now understand what you mean. 
Suppose I serialize a `parallel::distributed::Triangulation` . If I want the same `Parallel::distributed::Triangulation` upon a restart, then I can deserialize it into a `Triangulation`, and then this serial triangulation can be used to generate a `parallel::distributed::Triangulation`.  But, will  this change the element distribution amongst the processors ? 
Strictly speaking, will all the processors have the same `locally_owned_cells` as before ?

**Comment by Rombur** [comment]
It depends. The partition is done by p4est that is not saved when you serialized the ```Triangulation```. So when you copy the serial ```Triangulation``` to generate the ```parallel::distributed::Triangulation```, new p4est objects are created and the partition is done. I assume that if you didn't repartition your mesh before the serialization and you keep using the same number of processors you will get the same partitioning. One thing to note (and here again the documentation is missing) is that you can only copy a serial ```Triangulation``` to a ```parallel::distributed::Triangulation``` if the triangulation has never been refined. So the serialization/deserialization can be used to save the coarsest mesh you are working with but then you still need to use the ```save``` function from ```parallel::distributed::Triangulation``` to get the refined mesh.
