### ISSUE TITLE
gsl and gslcblas undefined symbols at linking stage using deal.ii autopilote

### ISSUE THREAD

**Issue by andreabonito** [dealii/dealii#2757]
Hi:

during the linking process, I get the following error:

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/libgsl.so: error: undefined reference to 'cblas_dasum'

and plenty similar others.

A fix around was to modify the file

CMakeFiles/TARGET_NAME.dir/link.txt

by adding -lgslcblas right after -lgsl .

Any way this could be automatically included in the autopilote process? 
In case it helps, I am attaching the detailed.log file from the deal.ii installation. 

Many thanks in advance,
Andrea
[detailed.log.txt](https://github.com/dealii/dealii/files/350902/detailed.log.txt)

**Comment by davydden** [comment]
looking at https://www.gnu.org/software/gsl/ 
> GSL requires a BLAS library for vector and matrix operations. The default CBLAS library supplied with GSL can be replaced by the tuned ATLAS library for better performance,

so it looks like in your case this default `cblas` is not withint `gsl`, but in a separate lib `libgslcblas`. This is not the case when `gsl` is compiled with package managers like [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gsl.rb) or [Spack](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/gsl/package.py).

@tamiko any ideas for a workaround?

**Comment by davydden** [comment]
p.s. if `libgsl.so` needs `libgslcblas.so`, should not it have this as rpath in `otool -L` (macOS) or `lld` (Linux)?

**Comment by andreabonito** [comment]
This is quite possible (and a bit out of my hands):

The command

ldd /usr/lib/libgsl.so

returns

	linux-vdso.so.1 =>  (0x00007fff47a00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f37b6920000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f37b6560000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f37b7088000)

If this is of any help, there is also a /usr/lib/libgslcblas.so file in the same /usr/lib directory which contains no symbol.

**Comment by davydden** [comment]
A workaround for now is to configure with `-DDEAL_II_WITH_GSL:BOOL=OFF`.

**Comment by andreabonito** [comment]
yep that works, thanks. Hopefully I will not need gsl anythime soon.

**Comment by tamiko** [comment]
@davydden I absolutely missed this bug. Next time just reopen and add the ```buildsystem``` tag :-P

**Comment by davydden** [comment]
@andreabonito FYI, this https://github.com/dealii/dealii/pull/2885 should fix this issue properly.
