### ISSUE TITLE
C++11 failure when only -std=c++0x is available

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2772]
I get a failure of the following form with GCC 4.6.3:
```
.../dealii/include/deal.II/base/quadrature_point_data.h:66:25: error: expected unqualified-id before ‘using’
```
This happens with the following set of lines from `include/deal.II/base/quadrature_point_data.h`
```
template <typename CellIteratorType, typename DataType>
class CellDataStorage : public Subscriptor
{
public:
  /**
   * A typedef for a vector of shared pointers with arbitrary data type @p T .
   */
  template <typename T> using CellVector = std::vector<std::shared_ptr<T> >;
```
The problem appears to be that GCC 4.6.3 has a flag `-std=c++0x` that makes the compiler accept *some* parts of C++11, but apparently not all -- in particular not template aliases (using) statements.

How do we address this? Only switch on C++11 mode if a compiler actually understands C++11, not just has a C++0x flag?

**Comment by davydden** [comment]
i know that one can declare in CMake which parts of c++11 are required. Perhaps this should be added so that c++11 is disabled if not all required parts of the standard are supported by a given compiler.

**Comment by bangerth** [comment]
Failing test for this compiler:
```
template <typename T> class X {};
template <typename T> using Y = X<T>;
```
We could also just put this test into `cmake/checks/check_01_cxx_features.cmake`. That may be the best option.

**Comment by bangerth** [comment]
On second thought, putting this into the cmake scripts is an awkward solution: it would downgrade some compilers that were previously detected as supporting C++11 (and with which people may have written programs that require C++11), and that are now declared as not supporting C++11. People's programs will then no longer compile.

I think I will instead think of ways to ensuring that that one header file just gets to compile with GCC 4.6. It's a new file anyway, so I will take the liberty to adjust it in incompatible ways as necessary.

**Comment by davydden** [comment]
> it would downgrade some compilers that were previously detected as supporting C++11 (and with which people may have written programs that require C++11), and that are now declared as not supporting C++11. People's programs will then no longer compile.

but if we are realistic, chances that this happens are super low. From the survey only 4.3% of users have compilers which do not support c++11 and they probably can use more modern compiler if they would need to.

> I think I will instead think of ways to ensuring that that one header file just gets to compile with GCC 4.6. It's a new file anyway, so I will take the liberty to adjust it in incompatible ways as necessary.

That may lead to a more obscure code. If this is the case, i think in the long run it make sense to keep the codebase follow modern standard and be clear as we are about to switch to c++11 anyway.

Alternative solution is to have another flag for this compiler feature like CXX_11_TEMPLATE_ALIASES.

**Comment by tjhei** [comment]
How inconvenient would it be to not use a template alias here?

**Comment by bangerth** [comment]
Yes, I had something like @drwells 's #2783 in mind. I might even have retained a
```
  typedef std::vector<std::shared_ptr<DataType>> CellVector;
```
which is just a regular `typedef` and names a type that is used everywhere. But I will profess liking #2783 better because I'm a big fan of making data types explicit for the sake of the reader.
