### ISSUE TITLE
Add assertion in ChartManifold::get_tangent_vector()?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2775]
One way to trigger the issue in #2763 at an earlier point is to with the following patch to `ChartManifold::get_tangent_vector`:
```
diff --git a/source/grid/manifold.cc b/source/grid/manifold.cc
index 912b751..027fd63 100644
--- a/source/grid/manifold.cc
+++ b/source/grid/manifold.cc
@@ -563,6 +563,9 @@ get_tangent_vector (const Point<spacedim> &x1,
                     const Point<spacedim> &x2) const
 {
   const DerivativeForm<1,chartdim,spacedim> F_prime = push_forward_gradient(pull_back(x1));
+  Assert (F_prime.determinant() >= 1e-12 * F_prime[0].norm(),
+          ExcMessage("The derivative of a chart function must not be singular."));
+  
   const Tensor<1,chartdim>                  delta   = sub_manifold.get_tangent_vector(pull_back(x1),
                                                       pull_back(x2));
 
```
In essence, what I am doing here is to ensure that the gradient of the chart mapping is not singular. This certainly seems sensible because otherwise, multiple directions will be mapped onto the same tangents -- as in fact happens in the testcase of #2763.

@luca-heltai -- what do you think of just adding this assertion? It would have saved me ~2 hours of debugging time, and I think that this should in fact always be satisfied or we would get in trouble downstream somewhere.

**Comment by luca-heltai** [comment]
Yes, this is sensible, and correct. The underlying Manifold should provide an invertible map...

**Comment by luca-heltai** [comment]
We should include this in the SphericalManifold PR (unless you already did this somewhere else) @ESeNonFossiIo

**Comment by bangerth** [comment]
Will prepare a patch for mainline. You'll get it via a rebase then.

**Comment by ESeNonFossiIo** [comment]
nice. I will wait for the patch and then i will rebase our branch.
Thank you

**Comment by bangerth** [comment]
See #2788.
