### ISSUE TITLE
The tests/scripts directory

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2778]
We currently have two Python scripts in the `tests/scripts` directory that don't seem to ever be run. @tjhei should we move these somewhere else, or did I miss their functionality?

**Comment by tjhei** [comment]
correct, we could move them to contrib/utilities.

**Comment by tamiko** [comment]
> correct, we could move them to contrib/utilities.

:+1: 

@drwells The ```tests/scripts``` directory contained considerably more script files a while ago but they were relocated to the ```cmake/*``` directories.
