### ISSUE TITLE
Initializing FE_ABF fails

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#2785]
While trying to initialize FE_ABF through FETools::get_fe_by_name (PR #2784),
I noticed that we fail for all polynomial degrees with errors like

---

An error occurred in line <99> of file <../source/fe/fe.cc> in function
     dealii::FiniteElement<<anonymous>, <anonymous> >::FiniteElement(const dealii::FiniteElementData<dim>&, const std::vector<bool>&, const std::vectordealii::ComponentMask&) [with int dim = 3; int spacedim = 3]
 The violated condition was: 
     restriction_is_additive_flags.size() == this->dofs_per_cell
 The name and call sequence of the exception was:
     ExcDimensionMismatch(restriction_is_additive_flags.size(), this->dofs_per_cell)
 Additional Information: 
 Dimension 36 not equal to 48

---

for FE_ABF<3>(1).

**Comment by tjhei** [comment]
Weird, isn't FE_ABF<2>(1) and (0) tested in fe/fe_project_2d and fe_abf_01 ?

**Comment by masterleinad** [comment]
Yes, it seems that just the 3D version is broken as enabling the corresponding line in the test in PR #2784 shows.

**Comment by bangerth** [comment]
Before anyone else gets on this, I have a patch forthcoming.
