### ISSUE TITLE
Improve continuous integration

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2795]
I finally sat down to set up an initial version of continuous integration (testing pull requests). See https://github.com/dealii/dealii/pull/2767#partial-pull-merging for an example run and http://www.math.clemson.edu/~heister/cib/dealii-tester-alpha/results.html for the "dashboard". See https://github.com/tjhei/docker-files/tree/ci for the setup (will be put into https://github.com/dealii/docker-files soon).

There are several limitations/todos right now:
- We need a more permanent empty machine for the testing. The more powerful the better.
- Process is not very well documented.
- I don't know how to make boot2docker inside virtualbox detect more than 8 cores (machine is set to 32), so the tester is somewhat slow.
- I am currently only compiling debug mode and testing 42 tests `ctest -R "multigrid/transfer"` , but it still takes 25 minutes to compile+test. We need to think about a reasonable fast setup and discuss what time is acceptable.
- Currently only @bangerth, @tamiko, and I are "trusted": only our PRs are tested automatically and only we can force running the tests using "/run-tests". Will update this at some point.

also see #1814 #1803

**Comment by bangerth** [comment]
If I had `virtualbox` installed on my tester machine, could I then download a virtual machine from somewhere that already has the necessary setup?

**Comment by tjhei** [comment]
> If I had virtualbox installed on my tester machine, could I then download a virtual machine from somewhere that already has the necessary setup?

Yes. I have played with moving from my custom built framework to a single jenkins server that then controls a number of workers (that can easily run in a VM). This would allow us to test various configurations including mac/linux.

**Comment by drwells** [comment]
At this point we have addressed all five points so lets close.
