### ISSUE TITLE
[cmake] DEAL_II_COMPONENT_COMPAT_FILES and directory structure.

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2802]
there used to be `DEAL_II_COMPONENT_COMPAT_FILES` cmake flag, which according to https://www.dealii.org/developer/users/cmake.html is not there anymore. The problem I have is that after installation `examples/`, `README` and `LICENSE` are in the root of the `prefix`, which is not convenient in case installation is done to `/usr/local` or in similar circumstances.

Presumable i can set `DEAL_II_EXAMPLES_RELDIR=share/deal.II/examples`, but i don't think one can fix `README` and `LICENSE` files, can one? If that is indeed the case, perhaps there should be a way to do this and move them, say, to `share/deal.II/`.

p.s. I could not find `DEAL_II_COMPONENT_COMPAT_FILES` mentioned in `changes.h` for current dev or a few previous releases, not sure when was it gone.

**Comment by tamiko** [comment]
Sure you can: For Gentoo, I for example set up the following structure:
```
-DDEAL_II_LIBRARY_RELDIR="$(get_libdir)"
-DDEAL_II_SHARE_RELDIR="share/dealii"
-DDEAL_II_DOCREADME_RELDIR="share/doc/dealii"
-DDEAL_II_EXAMPLES_RELDIR="share/doc/dealii/examples"
```

Have a look at ```https://www.dealii.org/developer/users/cmake.html#configureinstall``` it explains the variables at the end of the section. (It is not obvious but there is a 1 to 1 correspondence between the two listings).

**Comment by davydden** [comment]
@tamiko i don't see how can you have 1 to 1 correspondence between the listings of different size :smile:.

**Comment by davydden** [comment]
jokes aside, i think this part of the documentation could be improved/corrected.

**Comment by davydden** [comment]
@tamiko do you recall what's the last version of deal.II with `DEAL_II_COMPONENT_COMPAT_FILES`?

**Comment by tamiko** [comment]
```8.2.1-vs-8.3.0.h```:
```
 154   <li> Removed: The Component <code>compat_files</code> was removed entirely. deal.II
 155   now always configures and installs with a somewhat FSHS compliant              
 156   directory structure. Further, the ancient make_dependencies binary was         
 157   removed. Either migrate your project to CMake, or port your build system       
 158   to the new (incompatible) Make.global_options found at                         
 159   <code>\${DEAL_II_SHARE_RELDIR}</code>.                                         
 160   <br>                                                                           
 161   (Matthias Maier, 2015/01/13)                                                   
 162   </li>
```

**Comment by davydden** [comment]
@tamiko thanks.
