### ISSUE TITLE
petsc/solver_(01|02) and petsc_complex/solver_(01|02) tests broken.

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#2815]
All 4 tests throw a non-convergence error.

Prior to commit 6f53784f (back in 2013) this was apparently undetected. I accidentally checked in wrong comparison files with 6f53784f.

**Comment by tamiko** [comment]
In reference to #2814

**Comment by tamiko** [comment]
More tests that test for a single precision/maximal iteration count and simply fail:
```
petsc/solver_01
petsc/solver_02
petsc/solver_11
petsc_complex/solver_real_01
petsc_complex/solver_real_02
```

We have other tests (e.g. ```lac/solver```) that have intermittent ```NoConvergence``` errors - but test a variety of solvers and solver control values.

**Comment by tamiko** [comment]
@davydden @oneliefleft I guess none of the three original ```petsc/solver_*``` tests were ever meant to simply fail.

**Comment by davydden** [comment]
@tamiko judging from 
```
 // it needs to be expected for the
 // richardson solver that we end up
 // here, so don't abort
```
i would say they were meant to fail.

**Comment by tamiko** [comment]
@davydden *ugh* This doesn't make much sense. And funny enough it was me who wrote that.

**Comment by tamiko** [comment]
(the comment, not the tests)

**Comment by tamiko** [comment]
@davydden I'll fix it. It turns out that we reach a convergence after around 1800 iterations.
