### ISSUE TITLE
Document in PETSc instructions that --download-mpich is a bad idea

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2821]
We see people do it all the time, but it really only leads to lots of downstream problems :-(

**Comment by sairajat** [comment]
@bangerth The documentation still says that deal.ii 8.4.1 is compatible with petsc 3.6.0 and one may encounter problem with later version. 

> Note: The most recent version of PETSc that has been reported to be compatible with deal.II is version 3.6.0. If you use a later version than this and encounter problems, let us know.

Is the current released version not compatible even with 3.6.4 ? 
(I know about an issue that was raised to make dealii compatible with petsc 3.7.0)

**Comment by bangerth** [comment]
@sairajat -- I suspect that it is really 3.6.x, including 3.6.4. But the reality is that the PETSc people keep changing things in incompatible ways even between dot releases. So unless someone tries and tells us that a newer version of PETSc actually works, I don't think that we should change the statement.

**Comment by tamiko** [comment]
@sairajat We usually update the "known good versions" in the Readme every once in a while and especially prior to a release. The testsuite on ```simserv04``` uses 3.6.3 at the moment.
