### ISSUE TITLE
Issue in parallel scaling glossary

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#2829]
There is a line in the [documentation](http://www.dealii.org/developer/doxygen/deal.II/DEALGlossary.html#GlossParallelScaling) that says

> Rather, all programs cease to scale once either N or P grows larger than certain limits. We therefore often say things such as "the program scales up to 4,000 cores", or "the program scales up to **\form#91** unknowns".

I think there is a typo there.

**Comment by drwells** [comment]
Hm, interesting doxygen bug. I bet we could fix it by using `&ldquo;` and `&rdquo;` instead of the double quotes so that the math shows up. Would you like to give it a try?

**Comment by sairajat** [comment]
Hello, 
I would definitely love to contribute. However, given that I am a newbie with all this,
I really don't know how to use doxygen and `&ldquo;` and `&rdquo;`.

I would still be glad to give it a try and contribute if you / someone can guide me.

**Comment by bangerth** [comment]
Definitely a doxygen bug. I tried to use `10<sup>8</sup>` but that was rendered as is, i.e., without raising the `8` into an upper index. I'll have a patch in a second.

**Comment by drwells** [comment]
@sairajat Fair enough. Either way, thanks for reporting this!
