### ISSUE TITLE
 mpi/step-40_direct_solver got broken between 3e3fd07 and aa6946d for complex PETSc

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2840]
according to the tester  mpi/step-40_direct_solver got broken between 3e3fd07 and aa6946d for complex-valued PETSc.
Puzzling thing is that nothing really happened between the two commits:

```
$ git diff --name-only 3e3fd07
include/deal.II/lac/sparse_matrix.h # Doxygen only
source/grid/grid_reordering.cc #Assert only
tests/petsc/solver_01.cc
tests/petsc/solver_01.output
tests/petsc/solver_02.cc
tests/petsc/solver_02.output
tests/petsc/solver_11.cc
tests/petsc/solver_11.output
tests/petsc_complex/solver_real_01.cc
tests/petsc_complex/solver_real_01.output
tests/petsc_complex/solver_real_02.cc
tests/petsc_complex/solver_real_02.output
```

**Comment by drwells** [comment]
That's funny, it seems to work for me with 3.7.0. Let me see if I can reproduce this with an older version.

**Comment by davydden** [comment]
maybe it's some glitch on the tester for some reason. I see nothing in diffs that would make a difference.

**Comment by drwells** [comment]
I built a copy of complex-valued PETSC 3.6.4 and the test passes.

**Comment by davydden** [comment]
thanks @drwells . Must have been some glitch in the tester.
