### ISSUE TITLE
Package deal.ii-8.4.x for Debian / Ubuntu

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#2843]
Getting deal.ii-8.4.1 packaged for Debian testing/unstable:
- [x] Get all interesting build dependencies packaged for Debian: p4est [1], trilinos [2], petsc [3]
- [x] Update Debian package to 8.4.1-1, enable an interesting set of build dependencies [4]
- [x] Upload deal.ii-8.4.1 to unstable [5]
- [x] Verify deal.ii-8.4.1 package [6]

Getting deal.ii-8.4.1 into backports:
- [ ] Get all build dependencies into jessie-backports [7]
- [ ] Upload deal.ii-8.4.1 to jessie-backports

[1] https://packages.qa.debian.org/p/p4est.html
[2] https://packages.qa.debian.org/t/trilinos.html
[3] https://packages.qa.debian.org/p/petsc.html
[4] Configured features:

```
#  Configured Features (DEAL_II_ALLOW_BUNDLED = OFF, DEAL_II_ALLOW_AUTODETECTION = OFF):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#        DEAL_II_WITH_ARPACK set up with external dependencies
#        DEAL_II_WITH_BOOST set up with external dependencies
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#        DEAL_II_WITH_CXX11 = ON
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_GSL = ON
#        DEAL_II_WITH_HDF5 set up with external dependencies
#        DEAL_II_WITH_LAPACK set up with external dependencies
#      ( DEAL_II_WITH_METIS = OFF )
#        DEAL_II_WITH_MPI set up with external dependencies
#        DEAL_II_WITH_MUPARSER set up with external dependencies
#        DEAL_II_WITH_NETCDF set up with external dependencies
#        DEAL_II_WITH_OPENCASCADE set up with external dependencies
#        DEAL_II_WITH_P4EST set up with external dependencies
#        DEAL_II_WITH_PETSC set up with external dependencies
#        DEAL_II_WITH_SLEPC set up with external dependencies
#        DEAL_II_WITH_THREADS set up with external dependencies
#        DEAL_II_WITH_TRILINOS set up with external dependencies
#        DEAL_II_WITH_UMFPACK set up with external dependencies
#        DEAL_II_WITH_ZLIB set up with external dependencies
```

[5] https://packages.qa.debian.org/d/deal.ii.html
[6] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=222
[7] https://backports.debian.org/

**Comment by tamiko** [comment]
@tjhei This went way better than expected :-)

**Comment by tamiko** [comment]
https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=222
```
build_tests/step-49.release               - untitled.msh was gzipped
distributed_grids/2d_coarse_grid_01.debug - binary compressor in p4est's vtk output
distributed_grids/2d_coarse_grid_02.debug
distributed_grids/2d_coarse_grid_03.debug
distributed_grids/2d_coarse_grid_04.debug
distributed_grids/2d_coarsening_01.debug
distributed_grids/2d_coarsening_02.debug
distributed_grids/2d_refinement_01.debug
distributed_grids/2d_refinement_02.debug
distributed_grids/3d_coarse_grid_01.debug
distributed_grids/3d_coarse_grid_02.debug
distributed_grids/3d_coarse_grid_03.debug
distributed_grids/3d_coarse_grid_04.debug
distributed_grids/3d_coarse_grid_05.debug
distributed_grids/3d_coarsening_01.debug
distributed_grids/3d_coarsening_02.debug
distributed_grids/3d_refinement_01.debug
distributed_grids/3d_refinement_02.debug
distributed_grids/3d_refinement_03.debug
distributed_grids/codim_01.debug
mpi/codim_01.mpirun=3.debug
```

**Comment by tamiko** [comment]
Version 8.4.1-3 in Debian unstable: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1054

**Comment by tjhei** [comment]
very cool. Anything we can help with? All of the test failures are because you are configuring p4est with vtk compression.

**Comment by tamiko** [comment]
@tjhei Yes, but there is one tiny catch :-D

Right now, I am rerunning the testsuite of 8.4.1-3 against PETSc-3.7.3 (which just hit unstable/testing) and this doesn't look that good any more. Results in about an hour.

I will probably need a larger set of compatibility patches. At this point  am very tempted to do a point release 8.4.2 with all relevant PETSc changes.

**Comment by tamiko** [comment]
@tjhei https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1060 *mhm*

**Comment by bangerth** [comment]
These look like they're all the same problem. A backtrace will almost certainly show what the issue is. Keep the source files around...

**Comment by tamiko** [comment]
@bangerth Jup. I will blindly apply the 3 merges we had for the modified PETSc interface. As the author of said changes, @drwells can certainly help me with that :-)

**Comment by drwells** [comment]
Hm. I am surprised that it is having so much trouble with PETSc 3.7.3. In my defense that version of PETSc came out since I wrote those patches.

I'll take a look at this some time this week.

**Comment by drwells** [comment]
Quick question: the tester says PETSc 3.7.3. Is this the development or release version? If I recall correctly they give the current development version the same number as the last release version.

**Comment by tamiko** [comment]
@drwells This is the release version [1]. Current master works fine with it. It's just that we packaged 8.4.1 with a very minimalistic patchset for 3.7 in Debian [2,3,4].


[1] https://packages.qa.debian.org/p/petsc.html
[2] https://packages.qa.debian.org/d/deal.ii.html
[3] http://metadata.ftp-master.debian.org/changelogs/main/d/deal.ii/unstable_changelog
[4] https://sources.debian.net/patches/deal.ii/8.4.1-3/

**Comment by tamiko** [comment]
@drwells Thanks a lot for the PR. I have prepared 8.4.2-pre and added a couple of minor patchsets in #3043 #3045 #3046 that I would like to have in 8.4.2.

**Comment by bangerth** [comment]
@tamiko -- is this issue finished? Could it be closed?

**Comment by bangerth** [comment]
@tamiko -- ping?

**Comment by tamiko** [comment]
@bangerth  -- pong. ;-)
