### ISSUE TITLE
Websites are no longer updated

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2855]
The doxygen script appears to have stopped working. For example, the front page at https://www.dealii.org/developer/doxygen/deal.II/index.html shows an update date of July 13 both at the top and the bottom.

@guidokanschat -- as the maintainer of the website, any insight what is happening?

**Comment by bangerth** [comment]
@guidokanschat ?

**Comment by guidokanschat** [comment]
deal.II doers not configure with cmake 2.8.10 anymore. Server updated to 2.8.12 (Ubuntu 14.04 LTS).

Must have been one of the commits leading to #2822 

Shall we update the documentation?

**Comment by bangerth** [comment]
Thanks, @guidokanschat, for getting it to run again. The issue with cmake is tracked in #2902.
