### ISSUE TITLE
\VC\include\xutility(364): error C2039: 'iterator_category' : is not a member of 'dealii::IndexSet::ElementIterator'

### ISSUE THREAD

**Issue by loylick** [dealii/dealii#2870]
When compiling the file \dealii\source\multigrid\mg_tools.cc I got the error. I compared the current code with the code of 8.4.1 version to find the reason. xutility is used by VS 2013 in inner implementation of vector and set headers. the expression that causes the error is in line 1192 in mg_tools.cc:
boundary_indices[i].insert(boundary_indexset[i].begin(), boundary_indexset[i].end());
in 8.4.1 you had:
boundary_indices[i].add_indices(boundary_indexset[i].begin(), boundary_indexset[i].end());
It means that you used your own implementation of insert function.
The problem is that now you use your own iterators in standard container without deriving them from standard iterators. Realization of iterators is platform dependent so you have to declare your class
ElementIterator to inherit standard iterator which is used in vector or to continue using your own implementation add_indices. I can not see other options. I attach a complete log of this error to the post.
[ElementIterator_issue.txt](https://github.com/dealii/dealii/files/384825/ElementIterator_issue.txt)

**Comment by bangerth** [comment]
This is the error (copied from the attached file for easier reading):
```
2>  mg_tools.cc
2>C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xutility(364): error C2039: 'iterator_category' : is not a member of 'dealii::IndexSet::Elemen
tIterator'
2>          H:\DealII\source\dealii\include\deal.II/base/index_set.h(583) : see declaration of 'dealii::IndexSet::ElementIterator'
2>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xutility(649) : see reference to class template instantiation 'std::iterator_traits<
_Iter>' being compiled
2>          with
2>          [
2>              _Iter=dealii::IndexSet::ElementIterator
2>          ]
2>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\set(177) : see reference to function template instantiation 'void std::_Debug_range<
_Iter>(_InIt,_InIt,std::_Dbfile_t,std::_Dbline_t)' being compiled
2>          with
2>          [
2>              _Iter=dealii::IndexSet::ElementIterator,
2>              _InIt=dealii::IndexSet::ElementIterator
2>          ]
2>          H:\DealII\source\dealii\source\multigrid\mg_tools.cc(1193) : see reference to function template instantiation 'void std::set<_Kty>::insert<dealii::
IndexSet::ElementIterator>(_Iter,_Iter)' being compiled
2>          with
2>          [
2>              _Kty=unsigned int,
2>              _Iter=dealii::IndexSet::ElementIterator
2>          ]
2>          H:\DealII\source\dealii\source\multigrid\mg_tools.cc(1193) : see reference to function template instantiation 'void std::set<_Kty>::insert<dealii::
IndexSet::ElementIterator>(_Iter,_Iter)' being compiled
2>          with
2>          [
2>              _Kty=unsigned int,
2>              _Iter=dealii::IndexSet::ElementIterator
2>          ]
2>          H:\DealII\source\dealii\build\source\multigrid\mg_tools.inst(1761) : see reference to function template instantiation 'void dealii::MGTools::make_b
oundary_list<2,2>(const dealii::DoFHandler<dim> &,const std::map<_Kty,_Ty> &,std::vector<std::set<unsigned int>> &,const dealii::ComponentMask &)' being compil
ed
2>          with
2>          [
2>              dim=2,
2>              _Kty=dealii::types::boundary_id,
2>              _Ty=const dealii::Function<2,double> *
2>          ]
2>C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xutility(364): error C2146: syntax error : missing ';' before identifier 'iterator_category'
2>C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xutility(364): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

**Comment by bangerth** [comment]
Quite interesting! This might be the first time where I'd say that Visual Studio actually uncovers something of interest.

Patch forthcoming.

**Comment by bangerth** [comment]
Should be fixed by #2872. Once merged, I'd appreciate if you could try and see whether that solves the problem. Many thanks for already doing all of the leg work in figuring out what is going on -- this was clearly one of the more obscure cases...

**Comment by loylick** [comment]
Apparently you've fixed it. mg_tools.cc compiled clearly.

**Comment by bangerth** [comment]
Excellent. Thanks for verifying!

Thanks, by the way, for working through all of these issues with us. It's much appreciated!

**Comment by tamiko** [comment]
I absolutely love this remote compatibility fixing :-D

@bangerth I will give compilation under the newest Visual Studio another
try sometime later next week.

**Comment by bangerth** [comment]
I sorta enjoy this too. It makes me think about what other compilers are doing.

**Comment by bangerth** [comment]
In relation to #2397
