### ISSUE TITLE
Remove usage of features deprecated in C++11/C++14

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2882]
In no particular order, here are the deprecated functions that we use, or show up in documentation:

- [x] `bind2nd`
- [x] `mem_fun`
- [x] `mem_fun_1`
- [x] `ptr_fun`
- [x] `random_shuffle`

~~- `uncaught_exception`~~ (this is C++17 so we should skip it)
- [x] `unary_function`

In addition, we use some deprecated library features:
- [ ] `Subscriptor`'s destructor can throw exceptions. Since destructors (as of C++11) are now `noexcept(true)` by default this destructor needs to be marked as `noexcept(false)`; see https://stackoverflow.com/questions/16540725/c11-exceptions-destructor-allows-to-throw-now/16540757
- [x] Similarly, exception specifications (e.g., `virtual ~ExceptionBase () throw();`) are also deprecated: see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3051.html

There are some more things, like `std::iterator`, that have been deprecated in C++17, but that is such a low priority item that I don't think it is worth thinking about yet.

Update: cross out `std::uncaught_exception`

**Comment by bangerth** [comment]
`bind2nd`, `mem_fun{,_1}`, `ptr_fun`, `unary_function` are all easily replaceable by `std::bind`. What is the recommended replacement for `random_shuffle`?

About `~Subscriptor`: This destructor only throws if something goes terribly wrong. In reality, the usual path is that it calls `abort` via `Assert`, and an exception is only thrown if one calls `deal_II_exceptions::disable_abort_on_assert` or whatever this function is called. I wouldn't worry about it.

Exception specifications: Yes, we can get rid of those. They never led to any kind of improvements, so there is no point in keeping them.

**Comment by drwells** [comment]
I believe the recommended replacement for `std::random_shuffle` is `std::shuffle`, which has, as an argument, something from the new `<random>` header.

**Comment by bangerth** [comment]
I gave it a try eliminating the `throw()` exception specifications in all places, but this is not so trivial: we get lots of errors of the form
```
dealii/include/deal.II/base/exceptions.h:75:23: error: looser throw specifier for ‘virtual const char* dealii::ExceptionBase::what() const’
/usr/include/c++/4.6/exception:69:25: error:   overriding ‘virtual const char* std::exception::what() const throw ()’
```
We will have to make this conditional on compilers ignoring exception specifications. Maybe better, we should introduce a macro `DEAL_II_NOEXCEPT` that either expands to `throw()` or `noexcept`, depending on what the compiler understands.

**Comment by class4kayaker** [comment]
I currently cannot find any references to unary_function in any of source, include, examples, or tests as of the current master 6c837bb.

**Comment by class4kayaker** [comment]
Doing a search on uncaught_exception, my understanding is that it was deprecated in C++17 for a new function. As such, if I understand the intended scope of this issue correctly, modification to match the new behavior is not within that scope.

If it does need to be dealt with, the only use of it that I can find is in the Subscriptor::check_no_subscribers method.

**Comment by drwells** [comment]
@class4kayaker I believe the only place `unary_function` showed up was in a comment. I got rid of that and `binary_function` a few weeks ago.

All this Subscriptor stuff is tricky; I will have to think some more about the right way to do it. I thought the replacement function was in C++11 (not 17) so it isn't a big priority to update that anyway.

Thanks for filling in the checkboxes :)

**Comment by bangerth** [comment]
@drwells -- do you have a link about what one should use instead of `uncaught_exception`?

**Comment by drwells** [comment]
There is a very good discussion available at

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4152.pdf

The TLDR is 'use `std::uncaught_exceptions` which returns an `int` instead of a `bool`, but as @class4kayaker mentioned the deprecation and `std::uncaught_exceptions` are C++17 features (for some reason I thought it was C++11) so we should skip this for now.

**Comment by bangerth** [comment]
@drwells -- I think we've covered it all. I would ignore the issue with `~Subscriptor`. Should we close it?

**Comment by drwells** [comment]
Hm, probably. I want to see if I can do that with `noexcept(false)` (mainly for my own curiousity) before closing this.

**Comment by drwells** [comment]
Doing the right thing with `Subscriptor` requires changing the destructor of everything that inherits from it (so this will break any user code that uses `Subscriptor`). Since the compilers all currently allow for us to ignore the standard here I think that we should leave this for another time (so I agree).
