### ISSUE TITLE
Junk parallel output from TrilinosWrappers::SparsityPattern?

### ISSUE THREAD

**Issue by spco** [dealii/dealii#2887]
@tjhei @kronbichler _ping_
Attached_ is a modification of the new dof_tools_22a test introduced in #2846. It generates a sparsity pattern and then prints it in `gnuplot` format.
[dof_tools_22a_mod.txt](https://github.com/dealii/dealii/files/391761/dof_tools_22a_mod.txt) 

If run with the commented DynamicSparsityPattern section then you get the following output from the 1-processor and 5-processor runs:
![1](https://cloud.githubusercontent.com/assets/11610738/17268925/caa42bd2-5631-11e6-8b2d-941c839f0d06.png)
![5](https://cloud.githubusercontent.com/assets/11610738/17268927/cd1743fe-5631-11e6-9098-77944a63b04c.png)
which looks reasonable - just a little swapping of the order of blocks.

If run with the TrilinosWrappers::SparsityPattern code, then in parallel you end up getting junk in some entries, and repeated entries (it's not clear to me whether the repeats are just junk as well). See https://github.com/dealii/dealii/pull/2846#issuecomment-236142024 and following comments for a sample of the output and an indication from `valgrind`.

Typical outputs for 1 process and 5 processes in gnuplot look like:
![1](https://cloud.githubusercontent.com/assets/11610738/17268974/6f07c1c4-5633-11e6-8f58-39a5a40b81e1.png) (good)
![5](https://cloud.githubusercontent.com/assets/11610738/17268975/7349a248-5633-11e6-894f-fc7a55d9f564.png)
(bad)

**Comment by spco** [comment]
Ok, so attached is a MWE, which outputs both `print` and `print gnuplot`, which both show this behaviour.
[dof_tools_22a_mod2.txt](https://github.com/dealii/dealii/files/391886/dof_tools_22a_mod2.txt)
For easy viewing here it is:
```
#include "../tests.h"
#include <deal.II/base/logstream.h>
#include <deal.II/base/point.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/fe/fe_system.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/lac/trilinos_sparsity_pattern.h>

void test ()
{
  const int dim = 2;
  //setup system
  dealii::parallel::distributed::Triangulation<dim> triangulation(MPI_COMM_WORLD);

  GridGenerator::hyper_rectangle (triangulation,
                                  Point<dim>(0,0),
                                  Point<dim>(1,1),
                                  true);

  triangulation.refine_global(2);

  const FE_Q<dim> fe_system(1);
  DoFHandler<dim> dh (triangulation);
  dh.distribute_dofs (fe_system);

  IndexSet relevant_partitioning (dh.n_dofs());
  DoFTools::extract_locally_relevant_dofs (dh, relevant_partitioning);

  //generate empty constraints
  ConstraintMatrix constraints;

  //generate sparsity pattern
  TrilinosWrappers::SparsityPattern sp (dh.locally_owned_dofs(),
                                        dh.locally_owned_dofs(),
                                        relevant_partitioning,
                                        MPI_COMM_WORLD);

  DoFTools::make_sparsity_pattern (dh, sp,
                                   constraints,true,
                                   Utilities::MPI::this_mpi_process(MPI_COMM_WORLD));
  sp.compress();

  //output
  sp.print_gnuplot(deallog.get_file_stream());
  sp.print(deallog.get_file_stream());
}

int main(int argc, char **argv)
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization (argc, argv, testing_max_num_threads());
  MPILogInitAll log;

  test();
  deallog.pop();
}
```
Square mesh, only global refinement, single `FE`, empty constraints, and just `DoFTools::make_sparsity_pattern().`

The `valgrind` for this code is attached: 
[valgrind_trace.txt](https://github.com/dealii/dealii/files/391891/valgrind_trace.txt)

`compress()` seems unhappy calling `Epetra_CrsGraph::OptimizeStorage()`. I think this is beyond my sphere of knowledge!

**Comment by kronbichler** [comment]
@spco Thanks for the test case and the valgrind output. This is indeed a bug in the print functions of `TrilinosWrappers::SparsityPattern`. The `OptimizeStorage` method seems to work just fine, it just happens to be the place where the memory has been allocated. There are several things in these two functions that are wrong. This function has definitely not been written for the parallel case. Actually, it doesn't even work for rectangular matrices where the number of entries per row is larger than the number of rows... Are you interested in preparing a patch (and some tests)? Instead of
```
indices[global_row_index(*graph,static_cast<int>(j))]
``` 
one would need to use
```
indices[j]
```
But then it is still not correct. The second step would be to convert the indices from MPI-local space (which is what gave the weird picture in your case) to global index space, both at the place where `i` and `indices[j]` are output, by `graph->RowMap().GID(i)` and `graph->ColMap().GID(indices[j])`. Finally, to make this safe for 64 bit indices one would need to wrap a call to the global index in a function similar to `global_row_index` (one does not need that function any more I believe).

**Comment by kronbichler** [comment]
> There are several things in these two functions that are wrong. 

Here I mean the `print()` and `print_gnuplot()` functions for the Trilinos sparsity pattern.

**Comment by spco** [comment]
Thanks @kronbichler - at least I'm not going mad!

Realistically I'm not going to be able to look at this until November (I have a thesis to write!) so if anybody else wants to fix this before then, please be my guest!

**Comment by kronbichler** [comment]
@spco I've created a patch myself now, given that the changes are relatively modest. Thanks for digging this up and for the excellent test case.

**Comment by spco** [comment]
Fantastic, thanks! And my pleasure :) I'm all for learning new corners of the library, but not right now!

**Comment by kronbichler** [comment]
You're welcome! And good luck with your thesis!

**Comment by bangerth** [comment]
@kronbichler -- thanks for taking this off @spco 's hands, because I will actually have to evaluate that PhD thesis he's writing ;-) ;-)
