### ISSUE TITLE
Improve performance of ChartManifold::get_new_point

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#2896]
When working on a spherical geometry (I attached a `SphericalManifold` to a hyper_shell), I realized that computing the mapping support points takes almost half the computation time of one of my programs when using polynomial degree 5 for the mapping and 4 for the solution (this is 2D for simpler analysis, I have the same problem in 3D). I ran the program through my favorite profiler callgrind (well, the one with way best visualization of problematic regions):
![mapping_manifold_callgrind](https://cloud.githubusercontent.com/assets/8276200/17278232/7e18d24a-5758-11e6-9317-f69985bb28b1.png)
While there is probably little to complain about the `atan2`, `sin_avx` and `cos_avx` calls as that describes the geometry, I am concerned about the other half which consists of `malloc` and `free` calls that appear to be the main problem on my cluster (28 cores sharing memory). The reason for that is that we repeatedly create and destroy `Quadrature` objects in this function. The two places in question are `mapping_q_generic.cc:3514` (the above picture comes from here) and `manifold.cc:538` where a new quadrature formula is created for **every point** we compute. We really need find a better style for passing this information around. We can't have that many memory allocation in a function that is in the critical path of all programs that regularly reinit FEValues objects in every step/nonlinear iteration.

I can work on this, but I would like to hear the opinions of @luca-heltai and others before I start. My idea is to either teach `Quadrature` having modifiable weights and points that can be somehow re-used during the course of an evaluation or to have other means to pass information around. Any other suggestion is highly welcome.

**Comment by kronbichler** [comment]
Just some more numbers to show how drastic this issue is: On 28 cores, it takes me 266 s to assemble a linear system with 75m equations whereas solving it only takes 25 s with a matrix-based solver or 4.8 s with a matrix-free solver. The main contribution to the assembly time is a completely irregular part that sometimes takes 5 times more times than otherwise (the memory allocations of 28 cores frequently fighting for a lock I suppose). Without the MappingQ I can get the assembly times to around 30s.

**Comment by bangerth** [comment]
Are the objects we create always the same? We could use thread-local scratch variables as members of the class.

**Comment by kronbichler** [comment]
I guess not the same quadrature object as a whole: Either the weights or the points will be modified, some are the result of a `pull_back` operation, so I assume at least some data fields need to change.

**Comment by bangerth** [comment]
Hm, that's bad. It ultimately all gets converted into calls to the function that does a pairwise reduction. Maybe we ought to provide other venues to get to this function with data types that don't require dynamic memory allocation...

**Comment by luca-heltai** [comment]
Ouch. I had no idea that this would impact performance so much. We could probably do something similar to what we do in Mapping, but this complicates the design quite a lot. Maybe a different option would be to provide also functions of the type

~~~
get_new_point(object, point_in_reference_coordinates);
get_new_points(object, vector_of_points_in_reference_coordinates);
~~~

when a new point on the object is needed, we also always know the point in the reference coordinate system. What we do now is to construct a quadrature for each reference point, and call get_new_point with that quadrature. If we had the two functions above as entry points for internal dealii calls, then Manifold could use always the same quadrature object (maybe doing some casting magic to modify the weights) instead of letting it to the caller to construct quadratures...

**Comment by luca-heltai** [comment]
As an alternative, we could simply pass around two standard vectors (points and weights), and make sure that the same are used anywhere this is required instead of building and destroying quadrature objects all the times...

**Comment by luca-heltai** [comment]
I see two options:

- [ ] add additional function calls with objects and reference points, and make the quadrature constructed internally in Manifold
- [ ]  add `get_new_point` with two standard vectors of points and weights, and deprecate the one with the quadrature (or remove it entirely. It has always been somewhat "internal"), making sure that in the library we always call the new version with the same vector of points and weights, to avoid reallocation

any other suggestion?

**Comment by kronbichler** [comment]
I like the second option of changing the `get_new_point` method most. It provides the data structures and interface we need to work with (wasn't `Quadrature` just a vehicle for passing this information, it is not actually doing integration in there anyway?) and allows us to pass the data structures needed for evaluation around and modify them as appropriate. We could then allocate a vector once in the get_intermediate_points() methods which would be a vast improvement already. At that stage, we do some allocations anyway and I don't think it's critical any more if we cut allocations by a factor of 20-50 for degree around 3 and 4.

So the code in `ChartManifold::get_new_point` would then simply overwrite the input array `points` with the result of `pull_back` and send that array on to the `sub_manifold`, wouldn't it? It would make the points or weights arrays an in/out array, but for me that's fine. As you say, this is kind of an internal interface for us to evaluate the geometries, so I think it's important to allow for a simple design that does what we want rather than finding the optimal interface in terms of intuition. But we could have three arguments as well if someone prefers that.

**Comment by luca-heltai** [comment]
> So the code in ChartManifold::get_new_point would then simply overwrite the input array points with the result of pull_back and send that array on to the sub_manifold, wouldn't it? It would make the points or weights arrays an in/out array, but for me that's fine. As you say, this is kind of an internal interface for us to evaluate the geometries, so I think it's important to allow for a simple design that does what we want rather than finding the optimal interface in terms of intuition. But we could have three arguments as well if someone prefers that.

This is not entirely correct. `ChartManifold` needs internally a std::vector of points with different dimensions. It cannot overwrite the other points. But that one can be created once, and resized if necessary (a much cheaper operation than creating and destroying one every time).

**Comment by kronbichler** [comment]
Indeed, you're right, I confused `spacedim` and `chartdim`, must be because they are the same number of characters ;-).
If it keeps an internal variable, we need a `ThreadLocalStorage` of such a vector I assume, as @bangerth suggested. We can have multiple threads accessing the same manifold object, so every thread needs to be able to get its own scratch array. @bangerth do we have an abstraction for the list of objects we describe in the workstream paper? To be sure, we need to toggle a list until we find an unused vector because inside the `sub_manifold.get_new_point` method there might be other threaded calls, who knows...

**Comment by kronbichler** [comment]
@luca-heltai I have prepared a minimal patch that does what I want (I can extend this to a PR tomorrow). However, we still waste some operations (the `pull_back` operations) because we query a single point in `get_intermediate_points` in the `mapping_q_generic.cc` file. Would you see a problem to move the whole part to the manifold, so the chart manifold can do the pull back only once? I see the potential problem that this would lead to some code duplication, though, unless we can express the `get_intermediate_points` method in a more compact way.

**Comment by luca-heltai** [comment]
I wouldn't know how to avoid code duplication... can you point me to the patch and show what problems you foresee?

**Comment by kronbichler** [comment]
I will as soon as I have it online. It needs some more TLC.

**Comment by luca-heltai** [comment]
(Y)

**Comment by bangerth** [comment]
> suggested. We can have multiple threads accessing the same manifold object, so
> every thread needs to be able to get its own scratch array. @bangerth
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bangerth&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=KkOrCga5IcWjxrpeTIn1nmQG6jJSnwzdZwfNniMeeCc&m=jEMMsvK2JH8hsI1P5Vid1fndxM3cXRCtnEDWiKPdd-U&s=Q9ToTEsAHS6-gyC3r491WkMJVK_EpbU_euIR1T1ovWc&e=>
> do we have an abstraction for the list of objects we describe in the
> workstream paper?

No, unfortunately not. It has occurred to me on another occasion that this 
thread-local list of objects is in itself a design pattern that we should 
probably encode in a class of its own.

**Comment by bangerth** [comment]
@kronbichler -- is this fixed with the PRs that have been merged recently?

**Comment by kronbichler** [comment]
I just checked and it appears that we do much better now. There are still a few memory allocations that happen inside the `get_intermediate_points` and `get_intermediate_points_on_object` methods in `MappingQGeneric` but those are a bit more difficult to change. We would need to change the signature of
```
Manifold::get_new_point(const std::vector<Point<spacedim> > &,
                        const std::vector<double> &) const;
```
to
```
Manifold::get_new_point(const unsigned int n_points,
                        const Point<spacedim> *,
                        const double *) const;
```
i.e., we pass pointers and a length, or provide both functions. With the latter, we can use the fast method for those manifolds we are about and otherwise let the user do the basic methods. But I fear it will make the interface a bit more complicated because users need to think about two methods and not just one. If we only provide one entry point, a user might need to work with plain pointers and an array size which is potentially less safe. Yet, it would really make sense to avoid the allocations because we know the size at the caller's site, `GeometryInfo<some_dim>::vertices_per_cell`.
Anyway, it appears that the cost of the memory allocations inside `FEValues::reinit` has already been reduced from around 15% of run time to around 1% on my examples thanks to the work by @gassmoeller . I've not run the big problem yet to see whether the erratic behavior is still there but I suppose it is fine now.

**Comment by bangerth** [comment]
What's the current status of this issue? Do you see a need for more work in this area?

**Comment by kronbichler** [comment]
I checked on my cluster where I made the initial observations back in July and the code is much better now. Assembly with optimized data structures is between three and 10 times faster. (Even though this only affected the `FEValues::reinit` and not the actual integral computations in assembly, but the memory allocations apparently hurt that much.) Yay!
