### ISSUE TITLE
cmake 2.8.10:  Cannot compile with the user supplied flags

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2902]
cmake 2.8.10 seems to be unable to configure starting around #2822 : 

```
CMake Error at cmake/setup_compiler_flags.cmake:83 (MESSAGE):
  

    Configuration error: Cannot compile with the user supplied flags:
      CXX flags (DEBUG):  
      LD flags  (DEBUG):  
      LIBRARIES (DEBUG): ;
    Please check the CMake variables
      DEAL_II_CXX_FLAGS, DEAL_II_CXX_FLAGS_DEBUG,
      DEAL_II_LINKER_FLAGS, DEAL_II_CXX_FLAGS_DEBUG
    and the environment variables CXXFLAGS, LDFLAGS.

  

Call Stack (most recent call first):
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:95 (VERBOSE_INCLUDE)
```

**Comment by tjhei** [comment]
Works correctly with 2.8.12 or newer.

@tamiko ?

**Comment by tamiko** [comment]
@tjhei 2.8.12.2 is the oldest version I have conveniently available (via my distribution package  manager). I will try to install 2.8.8 and fix this.

**Comment by tjhei** [comment]
I am happy with incrementing the minimum version to 2.8.12.

**Comment by tamiko** [comment]
@tjhei I suggest we do one more release with 2.8.8 and increase afterwards.

**Comment by oneliefleft** [comment]
I am confused. Is this a deal.II problem? a CMake problem? an Ubuntu
problem?
Did I miss something?

2016-08-01 21:22 GMT+02:00 Matthias Maier <notifications@github.com>:

**Comment by tamiko** [comment]
@oneliefleft This was a deal.II problem: We did not correctly work around a bug in cmake version 2.8.10 or older. This is fixed now.

The question whether we increase the minimal required version is solely for our convenience.
