### ISSUE TITLE
Write function that extracts the locally owned index set

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2904]
#2894 introduces this piece of code in step-17:

```
std::vector<IndexSet> locally_owned_dofs_per_proc = DoFTools::locally_owned_dofs_per_subdomain(dof_handler);
IndexSet locally_owned_dofs = locally_owned_dofs_per_proc[this_mpi_process];
```

This seems wasteful because it requires computing the index sets of _all_ processors when we really only care about the one for the _current_ processor.

@tjhei writes in the corresponding comment to #2894:

```
dof_handler.locally_owned_dofs and DoFTools::extract_locally_owned_dofs return the whole IndexSet 
and DoFTools::dof_indices_with_subdomain_association returns the locally active, not the locally owned
unknowns.
```

This stumped me for a while but it is correct because step-17 uses just a plain old `Triangulation` object that doesn't know anything about partitioning. Correspondingly, the DoFHandler thinks it owns all DoFs. It is only later on that we manually set subdomain ids and split the matrix. 

We could address this either by adding a function like `DoFTools::extract_dofs_for_subdomain()`. Or, maybe, we should just convert step-17 to use `parallel::shared::Triangulation` like was done with step-18.  This would deprecate the approach taken currently, which I think we don't want to advertise anyway.

**Comment by jppelteret** [comment]
A comment on your last paragraph: Since `parallel::shared::Triangulation` and `parallel::distributed::Triangulation` don't yet support `hp::DoFHandler`'s, isn't it worth keeping at least one tutorial that uses manual partitioning in case someone wants to implement `hp` in parallel?

**Comment by bangerth** [comment]
Yes, that's fair. (Though it's the other way around: `hp::DoFHandler` doesn't support `parallel::*::Triangulation`.)

**Comment by jppelteret** [comment]
I'm always tripping up on the minor details ;-)

**Comment by bangerth** [comment]
But you made the big point and it was correct :-) Someone really needs to get going on equipping `hp::DoFHandler` to support parallel triangulations...

**Comment by jppelteret** [comment]
That would be awesome. I wish I could offer some man-hours to look at this, but its impossible this year.

**Comment by drwells** [comment]
We have long since fixed this - in particular, the original code path has been deprecated.
