### ISSUE TITLE
Linking error of python bindings with clang on macOS

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2915]
subj.:

```
[ 98%] Linking CXX shared module ../../../lib/python2.7/site-packages/PyDealII/Release.so
clang: error: invalid argument '-compatibility_version 8.5.0' only allowed with '-dynamiclib'
```

Looking at https://github.com/dealii/dealii/pull/2834 i don't see any flaws with CMake part, but there must be one.

**Comment by tamiko** [comment]
> ```
> [ 98%] Linking CXX shared module ../../../lib/python2.7/site-packages/PyDealII/Release.so
> clang: error: invalid argument '-compatibility_version 8.5.0' only allowed with '-dynamiclib'
> ```
>
> Looking at https://github.com/dealii/dealii/pull/2834 i don't see any flaws with CMake part, but there must be one.

In contrib/python-bindings/source/CMakeLists.txt can you try to remove
first the VERSION property, then the SOVERSION property (and finally
both)?

**Comment by davydden** [comment]
@tamiko 
> can you try to remove first the VERSION property

did not help

> then the SOVERSION property

did not help

> (and finally both)?

works!

Do you want me to create a PR with this change?

**Comment by davydden** [comment]
@tamiko there is another issue, it build `.so` file irrespectively of the platform
```
[ 98%] Linking CXX shared module ../../../lib/python2.7/site-packages/PyDealII/Debug.so
[100%] Linking CXX shared module ../../../lib/python2.7/site-packages/PyDealII/Release.so
```

**Comment by Rombur** [comment]
@davydden What is the problem? It should be building ```.so``` files.

**Comment by davydden** [comment]
> What is the problem? It should be building .so files.

i would expect `.dylib` on macOS.

**Comment by Rombur** [comment]
@davydden apparently it's normal that it creates a ```.so``` even on mac. I have asked someone who uses boost python on mac.

**Comment by Rombur** [comment]
A little bit old but python module have to be ```.so``` not ```.dylib``` http://stackoverflow.com/questions/2488016/how-to-make-python-load-dylib-on-osx

**Comment by davydden** [comment]
@Rombur i see, interesting, did not know about it. Thanks for clarifying.

**Comment by tamiko** [comment]
@davydden Thanks for verifying that this was indeed the problem.
