### ISSUE TITLE
Replace pointer members of Triangulation by std_cxx11::unique_ptrs

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2934]
As seen in #2769 (or as could of course also be discovered by looking at `include/deal.II/grid/tria.h` :-) ), class `Triangulation` has a number of raw pointer members (including, but possibly not exclusively, `levels`, `faces`, `vertex_to_boundary_id_map_1d`, `vertex_to_manifold_id_map_1d`). This is really an anachronism -- rather than managing this data ourselves, we should just be using `std_cxx11::unique_ptr` for all of these.

This might require small adjustments to the move constructor of #2769, but should generally make code simpler.

**Comment by tjhei** [comment]
I would prefer we use ``std::vector`` over ``new``/``delete``, even when using something like ``unique_ptr``.

**Comment by bangerth** [comment]
For reference, the objects I have in mind are these:
```
 std::vector<dealii::internal::Triangulation::TriaLevel<dim>*> levels;
 dealii::internal::Triangulation::TriaFaces<dim> *faces;
 std::map<unsigned int, types::boundary_id> *vertex_to_boundary_id_map_1d;
 std::map<unsigned int, types::manifold_id> *vertex_to_manifold_id_map_1d;
```
The first of these should become a vector of `unique_ptr`s. The others should just be a `unique_ptr`.

**Comment by drwells** [comment]
For what its worth we cannot currently do a vector of `std_cxx11::unique_ptr`s in C++98 mode (since we are really using `scoped_ptr`, which cannot be copied), so we can't finish this until we require C++11.

**Comment by bangerth** [comment]
Oh, bummer :-(

**Comment by danshapero** [comment]
You can assign this to me for whenever C++11 is required.

**Comment by bangerth** [comment]
@danshapero -- github only lets me assign issues to people with merge privilege :-( But I'll ping you once we're there.

**Comment by bangerth** [comment]
So this turns out to be a bit more complicated than thought. If I replace the pointer for `faces` by a `std_cxx11::unique_ptr`, I get this error:
```
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/access.hpp: In static member function ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > >]’:
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/serialization.hpp:69:5:   instantiated from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/serialization.hpp:128:9:   instantiated from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/archive/detail/iserializer.hpp:184:5:   instantiated from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/tests/serialization/triangulation_01.cc:178:1:   instantiated from here
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/access.hpp:118:9: error: ‘class std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > >’ has no member named ‘serialize’
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/access.hpp: In static member function ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<2>, std::default_delete<dealii::internal::Triangulation::TriaFaces<2> > >]’:
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/serialization.hpp:69:5:   instantiated from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<2>, std::default_delete<dealii::internal::Triangulation::TriaFaces<2> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/serialization.hpp:128:9:   instantiated from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<2>, std::default_delete<dealii::internal::Triangulation::TriaFaces<2> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/archive/detail/iserializer.hpp:184:5:   instantiated from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::text_iarchive, T = std::unique_ptr<dealii::internal::Triangulation::TriaFaces<2>, std::default_delete<dealii::internal::Triangulation::TriaFaces<2> > >]’
2994: /u/bangerth/p/deal.II/2/dealii/tests/serialization/triangulation_01.cc:178:1:   instantiated from here
2994: /u/bangerth/p/deal.II/2/dealii/bundled/boost-1.56.0/include/boost/serialization/access.hpp:118:9: error: ‘class std::unique_ptr<dealii::internal::Triangulation::TriaFaces<2>, std::default_delete<dealii::internal::Triangulation::TriaFaces<2> > >’ has no member named ‘serialize’
```
So this appears to mean that boost 1.56 doesn't know how to serialize `std::unique_ptr`.

What to do?

**Comment by bangerth** [comment]
Ah, on second thought: one just has to `#include` the correct header file...

**Comment by bangerth** [comment]
Most of this is fixed in #2945. The `levels` vector of pointers is left out for now and needs to be fixed once we use C++11.

**Comment by drwells** [comment]
@danshapero you volunteered for this last year. Are you still interested?

**Comment by danshapero** [comment]
@drwells Yes, now that I'm done with my thesis I can get back to important things :)

**Comment by danshapero** [comment]
Update: I have almost everything working in [this branch](https://github.com/danshapero/dealii/tree/tria-unique-ptrs), except the tests for serialization fail. The expected output will require some modification because boost serializes unique pointers differently from raw pointers. I can read about the difference myself, but if someone is already familiar with it, I'd appreciate any suggestions.

**Comment by bangerth** [comment]
The serialization tests actually do an internal comparison to ensure that the restored object equals the original one. So unless a test aborts, everything should be ok. I would just update the output files and not worry too much about this.

**Comment by bangerth** [comment]
@danshapero -- I looked at your diffs and they look reasonable. You have a couple of places where you do
```
-        triangulation.levels.push_back (new internal::Triangulation::TriaLevel<dim>);
+        std::unique_ptr<internal::Triangulation::TriaLevel<dim>> level =
+          std_cxx14::make_unique<internal::Triangulation::TriaLevel<dim>> ();
+        triangulation.levels.push_back (std::move(level));
```
but I think this can be done more easily by just calling `make_unique` in the argument list of `push_back`, like you do elsewhere, without creating another local variable.

We've used `emplace_back` instead of `push_back` since the switch to C++11, but I really don't think it makes a difference here, given that this is such a rarely executed operation.
