### ISSUE TITLE
Let GridGenerator functions *return* triangulations, rather than adjusting the one given as an argument

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2935]
With the merge of #2769 that introduced move constructors for class `Triangulation`, we can think about letting the functions in namespace `GridGenerator` actually _return_ the triangulation it creates, rather than use a reference argument. This may be more in the style of modern C++11 and it should be relatively simple to write wrappers for backward compatibility.

To make this work in practice, we may also need move assignment operators, however.

**Comment by bangerth** [comment]
This will require switching to C++11 first, however. See #1519.

**Comment by danshapero** [comment]
I think this can be written before the complete switch to C++11. You could do something like this:

    #ifdef DEAL_II_WITH_CXX11
    Triangulation<dim> hyper_rectangle(const Point<dim>& x0, const Point<dim>& x1)
    {
      Triangulation<dim> tria;
      hyper_rectangle(tria, x0, x1);
      return tria;
    }
    #endif

which just uses the old-style function that takes a reference. Overload resolution can distinguish between the old-style grid generator functions and the new-style ones that use move semantics since they take a different number of arguments.

**Comment by bangerth** [comment]
Yes, that would work. We can't use these new functions yet, though, so there is limited benefit for now. It will also require additional work once we remove the old functions, since we will have to copy function bodies. On the other hand, if we only implement the new functions one we use C++11, we can make the deprecated function call the new function,  and removal of deprecated functions only requires removing whole functions. 

So it may be worth waiting with this. We will also still need move assignment operators first

**Comment by bangerth** [comment]
#4358 uncovered some difficulties that makes this awkward to make work. Let's not worry about it.
