### ISSUE TITLE
Can not build tests under Visual Studio 2013

### ISSUE THREAD

**Issue by loylick** [dealii/dealii#2947]
When building tests I get some errors kind of: 'cat' is not recognized as an internal or external command, 'touch' is not recognized as an internal or external command. I guess it is because of linux shell commands in the config files. I wonder if I can specify somewhere a different shell to use instead of cmd.exe going by default under Windows. I have a bash shell which has all those commands "cat","touch" etc.

Alex

**Comment by loylick** [comment]
Strange that nobody proposed a simple workaround that I found later on in PETS documentation.  
Here is the citation from it:
"Microsoft Windows OS does not provide the same unix shell enviornment as the other OSes. Also the default MS/Intel/Compaq compilers behave differently than other unix compilers. So to install PETSc on Microsoft Windows - one has to install cygwin [for the unix enviornment].
 Setup cygwin terminal/bash-shell with Working Compilers: We require the compilers to be setup properly in a cygwin bash command shell, so that "cl foo.c" or "ifort foo.f" works from this shell. For example - if using VS2005 C and Intel 10 Fortran one can do:

    Start -> Programs -> Microsoft Visual Studio 2012 -> Visual Studio Tools -> Open VS2012 x64 Native Toos Command Prompt [32bit or 64bit depending on your usage]. This should start a 'dos cmd' shell.
    Within this shell - run cygwin terminal/bash-shell mintty.exe as: c:\cygwin\bin\mintty.exe
    verify if the compilers are useable [by running cl, ifort in this cygwin terminal/bash-shell]."

This approach resolves the issue of not working commands like "cat", "touch" etc. in cmake scripts.

**Comment by bangerth** [comment]
@loylick -- cygwin works, but it's not the right solution. Programs compiled on cygwin can not be executed on machines that don't have cygwin installed (because they are not really windows programs), and you can't link a cygwin-compiled library against Windows programs. In other words, cygwin is (and always has been) a workaround, but not a native solution. We would really like to have a native solution.

The better approach would be to use the Visual Studio environment and use the Intel C++ compiler (which we know is pretty good as far as C++ compliance is concerned). I don't think we ever tried that, but it would be the easiest way to generate native libraries.

**Comment by tamiko** [comment]
> @loylick -- cygwin works, but it's not the right solution. Programs
> compiled on cygwin can not be executed on machines that don't have
> cygwin installed (because they are not really windows programs), and
> you can't link a cygwin-compiled library against Windows programs. In
> other words, cygwin is (and always has been) a workaround, but not a
> native solution. We would really like to have a native solution.

@loylick s comment was about using a cygwin/mingw environment to provide
the unix tools in order to run the testsuite - not about using the
compiler toolchain.


@loylick Yes, this is how you have to run the testsuite at the moment
(and how we tested basic functionality).

**Comment by loylick** [comment]
Yes, I used cygwin just as an environment providing unix shell commands like "cat", "touch", "rm" etc..

**Comment by drwells** [comment]
This is tracked in #1921.
