### ISSUE TITLE
Test failures after #2967

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#2970]
A lot of other tests rely on the `testmatrix.h` header, which got moved; they now don't work.

I'll have a patch in a few minutes.

**Comment by tjhei** [comment]
sorry, I thought I found all places, but you are right.

``sed -i 's#lac/testmatrix.h#testmatrix.h#' */*cc`` ?

**Comment by drwells** [comment]
Yup. I am rerunning the test suite to make sure I didn't miss anything else. All of the tests are compiled so I should have this done in a few more minutes.

**Comment by bangerth** [comment]
Fixed by #2971.
