### ISSUE TITLE
unique_ptr.hpp not found

### ISSUE THREAD

**Issue by appiazzolla** [dealii/dealii#2973]
File deal.II/grid/tria.h calls for boost/serialization/unique_ptr.hpp ifdef DEAL_II_WITH_CXX11
but boost/serialization/unique_ptr.hpp exists from boost v1.56

Either dealii/cmake/modules/FindBOOST.cmake has to check for minimum version 1.56 instead of 1.54 or deal.II/grid/tria.h should use something else (e.g. boost/interprocess/smart_ptr/unique_ptr.hpp if compatible)

Commit is 3984025e36ed2b1bb2e533807b6c9f59c87ce338 from @bangerth

**Comment by bangerth** [comment]
This refers to a comment by @appiazzolla on what was merged through #2945. Apparently we can't use the BOOST 1.54 serialization facilities for C++11 `unique_ptr`s.

@tamiko -- What do we do? Up the requirements to 1.56 (which we bundle, so we always have a fallback)? We could disable serialization of `Triangulation` if boost 1.54 is used, but that would be a regression :-(

**Comment by appiazzolla** [comment]
If boost1.56 is required, for instance, all Ubuntu versions before WilyWerewolf release on Oct 22 2015 will be incompatible with deal.ii in this regard.

**Comment by tjhei** [comment]
> Up the requirements to 1.56 (which we bundle, so we always have a fallback)?

That might be a problem for debian packaging. At least for the backports. Right, @tamiko ?

**Comment by bangerth** [comment]
@tamiko ?

**Comment by tamiko** [comment]
> @tamiko ?

Let's simply increase the minimal required version.

**Comment by tamiko** [comment]
@tjhei Yes, that's a point. But I would suggest we still go ahead with requiring a minimal boost version of 1.56. (at least, we won't run into any troubles with Debian testing. it have a very new boost version.)

I dislike the idea to make the configuration more elaborate to work around a boost regression... 
Generally, the serialization bits in boost seem to be a bit... rocky.

Other opinions?

**Comment by tjhei** [comment]
> Other opinions?

write a few lines of code to manually serialize the unique_ptrs in triangulation?

**Comment by bangerth** [comment]
That doesn't solve the problem that we want to use `unique_ptr`s in other places as well. The only other option I would see is falling back to `boost::scoped_ptr` instead of `std::unique_ptr` when only boost 1.54 is available, regardless of whether we use C++11 or C++98. But that won't be an option once we require C++11.
