### ISSUE TITLE
online documentation is down

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2979]
https://www.dealii.org/developer/doxygen/deal.II/ appears to be down.

**Comment by tjhei** [comment]
The whole dealii.org website is down but @guidokanschat is working on it.

**Comment by davydden** [comment]
right, just realised that the whole website is down.

**Comment by masterleinad** [comment]
We had some problems with fire alarms and power outages here. Hopefully, the server is running again soon. But I can't promise anything...

**Comment by davydden** [comment]
cool, thanks @masterleinad .
