### ISSUE TITLE
opencascade 7.0 compatibility

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2983]
from https://github.com/Homebrew/homebrew-science/pull/4063

>  the opencascade 7.0.0 release is missing some headers dealii expects to be there, and similar such issues with some symbols renames, etc.

supposedly the same will happen to OCE...

**Comment by bangerth** [comment]
Does Opencascade/OCE have a `config.h` header that we can `#include` first to get their version number, and then guard the offending header files with something like
```
 #if OPENCASECADE_VERSION_MAJOR >= 7
 #  include <something>
 #else
 #  include <something_else>
 #endif
```
?

**Comment by davydden** [comment]
for `oce` there is  `oce_build_config.defs` with 
```
/* Make OCE release number visible when displaying OCCT version number */
#define OCC_VERSION_DEVELOPMENT "oce-0.17"
```
there is also `config.h` but i did not see any meaningful version numbers there.

I don't have opencascade around to test/check for `config.h`, unfortunately, only `oce` which is good with its current release.

**Comment by bangerth** [comment]
Using string constants for version numbers is really not very helpful :-(

**Comment by davydden** [comment]
it's actually elsewhere, from /FindOPENCASCADE.cmake
```
IF(EXISTS ${OPENCASCADE_INCLUDE_DIR}/Standard_Version.hxx)
  FILE(STRINGS "${OPENCASCADE_INCLUDE_DIR}/Standard_Version.hxx" OPENCASCADE_VERSION
    REGEX "#define OCC_VERSION _T"
    )
ENDIF()
```

**Comment by bangerth** [comment]
I see. This would allow us to export something like `DEAL_II_OPENCASCADE_VERSION_MAJOR/MINOR`.

**Comment by bangerth** [comment]
(And put it into our own `config.h`.)

**Comment by davydden** [comment]
the file contains
```
// Primary definitions
#define OCC_VERSION_MAJOR         6
#define OCC_VERSION_MINOR         8
#define OCC_VERSION_MAINTENANCE   0
```

**Comment by davydden** [comment]
not sure what the regex actually picks up, most likely the first match, ie. `major` version.

**Comment by bangerth** [comment]
That's even simpler then, we just need to `#include <Standard_Version.hxx>` first.

**Comment by ilovezfs** [comment]
@bangerth any luck with this?

**Comment by bangerth** [comment]
@ilovezfs -- I don't know, I really don't know very much about this. It would need someone with an installation of OpenCascade to test one of the ideas above.

**Comment by davydden** [comment]
OCE `0.18` is out, i will see if I can fix compilation of current `master` branch...

**Comment by davydden** [comment]
i don't have `opencascade` `7.0` around to look into this issue. (I use `oce` instead). Unless somebody @dealii/dealii plan to investigate in very near future what needs to be changed to make `dealii` compatible with `7.0`, i am switching this issue to `9.0` milestone.

**Comment by tamiko** [comment]
> i don't have `opencascade` `7.0` around to look into this issue. (I
> use `oce` instead). Unless somebody @dealii/dealii plan to investigate
> in very near future what needs to be changed to make `dealii`
> compatible with `7.0`, i am switching this issue to `9.0` milestone.

Don't jump the gun - give me a week.

**Comment by davydden** [comment]
> Don't jump the gun - give me a week.

thanks!

**Comment by davydden** [comment]
@tamiko ping.
