### ISSUE TITLE
Throw exception upon error in ParameterHandler::read_*

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2984]
As #2977 / #2980 demonstrates, the idea of returning an error code in our functions is as bad of an idea as it has been ever since C came out in 1972. That's why C++ introduced exceptions.

We have a few remnants of this programming style in one of the earliest deal.II classes, `ParameterHandler`, most notably in the `read_*` classes. We should really replace this, in particular if the input stream is not readable.

**Comment by drwells** [comment]
Closed by #3122.
