### ISSUE TITLE
Avoid creation of Mapping::InternalData object in FEValues if no mapping is needed

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3003]
@gassmoeller ran into this today and we realized that one could save some time in the following case: Let's say you're only interested in the values of shape functions or the solution, and let's say that you only need `FE_Q` or similarly simple elements. In that case, `FEValues` still asks the `Mapping` object it uses to create a `Mapping::InternalData` object, even though no `update_` flags in the mapping category are set and consequently this object contains nothing of use to the finite element.

This all doesn't matter if one then uses the `FEValues` object for assembly on every cell because the up-front start-up cost is amortized over all cells. But it does matter if you only use the `FEValues` object once -- for example, `VectorTools::point_value`, in `FEFieldFunction`, or in other places where we evaluate point values at different points on each cell.

It is conceivable that one could avoid calling `Mapping::get_data()` in these circumstances altogether, and similarly avoid calling `Mapping::fill_fe_values` with the `MappingRelatedData` object from within `FEValues::reinit()`. It may be worth trying this out and running the testsuite to see what happens in that case.

**Comment by tamiko** [comment]
I guess this isn't meant to be an Infrastructure bug? :-)

**Comment by bangerth** [comment]
@class4kayaker -- this issue is fixed, right?

**Comment by class4kayaker** [comment]
I believe so. At least the suggested cases are handled.
