### ISSUE TITLE
Separation of Mesh topology and geometry

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#302]
_From [dr.guido.kanschat](https://code.google.com/u/dr.guido.kanschat/) on September 17, 2012 15:27:07_

For handling of degrees of freedom and most of the structure of finite element data and code, the actual geometry of the mesh is irrelevant.

Therefore, it is suggested to create a class Mesh, which has a minimal comfortable interface to handle mesh topologies and create DoFHandler and similar structures, once the mesh is given.

The current Triangulation class could inherit from Mesh and have the actual functions that fill the mesh class. This way, topology and geometry can still be created by the same refinement functions, if so desired.

The classes of the library that would combine topology and geometry are FEValues and Mapping; in particular, the latter could be more flexible and allow for the exact representation of manifolds

_Original issue: http://code.google.com/p/dealii/issues/detail?id=1_

**Comment by bangerth** [comment]
Let's close this. It seems like nobody is motivated enough to actually do anything about this issue.
