### ISSUE TITLE
Use lower_bound more intelligently

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#304]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on April 02, 2013 22:31:42_

There are a bunch of places in the library where we use std::lower_bound or Utilities::lower_bound to find the place to insert or lookup an element into a sorted array. Importantly, some of these places actually look up or insert _several_ elements and in this case we can optimize things a bit. For example, if we have that

```
p = lower_bound (x.begin(), x.end(), values[i]);
```

then we could compute the place to insert values[i+1] using the same statement, or we could improve things by doing something like

```
if (values[i+1] > values[i])

    p = lower_bound (p, x.end(), values[i+1]);

else

    p = lower_bound (x.begin(), p, values[i+1]);
```

This should on average save one bisection step which may be relevant if the arrays we store into/lookup in are relatively small.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=25_

**Comment by drwells** [comment]
I don't doubt that there are places where we could improve this, but it is a logarithmic time search and I don't think I have ever seen it show up in profiling. Surely there are worse places we spend our time. Would anyone be opposed to closing this?

**Comment by bangerth** [comment]
No. Let's do it.
