### ISSUE TITLE
deal.II 8.4.2

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3049]
I have tagged 8.4.2-rc1.

All, please have a quick look at it before I tag 8.4.2. I plan to do this relatively quickly, in about 12h.

@drwells Thanks a lot for the review and the patches :-)

**Comment by tamiko** [comment]
Results for ```WITH_MPI=OFF`` on debian testing: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1086

**Comment by drwells** [comment]
Happy to help!

**Comment by tamiko** [comment]
We should also test 8.4.2-rc1 against the new p4est release candidate that was just announced.

**Comment by tjhei** [comment]
> in about 12h.

You are not giving us a lot of time here. :-)

Please test newest trilinos, petsc, and p4est before pulling the trigger.

**Comment by tamiko** [comment]
Results for `WITH_MPI=ON` on debian testing: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1096

**Comment by tamiko** [comment]
@tjhei 
> Please test newest trilinos, petsc, and p4est

This is exactly what I am already doing for the most part of today :-)

**Comment by tamiko** [comment]
@tjhei The reason is that I will need another 24h for the Debian packaging and all testing and I would like to get this done by Friday. Semester starts next week.

**Comment by tamiko** [comment]
Ah, sh** We need #3041 to resolve #2951 for 8.4.2 as well. So much for my 12h. :-/

**Comment by tamiko** [comment]
Results for `WITH_MPI=ON` on Gentoo with current development version of p4est: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1110

**Comment by drwells** [comment]
I don't think I have ever seen that VTK problem before. Can you handle it from here, or do you want some more testing done?

**Comment by tamiko** [comment]
@drwells You mean the two line change in VTK? VTK is simply not a stable output format. I don't think this is a problem.

Above are also not the latest development sources for libsc/p4est. So, another testrun...

**Comment by tamiko** [comment]
With current development version of p4est: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1128

**Comment by tamiko** [comment]
I have tagged 8.4.2, https://github.com/dealii/dealii/releases/tag/v8.4.2
 - [ ] Mac bundle, @luca-heltai 
 - [ ] Update documentation on website, @guidokanschat 
 - [ ] Update Debian/Ubuntu package, @tamiko
 - [ ] Update download page, @tamiko

**Comment by bangerth** [comment]
@guidokanschat?

**Comment by bangerth** [comment]
So what is the status of this? The package is there for download, but it
* doesn't seem to be announced
* the website is not up to date
* I don't know whether there are packages for Mac and/or Debian.

**Comment by tjhei** [comment]
> I don't know whether there are packages for Mac

Mac OS packages are attached to the release.

**Comment by tamiko** [comment]
I will just close.
After some lengthy setback 8.4.2 will finally hit Debian testing soon (fingers crossed) right before the freeze for a new version. We never updated the homepage, though.
