### ISSUE TITLE
add GridIn::parse_parameters, format detection

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#305]
_From [timo.heister](https://code.google.com/u/timo.heister/) on May 15, 2013 10:05:14_

It would be great to have GridIn::declare/parse_parameters. Additionally, the read() routine could guess the format from the file ending.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=56_

**Comment by bangerth** [comment]
This also seems like an issue nobody seems interested in working on. Since there hasn't been any activity in 4 years, let's close it -- we can always reopen.
