### ISSUE TITLE
Dealii 8.4.x  does not find PETSC and SLEPSC libraries when configuring under Windows

### ISSUE THREAD

**Issue by loylick** [dealii/dealii#3060]
Hello!

I've compiled PETSC and SLEPSC packages from the sources. As I started to configure Dealii to compile with these two libraries I can not get Dealii to pick up the packages. I configure it with this commande:
cmake -DCMAKE_INSTALL_PREFIX=/cygdrive/c/dev/install2 -DPETSC_DIR=/cygdrive/c/dev/petsc-3.6.4 -DPETSC_ARCH=x86 -DSLEPC_DIR=/cygdrive/c/dev/slepc-3.6.3 -DSLEPC_ARCH=x86 ..
I attach the complete log of configuring as well as a screen shot of my directory structure.  The issue may prove to be simple to resolve but I can not understand what is wrong.

Alex
[dealii_config.txt](https://github.com/dealii/dealii/files/453578/dealii_config.txt)
![petsc_dir](https://cloud.githubusercontent.com/assets/20624598/18227179/1e45e42a-7224-11e6-9346-fceee9478cfb.jpg)

**Comment by tjhei** [comment]
> The issue may prove to be simple to resolve but I can not understand what is wrong.

No, I am sorry, but this is not a simple to resolve problem. Please see https://github.com/dealii/dealii/issues/1921 (I just updated it). There are many more things to tackle on windows to be even close to supporting parallel computations and libraries like PETSc/SLEPc. We have _never_ run the full testsuite even for the most basic functionality inside the library and as such, I am sure many things will just not work.

**Comment by loylick** [comment]
All the same I'm not going to use  parallel computations right now. I've built PETSC/SLEPC without MPI support. Now I just wonder why Dealii does not recognize PETSC/SLEPC packeges given  PETSC_DIR and SLEPC_DIR variables in the command line of cmake at the configure stage.

**Comment by loylick** [comment]
Still have no ideas? I can precise my question. I do not ask to help me run or even build the dealii+petsc/slepc configuration. I'm just wondering where I should look in the building system to understand why Dealii does not find PETSC ans SLEPC packages with the information I provided to it?

**Comment by tjhei** [comment]
I am not surprised that external packages are not working. You probably need to dig into the cmake modules to make them work on windows. A few comments:
- From the log it looks like you are using Visual Studio 2012, we are not supporting such an old version.
- What compilers did you use to compile PETSc? It won't work if you use cygwin for example. Are you creating static libraries?
- the config log contains info about the FIND_LIBRARY call:
```
--     FIND_LIBRARY(PETSC_LIBRARY NAMES petsc HINTS /cygdrive/c/dev/petsc-3.6.4 /cygdrive/c/dev/petsc-3.6.4/x86 PATH_SUFFIXES lib lib64 lib)
-- PETSC_INCLUDE_DIR_ARCH not found! Call:
--     FIND_PATH(PETSC_INCLUDE_DIR_ARCH petscconf.h HINTS /cygdrive/c/dev/petsc-3.6.4 /cygdrive/c/dev/petsc-3.6.4/x86 PATH_SUFFIXES petsc include include/petsc)
```
Can you double-check that those paths are correct? Maybe on windows you need to add "libpetsc" to the NAMES section?


> I'm just wondering where I should look in the building system

the PETSC module under cmake/modules/.



> Does one need Dealii with MPI support compiled to run PETSC/SLEPC functions?

We still allow configuring both without MPI but I don't think this has any use (the serial vectors are deprecated and will be gone in the next release and why would you use PETSc for serial computations anyway?)

**Comment by loylick** [comment]
Yes, I use VS 2012 and I can compile happily dealii with it as well as PETSC and SLEPC as long as I compile them separately.  Yes, I compile static libs. Concerning NAMES section, does the script check "petsc" combinations with different suffixes and prefixes like "lib"+petsc"+ ."lib" and where the suffuxes are defined? It seems to me that it looks for *.a suffix for static libs under windows.

I use PETSc with serial computation because you mentioned that you do not support MPI under windows so I deduced that it would be logical not to use it in PETSc either.  Or MPI support in PETSc has nothing to do with MPI support in deallii and they are completely independent?

**Comment by tamiko** [comment]
On Sun, Sep 18, 2016, at 11:18 CDT, loylick <notifications@github.com> wrote:

> Yes, I use VS 2012 and I can compile happily dealii with it as well as
> PETSC and SLEPC as long as I compile them separately.  Yes, I compile
> static libs. Concerning NAMES section, does the script check "petsc"
> combinations with different suffixes and prefixes like "lib"+petsc"+
> ."lib" and where the suffuxes are defined? It seems to me that it
> looks for *.a suffix for static libs under windows.

You can find the relevant cmake bits in 'cmake/modules/FindPETSC.cmake'.
The relevant call looks like this:

  DEAL_II_FIND_LIBRARY(PETSC_LIBRARY
    NAMES petsc
    HINTS ${PETSC_DIR} ${PETSC_DIR}/${PETSC_ARCH}
    PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
    )

which is a small wrapper around CMake's FIND_LIBRARY (to provide some
useful output) and essentially boils down to calling the corresponding
cmake function:

  FIND_LIBRARY(PETSC_LIBRARY
    NAMES petsc
    HINTS ${PETSC_DIR} ${PETSC_DIR}/${PETSC_ARCH}
    PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
    )

So, the question of what exactly happens on a Windows target is entirely
up to what CMake actually does internally. According to documentation it
should cycle through a meaningful list of prefixes and postfixes.


According to your hint:
  -DPETSC_DIR=/cygdrive/c/dev/petsc-3.6.4 ...

Why is this not a Windows native path if you want to set up a MSVC*
configuration? CMake uses different library suffixes depending on
whether it is configured for a cygwin environment, or native windows.

Can you try again with the graphical, windows native cmake gui?

**Comment by loylick** [comment]
> Maybe on windows you need to add "libpetsc" to the NAMES section?

Yes, it worked. Finally PETSc/SLEPC were found. So, under Windows cmake does not check the prefix "lib" to the library name for unknown reason.

**Comment by loylick** [comment]
There are good news and bed news. After all, I've compiled dealii with PETSC/SLEPC under windows. But only in release, because in debug I got the error:  fatal  error LINK1248: image size (800000D4) exceeds maximum allowable size (80000000).  So the size of the lib becomes a problem. We should consider some ways to reduce it. I got release lib 850Mb.

**Comment by tjhei** [comment]
That's too bad but not totally unexpected. There are many things to be fixed before this becomes usable. I would like to encourage you to try some of the other solutions to run deal.II, even if you must run on windows, you can run in a virtual machine for example.

**Comment by loylick** [comment]
Some news on the issue. I've finally managed to compile the Dealii library and run rather complicated program calculating eigenvalues in an elasticity problem in 3D pyramid.  My configuration is Visual Studio 2015 x64 compiler PETSC+cblaslapack, SLEPC, Dealii last master version.  
in cygwin:
PETSC
export PETSC_DIR=/cygdrive/h/dev/petsc-3.7.5
export PETSC_ARCH="arch-mswin-c-debug"
./configure --with-cc="win32fe cl" --with-fc=0 --with-mpi=0 --with-debugging=1 --download-f2cblaslapack=1 -CFLAGS="-O2 -MD -wd4996" -CXXFLAGS="-O2 -MD -wd4996"
make PETSC_DIR=/cygdrive/h/dev/petsc-3.7.3 PETSC_ARCH=arch-mswin-c-debug all -- this one did not work so I had to run:
make -f gmakefile all

SLEPC
export SLEPC_DIR=`pwd`
export SLEPC_ARCH="arch-mswin-c-debug"
./configure
make SLEPC_DIR=$PWD PETSC_DIR=/cygdrive/h/dev/petsc-3.7.3 PETSC_ARCH=arch-mswin-c-debug
make -f gmakefile all
For some reason Dealii cmake configuration does not work in cygwin (it does not find PETSC, SLEPC because of /cygdrive prefix of disks in cygwin shell)
So I used mingw to run cmake configuration
in mingw:
Dealii
in root distrib dir:
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=/h/Dev/install ..
this created VS projet which needs only one thing to get the lib compiled. it is necessary provide a link to include direcoty containig mpi.h. For that I added h/Dev/petsc-3.7.5/include/petsc/mpiuni/ to list of include dirs in all VS projects generated by dealii cmake.
That's all. dealII.g.lib is about 3Gb, dealII.lib ~500Mb. Linker refused to link debug library cause it is too big I guess. but release lib was pretty good linked and I compiles an executable.

Regards

**Comment by loylick** [comment]
By the way here is a diff patch with my corrections to Dealii code.
[patches.txt](https://github.com/dealii/dealii/files/791810/patches.txt)

**Comment by bangerth** [comment]
Can you break your changes into individual patch sets? For example, the changes to `read_write_vector.templates.h` seem rather obvious and should be easy to merge. I suspect that the change to `mpi.cc` is equally uncontroversial if you just *remove* the offending lines rather than commenting it out.

@tamiko may have something to say about the changes in configuration -- put those into a separate pull request as well.

**Comment by drwells** [comment]
Since #4008 resulted in a patch that fixed this problem I believe we can close this issue.
