### ISSUE TITLE
printing in matrix market format.

### ISSUE THREAD

**Issue by inkstink** [dealii/dealii#3063]
Please forgive me if this is not the correct place to put this.

I have had a need to output matrices built in deal.II to a [matrix market format](url). This is a format that MATLAB (I think), Mathematica and some functions in the Nvidia linear algebra library can use.  

I wrote a way to do this (it is pretty straightforward).  I am wondering if it would be worthwhile to contribute this to the codebase.  I don't have unit tests written but I think documentation can be generated from the file.

So my questions are:
1) Was this the correct spot for this?
2) Should I contribute the functionality
2) Do I need unit tests?

**Comment by davydden** [comment]
I think it's a good feature to have. I myself also wrote a small function to output PETSc matrices:
```
    void print_matrixmarket(const dealii::PETScWrappers::MPI::SparseMatrix &matrix,
                            const std::string file_name)
    {
      PetscViewer    view;
      PetscViewerASCIIOpen(PETSC_COMM_WORLD,file_name.c_str(),&view);
      PetscViewerSetFormat(view,PETSC_VIEWER_ASCII_MATRIXMARKET);
      MatView(matrix,view);
      PetscViewerDestroy(&view);
    }
```

Which matrices did you output? As for PETSc, i think this could go to `PETScWrappers::MatrixBase`. Unit tests would be helpful on small matrices to make sure it works as expected.

**Comment by bangerth** [comment]
Definitely makes sense. Any code would be much appreciated, for any of the matrix classes.

**Comment by inkstink** [comment]
Ok, I will contribute it.  I have only contributed trivial changes before, so I might need some hand holding.

**Comment by bangerth** [comment]
We'd of course be happy to.  Give it a try and if you get stuck somewhere, let us know and we'll help you out!

**Comment by drwells** [comment]
This hasn't been a high-priority item - I think its fine if we leave our answer as 'use PETSc for exporting'.
