### ISSUE TITLE
fix step-18/19

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#307]
_From [timo.heister](https://code.google.com/u/timo.heister/) on August 14, 2013 20:09:55_

1. step 18 is somewhat out of date and should be updated. We can probably do parallel vtk output and remove step-19 (which is the file merger program).

2. I got the report that merged file output using step-19 is missing a few  elements, when merging a parallel output with >1 CPU. Investigate that.

3. step-18 also crashes on my machine:
  Cycle 1:

\--------------------------------------------------------
An error occurred in line \<806> of file \</scratch/deal-trunk/deal.II/include/deal.II/grid/tria_objects.h> in function
    unsigned int& dealii::internal::Triangulation::TriaObjects<G>::user_index(unsigned int) [with G = dealii::internal::Triangulation::TriaObject<3>]
The violated condition was: 
    user_data_type == data_unknown || user_data_type == data_index
The name and call sequence of the exception was:
    ExcPointerIndexClash()
Additional Information: 
(none)

Stacktrace:
\-----------
\#0  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: dealii::internal::Triangulation::TriaObjects<dealii::internal::Triangulation::TriaObject<3> >::user_index(unsigned int)
\#1  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: dealii::TriaAccessor<3, 3, 3>::user_index() const
\#2  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: 
\#3  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: dealii::Triangulation<3, 3>::save_user_indices_hex(std::vector<unsigned int, std::allocator<unsigned int> >&) const
\#4  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: dealii::Triangulation<3, 3>::save_user_indices(std::vector<unsigned int, std::allocator<unsigned int> >&) const
\#5  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: void dealii::GridTools::get_face_connectivity_of_cells<3, 3>(dealii::Triangulation<3, 3> const&, dealii::SparsityPattern&)
\#6  /scratch/deal-trunk/installed/lib/libdeal_II.g.so.8.1.pre: void dealii::GridTools::partition_triangulation<3, 3>(unsigned int, dealii::Triangulation<3, 3>&)
\#7  ./step-18: Step18::TopLevel<3>::refine_initial_grid()
\#8  ./step-18: Step18::TopLevel<3>::do_initial_timestep()
\#9  ./step-18: Step18::TopLevel<3>::run()
\#10  ./step-18: main

_Original issue: http://code.google.com/p/dealii/issues/detail?id=80_

**Comment by bangerth** [comment]
step-18 now uses VTU format, and it uses `parallel::shared::Triangulation`. I think it is generally useful, so I vote to leave it in place, even though it may not be the best parallel program to start with. I've also just verified that the program in its current form actually runs. This seems to address the major points regarding step-18 listed in the current issue.

step-19 is clearly outdated, and in fact no longer needed. I've just opened #2046 for this.
