### ISSUE TITLE
sporadic test failure

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3077]
I am getting sporadic test failures on one of my machines. Here is an example:
```
8015/8241 Test #401: all-headers/algorithms/any_data.h.debug ..................
.......................***Failed    0.54 sec
ninja: error: opening build log: No such file or directory
Test all-headers/algorithms/any_data.h.debug: BUILD
===============================   OUTPUT BEGIN  ===============================
all-headers/algorithms/any_data.h.debug: BUILD failed. Output:


all-headers/algorithms/any_data.h.debug: ******    BUILD failed    *******
```
Does anybody else experience this? Is this a race condition with file/folder creation? I am using 
```
$ ninja --version
1.6.0
$ cmake --version
cmake version 3.3.0
```

**Comment by tamiko** [comment]
On Wed, Sep  7, 2016, at 09:11 CDT, Timo Heister <notifications@github.com> wrote:

> I am getting sporadic test failures on one of my machines. Here is an example:
> ```
> 8015/8241 Test #401: all-headers/algorithms/any_data.h.debug ..................
> .......................***Failed    0.54 sec
> ninja: error: opening build log: No such file or directory
                ~~~~~~~~~~~~~~~~~

This is a race condition with ninja.

Ninja does not support concurrent builds invoked by multiple ninja
instances (a feature of GNU Make which we heavily use in the testsuite).

**Comment by tjhei** [comment]
> This is a race condition with ninja.

So the answer is "do not use ninja with deal.II"?

**Comment by tamiko** [comment]
> So the answer is "do not use ninja with deal.II"?

"do not use ninja in the testsuite".

ninja for compiling the library is fine. :-)


I would like to have an easy solution for the problem. Unfortunately,
not (ab)using testsubprojects for the ctest driver is a substantial
rewrite of the testsuite. :-/

**Comment by tjhei** [comment]
> "do not use ninja in the testsuite".

So, should we blacklist "setup_tests" when the generator is ninja?

Okay, for development I can use ninja to compile and make to test by configuring the testsuite in a separate build directory by setting DEAL_II_DIR to the build directory of deal.II (I never tried that before but it seems to work). Is there a better than doing that?

Also, how does that work for our automated testers, should we do the same there? (the deal.II-alpha-tester currently uses ninja for both). Should we use run_testsuite.cmake? Can I specify two generators that way?

**Comment by bangerth** [comment]
I never had that problem when calling `ninja setup_tests`. I think you can only get into trouble if you call this multiple times in parallel, right?

For running the testsuite with ctest, @tamiko committed a patch a while back that *always* runs `make` instead of `ninja`, regardless of the generator you have chosen at the top level.

**Comment by tjhei** [comment]
> I never had that problem when calling ninja setup_tests. I think you can only get into trouble if you call this multiple times in parallel, right?

setup_tests is not the problem, but running ``ctest -j xy``, which will execute ninja in parallel.



> For running the testsuite with ctest, @tamiko committed a patch a while back that always runs make instead of ninja

is that only for run_testsuite.cmake?

**Comment by bangerth** [comment]
@tamiko 's patch made sure that we never run `ninja` from `ctest`. Upon second thought, it turns out the patch is actually by you yourself: #2767.

**Comment by tjhei** [comment]
> is actually by you yourself:

Huh, another thing I totally blanked out on. But then the patch doesn't seem to work. @tamiko, why is that?

**Comment by tamiko** [comment]
@tjhei I don't know. #2767 works for me. How exactly do you configure; and how do you set up tests?

**Comment by bangerth** [comment]
I had a build directory that was several months old and ended up needing to blow it away before that patch started to work correctly for me.

**Comment by tjhei** [comment]
> I had a build directory that was several months old and ended up needing to blow it away before that patch started to work correctly for me.

That has been the solution so many times in the past and still didn't think of it. :-(
