### ISSUE TITLE
locally_owned_dofs belong to different block do not equal after DoFRenumbering::subdomain_wise and DoFRenumbering::block_wise

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#3078]
The description may not be very clear, but I will try to explain it.

Since `DoFTools::get_subdomain_association` use a coin-flip strategy to decide the ownership of DoFs on subdomain boundary, the DoFs belong to the save block on the subdomain boundary will be owned by different subdomain. After `subdomain_wise` and `block_wise`, DoFs belong to different blocks have different parallel partitions.

This is typically no harm, but when we want to use block preconditioner, problems may occur.
Say we have assembled a block matrix`[A, B; C, D]` and we want to use `[A+D, 0; 0, A+D]` as the preconditioner matrix. This will fail due to that matrix A and D have different parallel distributions.

Note that `p::d::Triangulation` do not have this problem because each DoF on an interface between processors is assigned to the processor with the smallest processor identifier.

Of course, we can use the same strategy as in `p::d::Triangulation`, but it seems like it will affect the load balance when the number of processes is not very large.

Is there another method to this problem?

The following code shows this problem.

```
#include <deal.II/base/mpi.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>

#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_renumbering.h>
#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_system.h>

#include <deal.II/distributed/tria.h>

#include <iostream>

int main(int argc, char **argv) {
  dealii::Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
  const unsigned int n_mpi_processes =
      dealii::Utilities::MPI::n_mpi_processes(MPI_COMM_WORLD);
  const unsigned int this_mpi_process =
      dealii::Utilities::MPI::this_mpi_process(MPI_COMM_WORLD);

  dealii::FESystem<3> fe(dealii::FE_Q<3>(1), 2);

  {
    dealii::Triangulation<3> tria;
    dealii::GridGenerator::hyper_cube(tria, -1, 1);
    tria.refine_global(3);

    dealii::GridTools::partition_triangulation(n_mpi_processes, tria);

    dealii::DoFHandler<3> dh(tria);
    dh.distribute_dofs(fe);

    dealii::DoFRenumbering::subdomain_wise(dh);
    dealii::DoFRenumbering::block_wise(dh);

    const std::vector<dealii::IndexSet> locally_owned_dofs_per_subdomain =
        dealii::DoFTools::locally_owned_dofs_per_subdomain(dh);

    const dealii::types::global_dof_index dofs_per_block = dh.n_dofs() / 2;
    std::vector<dealii::IndexSet> locally_owned_dofs_per_block(2);
    locally_owned_dofs_per_block[0] =
        locally_owned_dofs_per_subdomain[this_mpi_process].get_view(
            0, dofs_per_block);
    locally_owned_dofs_per_block[1] =
        locally_owned_dofs_per_subdomain[this_mpi_process].get_view(
            dofs_per_block, dh.n_dofs());

    // This assertion will fail.
    // Assert((locally_owned_dofs_per_block[0] ==
    // locally_owned_dofs_per_block[1]),
    //        dealii::ExcMessage("locally owned dofs do not equal!!!"));

    std::cout << "Seq, Block 0, Process " << this_mpi_process << " : ";
    locally_owned_dofs_per_block[0].print(std::cout);
    std::cout << "Seq, Block 1, Process " << this_mpi_process << " : ";
    locally_owned_dofs_per_block[1].print(std::cout);
  }

  {
    dealii::parallel::distributed::Triangulation<3> tria(MPI_COMM_WORLD);
    dealii::GridGenerator::hyper_cube(tria, -1, 1);
    tria.refine_global(3);

    dealii::DoFHandler<3> dh(tria);
    dh.distribute_dofs(fe);

    dealii::DoFRenumbering::block_wise(dh);

    const dealii::types::global_dof_index dofs_per_block = dh.n_dofs() / 2;
    std::vector<dealii::IndexSet> locally_owned_dofs_per_block(2);
    locally_owned_dofs_per_block[0] =
        dh.locally_owned_dofs().get_view(0, dofs_per_block);
    locally_owned_dofs_per_block[1] =
        dh.locally_owned_dofs().get_view(dofs_per_block, dh.n_dofs());

    // This assertion will NOT fail.
    Assert((locally_owned_dofs_per_block[0] == locally_owned_dofs_per_block[1]),
           dealii::ExcMessage("locally owned dofs do not equal!!!"));

    std::cout << "Dist, Block 0, Process " << this_mpi_process << " : ";
    locally_owned_dofs_per_block[0].print(std::cout);
    std::cout << "Dist, Block 1, Process " << this_mpi_process << " : ";
    locally_owned_dofs_per_block[1].print(std::cout);
  }

  return 0;
}
```

**Comment by bangerth** [comment]
Yes, I can see how this is awkward. The issue of course is that, at least in principle, a matrix such as `A+D` doesn't make any sense because it adds apples and oranges -- objects from different vector spaces. The fact that you may have discretized these objects using the same finite element space is irrelevant in this context. But I can of course see reasons why one would want to do it nevertheless in practice.

Can you describe how a perfect solution would look like for you? In particular, it would be interesting to hear what you think in which of the following cases you would like to make sure that DoFs of different vector components need to remain on the same processor:
* `FE_System(FE_Q,2)`
* `FE_Nedelec`
* `FE_System(FE_Q, 1,  FE_TraceQ, 1)    // same number of DoFs per face`

Alternatively, what would you think of a solution where we roll the dice not per DoF, but per face?

**Comment by adamqc** [comment]
Actually, I want to solve a time harmonic maxwell equation. The equation is curl(curl E) + k E = J, where k is a complex scalar. The finite element I use here is `FE_System(FE_Nedelec, 2)`. 

The linear system is `[C, -M; -M, -C]`, `[C]` is the stiffness term, `[M]` is the mass term. Solving this system is extremely difficult using general preconditioners. Since both `[C]` and `[M]` are symmetric positive semi-definite, `[C + M, 0; 0, C + M]` is a very efficient preconditioner and `[C + M]` can also be solved using AMS preconditioner (implemented in HYPER) efficiently.

That's why I need DoFs belong to different blocks have same parallel distributions.

> Alternatively, what would you think of a solution where we roll the dice not per DoF, but per face?

Sounds good. I will investigate whether it is difficult to implement.

**Comment by bangerth** [comment]
On 09/12/2016 06:47 AM, Ce Qin wrote:
>     Alternatively, what would you think of a solution where we roll the dice
>     not per DoF, but per face?
>
> Sounds good. I will investigate whether it is difficult to implement.

Great. Let us know if you need help!

**Comment by bangerth** [comment]
@adamqc -- any news?

**Comment by agrayver** [comment]
> Alternatively, what would you think of a solution where we roll the dice not per DoF, but per face?

@bangerth could you please elaborate on this? I faced this exact problem now and need to overcome. 

Ideally, I would like to have behvaiour that is identical to p::d::Tria when calling DoFRenumbering::block_wise with p::s::Tria.

**Comment by tjhei** [comment]
@tcclevenger was looking at this code when he implemented multigrid numbering for shared::Tria. We decided not to change it, but I think it would make sense to do. Right, @tcclevenger ?

**Comment by tcclevenger** [comment]
@tjhei We distributed the level dofs of `p::s::T` as in `p::d::T` (smallest processor) but decided not to change the subdomain association of active dofs.

**Comment by agrayver** [comment]
@tjhei do I understand correctly that in order to get behaviour identical to p::d::Tria one needs:

1. Change DoFTools::get_subdomain_association to distribute dofs with smallest processor.
2. In user code, call DoFRenumbering::subdomain_wise followed by DoFRenumbering::block_wise.
