### ISSUE TITLE
Extend DataOutBase to also accept 0-dimensional patches

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#308]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on August 15, 2013 03:19:04_

Aspect already does output of particles, and there's been discussion on the mailing list about outputting data at quadrature points. This could all easily be incorporated into DataOutBase if we allowed patches to store zero-dimensional data.

I'll eventually get around to this, but wanted to have this recorded.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=81_

**Comment by bangerth** [comment]
@gassmoeller -- might you be interested in this given that it would be useful to make the ASPECT particle code smaller?

**Comment by gassmoeller** [comment]
Well that depends a bit. It is certainly on my wish list to have this implemented, but I can currently not even guess how much or little work is involved in this rework, and I have a number of other projects needing attention as well. I do not know much about that part of the code, except I found it confusing whenever I looked into it. What would be the main obstacles to simply allow zero dimensional patches?

**Comment by bangerth** [comment]
I meant to add a smiley to the end of my last comment :-)

I think it actually ought to be quite simple. I'm envisioning simply specializing/overloading the functions in `namespace DataOutBase` for `dim==0`. I suspect that we could copy most of the ASPECT code without too much trouble.

**Comment by bangerth** [comment]
@gassmoeller -- was there anything else that was necessary to address this?

**Comment by gassmoeller** [comment]
Lets keep it open a few more days, until I have tested it in ASPECT. There might be some missing parts in DataOut, although it might just work already.

**Comment by gassmoeller** [comment]
geodynamics/aspect#1869 is essentially finished and the new implementation works for those purposes. I suppose this issue can be closed. #4695 is a possible future optimization, but the main objective of this issue has been solved.

**Comment by bangerth** [comment]
Excellent. Thanks for your work!
