### ISSUE TITLE
General contributions for problems with standard/common physics

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3091]
The (so far) positive response to #3080 has an obvious extension: 
- Will we accept code that has less to do with `deal.II` and FEM in general, and more to do with solving standard or common physics problems? For example, some of the functionality I'm slowly putting together in #3034 definitely falls into this category. 
- If so, then what would the scope of acceptable contributions be? Is it necessary to adopt some guidelines to decide what is acceptable and what is too specialised? 
  - What constitutes a "standard" physics problem? 
  - Standardisation: How does one choose a standard notation? etc... 

I personally hope that there's some scope to accept these sorts of contributions, as I've got a lot of code that I could add immediately (mainly constitutive laws for multi-physics problems). The `MeshWorker` framework tackles some standard problems already, so some precedent for this has already been set.

**Comment by drwells** [comment]
I think that adding physics functionality is a good idea (and if we look at things like `/base/flow_function.h` we already have a precedent for adding such things).

My answer to 'What constitutes a "standard" physics problem?': I would say that a useful definition of "standard" would be "things that the developers understand". We should avoid adding code that we don't understand or can't maintain.

**Comment by davydden** [comment]
> We should avoid adding code that we don't understand or can't maintain.

good point. 

I would say we can add functionality/utilities that help users employ effectively deal.II in their field. Common need in continuum mechanics -- basic tensors -> @jppelteret contributed these to save all users from re-implementing it, possibly with mistakes. Some users need to track particles w.r.t. the mesh in deal.II -> basic particle class and its manager IMHO is good to have (https://github.com/dealii/dealii/issues/3080). Often one needs to maintain data assigned to quadrature points -> now we have a few classes to help with it https://github.com/dealii/dealii/pull/2552. Neither of these are FEM specific, but each helps to write better quality code faster. 

Of course there is balance to find between going to deep in the single field (i.e. implementing 20 different constitutive laws in continuum mechanics) vs providing enough functionality which would be needed in majority of usage cases for a given field.

**Comment by Rombur** [comment]
> - Will we accept code that has less to do with deal.II and FEM in general, and more to do with solving standard or common physics problems? 

I think that's a good idea. After all, the name deal stands for Differential Equations Analysis Library and there is no mention of FEM in it ;-)

> - If so, then what would the scope of acceptable contributions be? Is it necessary to adopt some guidelines to decide what is acceptable and what is too specialised? 

I don't think that we need guidelines for now. As long as a few people see the interest in having that functionality in deal, I think that is sufficient to include it.

**Comment by bangerth** [comment]
For things that are *tools*, i.e., that could be used in a variety of applications, there is no question that we should accept these things. For things that are more application specific, I think the question is a bit more delicate. Examples you bring up would be material laws -- I think one could group them under the umbrella "tools" if they are small building blocks (such as the tensor functions in one of the recent pull requests), but if they form overarching frameworks, I'd be more comfortable putting them into tutorials, code galleries, or external libraries. I don't think we need specific guidelines -- just open a github issue in which you discuss what concretely you want to add (before you actually try to write a pull request) and we can figure out what category a contribution would fall into.

I've become quite hesitant about frameworks such as `MeshWorker` unless they are well documented to a point where we can expect that people can figure things out by themselves without too many questions on the mailing list. But I think we all agree on this.

**Comment by jppelteret** [comment]
Thanks for your input everyone. I think that you all raise good points, and I'm happy that there's some scope for development here. Are there any objections to me creating a new directory `dealii/physics` to place all of these utility functions in? I envisage there ultimately being a structure such as the following
- `dealii/physics/solids`
- `dealii/physics/electromagnetism`
- `dealii/physics/thermal`
- `dealii/physics/fluids`
- `dealii/physics/particles`

**Comment by tamiko** [comment]
@jppelteret I would very much prefer ```contrib/physics```.

**Comment by tamiko** [comment]
It might be time that we think about reorganizing our library structures in general, though. I.e., split the current codebase into smaller libraries.

With that we could quite flexibly support "modules" (for example above physics/* stuff, or the python bindings). Either managed within the main repository, or a git-module, or user provided stuff.

I think this would have quite a few advantages (closer to native windows support, cleaner code organization due to acyclic dependencies between library parts, more flexibility what can be part of the deal.II software package).

**Comment by jppelteret** [comment]
@tamiko In response to your prior comment, some of these functions would be used in the tutorials. Would this "module" then be installed along with the other headers and linked into the main library? I don't have the python-bindings installed so I can't work out if this happens for them.

**Comment by tamiko** [comment]
> @tamiko In response to your prior comment, some of these functions
> would be used in the tutorials. Would this "module" then be installed
> along with the other headers and linked into the main library? I don't
> have the python-bindings installed so I can't work out if this happens
> for them.

Do you intend to create a new category, i.e.

  /include/deal.II/physics/*
  /source/physics/*

or do you want to have a new top level hierarchy?

  /physics/include
  /physics/source

Because your question also applies to the latter case.

**Comment by jppelteret** [comment]
Oh right, I see that now. I had intended to create a new category.

**Comment by bangerth** [comment]
I'd say let's think of splitting into separate libraries once (i) there is a significant amount of material in the new categories, (ii) we have other categories. For now, the intellectual beauty of the approach doesn't seem to justify the pain associated by making the build system (for the library, and for user codes) more complicated.

**Comment by tamiko** [comment]
> Oh right, I see that now. I had intended to create a new category.

Disregard my comment then, please :-)

**Comment by drwells** [comment]
@jppelteret Since #3034 has been merged (which establishes a structure for such additions) may we close this issue?

**Comment by jppelteret** [comment]
Yip, thanks @drwells  :-)
