### ISSUE TITLE
Link tests with the CXXFLAGS given

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3096]
When I use this for `CXXFLAGS` during cmake time
```
-fsanitize=address -fsanitize=undefined -fsanitize-recover=all -ggdb
```
then I can compile everything with the address and undefined behavior sanitizers in recent versions of GCC. But I fail in the testsuite because tests aren't linked with these flags:
```
Linking CXX executable fe_prolongation_nedelec.debug/fe_prolongation_nedelec.debug

/usr/bin/cmake -E cmake_link_script CMakeFiles/fe_prolongation_nedelec.debug.dir/link.txt --verbose=on\
/home/bangerth/bin/gcc-6.2.0/bin/c++        -rdynamic -fuse-ld=gold -ggdb \
CMakeFiles/fe_prolongation_nedelec.debug.dir/fe_prolongation_nedelec.cc.o\
CMakeFiles/fe_prolongation_nedelec.debug.dir/fe_prolongation_nedelec.debug/interrupt_guard.cc.o  -o \
fe_prolongation_nedelec.debug/fe_prolongation_nedelec.debug -rdynamic\
/home/bangerth/p/deal.II/1/build-gcc6.2.0/lib/libdeal_II.g.so.8.5.0-pre -lbz2 -llapack -lblas -lm -lquadmath \
-lc -ldl -lz -lrt -Wl,-rpath,/home/bangerth/p/deal.II/1/build-gcc6.2.0/lib
```
Consequently, every test fails with linker errors like this:
```
/home/bangerth/p/deal.II/1/build-gcc6.2.0/lib/libdeal_II.g.so.8.5.0-pre: error: undefined reference to '__asan_report_store2'
```

What needs to happen is that we add `CXXFLAGS` also to the linker flags. Alternatively, should I have added these flags to `LDFLAGS`?

(I'll note that this issue is separate from the fact that the link of `expand_instantiations` fails, for the same reason. There, we have argued that `expand_instantiations` is a host tool, as opposed to a target executable, and that consequently one needs to be careful.)

**Comment by tjhei** [comment]
> Alternatively, should I have added these flags to LDFLAGS?

I am pretty sure the sanitizer also need link flags, yep: http://clang.llvm.org/docs/AddressSanitizer.html#usage

**Comment by bangerth** [comment]
That's exactly the point. 

I had hoped that what we pass in as CXXFLAGS also ends up being used for linking. But on second thought, I think that may not be very useful. I may eventually just add a cmake flag to switch on address and undefined behavior sanitizers. For now, the executables segfault somewhere in the sanitizer, after fixing #3098. I'll have to work on this more at some later time.

**Comment by drwells** [comment]
You can add these to the link flags, though it is not documented explicitly. I have a shell script that sets up all of the configuration options which starts with

```sh
if [ "$CXX" == "g++" ]; then
    DEBUG_FLAGS="-pipe -Wcast-align -Wsized-deallocation -Wvla -Wpacked"
    DEBUG_FLAGS+=" -Wunused-variable -Wlogical-op"
    DEBUG_FLAGS+=" -Wduplicated-cond -Whsa -Wsubobject-linkage -Wnull-dereference"
    DEBUG_FLAGS+=" -Wformat -Wmissing-include-dirs -Wmisleading-indentation"
    DEBUG_FLAGS+=" -fconcepts -fno-omit-frame-pointer"
    DEBUG_FLAGS+=" -fsanitize=undefined -fsanitize-recover=all -lubsan"
    RELEASE_FLAGS="-pipe -funsafe-loop-optimizations -floop-nest-optimize"
    RELEASE_FLAGS+=" -fconcepts -g"
    # RELEASE_FLAGS+=" -march=native"
    TRILINOS_STATE=ON
else
    TRILINOS_STATE=OFF
fi
```

followed by the actual call to CMake:

```sh
cmake -DCMAKE_INSTALL_PREFIX=~/Applications/dealii-dev/                                 \
      -DCMAKE_INSTALL_MESSAGE=LAZY                                                      \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                                                \
      -DDEAL_II_WITH_HDF5=ON                                                            \
# switch on just about everything else...
      -DDEAL_II_CXX_VERSION_FLAG="-std=c++14"                                           \
      -DDEAL_II_CXX_FLAGS_DEBUG="$DEBUG_FLAGS"                                          \
      -DDEAL_II_CXX_FLAGS_RELEASE="$RELEASE_FLAGS"                                      \
      -DDEAL_II_LINKER_FLAGS_DEBUG="-lubsan"                                            \
      ../
```

It is worth noting that linking now takes about 10 GB.

**Comment by tamiko** [comment]
@bangerth I would very much like to avoid to append `CXXFLAGS` to `LDFLAGS`. In principle, the linker could be different / a different compiler frontend. Further, it is better to simply delegate such decisions to CMake. (We, for example, do nowadays very little on our side to ensure correct rpaths, etc. - CMake does that for us.)

And in the end, simply populating `DEAL_II_LINKER_FLAGS` shouldn't be too hard :-)

**Comment by tamiko** [comment]
Where can I find the discussion for `expand_instantiations`?

**Comment by bangerth** [comment]
@tamiko -- I closed the issue because I came to the same conclusion, that it isn't useful to do this via setting `CXXFLAGS` and `LDFLAGS` by hand, but that one ought to do it by defining *features* in cmake.

The issue with `expand_instantiations` is that if you do set `CXXFLAGS` with certain flags, e.g., with the ubsan flags I had above, then you *need* to link also with these flags. That's what prompted me to originally think that the `CXXFLAGS` should also be appended to the linker flags. But it turns out that that is not even sufficient in that case -- in addition to the ubsan flags, you *also* have to link with `-lpthreads`, which of course cmake can't know until you actually teach it what all of that really means. At which time I came to realize that you're right.

**Comment by tamiko** [comment]
@bangerth

Well, the policy decision we made, namely to use CXXFLAGS (and
parts of LDFLAGS) for expand_instantiations as well, is nowhere near
pefect. This is why I asked.

We introduced this behavior to work around stupid/broken platforms where
we need to set certain CXXFLAGS/LDFLAGS in order to just make everything
compile. And we already faced an issue with ld.gold (if I remember
correctly). But every "solution" that comes to my mind is just even
more complicated than it already is. So, yes I agree as well, it might
be best to just keep it as it is. :-)

**Comment by bangerth** [comment]
Yes, correct. Magic is difficult.

(That is particularly true if we have front end nodes that compile for execution nodes, because then we need to differentiate between *host* tools such as `expand_instantiations` and the necessary tool chains, and the *target* tool chain for the rest of the compilation. I'm not sure we support this well right now, but I'm also not motivated to make it work. If these machines die out, the world will be a better place anyway!)

**Comment by tjhei** [comment]
> Yes, correct. Magic is difficult.

we could add something like ``DEAL_II_ENABLE_ADDRESS_SANITIZER`` or something that does the right magic.

**Comment by bangerth** [comment]
Yes, that's exactly what I had in mind until I found out that asan segfaults on my laptop for every test. That makes it a bit less useful.
