### ISSUE TITLE
Verify in multigrid that Triangulation is sufficiently smooth

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#310]
_From [dr.guido.kanschat](https://code.google.com/u/dr.guido.kanschat/) on August 22, 2013 18:28:58_

Multigrid methods will not complain if limit_level_difference_at_vertices is not set, but they produce wrong results at least with H1-conforming elements.

One of the multigrid classes should check whether this smoothness is needed, and if so, throw an exception if the Triangulation does not conform.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=98_

**Comment by masterleinad** [comment]
In `copy_local_forest_to_triangulation` (`distributed/tria.cc::2516`), we force `limit_level_difference_at_vertices` if `construct_multigrid_hierarchy` is set.
Is there a reason to leave this open?

**Comment by tjhei** [comment]
what about serial computations?

**Comment by masterleinad** [comment]
I thought that problem was restricted to `parallel::distributed::Triangulations`, but I might be mistaken here. I will investigate.

**Comment by tjhei** [comment]
The reason for the code in distributed/tria.cc::2516 is that I need this so I can determine cell neighbors correctly without communication, not to make the multigrid method converge.

**Comment by bangerth** [comment]
> what about serial computations?

In other words, you think that `p::d::Triangulation` is correct, but that `::Triangulation` may not, and also `p::s::Triangulation`.

**Comment by masterleinad** [comment]
We need ` limit_level_difference_at_vertices` to have the MGTransfer being sufficient, i.e. we only need to consider transferring information between two levels.

**Comment by masterleinad** [comment]
I would just assert to have `limit_level_difference_at_vertices` when calling `distribute_mg_dofs`.

**Comment by tjhei** [comment]
> I would just assert to have limit_level_difference_at_vertices when calling distribute_mg_dofs.

Yes, but it is currently allowed to construct a p:d:Triangulation without this flag set (even though it will temporarily set it in copy_local_forest_to_triangulation), so the assert would fail. We could set  limit_level_difference_at_vertices in the constructor if construct_multigrid_hierarchy is set?

**Comment by masterleinad** [comment]
In my opinion, we should be consistent and force `construct_multigrid_hierarchy` to be set if using multigrid no matter what kind of object the triangulation is. From what I can say, all the multigrid tests (i.e. ctest -R "multigrid") for `p::d::Triangulation` pass if I use `limit_level_difference_at_vertices` instead of `none` for `MeshRefinement`.

**Comment by bangerth** [comment]
I see nothing wrong with checking in `distributed_mg_dofs()` that the flag is set. If a user code aborts, they should just set the flag. Everything else runs afoul of the fact that the mesh is generated before the triangulation can know what it will be used for.
