### ISSUE TITLE
commit 3769e doesn't compile

### ISSUE THREAD

**Issue by inkstink** [dealii/dealii#3105]
Hi,

I get the following error when I try to compile the above mentioned commit.

Workspace/sandbox/dealii/source/base/index_set.cc:580:35: error: use of undeclared identifier 'MPI_UNSIGNED'
  MPI_Gather(&first_local_dof, 1, DEAL_II_DOF_INDEX_MPI_TYPE,

I am just starting to contribute to the code base so go easy on me if this isn't the correct place for this.  I am looking for advice.  I appreciate it.

**Comment by bangerth** [comment]
I think this was fixed a few seconds ago with #3104.

**Comment by inkstink** [comment]
Ok, I will pull that one. Thanks!
