### ISSUE TITLE
Better error for ParsedFunction

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3107]
Nan Zhang reported this for ASPECT:
---------------------------------
When I use function expression in my material model like:
*****************************************
subsection Material model
  set Model name = depth dependent
  subsection Depth dependent model
    set Base model = simple
    set Depth dependence method = Function
    subsection Viscosity depth function
      set Variable names      = r,phi,theta
      set Function expression = if( r>5670000, 5e21, 2e22 )
      #set Function expression = if( r>5670000, 5e21, (1e22*(22.72-8*r/2189e3)) )
    end
  end
  subsection Simple model 
    set Thermal expansion coefficient = 4e-5
    set Viscosity                     = 1e22
    set Thermal viscosity exponent = 8.0   #following 1 2 3
    set Reference temperature = 1600
    set Density differential for compositional field 1 = 165
  end
end
*****************************************
I got error report like:
*****************************************
FunctionParser failed to parse
FunctionParser failed to parse
FunctionParser failed to parse
         Viscosity depth function
         Viscosity depth function
with expression
with expression
         Viscosity depth function
FunctionParser failed to parse
with expression
FunctionParser failed to parse
FunctionParser failed to parse
        '       '        Viscosity depth function
        '        Viscosity depth function
with expression
with expression
if( r>5670000, 5e21, 2e22 )     ' 'FunctionParser failed to parse

------------------------------------

The fundamental mistake here is that the list of variables is `r,phi,theta`, but the function object we use is really only depth dependent, i.e., of type `Functions::ParsedFunction<1>`. In other words, it can't accommodate this many parameters, but the error message is completely unusable. This error message ought to get better.

**Comment by class4kayaker** [comment]
Reading through the code for the function parser, either it is not <1>, or it should have been caught by the AssertThrow at `parsed_function.cc:142`. I just checked, and it is <1> in the current master of ASPECT and has been for over a year, so it is necessary to identify why the mentioned error message was not given.

**Comment by bangerth** [comment]
Yes, ASPECT seems correct. I think we need to create a small testcase and see what error message we get and how that can be improved.

**Comment by class4kayaker** [comment]
I modified a depth dependent test case from Aspect to obtain
[depth_dependent_box_function_simple.prm.txt](https://github.com/dealii/dealii/files/472201/depth_dependent_box_function_simple.prm.txt), and as a result I obtained the following output with a reasonable error message, as I expected from examining the code.

```
-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 1.5.0-pre
--     . running in DEBUG mode
--     . running with 1 MPI process
--     . using Trilinos
-----------------------------------------------------------------------------

FunctionParser failed to parse
	 Viscosity depth function
with expression 
	' if(r>6.70e5,3.0e22,1.0e21);'

----------------------------------------------------
Exception on processing: 

--------------------------------------------------------
An error occurred in line <148> of file <##/deal.II-master/source/base/parsed_function.cc> in function
    void dealii::Functions::ParsedFunction<dim>::parse_parameters(dealii::ParameterHandler&) [with int dim = 1]
The violated condition was: 
    false
The name and call sequence of the exception was:
    ExcMessage("The list of variables specified is <" + vnames + "> which is a list of length " + Utilities::int_to_string(nn) + " but it has to be a list of length equal to" + " either dim (for a time-independent function)" + " or dim+1 (for a time-dependent function).")
Additional Information: 
The list of variables specified is <r,phi,theta> which is a list of length 3 but it has to be a list of length equal to either dim (for a time-independent function) or dim+1 (for a time-dependent function).
--------------------------------------------------------

Aborting!
----------------------------------------------------
```

I am therefore uncertain of the precise cause of the error described.

**Comment by bangerth** [comment]
I couldn't get feedback from the original reporter...
