### ISSUE TITLE
Regulate the distribution of the active cells on each core with p4est

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#311]
_From [fro...@mathematik.uni-siegen.de](https://code.google.com/u/109209230224152200061/) on August 22, 2013 21:16:04_

If there would be the possibility to use hp-adaptive refinement in parallel with p4est, it would be more efficient to regulate the distribution of the number of the active cells on each core.
This is also useful for elastoplastic contact simulation, where the assembling of plastified cells is more expansive than for elastic cells.
There should be already a function in p4est which can be used for this purpose.

Best, Joerg

_Original issue: http://code.google.com/p/dealii/issues/detail?id=99_

**Comment by bangerth** [comment]
This is addressed by #1131 .
