### ISSUE TITLE
does DEAL_II_INITIALIZE_CACHED_VARIABLES sets BOOST_DIR?

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3117]
A colleague of mine was figuring out how to link an extra  module of boost (`filesystem`) in his user project with deal.II. To that end he set
```
set(BOOST_ROOT ${BOOST_EXTERNAL})
```
before calling `find_package`. The downside is that he had to manually provide `-DBOOST_EXTERNAL=/same/boost/used/for/deal.ii/`. 

I did not see this documented, but does `DEAL_II_INITIALIZE_CACHED_VARIABLES()` sets `BOOST_DIR` (and the rest of `CmakeCache.txt`) when deal.II is configured with `boost`? If so, maybe it's worth mentioning in https://www.dealii.org/developer/users/cmakelists.html#cmakeadvanced.cached_variables. 

@tamiko do you happen to know the answer?

**Comment by tamiko** [comment]
> I did not see this documented, but does
> `DEAL_II_INITIALIZE_CACHED_VARIABLES()` sets `BOOST_DIR` (and the rest
> of `CmakeCache.txt`) when deal.II is configured with `boost`?

No, it doesn't.

Further, nothing in deal.II's project configuration does
something like that.

  find_package(deal.II ...)

guarantees

 - to only populate variables and macros prefixed with DEAL_II_
 - to not call into external project configuration

**Comment by davydden** [comment]
i see, thanks a lot for a swift reply.
