### ISSUE TITLE
Provide facilities to compute the most inclusive element in an hp::FECollection

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#313]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on January 25, 2014 04:57:31_

SolutionTransfer::prepare_for_coarsening_and_refinement has this lovely piece of code (or will at least soon):

```
      // take FE index from the child with most
      // degrees of freedom locally
      unsigned int most_general_child = 0;
      if (different_fe_on_children == true)
        for (unsigned int child=1; child<cell->n_children(); ++child)
          if (cell->child(child)->get_fe().dofs_per_cell >
              cell->child(most_general_child)->get_fe().dofs_per_cell)
            most_general_child = child;
      const unsigned int target_fe_index = 
           cell->child(most_general_child)->active_fe_index();
```

Comparing numbers of degrees of freedom is a really crude way to find out which element we can interpolate to from children that carry different FEs. We need to implement some functionality in hp::FECollection and the finite elements themselves that can provide this sort of information.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=177_

**Comment by davydden** [comment]
i think this PR might be useful to this issue https://github.com/dealii/dealii/pull/1488 . If one can assume that inclusion relationships on face are equal to inclusion relationships in volume, then the `find_least_face_dominating_fe( )` can be used, i suppose.

**Comment by bangerth** [comment]
@marcfehling -- this is sort of the opposite of the function you are looking for.

**Comment by marcfehling** [comment]
The function `compare_for_domination` provided in #7337 could be useful for this issue.

**Comment by bangerth** [comment]
@marcfehling -- is this functionality available now and could this issue be closed?

**Comment by marcfehling** [comment]
Not yet. A follow-up to #7899 will replace this code snippet for `SolutionTransfer`, and also for some other sections.
