### ISSUE TITLE
Building documentation in latest repo pull

### ISSUE THREAD

**Issue by cbcoutinho** [dealii/dealii#3131]
I am getting this error when trying to build the documentation along with dealii with the latest development repo and doxygen version 1.8.12

Without building the docs I don't get an error, but trying to build the docs (using the 'DEAL_II_COMPONENT_DOCUMENTATION' flag) produces the following result:

```
...
...
[ 23%] Building doxygen input file for tutorial program <step-47>
[ 23%] Built target tutorial_step-47
Scanning dependencies of target tutorial
[ 23%] Built target tutorial
Scanning dependencies of target doxygen
[ 23%] Generating header.html, footer.html
error: tag HTML_HEADER: header file `header.html' does not exist
make[2]: *** [doc/doxygen/CMakeFiles/doxygen.dir/build.make:610: doc/doxygen/header.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:446: doc/doxygen/CMakeFiles/doxygen.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

This is on an up-to-date version of openSUSE's rolling release: Tumbleweed

**Comment by davydden** [comment]
pls try with the current develop branch, see https://github.com/dealii/dealii/pull/3129

**Comment by cbcoutinho** [comment]
I just build the documentation with no errors, the last commit seems to have solved the problem. Thanks for the quick response regarding this problem.
