### ISSUE TITLE
Recognize libblas.so.3 and liblapack.so.3

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3142]
I've come across at least half a dozen systems on which the blas and lapack libraries are all of the following form:
```
bin/lib> ls -l /usr/lib64/libblas*
lrwxrwxrwx. 1 root root     16 Jul 20 05:20 /usr/lib64/libblas.so.3 -> libblas.so.3.2.1
lrwxrwxrwx. 1 root root     16 Jul 20 05:20 /usr/lib64/libblas.so.3.2 -> libblas.so.3.2.1
-rwxr-xr-x. 1 root root 354992 Aug 22  2010 /usr/lib64/libblas.so.3.2.1
```
and
```
bin/lib> ls -l /usr/lib64/liblapack*
lrwxrwxrwx. 1 root root      18 Jul 20 05:20 /usr/lib64/liblapack.so.3 -> liblapack.so.3.2.1
lrwxrwxrwx. 1 root root      18 Jul 20 05:20 /usr/lib64/liblapack.so.3.2 -> liblapack.so.3.2.1
-rwxr-xr-x. 1 root root 5258224 Aug 22  2010 /usr/lib64/liblapack.so.3.2.1
```
I tend to think that this is a packaging error to not create `libblas.so` and `liblapack.so`, but whatever the reason is: we don't find these libraries. If I have root rights on these machines, I just create a soft link in `/usr/lib64`, otherwise from my `$HOME/bin/lib` directory where I install software locally.

Given that I've had this problem so frequently, any kind of more generic option would be very much appreciated. For reference, the major version number is always 3, so searching for `libblas.so.3` in addition to `libblas.so` is all that's necessary, and same for lapack.

**Comment by tamiko** [comment]
@bangerth 
What linux distribution is this?

If this is a debian/ubuntu system you are simply missing the corresponding development packages `libblas-dev` and `liblapack-dev`. Similarly packages principles are followed in OpenSuSE with `blas-devel` and `lapack-devel`.

> I've come across at least half a dozen systems on which the blas and lapack libraries are all of the following form [...]

Are these all machines with the same Linux distribution and essentially same configuration?

**Comment by tamiko** [comment]
> I tend to think that this is a packaging error to not create `libblas.so` and `liblapack.so`.

Well, yes and no. A number of distributions split a package into a library and devel part. The first only contains the library without symlink, so for example `libfoo.so.2`, `libfoo.so.2.7`. The latter would have corresponding header and configuration files (pkgconfig, cmake, etc.) and the symlink `libfoo.so` -> `libfoo.so.2`.

It's just that with a fortran library you don't have much of a development package (essentially only containing the symlink and pkgconfig/cmake files).

**Comment by bangerth** [comment]
Ah, I see. But then surely I'm not the first one to make the mistake to install only one and not the other...

**Comment by drwells** [comment]
The situation where I think that this is most valuable would be when one is working on a cluster where the administrator does not install development versions of things and only `liblapack.so.3` is available. Less experienced people might not know how to get around this.

**Comment by bangerth** [comment]
That's the exact situation. I can work around it on my laptop.

I'll add that every time this happens to me, it is that I configure, build and install everything, just to find out that UMFPACK does not work. That's annoying. The reason of course is that UMFPACK is disabled if cmake can't find BLAS and LAPACK. But it only says that UMFPACK=OFF, not why, and I then have to spend 15 minutes finding out why that is so.

**Comment by drwells** [comment]
Since @tamiko and @davydden feel strongly that this approach is not right I think that we should consider an alternative: would it be acceptable (for the sake of closing the issue and making everyone happy) to print out a helpful error message saying something like "CMake could not find your BLAS and LAPACK libraries: it may be necessary to provide the full link path as `-DLAPACK_LIBRARIES=full/path/to/lapack.so.3;full/path/to/blas.so.3`" so that one can quickly fix the problem by giving CMake some more hints?

**Comment by davydden** [comment]
@drwells I think it's a good idea! 

@tamiko @bangerth what do you think?

**Comment by bangerth** [comment]
That would only make sense if these libraries indeed exist, i.e., we would have to search for them. 

But it does not address the problem that it's not obvious why UMFPACK was disabled. That was the core of my problem -- the chain from "want UMFPACK" to "needs BLAS" to "BLAS exists only as a .so.3" is lost in the first step. I don't see a good way to work around this.

**Comment by davydden** [comment]
maybe print out a warning that 

> UMFPACK is disabled as no Blas/Lapack was found

this together with a how-to for Blas/Lapack would probably be an ok workaround?

**Comment by tamiko** [comment]
I don't think that I did that of a terrible job of informing what is going on :smiley:. Unfortunately, by nature of our "autodetection" feature, you have to explicitly ask for getting information, i.e., as long as a user does not issue a configure command of the form
```
  $ cmake -DWITH_LAPACK=ON -DWITH_UMFPACK=ON ..
```
no error message will be printed.



> UMFPACK is disabled as no Blas/Lapack was found

We currently print the following information:
```
$ cmake -DWITH_LAPACK=OFF ..
[...]
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_umfpack.cmake
-- DEAL_II_WITH_UMFPACK has unmet configuration requirements: DEAL_II_WITH_LAPACK has to be set to "ON".
[...]
```

I doubt that making this a warning will help much at all. It will be buried under the following configure output as well.

For reference, the current error messages in question are

```
$ cmake -DWITH_UMFPACK=ON ..
[...]
CMake Error at cmake/macros/macro_configure_feature.cmake:204 (MESSAGE):
  
  DEAL_II_WITH_UMFPACK has unmet configuration requirements:
  DEAL_II_WITH_LAPACK has to be set to "ON".
```


```
$ cmake -DWITH_LAPACK=ON -DWITH_UMFPACK=ON ..
[...]
CMake Error at cmake/macros/macro_configure_feature.cmake:121 (MESSAGE):

  Could not find the lapack library!

  Please ensure that a suitable lapack library is installed on your computer.

  If the library is not at a default location, either provide some hints for
  autodetection,

      $ LAPACK_DIR="..." cmake <...>
      $ cmake -DLAPACK_DIR="..." <...>

  or set the relevant variables by hand in ccmake.
```

If someone wants to improve the last error message, it can be overwritten by setting
`FEATURE_LAPACK_ERROR_MESSAGE` in `cmake/configure/configure_1_lapack.cmake`, have a look at `cmake/configure/configure_2_umfpack.cmake`.

**Comment by tamiko** [comment]
@bangerth 
> But it does not address the problem that it's not obvious why UMFPACK was disabled. That was the core of my problem -- the chain from "want UMFPACK" to "needs BLAS" to "BLAS exists only as a .so.3" is lost in the first step. I don't see a good way to work around this.

I don't know what we can improve to remedy the last step. We could add a hint to above (the last) error message basically asking "Have you installed blas-devel/lapack-devel packages?".

**Comment by tamiko** [comment]
@bangerth
> But it does not address the problem that it's not obvious why UMFPACK was disabled.

The possible configure log notices are the following:

```
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_umfpack.cmake
-- DEAL_II_WITH_UMFPACK has unmet configuration requirements: DEAL_II_WITH_LAPACK has to be set to "ON".
```

```
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_umfpack.cmake
-- DEAL_II_WITH_UMFPACK is set to off.
```

```
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_umfpack.cmake
-- [...]
-- UMFPACK_LIBRARY not found! Call:
--     FIND_LIBRARY(UMFPACK_LIBRARY NAMES umfpack libumfpack HINTS /UMFPACK /../UMFPACK /UMFPACK PATH_SUFFIXES lib lib64 lib Lib UMFPACK/Lib)
--   UMFPACK_LIBRARIES: *** Required variable "UMFPACK_LIBRARY" set to NOTFOUND ***
-- Could NOT find UMFPACK
-- DEAL_II_WITH_UMFPACK has unmet external dependencies.
```

**Comment by bangerth** [comment]
Yes, I don't know either how to address this in a different way -- the error messages are all there, they're just buried in tons of other output. The thing I tried to address was that (i) if I just say `cmake ../deal.II-8.4.1, I was expecting UMFPACK to be switched on, but (ii) that didn't happen and (iii) the cause was not obvious without significant digging (which included to *explicitly* require UMFPACK).

Let's just call it a day on this issue. I know what to do, and nobody seems to have a particularly good idea of how to solve this issue. It may also be something that's specific to just my machines. Let's close this issue. We can always re-open it if someone else has this problem.

**Comment by tamiko** [comment]
> if I just say `cmake ../deal.II-8.4.1, I was expecting UMFPACK to be switched on

Well, this is something that we can change. Similarly to MPI being disabled by default, we could enable blas/lapack and umfpack support by default.

The downside is that a number of user will run into a non-trivial configure error (and would have to supply `-DWITH_LAPACK=OFF -DWITH_UMFPACK=OFF` manually).

**Comment by bangerth** [comment]
Yes, that's possible. I'm not sure it's a widespread enough problem, though. Let's just leave it where we left it.
