### ISSUE TITLE
Inconsistent interface between Trilinos and PETSc wrappers

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#315]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on March 15, 2014 03:32:44_

Following a thread on the mailing list, we seem to have an inconsistent set of interfaces between PETSc and the other matrix types. We should deprecate the old functions and add the ones that make the interface consistent.

Following the relevant messages:
.................................................................

It looks like the order of the parameters is switched for Petsc matrices vs Trilinos ones. http://dealii.org/8.1.0/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrix.html#a791d1d6a8e7f78f32c276350ee44fa6c http://dealii.org/8.1.0/doxygen/deal.II/classPETScWrappers_1_1MatrixBase.html#a4ebcb9648709b8ccb058b72214b8fdb8 On Wednesday, March 5, 2014 10:14:29 PM UTC+1, Gennadiy Rishkin wrote:

    Hi,

    Doing:

    system_matrix.add( theta*time_step, laplace_matrix );

    works perfectly with Trilinos but with PETSc, it gives the error below:

    /home/grishk/TEST/main.cc: In member function ‘void TestEquation<dim>::assemble_system()’:
    /home/grishk/TEST/main.cc:463:53: error: no matching function for call to ‘dealii::PETScWrappers::MPI::SparseMatrix::add(double&, dealii::LinearAlgebraPETSc::MPI::SparseMatrix&)’
      system_matrix.add( theta*time_step, laplace_matrix );
                                                         ^
    /home/grishk/TEST/main.cc:463:53: note: candidates are:
    In file included from /home/grishk/dealII/include/deal.II/lac/petsc_parallel_sparse_matrix.h:25:0,
                     from /home/grishk/dealII/include/deal.II/lac/generic_linear_algebra.h:50,
                     from /home/grishk/TEST/main.cc:18:
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1653:3: note: void dealii::PETScWrappers::MatrixBase::add(dealii::PETScWrappers::MatrixBase::size_type, dealii::PETScWrappers::MatrixBase::size_type, PetscScalar)
       MatrixBase::add (const size_type   i,
       ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1653:3: note:   candidate expects 3 arguments, 2 provided
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1684:3: note: void dealii::PETScWrappers::MatrixBase::add(const std::vector<unsigned int>&, const dealii::FullMatrix<double>&, bool)
       MatrixBase::add (const std::vector<size_type>  &indices,
       ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1684:3: note:   no known conversion for argument 1 from ‘double’ to ‘const std::vector<unsigned int>&’
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1701:3: note: void dealii::PETScWrappers::MatrixBase::add(const std::vector<unsigned int>&, const std::vector<unsigned int>&, const dealii::FullMatrix<double>&, bool)
       MatrixBase::add (const std::vector<size_type>  &row_indices,
       ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1701:3: note:   candidate expects 4 arguments, 2 provided
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1720:3: note: void dealii::PETScWrappers::MatrixBase::add(dealii::PETScWrappers::MatrixBase::size_type, const std::vector<unsigned int>&, const std::vector<double>&, bool)
       MatrixBase::add (const size_type                 row,
       ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1720:3: note:   candidate expects 4 arguments, 2 provided
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1736:3: note: void dealii::PETScWrappers::MatrixBase::add(dealii::PETScWrappers::MatrixBase::size_type, dealii::PETScWrappers::MatrixBase::size_type, const size_type*, const PetscScalar*, bool, bool)
       MatrixBase::add (const size_type    row,
       ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:1736:3: note:   candidate expects 6 arguments, 2 provided
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:962:17: note: dealii::PETScWrappers::MatrixBase& dealii::PETScWrappers::MatrixBase::add(const dealii::PETScWrappers::MatrixBase&, PetscScalar)
         MatrixBase &add (const MatrixBase &other,
                     ^
    /home/grishk/dealII/include/deal.II/lac/petsc_matrix_base.h:962:17: note:   no known conversion for argument 1 from ‘double’ to ‘const dealii::PETScWrappers::MatrixBase&’

_Original issue: http://code.google.com/p/dealii/issues/detail?id=193_

**Comment by masterleinad** [comment]
Fixed by #2749.
