### ISSUE TITLE
Document iterators at the place where they are typedef'ed

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#316]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on April 09, 2014 12:46:51_

I don't know why this took me 16 years to realize: People always have trouble figuring out which class actually implements the particular iterator they look at (rightfully so, the structure is complicated). There is even a report on just this issue.

What we should be doing is point to the concrete type each iterator represents _at the place where they are typedef'ed_ in the Triangulation and DoFHandler classes.

I don't have the time right now but will get to it before the next release.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=198_

**Comment by bangerth** [comment]
Well, took only 4.5 years :-)

**Comment by drwells** [comment]
It did take four patches over a year and a half.
