### ISSUE TITLE
disallow set_boundary_id() on internal face

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3160]
As it comes up time and time again (see for example https://groups.google.com/d/topic/dealii/gNVDGaaEe2k/discussion ), we should guard against somebody setting a boundary indicator on an internal face by accident.

**Comment by tjhei** [comment]
Currently we store 255 for internal boundaries. I wonder if we can just add something like
`` Assert(boundary_id()!=255, ...)``

**Comment by bangerth** [comment]
You need a way to set the 255 initially (or any other value) without possibly triggering an assertion. Other than that, it should be simple enough.

**Comment by masterleinad** [comment]
Fixed by #3186
