### ISSUE TITLE
Documented definition of second invariant for rank-2 tensors

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3164]
I'm not 100% sure about this, but I have a concern about the definition of the second invariant of a tensor provided in the documentation. Here's the definition on the [wikipedia entry](https://en.wikipedia.org/wiki/Invariants_of_tensors#Calculation_of_the_invariants_of_symmetric_3.C3.973_tensors) for 3x3 tensors
![Second invariant for 3x3 tensor](http://mathurl.com/j5eheas.png) 
, which is the same as the definition in the documentation. This is also the definition typically given in continuum mechanics textbooks. I note however that the implementation in deal.II uses the expanded format specialised for each space dimension, so this does not apply to the implementation itself.

I think that the general definition for any dimension d>1 of tensor is
![Second invariant for dim x dim tensor](http://mathurl.com/h6wuc64.png)
The motivation is as follows:
Consider, C to be the [d x d] identity matrix. Then
![Invariant calculations: Definitions](http://mathurl.com/hrfwo2m.png).
From the traditional definition
![Invariant calculations: Traditional](http://mathurl.com/hzps3tj.png)
while with the "dimension dependent" definition for d>1
![Invariant calculations: Dimensional dependent](http://mathurl.com/j8jze4p.png)

This property that the first and second invariants of the identity tensor are equal to the spatial dimension is important, for example in nonlinear elasticity where the stored energy of an undeformed [Mooney-Rivlin](https://en.wikipedia.org/wiki/Mooney%E2%80%93Rivlin_solid) solid is zero.

**Comment by davydden** [comment]
>  I have a concern about the definition of the second invariant of a tensor provided in the documentation

could you add a link to where this is documented? (maybe just edit the OP)

>  I note however that the implementation in deal.II uses the expanded format specialised for each space dimension, so this does not apply to the implementation itself.

so what is actually implemented in deal.II now, `1/2` or `1/dim-1`?


p.s. I checked a book we followed for Tensor calculus and the second invariant is defined with `1/2` there. But this was for a tensor in 3D and came from
![j2](https://cloud.githubusercontent.com/assets/8023934/18914920/56a4ec5c-858f-11e6-8752-e75a4c777abe.jpg)

**Comment by jppelteret** [comment]
The current implementation is
![Implementation of second invariant](http://mathurl.com/hdqkoy6.png)
and, as I said, is correct. Its the documented definition that I think is wrong (it doesn't hold for dim=2).

I can't give a link to the documentation since the website is down... but here's a snippet of the url if you have a locally installed doc: `doxygen/deal.II/classSymmetricTensor.html#a7bbdfc57da6931de6a1757a0fa7ee982`

**Comment by davydden** [comment]
>  Its the documented definition that I think is wrong (it doesn't hold for dim=2).

i see.

**Comment by jppelteret** [comment]
Whoops, I made an incorrect statement. Looking at the implementation for dim=1 and dim=2, my assertion that `(I2 - dim) == 0` doesn't hold for the current implementation either. I must be missing something here. I'm going to write a quick program to check this...

**Comment by bangerth** [comment]
Make that into a testcase :-)

**Comment by davydden** [comment]
and then you can also update documentation within the same PR to close this issue.

**Comment by jppelteret** [comment]
Will do. I'll try to find a source for the general definition of the invariants.

**Comment by jppelteret** [comment]
Hmm... I've made a mistake. It would seem like my original assertion that `I2(I) - dim = 0` for `dim  > 1` is incorrect in this case, and my "intuitive" alternative is utter nonsense. 

There are different ways of defining the second invariant, and for the chosen definition [1,2] this clearly does not hold. For the alternative definition [3] `I2(C) = C:C` my assertion holds. This is most evident when comparing their descriptions as given in terms of the principle values:
![Principle value decomposition](http://mathurl.com/gnpj9pm.png)

So, for those who wish to question fundamental definitions, here's an example showing that it may very well be a good idea more reading before asking silly questions! And for those who are implementing nonlinear elasticity, user beware :-)

References:
[1] Holzapfel, Nonlinear solid mechanics, 2007, eq. 1.171
[2] Wriggers, Nonlinear finite element methods, 2008, Appendix A
[3] Bonet & Wood, Nonlinear continuum mechanics for finite element analysis, 1997, eq. 2.53, eq. 2.60b
