### ISSUE TITLE
compile error in FE_Enriched

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3180]
My gcc 4.6.3 doesn't like your FE_Enriched @davydden, is this because of the delegating constructor?
```
/ssd/deal-git/source/fe/fe_enriched.cc: In constructor ‘dealii::FE_Enriched<dim, spacedim>::FE_Enriched(const dealii::FiniteElement<dim, spacedim>&, const dealii::FiniteElement<dim, spacedim>&, const dealii::Function<spacedim>*) [with int dim = 1, int spacedim = 1]’:
source/fe/fe_enriched.inst:11:17:   instantiated from here
/ssd/deal-git/source/fe/fe_enriched.cc:137:2: error: type ‘dealii::FE_Enriched<1, 1>’ is not a direct base of ‘dealii::FE_Enriched<1, 1>’
source/fe/fe_enriched.inst:11:17:   instantiated from here
/ssd/deal-git/source/fe/fe_enriched.cc:137:2: error: no matching function for call to ‘dealii::FiniteElement<1, 1>::FiniteElement()’
/ssd/deal-git/source/fe/fe_enriched.cc:137:2: note: candidates are:
/ssd/deal-git/include/deal.II/fe/fe.h:689:3: note: dealii::FiniteElement<<anonymous>, <anonymous> >::FiniteElement(const dealii::FiniteElementData<dim>&, const std::vector<bool>&, const std::vector<dealii::ComponentMask>&) [with int dim = 1, int spacedim = 1]
/ssd/deal-git/include/deal.II/fe/fe.h:689:3: note:   candidate expects 3 arguments, 0 provided
/ssd/deal-git/include/deal.II/fe/fe.h:569:7: note: dealii::FiniteElement<1, 1>::FiniteElement(const dealii::FiniteElement<1, 1>&)
/ssd/deal-git/include/deal.II/fe/fe.h:569:7: note:   candidate expects 1 argument, 0 provided
source/fe/fe_enriched.inst:11:17:   instantiated from here
/ssd/deal-git/source/fe/fe_enriched.cc:124:1: error: uninitialized member ‘dealii::FE_Enriched<1, 1>::is_enriched’ with ‘const’ type ‘const bool’ [-fpermissive]
/ssd/deal-git/source/fe/fe_enriched.cc:137:2: error: no matching function for call to ‘dealii::FESystem<1, 1>::FESystem()’
```

**Comment by davydden** [comment]
i suppose 4.6.3 does not implement all the C++11 features, it must be indeed related to delegating constructors which i used heavily. 

@tamiko shall we add a unit test for this part of C++11 and disable this part of the library if compiler does not provide it?

**Comment by davydden** [comment]
from http://en.cppreference.com/w/cpp/compiler_support delegating constructors starts from `gcc@4.7`.

**Comment by davydden** [comment]
indeed, this feature is not in `4.6` https://gcc.gnu.org/gcc-4.6/cxx0x_status.html.

**Comment by davydden** [comment]
an alternative it to mark `4.6.x` as not `c++11` since, strictly speaking, it does not implement all the c++11 features.

**Comment by tjhei** [comment]
> an alternative it to mark 4.6.x as not c++11 since, strictly speaking, it does not implement all the c++11 features.

I don't like that suggestion. Then I would vote against dropping support for non-cxx11 compilers for the foreseeable future because that is what I am running here.

> @tamiko shall we add a unit test for this part of C++11 and disable this part of the library if compiler does not provide it?

You want to disable FE_Enriched? How much work would be to make your code work without delegating constructors? That sounds like the easiest and most compatible solution to me.

**Comment by davydden** [comment]
> How much work would be to make your code work without delegating constructors? That sounds like the easiest and most compatible solution to me.

I am exactly against this one :smile:. Not idea how much work, but it is **not** a solution per-se.

The code is clean and modern and complies with C++11. Since we plan to move to C++11 in near future i don't see any reason why the code should degrade. An option to have an extra `DEAL_II_CXX11_DELEGATE_CONSTRUCTOR` define is my preffered workaround until C++11 is required in `9.0` or alike.

**Comment by davydden** [comment]
> That sounds like the easiest

disagree.

**Comment by davydden** [comment]
> Disable the whole class if delegate constructors are not supported

I am for that solution, which I suggested at the very beginning https://github.com/dealii/dealii/issues/3180#issuecomment-251224368
