### ISSUE TITLE
Functions in GridGenerator need more documentation

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#320]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on May 07, 2014 22:25:04_

The functions in namespace GridGenerator should be more explicit about the fact that you need to apply a boundary object to the geometry so generated for it all to work when you actually refine the mesh.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=212_

**Comment by drwells** [comment]
This is closed by #6274 :)
