### ISSUE TITLE
Crash with a trivial mesh from gMsh  

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#3201]
I created a 2-cell mesh with gMsh 2.13 (releases 22.08.16) and got this:

> An error occurred in line <897> of file </lib/dealii-dev/source/grid/grid_reordering.cc> in function
>     static void dealii::GridReordering<dim, spacedim>::invert_all_cells_of_negative_grid(const std::vectordealii::Point<spacedim >&, std::vectordealii::CellData<dim >&) [with int dim = 2; int spacedim = 2]
> The violated condition was: 
>     n_negative_cells==0 || n_negative_cells==cells.size()
> Additional Information: 
> This class assumes that either all cells have positive volume, or that all cells have been specified in an inverted vertex order so that their volume is negative. (In the latter case, this class automatically inverts every cell.) However, the mesh you have specified appears to have both cells with positive and cells with negative volume. You need to check your mesh which cells these are and how they got there.
> As a hint, of the total 2 cells in the mesh, 1 appear to have a negative volume.

Here is a sketch of the mesh with point numbers and their ordering (hope I draw arrows correctly) produced by gMsh (last four numbers are indices of corresponding vertices):
![mesh](https://cloud.githubusercontent.com/assets/8438035/19108666/f9d7704a-8af1-11e6-8bb1-38b213ee3869.png)

I guess errors arises because of that (doc GridIn):

> For quadrilaterals in two dimensions, the vertex indices in the quad list have to be such that the vertices are numbered in counter-clockwise sense.

There is a tool `https://github.com/martemyev/tethex/wiki`(@martemyev) that converts Tet meshes from gMsh to Hex meshes with dealii-conforming ordering. Its wiki page says that vertex ordering "bug" should long have been fixed, but apparently the issue persists.

I just wanted to summarize the current state of the problem because I try to think of workflows which potential users of deal.II-based modeling codes (including mine) can adopt. gMsh is practially the only freely available hex-generator and it's a pitty if people cannot use it. Toolchain gMsh -> tethex -> deal.II-based-code is an option (if you accept overhead in terms of number of elements coming from it), but not very attractive one if you promote your code among potential users, who are generally not experts in numerical methods. 

Is there anything that can be done within gMsh or GridIn::read_msh to overcome this?

**Comment by agrayver** [comment]
Changing order from "3 4 5 6" to "4 3 6 5" for the first element solves the problem. 

Can one write read_msh specific routine that would go through all elements and change ordering? Will this naive approach work in general?

**Comment by martemyev** [comment]
Hi Alexander,

> Toolchain gMsh -> tethex -> deal.II-based-code is an option (if you accept overhead in terms of number of elements coming from it)

There is no overhead in terms of number of elements coming from tethex if it is fed with a hexahedral/quadrilateral mesh. Tethex will only try to fix the order of vertices from the input mesh if it's incorrect. In fact, if you run tethex with those elements:
'''
$Elements
2
1 3 2 12 9 3 4 5 6
2 3 2 12 11 3 4 1 2
$EndElements
'''
you should get the following output:
'''
$Elements
2
1 3 2 12 9 3 6 5 4
2 3 2 12 11 3 4 1 2
$EndElements
'''
which is pretty much the same as your solution.

Hope this helps.

Cheers,
Mikhail

**Comment by bangerth** [comment]
@agrayver -- I think I don't quite understand where the offending file came from. Was it created "as is", i.e., without any modification by gmsh?

**Comment by agrayver** [comment]
@bangerth 
> I think I don't quite understand where the offending file came from. Was it created "as is", i.e., without any modification by gmsh?

It comes from gMsh, I just meshed and saved the mesh. 

> There is no overhead in terms of number of elements coming from tethex if it is fed with a hexahedral/quadrilateral mesh. Tethex will only try to fix the order of vertices from the input mesh if it's incorrect.

Ah, I see. I didn't know it can do only reordering for purely hex meshes! Well, in this case, why not making it part of read_msh method? 

I hit this problem first time a couple of years ago, situation is still the same. There are other people on the mailing list who had this. If we extract the reordering part from tethex and call it inside read_msh, this solves the problem?

For record, here is *.geo file:
> // Gmsh project created on Tue Oct 04 16:47:38 2016
> Point(1) = {-200, 0, 0, 600};
> Point(2) = {200, 0, 0, 600};
> Point(3) = {200, 400, 0, 600};
> Point(4) = {-200, 400, 0, 600};
> Point(5) = {-200, 800, 0, 600};
> Point(6) = {200, 800, 0, 600};
> Line(1) = {5, 6};
> Line(2) = {4, 3};
> Line(3) = {1, 2};
> Line(4) = {5, 4};
> Line(5) = {4, 1};
> Line(6) = {6, 3};
> Line(7) = {3, 2};
> Line Loop(9) = {1, 6, -2, -4};
> Plane Surface(9) = {9};
> Line Loop(11) = {3, -7, -2, 5};
> Plane Surface(11) = {11};

**Comment by agrayver** [comment]
@bangerth would you take a patch that does reordering (same as tethex is doing) of vertices inside read_msh? Without this, support of gMsh produces meshes is very much limited.

**Comment by agrayver** [comment]
Looking more carefully I see now that tethex does exactly the same thing as deal.II in [GridReordering::invert_all_cells_of_negative_grid](https://github.com/dealii/dealii/blob/8d2b4ea6e081d454bc1c084ebbd83bbda195201b/source/grid/grid_reordering.cc#L1017)

But you choose to be conservative (which might be a good strategy) and throw an exception at [grid_reordering.cc#L1038](https://github.com/dealii/dealii/blob/8d2b4ea6e081d454bc1c084ebbd83bbda195201b/source/grid/grid_reordering.cc#L1038)

Commenting this assertion produces exactly identical result as the gMsh -> tethex -> deal.II chain, except you don't need tethex. 

So, if you need gMsh to be compatible with deal.II, you may want to comment this assertion, with all responsibility that comes with this.

**Comment by bangerth** [comment]
@agrayver -- I think I still don't quite understand what is happening, but would like to do so. Am I correct that (i) you created a mesh with gmsh, (ii) wrote it into a .msh file, (iii) tried to read it via `GridIn::read_msh()`, and (iv) this resulted an an inverted cell?

I checked the testsuite, and there are a number of tests that read 3d meshes in .msh format. It is of course possible that all of them result in inverted meshes if we have a bug in mapping the order of vertices in .msh files to the order of vertices required by deal.II. That would definitely be worth fixing. But I would like to understand the issue better first.

**Comment by agrayver** [comment]
@bangerth 
(i),(ii),(iii) -- yes.

> (iv) this resulted an an inverted cell?

This resulted in an exception quoted at the top. The reason for this is that gMsh does not seem to put any constraints on the ordering and can produce *.msh files with both clockwise and counterclockwise ordering (as in the example above).

tethex written by @martemyev [inverts vertex order](https://github.com/martemyev/tethex/blob/master/tethex.cpp#L1789) to make it deal.II-conforming. (I consider 2D for simplicity, although it's the same for 3D).

deal.II has exactly the same code [here](https://github.com/dealii/dealii/blob/8d2b4ea6e081d454bc1c084ebbd83bbda195201b/source/grid/grid_reordering.cc#L1017) to invert cells, but you later require that either all or none of the cells are inverted. 

The bottom question is that after inverting a cell you do [check ](https://github.com/dealii/dealii/blob/8d2b4ea6e081d454bc1c084ebbd83bbda195201b/source/grid/grid_reordering.cc#L1027) that it is not degenerate. In this case, why wouldn't you allow it to proceed without this [exception](https://github.com/dealii/dealii/blob/8d2b4ea6e081d454bc1c084ebbd83bbda195201b/source/grid/grid_reordering.cc#L1038)? 

I cannot say in general, but all cases I have tested with mixed ordering worked eventually fine if I comment this assert.

**Comment by tjhei** [comment]
fixed by #13444. It only took a couple of years. ;-)
