### ISSUE TITLE
FE_Enriched compiler improvements

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3209]
As seen in #3180 and #3207, there were some problems with gcc 4.6.x (missing delegating constructors) and gcc 4.7.x (some other problem?) with a work-around in #3208.

We need to investigate:
- What is the earliest version of gcc that can compile FE_Enriched?
- Is the current solution to enforce cxx14 sufficient?
- Can we adapt the code to support 4.7.x? That might be possible.
- Can we find a better solution than enforcing cxx14?

**Comment by bangerth** [comment]
I think it should be enough to just replace the brace enclosed initializer with an explicit call to the constructor. This would work well here because we create a vector with only one element, for which we can just use the old vector constructor.

**Comment by bangerth** [comment]
Partially addressed by #3212.

**Comment by kostyfisik** [comment]
docs should be updated at  https://dealii.org/developer/doxygen/deal.II/group__CPP11.html too, section "Things that are only enabled if your compiler supports C++11"

**Comment by bangerth** [comment]
Thanks, @kostyfisik , for pointing this out! #3214 updates the list.

**Comment by kostyfisik** [comment]
it now compiles well on my centos 6.8 box with checkout at
[tig@rh-lum dealii-git]$ git log
commit c16afcdb0f39288e31b097732772287487bd92b8

**Comment by tjhei** [comment]
> it now compiles well on my centos 6.8 box

 you mean including #3212 but without  #3208 ?

**Comment by kostyfisik** [comment]
I do not really know. I just compiled the master branch, the problem has gone.

**Comment by davydden** [comment]
> What is the earliest version of gcc that can compile FE_Enriched?

The following c++11 features are used:

- Delegating constructors ( `gcc@4.7`, based on https://gcc.gnu.org/projects/cxx-status.html#cxx11 )
- ~~Initializer lists~~ got removed in https://github.com/dealii/dealii/pull/3212

> Is the current solution to enforce cxx14 sufficient?

i would say so

> Can we adapt the code to support 4.7.x? That might be possible.

I will try to check it with `4.7.4` tomorrow, but I am not in favour making code less clean just to support the old version of a compiler. Especially given the fact that we will move to c++11 in 9.0.

> Can we find a better solution than enforcing cxx14?

unless we really check for features and don't have just `c++11` but `c++11_feature_a` -- probably not.
