### ISSUE TITLE
intel test failures

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3211]
I set up a nightly test run with the intel compiler again and I see some scary test failures in release mode. I assume that these are miscompilations:
- wrong derivatives in base/anisotropic_1.release https://cdash.kyomu.43-1.org/testDetails.php?test=6197054&build=1742
- wrong results in bits/chunk_sparse_matrix_vector_05.release https://cdash.kyomu.43-1.org/testDetails.php?test=6192216&build=1742 (this is not an off by epsilon but 4.75004e+09 vs4.96617e+09)
- broken multigrid solvers multigrid/step-16-50-mpi.mpirun=7.release https://cdash.kyomu.43-1.org/testDetails.php?test=6190354&build=1742 https://cdash.kyomu.43-1.org/testDetails.php?test=6190928&build=1742
- broken multigrid transfer multigrid/transfer_03.release https://cdash.kyomu.43-1.org/testDetails.php?test=6191187&build=1742

see https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1742

I don't have time to look at those problems right now, but we need to look at this before the next release.

**Comment by drwells** [comment]
@tjhei Should we close #2203 and focus our efforts here? You have the same list in both issues :)

**Comment by tjhei** [comment]
I have zero recollection of creating that issue. That shows scatterbrained I am these days. ;-)

**Comment by tamiko** [comment]
@tjhei Unfortunately, the cdash instance saw its quarterly sledgehammer. Are the results [1] from Heidelberg comparable?

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=4263

**Comment by drwells** [comment]
@tjhei In #3893 you mentioned that the latest intel compiler works. Does that mean that these tests now pass and we can close this?

**Comment by tjhei** [comment]
Yes, thanks for the reminder.
