### ISSUE TITLE
Have member functions in DoFHandler to compute cell colorization

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#322]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on May 15, 2014 18:23:39_

To support multithreading better, we should provide default ways to get colorized arrays of cells, like we use in the paper with Turcksin and Kronbichler.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=215_

**Comment by drwells** [comment]
I believe `base/graph_coloring.h` implemented everything we need.
