### ISSUE TITLE
Show parallel adaptive multigrid in step-37

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#3222]
The `step-37` tutorial program should be changed to use parallel multigrid techniques with `parallel::distributed::Vector<double>` including hanging nodes. The extension is reasonably simple to combine it with the first tutorial on matrix-free as it only adds a few lines to the program. The code for parallel adaptive multigrid is already here: https://github.com/dealii/dealii/blob/master/tests/matrix_free/parallel_multigrid_adaptive_mf.cc

When re-writing the program, we should also include a comment on local smoothing with multigrid and the behavior of the vector assembly routines with hanging nodes as discussed in #3221.

Relates to #3072.

**Comment by kronbichler** [comment]
Since #3252 provides an infrastructure for the multigrid implementation, the new code should either use the `MatrixFreeOperators::Base` operator or implement those data structures for clarity and explain the availability of the `Base` operator in the results section as a tool provided by the library regarding the multigrid implementation. Since the things to show for `MatrixFree` are quite lengthy already I'd be inclined to use the `Base` operator.

**Comment by davydden** [comment]
> Since the things to show for MatrixFree are quite lengthy already I'd be inclined to use the Base operator.

Agreed. I would briefly mention this in tutorial and if you wish, add more discussion in the documentation of `MatrixFreeOperators::Base`.
