### ISSUE TITLE
Square shortcut

### ISSUE THREAD

**Issue by kostyfisik** [dealii/dealii#3227]
Not a big issue, but sometimes evaluating a square power of an expression looks overcomplicated while it actually should not. I use a shortcut which I usually put to the top of the file, but probably it can be put somewhere to dealii namespace?

As an example, an evaluation from step-29, to the second notation is easier to read and to understand, while for the first case it is easier to mess the indices by excedent.  Pow2 notation is rather easy to remember and quite intuitive, the first time I met it was a numerical library blitz++.
 
```c++
template <class T> inline T pow2(const T value) { return value * value; }

computed_quantities[i](0) = std::sqrt(uh[i](0)*uh[i](0) + uh[i](1)*uh[i](1));

computed_quantities[i](0) = std::sqrt( pow2(uh[i](0)) + pow2(uh[i](1)) );
```

**Comment by davydden** [comment]
there is a `fixed_power` in Utilities, which I use quote often https://www.dealii.org/developer/doxygen/deal.II/namespaceUtilities.html#a834c6b595ada6f8e73c78d9bbd8ec551

**Comment by bangerth** [comment]
In other places, we have introduced a function `square()` or `sqr()`. But in the end I don't think that any such function is more readable than `fixed_power()`.
