### ISSUE TITLE
Error While Compiling with gcc 5.2.0 and 

### ISSUE THREAD

**Issue by clarkpede** [dealii/dealii#3229]
I got the error "no instance of overloaded function "atomicMax" matches the argument list" in dealii/include/deal.II/lac/cuda_atomic.cuh when compiling dealii.  Here's the error message I got:

```
[ 59%] Building NVCC (Device) object source/lac/CMakeFiles/obj_lac_release.dir/obj_lac_release_generated_cuda_vector.cu.o
/opt/apps/ossw/applications/gcc/gcc-5.2/c7/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/opt/apps/ossw/applications/gcc/gcc-5.2/c7/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/workspace/dealii/include/deal.II/lac/cuda_atomic.cuh(97): error: no instance of overloaded function "atomicMax" matches the argument list
            argument types are: (unsigned long long *, unsigned long long)

3 errors detected in the compilation of "/tmp/tmpxft_00002d68_00000000-7_cuda_vector.cpp1.ii".
CMake Error at obj_lac_release_generated_cuda_vector.cu.o.cmake:268 (message):
  Error generating file
  /workspace/dealii/build/source/lac/CMakeFiles/obj_lac_release.dir//./obj_lac_release_generated_cuda_vector.cu.o


make[2]: *** [source/lac/CMakeFiles/obj_lac_release.dir/obj_lac_release_generated_cuda_vector.cu.o] Error 1
make[1]: *** [source/lac/CMakeFiles/obj_lac.release_cuda.dir/all] Error 2
```

I am running on a CentOS system with gcc 5.20, cmake 3.3.2, and I was using the git commit 92e0dfdfa7e97c0411da473854100455e8e6fb11

Since your website states that "GCC version 4.6 or later" is supported, gcc 5.20 should be supported.

**Comment by clarkpede** [comment]
Here's my configuration:

#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       DebugRelease
#        BUILD_SHARED_LIBS:      ON
#        CMAKE_INSTALL_PREFIX:   /workspace/dealii-8.4.1
#        CMAKE_SOURCE_DIR:       /workspace/dealii
#                                (version 8.5.0-pre, shortrev 92e0dfd)
#        CMAKE_BINARY_DIR:       /workspace/dealii/build
#        CMAKE_CXX_COMPILER:     GNU 5.2.0 on platform Linux x86_64
#                                /opt/apps/ossw/applications/gcc/gcc-5.2/c7/bin/g++
#
#  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#      ( DEAL_II_WITH_ARPACK = OFF )
#        DEAL_II_WITH_BOOST set up with bundled packages
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#        DEAL_II_WITH_CUDA set up with external dependencies
#        DEAL_II_WITH_CXX11 = ON
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_GSL set up with external dependencies
#        DEAL_II_WITH_HDF5 set up with external dependencies
#        DEAL_II_WITH_LAPACK set up with external dependencies
#      ( DEAL_II_WITH_METIS = OFF )
#      ( DEAL_II_WITH_MPI = OFF )
#        DEAL_II_WITH_MUPARSER set up with bundled packages
#      ( DEAL_II_WITH_NETCDF = OFF )
#      ( DEAL_II_WITH_OPENCASCADE = OFF )
#      ( DEAL_II_WITH_P4EST = OFF )
#      ( DEAL_II_WITH_PETSC = OFF )
#      ( DEAL_II_WITH_SLEPC = OFF )
#        DEAL_II_WITH_THREADS set up with external dependencies
#      ( DEAL_II_WITH_TRILINOS = OFF )
#        DEAL_II_WITH_UMFPACK set up with bundled packages
#        DEAL_II_WITH_ZLIB set up with external dependencies
#
#  Component configuration:
#      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
#        DEAL_II_COMPONENT_EXAMPLES
#      ( DEAL_II_COMPONENT_PACKAGE = OFF )
#      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )

**Comment by Rombur** [comment]
It looks like cmake detected cuda and turn on the cuda support :-( Can you reconfigure deal.II with `-DDEAL_II_WITH_CUDA=OFF`

**Comment by clarkpede** [comment]
That fixed it.  I won't need cuda, so disabling it isn't a problem for me.

**Comment by drwells** [comment]
@Rombur Should we explicitly disable CUDA by default? I ocassionally run into this problem myself but I know to turn CUDA off.

**Comment by tjhei** [comment]
> Should we explicitly disable CUDA by default? I ocassionally run into this problem myself but I know to turn CUDA off.

That might be a reasonal choice. The number of people who want to use it is small and it sounds like it is somewhat fragile.

**Comment by Rombur** [comment]
Yeah I thought that is what we did already. The cuda auto-detect does not work right now because because you have to add extra-flags manually.
