### ISSUE TITLE
parallel::distributed::Triangulation should be able to transfer vertex data

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#323]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on May 16, 2014 17:30:30_

For problems where we move around vertices, it is currently complicated to use distributed triangulations because the vertex locations are lost upon rebalancing. ASPECT current implements a scheme for free surfaces that we should migrate into deal.II proper.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=216_

**Comment by drwells** [comment]
There doesn't seem to be much interest in this so lets close.
