### ISSUE TITLE
[Meta] Rewrite edge orientation code

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3235]
The edge orientation code was originally written by Michael Anderson. It does well what it's supposed to do, but it doesn't follow our usual code conventions, and it is implemented twice: once for 2d, and once for 3d. Finally, it would be nice if it followed the algorithm and conventions used in the paper we currently have under review.

This github issues is simply a collector for all patches that re-implement this algorithm in a generic and modern way.

**Comment by drwells** [comment]
I thought about #3224 some more today and I think I have an idea for a possible replacement for the `std::set`. One could do something like

```cpp
template <>
class EdgeDeltaSet<3> : private std::vector<unsigned int>
{
public:
  using std::vector<unsigned int>::begin;
  using std::vector<unsigned int>::end;
  using std::vector<unsigned int>::clear;

  std::vector<unsigned int>::iterator insert (const unsigned int edge_index)
  {
    std::vector<unsigned int>::iterator lower_bound = std::lower_bound(begin(), end(), edge_index);
    // do not check for equality if the container is empty
    if (lower_bound != end() && *lower_bound == edge_index)
      return lower_bound;
    else
      return std::vector<unsigned int>::insert(lower_bound, edge_index);
  }
};
```

to get an array of unique and sorted integers.

**Comment by bangerth** [comment]
Something like this is what I had in mind if it turns out to be necessary.

The current 3d code is not a bottleneck in computations. I'll benchmark old and new code side by side once the new code is running, and then will see whether it is necessary to optimize anything.
