### ISSUE TITLE
Add another CUDA check or disable it by default

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3238]
I can confirm that with GCC 4.9 and a minimal set of flags (turning on things like MPI) our cmake configuration finds CUDA and configures it correctly. However, when compiling I get the same errors as in #3229.

I think that when we addressed this last time we just disabled CUDA when we did not have C++11 on. I think that it would be best to only enable this feature if `DEAL_II_WITH_CUDA=ON` is provided by the user.

Either way, we should check for this function (`atomicMax`) and throw a CMake error if this function is not available and the user requests CUDA. @Rombur is this related to #3037? I don't really know anything about CUDA.

**Comment by Rombur** [comment]
>Either way, we should check for this function (atomicMax) and throw a CMake error if this function is not available and the user requests CUDA. @Rombur is this related to #3037? I don't really know anything about CUDA.
Yes, it is the same problem.

**Comment by drwells** [comment]
Okay. Lets close this, then, in favor of #3037.
