### ISSUE TITLE
Bug in write_pvd_record

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#3259]
Hello,

I think there is a small possibility of bug in the write_pvd_record() in file
dealii/source/base/data_out_base.cc

This is because, if all the time data is of the order of 10^6, but suddenly the time steps become O(1), the time data printed in the file is then just O(6) and information is lost. Due to this, all subsequent files have the same time  and  Paraview is taking that only one file for all the files with same time.

I am copying a part here from the data file that I have for providing some clarification.

After having some very large time-steps in my simulation, the time-steps again drop to around 0.1.

  <DataSet timestep="9.85603e-08" group="" part="0" file="alpha_solution-00050.00000.pvtu"/>
    <DataSet timestep="4e+06" group="" part="0" file="alpha_solution-00051.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00052.00000.pvtu"/>

The time step after this is  0.1, but the file does not show this change. 

    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00053.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00054.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00055.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00056.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00057.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00058.00000.pvtu"/>

I think adding flags to out in the file might change this behaviour.

**Comment by bangerth** [comment]
Yes. This happens in `source/base/data_out_base.cc` around line 6236:
```
  for (unsigned int i=0; i<times_and_names.size(); ++i)
    out << "    <DataSet timestep=\"" << times_and_names[i].first
        << "\" group=\"\" part=\"0\" file=\"" << times_and_names[i].second
        << "\"/>\n";
```
What needs to happen is that that one number is output with more than the usual 6 digits of accuracy, e.g., using `std::precision`.

@sairajat -- want to write a patch and become one of the authors of deal.II thereby?

**Comment by sairajat** [comment]
@bangerth  Hello Professor.

Yes, I would love to contribute to deal.II. I will write a patch and submit it.

**Comment by bangerth** [comment]
@sairajat -- fantastic! Let us know if you need guidance on how to get there!

**Comment by sairajat** [comment]
@bangerth  Professor, I was busy with my exams. I will do it in next 2 days. 
I will definitely ask for your guidance if I am unable to submit a patch on my own.
Thanks.

**Comment by sairajat** [comment]
Should we close this issue now ?

**Comment by bangerth** [comment]
It will automatically be closed one #3259 gets merged :-)

As a general rule, we typically keep issues open until the fix has been merged, to make sure nothing falls through the cracks.

**Comment by bangerth** [comment]
I mean #3308, of course.

**Comment by bangerth** [comment]
As a follow-up (I didn't want to hold up #3308 any longer), do you want to propose another pull request that mentions your fix in the file `doc/news/changes.h` in the "specific changes" section?
