### ISSUE TITLE
Poor performance for constructor of FE_Nedelec in 3D.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#326]
_From [w0ss...@gmail.com](https://code.google.com/u/103951838845227944973/) on June 30, 2014 14:04:03_

For order 4 and above the time to call the constructor is taking 1000 seconds or more. I didn't bother to go past order 5.

E.g. running this code on my imac desktop (OSX 10.9.3)

int main ()
{
    const unsigned int dim=3;
    Timer timer;
    for (unsigned int k=0;k<6;k++)
    {
        timer.start ();
        FE_Nedelec<dim>          fe(k);
        timer.stop ();
        std::cout << "Order " << k << std::endl;
        std::cout << "DoFs per cell: " << fe.n_dofs_per_cell() << std::endl;
        std::cout << "Time: " << timer() << "s" << std::endl;
        timer.reset();
    }
    return 0;
}

I get:
Order 0
DoFs per cell: 12
Time: 0.002656s
Order 1
DoFs per cell: 54
Time: 0.414289s
Order 2
DoFs per cell: 144
Time: 6.07334s
Order 3
DoFs per cell: 300
Time: 68.2726s
Order 4
DoFs per cell: 540
Time: 1346.91s
Order 5
DoFs per cell: 882
Time: 16012s

I see similar performance on my linux installation, both using up-to-date versions from the svn.

Can this performance be improved? - I am planning on using orders up to 6 or 8, but these run times will be a problem.

Thanks

_Original issue: http://code.google.com/p/dealii/issues/detail?id=227_

**Comment by kronbichler** [comment]
I don't think we have an immediate solution here as one would need to manually go through the code, which will only happen if someone intensively works with that code. On the other hand, I plan to work on a nodal variant of Nedelec spaces in #9545 in the near future where these things should be easier, so I'm closing this for now.
