### ISSUE TITLE
step-42 obstacle.pbm is not copied when installing

### ISSUE THREAD

**Issue by vryy** [dealii/dealii#3265]
When installing dealii, the file obstacle.pbm, located in ${DEALII_INSTALL_DIR}/examples/step-42, which is necessary to run the problem with chinese character input is missing.

The command to reproduce error:
./step-42 p1_chinese.prm

**Comment by spco** [comment]
Hi @vryy, could you provide information on how you are installing deal.II (github developer version, release version from source, Mac OSX .dmg, candi, virtual box?), and when you installed it?

**Comment by masterleinad** [comment]
I can't reproduce this in a recent developer version.

**Comment by spco** [comment]
It certainly appears to be in the github repo.

**Comment by vryy** [comment]
Hi
I compiled and installed dealii from git repo, at commit 723b584d58c2891f6ba30fd95526f89d25c9b9fd
I believed it existed long time ago since I checked my compilation in July, still missing.

**Comment by davydden** [comment]
i can reproduce it on macOS with current deal.II (github compiled yesterday):
```
$ ls
CMakeLists.txt	p1_adaptive.prm	p1_chinese.prm	p1_global.prm	p2_adaptive.prm	p2_global.prm	step-42.cc
```

**Comment by bangerth** [comment]
Just for everyone's education because there appeared to be some confusion: the file is in the repo, but it was not copied into the *installed* location when doing `make install`.
