### ISSUE TITLE
Fix documentation for TrilinosWrappers namespace

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3267]
There appears to be some leakage from another part of the documentation onto the [TrilinosWrappers namespace](https://www.dealii.org/developer/doxygen/deal.II/namespaceTrilinosWrappers.html). 

> This class extends the base class to implement an array of Trilinos sparsity patterns that can be used to initialize Trilinos block sparse matrices that can be distributed among different processors. It is used in the same way as the BlockSparsityPattern except that it builds upon the TrilinosWrappers::SparsityPattern instead of the SparsityPattern. See the documentation of the BlockSparsityPattern for examples.

> This class is has properties of the "dynamic" type of Sparsity patterns (in the sense that it can extend the memory if too little elements were allocated), but otherwise is more like the basic deal.II SparsityPattern (in the sense that the method compress() needs to be called before the pattern can be used).

> This class is used in step-32.

**Comment by jppelteret** [comment]
I see how this has happened. In `lac/block_sparsity_pattern.h` the doxygen comments have been placed above the namespace, not the class. I'll submit a PR to fix this in a moment...

**Comment by bangerth** [comment]
Good spot. Funny how long it took for us to notice this :-)
