### ISSUE TITLE
More flexible FunctionMap with one ComponentMask per boundary indicator

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#327]
_From [florian....@gmail.com](https://code.google.com/u/103174404746239284090/) on July 04, 2014 14:42:12_

In my application I solve a system of equations with solution components u and v on a domain with boundaries A and B. I have Dirichlet values for u on the boundary A and Neumann boundaries on B. For v I have Dirichlet boundaries on both A and B. 

deal.ii doesn't support this use case as the boundary related functions (e.g. VectorTools::interpolate_boundary_values() or MGConstrainedDoFs::initialize()) ask for one FunctionMap and one ComponentMask. This design implies that all components must share the same Dirichlet boundary.

(Sometimes the problem can be circumvented by calling the method in question multiple times, but this is a workaround and doesn't work for e.g. the MGConstrainedDoFs class.)

It would be great if the "boundary functions" would be able to work with objects which can store one ComponentMask per boundary indicator. Either by adding this functionality to the FunctionMap or, to not break existing code, by having e.g. a MaskedFunctionMap object.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=230_

**Comment by masterleinad** [comment]
Fixed by #2847.
