### ISSUE TITLE
MatrixFree with parallel::shared::Triangulation

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#3285]
- [x] Create parallel test for MatrixFree with `parallel::shared::Triangulation`: copy of `matrix_free/matrix_vector_10.cc`
- [x] Deprecated the `reinit()` methods of `MatrixFree` that take an IndexSet argument. We have to take the IndexSet from the `dof_handler` that the MatrixFree object is based upon and cannot sensibly support anything different from that.

**Comment by kronbichler** [comment]
This is a reminder for myself as I cannot get around to fix those immediately because I don't have METIS on my installation.

**Comment by davydden** [comment]
both [candi](https://github.com/dealii/candi/blob/master/deal.II-toolchain/packages/parmetis.package) and [Spack](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py#L105) have metis/parmetis in deal.II stack, time to try one of those? :smile:

**Comment by kronbichler** [comment]
Fixed by #3313 and #3314.
