### ISSUE TITLE
Typos in documentation of FunctionParser

### ISSUE THREAD

**Issue by kbzowski** [dealii/dealii#3286]
I think I've noticed small mistake in examples inside documentation of FunctionParser class
https://www.dealii.org/8.4.1/doxygen/deal.II/classFunctionParser.html

There is:
`std::map<std::string> constants;`

Should be:
`std::map<std::string, double> constants;`

**Comment by davydden** [comment]
would you mind opening a PR which fixes this issue and thereby becoming a contributor to the library?

p.s. i think you are right as `initialize()` uses
```
typedef std::map<std::string, double> FunctionParser< dim >::ConstMap
```
