### ISSUE TITLE
Example Step-28, Missing 'project.prm' File

### ISSUE THREAD

**Issue by jkulesza** [dealii/dealii#3299]
deal.ii 8.5.0pre: in Step-28 of the example programs, a default parameter file 'project.prm' is called for.  This file does not appear to be included (so `make run` fails) nor is the format specified in, or pointed to by, step-28.cc.

Note that default parameters are given step-28.cc, so commenting out some of the calls in main() are sufficient to allow the program to run.

**Comment by bangerth** [comment]
Yes, good point. It used to be that the file was automatically generated in the current directory if it didn't exist, but that doesn't happen any more following #3122. I uploaded #3301 to fix this.

**Comment by jkulesza** [comment]
Excellent, thank you for the *quick* fix!  

A side-note of praise regarding Step-28: I was able to use it today to truly get into deal.II and adapted to my own purposes.  Once I surpassed a few familiarization issues, everything came together nicely.  My thanks also for well-crafted software *and* documentation!

**Comment by bangerth** [comment]
Thanks for the kind words. step-28 isn't exactly the easiest program to start with, but I think it's an interesting one for sure.
