### ISSUE TITLE
Implement a way to get a cell based on a CellId

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#330]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on August 15, 2014 08:00:05_

As discussed in a recent thread on the mailing list, there is currently no way to get a cell iterator for a given CellId. This would be useful for parallel computations that attach data to cells and need to send it to other processors upon repartitioning.

My suspicion is that we'd need a function
  Triangulation::get_cell (const CellId &) const;
or similar, and probably the same for the DoFHandlers.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=244_

**Comment by masterleinad** [comment]
Fixed by #2981.
