### ISSUE TITLE
Specify template arguments within .inst.in as opposed to template-arguments.in

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3312]
In scenarios where template arguments are relevant only for a single `.cc` file,  it would be good to be able to write something like

```
for (VEC: REAL_NONBLOCK_VECTORS; deal_II_dimension : DIMENSIONS; deg : {1;2;3;4} )
{

}

```

**Comment by drwells** [comment]
This system is complex enough that I think we should keep all of the lists in one place.
