### ISSUE TITLE
Run on travis new tests from a PR

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3327]
It would be good if it would be possible to run on Travis not only a few selected tests from the whole library, but also new tests from a given PR. Then if someone contributes a feature with unit tests, they would be automatically tested by Travis.

This would help to avoid follow-up PRs like https://github.com/dealii/dealii/pull/3320.

**Comment by drwells** [comment]
Its not running on travis, but we do have @tjhei's CI servers now that do exactly this. May we close this issue?

**Comment by davydden** [comment]
yes, i think so.
