### ISSUE TITLE
Allow continuation lines in ParameterHandler

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#333]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on September 26, 2014 04:14:20_

There are situations where one would really like to extend long lines in parameter files to the next line, for example using a backslash at the end of a line in much the same way as the C preprocessor allows.

This could be done relatively easily using the functions in https://github.com/geodynamics/aspect/blob/master/source/main.cc This would mean that we report errors on the first line of a continuation block, but that's likely acceptable.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=255_

**Comment by bangerth** [comment]
Implementation in #1520

**Comment by drwells** [comment]
Closed by #1520 and #2078.
