### ISSUE TITLE
switch MatrixFree::Base to DiagonalMatrix<Vector>

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3330]
subj. 

This is IMHO a good idea because if someone like me wants to have consistent diagonal, then I just derive from `Base` class and implement its calculation appropriately with the `DiagonalMatrix` class.

**Comment by kronbichler** [comment]
@davydden Do you mean that you want to replace the vector `Base::inverse_diagonal_entries` by `DiagonalMatrix<LA::d::Vector<Number> >`? That is definitely a good plan, but we currently do not have a good way for assembling the `FEEvaluation` contributions into such a vector. Do you have specific plans for how to fill that matrix already?

**Comment by davydden** [comment]
yes, exactly. For now I would not bother making `FEEvaluation` work with `DiagonalMatrix`, because we can also query the underlying vector and feed it into `FEEvaluation` for approximation of diagonal elements, like what we do for Laplace now.

But in order to have exact diagonals, you are correct, we need `FEEvaluation` to know what to do. Given that we may have a `Table` with heterogeneous coefficients to be used, I don't have a solution right now as I am not that familiar with implementation details of `FEEvaluation`.

**Comment by davydden** [comment]
fixed in https://github.com/dealii/dealii/pull/3476
