### ISSUE TITLE
Improve storage of AffineConstraints

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#334]
_From [kronbich...@gmail.com](https://code.google.com/u/107881102392393767705/) on September 26, 2014 10:44:50_

Due to the high memory consumption of ConstraintMatrix, it is suggested to improve the storage scheme in the 'close()' call by at least some of the following ideas:
- Detect re-occuring weights between different constraint lines
- Detect when we constrain to the same indices several times (think of Q7 elements in 3D where each of the 4 subfaces constraints to the same 64 indices on the mother faces, with only the weights differing).

Both methods require splitting the storage of weights and indices and invalidates the 'get_constraint_entries' method on the users' side, unfortunately. We might provide an alternative user interface to get a handle on the constraints by creating an iterator to constraints that picks the correct weight/index pair from storage and goes over it; unconstrained indices have begin(line) == end(line). All internal operations like condense(), distribute(), [distribute,add_entries]_local_to_global() should then be done with the iterators instead of the stored compressed data which is likely more complicated to work with. To give users time to adjust their code, we could introduce iterators before the next release (and deprecate get_constraint_entries) and do the actual compression later.

Any other ideas or suggestions?

_Original issue: http://code.google.com/p/dealii/issues/detail?id=256_

**Comment by kronbichler** [comment]
I will work on the iterators and parts of the suggested improvement during the next weeks.

**Comment by bangerth** [comment]
Awesome. I have always envisioned having a function
```
  ConstraintMatrix::add_constraint (const unsigned int i,
                        const std::vector<std::pair<unsigned int, double> > &linear_combination,
                        const double inhomogeneity);
```
that would constrain $U_i$ to the specified sum of other DoFs. The current interface rips the creation of the constraint apart from setting the components of the linear combination and the inhomogeneity. Not my best idea ever to create the interface this way.

Having such a function would also allow for compressing data storage, for example by storing a hash map with the weights, because we get to see the entire constraint right away, rather than piecemeal.

**Comment by kronbichler** [comment]
At least the iterator part should be fixed for release 8.5

**Comment by drwells** [comment]
This has not been a high priority enough issue for anyone to make progress on in a few years, so lets not associate it with a milestone for now.

**Comment by kronbichler** [comment]
I think we have not seen this as a high priority in the past 10 years, so let me close it for now. We have documented the ideas, and we have several concrete improvements in other places like the matrix-free framework with tensor-product interpolators and similar schemes. Whenever tackling this project, we need to start with a new list of goals and interfaces, so I suggest to close this issue at this point.
