### ISSUE TITLE
Make DiagonalMatrix member of MatrixFreeOperators::Base shared_ptr

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#3343]
If we have an `std_cxx11::shared_ptr<DiagonalPreconditioner<VectorType> >` in the `MatrixFreeOperators::Base` class and a return function for the shared pointer, we can share the storage inside the class with the outside world, e.g. in step-37 according to #3329.

**Comment by davydden** [comment]
I see now why you would like to have it to avoid having two objects, one in `Chebyshev` preconditioner, and one in `MatrixFreeBase`, i.e. 
```
        smoother_data[level].preconditioner.reset(new DiagonalMatrix<vector_t>());
        *smoother_data[level].preconditioner =
          mg_matrices[level].get_matrix_diagonal_inverse();
```

Totally agree :+1:
