### ISSUE TITLE
Precompute things in the background

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#335]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on September 26, 2014 17:45:43_

There are things every program needs at one point or another but that either
- could be precomputed in the background by the object that will eventually have to provide it, or
- could be computed in the background by objects that current compute it as part of their regular constructor.

In either case, the idea is to use available cores early on in the program at a time when they are mostly idle, and already have stuff ready by the time it is necessary. There is a longer discussion on this here: https://groups.google.com/forum/?fromgroups#!topic/dealii-developers/TE5b71IWaLk There was already a patch request (now abandoned) that shows how something like this can be implemented: https://github.com/dealii/dealii/pull/167 Things that could be precomputed:
- locally owned/active/relevant index sets
- some of the stuff we compute in the FE constructors
- possibly constraint matrices

_Original issue: http://code.google.com/p/dealii/issues/detail?id=257_

**Comment by drwells** [comment]
I think we are at the point where we could just ask application codes to set up tasks to assemble these themselves.
