### ISSUE TITLE
Inefficient preallocation in PETScWrappers::MPI::SparseMatrix

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#336]
_From [agray...@gmail.com](https://code.google.com/u/102807770450641062241/) on October 03, 2014 14:18:24_

Dear Devs,

From here: http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatCreateAIJ.html One can see that in order to efficiently preallocate a sparse matrix in parallel one has to specify nnz for both diagonal and off-diagonal portion of the matrix. 

Currently, PETScWrappers::MPI::SparseMatrix does not account for this (at least not for all cases) resulting in substantial performance penalty. 

For instance, this method: http://www.dealii.org/8.1.0/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1SparseMatrix.html#aa27a651db22faa0e0d007e209a16f173 creates a matrix in the following way:
ierr = MatCreateAIJ (communicator, local_rows, local_columns, m, n, n_nonzero_per_row, 0, 0, 0, &matrix);

the next line then disables the error message about extra allocations which will happen (because o_nnz is zero above) during matrix assembly:
ierr = MatSetOption (matrix, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE);

I have just hit this issue since my a part of my program slowed down in parallel.
In fact, other (but not all) reinit methods suffer the same issue. 

I would be happy to create a pull request, but I want first to ask which solution you think is better:
1. Simply use n_nonzero_per_row for both diagonal and off-diagonal blocks. This may result in a bigger memory allocation than required
2. Add another parameter to the init methods specifying nnz for diagonal and off-diagonal separately.

Best,
Alexander

_Original issue: http://code.google.com/p/dealii/issues/detail?id=258_

**Comment by drwells** [comment]
At this point we have alternative constructors and reinit functions that take, as argument, sparsity patterns; that gets around this performance issue and are compatible with the Trilinos wrappers. Is there any reason to not deprecate this old interface in favor of just building sparsity patterns? Steps 17, 18, and 40 already use this constructor.

**Comment by tjhei** [comment]
Agreed. We should deprecate all functions that are not using a sparsity pattern.

**Comment by drwells** [comment]
I will get to this after #4279 and #4297 are merged.
