### ISSUE TITLE
recheck nonlocal graph in Trilinos sparsity pattern

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#337]
_From [timo.heister](https://code.google.com/u/timo.heister/) on October 23, 2014 15:56:01_

Trilinos 11.12 and earlier have a bug that we can not use a nonlocal graph. Revisit this after 11.13 is released. See https://github.com/dealii/dealii/pull/209 and a914565

_Original issue: http://code.google.com/p/dealii/issues/detail?id=260_

**Comment by tamiko** [comment]
@tjhei, @kronbichler 11.14 is availabe - mind to have a look?

**Comment by kronbichler** [comment]
I think we now have a better solution where we build our own non-local matrices for most code paths. That is the future-proof way of doing things and also what Tpetra developers recommend doing for Tpetra. Therefore, I'm closing this now.
