### ISSUE TITLE
Static analysis: dealii-git/source/base/data_out_base.cc

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3378]
```
dealii-git/source/base/data_out_base.cc	7410	warn	V688 The 'vector_data_ranges' local variable possesses the same name as one of the class members, which can result in a confusion.
```

We should address these warnings and errors from the static analysis tool PVS. In response to #3342.

**Comment by bangerth** [comment]
The analyzer is mistaken -- this is not a local variable but in fact the member variable.

**Comment by kostyfisik** [comment]
Test mentioning analyzer mistakes from #3342
