### ISSUE TITLE
High-order MappingQ, Manifold and vector-valued FEs

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#338]
_From [agray...@gmail.com](https://code.google.com/u/102807770450641062241/) on November 10, 2014 16:46:16_

This issue originates from this topic: https://groups.google.com/forum/#!topic/dealii-developers/oMxq_t4rNz0 However, it turns out that the problem is not confined to FE_Nedelec. 

Here is small program to reproduce the issue: https://dl.dropboxusercontent.com/u/60982984/test_mapping.cc The code simply projects a polynomial function which is 0 on boundary on a mesh with an attached manifold. Deformations which the manifold does to the triangulation are small (max. 4&#37; -- se the attached figure fe_raviart_thomas_grid.png).
Here is L2 error of the projected function for two FE types and different mapping degrees:

DEAL::dim: 3 FE_RaviartThomas<3>(2)
DEAL::Mapping degree: 1 L2 error: 7.57e-05
DEAL::Mapping degree: 2 L2 error: 0.000505
DEAL::Mapping degree: 3 L2 error: 0.00467
DEAL::Mapping degree: 4 L2 error: 0.0110
DEAL::Mapping degree: 5 L2 error: 0.0111
DEAL::dim: 3 FE_Nedelec<3>(2)
DEAL::Mapping degree: 1 L2 error: 8.84e-06
DEAL::Mapping degree: 2 L2 error: 0.000358
DEAL::Mapping degree: 3 L2 error: 0.000417
DEAL::Mapping degree: 4 L2 error: 0.00904
DEAL::Mapping degree: 5 L2 error: 0.00913

DEAL::dim: 3 FE_RaviartThomas<3>(3)
DEAL::Mapping degree: 1 L2 error: 1.16e-07
DEAL::Mapping degree: 2 L2 error: 8.23e-05
DEAL::Mapping degree: 3 L2 error: 8.79e-05
DEAL::Mapping degree: 4 L2 error: 0.00169
DEAL::Mapping degree: 5 L2 error: 0.00244
DEAL::dim: 3 FE_Nedelec<3>(3)
DEAL::Mapping degree: 1 L2 error: 5.12e-08
DEAL::Mapping degree: 2 L2 error: 1.41e-05
DEAL::Mapping degree: 3 L2 error: 5.37e-05
DEAL::Mapping degree: 4 L2 error: 0.000307
DEAL::Mapping degree: 5 L2 error: 0.00176

I do not quite understand why errors grow so much?

As an illustration, I attached a visulation calculated for FE_RaviartThomas(3) and different MappingQ orders. Clearly, for MappingQ of degree five some rather odd features appear. 

If I comment the following lines:
  for (Triangulation<3>::active_cell_iterator cell=triangulation.begin_active(); cell!=triangulation.end(); ++cell)
    cell->set_all_manifold_ids(0);

everything works just fine for all cases.

Any insight is greatly appreciated.

Thanks,
Alexander

**Attachment:** [fe_raviart_thomas.png fe_raviart_thomas_grid.png](http://code.google.com/p/dealii/issues/detail?id=263)

_Original issue: http://code.google.com/p/dealii/issues/detail?id=263_

**Comment by rosskynch** [comment]
I just wanted to add to this issue: I am seeing a similar behaviour when using the mapping for an Eddy current problem on a conducting sphere in a background uniform field. I have an analytical solution for this problem, so capturing the spherical geometry is important to show full error convergence. However, as I increase the mapping degree, I see a stagnation in the error with p-refinement. The point of stagnation seems to increase with mapping order too. Here are some results using mappingq1 up to q6

The columns refer to:
n_cells n_DoFs n_GMRES_iterations L2_error H_curl_error

==> mapping1/log_all.out <==
288 2024 2 0.0204933 0.273523
288 14960 34 0.0135695 0.013652
288 49176 43 0.017177 0.0172336
288 115040 59 0.0166767 0.0167359
288 222920 69 0.0165935 0.0166527

==> mapping2/log_all.out <==
288 2024 2 0.022611 0.329102
288 14960 32 0.00311299 0.0366779
288 49176 40 0.0002452 0.00159489
288 115040 56 0.000258157 0.000261861
288 222920 62 0.000277372 0.000277759

==> mapping3/log_all.out <==
288 2024 2 0.02235 0.337453
288 14960 32 0.00405472 0.0851203
288 49176 40 0.000967377 0.013584
288 115040 56 0.000366722 0.0010348
288 222920 62 0.000436923 0.00047447

==> mapping4/log_all.out <==
288 2024 2 0.0224079 0.34183
288 14960 32 0.00430777 0.101182
288 49176 40 0.00136514 0.0429635
288 115040 56 0.000671112 0.0104698
288 222920 62 1.21855e-05 0.000634049

==> mapping5/log_all.out <==
288 2024 2 0.0223371 0.343346
288 14960 32 0.00449305 0.110654
288 49176 40 0.00176344 0.0620574
288 115040 56 0.000795856 0.0316142
288 222920 62 0.000424303 0.00669108

==> mapping6/log_all.out <==
288 2024 2 0.0224488 0.344516
288 14960 32 0.00461717 0.115401
288 49176 40 0.00211749 0.0734013
288 115040 56 0.00126854 0.0507629
288 222920 62 0.000831738 0.0275057

**Comment by tamiko** [comment]
Superseded by #1646
