### ISSUE TITLE
Further parallelize compilation

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3388]
It looks like we recently added some files that take about 3 GB of RAM to compile individually on my desktop. We can probably improve compilation times a bit by splitting these particular files up once or twice.

**Comment by bangerth** [comment]
I bet these are the new `VectorTools::project` variations that instantiate the whole `MatrixFree` framework with several different template arguments, in all combinations. Because they call *all* of them from a single function, I'm not sure there is much we can do about this -- other than moving these functions into a `.cc` file and instantiating them once and for all by hand, rather than letting the compiler do it at the place of use.

**Comment by kronbichler** [comment]
@bangerth I definitely agree that this is due to `MatrixFree` and its templates. I don't know if it helps but we might do the `project_parallel` functions only for `LinearAlgebra::distributed::Vector<Number>` and not all vector templates. We copy the content of the projection to the actual vector at the end of those functions, so it would make sense to create a separate function for the actual work so the compiler has to instantiate fewer symbols. Another thing that comes to mind is to split `vector_tools.templates.h` into a bunch of separate files called `vector_tools_project.templates.h` or `vector_tools_project_mf.templates.h` in analogy to the `.cc` files. It should not affect the amount of code that is generated but there should be considerably fewer symbols which might help.

A final remark regarding compilation speed: I am not a compiler writer but whenever I had a closer look at compilation times my experience was that compilation time and memory usage are not always in the most obvious places. Templates do hurt, sure, but one thing I found hurts more are long function names due to templates. I mean the ones that span several pages of terminal windows when binding a function with long, heavily templated arguments that span more than a page of terminal windows and appear in dozens of variants. (This is why there is a class `ParallelForInteger` in `include/deal.II/base/parallel.h` for example that does essentially the same as `parallel::apply_to_subranges`.)

**Comment by davydden** [comment]
> Another thing that comes to mind is to split vector_tools.templates.h into a bunch of separate files called vector_tools_project.templates.h or vector_tools_project_mf.templates.h in analogy to the .cc files. It should not affect the amount of code that is generated but there should be considerably fewer symbols which might help.

:+1:

**Comment by kronbichler** [comment]
An interesting thing is that already the assembler runs for 14 seconds on `vector_tools_project.cc` in debug mode (gcc 5.3), producing an object file that is 77.3 MB. So this is definitely a tough one to compile. (The compiler takes 2 minutes and 2.9 GB of RAM on my machine.)

**Comment by bangerth** [comment]
By "assembler" you mean the program that expands the instantiations? And the 77 MB is the size of the corresponding `.inst` file?

**Comment by kronbichler** [comment]
No, I mean the program `as` that converts the assembler code generated by `cc1plus` (in case of gcc) into machine code. You know more about compilers than me, but isn't that called the 'assembler'? And the size is for the `vector_tools_project.o`, i.e., the final compiler file that finally gets linked into the `.so` file by the linker.

**Comment by bangerth** [comment]
Yes, it's called an "assembler" indeed :-) I've lived in the FEM world for so long now that I thought "assembler" refers to the assembly of linear systems...

And yes, that's humongous. I hope this is for debug mode?

**Comment by kronbichler** [comment]
Yes, it is the debug mode (`-Og -ggdb` of gcc). The release file without debug symbols is smaller, at around 13.9 MB.

**Comment by bangerth** [comment]
I'm installing the new machines at my new workplace and I've just witnessed this as well -- the assembler taking 1.3GB of memory. I don't think I've ever seen anything of this sort. Imagine we tried to do interprocedural optimization or `-flto` on the result...

The debug version of the library now has a size close to 1.2GB. (The release version still 140MB.)

**Comment by davydden** [comment]
we can do 

> I don't know if it helps but we might do the project_parallel functions only for LinearAlgebra::distributed::Vector<Number> and not all vector templates.

by using 
```
REAL_NONBLOCK_VECTORS := { 
                    LinearAlgebra::distributed::Vector<double>;
                    LinearAlgebra::distributed::Vector<float> ;
                  }
```

and also in `vector_tools.templates.h` change 
```
switch (dof.get_fe().degree)
      {
      case 1:
        project_parallel<dim,VectorType,spacedim,1> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 2:
        project_parallel<dim,VectorType,spacedim,2> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 3:
        project_parallel<dim,VectorType,spacedim,3> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 4:
        project_parallel<dim,VectorType,spacedim,4> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 5:
        project_parallel<dim,VectorType,spacedim,5> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 6:
        project_parallel<dim,VectorType,spacedim,6> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 7:
        project_parallel<dim,VectorType,spacedim,7> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 8:
        project_parallel<dim,VectorType,spacedim,8> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      default:
        Assert (false, ExcNotImplemented());
      }
```
to
```
switch (dof.get_fe().degree)
      {
      case 1:
        project_parallel<dim,VectorType,spacedim,1> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 2:
        project_parallel<dim,VectorType,spacedim,2> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 3:
        project_parallel<dim,VectorType,spacedim,3> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      case 4:
        project_parallel<dim,VectorType,spacedim,4> (mapping,dof,constraints,quadrature,func,vec_result);
        break;
      default:
        Assert (false, ExcNotImplemented());
      }
```

That would be very straight-forward to do.

@bangerth could you give it  quick try and see if it helps on your machines?

**Comment by davydden** [comment]
same for 
```
    switch (fe_degree)
      {
      case 1:
        project_parallel<dim,VectorType,dim,1,2> (matrix_free,constraints,func,vec_result);
        break;
      case 2:
        project_parallel<dim,VectorType,dim,2,3> (matrix_free,constraints,func,vec_result);
        break;
      case 3:
        project_parallel<dim,VectorType,dim,3,4> (matrix_free,constraints,func,vec_result);
        break;
      case 4:
        project_parallel<dim,VectorType,dim,4,5> (matrix_free,constraints,func,vec_result);
        break;
      case 5:
        project_parallel<dim,VectorType,dim,5,6> (matrix_free,constraints,func,vec_result);
        break;
      case 6:
        project_parallel<dim,VectorType,dim,6,7> (matrix_free,constraints,func,vec_result);
        break;
      case 7:
        project_parallel<dim,VectorType,dim,7,8> (matrix_free,constraints,func,vec_result);
        break;
      case 8:
        project_parallel<dim,VectorType,dim,8,9> (matrix_free,constraints,func,vec_result);
        break;
      default:
        Assert (false, ExcNotImplemented());
      }
```

**Comment by davydden** [comment]
Among the two i think it's better to cut down on instantiation for different vectors but try to keep `fe_degree` high.

**Comment by bangerth** [comment]
My machine has 256GB of memory, so there is nothing inherently wrong with this :-)

But I'll give it a try on my laptop at home tonight unless someone beats me to it.

**Comment by davydden** [comment]
I will also fiddle with it on my mac to try to find a good middle point.

**Comment by davydden** [comment]
for the record, with clang+gfortran, debug and release version of the library are `292Mb` and `106Mb`.

**Comment by bangerth** [comment]
I should say that my numbers are with PETSc, Trilinos, p4est, SLEPc.

**Comment by davydden** [comment]
> I should say that my numbers are with PETSc, Trilinos, p4est, SLEPc.

same here, everything without `OpenCascade`.

**Comment by kronbichler** [comment]
I checked a version with Trilinos. For 502a400 (before any MatrixFree code was added to `vector_tools.templates.h` I get:
```
lrwxrwxrwx 1 kronbichler lnm         25  7. Nov 23:47 libdeal_II.g.so -> libdeal_II.g.so.8.5.0-pre
-rwxr-xr-x 1 kronbichler lnm 1012105416  7. Nov 23:47 libdeal_II.g.so.8.5.0-pre
lrwxrwxrwx 1 kronbichler lnm         23  7. Nov 23:45 libdeal_II.so -> libdeal_II.so.8.5.0-pre
-rwxr-xr-x 1 kronbichler lnm  119274856  7. Nov 23:45 libdeal_II.so.8.5.0-pre
```
whereas for the most recent version I get:
```
lrwxrwxrwx 1 kronbichler lnm         25  7. Nov 23:33 libdeal_II.g.so -> libdeal_II.g.so.8.5.0-pre
-rwxr-xr-x 1 kronbichler lnm 1054178768  7. Nov 23:33 libdeal_II.g.so.8.5.0-pre
lrwxrwxrwx 1 kronbichler lnm         23  7. Nov 23:32 libdeal_II.so -> libdeal_II.so.8.5.0-pre
-rwxr-xr-x 1 kronbichler lnm  125389592  7. Nov 23:32 libdeal_II.so.8.5.0-pre
```
So there is an increase, but it is not dramatic.

**Comment by davydden** [comment]
@kronbichler so it looks like it has almost no effect on the library sizes? From this perspective #3500 is probably a false direction to take. What you said above

> Another thing that comes to mind is to split vector_tools.templates.h into a bunch of separate files called vector_tools_project.templates.h or vector_tools_project_mf.templates.h in analogy to the .cc files. It should not affect the amount of code that is generated but there should be considerably fewer symbols which might help.

is probably a better strategy to investigate? I can easily move all QP projections into `vector_tools_project_qp.templates.h` as they are not using anything else from `VectorTools`.

**Comment by bangerth** [comment]
Well, the difference if 42MB :-)

**Comment by kronbichler** [comment]
@davydden There is a 5% increase in the release version and 4% in the debug version, which is probably mostly due to the matrix-free code. I'm not sure #3500 would help. I would definitely like to see the effect of splitting up files.

**Comment by davydden** [comment]
> I would definitely like to see the effect of splitting up files.

will try tomorrow...
