### ISSUE TITLE
Problems in handling the userdata of Distributed Triangulation

### ISSUE THREAD

**Issue by mpscIMR** [dealii/dealii#3389]
I add the userdata to each cell using the user_pointer. It seems that the userdata of some cells which are changed during the refining and coarsening procedure will lose. How can make sure that the refined children cells(the coarsened parent cell) inherit the userdata from the parent (the children). 

And how can I obtain the userdata of ghost cells （userdata of the neighbor cell, but the neighbor cell happen to belong to other process rather the present process）during parallel distributed computing?

Thanks very much!!

**Comment by jppelteret** [comment]
This relates to [this post](https://groups.google.com/forum/#!topic/dealii/Rqg7gwmS0Rg) on the forum and is being addressed there. Since this is the case, do you mind if I close this issue?

**Comment by mpscIMR** [comment]
Thanks very much. I will close this issue.
