### ISSUE TITLE
Convert boundaries->manifolds

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#339]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on November 14, 2014 03:28:58_

Now that we have manifolds well supported, we should go through the tutorial programs and replace boundary objects by manifold objects where appropriate.

I think that this would apply to steps 1, 2, 5, 6, 10, 11, 15, 16, 18, 24, 29, 32, 34, 38, 42, 47. What a depressingly long list :-(

_Original issue: http://code.google.com/p/dealii/issues/detail?id=264_

**Comment by luca-heltai** [comment]
I'll start with the first ones...

**Comment by luca-heltai** [comment]
I started doing step-1. This raises an issue, that I'd like to discuss here. In #413  I added a couple of functions which copy boundary and material ids to manifold ids. Now I'm creating another couple which simply sets all these ids to a given value, either for all ids or only for faces at the boundary. Should this go into `GridTools`, or should I add this directly to `Triangulation`?

Triangulation has the following functions:

~~~ C++
tria.set_manifold(0, manifold_obj) // Assign manifold_obj to manifold id 0
tria.set_manifold(0) // Remove the manifold associated to manifold id 0
~~~

I suggest adding also

~~~ C++
tria.set_all_manifold_ids(0) // Set all manifold ids of the Triangulation to 0
tria.set_all_manifold_ids_on_bondary(2) // Set all manifold ids of the boundary of the Triangulation to 2
~~~

Which would make the transition from `Boundary` to `Manifold` require, almost everywhere, only a single function call from Tria. Putting the above in `GridTools` has the disadvantage of adding another include in `step-1`, just for that function:

~~~ C++
GridTools::set_all_manifold_ids(0, tria);
GridTools::set_all_manifold_ids_on_boundary(2, tria);
~~~

What do you think? Should this go in GridTools or in Triangulation?

**Comment by luca-heltai** [comment]
I've just issued PR #422 which implements the Triangulation version...

**Comment by bangerth** [comment]
You already made the decision, and I'm ok with it. I think as a general rule, we've come to the conclusion that it's best to keep the interface of `Triangulation` as small as possible. In particular, I view `Triangulation` as a container that stores cells, faces, etc. Operations that act on this container should go into `GridTools`.
