### ISSUE TITLE
Static analysis: dealii-git/source/grid/grid_generator.cc

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3414]
```
dealii-git/source/grid/grid_generator.cc	1740	warn	V560 A part of conditional expression is always true: dim > 1.
```

We should address these warnings and errors from the static analysis tool PVS. In response to #3342.

**Comment by masterleinad** [comment]
@bangerth You were faster. :smile:

**Comment by bangerth** [comment]
Ah, my apologies. I'm done for a while with these patches. If you want to work on some, please do go ahead!
