### ISSUE TITLE
Static analysis: dealii-git/source/lac/sparsity_tools.cc

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3422]
```
dealii-git/source/lac/sparsity_tools.cc	228	err	V530 The return value of function 'remove_if' is required to be utilized.
```

We should address these warnings and errors from the static analysis tool PVS. In response to #3342.

**Comment by drwells** [comment]
cppcheck caught this one too, but my conclusion at the time was that there really is not anything for us to do with this value.

**Comment by bangerth** [comment]
I think I recall that `remove_if` does not actually eliminate elements from a collection, but just reorders them in such a way that all "removed" elements are at the end. The returned iterator then points to the beginning of the removed set of elements, and it makes sense that user code will want to use this iterator -- for example to actually remove these elements from the collection.

I'll have to look up how exactly the semantics of that function were.

**Comment by tjhei** [comment]
Yes, this looks like a bug to me.

**Comment by bangerth** [comment]
Here is a description of `remove_if`: http://www.cplusplus.com/reference/algorithm/remove_if/
