### ISSUE TITLE
lac/precondition_chebyshev_03 fails with different results

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3490]
On my system, the `lac/precondition_chebyshev_03` fails with slightly but noticeably different results. I though that this is because we only output 2 digits, so I switched that to 4 digits and now get the following diffs:
```
4761: lac/precondition_chebyshev_03.debug: DIFF failed. ------ First 50 lines diff output:
4761: *** /home/fac/f/bangerth/p/deal.II/1/dealii/tests/lac/precondition_chebyshev_03.with_lapack=true.output   Mon Oct 31 10:38:43 2016
4761: --- output        Mon Nov  7 09:51:34 2016
4761: ***************
4761: *** 1,13 ****
4761:
4761:   DEAL::Size 4 Unknowns 9
4761: ! DEAL::Residual step i=0:   ilu=0.33, cheby=0.08
4761: ! DEAL::Residual step i=1:   ilu=0.36, cheby=0.08
4761: ! DEAL::Residual step i=2:   ilu=0.17, cheby=0.05
4761:   DEAL::Size 8 Unknowns 49
4761: ! DEAL::Residual step i=0:   ilu=1.94, cheby=0.14
4761: ! DEAL::Residual step i=1:   ilu=2.15, cheby=0.15
4761: ! DEAL::Residual step i=2:   ilu=1.76, cheby=0.15
4761:   DEAL::Size 16 Unknowns 225
4761: ! DEAL::Residual step i=0:   ilu=6.15, cheby=0.38
4761: ! DEAL::Residual step i=1:   ilu=6.25, cheby=0.40
4761: ! DEAL::Residual step i=2:   ilu=5.65, cheby=0.37
4761: --- 1,13 ----
4761:
4761:   DEAL::Size 4 Unknowns 9
4761: ! DEAL::Residual step i=0:   ilu=0.3321, cheby=0.0936
4761: ! DEAL::Residual step i=1:   ilu=0.3592, cheby=0.0930
4761: ! DEAL::Residual step i=2:   ilu=0.1717, cheby=0.0561
4761:   DEAL::Size 8 Unknowns 49
4761: ! DEAL::Residual step i=0:   ilu=1.9436, cheby=0.1634
4761: ! DEAL::Residual step i=1:   ilu=2.1487, cheby=0.1655
4761: ! DEAL::Residual step i=2:   ilu=1.7563, cheby=0.1630
4761:   DEAL::Size 16 Unknowns 225
4761: ! DEAL::Residual step i=0:   ilu=6.1463, cheby=0.4249
4761: ! DEAL::Residual step i=1:   ilu=6.2524, cheby=0.4315
4761: ! DEAL::Residual step i=2:   ilu=5.6540, cheby=0.4061
4761:
4761:
```
But even if I switch to this, whoever got 0.08 in the first line will not get anything close enough to 0.0936 to make numdiff happy.

Any idea what may be going on?

**Comment by kronbichler** [comment]
This is my bad. I changed the eigenvalue estimate of the Chebyshev preconditioner slightly in #3476 but only checked the `matrix_free` tests rather than the Chebyshev tests. I will adjust the output.

It is a pity that the eigenvalue estimates are a bit worse now. In order to fix that, I will manually add a new variant that triggers high frequencies yet avoids random numbers because they depend on the state which is bad for a preconditioner.

There is also another failure to be addressed:
http://cdash.kyomu.43-1.org/testDetails.php?test=8599918&build=2317

**Comment by bangerth** [comment]
Thanks for looking into this. While there, add a couple more digits to the output to avoid the obvious round-off problems.

If you need random numbers, you can always locally create a BOOST random number generator. It will yield the same sequence of numbers every time.
