### ISSUE TITLE
Static analysis: include/deal.II/lac/petsc_vector_base.h

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3538]

**Comment by bangerth** [comment]
Close. I accidentally deleted the text of in the issue :-(

**Comment by bangerth** [comment]
We should address these warnings and errors from the static analysis tool PVS:
```
include/deal.II/lac/petsc_vector_base.h	230	warn	V690 The 'VectorBase' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class.
```

In response to #3342.

**Comment by bangerth** [comment]
This looks like a real bug.

**Comment by drwells** [comment]
I spent some time looking over the copy constructors and assignment operators for `VectorBase`, `Vector`, and `MPI::Vector`: the two inheriting classes need different copy logic based on whether or not they contain ghost entries (they already implement this) so I am not sure what the use of any copy operators or constructors is in the base class.

If one comments out the copy constructor in `VectorBase` then everything still compiles (and there don't seem to be any failures in the test suite) so I recommend deprecating this and then (in a year or so) marking the copy constructor and `operator=` with `=delete`. Thoughts?

**Comment by tjhei** [comment]
Interestingly, we call the default ``operator=`` from the derived classes, but we never use the constructors. Shouldn't ``VectorBase`` also be abstract?

My suggestions:
- make ``VectorBase`` abstract
- just remove all constructors (they are unused!)
- implement ``operator=``. I think the default implementation is incorrect (you can not just assign a PETSc ``Vec``).

I can take a look if we agree on this.

**Comment by drwells** [comment]
@tjhei This sounds reasonable. My only concern is that if `Vector` and `MPI::Vector` both also implement `operator=` and we do something like `v->operator=(...)` then we will end up with the wrong copy operator.

**Comment by tjhei** [comment]
True. The design of ``VectorBase`` is really weird: all operations are going to be messed up if you work with a pointer to ``VectorBase``. Hrm.

**Comment by drwells** [comment]
I can think of two ways around this:
1. make all `operator=`s virtual. While this might be the right thing to do the phrase 'overridden virtual operator overload' strikes fear in my heart.
2. Implement a protected member function `copy_owned_vector` that copies all of the things the base class knows about.

It might be better to start by refactoring this class: both `MPI::Vector` and `VectorBase` implement logic for handling the ghost values but these should really be in one class or the other: it seems strange that things are in both.

**Comment by bangerth** [comment]
I'm not too worried by someone actually using a pointer to base. I would just remove the `operator=`, without deprecation, if what it does simply makes no sense.

As for @drwells 's options:

* Making `operator=` virtual is not usually a useful strategy. That's because the operator in the base class takes a reference to base, whereas the one in the derived class takes a reference to derived. So it doesn't actually overload the one in the base class. That, by the way, also explains why something like `*base_ptr = some_vec` will simply never yield anything useful unless the base class explicitly has `operator=` implementations that take reference-to-derived as arguments.

* `copy_owned_vector`: I suspect that what an `operator=` actually does critically depends on what kind of object we actually have. So I would favor simply not doing anything at all with regard to copying in the base class, and just do it all in the derived classes. That would call for also just deleting `operator=` in the base class in C++11 mode -- that would take away another source of possible errors.

**Comment by drwells** [comment]
@bangerth Those are good points. I did not really like either option anyway so I agree that it would be best to get rid of these copy operators.

**Comment by drwells** [comment]
I'll get to this at some point this week.

**Comment by drwells** [comment]
I am still working on this: removing `operator=` did expose some latent bugs.
