### ISSUE TITLE
Static analysis: source/lac/trilinos_sparse_matrix.cc

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3567]

**Comment by bangerth** [comment]
Close. I accidentally deleted the text of in the issue :-(

**Comment by bangerth** [comment]
We should address these warnings and errors from the static analysis tool PVS:
```
source/lac/trilinos_sparse_matrix.cc	702	warn	V614 Potentially null smart pointer 'nonlocal_graph' used.
```

In response to #3342.

**Comment by masterleinad** [comment]
We check the validity of `nonlocal_graph` in the line above via `Assert(nonlocal_graph.get() != 0, ExcInternalError());` at least in debug mode.
