### ISSUE TITLE
use shared_ptr to store MatrixFree data in MatrixFreeOperators::Base

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3606]
subj, as discussed in https://github.com/dealii/dealii/pull/3329#issuecomment-257406633.

**Comment by Rombur** [comment]
@davydden I am working on this issue. Do you want to keep the current interface for [VectorTools::project](http://dealii.org/developer/doxygen/deal.II/namespaceVectorTools.html#a5cbdff3ad3ff3e74a95ecbdf85e7d23b) or also use a `shared_ptr` there?

**Comment by davydden** [comment]
I would keep interface of "project" unchanged. It is a one-time affair and IMO there is no need to share it there
