### ISSUE TITLE
Use Assert or AssertThrow for PETSc errors?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3620]
This is more of a request for discussion: @drwells 's #3576 adds a lot of checks for PETSc return values that we had previously ignore -- great progress. These are now all checked with `AssertThrow`, i.e., if they fail, we get an exception, not an `abort()`. 

Is this the right way to handle this? My sense is mostly that if you get an error from PETSc, it's because you do something that's wrong statically -- e.g., accessing elements of a matrix that don't exist, or calling functions with the wrong types of arguments. This would call for an `Assert`. The advantage of `Assert` is that it aborts the program and makes it supremely easy to find the place where this happened in a debugger.

Opinions?

**Comment by bangerth** [comment]
I should add that in practice, it matters little because we don't tend to get a lot of errors from PETSc -- these calls are all hidden from users and we seem to rarely call them with arguments we haven't already checked in our own wrappers.

**Comment by drwells** [comment]
Thanks :)

While I do not have much experience debugging PETSc my impression was that GDB can generate a complete backtrace for an uncaught exception as well as it can for an abort. Is this not true? If GDB cannot then it might make sense to switch.

I agree with your description of the frequency PETSc errors (they should never be encountered by users if we do things right).

I am in favor of using `AssertThrow`: these checks are cheap and if we ask PETSc to do something and it fails then something must have gone horribly wrong, so we should quit.

**Comment by tjhei** [comment]
> I am in favor of using AssertThrow: these checks are cheap and if we ask PETSc to do something and it fails then something must have gone horribly wrong, so we should quit.

Agreed. Another argument might be that some of these issues only appear for larger, parallel runs that likely are running in release mode (for example a machine ends up without any cells on a large computation and has a missing compress() ).

**Comment by bangerth** [comment]
But if we "should quit", then `Assert` is the right thing to do since it quits *right away* :-)

gdb can give you a backtrace if you do `catch throw` and then run the program -- that stops the program every time it encounters a `throw` command of any kind. But that's going to stop at every exception we throw, whether expected or not.

**Comment by davydden** [comment]
> I am in favor of using AssertThrow: these checks are cheap and if we ask PETSc to do something and it fails then something must have gone horribly wrong, so we should quit.

also in favour of this approach!

> Another argument might be that some of these issues only appear for larger, parallel runs

:+1:

**Comment by bangerth** [comment]
OK, so decided!
