### ISSUE TITLE
Incompatibility with 'emplace_hint' function and gcc versions below 4.8

### ISSUE THREAD

**Issue by naliboff** [dealii/dealii#3624]
This follows an issue raised on the ASPECT (https://github.com/geodynamics/aspect/issues/1271) GitHub page relating to deal.ii and the 'emplace_hint' function, which @bangerth was able to pinpoint. 

GCC versions prior to 4.8 do not contain the 'emplace_hint' function in map.h, but the checks in `boost/config/stdlib/libstdcpp3.hp` do not pick this up:
`//  C++0x headers in GCC 4.3.0 and later`
`//`
`#if (BOOST_LIBSTDCXX_VERSION < 40300) || !defined(BOOST_LIBSTDCXX11)`
`#  define BOOST_NO_CXX11_HDR_ARRAY`
`#  define BOOST_NO_CXX11_HDR_TUPLE`
`#  define BOOST_NO_CXX11_HDR_UNORDERED_MAP`
`#  define BOOST_NO_CXX11_HDR_UNORDERED_SET`
`#  define BOOST_NO_CXX11_HDR_FUNCTIONAL`
`#endif`

While deal.II compiles, to successfully compile the current developer version of ASPECT (uses of `emplace_hint` function) requires passing the following flag before calling `cmake` for deal.II:
`export CXXFLAGS=-DBOOST_NO_CXX11_HDR_UNORDERED_MAP`.

I'm not sure what the fix is here, but the issue has now been raised ;)

**Comment by bangerth** [comment]
To be precise, BOOST checks the wrong condition: It uses `emplace_hint` if it knows that there are unordered maps. But `emplace_hint` was apparently only added after GCC 4.8, even though 4.8 already had the unordered maps.

We ought to write a small test that checks (i) whether the `emplace_hint` function exists, and (ii) if not, `#define` the variables `BOOST_NO_CXX11_HRD_UNORDERED_MAP`.

**Comment by tjhei** [comment]
> (uses of emplace_hint function)

No, the bug is triggered when using ``boost/serialization/map.hpp``.

> We ought to write a small test that

I don't like the idea of defining ``BOOST_NO_CXX11_HDR_UNORDERED_MAP`` because this will have other impacts (for example using boost's unordered map in algorithm/searching/, etc.). But without this check 1.62, which we bundle, has a broken ``boost/serialization/map.hpp``. :-(

We could also do this define only in ASPECT before including ``boost/serialization/map.hpp`` or not?

**Comment by bangerth** [comment]
I wanted to do it in deal.II because *any* user of that header file will get the error, whether from deal.II or from ASPECT. Your suggestion of defining it right before the point of use could work, though.

**Comment by tamiko** [comment]
At the minimum we should set a check and export the defines for our bundled boost. I will make a PR.

**Comment by bangerth** [comment]
I reported this to the good folks at BOOST here: https://svn.boost.org/trac/boost/ticket/12755

It is still an issue with boost 1.63 (the current release).
