### ISSUE TITLE
improve documentation of FiniteElement::system_to_base_index() and alike

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3646]
the current description
>Return for shape function index the base element it belongs to, the number of 
the copy of this base element (which is between zero and the multiplicity of this element), 
and the index of this shape function within this base element.

> If the element is not composed of others, then base and instance are always zero, and the index 
is equal to the number of the shape function. If the element is composed of single instances of 
other elements (i.e. all with multiplicity one) all of which are scalar, then base values and dof 
indices within this element are equal to the system_to_component_table. It differs only in case 
the element is composed of other elements and at least one of them is vector-valued itself.

> This function returns valid values also in the case of vector-valued (i.e. non-primitive) shape functions, in contrast to the system_to_component_index() function.

from my perspective is not enough to understand what is written where in rather complicated output `
std::pair< std::pair< unsigned int, unsigned int >, unsigned int >`. I certainly figured it out at some point, but already forgot.

**Comment by jppelteret** [comment]
I agree that anything that we can do to improve the interpretation of what `system_to_base_index` and `system_to_component_index` returns would be very useful. I actually often refer to a table of outputs that @davydden once produced 

![fe_components](https://cloud.githubusercontent.com/assets/10460610/20701956/eb6c50f8-b615-11e6-90f3-9166f443f19c.png)

to confirm my understanding of what these return. Perhaps we should create a similar table in the documentation or decompose the compound output of these functions into individual functions?

**Comment by tjhei** [comment]
Neat! I think this should also include an image created with ``write_gnuplot_dof_support_point_info``, similar to

![](http://www.dealii.org/developer/doxygen/deal.II/support_point_dofs2.png)

(ignore the right cell)
