### ISSUE TITLE
Testsuite doesn't work with spaces in the path 

### ISSUE THREAD

**Issue by vinayak-gholap1993** [dealii/dealii#3659]
```
1: path/to/dealii/share/deal.II/scripts/run_test.sh: 47: /path/to/dealii/share/deal.II/scripts/run_test.sh: /media/vinayak/New: not found
```

the path to the project is actually `/media/vinayak/New Folder/....`.

**Comment by tamiko** [comment]
Honestly, that doesn't surprise me. I will have a look at the scripts involved and add all necessary quotes.
