### ISSUE TITLE
check that numdiff is working before using

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3661]
when setting up unit tests (in user's project) we should try at least running `numdiff -v` to make sure `numdiff` is sane. 

Otherwise user's unit tests fail in a very hard-to-debug way.

**Comment by tamiko** [comment]
The current behavior is that we look for an executable numdiff and if found, use it.

What exactly do we gain by trying to execute `numdiff -v`?

For example, if numdiff happens to be a symlink to diff, `numdiff -v` would be fine, but any further execution of numdiff with parameters would fail.

**Comment by davydden** [comment]
> What exactly do we gain by trying to execute numdiff -v?

at least we test that it runs, i just had an issue with a student for whom unit tests with deal.II did not work. It turned out that his `numdiff` installation was broken, it just hanged, even on `numdiff -v`. Bottom line, IMHO we gain enough from running `numdiff -v` before using `numdiff`.

**Comment by bangerth** [comment]
What do we want to do with this issue?

**Comment by davydden** [comment]
> What do we want to do with this issue?

i would prefer this to be addressed because one of my students got into "or, dealii tests don't work at all, something is broken", and it turned out that `numdiff` was not running at all. So simple `numdiff -v` check would suffice to rule this out.

**Comment by sairajat** [comment]
I think, the same thing happened with me. I did not have numdiff installed and 20 / 121 tests were being reported as failed in the diff stage because of leading white spaces. #3969

**Comment by davydden** [comment]
> I think, the same thing happened with me. I did not have numdiff installed and 20 / 121 tests were being reported as failed in the diff stage because of leading white spaces. #3969

actually this is a different problem. We do allow running tests without `numdiff`, it's just not recommended. This issue is related to broken `numdiff` which hanged infinity when being run.
