### ISSUE TITLE
Possible error in SymmetricTensor constructor

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3674]
I think that there may be a bug with constructor for the `SymmetricTensor` class that takes a `SymmetricTensor` with a different number type as an argument.

If I'm not mistaken, [this line](https://github.com/dealii/dealii/blob/master/include/deal.II/base/symmetric_tensor.h#L989) should be changed from
```
for (unsigned int i=0; i<n_independent_components; ++i)
```
to
```
for (unsigned int i=0; i<base_tensor_type::dimension; ++i)
```

If I understand correctly then `n_independent_components` corresponds to all of the entries in the `data` `Tensor`, but `base_tensor_type::dimension` corresponds to the number of rows in the underlying `Tensor`.

I someone is willing to confirm this then I'll issue a PR for the change.

**Comment by davydden** [comment]
I agree with your interpretation of parameters, but i think it's the former (current status) which is correct. I don't recall exactly what `data` is, but looking at implementation of [trace](https://github.com/dealii/dealii/blob/master/include/deal.II/base/symmetric_tensor.h#L2221), i think `data[0:dim-1]` gives you diagonal elements for rank-2 tensor.

**Comment by jppelteret** [comment]
I'm busy debugging a case for a rank-4 `SymmetricTensor`, which I think highlights the issues whereas for rank-2 the problem isn't triggered. For the rank-2 case `data` is a 1-dimensional tensor, so `length(data) == n_rows(data) == n_independent_components`. However for the rank-4 case `data` is a Tensor<2,...> so `n_independent_components == n_rows(data)*n_rows(data)`. 

If need be I can make a minimal test case to highlight the problem. I suppose I should probably do this anyway...

**Comment by bangerth** [comment]
I think @jppelteret is correct for rank-4 tensors, because these are stored as rank-2 non-symmetric tensors. We are reading and writing past the end in that loop.

Patch and testcase as always appreciated :-)

**Comment by davydden** [comment]
yes, he's right, i forgot to reply here, we chatted an hour ago in the office about this issue.

**Comment by jppelteret** [comment]
Ok, thanks for the confirmation. Patch and test case coming soon.
