### ISSUE TITLE
Assert is_compressed in IndexSet::nth_index_in_set() does not work

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3680]
I found out hard way that
```
  const unsigned int size = 100;

  IndexSet locally_owned(size);
  locally_owned.add_range(0,size);
  
  locally_owned.nth_index_in_set(0)
```
runs perfectly fine in `Debug` mode but fails with segmentation fault in `Release`. Obviously ` locally_owned.compress()` is missing, but the point is that
```
Assert (is_compressed == true, ExcMessage ("IndexSet must be compressed."));
```
inside `nth_index_in_set()` did not throw any error in `Debug` mode either. So this flag must be set to `true` somewhere else which makes the assert not useful.

**Comment by bangerth** [comment]
Interesting. Are you working on a patch or do you want others to look at this? It sounds like you already know what the problem is :-)

**Comment by davydden** [comment]
no, i am not working, i don't really know where it is :smile:

**Comment by bangerth** [comment]
OK, I can take a look sometime.

**Comment by bangerth** [comment]
Hm, when I make your code snippet into a test program, then I get kicked out with an exception in debug mode:
```
index_set_27.debug> ./index_set_27.debug 

--------------------------------------------------------
An error occurred in line <1609> of file </home/bangerth/p/deal.II/1/dealii/include/deal.II/base/index_set.h> in function
    dealii::IndexSet::size_type dealii::IndexSet::nth_index_in_set(unsigned int) const
The violated condition was: 
    is_compressed == true
Additional information: 
    IndexSet must be compressed.
--------------------------------------------------------

Aborted (core dumped)
```

**Comment by bangerth** [comment]
So the assert works as expected. We should just add the call to `compress` at the top; see also #3681 for more.

**Comment by davydden** [comment]
> So the assert works as expected.

i will check in small program, but it certainly did not throw any errors my mac in Debug mode.
