### ISSUE TITLE
doxygen of FEEvaluation lacks some functions like submit_symmetric_gradient()

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3694]
subj, just search for `submit_symmetric_gradient` in https://www.dealii.org/developer/doxygen/deal.II/classFEEvaluation.html .

**Comment by davydden** [comment]
it looks like it does not show `Public member functions inherited from FEEvaluationAccess`.

**Comment by kronbichler** [comment]
@davydden The problem with `submit_symmetric_gradient` is that it comes from a *specialization* of `FEEvaluationAccess`. This is because a symmetric gradient is only defined in case `n_components==dim`, and similarly a `divergence` and `curl`.

**Comment by kronbichler** [comment]
Even though it would be nice if this would show somehow, I do not know a way to do that. Providing a `submit_symmetric_gradient` for other cases does not make much sense and would rather confuse people I suppose...

**Comment by davydden** [comment]
Can we make doxygen pick up specialised cases somehow, similar to what happens with `Tensor` class [here](https://www.dealii.org/developer/doxygen/deal.II/classTensor.html)?

**Comment by tjhei** [comment]
One hack would be to do something like:
```
#ifdef DOXYGEN
/** @copydoc FEEvaluationAccess<dim,dim,number>::submit_symmetric_gradient()
 * @note: only available for dim==spacedim. 
 */
void submit_symmetric_gradient(const SymmetricTensor<2,dim,VectorizedArray<Number> > grad_in,
                                 const unsigned int      q_point);
#endif
```
Anybody want to give this a try?

**Comment by davydden** [comment]
Anyone @dealii/dealii knows another way to make doxygen pick up function  from a specialization of FEEvaluationAccess, i will try @tjhei 's workaround.

**Comment by davydden** [comment]
I am going to ask for advice on doxygen mailing list, there must be a way to add those partial template specialization of `n_components=dim` and `n_compoennts=1`.

**Comment by davydden** [comment]
an alternative would be to somehow make doxygen create documentation of partial specialization of `FEEvaluation`...

**Comment by davydden** [comment]
@tjhei 's idea works! If I won't hear anything from Doxygen mailing list/[stackoverflow](http://stackoverflow.com/questions/42140186/doxygen-show-in-derived-class-function-due-to-partial-template-specialization-o), i will create a PR with the workaround.
