### ISSUE TITLE
running `make documentation` installs documentation

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3696]
This currently occurs on master. I have no idea how long this has been going on.

I'll do some bisecting later today to try and figure this out.

**Comment by bangerth** [comment]
As long as I can remember, probably since @tamiko rewrote the configuration and make bits in cmake.

Is there even a `make doc-install` target or similar?

**Comment by drwells** [comment]
You are right: it has been this way since the move to CMake. Running `make documentation` installs the docs, but just running `make` does not. I guess this is mostly useful if one just wants to check the documentation (which is what I was doing).

I don't think that we have a `doc-install` target. That would probably be the right way to do things.

**Comment by tamiko** [comment]
If you only want to install a certain component the 'cmake'ism is
```
  $ cmake -P cmake_install.cmake -DCOMPONENT=...
```

The relevant code is in the following file `cmake/setup_custom_targets.cmake`:
```
 17 # Add convenience targets that build and install only a specific component:      
 18 #                                                                                
 19 #   library                                                                      
 20 #   documentation                                                                
 21 #   examples 

 25 IF("${CMAKE_INSTALL_PREFIX}" STREQUAL "/usr/local")                              
 26   #                                                                              
 27   # In case that CMAKE_INSTALL_PREFIX wasn't set, we assume that the user        
 28   # doesn't actually want to install but just use deal.II in the build           
 29   # directory. In this case, do not add the "install" phase to the               
 30   # convenience targets.                                                         
 31   #  
```

**Comment by drwells** [comment]
@tamiko is there a supported way to build, and not install, just the documentation?

**Comment by tamiko** [comment]
@drwells The logic so far is that if you do not set `CMAKE_INSTALL_PREFIX` a `make documentation` simply invokes the relevant targets (in this case doxygen, etc.). If you set `CMAKE_INSTALL_PREFIX`, the documentation gets installed, too.

The targets in `cmake/setup_custom_targets.cmake` are an ugly hack to conveniently install parts of the library. I have no problem if we decide to nuke it entirely (if you feel religious about `make documentation` trying to install something).

**Comment by drwells** [comment]
@tamiko I don't feel strongly about this and, since the current behavior is clearly documented in `cmake/setup_custom_targest.cmake` I think what we currently have is fine.
