### ISSUE TITLE
Licence file refers to non-existent document

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3701]
The author list referred to [in the licence file](https://github.com/dealii/dealii/blob/master/LICENSE#L5) does not appear to exist in the repository. Perhaps it should be pointing to [this page](http://www.dealii.org/authors.html) nowadays?

**Comment by tjhei** [comment]
Yes, that makes sense. Can you open a PR?

**Comment by tamiko** [comment]
> The author list referred to [in the licence
> file](https://github.com/dealii/dealii/blob/master/LICENSE#L5) does
> not appear to exist in the repository. Perhaps it should be pointing
> to [this page](http://www.dealii.org/authors.html) nowadays?

It might be good to also refer to the file AUTHORS as well that we
generate for every release.

**Comment by jppelteret** [comment]
I didn't notice that this AUTHORS file exists for releases, and that the license file is adjusted accordingly. I'll make another PR adding it in alongside the URL, and if its considered not to be appropriate then someone can just close the PR.
