### ISSUE TITLE
Trilinos VectorReference constness

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3726]
I reran cppcheck yesterday (patches are on their way) and found the following strange bit of code:

```cpp
/**
* Same as above but for non-const reference objects.
*/
const VectorReference &
operator = (const VectorReference &r);

/**
* Set the referenced element of the vector to <tt>s</tt>.
*/
const VectorReference &
operator = (const TrilinosScalar &s) const;
```

Should the first function return a `const VectorReference &`? The equivalent function in `PETScWrappers::VectorBase` does *not* return a `const` reference.

**Comment by bangerth** [comment]
It probably doesn't matter because one rarely keeps objects of this type around -- they only appear as temporary objects somewhere.

But you can probably construct a testcase that fails currently by saying
```
  Reference a, b, c;
  c = ...;
  (a = b) = c;
```
which should be equivalent to `a=b; a=c` but currently probably doesn't compile.
