### ISSUE TITLE
Build system error when using CUDA and cmake 3.7

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#3743]
I can't configure deal with cuda when using cmake 3.7. Everything works fine with cmake 3.6. 
cc: @kalj 

CMake Error at /home/bruno/spack/opt/spack/linux-ubuntu16-x86_64/gcc-6.2.0/cmake-3.7.1-m2qgd6oxyuihv6ildladecgkbdub357x/share/cmake-3.7/Modules/FindCUDA.cmake:1512 (file):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:obj_lac_debug,INCLUDE_DIRECTORIES>

  Target "obj_lac_debug" not found.
Call Stack (most recent call first):
  cmake/macros/macro_deal_ii_add_library.cmake:55 (CUDA_WRAP_SRCS)
  source/lac/CMakeLists.txt:150 (DEAL_II_ADD_LIBRARY)

**Comment by tamiko** [comment]
@Rombur I'll have a look.

@kalj @Rombur I am seriously fed up with the whacky state of `FindCUDA.cmake` and the very limited macros it exports. Further, all the CMake stuff for CUDA we implemented so far is way too intrusive for my taste (the cuda compiler stuff always assumes to be in charge - which is a pita with the current cmake stuff of our library). @kalj, your proposal to have a thorough look at the FindCUDA.cmake file and simply implement our own macros looks appealing.

Let me think about this for a bit and come back to you later today.

**Comment by tamiko** [comment]
I gave a nice little speech. Now, the bugfix.
