### ISSUE TITLE
New cmake warning about BOOST

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3765]
Not sure if because of a recent patch, or because I upgraded to a newer version of Ubuntu (with the newer cmake 3.5), but I now get these cmake warnings:
```
-- Include /home/bangerth/p/deal.II/1/dealii/cmake/configure/configure_boost.cmake
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/modules/FindBOOST.cmake:46 (FIND_PACKAGE)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/configure/configure_boost.cmake:53 (FIND_PACKAGE)
  /home/bangerth/p/deal.II/1/build/CMakeFiles/CMakeTmp/macro_configure_feature.tmp:1 (FEATURE_BOOST_FIND_EXTERNAL)
  cmake/macros/macro_configure_feature.cmake:76 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:245 (RUN_COMMAND)
  cmake/configure/configure_boost.cmake:74 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/modules/FindBOOST.cmake:46 (FIND_PACKAGE)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/configure/configure_boost.cmake:53 (FIND_PACKAGE)
  /home/bangerth/p/deal.II/1/build/CMakeFiles/CMakeTmp/macro_configure_feature.tmp:1 (FEATURE_BOOST_FIND_EXTERNAL)
  cmake/macros/macro_configure_feature.cmake:76 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:245 (RUN_COMMAND)
  cmake/configure/configure_boost.cmake:74 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/modules/FindBOOST.cmake:46 (FIND_PACKAGE)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/configure/configure_boost.cmake:53 (FIND_PACKAGE)
  /home/bangerth/p/deal.II/1/build/CMakeFiles/CMakeTmp/macro_configure_feature.tmp:1 (FEATURE_BOOST_FIND_EXTERNAL)
  cmake/macros/macro_configure_feature.cmake:76 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:245 (RUN_COMMAND)
  cmake/configure/configure_boost.cmake:74 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)

[...]
```

Any insight?

**Comment by tamiko** [comment]
Such a warning is pretty much out of our control.

My guess is that not all boost dependencies/modules are installed on your machine, or your boost version is too old for the FindBoost.cmake file shipped with CMake.

**Comment by Rombur** [comment]
Which version of boost do you use? It may be related to this https://github.com/dealii/dealii/pull/3279#issuecomment-255738397 but @drwells said he didn't have this problem with cmake 3.5

**Comment by drwells** [comment]
Yes: I was running CMake 3.5 while working on that patch and I did not notice any such problem with the bundled copy of boost.

**Comment by tamiko** [comment]
That doesn't surprise me :-) In case of bundled boost the external `FindBoost.cmake` shipped with CMake isn't used.

**Comment by bangerth** [comment]
The bundled boost I use is 1.61 but as far as I can see, I only have the libraries, not the headers installed. deal.II correctly seems to fall back to the bundled version then.

What does the warning message actually say? I can't figure out what it tries to tell me...

**Comment by tamiko** [comment]
@bangerth 

I had a look at `FindBoost.cmake`.
Your `FindBoost.cmake` shipped with your CMake 3.5* is too old for Boost 1.61.
Thus, it cannot declare import targets.

Well, we don't use import targets but unfortunately, this doesn't stop the CMake module from complaining.

Here is the logic:

```
if(NOT Boost_VERSION VERSION_LESS 103300 AND Boost_VERSION VERSION_LESS 103500)

# ...

elseif(NOT Boost_VERSION VERSION_LESS 105900 AND Boost_VERSION VERSION_LESS 106000)
  # ...
else()
  message(WARNING "Imported targets not available for Boost version ${Boost_VERSION}"
  set(_Boost_IMPORTED_TARGETS FALSE)
endif()
```

**Comment by bangerth** [comment]
Hm, ok. I guess there is nothing we can do then. We should probably just close this then, right?

Is the warning a problem at all? I have no idea what an "imported target" actually is. (I read https://cmake.org/Wiki/CMake/Tutorials/Exporting_and_Importing_Targets , but as almost always I find that the cmake documentation is poorly written because it is almost exclusively focused on *how* to use a feature, not *why* the feature is there to begin with.

**Comment by tamiko** [comment]
@bangerth No, that's not a problem - we don't use imported targets in our build system configuration (it is already a mess - and with two different strategies of keeping track of external libraries it will get worse).

I close :-)

**Comment by dkarma** [comment]
This isn't just a warning for me it's broken even with cmake 3.10:
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


CMake Error at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


Boost_FOUND NOT FOUND
-- Configuring incomplete, errors occurred!
See also "/home/dkarma/Downloads/nheqminer-master/nheqminer/build/CMakeFiles/CMakeOutput.log".
See also "/home/dkarma/Downloads/nheqminer-master/nheqminer/build/CMakeFiles/CMakeError.log".

**Comment by LongruiDong** [comment]
@dkarma 
having same error with you,have you solved  it?
thanks ~

**Comment by shliang0603** [comment]
I met same error ,can you help me?

**Comment by shliang0603** [comment]
Call Stack (most recent call first):
  /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:40 (find_package)


CMake Warning at /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:40 (find_package)


CMake Error at /home/mosheng/.local/lib/python2.7/site-packages/cmake/data/share/cmake-3.12/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


CMake Error at CMakeLists.txt:48 (MESSAGE):
  Boost not found in the system.


-- Configuring incomplete, errors occurred!
See also "/home/mosheng/work2/project/OpenFace-master/build/CMakeFiles/CMakeOutput.log".

**Comment by drwells** [comment]
AFAICT the error messages @dkarma and @shliang0603 reported do not rely on deal.II.  There is very little we can do to debug other libraries or your own system installation of BOOST or CMake. Please move these discussions to (in the second case) OpenFace itself, i.e., https://github.com/Yureni/openface-master.
