### ISSUE TITLE
Rename the compute_n_pols() functions for polynomial spaces

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3774]
Various ones of the polynomial space classes have a function called `compute_n_pols()`. What it really is is the dimension of the polynomial space, but this is not really apparent from the function's name. 

There also seems to be some confusion as to what exactly these functions do. The documentation in the different classes is variable and not really conclusive. It may be possible to make some of these functions `private`, in which case the issue largely disappears.

**Comment by drwells** [comment]
Fixed by #8623.
