### ISSUE TITLE
GridGenerator

### ISSUE THREAD

**Issue by GJSST** [dealii/dealii#3802]
I can not use this class.
 template<int dim>
void GridGenerator::subdivided_hyper_rectangle 	( 	Triangulation< dim > &  	tria,
		const std::vector< std::vector< double > > &  	step_sizes,
		const Point< dim > &  	p_1,
		const Point< dim > &  	p_2,
		const bool  	colorize 
	)
I need your help.
[error_messages.txt](https://github.com/dealii/dealii/files/706439/error_messages.txt)

[program.txt](https://github.com/dealii/dealii/files/706437/program.txt)

My program and error messages is in the file.

**Comment by tamiko** [comment]
The type for `step_size` is wrong. What exactly did you try to achieve?

The following is a minimal working example:
```
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/grid/tria.h>

#include <fstream>

using namespace dealii;

void make_grid()
{
  Point<2> p1(0, 0);
  Point<2> p2(8, 8);

  Triangulation<2> tria;

  std::vector<unsigned int> step_size(2);
  step_size[0] = 2;
  step_size[1] = 5;

  GridGenerator::subdivided_hyper_rectangle(tria, step_size, p1, p2);

  std::ofstream out("grid.eps");
  GridOut().write_eps(tria, out);
}

int main()
{
  make_grid();
}
```

**Comment by GJSST** [comment]
Thank you for your answer.
And if I want to use the follow function to split the grid,How should I use it.
void GridGenerator::subdivided_hyper_rectangle ( Triangulation< dim > & tria,
const std::vector< std::vector< double > > & step_sizes,
const Point< dim > & p_1,
const Point< dim > & p_2,
const bool colorize
)

**Comment by GJSST** [comment]
@tamiko Thank you for your help.
And if I want to use the follow function to split the grid,How should I use it.
void GridGenerator::subdivided_hyper_rectangle ( Triangulation< dim > & tria,
const std::vector< std::vector< double > > & step_sizes,
const Point< dim > & p_1,
const Point< dim > & p_2,
const bool colorize
)

**Comment by davydden** [comment]
Did u check documentation https://www.dealii.org/8.4.0/doxygen/deal.II/namespaceGridGenerator.html#ab96bbbe1d7cd1a894dcc038028a9684a ?

**Comment by tamiko** [comment]
@GJSST 
In that case you unfortunately have to provide the last argument `bool colorize` as well due to a missing default parameter (will do a pull request for that):
```
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/grid/tria.h>

#include <fstream>

using namespace dealii;

void make_grid()
{
  Point<2> p1(0, 0);
  Point<2> p2(8, 8);

  Triangulation<2> tria;

  std::vector<double> steps_right = { 1. , 2., 1. , 4. };
  std::vector<double> steps_up = { 1. , 1., 1. , 1., 2., 2. };
  std::vector<std::vector<double> > steps = { steps_right, steps_up };

  GridGenerator::subdivided_hyper_rectangle(tria, steps, p1, p2, false);

  std::ofstream out("grid.eps");
  GridOut().write_eps(tria, out);
}

int main()
{
  make_grid();
}
```

**Comment by GJSST** [comment]
@tamiko I understand.Thank you very much for your help!

**Comment by jppelteret** [comment]
@GJSST For future reference, you're welcome to ask these sorts of questions on the [deal.II user group](https://groups.google.com/forum/#!forum/dealii) as well. It'll get exposure to more deal.II users there and may help assist someone who has a similar problem.
