### ISSUE TITLE
Document FiniteElement::interpolate

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3810]
As a follow-up to #3807: `FETools::compute_node_matrix` calls `FiniteElement::interpolate()`, which is another woefully under-documented function for which I can't really figure out what it is supposed to do...

**Comment by bangerth** [comment]
This is actually a bit of an interesting case to which I'd appreciate input on how to proceed. Fundamentally, what I believe this function does is that it takes a vector of values (as many as there are components of the element) for each support point, and returns the corresponding values of the element's degrees of freedom. (If this was an `FESystem(FE_Q, ncomp)` element, every vector's entries would be a DoF, but that is not the case for elements such as `FE_RaviartThomas`.)

The `FiniteElement` class now has a number of overloads of this function:
```
  /**
   * Interpolate a set of scalar values, computed in the generalized support
   * points.
   *
   * @note This function is implemented in FiniteElement for the case that the
   * element has support points. In this case, the resulting coefficients are
   * just the values in the support points. All other elements must
   * reimplement it.
   */
  virtual
  void
  interpolate(std::vector<double>       &local_dofs,
              const std::vector<double> &values) const;

  /**
   * Interpolate a set of vector values, computed in the generalized support
   * points.
   *
   * Since a finite element often only interpolates part of a vector,
   * <tt>offset</tt> is used to determine the first component of the vector to
   * be interpolated. Maybe consider changing your data structures to use the
   * next function.
   */
  virtual
  void
  interpolate(std::vector<double>                &local_dofs,
              const std::vector<Vector<double> > &values,
              const unsigned int                  offset = 0) const;


  /**
   * Interpolate a set of vector values, computed in the generalized support
   * points.
   */
  virtual
  void
  interpolate(std::vector<double>                                         &local_dofs,
              const VectorSlice<const std::vector<std::vector<double> > > &values) const;
```

There are a number of things I'm unhappy about this interface:

* Derived classes need to overload different versions of this function.
* The first is only a convenience function for the second in case the element is scalar
* The second and third functions seem duplicative, taking essentially the same information
* `VectorSlice` is a bit of an outdated class and I had previously replaced it by `ArrayView` in the `FEValues` interfaces to `Mapping` and `FiniteElement`.
* The `offset` argument to the second function is not actually used anywhere outside the testsuite; there, it is used, but not in a way that I understand as being a case that's important to preserve.
* The name of the function really doesn't give anything away about what it really does.
* The order of arguments is not what we usually use.

I am tempted to throw this entire set of functions away and start over with a cleaner interface. I don't want to be gratuitously incompatible; at the same time, given how poorly these functions document what they do, it's hard to believe that the function is widely used outside the library itself. Within the library, it is used in only one place, in `FETools::compute_node_matrix()`, where we call the third variant of the function.

What are people's opinions on this?

**Comment by tjhei** [comment]
>  I think that it would be easy to just mark these three as DEAL_II_DEPRECATED and get rid of them in the near future (maybe for 9.0)

agreed.

**Comment by kronbichler** [comment]
> I am tempted to throw this entire set of functions away and start over with a cleaner interface.

I also agree that this functionality is probably not too widely used and we can get rid of it. So I agree with @drwells and @tjhei that we can deprecate them now and skip for the next major release.
