### ISSUE TITLE
vector_tools_project instantiations

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3825]
After fixing #3820 in #3824 we are now sadly back to the problem that compiling the instantiations of ``project()`` in ``VectorTools`` take a large amount of RAM. I played with this some more and the main culprit seems to be the matrix free project function and an explosion of the number of instantiations of  ``project_matrix_free``:
1. for each serial vector type
2. for each pair of ``dim`` and ``spacedim``
3. for 1,2,3, and 4 components (``project_matrix_free_component``)
4. for degree 1, ..., 8 (``project_matrix_free_degree``)

resulting in quite a few symbols:
```
$ ll ./source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_project.cc.o
-rw------- 1 heister cuuser 146M Jan 19 13:16 ./source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_project.cc.o
$ nm ./source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_project.cc.o | c++filt | wc -l
21650
$ nm ./source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_project.cc.o | c++filt | grep "project_matrix_free<" | wc -l
2688
```

To make this compile with say 2.5GB of RAM with g++, we probably need to split this ``vector_tools_project`` into something like 20 instantiation files (basically one object file for each dim/spacedim pair). That doesn't sound like a great solution to me. Note that making this ``project()`` function inline is also not a great idea, because the user code would then still require us to compile all variations of components/degrees. 

Any other suggestions? I guess we should have a general discussion about matrix free instantiations because we will hit this problem in many places.

Ping @kronbichler

**Comment by drwells** [comment]
One thing that we could do that would not be so painful is to force the use of block vectors when the number of components is greater than one. This would cut down the number of instantiations by quite a lot since we can set. I see a lot of functions of the form
```
void dealii::VectorTools::(anonymous namespace)::project_matrix_free_degree
<4, 1, dealii::LinearAlgebra::Vector<double>, 1>
(dealii::Mapping<1, 1> const&,
 dealii::DoFHandler<1, 1> const&,
 dealii::ConstraintMatrix const&,
 dealii::Quadrature<1> const&,
 dealii::Function<1, dealii::LinearAlgebra::Vector<double>::value_type> const&,
 dealii::LinearAlgebra::Vector<double>&, bool,
 dealii::Quadrature<(1)-(1)> const&,
 bool)
```
where, in reality, I think it is fair to not support multiple components for this type of vector.

**Comment by tjhei** [comment]
> force the use of block vectors

Hmm. If ``Vector`` would allow construction without a memory allocation (basically providing a view), one could create a temporary ``BlockVector`` with one block and only instantiate for ``BlockVector``. Or in other words, only instantiate for a ``VectorView``.

That would only cut the instantiations in half, but I guess every little bit helps.

**Comment by davydden** [comment]
Why do we want to make it work with 2.5Gb only? As of 2017 this is super low amount of ram.

**Comment by jppelteret** [comment]
I suppose many people still have older computers with low specifications (e.g. those cheap netbooks); I’m speculating that there also might be some limitations in terms of how much ram each CI build is allocated? I’m a +1 for decreasing the resources usage during builds if possible.

**Comment by jppelteret** [comment]
Sorry in advance if this is a stupid suggestion (because I'm pretty sure its been considered), but can we perhaps adopt the same approached used in #3820? Is it not possible to explicitly instantiate [`project_matrix_free`](https://github.com/dealii/dealii/blob/master/include/deal.II/numerics/vector_tools.templates.h#L902), but do so such that only one or two `degree`s are instantiated per source file?

**Comment by kronbichler** [comment]
> Why do we want to make it work with 2.5Gb only?

If we assume the worst case that all compilation units use 2.5 GB, you rather need **2.5 GB per core** which is not super low. I cannot compile deal.II with `-j12` on a system with 16 GB of RAM, and sometimes I even run into problems with `-j24` on a system with 32 GB RAM if I have some other programs open.

**Comment by kronbichler** [comment]
I'd need to look into the actual layout used but to me it looks like we should only build the templated stuff (using the polynomial degree and the number of components) on **two vector types only**, namely a `float` and a `double` vector of type `VectorizedArray`. Since a vector copy is so much cheaper than doing the actual work, I strongly suggest that we try this out. I can look into that, but maybe only in a week or so.

**Comment by kronbichler** [comment]
After a closer look I have to modify my previous statement a bit because the template-dependent stuff via `mass_matrix` is actually only using a single vector `LinearAlgebra::distributed::Vector<Number>`. So the savings are likely not as significant. An alternative would be to build a non-templated version of `MassMatrix` and `LaplaceMatrix` that hides both the `degree` and the `components` template from `VectorTools`. Anyone wants to give that a try?

**Comment by davydden** [comment]
> An alternative would be to build a non-templated version of MassMatrix and LaplaceMatrix that hides both the degree and the components template from VectorTools. 

As long as the templated versions of mass and laplace matrix-free operators are available, I am ok with this solution. Also, we don't really need `LaplaceMatrix` here, one could of course do it for consistency.

**Comment by kronbichler** [comment]
@davydden I would of course keep the templated versions available, but we might introduce two wrapper classes that precompile these variants within the library. Since we do not expose templated interfaces to the project functions of `VectorTools` (or do we?), that change would be very neat.

**Comment by davydden** [comment]
> Since we do not expose templated interfaces to the project functions of VectorTools (or do we?)

we actually do for projection from matrix-free quadrature point data. But these functions are smaller in terms of instantiations for different template parameters.

**Comment by tjhei** [comment]
> Why do we want to make it work with 2.5Gb only?

We currently have some files that need 3-4GB to compile with gcc. A typical machine today might have 8GB of RAM but some is used and I guess you want to compile with more than -j 1 without swapping? :-) 
Note that I made up the 2.5GB number (I would prefer 2GB but that is no longer feasible without splitting a ton of files). This is all made more complicated by the fact that tools like ``ninja`` try to use more tasks than cores (10 on my 4+4 core desktop). Also see Martin's comment.

> can we perhaps adopt the same approached used in #3820?

Yes, that is possible, but I think we would need around 20 .cc files to chop ``vector_tools_project`` down.

**Comment by bangerth** [comment]
On 01/19/2017 10:22 PM, Denis Davydov wrote:
> Why do we want to make it work with 2.5Gb only? As of 2017 this is super low
> amount of ram.

I want to compile with -j6 or more on my laptop.

**Comment by jppelteret** [comment]
> Yes, that is possible, but I think we would need around 20 .cc files to chop `vector_tools_project` down.

Sorry, I see that you mentioned exactly this in your initial post.

**Comment by tamiko** [comment]
The sweet spot would be 2GiB... But we're quite far away from it nowadays :-/

**Comment by davydden** [comment]
what if we don't instantiate those functions at all and just keep `.templates.h` with definitions included in `.h` by default? Or just move definitions into `.h`?

**Comment by tjhei** [comment]
> what if we don't instantiate those functions at all and just keep .templates.h with definitions included in .h by default? Or just move definitions into .h?

"Note that making this project() function inline is also not a great idea, because the user code would then still require us to compile all variations of components/degrees."

Any program that uses ``project()`` would need 3+GB and a long time to compile.

**Comment by davydden** [comment]
@tjhei :

> Any program that uses project() would need 3+GB and a long time to compile.

not necessarily. Users would likely use it with specific dim's and vector types. So yes, something would need to be instantiated implicitly, but i don't think instantiation would be as complete as we do now.

**Comment by bangerth** [comment]
Even if you only need a particular dimension and vector type, you still have to instantiate the various polynomial degrees.

We may in some cases win something for the polynomial degrees if we can use `constexpr` `if` statements that will be part of C++17 (see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0292r1.html) but that's a good ways away still.

**Comment by drwells** [comment]
The current version already copies things from an intermediate vector. In particular, we declare

```cpp
typedef LinearAlgebra::distributed::Vector<number> LocalVectorType;
LocalVectorType vec, rhs, inhomogeneities;
matrix_free->initialize_dof_vector(vec);
[...]
```

then later run
```cpp
cg.solve (mass_matrix, vec, rhs, preconditioner);
vec+=inhomogeneities;

constraints.distribute (vec);
IndexSet::ElementIterator it = locally_owned_dofs.begin();
for (; it!=locally_owned_dofs.end(); ++it)
  vec_result(*it) = vec(*it);
vec_result.compress(VectorOperation::insert);
```

so all we need to do is pull this copy operation (which does not depend on the FE degree or number of components) into a separate helper function. I almost have this patch done.
