### ISSUE TITLE
gcc 4.8 ignores Wunused-variable pragma

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3827]
I am getting many warnings like
```
/ssd/libs-candi/boost_1_60_0/include/boost/system/error_code.hpp:221:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
```
from boost even though the include is wrapped by ``DEAL_II_DISABLE_EXTRA_DIAGNOSTICS`` which contains 
```
_Pragma("GCC diagnostic ignored \"-Wunused-variable\"")          
```
This seems to be a bug in gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64079

Any suggestion on working around it?

I just learned about ``-isystem`` instead of ``-I`` (see http://stackoverflow.com/a/15053852). Maybe we should use this for external includes like boost?

**Comment by bangerth** [comment]
I've thought about using `-isystem` before. I think we even discussed this but there were some reasons not to use it. I don't recall which.
