### ISSUE TITLE
Recolour table background in glossary entry

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3836]
In this [glossary entry](http://dealii.org/developer/doxygen/deal.II/DEALGlossary.html#GlossNodes), its really hard to make out the text in the heads rows/columns since both the text and table background are blue (I've checked this in both firefox and safari). Perhaps the background colour should be changed to something that provides the hyperlinked text a greater contrast? The other colours in the headings should also be taken into considerations (right now its white).

**Comment by davydden** [comment]
yikes, does not look too good indee

**Comment by drwells** [comment]
I have a fix for this. I am recompiling the documentation to double check now.
