### ISSUE TITLE
ReductionControl and the Trilinos solvers

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3843]
I am trying to debug `lac/schur_complement_05.debug`, which fails with a floating point exception. The cause is that we initialize the `ReductionControl` object in the following way:
```
ReductionControl::ReductionControl(const unsigned int n,
                                   const double tol,
                                   const double red,
                                   const bool m_log_history,
                                   const bool m_log_result)
  :
  SolverControl (n, tol, m_log_history, m_log_result),
  reduce(red),
  reduced_tol(numbers::signaling_nan<double>())
{}
```
The point of the last line is that we must not read `reduced_tol` unless it is set in the first iteration. This happens as follows:
```
SolverControl::State
ReductionControl::check (const unsigned int step,
                         const double check_value)
{
  // if this is the first time we
  // come here, then store the
  // residual for later comparisons
  if (step==0)
    {
      initial_val = check_value;
      reduced_tol = check_value * reduce;
    }

  // check whether desired reduction
  // has been achieved. also check
  // for equality in case initial
  // residual already was zero
  if (check_value <= reduced_tol)
    {
      ...
```
In other words, in the first iteration we get the first residual (`check_value`) and multiply it by the desired reduction, and then `reduced_tol` contains a usable value.

The problem in this test is that apparently `ReductionControl::check()` is not, in fact, called in each iteration. The test uses the `TrilinosWrappers::CG` as solver, and at least as far as I can see, the first time `check()` is called is when `step` equals 74. This is because our Trilinos solver wrappers seem to pretty explicitly work around the design of `SolverControl`/`ReductionControl`:
```
  template<typename Preconditioner>
  void
  SolverBase::do_solve(const Preconditioner &preconditioner)
  {
    int ierr;

    // Next we can allocate the AztecOO solver...
    solver.SetProblem(*linear_problem);

    // ... and we can specify the solver to be used.
    switch (solver_name)
      {
      case cg:
        solver.SetAztecOption(AZ_solver, AZ_cg);
        break;
      case cgs:
        solver.SetAztecOption(AZ_solver, AZ_cgs);
        break;
      case gmres:
        solver.SetAztecOption(AZ_solver, AZ_gmres);
        solver.SetAztecOption(AZ_kspace, additional_data.gmres_restart_parameter);
        break;
      case bicgstab:
        solver.SetAztecOption(AZ_solver, AZ_bicgstab);
        break;
      case tfqmr:
        solver.SetAztecOption(AZ_solver, AZ_tfqmr);
        break;
      default:
        Assert (false, ExcNotImplemented());
      }

    // Set the preconditioner
    set_preconditioner(solver, preconditioner);

    // ... set some options, ...
    solver.SetAztecOption (AZ_output, additional_data.output_solver_details ?
                           AZ_all : AZ_none);
    solver.SetAztecOption (AZ_conv, AZ_noscaled);

    // ... and then solve!
    ierr = solver.Iterate (solver_control.max_steps(),        // *****************************
                           solver_control.tolerance());                   // *****************************

    // report errors in more detail than just by checking whether the return
    // status is zero or greater. the error strings are taken from the
    // implementation of the AztecOO::Iterate function
    switch (ierr)
      {
      case -1:
        AssertThrow (false, ExcMessage("AztecOO::Iterate error code -1: "
                                       "option not implemented"));
      case -2:
        AssertThrow (false, ExcMessage("AztecOO::Iterate error code -2: "
                                       "numerical breakdown"));
      case -3:
        AssertThrow (false, ExcMessage("AztecOO::Iterate error code -3: "
                                       "loss of precision"));
      case -4:
        AssertThrow (false, ExcMessage("AztecOO::Iterate error code -4: "
                                       "GMRES Hessenberg ill-conditioned"));
      default:
        AssertThrow (ierr >= 0, ExcTrilinosError(ierr));
      }

    // Finally, let the deal.II SolverControl object know what has
    // happened. If the solve succeeded, the status of the solver control will
    // turn into SolverControl::success.
    solver_control.check (solver.NumIters(), solver.TrueResidual());   // *****************************

    if (solver_control.last_check() != SolverControl::success)
      AssertThrow(false, SolverControl::NoConvergence (solver_control.last_step(),
                                                       solver_control.last_value()));
```

Note that the marked lines are the only interaction with the `SolverControl` class. In particular, we query `solver_control.tolerance()` before it is even set to anything useful.

Ideas on how to fix this?

**Comment by bangerth** [comment]
Also of note: The functions we call above to set the tolerance Trilinos's solvers should attain is implemented like this:
```
inline double
SolverControl::tolerance () const
{
  return tol;
}
```
This is at best awkward because it returns `SolverControl::tol` which is indeed set by `ReductionControl` via
```
ReductionControl::ReductionControl(const unsigned int n,
                                   const double tol,
                                   const double red,
                                   const bool m_log_history,
                                   const bool m_log_result)
  :
  SolverControl (n, tol, m_log_history, m_log_result),
  reduce(red),
  reduced_tol(numbers::signaling_nan<double>())
{}
```
In other words, we run the Trilinos solvers until the preset *tolerance* is achieved, not until *either the tolerance or the reduction goal* is achieved as is the intent of `ReductionControl`. Using `ReductionControl` with the Trilinos solvers therefore achieves exactly the same as if we had used a regular `SolverControl` object.

**Comment by jppelteret** [comment]
Huh, this explains a lot. I had huge difficulty in setting up the linear solvers using `LinearOperator` for these tests, and I thought I was doing something wrong. This also means that there's no direct equivalence between the hand-implemented Schur complement and what I done here using `LO`s as they're not necessarily going to converge to the same solution (i.e. the test is not particularly useful in its current state!).

In the worst case, when using `ReductionControl` could we perform one iteration at a time and check the state of `solver_control` after each iteration? Something like
```c++
while ( solver_control.check (solver.NumIters(), solver.TrueResidual()) == iterate)
{
   // Perform one iteration at a time
    ierr = solver.Iterate (1,  solver_control.tolerance());               

    switch (ierr)
      {
      case -1:
        ...
      }
}
```
I know this is not particularly efficient, and I don't know whether `Trilinos` would allow one to perform sequential individual iterations like this. Just throwing the idea out there...

**Comment by jppelteret** [comment]
In fact, we may be able to achieve this within the framework provided by `Trilinos` by defining our own [AztecOO_StatusTest](https://trilinos.org/docs/r12.10/packages/aztecoo/doc/html/classAztecOO__StatusTest.html) for the relative residual, using it [in combination](https://trilinos.org/docs/r12.10/packages/aztecoo/doc/html/classAztecOO__StatusTestCombo.html) with the those [typically](https://trilinos.org/docs/r12.10/packages/aztecoo/doc/html/classAztecOO__StatusTestMaxIters.html) [used](https://trilinos.org/docs/r12.10/packages/aztecoo/doc/html/classAztecOO__StatusTestResNorm.html) by `AztecOO`, and [passing it](https://trilinos.org/docs/r12.10/packages/aztecoo/doc/html/classAztecOO.html#a6b5ad4abc82f904605b74347516fb04f) to the solver. If you think that this is the way to go then I can have a crack at implementing it.

**Comment by bangerth** [comment]
You have already found a different solution, but for completeness, let me reply to this question:

> In the worst case, when using `ReductionControl` could we perform one iteration at a time and check the state of solver_control after each iteration?

This would indeed be inefficient because it assumes that iterative solvers have no "state" other than the current iterate, and consequently that you get the same solution if either (i) you do two iterations, or (ii) you do one iteration, take the solution this produced, and use it as the starting guess for a second iteration.

This assumption is false for Krylov space methods (though it is true for fixed point iterations like Jacobi!). This is most easily seen for GMRES that builds a whole space of vectors within which it then minimizes the norm of the residual. It is clearly more efficient to minimize the residual in a 30-dimensional subspace than to do 30 one-dimensional minimizations.
