### ISSUE TITLE
Compiler error for norm_sqr in the Vector<Number> class

### ISSUE THREAD

**Issue by stvdwtt** [dealii/dealii#3844]
If I use the version of deal.II on the master branch (v8.5_pre), I get a compiler error when trying to use the "norm_sqr()" method of the Vector<Number> class, saying that such a method doesn't exist. Was this method purposely removed or is that a bug? If it was deprecated, would it be possible to add a warning to that effect? In version 8.4.1, the method works fine.

Thanks!

**Comment by bangerth** [comment]
That function is still there. Can you post a small code snippet that shows the error you get?

**Comment by jppelteret** [comment]
@stvdwtt FYI. The function prototype is [here](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/vector.h#L488) and its definition is [here](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/vector.templates.h#L460). So it should work as expected for sensible `Number` types :-)

**Comment by stvdwtt** [comment]
Hi Wolfgang, thanks for the quick response.

Here's the line of code:
if (!numbers::is_finite(solutionSet[fieldIndex]->norm_sqr())){

where solutionSet is a std::vector<dealii::parallel::distributed::Vector<double>*>.

Here's the compiler error:
/home1/01625/stvdwtt/phaseField/applications/allenCahn/../../src/models/coupled/../../../include/../src/matrixfree/solveIncrement.cc(109): error: class "dealii::LinearAlgebra::distributed::Vector<double>" has no member "norm_sqr"
  	  if (!numbers::is_finite(solutionSet[fieldIndex]->norm_sqr())){
  	                                                   ^
          detected during instantiation of "void MatrixFreePDE<dim>::solve() [with dim=2]" at line 24 of "/home1/01625/stvdwtt/phaseField/applications/allenCahn/main.cc"

The line of code works (or at least compiles) for version 8.4.1 and earlier.

**Comment by Rombur** [comment]
It got removed by this commit https://github.com/dealii/dealii/commit/498f0caef5aa3c1054ddfb1e48b6535b72add9d4 I don't remember if it was intentional or not. Since the others distributed vectors don't have it, it is possible that it was on purpose. You can use `l2_norm()*l2_norm()` though.

**Comment by Rombur** [comment]
@kronbichler do you remember if it was supposed to be removed or not. Here is the PR if it helps you remember https://github.com/dealii/dealii/pull/2615

**Comment by kronbichler** [comment]
@Rombur We did indeed remove the functionality on purpose - well, kind of - because we wanted to design minimal interfaces and see if people want to have some additional functionality. Adding this functionality merely adds 3 lines of code because it is closely related to `l2_norm`. I'd rather not add the function since it is so easy to achieve it in user code but I don't have a strong opinion.

**Comment by kronbichler** [comment]
Even if we decide to not add `norm_sqr` to the new interface, we definitely need to add this function to the list of functions that have disappeared in the incompatibilities section in my changelog from 2016/06/15 and maybe even add a transition period where we still have the functionality but marked as deprecated, so this should remain open for now.

**Comment by davydden** [comment]
for consistency with other distributed vectors i would not add it again. But I agree that one should add this to incompatibilities log. Since the change is already done, and the fix is easy, i would not bother with `depricated`.
