### ISSUE TITLE
Glossary of Generalized support points

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#3872]
There seems to be some issue with the doxygen output of glossary of [Generalized support points].(https://dealii.org/developer/doxygen/deal.II/DEALGlossary.html#GlossGeneralizedSupport)

The problem is with interpreting \mathbf.

> "Generalized support points" are, as the name suggests, a generalization of support points. The latter are used to describe that a finite element simply interpolates values at individual points (the "support points"). If we call these points Missing argument for \mathbf (where the hat indicates that these points are defined on the reference cell K^), then one typically defines shape functions φj(x) in such a way that the nodal functionals Ψi[⋅] simply evaluate the function at the support point, i.e., that Missing argument for \mathbf, and the basis is chosen so that Ψi[φj]=δij where δij is the Kronecker delta function. This leads to the common Lagrange elements.

**Comment by jppelteret** [comment]
I think that the [paragraph above](https://github.com/dealii/dealii/blob/master/doc/doxygen/headers/glossary.h#L857) might be missing a `</dd>`

**Comment by jppelteret** [comment]
Patch on the way

**Comment by bangerth** [comment]
Confirmed fixed. Thanks, @sairajat for reporting the issue, and @jppelteret for fixing it!
