### ISSUE TITLE
duplicate symbols for EmptyPayload

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3877]
@jppelteret there is another issue, `EmptyPayload` got duplicate symbols:
```
duplicate symbol __ZN6dealii8internal14LinearOperatorplERKNS1_12EmptyPayloadES4_ in:
CMakeFiles/realfastdft.dir/source/simulator/solver_1.cc.o
CMakeFiles/realfastdft.dir/source/simulator/solver_2.cc.o
```
when `linear_operator_tools.h` is included in two different source files of a user's library.

**Comment by jppelteret** [comment]
Can you please post a MWE?

**Comment by davydden** [comment]
it's hard to have a MWE, because you need a user's library and two `.cc` files which include `#include <deal.II/lac/linear_operator_tools.h>`.

**Comment by davydden** [comment]
you could probably try reproducing it with your own library to check if it indeed behaves like that.

**Comment by davydden** [comment]
me and @jppelteret tried to reproduce the issue on a dummy library, but could not. I will strip down my whole lib trying to get a MWE. The mechanism which triggers the issue appears to be far more complicated than what i though initially.

**Comment by davydden** [comment]
@jppelteret i was linking against the wrong deal.II (not up-to-date). Attached is the smallest MWE which actually fits the description in the OP and fails with
```
$ make
[ 33%] Linking CXX shared library libtemp.dylib
duplicate symbol __ZN6dealii8internal14LinearOperatorplERKNS1_12EmptyPayloadES4_ in:
    CMakeFiles/temp.dir/simulator_01.cc.o
    CMakeFiles/temp.dir/simulator_02.cc.o
duplicate symbol __ZN6dealii8internal14LinearOperatormlERKNS1_12EmptyPayloadES4_ in:
    CMakeFiles/temp.dir/simulator_01.cc.o
    CMakeFiles/temp.dir/simulator_02.cc.o
ld: 2 duplicate symbols for architecture x86_64
```
That must be related to https://github.com/dealii/dealii/pull/1783

@dealii/dealii any ideas where duplicate `EmptyPayload` symbol make come from?

[EmptyPayload.zip](https://github.com/dealii/dealii/files/742022/EmptyPayload.zip)

**Comment by bangerth** [comment]
By the way, the symbol in question is `dealii::internal::LinearOperator::operator+(dealii::internal::LinearOperator::EmptyPayload const&, dealii::internal::LinearOperator::EmptyPayload const&)`

**Comment by bangerth** [comment]
The problem is that `operator+` and `operator*` in `linear_operator.h` are not declared as `inline`, see lines 938 and 948. This should be easy to fix.

**Comment by davydden** [comment]
@bangerth indeed, fixes the issue! Wow. PR incoming.
