### ISSUE TITLE
[C++11] Replace DEAL_II_STATIC_ASSERT by static_assert

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3878]
#3861 introduces a macro `DEAL_II_STATIC_ASSERT`. Once we require C++11, we can get rid of it again and replace it by a straight `static_assert`.

**Comment by drwells** [comment]
We can also get rid of the included `exceptions.h` header in most cases.

**Comment by drwells** [comment]
Since we reverted this patch in #3923 we no longer need this reminder, so I believe this may be closed.
