### ISSUE TITLE
numdiff should be picked up during setting up tests for an already installed deal.II

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3900]
When I try to test already installed dealii by
```
cmake -DDEAL_II_DIR=/path/to/installed/dealii  /path/to/dealii_source/tests
```
`numdiff` is not being picked up even if it is installed and is in path at this point. 

It appears so that in order for `numdiff` to be used in tests, **it has to be present during configure of the dela.II itself**. This is ok when tests are run in the build folder (configure/build deal.ii-> run tests), but is not correct when testing an already installed library (build & install dealii -> setup & run tests).

p.s. discovered in https://github.com/dealii/dealii/issues/3899

**Comment by tamiko** [comment]
Nowhere in the configuration of deal.II we search for numdiff - also no such information is ever recorded in `deal.IIConfig.cmake`. This is done exclusively in the testsuite projects (i.e. the subdirectories under `/test`):

```
$ mkdir build-test-subproject
$ cd build-test-subproject
$ cmake ../tests/bits
-- Using the deal.II-9999 installation found at /usr
...
-- Build files have been written to: /home/tamiko/workspace/dealii/build-test-subproject
$ grep NUMDIFF CMakeCache.txt
NUMDIFF_EXECUTABLE:FILEPATH=/usr/bin/numdiff
```

**Comment by davydden** [comment]
I was indeed mistaken in assuming that it's searched during config. If I have `numdiff` in path and then run `make setup_tests_vector_tools`, it is picked up.

**Comment by davydden** [comment]
@tamiko btw, i think I had that idea from how user libraries and tests work. There, there is not `make setup_tests` and `numdiff` is picked up during `cmake` config stage of the user's project. Therefore I assumed the same is happening during setting up of deal.II's tests.
