### ISSUE TITLE
[8.5.0 Release] Failing tests with Clang 3.9.1

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3908]
This is a fairly up to date userland with
- clang 3.9.1
- arpack 3.1.5 *)
- boost 1.62.0 *)
- hdf5 1.8.18
- lapack 3.6 *) 
- openmpi 2.0.1 *)
- muparser 2.2.5
- netcdf 4.2.1 *)
- opencascade 6.9.1
- p4est (current master)
- petsc 3.7.5.0
- tbb 7.0 (2017.20161128)
- trilinos 12.10.1
- umfpack 5.6.2 *)

(*) newer versions available

https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=4278

In reference to #3893.

**Comment by drwells** [comment]
What is going on with these `epoll` errors?

**Comment by tamiko** [comment]
These are scary. I don't know.

**Comment by tamiko** [comment]
Fixed userland and broke up into individual bug reports.
