### ISSUE TITLE
Tests opencascade/arclength_boundary plane_intersection fail for opencascade 6.9.1 and later

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3915]
The two tests
        7321 - opencascade/arclength_boundary_02.debug (Failed)
        7322 - opencascade/arclength_boundary_02.release (Failed)
        7357 - opencascade/plane_intersection_01.debug (Failed)
        7358 - opencascade/plane_intersection_01.release (Failed)

Fail for me with opencascade 6.9.1. It seems that some points get repeated in the output ??!
```
@@ -7,25 +7,25 @@
 4  1.00000 1.00000 0.00000
 5  0.500000 -0.207107 0.00000
 6  -0.207107 0.500000 0.00000
-7  -0.207107 0.500000 0.00000
+7  1.20711 0.500000 0.00000
 8  0.500000 1.20711 0.00000
-9  0.323223 0.500000 0.00000
+9  0.500000 0.500000 0.00000
 10  0.229402 -0.153281 0.00000
 11  0.770598 -0.153281 0.00000
 12  -0.153281 0.229402 0.00000
 13  -0.153281 0.770598 0.00000
-14  0.229402 -0.153281 0.00000
-15  0.229402 1.15328 0.00000
+14  1.15328 0.229402 0.00000
+15  1.15328 0.770598 0.00000
 16  0.229402 1.15328 0.00000
 17  0.770598 1.15328 0.00000
-18  0.411612 0.146447 0.00000
-19  0.411612 0.853553 0.00000
-20  0.0580583 0.500000 0.00000
-21  0.0580583 0.500000 0.00000
-22  0.145238 0.189433 0.00000
-23  0.385723 0.141597 0.00000
-24  0.145238 0.810567 0.00000
-25  0.385723 0.858403 0.00000
+18  0.500000 0.146447 0.00000
+19  0.500000 0.853553 0.00000
+20  0.146447 0.500000 0.00000
+21  0.853553 0.500000 0.00000
+22  0.189433 0.189433 0.00000
+23  0.810567 0.189433 0.00000
+24  0.189433 0.810567 0.00000
+25  0.810567 0.810567 0.00000
 $ENDNOD
 $ELM
 16
```

**Comment by davydden** [comment]
on macOS with `oce@0.18` I have the following failing (two extra):
```
7367 - opencascade/arclength_boundary_02.debug (Failed)
	7368 - opencascade/arclength_boundary_02.release (Failed)
	7403 - opencascade/plane_intersection_01.debug (Failed)
	7404 - opencascade/plane_intersection_01.release (Failed)
	7411 - opencascade/step_create.debug (Failed)
	7412 - opencascade/step_create.release (Failed)
	7417 - opencascade/step_write.debug (Failed)
	7418 - opencascade/step_write.release (Failed)
```

**Comment by tamiko** [comment]
@davydden The two extra `step_create` and `step_write` are due to an unstable (platform dependent) ordering. What about you check and simply add your output variants?

**Comment by davydden** [comment]
@tamiko will do, will be adding a few outputs anyway....

**Comment by davydden** [comment]
@tamiko why closing?

**Comment by tamiko** [comment]
@davydden I thought we had merged output variants for these tests a while ago, but I guess I mixed up the test names

**Comment by davydden** [comment]
> I thought we had merged output variants for these tests a while ago, but I guess I mixed up the test names

indeed, those tests are failing. I am not sure if they are failing due to the change in OpenCascade output, or something is wrong in deal.II's interface.

**Comment by davydden** [comment]
@tamiko @luca-heltai my understanding is that we postpone this issue until 9.0, i changed milestone to reflect this. Feel free to undo if this is not the case.

**Comment by davydden** [comment]
i don't see any opencascade tests failing anymore, so closing this.
