### ISSUE TITLE
Bug in Patterns::Selection::match

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#3927]
```
constitutive_law_Lp = "MTS";
	tmp.str(""); tmp << constitutive_law_Lp;
	prm.declare_entry("constitutive_law_Lp", tmp.str(),
	                  Patterns::Selection(" MTS | Perzyna  | Old | Clifton_Thermal_Softening"),
	                  "constitutive_law_Lp");

```

The above mentioned piece of code is throwing an exception.

> An error occurred in line <1632> of file </Libraries/deal/dealii8.3/dealii-8.3.0/source/base/parameter_handler.cc> in function
    void dealii::ParameterHandler::declare_entry(const string&, const string&, const dealii::Patterns::PatternBase&, const string&)
The violated condition was: 
    pattern.match (default_value)
The name and call sequence of the exception was:
    ExcValueDoesNotMatchPattern (default_value, pattern.description())
Additional Information: 
The string <MTS> does not match the given pattern <[Selection  MTS|Perzyna|Old|Clifton_Thermal_Softening ]>

However, the following code works.

```
constitutive_law_Lp = "MTS";
	tmp.str(""); tmp << constitutive_law_Lp;
	prm.declare_entry("constitutive_law_Lp", tmp.str(),
	                  Patterns::Selection("MTS | Perzyna  | Old | Clifton_Thermal_Softening"),
	                  "constitutive_law_Lp");

```
Note: There is no space at the beginning of the Patterns::Selection  constructor in the working code.
**" MTS .." ** earlier vs ** "MTS .. "** in the working code.

The bug is in line 476 of this [file](https://dealii.org/developer/doxygen/deal.II/parameter__handler_8cc_source.html#l00360).

It assumes that there is no space at the start of the sequence. All the spaces between the subsequent patterns is erased in the sequence function but the space at the beginning is not taken care of as there is no "|".

**Comment by sairajat** [comment]
I think this issue could also be in other match functions derived from the base class.

**Comment by drwells** [comment]
Thanks for reporting this. This is definitely a bug because everywhere else in `ParameterHandler` we trim white space at the start of any sequence (so here we should skip all space around `|` characters).

Would you be interested in writing up a patch and a new unit test for this?

**Comment by sairajat** [comment]
@drwells  Thanks for your prompt reply. I will definitely be interested in contributing. I will write a patch. I might need some help / reference for writing a unit test as I have never written a unit test before. 
Thanks again.

**Comment by davydden** [comment]
> I might need some help / reference for writing a unit test as I have never written a unit test before.

that's not too difficult. Try `grep`-ing `ParameterHandler` in `tests` folder to see other tests which use it. A unit test is simply a combination of `.cc` and `.output` file, the rest is done automatically by CMake scripts.

**Comment by sairajat** [comment]
This is what it looks like finally. Is this ok ? 

This may sound very stupid but how should I compile this code to test it ? I mean I use deal.ii as a library.
I use cmake to generate the executable but that uses an already compiled / installed version of the library. 

I have added parts that remove spaces at the beginning and the end of the string.

```
  bool Selection::match (const std::string &test_string) const
  {
    std::string tmp(sequence);
    // remove whitespace at beginning
    while ((tmp.length() != 0) && (std::isspace (tmp[0])))
      tmp.erase (0,1);

    // check the different possibilities
    while (tmp.find('|') != std::string::npos)
      {
        if (test_string == std::string(tmp, 0, tmp.find('|')))
          return true;

        tmp.erase (0, tmp.find('|')+1);
      };

    //remove whitespace at the end
    while ((tmp.length() != 0) && (std::isspace (tmp[*(tmp.end()-1)])))
        tmp.erase (tmp.end()-1);

    // check last choice, not finished by |
    if (test_string == tmp)
      return true;

    // not found
    return false;
  }
```

**Comment by davydden** [comment]
@sairajat would you mind submitting a PR? It's easier to see in the context of what lines are being altered.

**Comment by bangerth** [comment]
On 02/06/2017 09:52 AM, RAJAT ARORA wrote:
> This may sound very stupid but how should I compile this code to test it
> ? I mean I use deal.ii as a library.
> I use cmake to generate the executable but that uses an already compiled
> / installed version of the library.

Yes, you need to patch the deal.II source code, recompile the library, 
and then test the result. Since you only change one .cc file, 
recompiling the library should not actually take very long if you kept 
the build directory around.

**Comment by sairajat** [comment]
@davydden  done.
