### ISSUE TITLE
false failing tests due to Ctest picking up system GNU MP

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3929]
Sometimes I experience strange behaviour while running tests. First some tests fail, then they pass fine. Does not seem to be related to a time-out or running with `-j 4` and alike.

Here is one such example:
```
$ ctest -R "serialization/"
...
The following tests FAILED:
	7843 - serialization/pointer_02.release (Failed)
```
however
```
$ ctest -R "serialization/pointer_02.release"
Test project /home/davydden/libs/dealii-tests.mtp
    Start 7843: serialization/pointer_02.release
1/1 Test #7843: serialization/pointer_02.release ...   Passed    0.11 sec
```
Attached is the output after the first run (failure). As one can see, there are no errors, nothing in diffs, etc.
[pointer_02.release.zip](https://github.com/dealii/dealii/files/753811/pointer_02.release.zip)

p.s. I am running Cmake `3.7.2` on `Ubuntu16LTS`. `dealii` is compiled with `gcc@6.3.0`

**Comment by davydden** [comment]
the issue also manifest itself in the following way:
```
$ ctest -R "trilinos/precondition_muelu_smoother.debug"
Test project /home/davydden/libs/dealii-tests.mtp
    Start 8282: trilinos/precondition_muelu_smoother.debug
1/1 Test #8282: trilinos/precondition_muelu_smoother.debug ...***Failed    1.33 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.30 sec

The following tests FAILED:
	8282 - trilinos/precondition_muelu_smoother.debug (Failed)
Errors while running CTest
$ ctest -R "trilinos/precondition_muelu_smoother.debug"
Test project /home/davydden/libs/dealii-tests.mtp
    Start 8282: trilinos/precondition_muelu_smoother.debug
1/1 Test #8282: trilinos/precondition_muelu_smoother.debug ...   Passed    0.77 sec

100% tests passed, 0 tests failed out of 1
```

**Comment by davydden** [comment]
it may be related to the following (got from `-V`):
```
$ ctest -V -R "base/functions_spherical_01.debug"
...
1087: Test timeout computed to be: 600
1087: GNU MP: Cannot allocate memory (size=2305843009206983184)
1087: Aborted (core dumped)
...
```
which disappears if I run the `ctest` command a few times. No idea what is going on...

**Comment by davydden** [comment]
`Ubuntu16` has `libgmp-dev 2:6.1.0+dfsg-2` installed. But as far as I know nothing in the deal.II tool-chain uses it.

**Comment by davydden** [comment]
I uninstalled `gnu-mp` from `ubuntu` and on the next run of `ctest` some updates are done:
```
UpdateCTestConfiguration  from :/home/davydden/libs/dealii-tests.mtp/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/davydden/libs/dealii-tests.mtp/DartConfiguration.tcl
Test project /home/davydden/libs/dealii-tests.mtp
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
```
So it looks like `ctest` was using `GNU MP` somehow...

**Comment by davydden** [comment]
looks like uninstalling system's `libgmp-dev` was not enough to solve the problem, i need to double check...

**Comment by bangerth** [comment]
On 02/06/2017 12:37 AM, Denis Davydov wrote:
> |1087: Test timeout computed to be:
 > 600 1087: GNU MP: Cannot allocate memory (size=2305843009206983184)
 > 1087: Aborted (core dumped)|

I don't think this is cmake reporting about itself, but an error message 
the tested program generates.

The size GNU MP wants to allocate is of course ludicrous. It would be 
really useful to get a backtrace for this. Run the same program in a 
debugger multiple times until it finally triggers this (apparently 
non-reproducible) problem. In similar situations I've had to run the 
program a dozen times or more until it finally triggered the issue.

**Comment by davydden** [comment]
@bangerth so far I can't reproduce the issue outside of `ctest` environment. The only thing I notice is that the resulting test executables require deal.II to be in path:
```
$ ldd aligned_vector_move.debug | grep "deal"
	libdeal_II.g.so.8.5.0-pre => not found
```
but, to be fare, the installed libs soname do not have full path
```
$ objdump -p ~/spack/opt/spack/linux-ubuntu16-x86_64/gcc-6.3.0/dealii-develop-wrha3kpxcvgg2wd54rjm5dxl6ksdihf3/lib/libdeal_II.g.so.8.5.0-pre | grep SONAME
  SONAME               libdeal_II.g.so.8.5.0-pre
```

**Comment by bangerth** [comment]
If the error happens in the test, it must be possible to reproduce it outside ctest. Try something of the sort
```
  for i in `seq 1 100` ; do ./aligned_vector_move.debug ; done
```

**Comment by davydden** [comment]
@bangerth that still runs fine... will look at it again later this week.

**Comment by davydden** [comment]
could also be that `gmp` or `mfpr` used in `gcc` are broken or some confusion with system's versions. 

I still don't understand why `ctest` reacted at all (see [above](https://github.com/dealii/dealii/issues/3929#issuecomment-277611853) ) at me uninstalling `libgmp-dev`???

**Comment by bangerth** [comment]
Wait, so you are saying that there are two different GNU MPs installed? And that the path built into the executable/deal.II lib does not clearly identify which one?

**Comment by davydden** [comment]
> so you are saying that there are two different GNU MPs installed?

yes, one provided by default in `ubuntu16` (can check version on friday) and another one installed as a part of `gcc@6.3.0` build  -- `gmp@6.1.2`. 

>  the path built into the executable/deal.II lib does not clearly identify which one?

I have not run `$ldd` on test executables, but `dealii` itself does not appear to be linked against `gmp` anyhow, see [above](https://github.com/dealii/dealii/issues/3929#issuecomment-277606391). 

Do you have `gmp` linked in when building with `gcc`?

**Comment by bangerth** [comment]
No, it doesn't seem to link against gmp on my system. But neither does the `ctest` executable...

**Comment by tamiko** [comment]
@davydden 
I bet the only executable involved in a test that actually uses gmp is numdiff.
And this would also explain why you cannot reproduce it (you ran the test executable and not numdiff.)

Further, I guess this is some sort of silent ABI breakage. Or some uninitialized variable (which would explain the randomness).

**Comment by davydden** [comment]
@tamiko that's a good hint! I will check `numdiff` and see if it actually links against `gmp`. Hopefully this would sort things out.

**Comment by davydden** [comment]
looking at `ubuntu` [change-log of numdiff](https://launchpad.net/ubuntu/+source/numdiff/+changelog) i saw the following:

> compile with -O0 as per upstream known issue with optimization and GMP;
    this causes a lintian hardening-no-fortify-functions but is required as
    long as this issue is not solved upstream

will try using `numdiff` from Ubuntu as well as turning optimisation off in  self-compiled `numdiff`.

**Comment by tamiko** [comment]
*ouch* So, an uninitialized variable I guess - I love the `-O0` workaround.

**Comment by davydden** [comment]
problem is `numdiff` is not being developed since `2013` 😢 . Looking at it's release cycle, i have an impression that the project is abandoned.

**Comment by tamiko** [comment]
> problem is `numdiff` is not being developed since `2013` 😢 . Looking
> at it's release cycle, i have an impression that the project is
> abandoned.

If it gets problematic for us, we can fork and take over maintenance.

I'm pretty sure we can convince the debian sience guys to switch to our
upstream repo if necessary.

**Comment by davydden** [comment]
@tamiko i got in contact with `numdiff` developer, the new release is coming very soon. This issue with GMP should be fixed there.

**Comment by tamiko** [comment]
> i got in contact with `numdiff` developer, the new release is coming very soon. This issue with GMP should be fixed there.

Very nice.
