### ISSUE TITLE
deprecating supports_distributed_data causes tons of warning

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#3933]
Instantiation  of related vector classes now trigger warning like
```
In file included from /Users/qiaol/devel/NSolver/source/solver/solve.cpp:8:
In file included from /Users/qiaol/devel/NSolver/header/NSolver/solver/NSolver.h:98:
In file included from /Users/qiaol/devel/NSolver/header/NSolver/types.h:12:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:23:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/block_vector.h:23:
/Users/qiaol/Library/deal.II/include/deal.II/lac/block_vector_base.h:576:79: warning: 'supports_distributed_data' is deprecated [-Wdeprecated-declarations]
  static const bool supports_distributed_data DEAL_II_DEPRECATED = BlockType::supports_distributed_data;
                                                                              ^
/Users/qiaol/Library/deal.II/include/deal.II/lac/petsc_parallel_block_vector.h:62:32: note: in instantiation of template class 'dealii::BlockVectorBase<dealii::PETScWrappers::MPI::Vector>' requested here
    class BlockVector : public BlockVectorBase<Vector>
                               ^
/Users/qiaol/Library/deal.II/include/deal.II/lac/petsc_parallel_vector.h:179:25: note: 'supports_distributed_data' has been explicitly marked deprecated here
      static const bool supports_distributed_data DEAL_II_DEPRECATED = true;
```

**Comment by drwells** [comment]
I suppose that makes sense since we have the deprecation on the declaration and definition. I think that we can get around this by moving the definition, in each case, to the associated `templates.h` file.

**Comment by drwells** [comment]
Nevermind the current issue: just including the `vector.templates.h` file raises about a dozen deprecation warnings due to the dependence on `petsc_vector.h`. We should probably fix that to be less annoying.

**Comment by koecher** [comment]
What I can see is that only the inclusion of
`#include <deal.II/lac/petsc_vector.h>` and/or
`#include <deal.II/lac/petsc_block_vector.h>`
raises the warnings. All other vector classes behave quiet (warning comes up in user code, only if the deprecated field is used). I'm not that familiar with petsc vectors, but there might be a different implementation.

**Comment by koecher** [comment]
Well, I got other deprecation warnings than you @QiaoLei-88, but your problem should be resolved by using
`static const bool supports_distributed_data DEAL_II_DEPRECATED = !(is_serial_vector< BlockType >::value);`
in `include/deal.II/lac/block_vector_base.h` (in line 576)
May you please implement this by hand in your installation directory and report if the deprecation warnings are gone?

**Comment by QiaoLei-88** [comment]
@koecher The suggested fix works.
 Since @drwells is already working on this, I would not submit the patch.
