### ISSUE TITLE
The deal.II library - windows and Linux versions

### ISSUE THREAD

**Issue by bjdarrer** [dealii/dealii#3954]
I am using deal.II library with the "MIT Forward Solver". https://github.com/rosskynch/MIT_Forward
I have tried the windows version of deal.II but I am encountering bugs in the compiling stage.
http://stackoverflow.com/questions/41961934/build-message-unknown-compiler-version-for-dealii-4-8-1-library-on-visual-stu
I am now attempting to install Linux (Ubuntu) and to test deal.II on that platform. Is Linux better suited to deal.II than windows or are their compilation issues with that too?

**Comment by tjhei** [comment]
Please take a look at "Supported Platforms" in the readme: https://www.dealii.org/8.4.1/readme.html

Windows support is very experimental.

**Comment by davydden** [comment]
@bjdarrer if you don't mind, I am closing the issue as the link provided above should answer your question.
