### ISSUE TITLE
Test failure: linear_operator_10

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3968]
This fails when the library is compiled with 64 bit indices with the following message:

```
5065:
5065: terminate called after throwing an instance of 'std::runtime_error'
5065:   what():  /home/drwells/Documents/Code/CPP/trilinos/packages/xpetra/src/Map/Xpetra_EpetraMap.hpp:678:
5065:
5065: Throw number = 1
5065:
5065: Throw test that evaluated to true: !map->GlobalIndicesIsType<GlobalOrdinal>()
5065:
5065: Xpetra::EpetraMapT: GlobalOrdinal mismatch.
```

I believe that the issue is in the MueLu wrappers: we don't seem to create matrices with 64 bit indices in `PreconditionAMGMueLu::initialize`. This should not be hard to fix but I don't know Xpetra well enough to do it myself.

Ping @Rombur

**Comment by drwells** [comment]
linear_operator_10a fails for the same reason with 64 bit indices.

**Comment by davydden** [comment]
just tested 64bit indices build of deal.II with `gcc@6.3.0` in Spack and apart from opencascade tests also see those two failing:
```
99% tests passed, 8 tests failed out of 8146

Total Test time (real) = 16788.93 sec

The following tests FAILED:
	5002 - lac/linear_operator_10.debug (Failed)
	5003 - lac/linear_operator_10.release (Failed)
	5004 - lac/linear_operator_10a.debug (Failed)
	5005 - lac/linear_operator_10a.release (Failed)
	7152 - opencascade/arclength_boundary_02.debug (Failed)
	7153 - opencascade/arclength_boundary_02.release (Failed)
	7188 - opencascade/plane_intersection_01.debug (Failed)
	7189 - opencascade/plane_intersection_01.release (Failed)
```
with the same error. The rest is good!

**Comment by davydden** [comment]
this happens in `TrilinosWrappers::PreconditionAMGMueLu::initialize`, which is clearly not related to linear operators, per se.

**Comment by Rombur** [comment]
Our wrappers don't support 64bit indices for MueLu. The current interface was supposed to be temporary and it needs to be replaces once we add Tpetra support.

**Comment by bangerth** [comment]
Could we put an assert in the first place we encounter that just checks whether or not we have 64-bit indices? And if so, output an error message that says that 64-bit is not supported?

**Comment by tamiko** [comment]
On Mon, Feb 13, 2017, at 21:12 CST, Wolfgang Bangerth <notifications@github.com> wrote:

> Could we put an assert in the first place we encounter that just
> checks whether or not we have 64-bit indices? And if so, output an
> error message that says that 64-bit is not supported?

What about we simply disable the test for 64bit indices for now?

**Comment by bangerth** [comment]
> What about we simply disable the test for 64bit indices for now?

That works, but doesn't help users who happen to run into this.

**Comment by tamiko** [comment]
@bangerth 
Ah, I misunderstood. Well, let's do both
 - disable the test for 64bit indices for now
 - add an assert into our wrapper around the preconditioner that clearly states that it is not possible to use it with 64bit indices enabled.

**Comment by davydden** [comment]
> Ah, I misunderstood. Well, let's do both

:+1: for both!
