### ISSUE TITLE
DerivativeApproximation::approximate_derivative_tensor requires template arguments

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3979]
With relation to [this forum post](https://groups.google.com/forum/#!topic/dealii/2KEDTb1jDjo), the following MWE does not compile without additional template arguments being sent to `DerivativeApproximation::approximate_derivative_tensor`
```c++
#include <deal.II/base/tensor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/lac/vector.h>
#include <deal.II/numerics/derivative_approximation.h>

using namespace dealii;

int main ()
{
  Triangulation<2,2> triangulation;
  DoFHandler<2,2> dof_handler;
  Vector<double> solution;

  Tensor<1,2> cell_grad;
  Tensor<2,2> cell_hessian;

  DoFHandler<2>::active_cell_iterator
  cell = dof_handler.begin_active(),
  endc = dof_handler.end();
  for (; cell!=endc; ++cell)
  {
    // Doesn't work
    DerivativeApproximation::approximate_derivative_tensor(dof_handler, solution, cell, cell_grad);
    DerivativeApproximation::approximate_derivative_tensor(dof_handler, solution, cell, cell_hessian);
    // Works
    // DerivativeApproximation::approximate_derivative_tensor<DoFHandler<2>,2,2>(dof_handler, solution, cell, cell_grad);
    // DerivativeApproximation::approximate_derivative_tensor<DoFHandler<2>,2,2>(dof_handler, solution, cell, cell_hessian);
  }

  return 0;
}
```

It is necessary to fully qualify the DoFHandler type, dim and spacedim because
```sh
<path to my test code>/derivative_approximation.cc:26:5: error: no matching function for call to 'approximate_derivative_tensor'
    DerivativeApproximation::approximate_derivative_tensor(dof_handler, solution, cell, cell_grad);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<path>/include/deal.II/numerics/derivative_approximation.h:260:3: note: candidate template ignored: couldn't infer template argument 'spacedim'
  approximate_derivative_tensor
  ^
<path>/include/deal.II/numerics/derivative_approximation.h:243:3: note: candidate function template not viable: requires at least 5 arguments, but 4 were provided
  approximate_derivative_tensor
  ^
```

This doesn't seem very user friendly. One possible fix is to change the template arguments from
```
template <typename DoFHandlerType, int dim, int spacedim, class InputVector, int order>
void approximate_derivative_tensor
```
to
```
template <template<int,int> class DoFHandlerType, int dim, int spacedim, class InputVector, int order>
void approximate_derivative_tensor
```
and the function argument from `const DoFHandlerType &dof` 
to `const DoFHandlerType<dim,spacedim> &dof` (I see that this is already done for `approximate_gradient`).

**Comment by bangerth** [comment]
For the record, this is the signature in question: https://dealii.org/8.4.0/doxygen/deal.II/namespaceDerivativeApproximation.html#a15b14bc6f6eb3eb3e71d8a174221f57c

**Comment by bangerth** [comment]
The right solution is to just remove the `spacedim` template argument. Nothing in the function signature depends on it, so the compiler cannot infer it. I think it was just accidentally copied from the template argument list in the function just above where we have a `Mapping<dim,spacedim>` argument that allows the compiler to infer `spacedim`.

While we're doing this, we may as well also remove the `dim` argument and use `DoFHandlerType::dimension` in the place where it is used for the `derivative` argument.

**Comment by bangerth** [comment]
In other words, I suggest the following replacement signature:
```
template<typename DoFHandlerType , class InputVector , int order>
void DerivativeApproximation::approximate_derivative_tensor	
(const DoFHandlerType & 	dof,
 const InputVector & 	solution,
 const typename DoFHandlerType::active_cell_iterator & 	cell,
 Tensor< order, DoFHandlerType::dimension> & 	derivative,
 const unsigned int 	component = 0 
)	
```

**Comment by bangerth** [comment]
Just to further spam everyone: The downside is that this is no longer compatible with the way one calls the current signature. I wonder whether it's worthwhile keeping the current signature as deprecated.

**Comment by tjhei** [comment]
> Just to further spam everyone: The downside is that this is no longer compatible with the way one calls the current signature. I wonder whether it's worthwhile keeping the current signature as deprecated.

I am okay with just changing it, because the current version seems to be a copy&paste error.

**Comment by jppelteret** [comment]
I'll submit a patch incorporating @bangerth's suggestion tomorrow.
