### ISSUE TITLE
VS2013 not compiling

### ISSUE THREAD

**Issue by BRabbit27** [dealii/dealii#3996]
I tried to compile the latest version of deal ii under VS2013 and all I get is this error 

> Error C2899 - typename cannot be used outside a template declaration 

this occurs for the obj_fe_release project in line 443 of mapping_q_generic.cc

any advise?

**Comment by drwells** [comment]
I believe that this is a mistake in the source file: if I understand things correctly we do not need that `typename` since the type is fully qualified.

Do things work if you get rid of the `typename` keyword in that line? If so, would you mind putting together a PR with the fix?

**Comment by drwells** [comment]
It may be necessary to do the same fix on lines 497 and 575.

Our MSVC support is, at best, spotty. If you just want to get things working then I believe the usual advice is to use either a virtual machine or, if you are on Windows 10, the Linux subsystem.

**Comment by tjhei** [comment]
> Our MSVC support is, at best, spotty. If you just want to get things working then I believe the usual advice is to use either a virtual machine or, if you are on Windows 10, the Linux subsystem.

Agreed. If you really need to use MSVC, I would also suggest updating to MSVC2015 or MSVC2017 (they both should compile).

**Comment by BRabbit27** [comment]
I gave it a try using VS2015 and got some other errors.
- cannot open file ..\lib\deal_II_g.lib
- An internal error has occurred in the compiler
- Invalid or corrupt file

I think I will try with linux until windows support gets better, thanks !

**Comment by bangerth** [comment]
All of these errors may be related: If a compiler is killed because of an internal error, it often leaves behind an incomplete object file or library. The next time the compiler or linker try to read it, you will then get a follow-up error such as "invalid or corrupt file" or "cannot open file".

**Comment by loylick** [comment]
..\lib\dealII.g.lib is about 2GB it is too big for the linker I guess. So, the first option is to link in release. The second option try to build using amd64 toolschain.

**Comment by tjhei** [comment]
> So the challenge is to make the cmake generate a project for amd64 toolschain.

You can set ``set PreferredToolArchitecture=x64`` in the terminal before running cmake, see http://stackoverflow.com/a/23793055
another option is -T "host=x64" with cmake 3.8 (https://gitlab.kitware.com/cmake/cmake/commit/d079e71c290c3c55a2db5180953daf014a964c25). I have some problems with our testing framework with this, but using any of these two options fixes the terrible link times I had before.

**Comment by tjhei** [comment]
This seems to be fixed now.
