### ISSUE TITLE
Uses of compress() in matrix classes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#403]
I think we agreed a good long while ago that `compress()` without argument is bad and that's why the version with the `VectorOperation` argument was introduced. In fact, `compress()` without argument is deprecated in all classes.

I've tried to remove this function which is not overly difficult in the vector classes, but this function is used in quite a number of places in `trilinos_sparse_matrix.cc` and `petsc_matrix_base.cc`. Someone with a better understanding of these issues should take a look at these places and see what we should be doing there instead...

**Comment by bangerth** [comment]
For reference, these are the functions that should go as they have been deprecated for quite a while already:
```
include/deal.II/lac/petsc_matrix_base.h:    void compress () DEAL_II_DEPRECATED;
include/deal.II/lac/block_matrix_base.h:  void compress () DEAL_II_DEPRECATED;
include/deal.II/lac/trilinos_sparse_matrix.h:    void compress () DEAL_II_DEPRECATED;
```

**Comment by tjhei** [comment]
At least the petsc part is something I will look at.
