### ISSUE TITLE
Properly document the purpose of Assert, AssertThrow, AssertNothrow

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4038]
Reading over the description of the three macros I realize that we didn't do a stellar job in explaining the purpose of our three variants of asserts. We should improve the documentation. Further, we should check:
 - whether an `AssertThrow` should really be an `AssertThrow`, or whether `Assert` is more appropriate.
 - whether we correctly guard all asserts in destructors with `AssertNothrow` (that cannot throw).

In short:
 - `Assert` is our main assert macro that issues an error and aborts the program (normal behavior). This is the most useful macro for debugging, because a simple backtrack of the abort leads to the correct location in source code.
 - `AssertThrow` - sometimes input depends on runtime supplied user data. in this case using the C++ exception mechanism is more appropriate. (A program can catch an exception at runtime and correct for it). This macro must not be used for internal consistency checks, because it makes debugging considerably harder.
 - `AssertNothrow` - this macro is the same as `Assert` except that it guarantees to never throw an exception. This is needed for asserts in destructors (throwing an exception in a destructor is undefined behavior).

**Comment by bangerth** [comment]
There is, however, this page: https://www.dealii.org/developer/doxygen/deal.II/group__Exceptions.html

I'm working on rewording a few things.
