### ISSUE TITLE
MeshWorker yields different matrices from serial code

### ISSUE THREAD

**Issue by fmilicchio** [dealii/dealii#4056]
Dear all,

I was starting using MeshWorker but I found that a serial assembly and one with MeshWorker yield different matrices.

This is [the code I am using](https://bitbucket.org/snippets/fmilicchio/aebEd), it is a very simple remake of the linear elastic code from the tutorial, and this report [started from this discussion](https://groups.google.com/forum/#!topic/dealii/RdcA0WSWYpo).

I am attaching solutions and LHS/RHS for a single cell, not using a subdivided hyperrectangle here:

- [singlecell-matrix-parallel.txt](https://github.com/dealii/dealii/files/833474/singlecell-matrix-parallel.txt)
- [singlecell-matrix-serial.txt](https://github.com/dealii/dealii/files/833477/singlecell-matrix-serial.txt)
- [singlecell-vector-parallel.txt](https://github.com/dealii/dealii/files/833475/singlecell-vector-parallel.txt)
- [singlecell-vector-serial.txt](https://github.com/dealii/dealii/files/833476/singlecell-vector-serial.txt)

And these are the the results for a subdivided hyperractangle:

- [matrix-parallel.txt](https://github.com/dealii/dealii/files/833513/matrix-parallel.txt)
- [matrix-serial.txt](https://github.com/dealii/dealii/files/833515/matrix-serial.txt)
- [vector-parallel.txt](https://github.com/dealii/dealii/files/833514/vector-parallel.txt)
- [vector-serial.txt](https://github.com/dealii/dealii/files/833516/vector-serial.txt)

If you want to see the matrices, I've used Mathematica to analyze them:

- [TestDealii-manycells.pdf](https://github.com/dealii/dealii/files/833523/TestDealii-manycells.pdf)
- [TestDealii-singlecell.pdf](https://github.com/dealii/dealii/files/833524/TestDealii-singlecell.pdf)

**Comment by jppelteret** [comment]
I'm busy skimming though this to see if I can spot any obvious mistakes (I have no familiarity with meshworker). 

My first preliminary point: if you compare [this line](https://bitbucket.org/snippets/fmilicchio/aebEd#main.cpp-136) of your assembly with that of [step-8](https://www.dealii.org/developer/doxygen/deal.II/step_8.html#ElasticProblemassemble_system), you can see that they differ. The check for this contribution to the material stiffness should be `component_i == component_j`.

**Comment by jppelteret** [comment]
Actually, the whole term looks wrong to me:
```
(i == j) ?
(fe_v.shape_grad(component_i, q_point) *
fe_v.shape_grad(component_j, q_point) *
mu_values[q_point])
```
-->
```
(component_i == component_j) ?
(fe_v.shape_grad(i, q_point) *
fe_v.shape_grad(j, q_point) *
mu_values[q_point])
```

**Comment by fmilicchio** [comment]
Aw man, I feel ashamed of that. I sincerely read the very same weak form, that's why I posted on the forum first.

Close the issue, it was my fault.

Thanks!

**Comment by jppelteret** [comment]
Just to confirm, that was the source of the entire issue?

**Comment by jppelteret** [comment]
Well, I'll assume that what I indicated what the only source of error here.

> I feel ashamed of that

No problem, it happens to the best of us! I'm glad that you've now got it sorted out :-)

**Comment by fmilicchio** [comment]
@jppelteret Yes, I confirm it was a copy/paste error.
