### ISSUE TITLE
Add top level exception handling to tutorials 

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4070]
This was caught by Coverity: see #4012 for details. Briefly, we don't always catch exceptions in the `main` functions of tutorials.

I am working on this now: hopefully no one else is doing the same thing in another patch.

**Comment by bangerth** [comment]
We don't do it in the first few tutorials because it would be yet another thing we need to explain. It is first explained in step-6, and I think I would like to keep steps 1-5 free of exception handling. We should, however, consistently use it for step-6 and all following programs.

**Comment by drwells** [comment]
Good idea. I updated my patch to do this.
