### ISSUE TITLE
How can I use CG solver without print all the message

### ISSUE THREAD

**Issue by seekpossible** [dealii/dealii#4085]
I use CG to solve my problem but the output message make me annoy and slow the speed. how to fix that problem ?

**Comment by kronbichler** [comment]
Which messages do you mean? The ones printed to `deallog`? You can disable the messages by either setting `deallog.depth_console(x)` where `x` is an integer small enough (typically between 0 and 2) or you can disable the output in `SolverControl`. Consider setting the fourth argument to the constructor of SolverControl [1] to `false`. Does this help?

[1] https://www.dealii.org/8.4.1/doxygen/deal.II/classSolverControl.html

**Comment by drwells** [comment]
@seekpossible While @kronbichler's answer should resolve your problem, if you have more questions about the library then I recommend posting to our mailing list instead at https://groups.google.com/forum/#!forum/dealii: the mailing list has more people than our issue tracker and is set up to answer questions like this one :)

**Comment by drwells** [comment]
Since the solution to this issue is given above (i.e., the `LogStream::depth_console` method) I believe it is safe to close this.
