### ISSUE TITLE
[8.5 task] Mac OS X Packages

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#4109]
- [ ] Create package for Mac with latest brew installation - full dependency tree
- [x] <s>Create package for Mac with latest spack installation - full dependency tree</s>
- [ ] Create package for Mac - serial
- [x] Make python wrappers work on Mac (?? These never worked for me...)
- [ ] Sign packages (Timo?)

**Comment by luca-heltai** [comment]
I have Davyden spack installation. I'll try to make an app out of it.

**Comment by tjhei** [comment]
Luca, I can package and sign mac packages using brew but I probably need to update my machine to the latest OSX+latest brew, etc..

What is the reason for also generating packages from spack?

**Comment by luca-heltai** [comment]
I don't want to upset people... there seem to be different religions on what is "the best" way to maintain libraries and dependencies. Brew and spack use fundamentally different philosophies, and I don't have a direct preference over one or the other...

Anyway, if you want to save a few hours of compilation, i have here a package that contains the latest brew with the following installed packages:

~~~
adol-c		eigen		gsl		metis		p4est		sundials
arpack		fftw		hdf5		mpfr		parmetis	superlu
assimp		freeimage	hwloc		mumps		pcre		superlu_dist
autoconf	freetype	hypre		muparser	petsc		swig
automake	ftgl		isl		netcdf		pkg-config	szip
boost		gcc		libevent	ninja		readline	tbb
boost-python	gettext		libmatio	numdiff		scalapack	trilinos
cmake		gl2ps		libmpc		numpy		scotch		veclibfort
colpack		glm		libpng		oce		slepc		yaml-cpp
cppunit		glpk		libtool		open-mpi	sqlite
deal2lkit	gmp		makedepend	openssl		suite-sparse
~~~
and deal.II to the latest master. You can use this to bootstrap the signed deal.II build, by using the following (plus signature stuff) after you copied the deal.II app. 

~~~
REV=v8.5
NAME=8.5

export CXX=`which mpicxx`

SRC=/Applications/deal.II-$NAME-brew.app/Contents/Resources/brew/src/dealii/$NAME

if [ ! -d $SRC ]; then 
    rm -rf /Applications/deal.II-$NAME-brew.app/Contents/Resources/brew/src/dealii/*
    git clone /usr/local/src/d2-parallel-package/dealii $SRC
    pushd $SRC
    git co $REV -b package-$NAME
    rm -rf .git
    popd
fi

if [ ! -d ~/dealii/build-pack-$NAME ]; then
    mkdir ~/dealii/build-pack-$NAME
fi
cd ~/dealii/build-pack-$NAME

DST_INST=/Applications/deal.II-$NAME-brew.app/Contents/Resources/

cmake \
-GNinja \
-DDEAL_II_CPACK_EXTERNAL_LIBS:PATH=brew \
-DCMAKE_INSTALL_PREFIX:PATH=$DST_INST \
-DDEAL_II_COMPONENT_PACKAGE:BOOL=ON \
-DDEAL_II_CPACK_BUNDLE_NAME:STRING=deal.II-$NAME-brew \
$SRC

ninja package
# ninja -j$NP setup_tests
# ctest -j$NP -V -S ../tests/run_testsuite.cmake 
~~~

You can find the package here:

https://github.com/luca-heltai/dealii/releases/tag/v8.5.pre.5

**Comment by tjhei** [comment]
> Brew and spack use fundamentally different philosophies, and I don't have a direct preference over one or the other...

Fair enough. I think providing our binary package using brew like you have done works really well and is perfectly reasonable. I don't think providing two installers that do more or less the same thing is a good idea. At least we should "feature" only one of them.

**Comment by luca-heltai** [comment]
Ok. I'll stick to brew then. 👍

**Comment by tjhei** [comment]
Hey Luca,

I have been playing with automating the packaging on jenkins (*) and I have some questions:
1. Do I need to install brew packages into ``/Applications/deal.II-$NAME-brew.app/Contents/Resources/brew``? If yes, how do I do that?
2. The filename is always ``dealii-<deal.II version>.dmg``. I would like to change that so that we can also include an additional specifier like "MPI", "min", or something. Do you agree?
3. Does my Mac OS / xcode version matter and if yes, which one is preferred?

*: see https://jenkins.tjhei.info/job/temp-dealii-mac-package/TYPE=MIN,label=mac/lastBuild/console

**Comment by tjhei** [comment]
@luca-heltai Any comments?

I think I figured the automatic signing out: https://jenkins.tjhei.info/job/temp-dealii-mac-package/lastBuild/TYPE=MIN,label=mac/

**Comment by luca-heltai** [comment]
That's very good! 

If you want to install brew from scratch, using jenkins, for example, these are the steps I'd take.

Make sure you have a clean environment (no custom compilers, no custom python, etc.). Pick up the name you want your app to have:
~~~
# for example

# dealii sha1 
SHA=123abcd 

# Used for version name of the package inside brew path
VER=8.5

# Custom name (possibly, or not, based on version number/sha1/etc). You pick one.
NAME=deal.II-$VER-full-deps  

RES=/Applications/$NAME.app/Contents/Resources/
SRC=$RES/brew/src/dealii/$NAME
BLD=/tmp/build-$NAME-$SHA

mkdir -p $RES
mkdir -p $BLD

# Install brew in the right place
git clone https://github.com/Homebrew/brew.git  $RES/brew
export PATH=$RES/brew/bin:$PATH
brew install `brew deps dealii`

# Create source tree
git clone https://github.com/dealii/dealii $SRC
cd $SRC
git co $SHA
rm -rf .git

# build and install
cd $BLD

cmake \
-GNinja \
-DDEAL_II_CPACK_EXTERNAL_LIBS:PATH=brew \
-DCMAKE_INSTALL_PREFIX:PATH=$RES \
-DDEAL_II_COMPONENT_PACKAGE:BOOL=ON \
-DDEAL_II_CPACK_BUNDLE_NAME:STRING=$NAME \
$SRC

ninja package
~~~

The brew commands above install from scratch. This takes a long time. Change the cmake command to include your packaging part.

This should answer 1) and 2).

You pick the name of the package beforehand. Install everything somewhere under `/Applications/$NAME.app/Contents/Resources/`, including brew, indicate to cmake a relative path to `/Applications/$NAME.app/Contents/Resources/` to include in the package (`brew`, in our case), and call `ninja package` (or `make package`).

If you want to define some custom environment variables, or add custom things to path, you can create a file in `/Applications/$NAME.app/Contents/Resources/brew/external.conf`. This will be parsed, if found, by  `/Applications/$NAME.app/Contents/Resources/share/deal.II/dealii.conf` which is the file that is sourced by the `$NAME.app` application.

Hope this is a little more clear.

**Comment by tjhei** [comment]
okay, I will try to make that work this weekend if that is early enough for you.

**Comment by tjhei** [comment]
Oh, quick question: doesn't brew install to /usr/local/ in the default setting, which won't package the files because it is not under the app folder? Or am I missing something here?

**Comment by luca-heltai** [comment]
If you clone brew, and install it somewhere else than /usr/local, then it installs everything under the new path. I have several brew installations hanging around (for example, one is only there for git-kola, which comes with several hundred megabytes of additional packages. I did not want to package those as well in the deal.II pack...)

**Comment by tjhei** [comment]
I think I got it to work: https://jenkins.tjhei.info/job/temp-dealii-mac-package/TYPE=MAX,label=mac/lastBuild/

Can somebody with a mac test this installer and report back if it appears to be signed correctly?

**Comment by tjhei** [comment]
These might be a problem, right?
```
#            BZIP2_LIBRARIES = /usr/lib/libbz2.dylib
#            ZLIB_LIBRARIES = /usr/lib/libz.dylib
... /usr/lib/liblapack.dylib;/usr/lib/libblas.dylib
```

**Comment by luca-heltai** [comment]
No, they are not a problem, since they are bundled with mac os x. 

The signature seems not work. I get the warning:

"“deal.II-8.5.0.app” can’t be opened because the identity of the developer cannot be confirmed.

Also, some packages are missing (and I don't understand why. The log says that brew is installing PETSC, but it never finishes). GSL is also not installed. While you are at it, can you enable also python bindings as well?

**Comment by tjhei** [comment]
> It looks like the signature does not work. I get the warning:

Hm, this is weird. It looks like codesign ran successful though. I have no idea how to debug this, sadly. :-(

> Also, some packages are missing

I ran brew again and it continued installing more packages but it failed to install petsc:
```
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
C libraries cannot directly be used from Fortran
*******************************************************************************
```
Any ideas? (see https://jenkins.tjhei.info/job/temp-dealii-mac-package/27/TYPE=MAX,label=mac/console )

**Comment by tjhei** [comment]
@davydden are you familiar with this brew error message?

**Comment by davydden** [comment]
@tjhei you need to dig into PETSc's log, this error message won't help to get to the error.

**Comment by tjhei** [comment]
```
brew error:
Executing: /Applications/deal.II-8.5.0.app/Contents/Resources/brew/bin/mpif90  -o /tmp/petsc-6I1RTU/config.setCompilers/conftest  -Wl,-multiply_defined
,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first -Wl,-no_compact_unwind   -Wall -ffree-line-length-0 -Wno-u
nused-dummy-argument -g -O /tmp/petsc-6I1RTU/config.setCompilers/conftest.o -lto_library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchai
ns/XcodeDefault.xctoolchain/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib -lLTO -Wl,-rpath,/Applicat
ions/deal.II-8.5.0.app/Contents/Resources/brew/opt/libevent/lib -L/Applications/deal.II-8.5.0.app/Contents/Resources/brew/opt/libevent/lib -Wl,-rpath,/
Applications/deal.II-8.5.0.app/Contents/Resources/brew/Cellar/open-mpi/2.1.0/lib -L/Applications/deal.II-8.5.0.app/Contents/Resources/brew/Cellar/open-
mpi/2.1.0/lib -Wl,-rpath,/Applications/deal.II-8.5.0.app/Contents/Resources/brew/lib -L/Applications/deal.II-8.5.0.app/Contents/Resources/brew/lib -Wl,
-rpath,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/V
ersions/Current/Libraries -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Framewor
ks/OpenGL.framework/Versions/Current/Libraries -ldl -lmpi -lSystem -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctool
chain/usr/bin/../lib/clang/8.1.0/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0
/lib/darwin -lclang_rt.osx -ldl 
Possible ERROR while running linker: exit code 256
stderr:
ld: can't map file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib' for architecture x86_64
collect2: error: ld returned 1 exit status
                Popping language FC
            compilers: Error message from compiling {Cannot compile/link FC with /Applications/deal.II-8.5.0.app/Contents/Resources/brew/bin/mpif90.}
**** Configure header /tmp/petsc-6I1RTU/confdefs.h ****
```
A weird error. I decided to nuke the brew folder and start over...

**Comment by davydden** [comment]
oh, yes i know this one, a patch is here https://github.com/LLNL/spack/pull/3615

**Comment by tjhei** [comment]
ouch. @luca-heltai what version of xcode do you use?

**Comment by tjhei** [comment]
@luca-heltai what is the preferred version of xcode to use, 8.0? I would assume for best compatibility we would use the oldest compiler-set that is supported on the newest OS version? Otherwise you would get warnings about unsupported compiler options (I have seen those).

**Comment by luca-heltai** [comment]
I'd use xcode 8.0 until all issues have been resolved with 8.1. 

I verified that the package created with 8.0 works on 8.1. Maybe someone else with a Mac could give a shot at that?

**Comment by tjhei** [comment]
> Maybe someone else with a Mac could give a shot at that?

I tried your package on my mac (xcode 8.3, latest OS update) and I can not configure step-1 because
```
bash-3.2$ which mpicxx

/Applications/deal.II-8.5-brew.app/Contents/Resources/brew/bin/mpicxx

bash-3.2$ mpicxx -v

Illegal instruction: 4
```

Any idea what is going on here? Can you share your detailed log you used to compile your 8.5-brew package?

**Comment by tjhei** [comment]
I now also see "illegal instruction: 4" when compiling an archive on my machine and installing them on an older mac osx laptop. I think this is due to ``march=native`` being used by brew by default: https://github.com/Homebrew/homebrew-core/issues/4027 and https://github.com/Homebrew/brew/blob/master/docs/Bottles.md

I think we should build with ``--bottle-arch=core2``. @luca-heltai ?

**Comment by tjhei** [comment]
Doesn't work. Maybe ``brew install --build-bottle``?

**Comment by tjhei** [comment]
well, this would work in theory, but now I get this:
```
==> Installing homebrew/science/dealii dependency: adol-c
==> Downloading http://www.coin-or.org/download/source/ADOL-C/ADOL-C-2.6.2.tgz
Already downloaded: /var/lib/jenkins/Library/Caches/Homebrew/adol-c-2.6.2.tgz
==> ./configure --prefix=/Applications/deal.II-8.5.0.app/Contents/Resources/brew/Cellar/adol-c/2.6.2 --enable-sparse --with-colpack=/Applications/deal.II-8.5.0.app/Contents/Resources/brew/opt/colpack --enable-ulong
Last 15 lines from /var/lib/jenkins/Library/Logs/Homebrew/adol-c/01.configure:
checking whether to use 32-bit or 64-bit locations... 64-bit
checking whether to use single or double precision... double
checking whether to enable advanced branching operations... no
checking whether to use ADOL-C debug mode... no
checking whether to use ADOL-C hard debug mode... no
checking whether the default adouble constructor should initialize the value to 0... yes
checking whether the adouble variables have a late initialize option for functions like malloc/realloc... no
checking whether errno is thread save... no
checking which flag to use to enable OpenMP... none
checking for boostlib >= 1.54... yes
checking boost/pool/pool_alloc.hpp usability... yes
checking boost/pool/pool_alloc.hpp presence... yes
checking for boost/pool/pool_alloc.hpp... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
READ THIS: http://docs.brew.sh/Troubleshooting.html


Error: Your Xcode (8.1) is outdated.
```

So homebrew is broken with 8.3 but won't work with 8.1? Hurrah.

@luca-heltai ?

**Comment by luca-heltai** [comment]
At the moment I'm stuck with 8.1, and seeing what is happening to you, I'm a bit afraid of upgrading to 8.3. I'll do that later this week, and try to figure out a way to make this work.

**Comment by davydden** [comment]
> So homebrew is broken with 8.3 but won't work with 8.1? Hurrah.

probably, the only way is to fix it upstream

p.s. I stoped caring about homebrew and only keep an eye on deal.II stack in Spack, where `0ed18de8365f6e951938dc686392aaf7be3e621c` has all the needed fixes for XCode 8.3.

**Comment by tjhei** [comment]
> probably, the only way is to fix it upstream

Yeah, not something I want to get into (limited mac knowledge anyways). I am now running through everything with XCode 8.2 and we can see where that goes. I learned that you can install several xcode versions alongside each other and switch between them with ``xcode-select``.

> I stoped caring about homebrew and only keep an eye on deal.II stack in Spack

Maybe that is what we should be using instead then.

**Comment by davydden** [comment]
> Maybe that is what we should be using instead then.

i guess the problem here is to figure out how to create an `app` manually without `CMake` help, as it's currently done for `brew` installation (note that `dealii` is compiled by hand). The packaged `app`, essentially, should only contain the root of the spack folder, which should be usable as-is. Say if one day someone adds `aspect` package to `spack`, mac users should be able to do `spack install aspect` and enjoy the pre-installed `deal.ii`, distributed within the `app` package. 

Unfortunately, i have zero knowledge in packaging for macOS. I have always been building things manually.

**Comment by tjhei** [comment]
> Unfortunately, i have zero knowledge in packaging for macOS. I have always been building things manually.

Same here but I was stupid enough trying to figure things out. I guess it makes more sense to stay with brew for now because we are very close to having it work.

**Comment by davydden** [comment]
> I guess it makes more sense to stay with brew for now because we are very close to having it work.

that I agree. Figuring out packaging on macOS is far harder than fixing a few minor issues on brew.

**Comment by tjhei** [comment]
It gets even better:
```
$ brew install --build-bottle adol-c
Error: Your Xcode (8.2.1) is outdated.
Please update to Xcode 8.3.1 (or delete it).
```

@luca-heltai : the plan is to install gcc+mpi and ship it so that we don't depend on the users clang that is installed, right? But aren't we compiling all dependencies using clang because that is what brew is using? Or am I missing a way to tell brew what compiler to use (after we installed gcc)?

I am currently doing 
```
export HOMEBREW_BUILD_FROM_SOURCE=1
brew tap homebrew/science
brew install --build-bottle --only-dependencies dealii
```
and it doesn't work with xcode 8.1, 8.2, or 8.3.

**Comment by luca-heltai** [comment]
I can try to do that. But even simpler, if it is possible to load the environments used by spack version of deal.II, then we can still use the "manually built" deal.II, on top of spack installed stuff.

**Comment by davydden** [comment]
> I can try to do that. But even simpler, if it is possible to load the environments used by spack version of deal.II, then we can still use the "manually built" deal.II, on top of spack installed stuff.

see https://github.com/dealii/dealii/wiki/deal.II-in-Spack#develop-using-spack  The proper way to do it is with `spack setup`, but the command is currently broken and the fix is not merged yet https://github.com/LLNL/spack/pull/2664

**Comment by tjhei** [comment]
Can someone with an updated OSX and xcode please test https://jenkins.tjhei.info/job/dealii-mac-package/TYPE=MAX,label=mac/ ?
I am now using homebrew to install gcc+openmpi and then install trilinos and p4est (other deps disabled for now) using candi. I am interested to know if signing is successful and whether something like step-32 works.

**Comment by luca-heltai** [comment]
@tjhei , I get the same error: "can't be opened because the identity of the developer cannot be confirmed"...

:(

**Comment by tjhei** [comment]
Weird, but not too surprising because cpack is somehow not able to sign it (even though it thinks it does):
```
CPack: - Application has been codesigned
CPack: - package: /private/var/lib/jenkins/workspace/workspace/dealii-mac-package/TYPE/MAX/label/mac/build/dealii-8.5.0.dmg generated.
```
But
```
+ codesign -dv --verbose=4 dealii-8.5.0.dmg
dealii-8.5.0.dmg: code object is not signed at all
```
so I am signing manually:
```
+ codesign --deep -f -s 'Developer ID Application: Timo Heister' dealii-8.5.0.dmg
```
and then we get this:
```
+ codesign -dv --verbose=4 dealii-8.5.0.dmg
Executable=/private/var/lib/jenkins/workspace/workspace/dealii-mac-package/TYPE/MAX/label/mac/build/dealii-8.5.0.dmg
Identifier=dealii-8
Format=disk image
CodeDirectory v=20200 size=296 flags=0x0(none) hashes=1+6 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=6638d26e09dafad48db43301db6784b47a845cb5
Hash choices=sha256
Page size=none
CDHash=6638d26e09dafad48db43301db6784b47a845cb5
Signature size=8862
Authority=Developer ID Application: Timo Heister (NLL8XS39R3)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 2, 2017, 12:51:51 PM
Info.plist=not bound
TeamIdentifier=NLL8XS39R3
Sealed Resources=none
Internal requirements count=1 size=168
```
see the log at https://jenkins.tjhei.info/job/dealii-mac-package/TYPE=MAX,label=mac/lastBuild/console

**Comment by tjhei** [comment]
beside the signing process not working, is the build itself usable?

**Comment by tamiko** [comment]
Current status?

**Comment by tjhei** [comment]
I am playing with spack on my mac as an alternative to brew but I am (of course) running into issues:

1. I am compiling ``gcc@7.2.0`` and then installing ``openmpi%gcc``, but the ``pkg-config`` dependency fails with 
    ```
     702   /System/Library/Frameworks/Security.framework/Headers/Authorization.h:192:7: error: variably modified ‘bytes’ at file scope
    ```

2. I can use ``mpich%gcc`` instead, which seems to work (after adding an entry to /etc/hosts that I hope our users don't have to do): deal.II compiles, but the quicktest ``step.release`` fails with a segfault. All other tests work.

Question: should we stick to the idea of bundling gcc to avoid depending on the system's clang compilers? If not, can we only install gfortran (do we need to ship it?)?

**Comment by jppelteret** [comment]
You could also compile clang on spack and then use it in preference to the system version. Have you tried this yet?

**Comment by tjhei** [comment]
> You could also compile clang on spack and then use it in preference to the system version. Have you tried this yet?

Huh, interesting. I guess that could work too.

What are people normally using on OSX, the system clang + gfortran?

**Comment by tjhei** [comment]
1. I don't see clang in the spack repo
2. I assumed mixing gfortran and clang compilers might not be a well-supported option in spack, am I wrong?

**Comment by jppelteret** [comment]
That's the setup I'm using, and I think that Denis is too.

On 28 Aug 2017 23:03, "Timo Heister" <notifications@github.com> wrote:

You could also compile clang on spack and then use it in preference to the
system version. Have you tried this yet?

Huh, interesting. I guess that could work too.

What are people normally using on OSX, the system clang + gfortran?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dealii/dealii/issues/4109#issuecomment-325480727>, or mute
the thread

**Comment by jppelteret** [comment]
I think that clang is an option in the llvm suite. I've not yet run into
any issues using clang as the c++ compiler and gfortran compiled via spack
as the Fortran compiler. Its the recommended option on MacOS for slack.

**Comment by davydden** [comment]
> I don't see clang in the spack repo

i believe it's `llvm`:

```
$ spack info llvm
CMakePackage:   llvm

Description:
    The LLVM Project is a collection of modular and reusable compiler and
    toolchain technologies. Despite its name, LLVM has little to do with
    traditional virtual machines, though it does provide helpful libraries
    that can be used to build them. The name "LLVM" itself is not an
    acronym; it is the full name of the project.

Homepage: http://llvm.org/

Preferred version:
    4.0.0    http://llvm.org/releases/4.0.0/llvm-4.0.0.src.tar.xz
```

> I assumed mixing gfortran and clang compilers might not be a well-supported option in spack, am I wrong?

yes, it's well supported and recommended way for macOS. Apple's `clang` _compiler family_ has special hacks to find `gfortran` as a companion `fortran` compiler:
````
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/gcc-6.3.0-kn4b6xtmi7tqxwzz7gzctbtn2efngfhs/bin/gfortran
      fc: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/gcc-6.3.0-kn4b6xtmi7tqxwzz7gzctbtn2efngfhs/bin/gfortran
    spec: clang@8.1.0-apple
    target: x86_64
```
I have not tried using `llvm` though...

**Comment by jppelteret** [comment]
https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/llvm/package.py

**Comment by jppelteret** [comment]
I've installed LLVM on MacOS and it works fine. I didn't use clang though,
and I think that I needed to disable one or two of the variants (eg.
Polly). I could post a specific set of working variants tomorrow.

**Comment by davydden** [comment]
> Do we need to ship gfortran, I guess we only need it at build time, right?

correct, but some libs might be linking against `libgfortran` in the toolchain. So i would ship it as well. Also if users would want to build something else, it's good to have it around.

**Comment by tjhei** [comment]
> correct, but some libs in the toolchain might be linking against libgfortran. So i would ship it as well. Also if users would want to build something else, it's good to have it around.

Is there a way to only get gfortran? Otherwise we are shipping the whole gcc...

**Comment by davydden** [comment]
> Is there a way to only get gfortran? Otherwise we are shipping the whole gcc...

not unless you manually cut it out. `gcc` does not have a way to build/install `gfortran` only.

**Comment by davydden** [comment]
@tjhei i don't know how exactly you play around with Spack, but be sure to keep everything already in the right location, i.e. `/Applications/deal.ii/spack` (or whatever) because Spack uses `rpaths` extensively and it can get very cumbersome later to relocate things or fix `install_name`'s on macOS. Few more advices: Spack has different configuration _scopes_ (see http://spack.readthedocs.io/en/latest/configuration.html?highlight=configuration). What you want to do is to configure compilers in the so-called _site_ scope (`$(spack_prefix)/etc/spack/`). Users would then be able to still add their preferences in _user_ scope (`$~/.spack/`). 

Let me know if you need any help with this. I remember last time you was playing with it, I was able to provide you with the whole stack built with Apple's clang in `/Applications/dealii` folder or alike.

**Comment by jppelteret** [comment]
@tjhei This is the relevant portion of my `package.yaml`:
```yaml
  llvm:
    version: [4.0.0]
    variants: +all_targets+clang+compiler-rt~debug+gold+internal_unwind+libcxx~link_dylib~lldb~polly+shared_libs
```

**Comment by tjhei** [comment]
> @tjhei i don't know how exactly you play around with Spack, but be sure to keep everything already in the right location, i.e. /Applications/deal.ii/spack (or whatever) because Spack uses rpaths extensively and it can get very cumbersome later to relocate things or fix install_name's on macOS.

Yes, that is what I am doing. Then just run cpack on the whole thing like we did with homebrew.

> Spack has different configuration scopes

Does this matter though? I don't think I want people to use the spack inside the bundle that we ship.

> I remember last time you @luca-heltai was playing with it, I was able to provide the whole stack built with Apple's clang in /Applications/dealii folder or alike.

I already have that working, but deal.II is not working correctly. ;-) I guess we first have to decide what to do with respect to compilers: clang vs gcc, gfortran, what to ship, etc..

**Comment by jppelteret** [comment]
@tjhei I've come across something that you might find interesting: [A fortran compiler targeting LLVM](https://github.com/flang-compiler/flang). Maybe its not ready for our use yet (it requires some modified version of clang so packaging it into spack, although possible, would be a pain). But it appears that the aim is to integrate it into the LLVM suite in the future.

**Comment by tjhei** [comment]
> Maybe its not ready for our use yet

We need this to compile low-level BLAS stuff and for Trilinos, so no, nothing I want to touch. ;-)

**Comment by tjhei** [comment]
spack's mpich 3.2 is broken: https://lists.mpich.org/pipermail/discuss/2016-May/004764.html
This is fixed in homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpich.rb#L37

I am getting annoyed by this stuff. This is not how I want to spend my time.

**Comment by davydden** [comment]
Use 'openmpi', it's default provider

**Comment by tjhei** [comment]
I can not compile ``openmpi%gcc@7.2.0`` (see the message above)

**Comment by jppelteret** [comment]
How about we write a patch for `spack`'s MPICH2 that follows what they've done in `homebrew`? It sounds like it might be the easiest way to solve the issue and doesn't look like a terribly difficult fix.

**Comment by davydden** [comment]
I will have a look at patching, will do within an hour or so....

**Comment by davydden** [comment]
see https://github.com/LLNL/spack/pull/5235

**Comment by davydden** [comment]
> Does this matter though? I don't think I want people to use the spack inside the bundle that we ship.

there is no reason not to. I mean it is the same hassles to create a macOS package, why not giving users extra features for free?

**Comment by davydden** [comment]
@tjhei you can take my changes to your local Spack and keep going, you don't have to wait for that PR to be merged.

**Comment by tjhei** [comment]
Is somebody willing to try out https://jenkins.tjhei.info/job/dealii-mac-package/TYPE=MAX,label=mac/61/ ?

This is openmpi(homebrew), trilinos (with candi), p4est (with candi) + deal.II 8.5.1 using clang compilers. I am also curious if signing the .dmg worked correctly.

**Comment by tjhei** [comment]
What do we want to include at the end?
- arpack, gsl, hdf5, metis, netcdf, opencascade, p4est, petsc, slepc, trilinos
- parmetis?, superlu?
- numdiff? astyle?

I fear that including everything might be overkill. Thoughts?

**Comment by drwells** [comment]
I'd prefer to include everything: I think it would be very frustrating if a user wanted to use something obscure and found it in the online documentation but not in their local copy.

That being said, leaving out GSL and netcdf is probably safe.

**Comment by jppelteret** [comment]
@tjhei Very nice! This mostly worked for me (I could run a tutorial in serial), but there are a couple of issues that I encountered:

 - I'm running `MacOS 10.11`, so `step-33` failed with
```sh
bash-3.2$ mpirun -np 4 ./step-33
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/deal.II-8.5.1.app/Contents/Resources/brew/opt/libevent/lib/libevent-2.1.6.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```
Should we consider building this package for older versions of `MacOS` as well? I suspect that most people typically upgrade their Mac operating systems frequently, and I'm one of the outsiders.
- Maybe this is related to my using an older OS, but the package wouldn't verify and I had to bypass this.

Like @drwells I agree that we should try to include as much as possible (including `GSL` which can be very useful indeed).

**Comment by luca-heltai** [comment]
No. Don't leave out GSL. (we use it). Maybe netcdf (I have no idea where we use netcdf... shouldn't we remove it alltogether???)...

**Comment by luca-heltai** [comment]
@tjhei , signature is still broken.

However, the package works perfectly. I can run step-32 and step-40 in parallel with no issues.

**Comment by tjhei** [comment]
> I'm running MacOS 10.11

Yeah, I am not surprised that it won't work with an older OSX version.

> Should we consider building this package for older versions of MacOS as well?

That means we would to build on a machine running 10.11, right? Difficult for me to pull off.

**Comment by tjhei** [comment]
> No. Don't leave out GSL. (we use it).

How do you install GSL? This is typically a system package under linux.

> signature is still broken.

I think I now understand what is going on: cpack only signs the .app folder but not the dmg. I manually sign the .dmg (and it reports it to be signed), but that might not be correct. Can you check what ``codesign -dv --verbose=4 *dmg`` says?

**Comment by jppelteret** [comment]
If you can't build on (easily) `MacOS 10.11` then maybe we should just advertise the `.dmg` as being `MacOS 10.12` compatible only. 

> How do you install GSL?

`brew install gsl`?

**Comment by tjhei** [comment]
Now with a lot of dependencies https://jenkins.tjhei.info/job/dealii-mac-package/TYPE=MAX,label=mac/65/
(everything except netcdf and 64bit indices)

**Comment by davydden** [comment]
@luca-heltai already has a working macOS package, so I think this can be closed (please reopen if it's not the case)
