### ISSUE TITLE
MGMatrix is deprecated but used in tutorials

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#411]
class `MGMatrix` is deprecated in `include/deal.II/multigrid/mg_matrix.h`, but it is used in steps 37, 39 and 50. One or the other should change.

**Comment by bangerth** [comment]
It is now only used in step-50, which is not ready anyway. Whenever someone starts looking at it again, this will have to be addressed.

@tjhei : Or you could look at it right away. I think the change would simply have to be `MGMatrix<M,V>` -> `mg::Matrix<V>` but I'm not feeling comfortable doing this.

**Comment by tjhei** [comment]
will do

**Comment by guidokanschat** [comment]
I'm already at it!

**Comment by tjhei** [comment]
me too, done with mg::matrix, working on the other function calls...
