### ISSUE TITLE
python wrappers not working on MAC

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#4110]
With brew freshly installed on my mac:

~~~
guest-050:build-pack-8.5 heltai$ brew list
adol-c		fftw		hdf5		mpfr		parmetis	swig
arpack		freeimage	hwloc		mumps		pcre		szip
assimp		freetype	hypre		muparser	petsc		tbb
autoconf	ftgl		isl		netcdf		pkg-config	trilinos
automake	gcc		libevent	ninja		scalapack	veclibfort
boost		gettext		libmatio	numdiff		scotch		yaml-cpp
boost-python	gl2ps		libmpc		numpy		slepc
cmake		glm		libpng		oce		suite-sparse
colpack		glpk		libtool		open-mpi	sundials
cppunit		gmp		makedepend	openssl		superlu
eigen		gsl		metis		p4est		superlu_dist
~~~

I get the following errors and warnings when trying to build python bindings

~~~
[10/16] Building CXX object contrib/python-bindings/s...eFiles/PyDealII_release.dir/export_triangulation.cc.o
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/source/export_triangulation.cc:16:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/include/triangulation_wrapper.h:23:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/include/point_wrapper.h:23:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/include/boost/python.hpp:49:
/Applications/deal.II-8.5-brew.app/Contents/Resources/brew/include/boost/python/opaque_pointer_converter.hpp:172:1: warning: missing field 'tp_version_tag' initializer [-Wmissing-field-initializers]
};
^
1 warning generated.
~~~

and 
~~~
[15/16] Building CXX object contrib/python-bindings/s...Files/PyDealII_release.dir/triangulation_wrapper.cc.o
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/source/triangulation_wrapper.cc:16:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/include/triangulation_wrapper.h:23:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/include/point_wrapper.h:23:
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/include/boost/python.hpp:49:
/Applications/deal.II-8.5-brew.app/Contents/Resources/brew/include/boost/python/opaque_pointer_converter.hpp:172:1: warning: missing field 'tp_version_tag' initializer [-Wmissing-field-initializers]
};
^
In file included from /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/source/triangulation_wrapper.cc:16:
/Applications/deal.II-8.5-brew.app/Contents/Resources/brew/src/dealii/8.5/contrib/python-bindings/include/triangulation_wrapper.h:177:10: warning: private field 'updated' is not used [-Wunused-private-field]
    bool updated;
         ^
2 warnings generated.
ninja: build stopped: subcommand failed.
~~~

am I missing anything?

**Comment by davydden** [comment]
> am I missing anything?

probably dealii in brew is not maintained to work correctly with python wrappers. 

I don't see those issues with Spack, which builds ok with `python` wrappers `on` by default.

**Comment by davydden** [comment]
i think the issue belongs to homebrew, not dealii

**Comment by luca-heltai** [comment]
but this deal.II is not the one that comes with brew. It is using all brew packages, but it is a freshly cloned deal.II repo.

**Comment by luca-heltai** [comment]
cmake detects boost-python and python correctly, but then it fails to build. This is certainly a deal.II bug, not brew's fault if we detect things, say everything is fine, and then fail to compile...

**Comment by davydden** [comment]
in Spack we do `boost+python` and 
```
                '-DDEAL_II_COMPONENT_PYTHON_BINDINGS=%s' %
                ('ON' if '+python' in spec else 'OFF')
```
and it works. Why you have issues with homebrew -- no idea.

**Comment by davydden** [comment]
> detects boost-python and python correctly, but then it fails to build.  This is certainly a deal.II bug...

not necessarily, maybe `boost` is build against a different python that that detected by CMake.

**Comment by davydden** [comment]
@luca-heltai Spack build I sent you has `python` bindings enabled, btw.

**Comment by luca-heltai** [comment]
To be precise, these are the actions I took:

~~~
brew install `brew deps dealiii`
brew install boost-python

git clone dealii...
mkdir build; cd build; cmake -DDEAL_II_COMPONENT_PYTHON_BINDINGS=ON ../
make -j4
~~~

@davydden , I'm simply trying to understand why the obvious thing does not work.

**Comment by davydden** [comment]
>  I'm simply trying to understand why the obvious thing does not work.

don't know, but all I am saying is that it works if you don't use `brew`. You need dig into how they install boost and it's python part and how is it different from what is done in Spack which is working.

**Comment by luca-heltai** [comment]
Ok. I could make it compile by forcing python 2 library and include files in CMaceCache.txt. I still think this is a problem (maybe of cmake?) in our cmake detection of python libraries. It found python 2.7 executable (/usr/bin/python) and then selected the wrong include/lib files. It is definitely our cmake that does this. No external python here (while with spack you have also an external python).

**Comment by Rombur** [comment]
@luca-heltai The problem is that the python found by deal needs to be the same as the one used by booost.python. The problem is that on most system you have at least two versions of python (2.7 and 3.x). This is similar to having mpich and openmpi installed on your machine and letting deal pick the right one, it won't work. You need to set the python path yourself using `-D PYTHON_LIBRARY` and `-D PYTHON_INCLUDE_DIR `. We are using the standard `FindPython` from cmake https://cmake.org/cmake/help/v3.5/module/FindPythonLibs.html

**Comment by luca-heltai** [comment]
Thanks @Rombur . This makes sense.

**Comment by davydden** [comment]
> The problem is that the python found by deal needs to be the same as the one used by booost.python.

that is exactly what I mean above https://github.com/dealii/dealii/issues/4110#issuecomment-288986575 . With Spack it's guaranteed because the whole graph of packages is being concretized first and then you build everything (or use external packages to fill the gaps). Thereby only one `python` is allowed in the graph to satisfy link dependencies of boost and dealii.

**Comment by luca-heltai** [comment]
boost-python and deal.II find the same python executable. 

If this is the default FindPython, then it is broken (not the first time that this happens). It is `FindPython` that mixes two different versions. We're not talking about boost-python with python3, and deal.II with python2.

I'm saying that *our* cmake, selects python2 as an executable, and python3 as libraries. I have nowhere said to cmake what python libraries to use (and my env is clean). This has nothing to do with boost-python (as for your https://github.com/dealii/dealii/issues/4110#issuecomment-288986575), but with the FindPython script.

**Comment by davydden** [comment]
> I'm saying that our cmake, selects python2 as an executable, and python3 as libraries.

probably this needs to be submitted to CMake folks so that `FindPython` is fixed.
