### ISSUE TITLE
failing ABF test on 8.5 branch with gcc 5.4.0

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4113]
run from 4bc4550f51f204771b2938f4bc0325b3b2f4305d 
```
        2838 - fe/abf_02.debug (Failed)
	2839 - fe/abf_02.release (Failed)
```

```
2838: --------------------------------------------------------
2838: An error occurred in line <1187> of file </home/davydden/spack/var/spack/stage/dealii-develop-dm257dqqea7mmq5an6avrzahqij2ekxj/dealii/include/deal.II/lac/vector.h> in function
2838:     Number dealii::Vector<Number>::operator()(dealii::Vector<Number>::size_type) const [with Number = double; dealii::Vector<Number>::size_type = unsigned int]
2838: The violated condition was: 
2838:     i<vec_size
2838: Additional information: 
2838:     Index 0 is not in the half-open range [0,0). In the current case, this half-open range is in fact empty, suggesting that you are accessing an element of an empty collection such as a vector that has not been set to the correct size.
2838: --------------------------------------------------------
```

p.s. I am away from my Ubuntu box until the end of the next week, so I won't be able to dig into this issue...

---

p.p.s. also known opencascade tests https://github.com/dealii/dealii/issues/3915 with diff failure:
```
	7435 - opencascade/arclength_boundary_02.debug (Failed)
	7436 - opencascade/arclength_boundary_02.release (Failed)
	7471 - opencascade/plane_intersection_01.debug (Failed)
	7472 - opencascade/plane_intersection_01.release (Failed)
```
shall we remove those two tests from 8.5 branch?

**Comment by masterleinad** [comment]
For `fe/abf_02` the commit [`8c4e947cf88303202cbb751892163ae65c4649f1`](https://github.com/dealii/dealii/commit/8c4e947cf88303202cbb751892163ae65c4649f1) is the first failing.

**Comment by davydden** [comment]
@bangerth ping.

**Comment by masterleinad** [comment]
It seems that this just accidentally didn't fail before: The size of `generalized_support_points` (and `values[0]` resp. `support_point_values` is only 14 for a `FE_ABF<3>(0)` element while we try to access
entries 24-29 in the `Face integral of ABF terms` part of `interpolate` resp. `convert_generalized_support_point_values_to_nodal_values`.
