### ISSUE TITLE
step-33 fails

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4119]
this happens when I run step-33:
```
...
T=1.9
   Number of active cells:       2140
   Number of degrees of freedom: 9184

   NonLin Res     Lin Iter       Lin Res
   _____________________________________
   2.320e-01        0013        3.94e-12
   1.235e-01        0016        6.62e-12
   8.494e-02        0016        6.05e-12
   1.199e+01        0026        5.72e-10
ilut: zero pivot encountered!
```

Does anybody have an idea what is going on here? Do we need to fix this for 8.5?

**Comment by masterleinad** [comment]
I can't reproduce in `86e9bf463f2d37118` nor on the `dealii-8.5.0` branch(1d3d22f3be386160). Do you see this problem in the main branch, too?

**Comment by drwells** [comment]
I can reproduce this. A guess: @masterleinad what Trilinos version are you using? I have 12.10.

**Comment by drwells** [comment]
Hm. I see the same problem with 8.4 and 8.3, and with the direct solver: things blow up at T = 1.9.

**Comment by masterleinad** [comment]
Actually, I can reproduce it now. Not sure what I was doing...

**Comment by drwells** [comment]
Things seem to work fine with 8.2. I think it is time for a bisect.

**Comment by drwells** [comment]
Correction: the 8.2 version blows up at t = 8.38 even with more regularization and more iterations.

**Comment by drwells** [comment]
8.1 blows up in a similar spot (8.32). My best guess is that there is a subtle stability problem (either with the discretization or a bug) here which changes between 8.2 and 8.3 made worse.

**Comment by tjhei** [comment]
> Correction: the 8.2 version blows up at t = 8.38 even with more regularization and more iterations.

I failed to read the results section: the method is supposed to become unstable with the default parameters. When switching to ``diffusion power = 1.5`` things are stable for a long time for me. I assume we are at a steady state at that t = 8?

I think we can close this issue with "working as intended".
