### ISSUE TITLE
[8.5] deprecation warning in step-37

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4123]
```
[ 50%] Building CXX object CMakeFiles/step-37.dir/step-37.cc.o
In file included from /ssd/deal-git/examples/step-37/step-37.cc:55:
/ssd/deal-build/installed-clang/include/deal.II/matrix_free/matrix_free.h:141:10: warning: 'mpi_communicator' is deprecated [-Wdeprecated-declarations]
  struct AdditionalData
         ^
/ssd/deal-git/examples/step-37/step-37.cc:1182:9: note: in instantiation of member function 'Step37::LaplaceProblem<3>::setup_system' requested here
        setup_system ();
```

Can we remove ``DEAL_II_DEPRECATED`` in:
```
MPI_Comm            mpi_communicator DEAL_II_DEPRECATED;
```
?

**Comment by kronbichler** [comment]
So this is related to #4117 and only appears for the `clang` compiler where we cannot selectively disable the deprecation warnings. Apart from removing the deprecation warning for now, I do not see a good solution for this, so I would suggest we do this. (We can leave the deprecation warning in place for the constructor.)

**Comment by bangerth** [comment]
Can we just punt and say this is it for 8.5? I'm concerned that we're not converging towards a release.

**Comment by tjhei** [comment]
I am fine with that, but I would prefer to have #4122 in 8.5.
