### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by Menion93** [dealii/dealii#4146]
I am having a problem installing dealii on Windows. When I compile it on Visual Studio 2015 I get a class of similar errors like this one:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	

When i generated the source with cmake I also got some failed tests and a configuration with most of the feature disabled.

```
###
#
#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       DebugRelease
#        BUILD_SHARED_LIBS:      OFF
#        CMAKE_INSTALL_PREFIX:   C:/Program Files (x86)/deal.II
#        CMAKE_SOURCE_DIR:       F:/tesi/dealii-master
#                                (version 9.0.0-pre)
#        CMAKE_BINARY_DIR:       F:/tesi/dealii-master/build
#        CMAKE_CXX_COMPILER:     MSVC 19.0.24215.1 on platform Windows AMD64
#                                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
#
#  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#      ( DEAL_II_WITH_ARPACK = OFF )
#        DEAL_II_WITH_BOOST set up with bundled packages
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#      ( DEAL_II_WITH_CUDA = OFF )
#        DEAL_II_WITH_CXX11 = ON
#        DEAL_II_WITH_CXX14 = ON
#      ( DEAL_II_WITH_GSL = OFF )
#        DEAL_II_WITH_HDF5 set up with external dependencies
#      ( DEAL_II_WITH_LAPACK = OFF )
#      ( DEAL_II_WITH_METIS = OFF )
#      ( DEAL_II_WITH_MPI = OFF )
#        DEAL_II_WITH_MUPARSER set up with bundled packages
#      ( DEAL_II_WITH_NETCDF = OFF )
#      ( DEAL_II_WITH_OPENCASCADE = OFF )
#      ( DEAL_II_WITH_P4EST = OFF )
#      ( DEAL_II_WITH_PETSC = OFF )
#      ( DEAL_II_WITH_SLEPC = OFF )
#      ( DEAL_II_WITH_THREADS = OFF )
#      ( DEAL_II_WITH_TRILINOS = OFF )
#      ( DEAL_II_WITH_UMFPACK = OFF )
#        DEAL_II_WITH_ZLIB set up with external dependencies
#
#  Component configuration:
#      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
#        DEAL_II_COMPONENT_EXAMPLES
#      ( DEAL_II_COMPONENT_PACKAGE = OFF )
#      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )
#
#  Detailed information (compiler flags, feature configuration) can be found in detailed.log
#
#  Run  $ make info  to print a help message with a list of top level targets
#
###
-- Configuring done
-- Generating done
-- Build files have been written to: F:/tesi/dealii-master/build
```

**Comment by tjhei** [comment]
What happens if you do ``cmake --build .`` in the build directory?
What is the active target in the IDE? Can you change it to "dealii" please?

**Comment by Menion93** [comment]
> What happens if you do cmake --build . in the build directory?

It gives me 0 warnings and 0 errors.

> What is the active target in the IDE? Can you change it to "dealii" please?

http://oi64.tinypic.com/2eaqd1z.jpg

The active target was INSTALL which gives me failures, if I change to deal_II and try to compile it succeed to compile

`========== Build: 30 succeeded, 0 failed, 7 up-to-date, 0 skipped ==========`

but when I link the library that I assumed it is generated here 

`F:\tesi\dealii-master\build\lib`

Visual Studio cannot recognizes  any dealii class

**Comment by tjhei** [comment]
You can try installing by running ``cmake --build . --target install``. How do you configure the examples? 

> Visual Studio cannot recognizes any dealii class

Error messages? You also need to run ``cmake`` in each example directory and point it to the correct deal.II path.

**Comment by Menion93** [comment]
Solved!  Doing this `cmake --build . --target install` produced an obvious error that allowed me to fix it. I just needed to run the command with administrator privileges.

Thank you!

**Comment by tjhei** [comment]
Did this fix your issue?

**Comment by Menion93** [comment]
Yes, like you said i needed to run the command you mentioned in the last post, thank you
