### ISSUE TITLE
[8.5] cmake 2.8.11 error

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4147]
@tamiko I am getting 
```
CMake Error at examples/CMakeLists.txt:56 (GET_FILENAME_COMPONENT):
  get_filename_component unknown component DIRECTORY
```
with cmake 2.8.11 (which we support). This is particularly bad for the 8.5 release. How about we bump the required cmake version on master and remove the example building thingy for 8.5?

**Comment by tjhei** [comment]
This has the other advantage that the example building won't cause problems: it has not been extensively tested and I can see cases where deal.II will fail to build just because there is an issue with one of the examples.

**Comment by bangerth** [comment]
Hm, `GET_FILENAME_COMPONENT` was part of 2.8.11: https://cmake.org/cmake/help/v2.8.11/cmake.html#command:get_filename_component

But apparently the `DIRECTORY` tag for this command wasn't. This was only introduced in 3.0: https://cmake.org/cmake/help/v3.0/command/get_filename_component.html

The command in question is this:
```
      GET_FILENAME_COMPONENT(_directory ${_step} DIRECTORY)
```

**Comment by tamiko** [comment]
@bangerth No, it was introduced in 2.8.12. See pull request for a fix.

@tjhei I agree that I feel a bit uneasy about default enabling building the examples. I suggest to simply set the default to "OFF" for the release.

This also ensures that building the library is not an incredible resource hog of eating more than twice the amount of compilation time...

**Comment by tjhei** [comment]
> This also ensures that building the library is not an incredible resource hog of eating more than twice the amount of compilation time...

I have noticed that too, yeah. :-/

**Comment by tamiko** [comment]
I'd say enabling it for the development version but disabling for the release might be a good compromise.
This way we get both, willing compilation drones checking our examples (when they happen to use the development version) and happy users of the releases.

**Comment by tjhei** [comment]
What do we do for master for now, just bump the cmake version we require?

**Comment by tamiko** [comment]
@tjhei Yes, I will bump to 2.8.12, pull request in 5 minutes.
