### ISSUE TITLE
thread initialization

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#415]
```MPI_InitFinalize``` calls ```set_thread_limit``` which parses the environment variable ```DEAL_II_NUM_THREADS```. We obviously don't require calling ```MPI_InitFinalize``` for a serial program. I think it is confusing, that the environment variable is ignored in that case. I see the following options:

1. Call ```MPI_InitFinalize``` in every program. Maybe rename it to something more generic.
2. Make sure ```set_thread_limit``` is executed once before we use TBB. Maybe sneak in a call inside every ::loop function?
3. Just ignore this.

**Comment by bangerth** [comment]
We could call `set_thread_limit` in `main()` of all of the programs that don't call `MPI_InitFinalize`. In practice, I'm inclined to ignore the issue -- if you're going to set an environment variable, it's fair to also require you to add a line to `main()`.

**Comment by Rombur** [comment]
If I think that we could just call set_thread_limit in the tutorials that explicitly use multithreading. I think that we should to do something, every couple of months someone as the same question...

**Comment by Rombur** [comment]
I think this is in a much better shape. I'm going to close it. We can reopen it if we still have confused people on the mailing list
