### ISSUE TITLE
[8.5 and master] fedora: deal.II missing petsc includes due to distributions not installing petsc configuration

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4157]
@kronbichler You authored commit 7c0171f0 that contains the following change in `changes.h.in`:
```
+// Some systems require including mpi.h before stdio.h which happens in
+// types.h
+#if defined(DEAL_II_WITH_MPI) || defined(DEAL_II_WITH_PETSC)
+#  include <mpi.h>
+#endif
```

The "or petsc" clause looks sketchy. The include fails for me on all architectures that (a) have a sequential petsc installed, (b) but no `mpi.h` in a reachable include file.
petsc happens to install a header `mpiuni/mpi.h`. Was that what you meant? (or did you mean to `&&`)?

**Comment by tamiko** [comment]
Oh wow, we do that consistently in a couple of places.

I guess a solution would be to include .../mpiuni if petsc is compiled sequentally. Pull request incoming.

**Comment by bangerth** [comment]
PETSc installs a fake `mpi.h` in case it's compiled as a sequential library without *real* MPI support. Is that fake include file not reachable for you? It ought to be, because it must be reachable from all of the PETSc headers that simply `#include <mpi.h>`.

**Comment by tamiko** [comment]
@bangerth Yes, It is not reachable. I guess no one bothered to use a sequental Petsc in a very long time. I am currently writing a fix that simply adds the appropriate mpiuni include directory if petsc is set up with mpiuni support.

**Comment by tamiko** [comment]
@bangerth I need a beer.

**Comment by drwells** [comment]
I think PETSc makes us all feel that way from time to time...

**Comment by kronbichler** [comment]
@tamiko You have found a solution; just to clarify: my commit was copy-pasting those lines from somewhere else and I had not checked with a serial petsc.

**Comment by tamiko** [comment]
@kronbichler Sorry, had nothing to do with your commit in particular - It just happened to be the first include error I encountered :-)

**Comment by kronbichler** [comment]
I realized that; I just thought defending myself with "copy-paste" would help my credibility ;-)

**Comment by bangerth** [comment]
On 03/30/2017 04:31 PM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth> I need a beer.

Don't we all, always? At least I live in a town of 150,000 that happens to 
have 28 (or is it now 32?) craft breweries. That's 28 (or 32) times as many as 
in College Station. I suppose Minneapolis isn't bad in this regard either.
