### ISSUE TITLE
Fix MathJax CDN links

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4169]
It looks like MathJax, the library we use for rendering formulas, is shutting down their CDN:

https://www.mathjax.org/cdn-shutting-down/

We should update the website to use a self-hosted copy of the library instead of relying on CDN support: we will have to recompile the documentation for the last few releases (this is a good chance to clean things up: we should consider getting rid of links for 8.0 and 8.1, for example).

We should consider bundling a copy of MathJax in case people want to build the documentation separately.

We will also have to update `doc/doxygen/CMakeLists.txt` to no longer refer to this web page.

**Comment by bangerth** [comment]
Do you suggest bundling mathjax with the releases as well? How much would that add to our repositories and tar balls?

**Comment by drwells** [comment]
I believe bundling this would require a few megabytes worth of assets. The CDN does suggest that there is a auto-minification script available that trims out things that are not used (e.g., we don't need to include most of the fonts and since the documentation is in English I suspect we can get rid of some of the internationalization support too).

I am not sure if we should bundle it with the releases or not: I don't really understand what gets built if we do not have MathJax available.

**Comment by oneliefleft** [comment]
What bad things happen if we don't have MathJax?


01.04.2017 18:08 "David Wells" <notifications@github.com> napisał(a):

**Comment by drwells** [comment]
We use MathJax to render all of the math formulas on the web page right now, so those won't show up unless we fix things by the end of the month. Additionally, our CMake configuration supports building the documentation with rendering provided by including `MathJax.js` from the CDN: that won't work anymore unless we update the link.

**Comment by drwells** [comment]
The relevant `CMakeLists.txt` file could use some love. My `CMakeCache.txt` currently has

```
[drwells@archway build]$ ack -A5 -B5 MATHJAX CMakeCache.txt
[...]
//If set to ON, doxygen documentation is generated using mathjax
DEAL_II_DOXYGEN_USE_MATHJAX:BOOL=OFF

//If set to ON, doxygen documentation is generated using online
// (from CDN) mathjax copy
DEAL_II_DOXYGEN_USE_ONLINE_MATHJAX:BOOL=ON

//Force feature autodetection by undefining all DEAL_II_WITH_*
// variables prior to configure
DEAL_II_FORCE_AUTODETECTION:BOOL=OFF
[...]
```

which is not consistent. My locally built documentation renders all math as images (which is right, since `DOXYGEN_USE_MATHJAX` is off). It looks like we assume that if doxygen is present then `gs`, `dvips`, and `latex` are also present (which doxygen claims are necessary for building math formulas).

**Comment by drwells** [comment]
Since we can build the documentation without MathJax I don't think we need to bundle it, so I changed the title.

**Comment by bangerth** [comment]
I find the MathJax formulas so much nicer that I'd be quite happy if we just *always* use it.

**Comment by drwells** [comment]
Most distributions provide a MathJax package, so since we can build things without it I think that we should not bundle an extra dependency.

We should improve the detection, though; it would be nice if my local documentation used my local copy of mathjax.

**Comment by tjhei** [comment]
We do not enable mathjax by default (DEAL_II_DOXYGEN_USE_MATHJAX=OFF) but use it for the web server. If you have a local installation (via MATHJAX_PATH) of mathjax, we already use it by default. Of course we should update the cdn.
I will prepare a PR.

**Comment by bangerth** [comment]
On 04/01/2017 09:58 PM, David Wells wrote:
> Most distributions provide a MathJax package, so since we can build things
> without it I think that we should not bundle an extra dependency.

The question though is what to do about the version we put on the website. Do 
we need to change our scripts? Or simply reference the other CDN?

**Comment by tjhei** [comment]
> Do
> we need to change our scripts? Or simply reference the other CDN?

just merge #4173 and it should work (I will confirm that it worked by checking the URLs).

**Comment by drwells** [comment]
@tjhei We still need to fix the script location on the older versions of the documentation.

**Comment by tjhei** [comment]
That is true. I guess we would need to ask @guidokanschat to do some regex magic.

**Comment by drwells** [comment]
It looks like several versions still rely on the old CDN: we should link to 

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js

or else the old docs won't work come May 1. Ping @guidokanschat

**Comment by drwells** [comment]
It looks like the MathJax people were nice enough to put a stub in place of their script that redirects to the new URL (this is described in an update to the original announcement) so our old documentation still works. The same link says that this is a temporary measure so we still need to fix this in the near future.

**Comment by drwells** [comment]
The reality of the situation is that the shim works and should continue to work - if it ever breaks we'll know and we can fix this then.
