### ISSUE TITLE
Look for external packages in /opt/

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4175]
As noted in #3893, it might be helpful for us to look for things in `/opt/` (e.g., Trilinos may be installed in `/opt/trilinos/`.

I don't think that this is important enough to be in 8.5 but we should add it for 9.0.

**Comment by davydden** [comment]
the question is how often this happens and if it's `opt/trilinos-xyz` or `opt/trilinos.x.y.z`, or any other convention users may come up with.

If this is simple enough to do in CMake, then fine. Otherwise I would say it does not worth the efforts as users can specify `-DTRILINOS_DIR=` manually.

**Comment by drwells** [comment]
This is a good point. Arch Linux, at least, uses `/opt/trilinos/`, `/opt/opencascade/`, etc, so a minimal effort will help some users.

**Comment by tamiko** [comment]
What is wrong about manually augmenting `CMAKE_PREFIX_PATH` by `\opt`?

I am not in favor of adding `/opt` or other specific paths to the path detection. (the cmake defaults are already too large in my opinion. I recall at least two users in the last year accidentally picking up obsolete stuff from `/usr/local`.)

First of all, it is bad practice. Secondly, there is no way to guess what a user really wants. So it is best to require minimal hints for paths.

With respect to the AUR packages. If archlinux decides to install stuff under /opt - then add appropriate hints to the deal.II AUR package as well (which, as far as I remember is already done).

**Comment by drwells** [comment]
Hm. I was not aware that we were picking up obsolete stuff. Lets close this and stick with fixing build scripts elsewhere.

I emailed AUR package's author to offer to answer any questions regarding configuration, so that should fix the issue on Arch Linux, at least.

**Comment by ChuckDaniels87** [comment]
I think that is the correct way to proceed. Some packages are installed on `/opt`, specifically large self-contained packages. AUR packages are not officially supported by Archlinux and usually their maintainers are not core developers of the distro. AUR package mantainer should be responsible to use proper compilation flags and to add needed dependencies. Anyways, it is really kind of you to offer support to the AUR package mantainer.

**Comment by drwells** [comment]
Thanks!

Florian (the current author) suggested that I take over since he isn't actively following development. I will put something together when we are done with the release.
