### ISSUE TITLE
[8.5] broken images in tutorials

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4195]
At least on my machine (chromium on linux) images on the website like https://dealii.org/developer/doxygen/deal.II/step_33.html#Results are not loading due to
```
Failed to load resource: net::ERR_INSECURE_RESPONSE
```
I also get this using wget:
```
$ wget https://www.dealii.org/images/steps/developer/step-32.3d.cube.0.png
--2017-04-06 08:59:53--  https://www.dealii.org/images/steps/developer/step-32.3d.cube.0.png
Resolving www.dealii.org (www.dealii.org)... 129.206.107.89
Connecting to www.dealii.org (www.dealii.org)|129.206.107.89|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `www.dealii.org'.
To connect to www.dealii.org insecurely, use `--no-check-certificate'.
```

Do we need to rewrite all URLs to be https://dealii.org/... ? Because that works for me.

**Comment by davydden** [comment]
works here on my mac, strange...

**Comment by tjhei** [comment]
Also with wget?

**Comment by davydden** [comment]
i don't have `wget` on mac

**Comment by oneliefleft** [comment]
Timo, I get this response in firefox and lynx. This seems to be affecting
older online material 8.4 etc. I don't know how to circumvent this. Is it a
problem on the server side?


06.04.2017 15:03 "Timo Heister" <notifications@github.com> napisał(a):

**Comment by tjhei** [comment]
Yes, it looks like there is no SSL certificate for www.dealii.org only for dealii.org: https://www.ssllabs.com/ssltest/analyze.html?d=www.dealii.org

@guidokanschat ?

**Comment by davydden** [comment]
> Yes, it looks like there is no SSL certificate for www.dealii.org only for dealii.org:

oh, i might have disable some of those at some point, therefore I can't reproduce the issue locally.

**Comment by guidokanschat** [comment]
Sorry, I had only included `dealii.org`, not `www.dealii.org` in the domain list. And chromium seems to accept the certificate of the unqualified domain, while firefox or wget does not.

**Comment by tjhei** [comment]
Works now, thanks!
