### ISSUE TITLE
Change `clone`s to return `std::unique_ptr`s

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4209]
For example, in #4207, instead of

```cpp
clone_base_elements += Threads::new_task ([ &,i,ind] ()
{
  base_elements[ind]
    = std::make_pair (std::shared_ptr<FiniteElement<dim,spacedim>>(fes[i]->clone()),
                      multiplicities[i]);
});
```

we could just write

```cpp
clone_base_elements += Threads::new_task ([ &,i,ind] ()
{
  base_elements[ind] = {fes[i]->clone(), multiplicities[i]};
});
```

and still have the memory managed correctly in all circumstances (if any destructor is thrown the `FiniteElement<dim> *`'s destuctor will be ~~thrown~~ run).

While this change would not be backwards compatible, I am not aware of any user projects (from my list of stars on GitHub) that use this function. We would break (in a small way) every user defined `FiniteElement` (and `Mapping`) that is not already in the repository. Thoughts?

I am usually not in favor of breaking changes, but this one is extremely useful, unlikely to break user codes, and is relatively easy to fix in the case that it does, so I think we should consider it.

edit: delete redundant sentence
edit: fix word choice

**Comment by bangerth** [comment]
A first step would be to let `FESystem` and `hp::FECollection` store `std::unique_ptr` objects instead of `std::shared_ptr`.

**Comment by bangerth** [comment]
I had a 20-second look and noticed that we have this in `FESystem`:
```
  /**
   * Pointers to underlying finite element objects.
   *
   * This object contains a pointer to each contributing element of a mixed
   * discretization and its multiplicity. It is created by the constructor and
   * constant afterwards.
   *
   * The pointers are managed as shared pointers. This ensures that we can use
   * the copy constructor of this class without having to manage cloning the
   * elements themselves. Since finite element objects do not contain any
   * state, this also allows multiple copies of an FESystem object to share
   * pointers to the underlying base finite elements. The last one of these
   * copies around will then delete the pointer to the base elements.
   */
  std::vector<std::pair<std::shared_ptr<const FiniteElement<dim,spacedim> >,
      unsigned int> >
      base_elements;
```
Can one assign a `std::unique_ptr` returned by `clone()` to a `std::shared_ptr`?

**Comment by bangerth** [comment]
To answer my own question: no, see http://www.cplusplus.com/reference/memory/shared_ptr/shared_ptr/ . 

We could think about changing the `base_elements` member to let it store a `std::unique_ptr` instead. Copying `FESystem` objects seems like a bad idea anyway. It would be interesting to `=delete` the copy constructor of `FESystem` to see if that even ever happens (which would likely be a bug).

**Comment by drwells** [comment]
@bangerth point 9 says that we may construct a `shared_ptr` from an rvalue reference to a `unique_ptr`, which is exactly what


```cpp
std::unique_ptr<FiniteElement<dim,spacedim>> clone() const;
```

would return; this answer should be yes unless I have missed something.

**Comment by bangerth** [comment]
I should not work on Sundays.

**Comment by bangerth** [comment]
In other words, you are entirely correct and I can't seem to read today.

**Comment by drwells** [comment]
we have all been there...

**Comment by bangerth** [comment]
I tried out where we copy `FESystem` objects -- only in `tests/fe/copy_fe`. I don't see a particular reason why we should still allow this -- should we just remove this possibility?

**Comment by drwells** [comment]
Since we disallow copying in `FiniteElement` I believe that we should disallow it here and just rely on `clone()`.

**Comment by bangerth** [comment]
OK. Will provide patch soon.

**Comment by bangerth** [comment]
See #4276.

**Comment by luca-heltai** [comment]
There still #4318, so this should be opened again...
