### ISSUE TITLE
[RFC] Remove <code>compat</code> feature

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#421]
One question that I had on mind for quite a while now:
Do we still need the compat feature stuff? Specifically
 - <code>Make.global_options</code>
 - the awkward directory layout that forces a bunch of special code in the cmake configuration
 - installation of <code>make_dependencies</code> executable

If it is just about providing a Makefile includable configuration file (similar to <code>deal.IIConfig.cmake</code>) this could be done (in a backward incompatible manner) easily by providing the cmake configuration <code>deal.IIConfig.cmake</code> with Makefile compatible syntax.

**Comment by bangerth** [comment]
I'm in favor. We will have had 2 years or releases, it's time to allow cleanups.
