### ISSUE TITLE
Add support for user comments in ParameterHandler

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#4211]
In order to use https://github.com/dealii/parameter_gui effectively, we would like to tunnel comments users wrote in their .prm files through the ParameterHandler class (see dealii/parameter_gui#10) to be able to display them in the GUI. More precisely the ParameterHandler, when reading .prm files should associate every comment with the following parameter, store it in a field, and output it when writing the xml entry for this parameter. Write support for prm files is not necessary, but possible (it would cause confusion with the parameter description that we already write into prm files).

**Comment by tjhei** [comment]
One more thing to consider is how you want to parse the following:
```
# some comment at the top of the file (1)

# comment after an empty line (2)
set a=1

# comment before section (3)
set subsection c

# some comment (4)

# comment after empty line (5)
set d=0

# weird comment here (6)
end

# or here? (7)
```

- Do you want a header comment or attach (1) and (2) to "a"? 
- How do you deal with subsection comments (3)?
- Do (4) and (5) get merged and is the empty line in between removed?
- What happens with (6) and (7)?

**Comment by drwells** [comment]
This is really something that needs to be tackled by the GUI itself, not us. We don't really have a good way to parse and store comments.
