### ISSUE TITLE
C++ cleanup: Remove deprecated classes

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4212]
Removes:

 - [x] BlockDiagonalMatrix
 - [ ] <s>FilteredMatrix</s>
 - [x] InverseMatrixRichardson
 - [x] IterativeInverse
 - [x] ProductMatrix
 - [x] ProductSparseMatrix
 - [x] ScaledMatrix
 - [x] SchurMatrix
 - [x] ShiftedMatrix
 - [x] ShiftedMatrixGeneralized
 - [x] TransposeMatrix

**Comment by tamiko** [comment]
On second thought, I will not deprecate an remove `FilteredMatrix`. The interface might be old but we do not provide an alternative functionality base on `LinearOperator` yet.

**Comment by bangerth** [comment]
So what's left then for this issue? It looks like other than #4568, everything has been addressed!

**Comment by tamiko** [comment]
> So what's left then for this issue? It looks like other than #4568,
> everything has been addressed!

Yes, the moment #4568 gets merged this issue will be closed (the PR
description has a closes #4568 ;-) )
