### ISSUE TITLE
TableHandler improvements

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4227]
https://github.com/geodynamics/aspect/pull/1429 shows a number of oddities in the `TableHandler` class that we've known of for a while already but that are still worth addressing:

* Provide a "canonical" way to start a new row in the table, rather than have some magic in `TableHandler::add_value` that does this.
* Provide a way to "declare" a column, rather than creating it the first time it is used. This would help with  being able to describe a particular order for columns we may want to have when creating output, and keeping this order even if the code that fills the table moves around within a piece of software.

**Comment by drwells** [comment]
I wrote some (as of yet) unmerged changes in ConvergenceTable (which inherits from this class) so I am also interested in making improvements here. I don't have anything concrete to offer right now but I would be interested in helping overhaul these two classes :)
