### ISSUE TITLE
Old code using std_cxx11 failing

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#4242]
Old codes may rely on the inclusion of `base/std_cxx11/*` in our header files to be able to use the old `std_cxx11` namespace. Currently, we are breaking these codes since we replaced all
 ```#include <deal.II/base/std_cxx11/*>``` 
inclusions by the standard ones. 

Do we really want to force the users that strictly to replace the `std_cxx11` namespace by `std`?

**Comment by davydden** [comment]
> Do we really want to force the users that strictly to replace the std_cxx11 namespace by std?

given that the next one is a major release, I am fine with that.

**Comment by Rombur** [comment]
I don't see why it is a problem. The `std_cxx11` functions still exists. You shouldn't rely on header files included inside headers from deal. If you want to use `std_cxx11`, you should include the header yourself. Otherwise, we can never remove header files that we were added by mistake.

**Comment by masterleinad** [comment]
OK. There seems to be consensus.
