### ISSUE TITLE
Consider including ptree_serialization.hpp in parameter_handler.h

### ISSUE THREAD

**Issue by xywei** [dealii/dealii#4243]
Since dealii::ParameterHandler uses boost::property_tree internally, to serialize an object of ParameterHandler type, I had to manually inlcude ptree_serialization.hpp in my code, which was not obvious from the compiler error messages at all. I only realized this after digging into the source code.

Therefore I recommend to add `#include <boost/serialization/ptree_serialization.hpp>` to ptree_serialization.hpp, so that its serialization works out of the box.

**Comment by bangerth** [comment]
@xywei -- yes, this seems eminently reasonable. Would you like to submit a patch for this, and thereby become a contributor to deal.II?

**Comment by xywei** [comment]
@bangerth It's my pleasure. I have made a pull request at #4248.

**Comment by bangerth** [comment]
Fixed by #4248.
