### ISSUE TITLE
variadic templates

### ISSUE THREAD

**Issue by danshapero** [dealii/dealii#4249]
There are several spots where variadic templates could cut down on the code quite a bit. For example, there are several overloads for the constructor of `FESystem`; these could all be replaced with a variadic constructor.

For `FESystem` specifically, this might be best after resolving #4209 , but in any case I'm happy to work on it.

**Comment by bangerth** [comment]
The particular case where variadic templates would be useful is in the `Threads::new_thread()` and `Threads::new_task` functions.

**Comment by drwells** [comment]
See also #2299.
