### ISSUE TITLE
New test failures

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4294]
I get these test failures, likely as a result of #4291 (@danshapero?):
```
        2047 - bits/refine_and_coarsen_for_active_cell_index_05.debug (Failed)
        7882 - serialization/triangulation_01.debug (Failed)
        7884 - serialization/triangulation_02.debug (Failed)
        7906 - sharedtria/tria_load_01.mpirun=2.debug (Failed)
```
The first of these reads as follows:
```
2047: /usr/include/c++/4.8.2/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >]’:                                                                                                  
2047: /usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’           
2047: /usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’                       
2047: /usr/include/c++/4.8.2/bits/stl_vector.h:906:34:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >]’                                                             
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/collections_load_imp.hpp:96:9:   required from ‘typename boost::disable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type boost::serialization::stl::collection_load_impl(Archive&, T&, boost::serialization::collection_size_type, boost::serialization::item_version_type) [with Archive = boost::archive::text_iarchive; T = std::vector<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >, std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > > >; typename boost::disable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type = void]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/vector.hpp:91:57:   required from ‘void boost::serialization::load(Archive&, std::vector<U, Allocator>&, unsigned int, mpl_::false_) [with Archive = boost::archive::text_iarchive; U = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; Allocator = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; mpl_::false_ = mpl_::bool_<false>]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/vector.hpp:159:44:   [ skipping 28 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/detail/common_iarchive.hpp:66:40:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/basic_text_iarchive.hpp:70:9:   required from ‘void boost::archive::basic_text_iarchive<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/text_iarchive.hpp:82:54:   required from ‘void boost::archive::text_iarchive_impl<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/detail/interface_iarchive.hpp:68:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/tests/bits/refine_and_coarsen_for_active_cell_index_05.cc:123:10:   required from ‘void check() [with int dim = 3]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/tests/bits/refine_and_coarsen_for_active_cell_index_05.cc:170:13:   required from here
2047: /usr/include/c++/4.8.2/ext/new_allocator.h:120:4: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = dealii::internal::Triangulation::TriaLevel<3>; _Dp = std::default_delete<dealii::internal::Triangulation::TriaLevel<3> >]’
2047:   { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
2047:     ^
```
I'll look at the others later if nobody beats me to it.

**Comment by bangerth** [comment]
The other test failures are the same -- does anyone else see this as well?

**Comment by danshapero** [comment]
I just ran the first 3 tests on my machine and they all passed, but I'm running gcc-5.4.0 and it looks like you're using 4.8.2. The error message you showed seems to suggest that somewhere in there a unique pointer is being copied, which is of course illegal. I'll install gcc-4.8.2 and try to replicate the problem to see if I can figure out a work-around.

**Comment by danshapero** [comment]
It looks like [this line](https://github.com/dealii/dealii/blob/aa2075a5210de3d33991341aa2fa26e2b0453588/tests/bits/refine_and_coarsen_for_active_cell_index_05.cc#L123) in the test is the source of the trouble. When the triangulation is de-serialized, it tries to fill the vector of unique pointers to the levels objects by copying them instead of moving them. 

[This question](https://stackoverflow.com/questions/13347776/boost-serialization-of-stl-collection-of-std-unique-ptrs) appears to be related.

**Comment by bangerth** [comment]
Ah, yes, indeed, that looks similar. So we'd just have to serialize the vector elements by hand, and then deserialize by hand again later. Not elegant, but possible.

Do you want to give it a try?

**Comment by danshapero** [comment]
I can certainly try. The functions to look at here would be `Triangulation::save` and `Triangulation::load` right? I'm guessing that instead of calling `ar & levels`, you would do something like

    ar & levels.size()
    for (const auto& level: levels)
      ar & *level;

to save. To load, you would read from the archive into a temporary `level` object, then `std::move` the temporary object into the triangulation's vector of pointers to levels. Is that what you mean by serializing/deserializing by hand?

**Comment by bangerth** [comment]
Yes. Though to make reading simpler, I might suggest something along the lines
```
unsigned int size=levels.size();  // make type explicit -- makes re-reading it easier
ar & size;
for (unsigned int i=0; i<levels.size(); ++i)
  ar & levels[i];
```
because this avoids the ambiguity whether `*level` dereferences the iterator or the pointer.

In `load`, you'd do
```
unsigned int size;
ar & size;
levels.resize(size);
for (unsigned int i=0; i<levels.size(); ++i)
  ar & levels[i];  
```
If the last statement doesn't work, then do as you suggest: read it into a pointer that you then move to the correct place.

**Comment by danshapero** [comment]
Alright, I've attempted to manually serialize and de-serialize the triangulation; my code is in a branch [here](https://github.com/danshapero/dealii/tree/tria-unique-ptrs-fixup). It appears to be compiling, so I've eliminated the issue with copying a unique pointer. But I get an exception at runtime when I run the same test:

    refine_and_coarsen_for_active_cell_index_05.release: /home/daniel/programs/dealii/bundled/boost-1.62.0/include/boost/signals2/detail/slot_groups.hpp:80: boost::signals2::detail::grouped_list<Group, GroupCompare, ValueType>::grouped_list(const boost::signals2::detail::grouped_list<Group, GroupCompare, ValueType>&) [with Group = int; GroupCompare = std::less<int>; ValueType = boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(), boost::function<void()> >, boost::signals2::mutex> >]: Assertion `this_map_it != _group_map.end()' failed.

It's related to signals somehow but I can't make heads or tails of what's going on. Everything still works ok on gcc-5.4, this is only with gcc-4.8.5. Thoughts?

**Comment by bangerth** [comment]
For everyone's reference, the relevant patch is here: https://github.com/danshapero/dealii/commit/870725c2837929559044a4fd6382fc6776b1fcf2?w=1

The patch looks correct to me -- I can't spot anything that's obviously wrong. When you run the test in a debugger, where does the error happen? Can you try to get a backtrace? (Also, you show the error in release mode, but does it also happen in debug mode?)

**Comment by tjhei** [comment]
How about (de)serializing the references to the levels instead of the unique_ptrs?

> It's related to signals somehow but I can't make heads or tails of what's going on

I assume we are overwriting memory somehow. does ``valgrind`` say anything?

**Comment by danshapero** [comment]
I'm not having any more luck serializing/deserializing the references to the levels than the pointers to them. Valgrind isn't telling me any more than the error message I posted before. I'll try running it in GDB and see what I turn up.

**Comment by bangerth** [comment]
@danshapero -- can you create a pull request from your current branch? This makes it easy for others to pull the corresponding patch into their own trees to try this out.

**Comment by bangerth** [comment]
(I know that the pull request would not solve the problem, but it would at least make it easy for others to look at it *in their own development environments*.)

**Comment by danshapero** [comment]
@bangerth -- just made the PR. I poked around in GDB some but nothing jumped out at me. I'll keep trying but if someone else fixes it first my pride won't be too wounded :)
