### ISSUE TITLE
MUPARSER_INCLUDE_DIRS do not end up in include flags and muParser.h

### ISSUE THREAD

**Issue by MathiasMen** [dealii/dealii#4317]
Hi everyone,

I just installed `dealii@develop` with spack and wanted to run some tests on my code. Turned out my compiler doesn't find `muParser.h` needed by `deal.II/base/function_parser.h>`. Apparently that header wasn't needed in that specific place until [a recent commit](https://github.com/dealii/dealii/commit/38008cac24658c8eb2bd9a9b34f3a00134955f38) and subsequently I never ran into that problem until now.

I use a CMake-build system where the top-level `CMakeLists.txt` just adds one include-directory of my code, checks for `CMake`-version and `dealii`-version and then runs `DEAL_II_INITIALIZE_CACHED_VARIABLES()`. So I suppose that somehow the include-path for `muParser` isn't set correctly?  

Edit: For what it's worth, before reaching the point where the compiler tries to include `function_parser.h` and then subsequently `muParser.h` it does find some other `dealii` headers - even though I didn't skim through all of the deal-headers I included to check if they in turn rely on some other modules muParser, Trilinos and whatnot.

~ Mathias

**Comment by davydden** [comment]
> So I suppose that somehow the include-path for muParser isn't set correctly?

would be my best guess. It should not be related to your own code, rather deal.II's setup of include flags and https://github.com/dealii/dealii/blob/master/cmake/modules/FindMUPARSER.cmake . 

Can you try compiling in verbose mode and see if there is indeed now include flag for the `muparser` directory?

**Comment by davydden** [comment]
also have a look at `MUPARSER_INCLUDE_DIRS` in `detailed.log` in deal.II's build folder ( you would need to install with `spack install ---keep-stage` to keep the temporary folder after successful build).

**Comment by davydden** [comment]
@tamiko ping.

**Comment by MathiasMen** [comment]
Verbose mode shows no include flag for `muparser`. 

Are you suggesting to keep all the other modules and just do `spack install --keep-stage dealii@develop` (i.e. just installing `dealii` again) or do you want me to do a complete fresh install with all the other modules removed first?

**Comment by davydden** [comment]
> keep all the other modules and just do spack install --keep-stage dealii@develop (i.e. just installing dealii again)

yes, do `spack uninstall dealii` and `spack install --keep-stage dealii@develop`, then check the variable in the log. No need for reinstallation of the whole suite!

**Comment by MathiasMen** [comment]
During the CMake-phase I can see in `spack-build.out` that `DMUPARSER_DIR` is set correctly. 

And further down the line:
```
-- Include /home/mathias/Programs/spack/var/spack/stage/dealii-develop-5hlmjsyoawddznn5wd6xtv5rd25qka5h/dealii/cmake/configure/configure_muparser.cmake
-- Found MUPARSER_LIBRARY
-- Found MUPARSER_INCLUDE_DIR
--   MUPARSER_VERSION: 2.2.5
--   MUPARSER_LIBRARIES: /home/mathias/Programs/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/muparser-2.2.5-okpm5ctmfyexbr56cgwi4waw2pngz2ue/lib/libmuparser.so
--   MUPARSER_INCLUDE_DIRS: /home/mathias/Programs/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/muparser-2.2.5-okpm5ctmfyexbr56cgwi4waw2pngz2ue/include
-- Found MUPARSER
-- DEAL_II_WITH_MUPARSER successfully set up with external dependencies.
```

I guess these would be the paths that end up in the log anyway? If not I'll wait for my machine to finish and report back.

**Comment by davydden** [comment]
> I guess these would be the paths that end up in the log anyway?

correct. 

Then it must be our fault somewhere that makes those `MUPARSER_INCLUDE_DIRS` not appear among in `-I` flags...

**Comment by drwells** [comment]
Relates to #4306: I think we should properly include these paths but #4306 will at least fix this problem.

**Comment by davydden** [comment]
indeed, it should fix this problem. 

But I am still surprised that paths are not included...

**Comment by tamiko** [comment]
Yes, this is the same issue @tjhei was discussing lately. With the MSVC compatibility fixes the muparser header file got included in our headers (#4306). This would make it necessary to install the header files for the bundled version (#4298, which didn't happen so far because we did not need it) and export the header files to `USER_INCLUDE_DIRS` (which hasn't been "fixed").

We decided to undo #4298 and go with #4306 as a cleaner fix - so let's not pollute `USER_INCLUDE_DIR` and wait for #4306.

**Comment by tjhei** [comment]
Sorry, I have been slow to update #4306. I think we can merge it as is and follow it up with code that allows copying of FP objects.

**Comment by davydden** [comment]
@tamiko thanks for the detailed explanation. Now I see why those include paths were not there...

**Comment by davydden** [comment]
@bangerth do you mind merging #4306 as-is?

**Comment by davydden** [comment]
fixed by https://github.com/dealii/dealii/pull/4306
