### ISSUE TITLE
Get rid of PETSC_USE_64BIT_INDICES checks

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4329]
As discussed in #4325, `PetscInt` and `types::global_dof_index` always have the same size (though `PetscInt` is signed), so we do not have to special case things based on the size of one or the other.

**Comment by bangerth** [comment]
Where are the places where we are doing something special?

**Comment by masterleinad** [comment]
It seems `source/lac/petsc_vector_base.cc:1174` is the only place left.

**Comment by drwells** [comment]
I think that these are just leftovers from the days before we supported 64 bit indices.
