### ISSUE TITLE
Modify the p4est build script to include zlib

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4333]
There is a [thread](https://groups.google.com/forum/#!topic/dealii/p-64i1ahEWM) on the mailing list discussing this. We should add a check to our build script to make sure that we really do build p4est correctly.

**Comment by tjhei** [comment]
I did not find a way to make configuration fail if zlib is not present (see discussion in https://github.com/dealii/dealii/issues/4151 ). This means that the only other option is to report an error at the end of the install script.
