### ISSUE TITLE
Issues in copy_petsc_vector

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#4350]
In commit [88b34fd](https://github.com/dealii/dealii/commit/88b34fd76beaa45fc6192018148c5c1d930e781f), @drwells imported a new function [`copy_petsc_vector`](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/vector.templates.h#L102) to generalize the copying operation from PETSc vector to deal.II `Vector`. However, I found two issues in this function:

1. The custom deleter provided to the `unique_ptr` only destroys the `Vec` object, it does not release the memory allocated by `new`. This may cause memory leaks. Am I right?
2. The MPI communicator provided to `VecCreateSeq` can only contain one process. Calling this function on more that one process we will get the following error messages:
    PETSC ERROR: Invalid argument
    PETSC ERROR: Cannot create VECSEQ on more than one process
Also, VecCopy can not be used to copy distributed vector to sequential vector. Maybe we should use a `VecScatter`? PETSc does provide a function named `VecScatterCreateToAll` to copy all values to each processor.

**Comment by drwells** [comment]
It looks like I jumped the gun with the custom deleter: otherwise I just more or less went with the present implementation of the function. I will take a look at this today or tomorrow and try to fix things.

**Comment by drwells** [comment]
@adamqc Just so you know, merging #4354 (since it includes the string "closes #4350") will automatically close this: we don't have to manually intervene.
