### ISSUE TITLE
New improved CUDA functionality in CMake 3.8

### ISSUE THREAD

**Issue by kalj** [dealii/dealii#4361]
As recently announced [here](https://blog.kitware.com/cmake-ups-support-for-popular-programming-languages-in-version-3-8/), the new 3.8 release of CMake has better support for CUDA. This comes in the form of 
* a) Improvements to the existing interface. E.g. `SET_PROPERTY` now works (fixing [this bug](https://gitlab.kitware.com/cmake/cmake/issues/16401)). This means that `DEAL_II_SETUP_TARGET` now works also for `.cu` files. This makes our lives easier inside the library, but also greatly simplifies how a user would write a CUDA/Deal.II application. See https://github.com/dealii/dealii/pull/3785#issuecomment-272415881 and  #2594
* b) Addition of CUDA as a first-class language like C++ and Fortran. This means that `FindCUDA` and the custom macros like `CUDA_ADD_EXCEUTABLE` are not needed anymore. We can just do `enable_language(CUDA)` and then let file endings decide the rest.

The problem is of course that this requires CMake version 3.8, which is not included in any major Linux distribution yet. This probably makes it unrealistic to require 3.8 for the whole library. If we still want to start utilizing this now, I guess the main option is to make CMake 3.8 a requirement for the CUDA functionality -- you're fine without it as long as `DEAL_II_WITH_CUDA=OFF`. The CUDA functionality is pretty experimental at this point anyways. Is this a possibility?

( @tamiko, @Rombur )

BTW, can someone add the GPU tag?

**Comment by Rombur** [comment]
I think that's fine. We are not going to break anyone's code. If there is a way to require CMake 3.8 only when `DEAL_II_WITH_CUDA=ON`, we should do it.

**Comment by davydden** [comment]
> The problem is of course that this requires CMake version 3.8

I agree with @Rombur , we should just require `CMake 3.8` or newer when `DEAL_II_WITH_CUDA=ON`.

**Comment by oneliefleft** [comment]
I think that's fine. We are not going to break anyone's code. If there is a
way to require CMake 3.8 only when DEAL_II_WITH_CUDA=ON, we should do it.

Yes, I agree. That is the definitive way forward. :-)

**Comment by bangerth** [comment]
The top of `$ROOT/CMakeLists.txt` already looks like this:
```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.12)

#
# We support all policy changes up to version 3.1.0. Thus, explicitly set
# all policies CMP0001 - CMP0054 to new for version 3.1 (and later) to
# avoid some unnecessary warnings.
#
IF( "${CMAKE_VERSION}" VERSION_EQUAL "3.1" OR
    "${CMAKE_VERSION}" VERSION_GREATER "3.1" )
  CMAKE_POLICY(VERSION 3.1.0)
ENDIF()
```

I suspect you could do something like this on top:
```
  IF (${DEAL_II_USE_CUDA} == "ON")
    CMAKE_MINIMUM_REQUIRED(VERSION 3.8)
  ENDIF()
```

One could also put this into the CUDA configuration stuff, but that means that one might only get the error message about a too-old cmake version half-way through configuration.

**Comment by tamiko** [comment]
@bangerth 
```
  IF (${DEAL_II_USE_CUDA} == "ON")
    CMAKE_MINIMUM_REQUIRED(VERSION 3.8)
  ENDIF()
```
That won't work so early on in the configuration. Let's simply fatal_error the moment cuda is configured and the cmake version is too old.

@kalj 
That sounds like we can finally sanitize the cuda stuff a bit. The current solution is a bit too intrusive for my taste. :-)

**Comment by kalj** [comment]
Thanks all for the response. I will look into how we can add the requirement, and what it lets us simplify.
