### ISSUE TITLE
Compile deal.II with PGI

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#4363]
PGI made their compilers and their other tools (including their parallel debugger) free. This is particularly interesting for CUDA because with PGI, you can run CUDA code even with you don't have access to a GPU. The CUDA kernels are parallelized using OpenMP instead. So this would allow us to run the CUDA code on the tester (of course it won't help us if we try to access the device memory from the host).

**Comment by kalj** [comment]
Oh, that's interesting! Not super surprising also since Nvidia owns PGI. I guess it would also be interesting to offer both NVCC and PGI as options for device-native compilation. I don't find any details on how Cmake plays with that though. It would be unfortunate and a step backwards if we would have to go all manual again now that cmake offers this more automatic way. #4361

**Comment by Rombur** [comment]
I played with PGI this week end but I can't get boost to compile (bundled or manual install). A bug report has been open (https://svn.boost.org/trac/boost/ticket/11868) so hopefully they will fix it.

**Comment by davydden** [comment]
> https://svn.boost.org/trac/boost/ticket/11868

"Opened 17 months ago", sure the link is right?

**Comment by Rombur** [comment]
Well I get the same problem, so I didn't open a new one.

**Comment by davydden** [comment]
> Well I get the same problem, so I didn't open a new one.

i see, then i guess we should not have high hopes for it be fixed any time soon...

**Comment by masterleinad** [comment]
@Rombur I just used the [configure script](http://www.boost.org/doc/libs/1_64_0/libs/config/doc/html/index.html#boost_config.configuring_boost_for_your_platform.using_the_configure_script).

This is the resulting `user.hpp`:
> //
> //  Use this file to define a site and compiler specific
> //  configuration policy, this version was auto-generated by
> //  configure on Sat May 13 15:13:31 CEST 2017
> //  With the following options:
> //    CXX      = mpicxx
> //    CXXFLAGS = -I./../.. -I./../../libs/config/test -g -O2 -DBOOST_NO_CONFIG
> //    LDFLAGS  = 
> //    LIBS     = -lrt -lm -lpthread 
> //
> 
> // define this to disable all config options,
> // excluding the user config.  Use if your
> // setup is fully ISO complient, and has no
> // useful extentions, or for autoconf generated
> // setups:
> #ifndef BOOST_NO_CONFIG
> #  define BOOST_NO_CONFIG
> #endif
> 
> 
> // define if you want to disable threading support, even
> // when available:
> // #define BOOST_DISABLE_THREADS
> 
> // define if you want the regex library to use the C locale
> // even on Win32:
> // #define BOOST_REGEX_USE_C_LOCALE
> 
> // define this is you want the regex library to use the C++
> // locale:
> // #define BOOST_REGEX_USE_CPP_LOCALE
> 
> 
> //
> // options added by configure:
> //
> #define BOOST_MSVC6_MEMBER_TEMPLATES
> #define BOOST_HAS_VARIADIC_TMPL
> #define BOOST_HAS_UNISTD_H
> #define BOOST_HAS_TR1_COMPLEX_INVERSE_TRIG
> #define BOOST_HAS_TR1_COMPLEX_OVERLOADS
> #define BOOST_HAS_STDINT_H
> #define BOOST_HAS_STATIC_ASSERT
> #define BOOST_HAS_SIGACTION
> #define BOOST_HAS_SCHED_YIELD
> #define BOOST_HAS_RVALUE_REFS
> #define BOOST_HAS_PTHREADS
> #define BOOST_HAS_PTHREAD_YIELD
> #define BOOST_HAS_PTHREAD_MUTEXATTR_SETTYPE
> #define BOOST_HAS_PARTIAL_STD_ALLOCATOR
> #define BOOST_HAS_NRVO
> #define BOOST_HAS_NL_TYPES_H
> #define BOOST_HAS_NANOSLEEP
> #define BOOST_HAS_LONG_LONG
> #define BOOST_HAS_GETTIMEOFDAY
> #define BOOST_HAS_DIRENT_H
> #define BOOST_HAS_CLOCK_GETTIME
> #define BOOST_NO_MS_INT64_NUMERIC_LIMITS
> #define BOOST_NO_CXX17_STD_INVOKE
> #define BOOST_NO_CXX17_STD_APPLY
> #define BOOST_NO_CXX14_VARIABLE_TEMPLATES
> #define BOOST_NO_CXX14_DECLTYPE_AUTO
> #define BOOST_NO_CXX11_HDR_ATOMIC

**Comment by masterleinad** [comment]
At the moment I am only getting some linker errors when building the examples.

**Comment by Rombur** [comment]
@masterleinad I didn't try that. I was able to compile part of boost but not the serialization library which we need.

**Comment by masterleinad** [comment]
See also #4397.

**Comment by masterleinad** [comment]
The linker errors I am getting are:
>../lib/libdeal_II.g.so.9.0.0-pre: undefined reference to \`__atomic_add_fetch_4'
>../lib/libdeal_II.g.so.9.0.0-pre: undefined reference to \`__atomic_thread_fence'
>../lib/libdeal_II.g.so.9.0.0-pre: undefined reference to \`__atomic_sub_fetch_4'
>../lib/libdeal_II.g.so.9.0.0-pre: undefined reference to \`nans'
>../lib/libdeal_II.g.so.9.0.0-pre: undefined reference to \`__atomic_load_4'

**Comment by Rombur** [comment]
Can you try to recompile without multithreading? I would think that we don't need atomic if we have only one thread...

**Comment by bangerth** [comment]
Which system library are these functions defined in? I would think that for gcc, these are in some libgcc.a or libgcc.so...

**Comment by Rombur** [comment]
@masterleinad The configure script that you used is only for the header files `This configure script only sets up the Boost headers for use with a particular compiler. It has no effect on Boost.Build, or how the libraries are built. ` but we use boost serialization that needs to be built. So you are probably using an hybrid install of boost where the built part used gcc. That would explain why you get linker errors.

**Comment by masterleinad** [comment]
That might be true... Unfortunately, I don't have time to play with this at the moment. I will try again in about two weeks.

**Comment by Rombur** [comment]
By replacing `pgCC` by `pgc++`, I can actually compile part of boost but only as a static library. The only library that we use that I can't compile is `serialization` where I hit an internal error. However, I feel like `serialization` is not the most important functionality. I will try to deactivate `serialization` and see what I get.

**Comment by davydden** [comment]
this might solve the problems with boost + PGI https://github.com/LLNL/spack/pull/4426  but i have not tried.

**Comment by drwells** [comment]
If someone is interested in using PGI then they should take this over, but we have gone in a different direction with our CUDA wrappings.
