### ISSUE TITLE
Broken image links in documentation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#439]
The pictures showing the shape functions for FE_Q and FE_Q_Heirachical appear not to be linked correctly in either 8.2.0 or devel.
Examples of the links in question:
http://www.dealii.org/images/shape-%20%20functions/lagrange/Q3/Q3_shape0000.png
http://www.dealii.org/images/shape-%20%20functions/hierarchical/Q2/Q2H_shape0003.png

**Comment by kronbichler** [comment]
This is very likely because of the wrapcomments.py that was run over fe_q.h, since the link results in a line break at "shape-functions". Anyone who can formulate a separate rule for this?

**Comment by bangerth** [comment]
@tjhei ?
