### ISSUE TITLE
Precompiled headers and unity builds

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4392]
@gassmoeller did some interesting experiments in ASPECT with pre-compiled headers and combining source files for compilation (see https://github.com/geodynamics/aspect/pull/1473) that show large (factor of 2 and more!) speedups in compile time (see
https://github.com/geodynamics/aspect/issues/1491).

We may want to try at least the precompiled headers in deal.II as well. Combining source files may or may not be worth it, given that we already have some very large files.

**Comment by drwells** [comment]
I have set up some instrumentation for profiling our build locally (which I used, e.g., to measure performance when writing #4383).

The last time I checked `ninja` would not track memory usage, which I want to measure, so I start by wrapping compilers with calls to `/usr/bin/time`:

```bash
export CXX=time-cxx.sh
export CC=time-cc.sh
```

```sh
#!/bin/sh
# time-cxx.sh
/usr/bin/time -v g++ ${1+"$@"}
```

```sh
#!/bin/sh
# time-cc.sh
/usr/bin/time -v gcc ${1+"$@"}
```

save the build output via `make -j1 $target 2>&1 | tee build-log.txt` and then run

```python
#!/usr/bin/env python

import re

class CompilationInstance(object):
    def __init__(self, file_name, memory_usage, wall_time):
        self.file_name = file_name
        self.memory_usage = memory_usage
        self.wall_time = wall_time


count = 0
instances = list()
with open("build-log.txt", 'r') as log_handle:
    while True:
        current_line = log_handle.readline()
        count += 1
        if len(current_line) == 0:
            break # empty string means we are done
        re_result = re.search("Command being timed:", current_line)

        if re_result:
            # throw out the last '"' and the '\n'
            file_name = None
            terms = current_line[:-2].split()
            for term in terms:
                if term[-4:] == ".cpp" or term[-3:] == ".cc" or term[-2:] == ".h":
                    file_name = term
                    prefixes = ["/home/drwells/Documents/Code/CPP/dealii-dev/" + p
                                for p in ["source/", "examples"]]
                    for prefix in prefixes:
                        if file_name.startswith(prefix):
                            file_name = file_name[len(prefix):]

            # now that we have the file name, get the wall time and memory usage
            if file_name is not None:
                for _ in range(3): # skip three lines
                    log_handle.readline()
                    count += 1
                current_line = log_handle.readline()[:-1]
                count += 1
                str_wall_time = current_line.split()[-1]
                seconds = float(str_wall_time[-5:])
                minutes = float(str_wall_time[:str_wall_time.find(':')])
                wall_time = minutes*60 + seconds

                for _ in range(4): # skip four lines
                    log_handle.readline()
                    count += 1
                current_line = log_handle.readline()[:-1]
                count += 1
                memory_usage = float(current_line.split()[-1])/1024
                instances.append(CompilationInstance(file_name, memory_usage, wall_time))

# Sort by memory...
instances.sort(key=lambda a: a.memory_usage)
print("{:>45} {:>10} {:>10}".format("File name", "Memory, MB", "Time, s"))
for index in range(max(-60, -len(instances)), 0, 1):
    instance = instances[index]
    print("{:>45} {:>10} {:>10}".format(instance.file_name, int(instance.memory_usage), int(instance.wall_time)))

print("\n\n\n")
# and by wall time.
instances.sort(key=lambda a: a.wall_time)
print("{:>45} {:>10} {:>10}".format("File name", "Memory, MB", "Time, s"))
for index in range(max(-60, -len(instances)), 0, 1):
    instance = instances[index]
    print("{:>45} {:>10} {:>10}".format(instance.file_name, int(instance.memory_usage), int(instance.wall_time)))
```

to print out the most expensive files.

**Comment by drwells** [comment]
The profiling indicates that files in `base` are relatively quick to compile. I tried concatenating all source files in that directory into either one or two 'unity' files and observed the following (memory should be interpreted as a 'high water mark'):

master branch:
debug: 144s, 700 MB
release: 145s, 0.6 GB

Unity build with one file:
debug: 74s, 3 GB memory
release: 75s, 2 GB memory

Unity build with two files:
debug: 78s, 2 GB memory
release: 79s, 1.3 GB memory

I think two files is probably the sweet spot if we want to do this since our goal is to keep GCC memory usage at under 2 GB per process.

**Comment by bangerth** [comment]
Nice -- a factor of 2 makes a difference. The question is how to do this across all directories.

**Comment by drwells** [comment]
It is worth noting that some of our files are extremely expensive to compile while most are cheap. Here are two plots of sorted build times for every (all 650) file we compile:

y axis is time:
![sorted-file-build-time-linear](https://cloud.githubusercontent.com/assets/3917035/26064837/1f1f3cc6-3960-11e7-8d77-8706f1777eba.png)

y axis is log10 of time
![sorted-file-build-time-log](https://cloud.githubusercontent.com/assets/3917035/26064844/2394e4a4-3960-11e7-8c49-a7b0d9c03e2d.png)

The 50 most expensive files require about one-third of the total build time so there are some limits to the improvements we can get by concatenating things together.

**Comment by bangerth** [comment]
I guess that means that it would make sense to compile the bottom 90% of files combined into bigger units. But how do we make that happen without getting any of the bigger files into the picture?

**Comment by drwells** [comment]
A possible way to do this would be to generate lists of files from profiling information which fall below certain threshholds of memory and time usage and then create a small number of unity files for each directory (two or three). Ultimately this is going to require some manual intervention. We don't add new files that often so I don't think that that should necessarily stop us.

**Comment by tamiko** [comment]
Personally, I would like to see rather smaller compilation units than us manually combining code to bigger ones.

Regarding cotire, I have no problems adding support for it - but I hate bundling. Especially given the fact that the cotire script is roughly 60% of the size of all our cmake scripts combined...

So if we decide to support it I suggest the following:
Add a .gitmodules file for our code gallery (we should have done that ages ago) and for the github cotire project. Further, add necessary hooks to our object targets (very few lines of code).

But all in all, results aren't that great:
 - without cotire: ninja  13744.04s user 547.35s system 4205% cpu 5:39.81 total
 - with cotire: ninja  13683.20s user 576.36s system 4250% cpu 5:35.50 total and roughly 1k warnings

**Comment by drwells** [comment]
That's pretty disappointing performance from cotire. The manual approach I wrote up performs better:

* make -j10  8299.72s user 184.46s system 758% cpu 18:38.12 total (with ad-hoc unity build files)
* make -j10  9655.50s user 236.22s system 770% cpu 21:23.49 total (master)

I'll put the patch up at some point today, but all that I did was add new `unity.cc` files that `#include` other `.cc` files.

Our main problem, and the reason I don't think unity builds will provide the massive speedups some projects get, is the instantiation files that require compiling functions for 12 DoFHandlers times 15 vectors: those are going to take a lot of time to compile regardless of any other tricks we use.

**Comment by bangerth** [comment]
It may very well be that this doesn't yield what it yields for ASPECT. ASPECT certainly instantiates the same functions far fewer times (twice each, to be exact) and consequently the overhead of parsing is much higher in ASPECT than it is in deal.II.

I think it was worth trying out, though. Should we just close the issue, given that it isn't as useful here?

**Comment by drwells** [comment]
Hm. I would still like to write up what I have and do a few more measurements before canning this.

**Comment by gassmoeller** [comment]
Interesting that the improvements for deal.II seem to be so much smaller. I guess this means ASPECT actually spends all of the parsing time inside of deal.II's header files.
It might be interesting to let cotire also precompile deal.II internal headers. This would need to be redone every time one of them changes, but given the long overall compile time this still might pay off.
@tamiko: Did you get the results you posted above by only activating cotire in CMakeLists (= precompiling headers outside of the deal.II project), or did you compile a unity build by running `make deal_II_unity` or similar? Also has one of you a working branch that includes the cotire script? I gave it a try today, but it seems like it does not pick up the external header files correctly, or I just did something wrong.

**Comment by tamiko** [comment]
> Interesting that the improvements for deal.II seem to be so much
> smaller. I guess this means ASPECT actually spends all of the parsing
> time inside of deal.II's header files.
> It might be interesting to let cotire also precompile deal.II internal
> headers. This would need to be redone every time one of them changes,
> but given the long overall compile time this still might pay off.
> @tamiko: Did you get the results you posted above by only activating
> cotire in CMakeLists (= precompiling headers outside of the deal.II
> project), or did you compile a unity build by running `make
> deal_II_unity` or similar? Also has one of you a working branch that
> includes the cotire script? I gave it a try today, but it seems like
> it does not pick up the external header files correctly, or I just did
> something wrong.

Before we jump to conclusions - I am not claiming that I set up
everything correctly.

I will push my quick hack to a branch for further experimentation.

This was without a unity build - maybe this helps a bit.

**Comment by drwells** [comment]
Do we still want to look at precompiled headers? Otherwise this should be closed.

**Comment by bangerth** [comment]
I tend to think that precompiled headers are such a headache. Let's not worry about this and just close the issue.
