### ISSUE TITLE
CUDA support for matrix-free

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#4399]
This is the work left for CUDA support of matrix-free (superseed #2595 and #3332):
 - [ ] add support for constraints and add missing `matrix_vector` tests
 - [ ] use a template parameter instead of macro to define the size of `__constant__ double global_shape_xxx`
 - [ ] support number of quadrature point different than `fe_degree+1`
 - [ ] implement more variants to compute the tensor kernel (right now there is only the general version)
 - [ ] implement `CUDAWrappers::Point`
 - [ ] `FEEvaluation::get_/submit_gradient` can be optimized if the mesh is uniform
 - [x] have `CUDAWrappers` function to show up in doxygen
 - [x] add documentation on how to configure deal.II with CUDA support (minimum version of CUDA, minimum compute capabilities, etc.)
 - [ ] add support for multiple components FE
 - [ ] use similar optimizations as the ones done in #4111
 - [ ] add MPI support
 - [ ] add a simple tutorial solving Laplace equation with MPI
 - [ ] add support for atomic instead of coloring

**Comment by davydden** [comment]
one more TODO "add a simple tutorial solving Laplace equation with MPI"?

**Comment by Rombur** [comment]
@davydden good idea, I have added it. If you think about something else, feel free to edit my post.

**Comment by kalj** [comment]
@Rombur About item 2, can we really do that? The constant memory arrays must be declared like global arrays (although they are fundamentally a custom thing), and there the size must be a literal / macro, right?

**Comment by Rombur** [comment]
@kalj I was thinking of using something like a singleton pattern but maybe you can't. I haven't thought about it too much.

**Comment by Rombur** [comment]
Superseeded by #7037
