### ISSUE TITLE
CUDA_TOOLKIT_ROOT_DIR not found or specified

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4400]
this is being printed for me almost dozens of time during `make setup_tests` on the current `develop`.

p.s. i wiped the build folder but the issue is still there...

**Comment by tamiko** [comment]
@davydden Guess you have to install cuda now :-P


This was introduced in 109e139589a57bca650d044d83e53d806bc8cb6a:
```
@@ -240,9 +249,14 @@ MACRO(DEAL_II_ADD_TEST _category _test_name _comparison_file)
           OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${_target}/interrupt_guard.cc
           COMMAND touch ${CMAKE_CURRENT_BINARY_DIR}/${_target}/interrupt_guard.cc
           )
+        
+        FIND_PACKAGE(CUDA)
+        CUDA_INCLUDE_DIRECTORIES("${DEAL_II_INCLUDE_DIRS}")
+        CUDA_WRAP_SRCS( ${_target} OBJ _generated_files ${_source_file} )
 
         ADD_EXECUTABLE(${_target} EXCLUDE_FROM_ALL
-          ${_test_name}.cc
+          ${_generated_files}
+          ${_source_file}
           ${CMAKE_CURRENT_BINARY_DIR}/${_target}/interrupt_guard.cc
           )
```
@Rombur, please add a configure guard (using `DEAL_II_WITH_CUDA`) around the include?

**Comment by drwells** [comment]
#4402 did not completely fix this: I still see `CUDA_TOOLKIT_ROOT_DIR not found or specified` printed out while processing each test setup file.
