### ISSUE TITLE
Make `parse_input` behave like the old `read_input`

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#4408]
The following test
~~~
#include <deal.II/base/parameter_handler.h>

using namespace dealii;

int main()
{
    ParameterHandler prm;
    prm.declare_entry("Test", "0", Patterns::Double());
    prm.parse_input("testfile.prm”);
    return 0;
}
~~~
(correctly) throws with this exception:
~~~
 --------------------------------------------------------
An error occurred in line <196> of file </Users/heltai/dealii/dealii/source/base/path_search.cc> in function
    std::string dealii::PathSearch::find(const std::string &, const char *)
The violated condition was: 
    false
Additional information: 
    The file "testfile.prm" was not found in the path for files of class PARAMETERS.
--------------------------------------------------------

The program has unexpectedly finished.
~~~

In deal.II <= 8.5.0 we used to have `read_input` which in this case would generate a file containing the default parameters. This function has been deprecated in favour of `parse_input`, and we no longer have a way to parse+generate a default file at the same time.

I think we should revert `read_input` and no longer have it deprecated, or alternatively have this function behave like the old one. This was a useful function to have. What do people think?

**Comment by bangerth** [comment]
We discussed this at the time and came to the conclusion that the "unexpected side effect" of creating the file was not desirable, in particular in cases where a user may have simply misspelled the name of the input file.

The functionality of creating the file if it can't be found dates from a time when we still believed that functions can "guesstimate" what a user may have wanted to happen if the input arguments don't "quite" make sense (as in the case of a name of a file that doesn't exist). We've later learned that these approaches don't generally work all that well and have switched to just aborting (or throwing an exception) in cases where input arguments to functions are invalid. Users can always catch the exception and do what *they* want the right semantics to be. In your case, you'd do
```
retry:
  try
  {
     prm.parse_input();
  }
  catch (Exc....)
  {
     prm. ...  // write the file with all default values
     goto retry;
  }
```

**Comment by drwells** [comment]
It might be a good idea to resurrect part of the documentation for `read_input` to explain this. We used to have the following function signature:

```cpp
  /**
   * Read input from a file the name of which is given. The PathSearch class
   * "PARAMETERS" is used to find the file.
   *
   * Unless <tt>optional</tt> is <tt>true</tt>, this function will
   * automatically generate the requested file with default values if the file
   * did not exist. This file will not contain additional comments if
   * <tt>write_stripped_file</tt> is <tt>true</tt>.
   *
   * If non-empty @p last_line is provided, the ParameterHandler object
   * will stop parsing lines after encountering @p last_line .
   * This is handy when adding extra data that shall be parsed manually.
   *
   * @deprecated This function has been deprecated in favor of the replacement
   * ParameterHandler::parse_input, which raises exceptions to indicate errors
   * instead of returning an error code. ParameterHandler::parse_input does
   * not have the capability to write default values to a file on failure: if
   * you wish to duplicate that old behavior then you should catch the
   * PathSearch::ExcFileNotFound exception and then call
   * ParameterHandler::print_parameters.
   */
  virtual bool read_input (const std::string &filename,
                           const bool optional = false,
                           const bool write_stripped_file = false,
                           const std::string &last_line = "") DEAL_II_DEPRECATED;
```

which explains how to obtain the old behavior.

**Comment by luca-heltai** [comment]
@drwells :  a function with such a signature no longer exists. The signature of  `parse_input`  is different. We have simply removed a (useful, IMHO) functionality, by deprecating a function that is used in at least 50-60 projects (all my projects, all of my students' projects, etc.).

The idea behind that function was clear. I would agree with @bangerth, if the "unexpected side effect" was unwanted. But, as the documentation resurrected by @drwells shows, this was *not* unexpected, since one had to forcibly change the default behaviour (setting `optional` to `true`) in order to have the file written in case it was not there.

If the return code is what you wanted to avoid (as the deprecation warning assert in the resurrected documentation), then maybe it would have been enough to maintain the same signature for the function with the exception of the return type, and throw in case of errors.

**Comment by bangerth** [comment]
I think the reason for removing the functionality was more along the lines of "the old functionality tried to figure out what a user may have wanted to happen", but I find that something that's in general hard to do. In this particular case, the only indication a user got that a file didn't exist was a message to the screen -- but that's easy to miss if a lot of output is produced or if one submits jobs via a batch system. It may be that the user really wanted the file to be created, but it could also just have been that the name of the input file was misspelled on the command line.

I think of this issue in the same way as someone trying to write into an element of a vector that is past the end (think of `std::vector` for the moment). Should this be an error? Should we assume that the user really wanted to extend the vector by as many elements as is necessary to make the write valid? We can speculate and try to implement something that seems "sensible". Or we can just ask the programmer to be explicit about these things.

In your case, you can use the `try-catch` clause I mentioned earlier, or maybe easier:
```
  std::string filename = ...;
  if (fexists(filename))
    prm.parse_parameters(filename);
  else
    // create a file with default values; just use these default values after that
    prm.print_parameters(filename);
```

**Comment by drwells** [comment]
@luca-heltai I believe you may have misread the documentation: the *default* behavior is to write a parameter file with default values if a file with the given name cannot be found.

Regardless, I did not realize that there were so many projects using this. I believe @bangerth and I are in agreement that we should not try to second-guess what the user wanted but, if there are a lot of people depending on this functionality, then I think it would be fair to provide a wrapper function that executes the old, default behavior in the case that the file could not be located.

**Comment by luca-heltai** [comment]
Maybe it's just that I tend to be a lazy person, but now you are forcing every user to do as you suggested. This, by the way, is never done in the examples, so no one has ever seen this before.
~~~
std::string filename = ...;
  if (fexists(filename))
    prm.parse_parameters(filename);
  else
    // create a file with default values; just use these default values after that
    prm.print_parameters(filename);
~~~
of course it is a small change, and I already made a replacement function for this into our framework. Maybe a better choice could have been to change the default behaviour (se we don't guess by default) and to throw instead of returning a bool...

**Comment by bangerth** [comment]
> Maybe a better choice could have been to change the default behaviour (se we don't guess by default) and to throw instead of returning a bool...

Yes, we should have made this choice 19 years ago: not guess by default but throw. I think that was a mistake, and the change from `read_parameters` to `parse_parameters` fixed that mistake. I think what I'm resisting is the temptation to re-introduce the mistake for convenience

**Comment by drwells** [comment]
I am not sure how to proceed with this issue. I think that we all agree that the default should be to raise an exception if the file we are trying to parse does not exist. Should we add another function that explicitly fills in the default parameter values if the `prm` file does not exist? I must admit that I would not use such a function but if there is a use case then we should consider it. Alternatively, should we, as @luca-heltai suggested, document how to get around this by adding his example to the `ParameterHandler` documentation?

**Comment by tamiko** [comment]
The only standard compliant way I see is something on the line
```
if (!std::ifstream(filename)) {
  std::ofstream file(filename);
  prm.print_parameters(
      file, dealii::ParameterHandler::OutputStyle::Text);
}
```
Or am I missing something?

**Comment by luca-heltai** [comment]
I agree on updating the documentation. As soon as that is done, I'll close the issue.

:)
