### ISSUE TITLE
Should exception call MPI_Abort to avoid deadlock?

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#4411]
In geodynamics/aspect#1753 we ran into an issue with the current implementation of the Exception class. If processes are still involved in MPI communication when triggering an exception, the call to `std::abort` in base/exceptions.cc:415 can lead to a deadlock with other processes waiting for communication. Instead we should probably call `MPI_abort()` if `DEAL_II_WITH_MPI` is set. The exception class however does not know which MPI_Communicator to kill. Would `MPI_COMM_WORLD` work?

**Comment by bangerth** [comment]
Patch in progress
