### ISSUE TITLE
Implement a non-owning wrapper mode for PETScWrappers::MatrixBase

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4419]
This came up on the mailing list: see https://groups.google.com/forum/#!topic/dealii/1HHsnUeJC28. There is currently no good way for us to wrap a `Mat` with our own PETSc matrix classes, but we do support wrapping a `Vec` with `VectorBase`. We should implement similar functionality for `PETScWrappers::MatrixBase`.

**Comment by bangerth** [comment]
@drwells  This is fixed now with @stefanozampini recent changes, right? If so, let's close this issue and tick the second box at the top of #5454.

**Comment by drwells** [comment]
Yes - we've made a huge amount of progress here with Stefano's help. Lets close this as completed.
