### ISSUE TITLE
Issues with tag information and older git versions

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4420]
When I run `cmake` with a relatively old git version (1.8.3.1, the version
shipping with Red Hat 7) I encounter the following error output:

```
-- Include /home/wellsd2/Documents/Code/CPP/dealii-dev/cmake/setup_finalize.cmake
--
-- Include /home/wellsd2/Documents/Code/CPP/dealii-dev/cmake/setup_write_config.cmake
-- Query git repository information.
error: unknown option `sort=-creatordate'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>]
                [<pattern>...]
   or: git tag -v <tagname>...

    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags

Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns

Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object
```

we should just disable tag detection if the current version of git does not support this option.

**Comment by davydden** [comment]
yes, that's part of the `get_latest_tag.sh`, written by @tamiko , that we added in https://github.com/dealii/dealii/pull/4407

@drwells : I think we can just add some switch to this shell script. Can you try figuring out the correct alternative on your Git version?

**Comment by drwells** [comment]
That defaults to `rebase_here`: I don't see an easy fix for this (other than simply using the default ordering of tags in this version of git, which appears to be chronological).

**Comment by davydden** [comment]
> That defaults to rebase_here:

this is a left-over tag in your local repo, see https://github.com/dealii/dealii/pull/4407#issuecomment-303206298

**Comment by davydden** [comment]
> I don't see an easy fix for this (other than simply using the default ordering of tags in this version of git, which appears to be chronological)

can one manually re-order before going to [for loop](https://github.com/dealii/dealii/blob/master/cmake/scripts/get_latest_tag.sh#L11)?

**Comment by davydden** [comment]
btw, looks like `--sort` appeared in `git@2.0`
