### ISSUE TITLE
PETSc: Make solvers respect deal.II's global thread limit

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4425]
I knew it was bad - but I never really looked at it how bad it is.
So this is a testsuite via `cmake -j10` on an otherwise empty machine:

![load](https://cloud.githubusercontent.com/assets/3432917/26529797/b1a59758-438c-11e7-9d58-33317a95ba21.png)

We have to fix that. Problem is that if a test machine runs a concurrent job this excessive load leads to a number of tests failing due to the 10 minute timeout.

**Comment by drwells** [comment]
What exactly does 'load' indicate here?

**Comment by tamiko** [comment]
@drwells The posix "load 1 minute average". I.e. the number of concurrently running tasks exponentially weighted over 1 minute.

**Comment by tamiko** [comment]
I am currently running an adjusted testsuite. ETA 3h.

**Comment by tamiko** [comment]
So I did the following:
 - increased the scheduling weight for an mpi test to n_processes (was n_processes / 2) (I have to check whether this has actually any effect)
 - reduced the global task limit to 2 (instead of 5)
And the result is the same wth?
![load2](https://cloud.githubusercontent.com/assets/3432917/26531695/28c73dce-43b4-11e7-8484-67980f15987d.png)

**Comment by kronbichler** [comment]
Can you spot the parts of the tests that cause these spikes? I could imagine that some tests are not adhering to the global task limit (e.g. by a MPI_InitFinalize that skips the last argument) and rather invoke the default behavior of TBB - not sure how that could happen. Or that your machine uses a multithreaded BLAS which spawns multiple tasks.

**Comment by tamiko** [comment]
@kronbichler The first peak is `mpi/` the others are `pets/`, `trilinos/`, etc. It's mainly mpi processes behaving badly. Further, above testsuite runs are without `--schedule-random`, i.e. close to worst case.

I am surprised that the second run (trying to minimize the badness of MPI tests) did not show any improvement. I would have assumed to see a factor of 2 - 4 in less peak load.

**Comment by kronbichler** [comment]
@tamiko But isn't your last observation [no improvement when increasing MPI factor] suggesting that it is not really the MPI tests? Furthermore, only 32 out of 194 tests in `trilinos` are in fact using `mpirun`, so I'm inclined to think that this must be something else. Multithreaded BLAS that gets invoked by Trilinos (and PETSc)?

**Comment by kronbichler** [comment]
@tamiko The simplest way to test whether it could be an issuie is to `export OMP_NUM_THREADS=1`. I was bitten more than once by BLAS that tried to be clever and spawned 28 threads but ended up making things much worse when the program was nicely parallelized with 28 MPI processes on a higher level.

**Comment by tamiko** [comment]
That's a good point. Let me check what MPI implementation I am actually running.

**Comment by bangerth** [comment]
You can also do `ctest -j1` and see whether you get any spikes. If you have good timing information for the load, then you can go back and look at the timestamp of the executable files to match what is what.

**Comment by tamiko** [comment]
@kronbichler @bangerth Ha! The PETSc solvers happily issue n_cores threads per mpi processes completely trashing the system:

Without limiting `OMP_NUM_THREADS`:
```
Start 711: mpi/periodicity_01.mpirun=3.debug
1/18 Test #711: mpi/periodicity_01.mpirun=3.debug .....   Passed  118.28 sec
```
With setting `OMP_NUM_THREADS=1`:
```
 Start 711: mpi/periodicity_01.mpirun=3.debug
1/18 Test #711: mpi/periodicity_01.mpirun=3.debug .....   Passed   11.77 sec
```

**Comment by tamiko** [comment]
So, what to do about it?
 - Enforce `OMP_NUM_THREADS` in deal.II coupling it to our thread limit?
 - Exporting `OMP_NUM_THREADS` in the testsuite limiting concurrency?

**Comment by kronbichler** [comment]
@tamiko This just confirms my personal opinion is that OpenMP is poorly designed in assuming all threads as available as a default even on large machines - for something that is the de facto standard I would expect a less aggressive behavior. But hey, there must be a reason almost nobody wants to go away from plain MPI...

Regarding the solution, I think we need to export OMP_NUM_THREADS variable to say 2. In order to set the thread limit inside deal.II we must detect and compile with `-fopenmp`, which allows us to include `<omp.h>` and in turn call `omp_set_num_threads(DEAL_II_THREAD_LIMIT)`. Unless somebody wants to use OpenMP for something real, I would not add another probably few hundreds of lines of code to the cmake configuration.

**Comment by tamiko** [comment]
So, exporting `OMP_NUM_THREADS=2` results in

![load3](https://cloud.githubusercontent.com/assets/3432917/26551225/04566f76-4447-11e7-9153-7efa25871f8f.png)

*wow* The significantly smaller load at the end is due to our conservative scheduling of mpi tests (assuming a rather higher computational cost.)

**Comment by tamiko** [comment]
I will do a pull request for this shortly addressing at least the problem with the testsuite.

**Comment by kronbichler** [comment]
The new graph is very nice indeed :+1: 

Is it still with `n_processes / 2` as load factor? I guess that confirms that the settings (now) are correct and we have very reasonable behavior.

**Comment by tamiko** [comment]
It was actually with n_processes as load factor for mpi tests and deal.II threads reduced to 2 (default 5) - I forgot to remove these changes.

I will make a final run with `-j80` and all thread limits set to 2 and with the old cost n_processes / 2.

**Comment by tamiko** [comment]
So, one final boring graph: This is with `-j80` - CPU utilization was within 50-70% during tests, the whole testsuite (compilation + tests) took 35 min. Load is well controlled (first peak is at a maximum of 80 and is during compilation):

![load4](https://cloud.githubusercontent.com/assets/3432917/26553934/75887d72-4453-11e7-8e4e-bfe98bac0536.png)

**Comment by bangerth** [comment]
Nice progress. Where are you going to set `OMP_NUM_THREADS`? I think it should be set outside the executable, either from the place where we describe in cmake what to run for a test, or in the shell script that we use to run an individual test.

**Comment by tamiko** [comment]
And sorting passing tests by time [1] shows only moderate timing regression.

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlypassed&buildid=7588

**Comment by tamiko** [comment]
@bangerth At the moment simply globally. (In a custom worker daemon that is responsible for scheduling testsuite runs. The setup is... fancy.)

**Comment by tamiko** [comment]
@bangerth I was thinking of setting an **undefined** environment variable `OMP_NUM_THREADS` in `void MultithreadInfo::set_thread_limit(const unsigned int max_threads)` to the final value of `n_max_threads` (and keep a defined environment variable untouched).

**Comment by tamiko** [comment]
@bangerth One more :-D With the openmp thread limit in place I had to schedule `-j120` tasks on an 88 core machine to get at least partial saturation - so I guess your `-j60` for 80 cores rule was owed to the very same defect.

By the way: configure 24s, build 5m 36s, tests 25m 6s. \o/

**Comment by bangerth** [comment]
On 05/29/2017 09:36 AM, Matthias Maier wrote:
> @bangerth <https://github.com/bangerth> I was thinking of setting an 
> *undefined* environment variable |OMP_NUM_THREADS| in |void 
> MultithreadInfo::set_thread_limit(const unsigned int max_threads)| to the 
> final value of |n_max_threads| (and keep a defined environment variable 
> untouched).

That seems reasonable.

**Comment by drwells** [comment]
I looked into this and I am not convinced that setting the environment variable in `MultithreadInfo` will help. I read through GCC's implementation of `omp_get_num_threads` et al and the only place that this environment variable is read is in their initialization routine in

https://github.com/gcc-mirror/gcc/blob/6b4236b9779b293054f472f2eab946509d323abe/libgomp/env.c#L1188

which is called before `main`. Perhaps we should export our own environment variable when running the test suite? I don't know of any context in the test suite where we would want to use more than one OMP thread.

**Comment by bangerth** [comment]
I agree with setting the env variable outside the executable (as already stated above).

**Comment by kronbichler** [comment]
I would also vote for setting the environment variable.
