### ISSUE TITLE
Testsuite: fix tests that are running too long

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4427]
The following list are all tests that need more than 30 seconds to run (timing done two times with `-j4` on an 88 threads machine, no other load on the machine)

```
357.673 base/task_09.release
357.670 base/task_09.debug
205.448 mpi/periodicity_01.mpirun=7.release
205.393 mpi/periodicity_01.mpirun=7.debug
200.036 mpi/periodicity_01.mpirun=3.debug
198.821 mpi/periodicity_01.mpirun=3.release
173.471 mpi/periodicity_01.mpirun=5.debug
173.003 mpi/periodicity_01.mpirun=5.release
104.060 trilinos/precondition.debug
102.059 trilinos/precondition.release
72.3967 physics/step-18.debug
70.2204 physics/step-18-rotation_matrix.debug
54.5183 fe/fe_enriched_step-36.debug


42.2088 distributed_grids/3d_coarsening_04.debug
41.7379 fe/fe_nedelec_hessian_divergence_theorem.debug
38.6649 distributed_grids/3d_refinement_08.debug
38.4475 hp/distribute_dofs_linear_time.debug
37.9566 fe/fe_q_3rd_derivative_divergence_theorem.debug
36.4966 physics/step-44-standard_tensors-material_push_forward.debug
35.6598 matrix_free/parallel_multigrid_adaptive_02.mpirun=3.debug
35.1861 trilinos/direct_solver.debug
34.6952 matrix_free/thread_correctness_hp.release
34.4971 matrix_free/parallel_multigrid_adaptive_01.mpirun=3.debug
34.0551 matrix_free/parallel_multigrid_adaptive_03.mpirun=4.debug
33.5820 trilinos/direct_solver.release
33.2929 matrix_free/thread_correctness_hp.debug
33.0325 fe/fe_nedelec_gradient_divergence_theorem.debug
31.0227 matrix_free/parallel_multigrid_mf.mpirun=7.debug
30.9499 matrix_free/parallel_multigrid_adaptive_02.mpirun=3.release
30.6932 matrix_free/parallel_multigrid_02.mpirun=3.debug
30.2899 matrix_free/parallel_multigrid_adaptive_04.mpirun=3.debug
30.1864 matrix_free/parallel_multigrid_adaptive_01.mpirun=3.release
30.0501 matrix_free/parallel_multigrid_adaptive_03.mpirun=4.release
```

For future I suggest the following guideline: A single test should run in under 30 seconds and must not exceed 45 seconds. (Well, for some arbitrary measure of timings...)

Anyway, the following tests have to be fixed:
 - [x] base/task_09
 - [x] mpi/periodicity_01
 - [x] trilinos/precondition
 - [x] physics/step-18.debug
 - [x] physics/step-18-rotation_matrix.debug
 - [x] fe/fe_enriched_step-36.debug

**Comment by davydden** [comment]
> fe/fe_enriched_step-36.debug

that will stay as-is. It's already a cut-down version and it takes a lot due to bad condition number. And to be fair, `54.5183` is not that longer than `30` seconds, suggested above.

**Comment by tamiko** [comment]
@davydden 54s is above the proposed 45s.

**Comment by davydden** [comment]
> 54s is above the proposed 45s.

IMO this is not enough reason to take any actions. YMMW

**Comment by tamiko** [comment]
@davydden IMHO it is.

**Comment by drwells** [comment]
How on does `base/task_09` take your machine nearly six minutes? When I ran it it only took 35 seconds including compilation. All this test does is sleep and check that there is no deadlock.

**Comment by tamiko** [comment]
@davydden Let me expand a bit: If scheduled aggressively™ a single test run can in the worst case 10-15 times longer as above timings this unfortunately brings them very close to the 10 minute test timeout. It gets worse if you do something like `-j80` for the testsuite (with incerdibly high peak-load values). So I would really prefer some better timings for above tests.

**Comment by tamiko** [comment]
@drwells I do not know. I will check later today after brunch.

**Comment by tamiko** [comment]
@drwells Well, just replace the number of threads spawned by 176 and wait forever.

**Comment by tamiko** [comment]
@davydden Ah forgot - it is also only the debug version that has an issue of longer execution time.

**Comment by drwells** [comment]
@tamiko Ah, your machine has 80 cores, so it spends that whole time asleep. I'll write a patch (this is easy to fix).

**Comment by drwells** [comment]
This test seems fundamentally broken. It is trying to test what happens when one creates more tasks then processes but the scheduler seems to just run things in sequence anyway.

**Comment by kronbichler** [comment]
@davydden Given that `fe/fe_enriched_step-36.debug` does take considerably longer than `fe/fe_enriched_step-36.release`, I'm inclined to think that this happens somewhere in our code. If it were mostly a solver issue, the times should be similar because debug and release use the same PETSc infrastructure, don't they? Do you know what is so expensive? Assembly? That should be possible to fix in some way, if you really insist in having the test be as big as it is. Whether it's worth to put several hours of tuning into a test suite optimization is another issue... But it might also be a general inefficiency that is good to fix anyway.

**Comment by davydden** [comment]
> If it were mostly a solver issue, the times should be similar because debug and release use the same PETSc infrastructure, don't they?

yes, the code is equivalent. 

> Do you know what is so expensive? Assembly?

linear solvers are expensive as condition number is bad. Assembly as well, due to rather high number of quadrature points required to have a reasonable integration. But I never run any profiling on the test (or deal.ii's Timers) to see where the time is being spent. Most likely 90% of time is eigensolver.

> Whether it's worth to put several hours of tuning into a test suite optimization is another issue...

That's my point -- i would say no. One can cut down things a bit here and there, probably, but to my knowledge there is no big piece one can remove to suddenly make it run 10 times faster. On another hand, compromising accuracy (like quadrature points), may result in a less stable test which due to under-integration may be accidentally failing on some machines.

**Comment by tamiko** [comment]
@kronbichler For a bit of context why I opened this bug report at all.

Hhave a look at for example [1,2] and have a look at the timings. This is on an otherwise empty host - observe the differences in timings, also observe that we have a class of roughly a dozen "main offenders". Similar results by the way can be found on your machine. :-)

Now I have a new server in Minneapolis were I can use some computational resources to run the deal.Ii testsuite (*yay*). But I am not the only user of that machine - so I promised to run the testsuite with roughly *half* the server load as background task. But that implies that a test can run up to 10 - 15 times slower than on a machine without additional load.

Even without addressing #4425 just fixing above tests would improve the situation a lot. [3,4]

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlypassed&buildid=7563
[2] https://cdash.kyomu.43-1.org/viewTest.php?onlypassed&buildid=7562
[3] And in order to really utilize a many-core setup I have to overcommit the testsuite a bit.
[4] And frankly speaking running a testsuite where a number of tests repeatedly fail due to timeouts isn't what I am going to do.

**Comment by bangerth** [comment]
For the record, I typically run `ctest -j60` on my 80-core machine. That proved to be a reasonably compromise between the run time of the testsuite and the number of timeouts I see if I use a higher load factor.

**Comment by tamiko** [comment]
For `mpi/periodicity` see #4425

**Comment by tamiko** [comment]
@jppelteret *ping* Regarding physics/step-18 tests. :-)

**Comment by tamiko** [comment]
@kronbichler You were the author of `trilinos/precondition`. :-) What about simply splitting in two or three? (For the most part it seems to run sequential but I am a bit surprised to see a regression between my laptop 64s and the server with 100s).

**Comment by kronbichler** [comment]
@tamiko The reason for it being slower is most likely the BLAS implementation that is invoked for the Ifpack block preconditioners.

**Comment by tamiko** [comment]
That's the new timing distribution:
![timing](https://cloud.githubusercontent.com/assets/3432917/26551884/49de2b8a-444a-11e7-8938-df3c2c53fdfe.png)

Only 10 tests above 30 seconds :-)
