### ISSUE TITLE
make user projects know directories of dealii's dependencies

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4434]
In a user code my colleague @BenBrands need to link extra boost libraries, not needed by `deal.II` itself. Currently, `CMake` variables we store do not have any info on directories of dependencies. Only things like `DEAL_II_WITH_BOOST=ON` and `DEAL_II_BOOST_VERSION=1.62.0`. I think we should also store `DEAL_II_<PACKAGE>_DIR=` for such scenarios.  I can imaging the same situation with Trilinos where someone might need to link a Trilinos package/library not used by `deal.II`. 

@tamiko what do you think?

**Comment by tamiko** [comment]
I am not convinced to put that unconditionally into `deal.IIConfig.cmake` in particular because `<FEATURE>_DIR` is merely meant as a hint and might not be populated at all (e.g. if `CMAKE_PREFIX_PATH` is used, or if simply a system wide boost installation is found at a default location). Variables set in `deal.IIConfig.cmake` should be reliable populated and stable.

That said, we already have all of that information available and simply put it into another, namely `detailed.log`. So as a stop gap solution you could simply grep for `BOOST_DIR` in `detailed.log` and use that information to search for boost in the user project.

Further, we can modify `setup_write_config.cmake` to output the stuff written to `detailed.log` also in a cmake comptabile way into an extra configuration file. This would simply make all `<FEATURE>_*` variables available.

**Comment by davydden** [comment]
> Variables set in deal.IIConfig.cmake should be reliable populated and stable.

how about we put there `DEAL_II_BOOST_LIBS=` and `DEAL_II_BOOST_INCLUDE=`, those are set regardless of specifying prefix or picking up system boost, right?

> That said, we already have all of that information available and simply put it into another, namely detailed.log.

it's not being installed, AFAIK.

**Comment by davydden** [comment]
> output the stuff written to detailed.log also in a cmake compatible

that's also a work-around as you can not automate it. I am still in favor of finding a middle ground. Maybe once we got all the libraries (i.e. `BOOST_LIBRARIES` of `detailed.log`), we can populate `DEAL_II_BOOST_DIR`? That's probably set anyway during `FindPackage` call, we just not keep it around, right?

**Comment by tamiko** [comment]
> how about we put there `DEAL_II_BOOST_LIBS=` and
> `DEAL_II_BOOST_INCLUDE=`, those are set regardless of specifying
> prefix or picking up system boost, right?

That might not be sufficient in your case, we only call

  find_package(Boost 1.56 COMPONENTS iostreams serialization system thread)

so `BOOST_LIBRARIES` might not contain the library you need. You should
call find_package(Boost) again in the user project.


>> That said, we already have all of that information available and simply put it into another, namely detailed.log.
>
> it's not being installed, AFAIK.

Well, the idea is to simply put the configuration information that is
currently only available in `detailed.log` [1] into a cmake parsable
file (and of course also install that) alongside
  deal.IIConfig.cmake
  deal.IITargets.cmake

Maybe
  deal.IIFeatureConfig.cmake

(Too tired to think of a good name.)


The file would be handled similarly to deal.IITargets.cmake:

  find_package(deal.II REQUIRED)
  INCLUDE(${DEAL_II_TARGET_CONFIG})  # loads deal.IITargets.cmake

  INCLUDE(${DEAL_II_FEATURE_CONFIG}) # loads deal.IIFeatureConfig.cmake


[1] which is simply all internal information about external dependencies.

**Comment by tamiko** [comment]
> that's also a work-around as you can not automate it. 

That's very automated :-)

Have a look at line 213 and 224 of `setup_write_config.cmake`. Instead of
```
_detailed("#            ${_feature}_DIR = ${${_feature}_DIR}\n")
...
... loop ...
  _detailed("#            ${_feature}_${_var2} = ${${_feature}_${_var2}}\n")
```
we simply output an additional
```
SET(${_feature}_DIR \"${${_feature}_DIR\")
SET(${_feature}_${_var2} \"${${_feature}_${_var2}}\")
```
to a configuration file `deal.IIFeatureConfig.cmake`.

**Comment by davydden** [comment]
> so `BOOST_LIBRARIES` might not contain the library you need. You should

I know. That's what @BenBrands  is doing, calling `find_package` again to add extra libs from boost. But the point is to avoid specifying BOOST_PREFIX and get it from the already installed deal.II.

> the idea is to simply put the configuration information that is
currently only available in `detailed.log` [1] into a cmake parsable
file

> INCLUDE(${DEAL_II_FEATURE_CONFIG}) # loads deal.IIFeatureConfig.cmake

that sounds good to me.


> That's very automated :-)

sure, but i mean if we installed `detailed.log` in its current form, then one has to manually copy-paste the prefix. This, of course, does not apply to `deal.IIFeatureConfig.cmake` you suggest above :smile:

**Comment by tamiko** [comment]
> But the point is to avoid specifying BOOST_PREFIX and get it from the already installed deal.II.

Then we're on the same page.

**Comment by davydden** [comment]
looking at it now...

**Comment by bangerth** [comment]
I do think that #4437 is a nice idea, and be it just so that we can later more easily look up what has happened (in an installed library). But what was wrong with asking users to run `FindPackage(BOOST)` again, with the *additional* libraries they need?

**Comment by davydden** [comment]
> But what was wrong with asking users to run FindPackage(BOOST) again, with the additional libraries they need?

extremely inconvenient. You need to make sure you end up with the same boost. If you have multiple boosts around -- you need to be careful. If boost installed into some prefix, you need to provide it as additional configuration option to the user code and again only hope that it's the same as the one used to build deal.II.

**Comment by tamiko** [comment]
> [...], and be it just so that we can later more easily look up what has happened (in an installed library)

Exactly my thought :-)
