### ISSUE TITLE
base/timer_03.release unstable

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4439]
On a run with slightly higher load [1]:
```
base/timer_03.release: DIFF failed. ------ First 50 lines diff output:
*** /srv/testsuite/dealii/tests/base/timer_03.output	Sat May 27 18:11:26 2017
--- output	Mon May 29 17:05:35 2017
***************
*** 3,8 ****
  DEAL::OK
  DEAL::OK
  DEAL::OK
! DEAL::OK
  DEAL::OK
  DEAL::OK
--- 3,8 ----
  DEAL::OK
  DEAL::OK
  DEAL::OK
! DEAL::Ratio 0.666667 should be 1.00000
  DEAL::OK
  DEAL::OK
```

[1] https://cdash.kyomu.43-1.org/testDetails.php?test=24812856&build=7589

**Comment by class4kayaker** [comment]
I added this test as part of adding the method providing access to the timer data from within the program (#4369). I intended it to mimic timer_01, using a TimerOutput to gather the timing data to confirm both that the timing data gathered was reasonable and that the method was functioning correctly. The particular setup may have been more fragile than I expected, so modification might be necessary.
