### ISSUE TITLE
Timer interface inconsistent: Timer::get_lap_time returns wall time

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4457]
While working on #4456 I ran into a little disagreement with the current timer interface:

```
class Timer {
  /**
   * Access to the current CPU time without disturbing time measurement. The
   * elapsed time is returned in units of seconds.
   */
  double operator() () const;

  /**
   * Access to the current wall time without disturbing time measurement. The
   * elapsed time is returned in units of seconds.
   */
  double wall_time () const;

  /**
   * Return the last lap time; the time taken between the last start()/stop()
   * call.
   */
  double get_lap_time () const;
}
```

 - Improve wording: "without distubing time measurement" - that's actually not true :-)
 - inconsistent naming: `wall_time` versus `get_lap_time`
 - `get_lap_time` returns wall time

At the very least `get_lap_time` should CPU time consistent with `operator()`.

**Comment by tamiko** [comment]
What about deprecating parts of above interface and introducing something like

```
class Timer {
  double operator() (bool get_lap_time = false) const;
  double wall_time (bool get_lap_time = false) const;
  double get_lap_time () const DEAL_II_DEPRECATED;
}
```

**Comment by bangerth** [comment]
I think "without disturbing time measurement" was supposed to mean "without stopping a currently running timer".

I agree that deprecating the oddly named function makes sense. I don't like the addition of the default argument, though. Why not have pairs of functions `wall_time()`/`last_wall_time()` (or with `get_`), etc?

**Comment by tamiko** [comment]
@bangerth Something like
```
wall_time();
last_wall_time();
cpu_time();
last_cpu_time();
operator() // same as cpu_time;
```
?

**Comment by bangerth** [comment]
Sure, that sounds good to me.

**Comment by tamiko** [comment]
@masterleinad You take care of it? Thanks! :-)
