### ISSUE TITLE
Upgrade to astyle 3.0.1

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4471]
@davydden suggested to try astyle 3.0.1 (the current version) in the otherwise unrelated #4466. I experimented a bit with this, and some of the trivial changes it wants to make over 2.04 are in #4470.

Other than that, it gets some cases better than the older version. For example:
```
--- a/tests/aniso/up_and_down.cc
+++ b/tests/aniso/up_and_down.cc
@@ -174,32 +174,32 @@ void test ()
     // elements.
     new FESystem<dim> (FE_DGQ<dim>(1), 2),
     new FESystem<dim> (FE_DGP<dim>(1), 1,
-    FE_DGQ<dim>(2), 2),
+                       FE_DGQ<dim>(2), 2),
     new FESystem<dim> (FE_DGP<dim>(1), 2,
-    FE_DGQ<dim>(2), 2,
-    FE_DGP<dim>(0), 1),
+                       FE_DGQ<dim>(2), 2,
+                       FE_DGP<dim>(0), 1),
     new FESystem<dim> (FE_DGQ<dim>(1), 2,
```
and
```
--- a/tests/fail/circular_01.cc
+++ b/tests/fail/circular_01.cc
@@ -660,46 +660,46 @@ void LaplaceProblem<3>::create_coarse_grid ()
     // points on the lower surface
     Point<dim>(0,  0, -4),
     Point<dim>(std::cos(0*numbers::PI/6),
-    std::sin(0*numbers::PI/6),
-    -4),
+               std::sin(0*numbers::PI/6),
+               -4),
     Point<dim>(std::cos(2*numbers::PI/6),
```
and
```
--- a/include/deal.II/dofs/dof_objects.h
+++ b/include/deal.II/dofs/dof_objects.h
@@ -202,7 +202,7 @@ namespace internal
               ExcInternalError());

       return dofs[obj_index * dof_handler.get_fe()
-                  .template n_dofs_per_object<dim>() + local_index];
+                            .template n_dofs_per_object<dim>() + local_index];
     }
```

But it also has some really odd suggestions where it wants to align things differently under operators. There are many examples of the kind
```
--- a/include/deal.II/dofs/dof_accessor.templates.h
+++ b/include/deal.II/dofs/dof_accessor.templates.h
@@ -1097,8 +1097,8 @@ namespace internal
                               dof_handler.selected_fe->dofs_per_vertex));

         dof_handler.vertex_dofs[vertex_index *
-                                dof_handler.selected_fe->dofs_per_vertex
-                                + local_index]
+                                             dof_handler.selected_fe->dofs_per_vertex
+                                             + local_index]
           = global_index;
       }
```
Note how it tries to align things under and to the right of `operator *` in the first line -- this makes no sense, as it negates the effect of breaking long lines. We would have to go through all of these cases and break the `*` onto the next line by hand -- maybe not a bad idea in itself, but definitely a good deal of work.

Opinions?

**Comment by davydden** [comment]
i like better formatting you show at the top. Things with `operator *` are unfortunate. It might be possible to adjust them as never versions have more flags which specify how things are formatted.

**Comment by bangerth** [comment]
We'd have to find someone who figures out what flags to give...

**Comment by davydden** [comment]
i look through the `doc/astyle.html` and found this:

> --close-templates / -xy
Closes whitespace between the ending angle brackets of template definitions. Closing the ending angle brackets is now allowed by the C++11 standard. Be sure your compiler supports this before making the changes.
 Stack< int, List< int > > stack1;
becomes:
 Stack< int, List< int >> stack1;

but could not find anything to control the dangling operators at the end of lines ;-(

**Comment by bangerth** [comment]
Hm, `--close-templates` is interesting. I tried to run that with 3.0.1 and then change the unrelated indentations back with 2.0.4, but that leads to some changes such as this:
```
@@ -2827,8 +2827,8 @@ namespace Step14
       // Next, an object that describes the dual functional. It is only needed
       // if the dual weighted residual refinement is chosen, and also defaults
       // to a Null pointer.
-      std::unique_ptr<const DualFunctional::DualFunctionalBase<dim> >
-      dual_functional;
+      std::unique_ptr<const DualFunctional::DualFunctionalBase<dim>>
+                                                                  dual_functional;
```
Awkward. How do people feel about `> >` vs `>>`?

**Comment by davydden** [comment]
i would prefer 
```
std::unique_ptr<const DualFunctional::DualFunctionalBase<dim>>
dual_functional;
```

**Comment by bangerth** [comment]
Sure, and 3.0.1 may even give you that, but 2.04 apparently doesn't understand that `>>` is a closing template argument as opposed to `operator>>`.

**Comment by tjhei** [comment]
I am hesitant to change the required astyle version, because this is hand-coded in travis, various docker images of deal.II, candi, and in many derived projects.

If we want to go ahead with this, do we still want to strictly enforce  3.0.1 in case they introduce or fix bugs in later versions?

**Comment by bangerth** [comment]
Yes, I think we need to enforce one version for everyone, in all places.

I think the advantages of upgrading are quite limited -- I'm generally pretty happy with what we've got right now. Let's not bother then -- we can reconsider this issue every few years for newer versions of astyle :-)
