### ISSUE TITLE
Make ParameterHandler::print_parameters() save/restore the stream state

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4503]
As pointed out in #4495, `ParameterHandler::print_parameters()` modifies stream flags but doesn't reset them at the end. Fix this.

**Comment by drwells** [comment]
The preferable way to do this is with `boost::io::ios_flags_saver`, which saves the flags and a pointer to the stream in its constructor and restores the original flags in its destructor.

**Comment by bangerth** [comment]
On second thought, we really only call `std::setw()`, which only applies to the *next* output operation and is then cleared again. So I'm not sure whether there is a bug or not. But it doesn't hurt to add the flag saver -- I just can't seem to find a testcase that would have been wrong before.
