### ISSUE TITLE
mpi/step-39 fails because a Trilinos matrix is copied

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#452]
See
http://cdash.kyomu.43-1.org/testDetails.php?test=4621292&build=2674

I think this is due to a recent change by @tjhei . Failure is like this:

/node/bangerth/trunk/dealii/include/deal.II/lac/trilinos_sparse_matrix.h:1844:5: error: ‘dealii::TrilinosWrappers::SparseMatrix::SparseMatrix(const dealii::TrilinosWrappers::SparseMatrix&)’ is private
/node/bangerth/trunk/dealii/tests/mpi/step-39.cc:566:63: error: within this context

**Comment by tamiko** [comment]
@tjhei:  "Closes #452" only works from within a commit - as far as I recall.
