### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime_clock_gettime

### ISSUE THREAD

**Issue by MollyRaver** [dealii/dealii#4537]
Hi, I was running into the following errors for Step-37

[100%] Run step-37 with Debug configuration
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/opt/libevent/lib/libevent-2.1.6.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/deal.II-8.5-brew.app/Contents/Resources/brew/opt/libevent/lib/libevent-2.1.6.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

make[3]: *** [CMakeFiles/run] Trace/BPT trap: 5
make[2]: *** [CMakeFiles/run.dir/all] Error 2
make[1]: *** [CMakeFiles/run.dir/rule] Error 2
make: *** [run] Error 2

Do you know how to resolve this errors? Thank you very much!

**Comment by drwells** [comment]
I don't have a mac so I am guessing a bit here, but incorrect compilation/linking of UMFPACK sometimes creates errors referencing `clock_gettime` (UMFPACK should be compiled with `-lrt`). I suspect that there is some mismatch between the 8.5 bundle and a copy of UMFPACK installed elsewhere.

@davydden ideas?

**Comment by davydden** [comment]
Frankly I don't have ideas, could be the mismatch between Xcode/macOS used to create the bundle and the one being used

**Comment by drwells** [comment]
@MollyRaver Is this issue specific to step-37? Can you compile and run step-22?

**Comment by kronbichler** [comment]
Could it be related to our timer classes? @MollyRaver if step-22 works, please add a simple `Timer timer;` object somewhere in the code and check again.

**Comment by drwells** [comment]
I don't think we have ever managed to reproduce this. Since macOS changes substantially with each new release I don't believe this is still an issue.
