### ISSUE TITLE
doxygen does not build new changes file

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#4552]
I observed that the deal.II installation does not build the file `changes_after_8_5_0.html` file any more. As a consequence, the link on the homepage (Dev -> Recent changes) to https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_5_0.html is broken. I do not have the time to look into it right now, but it is broken since at least May 27 (that's the last time I have an update on that file for a local documentation build).

**Comment by bangerth** [comment]
I think it is because of this error:
```
/home/bangerth/p/deal.II/1/build-doc/doc/news/changes.h:721: warning: reached end of file while inside a f$ block!
```
I'll look into this tonight if nobody beats me (but have to run now to sell deal.II ;-) ).
