### ISSUE TITLE
I think DoFHandler::renumber_dofs() doesn't work in parallel for multilevel DoFs

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4559]
@tjhei and @kronbichler: This is question for the two of you.

I think that the multigrid version of `DoFHandler::renumber_dofs()` doesn't actually work for parallel triangulations. It says this in the documentation:
```
  /**
   * Renumber degrees of freedom based on a list of new dof numbers for all
   * the dofs.
   *
   * This function is called by the functions in DoFRenumbering function after
   * computing the ordering of the degrees of freedom. This function is
   * called, for example, by the functions in the DoFRenumbering namespace,
   * but it can of course also be called from user code.
   *
   * @arg new_number This array must have a size equal to the number of
   * degrees of freedom owned by the current processor, i.e. the size must be
   * equal to what n_locally_owned_dofs() returns. If only one processor
   * participates in storing the current mesh, then this equals the total
   * number of degrees of freedom, i.e. the result of n_dofs(). The contents
   * of this array are the new global indices for each freedom listed in the
   * IndexSet returned by locally_owned_dofs(). In the case of a sequential
   * mesh this means that the array is a list of new indices for each of the
   * degrees of freedom on the current mesh. In the case that we have a
   * parallel::distributed::Triangulation underlying this DoFHandler object,
   * the array is a list of new indices for all the locally owned degrees of
   * freedom, enumerated in the same order as the currently locally owned
   * DoFs. In other words, assume that degree of freedom <code>i</code> is
   * currently locally owned, then
   * <code>new_numbers[locally_owned_dofs().index_within_set(i)]</code>
   * returns the new global DoF index of <code>i</code>. Since the IndexSet of
   * locally_owned_dofs() is complete in the sequential case, the latter
   * convention for the content of the array reduces to the former in the case
   * that only one processor participates in the mesh.
   */
  void renumber_dofs (const std::vector<types::global_dof_index> &new_numbers);

  /**
   * The same function as above, but renumber the degrees of freedom of a
   * single level of a multigrid hierarchy.
   */
  void renumber_dofs (const unsigned int level,
                      const std::vector<types::global_dof_index> &new_numbers);
```
This would suggest that the `new_numbers` array for the second of the functions is also interpreted with regard to an index set of locally owned DoFs on this level, but reading through the functions in `dof_handler.cc` around line 1230 and following shows that we don't actually reference any such index set -- we just have statements such as
```
  for (std::vector<types::global_dof_index>::iterator i=mg_levels[level]->dof_object.dofs.begin();
       i!=mg_levels[level]->dof_object.dofs.end(); ++i)
    {
      if (*i != numbers::invalid_dof_index)
        {
          Assert(*i<new_numbers.size(), ExcInternalError());
          *i = new_numbers[*i];    // <-------------------- ***
        }
    }
}
```
So I think that (i) the documentation of the function is not correct, and (ii) this doesn't actually work because (iii) one would have to pass in an array of size equal to the *global* number of DoFs, and (iv) the function ignores that some of the elements of the array that we iterate over here may be equal to `numbers::invalid_dof_index` (namely on artificial cells) and so the access `new_numbers[*i]` is invalid.

I'm not looking for a patch, just a confirmation that I'm not on the wrong track here. I have patches in the works that will make that work also in the parallel case but first wanted to hear whether you recalled anything about this.

(I'm going to note on a tangent that the function is specialized only for the `<1,1>`, `<2,2>`, `<3,3>` cases, but not for the codimension cases. Assuming I'm on the right track with my work, this should be fixed as a side product.)

**Comment by bangerth** [comment]
As another data point: I ran the entire testsuite with the patch below that checks that we don't call `renumber_dofs(level,new_indices)` with a parallel triangulation, and there are no test failures. In other words, I don't think this functionality is used anywhere, and so may well be broken.

```
diff --git a/source/dofs/dof_handler.cc b/source/dofs/dof_handler.cc
index 6022ac2..876eef4 100644
--- a/source/dofs/dof_handler.cc
+++ b/source/dofs/dof_handler.cc
@@ -1232,6 +1232,9 @@ template <>
 void DoFHandler<1>::renumber_dofs (const unsigned int level,
                                    const std::vector<types::global_dof_index> &new_numbers)
 {
+  Assert (dynamic_cast<const parallel::distributed::Triangulation<1>*>(&*tria) == nullptr,
+          ExcInternalError());
+  
   Assert(mg_levels.size()>0 && levels.size()>0,
          ExcMessage("You need to distribute active and level DoFs before you can renumber level DoFs."));
   Assert (new_numbers.size() == n_dofs(level), DoFHandler<1>::ExcRenumberingIncomplete());
@@ -1268,6 +1271,8 @@ template <>
 void DoFHandler<2>::renumber_dofs (const unsigned int  level,
                                    const std::vector<types::global_dof_index>  &new_numbers)
 {
+  Assert (dynamic_cast<const parallel::distributed::Triangulation<2>*>(&*tria) == nullptr,
+          ExcInternalError());
   Assert(mg_levels.size()>0 && levels.size()>0,
          ExcMessage("You need to distribute active and level DoFs before you can renumber level DoFs."));
   Assert (new_numbers.size() == n_dofs(level),
@@ -1328,6 +1333,8 @@ template <>
 void DoFHandler<3>::renumber_dofs (const unsigned int  level,
                                    const std::vector<types::global_dof_index>  &new_numbers)
 {
+  Assert (dynamic_cast<const parallel::distributed::Triangulation<3>*>(&*tria) == nullptr,
+          ExcInternalError());
   Assert(mg_levels.size()>0 && levels.size()>0,
          ExcMessage("You need to distribute active and level DoFs before you can renumber level DoFs."));
   Assert (new_numbers.size() == n_dofs(level),
```

**Comment by bangerth** [comment]
For my own recollection -- #4560 moved this code to the policy class, but put an `Assert(false, ExcNotImplemented())` into the `ParallelDistributed::renumber_mg_dofs()` function to indicate that this is not actually implemented. It should be relatively straightforward to actually implement it, using `ParallelDistributed::renumber_mg_dofs()` as a template.

**Comment by tjhei** [comment]
I think you are correct. I found the following in ``dof_handler_policy.cc``:
```
//TODO [TH]: renumber DoFs for multigrid is not done yet
```
;-)

**Comment by bangerth** [comment]
OK, thanks for confirming.

I guess there wasn't much need for this functionality before -- I don't really see why one would need to renumber multilevel DoFs from their default, with the possible exception of the coarsest level. Let me remove the TODO for this reason, unless someone sees compelling reasons to implement multigrid renumbering algorithms that also work in parallel and not only on a single processor.
