### ISSUE TITLE
FullMatrix::reinit(n) -- Killed: 9

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4565]
i noticed that
```
FullMatrix::reinit(1)
```
does not work[1], whereas
```
FullMatrix::reinit(1,1);
```
does. I was trying to dig into `Table<2,...>`'s `reinit` in doxygen, but could not find it. 

Regardless, since there is a constructor `FullMatrix(n)` for square matrices, then i think we should also make `reinit(n)` behave correctly for square matrices.

[1] the only output is `Killed: 9`.

**Comment by tjhei** [comment]
Is this by any chance doing a ``reinit(1,invalid_unsigned_int)``, meaning a _very_ large matrix so you are running out of memory? ;-)

**Comment by davydden** [comment]
yes, look like it :smile: We should at least add asserts that those functions are not called with such default numbers.

**Comment by bangerth** [comment]
What is happening is that it calls `TableBase::reinit (const TableIndices<2> &, bool=false)` and `TableIndices<2>` has a constructor that takes one or more arguments. I think that the `TableIndices` constructor should check that all indices it uses are valid, or maybe even better split the one constructor
```
  TableIndices (const unsigned int index0,
                const unsigned int index1 = numbers::invalid_unsigned_int,
                const unsigned int index2 = numbers::invalid_unsigned_int,
                const unsigned int index3 = numbers::invalid_unsigned_int,
                const unsigned int index4 = numbers::invalid_unsigned_int,
                const unsigned int index5 = numbers::invalid_unsigned_int,
                const unsigned int index6 = numbers::invalid_unsigned_int,
                const unsigned int index7 = numbers::invalid_unsigned_int,
                const unsigned int index8 = numbers::invalid_unsigned_int);
```
into multiple as follows:
```
  TableIndices (const unsigned int index1)
  {
    static_assert(N==1, "...");
    ...
  }

  TableIndices (const unsigned int index1,
                         const unsigned int index2)
  {
    static_assert(N==2, "...");
    ...
  }
```
etc. That would have avoided the problem.

**Comment by bangerth** [comment]
Patch coming.
