### ISSUE TITLE
equivalent of MGTransferMatrixFree for LinearAlgebra::distributed::BlockVector

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4574]
I plan to add `MGTransferMatrixFree` equivalent for`LinearAlgebra::distributed::BlockVector` so that transfer is done for each block simultaneously. I am interested in the case where each block lives in the whole FE space. In other words, the result of the transfer should be the same as doing current `MGTransferMatrixFree` for each element in `std::vector< LinearAlgebra::distributed::Vector>` separately. 

The question is, if anyone is already working on those things or have such functionality implemented? 
If not, i will start digging into `MGTransferMatrixFree` and its parent classes to figure out how to do it.
Essentially, i expect it to be a matter of wrapping current transfer operations into `for (b = 0; b < v.n_blocks(); ++b)`.

@guidokanschat @kronbichler @masterleinad ping.

**Comment by masterleinad** [comment]
@davydden I started looking into this but didn't finish while working on the BlockVector support for MatrixFreeOperators::Base. I'll have a look what is missing in the implementation I started with.

**Comment by davydden** [comment]
@masterleinad feel free to push your current changes as a WIP PR and I do my best to help with it.

**Comment by masterleinad** [comment]
@davydden I am interested in the case where the underlying `DoFHandler` might be different for each block, but each block has entries for all the indices of the respective `DoFHandler`. Is this the same you have in mind?
I basically started with copying the specialization for `MGLevelGlobalTransfer<LinearAlgebra::distributed::Vector>` to `MGLevelGlobalTransfer<LinearAlgebra::distributed::BlockVector>`. The idea would then be to derive 
`MGTransferBlockMatrixFree` from it and consider how `MGTransferBlockMatrixFree` can be generalized. Do you have some better ideas?

As soon as I have something that is at least compiling I happily create a PR but maybe it's a good idea if we first agree on what needs to be done.

**Comment by davydden** [comment]
For me each block lives in FE space given by a single dof handler (think of eigenvectors). So each block has all entries of a single dof handler. This is a simpler case than what u want,  but  still fits.

I have not looked into class hierarchy, but for the case of single dof handler for each block I think it boils down to transfer for each block using the same operators.

It looks like the mane difference is that I would be getting/setting cell values using the same local indices, whereas u would use separate local DoFs for each block.

@kronbichler can u please advice if we should join our needs in a single class?

**Comment by kronbichler** [comment]
I think the demands are somewhat different. In @davydden's case we would essentially just need a loop around the already existing code (together with some specializations/restructuring that make `LA::d::BlockVector go through the path of `LA::d::Vector in `MGLevelGlobalTransfer`). For cache efficiency one might pull the loop in a bit but all in all the changes would be pretty straight-forward. @masterleinad's needs are to split the indexing within the level transfer, thus generating different indices on only part of the DoFHandler. So I see those two variants as different extensions around the inner working loops and think that they can be done independently.

**Comment by davydden** [comment]
Thanks for the comment, Martin. Let's do them independently.

**Comment by davydden** [comment]
@kronbichler i started looking into `MGLevelGlobalTransfer`. Looks like the way to have as little as possible duplication is to make it templated with a vector type and add a loop over blocks. For non-block vectors we will have `n_blocks=1` and accessor to the block gives the vector itself. I think we do similar tricks in matrix-free operators.

Before I pursue this direction into a PR, does it make sense to you?

**Comment by davydden** [comment]
@kronbichler nevermind, i guess i will try copy-pasting first and then see what has to be adjusted.
