### ISSUE TITLE
AUR package fails to build on updated Archlinux machine

### ISSUE THREAD

**Issue by ChuckDaniels87** [dealii/dealii#4581]
I have installed `deal-ii` package from the AUR. It was working fine but after the last update of my Archlinux machine, deal.II is not building anymore. I have detected some errors when compiling:

```
In file included from /tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparse_matrix.h:23:0,
                 from /tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparse_decomposition.h:20,
                 from /tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparse_decomposition.templates.h:24,
                 from /tmp/makepkg/deal-ii/src/dealii-8.5.0/source/lac/sparse_decomposition.cc:17:
/tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparsity_pattern.h: In member function ‘dealii::SparsityPatternIterators::size_type dealii::SparsityPatternIterators::Accessor::row() const’:
/tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparsity_pattern.h:1156:12: error: ‘upper_bound’ is not a member of ‘std’
       std::upper_bound(sparsity_pattern->rowstart,
            ^~~~~~~~~~~
/tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparsity_pattern.h:1156:12: note: suggested alternative: ‘lower_bound’
       std::upper_bound(sparsity_pattern->rowstart,
            ^~~~~~~~~~~
            lower_bound
```

Errors are all related to `std::upper_bound` calls. I did not find anything more on the logs but I can upload and share it if needed.

Archlinux machine on which I tried to build the library is up to date.

**Comment by bangerth** [comment]
Can you see what happens if you add `#include <algorithm>` to the top of `/tmp/makepkg/deal-ii/src/dealii-8.5.0/include/deal.II/lac/sparsity_pattern.h`?

Also, what compiler are you using?

**Comment by ChuckDaniels87** [comment]
Thanks @bangerth, adding that include fix this issue. It is building fine now. By the way, I am using GCC 7.1.1 to compile the library.

**Comment by drwells** [comment]
@ChuckDaniels87 thanks for reporting this. I'll fix the AUR package.

**Comment by bangerth** [comment]
@ChuckDaniels87 -- this needs to be fixed in our source one way or the other. Do you want to submit a pull request for it?

**Comment by drwells** [comment]
@bangerth @ChuckDaniels87 It looks like we already fixed this in 9c874026deeb. I suggest that we take this opportunity to release 8.5.1 with the appropriate patch.

**Comment by bangerth** [comment]
Ah, I see. I guess an 8.5.1 could make sense. Want to put that onto the hackathon work list?

**Comment by drwells** [comment]
Hm. I don't mind adding a patch to the Arch Linux package (i.e., I can effectively cherry-pick 9c87402 as part of the build process) but currently anyone who downloads the source and tries to compile it with boost 1.64 will get hard to understand compilation errors (and the serialization methods won't work, should they happen to add `#include <algorithm>` correctly).

I think that the best choice would be to put some warning on the download page stating that we don't yet support boost 1.64 (e.g., "deal.II has known compilation issues with boost 1.64 and we do not support it at  this time") and we release 8.5.1 at the hackathon. Debian Unstable is only using boost 1.62 and Fedora is on 1.63, so I don't think that this will be a stumbling block for a lot of users.

**Comment by ChuckDaniels87** [comment]
@drwells I think that it is a good idea to create a patch on the AUR package until 8.5.1 is released.

**Comment by drwells** [comment]
@ChuckDaniels87 I uploaded a new version to the AUR (nevermind the red; thats a [known problem](https://bbs.archlinux.org/viewtopic.php?id=228091)). Everything works on my machine (TM); let me know if you have any trouble :)

**Comment by ChuckDaniels87** [comment]
@drwells It seems that the patch path is wrong:
```
/tmp/makepkg/deal-ii/src/dealii-8.5.0
patch: **** Can't open patch file ../../fix-compilation-with-BOOST-1.64.patch : No such file or directory
```

I changed this line on PKGBUILD and now it seems to work:
```diff
-    patch -Np1 -i ../../fix-compilation-with-BOOST-1.64.patch
+    patch -Np1 -i ../fix-compilation-with-BOOST-1.64.patch
```

**Comment by drwells** [comment]
That's odd; the PKGBUILD works with both paths for me. I'll upload the fix.

**Comment by ChuckDaniels87** [comment]
> That's odd; the PKGBUILD works with both paths for me. I'll upload the fix.

Try to clean up the `makepkg` cache. There is probably a duplicate of the patch on `/tmp/makepkg/deal-ii`.

**Comment by drwells** [comment]
I didn't see any duplicated patch files. I went ahead and just wrote out the proper path to the patch in the source directory, which should always work.

Would you mind trying again today?

**Comment by ChuckDaniels87** [comment]
@drwells It is working fine now. Thanks!

**Comment by drwells** [comment]
Not a problem. I appreciate you taking the time to test things and report the issue.
