### ISSUE TITLE
Use tensorized evaluation for main work in MappingQGeneric

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#4598]
The functions `maybe_update_Jacobians`, `maybe_compute_q_points`, `maybe_update_jacobian_grads` of `MappingQGeneric` can be made substantially faster for high order if they do not use the naive summation over both quadrature points and the mapping support points at complexity n^{2d} but rather tensorized evaluation at complexity n^{d+1}, for the case that the quadrature is derived from a tensor product. Since our quadrature formulas do not provide this information yet, we need to add the functionality there first. With this ingredient and the functionality in `include/deal.II/matrix_free/evaluation_kernels.h`, this should be not more than a few hundreds lines of code. I hope to get around implementing this during the next months. If someone would like to contribute, I am more than happy to discuss the relevant parts.

**Comment by kronbichler** [comment]
I want to use this functionality because I have several codes where the mapping part really shows up in the profiles. Problem background: polynomial degrees between 6 and 10, using `MatrixFree` for the actual work, relatively regular changes in the geometry.

**Comment by masterleinad** [comment]
I am working on this.
