### ISSUE TITLE
Prevent double negation in cmake error messages

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#4600]
In [this google group post](https://groups.google.com/forum/#!topic/dealii/rKOubgbnKKw), the configuration-time cmake error message of a tutorial lead to some confusion regarding the requirements for PETSc complex number support. The error message

```sh
<path_to_deal_II_installation>/examples/step-17$ cmake .
CMake Error at CMakeLists.txt:42 (MESSAGE):

  Error! The deal.II library found at
 <path_to_deal_II_installation> was not configured with

      DEAL_II_WITH_PETSC = ON
      DEAL_II_PETSC_WITH_COMPLEX = OFF

  One or all of these are OFF in your installation but are required for this
  tutorial step.
```

has a double negation of the second prerequisite (i.e not `DEAL_II_PETSC_WITH_COMPLEX = OFF` == `DEAL_II_PETSC_WITH_SCALAR = ON`). It would be good to find a way to better transmit this message in this instance.

**Comment by tamiko** [comment]
Something like?

```
Error! The deal.II library found at
  <...>
is configured incorrectly.
For this example program the following options have to be set:
  DEAL_II_WITH_PETSC = ON
  DEAL_II_PETSC_WITH_COMPLEX = OFF
```

**Comment by tamiko** [comment]
I would like to avoid to rename `WITH_COMPLEX` to `WITH_SCALAR=OFF`. The former describes precisely, what configuration option is meant (i.e. complex number support). The latter does not. Further (in case of Trilinos) `WITH_COMPLEX=ON` does not imply `WITH_SCALAR=OFF`.

And, in more generality, it might not be possible to make all configuration options positive in the sense that requirements are always expressed via `= ON`.

**Comment by oneliefleft** [comment]
I would like to avoid to rename WITH_COMPLEX to WITH_SCALAR=OFF. The former
describes precisely, what configuration option is meant (i.e. complex
number support). The latter does not. Further (in case of Trilinos)
WITH_COMPLEX=ON does not imply WITH_SCALAR=OFF.

I agree. Its simple enough to just state what *is* required. Its enough to
delete the (weird) double negative, or adopt M's wording.

Toby

**Comment by jppelteret** [comment]
@tamiko I agree with your reasoning, and I think that your suggested fix is a good one (although maybe we continue referring to `step-xyz` as a tutorial rather than an example :-).

**Comment by tamiko** [comment]
> @tamiko I agree with your reasoning, and I think that your suggested
> fix is a good one (although maybe we continue referring to `step-xyz`
> as a tutorial rather than an example :-).

Feel free to make a pull request and improve the wording on the way ;-)

**Comment by jppelteret** [comment]
Will do later in the weekend!

**Comment by jppelteret** [comment]
OK, before I slog through all of the tutorial `CMakeLists.txt` files, let me get some final comments on my proposed change:
```
Error! The deal.II library found at
  <...>
is configured with options that are incompatible with this tutorial.
For this tutorial program the following options have to be set:
  DEAL_II_WITH_PETSC = ON
  DEAL_II_PETSC_WITH_COMPLEX = OFF
```

In my mind, the subtle difference between what I propose here and what we'd previously agreed on is that this could not be interpreted by the user to mean that their deal.II installation is broken in some way.

**Comment by bangerth** [comment]
I like the wording. Would it pedantically be more correct to say "...WAS configured..."?

One may quibble about the word 'incompatible'. It's true, but it seems like such a harsh word, as in "nothing can be done about it". But it's really just that this step "requires a deal.II configuration" that has certain flags set. I don't think that's important enough to really worry about, but if one were to do so anyway, one could say
```
Error! This tutorial requires a deal.II library that was configured with the following options:
  DEAL_II_WITH_PETSC = ON
  DEAL_II_PETSC_WITH_COMPLEX = OFF
However, the deal.II library found at
  <...>
was configured with options that conflict with these requirements.
```
