### ISSUE TITLE
[Post-9.0] Revisit TableIndices constructors

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4608]
#4597 has a lengthy discussion of the constructors of the `TableIndices` class. This is made more complicated by the fact that there is an existing constructor we want to keep for backward compatibility. But after 9.0, we remove that and reconsider introducing a constructor with a variadic template signature.

**Comment by bangerth** [comment]
See also #4249.

**Comment by drwells** [comment]
Fixed by #9740.
