### ISSUE TITLE
Refactor LinearOperator functions into their own namespace

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4610]
I discussed this matter with @drwells yesterday. I am now convinced™ that it would be better to refactor all specialized LinearOperator creation function into a separate namespace
```
namespace LinearOperator
{
  project_to_constrained;
  project_to_unconstrained;
  ...
}
```

I am tempted to keep `linear_operator` in the global dealii namespace.

**Comment by drwells** [comment]
I agree (and it would get rid of the awkward `x_y_linear_operator` naming convention). My main concern is that we should not use `LinearOperator` as a namespace name; perhaps `LinearOperators`?

**Comment by tamiko** [comment]
I suggest `LinearOperatorTools` because we already have a header file `linear_operator_tools.h` and this would match nicely.

Functions in `linear_operator.h`:
```
identity_operator
inverse_operator
linear_operator
null_operator
transpose_operator
```

Functions in `block_linear_operator.h`:
```
block_backward_substitution
block_diagonal_inverse
block_diagonal_operator
block_forward_substitution
block_operator
```

Functions in `constrained_linear_operator.h`:
```
distribute_constraints_linear_operator
project_to_constrained_linear_operator
constrained_linear_operator
```

I suggest to keep a subset in global namespace but put the majority into a `Tools` namespace (or similar). Suggestions? Opinions?

**Comment by bangerth** [comment]
Yes, you can't reuse the class name as a namespace name. I think using a plural is the right way to go. We have several `*Tools` namespaces, but also `GridRefinement`, `DoFRenumbering`, so there is no precedent for one namespace name or another.

Your suggestion for subdivision seems sensible to someone like me who doesn't have much knowledge of the area.

**Comment by tamiko** [comment]
Given the fact that we have now established all names for more than 3 years straight I'd say this ship has sailed.
