### ISSUE TITLE
Documentation of SchurMatrix is unclear

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#462]
Also found by Dakshina Ilangovan:

The documentation of `SchurMatrix` states this:

```
 * Given a non-singular matrix @p A (often positive definite) and a positive
 * semi-definite matrix @p C as well as matrices @p B and @p Dt of full rank,
 * this class implements a new matrix, the Schur complement a the system of
 * equations of the structure
 *
 * @verbatim
 * /        \  /   \     /   \
 * |  A  Dt |  | u |  -  | f |
 * | -B  C  |  | p |  -  | g |
 * \        /  \   /     \   /
 * @endverbatim
 *
 * Multiplication with the Schur matrix @p S is the operation
 * @verbatim
 * S p = C p + B A-inverse Dt-transpose p,
 * @endverbatim
 * which is an operation within the space for @p p.
 *
 * The data handed to the Schur matrix are as follows:
 *
 * @p A: the inverse of @p A is stored, instead of @p A. This allows the
 * application to use the most efficient form of inversion, iterative or
 * direct.
 *
 * @p B, @p C: these matrices are stored "as is".
 *
 * @p Dt: the computation of the Schur complement involves the function @p
 * Tvmult of the matrix @p Dt, not @p vmult! This way, it is sufficient to
 * build only one matrix @p B for the symmetric Schur complement and use it
 * twice.
 *
 * All matrices involved are of arbitrary type and vectors are BlockVectors.
```

This last sentence suggests that the matrices all really just have to have a `vmult/Tvmult` functions plus maybe something that queries their sizes. But in reality, around line 246 of `schur_matrix.h`, there is this code:

```
   h1->reinit(B->n_block_cols(), src.block(0).size());
```

which seems to suggest that the matrices `B` and `Dt` really need to be block matrices themselves. This is consistent with the fact that we multiply with the matrix `B A^{-1} Dt` but the `vmult` operator of this class is

```
  void vmult (BlockVector<double> &dst,
              const BlockVector<double> &src) const;
```

so the Schur complement is apparently expected to have a block structure to itself. 

@guidokanschat : Can you clarify what assumptions you had on the matrix and vector types when you wrote the class? Was your expectation that one would build, say, the Stokes system as a (d+1)x(d+1) block system rather than a 2x2 system?

**Comment by bangerth** [comment]
In the latter case, the block `A` would have dxd blocks, `B` and `D` would be 1xd blocks.

**Comment by guidokanschat** [comment]
I fear I cannot even remember what assumptions I made back then, given that I have not used Schur complement solvers in a decade.

But what I get from the code is the following: both vector types can be block vectors with arbitrarily many blocks... this is from the time of the LDG method for Stokes equations. If you have a system of ``n`` blocks, the matrix ``A`` covers say ``k`` of them and ``C`` the other ``n-k``. Thus, the matrices can be anything that has block matrix structure: BlockSparseMatrix or BlockMatrixArray for instance.

Now, the line 246 you quote seems utter nonsense to me. It essentially means, if all the blocks (in your example all velocity blocks AND the pressure block) have the same size, you have this automatic determination of the size of h1, else, it fails. Being many years older now, I would recommend against this.

My suggestion would be to make the signature (block structure) of the upper left part mandatory and remove the line 246. Although nice, I do not see how to allow for regular ``Vector<double>`` as well.

**Comment by drwells** [comment]
We have since removed this class in favor of a `LinearOperator`-based replacement, so this is no longer an issue.
