### ISSUE TITLE
Construction of QGauss*Chebyshev fails for dim>1

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#4625]
Trying to construct a `QGaussChebyshev`, `QGaussLobattoChebyshev` or `QGaussRadauChebyshev`object fails for `dim==2` and `dim==3` with error messages like
> An error occurred in line <148> of file <../source/base/quadrature.cc> in function
dealii::Quadrature<dim>::Quadrature(const SubQuadrature&, const dealii::Quadrature<1>&) [with int dim = 2; dealii::Quadrature<dim>::SubQuadrature = dealii::Quadrature<1>]
 The violated condition was: 
     (sum>0.999999) && (sum<1.000001)
[...]

**Comment by bangerth** [comment]
Can you add a self-contained code snippet? What is the value of `sum` at the place where the exception happens?

**Comment by masterleinad** [comment]
Sure. Have a look at https://gist.github.com/masterleinad/54e0b5c456cd56f125f2e454cbad259c
The first failing sum is 9.8696.

**Comment by bangerth** [comment]
Hm :-( I don't recall who actually added these classes. It would be useful to ask the authors whether they tried that at the time.

(It would also have been nice to have tests for this case...)
