### ISSUE TITLE
cdash unaccessible 

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#4658]
cdash is not accessible for me. Here is the error:

cdash.kyomu.43-1.org uses an invalid security certificate. The certificate expired on July 25, 2017 at 3:13 AM. The current time is July 25, 2017 at 10:35 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by tamiko** [comment]
Certificate rotated.

**Comment by Rombur** [comment]
@tamiko It's working now. Thanks!
