### ISSUE TITLE
deal.ii doesn't compile in C++17

### ISSUE THREAD

**Issue by gnzlbg** [dealii/dealii#4662]
Deal.II doesn't compile in C++17 mode. The first error one gets is: 

```shell
In file included from /Users/gnzlbg/projects/sideprojects/EDM/dealii-8.5.0/include/deal.II/grid/tria.h:32:
In file included from /usr/local/include/boost/signals2.hpp:15:
In file included from /usr/local/include/boost/signals2/deconstruct.hpp:28:
In file included from /usr/local/include/boost/shared_ptr.hpp:17:
In file included from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:28:
/usr/local/include/boost/smart_ptr/detail/shared_count.hpp:402:33: error: no template named 'auto_ptr' in namespace 'std'
    explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
```

(note: auto_ptr has been removed from C++ in the 17 standard)

---

The compiler is clang 6.0.0 (clang-trunk) and the standard library is libc++. The compiler option is `-std=c++17` although this fails with `-std=c++20a` as well.

**Comment by gnzlbg** [comment]
Adding the following to `tria.h` before including the boost headers fixes this for me, but it would probably be better to include the boost headers through a single source and define this there:

```c++
#define BOOST_NO_AUTO_PTR
```

**Comment by Rombur** [comment]
The problem comes from the version of boost that is installed on your system. Do you have the same problem if you use the bundled version instead?

**Comment by gnzlbg** [comment]
Indeed, sorry for the noise (closing this). I am using `DEAL_II_SETUP_TARGET`, can I choose the Boost version there?

**Comment by Rombur** [comment]
Reconfigure (and recompile deal) and use `-DBOOST_DIR` to set the path to the version of boost you want to use.

**Comment by bangerth** [comment]
What version of BOOST do you have installed on your system? Whether or not the version you have is pre-installed or bundled, compilation should not fail in this way...

**Comment by gnzlbg** [comment]
I have Boost 1.54 installed, but I've been able to use a new version of
boost without issues. I haven't tried yet to use the bundled version though.

On Wed, Jul 26, 2017 at 8:34 PM, Wolfgang Bangerth <notifications@github.com

**Comment by drwells** [comment]
I thought that we required boost 1.56 or newer. Is there something wrong with our version detection?

**Comment by bangerth** [comment]
Hm, good question. We do indeed require 1.56.

@gnzlbg -- how did you configure? And can you find out why deal.II accepted your version?

**Comment by tamiko** [comment]
@gnzlbg Can you please attach the `detailed.log` file to this issue?

**Comment by bangerth** [comment]
@gnzlbg -- ping?

**Comment by gnzlbg** [comment]
Indeed. The `/usr/local/include/boost/version.hpp` file defines `BOOST_LIB_VERSION "1_63"`so I guess the version must be Boost 1.63.0.

**Comment by bangerth** [comment]
Hm, that's still strange. What that suggests is that BOOST 1.63 is not able to tell that clang 6.0.0 with -std=c++17 does not have `std::auto_ptr`. Is that your interpretation as well?

(That seems entirely plausible: at the time boost 1.63 came out, clang 6.0 probably wasn't around yet, and so they didn't have the detection logic ready...)

**Comment by gnzlbg** [comment]
>Is that your interpretation as well?

Yes, libstdc++ removes `std::auto_ptr` (and all other removed std library features like `std::random_shuffle`) in c++17 mode. AFAIK one can re-enable them with a macro. 

> (That seems entirely plausible: at the time boost 1.63 came out, clang 6.0 probably wasn't around yet, and so they didn't have the detection logic ready...)

AFAIK `-std=17z` has been available since clang 3.X times, it is just that boost doesn't has build bots against clang/gcc trunk using `-std=11,14,17,20a` to detect breakage before it is actually shipped (in a compiler or in a  Boost release).

**Comment by bangerth** [comment]
Hm, ok. So what is the solution? To set `BOOST_NO_AUTO_PTR` whenever we encounter a sufficiently not clang? Always?

**Comment by bangerth** [comment]
(I don't want to set this for a single file. I think it would be useful to have it set uniformly for all files we compile.)

**Comment by gnzlbg** [comment]
I think the best deal.ii can do is make sure that the version of boost
provided with deal.ii is good enough, and then independently of whether
that version is used or not, in a different header, detect c++>=17 and if
the boost version is below some threshold then use pragma error to tell the
user what the problem is, and how to fix it(to add the macro before
including deal.ii or boost)

The user should be in charge of applying the fix, because this issue is not
in deal.ii, but in the compilation mode and boost libraries that the user
is combining. For example, the user might be trying to include boost before
including deal.ii, in which case the error might appear before we can do
anything about it inside deal.ii.

Another option would be to detect this incompatibility at configure time,
but depending on what the user does after requiring deal.ii we might not be
able to detect anything anyways (e.g if the user requires deal.ii in their
cmake file and afterwards sets -std=17 for some TU that includes
deal.ii...).

**Comment by bangerth** [comment]
I think detection at configure time is the right place to do it. This should be in the file `cmake/checks/check_01_cxx_features.cmake`and we should just set the `BOOST_NO_AUTO_PTR` flag for the command line then. Do you want to give this a try?

If users override these flags at a later time, then that's up to them -- we can't do anything about that.
