### ISSUE TITLE
Master does not compile with cuda

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#4682]
It looks like the recent changes in `hp::DoFHandler` broke the CUDA code. Any idea what is going here @bangerth ?
```
include/deal.II/hp/dof_handler.h(952): error: expression must be a pointer to a complete object type
include/deal.II/hp/dof_handler.h(954): error: expression must be a pointer to a complete object type
```

**Comment by Rombur** [comment]
It looks like a problem with my system. Even a commit that I know work doesn't anymore :-/

**Comment by davydden** [comment]
Either way, I guess we should add a CUDA tester to make sure things still work

**Comment by bangerth** [comment]
Hm, not actually sure whether the problem is really yours alone. Do you have a testcase that shows this, or is it while compiling deal.II?

The code in these two lines looks like this:
```
    for (unsigned int i = 0; i<levels.size(); ++i)
      delete levels[i];     // ************** 952
    for (unsigned int i = 0; i<has_children.size(); ++i)
      delete has_children[i];     // ************** 954
```
but we have these declarations:
```
    std::vector<std::unique_ptr<dealii::internal::hp::DoFLevel> > levels;
    std::vector<std::unique_ptr<std::vector<bool> > > has_children;
```
So I think that the `delete` statement is indeed wrong. If you had a test case that showed the problem, I'd be happy to fix it.

**Comment by Rombur** [comment]
@davydden I have a machine where I can test, I just need to find the time to set it up. I hope to do it next week.
@bangerth the problem appears when I compile deal. `nvcc` throws the error with no other warning/stack. I went back to earlier versions of deal and I had the same problem. I need to check that the drivers and the kernel are still sync. There was also an update on CUDA 8. So it could be that too...

**Comment by bangerth** [comment]
@Rombur -- can you check whether #4683 works to avoid this problem?

It seems like we don't have a test that checks serialization of an `hp::DoFHandler`. That would discovered this issue. I'll open an issue about this as well -- see #4684.

**Comment by Rombur** [comment]
That fixed it. Thanks @bangerth
