### ISSUE TITLE
arpack/step-36_parpack_mf_02 failing

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#4700]
Currently (4f6efca0da272c90a9cf), I get the following diff
> ***************
928: *** 1,6 ****
928:   DEAL::5931.69
928:   DEAL::5970.26
928:   DEAL::6035.05
928: - DEAL::6035.05
928:   DEAL::6099.84
928:   DEAL::Ok
928: --- 1,6 ----
928: + DEAL::5866.90
928:   DEAL::5931.69
928:   DEAL::5970.26
928:   DEAL::6035.05
928:   DEAL::6099.84
928:   DEAL::Ok

It seems that the double eigenvalue is just reported once and a lower one is found instead.

Unfortunately, CDash never runs this test (or I am still not able to find it there).

**Comment by davydden** [comment]
Yes, I sometimes see those. Try increasing the number of Arnoldi vectors. Probably has to with round-offs

**Comment by davydden** [comment]
something like `const unsigned int num_arnoldi_vectors = 2*eigenvalues.size() + 20;` might make it more robust.
