### ISSUE TITLE
deal.II Hackathon meta tracker

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4704]
This is a tracker issue for all pull requests and issues opened / worked on during the deal.II hackathon.

Please keep discussion on this tracker at a minimum. :-)

**Comment by masterleinad** [comment]
CFl is here: https://github.com/masterleinad/CFL

**Comment by drwells** [comment]
I think that, now that the hackathon is over, we should close this.

We had 113 PRs/issues that referenced this by my count (wow!), of which 11 are still open. Nice work team 🎆

**Comment by tjhei** [comment]
Yeah, good job everyone.
