### ISSUE TITLE
FEValues for General types.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#4706]
Luca + J-P  #4704

**Comment by luca-heltai** [comment]
- [ ] Come up with a failing test
- [ ] Rework/Discuss VectorSlice

**Comment by luca-heltai** [comment]
For @jppelteret  

cleanup = "!git branch --merged master | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d"

**Comment by bangerth** [comment]
@luca-heltai -- is this done now? If so, can you close it? If not, can you elaborate what the first two bullet points above require doing?

**Comment by bangerth** [comment]
@luca-heltai @jppelteret -- ping?

**Comment by jppelteret** [comment]
Thanks, I think that we've moved sufficiently far from this point that this is no longer relevant.
