### ISSUE TITLE
Link errors with suitesparse_config

### ISSUE THREAD

**Issue by bavier** [dealii/dealii#4745]
I tried building dealii-8.5.0 with a suitesparse-4.4.3 (with static libraries) and encountered "undefined reference to SuiteSparse_malloc..." while building.  I noticed the suitesparseconfig library, which defines those symbols, was not included on the link, and the `LAPACK_SUITESPARSECONFIG_WITH_PIC` check determines whether or not that library is including in linking.  

I then upgraded my suitesparse to version 4.5.5, which installs shared libraries by default and should be build with PIC.  I reconfigured and got the same errors.

Now I noticed that the `LAPACK_SUITESPARSECONFIG_WITH_PIC` cmake check was still failing.  I would have expected it to succeed since my suitesparse-4.5.5 built every object with `-fPIC`.

I tried recreating the cmake test in my own sandbox:
```
$ cat >conftest.cxx
extern int SuiteSparse_version (int[3]);
  void foo(int bar[3]) { SuiteSparse_version(bar);}
$ c++ -c conftest.cxx
$ c++ -shared -o conftest.so conftest.o /path/to/suitesparse/lib/libsuitesparse.so
ld: conftest.o: relocation R_X86_64_PC32 against undefined symbol `_Z19SuiteSparse_versionPi' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
which is the error cmake failed `LAPACK_SUITESPARSECONFIG_WITH_PIC`  for.  Out of curiosity I recompiled `conftest.cxx` with `-fPIC`:
```
$ c++ -fPIC -c conftest.cxx
$ c++ -shared -o conftest.so conftest.o /path/to/suitesparse/lib/libsuitesparse.so
$ echo $?
0
```
So that worked.  The `-fPIC` was absent from cmake's check.

As a workaround, I configured with `-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON`, and the `LAPACK_SUITESPARSECONFIG_WITH_PIC` test now passes and the build continues.

**Comment by drwells** [comment]
Thanks for reporting this. It looks like CMake 2.8.9 and newer support `CMAKE_POSITION_INDEPENDENT_CODE`: we should always turn this on and delete our own `fPIC` detection logic.

https://cmake.org/cmake/help/v3.0/policy/CMP0018.html

**Comment by tamiko** [comment]
I would prefer to simply remove the `LAPACK_SUITESPARCECONFIG_WITH_PIC` check. I bet it is safe to assume that workarounds for 6 year old Debian distributions don't need to be supported any more.
