### ISSUE TITLE
Proposal for MeshLoop

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4753]
After a long developer discussion about assembly today, we decided that we want a simpler and more low-level option to do "work" on mesh entities compared to MeshWorker without requiring the DoFInfo/DoFInfoBox/AnyData classes. The new MeshLoop would draw the line below working on FE related things (not containing FEValues, etc.).

Note: we are not replacing or changing MeshWorker, just offering a more low-level option to work on cells and faces of a mesh based on WorkStream that handles the logic to do:
- configurable logic for one/two-sided adaptive face actions
- configurable logic for own/ghost cells and own/ghost faces
- work on level or active cells/faces

We do NOT:
- require a specific copy/scratchdata object
- provide FE*Values

Cases where this should work and be useful:
- CG assembly
- error estimators
- DG assembly
- GMG
- hp?

Examples to write/adapt using the new MeshLoop:
- CG Laplace + Neumann Bdry
- replace WorkStream loop in existing tutorials (step-32 etc) by MeshLoop
- introduce step-12 variant using MeshLoop (or some other "manual" DG example)
- new error estimator example
- step-50 or other GMG example?

Proposed interface:
```
template <typename MeshType, typename Iterator, typename ScratchData, typename CopyData>
void
MeshLoop::run(
iterator begin,
iterator end,
std::function<void(const Iterator, ScratchData&, CopyData&)> cell_worker,
std::function<void(const Iterator, int face_no, ...?, ScratchData&, CopyData&)> face_worker,
std::function<void(const Iterator, int face_no, ...?, ScratchData&, CopyData&)> boundary_worker,
std::function<void(CopyData&)> copier,
const ScratchData & sample_scratch_data,
const CopyData & sample_copy_data,
LoopFlags flags = gooddefault?,
const unsigned int 	queue_length = 2*MultithreadInfo::n_threads(),
const unsigned int 	chunk_size = 8 );

enum LoopFlags:
do_own_cells?
do_ghost_cells
cells_first
own_faces: never?, one, both
faces_to_ghost: never, one, both
ghost_boundaries?
```

Thoughts:
- provide BaseScratchData and BaseCopyData to derive from (optionally)
- ScratchData/CopyData that contains functions/members that help for FE assembly

**Comment by bangerth** [comment]
@guidokanschat  -- FYI, in case you're interested!
