### ISSUE TITLE
Add generic `get_finite_element(unsigned int)` functions

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4770]
From a discussion @tjhei, @bangerth, and I just had: we have a long-standing incompatibility between `DoFHandler<dim,spacedim>::get_fe()` and `hp::DoFHandler<dim, spacedim>::gef_fe()`. The first returns a `FiniteElement &` and the second returns a `FECollection &`. We should deprecate these functions and implement `get_finite_element(unsigned int)` and `get_n_finite_elements()` functions for compatibility between the different dof handlers.

**Comment by davydden** [comment]
i think this is also discussed here https://github.com/dealii/dealii/issues/2023

**Comment by bangerth** [comment]
We may have to have both what's discussed here and what is suggested in #2023. The latter is necessary for all of those places that need to construct an `hp::FEValues` object and need a collection for that.
