### ISSUE TITLE
The 8.5.1 bugfix release

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4836]
As discussed, lets cherry-pick 9c874026deeb51c613e0418d37679fdf6b27c3e0 and 5ac1ad19d0eca363506d537c64281ecb7f2050ab (i.e., both commits in #4309) onto the 8.5 branch and make a quick release. We need to do the following:
- [x] update the release branch (cherry-pick and increase the release number)
- [x] rerun the tester
- [ ] mac packages
- [x] update the download page
- [x] binary packages
- [x] update the website

@tjhei lets try to get this done asap.

**Comment by tamiko** [comment]
@drwells Testsuite result http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=10097

**Comment by drwells** [comment]
The only failing test (the others are opencascade issues, solver iteration counts, memory consumption issues, etc) of interest is `mpi/locally_owned_dofs_per_subdomain_02.mpirun=2.debug`:

https://cdash.kyomu.43-1.org/testDetails.php?test=39273939&build=10097

**Comment by tamiko** [comment]
@drwells The failing test you mention is due to the inherent instability of metis. We have an alternative output file on current master, but I'd say it's not worth "fixing". (We have a couple of failing tests anyway.)

**Comment by drwells** [comment]
Relates to #4704.

**Comment by tjhei** [comment]
I tagged the release: https://github.com/dealii/dealii/releases/tag/v8.5.1

**Comment by tjhei** [comment]
updated downloads page

**Comment by drwells** [comment]
@tjhei What is the difference between the 'source code' and 'dealiii-8.5.1.tar.gz' downloads?

**Comment by drwells** [comment]
The website is now up to date 👍. We still need the binary packages, though.

We still need to update the docker and virtual box files.

**Comment by tjhei** [comment]
> @tjhei What is the difference between the 'source code' and 'dealiii-8.5.1.tar.gz' downloads?

They are identical files. We upload it again according to the release tasklist. I guess it makes it more obvious (bold font!). Any other reason, @tamiko ?

**Comment by tjhei** [comment]
> We still need to update the docker and virtual box files.

No reason to update docker to 8.5.1, I think. Virtual box is something I have to do at some point.

What about other packaging like debian, @tamiko ?

**Comment by drwells** [comment]
The docker hub instructions refer to 8.4.2; I agree that the 8.5.0 image is okay but we should at least update the information.

I'll get around to updating the Arch Linux package at some point soon (there is not much need to do this since I already bundle the boost and GCC7 patches in the current release anyway).

The main page of the website still says 8.5.0.

**Comment by drwells** [comment]
Does the current mac package avoid the problems with boost? If so we should close this and declare victory.

**Comment by tamiko** [comment]
The mac package is probably fine, let's just declare

*victory*
