### ISSUE TITLE
Update readme.html for Nanoflann and ADOL-C and SUNDIALS

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4850]
`doc/readme.html` lists our external dependencies. These have recently grown to include nanoflann and ADOL-C, and these should be listed there as well.

**Comment by bangerth** [comment]
...also SUNDIALS

**Comment by tjhei** [comment]
nanoflann is easy enough: https://github.com/dealii/candi/pull/47 (cmake with ``-D BUILD_SHARED_LIBS=ON`` and then ``make install``, then set NANOFLANN_DIR.)

**Comment by davydden** [comment]
i just tried building `dealii` with `adol-c` and got:
```
deal.II needs ADOL-C version 2.6.4 or newer
```
but the latest release is `2.6.3`: https://www.coin-or.org/download/source/ADOL-C/

@jppelteret ping.

**Comment by tamiko** [comment]
> i just tried building `dealii` with `adol-c` and got:
> ```
> deal.II needs ADOL-C version 2.6.4 or newer
> ```
> but the latest release is `2.6.3`: https://www.coin-or.org/download/source/ADOL-C/

This is correct and intended behavior ;-)
After all, we're from the future :-P

(aka we require the current development version that hopefully gets the
version number 2.6.4 one day.)

**Comment by jppelteret** [comment]
^ what @tamiko said :-)

**Comment by drwells** [comment]
Fixed by #6360 :)
