### ISSUE TITLE
BlockVector vs MultiVector

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4871]
Currently we mostly use `BlockVector` to cover cases like
```
|  M  B^T  |   =  | F |
|  B   0   |      | G |
```
and then be able to work on each block separately **as well as on the vector as a whole**, which necessitates the presence of `BlockVector::collect_sizes()` and `BlockVector::locally_owned_elements( )`. The latter creates a union of index spaces for each block with correct shifts. 

I am curios whether or not we want to distinguish between the case in the above and
```
|  L    0  |   =  | F1 |
|  0    L  |      | F2 |
```
where each block has the same index space and there is no need/use of creating the collected index space? Also the number of block here can be large, we are speaking about hundreds. 

Both shall provide some basic interface, i.e. 
```
unsigned int n_blocks () const
void add (const value_type a, const BlockVectorBase &V)
void update_ghost_values () const
```

But there are differences as well, the latter does not necessarily need to know how to `void add (const std::vector< size_type > &indices, const std::vector< Number > &values)` as one may have no global index space defined. The main usage is
```
(G1 G2) = L * (F1 F2)
```
that is, apply the same operator to all vectors. There are linear algebra packages targeted on efficient **sparse matrix multi vector (SpMMV)** products which store those `F1 F2` in such a way that you can't even access `BlockVector::block(unsigned int)`. That's another principal difference. Finally, one can think of a MultiVector consisting of BlockVectors.

However, Trilinos does not distinguish between the two cases and uses
```
typedef Epetra_MultiVector MV;
typedef Epetra_Operator OP;
```
for both, AFAIK. 

So I wonder if we shall distinguish between them? I see several options:

1. Don't bother
2. Add some mechanics to disable building of the collected index space and throw errors if it's being used without being constructed.
3. Introduce a top level `MultiVector` (interface) as well as `ComposedMultiVector<VectorType>` (simple case of a collection of vectors) classes and derived `BlockVector` from the latter. 

(3) Might be tricky when it comes to actual vectors (PETSc, Trilinos, LA::d::Vector) as one would have to split each implementation somehow. I would say (2) is probably the best option.

**Comment by bangerth** [comment]
Can't you address at least the storage of the matrix class via a `LinearOperator` derived something? If that is so, the you can store the matrix as a diagonal system of blocks that all point to the same matrix, and in that case the storage scheme used for the vector becomes irrelevant.

The only thing that would speak against that is that the matrix-vector product loads the same matrix many times over, whereas the multivector approach loads the matrix only once and applies it to multiple vectors at the same time.

**Comment by davydden** [comment]
> Can't you address at least the storage of the matrix class via a LinearOperator derived something?

that's not a problem at all, actually. I don't even need to store the complete operator and can do `std::vector<>` for each vector and do `vmult()` by hand. In the same way I could loop over block of the `BlockVector` and do `vmult()` assuming that they all based on the same index space.

**Comment by davydden** [comment]
> The only thing that would speak against that is that the matrix-vector product loads the same matrix many times over, whereas the multivector approach loads the matrix only once and applies it to multiple vectors at the same time.

i believe the most efficient way is for each row of a matrix do produce with all vectors in multi-vector, which means that they need to be located in memory appropriately (i.e. all 0-th elements together, then all 1-st elements etc).

But this is only an illustration that the interface is different, in principle.

**Comment by drwells** [comment]
I think we should just stick to block vectors as the official solution.
