### ISSUE TITLE
Bug in Tensor with CUDA

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#4886]
#4785 broke CUDA see https://github.com/dealii/dealii/commit/13af5c499daea7ed65c9a94631b6881242fb1523##commitcomment-23689576

@jppelteret Splitting the operation does not help. What if I create a partial specialization for `int`, `unsigned int`, `float`, and `double` where I use the old function. Would that work for you?

**Comment by bangerth** [comment]
Can you copy the error message here?

**Comment by Rombur** [comment]
```
terminate called after throwing an instance of 'dealii::StandardExceptions::ExcCudaError'
  what():  
--------------------------------------------------------
An error occurred in line <81> of file </home/dealii/tests/cuda/cuda_tensor_01.cu> in function
    void test_gpu()
The violated condition was: 
    cuda_error == cudaSuccess
Additional information: 
    an illegal memory access was encountered
--------------------------------------------------------
```
This is basically a segfault. We touched memory that we are not allowed to touch.

**Comment by jppelteret** [comment]
Yes, creating a partial specialisation would work for me. To be completely honest, I'm not specifically using this function but was rather trying to make sure that we're consistently initialising the underlying data correctly. If we need to revert this then I'd be OK with it, but it could cause hard to find bugs in the future.
