### ISSUE TITLE
Advertise the CommonInputs class (related to DataPostprocessor) a bit better

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#4898]
In answering [this forum question](https://groups.google.com/forum/#!topic/dealii/BSwYPbl8G-Q) I found the very useful [`CommonInputs`](https://www.dealii.org/8.5.0/doxygen/deal.II/structDataPostprocessorInputs_1_1CommonInputs.html) class to be inadequately advertised. It deserves mention in both the [`Graphical output`](https://dealii.org/8.5.0/doxygen/deal.II/group__output.html) module and the introduction to the [`DataPostprocessor`](https://dealii.org/8.5.0/doxygen/deal.II/classDataPostprocessor.html) class, especially given that the interface that it provides through the `DataPostprocessor::evaluate_*_field` is more flexible than the old interface of the `DataPostprocessor::compute_derived_quantities_*` functions.

**Comment by davydden** [comment]
>  CommonInputs class to be inadequately advertised

first time i hear about it :smile:

**Comment by bangerth** [comment]
Hm, the `evaluate()` function takes an argument whose type is described here: https://dealii.org/8.5.0/doxygen/deal.II/structDataPostprocessorInputs_1_1Scalar.html

It explicitly says this:

> "A structure that is used to pass information to DataPostprocessor::evaluate_scalar_field(). It contains the values and (if requested) derivatives of a scalar solution variable at the evaluation points on a cell or face.
>
> Through the fields in the CommonInputs base class, this class also makes available access to the locations of evaluations points, normal vectors (if appropriate), and which cell data is currently being evaluated on (also if appropriate)."

What else do you want to say, or how do you want to say it?

**Comment by jppelteret** [comment]
Don't ask how, but I think that I must have been looking at the documentation to `DataPostProcessor` in 8.4.1 when I opened this issue (even though I ended up linking to 8.5). So `evaluate()` is discussed in the class description. I also see that the `compute()` functions are even deprecated in favour of `evaluate()`... False alarm!
