### ISSUE TITLE
Documentation for nanoflann

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4914]
As of the hackathon we now support the very nice nanoflann library. We are still missing documentation describing how to install a copy of nanoflann compatible with deal.II and set up the library with it: this information should go in `doc/readme.html` and also possibly in `doc/external-libs/nanoflann.html`.

**Comment by davydden** [comment]
We should also have a smoke test for it

**Comment by drwells** [comment]
I completely missed that we already have an open issue for this; I am not sure how I missed it.

Closed in favor of #4850.
