### ISSUE TITLE
Check the CPU time calculations on Windows

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4927]
We currently measure CPU time in the `Timer` class on Windows as follows:

```cpp
    double system_cpu_duration = 0.0;
#ifdef DEAL_II_MSVC
    FILETIME cpuTime, sysTime, createTime, exitTime;
    if (GetProcessTimes(GetCurrentProcess(), &createTime,
                        &exitTime, &sysTime, &cpuTime))
      {
        system_cpu_duration = (double)
          (((unsigned long long)cpuTime.dwHighDateTime << 32)
           | cpuTime.dwLowDateTime) / 1e6;
      }
    // ...
```

where `cpuTime` contains two 32-bit values representing a 64-bit time value (hence the binary operations and the conversion to `unsigned long long`). The division by `1e6` implies that this unit is in microseconds; however, the [relevant MSDN documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683223(v=vs.85).aspx) states that "Such a structure contains two 32-bit values that combine to form a 64-bit count of 100-nanosecond time units", so we should really divide by `1e7` instead.

I don't have access to MSVC right now, but it would be pretty easy to test this by creating a timer around some CPU burn function and checking that the CPU time is close to the wall time.

**Comment by drwells** [comment]
I noticed this while working on #4867.

**Comment by bangerth** [comment]
Can't we replace all of this with the C++11 facilities as well?

**Comment by drwells** [comment]
unfortunately, no; the resource usage calculations are dependent on the OS.

**Comment by drwells** [comment]
I checked and we should divide by `1e7` instead. However, I am now getting stored CPU times of zero on Windows for other reasons that I don't quite understand. I'll keep looking into this.

**Comment by drwells** [comment]
For the sake of record: the reason I got zeros was that Windows, by default, measures CPU usage in units of 1/64th of a second (so very small times are truncated down to zero even if the wall clock time is nonzero).
