### ISSUE TITLE
No need to use 'static GrowingVectorMemory'

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4955]
In a number of places, specifically the `LinearOperator` framework, we use
```
    static GrowingVectorMemory<Domain> vector_memory;
```
This is unnecessary: `GrowingVectorMemory` draws from a single, global pool that is shared between all such objects. As a consequence, the `GrowingVectorMemory` object does not need to be `static` itself, and probably should not be.

This should be easy to fix, but I'm holding off on it because it gets in the way of #4954 and a couple other follow-up patches.

**Comment by drwells** [comment]
It might help if we advertise the fact that they are statically allocated better; this is hard to infer from the documentation right now. We can make it easier to see this if we add a `@note` to the last top level documentation paragraph of `GrowingVectorMemory` and explicitly state that the pool is statically allocated.

**Comment by bangerth** [comment]
Yes, good point. I'll add a paragraph.
