### ISSUE TITLE
Auto-differentiation meta-tracker

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#4958]
This is a meta-tracker to keep tabs on which issues and pull-requests relate to the implementation of automatic differentiation as a first-class citizen in deal.II.

**TODO:**

- [ ] Make a todo list

**Comment by davydden** [comment]
or use [projects](https://github.com/dealii/dealii/projects) :smile:

**Comment by jppelteret** [comment]
Closed in favour of using a project. @davydden is on top of this GitHub thing :-)

**Comment by davydden** [comment]
thanks, i think it looks very neat using the Project feature of GitHub.

**Comment by bangerth** [comment]
This is now https://github.com/dealii/dealii/projects/7
