### ISSUE TITLE
Normal vectors use wrong data type

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#496]
We have a problem with FEValues and normal vectors:
```
  const Point<spacedim> &normal_vector (const unsigned int i) const;
  const std::vector<Point<spacedim> > &get_normal_vectors () const;
```
The thing is that we use `Point<dim>` in places where we mean a physical point in space, whereas the difference between two points is a `Tensor<1,dim>`. A normal vector is most definitely of the "difference" kind and consequently should be represented by a tensor, not a point. I could change that in the first of the two places without too much trouble because the two are convertible into each other. The second one, however, I cannot change in a backward compatible way. 

Ideas?

**Comment by kronbichler** [comment]
The questions are:
a) How many people use this access method for actually creating a variable with references? We use this only four times in the library and maybe a dozen times in the test suite.
b) In case one's code is affected, the changes to be made a very simple. If it is stated in the 'incompatibilities' list, this is a no-brainer.

Given these facts, I would say that it won't hurt much and thus it is justifiable to just change the code. We've made some immediately incompatible changes before, even though it is somewhat of a semantic change here.

**Comment by tjhei** [comment]
The only backwards compatible way would be to deprecate the current function and introduce get_all_normal_vectors() or something. Not great but maybe better than breaking applications?

**Comment by bangerth** [comment]
@kronbichler : We use this in the testsuite as well :-(
```
examples/step-12/step-12.cc:    const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors ();
examples/step-12/step-12.cc:    const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors ();
examples/step-30/step-30.cc:    const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors ();
examples/step-30/step-30.cc:    const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors ();
examples/step-34/step-34.cc:        const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors();
examples/step-34/step-34.cc:                const std::vector<Point<dim> > &singular_normals = fe_v_singular.get_normal_vectors();
examples/step-34/step-34.cc:        const std::vector<Point<dim> > &normals = fe_v.get_normal_vectors();
```
Presumably people copy-paste this kind of code into their programs :-( I'm really quite disappointed that it would take us a decade to spot this problem. It's a shame that we can't make this backward compatible because there is this nice relationship between `fe_values.something(q)` and `fe_values.get_somethings()`. @tjhei 's name suggestion would fall out of context but I suppose I could explain this in the documentation. If I deprecate the `get_normal_vector` function in one release, I could change its return type in the next release and un-deprecate it (and maybe deprecate the new function `get_all_normal_vectors` instead).

Ideas?

**Comment by kronbichler** [comment]
Right, we have it in the tutorials and therefore, it is certainly more critical. Thinking this way, I would agree with @tjhei 's suggestion, too.
