### ISSUE TITLE
mesh loop discussion

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4962]
see https://github.com/dealii/dealii/projects/8 for an overview / todolist.

I would like to discuss a few questions and I thought an issue might be a good place to do this.

After re-implementing step-11 (see #4961), the following things occurred to me:
- We need to set ``cells_first`` because I am reusing the ``local_rhs`` that is initialized in the ``cell_worker``. Maybe we should flip the meaning and rename it to ``cells_last`` because that is less common? Makes sense?
- I don't need a separate ``FEFaceValues`` per face, because we are calling them sequentially. Does that make sense?
- The dependency between the different workers (and that we have a single scratch/copier) is a little confusing. I don't think we want to change this, though, right?
- Would it make sense to move the Copy and Scratch classes from step-11 into the library so we can reuse them? If you need to store more information, you can always derive from it or not use them.
- I think this makes step-11 more readable (better than ``create_boundary_rhs()``). Should we replace step-11?
- Moving forward, I would like to ask if we want to a) add new tutorials that rewrite examples with mesh_loop, b) replace existing tutorials (step-12, DG, step-50 parallel GMG, ...), c) write other tutorials? Personally, I feel like we might be able to remove MeshWorker, WorkStream, and create_*_matrix() approaches by ``mesh_loop`` and make assembly quite a bit simpler this way.

@luca-heltai I am especially interested in your input.

**Comment by bangerth** [comment]
Regarding `cells_first`: You need this because you need to call `cell_matrix.reinit(...,...)` in either the cell or the boundary function, right? (Or, in a different design, the matrix and rhs already had been initialized to the correct size, and all you'd have to do is `cell_matrix = 0`.)

This is error prone for sure. I'm sure half of the people forget to set things to zero, and the other half do it in the wrong function. I don't know how to resolve this other than what I think you're already doing, namely copying the sample object over to the copy object before we treat each cell.

**Comment by tjhei** [comment]
> You need this because you need to call cell_matrix.reinit(...,...) in either the cell or the boundary function, right?

Well, it is even worse. I have to zero ``cell_rhs`` in the cell_worker and not zero it in the ``boundary_worker`` because it would overwrite the ``cell_worker`` data.

> I don't know how to resolve this other than what I think you're already doing, namely copying the sample object over to the copy object before we treat each cell.

That is not enough (see above).

**Comment by luca-heltai** [comment]
> We need to set cells_first because I am reusing the local_rhs that is initialized in the cell_worker. Maybe we should flip the meaning and rename it to cells_last because that is less common? Makes sense?

Yes. I agree on this. I think that most of the times, we do work on cells first, then loop on faces.

> I don't need a separate FEFaceValues per face, because we are calling them sequentially. Does that make sense?

Yes. It makes sense.

> The dependency between the different workers (and that we have a single scratch/copier) is a little confusing. I don't think we want to change this, though, right?

No. I think we don't want to change this...

> Would it make sense to move the Copy and Scratch classes from step-11 into the library so we can reuse them? If you need to store more information, you can always derive from it or not use them.

Yes, I think this would make sense. I have a couple of these classes that I use for my codes that have been specialised with simple getters for fevalues objects that would fit well in this. I'll make a PR soon with them.

> I think this makes step-11 more readable (better than create_boundary_rhs()). Should we replace step-11?

I'm in favour. 

> Moving forward, I would like to ask if we want to a) add new tutorials that rewrite examples with mesh_loop, b) replace existing tutorials (step-12, DG, step-50 parallel GMG, ...), c) write other tutorials? Personally, I feel like we might be able to remove MeshWorker, WorkStream, and create_*_matrix() approaches by mesh_loop and make assembly quite a bit simpler this way.

I think there is value in keeping MeshWorker around, once we make its implementation use mesh_loop, as a higher level implementation (with a lot of assemblers already implemented).

I'd like to have a tutorial in which we evaluate a simple error estimator using mesh-loop. That would be very useful. As far as other examples are concerned, I have no particular preferences...

**Comment by tjhei** [comment]
> I think there is value in keeping MeshWorker around

I guess that makes sense. No harm in having two tutorials, one with mesh_loop and one with meshworker...

> I'd like to have a tutorial in which we evaluate a simple error estimator using mesh-loop. That would be very useful. As far as other examples are concerned, I have no particular preferences...

I have one of my student contribute this.

**Comment by drwells** [comment]
This has long since been worked on and merged.
