### ISSUE TITLE
FESubfaceValues and FEFaceValues?

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4969]
I think the logic to create either a ``FEFaceValues`` or a ``FESubfaceValues`` is unnecessarily complicated. It looks to me like they have identical data structures and just differ by ``reinit(cell, face_no)`` vs ``reinit(cell, face_no, subface_no)``.
Is there a good reason these are different classes instead of slamming both ``reinit`` functions into the same class?

I am asking because it makes the logic to do DG assembly unnecessarily complicated:
- I need to have scratch data for 4 class: ``fe_face_values``, ``fe_subface_values``, ``fe_face_values_neighbor``, ``fe_subface_values_neighbor``
- I need to make sure I initialize the correct class
- I need to make sure to use the correct class
- To make the assembly code independent of the choice above, one needs to use ``FEFaceValuesBase``

Anything I am missing? If not, I would add the other ``reinit`` into ``FEFaceValues``. We can then deprecate ``FESubfaceValues``.

**Comment by bangerth** [comment]
The constructors of the two classes are different. In one case, you project the (dim-1)-dimensional quadrature onto each face, getting a dim-dimensional quadrature with `faces_per_cell` copies among which `reinit` then selects the one that corresponds to the face the user wants.

In the subface case, you project the (dim-1)-dimensional quadrature onto each subface, and receive a dim-dimensional quadrature that has `faces_per_cell * subfaces_per_face` copies.

**Comment by bangerth** [comment]
Btw, since you only ever integrate subfaces from the coarser side, you never need `fe_subface_values_neighbor`.

**Comment by tjhei** [comment]
> The constructors of the two classes are different.

That is correct. Do you propose to stick with the current design? I am asking because none of this is user-facing and we can hide these differences (for example by initializing both or only the needed one on demand).

> Btw, since you only ever integrate subfaces from the coarser side, you never need fe_subface_values_neighbor.

We currently have options in the mesh_loop to call the faces twice (so from both sides). In that case I would need all four.

**Comment by bangerth** [comment]
I like the design we have. It clearly represents the different semantics of integrating over full or partial faces. It also allows to share most of the code that underlies it. 

I see that this is inconvenient in your current context, but I usually tend to err on the side of representing different semantic contexts with different classes, at the cost of possibly more code. If you want to make it easier for users, you can add pointers `this_cell_fe_face_values` and `neighbor_fe_face_values` that point to one or the other `FEFaceValues` or `FESubfaceValues` objects via a common base class.

**Comment by tjhei** [comment]
alright, we'll see how that looks like in practice.
