### ISSUE TITLE
Use LinearOperator in examples

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4977]
There are a lot of places where we define new matrix classes (e.g., both step-20 and step-55 define an `InverseMatrix` class). We should use `LinearOperator` instead. Things to do:

- [x] upgrade step-20
- [ ] upgrade step-22
- [ ] upgrade step-55
- [x] decide which tutorial program will contain the official introduction to `LinearOperator`

I am marking this as meta since there are probably more tutorial programs to add to the list (feel free to add them if you see them).

**Comment by jppelteret** [comment]
Great idea! I transitioned `step-44` to use linear operators quite some time ago, but I must admit that I never went into any depth on how they worked or what the benefit of their use may be.

**Comment by bangerth** [comment]
If y'all don't mind too much, I'd like to keep step-20 the way it is. That's the first example where we construct complicated solvers and preconditioners, and I think there is educational value in showing how one can build classes that look and act like matrices without storing any entries.

I would, however, be very much in favor of a section in the "Possibilities for extensions" that would show how to achieve the same effect with `LinearOperator` classes (i.e., with less code, but more obscurity what actually happens).

**Comment by hreinn91** [comment]
I would love it if you guys used linear operators in more examples. They look really useful but I'm having a hard time figuring out how to use them.  (I'm a novice in C++ and I learn best from seeing things used in examples )
 I'm doing a project where I'm going to implement GLT multigrid preconditioner in dealii.

**Comment by drwells** [comment]
It looks like #7702 added LinearOperator to step-20. Lets add the other ones as notes in #6774.
