### ISSUE TITLE
Implement DataPostprocessor[Symmetric]Tensor

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#4995]
[This comment](https://github.com/dealii/dealii/pull/4991#issuecomment-326033087) in #4991 refers.

> We don't currently support tensorial output. But I think it would still be nice to have the equivalent of these classes, say DataPostprocessorTensor and DataPostprocessorSymmetricTensor. They would output individual tensor components as scalars, so maybe that's not quite that useful, but it would still make some things easier.

**Comment by bangerth** [comment]
I already have a patch for `DataPostprocessorTensor` that should be good to go later today.

**Comment by bangerth** [comment]
I decided in #4997 that the general tensor case should be good enough for now. Since we can't output tensors anyway, there is probably little demand to also add the symmetric tensor case right now.
