### ISSUE TITLE
64bit indices in BLAS/LAPACK

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5018]
When building against a Blas/Lapack with 64 bit integers, our wrappers in https://github.com/dealii/dealii/blob/master/include/deal.II/lac/lapack_templates.h are broken as they assume `int` everywhere, whereas it should be `long long int` or `long int` ? ([openblas](https://github.com/xianyi/OpenBLAS/issues/234#issuecomment-19726351)).

Not sure how to autodetect this, as a part of configuration maybe we can try building and running a simple program with both cases and see which one fails.

p.s. I don't expect that someone will actually need 64bit ints in blas within the FEM, but users might still hit this issue unintentionally.

**Comment by bangerth** [comment]
Does BLAS/LAPACK somehow export what type they use? I figure that's difficult because there's no header file, right?

Out of curiosity, where exactly did you find a 64-bit BLAS? It seems entirely unnecessary, given that BLAS and LAPACK only do dense linear algebra...

**Comment by davydden** [comment]
> there's no header file, right

Exactly, those are Fortran libs.

> where exactly did you find a 64-bit BLAS?

Intel MKL can provide 64bit indexing, so no, it's not overly hard to find ;-)

But yes, I don't have understand why it exists for dense SERIAL linear algebra.

**Comment by kronbichler** [comment]
> But yes, I don't have understand why it exists for dense SERIAL linear algebra.

It definitely is weird as long as matrices are involved, but it is not if you have level 1 BLAS, i.e., dot products or vector updates. Quite a number of linear algebra packages go through BLAS for those functions, and while it is still rare to exceed 2 billion vector elements, it is definitely not impossible. I even set up a whole finite element problem with more than 4B entries on a shared memory machine (with 512 GB RAM).

**Comment by davydden** [comment]
> It definitely is weird as long as matrices are involved, but it is not if you have level 1 BLAS

are right, i completely forgot about the lower level operations. Then it's yet another reason to actually fix this and be on the safe side.

**Comment by bangerth** [comment]
Hm, vector-vector operations -- good point.

But so how do you detect which integer type is being used? For f77 functions, data types aren't even mangled into function names. So you just have to /know/? Or is there a way to /find out/?

**Comment by davydden** [comment]
> So you just have to /know/? 

i think a hard switch (config option) can be a good start. If we figure out how to autodetect it later, it will be easy to add.

btw, `openblas` can be configured with `INTERFACE64=1` to use 64bit ints.

**Comment by davydden** [comment]
here's one approach https://groups.google.com/forum/#!topic/hpctools/jKCDT5zAGLs

**Comment by bangerth** [comment]
What a hack :-(

**Comment by davydden** [comment]
found this http://www.icl.utk.edu/files/publications/2017/icl-utk-950-2017.pdf

**Comment by davydden** [comment]
another way to test https://stackoverflow.com/questions/37299929/detection-of-the-ilp-mode-of-blas
