### ISSUE TITLE
Directory structure for Particles/BoundingBoxes/etc.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#5019]
Dear all, one of my student is in the process of contributing a few functions that are somewhat relevant for particle in cells methods.

My suggestion would be to have a new directory under `include/deal.II/particle` as in aspect. 

Do you have other preferences for the name?

**Comment by luca-heltai** [comment]
@gassmoeller

**Comment by tjhei** [comment]
``particles``?

**Comment by bangerth** [comment]
Yes, I thought we had agreed on `particles/`.

**Comment by luca-heltai** [comment]
Ok. We'll use particles then.

**Comment by gassmoeller** [comment]
I agree, particles is the best name. I need to fix one more issue in ASPECT, then most of the basic functionality is ready to move (I can work on that next week).
