### ISSUE TITLE
Point::distance_square() with VectorizedArray and GCC 4.8.5

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5037]
I got the following error on a cluster with gcc 4.8.5 (don't see it with Clang on macOS or gcc 5.4.0 on Ubuntu):
```
/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/dealii-develop-7zqsrxk7m62idjqctdfa2enpuimjxtxw/include/deal.II/base/point.h: In instantiation of ‘typename dealii::numbers::NumberTraits<Number>::real_type dealii::Point<dim, Number>::distance_square(const dealii::Point<dim, Number>&) const [with int dim = 2; Number = dealii::VectorizedArray<double>; typename dealii::numbers::NumberTraits<Number>::real_type = dealii::VectorizedArray<double>]’:
<blablabla>:   required from here
/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/dealii-develop-7zqsrxk7m62idjqctdfa2enpuimjxtxw/include/deal.II/base/point.h:500:40: error: no match for ‘operator-’ (operand types are ‘const dealii::Tensor<0, 2, dealii::VectorizedArray<double> >’ and ‘dealii::VectorizedArray<double>’)
       const Number diff=this->values[i]-p(i);
                                        ^
```

I will look into this tomorrow, but if someone knows the answer straght away, feel free to create a PR 😄

**Comment by bangerth** [comment]
```
no match for ‘operator-’ (operand types are ‘const dealii::Tensor<0, 2, dealii::VectorizedArray<double> >’ and ‘dealii::VectorizedArray<double>’)
       const Number diff=this->values[i]-p(i);
                                        ^
```
You're trying to subtract a `Point<2,VectorizedArray>` and a `VectorizedArray`. That can't work.

What's your code that produced this error?

**Comment by davydden** [comment]
> You're trying to subtract a Point<2,VectorizedArray> and a VectorizedArray. That can't work.

you are mistaken. the operation is perfectly valid as far as I can tell and it's in `dealii`

nope, it's dealii: https://github.com/dealii/dealii/blob/master/include/deal.II/base/point.h#L500

Keep in mind that I don't have this issue with gcc 5.4.0 or Clang on macOS.

**Comment by davydden** [comment]
@bangerth I even added unit tests for this operation https://github.com/dealii/dealii/pull/4949

**Comment by bangerth** [comment]
Hm, I only see a test where you subtract one `Point<dim,VectorizedArray>` from another `Point<dim,VectorizedArray>`. But the compiler here says that you are subtracting a `VectorizedArray` from a `Point<dim,VectorizedArray>`.

What I don't understand is why that is what the compiler thinks, because in
```
const Number diff=this->values[i]-p(i);
```
I would have expected both `this->values[i]` and `p(i)` to have type `Number`. Somewhere in there is the problem.

**Comment by davydden** [comment]
> I only see a test where you subtract one Point<dim,VectorizedArray> from another Point<dim,VectorizedArray>.

it's in the PR I linked above https://github.com/dealii/dealii/blob/master/tests/base/point_03.cc#L45

> But the compiler here says that you are subtracting a VectorizedArray from a Point<dim,VectorizedArray>.

i don't think so:

```
no match for ‘operator-’ (operand types are ‘const dealii::Tensor<0, 2, dealii::VectorizedArray<double> >’ and ‘dealii::VectorizedArray<double>’)
```

As far as I can tell compiler does not know how to subtract `VectorizedArray<T>` from a tensor of rank 0 (==scalar) `Tensor<0,2, VectorizedArray <T>>`

**Comment by kronbichler** [comment]
@davydden The file you link into, 
https://github.com/dealii/dealii/blob/master/include/deal.II/base/point.h#L500
has a `static_cast<Number>(this->values[i])` that you introduced in ebbb290, but the compiler error indicates that there is no `static_cast` in your code. Are you using the most recent version of deal.II on said cluster?

**Comment by davydden** [comment]
@kronbichler yes, i noticed that as well and yes, I am using the most recent `deal.II`.

**Comment by davydden** [comment]
@kronbichler let me investigate more, it could be indeed that I am using an older version...

**Comment by kronbichler** [comment]
But then the compiler must pick up a `point.h` that is not the current version.

**Comment by kronbichler** [comment]
Because the compiler shows line 500 that is not the one in the current code.

**Comment by davydden** [comment]
@bangerth @kronbichler sorry for the noise. In July I used a _patched_ version of `dealii` installation which uses specific commit instead of the HEAD of _master_ branch and I completely forgot about it. My bad.
