### ISSUE TITLE
Add more functionality to IDA.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#5042]
IDA supports also `root_finding` and more elaborate initial condition computation. These should be added to our interface, together will all of the other configuration parameters that are available. 

For example, it allows for automatic computation of the Jacobian (which is possible only for small systems), and provides its own set of solvers which we now ignore, forcing the user to provide solving routines. 

We decided that for the typical FEM situation, we would need anyway to provide our own solvers, but this is not mandatory if one is interested in solving small, contained, systems of equations...

**Comment by drwells** [comment]
We've made a lot of independent progress on SUNDIALS recently that is tracked elsewhere.
