### ISSUE TITLE
doxygen: undocumented classes/members and warnings

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5054]
Based on #5053, I think we should figure out a way to deal with mistakes that can lead to members not showing up in doxygen. Things I have found out:
1. We can enable https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_warn_if_undocumented but that leads to 3000+ warnings. Most of them are not useful (all the internal classes, many warnings in .cc files, which we started running through doxygen, etc.)
2. We could enable https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_extract_all but then we get a lot of internal/undocumented functions/classes
3. The problem in #5053 was that the namespace was not documented. It turns out that this doesn't even generate a warning.
4. I am not 100% confident, but it looks like we need to have a comment block in front of every namespace (even if there is a documentation block for it in some other file). Otherwise members won't show up (except nested and documented namespaces).

Before I go ahead with anything: any suggestions on what to do? My suggestion:
1. after testing observation 4 again, enforce that each namespace is documented (write a script to check this?)
2. turn on ``extract_all`` and surround all internal stuff with ```#ifndef DOXYGEN``
3. check if we can then turn on warnings for undocumented classes/functions

**Comment by davydden** [comment]
your suggestion sounds good to me but i would probably just do (1).

**Comment by tjhei** [comment]
> your suggestion sounds good to me but i would probably just do (1).

There are around 400 places where a namespace is currently not documented, so we can fix those. But if we only do that, undocumented class/functions will still be missing.

**Comment by davydden** [comment]
> undocumented class/functions will still be missing.

I think/hope we don't have as many issues in this category, i would guess at most just a couple.

**Comment by tjhei** [comment]
> I am not 100% confident, but it looks like we need to have a comment block in front of every namespace (even if there is a documentation block for it in some other file). Otherwise members won't show up (except nested and documented namespaces).

So I tested this again and I can not reproduce it. Back to square one then.

**Comment by drwells** [comment]
We have decent CI for doxygen warnings now so this isn't a big deal any more.
