### ISSUE TITLE
FindBZIP2.cmake should respect BZIP2_DIR variable.

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5063]
I recently had a problem where our config ignored `DBZIP2_DIR=` and picked up `bzip2` from `/usr/*`:
```
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#            BZIP2_VERSION = 1.0.6
#            BZIP2_DIR = /spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/bzip2-1.0.6-4vcfqu3netbuizhbtflvsrliinx7jogd
#            BZIP2_INCLUDE_DIRS = /usr/include
#            BZIP2_LIBRARIES = /usr/lib64/libbz2.so
```
Apart from the unwanted surprise, the problem is that `/usr/lib64/libbz2.so` is there on log-in nodes, but isn't on calculation nodes.

My understanding that for this case we eventually call https://github.com/dealii/dealii/blob/master/cmake/macros/macro_configure_feature.cmake#L126

Judging from [CMake docu](https://cmake.org/cmake/help/v3.0/command/find_package.html), i think we should add `NO_CMAKE_PATH` so that it starts from point (2):

> \<package\>_DIR
CMAKE_PREFIX_PATH
CMAKE_FRAMEWORK_PATH
CMAKE_APPBUNDLE_PATH

@tamiko ping.

p.s. I know that I can override it with `-DBZIP2_FOUND=TRUE,...`

**Comment by tjhei** [comment]
Is this the same problem as https://groups.google.com/d/topic/dealii/19snsi6qJ_k/discussion ?

**Comment by davydden** [comment]
i don't know, the thread is long and I have not read it.

**Comment by davydden** [comment]
looking through the discussion, i think it's somewhat different. On Cluster+Spack I have almost nothing in system default locations (that's the whole point to keep things consistent and use libraries consistently to avoid problems discussed in that thread). So it's not that I have half of the dependencies installed to `/usr/` prefix and the rest is in custom `/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/*`. The installation of `petsc` is also clean, namely it links only against packages from Spack plus main external (gcc+openmpi+pthreads, etc), i.e.
```
$ ldd /home/woody/iwtm/iwtm108/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/petsc-3.7.6-isaidg43jcoe2icgx77g76tnddehqsol/lib/libpetsc.so | grep "libz"
	libz.so.1 => /home/woody/iwtm/iwtm108/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-yrijbmajetpxrkyaa4uclsyw62zbhc5m/lib/libz.so.1 (0x00007fb6928ee000)
```

**Comment by tamiko** [comment]
The `FindBZIP2.cmake` module simply never uses a corresponding `BZIP2_DIR` variable.
We usually supply such a variable as a `HINT`, i.e. it has priority over the default paths.

**Comment by davydden** [comment]
> The FindBZIP2.cmake module simply never uses a corresponding BZIP2_DIR variable.

are you saying this line https://github.com/dealii/dealii/blob/master/cmake/macros/macro_configure_feature.cmake#L126 is not being called at all?

**Comment by davydden** [comment]
... if it is being called, why don't we have a solution for all, namely add `${_feature}_DIR` as a hint if it is defined. But as I said above, [documentation](https://cmake.org/cmake/help/v3.0/command/find_package.html) suggests that it should be used **if we add NO_CMAKE_PATH to that call**.

**Comment by tamiko** [comment]
Because I would prefer to not change such a fundamental configuration option. Completely removing the cmake variable `CMAKE_PREFIX_PATH` from the configuration logic is certainly nothing we should do.

**Comment by tamiko** [comment]
In hindsight the whole `FEATURE_DIR` idiom was an unfortunate choice.

Instead a user should always populate `CMAKE_PREFIX_PATH` with installation prefixes that should take precedence over default locations. This is universally supported by any `FindPACKAGE.cmake` module (and the project configuration logic).

**Comment by tamiko** [comment]
@davydden And reading the documentation myself. I'm afraid this will not solve the problem. The documentation is about finding other project configurations (for example our `deal.IIConfig.cmake` configuration. However, BZIP2 is configured with the module logic `FindBZIP2.cmake`.
This module internally calls `find_library` [1], `find_path`, etc. Those calls however do not honor a `PROJECT_DIR` variable at all.

[1] https://cmake.org/cmake/help/v3.0/command/find_library.html

**Comment by davydden** [comment]
Please, read the bottom of https://cmake.org/cmake/help/v3.0/command/find_package.html where search paths are discussed. What I suggest is supported by Cmake

**Comment by tamiko** [comment]
@davydden I read the relevant documentation again. I am still convinced I interpreted the documentation correctly and my short description above is what is happening.

But, let's step back for a second and simply test the two solutions.

With the current master version
 -  `cmake -DCMAKE_PREFIX_PATH=/tmp/bzip2` -> picks up the bzip2 installation in `/tmp/bzip2`
 -  `cmake -DBZIP2_DIR` -> warning `BIZP2_DIR` unsused and wrong installation chosen.

With my proposed fix of our `FindBZIP2.cmake` module (to behave like every other of our module does):
 -  `cmake -DCMAKE_PREFIX_PATH=/tmp/bzip2` -> picks up the bzip2 installation in `/tmp/bzip2`
 -  `cmake -DBZIP2_DIR` -> picks up the bzip2 installation in `/tmp/bzip2`

By adding `NO_CMAKE_PATH` to every relevant call [1]
 - `cmake -DCMAKE_PREFIX_PATH=/tmp/bzip2` -> ignores hint, finds no library
 - `cmake -DBZIP2_DIR` -> warning `BIZP2_DIR` unsused, finds no library
 - `cmake` (no hint) -> finds no library



[1]
```
diff --git a/cmake/macros/macro_configure_feature.cmake b/cmake/macros/macro_configure_feature.cmake
index dd6e0de50c..82e13d6909 100644
--- a/cmake/macros/macro_configure_feature.cmake
+++ b/cmake/macros/macro_configure_feature.cmake
@@ -123,7 +123,7 @@ ENDMACRO()
 # Default macro for finding an external library:
 #
 MACRO(FEATURE_FIND_EXTERNAL _feature _var)
-  FIND_PACKAGE(${_feature})
+  FIND_PACKAGE(${_feature} NO_CMAKE_PATH)
   IF(${_feature}_FOUND)
     SET(${_var} TRUE)
   ENDIF()
diff --git a/cmake/modules/FindBZIP2.cmake b/cmake/modules/FindBZIP2.cmake
index e09106c6af..2e11a690ec 100644
--- a/cmake/modules/FindBZIP2.cmake
+++ b/cmake/modules/FindBZIP2.cmake
@@ -31,7 +31,7 @@
 
 # temporarily disable ${CMAKE_SOURCE_DIR}/cmake/modules for module lookup
 LIST(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
-FIND_PACKAGE(BZip2)
+FIND_PACKAGE(BZip2 NO_CMAKE_PATH)
 LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
 
 SET(BZIP2_VERSION ${BZIP2_VERSION_STRING})
```

**Comment by davydden** [comment]
@tamiko i stand corrected. I mis-read the most crucial part of the documentation https://cmake.org/cmake/help/v3.0/command/find_package.html

> 1. Search paths specified in cmake-specific **cache variables**
> ...
> 2. These are intended to be set in the **user’s shell configuration**

I somewhat thought that both are cmake's variables.
