### ISSUE TITLE
hp/step-3c fails due to round-off error changes.

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#5088]
hp/step-3c fails [1] due to round-off error changes. The change in output might be architecture and/or compiler dependent.

It would be nice if someone fixes it.

[1] https://cdash.kyomu.43-1.org/testDetails.php?test=46118264&build=11400

**Comment by tamiko** [comment]
*mhm* #5094 did not fix it - we actually have a small number of rounding errors of order 10^-6. :-(

https://cdash.kyomu.43-1.org/testDetails.php?test=46219441&build=11424

**Comment by bangerth** [comment]
Should be fixed by #5102.
