### ISSUE TITLE
fe/fe_move* tests failing with clang

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#5118]
it seems that the two tests are a bit overly strict about testing the state of the moved object [1].

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=11522

@masterleinad *ping*

**Comment by tamiko** [comment]
Correction: We might simply need an output variant because clang with libstdc++ has different object sizes.

**Comment by masterleinad** [comment]
> We might simply need an output variant because clang with libc++ has different object sizes.

I totally agree and would have done this already if I had the failing setup around...

**Comment by tamiko** [comment]
@masterleinad Will do.

**Comment by davydden** [comment]
@tamiko see if https://github.com/dealii/dealii/pull/5129 fixes it for you.

**Comment by masterleinad** [comment]
Closed by #5129.
