### ISSUE TITLE
over-subscription in MPI tests

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5123]
A colleague of mine came across an issue while running MPI tests in deal.II. Namely, all tests which need more processors than available fail with the error

>There are not enough slots available in the system to satisfy the #number slots" is thrown.

It looks like this can be solved with _over-subscription_ (see: https://www.open-mpi.org/faq/?category=running#oversubscribing) when calling `mpirun`.
Probably some mpi vendors/installation do that automatically, but apparently not all (`openmpi` did not on hist system but I have no problems with it on macOS).

It would be good to be able to make those tests with high number of MPI cores pass even when user's machine are limited to, say, 6 cores. Alternative is to skip such tests with some CMake magic.

@tamiko ping.

**Comment by bangerth** [comment]
Bizarre. In 18 years of using MPI I've never come across this issue.

Most of our tests run pretty quickly, so I would say we should just explicitly over subscribe (as we always do anyway).

**Comment by davydden** [comment]
@BenBrands could you provide some more details w.r.t. your setup (platform, CPU, OS, openmpi version, compiler)

**Comment by BenBrands** [comment]
The processor is an Intel i7-6800 with 6 cores. The OS is Ubuntu 16.04 and Open MPI 3.0.0 compiled with gcc 6.3.0.

**Comment by tjhei** [comment]
You should be able to set 
```
export OMPI_MCA_rmaps_base_oversubscribe=1
```
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849974

**Comment by davydden** [comment]
> You should be able to set

but don't we want this to work automatically somehow so that users don't need to bother with this?

**Comment by tjhei** [comment]
Ideally, sure. We would need to detect what MPI version we are running to check if we need to pass ``--map-by socket:OVERSUBSCRIBE`` or set the env variable while running the testsuite.

**Comment by davydden** [comment]
I can confirm this issue with `openmpi@3.0`, was not the case with `2.1.1`.

**Comment by drwells** [comment]
On my machine `mpirun --version` prints

```
$ mpirun --version
mpirun (Open MPI) 2.1.1

Report bugs to http://www.open-mpi.org/community/help/
```

so we can probably do this by setting an environment variable in `run_test.sh` after inspecting the output of that command.

**Comment by marcfehling** [comment]
Just for completion:
I stumbled over this issue again with the latest release of OpenMPI 4.0.0. However, this was related to a typo that has been fixed upstream: https://github.com/open-mpi/ompi/pull/6139

Don't use OpenMPI 4.0.0 for testing.
