### ISSUE TITLE
dofs/interpolate_q_system_mixed_01.debug

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5128]
```
2856: --------------------------------------------------------
2856: An error occurred in line <2639> of file </Users/davydden/spack/var/spack/stage/dealii-develop-rixvq6nkgcckw37plkmfyiyrkaxmebsv/dealii/source/fe/fe_values.cc> in function
2856:     dealii::FEValuesBase<1, 1>::FEValuesBase(const unsigned int, const unsigned int, const dealii::UpdateFlags, const Mapping<dim, spacedim> &, const FiniteElement<dim, spacedim> &) [dim = 1, spacedim = 1]
2856: The violated condition was:
2856:     n_q_points > 0
2856: Additional information:
2856:     (none)
2856: --------------------------------------------------------
```

UPDATE: 

looks like this test pass with 04ded8f990f6ce02a625c48038308f478c57049b

**Comment by davydden** [comment]
same here, also fails on all testers https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=dofs%2Finterpolate_q_system_mixed_01.debug&date=2017-09-22

**Comment by davydden** [comment]
bisecting...

**Comment by masterleinad** [comment]
It's
> commit 00314125da1e30f8eebe27512eda86af3685479a
> Author: Matthias Maier <tamiko@43-1.org>
> Date:   Thu Sep 7 17:14:48 2017 -0500
>
>   Add FETools::convert_generalized_support_point_values_to_dof_values

isn't it?

**Comment by davydden** [comment]
broken by 00314125da1e30f8eebe27512eda86af3685479a

**Comment by bangerth** [comment]
Yes, as mentioned in #4857. @tamiko -- you promised to fix these tests several days ago, what's the status?
