### ISSUE TITLE
serialization/[dof_handler_01|triangulation_01|triangulation_02] fails with newest clang

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5133]
```
2 20 0 0 1 3 4 2 3 4 6 7 5 6 7 9 10 8 9 10 11 12 13 4 0 2 5 8 13 0 0 -1 7 34 FESystem<1>[FE_Q<1>(2)-FE_Q<1>(1)] 23 Policy::Sequential<1,1>
```
vs
```
2 20 0 0 1 3 4 2 3 4 6 7 5 6 7 9 10 8 9 10 11 12 13 4 0 2 5 8 13 1 7 34 FESystem<1>[FE_Q<1>(2)-FE_Q<1>(1)] 23 Policy::Sequential<1,1>
```
somewhat similar in `triangulation`. Probably can just add another output...

**Comment by tamiko** [comment]
I see quite a number of serialization issues with clang-5.0.0 (and libc++) as well [1].
@davydden Was this with the newest clang version on Mac (corresponding to llvm/clang-5.0.0)?

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=11655

**Comment by davydden** [comment]
Yes, it’s the newest 9.0.0

**Comment by masterleinad** [comment]
@davydden Can you reproduce any problems anymore? At least [CDash](https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=serialization%2Fdof_handler_01.debug&date=2017-12-27) doesn't show any problems.

**Comment by davydden** [comment]
@masterleinad 

> Can you reproduce any problems anymore?

indeed, it is not an issue now. Probably it was related to that `singleton` thing in Boost as I still have `Apple LLVM version 9.0.0`, so compiler did not change since September.
