### ISSUE TITLE
add FiniteElement::extract(ComponentMask)

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5155]
We have many places in the code where we want to check that some part of an FESystem that we act on (interpolate, project, ...) is a specific element or has specific properties. This is quite awkward. See #5151 for example. I think we should introduce something like:
```
const FiniteElement& FiniteElement::extract(ComponentMask&) const
```
that drills down into an arbitrarily nested ``FESystem`` and returns the object in question (by going down the tree as far as possible). If the ``ComponentMask`` doesn't map to a single FE or a single`` FESystem``, throw an exception.

Makes sense? Is ``extract`` a good name?

**Comment by bangerth** [comment]
I like this idea. And you'd get an exception if the component mask spans more than one element.

Maybe `extract_base_element(...)` or `get_base_element(...)`?

**Comment by tjhei** [comment]
> And you'd get an exception if the component mask spans more than one element.

Yes, but I would like to count a nested system as a single element. Example:

``FESystem<2>(FE_BDM(k),1,FE_DGP(k-1))`` queried for the first 2 components would return the ``FE_BDM``.
``FESystem<2>(FE_Q(k),2,FE_Q(k-1))`` queried for the first 2 components would fail.
``FESystem<2>(FESystem(FE_Q(k),2),1,FE_Q(k-1))`` queried for the first 2 components would give the inner FESystem.
``FESystem<2>(FESystem(FE_Q(k),1),1)`` queried for the first (and only) component would return the ``FE_Q``.

> Maybe extract_base_element

Hm. We use "base elements" as the collection of items *directly* contained inside the ``FESystem``, right? Maybe use something like "child" or "subset"?
