### ISSUE TITLE
Failing SLEPc tests

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5179]
Trying to close #5141 I noticed that after configuring PETSc with  `--download-hypre --download-mumps --download-scalapack --download-parmetis --download-metis` even more SLEPc tests are failing with surprising error messages:

`fe/fe_enriched_step-36`, `fe/fe_enriched_step-36b`, `slepc/solve_01.debug`, `slepc/solve_04.debug`, `slepc/step-36_parallel.mpirun=3.debug`, `slepc/step-36_parallel_02.mpirun=3.debug`, `slepc/step-36_parallel_03.mpirun=3.debug`
> 3093: fe/fe_enriched_step-36.debug: RUN failed. ------ Return code 1
3093: fe/fe_enriched_step-36.debug: RUN failed. ------ Result: /mnt/data/darndt/Sources/dealii/build/tests/fe/fe_enriched_step-36.debug/failing_output
3093: fe/fe_enriched_step-36.debug: RUN failed. ------ Partial output:
3093: Cycle 0
3093:    Number of active cells:       120
3093:      FE / POUFE :                120 / 8
3093:    Number of degrees of freedom: 1432
3093: [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
3093: [0]PETSC ERROR: Invalid argument
3093: [0]PETSC ERROR: A is a non-square matrix
3093: [0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
3093: [0]PETSC ERROR: Petsc Release Version 3.6.3, Dec, 03, 2015 
3093: [0]PETSC ERROR: /mnt/data/darndt/Sources/dealii/build/tests/fe/fe_enriched_step-36.debug/fe_enriched_step-36.debug on a arch-linux2-c-opt named simserv02 by darndt Mon Oct  2 17:39:18 2017
3093: [0]PETSC ERROR: Configure options CXXOPTFLAGS=-O3 --with-debugging=0 --download-hypre --download-mumps --download-scalapack --download-parmetis --download-metis

Has anyone seen this before?

**Comment by davydden** [comment]
extremely weird, never saw that.

**Comment by masterleinad** [comment]
This might be a compatibility issue with `PETSc 3.6.3` and `gcc-7.2.0`.

**Comment by masterleinad** [comment]
After recompiling everything correctly, this also works for `PETSc 3.6.3` and `gcc-7.2.0`.
