### ISSUE TITLE
Unable to install with Trilinos and MPI

### ISSUE THREAD

**Issue by jtceleron** [dealii/dealii#5191]
Hello guys, 

I am having a hard time to install deal.II with Trilinos and MPI. Could anyone, who have successfully installed Trilinos and MPI and deal.II, provide a list of (related) installed packages as well as system configurations? I am currently using Ubuntu 16.04. But any system would be okay, since I can work on a virtual machine...

**Comment by davydden** [comment]
Me preferred set of “instructions” are in this python package manager https://github.com/dealii/dealii/wiki/deal.II-in-Spack

**Comment by drwells** [comment]
You may be able to find more information by posting this message on the [mailing list](https://groups.google.com/forum/#!forum/dealii).

I do not use Ubuntu myself, but it looks like it is possible to install openmpi and trilinos through `apt`: see [this page](https://dealii.org/8.5.0/external-libs/trilinos.html) for a list of trilinos components we require.

If you install these things through apt then you should be able to install deal.II in a user directory. Spack can do all of this too.

**Comment by bangerth** [comment]
Maybe as a general rule, there is really nothing concrete we can help you with if you only say "having a hard time". What is it that is not working? What are your error messages?

If you don't want to install packages by hand, take a look at the "candi" installer that's linked to from the download page. It downloads and installs everything you need!

**Comment by jtceleron** [comment]
Thank you! This is really the kind of short answers I wanted... I will try both suggestions, Spack and candi installer..

Installing packages by band is really an annoying job. For example, it seems g++ 5.4 (which is Ubuntu 16.04 LTS default) does not support some compile flags which are in dealii tests.

On Ubuntu 17.04, I can successfully proceed to make install step. All the required packages can be easily installed via apt-get. However the make install is stuck in building targets...

**Comment by drwells** [comment]
@jtceleron Let us know if you have more trouble :)
