### ISSUE TITLE
Group matrix-free cell blocks based on predicate (ie material ID)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5197]
In some applications, it would be good to have non-overlapping sets of cells for operator application. Within each group one would then do coloring for TBB and group single cells into SIMD groups.

Examples: fluid-structure interaction, solid mechanics with heterogeneous material (ie brain impact problem), etc.

Ps. Sorry for brevity, writing from phone. Will expand description later.

**Comment by kronbichler** [comment]
I already have a code for the grouping into SIMD based on user input in the pipeline. I hope to continue with the DG stuff where it is included in the following weeks.

**Comment by kronbichler** [comment]
For TBB there is no equivalent yet, but since the data structures in `MatrixFree` are going to change significantly I would propose to not start now unless you have very pressing needs in the next month.

**Comment by davydden** [comment]
Great!

Ps. I don’t have a pressing need. I just recalled this issue and wanted to document it while I remember. A master student of myself and @jppelteret had to do some workarounds to make it work with heterogeneous materials, that’s how we came to know it.

**Comment by davydden** [comment]
@kronbichler 

> I hope to continue with the DG stuff where it is included in the following weeks.

i assume it's coming and https://github.com/dealii/dealii/pull/5870 is the first step in that direction?

**Comment by kronbichler** [comment]
Yes, #5870 is the first big step. I hope to be faster with the next ones, though.
