### ISSUE TITLE
Tester: add a container testing everything with Spack

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5207]
In recent months we have added a lot of interfaces to third-party libraries. I think we ought to have at least one tester with **everything turned on**, i.e.:
```
Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = False )
#        DEAL_II_WITH_ADOLC set up with external dependencies
#        DEAL_II_WITH_ARPACK set up with external dependencies
#        DEAL_II_WITH_ASSIMP set up with external dependencies
#        DEAL_II_WITH_BOOST set up with external dependencies
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#        DEAL_II_WITH_CUDA set up with external dependencies
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_CXX17 = ON
#        DEAL_II_WITH_GSL set up with external dependencies
#        DEAL_II_WITH_HDF5 set up with external dependencies
#        DEAL_II_WITH_LAPACK set up with external dependencies
#        DEAL_II_WITH_METIS set up with external dependencies
#        DEAL_II_WITH_MPI set up with external dependencies
#        DEAL_II_WITH_MUPARSER set up with external dependencies
#        DEAL_II_WITH_NANOFLANN set up with external dependencies
#        DEAL_II_WITH_NETCDF set up with external dependencies
#        DEAL_II_WITH_OPENCASCADE set up with external dependencies
#        DEAL_II_WITH_P4EST set up with external dependencies
#        DEAL_II_WITH_PETSC set up with external dependencies
#        DEAL_II_WITH_SLEPC set up with external dependencies
#        DEAL_II_WITH_SUNDIALS set up with external dependencies
#        DEAL_II_WITH_THREADS set up with external dependencies
#        DEAL_II_WITH_TRILINOS set up with external dependencies
#        DEAL_II_WITH_UMFPACK set up with external dependencies
#        DEAL_II_WITH_ZLIB set up with external dependencies
```

I suggest that we use [Spack](https://github.com/dealii/dealii/wiki/deal.II-in-Spack) to do this. Two reasons:
1. It's the only automated way to install **all** dependencies (Candi lacks `ADOLC`, `ASSIMP`, `GSL`, `SUNDIALS`, `CUDA`, whereas, at the time of writing, `BOOST`, `SLEPC` and `TRILINOS` are outdated)
2. It's an actively developed project used by a number of HPC sysadmins around the world to manage huge stacks of software. So it's good to test `dealii` with the full software stack build by Spack (no system provided packages but compilers!).

We can choose any reasonable version of GCC, probably not too new as those might not be yet adopted by most HPC sites (i.e. in our cluster at FAU we still have 4.8.5...).

p.s. obviously, I can help setting things up, if there is something not clear from the link above.

**Comment by tamiko** [comment]
The official testing site `tester` currently has everything possible turned on (as was the case already for years :-) )
```
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#        DEAL_II_WITH_ADOLC set up with external dependencies
#        DEAL_II_WITH_ARPACK set up with external dependencies
#        DEAL_II_WITH_ASSIMP set up with external dependencies
#        DEAL_II_WITH_BOOST set up with external dependencies
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#      ( DEAL_II_WITH_CUDA = OFF )
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_CXX17 = ON
#        DEAL_II_WITH_GSL set up with external dependencies
#        DEAL_II_WITH_HDF5 set up with external dependencies
#        DEAL_II_WITH_LAPACK set up with external dependencies
#        DEAL_II_WITH_METIS set up with external dependencies
#        DEAL_II_WITH_MPI set up with external dependencies
#        DEAL_II_WITH_MUPARSER set up with external dependencies
#        DEAL_II_WITH_NANOFLANN set up with external dependencies
#        DEAL_II_WITH_NETCDF set up with external dependencies
#        DEAL_II_WITH_OPENCASCADE set up with external dependencies
#        DEAL_II_WITH_P4EST set up with external dependencies
#        DEAL_II_WITH_PETSC set up with external dependencies
#        DEAL_II_WITH_SLEPC set up with external dependencies
#        DEAL_II_WITH_SUNDIALS set up with external dependencies
#        DEAL_II_WITH_THREADS set up with external dependencies
#        DEAL_II_WITH_TRILINOS set up with external dependencies
#        DEAL_II_WITH_UMFPACK set up with external dependencies
#        DEAL_II_WITH_ZLIB set up with external dependencies
```

**Comment by tamiko** [comment]
Note, CUDA is disabled because this requires an NVIDIA graphics accelerator with drivers - something I don't have in these machine. @Rombur has set up a testing site for cuda.

**Comment by tamiko** [comment]
By the way, the other automated way of getting *all* dependencies for deal.II installed is using Gentoo linux - that's running on tester.

**Comment by tamiko** [comment]
@davydden What about I create an additional container with a minimal gentoo setup and simply test the spack installer (with full testsuite)?

**Comment by davydden** [comment]
> CUDA is disabled because this requires an NVIDIA graphics accelerator with drivers - something I don't have in these machine

fair enough. 

> all dependencies

you sure these are really all?

> Gentoo linux

My understanding is that in HPC context Ubuntu/Gentoo/etc packages are not of much help as you need to build against `mpi` configure/built for a given cluster.

> What about I create an additional container with a minimal gentoo setup and simply test the spack installer (with full testsuite)?

yes, that's roughly what I suggest, as long as we do it regularly (i.e. re-build dealii with changes in master branch).

p.s. I am not aware on which Linux the main CDash test are running, which build is it, what packages are enabled, etc. I don't think this information is documented anywhere. Could be it's only you who actually know this :smile:

**Comment by tamiko** [comment]
@davydden The live ebuild is currently not updated because I have literally no time at all to do that. Same with Debian.

**Comment by tamiko** [comment]
> My understanding is that in HPC context Ubuntu/Gentoo/etc packages are not of much help as you need to build against a custom mpi configured/built for a given cluster.

Just a side comment - given the fact that Gentoo is a source-based distribution, you can actually do that. (You can also use the gentoo package manager in a similar way than the whole spack design - i.e. building your own userland in a custom prefix.)

That said - In my opinion there is an immense gain of having deal.II packages for Debian, Ubuntu, Gentoo and Archlinux at least..

> p.s. I am not aware on which Linux the main CDash test are running, which build is it, what packages are enabled, etc. I don't think this information is documented anywhere. Could be it's only you who actually know this

Actually, I do not know out of my head and this regular changes depending on updates. I.e. `tester` usually runs with the newest version available, the `simserv04` site is frozen in time to a certain state.

The point is you do not need to know this at all. Simply go to `view notes` for a given test run: https://cdash.kyomu.43-1.org/viewNotes.php?buildid=11968

**Comment by tamiko** [comment]
@drwells *ping* Mind to update the archlinux package? :-)

**Comment by davydden** [comment]
> That said - In my opinion there is an immense gain of having deal.II packages for Debian, Ubuntu, Gentoo and Archlinux at least.

sure, some users just need to make it work quickly on their OS.

Anyway, we are drifting away from the main point: did you try building the full thing in Spack? You would need to explicitly enable a few variants which are `off` by default as they are not in any release yet: `spack install dealii@develop+optflags+adol-c+nanoflann+sundials+assimp`

**Comment by drwells** [comment]
@tamiko I already bundle the patches that we added for 8.5.1 into the arch linux build script; this is why I have procrastinated so much on updating it.

**Comment by drwells** [comment]
I'll update it at some point this week.

**Comment by drwells** [comment]
We are now updated in the AUR :)

**Comment by davydden** [comment]
@tamiko nevermind, I will setup the tester myself on a local unused Ubuntu machine. Will close the issue when I am done...

**Comment by davydden** [comment]
@tamiko ok, i think I did everything I wanted, builds are/will be in `experimental` section of CDash http://cdash.kyomu.43-1.org/index.php?project=deal.II where `build name`  identifies what the build is.

FYI, the bash script (less than 100 lines long) which does installation and testing is here https://github.com/davydden/dealii-testsuite-Spack/blob/master/dealii-spack-tests.sh

Note that it's just a single array variable which defines 6 different configurations of dealii to be tested:
```
declare -a SPECS=(
'^openmpi^openblas'
'^openmpi^intel-mkl'
'^openmpi^atlas'
'+int64^openmpi^openblas'
'^mpich^openblas'
'+optflags^openmpi^openblas');
```
without re-installing things which are the same between those builds :smile_cat:

**Comment by tamiko** [comment]
@davydden Roger - thanks a lot. I will have time to think about dealii development again hopefully end of this month :-/
