### ISSUE TITLE
Use an explicit NumberType template parameter value in FEEvaluation::get_symmetric_gradient

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5218]
As pointed out in [Google Groups](https://groups.google.com/forum/#!topic/dealii/XMiScYGR-tA):
> line 4545 of /include/deal.II/matrix_free/fe_evaluation.h:
  VectorizedArray<Number> half = make_vectorized_array (0.5);

> 0.5 is interpreted as double and it leads to using `make_vectorized_array<double>`. That is OK if Number=double but for any other type (eg. float) it results is compilation error. It should be replaced by:
  VectorizedArray<Number> half = make_vectorized_array<Number> (0.5);

**Comment by kronbichler** [comment]
I have this fixed on the DG branch but I guess it makes sense to fix it already now. Let's wait one more day if Michal Wichrowski wants to fix it, otherwise I can open a PR.
