### ISSUE TITLE
show how to output quadrature data in solid mechanics tutorials

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5219]
given how often on forums we have questions on output of quadrature data, I think we should extend tutorials to demonstrate this:

1. for continuous fields, one can do some simple L2 projection from quadrature points to some FE space to visualize stresses (i.e. step-8, step-44, step-18)
2. for fields which are expected to be discontinuous, recent developments with particle classes and alike may help writing the quadrature data as a collection of (second order symmetric tensor) values at a set of quadrature points (step-42)

**Comment by sairajat** [comment]
@davydden  I have recently implemented L2 projection of scalar quadrature point fields to the whole domain. 
I think I should be able to generalize that function and that would address part 1 in the above issue. 

Can you please guide me as to how a general function should be as per deal.ii norms?

This is what I thought, firstly, the function class needs to extended to take the point history as argument.
In that function, the user can decide which variable or variables needs to be interpolated (each to assumed an individual scalar field). 

This would be similar to [VectorTools::Project](https://www.dealii.org/8.5.0/doxygen/deal.II/namespaceVectorTools.html#af282602c17b8eb6afe47ef56fc417ecb)
except that the function now does not return data as per the location but needs to return it as per the quadrature point at which the integration is being done now in the matrix and rhs formulation for L2 projection.




Thanks.

**Comment by davydden** [comment]
@sairajat thanks for your will to help resolving this. As for (1), we have a [project function which takes std::function() to return scalar quadrature data](https://www.dealii.org/developer/doxygen/deal.II/namespaceVectorTools.html#ac03bd09f7225d0e12139428004655641).  So one could call this, say, for each component of 2nd order symmeric tensor. And if you use FE for which matrix-free works, then there won't be even any mass-matrix assembly involved.

However, judging from your comment

> This is what I thought, firstly, the function class needs to extended to take the point history as argument.
In that function, the user can decide which variable or variables needs to be interpolated (each to assumed an individual scalar field).

perhaps you have something else in mind. Could you please elaborate?

**Comment by sairajat** [comment]
@davydden  I just looked at the function you mentioned. This function was not there until 8.3 and hence I recently implemented it on my own. 

This is exactly what I had in mind except in place of ```std::function()```, we could pass a ```function``` class object which returns data based on ```cell iterator``` and ```quadrature point``` number.

> And if you use FE for which matrix-free works, then there won't be even any mass-matrix assembly involved.

I don't know much about matrix-free implementation. Can you please tell me which ```FE``` supports this. I have FE_Q<dim>(p) where 1 <= p <=3.

**Comment by sairajat** [comment]
Thank you professor. I was able to use this instead of the routine I wrote myself.

Thanks again.

**Comment by drwells** [comment]
This is a decent idea for a tutorial (or a tutorial extension). Rather than keep this and the other tutorial issues I migrated it over to 

https://github.com/dealii/dealii/projects/22
