### ISSUE TITLE
Clean up mandatory ZLIB dependendy

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5317]
It turns out that we rely on linking to a `boost` library that has `zlib` support in `iostreams` (also see #5289). For the bundled version, we currently simply don't build `iostreams` at all in this case. Unfortunately, this gives the same undefined references as in #5289. That means that we technically require `zlib` in one way or the other.

One possibility is to just fix up the places where `iostreams` is used and simply assert that deal.II is configured with `DEAL_II_WITH_ZLIB=ON`. This currently breaks 264 tests in debug mode for me.
All of them are MPI tests so I assume that they are all related to the use of `iostreams` in
`ParallelDistributed<DoFHandlerType>::renumber_dofs` (`source/dofs/dof_handler_policy.cc`).

Another option might be to just require `zlib` support (and bundle it) if using the bundled `boost`. Since this has not be an issue for anyone yet, this might not be too restrictive (especially for `MPI` as we already need `p4est` to be compiled with `zlib`).

Opinions?

**Comment by bangerth** [comment]
We also need zlib for compressed VTU output. 

I know that this has been discussed before (though I don't recall where), but can't we just *require* zlib? Then, if some external boost is not linked against zlib, we just revert to the bundled one, which we know we can link against zlib (because we have required zlib).

**Comment by davydden** [comment]
> if some external boost is not linked against zlib, we just revert to the bundled one

If external boost was provided and it does not satisfy requirements, the Cmake config should fail with some message. Otherwise users might think that it worked and they link against external one.

**Comment by masterleinad** [comment]
I went ahead to implement a solution in #5318. The idea is to just require `zlib` if we build the bundled `boost`. This seems to be minimally invasive.

**Comment by drwells** [comment]
I am (slightly) opposed to requiring zlib without bundling it because then users on Windows will need to install non-bundled components to get deal.II working.

**Comment by masterleinad** [comment]
> I am (slightly) opposed to requiring zlib without bundling it because then users on Windows will need to install non-bundled components to get deal.II working.

The important point here is that (currently) we require zlib already in one way or the other, i.e. we can't compile deal.II (wiothout undefined references) if zlib is not available on the system.

**Comment by drwells** [comment]
I may have misunderstood your original post: does this issue only show up if we require MPI?

**Comment by masterleinad** [comment]
Yes, it turns out that we only get `undefined references` if compiling with `MPI` and `p4est`.

**Comment by tjhei** [comment]
> but can't we just require zlib?

I prefer not to have this hard dependency. 

> they are all related to the use of iostreams in
> ParallelDistributed<DoFHandlerType>::renumber_dofs

Hang on, this is easy to fix. I will prepare a patch after I can reproduce the build errors here.

**Comment by masterleinad** [comment]
I can confirm that the testsuite passes compiling with `DEAL_II_WITH_ZLIB=OFF` and `DEAL_II_WITH_P4EST=OFF`.
