### ISSUE TITLE
Failing test: numerics/data_out_filter_01

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5337]
`numerics/data_out_filter_01` seems to fail on all [machines](https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=numerics/data_out_filter_01.debug&date=2017-10-27).

@gassmoeller Would you mind to take a look if the stored or the generated output is correct?

**Comment by gassmoeller** [comment]
Sorry for that, I changed the functionality before the merge of #5261 and forgot the adjust the test accordingly. #5341 should fix the results (and adjusts the test to the new functionality).
