### ISSUE TITLE
Design flaw in vector_tools.templates.h: transform()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5364]
This function looks like this (after #5345 and #5363 ):
```cpp
    template <int dim, int spacedim, typename FEValuesType, typename T3>
    void transform(const typename FiniteElementData<dim>::Conformity conformity,
                   const unsigned int offset,
                   const FEValuesType &fe_values_jacobians,
                   T3 &function_values)
    {
      switch (conformity)
        {
        case FiniteElementData<dim>::Hcurl:
          // See Monk, Finite Element Methods for Maxwell's Equations,
          // p. 77ff, formula (3.76) and Corollary 3.58.
          // For given mapping F_K: \hat K \to K, we have to transform
          //  \hat u = (dF_K)^T u\circ F_K

          for (unsigned int i = 0; i < function_values.size(); ++i)
            {
              const auto &jacobians =
                fe_values_jacobians.get_present_fe_values().get_jacobians();

              auto shifted_view = boost::make_iterator_range(
                                    std::begin(function_values[i]) + offset,
                                    std::begin(function_values[i]) + offset + dim);
              std::array<typename T3::value_type::value_type,dim> old_value;
              std::copy(std::begin(shifted_view),
                        std::end(shifted_view),
                        std::begin(old_value));

              // value[m] <- sum jacobian_transpose[m][n] * old_value[n]:
              TensorAccessors::contract<1, 2, 1, dim>(
                shifted_view, jacobians[i].transpose(), old_value);
[...]
```

The problem, now, is the following: `function_values` is both an input argument (transmitted through the `old_value` argument to the `contract` function) and an output argument (transmitted to that same place via the `shifted_view` argument into which `contract` writes its results).

The problem, now, is that that implies that the result of multiplying `old_value` by a Jacobian can be stored in the same data type. This is not always the case, however. The case that I'm running into is that the input vector is over `std::complex<float>`, and the Jacobians are of course stored as `double` objects. But the product of `std::complex<float>` and `double` is a `std::complex<double>`, and so the compiler complains (rightfully) that it can't find an overload of `TensorAccessor::contract` that takes an array of `std::complex<float>` as output argument.

@tamiko -- what's your opinion about this? I think that the right approach would probably be to separate input and output arguments of this function, and make sure that the output argument has the correct type -- namely some kind of array over `decltype(jacobians[0].transpose()[0][0] * old_value[0])`.

edited by @drwells: enable syntax highlighting

**Comment by tamiko** [comment]
@bangerth I have the feeling that not the `transform` function alone is the problem but the fact that we use `double` values while manipulating a `Vector<std::complex<float>>`. I am just thinking about this: Even if we modify this function, i.e., we input a `Vector<std::complex<float>>` and return a transformed `Vector<std::complex<double>>` you have to cast the `std::complex<double>` back to a `std::complex<float>` later on anyway.

It might be simpler and more pragmatic to transform the jacobians into `float`s.

**Comment by tamiko** [comment]
@bangerth Unfortunately, I haven't found time to finish support for complex values and generalized support points yet. I hope to find half a week to get the rest done soon. (Actually mid/end of this week finally looks good :-) )

**Comment by bangerth** [comment]
I'm not sure. I guess it's true that you have to get back to the type of the solution vector, which is `std::complex<float>`, but I don't know where that has to happen. You suggest that we should convert the Jacobians to `float`, but that seems wrong too: the type of the solution vector is `std::complex<float>`, so if anything that's what it should be converted to. Not sure whether that's the right strategy.

In any case, I think that this conversion should not happen in the `transform()` functions. These functions have a fairly clearly defined semantic context, and should respect the type system of multiplying a value (of underlying type `T`) by something related to the shape functions (of underlying type `double`). My sense is that the conversion back to something else should happen in the function that lives at a higher semantic context, i.e., `interpolate()` or its immediate helpers.

**Comment by davydden** [comment]
> My sense is that the conversion back to something else should happen in the function that lives at a higher semantic context, i.e., interpolate() or its immediate helpers.

:+1:

**Comment by tamiko** [comment]
Yes, I agree (and this is essentially what I tried to say).

A simple solution for this problem is probably to create the temporary vectors (that we need anyway) with the correct scalar result type `std::complex<double` (and leave `transform` and everything else as it is) and in the last step (lines 442 - 468) convert from double to float.

**Comment by bangerth** [comment]
Well, I have to change `transform()` somehow because the input and arguments of the `contract` call do not match the types I have in that function. Let me think about this a bit.

**Comment by bangerth** [comment]
Related in some sene to #2033.
