### ISSUE TITLE
 DoFRenumbering::subdomain_wise fails with p::s::Tria

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#5376]
In subdomain_wise, you allocate array like that

https://github.com/dealii/dealii/blob/78b76649de62dae7513458922076c67676f76cd3/source/dofs/dof_renumbering.cc#L1881

Later, the function calls renumber_dofs, which has the following assert

https://github.com/dealii/dealii/blob/78b76649de62dae7513458922076c67676f76cd3/source/dofs/dof_handler.cc#L1107

which gets triggered for shared triangulation ran on > 1 MPI processes. Is this intented?

**Comment by bangerth** [comment]
It's probably not intended. Can you put together a simple, self-contained testcase that triggers the assertion?

**Comment by agrayver** [comment]
I took the courage to propose a fix in #5412
