### ISSUE TITLE
ParameterHandler print_parameter latex and escaping

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5378]
``print_parameters(LateX)`` should escape ``_`` in sections, values, and documentation.

I will take a look at it when I have a few minutes of spare time.

**Comment by bangerth** [comment]
I think you're going to run into problems in the documentation because you have to exclude underscores in formulas. Also in verbatim and texttt. But it's a nobrainer in names values and sections.

**Comment by tjhei** [comment]
My idea:
1. escape in section names, parameter names, and default values
2. leave documentation as is (user has to escape _ outside formulas)
3. leave index names as is (these are the ``\label`` and ``\index`` entries) because they require no escaping.

I hope that works. ;-)

**Comment by tjhei** [comment]
default values should probably be displayed as ``\verbatim`` (for example if it is a string that contains a latex formula or just a ``$``)
