### ISSUE TITLE
Fix Documentation of FEFieldFunction::compute_point_locations

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5413]
```
     [...]  @p points[maps[3][4]] ends up as the 5th
     * quadrature point in the 4th cell. This is where optimization would
     * help. This function returns the number of cells that contain the given
     * set of points.
```
That doesn't make any sense. ``points[x]`` is a ``std::vector<Point>`` not a ``Point``.

**Comment by tjhei** [comment]
And I fail at reading. All of this is correct. Oops.

**Comment by tjhei** [comment]
Well, I still don't understand "This is where optimization would help". :man_shrugging:

**Comment by bangerth** [comment]
I don't understand this sentence either. Who wrote this sentence?

**Comment by bangerth** [comment]
Nice use of an emoji, btw! ;-)

**Comment by tjhei** [comment]
Scrolling back in the history it looks like this gem has been there for many years.

**Comment by bangerth** [comment]
Let's get this fixed. Someone remembers what the comment refers to?
