### ISSUE TITLE
[RFC] Remove template argument of `FunctionTime`

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#542]
When the type argument was added to `Tensor`, `Point` and `Function`, someone went a bit overboard and added such a type also to `FunctionTime` -- which now allows to store the *time* as a complex-valued number :-)

I don't see anyone using `FunctionTime` by itself other than as a base class for `Function`, so removing its template argument again should not cause too much trouble.

Opinions?

**Comment by luca-heltai** [comment]
Actually, having a templated FunctionTime also allows for Sacado types to be used. Maybe not a complex type, but automatic differentiation with time dependent functions, why not?

L.

--
Luca Heltai <luca.heltai@gmail.com>
http://people.sissa.it/~heltai/
Scuola Internazionale Superiore di Studi Avanzati
Phone:  +39 040 3787 449, Office: 622
--
There are no answers, only cross references

**Comment by bangerth** [comment]
Fair enough. In that case, let's rename the template argument `TimeType` and document the intended use of the template argument in the class docs.

**Comment by bangerth** [comment]
Given the arguments we've had elsewhere, I'll leave the name of the scalar type as it is, but document its intent.
