### ISSUE TITLE
AD number types broke compilation

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5420]
looks like https://github.com/dealii/dealii/pull/5382 broke testers https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=12975

Probably some number types are being expanded regardless of Sacado being around. 

@jppelteret can you please have a look?

**Comment by jppelteret** [comment]
I'm guessing that we need to remove the leading `::` from `::adouble` on [this line](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_adolc.cmake#L72). I'm testing a patch and will have a PR for this shortly.

**Comment by davydden** [comment]
p.s. i have the same issue on Ubuntu 16.04 with GCC 5.4.0.
