### ISSUE TITLE
checking: file permissions and line endings

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5426]
We could automatically check line endings and permissions of files when we run "make indent". That would highlight the problems during code review and something like #5425 won't be necessary. Thoughts?

**Comment by bangerth** [comment]
I don't know how to detect the line ending, just how to change things. File permissions are simpler for sure!

**Comment by tamiko** [comment]
> We could automatically check line endings and permissions of files
> when we run "make indent". That would highlight the problems during
> code review and something like #5425 won't be necessary. Thoughts?

That's a good idea - let's put a check for that in our CI.

**Comment by bangerth** [comment]
Let's put it into `contrib/utilities/indent` instead, at least for the file permissions.

**Comment by tjhei** [comment]
> Let's put it into contrib/utilities/indent instead,

Yes, then it  will be run automatically on Travis-CI.

**Comment by tjhei** [comment]
``grep -l $'\r' -r tests/`` returns 23 files that appear to have DOS format.

For the permissions we could just do ``chmod -x+X -R include/ source/ tests/``

**Comment by bangerth** [comment]
Of the 25 files in question mentioned above, #5425 appears to fix all source files. The remaining seem to be binary files such as mesh input files.
