### ISSUE TITLE
merge GridTools and parallel::GridTools

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#5427]
#5423 fixed the unity build: my compiler got confused between `GridTools` and `parallel::GridTools`. I suspect that adding this extra namespace will cause similar headaches in the future; in addition, since we already have some parallel stuff in plain old `GridTools`, I suggest that we just put everything in `GridTools`.

AFAIK this namespace did not exist in 8.5 so we can remove it now and not break too much stuff. Thoughts?

**Comment by davydden** [comment]
> Thoughts?

agree.

**Comment by tjhei** [comment]
I agree. Deeply nested namespaces are a problem for other reasons and even worse are nested namespace with the same name as other toplevel namespaces because of lookup ambiguity. Otherwise user might need to do similar fixes in their code bases.
