### ISSUE TITLE
project_to_object_01 appears to be fragile

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5435]
`project_to_object_01` appears to be a fragile test. On a tester with optimization flags enabled I see the difference:

```
##59      #:2   <== -2.00000
##59      #:2   ==> -0.768956
@ Absolute error = 1.2310440000e+0, Relative error = 1.6009290519e+0
##59      #:4   <== 2.44929e-16
##59      #:4   ==> -1.84627
@ Absolute error = 1.8462700000e+0, Relative error = 7.5379803943e+15
```

@kronbichler recently added an alternative output https://github.com/dealii/dealii/pull/5409 . There on line 59 the output is the same as I have on my tester
```
DEAL::-0.768956, 1.00000, -1.84627
```

@drwells since you added the test, do you have any ideas how to make it a bit more robust so that we don't need to collect numerous outputs for it?

p.s. it's been failing on other testers https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=grid%2Fproject_to_object_01.release&date=2017-11-09

**Comment by drwells** [comment]
The checks performed by the test are probably too hard: for example, there are a few places where I test the projection of a point onto an object where the closest point is on the boundary or not well-defined.

I'll take another look at the alternative output and make the checks easier.

**Comment by drwells** [comment]
It looks like the two patches and alternative output were enough to make this test work on our testers: I don't see any recent failures on the cdash instance.

**Comment by drwells** [comment]
We can open this again if things stop working, but I think we are good to go.

**Comment by drwells** [comment]
No, I am wrong: this still fails on the nonstandard testers that enable things like `funsafe-math-optimizations`. These cause the errors to be about 10x larger. I'll redo things with a lower tolerance at some point this week.

**Comment by masterleinad** [comment]
This test appears to be stable now.
