### ISSUE TITLE
VectorTools::interpolate still needs fixing for systems where parts have no support points

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5438]
#5334 introduces a fallback implementation for the case of system elements where parts have no support points (think Q2 x DGP1 for Stokes). This was necessary because #4857 broke this functionality. 

#5334 is only intended as a stop-gap. The correct way is to implement the necessary functionality in the new implementation introduced in #4857, not to duplicate a few hundred lines of code. @tamiko promised to fix this issue in #5334.

**Comment by tamiko** [comment]
Will do. @drwells Will do soon! :-D
