### ISSUE TITLE
dof_handler.begin_active_face() is still in documentation

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5440]
`doc/doxygen/headers/iterators.h` suggests that one can do `dof_handler.begin_active_face()`, but that's not the case. 

`begin_active_face()` and `end_face()` exist only for Triangulation.

ps. btw, can one not iterate over DoF faces directly as opposed to first cells->faces?

**Comment by bangerth** [comment]
We used to have functions that allow you to iterate over faces like over cells. But they were not used because there are no algorithms where they turn out to be useful -- the principle missing piece being that you can get back from faces to cells.
