### ISSUE TITLE
data_out tests are fragile

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5441]
the following tests are rather fragile in that they give different results when compiling with optimization flags:

```
base/data_out_base_vtu.release
base/data_out_base_vtu_cycle.release
base/data_out_base_vtu_time.release
base/data_out_base_vtu_time_and_cycle.release
```

The diff is always along the lines
```
##143     #:1   <== AQAAABAFAAAQBQAA0gAAAA
##143     #:1   ==> AQAAABAFAAAQBQAA0QAAAA
```

I think those tests should be changed to only `grep` some relevant info and then pass if things are ok.
For example we can check this line

```
<Piece NumberOfPoints="54" NumberOfCells="30" >
```

another way to look at it is to filter out that binary output somehow, i.e. remove averythng inside `DataArray` fields
```
      <DataArray type="Float64" NumberOfComponents="3" format="binary">
! AQAAABAFAAAQBQAA0gAAAA==eNqNUVsOgjAQRCNJQ2rT8tLb2EvAIfFyfvJpEAbDtGPsz2Rmt9PdaVH8Oq/HnzweOdAIHTgLzn7MuW8m/RLzdSN8Tcz7WvIBeqEX8Tkt55zwcVhOuetHbmJ+nvQ+OPC09efr1e4H/dM2XJM5pq2f3xu3/iMvKYfv+6t/EPt4ygf3QpLHOk9N94Gt0IGV4JZ0cEe6S/bLc/atCJ2oe6pDD1SHXou5vZgjELfkw3M15GdFzo58eM9G5NoSB3Yij17k3oocO5FLL/7zRhx4j28uS4pw
      </DataArray>
```

**Comment by davydden** [comment]
another option is to use boost property_tree and xml parser to rip off the binary data, https://akrzemi1.wordpress.com/2011/07/13/parsing-xml-with-boost/  https://stackoverflow.com/questions/21856831/boost-read-xml-from-stringstream-does-not-read-xml-format

**Comment by kronbichler** [comment]
Since the issue is related to roundoff and the data output is purely artificial, we could also think about using numbers that are represented exactly in floating point arithmetics. Small integer numbers (interpreted as float) rather than fractions `1.0*p/nsub` would also be an alternative.

**Comment by davydden** [comment]
You probably refer to `patches.h`, more specifically to
```
const float x1 = 1.*i1/nsub;
const float x2 = 1.*i2/nsub;
const float x3 = 1.*i3/nsub;
const float x4 = 1.*i4/nsub;
```
But there is also another one which gets values using some function...
