### ISSUE TITLE
sacado tests failing

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5455]
`sacado` tests failing on this tester https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=13149

```
/mnt/data/testsuite/dealii/tests/sacado/basic_01a.cc: In function ‘int main()’:
/mnt/data/testsuite/dealii/tests/sacado/basic_01a.cc:53:22: error: ‘ADvar’ in namespace ‘Sacado::Rad’ does not name a template type
   const Sacado::Rad::ADvar<double> x_ad (x);
                      ^
/mnt/data/testsuite/dealii/tests/sacado/basic_01a.cc:54:22: error: ‘ADvar’ in namespace ‘Sacado::Rad’ does not name a template type
   const Sacado::Rad::ADvar<double> y_ad (y);
                      ^
```
Looks like we need some guards for version of Sacado.

@jppelteret can you please have a look when you have time?

**Comment by jppelteret** [comment]
Thanks @davydden. I think that this relates to the TODO I've got noted in #5392. Last week I made a fix for the core issue (devised a guard, as you suggested) and just finished testing it on my Linux machine which had the same problem. So I'll start upstreaming that as soon as I can.

**Comment by jppelteret** [comment]
Oh I see now that this is not necessarily exactly the same problem, but rather that it relates to something I noticed while making a fix for that issue.

Note to self: This test probably just needs the header 
```
#include <Sacado_trad.hpp>
```
