### ISSUE TITLE
Quadrature Point without reinit cell

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#5460]
For the functions in file [fe_values.h](https://github.com/dealii/dealii/blob/master/include/deal.II/fe/fe_values.h)
like quadrature_point, JxW, among others, the values are returned without checking whether the
fe_values object is reinited to this cell. 
For example: [get_function_values](https://github.com/dealii/dealii/blob/master/source/fe/fe_values.cc#L1287) throws an exception (in debug mode) when the function is called and the fe_values object is not reinited to this cell. But this is not the case for (most) functions defined in fe_values.h file.
I am not sure but I think such an assert should also be present atleast in these functions.

```
template <int dim, int spacedim>
inline
const Point<spacedim> &
FEValuesBase<dim,spacedim>::quadrature_point (const unsigned int i) const
{
  Assert (this->update_flags & update_quadrature_points,
          ExcAccessToUninitializedField("update_quadrature_points"));
  Assert (i<this->mapping_output.quadrature_points.size(),
          ExcIndexRange(i, 0, this->mapping_output.quadrature_points.size()));

  return this->mapping_output.quadrature_points[i];
}




template <int dim, int spacedim>
inline
double
FEValuesBase<dim,spacedim>::JxW (const unsigned int i) const
{
  Assert (this->update_flags & update_JxW_values,
          ExcAccessToUninitializedField("update_JxW_values"));
  Assert (i<this->mapping_output.JxW_values.size(),
          ExcIndexRange(i, 0, this->mapping_output.JxW_values.size()));

  return this->mapping_output.JxW_values[i];
}

```

**Comment by bangerth** [comment]
Yes, this is correct -- the assertion is missing. Want to add it to the functions you mention? We'd be quite happy to merge such a patch!

**Comment by bangerth** [comment]
Thanks for reporting this, and in particular for fixing it!
