### ISSUE TITLE
Change coefficient type in KellyErrorEstimator::estimate()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5492]
#5419 changes the Neumann boundary values provided to `KellyErrorEstimator::estimate()` to match the type of the solution vector -- in other words, if the solution vector is complex-valued, then you now also need to pass a `Function<dim,std::complex<double>>` as argument for the Neumann values. This makes sense.

I did not change the coefficient function the `KellyErrorEstimator::estimate()` functions take. That's because that class is typically meant for elliptic problems where the coefficient would have to be real (we assume that the coefficient is a scalar, and the only Hermitian 1x1 matrix is a real one). But then, the class is also used for other purposes. What do you all think?

**Comment by davydden** [comment]
i would keep it as-is until we have a need for complex-valued heterogeneity coefficient. Personally, i have not came across such cases.

**Comment by bangerth** [comment]
There was no objection to leaving it as is. So let's go with that.
