### ISSUE TITLE
Installation errors with Sacado

### ISSUE THREAD

**Issue by ju4nk4** [dealii/dealii#5494]
The discussion started here:
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dealii/ee2w2X987ig
By trying to install from GIT: 
  git clone https://github.com/dealii/dealii.git
I get the errors in the attached file. They seem to come from the usage of trilinos_ver=11.12.1. It was suggested that the commit:
  git checkout fd01d88
should install ok, but it gave the same errors with Sacado.
[dealii-git-errors.txt](https://github.com/dealii/dealii/files/1483316/dealii-git-errors.txt)

**Comment by bangerth** [comment]
Trilinos 11.12 is really old. It may simply not have the necessary classes to support this. Would you be willing to try again with a newer Trilinos version?

**Comment by ju4nk4** [comment]
Yes, I am on it now =D

**Comment by jppelteret** [comment]
Thanks @ju4nk4 . @bangerth It looks to me like this version of Trilinos [should work](https://trilinos.org/docs/r11.12/packages/sacado/doc/html/classSacado_1_1Rad_1_1ADvar.html#adb21e2489fcfc950a063628e65d7a70c), but it would potentially save us a lot of grief to have @ju4nk4 verify this one way or another.

**Comment by ju4nk4** [comment]
I confirm that the problem was the old version of trilinos: 11.12. I installed the newer 12.4.2, and 
  git clone https://github.com/dealii/dealii.git
and it installed with no errors. However, the run:
make test
results in errors (see attached file
[quicktests.log](https://github.com/dealii/dealii/files/1483528/quicktests.log)
)

**Comment by jppelteret** [comment]
Great, thanks for the feedback!

@dealii/dealii  Should we bump the minimum version of Trilinos to 12.4.2, which is what's tested on `tjhei-alpha`?

**Comment by bangerth** [comment]
I think that's reasonable.

**Comment by davydden** [comment]
Same here

**Comment by masterleinad** [comment]
> @dealii/dealii Should we bump the minimum version of Trilinos to 12.4.2, which is what's tested on tjhei-alpha?

Then let us make sure that this version works with ROL.

**Comment by jppelteret** [comment]
Ok, I'm going to move this discussion to a new issue (#5498).
