### ISSUE TITLE
Increase minimum required version of Trilinos

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#5498]
As is noted in #5494, after recent additions to the library we can no longer support Trilinos `11.12`. i suggested that we bump the minimum required version to `12.4.2`, which is tested on `tjhei-alpha` but it has been subsequently suggested that we set it at `12.6.1` which includes the `ROL` module. I'm neutral about either choice since `ROL` is currently an optional module (which I think is a good feature to keep).

@dealii/dealii Thoughts?

**Comment by davydden** [comment]
Let’s bump to 12.4.2, ‘ROL’ is optional, so there is no real need to go for 12.6.1

**Comment by masterleinad** [comment]
Let me check if `ROL` works with 12.4.2 as well. Then we would have everything included.
