### ISSUE TITLE
Handling expensive manifolds

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#5506]
In https://github.com/dealii/dealii/pull/5368#issuecomment-343215888 @gassmoeller rightfully complained that `SphericalManifold` got much more expensive with the recent improvement in that PR. In a follow-up comment, I mentioned that also other manifolds like `TransfiniteInterpolationManifold` can be very expensive to evaluate all the time. This issue lists some strategies and things we could do in a more central place so they won't get lost. We should add things we want to address, tick items that were done and strike through items we don't want to address.

- [x] Further improvements to `SphericalManifold::get_new_points` (see a separate comment below)
- ~~Add inaccurate variant to `SphericalManifold` for users who do not need the accuracy~~ [There doesn't seem to be a need for this anymore]
- [x] Advertise alternative concepts, such as a single interpolation of mapping support points and using `MappingFEField` for the bulk of the work
- ~~Let `MappingQGeneric` cache the mapping support points (this might be quite tedious to implement because it must be thread-safe, work with multiple triangulations, etc.)~~ [Too tedious and error prone, `MappingFEField` is much better]

**Comment by kronbichler** [comment]
Regarding the improved `SphericalManifold::get_new_points` (for the use in 3D through `MappingQGeneric`): We currently call `get_new_point` for a single weight row at a time. We could do better by realizing that a typical 3D interpolation setting is as extrusion-like operation (in the spherical sense with respect to the center), so we would only need to compute a 2D set of interpolations on the unit sphere with `r=1` and distinguish the cases by the radius. This would need to copy the radius-normalization part in the `get_new_point` to the `get_new_points` function and check if several of the rows in the weights are the same after normalization and collection of points. I don't have time to look into this, but it should give an almost 5-fold speedup on a mapping of degree 4 I guess since we reduce the dimension by one.

**Comment by masterleinad** [comment]
Some statistics for the Newton-type iteration using a modified version of `step-10` (`set_all_manifold_ids`, `MappingQGeneric(5)`, `SphericalManifold`, `HyperShell<3>` with inner radius .5 and outer radius 1):
```
5 refinements: 7,553,352 calls terminate in the first iteration, 44,424 in the second
4 refinements: 1,721,424 calls in the first iteration and 44,424 in the second
3 refinements: 372,816 calls in the first iteration and 44,424 in the second
2 refinements: 52,944 calls in the first iteration and 44,424 in the second
1 refinements: 10,416 calls in the first iteration and 10,440 in the second
0 refinements: 1,152 calls in the first iteration and 1,152 in the second
```
So we only really improve the initial guess in the first two refinements in this setting.
It might be a good idea to simply not run in the Newton loop if the maximal distance is small compared to the radius.

**Comment by kronbichler** [comment]
Just as a general remark: I definitely think that we should introduce a tutorial that does `MappingFEField`. I volunteer to write a short one regarding the performance aspects of it, but since that class has other advantages as well (isoparametric representation e.g. in structural mechanics), I'd be happy if someone else wants to join...

**Comment by bangerth** [comment]
@masterleinad: your data makes sense to me -- a manifold, after all, is defined as something that, when looked at at a sufficiently small level of detail, is flat. In other words, the nonlinearity must disappear as mesh refinement proceeds. I think your data is a good illustration of this.

@kronbichler: Yes, that would definitely be great. I think we all would appreciate this! (I can't offer to help other than to review it when you have something, though :-( )

**Comment by simonpuchert** [comment]
In source/grid/manifold_lib.cc, lines 516-535:

```c                 
  const double costheta = (directions[i])*xVec;
  const double theta = atan2(sintheta, costheta);
- const double sinthetaInv = 1.0/sintheta;
+ const double sincthetaInv = theta/sintheta;

- vPerp *= sinthetaInv;
  const double cosphi = vPerp*Clocalx;
  const double sinphi = vPerp*Clocaly;

  gradlocal[0] = cosphi;
  gradlocal[1] = sinphi;
- gradient += (merged_weights[i]*theta)*gradlocal;
+ gradient += (merged_weights[i]*sincthetaInv)*gradlocal;

  const double sinphiSq = sinphi*sinphi;
  const double cosphiSq = cosphi*cosphi;
- const double tt = (theta*sinthetaInv)*costheta;
+ const double tt = sincthetaInv * costheta;
  const double offdiag = cosphi*sinphi*merged_weights[i]*(1.0-tt);
  Hessian[0][0] += merged_weights[i]*(cosphiSq+tt*sinphiSq);
  Hessian[0][1] += offdiag;
  Hessian[1][0] += offdiag;
  Hessian[1][1] += merged_weights[i]*(sinphiSq+tt*cosphiSq);
```

Sadly there is no nicer way of computing theta/sintheta from sintheta and costheta yet. Maybe one could test if the angle is small enough (by testing sintheta < c1 or costheta > c2) and in that (interesting) case just approximate sincthetaInv using a polynomial in costheta.

**Comment by kronbichler** [comment]
@simonpuchert Would you mind adding this small change as a pull request so we can acknowledge your contribution? This looks very nice indeed.

**Comment by simonpuchert** [comment]
Sure, I created a pull request.

On the previous idea, it is actually possible:
Set y = 1 - cos(x). Then
x / sin(x) = 1 + y / 3 + ... + 2^n * (n!)^2 / (2n+1)! *y^n + ...
(don't ask, it's mathemagics [or rather, some first-order ODE shenanigans]).
Now, this could be used by itself or, given a certain interval and degree of the polynomial, the Remez algorithm could be used to find the best approximation on that interval. For theta in [0,t] this yields errors of ~ 4^(-n) * t^(2n) and ~ 16^(-n) * t^(2n) for the n-term sum, respectively.

I can implement this if you think it's useful, but I don't know what precision you expect (and it might not actually be faster).

**Comment by masterleinad** [comment]
I guess we need some more profiling to find out which places need more optimization before.

**Comment by luca-heltai** [comment]
In my computations, I currently do the following:

- have a DoFHandler with spacedim FE_Q/FE_Bernstein describing the *absolute* geometry
- attach manifolds (as expensive as you wish)
- call VectorTools::get_position_vector
- create MappingFEField with the computed position vector
- discard manifolds and only use the MappingFEField afterwards

This is of course just a polynomial approximations, but it works pretty well for our needs. We could benchmark this, and make a small tutorial. @kronbichler , you'll come to Trieste soon. How about we prepare ourselves to write this tutorial in those days?

**Comment by kronbichler** [comment]
@luca-heltai Yes this sounds very reasonable and is indeed what I was thinking about in one of the items above (I just deleted the caching inside `MappingQGeneric` because it is too tedious). I agree we can do that when I am in Trieste.

**Comment by kronbichler** [comment]
We discussed the cached manifold concept in #6991, but I would propose a different variant: We could introduce the cache for `MappingQ` instead. I have implemented something like that in one of our application codes and would think it makes sense to add to the 9.1 release. The code is here:
https://github.com/kronbichler/exwave/blob/softwareX-SphereAdaptTest/source/explicit_wave.cc#L110-L150

The motivation for implementing this class was that we can cache all expensive uses in `FEValues` and friends once and for all via a mapping (rather than a cached manifold). It could even be used together with `MappingQEulerian` because that class can also be expensive due to the lookup and interpolation.

**Comment by kronbichler** [comment]
Are we ready to review another tutorial program until the release? I plan a short tutorial showing the transfinite interpolation, introduces a mapping cache class, for some geometry of a ball inside a cube. I will be done with it in around 24 hours if I push for it, but I only do it if there is someone reviewing the tutorial.

**Comment by drwells** [comment]
We really need this tutorial program. I can review it tomorrow night.

**Comment by kronbichler** [comment]
Great, then I go ahead.

**Comment by kronbichler** [comment]
We decided in #8058 to move this to the 9.2 release.
