### ISSUE TITLE
Configuring dealii with MPI fails with CMake 3.10.0

### ISSUE THREAD

**Issue by BenBrands** [dealii/dealii#5510]
I tried to install dealii (Developer version with MPI)  with CMake 3.10.0 (using spack) and the configuring failed.
I get the following output:

```
--   MPI_INCLUDE_DIRS: *** Required variable "MPI_CXX_INCLUDE_PATH" empty ***
--   MPI_USER_INCLUDE_DIRS: *** Required variable "MPI_CXX_INCLUDE_PATH" empty ***
--   MPI_CXX_FLAGS:
--   MPI_LINKER_FLAGS:
-- Could NOT find MPI
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:77 (MESSAGE):

Could not find any suitable mpi library!
```
Using Cmake 3.9.4 there is no problem and installing dealii succeeds.

**Comment by davydden** [comment]
is there any error in the terminal above those you cite during configuration? I always forget where `CMake` keeps logs of the configuration, try `<build_folder>/CMakeFiles/CMakeError.log`. Note that some checks should be fail and it's ok to have that file non-empty in general.

**Comment by BenBrands** [comment]
The first part of the configuration seems to be fine as the proper compiler for MPI is picked:
```
-- Check for working CXX compiler: /home/benjamin/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/openmpi-3.0.0-pxr27g4xplo2nshq6wv7naq4jodkwiyy/bin/mpic++
-- Check for working CXX compiler: /home/benjamin/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/openmpi-3.0.0-pxr27g4xplo2nshq6wv7naq4jodkwiyy/bin/mpic++ -- works
```

Down the road the configuring fails and I get that:
```
-- Include /home/benjamin/spack/var/spack/stage/dealii-develop-2qnnehopha7aakmih6jgskssy5rip6cl/dealii/cmake/configure/configure_1_mpi.cmake
-- Found MPI_C: /home/benjamin/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/openmpi-3.0.0-pxr27g4xplo2nshq6wv7naq4jodkwiyy/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /home/benjamin/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/openmpi-3.0.0-pxr27g4xplo2nshq6wv7naq4jodkwiyy/bin/mpic++ (found version "3.1") 
-- Found MPI_Fortran: /home/benjamin/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/openmpi-3.0.0-pxr27g4xplo2nshq6wv7naq4jodkwiyy/bin/mpif90 (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Performing Test MPI_HAVE_MPI_SEEK_SET
-- Performing Test MPI_HAVE_MPI_SEEK_SET - Success
-- Found MPI_MPI_H
--   MPI_VERSION: 3.1
--   MPI_LIBRARIES: *** Required variable "MPI_CXX_LIBRARIES" empty ***
--   MPI_INCLUDE_DIRS: *** Required variable "MPI_CXX_INCLUDE_PATH" empty ***
--   MPI_USER_INCLUDE_DIRS: *** Required variable "MPI_CXX_INCLUDE_PATH" empty ***
--   MPI_CXX_FLAGS: 
--   MPI_LINKER_FLAGS: 
-- Could NOT find MPI
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:77 (MESSAGE):
  

  Could not find any suitable mpi library!

  

  Please ensure that an mpi library is installed on your computer

  and set CMAKE_CXX_COMPILER to the appropriate mpi wrappers:

      $ CXX=".../mpicxx" cmake <...>
      $ cmake -DCMAKE_CXX_COMPILER=".../mpicxx" <...>

  Or with additional C and Fortran wrappers (recommended!):

      $ CC=".../mpicc" CXX=".../mpicxx" F90=".../mpif90" cmake <...>
      $ cmake -DCMAKE_C_COMPILER=".../mpicc"\
              -DCMAKE_CXX_COMPILER=".../mpicxx"\
              -DCMAKE_Fortran_COMPILER=".../mpif90"\
              <...>

Call Stack (most recent call first):
  /tmp/benjamin/spack-stage/spack-stage-G8CQCL/dealii/spack-build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_MPI_ERROR_MESSAGE)
  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:267 (EVALUATE_EXPRESSION)
  cmake/configure/configure_1_mpi.cmake:94 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)
```

**Comment by davydden** [comment]
@tamiko ping.

**Comment by Rombur** [comment]
`FindMPI` has been updated with cmake 3.10.0 see https://cmake.org/cmake/help/v3.10/release/3.10.html

**Comment by bangerth** [comment]
The error is produced at the end of `cmake/modules/FindMPI.cmake` from the command
```
DEAL_II_PACKAGE_HANDLE(MPI
  LIBRARIES
    REQUIRED MPI_CXX_LIBRARIES
 ...
```
The `MPI_CXX_LIBRARIES` variable is not set anywhere in this file, so I assume that the module expects it to be set up here:
```
#
# Call the system FindMPI.cmake module:
#

# in case MPIEXEC is specified first call find_program() so that in case of success 
# its subsequent runs inside FIND_PACKAGE(MPI) do not alter the desired result.
IF(DEFINED ENV{MPIEXEC})
  FIND_PROGRAM(MPIEXEC $ENV{MPIEXEC})
ENDIF()

# temporarily disable ${CMAKE_SOURCE_DIR}/cmake/modules for module lookup
LIST(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
FIND_PACKAGE(MPI)
```
I thought for a moment that cmake may have used to export something in `MPI_CXX_LIBRARIES` but now no longer does. But it still is:
https://cmake.org/cmake/help/v3.10/module/FindMPI.html#module:FindMPI

I think I need to leave it up to @tamiko to investigate this further. Is it possible that cmake 3.10 just exports an empty list of libraries, but that we expect a non-empty string?

**Comment by masterleinad** [comment]
At least, running the "more aggressive search" seems to work.

**Comment by davydden** [comment]
> running the "more aggressive search" seems to work.

what do you mean by that?

**Comment by masterleinad** [comment]
In `FindMPI.cmake` we have 
```
 IF(NOT MPI_CXX_FOUND AND DEAL_II_WITH_MPI)
   #
   # CMAKE_CXX_COMPILER is apparently not an mpi wrapper.
   # So, let's be a bit more aggressive in finding MPI (and if
   # DEAL_II_WITH_MPI is set).
   #
   MESSAGE(STATUS
     "MPI not found but DEAL_II_WITH_MPI is set to TRUE."
     " Try again with more aggressive search paths:"
     )
   # Clear variables so that FIND_PACKAGE runs again:
   SET(MPI_FOUND)
   SET(MPI_CXX_COMPILER)
   SET(MPI_C_COMPILER)
   SET(MPI_Fortran_COMPILER)
   UNSET(MPI_CXX_COMPILER CACHE)
   UNSET(MPI_C_COMPILER CACHE)
   UNSET(MPI_Fortran_COMPILER CACHE)
   FIND_PACKAGE(MPI)
 ENDIF()
 LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
```
Forcing this to run by disabling the if-switch, seems to work for me. Of course the question remains, what the real problem is. Apparently, `MPI_CXX_FOUND` is reported to be found but the relevant paths are not exported, i.e. empty.

**Comment by tamiko** [comment]
To clarify. What seems to be failing with cmake-3.10 is setting up mpi via
```
CC=mpicc CXX=mpicxx cmake [...]
```
or
```
CC=mpicc CXX=mpicxx cmake -DWITH_MPI=ON [...]
```

This is quite interesting. I will have a look.

**Comment by masterleinad** [comment]
I reported this issue at https://gitlab.kitware.com/cmake/cmake/issues/17538

**Comment by bangerth** [comment]
Can we work around this, or do we need to blacklist cmake 3.10? @tamiko -- you wanted to look into this?

**Comment by masterleinad** [comment]
The following patch works at least for me as a workaround:
```
diff --git a/cmake/modules/FindMPI.cmake b/cmake/modules/FindMPI.cmake
index 1c74da9..0bc1d23 100644
--- a/cmake/modules/FindMPI.cmake
+++ b/cmake/modules/FindMPI.cmake
@@ -74,10 +74,28 @@ ENDIF()
 LIST(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
 FIND_PACKAGE(MPI)
 
-IF(NOT MPI_CXX_FOUND AND DEAL_II_WITH_MPI)
+# if no include path and libraries for the CXX compiler were
+# found, we would normally decide that the compiler
+# can't be used as MPI compiler.
+# In CMake 3.10 however, it might happen that sufficent settings
+# for the C compiler were found that are also applicable
+# for the CXX compiler. So try that.
+IF ("${MPI_CXX_INCLUDE_PATH}" MATCHES "^\\s*$")
+ SET(MPI_CXX_INCLUDE_PATH ${MPI_C_INCLUDE_PATH})
+ENDIF()
+IF ("${MPI_CXX_LIBRARIES}" MATCHES "^\\s*$")
+  SET(MPI_CXX_LIBRARIES ${MPI_C_LIBRARIES})
+
+IF(DEAL_II_WITH_MPI AND
+   (NOT MPI_CXX_FOUND
+    OR "${MPI_CXX_INCLUDE_PATH}" MATCHES "^\\s*$"
+    OR "${MPI_CXX_LIBRARIES}" MATCHES "^\\s*$")
+  )
   #
-  # CMAKE_CXX_COMPILER is apparently not an mpi wrapper.
-  # So, let's be a bit more aggressive in finding MPI (and if
+  # CMAKE_CXX_COMPILER is apparently not an mpi wrapper or at least
+  # MPI_CXX_INCLUDE_PATH or MPI_CXX_LIBRARIES have not been set
+  # to something useful.
+  # So, let's be a bit more aggressive in finding MPI (if
   # DEAL_II_WITH_MPI is set).
   #
   MESSAGE(STATUS
@@ -93,6 +111,12 @@ IF(NOT MPI_CXX_FOUND AND DEAL_II_WITH_MPI)
   UNSET(MPI_C_COMPILER CACHE)
   UNSET(MPI_Fortran_COMPILER CACHE)
   FIND_PACKAGE(MPI)
+  IF ("${MPI_CXX_INCLUDE_PATH}" MATCHES "^\\s*$")
+    SET(MPI_CXX_INCLUDE_PATH ${MPI_C_INCLUDE_PATH})
+  ENDIF()
+  IF ("${MPI_CXX_LIBRARIES}" MATCHES "^\\s*$")
+    SET(MPI_CXX_LIBRARIES ${MPI_C_LIBRARIES})
+  ENDIF()
 ENDIF()
 LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
```

**Comment by tjhei** [comment]
It could be that they assume that you use the wrappers to compile, so then there would be no need to specify the include and library paths because the wrappers will add them automatically. Not sure how to make use of this, though.

**Comment by ChrisTX** [comment]
Hi, I wrote the new `FindMPI`.

You should generally not assume that `MPI_CXX_INCLUDE_PATH` or `MPI_CXX_LIBRARIES` are set, no matter on what version of CMake. `FindMPI` assumes that you compile your code with `CMAKE_<LANG>_COMPILER`, which it does, and therefore MPI support is considered implicitly given by the compiler (i.e. no settings needed) if your compiler is already MPI enabled.

This behavior is actually desired, since the compiler might ship a different MPI than there is available in the environment. A notorious case of this is when you're working with Cray PrgEnv, where the compiler provides MPI via a module, but have for example Intel Parallel Studio installed and loaded. The only `mpicc` in the environment is the one of Intel MPI, but considering it would load two MPIs and therefore cause all kinds of breakage.

 With 3.10, the search order changed so that the compiler is considered first instead of as a last resort to address such problems and prevent them explicitly. This also ensures that if `CMAKE_<LANG>_COMPILER` is set to an MPI wrapper, it cannot mismatch with `MPI_<LANG>_COMPILER`, which was previously possible.

However, this does not change the situation for systems like Cray: If you're using Cray PrgEnv with CMake 3.9 or older,  the include path and libraries will be empty. Therefore you should not depend on this behavior. Instead work with `MPI_<LANG>_FOUND`, this reliably indicates whether MPI is supported was found or not.

As a general advice, don't set `CMAKE_<LANG>_COMPILER` (or `CC`, `CXX`, ...) to MPI wrappers. This will work most of the time, with empty settings or not, but on some MPIs can cause bad behavior. Notoriously, Intel MPI gives settings dependent on the flags passed to it, and CMake has always only considered `mpicc -show`, without any flags whatsoever. If you now pass `MPI_<LANG>_LIBRARIES` to an Intel MPI wrapper (because it's in `CMAKE_<LANG>_COMPILER`) with `-g`, you obtain both release and debug MPI libraries on the link line.
You should only set `MPI_<LANG>_COMPILER` to the MPI compiler wrapper, and keep `CMAKE_<LANG>_COMPILER` set to the compiler you want to work with. This way you can also retain compatibility with MPIs without compiler wrappers like Cray (and also Microsoft MPI, which is just guessed settings).

**Comment by tamiko** [comment]
Working on it.

It will probably boil down to set MPI to default disabled and remove the old behavior alltogether.

**Comment by arijitlaik** [comment]
Just a simple question, i am on bleeding edge machine with ubuntu 18.04, where the cmake is >3.10, installing with candi says "Your cmake version is 3.10, which is above 3.9." do i switch on cmake in the candi confg ?

**Comment by davydden** [comment]
@arijitlaik 

> do i switch on cmake in the candi confg

those questions are better suited to Google forum https://groups.google.com/forum/?fromgroups#!forum/dealii

In general, you should be fine if you build `deal.II` from the `master` branch, where this PR is merged already. 

AFAIK `candi` does not build `cmake` for you, so if you need to build the latest stable release, you should simply change version of `cmake` it in your linux package manager.

**Comment by tjhei** [comment]
> AFAIK candi does not build cmake for you

Or you just do ``./candi.sh --packages="cmake"``, which will download an older cmake version that works with 8.5. Just enable it after installation.

**Comment by arijitlaik** [comment]
thanks @davydden @tjhei , if i have further doubts ill post it up in the google group

**Comment by Geof23** [comment]
I know this is old, but do you guys realize that the CMake MPI CXX stuff is for MPI c++?  C++ MPi was removed from the MPI standard: https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node519.htm.  So I'm saying if an MPI implementation doesn't give you MPI_CXX_LIBRARIES, it may mean they don't support C++ MPI (c++ wrappers)
