### ISSUE TITLE
Failing shared::Triangulation tests

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5513]
It seems #5436 broke some tests. At least for `locally_relevant_dofs_per_subdomain_01_hp` and `locally_relevant_dofs_per_subdomain_01`, I can reproduce this locally while the other [failing tests](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=13386) are working for me.

@tcclevenger Can you confirm that these particular teste are working for you or did #5436 invalidate all the outputs?

**Comment by tjhei** [comment]
Yeah, this broke 10+ tests. I already contacted @tcclevenger . The problem is that many of the tests use METIS and have accumulated several alternative output files. These are hard to adjust...
