### ISSUE TITLE
hp::dofhandler on p::d::tria with p::d::solutiontransfer 

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#5546]
Now that hp::dofhandler works with p::d:tria  #3511 , I think p:d:solutiontransfer is still not supported.

I tested a code that uses hp::dof_handler on p::d::tria  but on using p::d::solutiontransfer,
it gave a linking error. 

```
 undefined reference to 'dealii::parallel::distributed::SolutionTransfer<2, dealii::PETScWrappers::MPI::Vector, dealii::hp::DoFHandler<2, 2> >::SolutionTransfer(dealii::hp::DoFHandler<2, 2> const&)
```

I think this is _partly_ because it is not instantiated in this [file](https://github.com/dealii/dealii/blob/master/source/distributed/solution_transfer.inst.in).

If this is not a bug, does that mean currently AMR and serialization are not supported for p::d::tria and hp::dofhandler?

**Comment by bangerth** [comment]
`hp::DoFhandler` does not yet work with `p::d::Triangulation`. There are many steps left to make this work. `p::d::SolutionTransfer` is really only one, but there are many steps before that can be worked on.

**Comment by sairajat** [comment]
Hello Professor,
I looked at #3511  and it says that only writing tests is left. Everything else is _done_.
Also, I may be wrong, but I tested (and still testing) the hp::dofhandler  with p::d::tria from the latest master commit, it looks to me the dofs are distributed correctly.

Thanks.

**Comment by bangerth** [comment]
The list in #3511 is not correct. I *think* that some things now work correctly, but I *know* that there are others that I need to improve. For example, I'm not confident that constraints are correctly computed when a processor boundary is also a boundary between different finite elements.

**Comment by sairajat** [comment]
Oh, I see. I followed the list and assumed that everything _works_ now and can be used.
Thanks for the clarification. 

I hope this feature gets released _soon_ :).

**Comment by bangerth** [comment]
I've added this topic here to the list in #3511.

**Comment by weixiong-zheng-berkeley** [comment]
Just saw this. Does it mean parallel computation using MPI on distributed triangulation is available to use, as I asked two years ago?

**Comment by masterleinad** [comment]
No, the support for `parallel::distributed::Triangulation` in `hp::DoFHandler` is not complete yet.

**Comment by bangerth** [comment]
Correct. Some things work already, some things don't.
