### ISSUE TITLE
ReductionControl::check() does not log last iteration step to history_data

### ISSUE THREAD

**Issue by jodlbauer** [dealii/dealii#5550]
Hi,

the ReductionControl object does not correctly log the last iteration step. If the solution is below the given residual, the ReductionControl::check() method does not append the final iteration to the history data (around line 275 in solver_control.cc). Previous iterations are added via the call to the parent function SolverControl::check(). This causes an assert e.g. when calling average_reduction().

Can be easily fixed by adding the following lines 

```
      if (history_data_enabled)
        history_data.push_back(check_value);
```

**Comment by davydden** [comment]
do you mind creating a pull request with the fix? see https://github.com/dealii/dealii/wiki/Contributing

**Comment by jodlbauer** [comment]
Currently trying, but may take a while :)

**Comment by jodlbauer** [comment]
Ok, seems like I finally managed to submit a pull request #5551 . Let me know if I messed something up.
