### ISSUE TITLE
Avoid MPI communication in TimerOutput::~TimerOutput if an exception is pending

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5557]
As https://github.com/geodynamics/aspect/pull/2018 shows, there are cases where an exception is triggered on one MPI process that then propagates up and in the process of destroying objects, also calls the destructor of `TimerOutput` -- which proceeds to initiate MPI communications.

As @tjhei found out, in the best of cases this leads to a deadlock because the other processors don't want to communicate on this channel at this time. In the worst of cases, the messages sent interfere with other messages that happen to use the same message id and data type, leading to impossible to understand errors.

The solution around this is probably to make sure that no MPI communication is initiated if an exception is pending. I've been trying to come up with a legitimate case where this may happen, but in all likelihood, the reason why the `TimerOutput` object is destroyed when an exception is pending is because we are unwinding the stack, not because that's how the program is supposed to behave. There is of course the possibility that *all* processors have a pending exception -- in which case we'll just not get any output, but at least all processors will do the same thing and not get out of sync.

**Comment by drwells** [comment]
I worked with the timers recently; I can go ahead and fix this.
