### ISSUE TITLE
build failure with DEAL_II_WITH_OPENCASCADE=ON

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#557]
As evidenced by [1], the latest changes in template arguments broke the opencascade feature.
@bangerth, @luca-heltai: Can someone have a look?

[1] http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=3852

**Comment by bangerth** [comment]
Interesting case. Patch forthcoming.

**Comment by bangerth** [comment]
Also addressed by #562

**Comment by tamiko** [comment]
Seems to be resolved with the latest commits.

We have one test failing due to the latest Tensor changes [1].
Otherwise everything is back to normal.

[1] http://cdash.kyomu.43-1.org/testDetails.php?test=6713614&build=4090
