### ISSUE TITLE
netcdf-cxx4 support

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5570]
`netcdf-cxx` appears to be deprecated, see https://www.unidata.ucar.edu/downloads/netcdf/index.jsp . Successor being `netcdf-cxx4`: https://github.com/Unidata/netcdf-cxx4/releases

The only place we use `netcdf` is [grid_in.cc](https://github.com/dealii/dealii/blob/master/source/grid/grid_in.cc), namely `read_netcdf()`.

Could be that we only need to include different headers for `cxx4` version (there is no `netcdfcpp.h`), but it's also possible that some classes/functions have changed. On the download page developers mention templates, namespace, etc, so I would not be surprised if they are not compatible at all.

our `cmake` part would need to be adjusted as well, https://github.com/dealii/dealii/blob/master/cmake/modules/FindNETCDF.cmake#L40

**Comment by drwells** [comment]
> `netcdf-cxx` appears to be deprecated

I have installed the legacy NetCDF package for years. I think that they completely rewrote things at some point.

**Comment by drwells** [comment]
Clarification: I installed this just to run the tests, I have never personally used this interface in my own projects.

**Comment by davydden** [comment]
Neither did I.

**Comment by tamiko** [comment]
After, I don't know (wild guess), 10 years of `netcdf-cxx4` being around we should really consider either (a) upgrading to the new cxx wrapper, or (b) removing netcdf support.

Thoughts?

**Comment by bangerth** [comment]
I think that's a reasonable approach. Want to open an issue that tracks this for the 9.1 milestone?

**Comment by davydden** [comment]
>  Want to open an issue that tracks this for the 9.1 milestone?

why do we need another issue? This one already tracks it for 9.1. milestone.

**Comment by bangerth** [comment]
Oh, I missed that -- lesson for me: don't github and telecon at the same time :-)
