### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#5573]
I have started working on a Jupyter notebook that shows how to use the python wrappers (see [here](https://github.com/Rombur/dealii/blob/notebook/contrib/python-bindings/notebooks/tutorial.ipynb)). But I am wondering where it should go. For now, I have put it in `/contrib/python-bindings/notebooks/` because it is not a C++ tutorial but I don't know how to make it visible from `dealii.org` or maybe we can just link to the github page directly. Github knows how to render jupyter notebook and I don't think it is trivial to move a notebook to html. I would also like your opinion on whether the notebook should contains the executed code or not. The current notebook contains it which is nice if you want to read it like a tutorial but there is also no point in running the notebook.

**Comment by davydden** [comment]
nice! I dont mind referring users to the GitHub-rendered pages. 

Maybe we should structure it as 
```
dealii/contrib/python-bindings/notebooks/tutorial_01.ipynb
dealii/contrib/python-bindings/notebooks/index.ipynb
```
where the second file contains list of tutorials and quick explanation. I ecpec that eventually we'll have more than one tutorial.

**Comment by Rombur** [comment]
@davydden Good idea. Thanks!

**Comment by tjhei** [comment]
Another option would be to create a separate repo (like we do for the code gallery). This might be useful so we don't have unnecessary bloat in the main repo. If you include the output pictures (and I think we should!), the notebooks can become quite large. As an example, some of my notebook I use for teaching (not deal.II related) are 300-500kb big each.

**Comment by Rombur** [comment]
@tjhei make sense. I will create a new repo.

**Comment by davydden** [comment]
> @tjhei make sense. I will create a new repo.

before you do, @dealii/dealii any opinions on this matter? Personaly, I prefer `jupyter` notebooks which shows how to use a part of `dealii` (python wrappers) to  be in `dealii` repo.

**Comment by bangerth** [comment]
I feel that the use of external repos is really detrimental to being able to discover what's there. I'm not a fan of that.

**Comment by tjhei** [comment]
> I feel that the use of external repos is really detrimental to being able to discover what's there. I'm not a fan of that.

I don't like adding large binary files that don't diff well to the main repo, but your argument makes sense. Maybe we put them in the repo for now and don't try to go over board with embedded images.
