### ISSUE TITLE
Do hanging node constraints over periodic boundaries work?

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#5574]
I came across this while working on #5386 (the broken periodicity and Schur complement tests). Consider the following grid:
![test](https://user-images.githubusercontent.com/8276200/33548361-35564f94-d8e7-11e7-91ec-1009505550d0.png)

We have periodic boundary conditions over the two parts of the shell. Of course, we should have a hanging node constraint on the "hanging" node on the two cells close to the inner rim in the lower right part of the boundary. It appears that we do not have that. I do not have time to investigate this now, but looking at the source code in `source/dofs/dof_tools_constraints.cc` it appears that `make_hp_hanging_node_constraints` does not take the periodicity into account because all it checks for are the `children` of a face (line 1092). That seems wrong, isn't it?

**Comment by masterleinad** [comment]
At least, it is supposed to work. AFAIK, the periodicity constraints should be taken care of in a call to `make_periodicity_constraints` and not in `make_hanging_node_constraints`. 
Do you have a testcase for which these constraints are not set correctly?

**Comment by kronbichler** [comment]
OK, that seems reasonable. I did not directly look into constraints because that is a mess, I only looked at it implicitly through `mpi/periodicity_02` when the test failed once there were hanging nodes of the kind described above, whereas it did find without. But after #5575 I'm not sure any more if this is really due to the hanging node constraints or the fragility of the Schur complement setup. Give me a day or two to check this more carefully.

**Comment by kronbichler** [comment]
I checked this more closely and it appears that hanging node constraints are indeed found. It is just that the pressure solution in `mpi/periodicity` does not make a lot of sense because it is not smooth and thus indicated trouble, see also #5575.
