### ISSUE TITLE
Test lac/schur_complement_05 is overly fragile

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#5575]
While working on #5386, I experienced issues with the `lac/schur_complement_05` test. This test checks some reference Schur complement solver (manually building `InverseMatrix` objects, the same as `mpi/periodicity_02`) with the `LinearOperator` way of doing the same. The test compares the two solutions, but it already states https://github.com/dealii/dealii/blob/master/tests/lac/schur_complement_05.cc#L650 that we won't get very accurate results. When I'm looking into things, it appears that the `InverseMatrix` type result has very strange pressure fields, and this pressure field finally makes the test fail with my changes of #5386. It also fails when I use a better mesh, namely attach a `SphericalManifold` to the whole volume rather than only `HyperBallBoundary` at the boundaries. So the test is really really fragile because a better grid makes the pressure solutions differ strongly.

After spending several hours on this test I came to the conclusion that it does not make sense any more to look for a solution because either the physical model seems to be broken or the original (reference) Schur complement solver based on inverse matrix. I'd either remove the test or choose a more stable simulation where we do understand the solution and can determine what is going on. @jppelteret you wrote that test back in January, can you comment on this issue?

**Comment by kronbichler** [comment]
Here is the modification that makes the test fail, in case someone wants to do something with it:
```
diff --git a/tests/lac/schur_complement_05.cc b/tests/lac/schur_complement_05.cc
index 70e6bdf..b83616b 100644
--- a/tests/lac/schur_complement_05.cc
+++ b/tests/lac/schur_complement_05.cc
@@ -43,7 +43,7 @@
 #include <deal.II/lac/schur_complement.h>
 
 #include <deal.II/grid/grid_generator.h>
-#include <deal.II/grid/tria_boundary_lib.h>
+#include <deal.II/grid/manifold_lib.h>
 #include <deal.II/grid/grid_tools.h>
 
 #include <deal.II/dofs/dof_renumbering.h>
@@ -81,7 +81,7 @@ namespace Step22
 
     MPI_Comm                                    mpi_communicator;
 
-    HyperShellBoundary<dim>                     boundary;
+    SphericalManifold<dim>                      boundary;
     parallel::distributed::Triangulation<dim>   triangulation;
     FESystem<dim>                               fe;
     DoFHandler<dim>                             dof_handler;
@@ -870,9 +870,11 @@ namespace Step22
     triangulation.add_periodicity(periodicity_vector);
 #endif
 
+    triangulation.set_all_manifold_ids(0);
+    triangulation.set_manifold(0, boundary);
 
-    triangulation.set_boundary(0, boundary);
-    triangulation.set_boundary(1, boundary);
+    //triangulation.set_boundary(0, boundary);
+    //triangulation.set_boundary(1, boundary);
 
     triangulation.refine_global (4-dim);
```

**Comment by jppelteret** [comment]
@kronbichler Sorry you spent so much time trying to fix it. I'm not at all familiar with the parent test on which this is based, so I will likely have nothing of substance to add in terms of finding out what's going on here. Lets delete the test - it sounds like the simplest solution for now. I can always rewrite this test based on `step-44` (for example) at a later stage.

**Comment by kronbichler** [comment]
> Sorry you spent so much time trying to fix it.

That's my fault to a large extent - I have a talent of approaching problems from the wrong angle first and continuing to dig deeper and deeper before switching to the right path... 😄 

I will go ahead and delete the test and hope that you will add a more robust test later on. Thanks for the effort!
