### ISSUE TITLE
Possible bug in petsc_vector_base

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#5576]
Hello,

I think there may be a bug in this [file](https://github.com/dealii/dealii/blob/master/source/lac/petsc_vector_base.cc#L193).
I use the operator = after the reiniting, and then set some dofs while going in a loop over cells.
When I call Vec.compress(VectorOperation::add), it gives an exception that the last state is unknown.
Since, all processors set the value to the same constant, I think the vector state should be known at the end of this function call.

```
  locally_owned_Fp = 0;
    typename DoFHandler<mesh_dim>::active_cell_iterator
    fpdg_cell = dof_handler.begin_active(),
    endc = dof_handler.end();

    std::vector<types::global_dof_index> local_dof_indices(fe_dgq.dofs_per_cell);

    for (; fpdg_cell != endc; ++fpdg_cell)
        if (fpdg_cell->is_locally_owned())
            if (std::fabs(fpdg_cell->center()(1)) < fdm->NC_layer_height / 2.0)
            {
                fpdg_cell->get_dof_indices(local_dof_indices);
                const int mid = fpdg_cell->material_id();
                dummy_fe_values.reinit(fpdg_cell);
                for (unsigned int i = 0; i < fe_dgq.dofs_per_cell; ++i)
                {
                    const Point<mesh_dim> &xx = dummy_fe_values.quadrature_point(i);
                    double Fp12 = fdm->Fp_initialization_function(xx, mid, 0);
                    const unsigned int dof = local_dof_indices[i];
                    AssertThrow(locally_owned_dofs.is_element(dof), ExcMessage("All dofs within an element are not locally owned, Assumption incorrect"));
                    locally_owned_Fp(dof) = Fp12;
                }
            }
    locally_owned_Fp.compress(VectorOperation::add); ==> gives errror here
    locally_owned_Fp.compress(VectorOperation::insert); ==> No error here
```

**Comment by masterleinad** [comment]
Can you provide us with a minimal example showing the problem so we can check?

**Comment by tjhei** [comment]
Yes, it looks like we are not resetting ``last_action``.

**Comment by sairajat** [comment]
@masterleinad  Do I still need to provide a MWE? Please let me know. Thanks.

**Comment by masterleinad** [comment]
A MWE is still very welcome.

**Comment by bangerth** [comment]
In fact, it is *always* welcome since it makes the construction of a testcase trivial for the person who ends up fixing the bug :-)

**Comment by sairajat** [comment]
Ok. I will provide with a MWE. Also, I will try to fix this.
Thanks.

**Comment by tjhei** [comment]
> Ok. I will provide with a MWE.

should be something like:
```
Vector x(10);
x[0]+=1.0;
x.compress(Add);
x=0.0;
x[0]+=1.0;
x.compress(Add);
```

> Also, I will try to fix this.

You should only need to set the ``last_action`` back to ``unknown``.

**Comment by sairajat** [comment]
Hello @tjhei , 

I was trying to fix this bug. I created this MWE and even able to replicated the bug. However,
I am confused as to how to solve this one. When the ```vector```  is declared,
the ```state``` is already set to unknown. Then, where is the state changed when ```= operator``` is used,


```
    IndexSet locally_owned_dofs;
    DoFTools::extract_locally_owned_dofs(dof_handler, locally_owned_dofs);

    LA::MPI::Vector velocity(locally_owned_dofs, mpi_communicator);

    velocity = 0;
    std::pair<unsigned int, unsigned int> lr = velocity.local_range();
    for (unsigned int i = lr.first; i < lr.second; i++)
    {
        velocity[i] = i;
    }

std::cout << " about to give error " << std::endl;
velocity.compress(VectorOperation::add);
std::cout << " No error " << std::endl;
```

**Comment by tjhei** [comment]
This example is incorrect, you need to use ``VectorOperation::Insert`` if you use ``vector[i]=...``.

**Comment by sairajat** [comment]
I am not sure if I understand correctly then. Petsc does not provide read access but I can write to any index.
So, lets say, if different processors write to index ```i```, then ```vec[i] = rank```, and then I want to add all the values, Can I not do ```Vector Operation::Add``` on the vector ```vec```

**Comment by masterleinad** [comment]
> So, lets say, if different processors write to index i, then vec[i] = rank, and then I want to add all the values, Can I not do Vector Operation::Add on the vector vec

No, using `compress` you are specifying which operation you did, i.e. for `vec[i]=...` you have to use `VectorOperation::insert` and for `vec[i]+=...` you must use `VectorOperation::add`

**Comment by tjhei** [comment]
Precisely. This is explained in http://www.dealii.org/developer/doxygen/deal.II/DEALGlossary.html#GlossCompress

**Comment by sairajat** [comment]
> No, using compress you are specifying which operation you did, i.e. for vec[i]=... you have to use VectorOperation::insert and for vec[i]+=... you must use VectorOperation::add

Oh. I always thought, even if I assign the index, doing VectorOperation::Add will add the result from all processors. Thanks a lot for the clarification.

Then, I dont think there is any problem (atleast I cant find one). 
@tjhei  The test case you wrote also works fine without any error.
