### ISSUE TITLE
p::d::SolutionTransfer and LA::d::Vector

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5615]
the documentation of [p::d::SolutionTransfer](https://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1SolutionTransfer.html#a3d25f42f962e564689dd51b3d2cdafd3) states that for interpolation vectors most likely should be non-ghosted

>  On the other hand, ghosted vectors are generally not writable, so for calls to interpolate() or deserialize() you need to supply distributed vectors without ghost elements.

Probably the documentation should be improved to state that we need to write into all locally active DoFs, which happens in https://github.com/dealii/dealii/blob/master/source/distributed/solution_transfer.cc#L246

What is not clear to me is how to actually transfer ghosted `LA::d::Vector`. Clearly that's the guy to be provided to `prepare_for_coarsening_and_refinement()`, but after `setup()` and alike, `interpolate()` can not take a ghost vector because we hit an error on compression:
```
50: An error occurred in line <530> of file </Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/lac/la_parallel_vector.templates.h> in function
50:     void dealii::LinearAlgebra::distributed::Vector<float>::compress_start(const unsigned int, ::dealii::VectorOperation::values) [Number2 = float]
50: The violated condition was:
50:     vector_is_ghosted == false
50: Additional information:
50:     Cannot call compress() on a ghosted vector
```
On another hand, it can not take a fully distributed vector 
```
LinearAlgebra::distributed::Vector<LevelNumberType> distributed(dof_handler.locally_owned_dofs (), mpi_communicator);
```
either because we are writing into locally active DoFs:
```
50: An error occurred in line <1361> of file </Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/lac/la_parallel_vector.h> in function
50:     Number &dealii::LinearAlgebra::distributed::Vector<float>::operator()(const size_type) [Number2 = float]
50: The violated condition was:
50:     partitioner->in_local_range (global_index) || partitioner->ghost_indices().is_element(global_index)
50: Additional information:
50:     You tried to access element 36288 of a distributed vector, but this element is not stored on the current processor. Note: The range of locally owned elements is 48195 to 88563, and there are 0 ghost elements that this vector can access.
```

@kronbichler can you please advise on what am I doing wrong?  Once I figure this out, I plan to update the documentation of `p::d::SolutionTransfer` to discuss usage with `LA::d::vector`s.

p.s. this is outside of `MatrixFree` framework, when vectors are initialised via `MatrixFree::initialize_dof_vector()`, there are no issues with transferring. This is what I have been doing so far.

**Comment by davydden** [comment]
it looks like
```
    displacement.zero_out_ghosts();
    soltrans.interpolate(displacement);
    displacement.update_ghost_values();
```
is the right way. The first call allows writing into ghosts, but not reading. After interpolation, `update_ghost_values` should make things synchronized and allow reading from ghosts again.

**Comment by kronbichler** [comment]
Yes, `zero_out_ghosts` before writing into the entries is the correct way of doing things with `LA::d::Vector`. The question is whether we actually need to set any other index apart from the locally owned ones. To me this seems superfluous.

We should indeed augment the documentation with respect to the locally active dofs.

**Comment by davydden** [comment]
> The question is whether we actually need to set any other index apart from the locally owned ones.

I would say ideally we don't and let the vector to exchange the data itself. But I don't even know which direction one should look at to make it happen.

That would also fix interpolation round-off errors we had with `LA::d::Vector` when we try to set the DoF on the interface between MPI domains by both processes.
