### ISSUE TITLE
Compatibility of VectorMemory<> with std::vector

### ISSUE THREAD

**Issue by juan42** [dealii/dealii#5621]
I'd like to use VectorMemory with the std::vector as a container for it. The reason for this is i need
"an array of vectors" for sensitivities in IDAS. Although using
```
template <typename VectorType>
void test_std_vector_pointer()
{
  using VecMemArray = std::vector<typename VectorMemory<VectorType>::Pointer>;

  GrowingVectorMemory<VectorType> mem;

  VecMemArray va;
  va.push_back(typename VectorMemory<VectorType>::Pointer(mem));
}
```
results in
```
error: use of deleted function ‘dealii::VectorMemory<dealii::Vector<double> >::Pointer::Pointer(const dealii::VectorMemory<dealii::Vector<double> >::Pointer&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/juan/repos/dealii/tests/lac/vector_memory.cc:20:0:
/home/juan/repos/dealii/include/deal.II/lac/vector_memory.h:187:9: note: ‘dealii::VectorMemory<dealii::Vector<double> >::Pointer::Pointer(const dealii::VectorMemory<dealii::Vector<double> >::Pointer&)’ is implicitly declared as deleted because ‘dealii::VectorMemory<dealii::Vector<double> >::Pointer’ declares a move constructor or move assignment operator
   class Pointer : public std::unique_ptr<VectorType, std::function<void (VectorType *)> >
```
1) Should this work?
2) Is there a better way to do this?

**Comment by drwells** [comment]
I am certainly not an expert in the use of this class, but I'll try to answer this.

The point of `GrowingVectorMemory` is that it returns a pointer to a vector without using `malloc`: the intended use case is when one wants to reuse a common set of vectors over lots of computations. A good example of this is in the implementation of `SolverCG::solve`.

I don't understand your use case. Why would you want to put these pointers in a `std::vector`? Regardless: the compilation error is something we can fix (we need to explicitly declare `Pointer(Pointer &&)`).

**Comment by bangerth** [comment]
Yes, adding the move constructor is the right solution here. I thought we already have it, but apparently we don't. Thanks, @drwells, for beating me to it in adding it.

**Comment by masterleinad** [comment]
#5630 included a test for this.
