### ISSUE TITLE
Creating a PETScWrappers::MPI::Vector from a PETSc Vec

### ISSUE THREAD

**Issue by juan42** [dealii/dealii#5623]
Is there any method for PETScWrappers::MPI::Vector to create an instance without copying data, s.t. i can create a PETScWrappers::MPI::Vector from a PETSc Vec, which was not created by dealii?

Although not created by dealii, i know it must have the same layout, since its an internal "copy" of a vector i created via the PETScWrappers::MPI::Vector constructor.

**Comment by drwells** [comment]
I don't believe that we support this. The closest thing that we support in the library now is using `PETScWrappers::VectorBase` in its non-owning mode. Most of the PETSc functions in deal.II take a `VectorBase` as an argument for this reason.

This is something that needs to be addressed by #5454 (which I am working on slowly).

**Comment by juan42** [comment]
So i can basically use PETScWrappers::VectorBase without problems if i keep track of my operations? Like extract the local values in callbacks for SNES for example (manually do what FEValuesBase::get_function_values() does since it is not instantiated on VectorBase).

**Comment by drwells** [comment]
I believe that the answer is yes. At the same time, that particular constructor (that takes a `Vec` as argument) assumes that the vector is not ghosted so it might not work if you need ghost entries

I'm not sure why we don't support `VectorBase` in that instantiation list. I believe that the plan is to ultimately just support these functions with `ReadWriteVector`, so I don't think supporting `VectorBase` here is in the near future. For now it might be better to use `FEValuesBase::get_function_values_from_local_dof_values` if you have a copy of the development version.

**Comment by bangerth** [comment]
By the way, why do it that way anyway? Why not just create your vectors via the deal.II PETSc wrappers? You can always get the underlying `Vec` out of them. Or where are you getting a `Vec` from that you want to put under control of a deal.II class?

**Comment by juan42** [comment]
I get the Vec objects from converted N_Vector objects of the Sundials PETSc interface.

**Comment by bangerth** [comment]
I see. Have you found a way to work around this?

**Comment by juan42** [comment]
I just use the PETScWrappers::VectorBase for now.

**Comment by ChaliZhg** [comment]
> I just use the PETScWrappers::VectorBase for now.
Hi @juan42 , I have exactly the same problem here. Is there a way to convert PETScWrappers::VectorBase to PETScWrappers::MPI::Vector or Vector<double>, so that I can distribute constraints or visualize the solution?

**Comment by jppelteret** [comment]
@ChaliZhg There looks to be a [copy constructor for `dealii::Vector`](http://dealii.org/developer/doxygen/deal.II/classVector.html#a6478b634eb646ffaa11f6f82b91d92a9) that takes in a `PETScWrappers::VectorBase`. Does this not work for you?

**Comment by Rombur** [comment]
@jppelteret This exists only in the development version. In 8.5, the copy constructor only takes a derived type. So @ChaliZhg, you probably want to use the development version of deal.

**Comment by ChaliZhg** [comment]
@jppelteret @Rombur Thanks very much for pointing out that. I'll give it a go in the developer version.

**Comment by jppelteret** [comment]
Thanks for pointing that our @Rombur. It didn't cross my mind that the interface could have changed recently.
