### ISSUE TITLE
GMSH config is broken

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5644]
on macOS with the directory structure
```
<gmsh_prefix>/include/gmsh/*.h
<gmsh_prefix>/bin/gmsh
```
`dealii` currently picked up
```
GMSH_EXE:FILEPATH=<gmsh_prefix>/include/gmsh
```

Given that the whole configure is a single command: 
https://github.com/dealii/dealii/blob/master/cmake/modules/FindGMSH.cmake#L27-L30 which in turn is just a wrapper around `FIND_FILE` https://github.com/dealii/dealii/blob/master/cmake/macros/macro_deal_ii_find_file.cmake#L21, 
I have no idea how it ends up picking directory instead of binary... @tamiko ideas?

EDIT: 

Strangely enough appears to be expected behaviour, we don't specify `NO_DEFAULT_PATH`, therefore  `Cmake` starts with[1]

> Search paths specified in cmake-specific cache variables. These are intended to be used on the command line with a -DVAR=value. This can be skipped if NO_CMAKE_PATH is passed.
<prefix>/include/<arch> if CMAKE_LIBRARY_ARCHITECTURE is set, and <prefix>/include for each <prefix> in CMAKE_PREFIX_PATH
CMAKE_INCLUDE_PATH
CMAKE_FRAMEWORK_PATH

In my case, I have `gmsh` prefix in `CMAKE_PREFIX_PATH`. It still appears to be a bug in CMake as they find a directory instead of a file, but at least the result is consistent with the documentation...

p.s. `HINTS` are only number (3) in the list of paths to search...

[1] https://cmake.org/cmake/help/v3.0/command/find_file.html

**Comment by tamiko** [comment]
Easy fix - we need a `find_program` variant. `find_file` and `DEAL_II_FIND_FILE` (a wrapper around is) are primarily intended to find header files.
