### ISSUE TITLE
Fortran name mangling

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5657]
In various interfaces (`arpack`, `parpack`, `lapack`, `blas`, `scalapack`) we assume that name mangling is `name_`. We should eventually adopt something like

```
cmake_minimum_required(VERSION 2.8.6)
project(fortranc Fortran C CXX)
include(FortranCInterface)
FortranCInterface_HEADER(FC.h MACRO_NAMESPACE “FC_”)
#This creates a “FC.h” header that defines mangling macros
# FC_GLOBAL(), FC_GLOBAL_(), FC_MODULE(), and FC_MODULE_().
FortranCInterface_VERIFY(CXX)
FortranCInterface_VERIFY()
```

and fall back to 

```
#define “FC_”GLOBAL(name,NAME) name##_
```
in case Fortran compiler was not available during configuration.

Here's one config example https://github.com/elemental/Elemental/blob/master/cmake/detect/Fortran.cmake

**Comment by bangerth** [comment]
Do we have an example of where this fails? Is this critical and needs to be addressed for 9.0?

**Comment by davydden** [comment]
> Do we have an example of where this fails?

I did not came across, but I think ideally it's the right way to do (I see other projects doing this).

>  Is this critical and needs to be addressed for 9.0?

nah, i changed it to 9.1.

**Comment by davydden** [comment]
@bangerth 

> Do we have an example of where this fails?

judging from this comment on Trilinos-related issue https://github.com/spack/spack/issues/7247#issuecomment-390288606 Blas/Lapack/Scalapack/Arpack wrappers would fail with XL fortran compiler on IBM Power.

@Rombur @kronbichler did you try compiling deal.II with XL?

@tamiko since you know our CMake well, do you think we can get the right Fortran mangling to be on the safe side?

**Comment by Rombur** [comment]
No I haven't. I can't compile much simpler code than deal with XL...

**Comment by bangerth** [comment]
I've cursed the XLC compiler about as often as the MS VisualStudio compiler in my life...

**Comment by kronbichler** [comment]
We won't have this completed for now.

**Comment by masterleinad** [comment]
Since there is no demand, let's postpone.
