### ISSUE TITLE
CylindricalManifold<2> doesn't provide an implementation

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5683]
A `CylindricalManifold<2>` just describes just a `StraightBoundary`. Since we don't want to have a `static_assert` in the class template to allow for a dimension independent implementation, we should provide an implementation by deriving from `StraightBoundary`.

**Comment by davydden** [comment]
i guess it depends which dimension one wants to remove, i though the 2D case should be a circle.

**Comment by Rombur** [comment]
I have never heard of the 2D case being a circle. Usually people assume that the solution is symmetric and thus, the left side is the origin of the "circle" and the right side is the "exterior" of the cylinder.

**Comment by masterleinad** [comment]
At least using `FlatManifold` as replacement for `CylinderBoundary<2>` passes the tests.

**Comment by bangerth** [comment]
I would also have expected a "cylinder" in 2d to be a circle. Are you thinking of the (surface of the) cylinder as the `r-phi` space you get when you work in 2d? I think of the cylinder as just that -- a rod-shaped object in x-y-z space. In that case, the natural restriction to 2d would just be a cylinder.

**Comment by masterleinad** [comment]
If there is no agreement on what a two-dimensional cylinder is, let us go with the regular `Assert`.
