### ISSUE TITLE
step-58: Solving the Nonlinear Schroedinger Equation with an operator splitting approach

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5746]
I'm halfway through writing a code for the Nonlinear Schroedinger Equation that I promised to Yongyong Cai last year. The purpose of this issue is simply to claim step-58 for this purpose.

**Comment by drwells** [comment]
@bangerth As mentioned by @krishnakumarg1984 we reserved this slot but didn't put anything in it. Will we have time to finish this by the next release?

**Comment by bangerth** [comment]
Yes, I think so.

**Comment by drwells** [comment]
Fixed by #9892 et al.
