### ISSUE TITLE
Problem for VectorizedArray * VectorizedArray for complex-valued vectors

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5751]
As part of #5747, I also looked at `VectorizedArray`. This class underlies the vectorized implementation here:
```
    template <typename Number>
    struct AddAndDot
    {
      static const bool vectorizes = VectorizedArray<Number>::n_array_elements > 1;

      AddAndDot(Number *X, const Number *V, const Number *W, Number a)
        :
        X(X),
        V(V),
        W(W),
        a(a)
      {}

      Number
      operator() (const size_type i) const
      {
        X[i] += a * V[i];
        return X[i] * Number(numbers::NumberTraits<Number>::conjugate(W[i]));
      }

      VectorizedArray<Number>
      do_vectorized(const size_type i) const
      {
        VectorizedArray<Number> x, w, v;
        x.load(X+i);
        v.load(V+i);
        x += a * v;
        x.store(X+i);
        // may only load from W after storing in X because the pointers might
        // point to the same memory
        w.load(W+i);
        return x * w;
      }

      Number *X;
      const Number *V, *W;
      Number a;
    };
```

So in `operator()`, we do take the complex-conjugate of the second argument `W`. In the `do_vectorized()` function, we defer to `operator*` between two `VectorizedArray` objects, which goes here:
```
template <typename Number>
inline DEAL_II_ALWAYS_INLINE
VectorizedArray<Number>
operator * (const VectorizedArray<Number> &u,
            const VectorizedArray<Number> &v)
{
  VectorizedArray<Number> tmp = u;
  return tmp*=v;
}
```
This is already slightly awkward, because the connotation we have for `vector * vector` everywhere else is that it's a scalar product that requires taking the complex-conjugate of the second argument, but we don't have the same connotation for `operator *=` and indeed this operator is used in contexts where this is clearly not desirable.

But, in any case, it yields a call to this function:
```
  // general template
  VectorizedArray &
  operator *= (const VectorizedArray<Number> &vec)
  {
    data*=vec.data;
    return *this;
  }

  // one of the other cases
  VectorizedArray &
  operator *= (const VectorizedArray &vec)
  {
#ifdef DEAL_II_COMPILER_USE_VECTOR_ARITHMETICS
    data *= vec.data;
#else
    data = _mm512_mul_pd(data,vec.data);
#endif
    return *this;
  }
```

I guess for the various specializations of `VectorizedArray<double>` and `VectorizedArray<float>` that deal with particular processor architectures, this is ok. But the implementation would appear to be wrong for `VectorizedArray<std::complex<...>>`.

@kronbichler -- how do you think?

**Comment by kronbichler** [comment]
@bangerth Shouldn't we only arrive in the `do_vectorized` path only in case `VectorizedArray<Number>` has more than one entry, i.e., only for `VectorizedArray<double>` and `VectorizedArray<float>` but not for `VectorizedArray<std::complex<double>>`? There is a flag `Operation::vectorizes` that is used in `lac/vector_operations_internal.h` that only allows to select the path with `VectorizedArray` (that is not able to take the complex conjugate, and I wouldn't want to extend it either) for real scalars. From what I understood from #5747 it appears that you indeed get correct results with the deal.II vector classes for complex numbers, so we do select right path, don't we?

**Comment by bangerth** [comment]
I think you point out what I didn't understand -- namely, how we get to the `do_vectorized()` function to begin with. Are you saying that we can't get into this function unless the concrete data type is a real number? At least at the moment?

As far as correct results -- I don't actually know. I haven't tested the `add_and_dot()` function for complex-valued problems so far, and I don't think there are any existing tests either.

**Comment by bangerth** [comment]
@kronbichler : Can you take a look whether #5757 then makes sense?

**Comment by kronbichler** [comment]
@bangerth What happens is the following: We switch between different paths that either use `operator()` or `do_vectorized` by an `std::integral_constant<bool,false>` or `std::integral_constant<bool,true>` in the call to `accumulate_regular`, e.g. over here:
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/vector_operations_internal.h#L953

The `true/false` type is determined by `Operation::vectorizes` which uses the `static bool` variable in the various operations (inner product, norm, add and dot) that gets true in case `VectorizedArray<Number>::n_array_elements > 1`, i.e., we actually get some benefit from vectorization. This is a lot of template magic, but in the end I have written that code so that it really only does use the vectorized types when we know that they are real and either `double` or `float`, because that's the only types where `n_array_elements` might be larger than one.

**Comment by bangerth** [comment]
Great, thanks for the explanation!
