### ISSUE TITLE
Tweak documentation for hp::DoFHander::n_locally_owned_dofs_per_processor()

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#5762]
See [this comment](https://github.com/dealii/dealii/issues/5753#issuecomment-358754215) for the reason for it to be updated and [this one](https://github.com/dealii/dealii/issues/5753#issuecomment-358769734) for what the new text should be.

**Comment by bangerth** [comment]
@jppelteret -- I know you self-assigned this, but I took care of it in #5766.

**Comment by jppelteret** [comment]
Thank you very much @bangerth!
