### ISSUE TITLE
Update DoFRenumbering::subdomain_wise()

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#5763]
The function `DoFRenumbering::subdomain_wise()` is incompatible with `parallel::shared::Triangulation` according to [this comment](https://github.com/dealii/dealii/issues/5753#issuecomment-358731555). Update the documentation to reflect this, and add an assertion to prevent use with incompatible triangulations.

**Comment by bangerth** [comment]
Isn't the *default* numbering equivalent to `subdomain_wise()`? I don't understand why that would be inappropriate. @tjhei -- care to elaborate why this can't work?

**Comment by jppelteret** [comment]
I would have thought so. I've been debating whether we should rather just have an early return if using `p::s::Tria` instead of an assertion - maybe that would be better.

**Comment by bangerth** [comment]
It may be that someone renumbered in some way, and now wants to get back to the standard numbering. So I don't think the operation is meaningless.

**Comment by bangerth** [comment]
@tjhei -- I think the original comment was by you. Any suggestions?

**Comment by tjhei** [comment]
I consider it wrong to allow a ``subdomain_wise`` renumbering for ``p::shared`` or ``p::distributed``.  The mesh is already numbered by it. The user could (even inconsistently) change the subdomain_ids before making this call so we would need to be able to handle that case. We would also need to make sure we handle the hidden subdomain_ids (allow artificial cells), etc..

> It may be that someone renumbered in some way, and now wants to get back to the standard numbering.

I don't think that this is a useful idiom.

All that said: if you can make a case for a use and make it work, I am not opposed (but I would be confused seeing this in some user code). I think it is just simpler to disallow it and tell the user: "this is not needed".

**Comment by bangerth** [comment]
I don't feel strongly. I can see your point.
