### ISSUE TITLE
it would be good to have macOS tester on Travis

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5771]
i don't know details of how current `gcc` and `clang` linux testers are setup on Travis, but it would be good to have another one with macOS + Apple's clang to test PRs before merging.

**Comment by luca-heltai** [comment]
The issue is always compilation time. About 50% of the times, compilation does not go through because of time limits.

**Comment by tjhei** [comment]
Can you explain why clang on osx behaves differently than clang under linux? do we just need to compile+link the library?

**Comment by davydden** [comment]
> Can you explain why clang on osx behaves differently than clang under linux?

Because `Apple's Clang != LLVM Clang`.  `clang` from LLVM probably behaves the same on macOS as on linux.

> do we just need to compile+link the library?

yes, I think this would be a good start to make sure we don't break `dealii` on macOS.

**Comment by tjhei** [comment]
We would need to decide what dependencies we want and if it is enough to do only the debug build. Thoughts?

**Comment by davydden** [comment]
> what dependencies we want

I suppose those which fit the time limit @luca-heltai was speaking about.

> it is enough to do only the debug build

i would say so.

**Comment by masterleinad** [comment]
If you really want to use `Travis`, I don't think building for each PR is reasonable since starting the build takes a really long time (due to the large backlog https://www.traviscistatus.com/).

**Comment by tjhei** [comment]
So the problem is that I don't know of a way to sandbox the environment on OSX. It seems like virtualbox only supports a single core, vmware and parallels are not free, and there is no other way to run a clean unchanging environment I can roll back to after every build. Thoughts?

**Comment by davydden** [comment]
> there is no other way to run a clean unchanging environment I can roll back to after every build. Thoughts?

If I understand correctly, `spack` can do this. That's how I run dealii tests on my Ubuntu box, but in this case it would be enough just to build https://github.com/davydden/dealii-testsuite-Spack/blob/master/dealii-spack-tests.sh

**Comment by tjhei** [comment]
> If I understand correctly, spack can do this

I also want network, memory, disk, and time limits that are enforced. Otherwise the code can (un)willingly break my machine.

**Comment by davydden** [comment]
> I also want network, memory, disk, and time limits that are enforced.

Ah, I see. That would not help then

**Comment by davydden** [comment]
@tjhei it looks like you have a testers already `tjhei-osx`? Is it still a WIP ?

**Comment by tjhei** [comment]
Kind of. I don't know if the current configuration is useful, I assume some stuff will break in the first couple of days, and the output is not as pretty as it could be (but I don't have time to mess with this more right now).

**Comment by davydden** [comment]
great! Let's close this issue for now.
