### ISSUE TITLE
Optimize Utilities::pack/unpack for small POD objects

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5789]
We're starting to use `Utilities::pack` and `unpack` now in our MPI wrappers (see, for example, #5784). This is probably inefficient if we just exchange a couple of `int`s, for example, so we should introduce a fast path into these functions. Specifically, I'm thinking of something like this:
* If `T` is a POD or array of PODs, and if `sizeof(T)` is less than some magic number (say, 256 bytes), then just do a `memcpy` into the output buffer
* Otherwise, go through the existing path that uses (potentially compressed) BOOST serialization functions.

The idea being that if the object is small, then compression is likely not going to help much anyway. If, further, the object is POD, then `memcpy` guarantees a 1:1 transmission of data.

**Comment by bangerth** [comment]
I have a patch that is based on `std::is_trivially_copyable`, which is the predicate needed to determine whether something can be used with `std::memcpy`. But my gcc 4.8 rejects it. I wonder whether 4.8 claims to support C++11, but doesn't actually in this regard :-(

Can any of you with newer compilers test whether this code compiles:
```
#include <type_traits>

bool b = std::is_trivially_copyable<int>::value;
```

**Comment by bangerth** [comment]
Aw: https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std :-(

**Comment by masterleinad** [comment]
That's what https://godbolt.org/ is for :wink: `gcc-5.1` is the first version for which this compiles.

**Comment by davydden** [comment]
Maybe add a confit test to check if compiler supports it?

**Comment by bangerth** [comment]
I have a workaround.
