### ISSUE TITLE
Help CMake export the name of the executable into Eclipse projects

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#579]
When you call
```
  cmake -G"Eclipse CDT4 - Unix Makefiles" .
```
in a tutorial program directory, it very nicely sets up an Eclipse project that has all of the include directories and Makefile targets set up already -- outstanding service. Eclipse resolves practically all of the symbols in the step-XX.cc source files correctly and offers auto-completion, etc.

The one piece that's missing is that it doesn't know about any of the "Run configurations" or "Debug configurations", i.e., the name and path of the executables that are built and that one could then run inside Eclipse using the "run" and "debug" buttons at the top. It's not a big deal to set this up by hand (much less than, say, figuring out the issue with include paths) but it would still be nice if there was a way to have this done automatically.

I don't know if that's a consequence of us not making this information available, or of CMake not exporting it to Eclipse. It would just be nice to see if we could make this work.

(It would be interesting to also see whether CMake exports this sort of thing to Xcode, for example, as another data point.)

**Comment by bangerth** [comment]
This comments on the problem:
  http://www.cmake.org/pipermail/cmake/2012-June/050582.html
But I don't understand the person's self-reply...

**Comment by tamiko** [comment]
I fear that there is not much we can do about this. I cannot find a target/global scope property or cmake variable allowing to set any eclipse specific behavior in this direction.

**Comment by tamiko** [comment]
@bangerth Can you try to change the project name of one of the example steps such that the target and the project doesn't have the same name any more:
```
diff --git a/examples/step-1/CMakeLists.txt b/examples/step-1/CMakeLists.txt
index d69a1b1..c0a99c5 100644
--- a/examples/step-1/CMakeLists.txt
+++ b/examples/step-1/CMakeLists.txt
@@ -35,5 +35,5 @@ IF(NOT ${deal.II_FOUND})
 ENDIF()
 
 DEAL_II_INITIALIZE_CACHED_VARIABLES()
-PROJECT(${TARGET})
+PROJECT(foo)
 DEAL_II_INVOKE_AUTOPILOT()
```
 and try again to generate an eclipse configuration?

**Comment by bangerth** [comment]
So, a year and a half after opening this PR, this seems to actually work, both with and without your workaround. It's not clear to me what changed, if anything. (I did upgrade Eclipse in the meantime.) One of the things I noticed is that I need to highlight the project I want to debug in the "Projects" panel. I often don't do that because you can have multiple projects open at the same time, and open/edit files from any of them, so I don't care which one is highlighted as long as they're all open.

Either way, it seems to be all good now.
