### ISSUE TITLE
continuous integration with warnings as errors

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5795]
We should run continuous integration with warnings as errors to avoid things like #5791.

**Comment by drwells** [comment]
This sounds reasonable since we completely control those testing environments.

**Comment by tjhei** [comment]
it might be annoying in the sense that more builds will fail during patch review though. Maybe worth trying out.

**Comment by bangerth** [comment]
We have to  go back to fix warnings one way or the other. Putting this onto the original submitter by making the CI tester error out seems like the least disruptive way for dealing with the issue.

**Comment by masterleinad** [comment]
According to https://github.com/dealii/dealii/pull/5414#issuecomment-364478717, it seems that at least tjhei-osx is using `-Werror`. Can we close then?

**Comment by tjhei** [comment]
yep!
