### ISSUE TITLE
Expand the kinds of information that can be passed through Triangulation::create_triangulation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#583]
Right now, one can only set material_id in CellData and boundary_id in SubCellData. It would be nice if one could pass other information as well. This is motivated by a question by Pavel Kus on the mailing list in the last week. But it should in fact be quite useful also for mesh files that allow specifying other fields than just vertices, cells, and material ids.

It should actually not be particularly difficult -- just add some fields to these two classes, initialize them with what the triangulation currently sets them to, then modify create_triangulation to pass the field through.

**Comment by drwells** [comment]
I'd prefer not to do this since it adds a rather complex amount of data that needs to be tracked in `create_triangulation`. Users should instead use the material id to track these things.
