### ISSUE TITLE
 mpi/codim_01.mpirun=3 fails almost on all testers

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5839]
subj.

https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=mpi%2Fcodim_01.mpirun%3D3.debug&date=2018-01-31

**Comment by masterleinad** [comment]
It seems we just need an alternative test output without
```
<PPointData>
</PPointData>
```
Unfortunately, the test is not failing for me.

**Comment by drwells** [comment]
Same as #3910. I think.
