### ISSUE TITLE
GridRefinement only instantiated for Vector<Number>

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5858]
Currently, we only instantiate the `GridRefinement` methods only for `Vector<Number>`.
That means that these functions can only be used for `VectorType=Vector<Number>` which seems to be sufficient. In particular, I don't see a reason to ever use a different template type. It might be that even `Vector` is not ideal here, but this is what, e.g. `KellyErrorEstimator` provides.
Hence, I am in favor of changing the signature to always use a `Vector<Number>` type and to clean up the source files in this regards. 
This change is even backwards-compatible as long as the template parameters are not explicitly specified.
What do others think?

**Comment by bangerth** [comment]
That'd be ok with me.
