### ISSUE TITLE
Replace interface returning owning raw pointers

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5880]
We have multiple functions that return owning raw pointers such as `Mapping::clone` or `FETools::get_fe_by_name`. We should consider to return a `std::unique_ptr` instead to prevent memory leaks.

**Comment by drwells** [comment]
I actually have written the `Mapping` replacement. I'll put up a PR soon.

**Comment by masterleinad** [comment]
I am curious how you deal with the covariant return type.

**Comment by masterleinad** [comment]
I'll provide the `FETools::get_fe_by_name` part then.

**Comment by drwells** [comment]
My opinion is that we should remove the covariant behavior; if people really need it then they should `dynamic_cast`.

We could keep and extend the dynamic behavior by doing the following:

```cpp
class Parent
{
public: 
  // not virtual, but every class must implement
  std::unique_ptr<Parent> clone() const
  {
    return do_clone();
  }
protected:
   virtual Parent* do_clone() const =0
  {
    return new Parent(*this);
  }
};

class Child : public Parent
{
public:
  // hides, not overrides, the parent version
  std::unique_ptr<Child> clone() const
  {
    return do_clone();
  }
protected:
  Child* do_clone() const override
  {
    return new Child(*this);
  }
};
```

but I prefer just returning `std::unique_ptr<Mapping>` everywhere, since its what we do with e.g. `FiniteElement`.

**Comment by bangerth** [comment]
I think it's ok to give up the covariantness.

**Comment by drwells** [comment]
We are also somewhat inconsistent in how we do it: in principle, we could use it in every class inheriting from `Mapping`, but we only do it for the Q1 mappings (confusingly, MappingQ1Eulerian is treated differently than MappingQEulerian).

**Comment by bangerth** [comment]
@masterleinad : Are there any cases left that you are thinking of?

**Comment by masterleinad** [comment]
I am preparing a PR for `FilteredIteratpr*::clone`.

Apart from that I currently only find `Mapping::get_*data` which uses a covariant return type in the derived classes. Since these methods are at least `protected`, I would also be fine to just let them be.

**Comment by bangerth** [comment]
I suspect that the mapping functions should be easy to convert since they're only used in the `FEValues` classes. But you're right, this is not urgent.

**Comment by bangerth** [comment]
I decided to work on the mappings anyway. Will take a couple of hours, but I'm on it.

**Comment by masterleinad** [comment]
Then, I will also look after `FiniteElement::get_*data`.

**Comment by bangerth** [comment]
Give it a bit -- there is a wrinkle with using `Task<T>` if `T` is not copyable that I'll have to work out first.

**Comment by bangerth** [comment]
Nice -- I think we're now done with this!
