### ISSUE TITLE
document math operations consistently (latex instead of HTML)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5897]
we have a mixture of documentation styles, in some places we have

> <tt>C = A<sup>T</sup> * B</tt>

in others the same would be

> $C = A^T * B$

I think we should use the later consistently throughout.

EDIT: 

given results of [this poll](https://github.com/dealii/dealii/pull/5899#issuecomment-370182879), we should use consistently `\mathbf{C} = \mathbf{A}^T \cdot \mathbf{B}` and alike.

**Comment by bangerth** [comment]
I think @rezarastak did a lot of work in one his patches on this. I'd suggest that we close this given that I don't see a way to find all of the places where changes are necessary.
