### ISSUE TITLE
scalapack_10_b has strange scaling

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#5958]
This test takes me 5 minutes in both debug and release mode (with `mpirun=11`), but only 23 seconds with `mpirun=1`. Aside from being too long, this seems to indicate that there is something strange going on.

I did my measurements on a 4 core machine (with hyperthreading) so its possible that the saturation messed up the timing.

**Comment by drwells** [comment]
Help me, @davydden :)

**Comment by davydden** [comment]
Can u please check which part takes that long, curious whether or not it’s Scalapack’s selective eigenfunction method which has issues.

**Comment by drwells** [comment]
Sure.

I added timers everywhere. Here is the expensive bit:
```cpp
  {
    TimerOutput::Scope scope(timer_out, "copy and load");
    scalapack_matrix = full;
    scalapack_matrix.save(filename.c_str(),chunk_size);
    scalapack_matrix_copy.load(filename.c_str());
  }
```

Here is the output from the first (of 72) tests:


```
100x75 & 1 & 1x1


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      4.25s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| copy                            |         1 |  5.18e-05s |         0% |
| copy and load                   |         1 |      3.83s |        90% |
| copy full matrix                |         1 |  0.000426s |         0% |
| create_random                   |         1 |  0.000253s |         0% |
| output and frobenius norm       |         1 |  0.000337s |         0% |
| proccess_grid                   |         1 |     0.415s |       9.8% |
| remove file                     |         1 |  1.89e-05s |         0% |
+---------------------------------+-----------+------------+------------+
```

Copying seems to take about 4 seconds in each case, independently of matrix sizes
(if I have understood the test correctly).

A more fine-grained test where I chop things up as 

```cpp
  {
    {
      TimerOutput::Scope scope(timer_out, "set equal to full");
      scalapack_matrix = full;
    }
    {
      TimerOutput::Scope scope(timer_out, "save to disk");
      scalapack_matrix.save(filename.c_str(),chunk_size);
    }
    {
      TimerOutput::Scope scope(timer_out, "load from disk");
      scalapack_matrix_copy.load(filename.c_str());
    }
  }
```

yields

```
100x75 & 1 & 1x1


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      4.27s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| copy                            |         1 |  4.36e-05s |         0% |
| copy full matrix                |         1 |  0.000429s |         0% |
| create_random                   |         1 |  0.000274s |         0% |
| load from disk                  |         1 |      2.01s |        47% |
| output and frobenius norm       |         1 |   0.00034s |         0% |
| proccess_grid                   |         1 |     0.429s |        10% |
| remove file                     |         1 |  1.71e-05s |         0% |
| save to disk                    |         1 |      1.82s |        43% |
| set equal to full               |         1 |   5.1e-05s |         0% |
+---------------------------------+-----------+------------+------------+
```

so it really is both loading and saving.

**Comment by drwells** [comment]
This might be a problem with my own MPI and HDF5 installations; I'll try on another machine later today.

**Comment by davydden** [comment]
yes, that looks like `hdf5` related, not sure whether it's our fault or not...
@BenBrands have you seen any slowdowns with `hdf5` like the one here? Could you please run the test locally and see if it also takes abnormal amount of time for you?

**Comment by BenBrands** [comment]
I cannot run the tests on my machine, it is currently broken.
The reason why the test takes so much time are most likely the prescribed `chunk_sizes`, especially the very small `chunk_size` 1. For that setting the communication inside HDF5 determines the run time.
We certainly could choose larger values!

**Comment by drwells** [comment]
This test runs in a much more reasonable amount of time on my workstation, so I am going to tentatively label this as 'but definitely not our fault' (though it might be good to increase the chunk size).

**Comment by drwells** [comment]
Another interesting measurement: on my 4 core system, going from 8 cores to 9 cores (desktop) or 32 to 33 cores (workstation) causes massive slowdowns (about a factor of 20).

**Comment by davydden** [comment]
@drwells 

> going from 8 cores to 9 cores (desktop, 4 cores) or 32 to 33 cores (workstation, 16 cores) causes massive slowdowns (about a factor of 20).

wow, does this change for different chunk sizes or their relationship with matrix/block size? we currently test a couple of them https://github.com/dealii/dealii/blob/master/tests/scalapack/scalapack_10_b.cc#L82-L85 each with different size of the matrix and a block size of its distribution. 

I just discussed it with @BenBrands . Internally we first copy the block-cyclick distributed matrix into auxiliary matrix which has row process grid, that is each process own a contiguous set of rows of the original matrix. Then this matrix is written using `hdf5` and its chunk sizes. It's very likely that this stage is the problem for large matrices with small chunk size as, if I understand it correct, `hdf5` would be writing the matrix into the file in those chunks. 

Could you please try if something like
```
if (std::min(sizes[i].first,sizes[i].second) <= std::min(chunk_sizes[k].first,chunk_sizes[k].second) *10  ||
    std::min(sizes[i].first,sizes[i].second) < 100)
  test<double>(sizes[i],block_sizes[j],chunk_sizes[k]);
```
helps?

**Comment by drwells** [comment]
I changed the body of the test to
```cpp
 for (unsigned int i=0; i<sizes.size(); ++i)
    for (unsigned int j=0; j<block_sizes.size(); ++j)
      for (unsigned int k=0; k<chunk_sizes.size(); ++k)
        {
          if (std::min(sizes[i].first,sizes[i].second)
              <= std::min(chunk_sizes[k].first,chunk_sizes[k].second) *10  ||
              std::min(sizes[i].first,sizes[i].second) < 100)
            test<double>(sizes[i],block_sizes[j],chunk_sizes[k]);
        }

  for (unsigned int i=0; i<sizes.size(); ++i)
    for (unsigned int j=0; j<block_sizes.size(); ++j)
      for (unsigned int k=0; k<chunk_sizes.size(); ++k)
        {
          if (std::min(sizes[i].first,sizes[i].second)
              <= std::min(chunk_sizes[k].first,chunk_sizes[k].second) *10  ||
              std::min(sizes[i].first,sizes[i].second) < 100)
            test<float>(sizes[i],block_sizes[j],chunk_sizes[k]);
        }
```

but it does not seem to help: my laptop can do this with `mpirun=4` in about 2 seconds but needs 100 seconds with `mpirun=5`.

**Comment by BenBrands** [comment]
@drwells: I will try it tomorrow on my machines and report about the timings!

**Comment by BenBrands** [comment]
I did some timings inside `ScaLAPACKMatrix::save_parallel()` for two machines (one with 4 the other with 6 physical cores). For the 4 core machine I can confirm that mpirun=5 causes significantly longer run times, for the 6 core machine the limit seems to be mpirun=16.

To my surprise, it is not exclusively the HDF5 function calls causing the run time to increase. The run times for both copying the matrix to a row grid using ScaLAPACK functions as well as writing that matrix to the file using HDF5 severely suffer from the MPI over-subscription.

Perhaps, I can run further tests and timings on a cluster to check the scalability in a few weeks.

**Comment by davydden** [comment]
@drwells i guess the takeaway message is that this functionality slows down considerably if we oversubscribe  (33 vs 32 on 16-core or 9 vs 8 on 4-core). If you don't mind, I think we can close this issue as a user would not, in general, oversubscribe.

**Comment by drwells** [comment]
I agree that this will not be an issue in practice. We do usually oversubscribe when running the test suite (at least I do): would it be reasonable to shorten some of the tests that use a lot of MPI processes?

**Comment by BenBrands** [comment]
I can shorten it by choosing less parameters.

**Comment by drwells** [comment]
I think the tentative conclusion fro #5973 is that this is due to something inside an external library. I'll keep an eye out for very long tests but there is nothing else for us to do here.
