### ISSUE TITLE
sum(Tensor, MPI_Comm) is not in Utilities::MPI

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5962]
i just saw that the global reduction of the tensor over MPI comm is not in `Utilities::MPI` namespace. Anyone recall the reason for that? It should probably work OOB with [this sum](https://www.dealii.org/developer/doxygen/deal.II/namespaceUtilities_1_1MPI.html#afaf69c2cc054b615707da05e05239b1c) as `Tensor` should be representable as an `ArrayView`.

**Comment by masterleinad** [comment]
There is 
```
Tensor< rank, dim, Number > sum 
(const Tensor< rank, dim, Number > & local,
 const MPI_Comm & mpi_communicator)
```
 [here](https://www.dealii.org/developer/doxygen/deal.II/classTensor.html#af47eaebd03e0a183fd38a09d8863659f).

**Comment by davydden** [comment]
> There is

i know, that's exactly my point -- why is it there and not in `Utilities::MPI`?

**Comment by masterleinad** [comment]
It is declared at the same place as all the other `sum`, i.e. only doxygen shows it at a different place. In particular, we have the test `mpi/collective_tensor` which shows that the function is in `Utilities::MPI`.

**Comment by davydden** [comment]
Ah, that’s strange. Thanks for clarifying.
