### ISSUE TITLE
p::d::Tria in 1D

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5972]
are there any principal difficulties why we can't have `p::d::Tria` in 1D? Maybe fall-back somehow to `p::s::Tria` or alike? I would really like to run the same code on some simple 1D problems, but I see that even the constructor for `dim==1` is not matching to the one in `dim>=2`:

```
    template <int spacedim>
    Triangulation<1,spacedim>::Triangulation (MPI_Comm)
      :
      dealii::parallel::Triangulation<1,spacedim>(MPI_COMM_WORLD,
                                                  typename dealii::Triangulation<1,spacedim>::MeshSmoothing(),
                                                  false)
    {
      Assert (false, ExcNotImplemented());
    }
```

**Comment by tjhei** [comment]
It sounds useful to have for testing purposes. Of course I don't see a reason for parallel computing or a distributed mesh for 1d problems because the problems are tiny. How far can you get if you switch to ``p::s::`` in 1d?

**Comment by davydden** [comment]
> How far can you get if you switch to p::s:: in 1d?

i don't know, i have not tried yet. Do you suggest trying it via inheritance for `p::d::Tria`
```
class Triangulation<1,spacedim> : public dealii::parallel::shared::Triangulation<1,spacedim>
{
}
```
