### ISSUE TITLE
Improve AffineConstraints::distribute() for multiple p::d::Vector

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5978]
`ConstraintMarix::distribute()` call first figures out needed elements to distribute constraints in [this part](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/constraint_matrix.templates.h#L883-L891), and then creates a copy ghosted vector which communicates all we need.
Both operations can be very time-consuming if `distribute` is applied to ~100 of vectors with the same MPI partition (multi-vector).

There are three things one can do better:

1. Figure out `needed_elements` once for all ~100 vectors (i.e. take `std::vector<Vec*>` to be general)
2. Avoid copying the vector if `needed_elements` is already a subset of ghosts
3. Use `p::d::Vector::local_element()` for `O(1)` access

p.s. something similar must be happening already in `matrix-free` class, so maybe one can re-use some code or refactor it to avoid duplication. @kronbichler what do you think?

**Comment by bangerth** [comment]
You could cache the `needed_elements` and corresponding vector. You'd have to invalidate them if the partitioning of the vectors passed in changes, but it should be possible to make this work.

**Comment by bangerth** [comment]
We now compute the needed elements in `close()`, see the PRs linked to from #15375.

**Comment by bangerth** [comment]
What is missing is to construct a partitioner in `close()` already.

**Comment by bangerth** [comment]
This is also tracked in #15988. Let's close this one.
