### ISSUE TITLE
warnings from #5974 in Function::Spherical

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#5981]
I see warnings like
```
/.../dealii/source/base/function_spherical.cc:255:43: warning: ‘*((void*)& sg +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
See https://cdash.kyomu.43-1.org/viewBuildError.php?type=1&buildid=16012 after #5974 got merged. The implementation is clearly incorrect for dim!=3. @davydden, maybe add specializations for dim=1 and dim=2 ?

**Comment by davydden** [comment]
> maybe add specializations for dim=1 and dim=2 ?

there is an assert to prevent usage of this class with anything but `dim==3`, so i would rather try to avoid the warning.

**Comment by davydden** [comment]
ah, never mind, i will fix this today and make at least values work with 1d...

**Comment by tjhei** [comment]
> ah, never mind, i will fix this today and make at least values work with 1d...

I don't care if it works or triggers in assert, but it would be great to get rid of the warnings...

**Comment by drwells** [comment]
The trick I learned from @masterleinad is to use `constexpr` to compute indices in this case, e.g., 
```cpp
    constexpr unsigned int z_index = dim == 3 ? 2: 0;
    const double c_utheta2     = sg[0]/r +
                                 ((sin_phi!= 0.) ?
                                  (cos_phi*sg[z_index])/(r2*sin_phi)+sh[1]/(r2*sin_phi2) :
                                  0.);
```

**Comment by davydden** [comment]
fixed by https://github.com/dealii/dealii/pull/6004
