### ISSUE TITLE
In the tutorials, get rid of EPS output

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5982]

**Comment by bangerth** [comment]
Oh, hit ENTER to fast.

Rationale: EPS is sort of an outdated format to begin with. In addition, we don't support it in 1d, and you can't rotate it in 3d. I'd much rather we don't advertise this as good practice, but instead output as VTK or gnuplot.

**Comment by kronbichler** [comment]
I cannot agree more, I think we really should focus on teaching people to use the powerful tools with vtk (ParaView, VisIt). I think all other formats/tools are for advanced users with particular workflows, the basic user is fine with the former.

**Comment by bangerth** [comment]
We still have this:
```
step-12/step-12.cc:      grid_out.write_eps(triangulation, eps_output);
step-14/step-14.cc:      GridOut().write_eps(dof_handler.get_triangulation(), out);
step-1/step-1.cc:  grid_out.write_eps(triangulation, out);
step-1/step-1.cc:  grid_out.write_eps(triangulation, out);
step-30/step-30.cc:    grid_out.write_eps(triangulation, eps_output);
step-49/step-49.cc:  grid_out.write_eps(triangulation, out);
step-5/step-5.cc:  data_out.write_eps(output);
step-6/step-6.cc:    grid_out.write_eps(triangulation, output);
```

**Comment by krishnakumarg1984** [comment]
This does not seem to be completely agreeable to me. For instance, it looks like the `write_svg` function (SVG writer) does not know how to print curved cells and can only display quadrilaterals.
See #9296 .

For a newcomer to the library, this is off-putting when the visualization does not produce what you expect. In the case of a `hyper_ball` or `hyper_shell`, we need to see a curved outer boundary for sure.

**Comment by bangerth** [comment]
Well, this bug is simply about the fact that EPS is an outdated file format we should not be using any more.

As for your statement above: It is not clear what is correct. We use a manifold object that describes the outer boundary as the (curved) perimeter of a circle. But when you do computations, you generally use a mapping and then the actual domain you are solving on has a piecewise polynomial boundary (unless you use special mappings). So, for example, if you use a Q1 mapping, then the domain you are solving on really *is* one with piecewise straight boundaries. As a consequence, it is not clear to me that what you see is actually *different* than what you are doing. 

As for `write_svg` not supporting curved boundaries: If you take a look at what `write_eps` does, then it shouldn't be very difficult to implement the same in `write_svg`.

**Comment by bangerth** [comment]
By the way, current status of this PR:
```
examples/step-6/step-6.cc:    grid_out.write_eps(triangulation, output);
examples/step-14/step-14.cc:      GridOut().write_eps(dof_handler.get_triangulation(), out);
examples/step-30/step-30.cc:    grid_out.write_eps(triangulation, eps_output);
examples/step-12b/step-12b.cc:      grid_out.write_eps(triangulation, eps_output);
```

**Comment by krishnakumarg1984** [comment]
>As for write_svg not supporting curved boundaries: If you take a look at what `write_eps` does, then it shouldn't be very difficult to implement the same in `write_svg`.

Yes, I am happy to attempt to include this functionality in `write_svg` if I can figure out which `write_svg` to refer to? It looks like `write_svg` is a heavily overloaded function with the following instances defined under `source/` 

```
grid/grid_out.cc
4287:    write_eps(const dealii::Triangulation<1> &,
4297:    write_eps(const dealii::Triangulation<1, 2> &,
4307:    write_eps(const dealii::Triangulation<1, 3> &,
4317:    write_eps(const dealii::Triangulation<2, 3> &,
4330:    write_eps(const dealii::Triangulation<dim, spacedim> &tria,
4772:GridOut::write_eps(const Triangulation<dim, spacedim> &tria,
4776:  internal::write_eps(tria, out, mapping, eps_flags_2, eps_flags_3);
4805:        write_eps(tria, out, mapping);

base/data_out_base.inst.in
182:      write_eps(
192:      write_eps(

base/data_out_base.cc
3983:  write_eps(
3998:  write_eps(
4017:  write_eps(
4024:    write_eps(
4040:  write_eps(
7361:DataOutInterface<dim, spacedim>::write_eps(std::ostream &out) const
7363:  DataOutBase::write_eps(get_patches(),
8384:        write_eps(out);

grid/grid_out.inst.in
48:    template void GridOut::write_eps<deal_II_dimension>(
```

Is this really a trivial change to make? Even if I make the change in the `write_eps` source file(s), shouldn't there be a corresponding set of tests added in the test suite to check the functionality of the newly added code? This is starting to sound beyond my reach.

**Comment by bangerth** [comment]
The function you want to adjust is in `grid_out.cc` around line 1548 of the current sources:
```
void
GridOut::write_svg(const Triangulation<2, 2> &tria, std::ostream &out) const
{
```

The part in `write_eps()` that deals with curved boundaries starts in `grid_out.cc` at line 4428 and looks like this:
```
              // next if we are to treat
              // curved boundaries
              // specially, then add lines
              // to the list consisting of
              // pieces of the boundary
              // lines
              if (mapping != nullptr)
                {
                  // to do so, first
                  // generate a sequence of
                  // points on a face and
                  // project them onto the
                  // faces of a unit cell
                  std::vector<Point<dim - 1>> boundary_points(n_points);

                  for (unsigned int i = 0; i < n_points; ++i)
                    boundary_points[i](0) = 1. * (i + 1) / (n_points + 1);

                  Quadrature<dim - 1> quadrature(boundary_points);
                  Quadrature<dim>     q_projector(
                    QProjector<dim>::project_to_all_faces(quadrature));

                  // next loop over all
                  // boundary faces and
                  // generate the info from
                  // them
                  for (const auto &cell : tria.active_cell_iterators())
                    for (unsigned int face_no = 0;
                         face_no < GeometryInfo<dim>::faces_per_cell;
                         ++face_no)
                      {
                        const typename dealii::Triangulation<dim, spacedim>::
                          face_iterator face = cell->face(face_no);

                        if (face->at_boundary())
                          {
                            Point<dim> p0_dim(face->vertex(0));
                            Point<2>   p0(p0_dim(0), p0_dim(1));

                            // loop over
                            // all pieces
                            // of the line
                            // and generate
                            // line-lets
                            const unsigned int offset = face_no * n_points;
                            for (unsigned int i = 0; i < n_points; ++i)
                              {
                                const Point<dim> p1_dim(
                                  mapping->transform_unit_to_real_cell(
                                    cell, q_projector.point(offset + i)));
                                const Point<2> p1(p1_dim(0), p1_dim(1));

                                line_list.emplace_back(p0,
                                                       p1,
                                                       face->user_flag_set(),
                                                       cell->level());
                                p0 = p1;
                              }

                            // generate last piece
                            const Point<dim> p1_dim(face->vertex(1));
                            const Point<2>   p1(p1_dim(0), p1_dim(1));
                            line_list.emplace_back(p0,
                                                   p1,
                                                   face->user_flag_set(),
                                                   cell->level());
                          }
                      }
                }
```

We can walk you through writing a test, but there is also good documentation about this somewhere!

**Comment by bangerth** [comment]
When I take a look at existing code because I want to use it in a separate place, I typically see first if I can clean it up a bit before copying it. In the current case, there are clearly opportunities for that -- e.g., by using a face loop instead of the cell loop, and by making the quadrature objects `const`.

**Comment by drwells** [comment]
I assigned myself to this (from #9296) - I should redo step-6 so that we have clear instructions on how to create the plots I created with #6381.

**Comment by bangerth** [comment]
After #9492, only steps 6, 12b, and 14 are left. I'm not sure we should care much about 12b.

@drwells -- you're still willing to do step-6?

**Comment by drwells** [comment]
Yup :)

**Comment by bangerth** [comment]
I'm doing 14 now.

**Comment by tjhei** [comment]
I would think we leave 12b as is.

**Comment by drwells** [comment]
Why shouldn't we change 12b? The plotted output for that program uses gnuplot and vtk (i.e, we don't even show the EPS pictures)

**Comment by bangerth** [comment]
I tend to think as step-12b as outdated and to be removed once the methods in step-12 are more widely used. (In fact, I would argue that we should just remove step-12 outright.) If it is to be removed, it might not be worth the effort updating it.
