### ISSUE TITLE
Tensor issues

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#600]
A bunch of tests are failing due to Tensor related changes on Intel:
http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=4338

@bangerth ?

**Comment by bangerth** [comment]
I'm on it. It's a non-C++11 problem.

**Comment by tjhei** [comment]
There are still some issues: http://cdash.kyomu.43-1.org/testDetails.php?test=7732557&build=4545

**Comment by bangerth** [comment]
Should be fixed again now.
