### ISSUE TITLE
How to understand output of compute_projection_matrices

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#6019]
This code:
```
FE_Q<2> fe(1);
unsigned int ref_case = RefinementCase<dim>::isotropic_refinement;
FETools::compute_projection_matrices(fe, R, true);
R[ref_case-1][0].print(std::cout);
```
Gives this output:

>  0.56 0.37 0.37 0.25
> -0.19    0 -0.12    0
> -0.19 -0.12    0    0
> 0.062    0    0    0

How to understand this? Clearly, restriction matrix in this case is
> 1 0 0 0
> 0 0 0 0
> 0 0 0 0
> 0 0 0 0

And I was hoping to get something similar to this. 
Is this difference due to the fact that compute_projection_matrices gives projection and not interpolation?

**Comment by bangerth** [comment]
On 03/09/2018 06:08 AM, Alexander Grayver wrote:
> This code:
> 
> |FE_Q<2> fe(1); unsigned int ref_case = 
> RefinementCase<dim>::isotropic_refinement; 
> FETools::compute_projection_matrices(fe, R, true); 
> R[ref_case-1][0].print(std::cout); |
> 
> Gives this output:
> 
>     0.56 0.37 0.37 0.25
>     -0.19 0 -0.12 0
>     -0.19 -0.12 0 0
>     0.062 0 0 0
> 
> How to understand this? Clearly, restriction matrix in this case is
> 
>     1 0 0 0
>     0 0 0 0
>     0 0 0 0
>     0 0 0 0

Why? I would agree if the function computes the *interpolant*. But it computes 
the L2 projection. Projecting a function that is nonzero only on one of the 
children of a cell is certainly going to yield nonzero coefficients for each 
of the shape functions of the coarse parent.

Best
  W.



-- 
------------------------------------------------------------------------
Wolfgang Bangerth          email:                 bangerth@colostate.edu
                            www: http://www.math.colostate.edu/~bangerth/

**Comment by agrayver** [comment]
@bangerth this makes sense, thanks.
