### ISSUE TITLE
a function to preprocess .prm.in file for complicated unit tests

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6074]
Oftentimes when using unit tests with `dealii` parameter files are big but also need additional input thereby requiring organizing them as `.cc` with `SOURCE_DIR`. Typical approach is 
```
std::ostringstream oss;
oss << "set Extra input = " << SOURCE_DIR << "/some.format" << std::endl;
...
prm.parse_input_from_string(oss.str().c_str());
MyClass my_class(prm);
my_class.run();
```

This approach easily gets cumbersome when one needs to provide tens of lines of input.

To make life of users easier, we should 

(i) process `parameters.prm.in` file into `parameters.prm` via Perl and while doing so
(ii) substitute `SOURCE_DIR` keyword string with the actual location of the file
(iii) run `main parameters.prm` as usual.

EDIT: a different explanation https://github.com/dealii/dealii/issues/6074#issuecomment-374832474

**Comment by davydden** [comment]
@tamiko any hints?

**Comment by bangerth** [comment]
We could put a function into `tests/tests.h` that you give a filename as argument and that then
* reads that file into a string
* substitutes `SOURCE_DIR` in that string
* returns that string

You could then write something like
```
  prm.parse_input_from_string (read_and_process_prm_file("filename.prm"));
```

**Comment by davydden** [comment]
> We could put a function into tests/tests.h that you give a filename as argument and that then

ideally, i want the unit test system to do the job automatically, i.e. pick up a pair of
```
name.prm.in
name.output
```
and before running, process `name.prm.in` into `name.prm` and do `my_exec name.prm`.

**Comment by bangerth** [comment]
Ah, I see. I suspect that's not very difficult, but I'll let @tamiko walk you through that process.

**Comment by davydden** [comment]
> I suspect that's not very difficult

yeap, i think it should be doable.

**Comment by tamiko** [comment]
@davydden I am a bit confused - what exactly should the preprocessor *.prm.in -> *.prm do? :-)

**Comment by davydden** [comment]
@tamiko 

> what exactly should the preprocessor *.prm.in -> *.prm do? :-)

ahh, well : 

> substitute SOURCE_DIR keyword string with the actual location of the file

say i have `test_01.prm.in`
```
subsection Extra input
  set File = SOURCE_DIR/extra.mesh
end
```
and directory structure of 
```
test/test_01.prm.in
test/test_01.output
test/extra.mesh
```

In this simple case, one could do the same by moving the whole thing into `.cc` file and use preprocessor macro `SOURCE_DIR`. **BUT** this becomes **unnecessary cumbersome** in case, say, the main executable of the user code/library, runs 10 different template parameters based on some input parameter, i.e.
```
if (something==1) {
  MyClass<1> this(prm); this.run();
} else if (something == 2) {
...
}
etc
```

At the end of the day, it's more natural to run the main executable with the `.prm` file with the only minor difference that this file is obtained by  preprocessing `.prm.in` so that the result has correct path instead of the `SOURCE_DIR` keyword.

**Comment by tamiko** [comment]
> In this simple case, one could do the same by moving the whole thing into .cc file and use preprocessor macro SOURCE_DIR.

Would this actually work at all? :-D `SOURCE_DIR` does not get defined for non-test targets.

**Comment by tamiko** [comment]
On an unrelated related note.

What about simply providing include files only with a relative path?
```
subsection Extra input
  set File = extra.mesh
end
```

The first argument for the test is the parameter file with full path (to the main parameter file) and can be extracted in a neat manner:

```
#include <boost/filesystem.hpp>

int main(int argc, char ** argv)
{
  std::string source_dir =
      argc != 1
          ? boost::filesystem::path(argv[1]).remove_filename().string() + "/"
          : std::string();
```
and then the moment you want to use the extra file you simply prepend `source_dir`:
```
source_dir + parameter_handler.get("Extra Input/File");
```

Anyway, I will think about how to substitute `SOURCE_DIR` in parameter files. (Right now I have to prepare class, so will likely be a PR tomorrow.)

**Comment by davydden** [comment]
@tamiko 

> Would this actually work at all? :-D SOURCE_DIR does not get defined for non-test targets.

I am not saying you need to use this preprocessor variabe, but do the equivalent of it using scripts. Of course it will work!

**Comment by davydden** [comment]
> What about simply providing include files only with a relative path?

that's not the solution. Users actually already do that, say If I run calculations from the same folder where `dealii` parameter file is and where additional `extra.mesh` file is, of course I can simply give the relative path.

The whole thing we discuss is only relevant for unit tests because they are being run in a build folder which is out-of-source, therefore you do not apriori know where to find that extra input.
