### ISSUE TITLE
Merge SparsityPattern and DynamicSparsityPattern

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6085]
#6081 reminded me of this: I find it irritating that we always do the following:

1. build a `DynamicSparsityPattern`
2. copy it into a `SparsityPattern`

We should just have a `SparsityPattern`, where calling `close()` changes the internal representation from the dynamic version to the non-dynamic version. Thoughts?

**Comment by bangerth** [comment]
Would we incur any inefficiencies this way? I can't think of any.

The backward compatible path is if `SparsityPattern` simply acquires a member variable of type `DynamicSparsityPattern` that it forwards to in the `add()` and similar operations. `close()` then just calls `copy_from (member, *this)`.

**Comment by bangerth** [comment]
> Whenever you use the sparsity pattern for initializing a Trilinos 
> matrix? Unless we give all users of the sparsity patterns access to the 
> internal data structures of the uncompressed pattern, which we don't 
> want to, we perform a redundant copy of the sparsity pattern. And on top 
> of that, you'd have to write a new logic in the compressed form of 
> |SparsityPattern| that does the MPI-local -> global index translation 
> for the MPI case.

I think we miscommunicated. I was just proposing that we disallow iterating over the elements of a `SparsityPattern` that has not yet been `close()`d.

**Comment by bangerth** [comment]
Yes, I don't think we want to get rid of `DynamicSparsityPattern` altogether.

**Comment by davydden** [comment]
Let me add a different perspective to this discussion (relevant to https://github.com/dealii/dealii/issues/6917): I would like to keep one native class in deal.II which does not put diagonal elements first for square matrices. For example, DSP of 5x5 matrix is:
```
[0,0,1,2]
[1,0,1,2,3]
[2,0,1,2,3,4]
[3,1,2,3,4]
[4,2,3,4]
```
whereas `SparsityPattern::copy_from()` is:
```
[0,0,1,2]
[1,1,0,2,3]
[2,2,0,1,3,4]
[3,3,1,2,4]
[4,4,2,3]
```
For some scenarios this is not needed and adds extra confusion and complications.
