### ISSUE TITLE
python for bindings

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6139]
how do we search for Python to be used with Python bindings?

I have `export PYTHONHOME=<blabla>` environment variable set, `export CMAKE_PREFIX_PATH=` contains prefix to the installed Python, `export PATH=` has path to python executable but still dealii picks up system python:

```     
    -- Setting up python bindings
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.3")
    -- Found PythonInterp: /usr/bin/python3.6 (found version "1.4")
```

**Comment by Rombur** [comment]
We use [this](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) and [this](https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html). So you need to use `-DPYTHON_LIBRARY` and `-DPYTHON_INCLUDE_DIR` to set the library correctly and `-DPYTHON_EXECUTABLE ` to set the interpretor.

**Comment by davydden** [comment]
thanks @Rombur , that worked! I completely overlooked these settings.

**Comment by Rombur** [comment]
Apparently it is fixed in CMake master https://gitlab.kitware.com/cmake/cmake/commit/1673923c303c6a4184904c4c5849911feddb87e7
