### ISSUE TITLE
cmake 3.11.0 does not find python in boost 1.67.0.b1

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6142]
I have an issue that `cmake 3.11.0` does find boost python
```
     713    -- Setting up python bindings
     714    -- Found PythonLibs: /Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/python-2.7.14-7b3glgd5i3urukvocexcsorctsdwkbey/lib/libpython2.7.a (found version "2.7.14")
     715    -- Found PythonInterp: /Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/python-2.7.14-7b3glgd5i3urukvocexcsorctsdwkbey/bin/python2.7 (found version "2.7.14")
     716    -- Could NOT find Boost
  >> 717    CMake Error at contrib/python-bindings/source/CMakeLists.txt:42 (MESSAGE):
     718      DEAL_II_COMPONENT_PYTHON_BINDINGS has unmet configuration requirements: The
     719      external boost library does not provide Boost.Python
```
 although it's clearly installed
```
$ ls /Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/boost-1.67.0.b1-wi73ssw4tozdvzykmqopq7k5dhl2pfr6/lib/ | grep "python"
libboost_python27-mt.a
libboost_python27-mt.dylib
libboost_python27.a
libboost_python27.dylib
```
and I setup `python` libs and interpreter manually to be the same as the one used to compile boost.

anyone has any ideas? Could be, of course, related to the fact that this is a beta version of `boost`.

**Comment by Rombur** [comment]
It could be this https://www.boost.org/doc/libs/1_67_0_beta1/libs/python/doc/html/rn.html I think that CMake will need to update `FindBoost` because of the new naming convention. If you create symlinks that don't have the 27, does it work?

**Comment by davydden** [comment]
> I think that CMake will need to update FindBoost because of the new naming convention.

ah, right, could indeed be the case.

> If you create symlinks that don't have the 27, does it work?

probably, but I guess i will leave this for Cmake folks to figure out ;-)

**Comment by davydden** [comment]
see https://github.com/dealii/dealii/issues/6139#issuecomment-377959497
