### ISSUE TITLE
Minor changes to LinearIndexIterator

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6157]
It may be best to make an incompatible change to this feature before 9.0 goes out; I'll try to figure this out in the next few days.

**Comment by tamiko** [comment]
Reassigning to "Release 9.1" milestone

**Comment by drwells** [comment]
I forgot about this. I'll figure this out in the next few hours.

**Comment by drwells** [comment]
The change I had previously considered that would be breaking is not necessary. Lets close this.
