### ISSUE TITLE
step-37: possible extension for Kelly

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6162]
We should hint an adaptive refinement extension in Step-37. 
Not that much for the sake of estimation, but to mention that the user should adjust ghost range of vectors to be able to run Kelly. Similar to what we do in [MatrixFreeOperators::Base::adjust_ghost_range_if_necessary()](https://github.com/dealii/dealii/blob/master/include/deal.II/matrix_free/operators.h#L1199-L1225) this would be

```
          IndexSet locally_relevant_set;
          DoFTools::extract_locally_relevant_dofs (dof_handler,
                                                   locally_relevant_set);

          std::shared_ptr<dealii::Utilities::MPI::Partitioner> new_partitioner =
            std::make_shared<dealii::Utilities::MPI::Partitioner>(dof_handler.locally_owned_dofs(),
                                                                  locally_relevant_set,
                                                                  mpi_communicator);

          VectorType copy_vec(solution);
          solution.reinit(new_partitioner);
          solution.copy_locally_owned_data_from(copy_vec);
          constraints.distribute (solution);
          solution.update_ghost_values();
```

**Comment by kronbichler** [comment]
You can also directly initialize the vector with the two index sets, see the function here, which saves you a few lines in creating the partitioner (but it should of course be equivalent):
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/la_parallel_vector.h#L287
