### ISSUE TITLE
Deprecated functions in MG classes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#617]
The remaining functions in MG that were deprecated a while ago already are these:
```
include/deal.II/multigrid/mg_constrained_dofs.h:  get_refinement_edge_indices () const DEAL_II_DEPRECATED;
include/deal.II/multigrid/mg_constrained_dofs.h:  get_refinement_edge_boundary_indices () const DEAL_II_DEPRECATED;
include/deal.II/multigrid/mg_constrained_dofs.h:  bool set_boundary_values () const DEAL_II_DEPRECATED;
```

Other than these, there is only a pair of functions in `SparsityPattern` and then we've removed everything that was already deprecated in 8.2.

**Comment by bangerth** [comment]
@tjhei ?  @guidokanschat ?

**Comment by tjhei** [comment]
Yes, on my list. I think we addressed some of them on the parmg branch already. I have to resurrect the branch.

**Comment by bangerth** [comment]
@tjhei -- after the merge of the parallel functionality, what is the status here? We currently have four deprecated functions:
```
mg_constrained_dofs.h:  get_boundary_indices () const DEAL_II_DEPRECATED;
mg_constrained_dofs.h:  get_refinement_edge_indices () const DEAL_II_DEPRECATED;
mg_constrained_dofs.h:  get_refinement_edge_boundary_indices () const DEAL_II_DEPRECATED;
mg_constrained_dofs.h:  bool set_boundary_values () const DEAL_II_DEPRECATED;
```
Can we get rid of at least the last three before the release?

**Comment by tjhei** [comment]
Yes, I think they can all go. Will do.

**Comment by bangerth** [comment]
Great, thanks!

**Comment by tjhei** [comment]
see #2001
