### ISSUE TITLE
constness of zero_out_ghosts() vs update_ghost_values() in LA::d::Vector

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6197]
is there a reason `zero_out_ghosts()` is not const but `update_ghost_values()` is? Both alter ghost part only, so I would expect constness to be symmetric, i.e. both be `const` or non-`const`.

@kronbichler ping?

**Comment by kronbichler** [comment]
The reason why `update_ghost_values()` is `const` (despite changing *some* of the state) is that we use it inside operator evaluation routines. But I agree that this setting should be symmetric and the change of state from `ghosted/non-ghosted` should definitely be symmetric. Do you want to go ahead and adjust it?

**Comment by davydden** [comment]
> Do you want to go ahead and adjust it?

will do, just wanted to double check.
