### ISSUE TITLE
A function to generate regular polygons and corresponding prisms?

### ISSUE THREAD

**Issue by weixiong-zheng-berkeley** [dealii/dealii#6212]
I need hexagon and extrusion to prism but there's not. Thinking about making a function generating regular polygon and corresponding prisms, any suggestions?

**Comment by bangerth** [comment]
Isn't there a function in `GridGenerator` that does a triangle?

In general, it's not trivial to generate good meshes for general polygons. For a regular hexagon, however, you'd just split it into 3 quadrilaterals. That should be simple enough to code by hand. The prism can then be obtained by extrusion, of course.
