### ISSUE TITLE
Tutorial for matrix-free DG

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#6217]
Given the substantial contributions of matrix-free DG from #5667, we should also add a tutorial program that demonstrates the basic functionality. The following setup is realistic for the 9.0 release:
- Same setup as step-37, i.e., geometric multigrid for Poisson
- No hanging nodes to avoid the complication of flux matrices in DG (according to Kanschat, 2004)
- FE_DGQHermite
- Block-Jacobi smoother based on fast diagonalization method by `TensorProductMatrixSymmetricSum`

After the release, we might also want to add a second tutorial, showing a DG transport example with Runge-Kutta-type time integrator.

**Comment by bangerth** [comment]
@kronbichler -- is it realistic that we will still get this into 9.0? Should we slip to 9.1?

**Comment by kronbichler** [comment]
Let us move the target milestone to 9.1 for now. The program is posted, so it will get decided in the PR #6291 whether this gets into 9.0 or not.
