### ISSUE TITLE
Undefined references when running tests in parallel

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#6229]
I'm getting these errors, on a freshly checked out master, built on a fresh, empty directory:

```
 error: undefined reference to 'dealii::internal::VectorImplementation::minimum_parallel_grain_size'
````

The quick tests also fail on scalapack, same error:
```
scalapack.debug: RUN failed. Output:
./scalapack.debug: symbol lookup error: ./scalapack.debug: undefined symbol: _ZN6dealii8internal20VectorImplementation27minimum_parallel_grain_sizeE
./scalapack.debug: symbol lookup error: ./scalapack.debug: undefined symbol: _ZN6dealii8internal20VectorImplementation27minimum_parallel_grain_sizeE
./scalapack.debug: symbol lookup error: ./scalapack.debug: undefined symbol: _ZN6dealii8internal20VectorImplementation27minimum_parallel_grain_sizeE
./scalapack.debug: symbol lookup error: ./scalapack.debug: undefined symbol: _ZN6dealii8internal20VectorImplementation27minimum_parallel_grain_sizeE
./scalapack.debug: symbol lookup error: ./scalapack.debug: undefined symbol: _ZN6dealii8internal20VectorImplementation27minimum_parallel_grain_sizeE
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
```

**Comment by davydden** [comment]
it's clearly un-related to ScaLAPACK, I guess this is a quick test, right? Probably coming from `#include <deal.II/lac/vector.h>`.

**Comment by luca-heltai** [comment]
[detailed.log](https://github.com/dealii/dealii/files/1903903/detailed.log)

**Comment by luca-heltai** [comment]
I have something like ~400 tests failling for this. Not just the quick test.

**Comment by luca-heltai** [comment]
I'm pretty sure that variable is setup in `base/parallel.cc`

May this be related to using `gold`?

**Comment by bangerth** [comment]
Do you still have this?

This is on linux with GCC 7.3. Does anyone else have this compiler and can test?

**Comment by tamiko** [comment]
@luca-heltai *ping*

**Comment by luca-heltai** [comment]
I'm trying with the current master, and a clean build directory. 

P.S: this was obtained using spack to cpm and gcc7.3, so my guess is that if the issue is still there, I won't be the only one seeing this...

**Comment by luca-heltai** [comment]
Nope. Still there. Same problem.

**Comment by davydden** [comment]
> linux with GCC 7.3

I updated my Spack tester to Ubuntu 18.04 with GCC 7.3.  All tests [pass](https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1415).

**Comment by luca-heltai** [comment]
I keep getting this. If anyone more experienced than me wants to give a look at what's happening, I'll grant them access to this machine.

**Comment by tjhei** [comment]
Could it be that this symbol is stripped by the linker/gcc because it is (or seemed to be) unused in the library and only used by headers?

**Comment by drwells** [comment]
Does this use the unity build?

**Comment by luca-heltai** [comment]
Unless unity is used by default, it should not. I have never used unity.

**Comment by bangerth** [comment]
@luca-heltai -- following up on your listing of the symbols in `parallel.cc.o`: can you do the same for `libdeal_II.g.so` and `libdeal_II.so`? The symbols should of course have propagated there as well. 

Then pick a test that fails. The error happens during linking, so there must be an object file that is generated from the `.cc` file of the test, and apparently this object file references the missing variables. Run `nm` on the object file again to get the (mangled) symbol name that fails here. A comparison of these symbol names should show what is being referenced and what is available where.

**Comment by luca-heltai** [comment]
(I'm closing this issue, anyway, since the bug is not there in e0d2f38 ).

**Comment by bangerth** [comment]
Not necessary before the release, but it would be nice to understand which patch fixed this.
