### ISSUE TITLE
We need an parallel::distributed::ActiveFETransfer class, similar to parallel::distributed::SolutionTransfer

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6237]
This is part of #3511: We will need a class `parallel::distributed::ActiveFEIndicesTransfer` or similar that does for the `active_fe_indices` on `hp::DoFHandler` objects what `p::d::SolutionTransfer` does for solution vectors. We need this because the `hp::DoFHandler` will have to know what the active fe indices were before the triangulation was re-partitioned (or what it was before `save()` was called). These indices need to be correctly set again after `execute_coarsening_and_refinement()` or `load()` so that we can distribute DoFs again.

@marcfehling -- FYI.

**Comment by marcfehling** [comment]
I am currently implementing such a class and thinking about the transfer of indices in case of refinement/coarsening. Which index shall the children/parent adopt?

In case of refinement, I would suggest to simply assign the same index from the parent to the children. But I don't know what to do in case of coarsening. My first idea would be to pick the index which is associated to the FE object with the highest degree amongst the children. But this could cause trouble if FE objects of different types are stored in the `FECollection` object.

Do you have an idea?

**Comment by marcfehling** [comment]
I stumbled over the function `dealii::internal::hp::get_most_dominating_fe_index()` which I think fits our needs. I'll rely on this one for now.

**Comment by bangerth** [comment]
Yes, in case of refinement the new children should get the same indices as the parent cell.

In case of coarsening, one might be tempted to choose the lowest order element among those used on the children. The function you point to basically does this for faces where you want it for files -- the "dominating" element is essentially the one with the lowest polynomial degree. I think you could probably use this function (or something similar) for your purpose as well -- it's not quite right, but what dominates for the cell probably also dominates for the face.

What you are looking for, by the way, is the opposite of what #313 is asking for. But we don't have that either.

**Comment by bangerth** [comment]
It turns out that we apparently do have this -- take a look at #1488.

**Comment by bangerth** [comment]
In other words, you want the opposite of the function introduced in #1488. And once we have that opposite function, we can also call it instead of `dealii::internal::hp::get_most_dominating_fe_index()`.

**Comment by marcfehling** [comment]
Apparently, `get_most_dominating_fe_index()` has been moved in the unnamed namespace in `dof_handler_policy.cc` in `deali-9.0` and remains unreachable at the moment.

I'll come up with a function `FECollection::find_most_volume_dominating_fe()` in a different pull request.

**Comment by marcfehling** [comment]
Wait a second! Isn't the function `FECollection::find_most_volume_dominating_fe()` exactly the one we were looking for? It returns the `fe_index` in the whole `FECollection` which dominates those we pass as arguments.

Looking at the expected results of the corresponding test, I'll find exactly what I was looking for.
(See: https://github.com/dealii/dealii/blob/master/tests/hp/fe_collection_05.cc)
```
{Q1xQ1, Q2xQ2, Q3xQ4, Q4xQ3} with {2,3} => Q2xQ2       1
{Q1xQ1, Q3xQ4, Q4xQ3}        with {1,2} => Q1xQ1       0
{0x0, 0x0, Q1x0, 0xQ1}       with {2,3} => none        invalid_unsigned_int
{0x0, 0x0, Q1x0, 0xQ1}       with {2,3} => 0x0         0 (with dominating FE_Nothing)
{Q1xQ1, Q1xQ1, Q2xQ1, Q1xQ2} with {2,3} => Q1          0
{Q4xQ4, Q5xQ5, Q3xQ4, Q4xQ3} with {2,3} => none        invalid_unsigned_int
{Q1,Q2,Q4,Q3}                with {3}   => Q3          3
{Q3,Q4,Q1,Q1}                with {2,3} => Q1          2 (self-domination)
```
(I'll fix the indentation for this testcase in a separate pull request.)

I'm tempted to use this one as is. What do you think?

**Comment by bangerth** [comment]
This seems sensible. I had forgotten about this function. Is this what you used in the end?

**Comment by marcfehling** [comment]
Yes, I used this one. As you've already reviewed in the pull request :-)
