### ISSUE TITLE
Make a docker image based on spack

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#6247]
I was not able so far to get a docker image running using spack. Compilation has failed me at various stages and on various packages. 

The current docker base images are outdated, as they don't contain several of the newly supported libraries (sundials, assimp, gmsh, etc.).

Spack has turned out to be the most reliable way to install deal.II (thanks to @davydden !!), but I keep failing on making a docker image with it. I think this should be addressed before the release.

**Comment by davydden** [comment]
> I keep failing on making a docker image with it

one of my colleagues created a docker with it for students who need deal.II. But I have no experience in this, unfortunately.

**Comment by luca-heltai** [comment]
Can you ask your colleague to paste here the docker file?

I'll copy it into our `docker-files` repo, and make sure we generate a new image before our release.

**Comment by luca-heltai** [comment]
Yes. That works for simple programs. That exact configuration failed both ptesc and trilinos

**Comment by davydden** [comment]
Ah, I see. You can also try asking on Spack github. Meanwhile I already wrote an email to my colleague...

**Comment by davydden** [comment]
@luca-heltai i was mistaken about my colleague, he has not done anything with Docker, only virtual machines...

**Comment by luca-heltai** [comment]
I think I managed, using gcc5.4. It is an old compiler, but this was the only success I could get. 

You can find the image here:

https://hub.docker.com/r/dealii/dealii/tags/

master-gcc-mpi-fulldepsspack-debugrelease

Please test, and let me know if it works for you guys.

**Comment by tjhei** [comment]
> The current docker base images are outdated, as they don't contain several of the newly supported libraries (sundials, assimp, gmsh, etc.).

I have everything except gmsh working using candi on my machine, see some of the PRs on candi. We should have everything very soon.

**Comment by luca-heltai** [comment]
@tjhei, We already have everything using spack. 

The docker image 

dealii/dealii:master-gcc-mpi-fulldepsspack-debugrelease

has everything turned on, except 64bits.

**Comment by luca-heltai** [comment]
I'll make a PR to docker-files, so that before the release we have both spack and candi based images going.

**Comment by luca-heltai** [comment]
Or better, you do the candi one (which you seem to prefer in your infrastracture), and I'll take care of the spack one (with the help of @davydden , who's been very useful in the last year on this topic...).

**Comment by tjhei** [comment]
> Or better, you do the candi one

sure. I have everything working here already. Just waiting for stuff to be merged into candi.

**Comment by davydden** [comment]
closed by https://github.com/dealii/docker-files/pull/16
