### ISSUE TITLE
Inconsistent interface between DoFHandler and hp::DoFHandler

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#6259]
`hp::DoFHandler` lacks a default constructor and member function `initialize`, is this intended?

**Comment by drwells** [comment]
I think that this is just an oversight: I do not see any reason why we do not implement this.

Also of note: its weird that `DoFHandler::distribute_dofs` copies the `FiniteElement` argument while `hp::DoFHandler::distribute_dofs` only stores a pointer to the `hp::FECollection`. I still think we should just clone the `hp::FECollection` for consistency here (like we now do with Manifolds).

**Comment by adamqc** [comment]
I will try to make a PR to fix this tomorrow.

**Comment by bangerth** [comment]
@adamqc -- great, thanks! I agree that it's just an oversight.

As for the inconsistency in copying the FE, @drwells: Correct. But that's a separate issue.
