### ISSUE TITLE
ConstraintMatrix instantiation for complex number

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#6270]
We need to instantiate `ConstraintMatrix` when the distributed vector uses complex PetscScalar. See this [post](https://groups.google.com/forum/#!topic/dealii/HTp7ddVVV60) on the mailing list.

**Comment by tamiko** [comment]
@Rombur Same issue as #1760 :-) (what about we close this one and use #1760 to track progress?)
I suggest, I resurrect my old branch for immediately after the 9.0 release.

**Comment by Rombur** [comment]
@tamiko I don't think it's the same issue but I have poorly worded my post. Right now we can do `constraint_matrix.distribute_local_to_global` if we distribute into a complex petsc sparse matrix. However, if we want to distribute into a complex petsc sparse matrix and a complex vector, there is a linking error because we didn't instantiate this combination. The current code works if we include `constraint_matrix.templates.h`. My understanding is that #1760 is about complex constraints which is not the case here. The constraints are real.

**Comment by davydden** [comment]
@tamiko 

> I resurrect my old branch for immediately after the 9.0 release

I guess nobody will mind 😸

**Comment by tamiko** [comment]
> I guess nobody will mind 😸 

Let me make that my first project immediately after the release!
