### ISSUE TITLE
Review all documentation related to GridGenerator

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#6274]
GridGenerator functions have changed their default behaviour.

This should be reflected anywhere we discuss about manifold descriptions (e.g., tutorials, modules, etc.).

**Comment by drwells** [comment]
I need something easy to do on a Friday afternoon. I am going through the example programs now.

**Comment by tamiko** [comment]
@drwells @luca-heltai What's the state of this issue?

**Comment by drwells** [comment]
Good question. There are a few more minor updates that we need to make. My main concern is that there will be another issue similar to #6352.

I will run all tutorial programs and report back in about an hour with a clear answer.

**Comment by drwells** [comment]
I am working on step-6 now.

**Comment by drwells** [comment]
@luca-heltai would it be possible for you to review step-54?

**Comment by luca-heltai** [comment]
yes.

**Comment by luca-heltai** [comment]
(mesh surface extraction preserves manifold indicators, but it does not copy manifolds, at the moment, since they are different objects: One is a Manifold<dim,dim>, the other a Manifold<dim,spacedim>)

**Comment by drwells** [comment]
I would still like to get step-38 updated by tonight but I do not have time to push more commits right now. Would someone please handle that?

**Comment by drwells** [comment]
Another function that may need changes is `torus`.
