### ISSUE TITLE
Modify quadrature weights on a per-cell basis?

### ISSUE THREAD

**Issue by ataber** [dealii/dealii#6306]
I'm wondering if it's possible/straightforward to have per-cell quadrature weights? I want to keep the quadrature positions the same but update the quadrature weights. 

I have looked through the documentation, and in particular [the elasticity example](https://dealii.org/developer/doxygen/deal.II/step_8.html), and these lines in particular seem like a fruitful start to understanding how one might do this:
```
    FEValues<dim> fe_values (fe, quadrature_formula,
                             update_values   | update_gradients |
                             update_quadrature_points | update_JxW_values);
...

    typename DoFHandler<dim>::active_cell_iterator cell = dof_handler.begin_active(),
                                                   endc = dof_handler.end();
    for (; cell!=endc; ++cell)
      {
        cell_matrix = 0;
        cell_rhs = 0;
        fe_values.reinit (cell);
....
```

So it seems `fe_values` is being initialized with quadrature rule and `reinit`ed with each cell (as described [here](https://www.dealii.org/8.4.1/doxygen/deal.II/group__UpdateFlags.html)). However, I want to `reinit` with a new quadrature rule as well as new mapping. Is this possible?

**Comment by masterleinad** [comment]
A better place to ask such kind of questions is the [deal.II User Group](https://groups.google.com/forum/#!forum/dealii). Please repeat it there.

**Comment by ataber** [comment]
Okay, thanks!
