### ISSUE TITLE
Deprecate MeanValueFilter

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6332]
It looks like we have one last class that can be easily replaced by about a dozen lines of LinearOperator code. Like the other matrices (PointerMatrixAux, FilteredMatrix, etc) we should deprecate this class and replace it with a LinearOperator.

While not very exciting, I am going to label this as a 9.0 release item so that we really have deprecated everything that can ultimately be replaced by LinearOperator.

ping @tamiko :)

**Comment by tamiko** [comment]
Unfortunately, this requires a bit of thought about where to put the operator and how to name it. I suggest we postpone this to 9.1 (where we will probably also do a renameing of the `LinearOperator` interface that we failed to pull off for 9.0...).

**Comment by tamiko** [comment]
Blocks #6156

**Comment by tamiko** [comment]
@drwells I will do one last drive-by-deprecation so that we can finally remove the `matrix_lib.h` header in the next release :-)

**Comment by bangerth** [comment]
Should we postpone this deprecation to 9.1 as well?

**Comment by tamiko** [comment]
> @tamiko what is the status of this?

Thinking about a replacement right now.
