### ISSUE TITLE
State of Testsuite

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6343]
<h2>Main testing sites:</h2>

| Host | Configuration | Failing | Passing |
|-|-|:-:|:-:|
|tester| GNU-7.3.0-master-unity_build | 0 | 0 |
| | GNU-7.3.0-master-minimal_bundled | 0 | 7023 |
| | GNU-4.9.4-master-autodetection | 0 | 9970 |
| | GNU-6.4.0-master-autodetection | 0 | 10016 |
| | GNU-7.3.0-master-autodetection | 0 | 10016 |
| | Clang-4.0.1-master-autodetection | 0 | 9998 |
| | Clang-6.0.0-master-autodetection | 0 | 10016 |
| | Clang-6.0.0-master-autodetection | 0 | 10016 |
| | GNU-7.3.0-master-petsc_complex | 0 | 9710 |
| | GNU-7.3.0-master-64bit_indices | [<b>4</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1081) | 9978 |
| | GNU-7.3.0-master-optimized | [<b>22</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1083) | 9994 |
| | Clang-6.0.0-master-optimized | [<b>16</b>]( https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1084)| 10000 |
| simserv04 | GNU-5.3.0-master-autodetection | 0 | 8921 |
| | Clang-3.7.0-master-autodetection | 0 | 8921 |
|simserv02 | Intel-18.0.1.20171018-master | [<b>32</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1070) | 8266 |
| davyddenubuntu | GNU-7.2.0-master-^openmpi^openblas | 0 | 10006 |
| | GNU-7.2.0-master-^openmpi^intel-mkl  | [<b>28</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1099) | 9978 |
| CUDA8 | GNU-5.4.0-master | [<b>3</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1095) | 7000 |
| CUDA9 | GNU-5.4.0-master | [<b>2</b>](https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1094) | 7001 |

In reference to #6156

**Comment by drwells** [comment]
It looks like we finally got over 10000 tests.

Some of these links aren't right: the 64 bit GCC link goes to a clang optimized link.

**Comment by tamiko** [comment]
@drwells Fixed. I have to write a script that creates this table automatically at some point...

**Comment by davydden** [comment]
i am not surprised about intel-mkl's ScaLAPACK failures when used with GCC+OpenMPI. In the past I reported a bug.

**Comment by jppelteret** [comment]
@tamiko I think you've transposed the headers: I can't believe that we have zero passing tests :-P

**Comment by tamiko** [comment]
Let's revisit after the prerelease is tagged.
