### ISSUE TITLE
scalapack and MPI version

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#6351]
I am getting
```
/ssd/deal-git/source/lac/scalapack.cc:443:91: error: there are no arguments to ‘MPI_Comm_create_group’ that depend on a template parameter, so a declaration of ‘MPI_Comm_create_group’ must be available [-fpermissive]
```
This is using openmpi 1.6.5. Is this function only available in a newer MPI standard? What do we do?

**Comment by bangerth** [comment]
Yes. Didn't we have this discussion in that same context before? 

`MPI_Comm_create_group` is MPI 3.0. It is collective over that subset of processors that will participate in the new communicator. Before that, you could use `MPI_Comm_create`, which is collective over all processors that participate in the communicator from which the new one is to be created.

**Comment by tamiko** [comment]
I will add a version compatibility check (on openmpi) for scalapack. PR incoming.

**Comment by davydden** [comment]
@tamiko 

> I will add a version compatibility check (on openmpi) for scalapack

it's only one part of the code which use it, if we have some macros `MPI_GT(3.0)` we should just wrap this part of the code.

**Comment by tamiko** [comment]
So why do you create the group in the first place if its optional?

**Comment by tamiko** [comment]
But please go ahead, can you make a pull request please?

**Comment by davydden** [comment]
> why do you create the group in the first place if its optional

I did not say it's optional, I am just saying that we don't have to disable the whole ScaLAPACK but only one function where this is used.

FIY, I did not wrote this function

**Comment by bangerth** [comment]
Could we just revert back to using `MPI_Comm_create`?

**Comment by davydden** [comment]
>  just revert back to using MPI_Comm_create?
 
It’s a different function, I think it was contributed this way from the beginning. 
So there is nothing to revert to. But I guess we can you MPI_Comm_Create instead.

**Comment by bangerth** [comment]
That's what I meant -- go back to a function that has always been part of MPI, even if it hadn't been part of that piece of deal.II code.
