### ISSUE TITLE
Still can't find hdf5 even configure dealii with hdf5

### ISSUE THREAD

**Issue by Hilbertdotx** [dealii/dealii#6354]
My environment is ubuntu 16.04 64 
I download hdf5-1.8.9-linux-x86_64-shared. And the directory is like this:

`bin  COPYING  include  lib  README  RELEASE.txt  share`

Then I configure dealii (8.1.0) with the hdf5 lib using:

`sudo cmake -DCMAKE_INSTALL_PREFIX=/home/chenxi/dealiiwithhdf5 -DHDF5_DIR=/home/chenxi/hdf5-1.8.17/hdf5 ../.`

and get dealiiwithhdf5

But when I compile my homework in Cousera using:

```
cmake -DDEAL_II_DIR=/home/chenxi/dealiiwithhdf5 .
sudo make run

```
I still can't get the right answer . And the error is :

```
In file included from /usr/include/hdf5.h:24:0,
                 from /home/chenxi/Desktop/CA1_template/writeSolutions.h:3,
                 from /home/chenxi/Desktop/CA1_template/main1.cc:11:
/usr/include/H5public.h:34:23: fatal error: H5version.h: No such file or directory
compilation terminated.
CMakeFiles/main1.dir/build.make:62: recipe for target 'CMakeFiles/main1.dir/main1.cc.o' failed
make[2]: *** [CMakeFiles/main1.dir/main1.cc.o] Error 1
CMakeFiles/Makefile2:195: recipe for target 'CMakeFiles/main1.dir/all' failed
make[1]: *** [CMakeFiles/main1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I have already set the path to hdf5, but it seems it just search the dependencies from /usr/include
(I have put the hdf5.h into /usr/include)

**Comment by davydden** [comment]
> I download hdf5-1.8.9-linux-x86_64-shared

contradicts

> -DHDF5_DIR=/home/chenxi/hdf5-1.8.17/hdf5

which `hdf5` do you want to use?

> I have put the hdf5.h into /usr/include

you should never manually do such hacks.

If you have problems installing, maybe you should give some automated methods a try (Spack, Candi), see https://www.dealii.org/download.html#svn
