### ISSUE TITLE
Make step-8 use CompressedSparsityPattern

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#636]
We've moved away from direct initialization of SparsityPattern objects and use the CompressedSparsityPattern intermediate everywhere. step-8 still needs to learn this trick.

**Comment by tjhei** [comment]
My vote is for ```CompressedSimpleSparsityPattern``` (and maybe even retire the other two).

**Comment by bangerth** [comment]
I'm ok with either. I vote to use whatever we use in the other tutorials.

**Comment by kronbichler** [comment]
I agree with Timo. Our current data structures favor CompressedSimpleSparsityPattern over the other two; those basically only increase the amount of code we have to maintain in my opinion. Is it enough to rename CompressedSimpleSparsityPattern into CompressedSparsityPattern, remove the other two straight away and keep them alive by a 'typedef'? The user interface is pretty much identical, so I see nothing that would prevent that.

**Comment by tjhei** [comment]
Agreed. I am happy to do this but not today.

**Comment by bangerth** [comment]
This has apparently happened, maybe with #653.
