### ISSUE TITLE
Don't use the name of classes as template arguments

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#638]
We have instances like this:
```
template <typename SparsityPattern>
void make_sparsity_pattern (..., SparsityPattern &sp);
```
Thing is, `SparsityPattern` here is not the name of the class, but just a free template parameter. But that's hardly visible in the doxygen output, and doxygen also links to the documentation of the class (unhelpful). This then confuses readers who see
```
  CompressedSparsityPattern csp;
  make_sparsity_pattern (..., csp);
```
They say that this call shouldn't succeed.

Easy solution: Don't use the name of a class as a template argument's name.

**Comment by bangerth** [comment]
Case in point:
http://www.dealii.org/8.2.1/doxygen/deal.II/group__constraints.html#gab627b1d4845c9526521dbd1be83469dc

**Comment by tjhei** [comment]
Do we have a style guide for the capitalization, defaults, ```typename``` vs ```class``` etc. for template arguments?

I can think of ```Number```, ```DH``` (for DoFHandler types), ```Container``` and ```CONTAINER``` (for Triangulation or DoFHandler), ```CSP_t``` (that must have been me :-) )

My vote would be to always use ```typename``` and use ALL_CAPS for the name to completely avoid confusion.

**Comment by Rombur** [comment]
We don't have a rule for the template arguments, I have checked before. I have seen ```Number```, ``number```, ```Number2``, ```OtherNumber``` ...

I also prefer ```typename``` and ALL_CAPS.

**Comment by bangerth** [comment]
Let's not use ALLCAPS :-) How about I use `SP` for sparsity patterns?

**Comment by tjhei** [comment]
SP for static ones and CSP for compressed ones?

**Comment by tjhei** [comment]
And isn't ```SP``` all caps? :-)

**Comment by bangerth** [comment]
Damn, we really need C++ concepts to even keep static and compressed sparsity patterns apart :-( 

I'm ok with your suggestion. What to do in cases where the type of sparsity pattern doesn't actually make any difference?

**Comment by tjhei** [comment]
I think ```SP``` is fine then.
