### ISSUE TITLE
Documentation for NonMatching::coupling not compiling

### ISSUE THREAD

**Issue by GivAlz** [dealii/dealii#6394]
Hi everyone!
   I was sure that the following function didn't have documentation, as it does not appear in doxygen:
`
NonMatching::create_coupling_sparsity_pattern
NonMatching::create_coupling_mass_matrix
`
but if you look at the file include/non_matching/coupling.h you shall find the documentation is there!
I don't know why it does not compile: my first idea was to take the code from immersed_surface_quadrature.h and put it inside coupling.h (as they're still "related" concepts/functions) but it is not solving the problem, just avoiding it.

Anyone has suggestions on how to solve this?

**Comment by drwells** [comment]
This is somewhere between a doxygen bug and a doxygen feature. Adding documentation to the namespace itself (in exactly one of the headers in `non_matching/`) makes it show up for me. Would you be willing to do this?

**Comment by GivAlz** [comment]
Yes, I'll do it now: I tried looking around but don't know doxygen weel enough to understand the problem. Thank you!

**Comment by drwells** [comment]
Closed by #6399.
