### ISSUE TITLE
Bug: Use intermediate storage for BlockLinearOperator<..>.vmult()

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6437]
If source and destination vectors are the same, the following code in `block_linear_operator.h` garbles up the result:
```
359         for (unsigned int i = 0; i < m; ++i)                                     
360           {                                                                      
361             op.block(i, 0).vmult(v.block(i), u.block(0));                        
362             for (unsigned int j = 1; j < n; ++j)                                 
363               op.block(i, j).vmult_add(v.block(i), u.block(j));                  
364           } 
```
We really have to use some intermediate storage here.
<s>Should be not much of a deal - I plan to fix this issue between rc1 and rc2.</s>

**Comment by bangerth** [comment]
Can you just put an assert in there that forbids this for 9.0? This would give us time up to the next release to fix it. I think it's a rare enough case and a case with significant difficulty to get both right and efficient that we might want to bump it to 9.1
