### ISSUE TITLE
Fix fallout from 6446

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6458]
As discussed elsewhere, this patch breaks (sorry) approximately 50 tests that
rely on the geometry generated by `hyper_shell(tria, Point<3>, r, R, 96)` since
the 96 cell grid is now computed in a different way. The following tests
currently fail on my workstation (there may be a few that are unrelated, such as
the slepc and PETSc failures; in particular there is a bug with 32 bit hypre):

- [x] mpi/no_flux_constraints.mpirun=9.debug (Failed)
- [x] mpi/no_flux_constraints.mpirun=9.release (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=1.debug (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=1.release (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=9.debug (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=9.release (Failed)
- [x] mpi/normal_flux_constraints.mpirun=9.debug (Failed)
- [x] mpi/normal_flux_constraints.mpirun=9.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=1.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=1.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=10.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=10.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=24.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=24.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=4.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=4.release (Failed)

**Comment by drwells** [comment]
[detailed.log](https://github.com/dealii/dealii/files/1975970/detailed.log)

**Comment by drwells** [comment]
ping @tamiko . I forgot when I ran this that I was using the 32 bit Hypre which is not cooperative. I'll rerun these tests with the 64 bit version and report back.

**Comment by tamiko** [comment]
@drwells I am also currently running Bob on mainline (accidentally started with wrong commit or configuration twice...) Let me start helping to fix those tests. What about I start at the end of the list and you start at the beginning? Regarding hypre - if a test doesn't fail for me I will happily skip it.

**Comment by drwells** [comment]
This sounds reasonable.

**Comment by tamiko** [comment]
Most of the tests that I have checked so far pass for me.

**Comment by drwells** [comment]
I think the list might just be irrelevant problems in PETSc that we cannot deal with. I have not yet found anything either.

**Comment by drwells** [comment]
It is also possible that (despite what `detailed.log` states) I messed up the revision and tested before the right change.

**Comment by tamiko** [comment]
I found three tests so far that have updated results due to your change in `hyper_shell`.

**Comment by tamiko** [comment]
@drwells `mpi/normal_flux_constraints` and `mpi/step-40` suddenly stop distributing the mesh over multiple processors for me. Can you reproduce that?

**Comment by tamiko** [comment]
@drwells 16 failing tests on bob: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1445

**Comment by bangerth** [comment]
On 05/04/2018 04:32 PM, Matthias Maier wrote:
> @drwells <https://github.com/drwells> |mpi/normal_flux_constraints| and 
> |mpi/step-40| suddenly stop distributing the mesh over multiple 
> processors for me. Can you reproduce that?

Oh, did we previously generate 96 cells on the coarse level, and now 
it's only 12 cells on the coarse level that are all refined once? If 
that's the case, then we need to flatten the triangulation again.

**Comment by drwells** [comment]
I meant to keep the number of coarse cells at 96. I'll double check.

**Comment by drwells** [comment]
The program

```cpp
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria.h>

#include <iostream>

int main()
{
  using namespace dealii;

  Triangulation<3> tria;
  GridGenerator::hyper_shell(tria, Point<3>(), 1.0, 2.0, 96);

  std::cout << tria.n_cells() << '\n';
  std::cout << tria.n_levels() << '\n';
}
```

prints

```
96
1
```

so there really are 96 coarse level cells.

**Comment by tamiko** [comment]
@bangerth @drwells I think we hit an entirely unrelated issue. Somehow depending on available cores the maximal number of mpi processes gets reduced.
