### ISSUE TITLE
Fix result images for step-18

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#6473]
[They're very large](https://www.dealii.org/developer/doxygen/deal.II/step_18.html#Results) and extend beyond the edge of the page width. I'm guessing they need to be encapsulated by something like
```html
 * <td align="center" width="33%">
 * @image html path_to_figure
 * </td>
```

Blocks #6156

**Comment by drwells** [comment]
I can handle this.

I think that, incredibly, I was so far zoomed in that I completely missed the third column.

**Comment by jppelteret** [comment]
Thank you very much @drwells, I appreciate it! I'd be keen to learn how one fixes this problem.

**Comment by drwells** [comment]
I'll probably end up copying and pasting what I did recently for step-10; its not a hard fix :)

@jppelteret I think I need your help for something more difficult than aligning images. The current output is now completely symmetric: the shell never bends over to one side. Is this what we expect to happen? If so we need to update all pictures.

**Comment by jppelteret** [comment]
Yes, it looks like the results images still reflect the old output... I fixed a problem with the definition of the rotation tensor quite some time ago, which changed the results and we should have updated the images then. Do you now see the same output as https://github.com/dealii/dealii/pull/3777#issuecomment-272159025?

**Comment by drwells** [comment]
No; here is what I see at the end:

![step18](https://user-images.githubusercontent.com/3917035/39664041-233e19fa-504b-11e8-8125-cf19e5899534.png)

not nearly as exciting :(

**Comment by jppelteret** [comment]
Hmm... Give me a few moments to take a look into it.

> I'll probably end up copying and pasting what I did recently for step-10

Ah, I see that you've [set up the table completely differently](https://github.com/dealii/dealii/blob/master/examples/step-10/doc/results.dox#L28-L63). Cool, thanks for the tip :-)

**Comment by drwells** [comment]
I told a friend of mine (who is a professional web developer) that I was considering using `<table>` and he was not happy with me :) The CSS solution is preferable for a lot of reasons (its faster for the browser, has better accessibility, and does a better job separating content from layout procedure).

I would also like to add alt-text everywhere in case anyone wants to use a screen reader.

**Comment by jppelteret** [comment]
@drwells Sorry for the wait - I had to do a fresh build with PETSc enabled. 

I see the same behaviour as you. All of the output has changed (RHS norms, number of CG iterations) and the deformation is for all intents and purposes symmetric too. I suppose this must be a knock-on effect from the cylindrical manifold being applied to interior faces?

**Comment by drwells** [comment]
> I suppose this must be a knock-on effect from the cylindrical manifold being applied to interior faces?

This is probably it. In fact, thats a bad default setting because we will end up with a non-conforming discretization if there are any hanging nodes on the interior. We should fix this in time for the release.

**Comment by jppelteret** [comment]
> ...who is a professional web developer...

I'm happy to follow the (free) advice of someone who does this for a living :-)

**Comment by drwells** [comment]
While we do get a non-conforming discretization its a pretty minor variational crime. I reran the example with flat manifold ids on the interior and got essentially the same pictures.

**Comment by jppelteret** [comment]
Great, so maybe thats one less thing to worry about then. Do you plan on updating the images and results text (if necessary), or do you need me to do so?

**Comment by drwells** [comment]
I think I should clarify: I get essentially the same thing regardless of if I extend the manifold onto the interior of the domain: I cannot get the cool lopsided pictures.

**Comment by jppelteret** [comment]
> While we do get a non-conforming discretization its a pretty minor variational crime. I reran the example with flat manifold ids on the interior and got essentially the same pictures.

We could also add your comment to the documentation to make our readers aware of the "crime"...

>  I cannot get the cool lopsided pictures.

Understood. After our recent updates, I cannot either. So I conclude that the results currently presented in the documentation are not consistent with the output of the code. So we need to do something about this.

**Comment by bangerth** [comment]
I think that the lopsidedness was always a numerical artifact. It's a bit less cool to see it gone, but it's not wrong.

**Comment by jppelteret** [comment]
> I think that the lopsidedness was always a numerical artifact. 

Agreed, I think that this is the accepted numerical behaviour for thin-walled structures subject to large compressive deformation.

By the way, as best I can tell if you look down the axis of the deformed tube it is slightly elliptical on the upper surface (compare the deformation at the 45/225 degrees vs that of 135/225 degrees). Its just hardly noticeable, and if one increases the deformation the tube now inverts / snaps through before it buckles.

 
![screen shot 2018-05-05 at 18 34 30](https://user-images.githubusercontent.com/10460610/39665372-44f2799a-5093-11e8-8f4d-bd858c581206.png)

**Comment by jppelteret** [comment]
@drwells Did we both just make a mistake in not reading the results discussion correctly? 

There are two sets of results there: The first given by the default settings hard-coded in the tutorial, and the second given with these changes:
```diff
diff --git a/examples/step-18/step-18.cc b/examples/step-18/step-18.cc
index ca443dff8e..944079ebf7 100644
--- a/examples/step-18/step-18.cc
+++ b/examples/step-18/step-18.cc
@@ -740,7 +740,7 @@ namespace Step18
     dof_handler (triangulation),
     quadrature_formula (2),
     present_time (0.0),
-    present_timestep (1.0),
+    present_timestep (0.5),
     end_time (10.0),
     timestep_no (0),
     mpi_communicator (MPI_COMM_WORLD),
@@ -820,7 +820,7 @@ namespace Step18
           }

     // Once all this is done, we can refine the mesh once globally:
-    triangulation.refine_global (1);
+    triangulation.refine_global (2);

     // As the final step, we need to set up a clean state of the data that we
     // store in the quadrature points on all cells that are treated on the
```
The first do not exhibit the buckling behaviour, but the second are supposed to.
I've just run the tutorial again with the above diff applied, and got this output 
![screen shot 2018-05-06 at 00 04 11](https://user-images.githubusercontent.com/10460610/39667950-a38ed9fc-50c1-11e8-84ce-ab52b609f88a.png)
that more or less matches those given below the text
> Finally, here is the same output as we have shown before for the much smaller sequential case:

I think that the **HUGE** images (sorry, technically my fault!) might have made us get lost between the two simulation configurations. Can you confirm that you get a similar output with the diff applied? If so, then we just need to format the existing images correctly (i.e. remove the ability to see them from space).

**Comment by drwells** [comment]
> @drwells Did we both just make a mistake in not reading the results discussion correctly?

Don't overestimate me. I'll check.

**Comment by drwells** [comment]
I do not get that output with the patch you provided. Did you change something else?

**Comment by jppelteret** [comment]
@drwells No, I did not change something else (I compiled from 96699ec83c8de39a287e47751283e688a3640dab with #6476 applied). Admittedly though I could only run it with 8 MPI processes and am using a different OS, compiler, Metis version etc. I just ran the more refined version in serial and the instability behaviour is still there, although the solution is different. So maybe these factors collectively account for differences we're seeing. On Tuesday I can check the behaviour on a second machine, but if someone else is willing to check what the nature of the solution they're seeing for this problem (for 1, 8 and 16 processes, if possible) then that would be most helpful.

The way I see it, the optimal outcome is that your output is the "anomaly" and we just need to reformat the table and perhaps make a small note of the potential factors influencing the unstable solution. If my output is anomalous then we need to fix the table formatting, redo the images and rewrite the results discussion. Guess which outcome I'm hoping for...

**Comment by drwells** [comment]
> the optimal outcome is that your output is the anomaly

I'd rather not advertise such an ill-posed scheme, if possible: we should all get the same pictures regardless of metis version. I believe the optimal version is for us all to get the same interesting nonsymmetric picture.

I'm trying again at higher resolution.

**Comment by drwells** [comment]
I feel like everywhere I look, now that the release is imminent, I find serious bugs.

Incidentally, if you run this with hyre's preconditioner in release mode, does it use up all the system memory for you?

**Comment by jppelteret** [comment]
> Incidentally, if you run this with hyre's preconditioner in release mode, does it use up all the system memory for you?

No, it does not :-/ But `PreconditionBoomerAMG` does use a lot more memory, and takes a whole lot longer to solve than with `PreconditionBlockJacobi`. However, as I don't typically use PETSc I can't say whether this is expected or not, and I'm open to the idea that I've not used all of the correct settings (although a skim through step-40 + the class documentation suggest that I have). 

If its of any help, I'm using `petsc@3.7.5 + hypre@2.11.1` and here's how I set up the preconditioner:
```c++
//    PETScWrappers::PreconditionBlockJacobi preconditioner(system_matrix);
    PETScWrappers::PreconditionBoomerAMG preconditioner(
      system_matrix,
      PETScWrappers::PreconditionBoomerAMG::AdditionalData(
         true /*symmetric_system*/, 
         0.5 /*recommended setting for 3d*/));
```

**Comment by jppelteret** [comment]
@drwells I get a similar output for the "refined" case on my Linux machine with `openmpi@2.0.2 + gcc@6.3.0` as the compiler, with `petsc@3.7.5`, and `metis@5.1.0`. I've tested this with both 8 MPI processes as well as 16 (oversubscribed). In each case, the solution looks the same (symmetric buckling with a pinched top surface), but the orientation of the symmetry plane is dependent on the number of MPI processes (so I suppose how the numerical error accumulates). 

I'm really not surprised or bothered by this. I think that the only way that we could control this behaviour (i.e. make the response completely deterministic) would be to add an imperfection in the geometry or to apply a transverse load somewhere on the radial surface.

**Comment by tamiko** [comment]
> I'm really not surprised or bothered by this. I think that the only way that we could control this behaviour (i.e. make the response completely deterministic) would be to add an imperfection in the geometry or to apply a transverse load somewhere on the radial surface.

This might be a good point of improving the example step. Discussing how creating an asymmetry in the system leads to a stable result, whereas relying on numerical round-off errors to finally break symmetry might show random results highly depending on architecture, refinement and/or current weather.

**Comment by drwells** [comment]
Yes; lets not modify the code to explicitly get an asymmetrical result now. Lets just publish the current output.

**Comment by drwells** [comment]
These pictures look very nice now!
