### ISSUE TITLE
dealii-9.0: State of Intel support

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6488]
We currently have a couple of segmentation faults reported for the intel compiler [1].
That needs to be addressed for the release.

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1489

Blocks #6156

**Comment by drwells** [comment]
Most of these don't look like our fault, e.g.,

```
/usr/include/c++/5/cstddef(44): catastrophic error: cannot open source file "bits/c++config.h"
  #include <bits/c++config.h>
                             ^
```

and a few of the newly flagged ones complain about disk space.

**Comment by tamiko** [comment]
OK. The new iteration (thanks @masterleinad !) looks much more reasonable: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=1495

**Comment by masterleinad** [comment]
WIth C+17 support, these are the failing tests (after rerunning with `--rerun-failed` a few times) are:
```
683 - fe/system_04.debug (Failed)
684 - fe/system_04.release (Failed)
705 - fe/system_03.debug (Failed)
706 - fe/system_03.release (Failed)
6462 - lac/gmres_eigenvalues.release (Failed)
7201 - gmsh/create_tria_02.debug (Failed)
7202 - gmsh/create_tria_02.release (Failed)
```
