### ISSUE TITLE
Don't use classes derived from Function in the early steps

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#650]
The early steps introduce classes derived from `Function<dim>` even though that is not actually necessary -- we just call their `value` function, but we never pass such objects around. There is, consequently, no gain in introducing the whole situation.

Worse, in some of these codes, we implement both the `value` and `value_list` function, even though we only ever call one of the two. We then go to great length to explain why we want both and that they need to match -- none of which actually matters, all of which actually confuses students greatly.

I'm going to eventually remove this and just have a regular function of the kind
```
  double coefficient (const Point<dim> &p)
```
or similar. The `Function` object will then only be derived where we actually need it.

**Comment by tjhei** [comment]
We need the whole function explanation in step-4 for ```BoundaryValues``` (well, and there is ```ZeroFunction``` in step -3) and step-7 for ```integrate_difference``` anyways. The only advantage would be that coefficients and right hand sides are a bit simpler.

**Comment by bangerth** [comment]
That's what I mean.

**Comment by bangerth** [comment]
Fixed by #2844.
