### ISSUE TITLE
[C++17] Use <filesystem> in gmsh/utilities.cc

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#6510]
In `gmsh/create_triangulation` we are currently (as of #6508) using the `POSIX` `mkdtemp`.
After the release, we should use `boost::filesystem` resp. `std::filesystem` (C++17) for creating files and directories in a suitable manner.
This requires to enforce that the `Boost` library used is built with the `filesystem` module. In particualr, we need to include the module in our bundled package.

**Comment by kronbichler** [comment]
In the new boost-1.70, we include the `filesystem` module. Thus, I adjust the title that we should use boost's facilities for the relevant file in `source/gmsh/utilities.cc`.

**Comment by bangerth** [comment]
The problem is that we only require boost 1.59 when using the external boost. Does that version have the `fileystem` lib?

**Comment by masterleinad** [comment]
> The problem is that we only require boost 1.59 when using the external boost. Does that version have the `fileystem` lib?

Yes, `unique_path` is at least in 1.44. Unfortunately, `unique_path` is ont part of `std::filesystem` and I have no good idea for a path forward that doesn't rely on platform-dependent functions.

**Comment by masterleinad** [comment]
No priority here. Moving.

**Comment by marcfehling** [comment]
We'll move to the C++17 standard with release 10.0. Then this will be trivial to solve. I'll move the milestone forward.

**Comment by bangerth** [comment]
Let's do this once we have C++17, like in #12080.

**Comment by bangerth** [comment]
If anyone had an interest, this can now be done!

**Comment by bangerth** [comment]
The issue in question here is to replace the call to `mkdtemp`, a function that creates a temporary directory with a unique name. Unfortunately, there is no C++17 facility to do that -- only functions that create directories with names *we* select, but that defeats the atomic nature of `mkdtemp`.

So I think we need to close this issue.
