### ISSUE TITLE
Need a way to run MueLu tests only if TrilinosVersion >= 10.12

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#657]
The MueLu tests currently run whenever you have Trilinos installed (starting with #214 ), but they should only run if TRILINOS_VERSION >= 10.12.

@tamiko : Any good way of doing this?

**Comment by tamiko** [comment]
@bangerth : I'm currently thinking about a somewhat not totally messy solution. Unfortunately, it is not that simple. The big problem is that in the testsuite we do not have all configuration variables available, but only the subset exported in <code>deal.IIConfig.cmake</code>.

Personally, I dislike the idea of inflating <code>deal.IIConfig.cmake</code> and the testsuite logic... It is already horrible spaghetti code to begin with...

The most "elegant" solution I see so far is to add a Trilinos-version guard around the tests like we do in the library itself. This would be at least in line with the philosophy how @Rombur made muelu a strict requirement for Trilinos 11.14 [1].

[1] Of courese there is always the option to make the muelu optional, test for it in <code>FindTRILINOS.cmake</code> and export the result in <code>config.h.in</code>. But I do not see a compelling reason for that.

**Comment by tjhei** [comment]
Also fine in my opinion: the test is run for >=11.14 even if muelu is optional. It is just for the tester after all.
