### ISSUE TITLE
tests/tests.h is not in the 9.0.0 tarball but used by quick tests

### ISSUE THREAD

**Issue by piyueh** [dealii/dealii#6586]
Hi, thank you all for this amazing package!

In the 9.0.0 release tarball, there is no `tests/tests.h`. But several quick tests include that header in the source files:
```
./arpack.cc:19:#include "../tests.h"
./scalapack.cc:16:#include "../tests.h"
./umfpack.cc:21:#include "../tests.h"
```

**Comment by tamiko** [comment]
Wow. We tested for almost everything. Except this.

**Comment by davydden** [comment]
should add this to the release tasks.

**Comment by tamiko** [comment]
@davydden Jup. I added `11a/`, check `.gitattributes`.

**Comment by tamiko** [comment]
@piyueh I have signed and uploaded a new release tarball. Please test!

**Comment by davydden** [comment]
@tamiko 

> @piyueh I have signed and uploaded a new release tarball. Please test!

did you remove the previous tarbal? I think you should have kept the name, although the tarbal is different (one file difference). Inventing names which are not aligned with version number `9.0.0` vs `9.0.0-r1.tar.gz` is a PITA for package managers.

**Comment by drwells** [comment]
I am really not a fan of this naming convention. Could we please just call it 9.0.1?

**Comment by davydden** [comment]
> I am really not a fan of this naming convention. Could we please just call it 9.0.1?

indeed, either that or silently update the tarbal and keep 9.0.0.

**Comment by drwells** [comment]
I would also be okay with pretending the release on Friday did not happen and just call this 9.0.0

**Comment by drwells** [comment]
I just watched the video on how to not release software on Friday, so I feel somewhat bad about that statement, but this change does not effect anything in the actual library so I can live with it.

**Comment by tamiko** [comment]
I have updated the release tarball to 9.0.0-r1 (for "revision 1"). I did this because
 - the change does not affect the ABI/API, hence no soname change necessary
 - the change does not affect any installed files
 - recreating all tarballs and images and updating all package managers is prohibitively expensive.

**Comment by tamiko** [comment]
If you insist, just rename the file back to "9.0.0".

**Comment by davydden** [comment]
> If you insist, just rename the file back to "9.0.0".

yes, i certainly do.

**Comment by tamiko** [comment]
@davydden I am sorry, you won't. It's already done.

**Comment by davydden** [comment]
Let's hope we won't need to touch 9.0.0 release tarbal again.

**Comment by drwells** [comment]
Either way: thank you for the quick fix on a Sunday afternoon @tamiko. I am updating the AUR script now.

I could not figure out why the quick tests didn't work before: I assumed that it was something I did not understand in arch's build system. I'll report back if this does not fix it.

**Comment by tamiko** [comment]
@drwells Roger. I have to regenerate gentoo manifests right now as well...

**Comment by piyueh** [comment]
@tamiko Thank you for the fix! Quick tests work now in the 9.0.0 tarball.

**Comment by drwells** [comment]
`scalapack.cc` also requires `../lapack/create_matrix.h` so this quick test now always fails.

**Comment by davydden** [comment]
> scalapack.cc also requires ../lapack/create_matrix.h so this quick test now always fails.

i wrote about it but have not thought it's in a different header... you are right.

**Comment by davydden** [comment]
> scalapack.cc also requires ../lapack/create_matrix.h so this quick test now always fails.

PR incoming...
