### ISSUE TITLE
Quick tests don't work with MAKEFLAGS=-jn

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6589]
Tangentially related to #6586: I don't understand why, but I get a bunch of `read jobs pipe: Bad file descriptor.  Stop.` errors when `MAKEFLAGS` is defined to something convenient. `make -j8 test` also fails.

**Comment by tamiko** [comment]
Yes, I know. I already hit this when packaging 8.5.1 for Debian/Ubuntu. It would be helpful if you could tell me what make version and cmake version you have.

**Comment by drwells** [comment]
This was fixed (as much as is possible) by #7143.
