### ISSUE TITLE
#6375 breaks compilation on Cray

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#6600]
Since #6375 I get: 

```
[ 46%] Building CXX object source/base/CMakeFiles/obj_base_release.dir/mpi.cc.o
In file included from /users/ag/lib/dealii-master/include/deal.II/base/mpi.h:19:0,
                 from /users/ag/lib/dealii-master/source/base/mpi.cc:17:
/users/agrayver/lib/dealii-master/build/include/deal.II/base/config.h:330:30: error: operator '*' has no left operand
  ((DEAL_II_MPI_VERSION_MAJOR * 100 + \
                              ^
/users/ag/lib/dealii-master/source/base/mpi.cc:100:5: note: in expansion of macro 'DEAL_II_MPI_VERSION_GTE'
 #if DEAL_II_MPI_VERSION_GTE(3, 0)
     ^
```

After digging a bit, it turns that FindMPI.cmake does not export MPI_VERSION_MAJOR and MPI_VERSION_MINOR, so I have this in the config.h:

```
#ifdef DEAL_II_WITH_MPI
#  define DEAL_II_MPI_VERSION_MAJOR 
#  define DEAL_II_MPI_VERSION_MINOR 

#  define DEAL_II_MPI_VERSION_GTE(major,minor) \
 ((DEAL_II_MPI_VERSION_MAJOR * 100 + \
    DEAL_II_MPI_VERSION_MINOR) \
    >=  \
    (major)*100 + (minor))
#endif
```

This happens on a Cray cluster with their environment: 
https://pubs.cray.com/content/00477539-DA/DA00477538

**Comment by masterleinad** [comment]
Are you actually using a recent developer version? We had some problems with this macro for newer `CMake` versions which was fixed in #6424 and #6421. Which `CMake` version are you using? `CMake` is not listed on the page in your link.
Which `MPI_*` variables are actually set? In particular, what is `MPI_VERSION`?

**Comment by agrayver** [comment]
I downloaded master today. This is with CMake 3.8.1. I see no MPI_VERSION variable used anywhere in the library. Do I need to output it from within cmake?

**Comment by masterleinad** [comment]
No, you should find that piece of information in `detailed.log`.
In our `FindMPI.cmake` we currently assume that `MPI_VERSION` or `MPI_CXX_VERSION` is set. If only the latter one is set, we also set `MPI_VERSION` to this string.

**Comment by agrayver** [comment]
There is not much in the deteailed.log:

```
#      ( DEAL_II_WITH_LAPACK = OFF )
#      ( DEAL_II_WITH_METIS = OFF )
#        DEAL_II_WITH_MPI set up with external dependencies
#        DEAL_II_WITH_MUPARSER set up with bundled packages
#            MUPARSER_BUNDLED_INCLUDE_DIRS = /users/ag/lib/dealii-master/bundled/muparser_v2_2_4//include
#      ( DEAL_II_WITH_NANOFLANN = OFF )
#      ( DEAL_II_WITH_NETCDF = OFF )
#      ( DEAL_II_WITH_OPENCASCADE = OFF )
```
I checked on Ubuntu, there it is printed. Well, Cray systems are not standard in this sense. 

Note that if I set MPI_VERSION_MAJOR and MPI_VERSION_MINOR manually in config.h, everywthing compiles and works.

**Comment by masterleinad** [comment]
I suspect that `MPI_VERSION` is defined while `MPI_VERSION_MAJOR` and ` MPI_VERSION_MINOR` are not. Can you confirm this by putting
```
MESSAGE(STATUS "MPI_VERSION: ${MPI_VERSION}")
MESSAGE(STATUS "MPI_VERSION_MAJOR: ${MPI_VERSION_MAJOR}")
MESSAGE(STATUS "MPI_VERSION_MINOR: ${MPI_VERSION_MINOR}")
```
at the end of our `FIND_MPI` function in `cmake/modules/FindMPI.cmake`?

**Comment by masterleinad** [comment]
Does this patch help?
```
diff --git a/cmake/modules/FindMPI.cmake b/cmake/modules/FindMPI.cmake
index cbe43f7..16ec722 100644
--- a/cmake/modules/FindMPI.cmake
+++ b/cmake/modules/FindMPI.cmake
@@ -88,6 +88,21 @@ IF(NOT DEFINED MPI_VERSION AND DEFINED MPI_CXX_VERSION)
   SET(MPI_VERSION_MINOR ${MPI_CXX_VERSION_MINOR})
 ENDIF()
 
+# It might be the case MPI_VERSION is defined but MPI_VERSION_MAJOR
+# or MPI_VERSION_MINOR are not.
+
+IF(DEFINED MPI_VERSION AND NOT DEFINED MPI_VERSION_MAJOR)
+  STRING(REGEX REPLACE "^([0-9]+).*" "\\1"
+    MPI_VERSION_MAJOR "${MPI_VERSION}"
+    )
+ENDIF()
+
+IF(DEFINED MPI_VERSION AND NOT DEFINED MPI_VERSION_MINOR)
+  STRING(REGEX REPLACE "^[0-9]+\.([0-9]+).*" "\\1"
+    MPI_VERSION_MINOR "${MPI_VERSION}"
+    )
+ENDIF()
+
 #
 # Really old versions of CMake do not export any version information. In
 # this case, query the mpi.h header for the necessary information:
```

**Comment by agrayver** [comment]
No, this patch does not help. I am pretty confident the MPI_VERSION is not set.

**Comment by masterleinad** [comment]
If `MPI_VERSION` is not set, we end up in
```
IF(NOT MPI_MPI_H MATCHES "-NOTFOUND" AND NOT DEFINED MPI_VERSION)
  FILE(STRINGS "${MPI_MPI_H}" MPI_VERSION_MAJOR_STRING
    REGEX "#define.*MPI_VERSION")
  STRING(REGEX REPLACE "^.*MPI_VERSION[ ]+([0-9]+).*" "\\1"
    MPI_VERSION_MAJOR "${MPI_VERSION_MAJOR_STRING}"
    )
  FILE(STRINGS ${MPI_MPI_H} MPI_VERSION_MINOR_STRING
    REGEX "#define.*MPI_SUBVERSION")
  STRING(REGEX REPLACE "^.*MPI_SUBVERSION[ ]+([0-9]+).*" "\\1"
    MPI_VERSION_MINOR "${MPI_VERSION_MINOR_STRING}"
    )
SET(MPI_VERSION "${MPI_VERSION_MAJOR}.${MPI_VERSION_MINOR}")
```
which either sets `MPI_VERSION` to something sensible or to ".". The latter case is handled after that.

Can you just force `CMake` to print the relevant variables after each step in our `FindMPI.cmake`?

**Comment by bangerth** [comment]
In the worst case, we can always set version strings to 2.0. I don't know that there are any installations around that don't satisfy this very minimum. (2.2 may also be safe.)

**Comment by agrayver** [comment]
Here is output from FindMPI:

```
-- MPI_MPI_H not found! Call:
--     FIND_FILE(MPI_MPI_H NAMES mpi.h HINTS)
--   MPI_LIBRARIES:
--   MPI_INCLUDE_DIRS:
--   MPI_USER_INCLUDE_DIRS:
--   MPI_CXX_FLAGS:
--   MPI_LINKER_FLAGS:
-- Found MPI
-- MPI_VERSION:
-- MPI_VERSION_MAJOR:
-- MPI_VERSION_MINOR:
```

**Comment by agrayver** [comment]
Apparently, Cray specifics caused troubles since a long time: 

https://groups.google.com/forum/#!msg/dealii/HvcJGsa3Ib8/qHylCq3BX-gJ;context-place=topic/dealii/qrRwdm5yojE
