### ISSUE TITLE
Fix documentation for step-50

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#6608]
There are a number of lines of code in `step-50` that are commented out, and therefore leak into the surrounding doxygen documentation (e.g. [here](https://github.com/dealii/dealii/blob/master/examples/step-50/step-50.cc#L743)). I'm not sure if its best to remove these altogether or if we'd prefer to "protect" them somehow. If we can come to some resolution on this point then I'll submit a PR with the appropriate changes.

**Comment by bangerth** [comment]
Is that one of the unfinished programs?

**Comment by jppelteret** [comment]
Yip, I missed that :-)

So... nothing to do here then...

**Comment by jppelteret** [comment]
I got confused because the unfinished tutorials leak into the related pages. So `step-50` is actually listed at https://dealii.org/9.0.0/doxygen/deal.II/pages.html . I'm not sure if this is intended or not.

**Comment by bangerth** [comment]
I guess that means that we generated the documentation for the website from master, not the branch. Ah well.
