### ISSUE TITLE
9.0 documentation does not include the code gallery

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6609]
@jppelteret has already found himself confused by the fact that the 9.0 documentation contains step-50, an unfinished application: #6608. It turns out that the documentation also doesn't contain the code gallery: http://dealii.org/9.0.0/doxygen/deal.II/CodeGallery.html
That's arguably a bigger loss. 

@tamiko -- how did you generate the documentation? Can we redo this without too much trouble?

**Comment by tamiko** [comment]
@bangerth: I did not generate the documentation found at https://dealii.org/9.0.0/, @guidokanschat *ping*

**Comment by bangerth** [comment]
I made sure that the code gallery step is now also documented in item 11 in the release task list.

**Comment by bangerth** [comment]
Any news?

**Comment by masterleinad** [comment]
This is fixed now. It seems that the old tarball from May 11 included `step-47` and `step-50` somehow.
