### ISSUE TITLE
MGConstrainedDoFs::initialize() gives segmentation fault if MG dofs are not distributed

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6610]
clearly, not the way to use this class, but we should add an Assert that `distribute_mg_dofs()` was called.

p.s. happens as `mg_constrained_dofs.h:194 -- DoFTools::extract_locally_relevant_level_dofs(dof,l,relevant_dofs);`.

**Comment by bangerth** [comment]
Got a testcase?

**Comment by davydden** [comment]
> Got a testcase?

nope, but should be trivial to do eventually... I quickly posted this issue as I came across it while working on something else...
