### ISSUE TITLE
Adding serialization for complex numbers

### ISSUE THREAD

**Issue by GivAlz** [dealii/dealii#6612]
In https://github.com/dealii/dealii/pull/6240 I added a serialization for std::complex numbers at the top of the file, as it was the only way to make it compile. Clearly this is not optimal: what's the best place to put it?

As soon as I know I shall make a separate small PR to add this functionality (I actually thought it was included into the boost library but that's not the case).

Best,
Giovanni

**Comment by bangerth** [comment]
Is there really no BOOST header file that does this? We may not be `#include`ing it by default, but I'd be surprised if it doesn't exist.

**Comment by bangerth** [comment]
I think the correct header file is simply `<boost/serialization/complex.hpp>`.

**Comment by GivAlz** [comment]
Does the trick... I don't know why I didn't find it (I was reasonably sure boost had it too); sorry for the "not real" issue, and thank you @bangerth !
