### ISSUE TITLE
Documentation: Imbedding external resources

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6625]
For every single release I fight an uphill battle to remove all external image sources in our html files for the debian/ubuntu packages (otherwise the package might get rejected due to https://lintian.debian.org/tags/privacy-breach-generic.html). External resources also create problems for the offline documentation (they are simply not getting rendered).

Currently, we include
 - links to wikimedia resources: `https://upload.wikimedia.org/wikipedia/[...]`
 - links to zenodo: `https://zenodo.org/badge/DOI/10.5281/[...]`
 - links to w3.org: `http://[...].w3.org/[...]`

All of these resources could probably be replaced by local copies of the files (if the licensing terms allow that).

**Comment by bangerth** [comment]
This is annoying for sure. I can't access the debian page from here (didn't expect that), but it is a shame that we have to duplicate these things. Are you suggesting that we *permanently* ingest these images?

**Comment by tjhei** [comment]
> For every single release I fight an uphill battle to remove all external image sources in our html files

this is for the html documentation? are you bundling it? Why?

> (if the licensing terms allow that).

I don't mind if we replace the URLs with a local URL to a file that doesn't exist. Easier than figuring out if we are allowed to ship the images...

**Comment by drwells** [comment]
This is a comprehensive change and I don't think we will have this done today. I will change the milestone to 9.2

**Comment by bangerth** [comment]
@tamiko -- what's your idea how one could address this in a reasonable way? It isn't even quite clear how we would distinguish an external resource from an internal programmatically -- we link to all sorts of stuff via `http://`, but most of these are really just links to other pages (for example, we now have many links to wikipedia).

**Comment by tamiko** [comment]
I will try to work on this during our current release :-)

**Comment by peterrum** [comment]
Postponing since we have not made any progress here.

**Comment by tamiko** [comment]
Let's close.
