### ISSUE TITLE
Have inline on a separate line

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#6660]
In https://github.com/dealii/dealii/pull/6656 some people requested to have `inline` on a separate line.
`clang-format` seems not to be capable of doing so, but likely accepts when this done some other way.
Should we have a separate script taking care of this?
I prefer to do this after introducing `clang-format`.

**Comment by bangerth** [comment]
I've just posted #6661 for this -- easy enough to do this with this sort of perl expression:
```
perl -pi -e 's/^(\s*)inline\s+(.+)/\1inline\n\1\2/g;' include/deal.II/*/*h
```

**Comment by davydden** [comment]
It looks like @tamiko has good arguments against, closing for now.
