### ISSUE TITLE
Fix std::complex<> support

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6672]
After #6664 is merged, the following methods could be fixed to support complex numbers:
 - [ ] `make_periodicity_constraints` and `PeriodicFacePairs`
 - [ ] `distribute_cell_to_dof_vector`
 - [ ] convert multigrid to number-type aware `AffineConstraints`
 - [ ] port matrix-free `ConstraintValues` to support a templated number type. This potentially breaks the API, @kronbichler *ping*

**Comment by drwells** [comment]
I am not sure if we should extend this to other present issues with `std::complex` support. We also have (from experience with #6695):
- [ ] tests for LAPACK complex routines (nonsymmetric eigenvalues, SVD, LU factorization)
- [ ] fix for Hermitian LAPACK matrices

**Comment by drwells** [comment]
At this point anything that doesn't work with complex numbers should be a bug.
