### ISSUE TITLE
Differences in indentation compared to master

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6676]
With current master, and no changes to any files, if I run `./contrib/utilities/indent`, I get the following diffs:
```
diff --git a/source/matrix_free/matrix_free.inst.in b/source/matrix_free/matrix_free.inst.in
index 755bbe4..fddb7f1 100644
--- a/source/matrix_free/matrix_free.inst.in
+++ b/source/matrix_free/matrix_free.inst.in
@@ -15,58 +15,58 @@
 
 
 for (deal_II_dimension : DIMENSIONS)
-{
-    template class MatrixFree<deal_II_dimension,double>;
-    template class MatrixFree<deal_II_dimension,float>;
+  {
+    template class MatrixFree<deal_II_dimension, double>;
+    template class MatrixFree<deal_II_dimension, float>;
 
-    template void MatrixFree<deal_II_dimension,double>::
-    print_memory_consumption<std::ostream> (std::ostream &) const;
-    template void MatrixFree<deal_II_dimension,double>::
-    print_memory_consumption<ConditionalOStream> (ConditionalOStream &) const;
+    template void
+    MatrixFree<deal_II_dimension,
+               double>::print_memory_consumption<std::ostream>(std::ostream &)
+      const;
+    template void MatrixFree<deal_II_dimension, double>::
+      print_memory_consumption<ConditionalOStream>(ConditionalOStream &) const;
 
-    template void MatrixFree<deal_II_dimension,float>::
-    print_memory_consumption<std::ostream> (std::ostream &) const;
-    template void MatrixFree<deal_II_dimension,float>::
-    print_memory_consumption<ConditionalOStream> (ConditionalOStream &) const;
+    template void
+    MatrixFree<deal_II_dimension,
+               float>::print_memory_consumption<std::ostream>(std::ostream &)
+      const;
+    template void MatrixFree<deal_II_dimension, float>::
+      print_memory_consumption<ConditionalOStream>(ConditionalOStream &) const;
 
 #ifndef DEAL_II_MSVC
-    template
-    void
-    internal::MatrixFreeFunctions::ShapeInfo<double>::
-    reinit<deal_II_dimension>(const Quadrature<1> &,
-                              const FiniteElement<deal_II_dimension,deal_II_dimension> &,
-                              const unsigned int);
+    template void
+    internal::MatrixFreeFunctions::ShapeInfo<double>::reinit<deal_II_dimension>(
+      const Quadrature<1> &,
+      const FiniteElement<deal_II_dimension, deal_II_dimension> &,
+      const unsigned int);
```
Do others have that too?

**Comment by bangerth** [comment]
For completeness: This is the only file that has diffs, and I cut the diffs short because they just go on.

**Comment by davydden** [comment]
yes, I see that as well. But also I have `include/deal.II/fe/fe_nedelec_sz.h` which is _indented_ in a strange way, everything after

>  * This class represents an implementation of the
> * H<sup>curl</sup>-conforming N

is gone...

**Comment by bangerth** [comment]
It's because of the use of Unicode characters. That should be relatively simple to fix.

**Comment by kronbichler** [comment]
Interestingly, I get also a diff in a single `.inst.in` file, but in another file:
```
$ git diff
diff --git a/source/fe/fe_enriched.inst.in b/source/fe/fe_enriched.inst.in
index 853f36a..af9a4cf 100644
--- a/source/fe/fe_enriched.inst.in
+++ b/source/fe/fe_enriched.inst.in
@@ -14,10 +14,9 @@
 // ---------------------------------------------------------------------
 
 
-for (deal_II_dimension : DIMENSIONS; deal_II_space_dimension :  SPACE_DIMENSIONS)
-{
+for (deal_II_dimension : DIMENSIONS; deal_II_space_dimension : SPACE_DIMENSIONS)
+  {
 #if deal_II_dimension <= deal_II_space_dimension
     template class FE_Enriched<deal_II_dimension, deal_II_space_dimension>;
 #endif
-}
-
+  }
```
I have tried to look into this a bit more, but I cannot see what goes wrong here...

**Comment by bangerth** [comment]
Are both of you also working with the statically linked download of the indentation script?

This is an issue that we need to sort out... :-(

**Comment by tamiko** [comment]
Oh - I don't observe any of that. Might I ask for the exact system you're running commands on and the output of `locale`?

**Comment by davydden** [comment]
> Are both of you also working with the statically linked download of the indentation script?

No, Spack-built llvm 6.0.0

Also from https://github.com/dealii/dealii/pull/6277#issuecomment-392252416

> This modified the file "source/physics/elasticity/kinematics.inst.in" as well which i just ignored because its outside my edits.

Could that somehow be related to parallelization we do in the bash script?

**Comment by bangerth** [comment]
On 05/27/2018 03:51 PM, Matthias Maier wrote:
> Oh - I don't observe any of that. Might I ask for the exact system you're 
> running commands on and the output of |locale|?

Ubuntu 17.04. The locale says

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by tamiko** [comment]
Ha. I think I found the problem. Somehow the `indent` script itself only runs on exactly one file. In my case it is `source/algorithms/operator.inst.in` with now changes. Another file is chosen at random.

**Comment by tamiko** [comment]
The encoding issue is unrelated to that bug and we have to look at that as well - my guess is that something goes wrong on Mac.

Fixing the first issue now.

**Comment by tamiko** [comment]
Jup. Got the issue. Patch incoming. :-)

**Comment by davydden** [comment]
@tamiko

> The encoding issue is unrelated to that bug and we have to look at that as well 

There is already PR with a fix for this https://github.com/dealii/dealii/pull/6678

**Comment by tamiko** [comment]
@kronbichler Mind to share your locale as well? Curious what ordering you have set.

**Comment by kronbichler** [comment]
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

$ cat /etc/system-release
CentOS Linux release 7.5.1804 (Core) 
```
