### ISSUE TITLE
Extend line length to 100

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6683]
People have traditionally used 80 characters for line length because that's what was displayed in a terminal window before graphical user interfaces came along. And terminal windows used this line length because 80 characters is what a punch card would hold. I know this because I grew up playing with them :-)  (My mom used to program mainframes.)

But that time is over. Most of us probably use some kind of graphical user interface, and while I appreciate that 80 characters is probably a good *guideline*, it does not yield the prettiest results as far as indentation is concerned.

What about we set the new line length to 100? Would documentation become unreadable if we had paragraphs this long? What do people think?

**Comment by davydden** [comment]
> What about we set the new line length to 100?

👍 

> Would documentation become unreadable if we had paragraphs this long?

documentation is HTML (generated by doxygen), it does not care how long is the line width. This should not affect anything.

**Comment by bangerth** [comment]
> documentation is HTML (generated by doxygen), it does not care how long is the 
> line width. This should not affect anything.

Yes, but there are still human readers of documentation :-)

**Comment by masterleinad** [comment]
> Would documentation become unreadable if we had paragraphs this long?

In fact, we already have URLs that are that break the 80 character rule (and `clang-format` can't do anything).

**Comment by masterleinad** [comment]
I always prefer to discuss these kind of issues with the changes at hand. See #6687.

**Comment by tamiko** [comment]
The big problem I see with an extended line length of 100 characters is that clang-format aggressively tries to use the space. This leads to very awkward code snippets.

I suggest we first have a look at #6696. I have the feeling that this PR eliminates most of the awkward corner cases so that we don't need 100 characters per line any more.
(And seriously, places where we have an indentation level of 10 (TEN) need to be refactored anyway...)

**Comment by tamiko** [comment]
Another thought on this. I had a nice an long chat with a fellow developer from another open source project. He happens to be blind and pointed out that braille readers typically have a width of 40 or 80 characters.

**Comment by drwells** [comment]
I'd like to get all of the massive clang-format patches behind us sooner rather than later. Are people still interested in seeing this change? If so, lets vote and be done with it.

**Comment by tamiko** [comment]
What about we just close and don't introduce yet another 200k line changes?
In my opinion (as outlined above) a line width of 80 characters is sufficient (and what we currently have).

**Comment by drwells** [comment]
Since this issue hasn't received much attention over the last two months I suspect no one feels too strongly about going forward with this, so lets close this issue.

**Comment by bangerth** [comment]
I'm still interested in this, but I was going to wait until the Christmas break in hopes that that leaves fewer pending patches.

I still think that the indentation we get from clang-format is actually quite poor and that increasing line lengths to 100 would yield substantially better results.
