### ISSUE TITLE
Host .tar.gz files ourselves

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6684]
It turns out that github does not store our .tar.gz files on its own servers, but uses Amazon Cloud Services for this. Some of these machines appear to be blocked from China -- sometimes downloads work, sometimes they don't. 

Do we have the resources to host the release tarballs ourselves?

**Comment by tamiko** [comment]
@bangerth Let's say, if the traffic we generate with that is significantly above 25TB per month, we will have to find another solution.

**Comment by tamiko** [comment]
@bangerth Here you go: https://tenjin.kyomu.43-1.org/dealii/ (still populating, should be done in 30 minutes.)

**Comment by tamiko** [comment]
@bangerth I have added the mirror to https://www.dealii.org/download.html. Or do you want to also switch the primary download URLs?

**Comment by tamiko** [comment]
@dealii/dealii All, I have made available
 - A full mirror of our sources (and precompiled mac images): https://tenjin.kyomu.43-1.org/dealii/
 - A full mirror of the main repository https://github.com/dealii/dealii at `git://git.kyomu.43-1.org/dealii.git` (update interval every 5 minutes)
 - Similarly, backup mirrors of `code-gallery.git`, `candi.git`, `release-papers.git`, `parameter_gui.git` (update interval every hour)
 - A full git mirror of the historical svn archive available at `git://git.kyomu.43-1.org/dealii-svn.git`.

**Comment by tamiko** [comment]
@bangerth Have a look at http://dealii.kyomu.43-1.org/ (proper ssh certificate will be installed tomorrow) and tell me what is missing :-)

**Comment by tamiko** [comment]
And if someone feels nostalgic, there is now http://dealii.kyomu.43-1.org/cgi-bin/gitweb.cgi?p=dealii-svn.git;a=summary

**Comment by bangerth** [comment]
@tamiko -- thanks a lot!

If you don't mind, instead of (or in addition to) linking to the whole mirror page, I'd just add "(mirror)" behind every link we have. The typical user, if the download does not work, will just walk away and use a different package, rather than trying to read the whole page and look for a mirror site. If there is a "(mirror)" immediately after the link, they will at least see it right away.

**Comment by tamiko** [comment]
@bangerth I have updated the download page and added a link on the github release pages as well.
