### ISSUE TITLE
fix link to non-existing paper

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#672]
The grid renumbering documentation contains
" * linear time as well. Both algorithms are described in a paper by Agelek,
 * Anderson, Bangerth and Barth, see the publications page of the deal.II
 * library.
"
but that paper never made it into existence, or did it, @bangerth ?

**Comment by bangerth** [comment]
>   * Anderson, Bangerth and Barth, see the publications page of the deal.II
>   * library. " but that paper never made it into existence, or did it,
>     @bangerth <https://github.com/bangerth> ?

It has been 90% ready since 2005 but we never finished it. Maybe I should get 
it into a good enough shape to upload it to arXiv at least...

**Comment by tjhei** [comment]
I got told you would get at least one citation if you do. :-)

**Comment by bangerth** [comment]
I might make that my motivation :-)

**Comment by bangerth** [comment]
It's about to be submitted.
