### ISSUE TITLE
Fix "typex const" uses in exception classes, use "const typex" instead.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6724]
When defining the exception classes, #6718 introduces the uncommon use of `typex const &arg_name` for constructor arguments, and `typex const mem_name;` for member variables. This is necessary because `typex` is a macro argument, and so it may or may not be the same to say `typex const` vs. `const typex`.

This kind of confusion can be avoided if we do something like
```
  using arg_typex = typex;
```
at the top of the class, because we can then use `const arg_typex` again as we usually do.

**Comment by drwells** [comment]
This change complicates the macros quite a bit - lets keep the clang-tidy solution unless someone is willing to fix this.

**Comment by bangerth** [comment]
The easier way to do this might have been to just use `const decltype(typex) &`. No need for a `using` declaration.

Regardless, not worth anyone's effort :-)
