### ISSUE TITLE
condense() after vs. inside make_sparsity_pattern

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#675]
There are two common ways to remove constraints from a sparsity pattern:
1) condense after:

```
      DynamicSparsityPattern csp(dof_handler.n_dofs(), dof_handler.n_dofs());
      DoFTools::make_sparsity_pattern (dof_handler, csp);
      hanging_node_constraints.condense (csp);
      sparsity_pattern.copy_from(csp);
```

2) condense inside `make_sparsity_pattern`:

```
      DynamicSparsityPattern csp(dof_handler.n_dofs(), dof_handler.n_dofs());
      DoFTools::make_sparsity_pattern (dof_handler, csp, hanging_node_constraints);
      sparsity_pattern.copy_from(csp);
```

Method 2 is shorter, works very similar in parallel with PETSc/Trilinos, and is likely faster. We end up teaching method 1 in most tutorials.

I was wondering if we should replace it with method 2 right from the start. Thoughts?

**Comment by tjhei** [comment]
Oh, and I guess using ```distribute_local_to_global``` vs. ```condense(matrix)``` is the same issue.

**Comment by bangerth** [comment]
I think option 1 has the advantage that newbies actually see what is happening. I believe that there is pedagogical value in this. We can always (and do) introduce more concise methods in later tutorials.

**Comment by drwells** [comment]
Lets not condense there - its better to be explicit in all the steps (especially when we have to communicate parts of the sparsity pattern).
