### ISSUE TITLE
broken doxygen from clang-format comment wrapping

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#6752]
There are several instances where clang-format messes up the doxygen formatting. For example:
http://www.dealii.org/developer/doxygen/deal.II/classScaLAPACKMatrix.html#a84e89c6cfa606aaf5d39e981de7ae378

How do we fix this? What is the best way to disable the comment wrapping?

**Comment by bangerth** [comment]
It looks like clang-format doesn't see that this was markdown-formatted. We can work around this by using `@code ... @endcode` blocks, which clang-format seems to leave alone. The question is how we can find all of the places where this happened.

**Comment by tamiko** [comment]
@tjhei We currently have
```
CommentPragmas: '@(ref|p|copydoc) '
```
in `.clang_format`. We should add `|` as well so that tables remain untouched.

**Comment by tjhei** [comment]
urgh. The list of problematic entries is much larger where doxygen will get confused:
https://github.com/dealii/dealii/blob/1cf12e90abedcf5272eb4c4d916a059c36c7e0c7/contrib/utilities/wrapcomments.py#L118

**Comment by tamiko** [comment]
@tjhei Let me fix that up. PR incoming in about 30 minutes.

**Comment by tjhei** [comment]
I am worried that we now have a large number of broken things in doxygen. Not sure how to fix that.

**Comment by tamiko** [comment]
@tjhei By checking out a pre clang-format commit, running clang-format with the fixed pragmas on it and make a PR with the differences. Working on it.

**Comment by tjhei** [comment]
> @code ... @endcode

text inside code/endcode also seems to be mangled by clang-format. Not that it helps here, because then doxygen won't make a table from this markdown.
