### ISSUE TITLE
Removed header file breaks compatibility for using codes

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#6763]
I got the following error when compiling ASPECT with the recent deal.II master:
```
In file included from /home/rene/software/aspect/source/boundary_composition/spherical_constant.cc:24:
/home/rene/software/aspect/include/aspect/geometry_model/spherical_shell.h:28:10: fatal error: 
      'deal.II/grid/tria_boundary_lib.h' file not found
#include <deal.II/grid/tria_boundary_lib.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/aspect.dir/build.make:278: recipe for target 'CMakeFiles/aspect.dir/source/boundary_composition/spherical_constant.cc.o' failed
```

The corresponding header in deal.II was removed in #6582. Of course I can remove the include from ASPECT and fix our development version, but our recent release will not work with deal.II master any more. Would it make sense to keep this header with a warning that it will be removed in a future release?

**Comment by tjhei** [comment]
> Would it make sense to keep this header with a warning that it will be removed in a future release?

Yes. This effects one of my other codes too.

**Comment by davydden** [comment]
> Would it make sense to keep this header with a warning that it will be removed in a future release?

but to be fair, were not boundary classes deprecated in the previous release? That's why @drwells had this final clean-up PR. If so, I don't see how this is different from deprecating a class, removing it from the library and then some codes are broken unless they take action. So I would not add the header back.

**Comment by gassmoeller** [comment]
I agree that the fault is on our side (we removed the usage of the classes, but forgot to remove the includes), I was just worried that this might affect others as well, because there was no warning that we still included deprecated headers. If we decide there is no need to act that is ok with me, I just wanted to make everyone aware of the issue.

**Comment by davydden** [comment]
> there was no warning that we still included deprecated headers

I guess that

```
#warning This file is deprecated.
```

would have helped 😞

**Comment by tjhei** [comment]
> would have helped

Yes. What about we do exactly that now and remove it after the next release?

**Comment by davydden** [comment]
> What about we do exactly that now and remove it after the next release?

Ok.
