### ISSUE TITLE
FunctionMap is not deprecated correctly

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6765]
I am not sure what's wrong, but on Ubuntu with gcc 7.3.0 https://github.com/dealii/dealii/pull/6746 did not deprecate `FunctionMap`, but actually removed it.

I have compiler errors: 
```
expected nested-name-specifier before `FunctionMap`
```
for code `typename FunctionMap<dim>::type()` in error estimators.

As well as 
```
error: `FunctionMap` in namespace `dealii` does not name a template type
```
for 
```
typename dealii::FunctionMap<dim>::type()
```

**Comment by masterleinad** [comment]
Can you give me a minimal example?

**Comment by davydden** [comment]
> Can you give me a minimal example?

unfortunately not, that's a huge user code.

**Comment by masterleinad** [comment]
Do you include the appropriate header?

**Comment by davydden** [comment]
> Do you include the appropriate header?

that must be it, you indeed removed `#include <deal.II/dofs/function_map.h>` from other headers so what compiled previously does not unless I add the deprecated header.
