### ISSUE TITLE
Update example steps

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#6774]
Things to look for:
 - use `for (... auto cell : triangulation.active_cell_iterators())` and similar. (Make sure that the concepts are introduced. Basic usage is explained in step-1).
 - fix bilinear form indenting and other special cases, use trailing `//` for this.
 - `ConstraintMatrix` -> `AffineConstraints`

Checklist:
---
 - :warning:  Add your name when you start working on a step, and cross reference pull request :warning:
 - :information_source: Mark example steps that don't require any changes as done.
 - [x] step-1 (@tamiko, #6775, #7639)
 - [x] step-2
 - [x] step-3 (@tamiko, #6778)
 - [x] step-4 (@tamiko, #6779)
 - [x] step-5 (@tamiko, #6780)
 - [x] step-6 (@tamiko, #8102)
 - [x] step-7 (@tamiko, #6781)
 - [x] step-8 (@davydden, https://github.com/dealii/dealii/pull/6802)
 - [x] step-9 (@drwells, #6900)
 - [x] step-10 (@drwells, #6859)
 - [x] step-11 (@drwells, #6860)
 - [x] step-12 (@masterleinad, #6838)
 - [x] step-13 (@masterleinad, #6862)
 - [x] step-14 (@masterleinad, #6869)
 - [x] step-15 (@masterleinad, #6974)
 - [x] step-16 (@masterleinad, https://github.com/dealii/dealii/pull/6849)
 - [x] step-17 (@kronbichler, #8101)
 - [x] step-18 (@davydden, https://github.com/dealii/dealii/pull/6803)
 - [x] step-19
 - [x] step-20 (@masterleinad, https://github.com/dealii/dealii/pull/6806, #7419, #7702)
 - [x] step-21 (@drwells, #8088)
 - [x] step-22 (@masterleinad, https://github.com/dealii/dealii/pull/6817)
 - [x] step-23 (@drwells, #8005)
 - [x] step-24 (@drwells, #8006)
 - [x] step-25 (@drwells, #8007)
 - [x] step-26 (@masterleinad, #8099)
 - [x] step-27 (@masterleinad, https://github.com/dealii/dealii/pull/6870, #7371)
 - [x] step-28 (@drwells, #8024)
 - [x] step-29 (@drwells #8036)
 - [x] step-30 (@drwells, #8044)
 - [x] step-31 (@drwells, #8059)
 - [x] step-32 (@drwells, #8069)
 - [x] step-33 (modernise AD, #7341, @masterleinad #8106)
 - [x] step-34 (@drwells, #8100)
 - [x] step-35 (@masterleinad, https://github.com/dealii/dealii/pull/6833)
 - [x] step-36 (@davydden, https://github.com/dealii/dealii/pull/6804)
 - [x] step-37 (@drwells, #7129)
 - [x] step-38 (@drwells, #8100)
 - [x] step-39 (@masterleinad, #6858)
 - [x] step-40 (@drwells, #6839)
 - [x] step-41 (@drwells, #8100)
 - [x] step-42 (@masterleinad, #8097)
 - [x] step-43 (@masterleinad, #8096) 
 - [x] step-44 (@jppelteret, #8095)
 - [x] step-45 (@masterleinad, #6784)
 - [x] step-46 (@masterleinad, #8094)
 - [x] step-48 (@kronbichler, #8038)
 - [x] step-49 (@drwells, #5860, #6831)
 - [ ] step-50
 - [x] step-51 (@kronbichler, #8039)
 - [x] step-52 (@bangerth, #7193)
 - [x] step-53 (@masterleinad, #8063)
 - [x] step-54
 - [x] step-55 (@masterleinad, #8105)
 - [x] step-56 (@masterleinad, #8043)
 - [x] step-57 (@drwells, #7391)
 - [x] step-59 (@masterleinad, #8025)
 - [x] step-60
 - [x] step-61 (@bangerth; many PRs all linked to from #6455)
 - [x] step-62 (@masterleinad, #8019)
 - [x] step-63 (@masterleinad, #8016)

**Comment by bangerth** [comment]
Out of curiosity, why do you want to remove the final `try-catch` blocks? I think they are good practice that we should teach, regardless of whether the runtime happens to do this for us.

**Comment by tamiko** [comment]
Well,
 - We are actually not using these try-catch blocks for any control flow at all but merely reimplement a verbose terminate handler.
 - The verbose terminate handler prints more useful information [1] than what we do [2].
 - Most of our asserts, namely all with `Assert` do not throw at all.
 - We have only one example step, namely step-32 that uses a `try`-`catch` block for control flow.

And removing the try catch blocks saves 30 lines and 2 levels of indentation for `main()` in every example step and (in case of non-trivial main functions like found in step-7) makes the code easier to read.

I can see the point that we had to teach users to always catch exceptions 15 years ago, but I don't see how this is of much benefit nowadays. I would very much prefer to introduce the `try { ... } catch ( ...) { ... }` idiom earlier (maybe for `ExcNoConvergence`) and do something useful with it.


[1] standard terminate handler:
```
terminate called after throwing an instance of 'dealii::StandardExceptions::ExcMessage'
  what():  
--------------------------------------------------------
An error occurred in line <0> of file <> in function
    
The violated condition was: 
    
Additional information: 
    Throw me!
--------------------------------------------------------
```
[2] custom catch:
```
----------------------------------------------------
Exception on processing: 

--------------------------------------------------------
An error occurred in line <0> of file <> in function
    
The violated condition was: 
    
Additional information: 
    Throw me!
--------------------------------------------------------

Aborting!
----------------------------------------------------
```

**Comment by bangerth** [comment]
Hm. Can we rely on this being the case for all compilers? How about clang, icc on the linux side? How about MSVC on the windows side? These error messages are just so useful that it would be a shame if we lost them.

**Comment by masterleinad** [comment]
Let me check this.

**Comment by masterleinad** [comment]
ICC 16:
custom:
```
----------------------------------------------------
Exception on processing: 

--------------------------------------------------------
An error occurred in line <660> of file <step-6.cc> in function
    int main()
The violated condition was: 
    false
Additional information: 
    bla
--------------------------------------------------------

Aborting!
----------------------------------------------------
```
standard:
```
terminate called after throwing an instance of 'dealii::StandardExceptions::ExcMessage'
  what():  
--------------------------------------------------------
An error occurred in line <660> of file <step-6.cc> in function
    int main()
The violated condition was: 
    false
Additional information: 
    bla
--------------------------------------------------------

Aborted
```

**Comment by masterleinad** [comment]
For MSVC by default you get a ` ... has stopped working` popup dialog that doesn't print any information inserted into the `std::exception` object.

**Comment by masterleinad** [comment]
We could try to come up with a custom `terminate_handler` for MSVC.

**Comment by bangerth** [comment]
Anyone know how to do that?

**Comment by masterleinad** [comment]
At least, the straight-forward solution doesn't work with MSVC:
https://developercommunity.visualstudio.com/content/problem/135332/stdcurrent-exception-returns-null-in-a-stdterminat.html

**Comment by bangerth** [comment]
On 06/18/2018 09:59 AM, Daniel Arndt wrote:
> At least, the straight-forward solution doesn't work with MSVC:

It's amazing how MSVC is able to so consistently disappoint every time you 
want to do something nontrivial :-(

**Comment by tamiko** [comment]
@bangerth 
> It's amazing how MSVC is able to so consistently disappoint every time you want to do something nontrivial :-(

What a party pooper :-(

**Comment by tamiko** [comment]
@bangerth I will modify my PRs later this week. Currently on visit at TAMU and quite busy :-)

**Comment by drwells** [comment]
I would really like to get this done this week so that we can state, as of 9.1, that all of the tutorial programs are up-to-date.

**Comment by drwells** [comment]
I can tackle a few more of these today but I don't think we will be able to finish this for 9.1 unless we explicitly divide up the work among 3 or 4 of us. Should we move this to 9.2?

**Comment by kronbichler** [comment]
I won't have much time unfortunately. I could maybe do 1 or 2 tutorials. Anyone else? It's a pity that we need to stop so close to having this done. Since it's only tutorials and since it's only small changes, we might decide to cherry-pick if we are really sure not to introduce dangerous things. On the other hand, it wouldn't be a big dealbreaker if we only modernized *almost* all tutorials. @tamiko what do you think?

**Comment by drwells** [comment]
I am okay with continuing to cherry pick tutorial fixes for a few more days but it does require other people to sign on to doing a lot of work.

**Comment by jppelteret** [comment]
I'll do my best to modernise step-44 today. Unfortunately I also don't have the time to tackle any of the others, including step-33; it requires quite a bit of effort to rework the AD stuff :-(

**Comment by drwells** [comment]
A lot of the higher-number examples are newer and require less work. I am going to batch together a few.

**Comment by tamiko** [comment]
@jppelteret Agreed. Let's focus on safe cosmetic changes (not reworking every aspect of an example step).

**Comment by masterleinad** [comment]
Given that we are not going to include step-50 into the release, I guess we are done here once all the pull requests have been merged.

**Comment by drwells** [comment]
Yup. @masterleinad nice work redoing *22* of the tutorial programs!

**Comment by kronbichler** [comment]
This was a great effort, thanks to all who contributed and especially @masterleinad and @drwells who took the lion share. I'm closing this now because it feels so good to have this done. I will later open an issue for step-33 (AD). step-50 is on our todo list anyway and will be reviewed once it is ready.

**Comment by drwells** [comment]
I am still surprised that we managed to finish this. Well done everyone!
