### ISSUE TITLE
Unused functions in ParticleHandler class?

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#6790]
I am currently reworking the data transfer API to adjust it for the new p4est transfer functions. I stumbled over a function of the <code>ParticleHandler</code> class, that seems to be unused throughout the whole library, named <code>register_additional_store_load_functions</code>.

Thus, the member variables of this class are also unused:
- <code>size_callback</code>
- <code>store_callback</code>
- <code>load_callback</code>

So I wanted to ask if there may be any use of this function outside of deal.II (e.g. in ASPECT -- on first sight, I couldn't find any use of them there as well). Otherwise, I would consider to remove them to clean up the code.

@gassmoeller -- FYI

**Comment by gassmoeller** [comment]
The purpose of these functions is to be able to attach more data to the particles than they have properties. In ASPECT we attach additional data that is not per-se a property of the particle, but somehow related to it, specifically the intermediate positions we need for integrators like RK2 and RK4. One could argue that these should be properties, but they are not around between the integrator steps, and so I decoupled this data from the properties. If you feel this makes the whole structure too complicated, I could live with removing them, but it would require some work for me to rework it, so please only go in that directions if it is necessary (or if there are other reasons for it I do not see right now).

**Comment by marcfehling** [comment]
We'll try to replace the <code>void*</code> pointers to access the transfer buffers with ``std::vector<char>`` to be able to use the ``pack/unpack`` functions of the Utilities namespace. In the moment, this replacement only affects the callback functions of any class which is trying to send data through the ``Triangulation`` interface. Further, we let the ``Triangulation`` class take care of managing the data sizes that each registered callback function demands.

Alright, so these class members are mandatory. I just wanted to make sure :)

I implemented a workaround for the affected functions of the ``ParticleHandler`` class to cast the vector back to the void pointer, so no further changes are required for now.

But the transfer of particles across refinement would be predestined for the _variable size transfer_ feature we are currently working on. This will probably require some more changes on that class. I will let you know if we make this step.

**Comment by gassmoeller** [comment]
Sure, I am also fine if you want to deprecate the functions you mentioned above and replace them by functions that fill `std::vector<char>` instead of handing over dumb void pointers. That would be a simpler change for me.
