### ISSUE TITLE
Use MPI_Reduce_scatter in Utilities::MPI::compute_point_to_point_communication_pattern

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6796]
`Utilities::MPI::compute_point_to_point_communication_pattern` basically computes a transpose of a binary matrix where each processor has one row. We do this by hand, but it turns out that there is an MPI function that can do this: `MPI_Reduce_scatter`. This function is part of MPI 2.1. It would be nicer to use `MPI_Reduce_scatter_block`, which takes fixed-size inputs, but this function apparently only appeared in MPI 2.2.

Either way, we should look into using one of these functions.

**Comment by bangerth** [comment]
See for example section 6.5.6 of the book by Eijkhout: https://bitbucket.org/VictorEijkhout/hpc-book-and-course/src/default/EijkhoutIntroToHPC.pdf

**Comment by masterleinad** [comment]
Closed in #6851.
