### ISSUE TITLE
Can't fix broken indentation in documentation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6814]
I'd like to patch the broken indentation in the code examples of the documentation here: http://dealii.org/developer/doxygen/deal.II/classDataPostprocessorTensor.html

Specifically, I want to apply the following patch:
```
diff --git a/include/deal.II/numerics/data_postprocessor.h b/include/deal.II/numerics/data_postprocessor.h
index ff7df13..c5497c5 100644
--- a/include/deal.II/numerics/data_postprocessor.h
+++ b/include/deal.II/numerics/data_postprocessor.h
@@ -130,16 +130,16 @@ namespace DataPostprocessorInputs
    *       ... // overload other necessary member variables
    *       virtual
    *       void
-   *       evaluate_vector_field (const DataPostprocessorInputs::Vector<dim>
-   * &input_data, std::vector<Vector<double> > &computed_quantities) const
+   *       evaluate_vector_field (const DataPostprocessorInputs::Vector<dim> &input_data,
+   *                              std::vector<Vector<double> > &computed_quantities) const
    *       {
    *         const typename hp::DoFHandler<dim>::cell_iterator
-   *           current_cell = input_data.template get_cell<hp::DoFHandler<dim>
-   * >(); const viscosity = look_up_viscosity (current_cell->material_id());
+   *           current_cell = input_data.template get_cell<hp::DoFHandler<dim>>();
+   *         const viscosity = look_up_viscosity (current_cell->material_id());
    *
    *         for (unsigned int q=0; q<input_data.solution_gradients.size(); ++q)
    *           computed_quantities[q][0] = (viscosity *
-   * input_data.solution_gradients[q]).norm();
+   *                                        input_data.solution_gradients[q]).norm();
    *       }
    *   };
    * @endcode
@@ -635,9 +635,8 @@ private:
  *
  *   virtual
  *   void
- *   evaluate_scalar_field (const DataPostprocessorInputs::Scalar<dim>
- * &input_data, std::vector<Vector<double> >               &computed_quantities)
- * const
+ *   evaluate_scalar_field (const DataPostprocessorInputs::Scalar<dim> &input_data,
+ *                          std::vector<Vector<double> >               &computed_quantities) const
  *   {
  *     // ensure that there really are as many output slots
  *     // as there are points at which DataOut provides the
@@ -721,9 +720,8 @@ private:
  *
  *   virtual
  *   void
- *   evaluate_scalar_field (const DataPostprocessorInputs::Scalar<dim>
- * &input_data, std::vector<Vector<double> >               &computed_quantities)
- * const
+ *   evaluate_scalar_field (const DataPostprocessorInputs::Scalar<dim> &input_data,
+ *                          std::vector<Vector<double> >               &computed_quantities) const
  *   {
  *     AssertDimension (input_data.solution_gradients.size(),
  *                      computed_quantities.size());
@@ -893,9 +891,8 @@ private:
  *
  *     virtual
  *     void
- *     evaluate_vector_field (const DataPostprocessorInputs::Vector<dim>
- * &input_data, std::vector<Vector<double> >               &computed_quantities)
- * const
+ *     evaluate_vector_field (const DataPostprocessorInputs::Vector<dim> &input_data,
+ *                            std::vector<Vector<double> >               &computed_quantities) const
  *     {
  *       // ensure that there really are as many output slots
  *       // as there are points at which DataOut provides the
@@ -943,7 +940,8 @@ private:
  *     data_component_interpretation
  *     (dim, DataComponentInterpretation::component_is_part_of_vector);
  *     data_out.add_data_vector (solution,
- * std::vector<std::string>(dim,"displacement"), DataOut<dim>::type_dof_data,
+ *                               std::vector<std::string>(dim,"displacement"),
+ *                               DataOut<dim>::type_dof_data,
  *                               data_component_interpretation);
  *     data_out.add_data_vector (solution, grad_u);
  *     data_out.build_patches ();
@@ -982,9 +980,8 @@ private:
  *
  *     virtual
  *     void
- *     evaluate_vector_field (const DataPostprocessorInputs::Vector<dim>
- * &input_data, std::vector<Vector<double> >               &computed_quantities)
- * const
+ *     evaluate_vector_field (const DataPostprocessorInputs::Vector<dim> &input_data,
+ *                            std::vector<Vector<double> >               &computed_quantities) const
  *     {
  *       AssertDimension (input_data.solution_gradients.size(),
  *                        computed_quantities.size());
```

The problem is that clang-format insists on undoing almost all of these changes, even though they are in `@code ... @endcode` inside the class documentation.

The current version is clearly broken. What do I do if clang-format won't allow me to fix things?

**Comment by drwells** [comment]
We could just universally disable comment reflowing and go back to our old python script for wrapping comment lines, but I don't think its possible to selectively skip parts of comments without annotations in the comments themselves.

**Comment by bangerth** [comment]
OK, that may work for one of the places, but what about the others? The call to `add_data_vector` is completely broken, and so is the declaration of `evaluate_scalar/vector_field`? There is no rhyme and reason to it, and it's unreadable with the breaks put in...

**Comment by drwells** [comment]
ca9d4a43719 broke nearly all `@code`/`@endcode` blocks since `ReflowComments: true` was selected in `.clang-format`, so we cannot fix this by just reverting a commit :(

I think that there are two reasonable ways to proceed:
1. Manually edit all code samples to fit the 80 column limit and continue to use `ReflowComments: true`.
2. Manually edit all code samples and revert to using `wrapcomments` and set `ReflowComments: false`.

Neither option is great. I would be happy to hear if someone has an alternative.

In the mean time I suggest we go with 1. Lets vote:
1: vote :+1:
2: vote :tada:

**Comment by drwells** [comment]
Here is a list of header files that use `@code`/`@endcode`. I think we will just have to fix these manually:

- [ ] deal.II/base/timer.h
- [ ] deal.II/base/array_view.h
- [ ] deal.II/base/quadrature_lib.h
- [ ] deal.II/base/data_out_base.h
- [ ] deal.II/base/function.h
- [ ] deal.II/base/event.h
- [ ] deal.II/base/auto_derivative_function.h
- [ ] deal.II/base/conditional_ostream.h
- [ ] deal.II/base/index_set.h
- [ ] deal.II/base/exceptions.h
- [ ] deal.II/base/function_parser.h
- [ ] deal.II/base/geometry_info.h
- [ ] deal.II/base/iterator_range.h
- [ ] deal.II/base/mpi.h
- [ ] deal.II/base/parallel.h
- [ ] deal.II/base/parameter_handler.h
- [ ] deal.II/base/parsed_function.h
- [ ] deal.II/base/path_search.h
- [ ] deal.II/base/tensor.h
- [ ] deal.II/base/quadrature_point_data.h
- [ ] deal.II/base/signaling_nan.h
- [ ] deal.II/base/symmetric_tensor.h
- [ ] deal.II/base/table.h
- [ ] deal.II/base/table_handler.h
- [ ] deal.II/base/template_constraints.h
- [ ] deal.II/base/tensor_accessors.h
- [ ] deal.II/base/utilities.h
- [ ] deal.II/base/smartpointer.h
- [ ] deal.II/base/bounding_box.h
- [ ] deal.II/base/thread_management.h
- [ ] deal.II/base/vector_slice.h
- [ ] deal.II/base/vectorization.h
- [ ] deal.II/base/linear_index_iterator.h
- [ ] deal.II/base/parameter_acceptor.h
- [ ] deal.II/base/patterns.h
- [ ] deal.II/base/process_grid.h
- [ ] deal.II/distributed/shared_tria.h
- [ ] deal.II/distributed/solution_transfer.h
- [ ] deal.II/distributed/tria.h
- [ ] deal.II/dofs/dof_handler.h
- [ ] deal.II/dofs/dof_renumbering.h
- [ ] deal.II/dofs/dof_tools.h
- [ ] deal.II/dofs/block_info.h
- [ ] deal.II/fe/fe.h
- [ ] deal.II/fe/fe_system.h
- [ ] deal.II/fe/fe_values.h
- [ ] deal.II/fe/block_mask.h
- [ ] deal.II/fe/component_mask.h
- [ ] deal.II/fe/fe_enriched.h
- [ ] deal.II/fe/fe_nothing.h
- [ ] deal.II/fe/fe_p1nc.h
- [ ] deal.II/fe/fe_poly.h
- [ ] deal.II/fe/fe_poly_face.h
- [ ] deal.II/fe/fe_poly_tensor.h
- [ ] deal.II/fe/fe_q_base.h
- [ ] deal.II/fe/mapping_fe_field.h
- [ ] deal.II/fe/mapping_q1_eulerian.h
- [ ] deal.II/fe/mapping_q_eulerian.h
- [ ] deal.II/grid/grid_tools.h
- [ ] deal.II/grid/manifold_lib.h
- [ ] deal.II/grid/tria.h
- [ ] deal.II/grid/tria_accessor.h
- [ ] deal.II/grid/tria_iterator.h
- [ ] deal.II/grid/manifold.h
- [ ] deal.II/grid/filtered_iterator.h
- [ ] deal.II/grid/grid_generator.h
- [ ] deal.II/grid/grid_out.h
- [ ] deal.II/grid/intergrid_map.h
- [ ] deal.II/grid/persistent_tria.h
- [ ] deal.II/grid/tria_iterator_selector.h
- [ ] deal.II/hp/dof_handler.h
- [ ] deal.II/integrators/local_integrators.h
- [ ] deal.II/lac/block_vector_base.h
- [ ] deal.II/lac/cuda_vector.h
- [ ] deal.II/lac/diagonal_matrix.h
- [ ] deal.II/lac/block_linear_operator.h
- [ ] deal.II/lac/la_vector.h
- [ ] deal.II/lac/parpack_solver.h
- [ ] deal.II/lac/constrained_linear_operator.h
- [ ] deal.II/lac/la_parallel_block_vector.h
- [ ] deal.II/lac/trilinos_epetra_vector.h
- [ ] deal.II/lac/la_parallel_vector.h
- [ ] deal.II/lac/vector.h
- [ ] deal.II/lac/vector_space_vector.h
- [ ] deal.II/lac/vector_view.h
- [ ] deal.II/lac/sparsity_pattern.h
- [ ] deal.II/lac/linear_operator.h
- [ ] deal.II/lac/block_matrix_array.h
- [ ] deal.II/lac/full_matrix.h
- [ ] deal.II/lac/matrix_block.h
- [ ] deal.II/lac/slepc_spectral_transformation.h
- [ ] deal.II/lac/arpack_solver.h
- [ ] deal.II/lac/packaged_operation.h
- [ ] deal.II/lac/chunk_sparsity_pattern.h
- [ ] deal.II/lac/affine_constraints.h
- [ ] deal.II/lac/dynamic_sparsity_pattern.h
- [ ] deal.II/lac/filtered_matrix.h
- [ ] deal.II/lac/identity_matrix.h
- [ ] deal.II/lac/petsc_vector_base.h
- [ ] deal.II/lac/matrix_out.h
- [ ] deal.II/lac/petsc_parallel_vector.h
- [ ] deal.II/lac/petsc_solver.h
- [ ] deal.II/lac/read_write_vector.h
- [ ] deal.II/lac/precondition.h
- [ ] deal.II/lac/precondition_selector.h
- [ ] deal.II/lac/schur_complement.h
- [ ] deal.II/lac/slepc_solver.h
- [ ] deal.II/lac/solver.h
- [ ] deal.II/lac/solver_selector.h
- [ ] deal.II/lac/sparse_decomposition.h
- [ ] deal.II/lac/sparse_vanka.h
- [ ] deal.II/lac/utilities.h
- [ ] deal.II/lac/trilinos_vector.h
- [ ] deal.II/lac/vector_type_traits.h
- [ ] deal.II/lac/scalapack.h
- [ ] deal.II/matrix_free/fe_evaluation.h
- [ ] deal.II/matrix_free/operators.h
- [ ] deal.II/matrix_free/shape_info.h
- [ ] deal.II/meshworker/local_results.h
- [ ] deal.II/multigrid/mg_base.h
- [ ] deal.II/multigrid/mg_smoother.h
- [ ] deal.II/numerics/vector_tools.h
- [ ] deal.II/numerics/data_postprocessor.h
- [ ] deal.II/numerics/data_out_stack.h
- [ ] deal.II/numerics/derivative_approximation.h
- [ ] deal.II/numerics/error_estimator.h
- [ ] deal.II/numerics/fe_field_function.h
- [ ] deal.II/numerics/point_value_history.h
- [ ] deal.II/numerics/solution_transfer.h
- [ ] deal.II/numerics/time_dependent.h
- [ ] deal.II/numerics/data_out_dof_data.h
- [ ] deal.II/physics/notation.h
- [ ] deal.II/differentiation/ad/ad_number_traits.h
- [ ] deal.II/optimization/rol/vector_adaptor.h
- [ ] deal.II/sundials/arkode.h
- [ ] deal.II/sundials/ida.h
- [ ] deal.II/sundials/kinsol.h

**Comment by bangerth** [comment]
It's take us a long time to go through all of these files. Is there a technical way to fix this up, in the same way as @tamiko did before? The question is whether we want to keep reflow-comments -- if we do, then we need to fix up by hand; if we can live without, then we could revert at least the documentation to the situation before.

**Comment by drwells** [comment]
We could probably do it automatically with a script that does roughly the following:
1. find a `@code`/`@endcode` block
2. print it to `block.cc`
3. run `clang-format` with a modified line length parameter (to account for ` * `) on `block.cc`
4. replace the old block with the reflowed block

However, we would have to use the pre clang-format version of each block, since some text that was previously in comments is now uncommented.

**Comment by masterleinad** [comment]
For comparison, I have a PR in preparation that tries to revert the effects of `ReflowComments`.

**Comment by masterleinad** [comment]
See #6822.

**Comment by masterleinad** [comment]
It seems that all items on the list have been looked at. Is there anything else that should be addressed in this issue?

**Comment by drwells** [comment]
The consensus was to manually reflow comments. Since we have done that (well, mostly @masterleinad did it) I think we are done :)

**Comment by bangerth** [comment]
Thanks, y'all!
