### ISSUE TITLE
Backward compatibility for #6816

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#6828]
#6816 is not backward-compatible as the necessary changes in the tests and the [recently failing HDF5 test](https://cdash.kyomu.43-1.org/testDetails.php?test=17947376&build=2835) show. 
Examples are the `DataOutBase::write_*` functions.
We should keep the old signatures, deprecate them and forward to the new interface.

**Comment by davydden** [comment]
I know that those functions are in public namespace, but I would not bother deprecating it and just update the remaining tests. The rationale is that they are, IMO, in nature implementations details that users are unlikely to use. They are probably ‘public’ only to make testing possible.

**Comment by davydden** [comment]
Ps. High-level write_vtu and alike are unchanged

**Comment by masterleinad** [comment]
I am much happier to follow the policy of not breaking backward-compatibility in the public interface if avoidable. Let me write a PR.
