### ISSUE TITLE
Style: using or typedef?

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6836]
I think @masterleinad prefers the new `using` syntax while I prefer `typedef`. We should pick one as the preferred option so that we do not end up with some of one and some of the other. If we go with `using` it will take awhile to convert everything, but at least new stuff will be consistent.

Edit: I hit enter too soon

**Comment by drwells** [comment]
From #6833.

**Comment by masterleinad** [comment]
The main reason for preferring `using` over `typedef` is the (at least for me) unintuitive order of arguments. Something (made up) like
```
typedef number_type value_type
```
is less clear than
```
using value_type = number_type
```
Of course, the functionality of `using` is also a superset of the functionality of `typedef` (alias template). It also fits nicer with the syntax of `using`-declarations (for class members) and `using`-directives for `namespaces`. For users new to C++ it is one keyword less to remember.

**Comment by bangerth** [comment]
The real issue with `typedef` is if you have pointers to functions and similar:
```
  typedef int (*foo) (double);
```
is just weird. "Much" easier and clearer to write
```
  using foo = int (*) (double);
```
So for consistency then, I'd prefer `using`.

**Comment by jppelteret** [comment]
Also alias declarations (aka. template typedefs) use the using keyword. So it seems to me that using offers more flexibility + overall consistency.
