### ISSUE TITLE
Add SymmetricTensorFunction

### ISSUE THREAD

**Issue by ZeeD26** [dealii/dealii#6847]
Dear all,

sometimes I would like to use the existing functions functors interface to provide functions that are able to return SymmetricTensors.

Best regards.

**Comment by drwells** [comment]
I am not sure that I understand what you are proposing. Presently, we have `TensorFunction` that is not related to `Function` at all (i.e., we cannot use it to project or interpolate). Do you mean that we should also add `SymmetricTensorFunction` (which would be defined in a similar way and would not inherit from `Function`), or somehow add additional methods to `Function`?

**Comment by drwells** [comment]
There hasn't been any followup on this in a few years so demand is low - lets close the issue for now.
