### ISSUE TITLE
Installation error : make Error 2

### ISSUE THREAD

**Issue by jnfvope930** [dealii/dealii#6848]
I am getting error during installation, not sure if it is dealii bug or related with gcc

[ 19%] Building CXX object source/numerics/CMakeFiles/obj_numerics_release.dir/data_out.cc.o
c++: internal compiler error: Killed (program cc1plus)

source/numerics/CMakeFiles/obj_numerics_release.dir/build.make:62: recipe for target 'source/numerics/CMakeFiles/obj_numerics_release.dir/data_out.cc.o' failed
make[2]: *** [source/numerics/CMakeFiles/obj_numerics_release.dir/data_out.cc.o] Error 4
CMakeFiles/Makefile2:1198: recipe for target 'source/numerics/CMakeFiles/obj_numerics_release.dir/all' failed
make[1]: *** [source/numerics/CMakeFiles/obj_numerics_release.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davydden** [comment]
most likely you are running out of memory. Try building with fewer cores (`-j 2`)

**Comment by masterleinad** [comment]
Please ask this kind of questions in the [`deal.II User Group`](https://groups.google.com/forum/#!forum/dealii).
