### ISSUE TITLE
Cannot configure if Trilinos has CUDA support

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#6856]
I cannot configure deal if I compiled Trilinos with CUDA support. During configuration we check that Sacado supports C++11 (see [here](https://github.com/dealii/dealii/blob/master/cmake/modules/FindTRILINOS.cmake#L151)), the problem is that if CUDA is enabled we should use nvcc to try to compile the test but we are using gcc. So the test fails with the following error:
```
In file included from /home/bruno/Documents/software/trilinos_debug/install/include/Sacado_ConfigDefs.h:80:0,
                 from /home/bruno/Documents/software/trilinos_debug/install/include/Sacado_cmath.hpp:34,
                 from src.cxx:2:
/home/bruno/Documents/software/trilinos_debug/install/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type 
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline 
                                        ^  
/home/bruno/Documents/software/trilinos_debug/install/include/Sacado_cmath.hpp:62:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’   
   KOKKOS_INLINE_FUNCTION 
   ^ 
ninja: build stopped: subcommand failed. 
```
Since the test fails, we conclude that sacado does not support C++11 and the configuration stops with
```
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):
  

  Could not find the trilinos library!

  The Trilinos installation (found at
  "/home/bruno/Documents/software/trilinos_debug/install")

  is not compatible with the C++ standard selected for

  this compiler.  See the deal.II FAQ page for a solution.
```

Even if we can go through the configuration, we will need all the files that include Sacado (and probably MueLu) to be compiled with nvcc not gcc.  I am not sure how to fix this... I can live with having to install two different versions of Trilinos but that might be a problem for others if they want to use `Tpetra` with cuda support in their own code.

**Comment by Rombur** [comment]
Being able to disable Sacado is the easiest fix but this doesn't solve the problem that deal.II cannot be compiled if Trilinos has CUDA support enabled. I have tried to compile deal using `nvcc_wrapper` as the compiler (i.e. the whole library is sent to `nvcc`) but this doesn't work out of box. The biggest problem is that `nvcc` doesn't play too well with complex number so we will need to a way to disable the instantiation for complex number. This is not the only problem though...

**Comment by anates** [comment]
I would like to use Sacado/Trilinos on the GPU, which in the current situation is not possible. Thus I was wondering about the status here (so that I can use Trilinos fully on the GPU)?

**Comment by Rombur** [comment]
We haven't made any significant progress on this except being able to disable complex number support. What you could try is to use the development version of deal.II, the latest version of cuda/gcc that you have access to, disable complex numbers, use `nvcc_wrapper` as your compiler, and see how far in the compilation you get. Maybe there won't be too many things to fix.

**Comment by anates** [comment]
Unfortunately there still are quite a lot of errors when compiling deal.II that way, I attached the error log (no external libraries configured, just bare deal.II)
[nvcc_error.log](https://github.com/dealii/dealii/files/2746170/nvcc_error.log)

**Comment by Rombur** [comment]
:disappointed:  I am going to a meeting next week where a few Trilinos developers will be present. I'll ask them what's the best way forward.

**Comment by anates** [comment]
Perfect, thanks!

**Comment by Rombur** [comment]
@anates There is no easy solution to this problem. I was told to try `cuda clang` but I would be surprised if that fixes the problem. There are two solutions for this problem:
1) change the build system so that the files that include trilinos use `nvcc_wrapper` and the others use `gcc`. This is not a realistic solution due to its complexity.
2) fix all the errors 😞

**Comment by anates** [comment]
Which means if I would like to use things like AD on the GPU, I am (currently) out of luck?

**Comment by Rombur** [comment]
Yes, unfortunately. Also I can't tell you how long it will take us to fix this. I personally don't have time to fix it in the foreseeable future. So if it is something that you really need, you will probably have to fix these bugs yourself.

**Comment by masterleinad** [comment]
I can compile now if I disable `MueLu` and `Sacado`.

**Comment by anates** [comment]
Hmm, Sacado would be what I would have needed...

**Comment by masterleinad** [comment]
You are happily invited to fix the remaining errors. :smiley:

**Comment by Rombur** [comment]
I think the problem is because when I wrote the MueLU wrappers I went with a hammer and I forced the interface to use `Epetra` since this was the only thing we supported. I think that the comment 
```C++
 // For now, just use serial node, i.e. no multithreaing or GPU.
using node = KokkosClassic::DefaultNode::DefaultNodeType;
```
is not correct. The node type that we are using is whatever the default type is, i.e., GPU if we use GPU support. Of course you cannot create an `Epetra_Operator` on the GPU so it doesn't work. So we either need to change the function so that we don't use an `Epetra_Operator` on the GPU or change this [line](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_precondition_muelu.cc#L213) to use the serial node no matter what (this is of course a problem if Trilinos was compiled without support for serial execution...).

**Comment by anates** [comment]
Would it be possible (for the future) to switch to TPetra instead of EPetra? According to my knowledge (https://trilinos.org/docs/dev/packages/epetra/doc/html/index.html, https://trilinos.org/docs/dev/packages/tpetra/doc/html/index.html) the former one is intended to replace the latter one sooner or later, while having more features, such as hybrid parallelism. I think that should also solve this issue (untested yet). Or would it be possible to detect if Epetra or TPetra is available, and use the wrappers accordingly?

**Comment by jppelteret** [comment]
Hi,

I’m sure that Bruno will clarify this later today, but I believe that the is a long-standing discussion to move the Trilinos interfaces to using Tpetra. See, for example
https://github.com/dealii/dealii/issues/745#issuecomment-284618598 <https://github.com/dealii/dealii/issues/745#issuecomment-284618598>
There is already some work in progress in this regard, e.g.
https://github.com/dealii/dealii/pull/7180 <https://github.com/dealii/dealii/pull/7180>

Best,
Jean-Paul

**Comment by Rombur** [comment]
Switching to the Tpetra stack is something that we will eventually have to do but I don't think it is easy to do correctly, unless we limit ourselves to the CPU but then what's the point of switching. One problem is that Tpetra was started before GPU were used so everything was done thinking only about multithreading. Then to support GPU they started using Kokkos but they didn't remove the old interface so now you have two interfaces to navigate (one for `Teuchos::ArrayView` and one for `Kokkos`). There is also a plan to change Tpetra template parameters soon so this means probably more work if we add wrappers now since they will have to be updated soon. Finally using Tpetra sparse matrix with Kokkos interface (which you will need to use GPU) is not easy. I've tried, someone I work with also tried and we both gave up (maybe we tried to the wrong way and it's pretty easy to do but then the documentation should be made clearer) The PR @masterleinad has for Tpetra vector is a massive amount of work but it's the easy part and I am not sure that it works on GPU (we can't try since we can't compile deal with `nvcc_wrapper`).

**Comment by masterleinad** [comment]
> The PR @masterleinad has for Tpetra vector is a massive amount of work but it's the easy part and I am not sure that it works on GPU (we can't try since we can't compile deal with `nvcc_wrapper`).

As I said, I can compile with `nvcc_wrapper` now if I disable `MueLu` and `Sacado` support. I will test #7180 with this soon. Still, switching from `Epetra` to `Tpetra` is non-trivial and I think we can come up with a much easier solution here.

**Comment by masterleinad** [comment]
> I would like to use Sacado/Trilinos on the GPU, which in the current situation is not possible. Thus I was wondering about the status here (so that I can use Trilinos fully on the GPU)?

@anates Do you have `Sacado` code running on the `GPU` (natively without `deal.II`)?

**Comment by anates** [comment]
@masterleinad No, not yet, but after my problem requires using an AD-method (forming the jacobian), I assumed it would be good having everything on the GPU, not only having data on the GPU, and the matrix calculation on the CPU

**Comment by masterleinad** [comment]
Support for `DEAL_II_WITH_COMPLEX_VALUES` is blocked by https://github.com/kokkos/kokkos/issues/1964.
