### ISSUE TITLE
Documentation talks about Dirichlet boundary conditions when it should be "strong" boundary conditions

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#686]
For example, in the documentation of various functions in `MatrixTools`. These functions apply _strong_ boundary conditions, not _Dirichlet_ boundary conditions. This is often the same, but not always.

**Comment by tamiko** [comment]
Let's just stick with Dirichlet boundary conditions. I haven't found any consensus in the literature with respect to <i>essential</i>, <i>strong</i> and <i>Dirichlet</i> boundary conditions.

**Comment by bangerth** [comment]
I think there is general consensus that essential==natural==goes into the bilinear form, whereas strong==part of the function space==needs to be imposed after assembly and at the discrete level.

The thing is that for example for the mixed Laplace, Dirichlet conditions on the pressure are actually natural boundary conditions.

**Comment by tamiko** [comment]
*umh* essential != natural. More, essential == strong.

> The thing is that for example for the mixed Laplace, [...]
Yes, but I can still call strongly imposed Dirichlet boundary conditions, Dirichlet conditions...

But if you want we can compromise on something like »strong (Dirichlet) boundary conditions«.

**Comment by bangerth** [comment]
> /umh/ essential != natural. More, essential == strong.

Doh, of course.


>     The thing is that for example for the mixed Laplace, [...]
>     Yes, but I can still call strongly imposed Dirichlet boundary conditions,
>     Dirichlet conditions...
>
> But if you want we can compromise on something like »strong (Dirichlet)
> boundary conditions«.

Sure. It's not something that's been so urgent to me that I couldn't wait to 
fix it :-)

**Comment by tamiko** [comment]
> Sure. It's not something that's been so urgent to me that I couldn't wait to 
> fix it :-)

You can always add the label "High Priority". :-P

**Comment by bangerth** [comment]
Seems like this is pretty low on everyone's priority queue :-)
