### ISSUE TITLE
LA::d::Vector = TrilinosWrappers::MPI::Vector deprecation

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6867]
[LinearAlgebra::distributed::Vector::operator= (const TrilinosWrappers::MPI::Vector< Number > &)](https://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1distributed_1_1Vector.html#a53c325ee451ea45ade515f3c9544169e) is deprecated with reference to [LinearAlgebra::ReadWriteVector::import()](https://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1ReadWriteVector.html#afc746d51575b3bc8f2d4ba8f95f9d3d9), however LA::d::Vector is not derived from ReadWriteVector.

**Comment by masterleinad** [comment]
The implementation for `LinearAlgebra::distributed::Vector::operator= (const TrilinosWrappers::MPI::Vector< Number > &)` is
```
IndexSet combined_set = partitioner->locally_owned_range();
combined_set.add_indices(partitioner->ghost_indices());
ReadWriteVector<Number> rw_vector(combined_set);
rw_vector.import(trilinos_vec, VectorOperation::insert);
import(rw_vector, VectorOperation::insert);
```

Hence, what is meant is to create a corresponding `ReadWriteVector` object, calling its `import()` function and then `LinearAlgebra::distributed::Vector::import()`.

**Comment by davydden** [comment]
thanks for clarification.
