### ISSUE TITLE
adjust_ghost_range_if_necessary should also use is_globally_compatible

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6868]
In `MF` base operator we adjust ghost range if `LA::d::Vector` does not use the same partitioner object. What we should probably do is add another check via `is_globally_compatible` as the partitioner might be exactly the same but via a different object.

**Comment by kronbichler** [comment]
@davydden can you explain what you mean by

>>  as the partitioner might be exactly the same but via a different object.

If the pointer comparison in https://github.com/dealii/dealii/blob/master/include/deal.II/matrix_free/operators.h#L1366 succeeds, both objects share the same `shared_ptr`. There cannot be a different object at this point.

I am hesitant to add `is_globally_compatible`, i.e., global communication, in each matrix-vector product, at least in release mode. The only thing it would cover on top of the pointer comparison is that some processors use a different shared pointer set up than others, which means that the user has really messed things up, at which point the only sane thing could be to add an assertion in debug mode maybe, but not more than that.

**Comment by davydden** [comment]
> The only thing it would cover on top of the pointer comparison is that some processors use a different shared pointer set up than others, which means that the user has really messed things up, at which point the only sane thing could be to add an assertion in debug mode maybe, but not more than that.

Agree. 

Frankly I don't remember the reason why I came to this issue, let's close it for now.
