### ISSUE TITLE
Disable -Wclass-memaccess

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6875]
With GCC 8.1, I get lots of warnings of this sort:
```
/home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/container/detail/copy_move_algo.hpp:181:19: warning: ‘void* memmove(void*, const void*, size_t)’ writing to an object of type ‘boost::container::container_detail::iterator_to_element_ptr<std::pair<double, dealii::Tensor<1, 3> >*>::element_type’ {aka ‘struct std::pair<double, dealii::Tensor<1, 3> >’} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
       std::memmove((iterator_to_raw_pointer)(r), (iterator_to_raw_pointer)(f), sizeof(value_type)*n);
       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'm not in the mood of fixing BOOST or requiring a newer BOOST version. Should we simply disable `-Wclass-memaccess`?

**Comment by drwells** [comment]
I get a lot of these warnings when compiling in C++11 mode and they are annoying. I think we should just disable them. When we require C++17 in five years we can just turn it back on again.

**Comment by bangerth** [comment]
By then, we'll probably also have a fixed boost version.

Anyone object to disabling the warning?

**Comment by Rombur** [comment]
Do we still disable warnings in TPLs? I thought this was fixed by using `isystem`

**Comment by bangerth** [comment]
I had thought so as well, but apparently that's not the case. Maybe I have to look at how we include these files...

**Comment by masterleinad** [comment]
I prefer to keep the warning in our code and disable it if we don't have C++17 support (and in the bundled boost).

**Comment by masterleinad** [comment]
At least @drwells is easily addressable.
