### ISSUE TITLE
Cleanups for #6864

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6877]
Here are two small cleanups I'd like to tackle once #6864 is in:
* The unpack functions take the iterator range by-value, but that should be by-reference
* The pack functions pack into a `std::vector<char>` that is provided by reference. For this, they have to resize it, but in that case we may just as well let them create the `std::vector<char>` locally and then return the object, using move semantics all the way.

**Comment by marcfehling** [comment]
We can close this issue now since all requirements have been met.

**Comment by masterleinad** [comment]
Ah, for the next time you can simply mention "Fixes #6864" in your pull request description (https://help.github.com/articles/closing-issues-using-keywords/).
