### ISSUE TITLE
Add optional center arguments to GridGenerator functions

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#6890]
This could be useful for (as @davydden mentioned in #6863) functions like `hyper_cube_with_cylindrical_hole`.

**Comment by bangerth** [comment]
But you can always move a mesh around. Why duplicate this functionality in all functions individually?

**Comment by drwells** [comment]
At least for the shell functions (or things that have curved edges) this would be convenient since it would set up the manifolds correctly.

**Comment by davydden** [comment]
@drwells 

> This could be useful for (as @davydden mentioned in #6863) functions like hyper_cube_with_cylindrical_hole.

i was not price, what I meant is to shift the vertices of the hole in `hyper_cube_with_cylindrical_hole`. I think that's what's you do in #6863 , i.e. create a standard hole and then slightly offset vertices on the inner boundary to get non-symmetric hole.
