### ISSUE TITLE
Deal-9 MPI

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#6902]
```-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:84 (MESSAGE):


 Could not find any suitable mpi library!

 Your MPI implementation must define MPI_SEEK_SET.



 Please ensure that an mpi library is installed on your computer

```

I was able to install Deal-8 with the same script and I’m pretty sure that my MPI is fine. MPI_SEEK_SET is in mpio.h.

Detailed log attached.

PS I sent this message to your googlegroup. Has that one been abandoned?

[deal-9_intel17_impi_17_0.log](https://github.com/dealii/dealii/files/2176586/deal-9_intel17_impi_17_0.log)

**Comment by jppelteret** [comment]
I'm closing this to answer it on the deal.II mailing list.
