### ISSUE TITLE
Iterating over Trilinos sparsity pattern fails

### ISSUE THREAD

**Issue by mathsen** [dealii/dealii#6909]
Hello,

I stumbled upon a little problem, when I tried to generate a sparse matrix out of a sparse block matrix, in order to pass it directly to a direct sparse solver or use the matrix with an AMG preconditioner.
During this process I tried to generate my sparse matrix by iterating over the sparsity patterns of the single block matrices, which brought up this error.

In a nutshell: I have a sparsitiy pattern and iterate over it. Afterwards I reinit a sparse matrix with the sparsity pattern, which should not touch the pattern itself (as it is declared as a const parameter) and afterwards I can't iterate over the sparsity pattern again.

```
dealii::TrilinosWrappers::SparsityPattern sp(3,3);
dealii::TrilinosWrappers::SparseMatrix m;

// fill sp compress it

auto it_a = sp.begin() // works

m.reinit(sp);

auto it_b = sp.begin() //crash

```

If I try to create it_b, the following exception is thrown:

```
terminate called after throwing an instance of 'dealii::TrilinosWrappers::SparsityPattern::ExcTrilinosError'
  what():  
--------------------------------------------------------
An error occurred in line <733> of file </apps/candi/deal.II-toolchain/v9.0.0/system-mpich/tmp/unpack/deal.II-v9.0.0/source/lac/trilinos_sparsity_pattern.cc> in function
    void dealii::TrilinosWrappers::SparsityPattern::compress()
The violated condition was: 
    ierr == 0
Additional information: 
    An error with error number 1 occurred while calling a Trilinos function
--------------------------------------------------------
```

I have created a small example, that demonstrates the problem:
[sp_issue.zip](https://github.com/dealii/dealii/files/2183527/sp_issue.zip)

I have found a way to cope with this problem and now use the sparse matrices to initialize my new sparsity pattern, yet I wanted to report this problem.

Greetings,

Mathias

**Comment by bangerth** [comment]
@mathsen, since you reported the error, would you be willing to let us know your real name?

**Comment by koecher** [comment]
@bangerth: his name is Mathias Anselmann, a new PhD in our group.
He is currently working on extending my codes for wave equations.

**Comment by bangerth** [comment]
@koecher : Yes, @mathsen, he had already mentioned his name in #6915 and @masterleinad had added his name to the patch. Either way, @mathsen: welcome to the list of deal.II authors! (Your name will be added to that file when we go through all authors as part of the 9.1 release preparations.)
