### ISSUE TITLE
improve SparsityPattern to optionally NOT to store diagonals regardless

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6917]
I use sparsity pattern to store some auxiliary objects in MPI context. As a kind of a map from `(i,j)` pair to the data.

Current behaviour is such that even if I do not add elements to certain rows (through `DynamicSparsityPattern`), the resulting sparsity will contain entries in all rows. Namely, empty rows will have diagonal entries.

EDIT: for now I will switch to `std::vector` of `std::tuple`, unless there are big reasons not to add this functionality, I would like it to happen eventually.

**Comment by bangerth** [comment]
Yes, we used to do this but then switched to the format that if the matrix is square, we always store the diagonal and do so first in each row. It avoided a lot of `if` statements and is just the more efficient way. I think it should stay this way.

**Comment by davydden** [comment]
Ok, i will Stick with std::tuple for my needs.
