### ISSUE TITLE
\hat in LaTeX are not rendered correctly (Mapping classes)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6930]
documentation for all mapping classes has broken equations like

![screen shot 2018-07-19 at 08 51 36](https://user-images.githubusercontent.com/8023934/42926221-08d0b4e4-8b31-11e8-97a1-02d6beb3938c.png)

however LaTeX code is perfectly fine
```
J(\hat{\mathbf  x})
```
and renders as
![image](https://user-images.githubusercontent.com/8023934/42926249-1f56a89a-8b31-11e8-9dd1-c2ea5f382edc.jpeg)

Not sure it's fixable, but still somewhat annoying... ;-(

**Comment by bangerth** [comment]
We had a patch by @sophy1029 a while back that tried to address that in the tutorials but it wasn't fixable. It's a problem in MathJAX we concluded. It also seems to differ between browsers -- some of which render it correctly and some don't.

**Comment by bangerth** [comment]
See #5933.

**Comment by davydden** [comment]
damn, pitty that the patch did not fix it in Safari...
