### ISSUE TITLE
undefined reference on dealii::Vector<Sacado::Fad::DFad<double> >

### ISSUE THREAD

**Issue by fvanmaele** [dealii/dealii#6940]
Sample code: https://gist.github.com/fvanmaele/eb5140baba4c8c028f39d25f31a244d5
```
typedef Sacado::Fad::DFad<NumberType>  FAD_Number;
  dealii::FullMatrix<NumberType> diff(const dealii::Vector<FAD_Number> &f, size_t m)
```
Error:
```
23:18:30: Starting: "/usr/bin/cmake" --build . --target all
[ 50%] Linking CXX executable multiple-shooting
CMakeFiles/multiple-shooting.dir/multiple-shooting.cc.o:multiple-shooting.cc:function dealii::Vector<Sacado::Fad::DFad<double> >::Vector(unsigned int): error: undefined reference to 'dealii::Vector<Sacado::Fad::DFad<double> >::reinit(unsigned int, bool)'
CMakeFiles/multiple-shooting.dir/multiple-shooting.cc.o:multiple-shooting.cc:vtable for dealii::Vector<Sacado::Fad::DFad<double> >: error: undefined reference to 'dealii::Vector<Sacado::Fad::DFad<double> >::reinit(unsigned int, bool)'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/multiple-shooting.dir/build.make:208: recipe for target 'multiple-shooting' failed
CMakeFiles/Makefile2:195: recipe for target 'CMakeFiles/multiple-shooting.dir/all' failed
Makefile:83: recipe for target 'all' failed
make[2]: *** [multiple-shooting] Error 1
make[1]: *** [CMakeFiles/multiple-shooting.dir/all] Error 2
make: *** [all] Error 2
23:18:31: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project multiple-shooting (kit: Desktop)
When executing step "Make"
```
Build configuration: https://gist.github.com/fvanmaele/5bb72bd6c83ff4acb13cc9f22f22a6ba (In particular, deal.ii 9.0.0, clang 6.0, and Trilinos 2.10.1)

Oddly enough it works fine with Tensor. https://gist.github.com/fvanmaele/d6d3fbe0d039e88a7f7a19473c00a8a2
```
  template <size_t dim>
  dealii::FullMatrix<NumberType> diff(const dealii::Tensor<1, dim, FAD_Number> &f, size_t m)
```

**Comment by jppelteret** [comment]
Neither the `Vector` or `FullMatrix` class are instantiated for AD number types. Normally you would be able to simply include the template file (i.e. `#include <deal.II/lac/vector.templates.h>`) but I've just verified that this will not work because it will trigger an assertion for `is_finite<Number>` in debug mode. I'll see if I can add this functionality. In the mean time, you could consider storing all AD values in a `std::vector`.

**Comment by jppelteret** [comment]
So I've taken another look at this and am reminded of the difficulties in getting these two linear algebra classes (`Vector` and `FullMatrix`) to work with AD numbers. I'm going to close this issue saying that we have no immediate plans to extend these classes to support AD numbers. What I suggest is that you simply change your `Vector<ADNumberType>` to a `std::vector<ADNumberType>` - I would expect this to make your code function as expected. `std::vector` is the storage type that we use within the library itself.

**Comment by fvanmaele** [comment]
Thanks.

**Comment by jppelteret** [comment]
You're welcome, and sorry that this didn't turn out how you might have hoped it would. I will be making a PR in a few minutes to explicitly ensure that nobody tries to instantiate `Vector` and `FullMatrix` with AD numbers.
