### ISSUE TITLE
Interpolating function failing on distributed settings

### ISSUE THREAD

**Issue by GivAlz** [dealii/dealii#6956]
Hi everyone,
  it seems like one of the reasons my active PR is still there is that I've found a problem with interpolation. This is a minimal example generating the error:

```
#include <iostream>

#include <deal.II/base/function.h>
#include <deal.II/base/function_lib.h>
#include <deal.II/base/logstream.h>
#include <deal.II/base/mpi.h>

#include <deal.II/distributed/tria.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/mapping_q.h>

#include <deal.II/grid/filtered_iterator.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/grid_tools_cache.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/tria.h>

#include <deal.II/lac/la_parallel_vector.h>

#include <deal.II/numerics/vector_tools.h>

using namespace dealii;

template <int dim>
void
test_interpolating_distributed(unsigned int ref_cube)
{
  MPI_Comm     mpi_communicator = MPI_COMM_WORLD;
  unsigned int n_procs = Utilities::MPI::n_mpi_processes(mpi_communicator);

  std::cout << "Testing for dim = " << dim << " on " << n_procs << " processes"
          << std::endl;
  std::cout << "Cube refinements: " << ref_cube << std::endl;

  FE_Q<dim>       fe(1);
  // Implementing the constant function
  Functions::ConstantFunction<dim> f_constant(1.0);

  // Creating a distributed triangulation

  parallel::distributed::Triangulation<dim> cube_d(mpi_communicator);
  GridGenerator::hyper_cube(cube_d);
  cube_d.refine_global(ref_cube);
  std::cout << "Initializing the dof handler" << std::endl;
  DoFHandler<dim> dof_handler_d(cube_d);
  dof_handler_d.distribute_dofs(fe);

  std::cout << "Interpolating data" << std::endl;
  LinearAlgebra::distributed::Vector<double> data_d(dof_handler_d.n_dofs());
  VectorTools::interpolate(dof_handler_d, f_constant, data_d);
  std::cout << "Test passed" << std::endl;
}

int main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
  test_interpolating_distributed<2>(3);
}
```

If you try to run it with mpirun -np 2 (or even 1, actually), it will give and error:

> An error occurred in line <292> of file </opt/src/dealii/source/distributed/tria.cc> in function
>     bool dealii::{anonymous}::tree_exists_locally(const typename dealii::internal::p4est::types<dim>::forest*, typename dealii::internal::p4est::types<dim>::topidx) [with int dim = 2; int spacedim = 2; typename dealii::internal::p4est::types<dim>::forest = p4est; typename dealii::internal::p4est::types<dim>::topidx = int]
> The violated condition was: 
>     coarse_grid_cell < parallel_forest->connectivity->num_trees
> Additional information: 
>     This exception -- which is used in many places in the library -- usually indicates that some condition which the author of the code thought must be satisfied at a certain point in an algorithm, is not fulfilled. An example would be that the first part of an algorithm sorts elements of an array in ascending order, and a second part of the algorithm later encounters an element that is not larger than the previous one.
> 
> There is usually not very much you can do if you encounter such an exception since it indicates an error in deal.II, not in your own program. Try to come up with the smallest possible program that still demonstrates the error and contact the deal.II mailing lists with it to obtain help.

I initially thought the problem was with interpolation, but this is even more surprising (for this particular run I used version 9.0; but also with 9.1-pre I get the same error)

**Comment by GivAlz** [comment]
Ok, this might be a problem of my installation; I shall now check...

**Comment by GivAlz** [comment]
Something went wrong in the p4est installation, it seems. Thus I will now recompile an hopefully finish my PR. Sorry for the spam!

**Comment by jppelteret** [comment]
No worries, I'm glad we managed to sort this out!
