### ISSUE TITLE
Make indent issue

### ISSUE THREAD

**Issue by GivAlz** [dealii/dealii#6972]
Usually to indent PR I make use of "make indent"; there's a problem when indenting a PR which is behind the master last commit.

There are two small problems:
1) Some files are not found
`diff: tests/data_out/data_out_filter_02.cc: No such file or directory`
2) after this sort of error message, trying to change branch will result into a error like the following:
```
Please commit your changes or stash them before you switch branches.
error: The following untracked working tree files would be overwritten by checkout:
	tests/data_out/data_out_filter_02.cc
	tests/grid/merge_triangulations_05.cc
	tests/mpi/hp_distribute_dofs_01.cc
```

Best,
Giovanni

**Comment by drwells** [comment]
Could you try that?

**Comment by GivAlz** [comment]
Yes, now it works! The problem, clearly, is that every "old" branch needs to be rebased.
Thank you, sorry I looked for similar issues, but only on open issues...

**Comment by drwells** [comment]
Its annoying that we now have a bunch of stale branches, but `make indent`s performance problems with clang format were unfortunately a bigger issue.
