### ISSUE TITLE
Unclear documentation of IndexSet::create_trilinos_map()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#699]
@kronbichler : In the context of #698 I looked at the function in the title and was confused by the documentation which says:
```
   * On the other hand, if the second argument is true, then the index sets
   * can be overlapping, though they still need to contain each index exactly
   * once on all processors taken together. This is a useful operation if we
   * want to create vectors that not only contain the locally owned indices,
   * but for example also the elements that correspond to degrees of freedom
   * located on ghost cells.
   */
  Epetra_Map make_trilinos_map (const MPI_Comm &communicator = MPI_COMM_WORLD,
                                const bool      overlapping  = false) const;
```
I believe that the second part of the sentence "though they still need to contain each index exactly once" is not true, at least that's what I get when I run the testsuite. For example, we do this in creating a Trilinos sparsity pattern:
```
  SparsityPattern::reinit (const IndexSet  &row_parallel_partitioning,
                           const IndexSet  &col_parallel_partitioning,
                           const IndexSet  &writable_rows,
                           const MPI_Comm  &communicator,
                           const size_type  n_entries_per_row)
  {
    reinit(row_parallel_partitioning, col_parallel_partitioning,
           communicator,n_entries_per_row);

    IndexSet nonlocal_partitioner = writable_rows;
    AssertDimension(nonlocal_partitioner.size(), row_parallel_partitioning.size());

    nonlocal_partitioner.subtract_set(row_parallel_partitioning);     // <<----------------------
    if (Utilities::MPI::n_mpi_processes(communicator) > 1)
      {
        Epetra_Map nonlocal_map =
          nonlocal_partitioner.make_trilinos_map(communicator, true);  // <<---------------
        nonlocal_graph.reset(new Epetra_CrsGraph(Copy, nonlocal_map, 0));
      }
    else
      Assert(nonlocal_partitioner.n_elements() == 0, ExcInternalError());
  }
```
Do you agree that the documentation is misleading?

**Comment by kronbichler** [comment]
I agree. It should be 'at least once' and not 'exactly once'. We require the map to be surjective, if it is one-to-one we have a non-ghosted version.

**Comment by bangerth** [comment]
Well, but that's not true either. I think that's what the "overlapping" referred to, namely that multiple processors could nominate the same index. But, as I showed in the source snippet I quoted, there are cases where the index sets do not cover the index space at all but are only subsets.

**Comment by kronbichler** [comment]
Right, there is no restriction as long as one does not expect to access all the elements - it was actually me writing the code you point to :-). I will adjust the code.
