### ISSUE TITLE
Compiler Warnings during Built with OpenMPI 3.1.1

### ISSUE THREAD

**Issue by BenBrands** [dealii/dealii#6993]
When I built dealii using OpenMPI 3.1.1 lots of compiler warnings are put to the screen. With OpenMPI 3.1.0 I did not see that warnings. 

Just a short quote using Verbose:
`
[  4%] Building CXX object source/numerics/CMakeFiles/obj_numerics_release.dir/data_out_dof_data_codim.cc.o
cd /home/benjamin/dealii/build/source/numerics && /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/bin/mpic++  -DBOOST_NO_AUTO_PTR -I/home/benjamin/dealii/build/source/numerics -I/home/benjamin/dealii/build/include -I/home/benjamin/dealii/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/intel-mkl-2018.2.199-q2dcavqzz5kaecryinlif6ushw6kzyow/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/intel-tbb-2018.4-j7to3qqciwqzvsrzyya7v4wbz6pq2avs/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/zlib-1.2.11-av3mmgf66zwic2i34n7o2oxtp4quy6pi/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.67.0-l7tvj2utfa22pdivules7o7id7xs6kuq/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/metis-5.1.0-hfiksoz6zo2wxecsqmlyroa5egkqib4o/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/suite-sparse-5.2.0-nnp6xpnaxmqgw7zcfmfcyipmcnxbubja/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/adol-c-develop-omjty56hedqyctgkyppbd5cgszby3fmv/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/assimp-4.0.1-kqyhzkeric76whphkqo6vz7yjnvo75um/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/gsl-2.4-gj62rpwzeksjj4gdl36wznyfhiqzfgkt/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/hdf5-1.10.2-z7ojxgmneypxgqqiug4h7rsfukiyxhaz/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/muparser-2.2.5-iwitcknspidpa2cphbv2hczs7go7jzom/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/nanoflann-1.2.3-hmahtz2r5hchoemwi4z66nbctrhdh6tc/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/netcdf-cxx-4.2-czkev5gprqpo6mzv4yx5wbebegsdk5fw/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/netcdf-4.6.1-hlohi7rhbuuyvzfntz4o6exmwfzdtlwg/include -isystem /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/sundials-3.1.1-jip6oklogokk367peaaynnvxyzeobkqm/include  -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wsuggest-override -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++17 -march=native -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -O3 -o CMakeFiles/obj_numerics_release.dir/data_out_dof_data_codim.cc.o -c /home/benjamin/dealii/source/numerics/data_out_dof_data_codim.cc
In file included from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/mpicxx.h:226:0,
                 from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/mpi.h:2684,
                 from /home/benjamin/dealii/build/include/deal.II/base/config.h:405,
                 from /home/benjamin/dealii/include/deal.II/lac/block_vector.h:20,
                 from /home/benjamin/dealii/source/numerics/data_out_dof_data_codim.cc:16:
/home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/intracomm.h:101:22: warning: ‘virtual MPI::Intracomm& MPI::Intracomm::Clone() const’ can be marked override [-Wsuggest-override]
   virtual Intracomm& Clone() const;
                      ^~~~~
In file included from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/mpicxx.h:227:0,
                 from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/mpi.h:2684,
                 from /home/benjamin/dealii/build/include/deal.II/base/config.h:405,
                 from /home/benjamin/dealii/include/deal.II/lac/block_vector.h:20,
                 from /home/benjamin/dealii/source/numerics/data_out_dof_data_codim.cc:16:
/home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/topology.h:65:21: warning: ‘virtual MPI::Cartcomm& MPI::Cartcomm::Clone() const’ can be marked override [-Wsuggest-override]
   virtual Cartcomm& Clone() const;
                     ^~~~~
/home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/topology.h:143:22: warning: ‘virtual MPI::Graphcomm& MPI::Graphcomm::Clone() const’ can be marked override [-Wsuggest-override]
   virtual Graphcomm& Clone() const;
                      ^~~~~
In file included from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/mpicxx.h:228:0,
                 from /home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/mpi.h:2684,
                 from /home/benjamin/dealii/build/include/deal.II/base/config.h:405,
                 from /home/benjamin/dealii/include/deal.II/lac/block_vector.h:20,
                 from /home/benjamin/dealii/source/numerics/data_out_dof_data_codim.cc:16:
/home/benjamin/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.1-j4lnlmpxg22hrcgpugtxlxpflynebi2u/include/openmpi/ompi/mpi/cxx/intercomm.h:75:22: warning: ‘virtual MPI::Intercomm& MPI::Intercomm::Clone() const’ can be marked override [-Wsuggest-override]
   virtual Intercomm& Clone() const;
`

**Comment by Rombur** [comment]
That's fine. You get this warnings because you have the flag `-Wsuggest-override` so the compiler suggest you to use `override` in these places. However, all these places are in openmpi so there is nothing we can do about it.

**Comment by drwells** [comment]
These are warnings from inside openmpi itself, so we cannot fix them.

If you want to silence the error for now I suggest adding `-Wno-suggest-override` to `CMAKE_CXX_FLAGS`.

We should silence these warnings by using `isystem` to include the MPI headers, even if they are not installed in a standard location.

**Comment by bangerth** [comment]
Yes, it's the compiler wrapper that should be using `-isystem`. There's even less we can do about that...

**Comment by drwells** [comment]
Unless I am mistaken (its been a month) this is an issue with where MPI is installed and how the MPI compiler wrappers set up their flags. Since there is no way to fix this I am going to close it. If anyone can come up with some concrete action we can take then please post here.
