### ISSUE TITLE
Address comments in #6994

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#6999]
It would be good for us to attend to the few remaining comments listed in #6994.

**Comment by tjhei** [comment]
I don't think the test output is great. I cropped out the 2d data, put into a .vtk, and opened in Paraview. There is no data field and the one cell doesn't show any higher order boundaries (just a gray square).
I am also confused that the file ends with ``POINT_DATA 125`` without any data following it.
I don't have time right now, but we should add a test that actually outputs curved data on a curved cell...

**Comment by kronbichler** [comment]
I will do this. (I want to test this new feature myself, so I have an incentive here...)
