### ISSUE TITLE
GridGenerator::merge_triangulations with more than 2 triangulations to merge

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7007]
it's cumbersome to combine 4-5 triangulations with the current `merge_triangulation`. We should have a function which takes a `std::vector<Triangulation>` or `std:: initializer_list<Triangulation>` or alike to merge arbitrary number of triangulations specified by user. Internally it would of course call the same old `GridGenerator::merge_triangulation` to combine everything.

I think it should be something like
```
void 
GridGenerator::merge_triangulation(
    Triangulation &output, 
    const double tolerance, 
    Triangulation&&... inputs);
```
which can be called as
```
GridGenerator::merge_triangulation(out,1e-6,in1,in2,in3);
```

(see [this stackoverflow](https://stackoverflow.com/a/31453771/888478) ).

**Comment by masterleinad** [comment]
I should have code for this already in some older project.
