### ISSUE TITLE
Use kdtree in find_active_cell_around_point() ?

### ISSUE THREAD

**Issue by islent** [dealii/dealii#7008]
We notice low performance in the function *find_active_cell_around_point()* where you use for-loops to find the adjacent cells and points, and the **time consuming** is unacceptable in dynamic simulations.

Some tests on **kdtree** method showed significant performance improvements, using *PCL* library, and dealii has its own ketree method.However we encountered tons of problems when implementing ketree in the source code of dealii, due to the complex class relationships and data structures.

This seems not a large problem to those who are familiar to dealii, and is actually a necessary optimization we expect in dealii library. And compiling dealii with CUDA exists even errors. We expect more performance improvements in future versions.

**Comment by davydden** [comment]
there is already a version of this function which uses `kdtree`, see https://www.dealii.org/developer/doxygen/deal.II/namespaceGridTools.html#a8091d0c6974b0db667dc6158307feb1e and https://www.dealii.org/developer/doxygen/deal.II/classGridTools_1_1Cache.html

> And compiling dealii with CUDA exists even errors.

Please report those in a separate issue, it's unrelated to`find_active_cell_around_point`.

**Comment by davydden** [comment]
> Is dealii not suitable for this field, or we didn't play out its advantages?

I don't think anybody from principle developers are involved in galaxy simulations, but @tjhei @bangerth have tons of particles in convection in the Earth mantle. You might want to study their recent papers, for example 

```
@article{Gassmoeller2016,
	Author = {Gassmoeller, RENE and Heien, ERIC and Puckett, ELBRIDGE GERRY and Bangerth, WOLFGANG},
	Journal = {arXiv preprint arXiv:1612.03369},
	Title = {Flexible and scalable particle-in-cell methods for massively parallel computations},
	Year = {2016}}
```

and look at https://www.dealii.org/developer/doxygen/deal.II/classParticles_1_1ParticleHandler.html

I am closing this issue as

> Some tests on kdtree method showed significant performance improvements

is being answered, i think.

**Comment by Rombur** [comment]
> I hadn't noticed that the class cache has a kdtree member before. but the problem still exists:
we are developing a Poisson solver using dealii to do some galaxy dynamic simulations, which handles millions of particles, and the time cost is unbearable.

Have you tried to use `GridTools::Cache`? This should be pretty fast but you need nanoflann installed. If you don't use the cache, `find_active_cell_around_point()` will be pretty slow. My understanding is that PCL is based on FLANN while we are using nanoflann which is an optimized version of FLANN. So you should be able to get performance at least as good as what you get using PCL

**Comment by kronbichler** [comment]
> We expect more performance improvements in future versions.

To add a little perspective on this topic: We as a project of course strive to improve performance for our users, but we cannot make any definite promises. Many of us core developers work on other parts of the library and also in other projects - so do I, and I have done some high performance implementations in those sections of deal.II - but nobody in our project gets paid to deliver work upon service requests like yours. We instead try to encourage our users to contribute improvements to the library, like solutions to the pressing need you seem to be facing. At times, or actually pretty often, someone of the more experienced developers actually does get excited about such a topic - be it interesting from a research point of view, some altruistic code excitement or simply the need for the same improvement.

That said, we would be happy to guide you through the code if you still observe bottlenecks, ideally with some additional specification of what exactly gets slow and about ideas of what to improve, like possible problems with the solutions sketched by @Rombur or @davydden.

**Comment by bangerth** [comment]
As far as particles in particular are concerned, @davydden already pointed out the correct preprint. We have done computations with billions of particles -- but we've also spent a year or more of work on optimizing the data structures for this case. In particular, you can't use `GridTools::find_active_cell_around_point()`, but have to do things differently -- the preprint explains how to do that.

**Comment by islent** [comment]
Thank you all for reply.

Now I have more confidence in dealii, and many of your ideas are extremely instructive !

We would focus more on the advanced algorithms in the preprint .

Thanks again.
