### ISSUE TITLE
Update tutorials about higher order VTK output

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7021]
In #7004, we had a conversation that it would be useful to update the discussion of step-53 (and possibly other places) with a link to the fact that we can now output higher order cells and data in VTK. We should do this.

@agrayver offered kindly to produce an updated figure for this. That would be useful since I'm a Visit guy and Visit doesn't seem to support higher order cells yet :-( So, @agrayver, if you have a figure, simply attach it to a comment to this issue here -- thank you!

**Comment by bangerth** [comment]
I think another place worth revisiting would be step-10/11 which introduce higher order mappings.

**Comment by Rombur** [comment]
@bangerth 
I haven't tried yet but I found this (https://github.com/CEED/Laghos/issues/10#issuecomment-363780907):
```
Regarding the second issue, you need to use the Multires control in VisIt to visualize high-order data. 
This is under Operators / Selection and you increase it to get better curvature representation. For 
physics fields, this is sufficient to see the variation in each element. To see the high-order curved mesh:

    Plot Subset / blocks
    Double-click on the plot and select the Wireframe option.
    Select Operators / Selection / MultiresControl for this plot
    Open the little triangle next to Subset and double-click the MultiresControl
    Increase the multires resolution.
```

**Comment by Rombur** [comment]
Well it doesn't work. I think it's only for data output from mfem.

**Comment by agrayver** [comment]
> So, @agrayver, if you have a figure, simply attach it to a comment to this issue here -- thank you!

Here is a series of images, which show the effect of varying mapping order as applied to a triangulation with an attached ChartManifold. The topography on the top is described by a variant of exponential function exp(-x^2 - y^2).  Obviously, the meshes are saved using the new high-order VTK flag. 

Mapping degree = 1:
![mapping_p 1](https://user-images.githubusercontent.com/8438035/43662758-3aa5244a-9767-11e8-89bf-55de31896dab.png)

Mapping degree = 2:
![mapping_p 2](https://user-images.githubusercontent.com/8438035/43662812-6db6d2f2-9767-11e8-873f-4fbdfb199873.png)

Mapping degree 4:
![mapping_p 4](https://user-images.githubusercontent.com/8438035/43662830-83183bfe-9767-11e8-8473-ab147ba7b2af.png)

Mapping degree 6:
![mapping_p 6](https://user-images.githubusercontent.com/8438035/43662839-88b8ffbc-9767-11e8-9ec1-a23d3baf3f93.png)

Let me know if this is what you need.

**Comment by bangerth** [comment]
Yes, this should do -- thanks!

I'm going to be out for the next week but hope to get back to this sometime after that!

**Comment by kronbichler** [comment]
Unfortunately I think all our resources are tied in other places now before the release, so I think we will update/upload these pictures for the 9.2 release.

**Comment by kronbichler** [comment]
Note that I also plan to add a high-order VTK picture in step-65 via #8058, further helping the documentation of this excellent addition.

**Comment by agrayver** [comment]
@bangerth any news?

Since I was involved in adding this functionality, I am willing to update at least step-53 with the high-order meshes. It makes sense to do this before I implement step-53 in python as a part of #9015 

Regarding other steps:
step-10: not sure this step will benefit from the new high-order output. Images there deliver the message pretty well. Perhaps just a mention of the other possibilities? 
step-11: Adding graphical output with high-order meshes will be beneficial here.

**Comment by kronbichler** [comment]
Since you have been active in the issue #9015 where some good progress has been made, I guess we are close for step-53, given that we already have some pictures as listed above. step-10 is fine as it is; step-11 might benefit from a picture but should be straight-forward. Leaving the 9.2 release milestone for now despite the release only 2 months away.

**Comment by kronbichler** [comment]
Now that #9694 is (almost) done, we are only left with step-53. @bangerth how do you want us to proceed?

**Comment by bangerth** [comment]
Let's leave it at that. I think we've got this covered now!
