### ISSUE TITLE
Document steps to best visualize higher-order output in Paraview

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7023]
As was publicly demonstrated by me in #7006, the steps required to get the best visualisation of the higher order output in Paraview is perhaps not quite so easily understandable. The settings needed to get a smooth representation of higher order elements is hidden. Admittedly I didn't look at Paraview's documentation to find out how to do this, but then again I don't think that many of our users would do so either. 

We should document how to do this in either the Wiki or somewhere in the code docs. A section in the wiki would be most appropriate, as we can then show the steps with screenshots of paraview and, in this way, also show the difference between the default and the properly smoothed representations.

**Comment by davydden** [comment]
me and @luca-heltai now spent half an hour trying to locate 

> 'Nonlinear Subdivision level' property

as shown by Martin @kronbichler in https://github.com/dealii/dealii/pull/7006#issuecomment-409952433 . But it's not there in our Paraview... I am absolutely puzzled how to visualize it properly. We should definitely document it somewhere...

**Comment by jppelteret** [comment]
Or you can click the gear next to the search bar, which exposes all advanced properties.

**Comment by davydden** [comment]
@jppelteret 

> Or you can click the gear next to the search bar, which exposes all advanced properties.

thanks for clarification, we will give it a try tomorrow!

p.s. @luca-heltai FYI.

**Comment by luca-heltai** [comment]
> Or you can click the gear next to the search bar, which exposes all advanced properties.

This actually worked for me!

**Comment by kronbichler** [comment]
Unfortunately this is out of reach for the 9.1 release. This is related to #7021.

**Comment by agrayver** [comment]
I have created a wiki page: https://github.com/dealii/dealii/wiki/Notes-on-visualizing-high-order-output

Let me know what you think (@bangerth probably of interest...).

This is in preparation for #7021

**Comment by jppelteret** [comment]
@agrayver Sorry for taking some time to reply to you. Yes, that's great. Thanks a lot for adding the wiki entry!

**Comment by bangerth** [comment]
Thanks indeed! Is there a place where we should link to the wiki page?

**Comment by agrayver** [comment]
> Is there a place where we should link to the wiki page?

Several, I would say:
- Documentation of the DataOut::build_patches method
- step-65 and step-53 (once #7021 is addressed)
