### ISSUE TITLE
Dead link in online documentation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7040]
The [technical reports](http://www.dealii.org/reports.html) link on the [online documentation](https://www.dealii.org/developer/index.html) does not seem to work anymore :-(

**Comment by jppelteret** [comment]
But I have just noticed that the link in the side bar works. Strange...

**Comment by bangerth** [comment]
@drwells -- the link still doesn't seem to work for me.

**Comment by drwells** [comment]
It was worth a try. I'll take another look.

**Comment by tjhei** [comment]
1. the link works for me.
2. I didn't know this page existed.

Maybe we should merge this with publications.html?

**Comment by bangerth** [comment]
I think there are good things on that page, but we should not be using frames and, maybe, run this page through doxygen somehow so that one can link to it.

**Comment by bangerth** [comment]
#7850 gets rid of the frames craziness from the 1990s.
