### ISSUE TITLE
improvement to periodic BC

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7041]
A colleague of mine who use PBC says the following is not yet implemented (I have not checked it myself, just want to document the issue. If it's not an issue anymore, we can close it):

- [ ] there is no extra smoothing for Triangulation to make sure we have 1-level difference across periodic faces
- [x] hanging node constraints seem to be unaware of periodic faces. So you actually need to have same refinement level for them to work. That exactly https://github.com/dealii/dealii/issues/5574 and for that one should use `make_periodicity_constraints`. Still, we might actually combine the two.

**Comment by masterleinad** [comment]
At least for `parallel::distributed::Triangulation` [`add_periodicity`](https://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1Triangulation.html#aa7b797070e5443a18f03a4a7f0267453) makes sure that there is at maximum one level difference between periodic boundaries.

**Comment by jppelteret** [comment]
Have they called [`Triangulation::add_periodicity()`](https://www.dealii.org/developer/doxygen/deal.II/classTriangulation.html#adbf04756b28dae69194870812acaf941)? A quick skim through [`step-45`](https://dealii.org/9.0.0/doxygen/deal.II/step_45.html) indicates that nothing more is required in order to just uneven adaptive refinement to work.

**Comment by jppelteret** [comment]
@masterleinad beat me by 12 seconds... :-P

**Comment by davydden** [comment]
i asked my colleague to create MWE, it seems that we does both `make_periodicity_constraints` and `add_periodicity`.

**Comment by jppelteret** [comment]
Looking through my own code (non-distributed `Tria`), I guess I probably ran into the same problem and enforced the same refinement level for periodic neighbours. With the MWE we can probably come up with a decent fix for this issue.

**Comment by masterleinad** [comment]
After calling `add_periodicity` we know the periodic neighbor for all the relevant faces. Hence, we would just need to flag these cells additionally in the loops for `refinement_and_coarsening`.

**Comment by davydden** [comment]
we also have this old issue, which might be relevant https://github.com/dealii/dealii/issues/3240

**Comment by davydden** [comment]
here is MWE from my colleague:
```
#include <deal.II/base/geometry_info.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/grid/grid_tools.h>

int main (int argc, char *argv[]) {

    try {

        using namespace dealii;

        double left  = -1.;
        double right =  1.;

        Triangulation<2> tria;

        GridGenerator::hyper_cube(tria, left, right, true);

        // setup periodic boundary conditions
        std::vector<GridTools::PeriodicFacePair<typename Triangulation<2>::cell_iterator>> periodicity_vector;

        // for the hypercube faces
        unsigned int id1 = 0; // id of the left boundary
        unsigned int id2 = 1; // id of the right boundary boundary
        GridTools::collect_periodic_faces(tria, id1, id2, /*x-direction*/0, periodicity_vector);

        tria.add_periodicity(periodicity_vector);

        std::cout << "number of periodic face pairs   " << periodicity_vector.size() << std::endl;

        const unsigned int n_refinements = 5;
        double tolerance = 1e-3;

        for (unsigned int n = 0; n < n_refinements; ++n)
        {
            auto cell = tria.begin_active();
            auto endc = tria.end();

            for (; cell != endc; ++cell)
                if (cell->center()[0] > -tolerance)
                    cell->set_refine_flag ();

            tria.execute_coarsening_and_refinement();
        }

        // Let's check how many cells have a periodic neighbor.
        // After refinement, there are 4 cells and on the right hand side
        // and 32 cell on the left hand side of the cube, i.e. 36 cell should
        // have a periodic neighbor.
        unsigned int count = 0;

        auto cell = tria.begin_active();
        auto endc = tria.end();

        for (; cell != endc; ++cell)
            for (unsigned int f = 0; f < GeometryInfo<2>::faces_per_cell; ++f)
                if (cell->has_periodic_neighbor(f))
                    ++count;

        std::cout <<  "Number of cells with periodic neighbor  " << count << std::endl;

        std::ofstream out ("hyper_cube.eps");
        GridOut grid_out;
        grid_out.write_eps (tria, out);

    }
    catch (std::exception &exec) {

        std::cout << std::flush;

        std::cerr << "\n\n------------------------------------------------\n"
                  << "Exception thrown :\n" << exec.what() << std::endl
                  << "Aborting!\n"
                  << "----------------------------------------------------" << std::endl;

        return 1;
    }
    catch (...)
    {
        std::cout << std::flush;

        std::cerr << "\n\n------------------------------------------------\n"
                  << "Unknown exception!\n"
                  << "Aborting!\n"
                  << "----------------------------------------------------" << std::endl;
        return 1;
    }


    return 0;
}
```
which reports
```
number of periodic face pairs   1
Number of cells with periodic neighbor  36
```
with the mesh having more than 1 refinement level across the periodic boundaries (left-right):
![hyper_cube](https://user-images.githubusercontent.com/8023934/43768281-460a1b10-9a37-11e8-89cb-5b120064d085.jpg)

**Comment by masterleinad** [comment]
What's the name of your colleague?

**Comment by Rombur** [comment]
> What's the name of your colleague?

You are going to take him out? That's how you plan to fix the bug?

**Comment by davydden** [comment]
He’s aware that I created this issue and posted the code. Daniel, you most likely saw him while you were here, but I don’t recall if you guys chatted or not

**Comment by masterleinad** [comment]
I just 

> You are going to take him out? That's how you plan to fix the bug?

That would be one possibility, but the issue would probably remain. :wink:

I just want to include the name in the PR.

**Comment by bangerth** [comment]
The mesh smoothing code was written (long) before periodic boundaries. I'm totally willing to believe that what we ought to do is simply to change all calls in the smoothing routine from `cell->neighbor(...)` to `cell->neighbor_or_periodic_neighbor(...)`.

**Comment by masterleinad** [comment]
Yes, this exactly what I am doing right now. Just fighting corner cases...
