### ISSUE TITLE
Missing manifold in `GridGenerator::concentric_hyper_shells`?

### ISSUE THREAD

**Issue by Jie-Cheng** [dealii/dealii#7056]
Here is the grid I got by calling `GridGenerator::concentric_hyper_shells(triangulation, Point<2>(), 1.0, 2.0, 5u, 2.0)`. It looks like some manifold is missing in this function.
![grid](https://user-images.githubusercontent.com/12647461/44039383-f8bf500a-9ee6-11e8-8575-f0ad2c034b87.png)

**Comment by jppelteret** [comment]
What happens if you refine the grid using global refinement?

**Comment by jppelteret** [comment]
If global refinement doesn't show that there are manifolds attached to the boundaries then can you please post a minimal working example here to reproduce your test case. Thanks!

**Comment by drwells** [comment]
How did you generate that picture? Did you use the sample program in the documentation of that function?

**Comment by Jie-Cheng** [comment]
This is the code I used, global refinement doesn't show manifold.
```
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>

#include <iostream>
#include <fstream>
#include <cmath>

using namespace dealii;

int main()
{
  Triangulation<2> triangulation;
  GridGenerator::concentric_hyper_shells(triangulation,
                                         Point<2>(),
                                         1.0,
                                         2.0,
                                         5u,
                                         2.0);
  triangulation.refine_global(1);
  std::ofstream out("grid-1.eps");
  GridOut       grid_out;
  grid_out.write_eps(triangulation, out);
  std::cout << "Grid written to grid-1.eps" << std::endl;
}
```

**Comment by drwells** [comment]
Yes.

**Comment by Jie-Cheng** [comment]
Thanks!
