### ISSUE TITLE
Replace Threads::Mutex by std::mutex

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7103]
I've been spending far too much time on this already, and before I go even deeper into this rabbit hole, I think I wanted to see what people think.

I want to replace `Threads::Mutex` by `std::mutex` now that we can use it. The issue is that `std::mutex` cannot be copied: it's copy constructor is `=delete`d. On the other hand, `Threads::Mutex` has a copy constructor that simply doesn't copy any state. The problem is that we have *lots* of classes that have default copy constructors and use a mutex to guard some `mutable` variable. Examples are the polynomial classes, and the finite element classes. This used to work: the default copy constructor of these classes calls the default copy constructor of `Threads::Mutex`, which simply sets up a new mutex. But when I replace that by `std::mutex`, the fact that the copy constructor of `std::mutex` is deleted now also implicitly deletes the copy constructor of surrounding classes. This forces me to write lots of copy constructors by hand that simply copy all members except the mutex.

I can do that, but it has turned out to be a substantially longer thing that I really wanted it to be. What should we do? Just abandon the issue and stick with what we have?

**Comment by masterleinad** [comment]
Isn't `Threads::Mutex` already just a wrapper around `std::mutex` to allow copying? 
If you want to be able to use `Threads::Mutex` in place of a `std::mutex`, we could just derive publically from it instead.

**Comment by tamiko** [comment]
@bangerth What about we minimize the interface in `Mutex` to a skeleton? Something like:

```
#include <mutex>

class Mutex : public std::mutex
{
public:
  Wrapper() = default;

  Mutex(const Mutex &)
    : std::mutex()
  {
    //do nothing, default initialize std::mutex
  }
};


int main()
{
  Mutex m1;
  Mutex m2(m1);

  std::unique_lock<Mutex> t(m2);
}
```

We can do this in the existing class and simply depcrecate the current member class and methods.

**Comment by bangerth** [comment]
Yes, I think that is the right approach. I really don't have any appetite to get rid of the class altogether -- it is a giant headache, and requires us to re-add constructors that are currently `=default` and totally fine that way. I think the semantics of `std::mutex` are not suited to them being member variables guarding other member variables. I wished the standard had a different class for that purpose.

**Comment by bangerth** [comment]
Let's abandon this. I like the semantics of our class in the context in which it is used as a member variable.
