### ISSUE TITLE
Make FindADOLC.cmake more robust

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7116]
https://github.com/dealii/dealii/pull/6976#discussion_r212696526 refers.

Use
```
 # *define +USE_ADTL_REFCOUNTING +1
```
so that the number of spaces doesn't matter. Maybe its also possible to make detection of the trailing `1` more robust, so that it catches a `1`, `true` or no value (just that the `USE_ADTL_REFCOUNTING` macro is defined.

**Comment by kronbichler** [comment]
Any progress on this @jppelteret? If not, I suggest we postpone the target milestone.

**Comment by jppelteret** [comment]
This is relatively unimportant. I've postponed it for now.

**Comment by tamiko** [comment]
Resolved in #2d2a91386a1
