### ISSUE TITLE
Link to Mac OS "dealii-9.0.0.dmg" and PGP file (mirror) on web page fails (github works).

### ISSUE THREAD

**Issue by dpeschka** [dealii/dealii#7127]
Current target:

https://dealii.kyomu.43-1.org/downloads/dealii-9.0.0.dmg
https://dealii.kyomu.43-1.org/downloads/dealii-9.0.0.dmg.asc

Probably should be

https://dealii.kyomu.43-1.org/downloads/darwin-images/dealii-9.0.0.dmg
https://dealii.kyomu.43-1.org/downloads/darwin-images/dealii-9.0.0.dmg.asc

**Comment by bangerth** [comment]
Just to clarify, are you saying that the current links are broken?

**Comment by tamiko** [comment]
Yup. I went ahead and fixed the links on the homepage.
