### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by tcclevenger** [dealii/dealii#7146]
I was compiling the most recent dealii from github and I ran across the following error:

```
Scanning dependencies of target obj_sundials_debug
[ 68%] Building CXX object source/sundials/CMakeFiles/obj_sundials_debug.dir/arkode.cc.o
In file included from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/array_view.h:21:0,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/mpi.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/sundials/arkode.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/source/sundials/arkode.cc:19:
/home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/utilities.h: In function ‘constexpr unsigned int dealii::Utilities::pow(unsigned int, int)’:
**/home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/exceptions.h:1242:72: error: call to non-constexpr function** ‘void dealii::deal_II_exceptions::internals::issue_error_noreturn(dealii::deal_II_exceptions::internals::ExceptionHandling, const char*, int, const char*, const char*, const char*, ExceptionType) [with ExceptionType = dealii::StandardExceptions::ExcMessage]’
           ::dealii::deal_II_exceptions::internals::issue_error_noreturn( \
```
The flags that I am using are `DDEAL_II_WITH_P4EST,` `DDEAL_II_WITH_TRILINOS,` `DDEAL_II_WITH_PETSC,` `DDEAL_II_WITH_64BIT_INDICES,` and `DDEAL_II_WITH_MPI`

This was all on the master branch with no contributions of my own.

I'll include a screenshot from the terminal if it helps:
![dealii_compile_err](https://user-images.githubusercontent.com/11428698/45058039-72dbe800-b065-11e8-8706-ca2e972eb76d.png)

**Comment by drwells** [comment]
Uh oh

**Comment by drwells** [comment]
Hm, I cannot reproduce this. Could you post `summary.log` and `detailed.log` here?

**Comment by tcclevenger** [comment]
[summary.log](https://github.com/dealii/dealii/files/2350413/summary.log)
[detailed.log](https://github.com/dealii/dealii/files/2350414/detailed.log)

**Comment by masterleinad** [comment]
Does defining `issue_error_noreturn` as `constexpr void` help?

**Comment by tjhei** [comment]
I can reproduce the error here but I let @tcclevenger test out the constexpr idea.

**Comment by masterleinad** [comment]
I guess it is not inlined on your side for some reason while all the setups we test for do that.

**Comment by tcclevenger** [comment]
Adding constexpr did not work, but we now have a new error message:

[ 68%] Building CXX object source/sundials/CMakeFiles/obj_sundials_debug.dir/arkode.cc.o
In file included from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/tensor.h:26:0,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/symmetric_tensor.h:23,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/array_view.h:22,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/mpi.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/sundials/arkode.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/source/sundials/arkode.cc:19:
/home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/utilities.h: In function ‘constexpr unsigned int dealii::Utilities::pow(unsigned int, int)’:
/home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/utilities.h:379:3: **error: temporary of non-literal type ‘dealii::StandardExceptions::ExcMessage’ in a constant expression**
   }
   ^
In file included from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/array_view.h:21:0,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/mpi.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/include/deal.II/sundials/arkode.h:21,
                 from /home/tcclevenger/dealii/deal-git/dealii/source/sundials/arkode.cc:19:
/home/tcclevenger/dealii/deal-git/dealii/include/deal.II/base/exceptions.h:894:18: note: ‘dealii::StandardExceptions::ExcMessage’ is not literal because:
   DeclException1(ExcMessage, std::string, << arg1);

**Comment by kel85uk** [comment]
FWIW, I am also having the same issue. Below is my compile log along with the CMake logs.

[compile_log.log](https://github.com/dealii/dealii/files/2357136/compile_log.log)

[CMakeError.log](https://github.com/dealii/dealii/files/2357140/CMakeError.log)
[CMakeOutput.log](https://github.com/dealii/dealii/files/2357141/CMakeOutput.log)

**Comment by masterleinad** [comment]
Non-standard compliant compiler are annoying. An obvious workaround is to disable `C++14` support, of course. It seems that its time for another compiler check similar to https://godbolt.org/z/8VDSdG.

**Comment by tjhei** [comment]
that would disable c++14 for all gcc 5.x right? Should we disable this assert in pow() for now until we decide what to do?

**Comment by masterleinad** [comment]
No, I just wanted a feature check similar to the SPECIAL_MATH one.

**Comment by tjhei** [comment]
So that would be something like ``CAN_ASSERT_IN_CONSTEXPR`` and so we disable the assert with gcc 5.x?

**Comment by masterleinad** [comment]
Yes, exactly. It should cover all the cases where a non-`constexpr` function is called from a `constexpr` one if this is in a branch you don't hit in a `constexpr` context.
