### ISSUE TITLE
Using deal.II-9.0.0 Docker image with my C++ project seems to require C++14

### ISSUE THREAD

**Issue by alexanderzimmerman** [dealii/dealii#7148]
It appears to me that building my C++ project with deal.II using the Docker image at dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease requires C++14, when I expected it to require C++11.

Details:

I'm revisiting the deal.II version of a code I've been working on for the first time in a while; and I figured I'd upgrade to deal.II-9.0.0 before I dig back into it. Before, I was having Travis use the Docker image dealii/dealii:v8.5.0-gcc-mpi-fulldepscandi-debugrelease .

I see in [this announcement](https://groups.google.com/forum/#!topic/dealii/1iW2pMpZLnk) that C++11 is now required. This is fine for me, since my own project was already requiring C++11.

Using the 9.0.0 image, [this CI build of my project](https://travis-ci.org/geo-fluid-dynamics/phaseflow-dealii/builds/424836979?utm_source=github_status&utm_medium=notification) failed with something related to cxx14.

So, on a hunch, I just changed my CMakeLists.txt to require C++14. [This build](https://travis-ci.org/geo-fluid-dynamics/phaseflow-dealii/builds/424854556?utm_source=github_status&utm_medium=notification) passed.

**Comment by masterleinad** [comment]
It seems that `DEAL_II_CXX_14` is activated in the build you are using but the compiler doesn't support `C++14`. Building in a fresh directory should give you the right configuration (and disable `DEAL_II_CXX_14`).

**Comment by tjhei** [comment]
``dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease`` is very new (from yesterday) so I am not sure I messed up something. I just tested a deal.II example and it correctly gets compiled with ``--std=c++14``.

**Comment by alexanderzimmerman** [comment]
@tjhei , funny timing. Will it compile with --std=c++11?

**Comment by tjhei** [comment]
> @tjhei , funny timing. Will it compile with --std=c++11?

I don't understand your question. You do not have the choice of what c++ standard to pick if you link to deal.II. The autopilot in the cmake script should pick the same c++ standard that was used to compile deal.II (for this image it is c++14).

**Comment by tjhei** [comment]
can you try compiling and running one of the tutorial steps inside the container and report back? Also, as @masterleinad asks, is your project doing a clean build?

**Comment by alexanderzimmerman** [comment]
> The autopilot in the cmake script should pick the same c++ standard that was used to compile deal.II (for this image it is c++14).

This is what I was missing. 

For me it's fine to use C++14, and I already have this working.

Just an idea: Maybe consider building the Docker images with C++11 since this is the advertised standard for deal.II; but I'm sure you know whether or not this matters, and I'm satisfied having just brought it to your attention that some people might get confused by this.

As long as I'm here: Thanks for providing these great Docker images! I think it's quite amazing that I can upgrade to the latest deal.II after over a year and so quickly get my continuous integration process working again.

**Comment by tjhei** [comment]
> Just an idea: Maybe consider building the Docker images with C++11

I don't understand why you would want to do this. There should be no reason to pick an older c++ standard. Why do you specify the c++ standard in your CMakeLists.txt? If you omit this line, the standard that is detected by deal.II will be used (at least I hope so...).

**Comment by alexanderzimmerman** [comment]
Am I wrong that some people develop their projects with C++11 instead of C++14? The C++ standard moves pretty quickly and not everybody keeps up.

Anyway, my code works with C++14, so I'm happy.

**Comment by bangerth** [comment]
But C++11 is a subset of C++14 (with very few exceptions) and if you develop with C++11, then any C++14 compiler should compile your project just fine. So there is really no reason to explicitly only enable C++11 if a compiler understands C++14.

**Comment by alexanderzimmerman** [comment]
@bangerth, this is definitely true in my experience. I was developing with C++11, and C++14 worked immediately. So I'm convinced. Thanks to you and @tjhei for the explanations.

I'll go ahead and hit the "Close and comment" button.
