### ISSUE TITLE
move internal::VectorDataExchange to a base class which would serve as an interface

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7187]
I think it would be good to move most of matrix-free internal `VectorDataExchange` class (such as `update_ghost_values_start`, `update_ghost_values_finish`, etc) outside and make it an abstract interface vectors need to implement to be usable with matrix-free operators. Things like `MatrixFree<dim, Number>::DataAccessOnFaces` could also be part of the interface, and probably vectors should be responsible for all operations, including custom updates inside when `vector_face_access != dealii::MatrixFree<dim, Number>::DataAccessOnFaces::unspecified`. 
I think that would streamline implementation and make it easier test (currently you can't really test the interface outside of the whole matrix-free machinery).

@kronbichler would do you think?

EDIT: maybe even template magic with block/non-block vectors won't be needed as simply both will be responsible to provide certain operations.

**Comment by kronbichler** [comment]
I think that this is a good idea, yes.
