### ISSUE TITLE
openmpi 1.6.5 and const correctness

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#7225]
I can no longer compile deal.II on one of my machines that ships with an older openmpi version that is not const correct (all arguments lack ``const``). For example:
```
/ssd/deal-git/source/distributed/tria.cc:1984:47: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
           mpi_communicator, fname_fixed.c_str(), MPI_MODE_RDONLY, info, &fh);
```
(filename is ``char*`` instead of ``const char*`` in ``MPI_File_open``)
or
```
/ssd/deal-git/source/dofs/dof_handler_policy.cc:4950:58: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
```
(first argument of ``MPI_Allgather``, which should be const).

Any suggestions about what to do here? Before I submit a set of patches that casts away const, I thought I would ask...

**Comment by davydden** [comment]
> Before I submit a set of patches that casts away const, I thought I would ask...

I guess we need a configure test and then define something like `MPI_CONSTNESS` preprocessor variable which is empty for your version and `const` otherwise.

**Comment by drwells** [comment]
How many failures are there? Would it be reasonable to guard these with a version check?

**Comment by tjhei** [comment]
> How many failures are there?

I currently see about ~50 errors in total in tria.cc and dof_handler_policy.cc. Pretty much every call to one of the MPI_* functions.

This would add a ton of ugly const casts or ifdefs...

Interestingly, I think stuff would work without ``-fpermissive``...

**Comment by tjhei** [comment]
> openmpi 1.6.5 is five years old, do we really want to keep supporting it?

I don't think we have specified a "minimum version" anywhere so far, right? Yes, that machine is old but ubuntu 14.04 is not end of life until 2019. 

I could add a compile time test that will blacklist this version of MPI. 

Of course that means I can no longer use that machine until it is upgraded, which is annoying.

**Comment by bangerth** [comment]
I'm against obfuscating the code and instead just banning this old version. I'm slightly surprised that ubuntu 14.04 doesn't work for you -- I've used this for several years until a couple of months ago. Though I don't recall whether I used mpich or openmpi.

**Comment by masterleinad** [comment]
> Of course that means I can no longer use that machine until it is upgraded, which is annoying.

Of course, you could also just patch it on that machine. Rebasing should likely not result in merge conflicts.

**Comment by masterleinad** [comment]
> I don't think we have specified a "minimum version" anywhere so far, right?

We should do that for all the external packages we are using. Otherwise, we will have similar problems repeatedly.

**Comment by bangerth** [comment]
I'll add that the `const` in the specification of many MPI functions appears to have been introduced in MPI 3.0, released in 2012. My collection of MPI standards does not seem to show it in MPI 2.2.

**Comment by tjhei** [comment]
The weirdest thing is that an older build directory compiles without errors but a fresh build directory causes these errors. There is no difference in CXX flags just some dependencies. Weird.

**Comment by drwells** [comment]
I also find the sudden failure peculiar: IIRC I was using a machine with this version of open mpi two years ago when I added this workaround:

https://github.com/dealii/dealii/blob/master/include/deal.II/base/mpi.templates.h#L167

I believe everything else worked at the time, so there must be a way to fix this without removing absolutely every `const`.

**Comment by bangerth** [comment]
Bizarre. Have you looked at the MPI header files to see whether they contain the `const` in some for or other, possibly guarded by some `#define`?
