### ISSUE TITLE
Thread cleanup

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7228]
With native language support for threads we could think about

- [x] <s>replacing `ThreadLocalStorage` by `thread_local` qualified objects in the library and deprecate the class</s> (this doesn't work)
- [x] replace our `Mutex` and `ScopedLock` by `std::mutex` and `std::lock_guard`/`std::unique_lock` in the library and deprecate both classes
- [x] same for `std::condition_variable` and `ConditionVariable`
- [x] deprecate `PosixThreadBarrier`
- [x] deprecate almost everything under `Thread::*`, we have `std::thread::get_id`, `std::thread::hardware_concurrency`, etc.
- [x] clean up the cmake thread detection (almost all of this is obsolete)

**Comment by drwells** [comment]
We did not come to a conclusion regarding `std::mutex` vs `Mutex` earlier, since the former cannot be copied; see #7103 for the related discussion.

**Comment by bangerth** [comment]
We don't use the `PosixThreadBarrier` class anywhere, and one can imagine that none of our users are doing so either -- so we could just deprecate it without any replacement. But then it's a useful class for which C++ doesn't appear to have a replacement -- or do you happen to know whether there is one?

**Comment by masterleinad** [comment]
There is a stackoverflow question with various implementations https://stackoverflow.com/questions/24465533/implementing-boostbarrier-in-c11 and a TS https://en.cppreference.com/w/cpp/experimental/barrier.

**Comment by drwells** [comment]
@bangerth I think that the timer class also uses POSIX functionality (for counting CPU time), so we are not completely rid of it if we just remove this class.

**Comment by masterleinad** [comment]
We also have `posix_memalign` replaceable by `std::aligned_alloc` in C++17.

**Comment by bangerth** [comment]
OK, but that'll be a while until we can use that unconditionally :-)

**Comment by tamiko** [comment]
Almost there I would say :-)

**Comment by bangerth** [comment]
I read up on `thread_local`, see https://en.cppreference.com/w/cpp/language/storage_duration . The problem is that C++11 specifies that it can only be used for `static` member variables, but we most frequently use it for non-`static` member variables. So we can't quite get around using the class we currently have and which is based on ` tbb::enumerable_thread_specific` (https://www.threadingbuildingblocks.org/docs/help/reference/thread_local_storage/enumerable_thread_specific_cls.html).

There is also this piece of code that wants to access not only the current thread's data, but also that of others:
```
std::stack<std::string> &
LogStream::get_prefixes() const
{
#ifdef DEAL_II_WITH_THREADS
  bool                     exists         = false;
  std::stack<std::string> &local_prefixes = prefixes.get(exists);

  // If this is a new locally stored stack, copy the "blessed" prefixes
  // from the initial thread that created logstream.
  if (!exists)
    {
      const tbb::enumerable_thread_specific<std::stack<std::string>> &impl =
        prefixes.get_implementation();

      // The thread that created this LogStream object should be the first
      // in tbb's enumerable_thread_specific container.
      const tbb::enumerable_thread_specific<
        std::stack<std::string>>::const_iterator first_elem = impl.begin();

      if (first_elem != impl.end())
        {
          local_prefixes = *first_elem;
        }
    }

  return local_prefixes;
```

**Comment by bangerth** [comment]
Among the things that we can do of the list at the top of this issue, I think everything has been address. As mentioned, we can't do the thread-local thing. I will gladly let someone more skilled in cmake deal with the configuration of the threading model.

**Comment by tamiko** [comment]
@bangerth I agree. I missed the `static` requirement for `thread_local`, how disappointing.

**Comment by bangerth** [comment]
> @bangerth <https://github.com/bangerth> I agree. I missed the |static| 
> requirement for |thread_local|, how disappointing.

No kidding!

**Comment by bangerth** [comment]
@tamiko I think all that's left here is the cmake stuff you suggested -- which I'll happily leave to you.

**Comment by drwells** [comment]
The last part was done in #10324.
