### ISSUE TITLE
Compiling without threads broken

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#7245]
https://github.com/dealii/dealii/pull/7235 implies that we always use `std::mutex` and `std::lock_guard` even when compiling with `DEAL_II_WITH_THREADS=OFF` we either need to guard all of these cases or always compile with `THREADS` support.

**Comment by drwells** [comment]
I didn't think of it before, but a consequence of this is that we no longer use the placeholder classes that are no-ops; we really do lock and unlock when we compile without threads.

Is there appreciable overhead for this? I don't know if I have ever tried to measure it.

**Comment by masterleinad** [comment]
There is overhead https://stackoverflow.com/questions/32317370/avoid-cost-of-stdmutex-when-not-multi-threading but, of course, it is difficult to say how it compares with the cost of the rest of the function.

**Comment by masterleinad** [comment]
Let us actually just guard everything again and decide later what we really want to do.

**Comment by drwells** [comment]
I wasn't paying attention to this thread and wrote out most of the `#include` guards: it only took a few minutes to put preprocessor checks around each use of `lock_guard`. Do you already have something? If not I will post what I have.

**Comment by masterleinad** [comment]
See #7246. If you already did fixes and found something I overlooked, I am happy if you push it to that branch.

**Comment by drwells** [comment]
I think what you have is identical :+1:

**Comment by bangerth** [comment]
I think #7246 took the wrong approach. I had a follow-up patch (on my laptop at home, so not immediately accessible) that just removes the dummy classes altogether. In other words, we'd just always use the mutex classes, which is ok because now we unconditionally have access to them. Of course, there is a little bit of overhead to locking/unlocking, but I don't think it's a big deal -- and we also rarely work with threads disabled to begin with.

If I post this patch later on, can we undo what #7246 does?

**Comment by drwells** [comment]
As long as the performance overhead of using a lock in single-threaded mode is negligible I don't see any reason to lock anyway: it will make the code simpler. Do we have any measurements for these things?

**Comment by bangerth** [comment]
The link @masterleinad has posted shows 50ns per lock when there is no contention. I think that's acceptable and not worth worrying about.

**Comment by masterleinad** [comment]
> If I post this patch later on, can we undo what #7246 does?

Sure, as long as that also works with `THREADS=OFF`.

> The link @masterleinad has posted shows 50ns per lock when there is no contention. I think that's acceptable and not worth worrying about.

Yes, thinking about this a bit more that should be reasonable.
