### ISSUE TITLE
clang doesn't know -Wno-placement-new

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7262]
```
error: unknown warning option '-Wno-placement-new' [-Werror,-Wunknown-warning-option]
```

**Comment by yurivict** [comment]
Ah, this is just a check.

**Comment by bangerth** [comment]
Where do you get this? For every file you compile, or does this show up in some error log?

**Comment by bangerth** [comment]
OK. Yes, it's from testing whether the compiler understands the flag and the answer in this case is no, based on the error you found.
