### ISSUE TITLE
adol-c requirement in deal.ii ver 9.0.0

### ISSUE THREAD

**Issue by ncde** [dealii/dealii#7265]
Hello, 
I am new to deal.ii and trying to install it on my laptop. 
I try to install it with all the necessary libraries. 
The cmake files require ADOL-C version 2.6.4 but in the website of ADOL-C  2.6.3 is the latest version. 
(https://projects.coin-or.org/ADOL-C) 

Is this a typo?

**Comment by drwells** [comment]
@ncde Unfortunately, our ADOL-C bindings are only compatible with a future, presently unreleased version. The version requirement is correct.

**Comment by masterleinad** [comment]
Also, note that all the dependencies (except for `Boost`) are optional.
