### ISSUE TITLE
${DEAL_II_LINKER_FLAGS} not used in lapack symbol check

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7266]
I use ```DEAL_II_WITH_LAPACK```.

```
-- Found BLAS: /usr/local/lib/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Performing Test gfortran_LIBRARY
-- Performing Test gfortran_LIBRARY - Failed
-- Performing Test gcc_s_LIBRARY
-- Performing Test gcc_s_LIBRARY - Success
-- Performing Test gcc_LIBRARY
-- Performing Test gcc_LIBRARY - Success
-- Performing Test quadmath_LIBRARY
-- Performing Test quadmath_LIBRARY - Failed
-- Performing Test c_LIBRARY
-- Performing Test c_LIBRARY - Success
--   LAPACK_LIBRARIES: /usr/local/lib/libopenblas.so;/usr/local/lib/libopenblas.so;/usr/local/lib/libopenblas.so;m;gcc_s;gcc;m;gcc_s;gcc;c;gcc_s;gcc
--   LAPACK_LINKER_FLAGS: 
-- Found LAPACK
-- Performing Test DEAL_II_HAVE_FLAG_pthread
-- Performing Test DEAL_II_HAVE_FLAG_pthread - Failed
-- Performing Test LAPACK_SYMBOL_CHECK
-- Performing Test LAPACK_SYMBOL_CHECK - Failed
-- Could not find a sufficient BLAS/LAPACK installation: BLAS/LAPACK symbol check failed! Consult CMakeFiles/CMakeError.log for further information.
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):
  

  Could not find the lapack library!

  Could not find a sufficient BLAS/LAPACK installation:

  BLAS/LAPACK symbol check failed! This usually means that your BLAS/LAPACK
  installation is incomplete or the link line is broken.  Consult

    CMakeFiles/CMakeError.log
```

```CMakeError.log```: https://people.freebsd.org/~yuri/deal.II-lapack-problem-CMakeError.log

FreeBSD has ```gfortran.so``` and ```libgcc_s.so``` libraries in ```/usr/local/lib/gcc7```.
```LDFLAGS=-Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector -L/usr/local/lib```

```configure``` doesn't use these ```LDFLAGS``` and fails because it can't find these libs.

Please advise how to enable lapack. (IMO, if ```configure``` used ```LDFLAGS``` this problem would have likely gone away.)

**Comment by tamiko** [comment]
Regarding `LDFLAGS` - we do indeed respect the environment. Example:

```
$ LDFLAGS="-this-flag-does-not-exist" cmake .
...
CMake Error at cmake/setup_compiler_flags.cmake:83 (MESSAGE):
  

    Configuration error: Cannot compile with the user supplied flags:
      CXX flags (DEBUG):  
      LD flags  (DEBUG): -this-flag-does-not-exist 
      LIBRARIES (DEBUG): ;
    Please check the CMake variables
      DEAL_II_CXX_FLAGS, DEAL_II_CXX_FLAGS_DEBUG,
      DEAL_II_LINKER_FLAGS, DEAL_II_CXX_FLAGS_DEBUG
    and the environment variables CXXFLAGS, LDFLAGS.
```
Are you sure that you indeed export `LDFLAGS`? The contents of your environment variables should show up in `detailed.log` under "Base configuration". Alternatively, you can specify `-DDEAL_II_LINKER_FLAGS="..."` directly on the command line as well.

I hope that helps.

**Comment by yurivict** [comment]
```detailed.log``` isn't created at all for some reason.

Adding ```-DDEAL_II_LINKER_FLAGS:STRING="${LDFLAGS}"``` also doesn't help and lapack is still not found.

**Comment by tamiko** [comment]
@yurivict Disable lapack temporarily `-DWITH_LAPACK=OFF` and the file should be created. Are you sure that LDFLAGS is set in your environment?

**Comment by yurivict** [comment]
I just make sure that both ```configure``` and ```build``` phases have ```LDFLAGS``` in the environment, and lapack is still not found.

And ```DEAL_II_LINKER_FLAGS``` doesn't work either.

**Comment by tamiko** [comment]
Ah, there is a missing line in the configuration file. Can you please try the following:
 - add `-DLAPACK_LINKER_FLAGS="${LDFLAGS}"` to your cmake invocation
 - alternatively, try the following patch:
```
diff --git a/cmake/configure/configure_1_lapack.cmake b/cmake/configure/configure_1_lapack.cmake
index 8da6696b17..04487a6ed5 100644
--- a/cmake/configure/configure_1_lapack.cmake
+++ b/cmake/configure/configure_1_lapack.cmake
@@ -30,7 +30,7 @@ MACRO(FEATURE_LAPACK_FIND_EXTERNAL var)
     # Clear the test flags because the following test will use a C compiler
     #
     CLEAR_CMAKE_REQUIRED()
-    SET(CMAKE_REQUIRED_FLAGS "${LAPACK_LINKER_FLAGS}")
+    SET(CMAKE_REQUIRED_FLAGS "${DEAL_II_LINKER_FLAGS} ${LAPACK_LINKER_FLAGS}")
     SET(CMAKE_REQUIRED_LIBRARIES ${LAPACK_LIBRARIES})
     # Push -pthread as well:
     ENABLE_IF_SUPPORTED(CMAKE_REQUIRED_FLAGS "-pthread")
```

**Comment by tamiko** [comment]
This should convince the symbol check test to use the rpath flag and the undefined symbol issue should go away.

**Comment by yurivict** [comment]
```-DLAPACK_LINKER_FLAGS="${LDFLAGS}"``` helped to pass the ```configure``` stage.
I would just go with this for now, thank you!
