### ISSUE TITLE
package.py says that arpack depends on MPI, but configure says that it depends on lapack

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7267]
https://github.com/davydden/spack/blob/ca97d8c928eaa84eb25c3ecf2e4c86856458ac32/var/spack/repos/builtin/packages/dealii/package.py

configure passes when MPI is off, but not when LAPACK is off.

Which one is correct?

**Comment by davydden** [comment]
Can you please elaborate what is the problem with configure of deal.ii?

 Note that Spack is a separate project that some of deal.ii developers use.

**Comment by davydden** [comment]
also please check _README and installation instructions_ at https://www.dealii.org/developer/index.html

**Comment by yurivict** [comment]
> Can you please elaborate what is the problem with configure of deal.ii?

There is an obvious discrepancy. ARPACK seems to really depend on LAPACK, not MPI, unless there is also a bug in cmake scripts. I just wanted to confirm. In the FreeBSD port dependency between options should be specified.

**Comment by davydden** [comment]
arpack depends on LAPACK unconditionally, it may also depends on MPI in that case you build p-Arpack part of it. But that's NOT required, deal.II can distinguish between Arpack or Arpack + pArpack. 

p.s. A side note, I strongly recommend using arpack-ng, which have several important fixes like https://github.com/opencollab/arpack-ng/pull/85 and https://github.com/opencollab/arpack-ng/pull/21

**Comment by tamiko** [comment]
I think this question has been resolved let's close the issue for the time being. :smiley_cat:
