### ISSUE TITLE
ScaLAPACK vs SLATE

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7271]
This is more of a discussion question:

We've been adding ScaLAPACK interfaces recently. But ScaLAPACK is an evolutionary dead end: It's on the way to being replaced by the SLATE package, with quite a substantial effort going into the development of SLATE. I don't really have much of an opinion on this point, but it's probably worth discussing whether ScaLAPACK is where we want to go in the future.

@BenBrands, @davydden -- FYI.

**Comment by bangerth** [comment]
SLATE is here: https://icl.utk.edu/slate/
ScaLAPACK is here: http://www.netlib.org/scalapack/ The last major release was in 2011.

**Comment by bangerth** [comment]
Hm, that's not true for ScaLAPACK -- the page linked to is simply outdated. The last release was in 2017.

**Comment by davydden** [comment]
I have not heard of SLATE (will have a look), the advantage of ScaLAPACK is that it's provided by many libraries such as MKL or IBM's ESSL. So I think it's not completely dead, but the more the merrier ;-)

**Comment by Rombur** [comment]
> So I think it's not completely dead,

Not yet but the development team has moved to SLATE. The goal of SLATE is to replace ScaLAPACK.

**Comment by davydden** [comment]
> Not yet but the development team has moved to SLATE.

what I meant is that you have Intel MKL and IBM ESSL, and those guys probably have not moved to SLATE, as compared to `netlib-scalapack`  developers.

**Comment by BenBrands** [comment]
In my opinion it will be the reasonable step to switch to SLATE and abandon ScaLAPACK, but only when SLATE is mature and thoroughly tested. So far SLATE only offers some core BLAS and LAPACK functionalities as the project is WIP.
The advantages of SLATE are the nicer/more advanced API and that it enables you to run your code on heterogeneous CPU/GPU clusters, which ScaLAPACK totally lacks.
On the other hand ScaLAPACK is well tested and has given me reasonable scaling for solving eigenproblems on up to 1000 MPI processes (using INTEL MKL).

**Comment by bangerth** [comment]
All good points. Let's shelve this for now and come back to it at some unspecified point in the future. I just wanted to make sure we're all aware of the fact that ScaLAPACK is likely going to be at the end of its lifetime sometime soon.
