### ISSUE TITLE
hp::DoFHandler does not set active_fe_index on coarsened cells.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#7273]
The current implementation of the `hp::DoFHandler` does not set the `active_fe_index` on cells that have been coarsened [(see doc)](https://www.dealii.org/9.0.0/doxygen/deal.II/classhp_1_1DoFHandler.html).

However, we made that kind of automatism available in the `ActiveFEIndicesTransfer` class in case a `p::d::Triangulation` has been used. Here, we use the function `hp::FECollection::find_least_face_dominating_fe()` to determine the new `active_fe_index` of the parent cell.

I think we could easily apply this automatism on the `hp::DoFHandler` in general. I'll give it a try.

I'll leave this here as a board for discussions.

**Comment by bangerth** [comment]
I think that would be a nice extension. You'd only have to do that for the non-`p::d::` case, and in that case you know everything and could do it in the pre-refinement signal slot.

**Comment by marcfehling** [comment]
My current implementation idea is to look for the `coarsen_flags` on each level of the triangulation during `pre_refinement` and associate those `active_fe_indices` of cells to be coarsened with their parent cell, starting from the top level. We can then obtain the new `active_fe_index` for the parent cell using the `hp::FECollection::find_least_face_dominating_fe()` on its children indices and store the new ones across refinement. This way we don't have to store each child's `active_fe_index`.

In the `post_refinement` phase, we can ask if a cell has been coarsened comparing their possession of children before and after refinement (in the same way as if it was refined). We can then simply assign the previously calculated `active_fe_index`.

That's the best I could come up with, and I have a feeling that we can do it way easier. I may get a better idea over the weekend, but would follow this approach if not.

**Comment by bangerth** [comment]
Can't you already set the correct index in the pre-refinement phase?

**Comment by bangerth** [comment]
Or do you get an assertion that says you can't set active FE indices on non-active cells?

**Comment by marcfehling** [comment]
I cannot set the `active_fe_index` on cells that have children.
https://github.com/dealii/dealii/blob/360b94235fb2942bbe8ec2562327ccd8d7d9c6e4/include/deal.II/dofs/dof_accessor.templates.h#L3799

So I would rather prepare a vector for coarsened cells during pre-refinement that contains all active fe indices. In post-refinement, those cells can simply access those values.

**Comment by marcfehling** [comment]
I figured out a way by storing a `cell_iterator` object and an `unsigned_int` in a `std::map`, but I'm not sure if this will work with a `p::d::Tria`. Yes, we already have a class for that, namely `ActiveFEIndicesTransfer`, but those signals will be called anyway. My concern is that if ownerships of cells change, that we end up with invalid `cell_iterator` objects.

Is that the reason why you work with the `level` objects instead, since they store all information about the triangulation, even in the `p::d` case? This is the only conclusion I have right now that explains how the current implementation works. If so, I would stick to a `vector<vector<u_int>>` container storing fe indices on each level.

**Comment by bangerth** [comment]
On 10/08/2018 05:45 PM, marcfehling wrote:
> I figured out a way by storing a |cell_iterator| object and an |unsigned_int| 
> in a |std::map|, but I'm not sure if this will work with a |p::d::Tria|. Yes, 
> we already have a class for that, namely |ActiveFEIndicesTransfer|, but those 
> signals will be called anyway. My concern is that if ownerships of cells 
> change, that we end up with invalid |cell_iterator| objects.

Correct -- all of these iterators will be invalidated upon refinement of a 
p::d::T. But you can store the CellId that corresponds to the cell, and that 
is persistent and uniquely identifies the cell globally -- though of course 
the cell may no longer exist on the process that created the CellId.


> Is that the reason why you work with the |level| objects instead, since they 
> store all information about the triangulation, even in the |p::d| case? This 
> is the only conclusion I have right now that explains how the current 
> implementation works. If so, I would stick to a |vector<vector<u_int>>| 
> container storing fe indices on each level.

I don't recall. Remember also that the current implementation precedes all 
parallel triangulations.

**Comment by marcfehling** [comment]
I refactored the `pre_refinement` and `post_refinement` signals in such a way that almost any test of the testsuite finishes successfully -- all but one, namely `hp/solution_transfer`.

Again, I choose the `active_fe_index` of a coarsened cell depending on its children, using the `FECollection::find_least_face_dominating_fe_in_collection()` function. This works perfectly fine with `FECollection` objects consisting of `FE_Q` elements, but fails if it solely consists of `FE_DGQ` elements, which I first encountered in the above mentioned test. In this case, `FECollection::find_least_face_dominating_fe_in_collection()` returns an `invalid_unsigned_int`, that we obviously cannot assign to the parent cell.

Thus, this issue also exists for the current implementations of `p::d::ActiveFEIndexTransfer` and `p::d::SolutionTransfer`, in which we apply the same logic.

I don't have an idea right now how to solve this. :(

@davydden -- FYI

**Comment by marcfehling** [comment]
Or shall we just use the new function `find_face_dominating_fe_in_subset` in all of these cases? Since it starts with `FiniteElementDomination::either_element_can_dominate`, it would at least return some valid value, if I understood correctly. But the question still remains which index has to be returned in the case of `FE_DGQ` elements...

**Comment by marcfehling** [comment]
The algorithm works flawlessly now. I'll provide a pull request once #7337 is merged.

Have a peak at https://github.com/marcfehling/dealii/commit/e0b2a1e583b3607991d8ed3536f47208f6bd1b4b for a first impression. :)
