### ISSUE TITLE
Extend CellWeights class to parallel::shared::Triangulation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7281]
#7264 adds a new class `CellWeights` to deal with weighting individual cells by the number of DoFs for repartitioning. It was written for `parallel::distributed::Triangulation`, but it could easily be extended to `parallel::shared::Triangulation`.

**Comment by bangerth** [comment]
@marcfehling -- want to see what needs to be done?

**Comment by marcfehling** [comment]
Sure!

Do I just have too loosen the constraint on the type of Triangulation and add another `dynamic_cast` in the constructor?

**Comment by bangerth** [comment]
Yes, instead of storing a pointer to `p::d::Tria`, just store a pointer to `Tria` -- the former is derived from the latter, and so is `p::s::Tria`. You can then do without the `dynamic_cast` altogether, though it may be useful to have an assertion that the triangulation can in fact be cast to `parallel::Triangulation` (a baseclass of both `p::d::Tria` and `p::s::Tria`.
