### ISSUE TITLE
9.0.1 release

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7282]
I believe the current consensus is to do a bugfix release to improve compiler and external library support (e.g., #7260).

Here are the PRs we should duplicate on 9.0:
- [x] #6769 (see #7279)
- [x] #7156 (see #7269)
- [x] #6929 (see #7289)
- [x] #6658 (see #7291)
- [x] #7152 
- [x] #7270 (see #7286, @tamiko)

I erroneously added #6662 to the list earlier, but I think that that fixes a bug that was added after 9.0, so we should be able to skip it (we should run the test suite with complex petsc to be sure, though).

**Comment by masterleinad** [comment]
> we should run the test suite with complex petsc to be sure, though

Let me do that.

**Comment by masterleinad** [comment]
Compiling with `clang-6` and running the `petsc_complex` works fine for me. There are only some tests that fail due to missing `p4est` support. That does probably not have to be fixed for 9.0.1.

**Comment by drwells** [comment]
Lets skip #7152 then.

**Comment by drwells** [comment]
I reran the full test suite with the intel 17 and 16 compilers on a cluster (I did not install most dependencies, though). The only failing test that I see is the new `data_out_filter_02.debug` which is part of #6929.

**Comment by tamiko** [comment]
@drwells Running the full testsuite now on the dealii-9.0 release branch. Results should be complete in about 8h.

**Comment by tamiko** [comment]
Tester is also happy: http://cdash.kyomu.43-1.org/index.php?project=deal.II (the 64 bit container is currently broken, disregard that variant.)

**Comment by drwells** [comment]
I don't recall having so many problems with clang before. Did we?

**Comment by tamiko** [comment]
@drwells It basically boils down to 4 gmsh tests failing - that should now be resolved on the tester - as well as two step-36 and step-40 mpi variants failing. That has been a long standing issue and I suspect something in PETSc going wrong when calling mumps.

**Comment by tamiko** [comment]
Also, the mumps version in Gentoo is ancient. *ugh*.

**Comment by drwells** [comment]
Thats right; I had forgotten that SLEPc requires an LU solver at some point.

Is there anything else we need to do before we tag the release?

**Comment by tamiko** [comment]
@drwells What about tagging a release in the next 48h? (I am happy to do that) :-)

**Comment by masterleinad** [comment]
We should probably also include #6730.

**Comment by tamiko** [comment]
@masterleinad Correct me if I am wrong, but #6720 (which was reverted by #6730) was after the release branch was forked off, wasn't it?

**Comment by masterleinad** [comment]
Yes, what I meant to say that the release branch doesn't have `vectorization.cc` which appears to be a problem if `VectorizedArray::n_array_elements` is odr-used.

**Comment by davydden** [comment]
I have a few failing tests on 9.0 branch 
http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=5236 I will check details tomorrow

**Comment by tamiko** [comment]
@davydden That looks quite good. One is a timeout and the other 4 are failing gmsh tests (and are almost certainly bogus - last time those tests failed for me gmsh wasn't configured with lapack/blas support.).

**Comment by davydden** [comment]
I don’t think they bogus, looks like some incompatibility with GMSH version, I build with 4.0.0. Maybe the file format changed or alike.

**Comment by davydden** [comment]
Oh, and Gmsh 3.0.6 works perfectly fine 
http://cdash.kyomu.43-1.org/buildSummary.php?buildid=5220 Definitely not bogus! :-)

**Comment by masterleinad** [comment]
Do these tests pass on `master` with `Gmsh 4.0.0`?

**Comment by davydden** [comment]
> But this is really not relevant for the 9.0.1 release.

I agree, it's minor issue and should not hold `9.0.1` release. So, shall we go on and tag it? Looks like all the crucial fixes are in...

**Comment by bangerth** [comment]
So it!

**Comment by bangerth** [comment]
Err, *do* it!

**Comment by davydden** [comment]
> do it!

i certainly don't know how to tad, I guess we need to wait for @tamiko 😄

**Comment by tamiko** [comment]
- [ ] <b>*</b>   Nominate a "release officer" that is in charge of (almost all) of the following steps
- [ ] <b>1</b>   Create new changes file
- [ ] <b>1a</b>  Adjust doc/users/doxygen.html to link to the to-be-created TAG file.
- [ ] <b>11</b>  Create documentation and verify
- [ ] <b>11a</b> Check that .gitattributes is up to date. (Do quick tests work?)
- [ ] <b>12</b>  Push the button
    - Change VERSION to 9.0.1
    - Create a signed tag of exactly this commit
    - Push changes to github
- [ ] <b>13</b>  Create the tar files
    - Download the source tarball from github, verify that its contents is what we expect
    - Cryptographically sign it (detached, armored signature)
    - Create full offline_doc tarball and sign it
- [ ] <b>14a</b> Create a release on github and upload files (and detached signatures)
- [ ] <b>17a</b> Ask Luca for Mac packages
- [ ] <b>17b</b> Update dealii in [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py)
- [ ] <b>17c</b> Update dealii in [Candi](https://github.com/dealii/candi/blob/master/candi.cfg)
- [ ] <b>17d</b> Update dealii in [Gentoo Science overlay](https://gitweb.gentoo.org/proj/sci.git/tree/sci-libs/dealii)
- [ ] <b>17e</b> Update dealii in [Ubuntu/Debian](https://salsa.debian.org/science-team/deal.ii)
- [ ] <b>17f</b> Update dealii in [Archlinux AUR](https://aur.archlinux.org/packages/deal-ii/)
- [ ] <b>17g</b> Update dealii virtualbox images
- [ ] <b>18b</b> Adjust news.html in the deal.II homepage repo
- [ ] <b>19</b>  Announce the release via e-mail
- [ ] <b>19a</b> Send a note to the Facebook and Google+ accounts
- [ ] <b>19b</b> Update the deal.II wikipedia page
- [ ] <b>20</b>  Celebrate!

**Comment by tamiko** [comment]
@drwells @davydden A bit of updating is due :-)

**Comment by drwells** [comment]
I am heading out of town today, but I should have some time to update things on Saturday.

**Comment by koecher** [comment]
@tamiko I can not connect to my university network, thus I’m not able to test before Monday. But I put as first task. Thank you for the reminder.

**Comment by drwells** [comment]
I am still working on this.

A week ago Arch Linux switched some packages around and we now use openblas as the default BLAS. This caused the errors described in #2885 to return, even though we clearly add `libgslcblas.so` to the link interface.

**Comment by drwells** [comment]
The only workaround I could find was disabling `-Wl,--as-needed`.

**Comment by tamiko** [comment]
@drwells Where did you get the link errors? While linking the library, or while trying to link an executable? The fact that you had to disable `-Wl,--as-needed` indicates that some of the library dependencies of deal.II in AUR are "underlinked" [1]. This is bad.

[1] https://wiki.mageia.org/en/Underlinking_issues_in_packaging

**Comment by koecher** [comment]
@tamiko 17c is to be checked now. candi is updated and merged for deal.II v9.0.1

**Comment by tamiko** [comment]
On Tue, Oct 16, 2018, at 15:08 CDT, Uwe Köcher <notifications@github.com> wrote:

> @tamiko 17c is to be checked now. candi is updated and merged for deal.II v9.0.1

Very nice :-)
