### ISSUE TITLE
GridOut::write_vtk no longer useful

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#7296]
from 8.5.0 to 9.0.0 (I guess in a "let's remove code duplication effort") we made the `GridOut::write_vtk` no longer compatible with the `GridIn::read_vtk` function, i.e., now we use `DataOut::write_vtk`, which duplicates vertex information, making the final file useless if we want to read it back in.

VTK seems to be the only grid format where we could in principle store all the information required by deal.II (including manifold information, boundary, and material id information, and maybe even local refinement information).

I'd like to have these features at least in one grid format. Shall we choose VTK for this purpose?

**Comment by bangerth** [comment]
Ah, yes, that is awkward. Do you want to revert that patch? Can you identify which one it is?

**Comment by tjhei** [comment]
And we need a test that writes and reads back in to make sure it will work in the future.

**Comment by masterleinad** [comment]
Fixed in #7427.
