### ISSUE TITLE
Meta issue for deal.II 6th Users and Developers workshop.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#7297]
All issues and merge requests opened during the deal.II 6th Users and Developers workshop.

- #6945
- #6946
- #6947
- #6948
- #6964
- #6978 
- #6979
- #6980
- #6981 
- #6982

- #7010
- #6989
- #6988 
- #6986
- #6984
- #6977 
- #6976 
- #6975 
- #6974 
- #6971 
- #6968 
- #6967 
- #6966 
- #6965 
- #6962
- #6958
- #6957 
- #6955 
- #6953 
- #6952 
- #6951 
- #6950 
- #6949 
- #6944
- #6943

**Comment by davydden** [comment]
alternatively, next time we could add a dedicated label.
