### ISSUE TITLE
Tests: Changing the floating point environment in tests without setting FENV_ACCESS results in undefined behavior

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7318]
The following fails with clang:
```
#include <cfenv>
#include <cstdint>
#include <limits>
#include <vector>

int main()
{
  feenableexcept(FE_DIVBYZERO | FE_INVALID);

  const uint64_t max = std::numeric_limits<std::uint64_t>::max();
  const std::vector<long double> points = {0.7};
  volatile uint64_t i = (std::uint64_t)(points[0] * (long double)max);
}
```
In reference to #7313 #7312 

@bangerth Voila. Your proper bug report. :smile_cat:

**Comment by bangerth** [comment]
Too strange. Does it depend on the numeric values of `points[0]` and `max`?

There is nothing we can do about this other than file a bug report against clang. Anyone want to do that?

**Comment by tamiko** [comment]
@bangerth Yes, with points[0] == 0.2 no exception is thrown. If you lower max by 1 no exception either. I look at the assembly right now.

**Comment by tamiko** [comment]
That's a bit too much assembly for me today. Snippet:
```
uint64_t foo(long double l, uint64_t r)
  {
    return l * (long double)r;
  }
```
gcc creates
```
_Z3fooem:
        [...]
        movabsq $-9223372036854775808, %rdx
        xorq    %rdx, %rax
        popq    %rbp
        ret
```
And Clang:
```
_Z3fooem:
        [...]
        movabsq $-9223372036854775808, %rsi # imm = 0x8000000000000000
        xorq    %rsi, %rdi
        movq    -48(%rbp), %rsi
      > fxch    %st(1)
        fucompi %st(1)
        fstp    %st(0)
        cmovbq  %rsi, %rdi
        movq    %rdi, %rax
        popq    %rbp
        retq
```
The exception is thrown in the marked line (maybe the one after, if I misinterpreted the output of gdb).
When enabling any kind of optimization, clang happily removes this `%rdi` to `%rax` dance.

**Comment by tamiko** [comment]
LLVM IR:
```
; Function Attrs: noinline nounwind optnone uwtable
define dso_local i64 @_Z3fooem(x86_fp80, i64) #0 {
  %3 = alloca x86_fp80, align 16
  %4 = alloca i64, align 8
  store x86_fp80 %0, x86_fp80* %3, align 16
  store i64 %1, i64* %4, align 8
  %5 = load x86_fp80, x86_fp80* %3, align 16
  %6 = load i64, i64* %4, align 8
  %7 = uitofp i64 %6 to x86_fp80
  %8 = fmul x86_fp80 %5, %7
  %9 = fptoui x86_fp80 %8 to i64
  ret i64 %9
}
```
Looks innocent... @bangerth I will do a bug report after understanding this problem a bit more.

**Comment by tamiko** [comment]
So, I asked the wizards in #llvm@OFTC and I got the following response (about 30 seconds after posting):
<i>
tamiko: it's undefined behavior to run code in a non-default floating point
environment without using #pragma FENV_ACCESS ON. Unfortunately, clang does
not yet have complete support for that pragma, but it's work in progress.
</i>
[1] https://en.cppreference.com/w/cpp/numeric/fenv
[2] http://www.cplusplus.com/reference/cfenv/FENV_ACCESS/

@davydden So it was undefined behavior after all.

**Comment by tamiko** [comment]
Summary: Our current practice of enabling floating point exception in `tests.h` via `feenableexcept(FE_DIVBYZERO | FE_INVALID);` results strictly speaking in undefined behavior [1,2] as long as all relevant code isn't compiled with `#pragma STD FENV_ACCESS ON`.

Problem with this:
 - we cannot meaningfully compile <b>everything</b> (including external libraries) with `#pragma STD FENV_ACCESS ON`.
 - clang doesn't support the pragma
 - compilers seem to give us a sensible default behavior nevertheless (well, except this one instance...).

[1] https://en.cppreference.com/w/cpp/numeric/fenv
[2] http://www.cplusplus.com/reference/cfenv/FENV_ACCESS/

**Comment by bangerth** [comment]
That sounds like a cop-out. But since there's nothing we can do about it, I'd vote for closing the issue.

**Comment by tamiko** [comment]
@bangerth Let's keep this issue open as reference until we have sorted out clang-7 status (aka "the little rowdy"), looks like a lot of floating point exceptions in trilinos...

[1] http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=5214

**Comment by tamiko** [comment]
Looking at clang-7 again, these are _all_ floating point exceptions:
[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=5233

**Comment by bangerth** [comment]
OK, we can leave it open.

We can of course also disable floating point exceptions for clang. This has worked well for us with GCC, but if clang just can't do it (testable with a cmake test), then maybe we ought to disable it there.

**Comment by tamiko** [comment]
Given the fact that _all_ failing tests that clang-7 produced is due to "undefined behavior" because of this `FENV_ACCESS` business, I simply disabled floating point exceptions locally on the tester for clang tests.

:see_no_evil: :hear_no_evil: :speak_no_evil:
