### ISSUE TITLE
Cannot configure deal.II 9.0.0 with custom Boost on Windows

### ISSUE THREAD

**Issue by vdilecce** [dealii/dealii#7324]
I tried to configure deal.II 9.0.0 with a custom installation of Boost 1.66 (through CMake cache entry `-DBOOST_DIR`).

- On Linux (GCC 6.4) it worked.
- On Windows 10 (Visual Studio 2017 15.5), the `BOOST_SERIALIZATION_USABLE` test failed, so it configured with the bundled Boost 1.62 package as fallback.

In both cases, deal.II eventually built successfully. Here are some details about the Windows situation.

* CMake version: 3.11.4 (on both systems).

* Boost 1.66 build command:
   ```
   .\b2 --prefix="%MY_BOOST_PATH%" --build-dir=.\build --layout=versioned --with-filesystem --with-chrono --with-iostreams --with-serialization --with-thread toolset=msvc-14.1 variant=debug,release link=static architecture=x86 address-model=64 install
   ```
* deal.II 9.0.0 CMake command:
   ```
   cmake -G"Visual Studio 15 2017 Win64" -Thost=x64 -DCMAKE_INSTALL_PREFIX="%MY_DEALII_PATH%" -DBOOST_DIR="%MY_BOOST_PATH%"
   ```
Problems:

- Even though the find module does find Boost 1.66 and sets `BOOST_LIBRARIES` correctly with `debug` and `optimized` keywords, I found that in `cmake/configure/configure_2_boost.cmake`, when the `BOOST_SERIALIZATION_USABLE` test is run, variable `BOOST_LIBRARIES` contains no more `debug` and `optimized`, so **both** library variants are added to **all** MSVC configurations of project TestBoost:
   ```cmake
   # file cmake/configure/configure_2_boost.cmake (lines 174-188)
   EXECUTE_PROCESS(
     COMMAND ${CMAKE_COMMAND}
       -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
       -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
       "-DCMAKE_CXX_FLAGS=${DEAL_II_CXX_FLAGS}"
       "-DCMAKE_EXE_LINKER_FLAGS=${DEAL_II_LINKER_FLAGS}"
       "-DCMAKE_SHARED_LINKER_FLAGS=${DEAL_II_LINKER_FLAGS}"
       "-DBOOST_INCLUDE_DIRS=${BOOST_INCLUDE_DIRS}"
       "-DBOOST_LIBRARIES=${BOOST_LIBRARIES}" # <--- here "debug" and "optimized" have disappeared
       ${CMAKE_CURRENT_SOURCE_DIR}/cmake/configure/TestBoostBug
     WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/cmake/configure/TestBoostBug
     RESULT_VARIABLE _result
     OUTPUT_QUIET
     ERROR_QUIET
   )
   ```
   
- I managed to bypass this problem by doing the following:
  1. Edit file `configure_2_boost.cmake`
  2. Set manually the `-DBOOST_LIBRARIES` option for project TestBoost to the exact value of `BOOST_LIBRARIES` set by the find module
  3. Rerun CMake.

- Even after such workaround, target `derived` of MSVC solution `${CMAKE_CURRENT_BINARY_DIR}/cmake/configure/TestBoostBug/TestBoost.sln` failed because the linker "could not find `libboost_serialization-vc141-mt-gd-x32-1_66.lib`". However:
  * There is no such file in the Boost installation path
  * There is no such file in the Visual Studio project settings
  * This error occurs independently of the actual filename of the Boost libraries (i.e., Boost build options `--layout=versioned` or `--layout=tagged`, `link=shared` or `link=static` generate different filenames but the same error is triggered)

I tried the following:

- Rebuild Boost replacing `address-model=64` with `address-model=32,64`: that generated both x32 and x64 libraries so that I ended up having exactly `libboost_serialization-vc141-mt-gd-x32-1_66.lib` in my Boost installation path, and again set manually the `-DBOOST_LIBRARIES` option for project TestBoost in `configure_2_boost.cmake` to the x32 libraries (again, the find module set `BOOST_LIBRARIES` correctly to the x64 version). At this point target `derived` of solution TestBoost.sln built successfully, but target `test_boost` failed with two linking errors like:
   ```
   LNK2019	unresolved external symbol "private: void __thiscall polymorphic_derived2::serialize<class boost::archive::text_oarchive>(class boost::archive::text_oarchive &,unsigned int)" (??$serialize@Vtext_oarchive@archive@boost@@@polymorphic_derived2@@AAEXAAVtext_oarchive@archive@boost@@I@Z) referenced in function "public: static void __cdecl boost::serialization::access::serialize<class boost::archive::text_oarchive,class polymorphic_derived2>(class boost::archive::text_oarchive &,class polymorphic_derived2 &,unsigned int)" (??$serialize@Vtext_oarchive@archive@boost@@Vpolymorphic_derived2@@@access@serialization@boost@@SAXAAVtext_oarchive@archive@2@AAVpolymorphic_derived2@@I@Z)
   ```
- Use a custom installation of different Boost versions from 1.65 down to 1.62 (the same version as the one bundled with deal.II 9.0.0). None worked.

Might there be some Windows-specific problem in the `BOOST_SERIALIZATION_USABLE` test?

**Comment by tamiko** [comment]
We have never tested external boost support on Windows. Can you bypass the whole test by setting
`-DBOOST_SERIALIZATION_USABLE=yes` on the command line (or `BOOST_SERIALIZATION_USABLE` to a boolean and `true` in the graphical configuration tool)?

Does configuration finish with that? If yes, may we see the contents of `detailed.log`? (Do the listed libraries make sense?)

**Comment by vdilecce** [comment]
Thank you for the suggestion.

I tried running CMake with `-DBOOST_SERIALIZATION_USABLE=ON`. That indeed allowed to configure deal.II with an external installation of Boost; building also succeded.

(Just to make it clear, both deal.II configuring and building worked even without such option, it just ended up using the bundled Boost package since the Boost serialization test failed).

However, in `detailed.log` I see that `BOOST_LIBRARIES` still looks weird (all the rest is ok):
```
BOOST_LIBRARIES = 
C:/Program Files/Boost/boost-1.66.0/lib/libboost_serialization-vc141-mt-x64-1_66.lib;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_serialization-vc141-mt-gd-x64-1_66.lib;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_system-vc141-mt-x64-1_66.lib;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_system-vc141-mt-gd-x64-1_66.lib;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_thread-vc141-mt-x64-1_66.lib;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_thread-vc141-mt-gd-x64-1_66.lib;
optimized;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_chrono-vc141-mt-x64-1_66.lib;
debug;
C:/Program Files/Boost/boost-1.66.0/lib/libboost_chrono-vc141-mt-gd-x64-1_66.lib
```
The `debug` and `optimized` keywords are used only for the chrono library. Therefore, all variants for the other libraries are linked in all configurations (which is unwanted).

**Comment by tamiko** [comment]
> Thank you for the suggestion.
>
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_serialization-vc141-mt-gd-x64-1_66.lib;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_system-vc141-mt-x64-1_66.lib;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_system-vc141-mt-gd-x64-1_66.lib;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_thread-vc141-mt-x64-1_66.lib;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_thread-vc141-mt-gd-x64-1_66.lib;
> optimized;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_chrono-vc141-mt-x64-1_66.lib;
> debug;
> C:/Program Files/Boost/boost-1.66.0/lib/libboost_chrono-vc141-mt-gd-x64-1_66.lib
> ```

I will write a small fix later today that filters out the optimized and
debug libraries into their respective variable.

Best,
Matthias

**Comment by luca-heltai** [comment]
@tamiko ping?

**Comment by vdilecce** [comment]
I have some updates.

I still have the same problem with the following setup:

- Windows 10
- deal.II 9.2-pre
- Boost 1.70
- Visual Studio 2017 15.9
- CMake 3.15

but this time I made some progress.

Boost build command:
```
.\b2 --prefix="%MY_BOOST_PATH%" --build-dir=.\build --layout=versioned --with-filesystem --with-chrono --with-iostreams --with-serialization --with-thread --with-system toolset=msvc-14.1 variant=debug,release link=static architecture=x86 address-model=64 install
```

deal.II configure command:
```
cmake -G"Visual Studio 15 2017" -Ax64 -Thost=x64 -DDEAL_II_WITH_CXX14=ON -DDEAL_II_WITH_CXX17=OFF -DDEAL_II_ALLOW_AUTODETECTION=OFF -DBOOST_DIR="%BOOST170%" -DBoost_ARCHITECTURE=-x64
```

In file `cmake/configure/configure_2_boost.cmake (line 180 and after)` I did the following:
- Add `-Ax64`
- Add `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE`
- Replace `${BOOST_LIBRARIES}` with the correct list including many otherwise missing `debug` and `optimized` keywords

```cmake
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND}
    -Ax64
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    "-DCMAKE_CXX_FLAGS=${DEAL_II_CXX_FLAGS}"
    "-DCMAKE_EXE_LINKER_FLAGS=${DEAL_II_LINKER_FLAGS}"
    -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE
    "-DCMAKE_SHARED_LINKER_FLAGS=${DEAL_II_LINKER_FLAGS}"
    "-DBOOST_INCLUDE_DIRS=${BOOST_INCLUDE_DIRS}"
    "-DBOOST_LIBRARIES=optimized;C:/boost-1.70.0/lib/libboost_serialization-vc141-mt-x64-1_70.lib;debug;C:/boost-1.70.0/lib/libboost_serialization-vc141-mt-gd-x64-1_70.lib;optimized;C:/boost-1.70.0/lib/libboost_system-vc141-mt-x64-1_70.lib;debug;C:/boost-1.70.0/lib/libboost_system-vc141-mt-gd-x64-1_70.lib;optimized;C:/boost-1.70.0/lib/libboost_thread-vc141-mt-x64-1_70.lib;debug;C:/boost-1.70.0/lib/libboost_thread-vc141-mt-gd-x64-1_70.lib;optimized;C:/boost-1.70.0/lib/libboost_chrono-vc141-mt-x64-1_70.lib;debug;C:/boost-1.70.0/lib/libboost_chrono-vc141-mt-gd-x64-1_70.lib"
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/configure/TestBoostBug
  WORKING_DIRECTORY ${_binary_test_dir}
  RESULT_VARIABLE _result
  OUTPUT_QUIET
  ERROR_QUIET
  )
```

Now the test project builds succesfully, but during the execution of `test_boost.exe` it seems like some assertion fails saying `abort() has been called`.

**Comment by masterleinad** [comment]
Just as an update to the Windows support: We now run a MSVC build test for each pull request, see https://ci.appveyor.com/project/tjhei/dealii-8th3t/history, and export the built `Debug` library as artifact for the the `master` branch, see e.g. https://ci.appveyor.com/project/tjhei/dealii-8th3t/builds/29742844/artifacts. Of course, that one uses a bundled `Boost` library.

**Comment by vdilecce** [comment]
I managed to configure and build deal.II 9.4.2 with Boost 1.83 on Windows (Visual Studio 2022) as follows:

Boost 1.83:
```
.\bootstrap.bat

.\b2 --prefix="C:\sw\boost\msvc-2022\1.83.0-static" --build-dir=.\build-static --layout=versioned --abbreviate-paths --hash --without-python --without-graph_parallel --without-mpi toolset=msvc-14.3 link=static runtime-link=static,shared variant=debug,release architecture=x86 address-model=64 cxxstd=17 install
```

deal.II 9.4.2:
```
cmake -G "Visual Studio 17 2022" -A x64 -T host=x64 -DCMAKE_INSTALL_PREFIX=C:/sw/dealii/msvc-2022/9.4.2 -DDEAL_II_CXX_FLAGS="/std:c++17" -DDEAL_II_ALLOW_AUTODETECTION=OFF -DBOOST_DIR=%BOOST_ROOT% -DBoost_USE_STATIC_RUNTIME=OFF -DBoost_ARCHITECTURE=-x64 -DDEAL_II_WITH_TBB=ON -DTBB_DIR=%TBB_ROOT% -S . -B build

cmake --build build --parallel

cmake --install build
```

Closing.
