### ISSUE TITLE
Problems with step-16

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7331]
It looks like one of the recent changes to step-16 in the clang-tidy cleanups broke something (this was reported on the mailing list by Maxi Miller). I got things working again by reverting 361ff1bc and 07aa88f430, but I do not have time right now to investigate further.

**Comment by drwells** [comment]
This might be an issue with older compilers; I only checked with GCC 5.4.

**Comment by bangerth** [comment]
It's a problem with the second commit -- we hand-coded the wrong type there. Can someone try out the comment I left in 07aa88f?

**Comment by tjhei** [comment]
> Can someone try out the comment I left

Yes, the types need to be different. That is the reason for introducing the typedef in the first place.
