### ISSUE TITLE
BOOST_SERIALIZATION_USABLE fails: the test program crashes

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7344]
This command: https://github.com/dealii/dealii/blob/master/cmake/configure/configure_2_boost.cmake#L192

crashes:
```
Scanning dependencies of target derived
[ 25%] Building CXX object CMakeFiles/derived.dir/polymorphic_derived2.cpp.o
[ 50%] Linking CXX shared library libderived.so
[ 50%] Built target derived
Scanning dependencies of target test_boost
[ 75%] Building CXX object CMakeFiles/test_boost.dir/test_dll_exported.cpp.o
[100%] Linking CXX executable test_boost
[100%] Built target test_boost
Scanning dependencies of target run
*** Signal 11
```

FreeBSD 10 and 12, not 11.

**Comment by davydden** [comment]
Which version of boost?

P.s. if it fails, it probably means you try to use boost with broken serialization. See 
https://github.com/boostorg/serialization/pull/105 for 1.68.0

**Comment by yurivict** [comment]
```boost-libs-1.68.0```

**Comment by davydden** [comment]
Oh, then definitely see the issue above and link to the patch there.

Closing this as it’s not dealii issue

**Comment by yurivict** [comment]
Strangely, it only fails on some OS versions, and not others.
