### ISSUE TITLE
Underlinkage in quick tests with GSL

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7352]
Lets move the discussion here from #7282.

It is not clear to me what caused this change, but the issue from #2885 now appears in Arch Linux again (but only in the quick tests). We disable `--as-needed` when linking examples and also (AFAICT) the test suite; however, we do not disable it when linking quick test programs and this results in underlinkage again with GSL.

(labeling as `definitely not our fault` since the core issue is that GSL is still underlinked)

**Comment by tamiko** [comment]
@drwells Can you add a `detailed.log` quickly? And maybe also post the dynamic section [1] of all libraries in question?

[1] something like `readelf -d [...].so | grep NEEDED`

**Comment by drwells** [comment]
Let me recompile everything one more time to make sure there are no ghosts in the machine.

**Comment by drwells** [comment]
[detailed.log](https://github.com/dealii/dealii/files/2479413/detailed.log)

for readelf:
```
[drwells@learch lib]$ readelf -d libdeal_II.g.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libgsl.so.23]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

```
[drwells@learch lib]$ readelf -d libgsl.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

and ldd:
```
[drwells@learch quick_tests]$ ldd step.debug
        linux-vdso.so.1 (0x00007ffccb7e8000)
        libdeal_II.g.so.9.1.0-pre => /home/drwells/[...]/dealii-dev/build-min/lib/libdeal_II.g.so.9.1.0-pre (0x00007fa55d3a9000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fa55d196000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fa55d011000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa55cff7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fa55ce33000)
        libgsl.so.23 => /usr/lib/libgsl.so.23 (0x00007fa55c9b0000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa56a2c9000)
```

**Comment by drwells** [comment]
```
step.debug: RUN failed. Output:
./step.debug: symbol lookup error: /usr/lib/libgsl.so.23: undefined symbol: cblas_ctrmv
```

**Comment by tamiko** [comment]
@drwells Well, well. I suggest to fix the gsl AUR package to explicitly link in the cblas library. Corresponding Debian patch [1]. Alternatively, build and link gsl against an external cblas library (for example the one provided by `openblas`) [2]:
 - export `CBLAS_LIBS`, `CBLAS_CFLAGS`
 - configure with `--with-cblas-external`

[1] https://sources.debian.org/patches/gsl/2.5+dfsg-5/
[2] https://github.com/gentoo/gentoo/blob/master/sci-libs/gsl/gsl-2.5.ebuild

**Comment by drwells** [comment]
GSL is not an AUR package: my latest installation date is from June. I am still baffled as to why this worked for me until last week: my best guess is that, by coincidence, I picked up `-lcblas` somewhere else.

I'll open a bug report but I would be surprised if it got anywhere: Arch developers usually avoid these kinds of patches.

It sounds like this issue is specific to Arch Linux. Should we close this?

**Comment by tamiko** [comment]
Let's close. There is not mut we can do :-/

**Comment by drwells** [comment]
Yes, unfortunately.
