### ISSUE TITLE
SphericalManifold inaccurate/broken

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#7357]
In some convergence studies with high order finite elements, I observed some serious convergence issues with `SphericalManifold`. Note that the implementation is due to #5368 and the optimizations in #5562.

Let me first describe my reduced "test case" (that I found after unsuccessfully chasing for bugs in some solver settings somewhere else for nearly two days):
- On a given mesh (uniformly refined for a hyper shell) I interpolate a simple function (consisting of some sines) onto a `DoFHandler` with elements of degree p, say 3-7. I also use a mapping of the same degree.
- I compute the interpolation error on that mesh with `VectorTools::integrate_difference`.
- Then I do one uniform refinement and a `SolutionTransfer` to interpolate the solution to the fine mesh.
- Again, I compute the interpolation error of the transferred solution with `integrate_difference`. Ideally, the error should be very close to the value I had before, since we are essentially looking at the same solution with a more refined mesh, whose solution space I expect to be a superset apart from some distortion in the mapping from real to unit cell, which we expect to be small (since otherwise we won't get the usual convergence results).

Now, here is what happens with current master, the second test column indicates the initial interpolation error, the third column the error after the transfer to the next finer mesh:
```
Results for degree p=3
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
224           0.13212           0.133738             0.00394132
1526          0.0208251         0.0213652            0.000290693
11258         0.001163          0.00121747           2.30016e-05
86450         7.5112e-05        8.85863e-05          6.2334e-06
677474        6.62049e-06       3.66632e-05          4.80741e-06

Results for degree p=4
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
490           0.0725173         0.0691691            0.000912379
3474          0.00242367        0.00415792           0.000260374
26146         0.000104775       0.00027381           2.19432e-05
202818        3.38376e-06       3.84259e-05          6.21389e-06
1597570       1.92106e-07       3.60443e-05          4.80252e-06

Results for degree p=7
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
2368          0.00291617        0.00969922           0.000773847
17670         1.16211e-05       0.00327867           0.000258108
136474        6.68246e-08       0.000255971          2.18906e-05
1072626       2.20652e-10       3.95126e-05          6.21626e-06
8505058       5.42127e-12       3.61208e-05          4.80049e-06
```

This is really bad: For a solution that initially looks like being accurate to 1e-11, we get out with accuracy of around 3.5e-5! The reason for the complete absence of convergence in the last two steps is because the representation switches to a simpler formula at some point to save some costs, see the discussion in #5562.

Who is affected: Basically everyone with a mapping of degree higher than 2 (midpoints are computed exactly) who transfers between meshes on a `SphericalManifold` description and relies on accuracies more than 1e-4. Multigrid users are also affected (even though a Krylov solver around multigrid will mitigate most problems from bad interpolation). At the same time, the representation within a mesh is reasonably accurate, so what breaks down is mostly the identity of a point say (0.1,0.1,0.1) in the reference coordinates of the coarse mesh that does map to a different point than (0.2,0.2,0.2) on the first children. I compared those two points for the first cell on the last and second to last level in the last result column.

Now I thought that this would be relatively easy to fix by simply adjusting that magic value `2e-2` [in manifold_lib.cc](https://github.com/dealii/dealii/blob/master/source/grid/manifold_lib.cc#L646) and add an optional parameter to `SphericalManifold` that lets users decide about the tolerance. However, the picture is not much better here:
```
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
224           0.13212           0.133738             0.00394132
1526          0.0208251         0.0213652            0.000290693
11258         0.001163          0.00121747           2.30016e-05
86450         7.5112e-05        7.80346e-05          1.58871e-06
677474        4.73196e-06       4.91085e-06          1.03866e-07

Results for degree p=4
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
490           0.0725173         0.0691691            0.000912379
3474          0.00242367        0.00415792           0.000260374
26146         0.000104775       0.00027381           2.19432e-05
202818        3.38376e-06       1.65516e-05          1.53106e-06
1597570       1.0623e-07        1.02214e-06          1.00318e-07

Results for degree p=7
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
2368          0.00291617        0.00969922           0.000773847
17670         1.16211e-05       0.00327867           0.000258108
136474        6.68246e-08       0.000255971          2.18906e-05
1072626       2.20652e-10       1.62181e-05          1.52956e-06
8505058       8.7109e-13        1.01681e-06          1.00273e-07
```
So while I now get at least convergence, I do not get p-convergence at all, and the improvement seems to be limited to fourth order.

Just for comparison, this is what I get in 2D (and similar numbers for other manifolds such as `CylindricalManifold`):
```
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
120           0.00780943        0.00785413           5.83388e-05
420           0.000561945       0.000564668          3.75506e-06
1560          3.60791e-05       3.62498e-05          2.37905e-07
6000          2.26938e-06       2.28006e-06          1.49664e-08
23520         1.42061e-07       1.42729e-07          9.38393e-10

Results for degree p=4
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
200           0.00134236        0.00134429           1.48907e-06
720           4.41618e-05       4.42296e-05          4.79036e-08
2720          1.4002e-06        1.40238e-06          1.51733e-09
10560         4.39408e-08       4.40092e-08          4.77259e-11
41600         1.3746e-09        1.37675e-09          1.49625e-12

Results for degree p=7
ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine
560           3.05574e-06       3.05575e-06          1.66301e-11
2100          1.2188e-08        1.2188e-08           6.4976e-14
8120          5.08135e-11       5.08136e-11          1.22152e-15
31920         1.99673e-13       1.99632e-13          1.66536e-15
126560        1.4698e-15        2.38283e-15          1.22214e-15
```
Note the fast convergence for degree 7. This is what I would expect.

Thus, it seems that our algorithm to compute points on the spherical manifold is only fourth order accurate in the surrounding points. This is still bad. I do not remember the details of the algorithm from http://math.ucsd.edu/~sbuss/ResearchWeb/spheremean/ but maybe @masterleinad does?

Here is the code to reproduce:
```
#include <deal.II/grid/tria.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/function.h>
#include <deal.II/numerics/vector_tools.h>
#include <deal.II/lac/vector.h>
#include <deal.II/numerics/solution_transfer.h>
#include <deal.II/numerics/vector_tools.h>

using namespace dealii;

template <int dim>
class MyFunction : public Function<dim>
{
public:
  virtual double value (const Point<dim> &p,
                        const unsigned int) const override
  {
    return std::sin(numbers::PI*(p[0] + p[1]));
  }
};


template <int dim>
void test(const unsigned int degree)
{
  Triangulation<dim> triangulation;
  GridGenerator::hyper_shell(triangulation, Point<dim>(), 0.5, 1.);
  DoFHandler<dim> dof_handler(triangulation);
  FE_Q<dim> fe(degree);
  MappingQGeneric<dim> mapping(degree);
  std::cout << "Results for degree p=" << degree << std::endl;

  std::cout << "ndofs_coarse  error_on_coarse   error_after_refine   error_map_coarse_fine" << std::endl;
  for (unsigned int cycle = 0; cycle<5; ++cycle)
    {
      dof_handler.distribute_dofs(fe);
      const types::global_dof_index ndofs = dof_handler.n_dofs();
      Vector<double> mysol(dof_handler.n_dofs());
      VectorTools::interpolate(mapping, dof_handler, MyFunction<dim>(), mysol);
      Vector<float> error_per_cell(triangulation.n_active_cells());
      VectorTools::integrate_difference(mapping, dof_handler, mysol,
                                        MyFunction<dim>(), error_per_cell,
                                        QGauss<dim>(degree+4), VectorTools::L2_norm);
      const double error_in = error_per_cell.l2_norm();

      for (const auto &cell : triangulation.active_cell_iterators())
        cell->set_refine_flag();

      SolutionTransfer<dim> transfer(dof_handler);
      triangulation.prepare_coarsening_and_refinement();
      transfer.prepare_for_coarsening_and_refinement(mysol);
      triangulation.execute_coarsening_and_refinement();
      dof_handler.distribute_dofs(fe);
      Vector<double> mysol2(dof_handler.n_dofs());
      transfer.interpolate(mysol, mysol2);
      error_per_cell.reinit(triangulation.n_active_cells());
      VectorTools::integrate_difference(mapping, dof_handler, mysol2,
                                        MyFunction<dim>(), error_per_cell,
                                        QGauss<dim>(degree+4), VectorTools::L2_norm);
      const double error_out = error_per_cell.l2_norm();
      std::cout << std::left << std::setw(14) << ndofs
                << std::left << std::setw(18) << error_in
                << std::left << std::setw(21) << error_out;
      Point<dim> p0;
      for (unsigned int d=0; d<dim; ++d)
        p0[d] = 0.1;
      Point<dim> p1;
      for (unsigned int d=0; d<dim; ++d)
        p1[d] = 0.2;
      std::cout << (mapping.transform_unit_to_real_cell(triangulation.begin(triangulation.n_levels()-2), p0)-mapping.transform_unit_to_real_cell(triangulation.begin(triangulation.n_levels()-1), p1)).norm() << std::endl;
    }
  std::cout << std::endl;
}


int main()
{
  std::cout << "Test in 2D" << std::endl;
  for (unsigned int p=3; p<8; ++p)
    test<2>(p);
  std::cout << std::endl << std::endl << "Test in 3D" << std::endl;
  for (unsigned int p=3; p<8; ++p)
    test<3>(p);

  return 0;
}
```

Now how do we move forward:
- The problem could be cured by computing new points on a finer mesh. So in `get_new_point`, we would need to somehow create a refined point distribution from the accurate mid points. This would be a lot of work to implement and it would be very likely even slower than what we do in the expensive path of `SphericalManifold` now.
- There could be another way to describe *accurate* point distributions within the octants of a shell. I have not looked in literature, but I guess it is not a very common problem.
- We could start looking into writing algorithms that move the points of a given mapping into better locations, as a means to preserve the mapped point positions (and hence maintain the quality of interpolation). I have not looked into this much yet, but the high order meshing community is pretty big, so there should be plenty of strategies available.

**Comment by masterleinad** [comment]
> Thus, it seems that our algorithm to compute points on the spherical manifold is only fourth order accurate in the surrounding points. This is still bad. I do not remember the details of the algorithm from http://math.ucsd.edu/~sbuss/ResearchWeb/spheremean/ but maybe @masterleinad does?

The algorithm should compute a point that minimizes the sum of the weighted spherical distances up to machine precision if sufficiently many iterations are performed. In fact, the authors of the paper show runtime results for 16 digits precision. We might want to reevaluate that the algorithm really is implemented correctly and follows the description in the paper.

**Comment by kronbichler** [comment]
> The algorithm should compute a point that minimizes the sum of the weighted spherical distances up to machine precision if sufficiently many iterations are performed.

The question is whether the minimization is "stable", i.e., whether the minimum on a large cell with 4 vertices and unit coordinates `(0.1,0.1,0.1)` gives the same answer as the first child at coordinates `(0.2,0.2,0.2)`. This is the assumption all our interpolation operators rely on, so the manifold description needs to provide it.

**Comment by masterleinad** [comment]
> The question is whether the minimization is "stable", i.e., whether the minimum on a large cell with 4 vertices and unit coordinates `(0.1,0.1,0.1)` gives the same answer as the first child at coordinates `(0.2,0.2,0.2)`. This is the assumption all our interpolation operators rely on, so the manifold description needs to provide it.

The following program distorts the vertices (and weights) of a face with vertex coordinates `(-.1, -.1, .5), (-.1, -.1, .5), (-.1, -.1, .5), (-.1, -.1, .5)` and computes the maximum difference for the new point computed:

```
#include <deal.II/base/function.h>
#include <deal.II/base/logstream.h>
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>

#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>

#include <deal.II/lac/dynamic_sparsity_pattern.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/precondition.h>
#include <deal.II/lac/solver_cg.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/vector.h>

#include <deal.II/numerics/data_out.h>
#include <deal.II/numerics/matrix_tools.h>
#include <deal.II/numerics/vector_tools.h>

#include <fstream>
#include <iostream>
#include <random>

using namespace dealii;

int
main()
{
  SphericalManifold<3> manifold;

  for (int j = 2; j < 20; ++j)
    {
      const double                    eps = std::pow(10, -j);
      const int                       n   = 100;
      std::random_device              rd;
      std::mt19937                    gen(rd());
      std::uniform_int_distribution<> dis(-1., 1.);

      std::vector<Point<3>> points_ref{{-.1, -.1, .5},
                                       {.1, -.1, .5},
                                       {-.1, .1, .5},
                                       {.1, .1, .5}};
      std::vector<double>   weights_ref{.25, .25, .25, .25};

      const Point<3> new_point_ref =
        manifold.get_new_point(make_array_view(points_ref),
                               make_array_view(weights_ref));

      double max_difference = 0.;

      for (unsigned int i = 0; i < n; ++i)
        {
          std::vector<Point<3>> points  = {{-.1, -.1, .5},
                                          {.1, -.1, .5},
                                          {-.1, .1, .5},
                                          {.1, .1, .5}};
          std::vector<double>   weights = {.25, .25, .25, .25};

          for (auto &point : points)
            {
              point[0] += dis(gen) * eps;
              point[1] += dis(gen) * eps;
              point[2] += dis(gen) * eps;
            }

          for (auto &weight : weights)
            {
              weight += dis(gen) * eps;
            }

          const Point<3> new_point =
            manifold.get_new_point(make_array_view(points),
                                   make_array_view(weights));
          const Tensor<1, 3> difference      = new_point - new_point_ref;
          const double       difference_norm = difference.norm();
          max_difference = std::max(difference_norm, max_difference);
        }


      std::cout << "Tolerance: " << eps << " max difference: " << max_difference
                << std::endl;
    }
  return 0;
}
```

The results are:
```
Tolerance: 0.01 max difference: 0.0137971
Tolerance: 0.001 max difference: 0.00140043
Tolerance: 0.0001 max difference: 0.000131723
Tolerance: 1e-05 max difference: 1.45863e-05
Tolerance: 1e-06 max difference: 1.30281e-06
Tolerance: 1e-07 max difference: 1.48598e-07
Tolerance: 1e-08 max difference: 1.42467e-08
Tolerance: 1e-09 max difference: 1.56219e-09
Tolerance: 1e-10 max difference: 1.45853e-10
Tolerance: 1e-11 max difference: 1.62232e-11
Tolerance: 1e-12 max difference: 1.44263e-12
Tolerance: 1e-13 max difference: 1.56688e-13
Tolerance: 1e-14 max difference: 1.56373e-14
Tolerance: 1e-15 max difference: 1.44707e-15
Tolerance: 1e-16 max difference: 2.34829e-16
Tolerance: 1e-17 max difference: 1.8735e-17
Tolerance: 1e-18 max difference: 0
Tolerance: 1e-19 max difference: 0
```
In particular, the maximum difference has the same magnitude as the distortion.

**Comment by bangerth** [comment]
I have little to contribute to the discussion, but can you make this into a stand-alone test?

**Comment by masterleinad** [comment]
> I have little to contribute to the discussion, but can you make this into a stand-alone test?

I could but I don't yet see the benefit since the program doesn't show any problem.

**Comment by bangerth** [comment]
Programs that currently work make for good testcases because they ensure that the same functionality will continue to work in the future :-)

**Comment by masterleinad** [comment]
> Programs that currently work make for good testcases because they ensure that the same functionality will continue to work in the future :-)

Oh, I thought you wanted me to make that example independent from `deal.II` instead to help finding the problem here. Of course, I can contribute it to the testsuite. Give me a sec.

**Comment by masterleinad** [comment]
@kronbichler I am actually not sure if that example answers your question regarding the stability of the algorithm. I
n the situation you describe, do you expect the coordinates of the vertices of the child cell to be the same as the ones for the large cell up to a small tolerance? Then, the test above should show the desired stability. 
If not, can you specify the invariant (or assumption) that should hold true and I can test?

**Comment by kronbichler** [comment]
No, the example does not answer my question. What I expect is that the manifold maps to the *same* point when done from a coarser parent cell or a finer child cell. Take for example the following code:
```
#include <deal.II/grid/manifold_lib.h>
#include <iostream>

using namespace dealii;

int
main()
{
  SphericalManifold<3> manifold;

  std::vector<Point<3>> points_coarse{{-.1, -.1, .5},
                                      {.1, -.1, .5},
                                      {-.1, .1, .5},
                                      {.1, .1, .5}};
  std::vector<double>   weights_coarse{.81, .09, .09, .01};

  std::vector<Point<3>> points_fine{{-.1, -.1, .5},
                                    {0, -0.10190493307301364, 0.50952466536506813},
                                    {-0.10190493307301364, 0, 0.50952466536506813},
                                    {0, 0, 0.51961524227066325}};
  std::vector<double>   weights_fine{.64, .16, .16, .04};

  std::cout.precision(15);
  std::cout << "Spherical manifold" << std::endl;
  std::cout << "Location coarse: "
            << manifold.get_new_point(make_array_view(points_coarse),
                                      make_array_view(weights_coarse))
            << std::endl
            << "Location fine:   "
            << manifold.get_new_point(make_array_view(points_fine),
                                      make_array_view(weights_fine))
            << std::endl
            << std::endl;

  CylindricalManifold<3> cylindrical;
  std::vector<Point<3>> points_fine_cyl{{-.1, -.1, .5},
                                        {0, -.1, 0.5},
                                        {-.1, 0., 0.5099019513592784},
                                        {0, 0, 0.5099019513592784}};

  std::cout << "Cylindrical manifold" << std::endl;
  std::cout << "Location coarse: "
            << cylindrical.get_new_point(make_array_view(points_coarse),
                                         make_array_view(weights_coarse))
            << std::endl
            << "Location fine:   "
            << cylindrical.get_new_point(make_array_view(points_fine_cyl),
                                         make_array_view(weights_fine))
            << std::endl
            << std::endl;

  return 0;
}
```
The output of this program is as follows:
```
Spherical manifold
Location coarse: -0.0807333026126765 -0.0807333026126765 0.506916430685079
Location fine:   -0.0807332710004368 -0.0807332710004368 0.506916440754431

Cylindrical manifold
Location coarse: -0.08 -0.0801876514022031 0.503557286276943
Location fine:   -0.08 -0.0801876514022031 0.503557286276943
```
Note that the spherical manifold maps to a different point when given the points of a child element, whereas the cylindrical manifold maps to the exact same point. The points for the child element were created by `manifold.get_new_point(points_coarse,weights)` where `weights` runs through `(0,0,0), (0.5,0.5,0),(0.5,0,0.5,0),(0.25,0.25,0.25,0.25)`, corresponding to the usual refinement routines we apply.

In the current example, the points are pretty close - this corresponds to a refinement level of maybe 3 already, but still we see a difference in the seventh digit. If the points are farther apart the difference will be higher. If the same point in reference coordinates is mapped to different locations by the mapping this means that are is no chance for higher order mappings to do the interpolation (solution transfer) more accurately.

**Comment by masterleinad** [comment]
From the paper:
> Sometimes, we use a superimposed ‘+’ and small circle to represent the same quantity, namely,
we sometimes denote $\specialsum w_i p_i$ by
\[
w_1 p_1 \oplus w_2 p_2\oplus \dots \oplus w_n p_n
\]
This modified summation and addition notation is suggestive, but the reader should be aware that 
many common properties of ordinary summations are not shared by spherical weighted averages; for 
instance, it is usually the case that the values
\[
\frac{2}{3} \cdot ( \frac{1}{2} \cdot p_1 \oplus \frac{1}{2} \cdot p_2 ) \oplus \frac{1}{3} \cdot  p_3
\]
and
\[
\frac{1}{3} \cdot \frac{2}{3} ( p_1 \oplus \frac{1}{2}p_2 \oplus \frac{1}{2} p_3)
\]
are distinct.  This failure of associativity is an example of how our weighted average \textit{Avg} differs 
from using progressive slerping, that is to say, the \textit{Avg} value cannot be computed by taking
successive spherical averages of pairs of points.  Indeed, by Brown and Worsey [5], there is no way to 
define spherical averages which is intrinsic to the sphere so that associativity holds.
>
>[5] L. Brown and A. J. Worsey, Problems with defining barycentric coordinates for the sphere, 
Mathematical Modelling and Numerical Analysis (Modélisation Mathématique et Analyse Numérique),
26 (1992), pp. 37–49
```

**Comment by kronbichler** [comment]
So the conclusion from this statement is that we cannot have both an associative evaluation of weights that is consistent in the parent-child transfer and at the same time minimizing the distances. Right now we relax the associativity but one could also relax the spherical averaging instead to preserve the distances. It would be interesting to see how the latter compares. If I have some time, I will test this with the transfinite intepolation mechanisms at some point for the sphere to see how that compares.

**Comment by kronbichler** [comment]
Providing a proper fix along an alternative direction (via transfinite interpolation) takes more time than I have before the release, so we need to move the target milestone; it is a bit scary though because the spherical manifold will give wrong (sub-optimal) results in the combination of `SolutionTransfer` and more polynomials of degree higher than 3 (and degree 3 might have worse error constants).

**Comment by kronbichler** [comment]
Just as a remark, an easier fix in the multigrid context of this problem is to use `MappingFEField` on the finest level with `VectorTools::get_position_vector`, and then use `MGTransferMatrixFree::interpolate_to_mg` as in https://github.com/dealii/dealii/blob/master/tests/mappings/mapping_fe_field_05.cc
This should give consistent fields between the levels present in the grid, but of course does not solve the problem for the `SolutionTransfer` and other algorithms.

**Comment by kronbichler** [comment]
I think I have a fairly good understanding of the issue here, but no simple solution except the one that interpolates the mapping from a fine mesh to a coarser one.
