### ISSUE TITLE
more MPI warnings

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#7365]
I am using mvapich2 (2.2 which is current in OpenSuse 15.0) and I am getting the following warnings (about 18 of those):
```
/scratch/deal-git/source/distributed/tria.cc:1843:39: warning: argument type 'const unsigned int *' doesn't match specified 'MPI' type tag that requires 'unsigned int *' [-Wtype-safety]
                                      DEAL_II_MPI_CONST_CAST(data),
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/deal-git/include/deal.II/base/mpi.h:68:42: note: expanded from macro 'DEAL_II_MPI_CONST_CAST'
#    define DEAL_II_MPI_CONST_CAST(expr) (expr)
                                         ^~~~~~
source/distributed/tria.inst:30:17: note: in instantiation of member function 'dealii::parallel::distributed::Triangulation<2, 2>::DataTransfer::save' requested here
 template class Triangulation< 2 >;
                ^
```

It seems to me that the warning is bogus (we do not do the const cast macro trickery as this library supports mpi 3) and passing a ``const int *`` is okay. Note that the function declarations are const correct (in contrast to the bug #7225), there just seem to be annotations that incorrectly generate these warnings.

Thoughts? Always cast const away in these arguments?

**Comment by tjhei** [comment]
Also see https://github.com/pmodels/mpich/issues/2223

**Comment by masterleinad** [comment]
> Thoughts? Always cast const away in these arguments?

This seems to be fixed in recent versions. I would just ignore these bogus warnings or provide a configure time check for when to use `DEAL_II_MPI_CONST_CAST`. 
I think that we should not use `const_cast`s when they are not strictly necessary.

**Comment by tjhei** [comment]
I realized opensuse has an ancient ``mvapich2`` package and a more modern ``mpich`` that works correctly. I am too lazy to fix the warnings for the older MPI. Closing.
