### ISSUE TITLE
Revert 7339

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7372]
The changes made in #7339 unfortunately result in unwanted pollution of the terminal, e.g.
```
ADOL-C error: reading integer tape number 4!
              >>> File or directory not found! <<<
```
We should therefore revert the changes made there (although it may still be a good idea to retain the try-catch block). The reasoning behind this change should be added to the already lengthy diatribe that will be re-introduced into that function.

**Comment by bangerth** [comment]
It sounded so good...
