### ISSUE TITLE
Function should NOT be derived from FunctionTime<RangeNumberType> 

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7374]
IMO it does not make sense to have 
```
class Function : public FunctionTime<RangeNumberType>
```
that means that if the function's range is `std::complex<double>`, we ask users to provide time as a complex-valued number:
```
Number FunctionTime< Number >::get_time() const
```

What should happen instead is that we use type-traits to get real-valued type based on `RangeNumberType`.

**Comment by bangerth** [comment]
Yes, nice idea. I think we have the ability to extract a real scalar type in `class NumberTrait` already.
