### ISSUE TITLE
why not use boost::zip_iterator for sparsity pattern and sparse matrix objects?

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7378]
I came across [boost::zip_iterator](https://www.boost.org/doc/libs/1_68_0/libs/iterator/doc/zip_iterator.html) class that can wrap multiple iterators. There is also an implementation discussed on [stackoverflow](https://codereview.stackexchange.com/questions/30846/zip-like-functionality-with-c11s-range-based-for-loop) that can take arbitrary number of iterators and zip it. 

Maybe one could adopt such classes as an alternative to iterate over elements of sparse matrices (together with the associated sparsity patterns). 

The advantage would be that one could use all C++ machinery like `std::for_each()` or range based loops etc.

**Comment by drwells** [comment]
Right now the `SparseMatrix` accessor class inherits from the `SparsityPattern` accessor, so they are already deeply coupled: the sparse matrix iterator uses the sparsity pattern one for all indexing purposes.

**Comment by tamiko** [comment]
@drwells is right - our sparsity pattern does all index operations. In case I have to access multiple matrices that have the same sparsity pattern, I use the something like the following function to transform a sparsity pattern iterator into a matrix iterator (in order to avoid any index operation):
```
  template <typename Matrix, typename Iterator>
  inline DEAL_II_ALWAYS_INLINE double get_entry(const Matrix &matrix,
                                                const Iterator &it)
  {
    const auto global_index = it->global_index();
    const typename Matrix::const_iterator matrix_iterator(&matrix,
                                                          global_index);
    return matrix_iterator->value();
  }
```

**Comment by davydden** [comment]
> they are already deeply coupled

I know, I just had an impression that this part can be simplified and generalized by zipping, essentially doing things like 
```
boost::make_zip_iterator(
  boost::make_tuple(
    sp.begin(row), 
    value.data()+sp.begin(row)->index()))
```

**Comment by bangerth** [comment]
Even if not for the purpose you originally had in mind, it seems like this zip iterator could replace the `SynchronousIterator` class.

**Comment by davydden** [comment]
Another thing I noticed is that our matrix iterators actually never _iterate_ over matrix elements (in a sense of `auto it = val.begin(); ++it` etc). Instead, we let accessors know how to return the right element given the iterator to `SparsityPattern` object by, essentially, doing `matrix->val[global_index]`. This may not lead to any measurable difference in terms of performance and how this matrix is being used, but it's still a difference in the way iterators are implemented.

**Comment by drwells** [comment]
This would be a nice feature to have but ultimately I think Matthias' solution is the preferrable one since it is the simplest. We can reopen this later if people want to do more sophisticated things with iterators but its a bit of a niche application.
