### ISSUE TITLE
deal.II 9.0 not working on CentOS 6

### ISSUE THREAD

**Issue by vdilecce** [dealii/dealii#7389]
### In short

On CentOS 6:
- deal.II 8.5 builds and passes the `make test` step
- deal.II 9.0 builds but **fails** `make test` due to **segmentation fault**

### In detail

- I built the following versions of GCC on CentOS 6:
    - GCC 8.1
    - GCC 6.4
    - GCC 5.5
    - GCC 4.9.4

- I configured deal.II as follows:
    ```
    $ cmake -DCMAKE_INSTALL_PREFIX=/opt/dealii-9.0.0
            -DCMAKE_C_COMPILER=/opt/gcc/bin/gcc
            -DCMAKE_CXX_COMPILER=/opt/gcc/bin/g++
            -DCMAKE_Fortran_COMPILER=/opt/gcc/bin/gfortran
            -DDEAL_II_LINKER_FLAGS=-Wl,
                    -L,    /opt/gcc/lib64,
                    -L,    /opt/gcc/lib/gcc/x86_64-pc-linux-gnu/6.4.0/plugin,
                    -L,    /opt/gcc/libexec/gcc/x86_64-pc-linux-gnu/6.4.0,
                    -rpath,/opt/gcc/lib64,
                    -rpath,/opt/gcc/lib/gcc/x86_64-pc-linux-gnu/6.4.0/plugin,
                    -rpath,/opt/gcc/libexec/gcc/x86_64-pc-linux-gnu/6.4.0
    ```  
- In all cases deal.II built successfully
- In all cases `make test` failed due to segmentation fault:
    ```
    Start 1: step.debug
    1/5 Test #1: step.debug .......................***Failed   11.70 sec
    /bin/sh: line 1:  7308 Segmentation fault      (core dumped) ./step.debug > step.debug-OK 2>&1
    gmake[7]: *** [tests/quick_tests/CMakeFiles/step.debug.run] Error 1
    gmake[6]: *** [tests/quick_tests/CMakeFiles/step.debug.run.dir/all] Error 2
    gmake[5]: *** [tests/quick_tests/CMakeFiles/step.debug.run.dir/rule] Error 2
    gmake[4]: *** [step.debug.run] Error 2
    ```
- Running `ldd` on the output libraries returned the expected results.

- Other attempts:
    - Using `ninja` instead of `make`: it did not work
    - Trying deal.II **8.5**: it **passed** the `make test` step
    - Trying deal.II 9.0 and 8.5 on *Debian 9* (default GCC 6.4 and GCC 8.2): **both passed** the `make test` step

**Comment by davydden** [comment]
> In all cases make test failed due to segmentation fault

what happens if you run this test `step.debug` with `gdb`? Does it point anywhere?

**Comment by tjhei** [comment]
> * -DDEAL_II_LINKER_FLAGS=-Wl,

Do you need to specify these linker flags? What happens if you don't specify them?

**Comment by vdilecce** [comment]
> > * -DDEAL_II_LINKER_FLAGS=-Wl,
> 
> Do you need to specify these linker flags? What happens if you don't specify them?

Build fails:
```
../../bin/expand_instantiations: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ../../bin/expand_instantiations)
```
This is because I am using a custom GCC: actually, I checked it is enough to either specify `-Wl,-rpath` or run configuration and build with `LD_LIBRARY_PATH` set to those paths (actually, `/opt/gcc/lib64` should be enough).

---

> > In all cases make test failed due to segmentation fault
>
> what happens if you run this test step.debug with gdb? Does it point anywhere?

I ran `gdb bin/step-1.debug` and got:
```
(gdb) run
Starting program: /media/DATA/software/dealii-9.0.0/build/bin/step-1.debug 
warning: File "/opt/gcc-6.4.0/lib64/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "/usr/share/gdb/auto-load:/usr/lib/debug:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /opt/gcc-6.4.0/lib64/libstdc++.so.6.0.22-gdb.py
line to your configuration file "/home/valerio/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/valerio/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff09cc96c in tbb::interface9::global_control::active_value(int) ()
    at /media/DATA/software/dealii-9.0.0/bundled/tbb-2018_U2/src/tbb/tbb_main.cpp:563
563	    return controls[param]->active_value();
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6.x86_64 zlib-1.2.3-29.el6.x86_64
```

**Comment by vdilecce** [comment]
> > This is because I am using a custom GCC
> 
> This means things are going to break if you pull in any other library. Can you check with `ldd` that your deal.II library is not using anything that might be incompatible with your custom gcc?

```
$ ldd libdeal_II.so
	linux-vdso.so.1 =>  (0x00007ffc08e8f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007efe9def8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007efe9dce1000)
	libstdc++.so.6 => /opt/gcc-6.4.0/lib64/libstdc++.so.6 (0x00007efe9d94d000) (*)
	libm.so.6 => /lib64/libm.so.6 (0x00007efe9d6c9000)
	libgcc_s.so.1 => /opt/gcc-6.4.0/lib64/libgcc_s.so.1 (0x00007efe9d4b2000) (**)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efe9d295000)
	libc.so.6 => /lib64/libc.so.6 (0x00007efe9cf01000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558438783000)

(*)
$ ldd /opt/gcc-6.4.0/lib64/libstdc++.so.6
	linux-vdso.so.1 =>  (0x00007ffdecbd7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fca74aea000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fca74756000)
	/lib64/ld-linux-x86-64.so.2 (0x0000564bdaaaf000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fca7453f000)

(**)
$ ldd /opt/gcc-6.4.0/lib64/libgcc_s.so.1
	linux-vdso.so.1 =>  (0x00007ffff61e9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f43a5c1c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c0afdb2000)
```

**Comment by bangerth** [comment]
I think it is universally a bad idea to use a custom compiler because you may be linking against libraries that were compiled using different compilers. That's particularly true because not all versions of GCC are ABI compatible to each other. You have to be really careful in linking such libraries together, and if you are not, things like segmentation faults are what happens. In particular, if you use a particular compiler, you need to make sure that the program is run with the exact same values for the environment variables as were set when you compiled the program.

What is it that you are trying to achieve? Maybe there is an easier way to do that?

**Comment by vdilecce** [comment]
Apparently I found a way to work around this issue. I made the following attempts:

1. I configured deal.II with `-DDEAL_II_WITH_THREADS=OFF`: `make test` succeeded (so yes, as the `gdb` output suggested, the problem was the bundled TBB library).

1. I tried using TBB from CentOS 6 repos, but it's outdated; by the way, I found this because of a build error due to a missing header file, so I'm wondering if there is a way to check the external TBB version during configuration...

1. I built the **TBB 2018 U2** [from source](https://github.com/01org/tbb/releases/tag/2018_U2) with the *default* GCC 4.4.7. I configured **deal.II** with `-DTBB_DIR` (pointing to such self-compiled TBB) and built it (with GCC 6.4): `make test` succeeded.

**Comment by bangerth** [comment]
My apologies for not getting back to this earlier. 

About the version of the TBB: We do check what version the system has, and if it is too old, we fall back to the one that's in the `bundled/` directory. What version of the TBB do you have on your system? The current deal.II dev version requires at least TBB 4.2: https://github.com/dealii/dealii/blob/master/cmake/configure/configure_1_threads.cmake#L143

**Comment by vdilecce** [comment]
> What version of the TBB do you have on your system? The current deal.II dev version requires at least TBB 4.2

In the repos there's TBB 2.2 (very old, yet the find module seems ok with the syntax though)

**Comment by masterleinad** [comment]
That seems strange. https://github.com/dealii/dealii/blob/master/cmake/configure/configure_1_threads.cmake#L148 should prevent being able to use `TBB 2.2`.
What is the TBB version reported in `detailed.log`?

**Comment by bangerth** [comment]
I think the check in the repo is pretty new. @vdilecce -- you are reporting this with deal.II 8.5 and 9.0, correct? I'm pretty sure that with the current dev versions of deal.II, TBB 2.2 would be rejected and deal.II reverts to its own bundled version.

**Comment by vdilecce** [comment]
I reconfigured deal.II on CentOS 6 to be sure, and from `detailed.log` it looks like that version 9.0 has some problems:

**9.0.0**:
```
#        DEAL_II_WITH_THREADS set up with external dependencies
#            TBB_VERSION = 2.2
#            THREADS_LINKER_FLAGS = -pthread
#            THREADS_INCLUDE_DIRS = /usr/include
#            THREADS_USER_INCLUDE_DIRS = /usr/include
#            THREADS_LIBRARIES = /usr/lib64/libtbb.so
```
**commit** 28fa42f944c428dde697f7cb01516dac088e0bf8:
```
#        DEAL_II_WITH_THREADS set up with bundled packages
#            TBB_VERSION = 2.2
#            THREADS_CXX_FLAGS = -Wno-parentheses
#            THREADS_LINKER_FLAGS = -pthread
#            THREADS_DEFINITIONS_DEBUG = TBB_USE_DEBUG;TBB_DO_ASSERT=1
#            THREADS_USER_DEFINITIONS_DEBUG = TBB_USE_DEBUG;TBB_DO_ASSERT=1
#            THREADS_BUNDLED_INCLUDE_DIRS = /media/DATA/software/dealii/dealii-master/bundled/tbb-2018_U2/include
#            THREADS_LIBRARIES = dl
```

**Comment by bangerth** [comment]
I think the message is just wrong:
```
#        DEAL_II_WITH_THREADS set up with bundled packages
#            TBB_VERSION = 2.2
...
#            THREADS_BUNDLED_INCLUDE_DIRS = /media/DATA/software/dealii/dealii-master/bundled/tbb-2018_U2/include
#            THREADS_LIBRARIES = dl
```
Note how it says that it uses the bundled version, but then reports the version as 2.2. I think this is just the version number that it *previously* found (the external version).

Do you have a way to figure out what it is really using? My bet is that it is the bundled version.

**Comment by bangerth** [comment]
I've made a change in #7552 to ensure that the screen message does not reflect the old version. If you don't mind, can you try that out?

**Comment by vdilecce** [comment]
Yes, as of commit 458ea04 it appears to be ok:

```
#        DEAL_II_WITH_THREADS set up with bundled packages
#            TBB_VERSION = bundled
#            THREADS_CXX_FLAGS = -Wno-parentheses
#            THREADS_LINKER_FLAGS = -pthread
#            THREADS_DEFINITIONS_DEBUG = TBB_USE_DEBUG;TBB_DO_ASSERT=1
#            THREADS_USER_DEFINITIONS_DEBUG = TBB_USE_DEBUG;TBB_DO_ASSERT=1
#            THREADS_BUNDLED_INCLUDE_DIRS = /media/DATA/software/dealii/dealii/bundled/tbb-2018_U2/include
#            THREADS_LIBRARIES = dl
```

**Comment by bangerth** [comment]
OK. Do you agree that we can then close this issue?

**Comment by vdilecce** [comment]
I agree. Thank you!
