### ISSUE TITLE
sparsity pattern with missing entries for vector-valued dG methods

### ISSUE THREAD

**Issue by koecher** [dealii/dealii#7390]
Dear all,
as reported on the maillist
https://groups.google.com/forum/#!topic/dealii/ZxXUCFc0q4U
I have some (for me) new issues with deal.II v9.0.x within the FESystem framework (dim=spacedim>1)

- [x] FE_DGQArbitraryNodes(QGauss( p+1 )) works correctly
- [ ] FE_DGQArbitraryNodes(QGaussLobatto( p+1 )) yields missing flux terms (dealii::DoFTools::nonzero)
- [ ] FE_DGQArbitraryNodes(QGaussLobatto( p+1 )) yields FE_DGQ(p) element even for p > 2

The third one of the list seems to be incorrect for me, since there are some (slight) convergence and/or dispersion differences between equidistantly spaced and Gauss-Lobatto-quadrature point spaced basis functions for the discrete (dG) basis functions for a local polynomial degree p > 2.

My test program (not perfectly minimized) can be found on:
https://bitbucket.org/dtmproject/unittest-003

If nobody finds a simple solution over this weekend, I'll dig in deeper next week.

Kind regards
  Uwe

**Comment by koecher** [comment]
@drwells thanks for adding the bug label, I really think we have a problem here

**Comment by drwells** [comment]
Absolutely.

In case its not clear from the initial report: this test case worked with 8.5.

**Comment by koecher** [comment]
I've studied the issue a bit deeper now.

The bug seems to be located inside `void DoFTools::make_flux_sparsity_pattern` with two coupling tables and 5 parameters overall, that are `dof,sparsity,cell_integrals_mask,face_integrals_mask,subdomain_id`

- v8.4 did not had the function with the 5th parameter `subdomain_id`
- v8.5 has the issue (missing sparsity entries)
- v9.0.x has the issue (missing sparsity entries)
- current developer version has the issue (missing sparsity entries)

The function `void DoFTools::make_flux_sparsity_pattern` without coupling tables, and the 5 parameters `dof,sparsity_pattern,constraints,keep_constrained_dofs,subdomain_id` works as expected.

**Comment by masterleinad** [comment]
Can you turn your example into a test case so we can run `git bisect` on it?

**Comment by koecher** [comment]
@masterleinad originally I thought that I was only switching deal.II v8.5 to v9.0 due to an issue with interpolation of a FESystem() with multiple different FE's inside - but I was also changing the way of implemementing the sparsity_pattern; shortly spoken there seems to be no way to do something like `git bisect`

The current stage of my analysis is, that the (newer) implementation of `make_flux_sparsity_pattern` calls
```
support_on_face(i, f) = fe.has_support_on_face(i, f);
```
in line 761 of `source/dofs/dof_tools_sparsity.cc`, which gives different results for the reported FEs (from the initial report above. Having a first view this seems to be correct - but my assemblies having entries on other dof-couplings. I'm trying to find out why.

**Comment by koecher** [comment]
Oh dear. Sorry - found the issue. Please remove the bug label.

Note: I have misunderstood

> Two components couple only if their shape functions are both nonzero on a given face. This flag is only used when computing integrals over faces of cells, e.g., in DoFTools::make_flux_sparsity_pattern().

of the documentation of `DoFTools::Coupling::nonzero`.

Indeed my shape functions are zero on those faces - but I'm using an IPDG method using gradients as well, which are not zero.

Maybe we can give an explicit note on that case `DoFTools::Coupling::always` must be used, e.g.

> Two components couple only if their shape functions are both nonzero on a given face. This flag is only used when computing integrals over faces of cells, e.g., in DoFTools::make_flux_sparsity_pattern(). Use Coupling::always in general cases where gradients etc. occur.

**Comment by drwells** [comment]
@koecher I am glad we got to the bottom of this without having to bisect across three releases. Would you mind putting together a PR with that note in it?

**Comment by koecher** [comment]
@drwells I'm as well - really scary when a code which was working for years now yields into trouble (but in this case this was totally my fault). Your request is done by PR #7394.

On the other hand, I've learned that we do have 3 implementations of 'make_flux_sparsity_pattern'; and at least one have a TODO note from @tamiko for QA from 2012. (I'm sure that we can kick off at least one implementation).

Also the implementations differ in their choice of naming conventions of variables and sometimes we do have unnecessary variables inside. I'll set for that a PR as soon as possible.
