### ISSUE TITLE
Can we use triangular mesh in dealii?

### ISSUE THREAD

**Issue by chtld** [dealii/dealii#7399]
Most dealii example use rectangle mesh, did there are some examples using triangular mesh.

**Comment by drwells** [comment]
No, this is not possible: see https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-useimplement-trianglestetrahedra-in-dealii

The best one can do is to convert a tetrahedral or triangular mesh to hexahedra or quadrilaterals. These meshes are not great but they work. There is a program (tethex) on GitHub that can do this; I believe Trellis can too.

**Comment by drwells** [comment]
Since we have no support for this in deal.II itself I am going to close this issue.
