### ISSUE TITLE
matrix-free/stokes_computation fails on macOS with clang

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7407]
diff is in iteration counts:

```
DEAL:2d::Sinker problem in 2D.
DEAL:2d::n_sinker: 4       max/min viscosity ratio: 1000.00
DEAL:2d::
DEAL:2d::Number of active cells: 1024 (on 6 levels)
DEAL:2d::Number of degrees of freedom: 9539 (8450+1089)
DEAL:2d::Solved-in 19 iterations, final residual: 2.96651e-08
DEAL:2d::
DEAL:2d::Number of active cells: 4096 (on 7 levels)
DEAL:2d::Number of degrees of freedom: 37507 (33282+4225)
DEAL:2d::Solved-in 19 iterations, final residual: 1.81068e-08
DEAL:2d::
DEAL:3d::Sinker problem in 3D.
DEAL:3d::n_sinker: 4       max/min viscosity ratio: 1000.00
DEAL:3d::
DEAL:3d::Number of active cells: 512 (on 4 levels)
DEAL:3d::Number of degrees of freedom: 15468 (14739+729)
DEAL:3d::Solved-in 47 iterations, final residual: 1.67932e-08
DEAL:3d::
```

vs

```
DEAL:2d::Sinker problem in 2D.
DEAL:2d::n_sinker: 4       max/min viscosity ratio: 1000.00
DEAL:2d::
DEAL:2d::Number of active cells: 1024 (on 6 levels)
DEAL:2d::Number of degrees of freedom: 9539 (8450+1089)
DEAL:2d::Solved-in 62 iterations, final residual: 5.37736e-08
DEAL:2d::
DEAL:2d::Number of active cells: 4096 (on 7 levels)
DEAL:2d::Number of degrees of freedom: 37507 (33282+4225)
DEAL:2d::Solved-in 61 iterations, final residual: 2.94930e-08
DEAL:2d::
DEAL:3d::Sinker problem in 3D.
DEAL:3d::n_sinker: 4       max/min viscosity ratio: 1000.00
DEAL:3d::
DEAL:3d::Number of active cells: 512 (on 4 levels)
DEAL:3d::Number of degrees of freedom: 15468 (14739+729)
DEAL:3d::Solved-in 54 iterations, final residual: 2.12652e-08
DEAL:3d::
```

Probably it's better to adjust the test NOT to print iterations, instead maybe print solution at some pre-defined point.

**Comment by kronbichler** [comment]
Is this issue still happening? It is a bit scary that the 2D iteration counts are so much higher - this would suggest that this is not simply a roundoff issue but something more substantial. Can anybody else reproduce this?

**Comment by davydden** [comment]
> Is this issue still happening?

yes, I still see this issue ;-(

**Comment by kronbichler** [comment]
Is this failure in debug or release mode? Any more matrix-free tests failing or other things that could give a hint of what could go wrong? If not, I feel that we need to postpone this to the 9.2 release.

**Comment by davydden** [comment]
> Is this failure in debug or release mode or both?

both debug and release

> Any more matrix-free tests failing or other things that could give a hint of what could go wrong?

not to my knowledge.

>  If not, I feel that we need to postpone this to the 9.2 release.

agreed.

**Comment by kronbichler** [comment]
This seems to not have bothered us much, adjusting the target milestone and thus lowering priority unless we get more reports about this topic.

**Comment by peterrum** [comment]
Is this still a thing? Anyway, adjusting the milestone.

**Comment by bangerth** [comment]
Nobody has taken the time to check that this is indeed still the case over the past 4.5 years. I'm taking the liberty to close the issue -- if someone is adamant, they can always check and reopen.
