### ISSUE TITLE
Windows: Compilation error on master branch

### ISSUE THREAD

**Issue by StefanoDominici89** [dealii/dealii#7421]
I'm trying to compile the master branch, at its most recent commit, of the Deal.II on a Windows machine with Visual Studio, but the compilation process dies due to the following error:

```
dealii\include\deal.ii\base\thread_management.h(267): error C3646: 'barrier': unknown override specifier.
dealii\include\deal.ii\base\thread_management.h(267): error C4430: missing type specifier - int assumed.
```

Here is the file reporting the build configuration: [detailed.log](https://github.com/dealii/dealii/files/2553445/detailed.log)

I investigated the problem a little bit, and this is what I found out so far:

The error seems to be triggered by an unrecognized data type, namely `pthread_barrier_t`. This is odd to me, since in Windows Visual Studio `<pthread.h>` doesn't exist, and I'm not sure it makes sense, for CMake, to generate a solution inclusive of pthread-dependent code.

Prior versions of Deal.II compile without problems, so I decided to compare the `thread_management.h` files from the *master branch* and *v.9.0.1*. 
In *v.9.0.1*, It look like that the line of code causing the error are inside a block `#ifdef DEAL_II_WITH_THREADS ... #endif`. While, in the *master branch* version, the line of code causing the error is not enclosed by a `#ifdef ... #endif` guarding block anymore.

**Comment by drwells** [comment]
We recently overhauled our thread handling to use C++11 features instead of relying on POSIX features, which is why the `#ifdef` guards have changed.

I think this might be a bug in how we detect posix features. Could you please post the generated file (its in the build directory) `include/deal.II/base/config.h`?

**Comment by drwells** [comment]
@StefanoDominici89 this should now be fixed. Please post again if things don't work :)
