### ISSUE TITLE
GridGenerator images missing on web

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7437]
in particular https://www.dealii.org/developer/doxygen/deal.II/plate_with_a_hole.png

**Comment by drwells** [comment]
I have no idea why those would be missing while other new pictures (e.g., for `truncated_cone`) would show up. Are the pictures not updated automatically?

**Comment by davydden** [comment]
> Are the pictures not updated automatically?

they should, as far as I know.

**Comment by drwells** [comment]
My best guess is that the inline HTML from #7406 is confusing some script that puts up the images.

**Comment by drwells** [comment]
I don't have time to fix this now, but it should be easy to fix this by just shrinking the image itself, something like

```
convert -scale 600x1 plate.png plate.png
```

to set the width to 600px but keep the correct aspect ratio, and then revert to the common doxygen image command.

**Comment by davydden** [comment]
>  it should be easy to fix this by just shrinking the image itself

i would not do that. Internet bandwidth is cheap and high quality images are good to have in the long run.

This can be fixed later eventually.

**Comment by tjhei** [comment]
Sorry, I tested this locally of course. Let me figure out what is going on.

**Comment by tjhei** [comment]
Yeah, the image is not getting "installed" so it doesn't show up in the output directory. Fix incoming...
