### ISSUE TITLE
Update step-30

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7454]
While looking at #7212 and #7453, I realize that step-30 refers to step-12 a lot -- but at the *old* version of step-12, before the introduction of the `MeshWorker` framework there. This is confusing.

In addition, step-30 has an `assemble_system1()` and an `assemble_system2()` function in its class declaration -- but only the latter is actually implemented. I don't know what that is about.

**Comment by drwells** [comment]
I fixed this in #8044.
