### ISSUE TITLE
CUDAWrappers::MatrixFree Interface

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#7481]
I would like your opinion on how to improve the current interface of `CUDAWrappers::MatrixFree`. The particularity of `CUDAWrappers::MatrixFree` is that it only treats correctly the hanging nodes. To treat homogeneous Dirichlet boundary conditions, you need to set the constrained entries to zeros at the end of `vmult.` The current code looks like this:

```C++
Vector<double> src = my_src();
Vector<double> dst(size);

// Create MatrixFree object
MatrixFree matrix_free;
matrix_free.reinit(dof_handler, constraints, quad);

// Set all constrained dofs to zeros (Dirichlet boundary conditions
// and hanging nodes).
matrix_free.set_constraints(0., src);

// vmult
{
cell_loop(functor, src, dst);
// The constrained dofs (hanging nodes + BC) are set to zero. This gives the same results
// as SparseMatrix vmult.
matrix_free.copy_constrained_values(src, dst);
}
```

We can:
 - keep the current code
 - set the constraints inside `cell_loop` (what happens if `src` doesn't have zeros at the constrained dofs? Will it be a problem for Krylov solver?)
 - tell people to apply the constraints outside `vmult`

I am not really sure what's the best way to do that.

**Comment by davydden** [comment]
I would exclude

> tell people to apply the constraints outside vmult

from list of options.

If I am not mistaken, CPU code is essentially similar to what you have in GPU now.

**Comment by kronbichler** [comment]
I think that some variant of `copy_constrained_values` part is the way to go, or rather the `preprocess_constraints` and `postprocess_constraints` we do in `matrix_free/operators.h`, https://github.com/dealii/dealii/blob/master/include/deal.II/matrix_free/operators.h#L1427. This way one is more flexible than with including the constraints inside the `cell_loop` and on a GPU it should be pretty cheap.

**Comment by Rombur** [comment]
Thanks @davydden and @kronbichler
