### ISSUE TITLE
Output variants for clang and libc++ on failing tests

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#7500]
#7272 introduced a new `active_fe_index` inheritance paradigm for the `Triangulation` class, which broke [a few tests](https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=6089) when `clang` is used in combination with `libc++`. We have to specify dedicated output files for these tests, since they rely on which standard library is used, as pointed out in the original commit https://github.com/dealii/dealii/commit/b83b4cf3007d141474d701579cc606ea52addb2b. Thus, we need updates on:
- `tests/hp/dof_renumbering_04.output.clang-libc++`
- `tests/hp/dof_renumbering_05.output.clang-libc++`

Could someone provide these files, or give assistance on how to build `deal.II` with `clang-7.0` and `libc++-7.0`? I get horrible linker errors when trying the latter in the following configuration...
```
cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++abi" -DDEAL_II_WITH_THREADS=OFF ..
```

**Comment by masterleinad** [comment]
Configuring with
```
cmake -DCMAKE_BUILD_TYPE=Release -DDEAL_II_CXX_FLAGS=-stdlib=libc++ -DDEAL_II_LINKER_FLAGS="-stdlib=libc++ -lc++abi"
```
compiling works for me. Somehow I have a problem with the debug flags.

**Comment by masterleinad** [comment]
See #7507 for a workaround/fix for the problems with debug flags.
