### ISSUE TITLE
Incorrect assignment of boundary indicators when reading in GMSH-4 meshes

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#7501]
https://groups.google.com/forum/#!topic/dealii/NWe7cCSvP9k reports that boundary indicators are not set correctly for GMSH-4 meshes. The attached [archive](https://github.com/dealii/dealii/files/2644238/test_gmsh_4.tar.gz) shows a failing example.

**Comment by masterleinad** [comment]
Creating a gmsh-4 mesh from "grid/grids/grid_in_msh_02.msh" and testing it in `grid/grid_in_msh_02.cc`. Is actually a much better (because smaller) failing test case.
It seems that we really need to parse the `$Entities` section since the ids used for the `boundary_id` link there.

**Comment by blaisb** [comment]
The fix in #7637 completely fixes this issue on the tests I have tried.
The issue should be closed when #7637 is merged.
