### ISSUE TITLE
Behaviour of find active cell around point with artificial cells

### ISSUE THREAD

**Issue by GivAlz** [dealii/dealii#7576]
Hi everyone,
  I am sorry to have noticed this late!

== SHORT VERSION ==

If GridTools::find_active_cell_around_point is called with a distributed triangulation, on a point lying inside an artificial cell, it now throws an exception. In the past it would return the artificial cell. Did anyone decide this, or is it a side effect of something else?  ( I personally believe it happened after introducing the search for the cell using rtrees ).

I believe this is a bug as some functions now have problems because of this behaviour (e.g. https://github.com/dealii/dealii/issues/7532 is caused by this).

== ADDITIONAL PART ==

As I discussed in the mailing list, in the past "find active cell around point" would also return artificial cells, now it doesn't. Unfortunately some functions relied on the possibility of discarding points lying on artificial cells: this is why with certain configurations NonMatching::coupling_matrix_functions do not work, and it's why the GridTools::distribtued_compute_point_locations went haywire (sorry @masterleinad : I see it was you who found a way to fix the problem, while it should have really been me...then maybe I'd found out about this sooner).

I was going to propose a PR to modify GridTools::compute_point_locations so that ignores completely points which are not found, documenting this change and leaving the "responsibility" to the user (currently what happens if a point "is not found" is not documented), but @luca-heltai  pointed out it would be nice to separate between "point inside mesh but on artificial cell" and "point not found. Anywhere.".

All I in all I believe something about GridTools::find_active_cell_around_point and/or GridTools::compute_point_locations has to be done.

What do you think? Shall we make it so the rtree returns also coarse cells?

Best,
Giovanni

P.S. Here is a simple test which currently crashes because of this exception (call it with -np 4 , for example), but would behave well with deal.ii version 9.0 .

```
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/grid_tools_cache.h>
#include <deal.II/grid/tria.h>

#include <deal.II/distributed/grid_refinement.h>
#include <deal.II/distributed/tria.h>

#include <deal.II/numerics/fe_field_function.h>

#include <iostream>

#include "../tests.h"

using namespace dealii;

template <int dim>
void
test_compute_pt_loc(unsigned int n_points)
{
  deallog << "Testing for dim = " << dim << std::endl;
  deallog << "Testing on: " << n_points << " points." << std::endl;

  // Creating a grid in the square [0,1]x[0,1]
  parallel::distributed::Triangulation<dim> tria(MPI_COMM_WORLD);
  GridGenerator::hyper_cube(tria);
  tria.refine_global(std::max(8 - dim, 3));

  // Creating the finite elements needed:
  FE_Q<dim>       fe(1);
  DoFHandler<dim> dof_handler(tria);
  dof_handler.distribute_dofs(fe);

  // Creating the random points
  std::vector<Point<dim>> points;

  for (size_t i = 0; i < n_points; ++i)
    points.push_back(random_point<dim>());

  // Initializing the cache
  GridTools::Cache<dim, dim> cache(tria);

  auto   cell_qpoint_map = GridTools::compute_point_locations(cache, points);
  size_t n_cells         = std::get<0>(cell_qpoint_map).size();

  deallog << "Points found in " << n_cells << " cells" << std::endl;

  // testing if the transformation is correct:
  // For each cell check if the quadrature points in the i-th FE
  // are the same as std::get<2>(cell_qpoint_map)[i]
  for (unsigned int i = 0; i < std::get<0>(cell_qpoint_map).size(); ++i)
    {
      auto &cell      = std::get<0>(cell_qpoint_map)[i];
      if(cell->is_locally_owned())
      {
        auto &quad      = std::get<1>(cell_qpoint_map)[i];
        auto &local_map = std::get<2>(cell_qpoint_map)[i];

        // Given the std::get<1>(cell_qpoint_map) of the current cell, compute the
        // real points
        FEValues<dim> fev(fe, quad, update_quadrature_points);
        fev.reinit(cell);
        const auto &real_quad = fev.get_quadrature_points();

        for (unsigned int q = 0; q < real_quad.size(); ++q)
          {
            // Check if points are the same as real points
            if (real_quad[q].distance(points[local_map[q]]) > 1e-10)
              deallog << "Error on cell : " << cell << " at local point " << i
                      << ", corresponding to real point " << points[local_map[q]]
                      << ", that got transformed to " << real_quad[q]
                      << " instead." << std::endl;
          }
      }
    }
  deallog << "Test finished" << std::endl;
}

int
main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
  MPILogInitAll                    log;

  deallog << "Deal.II compute_pt_loc:" << std::endl;
  deallog << "On a distributed triangulation:" << std::endl;
  test_compute_pt_loc<2>(100);
  test_compute_pt_loc<3>(200);
}

```

**Comment by GivAlz** [comment]
Ok, I just pinned down the exact source of this behaviour! It has been hiding in plain sight...

Currently, find active cell around points uses `Cache<dim, spacedim>::get_used_vertices_rtree()`: we are searching only on "used vertices" thus, for a distributed triangulation, we miss the artificial cells.

I believe there are two solutions:
1) Make it so the search uses get_vertex_kdtree : then we shall accept an artificial cell as an answer of find active cell around points
2) Make it so compute point locations ignores such exceptions (and document it). Anyway with the current function output it is always possible to find out which and how many points were discarded).

Personally I like the 2nd option better, as it is more computationally more efficient (smaller tree, no effort computing qpoints on artificial cells which are not used etc.) and the user can always find out which points were problematic and decide what to do, anyway...I am ok with both solutions, as long as I can restore the functionality of nonmatchin::generate_coupling_matrix/sparsity :) 

Also I believe the behaviour of find active cell around points should be documented better for these "not found" cases (e.g. as it is now it should be noted the cell might lie on an artificial cell)

Best,
Giovanni

**Comment by masterleinad** [comment]
> Did anyone decide this, or is it a side effect of something else? ( I personally believe it happened after introducing the search for the cell using rtrees ).

I summarized the problem in #7555. Basically, the R-tree used in the `Cache` object just doesn't take artificial cells into account (opposed to `GridTools::find_closest_vertex`).

**Comment by luca-heltai** [comment]
I think this should be fixed in the extract_used_vertices. That function *should* return also artificial vertices, and my understanding was exactly this. There should be no check wether the cell is artificial or not. This should be resolved also in the compute_point_locations, i.e., we should remove the check on the fact that the cell is artificial.

**Comment by luca-heltai** [comment]
I'm not sure about this:

>  R-tree used in the Cache object just doesn't take artificial cells into account (opposed to GridTools::find_closest_vertex).

There are different cache objects. One for the vertices, and one for the cells. The one that should be used in compute_point_locations is the one for the used vertices. As stated above, if this does not contain artificial vertices, it should be considered a bug of the `extract_used_vertices`.  The function is not called `extract_locally_owned_used_vertices` after all.

**Comment by nfehn** [comment]
@luca-heltai @tamiko @kronbichler Can we close this issue since #10456 and #10514 have already been merged? It should now be clear how the algorithm deals with artificial cells
