### ISSUE TITLE
Error "lambda-expression in unevaluated context" in AssertDimension

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#7579]
@masterleinad As we discussed in #7020 a lambda expression in AssertDimension generates the error `lambda-expression in unevaluated context`

I did git bisect and I think that the PR that introduced the problem is #7494.

If you propose a solution, I'm happy to test it. I can also propose a generic code/test that reproduces the error.

The code that generated the error is:
```c++
    AssertDimension(
      [&count] {
        unsigned int size = 1;
        for (const auto &value : count)
          {
            size *= value;
          }
        return size;
      }(), data.size())
```
where count and data are std::vectors

**Comment by masterleinad** [comment]
Yes, that makes sense. We need C++20 for taking the type of an unevaluated lambda.
If possible, I prefer to rather not use lambdas in `AssertDimension` instead of reverting #7494.
In the end, this problem doesn't appear in #7020 anymore.

**Comment by dangars** [comment]
That makes sense and there are good alternatives to lambda functions, as we did in #7020. I close this issue.
