### ISSUE TITLE
Add cell->active_cell_index()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#761]
We have a lot of places where we create vectors with a number of elements equal to the number of active cells (e.g., creating error estimates, refinement criteria, generating output, etc). These are typically treated with code such as
```
  unsigned int index = 0;
  for (cell=...; cell!=tria.end(); ++cell, ++index)
    ...etc...
```
This is clumsy. Worse, it is not possible to look up the values on neighboring cells because we, in essence, can only walk through the vector in forward direction in the order in which we visit cells. This prevents us from, for example, averaging values between all neighboring cells. 

The solution is to have each active cell store not only a level index but also its index within all active cells.

**Comment by guidokanschat** [comment]
Yes!

**Comment by QiaoLei-88** [comment]
How about add some flags tuning on and off such indices just as "update_values    |  update_gradients". Maybe the active_cell_index is not always needed.

**Comment by tamiko** [comment]
@QiaoLei-88 This is a completely different context. <code>active_cell_index()</code> as described above will provide "static" information for a cell iteration and not from a <code>FEValues</code> object (that in fact does have to do expensive computation for updates).

**Comment by bangerth** [comment]
The memory consumption of the triangulation is entirely irrelevant in all problems where memory really matters. For example for Stokes in 3d, the matrix alone stores about 5kB per degree of freedom, and we have 25 degrees of freedom owned per cell. The preconditioner probably stores even more. I am not concerned about the extra 4 bytes per cell for this flag :-)

**Comment by QiaoLei-88** [comment]
The flag can also save some time. Why we generate this index when we don't need it?

**Comment by Rombur** [comment]
@QiaoLei-88 This won't save you any time.  Your code is going to spend most of its time in the solver. This kind of micro-optimizations seems nice but you gain nothing and now you have two cases to take into account. Run one of your code in a profiler and you will see that this is totally negligible.

**Comment by QiaoLei-88** [comment]
Yes. I agree this is just a tiny piece of work. I just want to follow the "lazy" pattern, which means the code will not do something until explicitely required and by default the code will stay in a lean and nice state.

**Comment by tamiko** [comment]
> and by default the code will stay in a lean and nice state.

And exactly this will not be guaranteed. With the addition of such a
flag the validity of calling active_cell_index() will depend on the fact
whether a flag was set some arbitrary time beforehand.

This adds complexity. And worse, in return, we gain very little.

**Comment by tjhei** [comment]
Do you want this index to be equal to ```distance(begin_active(), cell)```?

We should discuss if this index includes artificial cells or not. I think we made a big mistake in including artificial cells in begin_active() and I wonder if we can still change this.

Wolfgang, can you think of a way to get a cell iterator using an active_cell_index in O(1)?

**Comment by bangerth** [comment]
Yes, it's the equivalent of the `std::distance` call you have. It includes active artificial and ghost cells.

I understand your point, but I think the boat has sailed as for what these vectors represent -- they uniformly, throughout the library, reference active cells whether locally owned or not. That may have been a poor decision, but in the end it's not like it costs us a lot of memory (almost all active cells are locally owned in parallel computations) and it is consistent with sizing them by `triangulation.n_active_cells()`. I think that that is where the original sin lies: that `n_active_cells()` returns the total number of active cells, not just those that are locally owned. I don't think that that is something we can still do a lot about.

**Comment by bangerth** [comment]
OK, patch for basic functionality is submitted. I will go through the code base on occasion adjusting the following places where we currently use the active cell index by hand:
```
1/dealii> grep -r '++cell' include/ source/ examples/ | grep index
include/deal.II/numerics/vector_tools.templates.h:      for (unsigned int index=0; cell != endc; ++cell, ++index)
source/numerics/data_out.cc:  // active_index - index for a cell when counting from begin_active() using ++cell
source/numerics/error_estimator_1d.cc:       ++cell, ++cell_index)
source/dofs/dof_tools.cc:    for (unsigned int index=0; cell!=endc; ++cell, ++index)
source/grid/grid_refinement.cc:  for (unsigned int index=0; index<n_cells; ++cell, ++index)
source/grid/grid_refinement.cc:  for (unsigned int index=0; index<n_cells; ++cell, ++index)
source/grid/grid_tools.cc:         cell != triangulation.end(); ++cell, ++index)
source/grid/grid_tools.cc:         cell != triangulation.end(); ++cell, ++index)
source/grid/grid_tools.cc:         cell != triangulation.end(); ++cell, ++index)
source/grid/grid_tools.cc:         cell!=triangulation.end(); ++cell, ++index)
source/grid/grid_out.cc:       cell!=endc; ++cell, ++cell_index)
source/grid/grid_out.cc:       cell!=endc; ++cell, ++cell_index)
source/grid/grid_out.cc:  for (; cell!=endc; ++cell, ++cell_global_index)
source/grid/grid_generator.cc:             cell != tmp.end(); ++cell, ++index)
source/distributed/grid_refinement.cc:         cell != tria.end(); ++cell, ++active_index)
examples/step-28/step-28.cc:    for (unsigned int cell_index=0; cell!=endc; ++cell, ++cell_index)
examples/step-46/step-46.cc:           cell != dof_handler.end(); ++cell, ++cell_index)
examples/step-14/step-14.cc:      for (unsigned int cell_index=0; cell!=endc; ++cell, ++cell_index)
examples/step-18/step-18.cc:      for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:    for (unsigned int index=0; cell!=endc; ++cell, ++index)
```

**Comment by bangerth** [comment]
It turns out that contrary to my recollection, both `DataOut` and `KellyErrorEstimator` use other methods to keep track of which cell they're on (in the case of `DataOut`, this makes sense since we may not output data on some cells, or may indeed output from non-active cells).

So the only places that need to be converted are the tutorials.

**Comment by bangerth** [comment]
Current status:
```
> grep -n -r '++cell' include/ source/ examples/ | grep index
source/numerics/data_out.cc:339:  // active_index - index for a cell when counting from begin_active() using ++cell
source/grid/grid_generator.cc:1825:        for (unsigned int j=0; j<sizes[face]; ++j,++cell_index)
examples/step-28/step-28.cc:1096:    for (unsigned int cell_index=0; cell!=endc; ++cell, ++cell_index)
examples/step-46/step-46.cc:1001:           cell != dof_handler.end(); ++cell, ++cell_index)
examples/step-14/step-14.cc:1025:      for (unsigned int cell_index=0; cell!=endc; ++cell, ++cell_index)
examples/step-18/step-18.cc:1304:      for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:385:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:446:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:469:        for (unsigned int index=0; cell!=endc; ++cell, ++index)
examples/step-27/step-27.cc:756:    for (unsigned int index=0; cell!=endc; ++cell, ++index)
```
