### ISSUE TITLE
add GridGenerator::quarter_plate_with_a_hole()

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7649]
same as GridGenerator::plate_with_a_hole() but only a quarter (or 1/8). A connivence function that should have correct manifolds set at the end. This requires to first have a 2D quarter mesh and then do extrusion while keeping manifolds. But still very straight-forward.

**Comment by drwells** [comment]
Users can construct this from `plate_with_a_hole` by deleting the cells they don't want, so lets close this unless someone wants to implement the specialized function.
