### ISSUE TITLE
Bug in distribute_local_to_global with inhomogeneities

### ISSUE THREAD

**Issue by starki0815** [dealii/dealii#7658]
I noticed the following:

If I distribute a local matrix having all its diagonal entries zero (which happens e.g. for Lagrangian multiplier terms) with `constraints.distribute_local_to_global(local_matrix, local_vector, local_dof_indices, global_matrix, global_vector, use_inhomogeneities_for_rhs)` to the global matrix, the diagonal elements of constrained dof's are set to zero in the global matrix; and if there is no contribution to these diagonal elements from somewhere else, this results in a singular global matrix.

I think the reason for this behavior is that the values of the diagonal elements associated with constrained dof's are set equal to the average of the absolute values of the diagonal elements of local_matrix in the function set_matrix_diagonals(), which just yields zero in this particular case.

My suggestion would be to modify the function set_matrix_diagonals() such that it computes the magnitude of the diagonals from some norm of the local matrix divided by the size of the matrix in case that the average of the absolute diagonal values is zero.

**Comment by masterleinad** [comment]
Do you have a minimal example code that shows the problem?

**Comment by starki0815** [comment]
Sure, here's a small example:

```c++
#include <iostream>
#include <stdio.h>
#include <deal.II/lac/affine_constraints.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/vector.h>

using namespace dealii;
using namespace std;

int main(){

	// test problem: solve Pi = a^2 + 2*a*b -> Min., s.t. b=1
	//
	// dof's: (a b)
	//
	// Hessian:
	//                          (1   0)     (0   1)     (1   1)
	//          H = H_0 + H_1 = (     )  +  (     )  =  (     )
	//                          (0   0)     (1   0)     (1   0)
	//
	//                                (0)     (0)     (0)
	// RHS:     RHS = RHS_0 + RHS_1 = ( )  +  ( )  =  ( )
	//                                (0)     (0)     (0)

	// constrained Hessian should be (with a constant c!=0):
	//                 (1   0)
	//          H_c =  (     )
	//                 (0   c)
	//
	// constrained RHS should be:
	//                   (-1)
	//          RHS_c =  (  )
	//                   ( c)

	// BUT:
	//
	// actual result for constrained Hessian is:
	//                 (1   0)
	//          H_c =  (     )
	//                 (0   0)
	//
	// actual result for RHS is:
	//                   (-1)
	//          RHS_c =  (  )
	//                   ( 0)
	//

	//set up constraint b=1
	AffineConstraints<double> constraints;
	constraints.add_line(1);
	constraints.set_inhomogeneity(1,1.);
	constraints.close();

	//constrained Hessian and RHS
	FullMatrix<double> H_c(2);
	Vector<double> RHS_c(2);

	//first part: H_0 and RHS_0 (as the second row and column of H_0 are anyway zero, these need not be included):
	FullMatrix<double> H_0(1);
	H_0(0,0)=1.;
	Vector<double> RHS_0(1);
	constraints.distribute_local_to_global(H_0, RHS_0, {0}, H_c, RHS_c, true);

	//second part: H_1 and RHS_1
	FullMatrix<double> H_1(2);
	H_1(1,0)=H_1(0,1)=1.;
	Vector<double> RHS_1(2);
	constraints.distribute_local_to_global(H_1, RHS_1, {0, 1}, H_c, RHS_c, true);

	//output the actual constrained Hessian and RHS
	cout << "H_c = \n";
	for(unsigned int m=0; m<H_c.m(); ++m){
		for(unsigned int n=0; n<H_c.n(); ++n)
			printf(" %- 1.2e ", H_c(m,n));
		cout << endl;
	}
	cout << "\nRHS_c = \n";
	for(unsigned int m=0; m<RHS_c.size(); m++)
		printf(" %- 1.2e\n", RHS_c(m));
}
```

**Comment by masterleinad** [comment]
> My suggestion would be to modify the function set_matrix_diagonals() such that it computes the magnitude of the diagonals from some norm of the local matrix divided by the size of the matrix in case that the average of the absolute diagonal values is zero.

That sounds reasonable, maybe even just setting them to one is appropriate in this case (what would you want to do if all the local matrix entries are zero?). Do you want to give it a try yourself and write a pull request?

**Comment by bangerth** [comment]
I agree that this seems like a sensible idea. I would like to keep the current values if the sum of the absolute values of the diagonal is not zero, so as to remain backward compatible for the common case.

Like @masterleinad I'd like to encourage you to try out whether you can come up with a patch yourself. We will of course do our best to help! Have you taken a look at the links you can find under the "Contribute" button on the website?

**Comment by bangerth** [comment]
Ah, I forget that you're already a seasoned contributor to deal.II :-) Of course you already know how to do all of this!

**Comment by starki0815** [comment]
@bangerth For myself I have already fixed it the way you have suggested it: Only if the sum of the absolute diagonals is zero, I use the l1 norm of the local matrix divided by the size of the local matrix for what is added to the diagonal of the global matrix. This is not only backward compatible but will also (hopefully) avoid breaking too many tests.

@masterleinad In case the l1 norm is zero (i.e., the entire local matrix is zero), I am just adding 1. 

I'll create a pull request for the patch asap.

**Comment by bangerth** [comment]
Thanks very much, @starki0815 !
