### ISSUE TITLE
Windows: Compilation error on master branch

### ISSUE THREAD

**Issue by StefanoDominici89** [dealii/dealii#7673]
I'm trying to compile the library, at the most recent commit of master branch, and the compilation process fails due to a bunch of compilation errors, with messages of type `error C2131: expression did not evaluate to a constant`.

Inspecting the code, turns out that all errors come from line 181 of file `include/deal.II/base/vectorization.h`: `static const unsigned int n_array_elements;`. 
This line declares `n_array_elements` for the unspecialized template class `VectorizedArray`, but does not define any value for it. The value for `n_array_elements` for the unspecialized template class `VectorizedArray` is defined later in the same file, at line 456 .

Apparently, windows compiler (msvc  v.19.00.24215.1) doesn't recognize the variable definition outside the class body, and issues an error for all occurrences of `VectorizedArray<Number>::n_array_elements` stating that it's not a compile time constant.

The first thought I had was to comment the definition at line 456, and just modify line 181 to define the constant inside the class body as `static const unsigned int n_array_elements = 1;`.
However, even if the compilation doesn't fail anymore, I'm afraid that msvc may misunderstand every occurrence of `VectorizedArray<Number>::n_array_elements` with 1, instead of looking for the appropriate value once the class using `VectorizedArray<Number>` is instantiated for different values of type `Number`.

**Comment by StefanoDominici89** [comment]
I'm going to run some tests in order to check the sanity of the in-class definition and check whether substitutions are properly implemented at compile time.

**Comment by Rombur** [comment]
`nvcc` and `msvc` want different things :( relates to #7650

**Comment by StefanoDominici89** [comment]
@Rombur , Thanks for pointing it out! I wasn't aware of that issue.

**Comment by masterleinad** [comment]
See #7672.

**Comment by StefanoDominici89** [comment]
@masterleinad , thanks! This issue is redundant, I'm going to close it.
