### ISSUE TITLE
OpenMPI-4.0 dropped MPI-1 standard support

### ISSUE THREAD

**Issue by pratikvn** [dealii/dealii#7676]
I was trying to compile with OpenMPI-4.0 and it seems that they have dropped support for MPI1 standard routines from 4.0 ([Reference](https://www.open-mpi.org/faq/?category=mpi-removed)) and hence deal.II does not compile with OpenMPI-4.0.

The only function that deal.II uses from MPI-1 standard seems to be [MPI_Type_struct](https://github.com/dealii/dealii/blob/master/source/base/mpi.cc#L451).This function seems to be deprecated in OpenMPI from version 2.0 and all other implementations seems to support its alternative and recommended version [MPI_Type_create_struct](https://www.open-mpi.org/doc/v3.0/man3/MPI_Type_create_struct.3.php).

The fix is to just replace MPI_Type_struct with MPI_Type_create_struct. The arguments and everything else remains the same.

If this is an already known issue, please feel to delete this.  

Thanks.

**Comment by drwells** [comment]
I do not think this has been reported before (that release is very new; I have not switched to it yet and I doubt any of the other principal developers have either).

Thanks for reporting this (and for all the links); it should now be easy to fix.

**Comment by davydden** [comment]
I use 4.0 build by Spack, IIRC one can enable deprecated interface using some flags.

**Comment by bangerth** [comment]
@pratikvn -- do you want to give writing a patch a try? We'd be happy to help you with it, and appreciate anyone who helps with the project!

**Comment by bangerth** [comment]
Ah, I come too late -- @drwells already did the necessary patch in #7677 :-)
