### ISSUE TITLE
a base class to provide interface for FEEvaluation complied vector?

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7684]
currently the read/write access to elements in a vector within `FEEvaluation`  class is done using templated functions (with sensible defaults)
```
  template <typename VectorType>
  inline typename VectorType::value_type &
  vector_access(VectorType &vec, const unsigned int entry)
  {
    return vec(entry);
  }

  template <typename Number>
  inline Number &
  vector_access(MyFavoriteVector<Number> &vec,
                const unsigned int                                entry)
  {
    return vec.local_element(entry);
  }
```
and an auxiliary class `VectorReader`:
```
template <typename Number>
  struct VectorReader
  {
    template <typename VectorType>
    void
    process_dof(const unsigned int index, VectorType &vec, Number &res) const
    {
      res = vector_access(vec, index);
    }
....
}
```

What do you think if we try to move such interfaces / operations into a base vector class like `MatrixFreeVector` so that any class to be used with `FEEvaluation` should provide that interface? Things should still stay templated with the vector type, we just add a static assert that a vector is derived from the base class. 

That would also be an opportunity to document this interface and the different ways/circumstances DoFs are being read from a vector.

The downside is that we kind of expose internal implementation of `FEEvaluation` but it also makes life much more easier to add new vectors. It also makes vectors themselves responsible for providing the interface as opposed to internal structures in `FEEvaluation` to switch to the right function based on the given vector class.

EDIT: another advantage is that one can test the interface separately outside of the `FEEValuation` machinery. 

EDIT2: we can also keep this interface `private` and make `FEEValuation` a friend to be flexibly with adjusting it along the way, if needed.

**Comment by davydden** [comment]
this is similar to https://github.com/dealii/dealii/issues/7187 and `internal::VectorDataExchange`

**Comment by kronbichler** [comment]
While I see the need for allowing a user to transparently select one path or another in `FEEvaluation`, I struggle a bit with adding a particular need of a downstream class such as `FEEvaluation` to our generic vector classes. After all, matrix-free implementations with their need for fast vector access are a particular application and not all of deal.II.

The questions to be transported to the user and, if used with a separate vector class, are in my opinion:
- Do we have an `update_ghost_values()` and `compress()` functionality, either via blocks or in plain format
- Do we have a `local_element()` function for fast access
- Can we use `vec.begin()+offset` equivalently to `vec.local_element(offset)`

The last item is less important in the sense that it affects only performance, not functionality. I think we could capture the two first with some `std::enable_if` magic (but I have not thought closely about it), which is less invasive and yet provides the desired result.

A side remark is the fact that we currently access `vec(entry)` for generic non-`LA::dist::Vector` classes, which is at least wrong for distributed Trilinos and PETSc vectors. If we think about fixing interfaces up, we should also keep those in mind.

**Comment by davydden** [comment]
Right now I was more interested in non-MPI parts of matrix-free (just reading/writing into the vector inside FEEvaluation). I would say it's less about

> While I see the need for allowing a user to transparently select one path or another in FEEvaluation

but rather make requirements for vector classes to be used with FEEvaluation more straight-forward. Primarily for development and not for users.

So if we just focus on `local_element()` and `begin()+offset`,  could not we make our vector classes provide 
```
static const bool supports_local_element = true;
```
and 
```
static const bool supports_begin_offset_access = true;
```
and then based on that do the right thing in `FEEValuation`? 

Currently, we have custom implementation for vectors that support `local_element()`, i.e. 
```
  template <typename Number>
  inline Number &
  vector_access(LinearAlgebra::distributed::Vector<Number> &vec,
                const unsigned int                          entry)
  {
    return vec.local_element(entry);
  }
```
This means that every new vector that support `local_element()` should be forward-declared in this header and its accessor should be added.  I am just looking for ways of improving this part so that there is no need to list any vectors in `fe_evaluation.h`.

**Comment by kronbichler** [comment]
But couldn't we do the functionality of `static const bool supports_local_element = true;` via an `std::enable_if` variant? It does not help the development I fear, but it would avoid a boolean which simply tells us that there is a function with the same name in some of our vector classes. I generally like to your idea, but I want to not go too deep into the basic vector classes if there is an acceptable solution somewhere else.

**Comment by davydden** [comment]
> It does not help the development I fear

I think it would, because all `FEEvaluation` and friends would need to know are those two values. They would not need to know that there exist a `LA::d::Vector` or `TrilinosWrappers::...` or `PetscWrappers::...` or anything else. All decisions and branching for the right implementation of functions like `process_dofs_vectorized_transpose` should be doable based on these two flags.

**Comment by davydden** [comment]
I think we can test for existence of `local_element` (and whatever else we needed) with SFINAE
```
template<typename T> struct has_local_element 
{
   private:
    // this will work always
    static int detect(...);
    // this detecter will work inly if we have local_element()
    template<typename U> decltype(std::declval<U>().local_element(u0)) detect(const U&);
  public:
    static constexpr bool value = std::is_same<void, decltype(detect(std::declval<T>()))>::value;
};
```

then I think one can simplify the code in `FEEvaluation` without forward-declaring specific vector types (and also providing custom implementation functions) and on another avoid introducing `static const bool`. 

What do you say @kronbichler ?

**Comment by kronbichler** [comment]
@davydden This is exactly what I've been thinking about in my previous posts :+1: Do you want to try this?

**Comment by davydden** [comment]
Yes, i will give it a try this week.
