### ISSUE TITLE
Change behavior of 'make debug' and 'make release'

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7693]
https://github.com/geodynamics/aspect/pull/2800 is about an issue that has bugged me for a very long time already in ASPECT: When you call `make debug`, it switches to debug mode *and* re-compiles everything. This is fine if you have a tutorial with just one source file, but if you have a project with 263 source files this is annoying *because cmake compiles everything with `-j1`*. So it's exceedingly slow.

Might I suggest that we change the behavior of `make debug` and `make release` to just *switch* to the respective mode, delete the executable (to avoid anyone using it), and then asking the user to explicitly compile again?

(I'm apparently not the only one who has their own workaround to this issue -- @tjhei has as well: https://community.geodynamics.org/t/makefile-multiple-processor-issue/413?u=bangerth )

**Comment by tjhei** [comment]
The main usage for the autopilot is for deal.II tutorial steps. As there is no parallel compilation needed (or possible), it is not a problem there, I think. So, maybe "don't use autopilot for big projects" is the simplest solution to this?

**Comment by bangerth** [comment]
@tjhei: Yes, that's likely true. But I do think that we advertise the use of the autopilot in the sample "large project" cmake files.

**Comment by masterleinad** [comment]
Why not extra targets like `switch_to_release` and `switch_to_debug`?

**Comment by drwells** [comment]
It might be possible to get around this with ninja and newer versions of CMake via the new (in 3.12) `--parallel` option: 

> -j [\<jobs\>], --parallel [\<jobs\>]
> The maximum number of concurrent processes to use when building. If \<jobs\> is omitted the native build tool’s default number is used.

see

https://cmake.org/cmake/help/latest/manual/cmake.1.html

I don't think it is possible to get this to work in `make`, though; I haven't yet (see also #7143) been able to figure out a way to propagate `-jN` through `make` to `cmake` and back to `make` in this setting.

**Comment by tamiko** [comment]
Well, the one responsible for this behavior in `DEAL_II_INVOKE_AUTOPILOT` is me *cough*. I think there was little thought that went into deciding this - originally this macro was only meant for really small projects (based on example steps).

That said, I don't see anything speaking against changing the behavior. The `debug` and `release` targets are probably used overwhelmingly in the following way:
```
make debug|release
make run
```
And here it doesn't really matter where the project is compiled.

**Comment by masterleinad** [comment]
...unless you are using `MPI`. :wink:

**Comment by tamiko** [comment]
@masterleinad Huch? The depend line should ensure that the executable is always built prior to `make run`. Does this not work?
```
   93     ADD_CUSTOM_TARGET(run                                                        
   94       COMMAND ${_command}                                                        
   95       DEPENDS ${TARGET}                                                          
   96       COMMENT "Run ${TARGET} with ${CMAKE_BUILD_TYPE} configuration"             
   97       )
```

**Comment by masterleinad** [comment]
No, I wanted to say that you usually don't invoke `make run` for applications that use `MPI`.

**Comment by tjhei** [comment]
In https://github.com/geodynamics/aspect/pull/2800 I changed debug and release to not build but print a big comment about having to build. Maybe worth including here?

**Comment by tamiko** [comment]
@tjhei I added your these messages to the pull request.

**Comment by bangerth** [comment]
Nice, thanks @tamiko !
