### ISSUE TITLE
Step-61: Improve grammar and language

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7712]
@masterleinad @drwells @bangerth all promised to have another look at grammar, language and exposition in step-61

**Comment by drwells** [comment]
It looks like the images for this example step are not online.

**Comment by bangerth** [comment]
The pictures are now online and there were patches for introduction and results sections that addressed language and grammar (linked to from the original step-61 PR). What's still necessary are some edits to the program itself.

**Comment by bangerth** [comment]
I've fixed this with a long sequence of PRs all linked to from #6455. The last one is #8035.
