### ISSUE TITLE
No doxygen for BoundingBox::NeighborType enumerator

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7730]
[subj](https://www.dealii.org/developer/doxygen/deal.II/classBoundingBox.html#a62544200c2e2498fc07845eb3f2c44fa).

**Comment by kronbichler** [comment]
Uncritical, postponing for the 9.2 release.

**Comment by bangerth** [comment]
As reported by @peterrum over at #9486:

> The following enum classes seem to make also problems: Storage, ComponentExtractor and SIMDComparison...

**Comment by bangerth** [comment]
I've tried to figure out what's going on here several times but can't seem to make progress. There is no error in `doxygen.log`, and no other indication of what's going wrong. I've also tried to replace the `enum class` by `enum` or `class` to see whether doxygen likes that better, but the answer is no for `enum`. For `class`, it seems to work, but that's of course not useful. I'm not sure what we should do.

**Comment by tjhei** [comment]
I changed the settings
```
--- a/doc/doxygen/options.dox.in
+++ b/doc/doxygen/options.dox.in
@@ -39,12 +39,12 @@ BUILTIN_STL_SUPPORT    = YES
 # Build related configuration options
 #---------------------------------------------------------------------------
 
-EXTRACT_ALL            = NO
+EXTRACT_ALL            = YES
 EXTRACT_PRIVATE        = YES
 EXTRACT_STATIC         = YES
 EXTRACT_LOCAL_CLASSES  = YES
-HIDE_UNDOC_MEMBERS     = YES
-HIDE_UNDOC_CLASSES     = YES
+HIDE_UNDOC_MEMBERS     = NO
+HIDE_UNDOC_CLASSES     = NO
 SORT_MEMBER_DOCS       = NO
```
and now it shows up for me. I am not sure which of those settings did it, though. Worth changing the defaults for?

**Comment by bangerth** [comment]
Which of these settings is it?

**Comment by tjhei** [comment]
I played with this some more (including other extract_* flags we don't have in our options, setting ``@file``, settings ``@relates``, etc.): The only thing that makes this enum show up is ``EXTRACT_ALL=YES`` or putting it into a namespace (*).
*: we delete the "namespace dealii{" for doxygen, which makes this enum a global symbol. A workaround would be to move it into a namespace (or class scope).
Or, we could just enable ``EXTRACT_ALL``?
