### ISSUE TITLE
doxygen doesn't run any more

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7737]
The doxygen portion of the website is no longer updated -- the page at
https://dealii.org/developer/doxygen/deal.II/index.html
states that the last update happened on Feb 8. Can someone check what is happening?

**Comment by bangerth** [comment]
See also #7740.

**Comment by bangerth** [comment]
Indeed, #6455 (step-61) was merged on Feb 8.

**Comment by bangerth** [comment]
Hm, #7740 didn't help :-(

**Comment by masterleinad** [comment]
Maybe, #7741 did?

**Comment by bangerth** [comment]
Hm, still not. I guess someone will have to take a look at the logs there :-(

**Comment by kronbichler** [comment]
It seems to be up again. I'm closing.
