### ISSUE TITLE
Refactor DEAL_II_WITH_CUDA_AWARE_MPI into a non DEAL_II_WITH variable

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7758]
Umh, I somehow missed this.
The fact that `DEAL_II_WITH_CUDA_AWARE_MPI` is a "feature" variable is in my opinion a bit suboptimal. We have a number of features (such as CUDA) that have some subordinate configuration options. Would it be possible to refactor `DEAL_II_WITH_CUDA_AWARE_MPI` into an option `DEAL_II_CUDA_WITH_MPI` and configure it together with `DEAL_II_WITH_CUDA`? (In short I would like to see that a feature, i.e. something with `DEAL_II_WITH` should only refer to an external/internal feature - such as an external library).

@Rombur @masterleinad *ping*

**Comment by masterleinad** [comment]
This is rather a `MPI` feature than a `CUDA` feature. I would be fine calling it `DEAL_II_MPI_WITH_CUDA_AWARENESS` or the like.

**Comment by tamiko** [comment]
@masterleinad Sounds good. What exactly do we need to eventually autodetect `MPI_WITH_CUDA_AWARENESS` in `FindMPI.cmake`? (Configure CUDA before MPI?)

**Comment by masterleinad** [comment]
This feature is not autodetected but must be set by the user and requires both `MPi` and `CUDA` support.

**Comment by masterleinad** [comment]
Would just renaming the option be fine for you?

**Comment by tamiko** [comment]
> Would just renaming the option be fine for you?

Absolutely. :-)

I planned to rename it to something other than "DEAL_II_WITH" and move
it either to the mpi or cuda configuration files under cmake/configure
