### ISSUE TITLE
Tutorial graph is no longer built

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7778]
Well, it's almost 1am here and I have a meeting at 7:30am so I'm not going to investigate this now -- but the tutorial graph at
https://dealii.org/developer/doxygen/deal.II/Tutorial.html#TutorialConnectionGraph
no longer shows.

Looking a bit further, no graphs seem to be built:
https://dealii.org/developer/doxygen/deal.II/classSparsityPattern.html
https://dealii.org/developer/doxygen/deal.II/classFiniteElement.html
I wonder whether the invocation of graphviz by doxygen no longer works -- is graphviz no longer installed on that system?

**Comment by masterleinad** [comment]
Fixed. We had to install graphviz again.
