### ISSUE TITLE
Don't check for noexcept for move constructors in clang-tidy CI task

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7779]
As shown here https://github.com/dealii/dealii/pull/7767#issuecomment-469287503, the clang-tidy step of the continuous integration framework apparently requires move constructors be annotated as noexcept. But that leads to ugly workarounds if such a constructor is also marked `=default`.

I'm not sure this clang-tidy step adds anything useful. Should we get rid of it so as to simplify the code?

**Comment by masterleinad** [comment]
I would rather just disable the check locally via
```
// NOLINT
```
for these special cases.

**Comment by tjhei** [comment]
If you want to permanently remove a check, see https://github.com/dealii/dealii/blob/master/.clang-tidy

**Comment by bangerth** [comment]
Seems not worth bothering with.
