### ISSUE TITLE
TPetra detection and MPI compilers

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#7790]
when I am configuring deal.II with
```
cmake -D DEAL_II_WITH_MPI=ON ....
```
the TPetra check from #7180 fails:
Performing C++ SOURCE FILE Test TRILINOS_TPETRA_IS_FUNCTIONAL failed with the following output:
```
/usr/bin/ld: CMakeFiles/cmTC_e739a.dir/src.cxx.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
```
which is caused by not using the OpenMPI compiler wrappers (or link flags, etc.).

Note that the check works if I do
```
CXX=mpicxx CC=mpicc cmake [....]
```

I tried modifying https://github.com/dealii/dealii/blob/master/cmake/configure/configure_2_trilinos.cmake#L176
by adding
```
      LIST(APPEND CMAKE_REQUIRED_LIBRARIES ${MPI_LIBARARIES})
```
but it turns out those are empty.

I have never specified the wrappers explicitly in the past and things worked. Am I just doing things "wrong"?

**Comment by tjhei** [comment]
@masterleinad How does that work for you?

**Comment by masterleinad** [comment]
Hmm... I often configure with some kind of compiler wrapper as `CMAKE_CXX_COMPILER`, but also without it, `Tpetra` is detected correctly for me. See the attached [detailed.log](https://github.com/dealii/dealii/files/2952618/detailed.log).

**Comment by masterleinad** [comment]
```
[...]
-- Found TRILINOS
 -- Check whether the found trilinos package contains all required modules:
 -- Found Amesos
 -- Found Epetra
 -- Found Ifpack
 -- Found AztecOO
 -- Found Teuchos
 -- Found ML
 -- Found MueLu
 -- Found EpetraExt
 -- Module ROL not found!
 -- Found Sacado
 -- Found Tpetra
 -- Found Zoltan
 -- Looking for KOKKOS_ENABLE_CUDA_LAMBDA
 -- Looking for KOKKOS_ENABLE_CUDA_LAMBDA - not found
 -- Performing Test TRILINOS_TPETRA_IS_FUNCTIONAL
 -- Performing Test TRILINOS_TPETRA_IS_FUNCTIONAL - Success
 -- Found SACADO_CONFIG_H
 -- Found SACADO_TRAD_HPP
 -- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
 -- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD - Failed
 -- DEAL_II_WITH_TRILINOS successfully set up with external dependencies.
[...]
```

**Comment by tamiko** [comment]
@tjhei Is this still current? Or can we close?

**Comment by tjhei** [comment]
I have no idea how to reproduce, so let's close.
