### ISSUE TITLE
deal.II Release 9.1 5/17/2019

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#7809]
We plan for the 9.1 release on May 17, 2019. Given our experience in #6618, we plan to close the time window for contributions on **May 10, 2019**, which is when we branch off for the release and only allow bug fixes. May 10 is also the time limit set for the 9.1 release milestone.

This issue will keep track of our progress towards the release so that everyone can adapt to the timing. As the release date comes closer, we will list the specific progress in our release list similarly to #6156.

**Comment by kronbichler** [comment]
We currently still have a long list of issues open for the 9.1 release here: https://github.com/dealii/dealii/milestone/6

Since we set today as the last day for feature contribution to the release, we ought go through this list and re-prioritize. Most of the topics, apart from those where we have PRs open, are uncritically and should be moved to the 9.2 release milestone. Unless someone actively reports the status on some of those topics, I will go through that list later today.

**Comment by kronbichler** [comment]
I'm done with my iteration through open issues/prs for the 9.1 milestone. We have around a dozen of things in flight which I believe could go in, and a few more topics where we will get opinion of the developers soon (those have been active today). One big topic is the AD/symbolic differentiation of @jppelteret where I'd like to ask what the status is. Otherwise I think we have a manageable amount of open topics before we close the merge window by the end of today/early tomorrow in my time zone. Please post additional topics to be included at this page.

**Comment by kronbichler** [comment]
Regarding our unfinished tutorial programs (besides step-64 which I'm optimistic will be ready).

- @tjhei @tcclevenger step-63 is still noted as work in progress: I assume this will not be finished for the 9.1 release?
- Otherwise, we also have step-50 as unfinished tutorial, which will remain so.

**Comment by tjhei** [comment]
> * is still noted as work in progress: I assume this will not be finished for the 9.1 release?

we are really close (writing documentation currently). If you insist on the cutoff of today, then no, we won't be able to finish.

> * Otherwise, we also have step-50 as unfinished tutorial, which will remain so.

This is planned for this summer.

**Comment by kronbichler** [comment]
> we are really close (writing documentation currently). If you insist on the cutoff of today, then no, we won't be able to finish.

If it is mostly documentation, we can still cherry-pick it into the branch. Feel free to go ahead and open a PR (even if unfinished) later today so we have it on the radar. The important aspect is that we won't have too many code changes that might trigger various configurations.

**Comment by tcclevenger** [comment]
> > we are really close (writing documentation currently). If you insist on the cutoff of today, then no, we won't be able to finish.
> 
> If it is mostly documentation, we can still cherry-pick it into the branch. Feel free to go ahead and open a PR (even if unfinished) later today so we have it on the radar. The important aspect is that we won't have too many code changes that might trigger various configurations.

@kronbichler @tjhei: I will be finished with the documentation fully (at least for you guys to comment on) by the end of the weekend. I will go ahead and create the pull request this afternoon.

**Comment by kronbichler** [comment]
See #8080 for the release progress.

**Comment by tamiko** [comment]
Ah, I missed this issue, @kronbichler shall we close one of the issues? (I suggest to keep #8080 open - it has a catchy number).

**Comment by kronbichler** [comment]
@tcclevenger it's fantastic that you make the final push - this gives us 4 new tutorials!

**Comment by kronbichler** [comment]
> shall we close one of the issues?

I suggest we close this issue once we have made the branch - this keeps the deadline (in case anyone has missed it) open (without cluttering the other issue with such boring details).

**Comment by tamiko** [comment]
Outstanding:
 [ ] #8012
 [ ] #8033
 [ ] #8072
 [ ] #8075
 [ ] #8079
Documentation:
 [ ] #7823
 [ ] #8060

**Comment by masterleinad** [comment]
Doing a review for #8033 now.

**Comment by jppelteret** [comment]
Great, although its super late here I'll try to stay up to address @masterleinad's comments before going to Club Duvet.

**Comment by tamiko** [comment]
Closing! I think we can keep track of #8079 and #8139 without this Issue :-D
