### ISSUE TITLE
Edit step-22 InverseMatrix discussion

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7812]
Followup to #4977: step-20 got converted but step-22 still talks about the old implementation in step-20.

**Comment by kronbichler** [comment]
We won't be able to do this for the current release, adjusting target milestone.

**Comment by drwells** [comment]
Would it be ok if I put up a patch for this late tonight, or would that count as outside the merge window?

**Comment by kronbichler** [comment]
I would be fine with that, yes.
