### ISSUE TITLE
AMD GPU support

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#7821]
Someone asked me about deal.II support for AMD GPU recently, so I looked how we could support both type of GPUs. The good news is that HIP C++ (AMD's language) is extremely close to CUDA. Many CUDA functions have an equivalent in HIP C++ for example: `cudaMalloc` and `hipMalloc` and all of our kernels are mostly compatible with both languages (the only thing that is not compatible is that `threadIdx.x` becomes `hipThreadIdx_x`). There are a few things that HIP C++ doesn't support that CUDA supports, the big one is UVM but we don't use it. So I think that at least for `MatrixFree` there is a way to support both GPUs with some small refactors. For the `SparseMatrix`, we use CUDA libraries so it would require more work. I see two ways forward: 

1. We encapsulate the CUDA code and provide an HIP C++ version of the code
2. AMD provides a script that automatically transform CUDA code in HIP C++. So we could just keep most of our CUDA code unchanged and just make sure that the script is able to convert all the CUDA code.

Personally, I prefer solution 2. I think it will be less work and since I don't have access to an AMD GPU, there is no way to check that the code we would write is correct. Of course there is still the problem of the `#if DEAL_II_WITH_CUDA`, some should be kept some should be changed but at least it is a step in the right direction. What do you all think?

**Comment by masterleinad** [comment]
The second approach sounds more favorable for me as well. From playing around with `HIP` a bit, it seems that the code generated by `hipify` can still be compiled by `nvcc` provided the `rocm` headers can found in the include directories. We then only have to make sure that these always exist when we compile with `CUDA` support, i.e. we should bundle `HIP`. Otherwise, we would break `CUDA` support for people only having `nvcc`.

We still need to try if all the code can be converted, though.

**Comment by Rombur** [comment]
The way I see it we wouldn't change much for CUDA. If someone wants to use AMD, she would have to run `hipify` and then compile. Our job would be to make sure that the `HIP` conversion step works. I don't want everybody to have to use `hipcc` if they don't need to. It's already a pain to get `cmake` and CUDA to work on every platform, I don't want to make that more complicated than it is.

**Comment by masterleinad** [comment]
I just tried. At least, it doesn't work out of the box to compile using `hipcc` or `nvcc` after running `hipify`. I guess we need to write some kind of tutorial once someone has successfully done that.

**Comment by jppelteret** [comment]
Here's a totally naive question: Is it possible to abstract out things like `threadIdx.x` into a set of global functions like `get_threadIdx_x()`? This would then have different definitions based on which GPU brand is being  compiled for.

**Comment by masterleinad** [comment]
That is certainly possible, but probably only worth it if we plan to support another `GPU` brand fully.

**Comment by Rombur** [comment]
> I just tried. At least, it doesn't work out of the box to compile using hipcc or nvcc after running hipify. 

That's expected, we do use a few features that are not supported by `hipcc` but most of the code should be fine.

> Is it possible to abstract out things like threadIdx.x into a set of global functions like get_threadIdx_x()?

Yes, that's basically the option (1) that I described before. If that's the way we want to go I am fine with it, it's just that it's basically what `hipify` does. So writing wrapper is more work.

**Comment by jppelteret** [comment]
> Yes, that's basically the option (1) that I described before. If that's the way we want to go I am fine with it, it's just that it's basically what hipify does. So writing wrapper is more work.

Thanks for the explanation! OK, well then I'm fully on board with option (2). I think that it would be fantastic if we could somehow be brand-agnostic with our GPU support.

**Comment by masterleinad** [comment]
If someone is interested, https://github.com/masterleinad/dealii/tree/hipify_deal_ii is a branch that compiles after calling `hipify` and fixing up some issues.

**Comment by Rombur** [comment]
Very nice! I think we should see if we can get the fixes that you did by hand in master. Let's not worry about the changes in boost.

**Comment by drwells** [comment]
Do we still need to keep this open?
