### ISSUE TITLE
Deprecate all functions acting on meshes in GridGenerator. Move them to GridTools

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#783]
The GridGenerator namespace contains functions which *create* grids from scratch. All tools that *manipulate* grids (either extracting part of a grid, or flattening, etc.) should be marked deprecated in GridGenerator and moved to GridTools.

**Comment by bangerth** [comment]
Agreed. Do you have a list of functions?

**Comment by luca-heltai** [comment]
I think these belong to `GridTools`

- merge_triangulations
- create_union_triangulation
- create_triangulation_with_removed_cells
- extract_boundary_mesh
- flatten_triangulation

**Comment by bangerth** [comment]
But all of these five create a new triangulation from existing ones, not just modify an existing one. Why do you want to move them?

**Comment by luca-heltai** [comment]
Good point. Then it's perfectly fine to have them there. I didn't see it that way, but I guess it makes sense.
