### ISSUE TITLE
ArrayView:  default constructor and reinit() 

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7882]
Anything speaks against having `ArrayView::ArrayView()` and `ArrayView::reinit(...)`? 

I am interested in storing a vector of objects, where each object contains a view to a data structure. Currently I am forced to wrap `ArrayView` into a shared pointer, but given that this class does nothing else but stores a pointer and size, I would say we could have a default constructor and `reinit()` methods.

**Comment by bangerth** [comment]
I tend to think of these objects as created on the fly, and so never thought that a function `reinit()` might be useful. But I see no reason not to add one.

**Comment by drwells** [comment]
We already check to see if we have an empty array view so I don't see any reason why we could not add a default constructor.

**Comment by davydden** [comment]
Ok, given that there seem to be no objection, I will look into doing this... The only change is that private attributes (i.e. `size`) will loose constness once we add `reinit()`.
