### ISSUE TITLE
LAPACK_INCLUDE_DIRS is not used in downstream projects

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7883]
I have problem building downstream code with `dealii+gcc+mkl`. `dealii` is configured with manual setup of `lapack`: 

```
-DLAPACK_INCLUDE_DIRS=/apps/intel/ComposerXE2018/compilers_and_libraries_2018.3.222/linux/mkl/include
```

but this include directory is missing when building downstream projects (verified with `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`), which expectedly gives errors like:

```
deal.II/lac/blas_extension_templates.h:34:12: fatal error: mkl_trans.h: No such file or directory
 #  include <mkl_trans.h>
            ^~~~~~~~~~~~~
```

If someone (@tamiko ? 😄 ) immediately knows what to fix, don't let me stop you ;-) otherwise I will dig into the CMake part a bit later...

**Comment by davydden** [comment]
I looked at [configure_feature](https://github.com/dealii/dealii/blob/master/cmake/macros/macro_configure_feature.cmake) macro and don't see anything like `${FEATURE}_INCLUDE_DIRS`, not sure how include directories are handled...

**Comment by davydden** [comment]
PR incoming...

**Comment by masterleinad** [comment]
#7722 might be related.

**Comment by masterleinad** [comment]
#7722 might be related.

**Comment by tamiko** [comment]
@davydden Traditionally BLAS/Lapack as pure Fortran libraries had no C/C++ headers. All you need to do is to add
```
INCLUDE_DIRS OPTIONAL ...
USER_INCLUDE_DIRS OPTIONAL ...
```
to the `DEAL_II_PACKAGE_HANDLE` call.

**Comment by tamiko** [comment]
I guess #7722 is the same issue.

**Comment by davydden** [comment]
I did that, testing, AKF to finish and create a PR

**Comment by davydden** [comment]
That’s why

> PR incoming...

is there, it’s just slowly incoming ;-)

**Comment by davydden** [comment]
@tamiko does not seem to be working... I am re-configuring now in a clean build folder to double check, but meanwhile, how do I make sure that `LAPACK_INCLUDE_DIRS` is actually used? I checked `CMakeCache` and the only place where I see `linux/mkl/include` is 
```
//No help, variable specified on the command line.
LAPACK_INCLUDE_DIRS:UNINITIALIZED=/apps/intel/ComposerXE2018/compilers_and_libraries_2018.3.222/linux/mkl/include
```
Also `detailed.log` does not show `LAPACK_USER_INCLUDE_DIRS`.

Here's what I am testing:
```
$ git diff --cached
diff --git a/cmake/modules/FindLAPACK.cmake b/cmake/modules/FindLAPACK.cmake
index 0d79cc0..0c0f7bd 100644
--- a/cmake/modules/FindLAPACK.cmake
+++ b/cmake/modules/FindLAPACK.cmake
@@ -97,6 +97,10 @@ DEAL_II_PACKAGE_HANDLE(LAPACK
     REQUIRED _lapack_libraries
     OPTIONAL BLAS_LIBRARIES ${_additional_libraries}
   LINKER_FLAGS OPTIONAL _lapack_linker_flags BLAS_LINKER_FLAGS
+  INCLUDE_DIRS
+    OPTIONAL LAPACK_INCLUDE_DIRS
+  USER_INCLUDE_DIRS
+    OPTIONAL LAPACK_INCLUDE_DIRS
   CLEAR
     atlas_LIBRARY atlcblas_LIBRARY atllapack_LIBRARY blas_LIBRARY
     eigen_blas_LIBRARY f77blas_LIBRARY gslcblas_LIBRARY lapack_LIBRARY
```

**Comment by tamiko** [comment]
*yeah* Reminds me that I have to fix the macro at some point. This works:
```
diff --git a/cmake/modules/FindLAPACK.cmake b/cmake/modules/FindLAPACK.cmake
index 0d79cc018e..e10bd1420f 100644
--- a/cmake/modules/FindLAPACK.cmake
+++ b/cmake/modules/FindLAPACK.cmake
@@ -89,7 +89,7 @@ FOREACH(_lib ${_fortran_libs})
   LIST(APPEND _additional_libraries ${_lib}_LIBRARY)
 ENDFOREACH()
 
-
+SET(_lapack_include_dirs ${LAPACK_INCLUDE_DIRS})
 SET(_lapack_libraries ${LAPACK_LIBRARIES})
 SET(_lapack_linker_flags ${LAPACK_LINKER_FLAGS})
 DEAL_II_PACKAGE_HANDLE(LAPACK
@@ -97,6 +97,10 @@ DEAL_II_PACKAGE_HANDLE(LAPACK
     REQUIRED _lapack_libraries
     OPTIONAL BLAS_LIBRARIES ${_additional_libraries}
   LINKER_FLAGS OPTIONAL _lapack_linker_flags BLAS_LINKER_FLAGS
+  INCLUDE_DIRS
+    OPTIONAL _lapack_include_dirs
+  USER_INCLUDE_DIRS
+    OPTIONAL _lapack_include_dirs
   CLEAR
     atlas_LIBRARY atlcblas_LIBRARY atllapack_LIBRARY blas_LIBRARY
     eigen_blas_LIBRARY f77blas_LIBRARY gslcblas_LIBRARY lapack_LIBRARY
```

**Comment by davydden** [comment]
>  Reminds me that I have to fix the macro at some point.

perhaps document this as an issue?
