### ISSUE TITLE
Use fe.degree explicitly in example quadrature rules.

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7903]
This came up on the mailing list and I want to make sure we do not forget about it.

Some of the example programs (e.g., step-40) hard-code the degree of the quadrature formula. We should always do, e.g., `QGauss<dim>(fe.degree + 1)` for linear problems to ensure things are consistent.

Maxi Miller volunteered to do this, but may not have time until about April 22.

**Comment by masterleinad** [comment]
Closed by #7943.
