### ISSUE TITLE
Allow MeshWorker::mesh_loop() to work on iterator ranges

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7907]
Reviewing #7906 made me wonder whether we could add some more variants of `MeshWorker::mesh_loop()` that work on iterator ranges. This would mean that we could do this for normal cells:
```c++
mesh_loop(dof_handler.active_cell_iterators(),...);
```
this for some custom post-processors
```c++
const auto selected_material_cell_range =
  filter_iterators(dof_handler.active_cell_iterators(),
                   IteratorFilters::MaterialIdEqualTo(...));
mesh_loop(selected_material_cell_range,...);
```
and this for `p::d::Tria`
```c++
const auto locally_owned_cell_range =
  filter_iterators(dof_handler.active_cell_iterators(),
                   IteratorFilters::LocallyOwnedCell());
mesh_loop(locally_owned_cell_range,...);
```
(although I don't know if the latter is truly necessary; I've not yet worked with `mesh_loop()`)

**Comment by bangerth** [comment]
Yes, I look forward to using ranges and so that we can use the extensions of the "ranges" additions to C++20: https://en.cppreference.com/w/cpp/ranges

**Comment by bangerth** [comment]
The first place that probably ought to be augmented is `WorkStream::run()`.
