### ISSUE TITLE
Cannot start deal.ii image on VirtualBox 4.3.26

### ISSUE THREAD

**Issue by qaimirah** [dealii/dealii#791]
I have had two major issues in getting deal.ii to run.  Attached is a log.  Below are some additional details regarding my physical machine, as well as the steps I've taken thus far.

My physical machine:
Processor: Intel Core i1-2760QM CPU @ 2.40GHz
RAM: 8GB
System type: 64-bit OS (Windows 7 Professional)

I already had VirtualBox 4.3.26 installed and had run Clawpack 4.6 on it-- it worked perfectly fine.

I recently downloaded the deal/ASPECT image from http://www.math.clemson.edu/~heister/dealvm/.

I imported the image as directed.  The first issue I encountered was an error message (see picture).
![dealii_error](https://cloud.githubusercontent.com/assets/11926958/7118571/01d46b78-e1ce-11e4-835d-c372f8a57fad.png)

I then scoured a few VirtualBox forums and eventually found a fix.  Namely, I had to go into VBoxManage.exe and set longmode and hwvirtex to 'off' as well as cpus to 1.  (See https://forums.virtualbox.org/viewtopic.php?f=6&t=58820).

Now, I can get the deal.ii image to start, but Ubuntu won't boot.  (I'd attach a log, but I can't see how to do so at the moment.)

At this point, my already meager computer knowledge has run dry.  Any help would be appreciated, and I'd be happy to provide more information if necessary.  I should forewarn you that I am a math, not a compsci kid, and may need a little hand-holding.

**Comment by tjhei** [comment]
1.  did you try turning on VT-x in your bios of your computer?
2. Can you try http://www.ces.clemson.edu/dealii/deal_aspect-v11.ova (newer version of the image) and report if it works for you?

**Comment by qaimirah** [comment]
I did eventually learn how to turn on virtualization in the BIOS.  (Being new to all this, I had no idea it was a common issue or an easy fix.)  I was then able to get the image to run.  I will also try the new image.  Thanks!

**Comment by tamiko** [comment]
:-)
