### ISSUE TITLE
dealii@develop build error with intel@19.0.3.199 on cori via spack/xsdk

### ISSUE THREAD

**Issue by balay** [dealii/dealii#7912]
Attaching the build log.

The commit tested is a5465021cc1eb5f5fd518c2bed276b131aeb6cfa

This must be due to https://github.com/dealii/dealii/pull/7806

Reverting to a73bbc813e6eb086f29c5fcc307c116ca7d7c400 gets the build going

[dealii-spack-build.out.txt](https://github.com/dealii/dealii/files/3069164/dealii-spack-build.out.txt)

**Comment by davydden** [comment]
I think it will be fixed by https://github.com/dealii/dealii/pull/7910

**Comment by davydden** [comment]
indeed, errors are
```
dealii/source/meshworker/scratch_data.cc(131): error: namespace "std" has no member "make_unique"
        fe_values = std::make_unique<FEValues<dim, spacedim>>(*mapping,
                         ^
```
and alike.
