### ISSUE TITLE
GridTools::find_closest_vertex_of_cell ignores mapping

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#7922]
GridTools::find_closest_vertex_of_cell does not consider the fact that vertices may be in a different position if a Mapping is present that transforms the cells.

**Comment by masterleinad** [comment]
@luca-heltai As far as I can see this case was already considered in https://github.com/dealii/dealii/commit/fcbc08d4de5. In particular, there is https://github.com/dealii/dealii/blob/755e9fd4a0668909fb0fae3f70af47d1adf872eb/source/grid/grid_tools.cc#L1314-L1366.
Can you provide a case that is failing for you?

**Comment by luca-heltai** [comment]
The example you refer to is for `find_closest_vertex`, not `find_closest_vertex_of_cell`. The second function is used in the ParticleHandler class (@gassmoeller, you may be interested in this as well). It should take an additional mapping argument, otherwise the returned result makes no sense whenever a MappingFEField or MappingQEulerian is used.

**Comment by luca-heltai** [comment]
Incidentally, `find_closest_vertex` works correctly.

**Comment by luca-heltai** [comment]
Addressed in #10108
