### ISSUE TITLE
Error while make run for smoke test in WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by sreekar2858** [dealii/dealii#7929]
I followed the code as is to install the deal.ii in WSL but when I tried to run the smoke test. 
It says `undefined reference to fftw_join_taint` 

Please Help me

Cheers
Happy coding

**Comment by masterleinad** [comment]
What exactly are you proposing? Is there a package missing?

**Comment by drwells** [comment]
It sounds like a dependency of deal.II has an incomplete link interface to FFTW. This is almost surely not something that can be fixed from inside deal.II.

**Comment by drwells** [comment]
Since this problem is not something that can be addressed by changing something in deal.II I believe we should close this issue.

@sreekar2858 if you are still having trouble getting all of the dependencies to work then I suggest posting this on the mailing list.
