### ISSUE TITLE
Bug in find_active_cell_around_point

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#7930]
GridTools::find_active_cell_around_point<dim>(tria,p,marked_vertices) fails in a case like this

![](https://gitlab.com/MDLSoft/ginestra-fem/uploads/209de5a254859cb08d9a5413c8707b20/image.png)

because if marked_vertices is not empty the algorithm does the following:

- searches the closes vertex (V5 in this case)
- searches only between the cells adjacent to the vertex, not finding the point

If marked_vertices is empty the algorithm searches also the other cells.

**Comment by bangerth** [comment]
If I see this right, if we don't find a cell we simply return an empty iterator object, right? If so, should the function simply call itself without marked vertices if that is about to happen?

**Comment by kronbichler** [comment]
I think this is what was eventually fixed in #15233 by @richardschu with help of @jh66637. So I feel this has deserved to be closed.
