### ISSUE TITLE
CMake: C++ specific flags in CXXFLAGS env variable breaks find(LAPACK) call (with intel mkl)

### ISSUE THREAD

**Issue by isuruf** [dealii/dealii#7937]
Since CMAKE_REQUIRED_FLAGS is set here, 
https://github.com/dealii/dealii/blob/3205b61f9260e0b8cb94b78a1a1b7fca7c19b7ef/cmake/macros/macro_reset_cmake_required.cmake checking for pthread.h is broken because a C compiler is used with C++ specific flags.

**Comment by masterleinad** [comment]
Where exactly do you encounter an error. Can you share the failing `CMakeError.txt` output?

**Comment by isuruf** [comment]
```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: $SRC_DIR/build/CMakeFiles/CMakeTmp
Run Build Command(s):$BUILD_PREFIX/bin/make cmTC_83637/fast 
$BUILD_PREFIX/bin/make -f CMakeFiles/cmTC_83637.dir/build.make CMakeFiles/cmTC_83637.dir/build
make[1]: Entering directory '$SRC_DIR/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_83637.dir/CheckIncludeFile.c.o
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/dealii-9.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -isysroot /Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9   -o CMakeFiles/cmTC_83637.dir/CheckIncludeFile.c.o   -c $SRC_DIR/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
error: invalid argument '-std=c++14' not allowed with 'C/ObjC'
make[1]: *** [CMakeFiles/cmTC_83637.dir/build.make:66: CMakeFiles/cmTC_83637.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '$SRC_DIR/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_83637/fast] Error 2
```
This is on MacOSX with a custom built clang 4.0.1

**Comment by tamiko** [comment]
@isuruf Would you mind to share more context? In particular `CMakeCache.txt`, your command line invocation of cmake and the cmake output. Are you certain that `CMAKE_C_FLAGS` didn't accidentally get populated by `-stdlib=libc++ -std=c++14`?

For context, the relevant CMake snippet is found in `configure_1_threads.cmake` and reads:
```
  IF(CMAKE_C_COMPILER_WORKS)
    #
    # Clear the test flags because FindThreads.cmake will use a C compiler:
    #
    CLEAR_CMAKE_REQUIRED()

    SWITCH_LIBRARY_PREFERENCE()
    FIND_PACKAGE(Threads)
    SWITCH_LIBRARY_PREFERENCE()

    RESET_CMAKE_REQUIRED()
```

**Comment by isuruf** [comment]
Looks like `configure_1_lapack.cmake` gets called before `configure_1_threads.cmake` which calls CMake's FindLAPACK.cmake which in turn calls `FIND_PACKAGE(Threads)` before deal.ii does.
(ref: https://github.com/Kitware/CMake/blob/master/Modules/FindLAPACK.cmake#L215)

I checked and `CMAKE_C_FLAGS` is not populated with C++ flags.

Following patch fixes this issue for me,
```diff
diff --git a/cmake/configure/configure_1_lapack.cmake b/cmake/configure/configure_1_lapack.cmake
index 2eb4519a15..b773ccbb8d 100644
--- a/cmake/configure/configure_1_lapack.cmake
+++ b/cmake/configure/configure_1_lapack.cmake
@@ -18,6 +18,7 @@
 #
 
 MACRO(FEATURE_LAPACK_FIND_EXTERNAL var)
+  CLEAR_CMAKE_REQUIRED()
   FIND_PACKAGE(LAPACK)
 
   #
```

**Comment by isuruf** [comment]
Btw, a simple reproducer is  `CXXFLAGS="-std=c++14" cmake ..`

**Comment by tamiko** [comment]
@isuruf Ah, very good. What about you open a pull request for above one-liner?

I guess the combination of using intel lapack libraries (`BLA_VENDOR` set to `Intel`) and setting a C++ specific flag in CXXFLAGS is relatively rare :-)
