### ISSUE TITLE
Wrong vtu output with complex SLEPc and MPI

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#7940]
I get a wrong vtu output when I use complex SLEPc to calculate the eigenfrequencies of a structure. I think that the problem is in deal.ii. I can write and submit a PR with a test that reproduces the problem. I have not been able to find the source of the problem.

The output is correct in serial (MPI_processes = 1), but the output is wrong with MPI_processes = 16
# Detailed description of the problem
The program is based on step_62, see #6747 . I'm planing to do a tutorial on how to calculate the complex eigenfrequencies in parallel with SLEPc. I calculate the mass and stiffness matrices and use SLEPc to calculate the eigenfrequencies.

## Serial simulation MPI_processes = 1
The fundamental mode for a beam looks like this
![eigenmode_deformed](https://user-images.githubusercontent.com/25910642/56429821-8a9a7080-62c4-11e9-9873-3f779ec60364.jpg)

The eigenvalue is ω <sup>2</sup> = (3.33875e+17,-6.67817e+15). The eigenvalue is complex because I introduced damping.

## Parallel simulation MPI_processes = 16
The fundamental mode for a beam looks like this
![eigenmode_deformed_mpi](https://user-images.githubusercontent.com/25910642/56430240-0ea12800-62c6-11e9-96b2-c8309163cf5f.jpg)

The eigenvalue is ω <sup>2</sup> = (3.33875e+17,-6.67817e+15), which is the same as in the serial version. This suggests that there is a problem with the assembly of the vtu output.

Below you can find the subdomain plot (MPI processes). This clearly shows the correlation between the output and the MPI processes
![subdomain](https://user-images.githubusercontent.com/25910642/56430428-9be47c80-62c6-11e9-97cf-b412d257f834.jpg)

## Serial vs parallel
Below you can find the comparison serial vs parallel. The signature of the subdomain division is very clear. The top figure is the undeformed result in serial, and the bottom figure is the undeformed result in parallel.
![eigenmode](https://user-images.githubusercontent.com/25910642/56430490-c7fffd80-62c6-11e9-9c2e-8a7bea367447.jpg)

**Comment by masterleinad** [comment]
This looks like the information on the information is wrong, i.e. the vector does not have the correct values for the locally active degrees of freedom. Can you make sure that the vector you are using for `vtu` output is indeed ghosted and has its ghost values updated?

**Comment by dangars** [comment]
@masterleinad Thanks a lot for the quick reply!
You are right! The problem was related to the ghost values.
My fault, there is no bug in the deal.ii library :)
