### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by Cristilex25** [dealii/dealii#7941]
Hi, everyone. How can I add a flag (let's say something like DEAL_II_WITH_OPENMP=ON) for my cmake compiler in order to successfully run the project with openMp support? Do I need to install Deal.II again afterwards?

**Comment by masterleinad** [comment]
No, `deal.II` doesn't use `OpenMP` explicitly but its dependencies, e.g, `cuSolver` might. Dependencies (apart from bundled packages) must be configured individually.
