### ISSUE TITLE
TimerOutput for CPU time seems not correct

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#795]
Firstly I modified step-40 to output both cpu time and wall time, then
I run step-40 with 4 processes, and involuntarily 2 threads per process. (See https://groups.google.com/forum/#!topic/dealii/XJUrCGIEasE for discussion on this "unstoppable" multithread.)

And I got timer output like this:
//////////////////////////////////////////////////////////////////////////////////
$ mpirun -n 4 ./step-40 | grep -e Cycle -e elapsed 
Cycle 0:
| Total CPU time elapsed since start          |      2.06s |            |
| Total wallclock time elapsed since start    |     0.219s |            |
Cycle 1:
| Total CPU time elapsed since start          |      6.01s |            |
| Total wallclock time elapsed since start    |     0.525s |            |
Cycle 2:
| Total CPU time elapsed since start          |      11.1s |            |
| Total wallclock time elapsed since start    |     0.984s |            |
Cycle 3:
| Total CPU time elapsed since start          |      20.9s |            |
| Total wallclock time elapsed since start    |       1.8s |            |
Cycle 4:
| Total CPU time elapsed since start          |      40.9s |            |
| Total wallclock time elapsed since start    |      3.54s |            |
//////////////////////////////////////////////////////////////////////////////////

The cpu time is roughly 10 or more than 10 times to wall time. I don't think this is reasonable.
Because the cpu on my laptop is Intel Core i7 with totally 2 cores and 4 hyper-threads. The max cpu time to wall time ratio should be 4.

Similar output also shows up on Linux cluster. So I think this should not be a problem related to OS X timing API or my CPU clock.

Or, my understanding of CPU time is wrong?

**Comment by QiaoLei-88** [comment]
CPU time looks good with just one mpi process:

  >>  $ mpirun -n 1 ./step-40  |  grep -e Cycle -e elapsed 
  >>  Cycle 0:
  >>  | Total CPU time elapsed since start          |     0.772s |            |
  >>  | Total wallclock time elapsed since start    |     0.834s |            |
  >>  Cycle 1:
  >>  | Total CPU time elapsed since start          |      1.81s |            |
  >>  | Total wallclock time elapsed since start    |      1.92s |            |
  >>  Cycle 2:
  >>  | Total CPU time elapsed since start          |      3.22s |            |
  >>  | Total wallclock time elapsed since start    |      3.31s |            |
  >>  Cycle 3:
  >>  | Total CPU time elapsed since start          |      6.24s |            |
  >>  | Total wallclock time elapsed since start    |      6.55s |            |

And with 2 processes, the CPU time becomes 4 times to wall time
  >>  mpirun -n 2 ./step-40  |  grep -e Cycle -e elapsed 
  >>  Cycle 0:
  >>  | Total CPU time elapsed since start          |      1.64s |            |
  >>  | Total wallclock time elapsed since start    |     0.543s |            |
  >>  Cycle 1:
  >>  | Total CPU time elapsed since start          |      4.45s |            |
  >>  | Total wallclock time elapsed since start    |      1.13s |            |
  >>  Cycle 2:
  >>  | Total CPU time elapsed since start          |      8.48s |            |
  >>  | Total wallclock time elapsed since start    |      2.14s |            |
  >>  Cycle 3:
  >>  | Total CPU time elapsed since start          |      16.4s |            |
  >>  | Total wallclock time elapsed since start    |      4.18s |            |

And with three processors, CPU time goes to roughly 9 times to wall time:
  >>  step-40$ mpirun -n 3 ./step-40  |  grep -e Cycle -e elapsed 
  >>  Cycle 0:
  >>  | Total CPU time elapsed since start          |      2.88s |            |
  >>  | Total wallclock time elapsed since start    |     0.439s |            |
  >>  Cycle 1:
  >>  | Total CPU time elapsed since start          |      7.98s |            |
  >>  | Total wallclock time elapsed since start    |      0.92s |            |
  >>  Cycle 2:
  >>  | Total CPU time elapsed since start          |      14.4s |            |
  >>  | Total wallclock time elapsed since start    |      1.67s |            |
  >>  Cycle 3:
  >>  | Total CPU time elapsed since start          |      26.7s |            |
  >>  | Total wallclock time elapsed since start    |      3.02s |            |

Now the situation is quite obvious: too much addition is done on cpu time.

**Comment by QiaoLei-88** [comment]
I believe this is the trouble maker:

from line 409 in timer.cc
>  double cpu_time = sections[actual_section_name].timer();
>  sections[actual_section_name].total_cpu_time
>  += Utilities::MPI::sum (cpu_time, mpi_communicator);

This is the right way to do 
>  double local_total_cpu_time += sections[actual_section_name].timer();
>  sections[actual_section_name].global_total_cpu_time
>  = Utilities::MPI::sum (cpu_time, mpi_communicator);

Now I have to find out where is the proper place to insert the new variable local_total_cpu_time.

**Comment by tjhei** [comment]
Yes, that makes sense.

**Comment by QiaoLei-88** [comment]
The bug is here bu the previous suggested fix doesn't work.
I created pull request #799 to address issue.
To complete this discussion, I post the key part of the patch there again:

from line 409 in timer.cc
>  // get cpu time. on MPI systems, noticed that the Timer for the new sectiont
>  // is initialized with a provided mpi_communicator and then the Timer class
>  // will do the summation through out the mpi_communicator, we do not need to
>  // do it again here, no matter the mpi_communicator is MPI_COMM_WORLD,
> // MPI_COMM_SELF or something else.
> const double cpu_time = sections[actual_section_name].timer();
> sections[actual_section_name].total_cpu_time = cpu_time;

**Comment by QiaoLei-88** [comment]
Closed by PR #799.
