### ISSUE TITLE
step-62 has 404 link

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#7997]
The link to the notebook in step-62 page leads me to this 404 page:

https://github.com/dealii/dealii/blob/phononic-cavity/examples/step-62/step-62.ipynb

There are also a few 'Undefined control sequence \lamda' instead of equations. 

Great tutorial otherwise! I hope we see more python integration in the future.

**Comment by Rombur** [comment]
Thanks for the report. We should point to master not phononic-cavity.

**Comment by dangars** [comment]
@agrayver Thanks a lot for your message! I'm happy to hear that you liked the tutorial :)
I fixed the lambda typos in #8001
