### ISSUE TITLE
"constexpr"ing Tensor, Point, and SymmetricTensor

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#8003]
By adding `constexpr` to the constructors, assignment operations, and `operator[]`, we can achieve full compile time evaluation of fixed-sized fundamental data types such as Tensor, Point, and SymmetricTensor when they are instantiated with trivial types. The goal is to eventually have all tensors in `Physics::Elasticity::StandardTensors` (and other similar places) computed as compile-time constants.

I'm interested to try this and submit multiple PRs. I'm relatively new and I appreciate your guidance. Please let me know:
* What are your concerns about this? What should I be careful about?
* Has anyone tried it or thought about it before?
* Should I wait for the incoming release before I make these changes?

Some of the issues I anticipated and how we can possibly solve them:
1. Many functions cannot be defined as consexpr in c++11 and they need at least c++14:
   * We can define and use macros similar to `BOOST_CXX14_CONSTEXPR`, `BOOST_CONSTEXPR_OR_CONST`, and `BOOST_STATIC_CONSTEXPR` to ensure compatibility with c++11.
1. How does a consexpr constructor or member function behave if the tensor is initialized with AD types which have dynamic allocation?
   * There are no issues with that. The compiler disregards the constexpr keyword if a non-trivial type is stored. [Example](https://www.godbolt.org/z/5X7Jt1)
1. Code will have additional clutter due to the use of macros.
1. In some small cases, code duplication may be necessary in order to make sure it works both with c++11 and c++14. For example, some global constants must be calculated in source file with c++11. My proposed changes require the the calculation of these constants to be copied to the header file.

Tasks:
- [x] `constexpr Tensor`
- [x] `constexpr SymmetricTensor`
- [x] `constexpr TableIndices`
- [ ] `constexpr Point`
- [ ] use constexpr in tutorials
- [x] add documentation about `constexpr` features
- [ ] `constexpr Quadrature`

**Comment by drwells** [comment]
This sounds like a nice set of features. My main concern (though I have not looked too closely at it) is that this will be too hard to do without C++14. I am not a big fan of putting those types of macros everywhere but I could live with it.

An example of something similar we did: @masterleinad converted `GeometryInfo` to `constexpr`. See #5748.

**Comment by masterleinad** [comment]
I tried doing that already but so far the clutter needed to make it work with C++11 appeared to outweigh the usefulness. A typical example might be `Utilities::pow` (https://github.com/dealii/dealii/blob/master/include/deal.II/base/utilities.h#L420-L457) which looks pretty cryptic compared to what it really does.
Changing from `const` to `constexpr` in case at least `C++14` support is enabled does not look favorable to me.
Of course, you can still just give it a shot and you might find a nice solution.

There should not be too many changes that will still make it into the new release so starting already should not be a problem.

**Comment by Rombur** [comment]
> Changing from const to constexpr in case at least C++14 support is enabled does not look favorable to me.

Why not? I don't see the problem?  Personally, I think it's fine to have a macro `DEAL_II_CONSTEXPR` that enable `constexpr` only if the compiler supports it.  For example, in `Utilities::pow` we would enable `constexpr` only if it works out-of-the-box, if it doesn't we fall back to the current behavior. This way we don't clutter the code and you can take advantage of `constexpr` if your compiler allows it.

**Comment by drwells** [comment]
I think we have made most of the progress that is possible to make on this with our current compiler support.
