### ISSUE TITLE
gcc9 warning: std::move with unique_ptr redundant

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8015]
When compiling deal.II with the freshly released gcc-9, I get a large number of warnings. Some are related to boost (as usual with new compiler releases), some are due to our code. I get a lot of warnings of this type:
```
/home/kronbichler/sw/dealii_git/source/fe/mapping_cartesian.cc: In instantiation of ‘std::unique_ptr<typename dealii::Mapping<dim, spacedim>::InternalDataBase> dealii::MappingCartesian<dim, spacedim>::get_data(dealii::UpdateFlags, const dealii::Quadrature<dim>&) const [with int dim = 1; int spacedim = 1; typename dealii::Mapping<dim, spacedim>::InternalDataBase = dealii::Mapping<1, 1>::InternalDataBase]’:
/home/kronbichler/sw/build_deal_git/source/fe/mapping_cartesian.inst:10:16:   required from here
/home/kronbichler/sw/dealii_git/source/fe/mapping_cartesian.cc:108:24: warning: redundant move in return statement [-Wredundant-move]
  108 |   return std::move(data);
      |                        ^
/home/kronbichler/sw/dealii_git/source/fe/mapping_cartesian.cc:108:24: note: remove ‘std::move’ call
```

Looking at the [source code for this particular example](https://github.com/dealii/dealii/blob/master/source/fe/mapping_cartesian.cc#L96-L109), I can certainly understand why the compiler complains: We create a `unique_ptr` within the function body, and return that `unique_ptr` at the end. No need to move the object here. This was introduced in #6115 as far as I can see. On the other hand, we've had contributions where we had to insert `std::move`, see e.g. #6558 or #6556, so there seem to be instances where this is needed. Does anybody recall what criteria were fulfilled when we had to add them? Is it for non C++-14 compilers? And how should we go forward with this?

**Comment by drwells** [comment]
I think we could write an equivalent fix for #6558 by writing something like
```cpp
std::unique_ptr<typename FiniteElement<dim,dim>::InternalDataBase>data(new FE_SZ_Data{});
```
so that the `unique_ptr` always has the correct type. This should always work. I will give it a try

**Comment by masterleinad** [comment]
> Does anybody recall what criteria were fulfilled when we had to add them? Is it for non C++-14 compilers? And how should we go forward with this?

There was a nice talk at CppCon2018 (https://github.com/CppCon/CppCon2018/blob/master/Presentations/return_value_optimization_harder_than_it_looks/return_value_optimization_harder_than_it_looks__arthur_odwyer__cppcon_2018.pdf). As long as the selected converting constructor allows rvalue-references implicit moves will happen. This does not work, e.g. when slicing.

**Comment by drwells** [comment]
I got a build of GCC 10 working on my workstation so I can handle this pretty easily now.
