### ISSUE TITLE
distribute_sparsity_pattern shall take an std::vector<IndexSet>

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#8041]
following discussion in https://github.com/dealii/dealii/pull/7831#discussion_r267541748

> I think we shall deprecate the old interface and take std::vector<IndexSet> and then add an asssert here.

similar to https://github.com/dealii/dealii/pull/7828/

**Comment by kronbichler** [comment]
This has been resolved by taking simply the `IndexSet` of the present processor in #9710.
