### ISSUE TITLE
step-61: Couple degree of RT element to that of the other elements.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8042]
@sophy1029: Right now, step-61 always creates an `FE_RT(0)`. When you made the experiments shown in the results section, you probably had to change by hand the polynomial degrees of all elements, right? I think it would be easier to make sure that the degree of the `FE_RT` is always equal to that of the interior and interface elements, for example by creating it via `FE_RT(fe.base_element(0).degree)`, which would create an `FE_RT(0)` if one uses piecewise constant elements in the interior, `FE_RT(1)` if one uses piecewise bilinear elements in the interior, etc.

Does this make sense to you? Or is there ever a reason to use some other RT element?

**Comment by sophy1029** [comment]
Yes, that makes sense. I just need the degree of FE_RT to be the same as DGQ and FaceQ. 
Then it's much easier! Thanks!
