### ISSUE TITLE
Deprecate nanoflann

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8068]
As discussed in https://github.com/dealii/dealii/pull/8030#issuecomment-490216282 we can deprecated nanoflann as the RTree library is deemed much better. We should do this for the 9.2 release.

**Comment by drwells** [comment]
Should we deprecate in 9.1 as well?

**Comment by kronbichler** [comment]
> Should we deprecate in 9.1 as well?

If you want to go ahead, I'm fine with it.

**Comment by luca-heltai** [comment]
I'm not sure how many people are using this. Internally, we replaced all nanoflann use with RTree.
