### ISSUE TITLE
Documentation build system now requires python3

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8084]
Maybe I was overly zealous, but #7628 introduced a dependency on python3, which I happen to not have on my system.

#8083 tries to address this, but trying things out, it turns out that the `doc/doxygen/scripts/set_canonical_doxygen.py` script really does need python3:
```
Traceback (most recent call last):
  File "/home/fac/f/bangerth/p/deal.II/1/dealii/doc/doxygen/scripts/set_canonical_doxygen.py", line 27, in <module>
    filenames = glob.iglob('**/*html', recursive=True)
TypeError: iglob() got an unexpected keyword argument 'recursive'
make[3]: *** [doxygen.log] Error 1
make[3]: *** Deleting file `doxygen.log'
make[2]: *** [doc/doxygen/CMakeFiles/doxygen.dir/all] Error 2
make[1]: *** [CMakeFiles/documentation.dir/rule] Error 2
make: *** [documentation] Error 2
```
Ugh. Suggestions?

**Comment by bangerth** [comment]
@dangars -- FYI.

**Comment by drwells** [comment]
I can take a look but I really don't think requiring python3 is very onerous: python2 is EOLed as of 2020. What machine doesn't have python3?

**Comment by drwells** [comment]
I still write a lot of python and this script is short. Let me see if I can cook up something that works with 2 and 3 for now.

**Comment by drwells** [comment]
I think I have it. I will put up a PR once I check that I can generate the documentation locally.

**Comment by dangars** [comment]
@bangerth Sorry for the python3 dependency. Now, I make sure that all my scripts are python3 as next year python2 will be dropped.

Maybe as @drwells proposed, it is better to write a script that works for python2 and python3.

**Comment by dangars** [comment]
The exact date for the end of life of python2 is January 1st 2020. That is 7 months from now ;)

**Comment by bangerth** [comment]
No worries :-) I wouldn't have noticed if my big development machines weren't lacking python3.
