### ISSUE TITLE
step-42 fails to compile with clang-4.0

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8111]
The regression tester [1] reveals a build failure with clang-4.0. Due to the heavy activity during the last days and other failures, the tester only reveals that this happened between 2365fe395a  and 7b51bc066c . The update #8097 does not seem to be the culprit as the error is related to `unit_symmetric_tensor<dim>()`. My guess is that this was introduced by f6c96c520478d963cd9ebb6f4877d59e3ddb8b01 . This in turn would indicate that clang-4.0 does not support default template arguments in functions. How should be proceed? I'm leaning towards undoing the offending commit to `symmetric_tensor.h` for the release as clang-4.0 is a primary target.

[1] https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=9724

**Comment by rezarastak** [comment]
I wasn't expecting any build issues when submitting #8082. My changes looked trivial so I submitted it before the release. I'm slowly learning about these compiler issues :)

I'm having a hard time trying to [recreate](https://www.godbolt.org/z/XO93ol) this build error in Compiler Explorer. Does anyone know to get a similar error in a small code example?
