### ISSUE TITLE
use latex bibliography in steps?

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8152]
We do not use latex bibliographies for the citations in the tutorials. Instead, each tutorial uses a different approach. See step-14, step-43, and step-56 for examples. Many other examples cite source in an incomplete manner "inline".

Here is some info:
- https://stackoverflow.com/questions/11454727/doxygen-cite-producing-empty-bibliography
- http://www.doxygen.nl/manual/config.html#cfg_cite_bib_files

One disadvantage is that this generates one central bibliography and not a bibliography for each tutorial. Alternatively, change every tutorial to something like step-14?
Parts of this could be a nice starter project...

**Comment by jppelteret** [comment]
In the spirit of step-14, we could also make a `.bibliography` file for all tutorials that gets appended after the `.intro` file, and fill it with entries in this doxygen supported format
```
 * @code{.bib}
 * @InProceedings{Fike2011a,
 *   author    = {Fike, Jeffrey A and Alonso, Juan J},
 *   title     = {The Development of Hyper-Dual Numbers for Exact Second-Derivative Calculations},
 *   booktitle = {49th {AIAA} Aerospace Sciences Meeting including the New Horizons Forum and Aerospace Exposition},
 *   year      = {2011},
 *   volume    = {886},
 *   pages     = {124},
 *   month     = {jan},
 *   publisher = {American Institute of Aeronautics and Astronautics},
 *   doi       = {10.2514/6.2011-886},
 * }
 * @endcode
```
These render quite neatly ([see this module file](https://dealii.org/developer/doxygen/deal.II/group__auto__symb__diff.html), for example).

**Comment by tamiko** [comment]
*mhm* The links for the references are currently not working (i.e. the bibliography page does not get populated). Do we need to change something in our doxygen configuration?

**Comment by tjhei** [comment]
> _mhm_ The links for the references are currently not working (i.e. the bibliography page does not get populated). Do we need to change something in our doxygen configuration?

I assume the bibtex is broken because they used to work, let me check.

**Comment by tjhei** [comment]
Yes, there are bibtex errors. Let me try to make a PR.

**Comment by krishnakumarg1984** [comment]
Found an inline citation in Step-10.

**Comment by bangerth** [comment]
@krishnakumarg1984 Feel free to propose a patch!

**Comment by krishnakumarg1984** [comment]
@bangerth done. See my PR #11042
