### ISSUE TITLE
ugly clang-format in step-42

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8153]
I don't know why clang-format decides to do this weird formatting in https://github.com/dealii/dealii/blob/master/examples/step-42/step-42.cc#L820
but it would be great if we can teach it to put the commas at the end of the line.

**Comment by tamiko** [comment]
@tjhei See #8156 :-)

**Comment by kronbichler** [comment]
We have closed #8156, so I will close this one as well.
