### ISSUE TITLE
missing step-58 blurb in tutorial overview 

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8183]
see doc/doxygen/tutorial/tutorial.h.in

**Comment by tjhei** [comment]
see #8080

**Comment by masterleinad** [comment]
step-58 doesn't exist...

**Comment by tjhei** [comment]
Oh!

**Comment by tjhei** [comment]
can I have step-58 then or is there something planned I don't know about?

**Comment by Rombur** [comment]
@bangerth claimed it in #5746 but it was more than a year ago

**Comment by bangerth** [comment]
It's still planned and I hope to finish it this summer. So, no, you can't have it :-)
