### ISSUE TITLE
Revisit compiler compatibility

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#8184]
After the 9.1 release it is time to revisit our compiler compatibility again - purely for economical reasons.

I currently test on bob:

clang: 4.0, 5.0, 6.0, 7.0, 8.0, 8.0 (with lld)

gcc: 4.9, 6, 7, 8, 9

**Comment by kronbichler** [comment]
I think we have strived to keep the gcc-4.9 and clang-4.0 compilers happy during this release, so I suggest to move this to the 9.3 release.

**Comment by bangerth** [comment]
There is relatively little pain associated with keeping this list of compilers. What if we just closed this PR and only re-evaluate the list once we switch to C++14 or C++17? Maybe for the 2022 release? (I don't perceive great pressure to do that right now...)

**Comment by tjhei** [comment]
My suggestion would be to require clang-4.0 for 9.2 unless someone volunteers testing with clang 3.3 for the release. We have good coverage for 4.0.

**Comment by kronbichler** [comment]
Right, we still list clang-3.3 and gcc-4.8 as the latest supported version on https://dealii.org/developer/readme.html - we should adjust this to clang-4.0 and gcc-4.9 in my opinion. Any objections?

**Comment by tjhei** [comment]
> we should adjust this to clang-4.0 and gcc-4.9 in my opinion. Any objections?

Yes, this is what I suggest as well. Do we want to blacklist them as well in cmake/?

**Comment by bangerth** [comment]
Can someone outline what changed between gcc 4.8 and 4.9, and between clang 3.3 and 4.0 that makes it worthwhile requiring the latter? Or is it simply that we no longer test the former?

**Comment by bangerth** [comment]
For reference, gcc 4.9.0 was released in April 2014. clang 4.0 was released in March 2017.
