### ISSUE TITLE
New warnings from Trilinos

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#819]
@tamiko: I'm now getting these warnings that we didn't get before:

```
In file included from /home/bangerth/bin/trilinos-11.12.1-mpi/include/ml_MultiLevelPreconditioner.h:79:0,
                 from /home/bangerth/p/deal.II/1/dealii/source/lac/trilinos_precondition.cc:29:
/home/bangerth/bin/trilinos-11.12.1-mpi/include/Epetra_MsrMatrix.h: In copy constructor 'Epetra_MsrMatrix::Epetra_MsrMatrix(const Epetra_MsrMatrix&)':
/home/bangerth/bin/trilinos-11.12.1-mpi/include/Epetra_MsrMatrix.h:416:3: warning: base class 'class Epetra_Object' should be explicitly initialized in the copy constructor [-Wextra]
/home/bangerth/bin/trilinos-11.12.1-mpi/include/Epetra_MsrMatrix.h:416:3: warning: base class 'class Epetra_CompObject' should be explicitly initialized in the copy constructor [-Wextra]
```

Any idea?

**Comment by tamiko** [comment]
This seems to happen when compiling in C++98 mode, [1]. Also happens for Trilinos 11.14, and did not show up when compiling in C++11 (if I recall correctly).

[1] https://cdash.kyomu.43-1.org/viewBuildError.php?type=1&buildid=5891

**Comment by tamiko** [comment]
Here, we have the same problem as in the case of opencascade. The only thing we can do is to disable <code>-Wextra</code>.

Could you live with a preprocessor macro guarding the <code>#pragma</code> foo? Something like
```
DEAL_II_DISABLE_EXTRA_DIAGNOSTICS
#include ... // bad headers
DEAL_II_ENABLE_EXTRA_DIAGNOSTICS
```

and we put the contents of those two macros into <code>config.h.in</code>?
With this, we do not clutter up our headers too badly.
