### ISSUE TITLE
ScratchData: Doxygen section tags leaking into documentation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#8192]
Sorry I don't have time to propose a patch for this, but it would be nice if this could be fixed for 9.1

See https://dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1ScratchData.html

```
CurrentCellMethos Methods to work on current cell
NeighborCellMethods Methods to work on neighbor cell

```
This one is also broken in a more significant way:
```
CurrentCellEvaluation Evaluation of finite element fields
--
and their derivatives on the current cell
```

**Comment by bangerth** [comment]
The issue is that `@name` does not take a target as first argument that can be used in `@ref`. `@name` just names a section. I thought that you want to prefix the `@name` clause with `@anchor` to provide the tag: http://www.doxygen.nl/manual/commands.html#cmdanchor but apparently `@anchor` can not be used this way.

**Comment by jppelteret** [comment]
And ['section'](http://www.doxygen.nl/manual/commands.html#cmdsubsection) is not right either :-/

**Comment by jppelteret** [comment]
How do we prevent clang-format from indenting long lines? I believe that the section label `@name` must be on a single line.

**Comment by Rombur** [comment]
> How do we prevent clang-format from indenting long lines? 

Use `// clang-format off` and then re-enable it with `//clang-format on`

**Comment by jppelteret** [comment]
Thanks a lot @Rombur. That works :-)

**Comment by tjhei** [comment]
I saw doxygen warnings about these ``@ref`` commands but ignored them (too many doxygen warnings...) and I now regret I didn't point it out.

**Comment by jppelteret** [comment]
No hassles :-D
