### ISSUE TITLE
GridGenerator::hyper_ball: Do we want alternative variant?

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8198]
The meshes used by `GridGenerator::hyper_ball` use the minimal numbers of cells possible, 5 in 2D and 7 in 3D. An alternative mesh is to use 12 cells for the base mesh in 2D (3 cells per quarter) and 32 in 3D. The 2D mesh looks like this (one can play a bit with where to put the additional point):

![mesh_circle](https://user-images.githubusercontent.com/8276200/57861233-7fb8fa00-77f6-11e9-9cab-0435aad50458.png)

I think it would be good to provide this as alternative to `GridGenerator::hyper_ball` (to be selected via an optional argument `n_cells`?) because this variant has somewhat better mesh quality and more uniform cell sizes between the circumferential and radial directions. In essence, this mesh corresponds to the hyperball mesh refined once and removing one of the outer mesh layers. We also have this form for the quarter ball. What do others think?

**Comment by tjhei** [comment]
> I think it would be good to provide this as alternative to `GridGenerator::hyper_ball` (to be selected via an optional argument `n_cells`?)

I think this would be useful to have. I am not a big fan of optional arguments but it would mirror what we do for hyper_shell...

**Comment by bangerth** [comment]
I like this variant. As mentioned, it nicely mirrors what we already do for other geometries.

**Comment by kronbichler** [comment]
I am looking at this right now. One complication I see is the current signature:
```
  hyper_ball(Triangulation<dim> &tria,
             const Point<dim> &  center = Point<dim>(),
             const double        radius = 1.,
             const bool attach_spherical_manifold_on_boundary_cells = false);
```
If I add an optional argument, I need to add it after `attach_spherical_manifold_on_boundary_cells`, which is a bit different from the `hyper_cell` functions that do this before their `colorize` argument. This sort of confirms @tjhei's scepticism about default integer/bool arguments. Since we have had that argument since the 9.0 release, we probably don't want to change that, even though I assume it is not often used? Opinions?

**Comment by tjhei** [comment]
> Opinions?

I don't like trying to fit in a new function with optional arguments. I would just create a new function with a different name (and maybe deprecate the old one). Maybe something like ``hyper_ball_ex``, ``hyper_ball_version2`` or something?

**Comment by bangerth** [comment]
If you create a different function, you could re-use the same name and make the argument you add the second one, between `tria` and `center`. Then the existing one could just forward to the new one and be deprecated.

**Comment by kronbichler** [comment]
I now have a solution to the mesh for the hyper ball around locally - the only question is how we want to proceed with the interface. Given that we have
```
  hyper_ball(Triangulation<dim> &tria,
             const Point<dim> &  center = Point<dim>(),
             const double        radius = 1.,
             const bool attach_spherical_manifold_on_boundary_cells = false);
```
We can
- create a second function `hyper_ball_balanced` (or any other attribute that describes what this does) as suggested by @tjhei with three/four arguments mirroring `hyper_ball`
- create a second function and add an integer parameter as suggested by @bangerth 
- add a fifth `bool` parameter to select the `balanced` option (as it is really just 2 variants, and it is unlikely that we add more)
- replace the fourth `bool` parameter by the new one; `attach_spherical_manifold_on_boundary_cells` is broken in 2D because it assigns the spherical manifold to the single inner cell instead of the rim (I can add a PR to fix it if we keep this variant) and this setup is very questionable otherwise; we should fix the mesh by the transfinite manifold instead. If we want to curve the inner cell a bit, we need another mechanism.

I am in favor of the first variant, but happy to accept any other solution. As long as we don't waste too much time on this topic.
