### ISSUE TITLE
doxygen: symengine doxygen blurb not visible

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8203]
The following paragraph is not visible anywhere:
https://github.com/dealii/dealii/blob/master/include/deal.II/differentiation/sd/symengine_math.h#L34

@jppelteret where can we put it?

**Comment by jppelteret** [comment]
Hmm... maybe we should just leave this as a comment at the top of the page. I don't think that these math functions deserve their own group or anything. I'd submit a PR for this.

**Comment by tjhei** [comment]
> maybe we should just leave this as a comment at the top of the page

well, that is already the case. ;-)

**Comment by jppelteret** [comment]
But as a comment comment, not a doxygen comment. I will submit a PR for this trivial change :-D
