### ISSUE TITLE
step-63: Random shuffle is unnecessarily complicated

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8222]
The random shuffle function in step-63 appears unnecessarily complicated. It has this code:
```
    std::vector<unsigned int> ordered_cells;
    ordered_cells.reserve(dof_handler.get_triangulation().n_cells(level));
    for (const auto &cell : dof_handler.cell_iterators_on_level(level))
      ordered_cells.push_back(cell->index());

    std::mt19937 random_number_generator;
    for (unsigned int i = 1; i < ordered_cells.size(); ++i)
      {
        const unsigned int j =
          std::uniform_int_distribution<>(0, i)(random_number_generator);
        if (i != j)
          std::swap(ordered_cells[i], ordered_cells[j]);
      }
```
Since `j` is drawn in the interval `0...i` inclusively (see https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution), it seems silly to then discard the case `j!=i` -- we might as well just draw from the interval `0...i-1`. All the current code does is to *not* swap elements with a particular probability. Or is this exactly the point?

Of course, an even better way of approaching this problem would have been to use `std::shuffle` instead: https://en.cppreference.com/w/cpp/algorithm/random_shuffle

@tjhei, @tcclevenger: FYI.

**Comment by tcclevenger** [comment]
Yes, what you are saying makes sense. We renumbered this way since that is what is done in `DoFRenumbering::compute_random()`.

Do you think we should just switch to `std::shuffle`? Seems much simpler.

**Comment by bangerth** [comment]
Yes, I think `std::shuffle` would be nice because it is the exact equivalent of what you do in the downstream function (where you call `std::sort` instead). 

If you feel ambitious, you can also use `std::shuffle` in `compute_random()` :-)

**Comment by drwells** [comment]
For what its worth: I tried replacing our usage of `boost::random` with `std::random` about a year ago and got stuck since they were initialized with different seeds (and therefore produce different sequences).

**Comment by bangerth** [comment]
On 5/17/19 11:27 AM, David Wells wrote:
> For what its worth: I tried replacing our usage of |boost::random| with 
> |std::random| about a year ago and got stuck since they were initialized with 
> different seeds (and therefore produce different sequences).

Yes, one will have to update a couple of output files.
