### ISSUE TITLE
CUDAWrappers::MatrixFree::point_type

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8240]
The `CUDAWrappers::MatrixFree` class has this local typedef:
```
  template <int dim, typename Number = double>
  class MatrixFree : public Subscriptor
  {
  public:
    using jacobian_type = Tensor<2, dim, Tensor<1, dim, Number>>;
    // TODO this should really be a CUDAWrappers::Point
    using point_type = Tensor<1, dim, Number>;
```
I had to look this up when I saw it in step-64. The question I have is: Why is this not `Point<dim,Number>`? That's what we usually use to denote points in `dim` dimensional space, such as quadrature points.

In particular, the current definition leads to this function returning an apparently wrong data type:
```
  template <int dim, typename Number>
  __device__ inline typename CUDAWrappers::MatrixFree<dim, Number>::point_type &
  get_quadrature_point(
    const unsigned int                                          cell,
    const typename CUDAWrappers::MatrixFree<dim, Number>::Data *data,
    const unsigned int                                          n_q_points_1d)
  {
    return *(data->q_points + data->padding_length * cell +
             q_point_id_in_cell<dim>(n_q_points_1d));
  }
```
In step-64, this is then used as follows:
```
  const Tensor<1, dim> q_point =
    CUDAWrappers::get_quadrature_point<dim, double>(cell,
                                                    gpu_data,
                                                    n_dofs_1d);
```

**Comment by masterleinad** [comment]
For the second question: @kronbichler asked to replace `auto` by `Tensor<1,dim>` and I will have a look if we can change `point_type` to be `Point`.

**Comment by kronbichler** [comment]
That would be great @masterleinad - I think the reason is that at some point the GPU compiler (more specifically, some `__device__` annotations) did not work for `Point` or were not yet implemented.

**Comment by Rombur** [comment]
> I think the reason is that at some point the GPU compiler (more specifically, some __device__ annotations) did not work for Point or were not yet implemented.

That's correct. `Point` was missing the `__device__` annotations at the time I wrote that code.
