### ISSUE TITLE
step-64: Unclear variable name

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8241]
step-64 has this piece of code:
```
// We need to store the value of the coefficient for each quadrature point in every locally owned cells.

  const unsigned int n_owned_cells =
    std::distance<decltype(dof_handler.begin_active())>(
      dof_handler.begin_active(), dof_handler.end());
  coef.reinit(Utilities::pow(fe_degree + 1, dim) * n_owned_cells);
  VaryingCoefficientFunctor<dim, fe_degree> functor(coef.get_values());
  mf_data.evaluate_coefficients(functor);
}
```
I *suspect* that the variable name is incorrect because it's really not the number of (locally owned?) cells but the total number of active cells on the current processor (some of which are owned and some of which aren't). Since I'm working this over right now, I'm going to change the variable name as well but if anyone disagrees with my interpretation, this issue is going to remind us of it.

If you agree with my interpretation, please just close this issue.

@Rombur @kronbichler @masterleinad : FYI.

**Comment by masterleinad** [comment]
The cells we access for each thread are set up in `MatrixFree::internal_reinit` (https://github.com/dealii/dealii/blob/master/include/deal.II/matrix_free/cuda_matrix_free.templates.h#L832-L867). In fact, we only access all active, locally owned cells. Hence, we should rather initialize `coef` with this number. I pushed a respective commit to #8242.
