### ISSUE TITLE
GMSH-4.3 msh compatibility (Mesh format 4.1)

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#8245]
We should update our `read_msh` function to be able to deal with meshes created by gmsh-4.3:

```
2: --------------------------------------------------------
2: An error occurred in line <1479> of file <../source/grid/grid_in.cc> in function
2:     void dealii::GridIn<dim, spacedim>::read_msh(std::istream&) [with int dim = 2; int spacedim = 2; std::istream = std::basic_istream<char>]
2: The violated condition was: 
2:     n_physicals < 2
2: Additional information: 
2:     More than one tag is not supported!
2: --------------------------------------------------------
```

**Comment by tamiko** [comment]
In reference to #8170

**Comment by bangerth** [comment]
Hm, this was already tracked in #7326. It should have been fixed by #7414.

**Comment by tamiko** [comment]
@luca-heltai @bangerth #7414 was about mesh format 4.0 not 4.1 if I recall correctly.

Output file for `gmsh/create_tria_01` with gmsh 4.3:
```
$MeshFormat
4.1 0 8
$EndMeshFormat
$PhysicalNames
1
2 1 "dealii_surface"
$EndPhysicalNames
$Entities
4 4 1 0
1 0 0 0 0 
2 25 0 0 0 
3 25 1 0 0 
4 0 1 0 0 
1 0 0 0 25 0 0 0 2 1 -2 
2 25 0 0 25 1 0 0 2 2 -3 
3 0 1 0 25 1 0 0 2 3 -4 
4 0 0 0 0 1 0 0 2 4 -1 
6 0 0 0 25 1 0 1 1 4 3 4 1 2 
$EndEntities
$Nodes
5 4 1 4
0 1 0 1
1
0 0 0
0 2 0 1
2
25 0 0
0 3 0 1
3
25 1 0
0 4 0 1
4
0 1 0
2 6 0 0
$EndNodes
$Elements
1 1 1 1
2 6 3 1
1 3 4 1 2 
$EndElements
```

**Comment by tamiko** [comment]
For reference gmsh-4.0 generates:
```
$MeshFormat
4 0 8
$EndMeshFormat
$PhysicalNames
1
2 1 "dealii_surface"
$EndPhysicalNames
$Entities
4 4 1 0
1 0 0 0 0 0 0 0 
2 25 0 0 25 0 0 0 
3 25 1 0 25 1 0 0 
4 0 1 0 0 1 0 0 
1 0 0 0 25 0 0 0 2 1 -2 
2 25 0 0 25 1 0 0 2 2 -3 
3 0 1 0 25 1 0 0 2 3 -4 
4 0 0 0 0 1 0 0 2 4 -1 
6 0 0 0 25 1 0 1 1 4 3 4 1 2 
$EndEntities
$Nodes
5 4
1 0 0 1
1 0 0 0
2 0 0 1
2 25 0 0
3 0 0 1
3 25 1 0
4 0 0 1
4 0 1 0
6 2 0 0
$EndNodes
$Elements
1 1
6 2 3 1
9 3 4 1 2 
$EndElements
```

**Comment by masterleinad** [comment]
> Output file for `gmsh/create_tria_01` with gmsh 4.3:

The line breaks look strange here...

> Hm, this was already tracked in #7326. It should have been fixed by #7414.

That was for `gmsh-4`, though. In case, the problem are really the multiple tags we need to decide which one to take for the boundary/manifold ids.

At least ,it seems that the version check is precise.

**Comment by luca-heltai** [comment]
Well, that also implies we now can have *both* boundary and manifold ids. I'd take the first tag for boundary/material id, and the second for manifold.

**Comment by luca-heltai** [comment]
I'll try to look into this tomorrow. Do you want to put this into 9.1?

**Comment by tamiko** [comment]
@luca-heltai It would be great to get that in for 9.1 (in particular given the fact that Debian/Ubuntu etc. are updated gmsh soonish). Getting some update tomorrow would be great! (In particular it would be great to be able to run the full testsuite before we tag the final release version on Tuesday).

**Comment by luca-heltai** [comment]
I'm having some difficulties on my mac, but I'm on it... Hopefully by tonight I'll have a working PR.

**Comment by tamiko** [comment]
@luca-heltai Roger. Ping me, if I can help with something.

**Comment by masterleinad** [comment]
I just don't understand how they can make an incompatible change to their mesh format without bumping the major version number...

**Comment by luca-heltai** [comment]
I have many issues with my current setup. I installed clang-8.0.0 in view of the new package release, and this apparently broke my mac... I'll double check that the fix works on a linux machine I just managed to update...
