### ISSUE TITLE
C2 continuity

### ISSUE THREAD

**Issue by SBahramH** [dealii/dealii#8273]
Dear all,

I am recently interested in dealii package and I am trying to figure out its capacities and limits. I am interested to model Euler-bernoulli beam therory and Kirchhoff plate theory, which require C2 continuity. Is there any example, where forth order (or even higher) differential equation is implemented? Or even is it possible to implement C2 continuity?

**Comment by drwells** [comment]
Are you sure that you need full C2 continuity? Usually beam models only require C1 continuity in the weak form.

Either way: we do not have support in the library for C1 or C2 elements in the library. The recommended approach for fourth-order problems is to split the problem into two coupled second-order problems.

We get this question a lot: we should really add an FAQ entry on this to the wiki.

**Comment by SBahramH** [comment]
Thanks a lot for the fast reply. To be more specific, I am planning to implement "gradient elasticity" for both cases, which requires higher continuity.

**Comment by drwells** [comment]
Ah.

I just realized that I didn't answer your second question: it should be *possible* to implement C^1 and higher elements in deal.II, but it would not be straightforward since these elements usually require individualized. unit-to-reference mappings.

**Comment by masterleinad** [comment]
We did that [here](https://arxiv.org/abs/1810.02473) for a topologically regular mesh.

**Comment by drwells** [comment]
I added an entry: see

https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-solve-problems-with-higher-regularity-requirements

I think this is enough to close the issue.
