### ISSUE TITLE
Read mesh issue introduced by gmsh-4.1 fix

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#8276]
@luca-heltai @masterleinad Houston, we have a problem.

The GMSH-4.1 compatibility changes introduced by d4815f3c75bb346a278f677e4c9c251171f58088 introduce 12 failing tests [1], all related to `dealii::GridIn<dim, spacedim>::read_msh(std::istream&)`. This is a regression we have to fix, and we have to make a point release to 9.1.1 in order to address this.

  [1] https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=10013

**Comment by tamiko** [comment]
Guess I was a bit fast with tagging...

**Comment by davydden** [comment]
> Guess I was a bit fast with tagging...

looks like it 😢 

Shall we wait for https://github.com/dealii/dealii/issues/8275 to be resolved as well?

**Comment by masterleinad** [comment]
What is the `gmsh` version for the testers?

**Comment by masterleinad** [comment]
I guess we can just replace the switch statement and its body by
```
if (gmsh_file_format < 20)
...
else if (gmsh_file_format <= 41)
...
else
```

**Comment by tamiko** [comment]
@masterleinad The server runs gmsh-4.0.2, but that's not the problem here. The failing tests store their own ancient `msh` files - see for example `tests/grid_in_msh_02/mesh.msh`.

**Comment by tamiko** [comment]
@masterleinad I am a bit surprised that we can actually hit the `AssertThrow(false, ExcNotImplemented());` in line 1826. From the control flow it looks like this should never happen.

**Comment by tamiko** [comment]
@davydden Yes.
