### ISSUE TITLE
Improve step-17

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#829]
Step-17 is well documented but there is no subsection in the commented program (it's just one huge block). There is also a big TODO in the middle of ```assemble_system()```.

**Comment by bangerth** [comment]
Oh, I clicked on the link at the bottom of the email thinking that I would get to approve a pull request -- I guess that was wishful thinking. I'm not too fond of step-17/18, but you're right that eventually we should think about what we want to do with them. 

@davydov had this nice patch with the shared triangulation that would have neatly replaced the program by something I'd much more happy with. But all of this is of course for another day.
