### ISSUE TITLE
Version 9.1.1 installs detailed.log and summary.log into $PREFIX

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#8290]
Please remove these files.

**Comment by drwells** [comment]
We decided to install these in #7201: I think it makes sense to disable this for releases (the build environment is not necessarily on the machine).

**Comment by tamiko** [comment]
Yes, we violate the FSHS by installing these two files into `${PREFIX}`. But it is also true that you can easily remove them again with a one-liner in your ports file.

We don't need another point release for that change.

**Comment by tamiko** [comment]
@yurivict It does so only if `DEAL_II_DOCREADME_RELDIR` is not modified. For packagaging purposes, please set the following variables on the command line to whatever convention FreeBSD follows:
```
-DDEAL_II_DOCHTML_RELDIR="share/doc/dealii/html"
-DDEAL_II_DOCREADME_RELDIR="share/doc/dealii"                                           
-DDEAL_II_EXAMPLES_RELDIR="share/doc/dealii/examples"
-DDEAL_II_LIBRARY_RELDIR="lib64"
-DDEAL_II_SHARE_RELDIR="share/dealii"
```
