### ISSUE TITLE
Code optimizations for >100k MPI ranks

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8293]
I'm looking at a run of deal.II on 304,128 cores right now:
```
Cycle 34
Time create grid              25.407      [p169179] 25.43       25.459      [p17739 ]
Time distribute DG dofs       8.8281      [p199286] 8.8357      8.8419      [p117609]
Number of degrees of freedom  1,099,511,627,776 = (4,096 x 2,048 x 2,048) x 4^3
Time distribute fe dofs       7.5373      [p10692 ] 7.5441      7.5643      [p98357 ]
Time distribute fe mg dofs    8.7065      [p197882] 9.3725      9.9435      [p2837  ]
Compute numbering L0          0.22594     [p251129] 0.30643     0.37282     [p20196 ]
Apply new numbers L0          0.19688     [p195524] 0.25103     0.27644     [p26683 ]
Compute numbering L1          0.18782     [p129933] 0.22178     0.25139     [p182506]
Apply new numbers L1          0.1976      [p164685] 0.25189     0.28095     [p109296]
Compute numbering L2          0.19066     [p204755] 0.2251      0.24673     [p20984 ]
Apply new numbers L2          0.2033      [p7121  ] 0.25571     0.28955     [p166320]
Compute numbering L3          0.18837     [p260943] 0.22299     0.24845     [p44645 ]
Apply new numbers L3          0.19909     [p133311] 0.25184     0.2965      [p187072]
Compute numbering L4          0.18634     [p98239 ] 0.22364     0.24942     [p212268]
Apply new numbers L4          0.20318     [p195401] 0.25861     0.31113     [p16181 ]
Compute numbering L5          0.1919      [p274846] 0.22556     0.24382     [p99466 ]
Apply new numbers L5          0.27852     [p194310] 0.31275     0.33555     [p156624]
Compute numbering L6          0.20708     [p97629 ] 0.2337      0.26738     [p72537 ]
Apply new numbers L6          0.31305     [p10692 ] 0.34891     0.37427     [p41142 ]
Compute numbering L7          0.20731     [p171822] 0.23188     0.24859     [p48050 ]
Apply new numbers L7          0.31745     [p152361] 0.34565     0.3826      [p144677]
Compute numbering L8          0.2073      [p302909] 0.23454     0.247       [p216398]
Apply new numbers L8          0.31612     [p196019] 0.34979     0.39201     [p114101]
Compute numbering L9          0.22149     [p237418] 0.24978     0.27724     [p66485 ]
Apply new numbers L9          0.32666     [p10344 ] 0.35676     0.38582     [p141273]
Compute numbering L10         0.32101     [p302936] 0.35299     0.40104     [p36674 ]
Apply new numbers L10         0.37295     [p10692 ] 0.40364     0.45071     [p14258 ]
Compute numbering L4294967295 0.7249      [p195567] 0.82176     0.93204     [p292661]
Apply new numbers active      0.53602     [p10692 ] 0.58654     0.67487     [p225221]
Apply new numbers L11         0.61007     [p195542] 0.65893     0.702       [p167104]
Time renumber fe dofs         9.5388      [p149390] 9.5409      9.542       [p171113]
Time matrix-free SP           5.2877      [p189471] 5.3075      5.3493      [p12578 ]
Time matrix-free DP           1.3225      [p3326  ] 1.3242      1.3318      [p93216 ]
Time build MG transfer        10.454      [p195981] 10.455      10.458      [p224352]
Time compute rhs              0.76855 rhs_norm = 0.0031709
Smoother norms: 9.6257 21.055 75.752 421.17 2474.3 14335 82102 4.6734e+05 2.6519e+06 1.5025e+07 8.506e+07 4.8136e+08 
Time initial smoother         1.2998      [p197677] 1.4553      1.6285      [p66233 ]
Memory stats [MB]             1219.5      [p46034 ] 1445.7      1591.8      [p219288]
Time solve CG                 4.1745      [p388   ] 4.1755      4.1777      [p94100 ]
Time solve CG                 1.8059      [p1352  ] 1.8068      1.8115      [p86899 ]
Time solve CG                 1.8075      [p347   ] 1.8084      1.8133      [p86892 ]
Time solve CG                 1.7776      [p499   ] 1.7785      1.7835      [p86892 ]
Time solve CG                 1.8023      [p38954 ] 1.8032      1.8081      [p86892 ]
Coarse solver 40 times: 0.0043462 tot prec 33.3
level  smoother    mg_mv     mg_vec    restrict  prolongate  inhomBC
L1     0.01067     0.0006896 0         0.0008517 0.0004574   0         
L2     0.01457     0.0009808 0         0.00152   0.0006535   0         
L3     0.01882     0.001236  0         0.002734  0.000829    0         
L4     0.01816     0.001624  0         0.003392  0.0009296   0         
L5     0.01757     0.001329  0         0.002745  0.001094    0         
L6     0.02939     0.002053  0         0.002917  0.0008366   0         
L7     0.07084     0.004982  0         0.003383  0.001885    0         
L8     0.2386      0.04006   0         0.02702   0.003944    0         
L9     0.7709      0.07352   0         0.06638   0.005125    0         
L10    1.681       0.1725    0         0.1934    0.04947     0         
L11    6.68        0.5491    0         0.3238    0.2834      0         
L12    16.52       1.459     3.529     0         0.4065      0         
Time matvec dp 40 loop        1.686       [p197685] 1.9416      2.0897      [p1104  ]
Time matvec dp 40 communic    0.098728    [p0     ] 0.2972      0.4907      [p169208]
Time matvec sp 495 loop       12.848      [p10323 ] 14.607      16.372      [p39125 ]
Time matvec sp 495 communic   0.80516     [p303120] 1.878       3.289       [p15104 ]
matvec time dp 0.046833 [p195802] 0.047942 0.048857 [p164744] DoFs/s: 2.2505e+13
matvec time dp 0.046986 [p195722] 0.047927 0.049195 [p275864] DoFs/s: 2.235e+13
matvec time dp 0.047256 [p198353] 0.048183 0.049226 [p245760] DoFs/s: 2.2336e+13
matvec time dp 0.046758 [p197886] 0.04803 0.049288 [p96048] DoFs/s: 2.2308e+13
matvec time dp 0.046892 [p197910] 0.048172 0.04935 [p818] DoFs/s: 2.228e+13
matvec time sp 0.026805 [p197910] 0.027658 0.028606 [p233241] DoFs/s: 3.8436e+13
matvec time sp 0.027168 [p2376] 0.02797 0.028704 [p174529] DoFs/s: 3.8306e+13
matvec time sp 0.02694 [p297500] 0.027689 0.028733 [p864] DoFs/s: 3.8267e+13
matvec time sp 0.027009 [p130340] 0.027762 0.028784 [p194] DoFs/s: 3.8198e+13
matvec time sp 0.026886 [p173745] 0.027686 0.02832 [p138761] DoFs/s: 3.8825e+13
Time matvec dp 250 loop       8.984       [p32413 ] 10.362      11.448      [p63216 ]
Time matvec dp 250 communic   0.60251     [p241632] 1.6483      2.9994      [p234265]
Time matvec sp 250 loop       5.0261      [p195477] 5.8392      6.4069      [p274992]
Time matvec sp 250 communic   0.51705     [p274992] 1.0965      1.8718      [p32228 ]
```
This experiment certifies that deal.II is able to do totally unexciting things given 2.5 MW of power budget, like solving Poisson's equation on a cube :wink: - well, at least it does so with 1 trillion unknowns. It uses a customized variant of deal.II's matrix-free solvers with some additional shortcuts that I plan to bring into deal.II during the coming months. Solver code: https://github.com/kronbichler/multigrid/tree/experimental_merge_vector/common

There are several things that worry me and that we should address:
- [x] The memory consumption of small computations is already around 800 MB per MPI rank. This is likely addressed by #8067, together with some timing implications. I had a larger computation with 1.9 trillion dofs doing fine all the way until the CG solver requested its auxiliary vectors, which is the last spike in memory consumption of my program. I successfully completed a simulation with half the number of dofs on half the number of MPI ranks, so the memory is an issue:
```
Number of degrees of freedom  1,855,425,871,872 = (2,048 x 2,048 x 2,048) x 6^3
...
Memory stats [MB]             1625.3      [p55538 ] 1896.4      2010.9      [p14427 ]
... out of memory ...
```
- [x] The solver phase, involving a conjugate gradient solver plus a geometric multigrid preconditioner involving 2 V-cycles, so some of the heavier global communication one can think of, can scale to as low times as 0.02 seconds for the complete solve (the time recorded for 8 billion unknowns on 300k ranks). However, essentially every setup on *every* level takes at least 0.2 seconds. I suspect this is due to an excessive number of `MPI_Allgather` functions and similar operations. We need to go through the implementations and check for alternatives.
- [x] One possible solution that I will look into together with @peterrum are sub-communicators for the MPI-shared memory region that will hopefully avoid some bottlenecks. This might also help with the excessive cost of data exchange, seen by comparion the "Time matvec dp XXX communic" section versus the "Time matvec dp XXX loop" section doing the actual work.

**Comment by tjhei** [comment]
Impressive!
Do you have statistics about the various objects that consume the 800 MB memory?
Let me know if I or @tcclevenger can help with anything.

**Comment by bangerth** [comment]
> This experiment certifies that deal.II is able to do totally unexciting things 
> given 2.5 MW of power budget, like solving Poisson's equation on a cube 😉

:-)

**Comment by kronbichler** [comment]
Since it will take a few weeks until my next run on 300k cores, I extracted two weak scaling tables that should allow us to track progress on a smaller scale.

Fixed size: 6.10M DoFs/core
```
Number of cores      |    38k |   152k | 304k
Time grid            | 2.2036 | 5.4788 | 17.281
Time dofs            | 18.131 | 18.287 | 18.299
Time mg dofs         | 17.079 | 18.700 | 19.884
Time renumber mg     | 4.3024 | 6.7093 | 11.131
Time mat-free levels | 3.1533 | 4.4211 | 6.2041
Time mg transfer     | 2.4694 | 5.5551 | 11.203
Memory average       | 1415.4 | 1643.0 | 1896.2
Memory highest       | 1509.2 | 1738.2 | 2029.5
Time solve           | 2.7745 | 2.868  | out-of-mem
```
I have two jobs with 19k and 76k ranks in the queue to fill in add additional data points but this table makes pretty clear that a number of our reinit routines are non-optimal and we should look into them. Note that the 304k results are minima out of three runs, and I see e.g. the grid setup taking 22s and 25s on the other two runs. I also note that the 304k result has one more level than the other two cases (and the 19k result would have yet another one less).

Here is a smaller data point with 95k DoFs/core, i.e., 1/64th the previous size, to emphasize what parts have non-negligible O(1) costs:
```
Number of cores      |    38k |   152k | 304k
Time grid            | 0.5303 | 3.1762 | 14.468
Time dofs            | 1.7935 | 1.8678 | 1.9844
Time mg dofs         | 2.3606 | 2.8624 | 3.9505
Time renumber mg     | 0.5666 | 2.5619 | 6.1974
Time mat-free levels |   0.26 | 1.1676 | 2.8949
Time mg transfer     |  0.555 | 3.0411 | 7.747
Memory average       |  272.8 | 554.31 | 698.81
Memory highest       | 294.82 | 588.15 | 780.98
Time solve           | 0.0554 | 0.0579 | 0.06367
```
Apart from the solver which shows an ~50x speedup for 1/64th the size, times for everything else reduce by a much more modest, if not embarrassingly bad, rate.

**Comment by kronbichler** [comment]
> Do you have statistics about the various objects that consume the 800 MB memory?

Unfortunately not for the big run, I only have the memory statistics I recorded. But I will prepare some more information during my next run, so now I'm going to look into some obvious places, in particular all places which are filled via `MPI_Allgather`. Not sure how accurate our `memory_consumption` functions are, though.

**Comment by tjhei** [comment]
> Not sure how accurate our `memory_consumption` functions are, though.

I think it varies by class and I wouldn't be surprised if things are missing. I am not sure how to approach this except looking into the implementation. We were thinking about doing this on a much smaller scale to get a better idea about memory consumption.

**Comment by kronbichler** [comment]
I have not yet been able to extract all the numbers for some new runs I did last night, but #8298 and #8300 can be considered a success in terms of the memory consumption. A small setup now involves 200-300 MB/MPI rank just as serial computations, rather than 700 MB before those patches. This pushes the largest problems that can be solved.

While my code would previously fail with 1.9 trillion dofs on 6336 nodes with 96 GB RAM each, I have now solved a problem with 2.15 trillion dofs fine with a peak memory consumption of 1.6 GB / core in 3.5 seconds:
```
Time create grid              12.61       [p88192 ] 12.649     12.666      [p225721]
Time distribute DG dofs       16.06       [p0     ] 16.064     16.068      [p49712 ]
Number of degrees of freedom  2,147,483,648,000 = (4,096 x 2,048 x 2,048) x 5^3
Time distribute fe dofs       16.113      [p304127] 16.116     16.12       [p63201 ]
Time distribute fe mg dofs    14.063      [p119481] 15.429     16.417      [p146   ]
Time renumber fe dofs         26.347      [p256137] 26.362     26.386      [p88184 ]
Time matrix-free SP           8.5006      [p50199 ] 8.5138     8.6367      [p152568]
Time matrix-free DP           3.2892      [p188648] 3.2921     3.321       [p168199]
Time build MG transfer        14.539      [p54307 ] 14.542     14.548      [p171147]
Time compute rhs              1.7541 rhs_norm = 0.0023701
Time initial smoother         5.3549      [p221930] 5.4683     6.9039      [p185643]
Memory stats [MB]             1249.8      [p55538 ] 1529.5     1641        [p16525 ]
Time solve CG [best of 40]    3.4618      [p567   ] 3.469      3.5181      [p94913 ]
matvec time dp 0.087361 [p130338] 0.08851 0.090504 [p232031] DoFs/s: 2.3728e+13
matvec time sp 0.049628 [p21681] 0.050827 0.052075 [p83051] DoFs/s: 4.1238e+13
```

**Comment by kronbichler** [comment]
I will consider this fixed when we have #8813 merged (even though we only addressed a small subset of the sub-communicators in my third bullet point for setup of a fully distributed triangulation, but that is a different topic), so I put the marker there.

**Comment by kronbichler** [comment]
To document the progress, here are two figures both run with 1024 nodes (49,152 MPI ranks) on my favorite multigrid benchmark (`FE_DGQHermite` of degree 5, using coarsening via `FE_Q` of degree 5), recording setup costs only, listed as a function of the problem size. Ideally, we would expect a linear increase with the problem size (or decrease if you read the plots from right to left).

This is the status shortly after the release 9.1:
![scaling_may](https://user-images.githubusercontent.com/8276200/65583651-e659db80-df7f-11e9-8062-93e4dd2a6c17.png)

And this is now (including the patch #8813):
![scaling_september2](https://user-images.githubusercontent.com/8276200/65583702-01c4e680-df80-11e9-9e13-595c658f7e80.png)

The items in the list are the following:
- mesh: `GridGenerator::hyper_rectangle` (using a 1x1x1, 2x1x1, 2x2x1 base mesh) and `Triangulation::refine_global()`
- dist dofs: `DoFHandler::distribute_dofs(FE_DGQHermite<3>(5))`
- dist fe dofs: `DoFHandler::distribute_dofs(FE_Q<3>(5))`
- dist fe mg dofs: `DoFHandler::distribute_mg_dofs()` (on the `DoFHandler` associated with `FE_Q`)
- renumber mg: I renumber the `FE_Q` degrees of freedom on all levels and the active cells by some sophisticated algorithm to increase data locality that I plan to contribute soon. It involves setting up a MatrixFree object on each level and doing some index searches there. I also have some 30 timers with an `MPI_Allreduce(MinMaxAvg)` in there to display details I used for debugging, which might also affect scaling a bit compared to the other quantities. This also includes setup of `MGConstrainedDoFs`
- mf sp: Setup of MatrixFree on all levels (`FE_Q`) in single precision as well as a MatrixFree for `FE_DGQHermite` in single precision
- mf dp: Setup of MatrixFree on active unknowns for `FE_DGQHermite` in double precision
- mg transfer: `MGTransferMatrixFree::build(DoFHandler&)`
- smoother: Computation of diagonal on all levels by some matrix-free algorithm (apply operator on unit vectors on each cell separately)

The *smoother* part is essentially the same in both figures and scales well, so it can be considered as the point of comparison for the other graphs (and a reference for what ideal scaling would be). Apart from the meshing which we know is difficult - and where we depend on the scalability of p4est as well - we now get very good performance for all components. The renumbering is a bit expensive but given that I do set up several `Utilities::MPI::Partitioner` objects on all levels that each must do dictionary-based index lookup, and the aforementioned `MPI_Allreduce for timing purposes, even that is good enough at this stage in my opinion.

**Comment by bangerth** [comment]
Impressive!
