### ISSUE TITLE
Changes page not reachable.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#8295]
Tha page 

https://www.dealii.org/current/doxygen/deal.II/changes_between_9_0_1_and_9_1_0.html

is not there (and we point to it from the menu of the release).

**Comment by kronbichler** [comment]
I guess the problem is that we need to move the `current` directory to the new 9.1 release files. Can someone with access to the online doxygen infrastructure adjust that?

**Comment by masterleinad** [comment]
It seems that we haven't generated documentation for the release at all, yet.

**Comment by tamiko** [comment]
@guidokanschat *ping* 
The 9.1.0 documentation has not yet been generated on the webpage.

**Comment by tjhei** [comment]
/current/ and /9.1.1/ exist now, but I see a buggy menu show up when clicking the link above. Guido is looking into it...

**Comment by bangerth** [comment]
Hm, what is it that isn't working for you? The page looks reasonable to me. Are you using something other than chrome?

**Comment by tjhei** [comment]
> The page looks reasonable to me. Are you using something other than chrome?

it turns out chrome got confused because older versions were in the cache. Everything works after force-refreshing the page. :+1:
