### ISSUE TITLE
Add a CITATION.cff file

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8297]
There is an emerging standard of how to ask people to cite the right papers for a software:
  https://citation-file-format.github.io/
I suspect it would be easy for us to add such a file for the next release. An example is here:
  https://github.com/SCM-NV/qmflows/blob/master/CITATION.cff

**Comment by bangerth** [comment]
Let's postpone this until after the new paper is out with a page number.

**Comment by masterleinad** [comment]
This looks independent of any release if we are to mention the new overview paper.

**Comment by jpthiele** [comment]
Seems like I forgot a 'fixes' or similar, but we do have one now.
