### ISSUE TITLE
Replace n_..._dofs_per_processor in distribute_sparsity_pattern

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#8306]
In the discussion of #8298 we observed that `SparsityTools::distribute_sparsity_pattern` still uses the `n_locally_owned_dofs_per_processor` information that we want to discourage. This issue is to remind ourselves to eventually implement a better-performing alternative that avoids the MPI all-to-all communication, see also #8293.

**Comment by kronbichler** [comment]
This is also related to #8041 and #7831 which did some improved setup already.

**Comment by bangerth** [comment]
I was surprised that you deprecated that function. Is computing the all-gather of a single number per processor really that expensive? It doesn't take much memory either. (I do see the point why you wanted to get rid of the functionality for collecting the index sets on all processors.)

Do we call this function in essentially all parallel programs? As long as that is the case, there are no savings to getting rid of doing the all-gather in dof_handler_policy.cc already. Getting rid of it there is only useful if we find ways to avoid filling this argument to `SparsityTools::distribute_sparsity_pattern` altogether.

**Comment by kronbichler** [comment]
We do not call the collection of all index sets for all processors in all programs because Trilinos-based programs (that distribute the sparsity pattern via Trilinos facilities) or matrix-free programs do it on their own. But I agree that it is a considerable share of our parallel programs nonetheless. As I said, I will look into it more closely.

> I was surprised that you deprecated that function. Is computing the all-gather of a single number per processor really that expensive?

As I discussed in #8298 with @tjhei, I only deprecated the function that returns the reference (because we do not hold it by default). There is a `compute_n_...` function that does the computation and which is still allowed.

Regarding its cost, one could think that it is not that expensive. However, when I did some measurements on 300k MPI ranks it was around 1-2 seconds per call when going through the variable `IndexSet` path that does the compression with zlib/boost (at least I believe that I had zlib enabled, I need to check on the machine when I get access to it again). The 1-2 seconds add up if you do it on every multigrid level, so this is clearly something that does hurt.

To give a bit more background, I am trying to look into a number of places that make our setup costs scale like this:
![scaling_costs](https://user-images.githubusercontent.com/8276200/59999992-9824fb80-9663-11e9-9b33-ec96c800890e.png)

This is a picture of a simulation with 43k time steps and 180m DoFs from [a paper about a wave equation solver with explicit time integration](https://doi.org/10.1016/j.softx.2019.01.001). Apart from the fact that the "computation" part is almost ridiculously optimized, the slope of the "mesh adaptation" part does worry me and is something I try to address over the coming years. It is not just a single inefficient part but rather the combination of several dozen spots that all do have some part that is not behaving optimally. The *allgather* related stuff was the most prominent one at an even larger scale. There are some really hard things among them, but there is plenty of low-hanging fruit. Or at least medium-low-hanging.

**Comment by bangerth** [comment]
Right, and I'm sure everyone agrees that we really appreciate the work you are putting into this! You have a unique skill set (and access to machines) that will make our lives so much better ten years from now when we all get to play at the kind of scale you're working at!

My question was strictly about computing the number of unknowns per processor. I understand that the thing with exchanging the `IndexSet` objects is expensive and, likely, unnecessary in many cases. But knowing how many DoFs each processor owns is useful and something that I *think* is often enough used that it might be of value to just compute once and store. But then, you're the expert and if you think it's too expensive, then let's not do it.

**Comment by kronbichler** [comment]
I agree that the information about the index sets all processors own (or the number of dofs, to take the reduced part) might get used again. My take on it is that
- it is pretty cheap to communicate it on small processor sizes so it won't likely hurt to do it repeatedly (I expect on the order of 1e-5...1e-4 seconds on up around a thousand MPI ranks)
- a user can still store it in the application program for repeated use as the documentation of the `compute_...._pre_processor` functions is clear that it involves global communication and could be expensive
- on more than a few thousands of MPI ranks, I would discourage to use that information as most of the information that is needed locally can be constructed by other means more cheaply. For example by the function in #8300 (which should be used here once we have it).
