### ISSUE TITLE
Documentation of Triangulation::set_manifold is incorrect

### ISSUE THREAD

**Issue by alexrobomind** [dealii/dealii#8309]
The documentation of Triangulation::set_manifold states:

The manifold_object is not copied and MUST persist until the triangulation is destroyed. This is also true for triangulations generated from this one by copy_triangulation.

However, the grid generator routines create a lot of manifolds from temporary objects and the implementation of set_manifold (https://www.dealii.org/current/doxygen/deal.II/grid_2tria_8cc_source.html#l08955) shows that this is not the case:

`manifold[m_number] = manifold_object.clone();`

**Comment by bangerth** [comment]
Yes, this is outdated -- it describes the status of a couple of years ago.

Want to try and write a pull request that fixes this? ;-)

**Comment by alexrobomind** [comment]
Will do, I just waited for a response from you to confirm my view on this.

**Comment by bangerth** [comment]
@alexrobomind -- I think that would be great. Thanks in advance!
