### ISSUE TITLE
LineMinimization not showing up in documentation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#8316]
The `LineMinimization` namespace in [`optimization/line_minimization.h`](https://github.com/dealii/dealii/blob/master/include/deal.II/optimization/line_minimization.h) is not showing up in the documentation. Maybe others in the `optimization` directory as well? This should be fixed.

**Comment by tjhei** [comment]
The namespace is there: https://www.dealii.org/developer/doxygen/deal.II/namespaceLineMinimization.html#a1851b14669971047cc128ef686ad128a

Or do you mean the source file itself?

**Comment by jppelteret** [comment]
But its not here: [https://www.dealii.org/current/doxygen/deal.II/namespaces.html](https://www.dealii.org/current/doxygen/deal.II/namespaces.html)

I looked at `current`, not `developer`. I guess I got confused because `current` still points to "Reference documentation for deal.II version 9.0.1". Clearly this link needs to be updated -- I can't remember if this is a known issue.
