### ISSUE TITLE
Documentation of GridTools::extract_boundary_mesh is incorrect

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#8321]
The documentation states: 

> For dim=2 (i.e., where volume cells are quadrilaterals and surface cells are lines), the order of vertices of surface cells and the corresponding volume faces match. For dim=3 (i.e., where volume cells are hexahedra and surface cells are quadrilaterals), the order of vertices may not match in order to ensure that each surface cell has a right-handed coordinate system when viewed from one of the two sides of the surface connecting the cells of the surface mesh.

however this is wrong for any non trivial mesh generated externally (for example using gmsh) also in dim = 2.

**Comment by starki0815** [comment]
I believe I fixed the documentation accordingly when I changed the behavior of `extract_boundary_mesh()` in 3ee095da99613918d6256b66d2df8dcaa0ea59b1; also I cannot find the paragraph you are citing in the current documentation ([here](https://dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#a0998531458df88a603ae008c726c3c6e)). Is it possible that you just used an old version of the documentation together with a current version of the library?

**Comment by drwells** [comment]
AFAICT @starki0815 is correct and this has been fixed. Hence, lets close the issue. @starki0815 thanks for double-checking this issue!
