### ISSUE TITLE
Different results in the test for Nedelec and NedelecSZ

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#8323]
Hi, I submitted the PR #8322 to add `std::complex` support for `project_boundary_values_curl_conforming_l2`.

When I wrote the test for #8322, I realized that the test `numerics/project_bv_curl_conf` (that is already in the repository) gives different results for `FE_Nedelec` than for `FE_NedelecSZ`. I think that the results of the test should be the same for both elements.

Results of `numerics/project_bv_curl_conf` for `FE_Nedelec`:
```
DEAL::dim=3:
    0 = 1.00000
    1 = 0
    2 = 1.00000
    3 = 0
    4 = 0.500000
    5 = 0
    6 = 0.500000
    7 = 0
```
Results of `numerics/project_bv_curl_conf` for `FE_NedelecSZ`:
```
DEAL::dim=3:
    0 = -1.00000
    1 = 0
    2 = -1.00000
    3 = 0
    4 = -0.500000
    5 = 0
    6 = -0.500000
    7 = 0
```

**Comment by masterleinad** [comment]
Why do you think that the output needs to be the same? In case the shape functions just differ by a sign, this should still be fine.

**Comment by dangars** [comment]
That makes sense!
I'm closing the issue
