### ISSUE TITLE
Communicate active_fe_indices after refinement?

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#8376]
Reviewing the recently added feature of an automatic transfer of `active_fe_indices` after refinement, I noticed that we are communicating these indices on ghost (and artificial) cells in case of a `parallel::shared::Triangulation` ...
https://github.com/dealii/dealii/blob/59a12e7559c7710ae4125632c9fea25be61d727d/source/hp/dof_handler.cc#L2119
... but skip it for `parallel::distributed::Triangulation`. Thus, they are only available on locally owned cells in the latter case.
https://github.com/dealii/dealii/blob/59a12e7559c7710ae4125632c9fea25be61d727d/source/hp/dof_handler.cc#L2148

---

In applications, we usually have to call `distribute_dofs()` which does the job of communicating the indices, but it may lead to confusion whenever a user wants to access an `active_fe_index` on a ghost cell immediately after refinement happened.

What do you think? Should we include the communication, or leave it out completely? I'll tend towards including the communication to avoid confusion of users.

I'll prepare a PR according to the result of this discussion :)

**Comment by bangerth** [comment]
Yes, I think that is reasonable. The added work is rather minimal, I imagine.
