### ISSUE TITLE
deal.ii does not compile, error in boost-1.17

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#8440]
Hi, I can't compile deal.ii due to an error with boost-1.17. Probably related to #8386

Boost requires the file `boost/type_traits/detail/is_function_cxx_03.hpp` which I don't understand because I'm using C++17. clang 3.9.

The file `boost/type_traits/detail/is_function_cxx_03.hpp` does not exists.

The file `bundled/boost-1.70.0/include/boost/type_traits/is_function.hpp` has the following code:
```c++
#ifdef BOOST_TT_HAS_ASCCURATE_IS_FUNCTION

#include <boost/type_traits/detail/is_function_cxx_11.hpp>

#else

#include <boost/type_traits/detail/is_function_cxx_03.hpp>

#endif
```
Why that file points to a file that does not exists in boost? Is that a bug in boost?

This is the error that I get:
```
In file included from /opt/src/dealii/bundled/boost-1.70.0/libs/serialization/src/basic_iarchive.cpp:34:
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/serialization/state_saver.hpp:32:
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/has_nothrow_copy.hpp:19:
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/is_copy_constructible.hpp:17:
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/is_constructible.hpp:17:     
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/is_destructible.hpp:15: 
In file included from /opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/is_complete.hpp:15:    
/opt/src/dealii/bundled/boost-1.70.0/include/boost/type_traits/is_function.hpp:23:10: fatal error: 'boost/type_traits/detail/is_function_cxx_03.hpp' file not found
#include <boost/type_traits/detail/is_function_cxx_03.hpp>
```

**Comment by dangars** [comment]
According to the website of boost clang c++ 3.9.1 is supported.
https://www.boost.org/users/history/version_1_70_0.html

**Comment by masterleinad** [comment]
Does it work if you copy that file? We are trying to keep the bundled boost at a minimum to support what we need in `deal.II` and it appears that this file didn't exist in `boost-1.62.0` and is not needed for the setups we regularly test for.

**Comment by dangars** [comment]
If I add the following files, it works :)
```
is_function_cxx_03.hpp
is_member_function_pointer_cxx_03.hpp
```
I downloaded those files directly from boost.

**Comment by masterleinad** [comment]
Great! Just create a pull request then.

**Comment by dangars** [comment]
Done :)
