### ISSUE TITLE
Rename parallel::Triangulation to parallel::TriangulationBase

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8535]
@tjhei *loves* the idea.

**Comment by peterrum** [comment]
I did understand the result of our discussion as following, expressed as a class hierarchy (see also the discussion in PR#8558):
* Tringulation
  * parallel::Triangulation
    * parallel::shared::Triangulation
    * **parallel::DistributedTrinagulationBase** (?)
      * parallel::distributed::Trianguation
      * parallel::fullydistributed::Trianguation  

In this circumstance, we would not have to rename `parallel::Triangulation`...

**Comment by bangerth** [comment]
@peterrum Your naming scheme is fine with me. But I also don't see much of a reason to not *also* rename `parallel::Triangulation` to `parallel::TriangulationBase`: it's a rather internal class, so I'm not too worried about it being incompatible.

**Comment by peterrum** [comment]
@bangerth @tjhei  The updated class hierarchy is as follows:
* Tringulation
  * **parallel::TriangulationBase**
    * parallel::shared::Triangulation
    * **parallel::DistributedTrinagulationBase**
      * parallel::distributed::Trianguation
      * parallel::fullydistributed::Trianguation

**Comment by peterrum** [comment]
We can close this issue. It has been resolved by PR #8600.

**Comment by masterleinad** [comment]
You know that you can close issues automatically by saying "Fixes #..." ? https://help.github.com/en/articles/closing-issues-using-keywords
