### ISSUE TITLE
Introduction of parallel::fullydistributed::Triangulation

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#8558]
At the 7th deal.II users and developers workshop, we have agreed on merging the new `parallel::fullydistributed::Triangulation` (short `p:f:t`, see also PR #8418) in at least 5 stages. The name `parallel::fullydistributed::Triangulation` has been accepted. The stages are:

**Step 1:** modify class hierarchy
- [x] rename `parallel::Triangulation` to `parallelTriangulationBase`
- [x]  introduce a new `parallel::DistributedTrinagulationBase`, which will be the base class for `p:d:t` and `p:f:t`. This way we can handle `p:d:t` and `p:f:t` at many places in the library the same way.

**Step 2:** generalization
- [x]  redefinition of `CellId`: `coarse_cell_id`s should define uniquely coarse cells (even in the fully distributed case)
- [x] let the user access `CellId`'s  `coarse_cell_id` directly
- [x]  rewrite the `DoFHandlerPolicy` of `p:d:t` such that it takes a reference to `parallel::DistributedTrinagulationBase`, only uses the redefined `CellID`s and does not use the p4est-mappings
- [x] Enable `DoFHandlerPolicy` of `p:d:t` for 1D
- [x] Implement `DoFAccessor::set/get_mg_dof_indices` for 1D

**Step 3:**
- [x]  introduce the new `parallel::fullydistributed::Triangulation` with a single method to create the `ConstructionData`

**Step 4:**
- [x]  introduce (de)serialization capabilities
- [x] perform partitioning by a subgroup of processes  

**Step 5:**
- [ ]  enable global coarsening and refinement

For the future we leave:
* introduce advanced multilevel portioning algorithms in  `parallel::fullydistributed::util`
* re-partitioning algorithms (in the form of an oracle)

*ping:* @bangerth, @tjhei, @tamiko, @luca-heltai, @kronbichler

**Comment by peterrum** [comment]
* In what way is #8535 related to the issue?
* How do we want to call the `ConstructionData`. We discussed the term `MeshPartitionerData`... I prefer the first term. Which term *loves* @bangerth *and* @tjhei?

**Comment by peterrum** [comment]
@bangerth @tjhei  I think the 6 PRs #8567, #8586, #8579, #8587, #8592, and #8593 contain all necessary generalizations of deal.II that are required by `p:f:t` to be able to run simulations on fully distributed triangulations (also for 1D with MG). Let's get these merged step by step!

In the meantime, I will locally update the `p:f:t` classes to the new infrastructure and will update the tutorials in my repo (hopefully that means only to recompile deal.II and the programs). Once the 6 PRs are merged, I will open the PR regarding the actual introduction of `p:f:t`. Although, the PR will only contain `p:f:t` and a single utility function to setup the triangulation (and some tests), I cannot guarantee it will be less than 100 locs.

**Comment by peterrum** [comment]
@bangerth @tjhei @kronbichler Regarding the next PR (which will contain the actual `p:f:t`)

Do you have any special tests in mind? I was thinking that I add step 1, 3, 4, 5, 7, and 8 from my [documentation](https://github.com/peterrum/dealii-pft). I leave (de)serialization and the advanced partitioning techniques for a later PR.

Side note: `p:f:t` seems to work with the new infrastructure after small change. So I am confident that I can open the PR soon.

**Comment by peterrum** [comment]
@tamiko I have slightly updated your code from #7988 for the new distributed triangulation:

```cpp
#include <deal.II/base/conditional_ostream.h>
#include <deal.II/base/timer.h>

#include <deal.II/distributed/fully_distributed_tria.h>
#include <deal.II/distributed/fully_distributed_tria_util.h>
#include <deal.II/distributed/tria.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>

#include <fstream>
#include <iostream>


const MPI_Comm comm = MPI_COMM_WORLD;

using namespace dealii;

template<int dim>
void
test(unsigned int refinement)
{
  
  ConditionalOStream pcout(std::cout, Utilities::MPI::this_mpi_process(comm)==0);

  dealii::TimerOutput timer(comm,
                            pcout,
                            TimerOutput::never,
                            TimerOutput::wall_times);

  pcout << "Running dim=" << dim << " refinement=" << refinement  << std::endl;
  
  Triangulation<dim> tria;
  {
    TimerOutput::Scope s(timer, "serial");

    pcout << "Creating serial triangulation... " << std::flush;
    Triangulation<dim> triangulation_temp;
    GridGenerator::hyper_cube(triangulation_temp);
    triangulation_temp.refine_global(refinement);
    GridGenerator::flatten_triangulation(triangulation_temp,
                                         tria);
    pcout << "done" << std::endl;
  }

  parallel::distributed::Triangulation<dim> pdt(comm);
  {
    TimerOutput::Scope s(timer, "parallel");

    pcout << "Copying to distributed triangulation... " << std::flush;
    pdt.copy_triangulation(tria);
    pcout << "done" << std::endl;
  }

  parallel::fullydistributed::Triangulation<dim> pft(comm);
  {
    TimerOutput::Scope s(timer, "fully_distributed");

    pcout << "Copying to pft... " << std::flush;
    
    {
      const unsigned int n_procs = Utilities::MPI::n_mpi_processes(comm);
      const unsigned int n_cells_per_process = (tria.n_active_cells() + n_procs) / n_procs;
      
      // partition equally the active cells
      for(auto cell : tria.active_cell_iterators ())
        cell->set_subdomain_id (cell->active_cell_index() / n_cells_per_process);
    }
    
    const auto construction_data = parallel::fullydistributed::Utilities::
    create_construction_data_from_triangulation(tria, comm);
    pft.create_triangulation(construction_data);
    pcout << "done" << std::endl;
  }

  timer.print_summary();
}

int
main(int argc, char **argv)
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
    
    for(unsigned int refinement = 7; refinement < 12; refinement++)
        test<2>(refinement);

  return 0;
}
```

**Comment by peterrum** [comment]
If I have not done any major mistake, this is my timings (on Intel(R) Xeon(R) CPU E5-2690 v4 with 28 cores):
```
Running dim=2 refinement=8
Creating serial triangulation... done
Copying to distributed triangulation... done
Copying to pft... done


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |     0.186s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| fully_distributed               |         1 |    0.0047s |       2.5% |
| parallel                        |         1 |    0.0707s |        38% |
| serial                          |         1 |     0.106s |        57% |
+---------------------------------+-----------+------------+------------+

Running dim=2 refinement=8
Creating serial triangulation... done
Copying to distributed triangulation... done
Copying to pft... done


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |     0.811s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| fully_distributed               |         1 |    0.0158s |       1.9% |
| parallel                        |         1 |     0.309s |        38% |
| serial                          |         1 |     0.484s |        60% |
+---------------------------------+-----------+------------+------------+

Running dim=2 refinement=9
Creating serial triangulation... done
Copying to distributed triangulation... done
Copying to pft... done


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      3.89s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| fully_distributed               |         1 |    0.0743s |       1.9% |
| parallel                        |         1 |      1.71s |        44% |
| serial                          |         1 |       2.1s |        54% |
+---------------------------------+-----------+------------+------------+

Running dim=2 refinement=10
Creating serial triangulation... done
Copying to distributed triangulation... done
Copying to pft... done


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      20.3s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| fully_distributed               |         1 |     0.378s |       1.9% |
| parallel                        |         1 |      10.4s |        51% |
| serial                          |         1 |      9.52s |        47% |
+---------------------------------+-----------+------------+------------+

Running dim=2 refinement=11
Creating serial triangulation... done
Copying to distributed triangulation... done
Copying to pft... done


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |       143s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| fully_distributed               |         1 |      1.83s |       1.3% |
| parallel                        |         1 |      99.5s |        69% |
| serial                          |         1 |      42.2s |        29% |
+---------------------------------+-----------+------------+------------+
```

ping @bangerth @tjhei @kronbichler @tamiko

**Comment by kronbichler** [comment]
For reference of these timings, can you measure how much time is needed if you do not initially create a serial triangulation, flatten it, and copy to a parallel distributed triangulation, but create a parallel distributed straight away, so a hyper-cube and then 8-11 refinements?

**Comment by peterrum** [comment]
@kronbichler  I have updated the numbers and measurements with your suggestion!

**Comment by peterrum** [comment]
I am closing this one, since I think I consider p:f:T as introduced even if *enable global coarsening and refinement* is not working. For now, I am quite happy the way p:f:T is created (based on another triangulation and no way to alter it).
