### ISSUE TITLE
begin() and end() of PETScWrappers::MPI::SparseMatrix segfaults

### ISSUE THREAD

**Issue by starki0815** [dealii/dealii#8571]
This little example segfaults if run on more than one processor:
```cpp
#include <vector>
#include <iostream>

#include <deal.II/base/mpi.h>
#include <deal.II/lac/petsc_sparse_matrix.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>

using namespace dealii;
using namespace std;

int main(int argc, char **argv)
{
	Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

	int n_procs;
	MPI_Comm_size(MPI_COMM_WORLD, &n_procs);

	int this_proc;
	MPI_Comm_rank(MPI_COMM_WORLD, &this_proc);

	IndexSet local_indices(n_procs);
	local_indices.add_index(this_proc);

	vector<unsigned int> n_rows_per_proc(n_procs, 1);

	DynamicSparsityPattern dsp(local_indices);

	PETScWrappers::MPI::SparseMatrix K(MPI_COMM_WORLD, dsp, n_rows_per_proc, n_rows_per_proc, this_proc);

	K = 0.0;
	K.compress(VectorOperation::insert);

	// this fails if run with more than one processor
	// the reason is that begin() will always start from the first global line,
	// no matter what the local range is; similarly end() will always point past
	// the last global line, no matter what the local range is
	if(this_proc == 1)
		cout << K.begin()->column() << endl;
}
```

The reason seems to be that  `begin()` and `end()` of the base class `PETScWrappers::MatrixBase` don't check for the local range. So, my suggestion would be to make sure that  `begin()` and `end()` take the local range into consideration. If there's nothing opposed to this approach, I can write a patch for this.

**Comment by bangerth** [comment]
My preferred approach would be to put an assertion into `begin()` that says that you can only do that on processor zero, and on all other processors need to call `begin(first_locally_owned_row)` and similarly `end(last_locally_owned_row)`.

I think that silently doing this hides the fact that different processors will loop over a different set of elements, even though that is not obvious to the person writing the code.

**Comment by starki0815** [comment]
Ok, good point. I will just add assertions into `begin()` and `end()`.

**Comment by starki0815** [comment]
I am struggling a bit with the following issues:

(1) Even if `begin()` is called only on the first processor, it will still run into an assertion if the first locally owned line on the first processor is actually an empty line. How to deal with that? Just assume that the user checks that the row length of the first row is greater than zero or increment to the first non-zero line if there is one (and assert if there is actually no non-zero line)?

(2) The behavior will not be consistent with what `LinearAlgebra::distributed::Vector` does. Because there the documentation for `begin()` says 

> Make the Vector class a bit like the vector<> class of the C++ standard library by returning iterators to the start and end of the locally owned elements of this vector.

In any case, if the behavior of `begin()` and `end()` is that it can only be called on the first and last processor, respectively, the functions are not of much value anyway in parallel then. So, wouldn't it make sense to just assert on that `begin()` and `end()` cannot be used in parallel and generally refer the user to `begin(row)` and `end(row)`?

**Comment by bangerth** [comment]
On 8/15/19 3:54 AM, Sebastian Stark wrote:
> (1) Even if |begin()| is called only on the first processor, it will 
> still run into an assertion if the first locally owned line on the first 
> processor is actually an empty line. How to deal with that? Just assume 
> that the user checks that the row length of the first row is greater 
> than zero or increment to the first non-zero line if there is one (and 
> assert if there is actually no non-zero line)?

That's an issue also on sequential cases as well? What the user expects 
for `begin()` is to get a pointer to the first element of a matrix, 
whichever row it may live in. For `begin(row)`, the user expects a 
pointer to the first element of row `row` or, if there are no elements 
in this row, the return value of `end(row)`, whatever that may be.


> (2) The behavior will not be consistent with what 
> |LinearAlgebra::distributed::Vector| does. Because there the 
> documentation for |begin()| says
> 
>     Make the Vector class a bit like the vector<> class of the C++
>     standard library by returning iterators to the start and end of the
>     locally owned elements of this vector.
> 
> In any case, if the behavior of |begin()| and |end()| is that it can 
> only be called on the first and last processor, respectively, the 
> functions are not of much value anyway in parallel then. So, wouldn't it 
> make sense to just assert on that |begin()| and |end()| cannot be used 
> in parallel and generally refer the user to |begin(row)| and |end(row)|?

Yes, that is correct. It is unfortunate that 
`LinearAlgebra::distributed::Vector` does something different -- I think 
that the latter is a mistake :-(

**Comment by starki0815** [comment]
> That's an issue also on sequential cases as well? What the user expects for `begin()` is to get a pointer to the first element of a matrix, whichever row it may live in. For `begin(row)`, the user expects a pointer to the first element of row `row` or, if there are no elements in this row, the return value of `end(row)`, whatever that may be.

Yes, that does fail in sequential as well. Probably you are right that most of the time the user expects what you describe when using `begin()`, though I was rather convinced that `for(const auto& index : matrix)` loops over the elements the current processor knows about without asking anybody else.
So, for the sequential case, I'll change the behavior so that begin() returns the first element of the matrix existing in the sparsity pattern. To cover the parallel case, does it make sense for you to generally assert on whether the calling processor owns all elements (i.e., the global range is equal to the local range) and add a note to the documentation? I think this would prevent the user from making any, possibly invalid, assumptions. If you prefer that `begin()` can only be called on the first processor and `end()` on the last processor, I can do that as well (though what happens will then depend on whether the first processor actually has elements in its part of the sparsity pattern or not).

**Comment by bangerth** [comment]
I think that's an entirely reasonable approach: `begin()` and `end()` can only be called if a process owns all rows. In all other cases, an assertion triggers. So yes, please go ahead with the approach you suggest!
