### ISSUE TITLE
petsc 3.5.3 doesn't work with 64 bit indices

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#863]
PETSc 3.5.3 crashes when using 64 bit indices. I'll look into it when I'm back in College Station at the end of the week.

**Comment by Rombur** [comment]
The tests passed on my machine with PETSc 3.5.3 and gcc-4.9.1 @tamiko can you check that PETSc is configured correctly on simserv04.

**Comment by tamiko** [comment]
@rombur Can you provide me with a working ```$PETSC_ARCH/conf/configure.log```, please? I cannot spot an obvious mistake, i.e. PETSc was configured with ```--with-64-bit-indices```.

**Comment by tamiko** [comment]
@rombur Ah, stop. I have an idea. This is a Gentoo prefix setup that has the tendency to mess with rpaths. Let me check.

**Comment by tamiko** [comment]
Ok. Should be fixed now.

**Comment by tamiko** [comment]
@rombur Now we have ```libbob``` (which is ```libdeal_II```) linking against ```libbobsc``` (which is ```libpetsc```):

```
mmaier@simserv04 build % mpirun -np 1 ldd lib/libbob.g.so | grep petsc
        libbobsc.so.3.5 => /mnt/data/testsuite/petsc-3.5.3/linux-gnu-cxx-opt/lib/libbobsc.so.3.5 (0x00007fc227824000)
```
