### ISSUE TITLE
Implement exact inverse transformation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#866]
Against all odds, I have been pointed to the fact that at least in 2d, one can write down an exact answer to the inverse of the mapping from reference cell to real cell. We currently use a Newton method. The formula is here:
http://nbviewer.ipython.org/gist/nicoguaro/73d1cd14b1aa19a4b817

Given how much trouble the Newton iteration is often giving us, we might want to try this!

**Comment by bangerth** [comment]
And here it is in Maple, already with coordinates:
```
> eqs := { x = x0*(1-xi)*(1-eta)+x1*xi*(1-eta)+x2*(1-xi)*eta+\                                                          
> x3*xi*eta, y = y0*(1-xi)*(1-eta)+y1*xi*(1-eta)+y2*(1-xi)*eta+y3*xi*eta };
eqs := {x = x0 (1 - xi) (1 - eta) + x1 xi (1 - eta) + x2 (1 - xi) eta + x3 xi eta,

    y = y0 (1 - xi) (1 - eta) + y1 xi (1 - eta) + y2 (1 - xi) eta + y3 xi eta}

> solve (eqs, {xi,eta});                                                                                                
memory used=3.5MB, alloc=40.3MB, time=0.21
               x0 %1 - x1 %1 + x - x0
{eta = ---------------------------------------, xi = %1}
       x0 %1 - x1 %1 - x2 %1 + x3 %1 - x0 + x2

                                                                               2
%1 := RootOf((x0 y2 - x0 y3 - x1 y2 + x1 y3 - x2 y0 + x2 y1 + x3 y0 - x3 y1) _Z

     + (-x y0 + x y1 + x y2 - x y3 + x0 y - 2 x0 y2 + x0 y3 - x1 y + x1 y2 - x2 y + 2 x2 y0 - x2 y1 + x3 y - x3 y0) _Z

     + x y0 - x y2 - x0 y + x0 y2 + x2 y - x2 y0)
```

**Comment by bangerth** [comment]
The place to implement this is in `MappingQ1::transform_real_to_unit_cell`.

**Comment by drwells** [comment]
I believe that this can be closed now, due to what I did in #1177. It is implemented, but I do not (and I talked about this with @tamiko at the workshop) believe there is a robust way to obviate the Newton algorithm in 2D.

**Comment by bangerth** [comment]
I think the direct algorithm will only fail if the point actually lies outside the cell. For most cases this will not be relevant if we find ways to filter out these cases. For example, we could implement the things discussed in #314 for `CellAccessor::point_inside`. But for the current issue, let's close it indeed.

**Comment by drwells** [comment]
I set up the logic so that if the direct method determines that the point lies outside the cell, then the Newton method is always used (I did this to keep the output consistent with what the direct method replaced). Put another way, I force the direct method to always 'fail' if the point is outside the cell.

I should add this to the method documentation.
