### ISSUE TITLE
Rename AnisotropicPolynomials::compute() to evaluate()

### ISSUE THREAD

**Issue by GrahamBenHarper** [dealii/dealii#8682]
This is a follow-up to #8619 to make all the polynomials classes consistent; however, this is used in many test files and also referred to by classes like `PolynomialsBernardiRaugel`, so the changes for this will likely span many files.

This was made obvious in  #8678 while changing the test `anisotropic_1.cc`. Now there are two polynomial spaces side-by-side, one is `TensorProductPolynomials<dim>`, and one is `AnisotropicPolynomials<dim>`, and the former calls `evaluate()` but the latter calls `compute()`.

**Comment by bangerth** [comment]
Yes, we should clean that up as well. Couldn't we also derive `AnisotropicPolynomials` from `ScalarPolynomialsBase` eventually? (In a follow-up, once everything else is settled?)

Part of #1973.

**Comment by GrahamBenHarper** [comment]
Yes deriving it from `ScalarPolynomialsBase` would be the best idea. From what I saw, there's enough work that I could tackle it as its own PR in the next week.

**Comment by bangerth** [comment]
Separate PR would be great -- thanks for considering it!
