### ISSUE TITLE
Get rid of convoluted syntax to set up RHS and BoundaryCondition constructors 

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#8685]
As per the [release notes](https://github.com/dealii/dealii/releases/tag/v9.0.0) of deal. ii v9.0.0,

>C++11 is now both required and used

However. step-4 of the tutorial goes to great lengths to provide a default constructor for the RHS & BoundaryValues. To quote,

>Unfortunately, we have to explicitly provide a default constructor for this class (even though we do not need the constructor to do anything unusual) to satisfy a strict reading of the C++ language standard. Some compilers (like GCC from version 4.3 onwards) do not require this, but we provide the default constructor so that all supported compilers are happy.

GCC pre 4.3 does not anyway support C++11 standards: [Reference](https://en.cppreference.com/w/cpp/compiler_support#cpp11). Consequently, I believe that it may be possible to rewrite this tutorial (step-4) and possibly others with cleaner code.  Do the maintainers agree?

**Comment by bangerth** [comment]
Yes, that's a left-over from long ago. Want to write a patch that just removes the workaround in step-4?

**Comment by krishnakumarg1984** [comment]
@bangerth Is this only present in step-4? I am still a (slow) learner. I can certainly write a patch after testing on my machine (in the next week or so, if that's okay with you?).

**Comment by bangerth** [comment]
I don't know -- the comment is probably only in step-4, but the default constructor might be in other places as well. Feel free to look around -- though I'm an incrementalist and consequently think that a patch that even just fixes the issue in one place is a good patch.

**Comment by krishnakumarg1984** [comment]
Okay, I'll try to give this a go.

**Comment by krishnakumarg1984** [comment]
Actually, we can close this. This issue has been fixed by commit 731c5d15520f76f947983c8c08fa5a6bf0f1adec
