### ISSUE TITLE
Possibly incorrect statement on maximum number of dofs in documentation

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#8689]
On the page [Parallel computing with multiple processors using distributed memory](https://www.dealii.org/developer//doxygen/deal.II/group__distributed.html#details) the following statement is made:

"we do not have solvers that are capable of more than 2^31 degrees of freedom due to the use of signed int as index"

Is this statement still valid? Isn't the purpose of DEAL_II_WITH_64BIT_INDICES to avoid this?

**Comment by bangerth** [comment]
On 9/3/19 9:09 AM, Simon Sticko wrote:
> Is this statement still valid? Isn't the purpose of 
> DEAL_II_WITH_64BIT_INDICES to avoid this?

No. Yes.

Want to write a patch to fix this statement?

**Comment by simonsticko** [comment]
Removed the statement in #8692.

**Comment by masterleinad** [comment]
FYI, the `GitHub` way for closing issues addressed in pull requests is to mention a keyword in the commit message (https://help.github.com/en/articles/closing-issues-using-keywords).
