### ISSUE TITLE
Step-4 documentation: Explanation of keywords virtual & override in RHS/BC template functions

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#8696]
Step-4 tutorial explains the idea of deriving the `RHS` and `BC` classes from the general `Function` class. However, there is a sudden mental jump for the reader upon encountering the actual `c++` code.

In particular, the line
`virtual double value(const Point<dim> & p, const unsigned int component=0) const override;` 

might be confusing to a newbie (it certainly is for me).  I don't know much about inheritance, but I can guess that the `virtual` and `override` have something to do with inheritance.  I know that this is a C++ question rather than a deal.ii question, however a general web search yields quite a bit of daunting information which can be off-putting for someone to quickly get through this tutorial (and not get stuck).

A one-liner explanation of why these additional keywords were suddenly introduced (with an optional link to further resources on the topic) may be considered if there is consensus.

PS:
I am only pointing this out because of the context in which I arrived at this juncture. So far, it has been a linear/smooth ride. There was even a detailed explanation of what templates are, in the form of an entire video lecture, in addition to the intro section. There is even a deal.ii FAQ section for templates. IMHO, templates seem conceptually easier to understand than inheritance. And, therefore, to help with the reading continuity, a line or two on inheritance is much appreciated. Perhaps the mailing list is more appropriate for this type of requests, but I am raising this here, since potentially this may involve an update to the tutorial.

**Comment by masterleinad** [comment]
As always, we are happy to discuss any contribution in the form of a pull request. Currently, you are in a good position to tell what would have been helpful for you by adding it directly to the documentation for `step-4`.

**Comment by krishnakumarg1984** [comment]
@masterleinad I don't understand these keywords myself (they caught me by surprise), and hence don't feel qualified to offer a pull request.

**Comment by bangerth** [comment]
@krishnakumarg1984 -- take a look at #8766.

**Comment by krishnakumarg1984** [comment]
Thank you! That was indeed helpful.
