### ISSUE TITLE
Step-4 documentation (possible) mistake: 2D-solution plot is incorrect (looks like from step-3)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#8697]
In step-4, we solve $\nablaLaplacian u = 4(x^2+y^2)$ for the 2D case with BC = $x^2+y^2$.  However, the plot on the `dev` version is that corresponding to the step-3 (RHS=1 and zero BC), which is also what is shown from `13:00` to `14:10` in the corresponding [video lecture](https://www.youtube.com/watch?time_continue=731&v=l9XSA6pRs9w).

If the maintainers concur that this is indeed the case, I shall be happy to raise a pull-request with the correct figure.

![visit0000](https://user-images.githubusercontent.com/15239509/64278667-33303080-cf45-11e9-827c-5a3a5adaa3c8.png)

**Comment by masterleinad** [comment]
For me, the pictures in step-4 look much different from the ones in step-3. In particular, I don't see homogeneous Dirichlet boundary conditions. Can you post a link to the plot that you think is wrong?

**Comment by krishnakumarg1984** [comment]
Aargh. Indeed I am sorry. I saw some differences between the tutorial image and my simulation output image and jumped to a wrong conclusion. Sorry for the noise. Shall close this issue.
