### ISSUE TITLE
Fichera corner Maxwell simulation fails

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#8710]
@bangerth , @tamiko and @tjhei During the workshop I showed you some Maxwell simulations in which the solution was discontinuous. I've been working on this and I've been able to isolate the problem. I find these discontinuities when I have sharp metallic corners.

I find the same problem for `Nedelec` and for `NedelecSZ`. I don't know if the problem is related to the finite element. @rosskynch any ideas?

The Nedelec element is supposed to be able to deal with the singularities of the Maxwell equations. An example is the Fichera Corner. I found that `deal.II` provides the [Fichera Corner geometry (hyper_L)](https://www.dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#a3b2a4ad8296c2b72a11d23b5969e8cc0) and there is a reference to Fichera in the `deal.II` documentation, which makes think me that somebody studied these problems with `deal.II` in the past.

The test #8709 reproduces the problem. The manufactured solution has a singularity for `curl(curl E)` at `x=y=0`. The solution for `E_z` is correct, but the solution is discontinuous for `E_x` and `E_y`. Below you can find the results for `z=0`:

![e_z](https://user-images.githubusercontent.com/25910642/64487191-8bae4900-d237-11e9-834d-1b92598afdc9.png)
![e_x](https://user-images.githubusercontent.com/25910642/64487187-7cc79680-d237-11e9-81b9-b01e44a440ac.png)
![e_y](https://user-images.githubusercontent.com/25910642/64487189-851fd180-d237-11e9-9736-1221239157e7.png)

**Comment by rosskynch** [comment]
How do things behave if you try to isolate the singularity with h refinement?

**Comment by dangars** [comment]
@rosskynch Thanks for the quick reply!

I'll try h refinement. I just tried a global refinement, but it does not help as you can see below. In "average" the solution is good, but there are discontinuities. I'm using `std::complex`, I don't think that the origin is the `std::complex` algebra, but I can do the same test for a `real` simulation.

I din't use the `hyper_L` geometry for the test. In order to rule out the mesh, I used a cube that has the dimensions `0.04x0.04x0.04mm` and a manufactured solution with a singularity in `curl(curl(E))`. I had to play a lot with different manufactured solutions in order to find one that reproduces the problem. Below you can find the vector field of the exact manufactured solution.

![e_x_2](https://user-images.githubusercontent.com/25910642/64488003-6d017f80-d242-11e9-9e57-543e1e32a4e1.png)
![vector_field](https://user-images.githubusercontent.com/25910642/64488016-98846a00-d242-11e9-8300-be904134cee3.png)

**Comment by rosskynch** [comment]
I always solved the real and imaginary parts separately rather than using complex numbers, but I don't see why it shouldnt work.

I don't think uniform refinement helps you here, you need to mesh tightly around the singularity. This may be tricky as nedelecSZ doesn't support hanging nodes (possibly the old element can handle it though).

**Comment by dangars** [comment]
All my tests with `std::complex` that don't have singularities give good results, but I'll try real algebra.

I'll try h-refinement with the old element.

This is a very basic question: I've been reading Peter Monk book, but it is still not clear to me how the continuity is enforced with the Nedelec element. The electric field should be continuous if there is no dielectric boundary, in fact the condition for the longitudinal continuity of the Electric field  (Monk book): `nu*(epsilon_r1*E_1-epsilon_r2*E_2)=rho_s` with `nu` the normal vector. 

The nedelec element enforces continuity in the tangential part of the electric field (edge degree of freedom). How does the Nedelec element enforces the continuity of the longitudinal component in the case of no dielectric boundaries? In the test #8709 there are no dielectric boundaries, the material is homogeneous, therefore there shouldn't be any discontinuities in the electric field.

**Comment by dangars** [comment]
@rosskynch I found something very interesting, the Nedelec element is very sensitive to the quadrature degree when you have singularities.

I realized that in your implementation you have the degrees of freedom for the edges, faces and volume. That makes lot of degrees of freedom per cell. I was using `QGauss<dim>(degree + 1)` I noticed that you used `QGauss<dim>(2 * degree + 3)` in `fe_nedelec_sz_non_rect_2d.cc`.

I wonder if `QGauss<dim>` is the best quadrature formula for Nedelec.  I'm happy to write a quadrature formula for Nedelec. Do you have any suggestion?

I will update the documentation to mention that it is very important to use a high degree quadrature formula for Nedelec when there are singularities.

Below you can find the solution for `QGauss<dim>(2)` and for `QGauss<dim>(10)`

![quadrature](https://user-images.githubusercontent.com/25910642/64491619-e8772700-d26a-11e9-9a5c-63c0a6ae4b78.png)

**Comment by dangars** [comment]
The element `FE_NedelecSZ(1)` has 54 degrees of freedom in 3D. This improves the precision but it can be confusing and may have some drawbacks. For example in my code I do a frequency sweep and I have a "cache" for the quadrature points (see step-62). An element with 54 degrees of freedom explodes that "cache".

Acording to Peter Monk's book the linear Nedelec element has only degrees of freedom on the edges, that means that the linear Nedelec element in 3D should have 12 degrees of freedom. Would it be a good idea to give the option to choose a lower number of degrees of freedom for the Nedelec element? For example only on the edges?

If we define now that `FE_NedelecSZ(1)` has only degrees of freedom on the edges, that could potentially break the code of some people. How about we add an option or a template parameter that allows to choose for example only dofs on the edges, faces or volume?

**Comment by rosskynch** [comment]
On the quadrature - I remember it needing to be higher but I can't remember the precise reason. If you look at the basis set I think you'll see there are polynomials with higher degrees than degree+1 in them.

Peter Monk's book is excellent on the subject but I'd also point you to the thesis of Sabine Zaglmayr which I based a lot of the code on (and where the SZ comes from): https://www.applied.math.tugraz.at/~zaglmayr/pub/szthesis.pdf

I think it may be a good idea to write a QNedelecSZ which wraps a suitable quadrature for a given degree. If QGauss is not suitable, then there may be something in Sabine's thesis which may help.

On your question about the degrees of freedom on edges, I think FE_NedelecSZ(0) contains only linear edge DoFs.

**Comment by dangars** [comment]
@rosskynch Thanks a lot for all your answers, they helped me a lot!

That is right `FE_NedelecSZ(0)` has 12 degrees of freedom in 3D, therefore there is no need to add any additional option.

I'm going to read the Sabine Zaglmayr thesis to see if I can come with a better Quadrature formula for Nedelec.

I'm going to update the documentation for `FE_NedelecSZ` and `FE_Nedelec` and add what we have discussed here.

I close this issue.

**Comment by rosskynch** [comment]
Glad I could be of some help!

**Comment by agrayver** [comment]
FWIW, Markus Bürg has considered many singular cases, including L-shape domains, in his PhD thesis for Maxwell's equations (he used FE_Nedelec). 

Perhaps part of the issue owns to the fact that your equation is indefinite, thereby imposing constraints on the mesh.

**Comment by dangars** [comment]
@agrayver Could you add the link to the pdf version of Markus Burg thesis? I couldn't find it

If the Markus thesis can not be found online, I'll send you an email. I found your email at your ETH website.

**Comment by agrayver** [comment]
Yes, sure: https://publikationen.bibliothek.kit.edu/1000029034

**Comment by dangars** [comment]
Thanks!

**Comment by bangerth** [comment]
Yes, the polynomial degree of the `FE_Nedelec(0)` element is one, so you need a quadrature formula with at least 2 points per direction. People define the "order" of an element in inconsistent ways, independent of the degree of the polynomial.

I think you've already found help here, but I'd like to add a couple of ideas:
* I've learned to distrust images. I would have written independent code to ensure that the solution really is discontinuous in ways that are not allowed. For example, the Nedelec element only guarantees continuity in tangential direction but not in normal direction. So the pictures you show are "allowed" -- the element allows for these discontinuities even thought they are of course not desirable.
* It would also have been interesting to see whether you get similar pictures if you *interpolate* or *project* the solution, rather than solving a PDE. This would allow you to figure out whether the problem is in the assembly/solve phase, or indeed in the description of the element itself.

**Comment by dangars** [comment]
> Yes, the polynomial degree of the `FE_Nedelec(0)` element is one, so you need a quadrature formula with at least 2 points per direction. People define the "order" of an element in inconsistent ways, independent of the degree of the polynomial.

I added PR #8720 to clarify in the documentation the oder/degree and the required number of quadrature points.

> * It would also have been interesting to see whether you get similar pictures if you _interpolate_ or _project_ the solution, rather than solving a PDE. This would allow you to figure out whether the problem is in the assembly/solve phase, or indeed in the description of the element itself.

How do you do the interpolation and in which part of the program would you do that? You would do the interpolation in `assemble_system()`?

**Comment by bangerth** [comment]
There is not going to be any linear system to solve, so you just comment out the calls to `assemble_system` and `solve` and instead call the interpolation or projection function.

**Comment by bangerth** [comment]
I wanted to suggest that you use `VectorTools::interpolate()`, but I'm not sure it works for Nedelec elements. I think it does. If it doesn't, use `VectorTools::project()`.

**Comment by dangars** [comment]
Ok, I'll try that!
