### ISSUE TITLE
doxygen: ordinal not in range (Ubuntu 18.04)

### ISSUE THREAD

**Issue by fvanmaele** [dealii/dealii#8714]
I am trying to build `dealii 9.1.1` using the [`debian sid` source package](https://packages.debian.org/source/sid/deal.ii) on `Ubuntu 18.04 x86_64`. (This package appears identical to the `Ubuntu eoan` version, an [`arm64` issue](http://changelogs.ubuntu.com/changelogs/pool/universe/d/deal.ii/deal.ii_9.1.1-4ubuntu1/changelog) aside.)

Using `pbuilder`, the build completes except for the last `Doxygen` target:
```
[100%] Built target deal.ii.g
cd /build/deal.ii-9.1.1/obj-x86_64-linux-gnu/doc/doxygen && /build/deal.ii-9.1.1/doc/doxygen/scripts/set_canonical_doxygen.py
Traceback (most recent call last):
  File "/build/deal.ii-9.1.1/doc/doxygen/scripts/set_canonical_doxygen.py", line 45, in <module>
    if '<link rel="canonical"' not in file_handle.read():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6272: ordinal not in range(128)
doc/doxygen/CMakeFiles/doxygen.dir/build.make:708: recipe for target 'doxygen.log' failed
make[3]: *** [doxygen.log] Error 1
make[3]: *** Deleting file 'doxygen.log'
make[3]: Leaving directory '/build/deal.ii-9.1.1/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:595: recipe for target 'doc/doxygen/CMakeFiles/doxygen.dir/all' failed
make[2]: *** [doc/doxygen/CMakeFiles/doxygen.dir/all] Error 2
make[2]: Leaving directory '/build/deal.ii-9.1.1/obj-x86_64-linux-gnu'
Makefile:132: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/build/deal.ii-9.1.1/obj-x86_64-linux-gnu'
dh_auto_build: cd obj-x86_64-linux-gnu && make -j2 "INSTALL=install --strip-program=true" returned exit code 2
debian/rules:7: recipe for target 'binary' failed
make: *** [binary] Error 2
```
The `debian/rules` file for reference:
https://salsa.debian.org/science-team/deal.ii/blob/master/debian/rules

**Comment by drwells** [comment]
This is a really bizarre error: it implies that we cannot compile the documentation on 9.1.1, but we (at least me) have done this.

My best guess (which is not that great) is something wrong with the version of python that we rely on (which is not well documented at all) with sid.

**Comment by tamiko** [comment]
This is definitely a python 2 versus 3 issue.
We switched to python3 in the current sid package because it looked quite save to do so. So I am a bit surprised to see this exploding.

@fvanmaele 

We provide a ppa with a backported dealii-9.1.1 here: https://launchpad.net/~ginggs/+archive/ubuntu/deal.ii-backports Would you mind to either use that (or the corresponding source package) instead?

**Comment by fvanmaele** [comment]
Thank you! I was not aware there was already a backported package 
available. deal.ii - 9.1.1-2~ubuntu18.04.1~ppa1 compiled without issue.

**Comment by drwells** [comment]
We talked at the workshop about getting rid of the additional python dependency. Did we ever open an issue to track it?

**Comment by fvanmaele** [comment]
I think it should be feasible to rewrite set_canonical_doxygen in Perl 
(similar to most of the other doxygen scripts). If there is no existing 
issue for it, I could open one + resulting PR?

**Comment by drwells** [comment]
@fvanmaele we need to do this, so go ahead please!

**Comment by fvanmaele** [comment]
@tamiko Just one more question, are the debug symbols (`-dbg` or `-dbgsym`) for the `9.1.1-2~ubuntu18.04.1~ppa1` packages also available?
