### ISSUE TITLE
Not convergence in MappingQEulerian.transform_real_to_unit_cell

### ISSUE THREAD

**Issue by YongYang86** [dealii/dealii#872]
An example to show MappingQEulerian.transform_real_to_unit_cell is not convergent. It comes from the debug information. dim = 2.
```c++
void TestDealii::test_MappingQEulerian(){
	Triangulation<dim> mesh_new;
	GridGenerator::hyper_cube(mesh_new,-1,1);

	FESystem<dim>              fe_new(FE_Q<dim>(1), dim+1);
	DoFHandler<dim>            dof_h_new(mesh_new);

	dof_h_new.distribute_dofs(fe_new);

	dof_h_new.begin_active()->vertex(0)(0) = -1;
	dof_h_new.begin_active()->vertex(0)(1) = -0.0625;

	dof_h_new.begin_active()->vertex(1)(0) = -0.9375;
	dof_h_new.begin_active()->vertex(1)(1) = -0.0625;

	dof_h_new.begin_active()->vertex(2)(0) = -1;
	dof_h_new.begin_active()->vertex(2)(1) = 0;

	dof_h_new.begin_active()->vertex(3)(0) = -0.9375;
	dof_h_new.begin_active()->vertex(3)(1) = 0;

	Vector<double> sltn(dof_h_new.n_dofs());
	sltn(0)=0.00078884082972521753;
	sltn(1)=-0.013778743540893043;
	sltn(3)=0.000073172763444759989;
	sltn(4)=-0.014511736600762624;
	sltn(6)=-0.000067256126875951891;
	sltn(7)=0.015145778219910718;
	sltn(9)=-0.00059218542240841734;
	sltn(10)=-0.014492948354456853;

	MappingQEulerian<dim> map(1,sltn,dof_h_new);
	Point<dim> pt1,pt2;
	pt1(0) = -0.81329655479912066;
	pt1(1) = -0.0035340119568671759;
	std::cout<<pt1<<std::endl;
	// not convergent!!!
	pt2 = map.transform_real_to_unit_cell(dof_h_new.begin_active(),pt1);
	std::cout<<pt2<<std::endl;
}
```

**Comment by bangerth** [comment]
I think this is not a failure of `MappingQEulerian` but in fact of the underlying code. Can you try to move the points of the original mesh according to your displacements and simply use a `MappingQ`? Do you observe the same problem in that case?

**Comment by YongYang86** [comment]
It is strange. If I add `MappingQ<dim> map_q(map);` after `MappingQEulerian<dim> map(1,sltn,dof_h_new);` and use `pt2 = map_q.transform_real_to_unit_cell(dof_h_new.begin_active(),pt1);`, then it works. The original exception information is  
`libc++abi.dylib: terminating with uncaught exception of type dealii::Mapping<2, 2>::ExcTransformationFailed: 
An error occurred in line <1818> of file <../source/fe/mapping_q1.cc> in function
    Point<dim> dealii::MappingQ1<2, 2>::transform_real_to_unit_cell_internal(const typename Triangulation<dim, spacedim>::cell_iterator &, const Point<spacedim> &, const Point<dim> &, dealii::MappingQ1::InternalData &) const [dim = 2, spacedim = 2]
The violated condition was: 
    false
The name and call sequence of the exception was:
    (typename Mapping<dim,spacedim>::ExcTransformationFailed())
Additional Information: 
(none)`

**Comment by bangerth** [comment]
What I meant is not to simply replace the MappingQEulerian by MappingQ, but to also move the points by hand. For example, the MappingQEulerian moves vertex 0 to
```
  dof_h_new.begin_active()->vertex(0)(0) = -1+0.00078884082972521753;
    dof_h_new.begin_active()->vertex(0)(1) = -0.0625-0.013778743540893043;
```
What happens if you do this by hand and then use a zero displacement vector? If this still produces the same error as before, then you can replace MappingQEulerian + zero displacement by a direct MappingQ object.

**Comment by YongYang86** [comment]
After moving points by hand, both of methods generate same exception as before.(1. zero displacement + MappingQEulerian; 2. MappingQ).  
```c++
	dof_h_new.begin_active()->vertex(0)(0) = -1+0.00078884082972521753;
	dof_h_new.begin_active()->vertex(0)(1) = -0.0625-0.013778743540893043;

	dof_h_new.begin_active()->vertex(1)(0) = -0.9375+0.000073172763444759989;
	dof_h_new.begin_active()->vertex(1)(1) = -0.0625-0.014511736600762624;

	dof_h_new.begin_active()->vertex(2)(0) = -1-0.000067256126875951891;
	dof_h_new.begin_active()->vertex(2)(1) = 0+0.015145778219910718;

	dof_h_new.begin_active()->vertex(3)(0) = -0.9375-0.00059218542240841734;
	dof_h_new.begin_active()->vertex(3)(1) = 0-0.014492948354456853;

	Vector<double> sltn(dof_h_new.n_dofs());
	sltn = 0.0;

	// test-1
	//MappingQEulerian<dim> map(1,sltn,dof_h_new);
	// test-2
	MappingQ<dim> map(1);

	Point<dim> pt1,pt2;
	pt1(0) = -0.81329655479912066;
	pt1(1) = -0.0035340119568671759;
	std::cout<<pt1<<std::endl;
	// not convergent!!!
	pt2 = map.transform_real_to_unit_cell(dof_h_new.begin_active(),pt1);
	std::cout<<pt2<<std::endl;
```

**Comment by bangerth** [comment]
For reference, here is a picture of the cell and the point. The point is far outside, I'm not surprised that the inversion formula fails.
![x](https://cloud.githubusercontent.com/assets/7504421/7330515/6ddb76aa-eab5-11e4-95aa-511be17390c2.png)

**Comment by bangerth** [comment]
Related issues: #866 and #314.

@YongYang86 : If you feel adventurous, you could try to implement the idea in issue #866 and we will see whether that helps any.

**Comment by YongYang86** [comment]
It is interesting. I will try to implement it following the reference #866 . Thanks.

**Comment by drwells** [comment]
While working on #1177 (and reading through some computer graphics literature) I came to the conclusion that the unit to real mapping is not guaranteed to be invertible for points outside of the cell (in fact, one can get two solutions via the exact formula for some pathological inputs). I am somewhat pessimistic that it is possible to improve the code enough to fix this, so should this be closed?

**Comment by bangerth** [comment]
Correct. The documentation of `Mapping::transform_real_to_unit_cell()` already says this:
```
   * @note Polynomial mappings from the reference (unit) cell coordinates to
   * the coordinate system of a real cell are not always invertible if the
   * point for which the inverse mapping is to be computed lies outside the
   * cell's boundaries. In such cases, the current function may fail to
   * compute a point on the reference cell whose image under the mapping
   * equals the given point @p p.  If this is the case then this function
   * throws an exception of type Mapping::ExcTransformationFailed . Whether
   * the given point @p p lies outside the cell can therefore be determined by
   * checking whether the return reference coordinates lie inside or outside
   * the reference cell (e.g., using GeometryInfo::is_inside_unit_cell()) or
   * whether the exception mentioned above has been thrown.
```
