### ISSUE TITLE
PETSc issue: Convergence failure with hp-adaptivity

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#8729]
I continued to prepare scaling plots with parallel hp-adaptivity for my graduation after tracing back some issues to `hypre` in #8565. But I encountered a different issue with `PETSc`, which also occurs with the 'compatible' version of `hypre`: The `SolverCG` object does not converge by solving the Poisson equation from `step-27`, even when using `PreconditionJacobi`. I am still working with the same scenario introduced in #8565.

I'll post some logs from some runs on our `Jureca Booster` supercomputer below, so that you may get a picture yourself. By checking the logs for the failing `PETSc` cases, I was questioning whether `SolverControl` has a hard-coded maximum number of iterations set to `10000`?

However, using `SolverCG` from `Trilinos` with `ML` as an AMG preconditioner, there are no convergence issues so far. The only concern I have right now is that the number of iterations explode with increasing number of degrees of freedom (and constraints). I should maybe provide better suited properties to the `AdditionalData` object in case of hp-adaptivity, e.g. enabling `higher_order_elements` since we do not solely work with linear elements anymore. @bangerth @tjhei @kronbichler -- Maybe you have some suggestions in this regard, since I don't have that much experience picking the right combination of solver and preconditioner...

At least for now, I will continue to use `Trilinos` for my investigations and come back to this issue later, when the thesis is handed in. I will start by checking if this is also an issue in the non-hp case, so that it is maybe related to the domain rather than to hp-adaptivity.

---

# Logs

### Code:
```
SolverControl solver_control(dof_handler.n_dofs(), 1e-8);
LinearAlgebraPETSc::SolverCG  cg(solver_control, mpi_communicator);

LinearAlgebraPETSc::MPI::PreconditionAMG                 preconditioner;
LinearAlgebraPETSc::MPI::PreconditionAMG::AdditionalData data;
data.symmetric_operator = true;

preconditioner.initialize(system_matrix, data);
cg.solve(system_matrix,
         completely_distributed_solution,
         system_rhs,
         preconditioner);
```

### `PreconditionAMG` & `data.symmetric_operator = true;`
```
Running with PETSc on 384 MPI rank(s)...
Cycle 0:
   Number of active cells      : 49152
   Number of degrees of freedom: 198144
   Number of constraints       : 3792
   Solved in 8 iterations.
Cycle 1:
   Number of active cells      : 58818
   Number of degrees of freedom: 297682
   Number of constraints       : 12471
   Solved in 11 iterations.
Cycle 2:
   Number of active cells      : 63213
   Number of degrees of freedom: 424413
   Number of constraints       : 37948
   Solved in 12 iterations.
Cycle 3:
   Number of active cells      : 67929
   Number of degrees of freedom: 560387
   Number of constraints       : 77877
   Solved in 21 iterations.
Cycle 4:
   Number of active cells      : 75966
   Number of degrees of freedom: 738436
   Number of constraints       : 117773
   Solved in 33 iterations.
Cycle 5:
   Number of active cells      : 78216
   Number of degrees of freedom: 899142
   Number of constraints       : 155587
   Solved in 59 iterations.
Cycle 6:
   Number of active cells      : 80556
   Number of degrees of freedom: 1068303
   Number of constraints       : 188171
--------------------------------------------------------
An error occurred in line <148> of file </p/project/cias-7/fehling1/dealii/source/lac/petsc_solver.cc> in function
    void dealii::PETScWrappers::SolverBase::solve(const dealii::PETScWrappers::MatrixBase &, dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::PreconditionerBase &)
The violated condition was:
    false
Additional information:
Iterative method reported convergence failure in step 5. The residual in the last step was 0.0212258.

This error message can indicate that you have simply not allowed a sufficiently large number of iterations for your iterative solver to converge. This often happens when you increase the size of your problem. In such cases, the last residual will likely still be very small, and you can make the error go away by increasing the allowed number of iterations when setting up the SolverControl object that determines the maximal number of iterations you allow.

The other situation where this error may occur is when your matrix is not invertible (e.g., your matrix has a null-space), or if you try to apply the wrong solver to a matrix (e.g., using CG for a matrix that is not symmetric or not positive definite). In these cases, the residual in the last iteration is likely going to be large.
--------------------------------------------------------
```

### `PreconditionAMG` & `data.symmetric_operator = false;`
```
Running with PETSc on 384 MPI rank(s)...
Cycle 0:
   Number of active cells      : 49152
   Number of degrees of freedom: 198144
   Number of constraints       : 3792
   Solved in 8 iterations.
Cycle 1:
   Number of active cells      : 58818
   Number of degrees of freedom: 297682
   Number of constraints       : 12471
   Solved in 11 iterations.
Cycle 2:
   Number of active cells      : 63213
   Number of degrees of freedom: 424413
   Number of constraints       : 37948
   Solved in 12 iterations.
Cycle 3:
   Number of active cells      : 67929
   Number of degrees of freedom: 560387
   Number of constraints       : 77877
   Solved in 21 iterations.
Cycle 4:
   Number of active cells      : 75966
   Number of degrees of freedom: 738436
   Number of constraints       : 117773
   Solved in 33 iterations.
Cycle 5:
   Number of active cells      : 79296
   Number of degrees of freedom: 906384
   Number of constraints       : 155140
--------------------------------------------------------
An error occurred in line <148> of file </p/project/cias-7/fehling1/dealii/source/lac/petsc_solver.cc> in function
    void dealii::PETScWrappers::SolverBase::solve(const dealii::PETScWrappers::MatrixBase &, dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::PreconditionerBase &)
The violated condition was: 
    false
Additional information: 
Iterative method reported convergence failure in step 10000. The residual in the last step was 3.32354e-05.

This error message can indicate that you have simply not allowed a sufficiently large number of iterations for your iterative solver to converge. This often happens when you increase the size of your problem. In such cases, the last residual will likely still be very small, and you can make the error go away by increasing the allowed number of iterations when setting up the SolverControl object that determines the maximal number of iterations you allow.

The other situation where this error may occur is when your matrix is not invertible (e.g., your matrix has a null-space), or if you try to apply the wrong solver to a matrix (e.g., using CG for a matrix that is not symmetric or not positive definite). In these cases, the residual in the last iteration is likely going to be large.
--------------------------------------------------------
```

### `PreconditionJacobi`
```
Running with PETSc on 384 MPI rank(s)...
Cycle 0:
   Number of active cells      : 49152
   Number of degrees of freedom: 198144
   Number of constraints       : 3792
   Solved in 720 iterations.
Cycle 1:
   Number of active cells      : 58935
   Number of degrees of freedom: 298551
   Number of constraints       : 13110
   Solved in 1206 iterations.
Cycle 2:
   Number of active cells      : 63627
   Number of degrees of freedom: 428033
   Number of constraints       : 40082
   Solved in 1788 iterations.
Cycle 3:
   Number of active cells      : 72234
   Number of degrees of freedom: 603781
   Number of constraints       : 79870
   Solved in 2445 iterations.
Cycle 4:
   Number of active cells      : 78540
   Number of degrees of freedom: 778115
   Number of constraints       : 125120
   Solved in 3180 iterations.
Cycle 5:
   Number of active cells      : 84201
   Number of degrees of freedom: 973346
   Number of constraints       : 172439
   Solved in 4057 iterations.
Cycle 6:
   Number of active cells      : 87828
   Number of degrees of freedom: 1189531
   Number of constraints       : 229537
   Solved in 5711 iterations.
Cycle 7:
   Number of active cells      : 94614
   Number of degrees of freedom: 1452985
   Number of constraints       : 289226
--------------------------------------------------------
An error occurred in line <148> of file </p/project/cias-7/fehling1/dealii/source/lac/petsc_solver.cc> in function
    void dealii::PETScWrappers::SolverBase::solve(const dealii::PETScWrappers::MatrixBase &, dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::VectorBase &, const dealii::PETScWrappers::PreconditionerBase &)
The violated condition was: 
    false
Additional information: 
Iterative method reported convergence failure in step 10000. The residual in the last step was 1.36075e-08.

This error message can indicate that you have simply not allowed a sufficiently large number of iterations for your iterative solver to converge. This often happens when you increase the size of your problem. In such cases, the last residual will likely still be very small, and you can make the error go away by increasing the allowed number of iterations when setting up the SolverControl object that determines the maximal number of iterations you allow.

The other situation where this error may occur is when your matrix is not invertible (e.g., your matrix has a null-space), or if you try to apply the wrong solver to a matrix (e.g., using CG for a matrix that is not symmetric or not positive definite). In these cases, the residual in the last iteration is likely going to be large.
--------------------------------------------------------
```

# Trilinos

## `PreconditionAMG` & default `AdditionalData`
```
Running with Trilinos on 384 MPI rank(s)...
Cycle 0:
   Number of active cells      : 49152
   Number of degrees of freedom: 198144
   Number of constraints       : 3792
   Solved in 18 iterations.
Cycle 1:
   Number of active cells      : 58758
   Number of degrees of freedom: 297499
   Number of constraints       : 12573
   Solved in 29 iterations.
Cycle 2:
   Number of active cells      : 63168
   Number of degrees of freedom: 424183
   Number of constraints       : 37944
   Solved in 41 iterations.
Cycle 3:
   Number of active cells      : 68919
   Number of degrees of freedom: 572452
   Number of constraints       : 75721
   Solved in 51 iterations.
Cycle 4:
   Number of active cells      : 77154
   Number of degrees of freedom: 751833
   Number of constraints       : 114273
   Solved in 60 iterations.
Cycle 5:
   Number of active cells      : 80418
   Number of degrees of freedom: 920478
   Number of constraints       : 152049
   Solved in 114 iterations.
Cycle 6:
   Number of active cells      : 84798
   Number of degrees of freedom: 1103671
   Number of constraints       : 186474
   Solved in 412 iterations.
Cycle 7:
   Number of active cells      : 88983
   Number of degrees of freedom: 1292478
   Number of constraints       : 217475
   Solved in 892 iterations.
Cycle 8:
   Number of active cells      : 91470
   Number of degrees of freedom: 1491980
   Number of constraints       : 247361
   Solved in 2022 iterations.
Cycle 9:
   Number of active cells      : 95511
   Number of degrees of freedom: 1729013
   Number of constraints       : 293411
   Solved in 5087 iterations.
Cycle 10:
   Number of active cells      : 106944
   Number of degrees of freedom: 2063872
   Number of constraints       : 366391
   Solved in 13309 iterations.
```

**Comment by marcfehling** [comment]
I am confused that there are differences in the convergence error messages for different values for `data.symmetric_operator`. Is it possible that something went wrong during the assembly of the equation system, so that the matrix is no longer symmetric? But if that is the case, why doesn't `Trilinos` complain about it?

**Comment by bangerth** [comment]
The wisdom of the community is that hypre is better for Q1 elements, and ML is better for higher order elements. Since you do have higher order elements, the use of the `higher_order_elements` flag seems useful.

The growth in the number of iterations is disappointing. This makes the whole method rather unusable. Is what you see here dependent on having adaptively refined meshes, or do you see the same if you had a uniformly refined mesh with constant polynomial degree everywhere?

As for the 10,000 iterations: I can't see that number appearing in deal.II itself. So it must be either in the place where you set up the `SolverControl` object, or be a number internal to PETSc.

**Comment by bangerth** [comment]
As for the symmetric flag: When you specify it, you get one refinement step further, so clearly the preconditioner is better than the one you get if you don't set that flag. That seems reasonable to me. Or do I misunderstand?

**Comment by marcfehling** [comment]
> As for the symmetric flag: When you specify it, you get one refinement step further, so clearly the preconditioner is better than the one you get if you don't set that flag. That seems reasonable to me. Or do I misunderstand?

Yes, we get an additional refinement step with that flag.

I was confused that the error message with `symmetric_operator = true` says that the `iterative method reported convergence failure in step 5`, which appears to me that it is giving up way too early. Maybe `PETSc` complains about something, which is interpreted by `deal.II` as some complaint about convergence, but is in fact something completely different?

**Comment by marcfehling** [comment]
> The wisdom of the community is that hypre is better for Q1 elements, and ML is better for higher order elements. Since you do have higher order elements, the use of the `higher_order_elements` flag seems useful.

I just tried setting the `higher_order_elements` flag on our supercomputer, but I cannot observe any reduction on the number of iterations :(

> 
> The growth in the number of iterations is disappointing. This makes the whole method rather unusable.

I know :(

> Is what you see here dependent on having adaptively refined meshes, or do you see the same if you had a uniformly refined mesh with constant polynomial degree everywhere?

I haven't tried that kind of 'divide of conquer' approach yet, but will do tomorrow. I may also try to switch back to a non-hp `DoFHandler` to check if that issue is related to the domain shape or adaptive mesh refinement in general.

**Comment by marcfehling** [comment]
> As for the 10,000 iterations: I can't see that number appearing in deal.II itself. So it must be either in the place where you set up the `SolverControl` object, or be a number internal to PETSc.

We should think about tackling this in a later PR: Either by overwriting these defaults (if they exists), or warning the user that their provided maximum number of iterations will be overwritten by these defaults.

**Comment by bangerth** [comment]
On 9/10/19 3:39 PM, marcfehling wrote:
> We should think about tackling this in a later PR: Either by overwriting 
> these defaults (if they exists), or warning the user that their provided 
> maximum number of iterations will be overwritten by these defaults.

Yes -- feel free to open an issue about this.

**Comment by tjhei** [comment]
Two quick comments:
You are using CG, which means your system and preconditioner need to be SPD. If they are not, CG can fail at any time (break down) or not converge. So you need to use ``data.symmetric_operator=true``, otherwise PETSc might use a smoother or coarse solver that is not symmetric.

Secondly, I would suggest experimenting with GMRES first as it is typically the most robust method and does not require for the system to be SPD.  For timings you don't want to do that, but maybe one of the constraints breaks positive definiteness. If GMRES works but CG doesn't you know what the problem is...

**Comment by marcfehling** [comment]
I redid calculations with only one type of elements (`FE_Q(2)` and `FE_Q(7)` respectively) and the combination of solver and preconditioner scales about linearly with the number of degrees of freedom, so as expected. The more different finite elements are involved in constructing the equation system, the worse is the performance of the solver, i.e. see the example above which was using finite elements from `FE_Q(2)` until `FE_Q(13)`. I switched from `ML` to `MueLu`, but could not observe any difference in scaling.

Are AMG preconditioners suited for p-adaptivity? Maybe we should think about introducing a geometric hp-preconditioner at some point (not before my graduation).

I'll reach out to the `ML` developers and hope that they could help me out with some tips.

**Comment by tjhei** [comment]
> Are AMG preconditioners suited for p-adaptivity?

No, but they kind of work. I wouldn't expect an FE_Q(13) to work well (even without h or p adaptivity).

**Comment by marcfehling** [comment]
> > Are AMG preconditioners suited for p-adaptivity?
> 
> No, but they kind of work. I wouldn't expect an FE_Q(13) to work well (even without h or p adaptivity).

Maybe I was expecting too much of a miracle...

Comparing wallclock times for the solution process between the adaptive case `FE_Q(2) ... FE_Q(7)` and the static case `FE_Q(7)` shows that the adaptive one is actually faster. I'll come up with a reasonable presentation of these results that we could discuss later at some stage. Anyways, thanks for the hint that I should not expect too much of the AMG blackbox in this respect.

**Comment by marcfehling** [comment]
However, the issue with PETSc still persists, so I'll keep this issue open.

**Comment by marcfehling** [comment]
> Two quick comments:
> You are using CG, which means your system and preconditioner need to be SPD. If they are not, CG can fail at any time (break down) or not converge. So you need to use `data.symmetric_operator=true`, otherwise PETSc might use a smoother or coarse solver that is not symmetric.
> 
> Secondly, I would suggest experimenting with GMRES first as it is typically the most robust method and does not require for the system to be SPD. For timings you don't want to do that, but maybe one of the constraints breaks positive definiteness. If GMRES works but CG doesn't you know what the problem is...

Sorry, I missed that comment...

I tried `GMRES` with `Trilinos` on that case to check if there are any performance differences, but there really is none. Haven't tried that with `PETSc` yet -- Will do!

**Comment by kronbichler** [comment]
A quick answer before I find more time: I would not expect AMG to do well for polynomials of degree higher than 5 in 2D and higher than 3 in 3D because it tends to coarsen too much, be it DG or continuous elements. One needs quite some hand-tuning to make AMG run well, and most successful strategies I am aware of are not really black box any more. I would prefer some geometric/p-coarsening. Let's hope @peterrum soon finds time to work on integrating the p-multigrid, then we might also try to extend that to hp.

**Comment by marcfehling** [comment]
@kronbichler Thank you for your feedback! I didn't expect that aggressive coarsening would be the main reason for poor performance. Maybe changing a few parameters for the AMG algorithms will yield some performance benefits. I do not expect miracles, though.

For [hypre](https://www.dealii.org/current/doxygen/deal.II/structPETScWrappers_1_1PreconditionBoomerAMG_1_1AdditionalData.html), I had in mind trying a different `strong_threshold` parameter. For [ML](https://www.dealii.org/developer/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionAMG_1_1AdditionalData.html), I was thinking about adapting the `aggregation_threshold` or using a different `smoother_type` (e.g. Block- or IFPACK-Chebyshev smoothers). I'll play around with some parameters trying to figure out what works in my case. I'll appreciate any kind of suggestion :)

Surely, geometric MG is the method of choice, and I would like to join you working on hp-GMG. [Mitchell (2010)](https://math.nist.gov/~WMitchell/papers/hpmultigrid.pdf) already had some ideas. But unfortunately I have to add this topic to the other things that I have postponed to the time after my graduation...

**Comment by marcfehling** [comment]
For hypre, I noticed that increasing the `strong_threshold` for `PETScWrappers::PreconditionBoomerAMG::AdditionalData` helps to achieve convergence. I've increased it to a higher value than the default one (`0.25 -> 0.5`), which helped in this particular scenario.

I just conclude that AMR preconditioners are really not getting along well with hp-FEM. Thus I'll close this issue.
