### ISSUE TITLE
doxygen: avoid Python dependency for setting canonical links

### ISSUE THREAD

**Issue by fvanmaele** [dealii/dealii#8735]
`set_canonical_doxygen.py` may lead to errors when using certain Python3 versions (`UnicodeDecodeError` on `/usr/bin/python3.6`, see issue #8714). 

Having the script in Perl (as most of the other `doxygen` scripts) avoids these issues and the additional Python dependency.

----
While rewriting the script, I noticed that `# Do not add canonical link twice` does not actually work, since the `canonical_link_added` is always set to `False` inside the loop. This should be fixed in the follow-up PR to this issue.

**Comment by fvanmaele** [comment]
PR #8736

**Comment by drwells** [comment]
Fixed by #8736.
