### ISSUE TITLE
Adding deal.II to Compiler Explorer

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#8744]
[Compiler Explorer](https://godbolt.org) is a fantastic online tool for teaching and communication of coding information. It now allows the users to incorporate external libraries in their code and the main website offers 36 pre-installed libraries. Additionally, it allows execution of the code and shows the standard output.

It would be great if we also install `deal.II` in Compiler Explorer. It will allow us to show demos in classes and presentations. It also allows us to effectively share and discuss sample deal.II codes on github or the mailing list.

This is not an urgent task but we can think about doing it at some point. I found [some info](https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALibrary.md) on how to add a new library to compiler explorer. I don't have experience with the build system, so I wouldn't assign this task to myself.

**Comment by drwells** [comment]
This would be a cool feature but that page has a large number of caveats when it comes to building C++ libraries - I don't think we have the manpower to maintain something like this. I'm going to close this for now - we can reopen it if someone is explicitly interested in adding this functionality to compiler explorer.
