### ISSUE TITLE
minor documentation flaw in step-51

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#876]
Something wrong at
"this term simply reads Undefined control sequence \ve".

I am not familiar this tutorial and don't know how to fix it at this moment. 
Maybe someone else could fix this easily.

**Comment by bangerth** [comment]
Is this your local installation or the website? It looks ok to me at 
http://dealii.org/developer/doxygen/deal.II/step_51.html

**Comment by QiaoLei-88** [comment]
Sorry. It's in version 8.2.0.
I was led to there by Google.
