### ISSUE TITLE
Bug with face orientations in FEInterfaceValues

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8786]
I woke up last night at 2am and realized that there is a bug in the `FEInterfaceValues` class (#8660) that I approved a couple of days ago. It took me an hour to go back to sleep.

The bug is that the class assumes that quadrature points are sorted in the right order on the faces of the two adjacent cells. In other words, that `fe_interface_values.get_fe_face_values(0).quadrature_point(q)` is at the same physical location as `fe_interface_values.get_fe_face_values(1).quadrature_point(q)`. But I don't think that's actually correct -- it's only true if I recall correctly if the coordinate systems of the two adjacent cells match. If that's not the case, then we need to sort quadrature points on the two sides of the interface and have a mapping that makes sure that they match.

At least that's what my brain came up in the half-daze I was in.

**Comment by bangerth** [comment]
I'll have a test that checks this later today.

**Comment by tjhei** [comment]
Ouch. I can prep a PR that adds this assert if that helps?

**Comment by bangerth** [comment]
Let me work on this for a few minutes. I may just be wrong -- if what I dreamed up was true, every DG code would be wrong on such meshes.

**Comment by bangerth** [comment]
Turns out I'm wrong. Test demonstrating this coming soon. Apparently the people who wrote `FEFaceValues` thought about this issue at some point. I should remember this when I'm lying awake over a bug next time...

**Comment by luca-heltai** [comment]
I think you got caught in the discussion we were having on the mailing list with Alberto Salvadori. This is true for the coupling between faces and co-dimension one cells, but it is taken care of between neighboring cells.

**Comment by bangerth** [comment]
On 9/18/19 1:55 PM, Luca Heltai wrote:
> I think you got caught in the discussion we were having on the mailing 
> list with Alberto Salvadori.

Yes. My brain --unsurprisingly -- did not work well in the middle of the 
night and then I was so spooked that I needed to double check myself :-)
