### ISSUE TITLE
undefined references linker errors with intel 19.0.5

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8791]
I don't have time to investigate but I see the following:
```
[54/103] Linking CXX executable bin/step-7.release
FAILED: : && /home/heister/bin/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc    -rdynamic -Wl,--as-needed -shared-intel -qopenmp -rdynamic -fuse-ld=gold -pthread examples/CMakeFiles/step-7.release.dir/step-7/step-7.cc.o  -o bin/step-7.release  -Wl,-rpath,/home/heister/build-deal-intel2/lib:/home/heister/candi-system/OpenBLAS-0.2.20/lib: lib/libdeal_II.so.9.2.0-pre /home/heister/candi-system/OpenBLAS-0.2.20/lib/libopenblas.so -lgfortran -lm -lquadmath -lc -ldl -lz -lrt && :
lib/libdeal_II.so.9.2.0-pre: error: undefined reference to 'dealii::TensorProductPolynomials<0, dealii::Polynomials::Polynomial<double> >::evaluate(dealii::Point<0, double> const&, std::vector<double, std::allocator<double> >&, std::vector<dealii::Tensor<1, 0, double>, std::allocator<dealii::Tensor<1, 0, double> > >&, std::vector<dealii::Tensor<2, 0, double>, std::allocator<dealii::Tensor<2, 0, double> > >&, std::vector<dealii::Tensor<3, 0, double>, std::allocator<dealii::Tensor<3, 0, double> > >&, std::vector<dealii::Tensor<4, 0, double>, std::allocator<dealii::Tensor<4, 0, double> > >&) const'
lib/libdeal_II.so.9.2.0-pre: error: undefined reference to 'dealii::TensorProductPolynomials<0, dealii::Polynomials::Polynomial<double> >::clone() const'
```

**Comment by bangerth** [comment]
Hm. Do you have an idea of where these are instantiated?

**Comment by anates** [comment]
The same thing happens for icc 18.0.3 20180410 here.

**Comment by tjhei** [comment]
I don't know. This only happens when linking applications based on deal.II. @bangerth how do I find out who instantiates it?

**Comment by tjhei** [comment]
actually, I found a way: by specializing the dim=0 case...

**Comment by tjhei** [comment]
https://github.com/dealii/dealii/blob/ec03a88e9f92cdd26f591ebf55983e307a4c973c/source/fe/fe_abf.cc#L187
is the first offender...

**Comment by tjhei** [comment]
2:
https://github.com/dealii/dealii/blob/ec03a88e9f92cdd26f591ebf55983e307a4c973c/include/deal.II/base/tensor_product_polynomials_const.h#L263-L268
3:
https://github.com/dealii/dealii/blob/ec03a88e9f92cdd26f591ebf55983e307a4c973c/include/deal.II/base/tensor_product_polynomials_bubbles.h#L248-L253

**Comment by tjhei** [comment]
https://github.com/dealii/dealii/blob/ec03a88e9f92cdd26f591ebf55983e307a4c973c/source/fe/fe_raviart_thomas.cc#L168-L172

**Comment by tjhei** [comment]
So, I am not sure how to fix this, but it seems easiest to instantiate things even for dim=0. Thoughts?

**Comment by bangerth** [comment]
Yes, just instantiate `TensorProductPolynomials<0>`. Is `PolynomialsBase<0>` instantiated?

**Comment by tjhei** [comment]
I can now link without errors...

**Comment by masterleinad** [comment]
Even better!
