### ISSUE TITLE
std::uncaught_exception() is deprecated in c++17

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#8793]
[std::uncaught_exception() is deprecated in c++17 and should be replaced with std::uncaught_exceptions()](https://en.cppreference.com/w/cpp/error/uncaught_exception)

We didn't remove this deprecated function in #2882, but we can think about it now.

We use `std::uncaught_exception()` in three places inside the code.
```
$ grep uncaught_exception -n -r source/
source/base/mpi.cc:783:          if (std::uncaught_exception())
source/base/subscriptor.cc:77:      if (std::uncaught_exception() == false)
source/base/timer.cc:386:  if (std::uncaught_exception() && mpi_communicator != MPI_COMM_SELF)
```

The compiler should already give us a [warning](https://godbolt.org/z/R4TdNf) and I'm not sure why we don't see the warning when we build `deal.II`.

**Comment by bangerth** [comment]
For reference, here are two ASPECT commits where we already did this replacement: https://github.com/geodynamics/aspect/pull/2728 and https://github.com/geodynamics/aspect/pull/2846
