### ISSUE TITLE
Function<dim> default constructor in examples and intel compiler

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8814]
Intel 19.0.5 gives the following warnings:
```
/home/heister/deal-git/examples/step-4/step-4.cc(327): warning #854: const variable "right_hand_side" requires an initializer -- class "RightHandSide<2>" has no user-provided default constructor
    const RightHandSide<dim> right_hand_side;
```
I think this comes from removing it in #8767 
@bangerth thoughts?

**Comment by bangerth** [comment]
The particular change you run into is in #8766. Do you get the same warning in the other tutorials where I removed the default constructor in #8767?

I think we had gotten past the point where the compiler warns about this issue :-(

**Comment by tjhei** [comment]
> Do you get the same warning in the other tutorials where I removed the default constructor in #8767?

Yes.

> I think we had gotten past the point where the compiler warns about this issue :-(

Well, it is only a warning and we could try to silence it.

On the other hand, I don't mind having the constructor there to explicitly call the ``Function<dim>`` constructor: more verbose, but it makes it obvious what to change if you want more than one component.

**Comment by bangerth** [comment]
So we'd have to revert #8767 and that part of #8766. That's a bummer. It's not wrong, it's just one more thing one has to explain.

Before we do this, can someone point out where in the standard it says that such classes should have user-defined constructors? Would an `=default` constructor do?

**Comment by rezarastak** [comment]
Obeservations from [here](https://godbolt.org/z/TI96Ii)

* The warning only appears when we define `RightHandSide right_hand_side` with `const` specifier.
* Changing the constructors or changing the member initialization of `Function` or `FunctionTime` does not help.
* Setting `= default` works.

**Comment by rezarastak** [comment]
Also, this one works too (without a need to add default constructor).
```c++
const RightHandSide<dim> right_hand_side{};
```

**Comment by masterleinad** [comment]
This is DR35 (http://open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html) with C++17 status. It seems that Intel didn't implement the new behavior yet.

**Comment by tjhei** [comment]
Okay, I will just disable the warning as this is considered a "defect".

**Comment by bangerth** [comment]
Is DR35 really the right number? It's 20 years old and has been resolved since TC1. For reference, this link takes you directly to #35: http://open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#35

**Comment by bangerth** [comment]
@tjhei: Can you try something else? I wonder whether the issue is that icc doesn't want to create a default constructor of the derived class because the base class has no default constructor. All it has is this:
```
  /**
   * Constructor. May take an initial value for the number of components
   * (which defaults to one, i.e. a scalar function), and the time variable,
   * which defaults to zero.
   */
  Function(const unsigned int n_components = 1,
           const time_type    initial_time = 0.0);
```
I wonder what would happen if we did the following:
```
  /**
   * Default constructor that corresponds to a function with one vector component
   * and sets the time this function corresponds to to zero.
   */
  Function ();

  /**
   * Constructor. May take an initial value for the number of components
   * (which defaults to one, i.e. a scalar function), and the time variable,
   * which defaults to zero.
   */
  Function(const unsigned int n_components,
           const time_type    initial_time = 0.0);
```
and then implement
```
  Function::Function ()
  : Function(1, 0.0)     // simply forward to the other constructor
```
Does that address the problem?

**Comment by masterleinad** [comment]
> Is DR35 really the right number? It's 20 years old and has been resolved since TC1. For reference, this link takes you directly to #35: http://open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#35

Oops, I meant http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#253.

**Comment by bangerth** [comment]
I'd suppress the warning. The DR was only accepted for C++17, but I think it was always considered a defect. I can't imagine icc implementing anything other than what gcc does, even though it warns.

**Comment by tjhei** [comment]
> Does that address the problem?

no, doesn't work.

> I'd suppress the warning.

Will do.
