### ISSUE TITLE
Incorrect count on DoFHandler::n_boundary_dofs() for distributed Triangulations

### ISSUE THREAD

**Issue by dougshidong** [dealii/dealii#8897]
Found this bug while cross-checking my own count.

https://github.com/dealii/dealii/blob/f538a13de76f5c9fb0f8744e036ec57c81cf6c79/source/dofs/dof_handler.cc#L1095-L1129

This is problematic when the Triangulation is distributed.

`cell->face(f)->get_dof_indices(dofs_on_face);`

will return `numbers::invalid_dof_index`, and this index (4294967295 in my case), will get inserted into the set once. 

Additionally, this will double-count indices on shared edges across sub-domains. So each domain will count (all_dofs_it_sees+1). Therefore, we can't even do some kind of MPI sum on it.

A solution would be to add a check on the locally owned DoFs and then MPI sum it
``` C++
dealii::IndexSet locally_owned_dofs = locally_owned_dofs();
std::unordered_set<unsigned int> locally_owned_dofs(locally_owned_dofs.begin(), locally_owned_dofs.end());
...
   for (unsigned int i = 0; i < dofs_per_face; ++i) {
       const int global_idof_index = dofs_on_face[i];
       if ( locally_owned_dofs.find(global_idof_index) != locally_owned_dofs.end() ) ) {
            boundary_dofs.insert(dofs_on_face[i]);
       }
   }
...
call some MPI_Reduce(sum);
```

**Comment by masterleinad** [comment]
Yes, that is one of the functions we didn't update for `parallel::Triangulation` objects yet. Do you want to give improving the behavior a shot?

You would likely need to try to cast the `Triangulation` object to a `parallel::Triangulation` object and in case of success perform the `MPI_Reduce` operation.

**Comment by tjhei** [comment]
How do want to do handle this? Many other functions have "global" versions: n_active_cells() vs n_global_active_cells(). I also don't think we have any of these n_* functions do an MPI communication. This would make the call a collective call (every processor needs to call it), which is surprising (at least to me).
So, my suggestions would be to just fix n_boundary_dofs to return something sensible but only counting local entries.

**Comment by tjhei** [comment]
That said, @dougshidong : what do you want to use this information for? If you care about the global number of boundary dofs, having this function return the locally_owned boundary dofs might be enough (you can then do an MPI::sum() outside).

**Comment by dougshidong** [comment]
> How do want to do handle this? Many other functions have "global" versions: n_active_cells() vs n_global_active_cells(). I also don't think we have any of these n_* functions do an MPI communication. This would make the call a collective call (every processor needs to call it), which is surprising (at least to me).
> So, my suggestions would be to just fix n_boundary_dofs to return something sensible but only counting local entries.

Yes, that is what I was thinking. Performing a collective call inside doesn't sound like the best practice. I think that returning the number of locally owned boundary dofs sounds reasonable. Will have to add some documention about this though.

I personally ended up coding my own count before I knew this function existed because I needed to serialize my boundary points. Just wanted to check that I had the correct number with n_boundary_dofs(). I am not actually using it. Ended up verifying by visually counting

> Yes, that is one of the functions we didn't update for `parallel::Triangulation` objects yet. Do you want to give improving the behavior a shot?

A bit swamped right now. I can make a pull request to make it return the number of locally owned boundary dofs, but I won't have time to make a nice new test for it. I mean, worst case scenario, the count is still wrong.

**Comment by masterleinad** [comment]
> A bit swamped right now. I can make a pull request to make it return the number of locally owned boundary dofs, but I won't have time to make a nice new test for it. I mean, worst case scenario, the count is still wrong.

That would be much appreciated. It should be pretty straight-forward to write a test for this, but we can help with that if you fix it the function in a pull request.

**Comment by bangerth** [comment]
I'd say that the function should return the global number. I don't see a problem with the fact that the function becomes collective this way, but if that is ever an issue, we can always move the number of boundary DoFs into the number cache where we also store the total number of DoFs, and then `n_boundary_dofs()` just reads the number from the cache.

**Comment by masterleinad** [comment]
#8901 fixed this. Do you insist on returning the global number instead?

**Comment by bangerth** [comment]
Oh, I'm just catching up from two weeks and didn't read chronologically through my inbox. I'll go through that PR later and comment there.

**Comment by tjhei** [comment]
> I'd say that the function should return the global number. 

That would be inconsistent with every other n_* function inside ``Triangulation``.

> I don't see a problem with the fact that the function becomes collective this way

I would find that quite surprising.

**Comment by bangerth** [comment]
I agree that it is inconsistent with the functions in `Triangulation`, but not with the ones in `DoFHandler`. Either way, it's settled :-)

**Comment by dougshidong** [comment]
I can always change the name to `n_locally_owned_boundary_dofs()`. This would be consistent with `DoFHandler::n_locally_owned_dofs()`. Let me know if that's preferable. Otherwise, we can close this issue.
