### ISSUE TITLE
step-22 uses a definition of Stokes that nobody uses

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#892]
When I wrote step-22, I was stupid and didn't know that the equation with the symmetric gradient is physically more correct, but requires a factor of two (which it doesn't have).

When I realized that, I got defensive and tried to explain that there is a genuine disagreement between different parts of the sciences of whether the factor of 2 should be there or not. That's b.s.. I should have just fixed it by adding the factor of 2.

This remains the state today. Someone just has to go through the introduction and add the factor of 2 in all places, the do the same in the assembly (which I think is the only place where it's necessary in the program) and then update the results section.

**Comment by guidokanschat** [comment]
Well, as long as you have only no-slip boundary conditions, it does not matter if you use the divergence of the gradient or of the strain tensor. But it's surely better with strain tensors.
