### ISSUE TITLE
Missing classes in Vectors doxygen module

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#894]
Somehow not all of vector classes show up [1].

[1] https://www.dealii.org/developer/doxygen/deal.II/group__Vectors.html

**Comment by tjhei** [comment]
Yeah, SparseMatrix has been broken for a long time too. Please see https://bugzilla.gnome.org/show_bug.cgi?id=722940 (finally fixed? Yay!)

**Comment by guidokanschat** [comment]
Check out the online documentation!

Close?

**Comment by bangerth** [comment]
Yes, looks good. What did you change to make this happen? Just upgrade doxygen?

**Comment by guidokanschat** [comment]
Indeed. I also fixed the documentation of 8.2.1

**Comment by bangerth** [comment]
Nice, thank you!
