### ISSUE TITLE
compile error with std::vector<FunctionParser<dim>>

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#8951]
I am getting a compile error when I `push_back` (or `emplace_back`) data into an object of type `std::vector<FunctionParser<dim>>`.

There are multiple compile errors. All of them are related to the following member variable.
```c++
mutable Threads::ThreadLocalStorage<std::vector<std::unique_ptr<mu::Parser>>> fp;
```
One error is caused due to the forward declaration of `mu::Parser`. However, even after fixing that, I saw more compile errors which I couldn't fix.

The necessary files for reproducing this error and the logs are attached here.
[CMakeLists.txt](https://github.com/dealii/dealii/files/3765446/CMakeLists.txt)
[function_parser_vec.cc.txt](https://github.com/dealii/dealii/files/3765444/function_parser_vec.cc.txt)
[error.txt](https://github.com/dealii/dealii/files/3765442/error.txt)
[summary.log](https://github.com/dealii/dealii/files/3765443/summary.log)

**Comment by bangerth** [comment]
Yes, `FunctionParser` objects can't be copied, but `std::vector<T>` requires that `T` is copyable. So you can't have a vector of `FunctionParser` objects.

**Comment by rezarastak** [comment]
Thank you for explaining that. I will store my expressions in `std::vector<std::string>` instead of `std::vector<FunctionParser<dim>>` and use a single `FunctionParser` to create the functions later from the expressions. So, my issue is solved. 

Even though `FunctionParser` is is not copiable, I think it should allow us to move it into a container or construct it in-place using `emplace_back`. Since c++11, `std::vector<T>` does not require `T` to be copiable. For example, we should be able to do something like
```c++
FunctionParser<2> f("x");
std::vector<FunctionParser<2>> v;
v.push_pack(std::move(f));
v.emplace_back("x + y");
```

**Comment by bangerth** [comment]
Yes, that's possible.

You can of course also store *pointers* to `FunctionParser* objects in your vector.
