### ISSUE TITLE
How to deal with MPI P2P communication using the same MPI tag

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8958]
We've had a good amount of discussion over the last few days about the potential for deadlocks and other Bad Things (TM) happening in functions that do point-to-point communication when they are called multiple times in a row. That's because it is conceivable that we get into the following scenario:
```
  void foo ()
  {
    MPI_Send (something to processor 0, mpi_tag=1234);

    for (number of expected packets)
      MPI_Recv (..., MPI_ANY_SOURCE);
  }
```
In these cases, if the function is called twice in a row and if a processor ends up not expecting any packets, they will end up sending two packets in a row, with the same tag, to potentially the same target. Because the target processor receives packets via `MPI_ANY_SOURCE` in whatever order they come in, it's possible that it processes both packets from the fast processor and not the ones that were intended to be processed from the first invocation of the function.

The cheap way out is to put a barrier at the end of the function. This will make sure that no processor sends its second batch of messages before the first is completely processed because the function doesn't even exit before every processor has completed processing.

But that's inefficient. We don't need a barrier, we really only want to avoid sending new messages before everyone is done processing. This could be done by putting the barrier at the *beginning* of the function -- we're allowed to do something else after exiting `foo()`, we just can't start sending again before everyone is back at the top of `foo()`.

But that's also inefficient. I think that the right design pattern is to actually start an IBarrier at the end of the function, and check that we had gotten there at the top of the function. Maybe something like this pattern would work:
```
  void foo ()
  {
    static MPI_Request ibarrier = invalid_request;
    if (ibarrier != invalid_request)
     MPI_Wait(ibarrier);     // make sure that all processors have signaled that the
                                        // have finished their processing

    {   // existing code
      MPI_Send (something to processor 0, mpi_tag=1234);

     for (number of expected packets)
       MPI_Recv (..., MPI_ANY_SOURCE);
   }

   // Place the barrier, but return immediately
   MPI_Ibarrier (mpi_communicator, &ibarrier);
 }
```
I *think* that that would achieve what we want, without (i) incurring any delay on returning from the function or starting its work, (ii) requiring global communication.

I suspect that one could abstract this functionality into a class that does the check in the constructor and sets the barrier in the destructor. It would have to be a bit smarter to make sure we don't use the same barrier if the function is called with different communicators, but that could be done using a `std::map`, I suspect.

**Comment by bangerth** [comment]
@tjhei @kronbichler @peterrum -- FYI.

**Comment by tjhei** [comment]
> I _think_ that that would achieve what we want, without (i) incurring any delay on returning from the function or starting its work, (ii) requiring global communication.

Yes, this does what you describe, but it does require global communication (I assume a barrier is basically MPI_Reduce followed by MPI_Broadcast).
One problem that remains with this solution is that the tags we use across the whole library need to be unique, otherwise processors can mix up messages between two different routines.

> It would have to be a bit smarter to make sure we don't use the same barrier if the function is called with different communicators, but that could be done using a `std::map`, I suspect.

This might not be needed, I think. With your pseudo-code, you will just have at most one barrier in flight and wait for it to finish on each processor before doing the next call. It might be a different one if some processors did the same function again, but that doesn't matter.

I see one problem with your approach though: you will have an open MPI_Request in a static variable for each P2P algorithm that might never be cleared before exiting the application. Not sure how much of a problem that is, but it is not very elegant. Does this generate an error when calling MPI_Finalize? If yes, one would need to register the request in some central location and clean it up later...

**Comment by peterrum** [comment]
> If yes, one would need to register the request in some central location and clean it up later...

What about `MPI_InitFinalize`?

**Comment by bangerth** [comment]
On 10/24/19 11:52 AM, Timo Heister wrote:
>     I /think/ that that would achieve what we want, without (i) incurring any
>     delay on returning from the function or starting its work, (ii) requiring
>     global communication.
> 
> Yes, this does what you describe, but it does require global communication (I 
> assume a barrier is basically MPI_Reduce followed by MPI_Broadcast).

True, but these global communications happen in the background. Nobody is 
waiting on the communication to finish -- these are all IReduce and IBroadcast 
operations.


> One problem that remains with this solution is that the tags we use across the 
> whole library need to be unique, otherwise processors can mix up messages 
> between two different routines.

Correct. But that is the same as currently -- we probably ought to have some 
central register for tags. (I have had this thought for ~18 years now but 
never felt the need to actually do it...)


>     It would have to be a bit smarter to make sure we don't use the same
>     barrier if the function is called with different communicators, but that
>     could be done using a |std::map|, I suspect.
> 
> This might not be needed, I think. With your pseudo-code, you will just have 
> at most one barrier in flight and wait for it to finish on each processor 
> before doing the next call. It might be a different one if some processors did 
> the same function again, but that doesn't matter.

Good point. It might be more efficient to have multiple barriers if one were 
to call the same function in succession with different communicators, but I 
suspect that that rarely happens.


> I see one problem with your approach though: you will have an open MPI_Request 
> in a static variable for each P2P algorithm that might never be cleared before 
> exiting the application. Not sure how much of a problem that is, but it is not 
> very elegant. Does this generate an error when calling MPI_Finalize? If yes, 
> one would need to register the request in some central location and clean it 
> up later...

Hm, really? Can't you just abandon an MPI_Request object? (I do see that MPI 
provides MPI_Request_free() as a destructor; I have no idea whether we 
actually use that -- a quick search shows that we don't ever free our 
requests: We may wait for all of them, but we never release them.)

I've read through ~10 pages of the MPI standard now, and I can't find a 
normative statement that says whether every request eventually has to be 
checked, and whether it has to be destroyed via MPI_Request_free(). As a 
consequence, it would surprise me if we can't just abandon requests -- that 
might pile up memory in the MPI run time for open requests, but we won't have 
that many (one per function where we do P2P communication).

**Comment by tjhei** [comment]
> a quick search shows that we don't ever free our requests: We may wait for all of them, but we never release them.)

if MPI_Wait[all] succeeds, it will free the request: http://mpi.deino.net/mpi_functions/MPI_Wait.html

**Comment by tjhei** [comment]
> it would surprise me if we can't just abandon requests -- that might pile up memory in the MPI run time for open requests, but we won't have that many (one per function where we do P2P communication).

@peterrum says it is a problem (see above)

**Comment by bangerth** [comment]
On 10/24/19 12:31 PM, Timo Heister wrote:
> if MPI_Wait[all] succeeds, it will free the request: 
> http://mpi.deino.net/mpi_functions/MPI_Wait.html

Ah. I guess that also means one can't call MPI_Wait on the same request 
multiple times. (One can: MPI_Wait sets it to an invalid request, and on that 
invalid request, MPI_Wait immediately returns; but in these latter calls, the 
status argument is no longer filled.)

So yes, I guess that means that every user-side MPI_Request is associated with 
some internal MPI data structure that is released whenever MPI_Wait is called 
and that, in our idea, is not currently released. But it shouldn't be very 
difficult (as @peterrum correctly suggests) to add a (static) signal to 
MPI_InitFinalize that we call before finalizing MPI and to which all of our 
objects attach via a `clean_up()` function that just waits for all still 
pending requests.

**Comment by tjhei** [comment]
I am working on a draft for this: https://github.com/tjhei/dealii/commits/mpi_wait_finalizer

**Comment by peterrum** [comment]
>I am working on a draft for this: https://github.com/tjhei/dealii/commits/mpi_wait_finalizer

On the first glance it looks good @tjhei !

**Comment by tjhei** [comment]
And it seems to work for my toy unittest. :-) 

okay, I cleaned things up some more and will open a PR in a minute.

**Comment by bangerth** [comment]
I've thought about this some more, and here is an alternative approach that
* uses no communication (even in the background) at all
* avoids the issue of clean-up
* avoids the issue that different parts of the program might inadvertently use the same tag:
```
  int next_unused_MPI_tag (const MPI_Comm communicator)
  {
    // need to protect the rest of this function using a mutex
    static std::map<MPI_Comm, int> last_used_tag;
    if (last_used_tag.find(communicator) == last_used_tag.end())
      {
         last_used_tag[communicator] = 0;
         return 0;
      }
   else
     {
         ++last_used_tag[communicator];
         return last_used_tag[communicator];
     }
  }
```

Then the original function would simply look like this:
```
 void foo ()
  {
    const int mpi_tag = next_unused_MPI_tag (communicator);
    MPI_Send (something to processor 0, mpi_tag);

    for (number of expected packets)
      MPI_Recv (..., MPI_ANY_SOURCE);
  }
```
This way, we simply use a new tag every time we work on an operation, and subsequent communication steps can't interfere with each other as long as we use the correct tag in the `MPI_Irecv` (i.e., in particular not use MPI_ANY_TAG).

**Comment by tjhei** [comment]
> I've thought about this some more, and here is an alternative approach

This is likely to work as well. A few things come to my mind:
1. We need to be careful with ints wrapping around (okay, 4b communication steps is not very likely, but still).
2. Can the MPI library re-use communicator ids? If yes, this can lead to a problem. For example:
    a) half of the ranks duplicate a communicator (and get id=1)
    b) they grab a tag (for example tag 5 and store 6 as the next tag for id =1)
    c) they free the communicator with id=1
    d) all ranks duplicate comm_world and receive id=1 again
    e) now half of the ranks thing the next tag is 6, half of them think it is 0.
3. This algorithm does not scale if someone keeps duplicating communicators. Again, unlikely to be a big issue, but worth thinking about.
4. It assumes all processors acquire the tags in the same order (also okay, so I hope the mutex is not needed)
5. It needs to work if a single algorithm requires more than one tag (this should also work with the implementation above).

I don't think the cost of the non-blocking barrier solution is a problem (we are talking 1e-4s or something). I am not opposed to the solution using tags, but the critical section using barriers has one advantage: one could create a barrier when entering and leaving the critical section in debug mode, which could be very handy to detect bugs in these kind of algorithms. This would have been quite useful for my bug hunting the last few weeks, because I had no idea where the 10k+ ranks were hanging.

Anyways, before I go implement more, let's discuss first. @kronbichler , @peterrum , what do you think?

**Comment by bangerth** [comment]
>  1. We need to be careful with ints wrapping around (okay, 4b communication
>     steps is not very likely, but still).

Yes, I thought of that as well -- it should be easy to check this using 
`std::numeric_limits<decltype(MPI_ANY_TAG)>::max()`. It might be substantially 
less than 4B, depending on the actual data type. We also need to avoid the 
special tags such as MPI_ANY_TAG.


>  2. Can the MPI library re-use communicator ids? If yes, this can lead to a
>     problem. For example:
>     a) half of the ranks duplicate a communicator (and get id=1)
>     b) they grab a tag (for example tag 5 and store 6 as the next tag for id =1)
>     c) they free the communicator with id=1
>     d) all ranks duplicate comm_world and receive id=1 again
>     e) now half of the ranks thing the next tag is 6, half of them think it is 0.

Ah yes, that's awkward. That might be a killer argument :-( I wonder if we 
could think about releasing numbers by wrapping MPI_Comm_free().


>  4. It assumes all processors acquire the tags in the same order (also okay,
>     so I hope the mutex is not needed)

I thought about this as well, but in essence it comes down to thread-safety: 
You only get in trouble if someone has concurrent calls to communication 
functions from different threads but using the same communicator. I hope that 
we avoid that.


>  5. It needs to work if a single algorithm requires more than one tag (this
>     should also work with the implementation above).

Yes. You'd just acquire two subsequent tags.


> I don't think the cost of the non-blocking barrier solution is a problem (we 
> are talking 1e-4s or something). I am not opposed to the solution using tags, 
> but the critical section using barriers has one advantage: one could create a 
> barrier when entering and leaving the critical section in debug mode, which 
> could be very handy to detect bugs in these kind of algorithms. This would 
> have been quite useful for my bug hunting the last few weeks, because I had no 
> idea where the 10k+ ranks were hanging.

I agree that the IBarrier is still the more elegant solution.

**Comment by tjhei** [comment]
skype call with @bangerth @kronbichler @peterrum and me:
- We will go forward with #8964 and two blocking barriers as soon as possible
- Use the new CollectiveMutex in the places necessary: #8997
- Later we can try to optimize and simplify the code (the IBarrier does not seem to be correct on my system)

**Comment by tjhei** [comment]
I have a list with source location and MPI tag for all places where we use MPI_ANY_SOURCE and was thinking that should go into the repo somewhere. Should I just make a table in doc/doxygen/headers/ ?

**Comment by bangerth** [comment]
I wonder whether we should have
```
  namespace MPI {
    namespace internal {
       enum class Tags : decltype(MPI_ANY_TAG) {
          distribute_dofs,
          compute_p2p,
          ...
       }
    }
  }
```
This way, things just stay in sync. It's a bit clunky, but the list does not change very often.

**Comment by tjhei** [comment]
Neat idea, will try something like that.

**Comment by tjhei** [comment]
> one doesn't even have to re-compile everything if one adds a tag.

sadly, it is needed in mpi.h...

**Comment by tjhei** [comment]
I think there is nothing left to do here. Closing.
