### ISSUE TITLE
MPI tests can be only run with p4test

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#8966]
I wanted to test some deal.II MPI features (which I know do not depend on p4est) with a minimal build (with as few external libraries as possible, i.e without p4est). However, this did not work because these tests are only build if deal.II is built with p4est.

The reason:
https://github.com/dealii/dealii/blob/c223f4e0c4256f9f9ca9816500bf07fb25989bb2/tests/mpi/CMakeLists.txt#L4-L6

Can we remove the `AND DEAL_II_WITH_P4EST`? If deal.II is compiled with p4estis also tested with `*with_p4est=true.*.output`, isn't it?

**Comment by masterleinad** [comment]
This will likely break tests that in fact need `p4est` in that folder (and don't have `with_p4est=on` in the output filename).

**Comment by peterrum** [comment]
> This will likely break tests that in fact need p4est in that folder (and don't have with_p4est=on in the output filename).

@masterleinad  This can be changed (with some work) without problem, cannot it?

**Comment by bangerth** [comment]
On 10/27/19 7:14 AM, Peter Munch wrote:
> @masterleinad <https://github.com/masterleinad> This can be changed (with some 
> work) without problem, cannot it?

Yes. You probably just need to identify which of these tests don't have 
`with_p4est=on` in the test output name, and still use `p::d::Triangulation`.
