### ISSUE TITLE
VectorTools::project_boundary_values_curl_conforming_l2 fails in 3d on FESystems containing FE_Nedelec and FE_Q 

### ISSUE THREAD

**Issue by winnifried** [dealii/dealii#8974]
This is issue 2 described in detail in 
https://groups.google.com/forum/#!topic/dealii/taFA8q2ugsg

When trying to use VectorTools::project_boundary_values_curl_conforming_l2 to apply boundary values to the FE_Nedelec component of a FESystem containing also one FE_Q element the application fails with the error 

"Error: Unexpected number of 3D edge DoFs"

**Comment by bangerth** [comment]
Can you copy a minimal testcase here, so that the issue is recorded completely in github?

**Comment by winnifried** [comment]
Shure: Here it is

[main.cc](https://github.com/dealii/dealii/files/3804703/main.txt)

**Comment by winnifried** [comment]
I will have a look if that works. 

For your reference, I have a more elaborate test program that not 
only tests if the assertions passes, but also if the values are correctly applied. 
The code is here for your use:
[main.cc](https://github.com/dealii/dealii/files/3813404/main.txt)
