### ISSUE TITLE
Failing build with Tpetra

### ISSUE THREAD

**Issue by winnifried** [dealii/dealii#8975]
> It is tested in deal v 9.1.1 - I could not test in the current deal git version since dealii/dealii/master fails to compile in debug mode at the moment.

Would you mind opening another issue for this? Our regression tests (https://cdash.43-1.org/index.php?project=deal.II) don't indicate any problem, though.

**Comment by masterleinad** [comment]
Oh, I mean telling us the problem you are seeing.

**Comment by winnifried** [comment]
I have configured the current deal.II git master branch   
(1d48c9c5d8c0d075d3b351ff2d94dcbd0833a8b1)
with p4est 2.0, petsc 3.9.4, scalapack 2.0.2, slepc 3.9.2, trilinos 12.12.1 
when compiling I get the following error 

In file included from [...]dealii-git-sources/source/numerics/vector_tools_integrate_difference.cc:22:0:
[...]dealii-git-build/source/numerics/vector_tools_integrate_difference.inst:31045:2: error: expected identifier before ‘&’ token

**Comment by winnifried** [comment]
The compiler is the mpich wrapper for gcc 5.4.0. 
This setup worked well with the latest release.

**Comment by masterleinad** [comment]
How do the lines around `dealii-git-build/source/numerics/vector_tools_integrate_difference.inst:31045:2` look like?

**Comment by winnifried** [comment]
# ifdef DEAL_II_TRILINOS_WITH_TPETRA
 template void
 integrate_difference< 1 ,
 LinearAlgebra::TpetraWrappers::Vector<float>,
 Vector<float>,
  1 >(
 const DoFHandler< 1 ,  1 > &,
 const LinearAlgebra::TpetraWrappers::Vector<float>,
 &,
 const Function< 1 > &,
 Vector<float> &,
 const Quadrature< 1 > &,
 const NormType &,
 const Function< 1 > *,
 const double);
# endif

**Comment by winnifried** [comment]
To me it looks like line 323 in sources/numerics/vector_tools_integrate_difference.inst.in creates this, and there a  `const LinearAlgebra::TpetraWrappers::Vector<float>, &,` should in fact be 
`const LinearAlgebra::TpetraWrappers::Vector<float> &,`
I will see if that is solves the issue and then open another pull request.

**Comment by masterleinad** [comment]
Yes, that looks wrong.

**Comment by winnifried** [comment]
It seems changing line 323 in sources/numerics/vector_tools_integrate_difference.inst.in fixes the compile issue. I have added this to the pull request, and close this issue.

**Comment by masterleinad** [comment]
Do you know that you can automatically close issues when you refererence them from the initial comment on a pull request by "Fixes #..."?
