### ISSUE TITLE
Use FE_DGRT everywhere in step-61

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8978]
step-61 still uses `FE_RaviartThomas` in a number of places. We should really be using `FE_DGRT` everywhere -- not because it makes a difference (all of the places do cell-local computations), but because it's the right thing to do (precisely because we're doing cell-local computations: All of the things we compute only live on a single cell, with no shape functions extending to neighboring cells.

@sophy1029 -- do you want to give this a try? I think you really just need to replace all of the places where we create a `FE_RaviartThomas` by the other element, remove the `fe_raviart_thomas.h` header file, and make sure that the result doesn't change.

**Comment by bangerth** [comment]
Follow-up to #8898.

**Comment by sophy1029** [comment]
Yes, I will change that.

**Comment by bangerth** [comment]
This is addressed in #8999.
