### ISSUE TITLE
Assert for parallel::distributed::Triangulation and hp::DoFHandler

### ISSUE THREAD

**Issue by BenBrands** [dealii/dealii#8993]
I have created an example (extension of step-4) using both the hp::DoFHandler and the distributed Triangulation to illustrate the problem.

As soon as I use local refinement, the following assertion is thrown:

> An error occurred in line <1119> of file </home/benjamin/spack/var/spack/stage/dealii-develop-tddwd3d2gapfekuseackzafq6slbo6kk/spack-src/source/dofs/dof_tools_constraints.cc> in function
    void dealii::DoFTools::internal::make_hp_hanging_node_constraints(const DoFHandlerType&, dealii::AffineConstraints<number>&) [with DoFHandlerType = dealii::hp::DoFHandler<2, 2>; number = double]
The violated condition was: 
    cell->face(face)->child(c)->n_active_fe_indices() == 1
Additional information: 
    This exception -- which is used in many places in the library -- usually indicates that some condition which the author of the code thought must be satisfied at a certain point in an algorithm, is not fulfilled. An example would be that the first part of an algorithm sorts elements of an array in ascending order, and a second part of the algorithm later encounters an element that is not larger than the previous one.
There is usually not very much you can do if you encounter such an exception since it indicates an error in deal.II, not in your own program. Try to come up with the smallest possible program that still demonstrates the error and contact the deal.II mailing lists with it to obtain help.
/home/benjamin/spack/opt/spack/linux-linuxmint18-x86_64/gcc-7.2.0/dealii-develop-tddwd3d2gapfekuseackzafq6slbo6kk/lib/libdeal_II.g.so.9.2.0-pre: void dealii::DoFTools::internal::make_hp_hanging_node_constraints<dealii::hp::DoFHandler<2, 2>, double>(dealii::hp::DoFHandler<2, 2> const&, dealii::AffineConstraints<double>&)
/home/benjamin/spack/opt/spack/linux-linuxmint18-x86_64/gcc-7.2.0/dealii-develop-tddwd3d2gapfekuseackzafq6slbo6kk/lib/libdeal_II.g.so.9.2.0-pre: void dealii::DoFTools::make_hanging_node_constraints<dealii::hp::DoFHandler<2, 2>, double>(dealii::hp::DoFHandler<2, 2> const&, dealii::AffineConstraints<double>&)
./step-4: Step4<2>::setup_system()
./step-4: Step4<2>::run()
./step-4: main

I'm wondering whether the assertion in `DoFTools::internal::make_hp_hanging_node_constraints` is actually relevant, as the code gives the expected results in Release mode.

Do you have any suggestions, @marcfehling?

[CMakeLists.txt](https://github.com/dealii/dealii/files/3803929/CMakeLists.txt)

[step-4.cc](https://github.com/dealii/dealii/files/3803933/step-4.txt)

**Comment by marcfehling** [comment]
It is basically the following sanity check that will be triggered by your code:
https://github.com/dealii/dealii/blob/ba3e307eabc80e7eae43a76be1d5e2de21793e0c/source/dofs/dof_tools_constraints.cc#L1105-L1120

I already loosened this assertion in https://github.com/dealii/dealii/pull/8365, but this did not seem to do the trick for you. I assume your issue only occurs with at least two MPI processes?

I need to think about this...

**Comment by marcfehling** [comment]
I could not reproduce your assertion with my build of `deal.II`.

Are you linking your scenario against the most recent version of [`deal.II master`](https://github.com/dealii/dealii/tree/master)? I suspect that your build does not incorporate changes made in #8365. Otherwise, I'm out of ideas for now...

**Comment by BenBrands** [comment]
That's absolutely true. I was using an obsolete version.
Thank you very much, @marcfehling!

**Comment by marcfehling** [comment]
You are very welcome! This shows us that these 'special cases' we stumble upon once in a while are indeed scenarios that reappear in the work of others. We need this kind of input to know that we are on the right track. Thank you for sharing your application example :)

**Comment by bangerth** [comment]
Would it make sense to turn the code into a testcase?

**Comment by BenBrands** [comment]
I would not mind creating a small test if you consider it useful.
@marcfehling: Is there already a test for this particular functionality?

**Comment by bangerth** [comment]
On 11/4/19 4:33 PM, BenBrands wrote:
> I would not mind creating a small test if you consider it useful.

Yes, always! More tests = more better. Especially, if they are 
real-world cases, rather than artificially constructed ones.

**Comment by marcfehling** [comment]
There is a testcase in #8365. But as @bangerth states, you can't have enough of them!

**Comment by BenBrands** [comment]
In which directory should I put the test?

**Comment by bangerth** [comment]
It does not really matter very much, but maybe `mpi/` since it runs in parallel?

**Comment by marcfehling** [comment]
The test from #8365 is called `tests/mpi/hp_hanging_node_constraints.cc`. Maybe something similar would be suitable, e.g. `tests/mpi/hp_step-4.cc`? There is already a test `tests/mpi/hp_step-40.cc` so I think this is a good pick.
