### ISSUE TITLE
Improve indent error message

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9006]
In the last few weeks, we had a lot of new user (which is good) who got during their first PR the following error message:

> invalid author 'MaxMustermann' without firstname and lastname

and in some cases we had to help them fix this issue. Could we improve the error message here 

https://github.com/dealii/dealii/blob/5e6bc00896e6eebccaaf0105f52c166dbcfe2005/contrib/utilities/indent_common.sh#L88

somehow?

Maybe with a link to a new (?) wiki entry, which describes a possible solution step by step.

ping @tjhei

**Comment by tjhei** [comment]
That would be useful, I agree. Instead of writing a lot of text, can you suggest links that show how to edit the username and rewrite the history?

**Comment by peterrum** [comment]
Maybe: https://makandracards.com/makandra/1717-git-change-author-of-a-commit

**Comment by masterleinad** [comment]
I like https://www.git-tower.com/learn/git/faq/change-author-name-email. That also covers setting it globally.

**Comment by tjhei** [comment]
great resource. I would create a wiki page and link to this document instead of directly linking to this URL, though. Let me prep that...

**Comment by tjhei** [comment]
see https://github.com/dealii/dealii/wiki/Indentation 
edits welcome.

**Comment by peterrum** [comment]
@tjhei thanks!
