### ISSUE TITLE
Import .stl files for meshes?

### ISSUE THREAD

**Issue by GrahamBenHarper** [dealii/dealii#9029]
Many data sets for 3D scanning and 3D printing are given in the `.stl` file format. While deal.II doesn't directly support the import of `.stl` files, other programs like GMSH may be used to work around that to generate a `.msh` file that can be imported.

Have there ever been considerations of cutting out the middle program and directly importing `.stl` files as 2-manifolds in 3D space? deal.II would need to split it from a triangle mesh to a quadrilateral mesh.

Taking a closed 2-manifold and turning it into a solid 3D domain would be an even more exciting problem, but it would probably be beyond the scope of a finite element library since most applications do not contain internal vertices, meaning deal.II would have to add internal vertices on its own.

**Comment by bangerth** [comment]
It turns out that we've debated patches for exactly this over the past couple of weeks. Take a look at #9029 and before that #8976/#9026.

**Comment by bangerth** [comment]
Any help as always appreciated!

**Comment by GrahamBenHarper** [comment]
Perfect! I'll check those out.

**Comment by GrahamBenHarper** [comment]
I just realized that #9048 closes this. :)
