### ISSUE TITLE
Web page: link to recent changes?

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#905]
There used to be a link to the changes done to the library since the last release (the file generated from changes.h). 

There are links for changes from 8.1 and 8.2 (as well as older ones), but I could not find the current one,  even if the page is still generated by doxygen...

A link to this page should be in the news section, in the home page, as well as in the news submenu...

**Comment by tjhei** [comment]
If you go to dealii.org, there is "recent changes" under "dev" linking to https://github.com/dealii/dealii/commits/master

**Comment by tjhei** [comment]
Or do you mean https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_2_1.html instead?

**Comment by luca-heltai** [comment]
I mean  https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_2_1.html 

I could not find a direct link to that. Is it anywhere?

**Comment by tjhei** [comment]
No, how about we replace the somewhat useless current link behind "recent changes"?

**Comment by bangerth** [comment]
How about we keep both? I'll take care of it later today.

**Comment by tjhei** [comment]
I don't feel strongly about it, but https://github.com/dealii/dealii/commits/master is kind of useless (and you can get there by clicking on "github repository" -> "commits").

**Comment by bangerth** [comment]
I made the change. Unfortunately, something with the script to update the website doesn't quite seem to work. I suppose the change will eventually propagate to the public pages.
