### ISSUE TITLE
Reserve step-70

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#9068]
@blaisb and I have been working for a couple of weeks on massively parallel immersed boundary computations. 
We came up with (what we think is) a very nice tutorial program showing the following features (most of which are new, and will be added as pull requests shortly):

- Use of particles (tracing in a stokes flow)
- Fluid structure interaction on non-matching grids in a fully distributed manner
- GridGeneration from parameter files
- Global particle generation and handling
- Interpolation between FE fields and particles (both directions)

We'd like to reserve step-70 (as a nice continuation of step-60, showing Lagrange multiplier methods on non-matching grids). :) 

Here is a preview of the results at very low resolution, showing a numerical version of a classical experiment by sir G.I. Taylor

![movie](https://user-images.githubusercontent.com/2919756/69364651-fd246200-0c92-11ea-89e5-3fb4c2f4508b.gif)

**Comment by bangerth** [comment]
Nice! And cool to see a tutorial program that uses particles!

**Comment by drwells** [comment]
Fixed by #9078.
