### ISSUE TITLE
MultipleParameterLoop::UserClass::declare_parameters(…) unused

### ISSUE THREAD

**Issue by fsonner** [dealii/dealii#909]
The class `MultipleParameterLoop::UserClass` declares the pure virtual function `declare_parameters(…)` but this function is never used in the library. Therefore I propose the removal of this function, even if it is considered best practice. 

In the examples the function could then be made static, which prevents any confusion about whether or not the parameter declaration can use the problem object (currently answered through the comment `note: must be static member!`).

**Comment by bangerth** [comment]
I agree. I'd be happy to see a patch that removes the function and updates the documentation accordingly.
