### ISSUE TITLE
FE_DGQ::memory_consumption() is not implmented

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9102]
The method `FE_DGQ::memory_consumption()` is not implemented:

https://github.com/dealii/dealii/blob/fe4975c998b1fdc124aef18238e3eb06d7ab88ed/source/fe/fe_dgq.cc#L822-L828

so that the following program fails:

```cpp
#include <deal.II/dofs/dof_handler.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria.h>

#include <deal.II/fe/fe_dgq.h>

using namespace dealii;

const int dim    = 2;
const int degree = 2;

int main()
{
    
    if(false)
    {
      Triangulation<dim> tria;
      GridGenerator::hyper_cube(tria);
    
      FE_DGQ<dim> fe(degree);
      DoFHandler<dim> dof_handler(tria);
      dof_handler.distribute_dofs (fe);
    
      // failing
      std::cout << dof_handler.memory_consumption () << std::endl;
    }
    
    if(true)
    {
      FE_DGQ<dim> fe(degree);
      
      // failing
      std::cout << fe.memory_consumption () << std::endl;
    }
    
}
```

Is there a particular reason we cannot use the implementation from `FiniteElement`?

**Comment by bangerth** [comment]
What is the error message you get? Does one of the intermediate classes intercept the virtual function and produce an error of its own?

I believe that we should just implement this in the last class before `FE_DGQ` that actually stores data.
