### ISSUE TITLE
SSL problem with www.dealii.org

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#9107]
Hi, when I try to access www.dealii.org, I get the warning message "Your connection is not private". I'm using Debian stretch and I get the same message with chromium and firefox.

I think that it is either, the server is down or there is a problem with the SSL signature.

Do other people get the same warning?

**Comment by peterrum** [comment]
The same here (I noticed it an hour ago - but did not care).

**Comment by peterrum** [comment]
The same is for the doxygen side, which is really annoying!

**Comment by tjhei** [comment]
fixed!

**Comment by dangars** [comment]
Thanks @tjhei :)
