### ISSUE TITLE
What is the most recent compatible petsc?

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#9120]
The version 9 cmake doesn't seem to recognize 3.11 as newer than 3.3.

Stick with 3.9 for a while?

Victor.

**Comment by masterleinad** [comment]
This was fixed in https://github.com/dealii/dealii/pull/7203 which is part of version 9.1.1.

**Comment by tjhei** [comment]
> Stick with 3.9 for a while?

Yes, I don't think you get any big advantages from going to a very new version.

In candi we install 3.11.3 for deal.II 9.1 for example: [source](https://github.com/dealii/candi/blob/dealii-9.1/deal.II-toolchain/packages/petsc.package#L1) while we use 3.7 for 9.0.

**Comment by krishnakumarg1984** [comment]
@tjhei the spack-install uses a very new petsc though
