### ISSUE TITLE
Introduce element-centric loops (ECL)

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9153]
In collaboration with @kronbichler, I will integrate element-centric loops (ECL) into the matrix-free framework. ECL can be used for `FE_DGQ` and `FE_DGQHermite`; in contrast to the face-centric loop `MatrixFree::loop` (FCL), which processes cells, faces, and boundary faces independently, the new loop will process a cell and all its faces in one go. As a consequence, faces will be processed two times. However, the benefit of ECL is the improved cache locality and its suitability for shared memory 
(see also https://dl.acm.org/citation.cfm?id=3325864).

I will reference this issue by the upcoming PRs.

**Comment by peterrum** [comment]
FYI @nfehn

**Comment by peterrum** [comment]
I think these 5 PRs are enough for first working ECL implementation. They have added:
- the capability to access neighboring cells even if `FEFaceEvaluation::reinit(cell, face)` was celled
- a cell loop with the capability to update the ghost values of a vector and to compress (so that all ghost faces/cells are updated)
- the capability to read/write mapping information and values (even for neighbors)

**Comment by peterrum** [comment]
While reviewing PR #8319, I was wondering in which tutorial we could present ECLs. The tutorial in this PR might be suitable since it uses explicit explicit time stepping and so we could merge simply both the advection and the inverse-mass matrix operator. What do you think @kronbichler? We probably need to extend ECLs for unstructured meshes so that it works for the cylinder, but that is either way planed...

**Comment by kronbichler** [comment]
I do plan to switch this tutorial program to that variant once we are settled with the infrastructure, indeed. But there is no hurry and right now there is independent value in having this version, too.

**Comment by peterrum** [comment]
@kronbichler While working on an improved version of step-67 and working on the simplification of the ECL support in hyper.deal (https://github.com/hyperdeal/hyperdeal/pull/30), I found that some common utility functions would be nice. Let's discuss next where to put these!

**Comment by drwells** [comment]
I believe ECL is now mostly done - if not lets reopen this.
