### ISSUE TITLE
bibtex references broken on homepage

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9222]
While looking into #8445, I realized that the references generated by doxygen from bibtex are broken in the developer version. On the other hand, they are fine on my system. I looked into the ones for step-63 [here](https://dealii.org/developer/doxygen/deal.II/step_63.html) - search e.g. for "KanschatNotesIterative". A quick [googling](https://stackoverflow.com/questions/11454727/doxygen-cite-producing-empty-bibliography) reveales that it might either be due to missing perl (that doxygen cannot find) or too old doxygen. That version seems new enough on the server, so I wonder if anyone knows about the former or some other solution.

Related to the topic is the format by which references are listed. At least on my system, bibtex sets references as numbers, e.g. `[17]` to refer to a certain paper/book (abbrv style of bibtex I believe). Since we are increasingly using these kind of references, including for example #8445 or #8319, this list will grow longer, making numbers ugly. Unless there is some mouse-over effect showing the authors/year that I cannot see locally, I would very much prefer the APA style or something similar, printing e.g. like `(Bangerth & Rannacher, 2003)`. I guess this should be possible to change via some option in `doc/doxygen/options.dox.in`, but I have not tried to look for it yet.

Any opinions?

**Comment by tjhei** [comment]
I agree that the style is not great. I tried setting ``LATEX_BIB_STYLE        = apalike`` but this doesn't have any effect (same with ``alpha``). Maybe this is only supported in latex not in html.

**Comment by tjhei** [comment]
this is hard-coded for html in doxygen: https://github.com/doxygen/doxygen/blob/master/templates/html/bib2xhtml.pl#L132

**Comment by kronbichler** [comment]
> this is hard-coded for html in doxygen

That's a pity; well, I guess we use that for now.

**Comment by tjhei** [comment]
@guidokanschat would you be able to check if doxygen produces any errors when generating the documentation on master?

**Comment by bangerth** [comment]
Anyone interested in opening a github issue with the doxygen folks for this?

**Comment by krishnakumarg1984** [comment]
It looks like the latest version of doxygen works on my machine for a local project.

**Comment by tjhei** [comment]
This is now fixed, thanks @guidokanschat !
