### ISSUE TITLE
[documentation] Lack of clarity on simplex() function in the GridGenerator namespace

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9226]
I am a bit confused by the documentation of the `simplex()` function in the `GridGenerator` namespace [here](https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#acea0cbcd68e52ce8113d1134b87de403).

* First, aren't the meshes handled by deal.ii all quadrilaterals in 2D?  I do not understand the triangles drawn in this function's documentation.

* Secondly, there is some really confusing wording for the function's description.  Improving this shall be very helpful to novice users of deal.II (I landed here following the "suggested steps" in the 'results' section of Step-3 tutorial). 

* Finally, there is some odd choice of words
>And I am not happy about the discrimination involved here.

Who is "I" here, and what "discrimination" are we talking about?

**Comment by masterleinad** [comment]
> * First, aren't the meshes handled by deal.ii all quadrilaterals in 2D?  I do not understand the triangles drawn in this function's documentation.

This function meshes a simplex by introducing additional vertices at the face centers, line centers, and the midpoint.

> * Secondly, there is some really confusing wording for the function's description.  Improving this shall be very helpful to novice users of deal.II (I landed here following the "suggested steps" in the 'results' section of Step-3 tutorial).

We are happy to take any suggestions for improvements as pull requests.

>  * Finally, there is some odd choice of words 
> > And I am not happy about the discrimination involved here.

This can likely just be deleted.

**Comment by krishnakumarg1984** [comment]
>This function meshes a simplex by introducing additional vertices at the face centers, line centers, and the midpoint.

I had forgotten my basics and had to look up `simplex` on [Wikipedia](https://en.wikipedia.org/wiki/Simplex)! According to Wikipedia,

>In geometry, a simplex (plural: simplexes or simplices) is a generalization of the notion of a triangle or tetrahedron to arbitrary dimensions.
For example,
    a 0-simplex is a point,
    a 1-simplex is a line segment,
    a 2-simplex is a triangle,
    a 3-simplex is a tetrahedron,
    a 4-simplex is a 5-cell.

Well, the 2-simplex  and 3-simplex cases seem to be in direct contrast with the [FAQ entry here](https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-useimplement-trianglestetrahedra-in-dealii) which says

>_Can I use/implement triangles/tetrahedra in deal.II?_
This is truly one of the most frequently asked questions. The short answer is: No, you can't. deal.II's basic data structures are too much tailored to quadrilaterals and hexahedra to make this trivially possible. .......

Also, the video lectures by Prof. Bangerth clearly convey the same idea that only quadrilaterals and hexahedra are the only supported ones (and that triangles and tetrahedra are not supported).

So, IMHO this certainly needs some clarification to resolve this apparent contradiction. With this new C++ function, do you now mean that triangles/tetrahedra are now supported?

>We are happy to take any suggestions for improvements as pull requests.

I do not feel that I have the technical competence currently to write about this function.

>This can likely just be deleted.

Raising a pull-request just for deleting this one sentence seems not worth it.  If the developers are able to comprehensively hash out this issue, and decide to make any holistic set of changes, this deletion can perhaps just be considered during the refactoring.

**Comment by blaisb** [comment]
> > This function meshes a simplex by introducing additional vertices at the face centers, line centers, and the midpoint.
> 
> I had forgotten my basics and had to look up a 'simplex' on [Wikipedia](https://en.wikipedia.org/wiki/Simplex)! According to Wikipedia,
> 
> > In geometry, a simplex (plural: simplexes or simplices) is a generalization of the notion of a triangle or tetrahedron to arbitrary dimensions. For example,
> > a 0-simplex is a point,
> > a 1-simplex is a line segment,
> > a 2-simplex is a triangle,
> > a 3-simplex is a tetrahedron,
> > a 4-simplex is a 5-cell.
> 
> Well, the 2-simplex and 3-simplex cases seem to be in direct contrast with the [FAQ entry here](https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#can-i-useimplement-trianglestetrahedra-in-dealii) which says
> 
> > **Can I use/implement triangles/tetrahedra in deal.II?**
> > This is truly one of the most frequently asked questions. The short answer is: No, you can't. deal.II's basic data structures are too much tailored to quadrilaterals and hexahedra to make this trivially possible. .......
> 
> Also, the video lectures by Prof. Bangerth clearly convey the same idea that only quadrilaterals and hexahedra are the only supported ones (and that triangles and tetrahedra are not supported).
> 
> So, IMHO we need some clarification to resolve this apparent contradiction. With this new C++ function, do you now mean that triangles/tetrahedra are now supported?

I think you are confusing the notion of grids and the supported elements. What the GridGenerator::simplex function do it create a simplex geometry (so in 2D a triangle, in 3D an hexahedron) and mesh it. To mesh a triangle using only quads, you can use three quads (which in turn require 7 nodes). A similar thing can be accomplished for a hexahedron.
What the simplex() GridGenerator does is what all GridGenerators do. That is generate a grid (or a mesh) of a geometrical entity (in this case this entity is a simplex). It does not imply anything about the type of geometrical elements that are supported within deal.II. 

I hope that this explanation makes things clearer.

**Comment by krishnakumarg1984** [comment]
Ah. Got it. Sorry, I did indeed get confused. This is very clear now.

**Comment by bangerth** [comment]
On 1/5/20 12:47 PM, Krishnakumar wrote:
> Raising a pull-request just for deleting this one sentence seems not worth it.

On the contrary! We do that all the time, and @masterleinad did it for this 
one sentence: #9233. In the future, feel free to do the same if you see 
anything that could use improvement -- we really appreciate all of these small 
fixes!

(I've updated the documentation a bit more in #9236.)

**Comment by krishnakumarg1984** [comment]
Thank you so much. This is very clear to me now. Hopefully, other users shall also benefit from this change.
