### ISSUE TITLE
[Tutorial step-3] Request for python equivalent of possible extension ("Using R and ggplot2 to generate PDFs with plots of the grid, the solution and convergence curves")

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9232]
In the `develop` version of step-3 tutorial, there is a suggested extension section titled "Using R and ggplot2 to generate PDFs with plots of the grid, the solution and convergence curves"

I am already having an overload of with having to deal with multiple programming/scripting languages (bash, python, C, C++, fortran, matlab, julia), and I do not want to complicate my life by having to learn the syntax of yet another language (R). I suspect there may be others who are in my similar situation.

This issue is just an appeal to some good soul requesting their goodwill/kindness to replicate the aforementioned documentation section in python and matplotlib :)

**Comment by bangerth** [comment]
I think that would be well received!

As with many other possible addition, we are a volunteer project that lives off contributions made by the community. Would you like to give your suggestion a try? I suspect that unless someone steps forward to do what you suggest, it will take a long time until this issue is closed :-(

**Comment by krishnakumarg1984** [comment]
Dear Prof Bangerth,

While I would love to do this, currently I am short of time. In my post-doc role here, I have been trying to get upto speed with C++ and deal.II at the same time, and have had to watch your videos, do a coursera MOOC, and go through these tutorials multiple times, while juggling time with the job.  I absolutely need to develop the software for my project sooner than later.

Would it be okay to leave this issue open, and perhaps if no one else has done it in the next couple of months, I shall revisit it, and write up the python-based workflow?

**Comment by bangerth** [comment]
On 1/7/20 8:09 AM, Krishnakumar wrote:
> While I would love to do this, currently I am short of time. In my post-doc 
> role here, I have been trying to get upto speed with C++ and deal.II at the 
> same time, and have had to watch your videos, do a coursera MOOC, and go 
> through these tutorials multiple times, while juggling time with the job. I 
> absolutely need to develop the software for my project sooner than later.

I understand. But you probably also understand that that is true for all of 
the principal developers as well :-)


> Would it be okay to leave this issue open, and perhaps if no one else has done 
> it in the next couple of months, I shall revisit it, and write up the 
> python-based workflow?

Sure, we can leave it open. We appreciate all contributions, now or later!

**Comment by jpthiele** [comment]
Fixed by the linked and merged PR, right?
