### ISSUE TITLE
Test mpi/hp_step_4 fails because of missing Trilinos component

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9252]
This test fails for me with the error
```
7614: --------------------------------------------------------
7614: An error occurred in line <829> of file </home/fac/f/bangerth/p/deal.II/1/dealii/source/lac/trilinos_solver.cc> in function
7614:     void dealii::TrilinosWrappers::SolverDirect::do_solve()
7614: The violated condition was: 
7614:     Factory.Query(additional_data.solver_type.c_str())
7614: Additional information: 
7614:     You tried to select the solver type <Amesos_Mumps> but this solver is not supported by Trilinos either because it does not exist, or because Trilinos was not configured for its use.
7614: --------------------------------------------------------
```

I don't know what the appropriate `with_...=true` component to the output file name should be in this case, but we ought to predicate running the test on the existence of Amesos_Mumps.

@marcfehling -- FYI.

**Comment by marcfehling** [comment]
This test was introduced in PR #9036. @BenBrands -- FYI.

I don't know either, but I'll have a look if there are similar tests requiring Mumps.

**Comment by marcfehling** [comment]
There are similar flags `with_trilinos_with_tpetra`, `with_trilinos_with_sacado`, and `with_trilinos_with_zoltan` in the `tests/` folder to check whether Trilinos has been configured with these features.

Not sure yet whether there is a corresponding flag `with_trilinos_with_amesos`. I'll try it out.

**Comment by marcfehling** [comment]
Does https://github.com/marcfehling/dealii/commit/c2cead09b3b9f978fc82cc034136870d6f375075 resolve the issue?
