### ISSUE TITLE
URL links on the news page of dealii.org website do not work

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9279]
Just came across a few broken links on the [news](https://dealii.org/news) webpage 

In particular, quite a few links on sentences ending with the text _on this page_ are broken.  These are mainly towards the bottom of the news page. I did not attempt to access every link before reporting this issue.

- Is there some automated tool available for detecting broken weblinks? This might make testing easier.  
- Secondly, and related to above, does deal. have tests set up for its website (I mean, I know that C++ code testing is quite extensive, but unsure about whether we are currently checking if the html code of the site is W3C compliant, accessibility requirements etc.)

edit (masterleinad): fix link

**Comment by bangerth** [comment]
It doesn't greatly surprise me that we have dead links. But does it matter greatly if we have dead links in old news entries? Is anyone going to click on news entries from ten years ago? What are the newest ones that you found that don't work?

We have a script that checks internal links between one part of the documentation and another (i.e., between things that live in the github repo), but nothing that alerts us if an external link has died. The page you mention also lives outside the github repo, and so no checking at all is done on it. That's certainly something that could be improved.

**Comment by krishnakumarg1984** [comment]
It is not just the links to _old_ news items that are broken.

The latest newsletter #105 (https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dealii/xPCngMHpeG8) says 

>A list of all major changes since the last release can be found at [this website](https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_5_0.html).

which leads to an unreachable 404 error, when clicked upon.

It looks like it might be worthwhile to investigate in setting up some automated testing for the validity of all www URLs.

**Comment by masterleinad** [comment]
> It is not just the links to **old** news items that are broken. The latest newsletter [#105](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dealii/xPCngMHpeG8) says _"A list of all major changes since the last release can be found at [this website](https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_5_0.html)."_, which leads to an unreachable 404 error when clicked upon.

@gassmoeller You might want to change that link to  https://www.dealii.org/developer/doxygen/deal.II/recent_changes.html.

**Comment by masterleinad** [comment]
> t looks like it might be worthwhile to investigate in setting up some automated testing/CI at each release-tag for validating all www URLs contained in the project's github repo. For example, I wonder if [pa11y](https://github.com/pa11y/pa11y) might be a good solution to both validate the accessibility (and hence, the existence) of external URLs?

Well, except for the documentation the URLs don't really change with pull requests. But we could add some check to our release task list if someone volunteers to set up a sensible script. Of course, we are happy to just fix single links as well.

**Comment by gassmoeller** [comment]
Thanks for the report, I fixed the newsletter it should now always point to the recent changes.
