### ISSUE TITLE
[documentation] Step-6 might be having some potentially confusing wording on the degree of gauss formula to use 

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9292]
I'd like to raise this github issue to trigger a quick discussion surrounding some wording in the `develop` branch of Step-6 documentation.

>There are two __code changes__ compared to step-5:
>First, we have to use a higher-order quadrature formula to account for the higher polynomial degree in the finite element shape functions. This is easy to __change__: the constructor of the QGauss class takes the number of quadrature points in each space direction. Previously, we had two points for bilinear elements. Now we should use three points for biquadratic elements.

The relevant line of code is the following:

`const QGauss<dim> quadrature_formula(fe.degree + 1);`

Strictly speaking, there are __no__ code changes for this aspect when compared to all the previous tutorials.  The code has been written in such a way that the Gauss quadrature formula correctly becomes a 3-point formula in this case, compared to 2-point formula in the previous tutorials.

In consideration of this, do the developers here think that the documentation need to be updated suitably? If so, I am not very clear how to deftly phrase the words to reflect this subtlety, and happy to take suggestions.

**Comment by bangerth** [comment]
step-5 used to used a fixed number of quadrature points, but this was changed a while back. The section you quote can just be removed.
