### ISSUE TITLE
Issue a sane error message when crashing for three-dimensional svg write attempts

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9299]
According to the `write_svg` documentation,

>    This function is currently only implemented for two-dimensional grids in two space dimensions

When I attempted to run this to visualize a 3D mesh, the program crashes, however, with a cryptic error message from the linker!

>Undefined symbols for architecture x86_64:
  "void dealii::GridOut::write_svg<3, 3>(dealii::Triangulation<3, 3> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const", referenced from:
      first_grid() in step-1.cc.o
ld: symbol(s) not found for architecture x86_64

Since the linker error message wasn't exactly pinpointing on the spot, It took me a small bit of digging to figure out why `write_eps` worked while `write_svg` didn't. I mean, my debugging hat  didn't immeditaly think in this direction as I have visualised 3D svg output in a browser before coming to deal.II

I think that, following the exact idea on good programmign practices proposed in Prof. Bangerth's lecture, it may be wise to use the `Assert` macro with [ExcNotImplemented](https://dealii.org/developer/doxygen/deal.II/group__Exceptions.html#ga7b52b286796c23ef9ff178faf7a4b68f) or [ExcImpossibleInDim](https://dealii.org/developer/doxygen/deal.II/group__Exceptions.html#ga7b52b286796c23ef9ff178faf7a4b68f)  for returning a better error message.
______________________________

Additionally, I think it is a bit of a restriction that `ExcImpossibleInDim` can only take in one argument. In this case, we  know that only `dim=2` is a valid argument, and that `1` and `3` should produce errors. It would be better if this exception was made flexible to accept multiple arguments.

**Comment by bangerth** [comment]
This is a bug. I fixed it in #9328.
