### ISSUE TITLE
In all documentation pages, consider replacing l_2 with its LaTeX equivalent notation 

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9302]
For example, in the documentation of the `distance` function [here](https://dealii.org/developer/doxygen/deal.II/classPoint.html#a3df8e6ab311dab9337c8d7b039c7b815), it says 

>Return the Euclidean distance of this point to the point p, i.e. the l_2 norm of the difference between the vectors representing the two points.

This would look much more readable if a mathjax-based LaTeX rendering is used. Can we replace all intances of `l_2` in the project with `$L_2$`?

**Comment by bangerth** [comment]
Yes, go ahead. But you want to use $l_2$, the norm on the finite dimensional space of vectors. $L_2$ is the norm on the function space.

**Comment by krishnakumarg1984** [comment]
Surprisingly, found only one instance of this usage in the whole project!. Fixes through PR #9303
