### ISSUE TITLE
In Step-4 tutorial, provide a better explanation of the symbols used liberally for function spaces 

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9305]
For practising engineers, or for anyone who is not closely working with real analysis on a regular basis (but still using the FE method and deal.II in their research), it is a bit off-putting to have mathematical symbols of function spaces used liberally without even a basic expansion in words.

For example, in step-6 documentation,

>That means, that the solution is at least still in the space W1,∞. On the other hand, we know that in the most extreme cases – i.e., where the domain has reentrant corners, the right hand side only satisfies f∈H−1, or the coefficient a is only in L∞ – all we can expect is that u∈H1, a much larger space than W1,∞. It is not very difficult to create cases where the solution is in a space H1+s where we can get s to become as small as we want. Such cases are often used to test adaptive finite element methods because the mesh will have to resolve the singularity that causes the solution to not be in W1,∞ any more.

That paragraph is completely lost to me, even though I am sure my research in applied engineering can still benefit from its understanding. Naturally, one can't expect a whole load of explanation in a tutorial of a software package, but at least a basic expansion of terms should be helpful. 

Something along the lines of `[ Sobolev Space, $H^1_0 (\omega) ]` (wikipedia link) shall be immensely valuable to the reader unfamiliar with these terms, while it won't detract the experts too much.

**Comment by bangerth** [comment]
I've added a few links to the discussion in step-6, but I would like to point out that the paragraph you quote is from the discussion of possibilities for extensions of step-6. I think it is clear to everyone that that is not mandatory material to understand. I don't think that we ought to provide an introductory course in functional analysis in the tutorials.

If you have places in the discussion for step-4 (which you mention in the title of the issue), we can address those separately.

**Comment by krishnakumarg1984** [comment]
Thank you so much. This is so helpful.
