### ISSUE TITLE
[Documentation] Bibtex entries/hyperlinks not rendered in doxygen (steps 1, 6, 13, 18 etc.)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9306]
I am a bit unsure about how `bibtex` integrates with `doxygen` in general. 

What is the purpose of using the `@cite` markup for the documentation rendered in the browser? 
 - Is it intended to format the citations as per some style (MLA, Chicago, APA, IEEE)? 
 - Is it intended to provide a hyperlink to some open-access versions of these papers?
 - a combination of both?

Whatever be the case, the current `master` branch rendering of steps 1, 6, 13 and 18 do not seem to render the citations in any particularly useful way. For example, in Step-6, we have
>The typical example one uses for this is called the Kellogg problem (referring to [Kel74]), which in the ......

**Comment by tjhei** [comment]
yes, this broke a few days ago: #9222
(closing this issue)
