### ISSUE TITLE
[Step-6] Out-of-date documentation about class destructor?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9307]
In the `master` branch of the documentation, we have the following sentence:

>In addition, we have added a destructor to the class for reasons that will become clear when we discuss its implementation.

However, there is no destructor in the code, and no explanation about such a destructor is also given.  What is happening here? I am presuming the documentation went out of date somehow?

**Comment by bangerth** [comment]
Where is this?

**Comment by krishnakumarg1984** [comment]
In step-6 documentation

**Comment by bangerth** [comment]
On 1/13/20 2:07 PM, Krishnakumar Gopalakrishnan wrote:
> In step-6 documentation

Ah, sorry -- I missed that it's in the title already. Yes, the sentence is a 
left-over from earlier. Feel free to remove it.
