### ISSUE TITLE
Tutorial dot diagram/dependency DAG is missing input dependencies for Step-19

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9308]
In the latest [`master`](https://dealii.org/developer/doxygen/deal.II/Tutorial.html) version of the tutorial, the dot diagram showing dependencies of various steps is missing an input dependency for Step-19. 

This conveys the false idea that one could start using deal.II by just looking from step-19 onward.  This is clearly not the case, since Step-19 makes use of so many concepts already covered in the preceding tutorials.

**Comment by bangerth** [comment]
You mean here: https://dealii.org/developer/doxygen/deal.II/Tutorial.html#graph ?

19 is the orange box in the middle of nowhere somewhere in the center of the image. It is true that 19 doesn't depend on much at all -- it's a stand-alone. See also #2046.

**Comment by krishnakumarg1984** [comment]
Thank you. This is quite clear now. I shall close this issue.
