### ISSUE TITLE
Outdated clang-format binary forced upon for indendation in PRs

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9314]
According to the contribution guidelines in the project's [Wiki](https://github.com/dealii/dealii/wiki/Indentation), one needs to simply run 

`./contrib/utilities/indent`

However, this raise an error

> ***   This indent script requires clang-format version 6.0,
> ***   but version 9.0 was found instead.

I believe that `clang-format` is backwards compatible. If the project would like to stick to v6.0, this can simply be specified in the .`clang-format file`.

Forcing a committer to install an outdated-binary isn't really helpful and can discourage them. It would be great if the indent script removed the version check on the actual binary.

**Comment by Rombur** [comment]
> I believe that clang-format is backwards compatible. 

It is not. They are slight differences depending on the version you are using.

**Comment by drwells** [comment]
The differences are quite minor but they do exist (e.g., they fixed the opening bracket of lambda functions, some issues with indenting around macros (like our cuda macro)) and a few other things.

One workaround is to comment out the version check and then only commit indentation changes on code that you actually changed (I do this regularly) since the incompatibilities are relatively rare. I don't recommend this workaround since it requires one know the differences in indentation rules between different versions of clang-format.

**Comment by drwells** [comment]
Even if we changed our version of clang-format today we would be out of date again in a few more months when the new version comes out. Hence lets close this issue for now.

**Comment by krishnakumarg1984** [comment]
@drwells I think there might be a misunderstanding here.  

The executable program `clang-check` can be made to obey an earlier version of `.clang-format` file as long as this compatibility version is specified in that file. 

My only objection is to the checking of the executable's version. If one always has modern toolchain on the machine, forcing to go back to an earlier version of the __executable__ is not a great idea.  I am talking about the check on the __executable__, not on the format specification itself.

**Comment by masterleinad** [comment]
> The executable program `clang-check` can be made to obey an earlier version of `.clang-format` file as long as this compatibility version is specified in that file.

Can you demonstrate this?

**Comment by krishnakumarg1984** [comment]
Alright. I give in. It looks like I will have to use clang-format 6.0.0. Ok, I shall do that. No problems.
