### ISSUE TITLE
Specifying MPI libraries

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#9316]
```
-- Found PETSC
-- Could not find a sufficient PETSC installation: PETSC is compiled against a different MPI library than the one deal.II picked up.
-- DEAL_II_WITH_PETSC has unmet external dependencies.
CMake Error at cmake/configure/configure_3_petsc.cmake:141 (MESSAGE):


  Could not find the petsc library!

  Could not find a sufficient PETSC installation:

  PETSC has to be compiled against the same MPI library as deal.II but the
  link line of PETSC contains:

    /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release_mt/libmpi.so

  which is not listed in MPI_LIBRARIES:

    MPI_LIBRARIES = "/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpicxx.so /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpifort.so /opt/int
el/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release/libmpi.so /lib64/librt.so /lib64/libpthread.so /lib64/libdl.so"
```

See the difference between `release` and `release_mt`? I think PETSc is using the right library (in case you want to THREAD_MULTIPLE your MPI), so how can I tell Deal where to find the MPI libraries?

**Comment by VictorEijkhout** [comment]
Attempt to "-D MPI_LIBRARIES" leads to an error in the lapack detection, before it even gets to petsc.
[CMakeError.log](https://github.com/dealii/dealii/files/4060344/CMakeError.log)
[CMakeOutput.log](https://github.com/dealii/dealii/files/4060345/CMakeOutput.log)

**Comment by masterleinad** [comment]
What is the actual output when running `cmake`?

**Comment by VictorEijkhout** [comment]
```
-- Could NOT find LAPACK
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
--
-- Include /admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake
-- Could not find a sufficient MPI version: Your MPI implementation must define MPI_SEEK_SET.
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:57 (MESSAGE):


  Could not find any suitable mpi library!

  Your MPI implementation must define MPI_SEEK_SET.



  Please ensure that an mpi library is installed on your computer

  and set CMAKE_CXX_COMPILER to the appropriate mpi wrappers:

      $ CXX=".../mpicxx" cmake <...>
      $ cmake -DCMAKE_CXX_COMPILER=".../mpicxx" <...>

  Or with additional C and Fortran wrappers (recommended!):

      $ CC=".../mpicc" CXX=".../mpicxx" F90=".../mpif90" cmake <...>
      $ cmake -DCMAKE_C_COMPILER=".../mpicc"\
              -DCMAKE_CXX_COMPILER=".../mpicxx"\
              -DCMAKE_Fortran_COMPILER=".../mpif90"\
              <...>

Call Stack (most recent call first):
  /tmp/dealii-build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_MPI_ERROR_MESSAGE)
  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:267 (EVALUATE_EXPRESSION)
  cmake/configure/configure_1_mpi.cmake:74 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/tmp/dealii-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/dealii-build/CMakeFiles/CMakeError.log".
```

You mean to tell me that cmake does not log all its information in its log files?

**Comment by masterleinad** [comment]
It's normally much more usefull to look at the output of `cmake` first before considering `CMakeOutput.log` and `CMakeError.log` since there is a lot of information stored in the latter two files.

For some reason, the `cmake` output tells that there is a problem with `MPI_SEEK_SET` while your `CMakeOutput.log` shows
>  MPI_HAVE_MPI_SEEK_SET succeeded with the following output:

Can you confirm that they both refer to the same configuration?

**Comment by VictorEijkhout** [comment]
Ok, too much experimenting. This is from one run. The log files have nothing about seek'ing

```
root@build-BLDCHROOT:SPECS # !2401
grep -i seek deal-9_gcc91_impi_19_5.log
-rw-rw-r-- root/root      5457 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/iostreams/seek.hpp
-rw-rw-r-- root/root      2196 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/spirit/home/x3/directive/seek.hpp
-rw-rw-r-- root/root      2241 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/spirit/home/x3/extensions/seek.hpp
-rw-rw-r-- root/root      4220 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/spirit/repository/home/qi/directive/seek.hpp
-rw-rw-r-- root/root       695 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/spirit/repository/home/support/seek.hpp
-rw-rw-r-- root/root       560 2019-05-27 02:07 dealii-9.1.1/bundled/boost-1.62.0/include/boost/spirit/repository/include/qi_seek.hpp
-- Could not find a sufficient MPI version: Your MPI implementation must define MPI_SEEK_SET.
  Your MPI implementation must define MPI_SEEK_SET.
root@build-BLDCHROOT:SPECS # !2402
grep seek /tmp/dealii-build/CMakeFiles/CMake*log
root@build-BLDCHROOT:SPECS #
```

Error from cmake:

```
-- Include /admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake
-- Could not find a sufficient MPI version: Your MPI implementation must define MPI_SEEK_SET.
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:57 (MESSAGE):


  Could not find any suitable mpi library!

  Your MPI implementation must define MPI_SEEK_SET.



  Please ensure that an mpi library is installed on your computer

  and set CMAKE_CXX_COMPILER to the appropriate mpi wrappers:

      $ CXX=".../mpicxx" cmake <...>
      $ cmake -DCMAKE_CXX_COMPILER=".../mpicxx" <...>

  Or with additional C and Fortran wrappers (recommended!):

      $ CC=".../mpicc" CXX=".../mpicxx" F90=".../mpif90" cmake <...>
      $ cmake -DCMAKE_C_COMPILER=".../mpicc"\
              -DCMAKE_CXX_COMPILER=".../mpicxx"\
              -DCMAKE_Fortran_COMPILER=".../mpif90"\
              <...>

Call Stack (most recent call first):
  /tmp/dealii-build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_MPI_ERROR_MESSAGE)
  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:267 (EVALUATE_EXPRESSION)
  cmake/configure/configure_1_mpi.cmake:74 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/tmp/dealii-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/dealii-build/CMakeFiles/CMakeError.log".
```
[CMakeError.log](https://github.com/dealii/dealii/files/4061715/CMakeError.log)
[CMakeOutput.log](https://github.com/dealii/dealii/files/4061716/CMakeOutput.log)

**Comment by VictorEijkhout** [comment]
Is cmake debuggable? I can not even figure out where your configuration looks for that MPI_SEEK_SET.

```
root@build-BLDCHROOT:SPECS # grep -i mpi_seek /admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/*.cmake
/admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake:    IF(NOT MPI_HAVE_MPI_SEEK_SET)
/admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake:        "Your MPI implementation must define MPI_SEEK_SET.")
/admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake:        "Your MPI implementation must define MPI_SEEK_SET.\n")
root@build-BLDCHROOT:SPECS #
```

**Comment by masterleinad** [comment]
The check is in `cmake/modules/FindMPI.cmake` and fairly simple. Now, I am surprised to not find anything about `MPI_SEEK_SET` in `CMakeError.log` or `CMakeOutput.log`. Did you start from a clean build directory?

**Comment by VictorEijkhout** [comment]
Guys, I'm still stuck. 

Petsc builds with `${TACC_IMPI_DIR}/intel64/lib/release_mt/libmpi.so`

Deal want to pick up `${TACC_IMPI_DIR}/intel64/lib/release/libmpi.so`

and then complains about the petsc library. My attempt to specify MPI libraries explicit to deal are failing.

I sort of feel that petsc is picking up the right libraries: the `_mt` is required for THREAD_MULTIPLE mode.

**Comment by masterleinad** [comment]
Again, how are you invoking `cmake`? What happens if you do
```
cmake -D MPI_LIBRARIES=${TACC_IMPI_DIR}/intel64/lib/release_mt/libmpi.so .
```
?

**Comment by VictorEijkhout** [comment]
On , 2020Jan27, at 09:41, Daniel Arndt <notifications@github.com<mailto:notifications@github.com>> wrote:


Again, how are you invoking cmake? What happens if you do

cmake -D MPI_LIBRARIES=${TACC_IMPI_DIR}/intel64/lib/release_mt/libmpi.so .


Cmake line:

+ cmake -VV -DCMAKE_INSTALL_PREFIX=/home1/apps/intel19/impi19_0/dealii/9.1.1 -DDEAL_II_WITH_CXX11=ON -DDEAL_II_WITH_CXX17=OFF '-DDEAL_II_CXX_FLAGS_DEBUG=-g -march=native -I/opt/intel/compilers
_and_libraries_2019.5.281/linux/tbb/include -O0' '-DDEAL_II_CXX_FLAGS_RELEASE=-g -march=native -I/opt/intel/compilers_and_libraries_2019.5.281/linux/tbb/include -O2' -DDEAL_II_COMPONENT_MESH_C
ONVERTER=ON -DDEAL_II_WITH_MPI=ON -D MPI_LIBRARIES=/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release_mt/libmpi.so -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc
 -DMPICH_IGNORE_CXX_SEEK=ON -DBOOST_DIR=/opt/apps/intel19/python2_7/boost/1.69 -DDEAL_II_WITH_GSL=ON -DGSL_INCLUDE_DIR=/opt/apps/intel19/gsl/2.5/include -DGSL_LIBRARY_DIR=/opt/apps/intel19/gsl
/2.5/lib '-DGSL_LIBRARY=/opt/apps/intel19/gsl/2.5/lib/libgsl.so;/opt/apps/intel19/gsl/2.5/lib/libgslcblas.so' -DHDF5_DIR=/opt/apps/intel19/impi19_0/phdf5/1.10.4/x86_64 -DDEAL_II_WITH_METIS=ON
-DMETIS_DIR=/opt/apps/intel19/metis/5.1.0 -DMUMPS_DIR= -DDEAL_II_WITH_PETSC=ON -DPETSC_DIR=/home1/apps/intel19/impi19_0/petsc/3.12/ -DPETSC_ARCH=clx -DDEAL_II_WITH_SLEPC=ON -DSLEPC_DIR=/home1/
apps/intel19/impi19_0/slepc/3.12 -DDEAL_II_WITH_P4EST=ON -DP4EST_DIR= -DDEAL_II_WITH_TRILINOS=ON -DTRILINOS_DIR=/home1/apps/intel19/impi19_0/trilinos/12.14.1/ /admin/build/admin/rpms/frontera/
BUILD/dealii-9.1.1/dealii-9.1.1 /admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1

Error:

-- Performing Test dl_LIBRARY - Success
--   LAPACK_LIBRARIES: *** Required variable "_lapack_libraries" empty ***
--   LAPACK_LINKER_FLAGS:
--   LAPACK_INCLUDE_DIRS:
--   LAPACK_USER_INCLUDE_DIRS:
-- Could NOT find LAPACK
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
--
-- Include /admin/build/admin/rpms/frontera/BUILD/dealii-9.1.1/cmake/configure/configure_1_mpi.cmake
-- Could not find a sufficient MPI version: Your MPI implementation must define MPI_SEEK_SET.
-- DEAL_II_WITH_MPI has unmet external dependencies.
CMake Error at cmake/configure/configure_1_mpi.cmake:57 (MESSAGE):


  Could not find any suitable mpi library!

  Your MPI implementation must define MPI_SEEK_SET.



  Please ensure that an mpi library is installed on your computer



Cmake log junk attached.

**Comment by tjhei** [comment]
Hi Victor,

it looks like you are trying to install deal.II on Frontera. :-)
I am running on successfully on Frontera with the instructions at https://github.com/geodynamics/aspect/wiki/Installation-on-Frontera 
Note: I did not include PETSc there, but installing PETSc using candi (add "once:petsc" to the candi.sh line in step 1) works correctly. You will need to set DEAL_II_WITH_64BIT_INDICES=OFF.

I am not sure how the PETSc package is configured on Frontera, but I did not need any magic cmake arguments to make things work.
My deal.II (9.1.1 or master) cmake line is:
```
CC=mpicc CXX=mpicxx cmake \
      -D DEAL_II_WITH_MPI=ON \
      -D DEAL_II_CXX_FLAGS="-march=native" \
      -D DEAL_II_WITH_CXX17=OFF \
      -D DEAL_II_COMPONENT_EXAMPLES=OFF \
      -D CMAKE_INSTALL_PREFIX=`pwd`/install  \
      ../dealii
```
(PETSC_DIR, P4EST_DIR, etc. is picked up automatically).

**Comment by VictorEijkhout** [comment]
Your instructions work, but as you say, you're not including petsc. Configure gives the following message:

```
configure.log:-- Could not find a sufficient PETSC installation: PETSC is compiled against a different MPI library than the one deal.II picked up.
```

and that's what started this whole thread. Can you make an installation that uses the pre-installed petsc of the system? `module load petsc/3.12` ?

**Comment by tamiko** [comment]
@VictorEijkhout The above check (that prevents PETSc from being picked up) safeguards against a very serious problem - the moment you mix two MPI installations everything goes south. This might have triggered this nasty MPI configure error you reported first.

Regarding PETSc: I take it that you tried to use the preinstalled PETSc version (via `module load petsc/3.12`)? If yes, you have to ensure that you load the right MPI module as well (the one used by PETSc).

If this is not possible, you have to compile your own PETSc version first (this is what @tjhei suggested).

**Comment by VictorEijkhout** [comment]
I understand the problem. Hence my question: how can I tell deal what MPI_LIBRARIES to use.

Yes, I have the right MPI loaded. The module system basically does not allow you to load the wrong MPI. Btw the matter of "the right MPI" is subtle. Please read the above: it's about whether the release or release_mt version (out of the same distribution) is being used.

And the pre-installed PETSc was built by me.....

Can you try to make an installation that correctly uses the system PETSc? Maybe take a look and see which MPI library is being used? Is that release or release_mt ?

**Comment by VictorEijkhout** [comment]
Ok, I just built petsc and it uses a different MPI than the "system" one. Beats me where the difference lies. But for now I'm going to try to rebuild the system petsc to use the non-mt MPI since it seems impossible to change deal's mind about MPI libraries. Let's hope petsc is easier to customize.

**Comment by tjhei** [comment]
> Can you try to make an installation that correctly uses the system PETSc? 

I generally don't use system installed libraries for dependencies like PETSc, because I don't trust the settings and configurations used (and also require certain dependencies/settings). I have run into issues like you describe often, that I don't have when installing PETSc myself.
I know this doesn't answer your question, sorry. I can try to use the system package at some point, but I also don't know how to specify the library. Can you tell me how you configured PETSc?

> Maybe take a look and see which MPI library is being used? Is that release or release_mt ?

```
theister@login2 /work/02578/theister/frontera/env7/deal-test-32/lib $ ldd libdeal_II.g.so | grep libmpi
        libmpi.so.12 => /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00002b5e343b6000)
        libmpifort.so.12 => /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpifort.so.12 (0x00002b5e364ad000)
        libmpicxx.so.12 => /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpicxx.so.12 (0x00002b5e3f0af000)
theister@login2 /work/02578/theister/frontera/env7/deal-test-32/lib $ ldd libdeal_II.g.so | grep petsc
        libpetsc.so.3.11 => /work/02578/theister/frontera/env7/candi/petsc-3.11.3/lib/libpetsc.so.3.11 (0x00002b125a704000)
theister@login2 /work/02578/theister/frontera/env7/deal-test-32/lib $ ldd /work/02578/theister/frontera/env7/candi/petsc-3.11.3/lib/libpetsc.so.3.11 | grep libmpi
        libmpifort.so.12 => /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpifort.so.12 (0x00002ab4a8697000)
        libmpi.so.12 => /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00002ab4a8a55000)
```
so ``/release/libmpi.so`` for both.

**Comment by tjhei** [comment]
It seems like you should be able to select your mpi library as described in https://software.intel.com/en-us/mpi-developer-guide-linux-selecting-library-configuration before configuring deal.II and PETSc.

**Comment by VictorEijkhout** [comment]
I think I solved this one by rebuilding petsc with the mpi libraries that deal wants.
