### ISSUE TITLE
Improve the example codes in the documentation module/glossary entry for boundary indicator id and manifold_id

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9319]
Currently, we have rather convoluted code explaining the setting of boundary indicator id in the [documentation](https://dealii.org/developer/doxygen/deal.II/DEALGlossary.html#GlossBoundaryIndicator).

This is related to #9227 

I will provide a PR to simplify this code and close this issue.

**Comment by software2Daniel** [comment]
go to this article to know which are the races that fit your tastes
Enter now

https://sites.google.com/aprendizajesignificativo.org/top5-caballos/p%C3%A1gina-principal

**Comment by rumajo** [comment]
Looks like the wrong issue was referenced in #9379 which meant this didn't get closed automatically when the PR was merged. Looks like it can be closed now?

**Comment by krishnakumarg1984** [comment]
Sorry, is this shortened code now in R 9.2?

**Comment by masterleinad** [comment]
Yes, #9379 is part of 9.2.0.

**Comment by krishnakumarg1984** [comment]
Ah. I see. That's nice to know! Quite happy about that. Thanks for your quick response.
