### ISSUE TITLE
Incorrect pattern with one version of make_flux_sparsity_pattern

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#9322]
There are several version of the function `make_flux_sparsity_pattern`. At least one of them appears to produce an incorrect pattern.

If I create a 1D-triangulation of 3 elements by refining 1 out of 2 elements:
```
const unsigned int n_elements = 3;
GridGenerator::subdivided_hyper_cube(triangulation, n_elements - 1);
auto cell = triangulation.begin_active();
cell++;
cell->set_refine_flag();
triangulation.execute_coarsening_and_refinement();
```
and then distribute `FE_Q<1>(1)` and create a pattern with the function

```
make_flux_sparsity_pattern(const DoFHandlerType &dof_handler,
                             SparsityPatternType & sparsity_pattern);
```

I get the correct sparsity pattern `[i, j0, j1,...]`:

[0,0,1,2]
[1,0,1,2,3]
[2,0,1,2,3]
[3,1,2,3]

but if I call the function

```
void
make_flux_sparsity_pattern(const DoFHandlerType &           dof,
                           SparsityPatternType &            sparsity,
                           const AffineConstraints<number> &constraints,
                           const bool                keep_constrained_dofs,
                           const Table<2, Coupling> &couplings,
                           const Table<2, Coupling> &face_couplings,
                           const types::subdomain_id subdomain_id);
```

with arguments that should be equivalent, I get the following pattern:

[0,0,1]
[1,0,1,2,3]
[2,1,2,3]
[3,1,2,3]

where some flux-couplings are missing.

This doesn't occur if I create an equivalent 3-element triangulation where all
cells are on the same level, see attached example.

[example.zip](https://github.com/dealii/dealii/files/4060515/example.zip)

**Comment by bangerth** [comment]
The first output seems correct to me. What are the arguments you are passing to the second function? (I know I could look it up in the .zip file, but it might be easier to just paste the relevant code here).

**Comment by simonsticko** [comment]
> What are the arguments you are passing to the second function?

```
  AffineConstraints<double> constraints;
  constraints.close();

  const bool keep_constrained_dofs = true;

  // Set all couplings to be connected.
  const unsigned int           n_components = 1;
  Table<2, DoFTools::Coupling> couplings(n_components, n_components);
  couplings[0][0] = DoFTools::Coupling::always;
  Table<2, DoFTools::Coupling> face_couplings(n_components, n_components);
  face_couplings[0][0] = DoFTools::Coupling::always;

  const types::subdomain_id subdomain_id = 0;

  DynamicSparsityPattern dynamic_pattern(dof_handler.n_dofs());

  DoFTools::make_flux_sparsity_pattern(dof_handler,
                                       dynamic_pattern,
                                       constraints,
                                       keep_constrained_dofs,
                                       couplings,
                                       face_couplings,
                                       subdomain_id);
```

**Comment by simonsticko** [comment]
As far as I can tell, the two functions only give different results in 1D.

I suspect the problem with the second function is this piece (from line 1177 in dof_tools_sparsity.cc).
```c++
typename DoFHandlerType::face_iterator cell_face =
  cell->face(face);

...

if (neighbor->has_children())              
  {                                        
    for (unsigned int sub_nr = 0;          
         sub_nr != cell_face->n_children();
         ++sub_nr)                         
      {                                    
          ... [Pattern entries added here]
   } 
else
   {          
         ... [Pattern entries added here]
   }
```
The neighbor has children, but in 1D the number of children of a face is always zero so no entries are added to the pattern.

The first function has a special treatment of the 1D case (line 597 in dof_tools_sparsity.cc).
```c++
if (DoFHandlerType::dimension == 1)                 
  while (neighbor->has_children())                  
    neighbor = neighbor->child(face == 0 ? 1 : 0);  
                                                    
if (neighbor->has_children())                       
  {                                                 
    for (unsigned int sub_nr = 0;                   
         sub_nr != cell_face->number_of_children(); 
         ++sub_nr)                                  
      {                                    
          ... [Pattern entries added here]
   } 
else
   {          
         ... [Pattern entries added here]
   } 
```
This results in the second if-statement always being skipped in 1D. 

I'll try to submit a patch for this.

**Comment by simonsticko** [comment]
The version of `make_flux_sparsity_pattern` with the signature that has this bug has a specialization for `hp::DoFHandler`. I suspect that the bug is present also in the specialization, but the hp version is not instantiated in 1D (line 215 in dof_tools_sparsity.inst.in).

Does anyone know the reason for this? :thinking:
