### ISSUE TITLE
GridIn class is missing functions to import lagrit file format

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9323]
I am a complete newbie in meshes and mesh-generating software. I am merely reporting my findings based on the documentation in tutorials. 

Step-49 tutorial says:
>Meshes can be generated from different tools like gmsh, lagrit and cubit. See the documentation of GridIn for more information. 

However, [GridIn](https://dealii.org/developer/doxygen/deal.II/classGridIn.html) does not seem to provide any method/function to import meshes produced by `lagrit`?

**Comment by bangerth** [comment]
What formats can lagrit write? I bet that it can export meshes in one of the supported file formats.

**Comment by krishnakumarg1984** [comment]
Apologies. No idea whatsoever:)  I just merely reported the finding that there is no `read_lagrit` function that corresponds to the claim in Step-49 about ability to read `lagrit` meshes.  Perhaps we may consider removing all mentions of `lagrit` in the project.

**Comment by drwells** [comment]
Lagrit can export UCD (it explicitly supports "AVS UCD" in its own documentation): therefore we support lagrit and the documentation is fine.
