### ISSUE TITLE
[Step-49] Consider including Gmsh's C++ API features (in addition to or replacing .geo file)?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9325]
From Step-49 tutorial,

>In Gmsh, a mesh is described in a text based .geo file, that can contain computations, loops, variables, etc. It is very flexible. The mesh is generated from a surface representation, which is build from a list of line loops, which is build from a list of lines, which are in turn built from points. The .geo script can be written and edited by hand or it can be generated automatically by creating objects graphically inside Gmsh.

All this sounds very primitive. Gmsh seems to have acquired so much functionality in the last few years. They even boast of a stable C++ API.  From the [feature overview slides](http://gmsh.info/doc/course/general_overview.pdf) of Gmsh,

>Gmsh 4 introduces a new stable Application Programming Interface (API) forC++, C, Python and Julia, with the following design goals:
 - Allow to do everything that can be done in .geo files•...  and then much more!
 - Be robust, in particular to wrong input data (i.e.  “never crash”)-
 - Be efficient; but still allow to do simple things, simply
 - Be maintainable over the long run

All these sound exactly the kind of desirable things that were discussed in Prof Bangerth's video lectures covering good programming practices.  Since Deal.II is C++, would it be more appropriate and programmatically congruent to use Gmsh's C++ API for mesh generation?

**Comment by bangerth** [comment]
We already do that in `Gmsh::create_triangulation_from_boundary_curve()`. We just don't (yet) mention it in step-49.
