### ISSUE TITLE
Facilities to compute "goodness" of a mesh (i.e. a mesh-quality indicator)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9338]
In the results/extension section of Step-6 as well in Step-49, there is a great deal of discussion about obtaining good meshes are for a problem, with the caveat that this is a highly specialized topic. Step-49 is full of warnings about things that can go wrong when applying certain transformations, and it seems to implant doubts in my mind that my meshes are never going to be correct :) 

Given this, in the spirit of the Kelly Indicator for solution errors in a cell, is there a similar single-metric for the quality/goodness of each cell in a mesh?  Maybe there is something based on the smallest internal angle (to prevent slivers, for Jacobian of the mapping to be invertible, to prevent inverted cells etc).

After all, the error estimation is a complicated topic, nevertheless the Kelly Indicator seems to do a reasonable job for quite a few equations.  If currently not implemented in Deal.II, is there any journal article that discusses research in this direction?

**Comment by blaisb** [comment]
I think such questions are better asked on the deal.II google group than on the github. This is not an issue per se, it's a discussion :). A good one nonetheless.

**Comment by krishnakumarg1984** [comment]
Sorry about that. Indeed your point is correct. I shall close this and ask this on the discussion forum. Thank you for pointing this out.
