### ISSUE TITLE
[Step-49] Unclear documentation "using an object of class having an operator()" for GridTools::Transform

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9349]
This is related to the recently closed #9334 .

In Step-49 documentation, in the section talking about `GridTools::Transform`, we have

>There are different ways of providing such an argument: It could be a pointer to a function; it could be __an object of a class that has an operator()__;

which is demonstrated in `grid_6: Demonstrating GridTools::transform, part 2`

>To make things more interesting, rather than doing so in a single function as in the previous example, we here create __an object with an operator()__

and the relevant lines of code are: 

```
struct Grid6Func
{
  double trans(const double y) const
  {
    return std::tanh(2 * y) / tanh(2);
  }
  Point<2> operator()(const Point<2> &in) const
  {
    return {in(0), trans(in(1))};
  }
};

GridTools::transform(Grid6Func(), triangulation);
```
__________________________

There seem to be a couple of confusions with the above. 

- Do we really have an __object__ here? I do not see an explicit object name created for the struct `GridFunc`. Instead `GridTools::transform` seems to be content with just being passed the struct's name (is that somehow a pointer, err?) as its argument, not an __object__ of the struct.
- Secondly, the sentence claiming _an object of a class that has an operator()_ is confusing because there is no _class_ here, only a _struct_?  (And there is no _object_, but that point is by now beaten to death above)

C++ is already hard, and such subtleties render it even more confusing. Can someone please clarify this?

**Comment by bangerth** [comment]
Yes: `Grid6Func` is the name of a type, and `Grid6Func()` is an (unnamed) object of this type that is passed as argument to `GridTools::transform()`.

There is no difference between `class` and `struct`. The only difference is that by default, the members of `struct` are `public`, whereas for a `class`, they are `private`.

**Comment by krishnakumarg1984** [comment]
>Grid6Func is the name of a type, and Grid6Func() is an (unnamed) object of this type that is passed as argument to GridTools::transform().

Wow. I didn't know that the parenthesis () after struct name was so important that it made it an (unnamed) object of this type!  This is a really big programming language.

Thank you for the explanation!

**Comment by bangerth** [comment]
On 1/16/20 8:22 AM, Krishnakumar Gopalakrishnan wrote:
> Wow. I didn't know that the parenthesis () after struct name was so important 
> that it made it an (unnamed) object of this type! This is a really big 
> programming language.

You're just calling the constructor without arguments. If you want to pass 
arguments, you'd put them between the parentheses.

**Comment by krishnakumarg1984** [comment]
Thank you. I thought a constructor should have the same name of the class/struct. However, there is no function named `Grid6Func()` in the struct?

**Comment by masterleinad** [comment]
Have a look at https://en.cppreference.com/w/cpp/language/default_constructor, Implicitly-declared default constructor.

**Comment by krishnakumarg1984** [comment]
Thank you!
