### ISSUE TITLE
[Possible bug?] Conflict in the documentation of the different mapping classes

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9350]
In Step-10 tutorial, they say that 

>As a side note, for a piecewise linear mapping, you could give a value of 1 to the constructor of MappingQ, but there is also a class MappingQ1 that achieves the same effect. Historically, it did a lot of things in a simpler way than __MappingQ__ but is today just a wrapper around the __latter__. 

But the documentation of [MappingQ1](https://dealii.org/developer/doxygen/deal.II/classMappingQ1.html) conflicts with the above statement.

>    This class is, in all reality, nothing more than a different name for calling __MappingQGeneric__ with a polynomial degree of one as argument.

But this can't be correct, right? `MappingQGeneric` acts everywhere including the interior, whereas `MappingQ` acts only on the boundary!   So, the above statement should really be 

_nothing more than a different name for calling MappingQ with a ..._ 

isn't it? Is this a bug only in the documentation (and hopefully not in the code)?

**Comment by masterleinad** [comment]
The doxygen documentation for `MappingQ1` clearly shows that `MappingQ1` is derived from `MappingQGeneric`. For degree=1, `MappingQ` and `MappingQGeneric` coincide in functionality.

**Comment by krishnakumarg1984** [comment]
>Because bi-/trilinear mappings are significantly cheaper to compute than higher order mappings, it is advantageous in such situations to use the higher order mapping only on cells at the boundary of the domain – i.e., the behavior of MappingQ. Of course, MappingQGeneric also uses bilinear mappings for interior cells as long as it has no knowledge about curvature of interior edges, but it implements this the expensive way: as a general Qp mapping where the mapping support points just happen to be arranged along linear or bilinear edges or faces


So, it seems this is an expensive way to do things for mappingQ1?

**Comment by drwells** [comment]
>  since MappingQGeneric is not efficient in the linear case

Why not?

**Comment by krishnakumarg1984** [comment]
@drwells I am too confused with this nomenclature.

Can you please offer a clarification on the statement from the documentation that I have block-quoted above regarding the sub-optimal behaviour of MappingQGeneric for the linear case?

**Comment by drwells** [comment]
I just don't understand why you think `MappingQGeneric` is not efficient in the multilinear case.

**Comment by krishnakumarg1984** [comment]
@drwells  Because that's what the documentation says!

>__MappingQGeneric__ also uses bilinear mappings for interior cells as long as it has no knowledge about curvature of interior edges, but it implements this the ___expensive___ way: as a general Qp mapping where the mapping support points just happen to be arranged along linear or bilinear edges or faces

**Comment by tamiko** [comment]
@krishanusen25 Thanks a lot for your careful read of the documentation - feedback is always very much appreciated!

I have a suggestion: You are opening a lot of issues essentially for questions about the documentation. What about you join us on slack,  https://dealii.slack.com for discussions? This is actually how we operate as developers: We often discuss questions and ideas on slack first - in particular when we have only a partial overview of the topic - and then when we reach some understanding as a group we open an issue summarizing what has to be done, and or a PR fixing the particular issue.
That way you wouldn't need to open so many issues on github (with the real danger that your question might get buried underneath all the other 400 issues we have open right now).

**Comment by krishnakumarg1984** [comment]
@tamiko yes, can you please send me an invite to the workspace to my email address krishnak [at] vt [dot] edu?
