### ISSUE TITLE
Potentially incomplete documentation for ConvergenceTable add_value() example

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9355]
In the [documentation page](https://dealii.org/developer/doxygen/deal.II/classConvergenceTable.html) for the `add_value()` method of the `ConvergenceTable` class, we have

>The number of cells and the number of DoFs may be added to the table by calling e.g. add_value("n cells", n_cells). 

Does `n_cells` already contain the number of dofs?  Also, shouldn't it be `triangulation.n_cells` if I remember correctly from some early tutorials?

**Comment by masterleinad** [comment]
No, all entries need to be added individually, like
```
    convergence_table.add_value("cycle", refinement_cycle);
    convergence_table.add_value("cells", n_active_cells);
    convergence_table.add_value("dofs", dof_handler.n_dofs());
    convergence_table.add_value("L2_v", L2_error_velocity);
    convergence_table.add_value("H1_v", H1_error_velocity);
    convergence_table.add_value("Linfty_v", Linfty_error_velocity);
    convergence_table.add_value("L2_div_v", L2_div_velocity);
    convergence_table.add_value("L2_p", L2_error_pressure);
    convergence_table.add_value("H1_p", H1_error_pressure);
    convergence_table.add_value("Linfty_p", Linfty_error_pressure);
```
in tests/fe/fe_q_dg0.cc.

**Comment by krishnakumarg1984** [comment]
Thank you. I will submit a PR to fix this sentence

>The number of cells __and the number of DoFs__ may be added to the table by calling e.g. add_value("n cells", n_cells).
