### ISSUE TITLE
[Step-10] Potentially need a documentation line explaining why the header file fe_nothing was introduced

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9356]
Step-10 is the first tutorial wherein the `FENothing` class is introduced.

In the spirit of all other tutorials, the inclusion of the corresponding header file warrants a line of explanation, and probably cannot be glossed over as currently done here. Also, the statement claiming that `MappingQ` is the only one new is false.

__________________________________________
>This is the only new one: in it, we declare the MappingQ class which we will use for polynomial mappings of arbitrary order:
>`#include <deal.II/fe/mapping_q.h>`

>The first of the following include files are probably well-known by now and need no further explanation.
>
```
#include <deal.II/base/quadrature_lib.h>
...
bunch of include files
...
__#include <deal.II/fe/fe_nothing.h>__
#include <deal.II/fe/fe_values.h>
```

**Comment by bangerth** [comment]
Sure -- that should be easy enough to add.
