### ISSUE TITLE
Weird doxygen behaviour for Step-10 documentation direct link to Plain Program in the browser

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9357]
This is a really weird one.  All the tutorials so far have correct hyperlinking of the doxygen-generated pages rendered in a browser.

However, for Step-10, the direct link to the `Plain Program` does not work in both the

- master version (https://dealii.org/developer/doxygen/deal.II/step_10.html#PlainProg)
- v9.1.1 version (https://dealii.org/current/doxygen/deal.II/step_10.html#PlainProg)

Puzzlingly, the problem is only with step-10. I have tested this with Steps 1 through 9 as well as 11, and they all correctly fly to the Plain Program directly on both the master as well as the latest released branches. I could not figure out why this is happening!

**Comment by bangerth** [comment]
Confirmed. We have the correct `<a name="PlainProg"> piece in place after processing the input files, but then doxygen escapes the `<` to `&lt;`.

I'll have to investigate further.
