### ISSUE TITLE
[Step-10] Incomplete/incorrect input dependency in the tutorial dot diagram/DAG graph

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9358]
In the dot diagram/DAG graph in the [main landing page](https://dealii.org/developer/doxygen/deal.II/Tutorial.html) of the tutorial section showing the relationship among various tutorials, I believe that the input dependencies of step-10 is incomplete.

Currently, it is marked that Step-10 depends only on Step-4. This is incorrect. Step-10 pulls a whole load of code and concepts  (without the corresponding explanation) about facilities from the `ConvergenceTable` class, which is first introduced in Step-7.  

Prior to coming into step-10, I had only visited Steps 1-6 and 49. I thought Step-10 has a sole dependency on Step-4. But however, had to jump to Step-7 to figure out how the convergence table facilities work.

Also, the `FEFaceValues` class is first introduced in step-7. 

Some relevant lines are the following:

```
#include <deal.II/base/convergence_table.h>
...
  ConvergenceTable table;
....
            table.add_value("cells", triangulation.n_active_cells());
....
            table.add_value("eval.pi", static_cast<double>(area));
            table.add_value("error", static_cast<double>(std::fabs(area - pi)));
 ....
        table.omit_column_from_convergence_rate_evaluation("cells");
        table.omit_column_from_convergence_rate_evaluation("eval.pi");
        table.evaluate_all_convergence_rates(
          ConvergenceTable::reduction_rate_log2);
        table.set_precision("eval.pi", 16);
        table.set_scientific("error", true);
        table.write_text(std::cout);
....
```

**Comment by bangerth** [comment]
On 1/16/20 4:45 PM, Krishnakumar Gopalakrishnan wrote:
> Prior to coming into step-10, I had only visited Steps 1-6 and 49. I thought 
> Step-10 has a sole dependency on Step-4. But however, had to jump to Step-7 to 
> figure out how the convergence table facilities work.
Feel free to change it to step-10 in |examples/step-10/doc/depends-on|.

**Comment by krishnakumarg1984** [comment]
Also, the FEFaceValues class is first introduced in step-7.
