### ISSUE TITLE
Step-10 tutorial suddenly introduces Utilities::to_string without explanation (or comparison with std::string)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9361]
All the way until Step 6,  whenever the mesh refinement cycle number was appended to filenames,  `std::to_string` was used.

However, in step-10, this suddenly switched to a deal.ii function, `Utilities::to_string`, for eg.

` std::string filename_base = "ball_" + Utilities::to_string(refinement); `

Why is this change? How is the deal.ii version different to the std version?

**Comment by drwells** [comment]
`Utilities::to_string` predates C++11 but does the same thing. It looks like we never got around to converting all of these over to `std::to_string`. Would you be willing to do this?

**Comment by krishnakumarg1984** [comment]
Yes. I shall submit a PR.

- Is the plan to `Utilities::to_string` from the library in the future?
- Are there are any other such functions in the `Utilities` namespace that have been superseded by std counterparts?

**Comment by drwells** [comment]
Thanks :)

1. `Utilities::to_string` has a second argument that is very convenient, so no.
2. A few things have been deprecated, like `fixed_int_power`, but I don't think there is anything in `Utilities` that could be replaced by the standard library that has not been deprecated.

**Comment by krishnakumarg1984** [comment]
@drwells  There may be more at stake than what is perceived. There are 112 occurrences  of `Utilities::to_string` throughout the library!

`Utilities::to_string` has been only introduced in `8.4.0` and seems quite sophisticated. 

> New: There is now a function Utilities::to_string that works like
>   int_to_string, but is more safe for long integers, negative integers, and
>   also handles floating point numbers. The implementation of int_to_string
>   was changed to simply call to_string. int_to_string is kept for
>   compatibility, but should only be used for unsigned integers.
>   (Rene Gassmoeller, 2015/12/09)

Given that this was introduced late Dec 2015, are we sure it was implemented only because there was no C++11 functionality (somehow the timeline seems off to me).

**Comment by drwells** [comment]
They don't do the same thing: see the documentation. Furthermore we did not *require* C++11 until after December 2015.

**Comment by drwells** [comment]
Ultimately, this really doesn't matter: all of these functions convert numbers to strings. The details are really irrelevant to the larger goals of the library. Nevertheless lets go ahead and convert these over.

**Comment by drwells** [comment]
I should clarify both of my previous remarks, since they are inconsistent: `Utilities::to_string` has an extra argument for padding. However, we rarely use it - in practice we almost always ignore the second argument and use it in a way equivalent to `std::to_string`. Hence we can convert nearly all occurrences of our own function to the one in the standard library, which is what #9400 does.

**Comment by krishnakumarg1984** [comment]
Thank you for the clarification. This helps!

**Comment by bangerth** [comment]
See also #9409.
