### ISSUE TITLE
/contrib/utilties/indent script is broken for latest update of GNU sed

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9368]
`/contrib/utilties/indent` has just broken leading to errors like __invalid character etc.__ with the latest update of GNU sed `v4.8`.

Using GNU-specific flags could be problematic, since different contributors will be on different platforms. Perhaps relying only on POSIX flags is the answer?

**Comment by masterleinad** [comment]
Can you give an example of the problems you are seeing? Which GNU-specific flags are you referring to?

**Comment by tjhei** [comment]
Is this from #9351 ?

**Comment by masterleinad** [comment]
Must be. This is the only recent change, but I don't see how we are doing anything more platform-specific than before.

**Comment by tjhei** [comment]
https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

**Comment by krishnakumarg1984** [comment]
We'll probably need to revisit this? 

Right now, I get the following error when the indent script is run from the root of the repo:

>sed: 1: "examples/step-7/doc/int ...": invalid command code e

I am on BSD sed released May 10, 2005, which is what the latest macOS ships! See @9393
