### ISSUE TITLE
Steps 47, 58, 66-70 are missing?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9374]
In the tutorials landing page, steps 47, 58, 66-70 are entirely missing (from the DAG, from the list and the headings/categories). 

Is this due to an oversight? Or are these currently vacant placeholders for upcoming tutorials?

In either case, I think perhaps we can take some inspiration from the LaTeX project's [newsletters  page](https://www.latex-project.org/news/latex2e-news/), which has a similar situation

>Note: ltnews18 doesn't exist.
By mistake we incremented the issue number twice moving directly from 17 to 19. 

and perhaps post a similar message along these lines on the tutorials landing page. Right now, browser searches for these numbers return an uncomfortable beep and red highlighting saying "phrase not found" which is ever so slightly off-putting to users:)

**Comment by drwells** [comment]
Yup: some of these are reserved for future tutorial programs. Others were just never completed. See also #8445, #9068, etc.

**Comment by krishnakumarg1984** [comment]
>Yup: some of these are reserved for future tutorial programs. 

@drwells  Could we please mention this fact in the main landing page of the tutorials?

**Comment by drwells** [comment]
I have a better plan :)

**Comment by bangerth** [comment]
On 1/20/20 8:18 AM, Krishnakumar Gopalakrishnan wrote:
> @drwells <https://github.com/drwells> Could we please mention this fact 
> in the main landing page of the tutorials?

The problem with mentioning everything is that too many comments in all 
places make it hard to find the *important* information. I think that 
the number of people who want to know why there are holes in the 
numbering is actually quite small :-)
