### ISSUE TITLE
In tutorials, mismatch between legend colour/shading and DAG nodes for code-gallery

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9378]
In the `master` branch of the tutorials, there is a mismatch in the shading applied to the `Code gallery` nodes and the corresponding legend entry. The nodes within the DAG are _shaded white_, while the legend entry has a _dark/black shade_.

This raises a question:

Are these not synced automatically by the `dot` post-processor/doxygen framework? It would be pretty tedious to keep legend entries and node colouring in sync if any changes have to applied manually to both placed?

**Comment by bangerth** [comment]
See #9381.

**Comment by krishnakumarg1984** [comment]
Thank you.
