### ISSUE TITLE
unused-function warning in lac/matrix_out.h

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#938]
/Users/qiaol/devel/dealii/include/deal.II/lac/matrix_out.h:227:14: warning: unused function 'get_element' [-Wunused-function]
/Users/qiaol/devel/dealii/include/deal.II/lac/matrix_out.h:240:14: warning: unused function 'get_element' [-Wunused-function]

**Comment by bangerth** [comment]
Does the warning disappear if you make these functions `inline`? If so, feel free to submit a patch!

**Comment by QiaoLei-88** [comment]
Closed by #939
