### ISSUE TITLE
Redundancy persists in tutorial DAG code-gallery edges

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9383]
I could not figure out how to get rid of this redundancy in the tutorial DAG that pertains to code-gallery edges. Here is the image of the problem I am talking about

![duplicate_dag](https://user-images.githubusercontent.com/15239509/72646144-53e5a980-396d-11ea-8681-6943b3ecce08.PNG)

I think we need to remove the dotted edge from 18 onto both these code galleries, right?

**Comment by bangerth** [comment]
This information comes from the code gallery program, which is in a separate repository: https://github.com/dealii/code-gallery

**Comment by krishnakumarg1984** [comment]
Ah that explains it. Well, the PR is https://github.com/dealii/code-gallery/pull/65
