### ISSUE TITLE
Documentation issues in  VectorTools::NormType

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9392]
None of the notation is consistently used in the documentation for  [VectorTools::NormType](https://dealii.org/developer/doxygen/deal.II/namespaceVectorTools.html#a69967cb7a148a7169963126249213db1) which is very confusing.

In the table listing the integral formulae for various norms, the notation is all over the place. There are a proliferation of symbols

- f
- $\hat{f}$
- $f_c$
- $\hat{f_c}$

And combinations thereof. In reality, we just need two symbols.  Can someone clarify this and provide the canonical notation and their definition?

**Comment by masterleinad** [comment]
I am not quite sure what is confusing. Admittedly, `\hat{f}_c` is not separately defined but `f`, `f_c` and `\hat{f}` are and I would argue that it is not hard to deduce that `\hat{f}_c` is defined analogously.

What kind of other combinations are you referring to? Do you mean `e` and `e_c`?

**Comment by bangerth** [comment]
In general, since you know what confuses you, feel free to just fix things however you see fit. In this case, the function is in `include/deal.II/numerics/vector_tools.h`.
