### ISSUE TITLE
[Step-7] Violation of the philosophy of multiplying the test function from the left 

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9396]
In Step-3, the documentation goes to great lengths to explain why it is better to multiply the test function from the left. There is even an entire [section](https://dealii.org/developer/doxygen/deal.II/step_3.html#Shouldwemultiplybyatestfunctionfromtheleftorfromtheright) dedicated to this. And in one of the earlier video lectures of Math 676, Prof Bangerth again goes through this aspect in detail.

However, all of this is suddenly flouted (at least in the documentation) in Step-7.  See below:

<img width="1210" alt="Screenshot 2020-01-19 at 18 20 25" src="https://user-images.githubusercontent.com/15239509/72686064-69cba980-3ae8-11ea-9fed-0c27c1878c63.png">

Also, the test function is suddenly changed to $v$, rather than $\varphi$. Do the developers agree with these observations?

**Comment by tamiko** [comment]
Example steps and documentation are written by many different authors and over a course of many years. That said, it is quite common to have a test function testing on the right in a variational setting in the mathematical literature.

I agree that we are not terribly consistent at that - but this is honestly not a terribly grave problem (The documentation explains that nu is a test function). I think we should give our many contributors of example step the artistic freedom to express equations and choose notation in a context they seem fit. This also applies to step 7 that is not one of our core example steps.

Also note that in the actual definition of the matrix, the philosophy of "test function from the left" is obeyed.

**Comment by bangerth** [comment]
All of @tamiko 's observations are correct, but that doesn't mean we can't improve things or make them more consistent. I would accept a patch that changes the documentation of step-7.
