### ISSUE TITLE
Post-function in matrix-free cell_loop() is not executed correctly when not using AdditionalData::none

### ISSUE THREAD

**Issue by anates** [dealii/dealii#9405]
When choosing to use a task scheme other than `AdditionalData::none` in the matrix-free environment, at least the post-loop-function is not executed correctly at all. I could not test the pre-loop-function yet.

When comparing the resulting vector after the application of the matrix-free `apply()`-function, according to the output there is no visible influence of any post-loop function. This can be tested using the attached code (had to rename it to .txt, github does not allow .cpp-files). When setting `use_scale_function` to `false` and `use_threads` to `true`, the resulting output vector (which can be printed using the commented function print_vector()) does not change, regardless of the applied function. It also is different compared to the output vector resulting from either `use_scale_function = true` (value for `use_threads` is not important here) or the output from `use_scale_function = false` and `use_threads = false`, which both are identical. 

After working on that problem for several days, would it be possible to at least add a warning, to spare others the debugging?
[main.txt](https://github.com/dealii/dealii/files/4087083/main.txt)

**Comment by peterrum** [comment]
ping @kronbichler

**Comment by kronbichler** [comment]
This is a bug and we need to fix it. Thanks for letting us know. I will try to do so as soon as possible.
