### ISSUE TITLE
PolynomialsAdini does not derive from ScalarPolynomialsBase

### ISSUE THREAD

**Issue by GrahamBenHarper** [dealii/dealii#9438]
I just saw this while working on another PR. It looks like `PolynomialsAdini` hasn't seen much love in a while.

I assign this to myself, but I'm opening an issue so I don't forget. :stuck_out_tongue:

**Comment by GrahamBenHarper** [comment]
Also, there are currently no tests for `PolynomialAdini`, meaning we have no clue if it is still functioning as intended. I will also add a minor test for it when I take care of this.

**Comment by bangerth** [comment]
Thanks in advance! Is there no class that uses `PolynomialsAdini` and that is itself tested?

**Comment by masterleinad** [comment]
> Thanks in advance! Is there no class that uses `PolynomialsAdini` and that is itself tested?

No.
```
$ git grep -n "PolynomialsAdini"
include/deal.II/base/polynomials_adini.h:42:class PolynomialsAdini
include/deal.II/base/polynomials_adini.h:48:  PolynomialsAdini();
source/base/polynomials_adini.cc:38:PolynomialsAdini::PolynomialsAdini()
source/base/polynomials_adini.cc:129:PolynomialsAdini::compute(const Point<2> &           unit_point,
source/base/polynomials_adini.cc:161:PolynomialsAdini::compute_value(const unsigned int i, const Point<2> &p) const
source/base/polynomials_adini.cc:173:PolynomialsAdini::compute_grad(const unsigned int i, const Point<2> &p) const
source/base/polynomials_adini.cc:193:PolynomialsAdini::compute_grad_grad(const unsigned int i,
```

**Comment by GrahamBenHarper** [comment]
Actually, the reason I even saw it was because I ran a `grep -rn "compute("` for the other PR and I said "hey, I've never seen this PolynomialsAdini before!" The reason I never saw it is because `PolynomialsAdini` has no associated finite elements *and* no tests.

**Comment by bangerth** [comment]
Yes, that empirically means that the class probably doesn't do what it's supposed to do!

I believe that it was originally written by Baerbel Holm for her PhD thesis, but the element she implemented never made it into the library. (The Adini element is used for the solution of fourth-order problems -- for which we now have a better way in the form of the C0IP method used in step-47.)
