### ISSUE TITLE
Missing file fully_distributed_tria_util.h

### ISSUE THREAD

**Issue by GrahamBenHarper** [dealii/dealii#9440]
@peterrum it seems like we're missing a file related to the fully distributed work. I'm on the updated master branch but when I build I receive this error.
```
/home/graham/Programming/cpp/Deal.II/deal.II-master/source/distributed/fully_distributed_tria_util.cc:20:10: fatal error: deal.II/distributed/fully_distributed_tria_util.h: No such file or directory
 #include <deal.II/distributed/fully_distributed_tria_util.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Originally, this gave some other really cryptic errors about `ConstructionData` before I cleaned out my install directory and tried again. Should this file exist somewhere?

Files that are based on `fully_distributed_tria_util`:
```
grep -rn "fully_distributed_tria_util"
source/distributed/fully_distributed_tria_util.cc:20:#include <deal.II/distributed/fully_distributed_tria_util.h>
source/distributed/fully_distributed_tria_util.cc:673:#include "fully_distributed_tria_util.inst"
tests/fullydistributed_grids/copy_distributed_tria_03.cc:23:#include <deal.II/distributed/fully_distributed_tria_util.h>
tests/fullydistributed_grids/copy_serial_tria_08.cc:23:#include <deal.II/distributed/fully_distributed_tria_util.h>
```
Looking for the `.cc` file returns one file
```
find . -name "fully_distributed_tria_util.cc"
./source/distributed/fully_distributed_tria_util.cc
```
Looking for the `.h` file returns nothing
```
find . -name "fully_distributed_tria_util.h"
```

**Comment by bangerth** [comment]
Interesting -- I do have that `.cc` file as well, but because it's not listed in `CMakeLists.txt`, it shouldn't be compiled. You can probably make the compiler error go away by calling `cmake .` again, but the bigger question of why the file is there and what its purpose is of course remains :-)

**Comment by peterrum** [comment]
It should have been deleted ;) Feel free to create a PR. Else I create one in 30 minutes or so...

**Comment by GrahamBenHarper** [comment]
@peterrum Which file? `source/distributed/fully_distributed_tria_util.cc`?

**Comment by GrahamBenHarper** [comment]
I can do a quick PR for it too.

**Comment by peterrum** [comment]
Yes. Nothing more ;)

**Comment by peterrum** [comment]
The content has moved to another file a week ago...

**Comment by GrahamBenHarper** [comment]
Good to know! I guess my cmake configuration was set at a time when the file existed, so it was trying to build something that didn't exist.

I even tried a `make clean` but it never occurred to me to run the cmake configure again :stuck_out_tongue:
