### ISSUE TITLE
Issue with boundary indicator in GridGenerator::half_hyper_shell

### ISSUE THREAD

**Issue by krishanusen25** [dealii/dealii#9442]
The documentation of half_hyper_shell grid generator mentions that If colorize is set to true, the part of the boundary where x=0 (half of it is above the x-axis and the other half is below the x-axis if we consider the origin as the center), gets indicator 2.

I tried using that boundary indicator 2 to set constraints, but deal.ii seems to apply the constraints only to the half of the part which is above the x-axis, and not on the half which is below the x-axis.

**Comment by GrahamBenHarper** [comment]
Is this problem appearing with a 2D or 3D mesh?

**Comment by krishanusen25** [comment]
I am using a 2D mesh.

**Comment by GrahamBenHarper** [comment]
I may see what the issue is in `grid_generator.cc`, but I'm not certain yet. In particular, the mesh is colorized using the following code:
```
if (colorize)
      {
        Triangulation<2>::cell_iterator cell = tria.begin();
        for (; cell != tria.end(); ++cell)
          {
            cell->face(2)->set_boundary_id(1);
          }
        tria.begin()->face(0)->set_boundary_id(3);

        tria.last()->face(1)->set_boundary_id(2);
      }
```
I'll dig deeper later today and let you know if we find a fix.

**Comment by krishanusen25** [comment]
Thanks, for the help. I think I should also mention that I am using an older version (8.5.1) of deal.ii and just noticed that the part you mentioned is different between the current version of deal.ii (9.1.1) and the version I am using (8.5.1).

**Comment by masterleinad** [comment]
It only really makes sense to report bugs in `master` or at least the latest release...

**Comment by GrahamBenHarper** [comment]
@krishanusen25 please let us know if the problem persists when you update to current version and we can take another look at it :)

**Comment by krishanusen25** [comment]
Hello Graham,

Thanks for your response. I have updated to the current version (9.1.1) today and it seems the boundary indicator 2 still seems to identify only the top part of the boundary located at x=0.

Looking at the code you mentioned earlier, it seems that there exists a boundary indicator 3 where as in the documentation, the description of the hypershell grid genenerator only mentions boundary indicators 0, 1 and 2. I think that might be the issue.

**Comment by bangerth** [comment]
@krishanusen25 : Do you think you could produce a small self-contained example that shows the issue? That would certainly help a lot both in debugging the issue, and for having a test case for the test suite once the bug is fixed!

**Comment by GrahamBenHarper** [comment]
@bangerth Actually I just ran a small test on my end. In accordance with the code I posted, the edge above y=0 is assigned the boundary label 2, and the edge below y=0 is assigned boundary label 3, so the documentation is mildly misleading. Here's the example I tested.

```
  Triangulation<2>          triangulation;
  GridGenerator::half_hyper_shell(triangulation,
                                            Point<2>(0.0, 0.0),
                                            1,
                                            2,
                                            0,
                                            true);

  Triangulation<2>::cell_iterator cell = triangulation.begin();
  for (; cell != triangulation.end(); ++cell)
  {
    for (unsigned int f=0; f<4; ++f)
    {
      if(cell->face(f)->boundary_id() == 2)
      {
        cell->face(f)->vertex(0) = Point<2>(-2.0, 3.0);
        cell->face(f)->vertex(1) = Point<2>(-1.0, 3.0);
      }

      if(cell->face(f)->boundary_id() == 3)
      {
        cell->face(f)->vertex(0) = Point<2>(2.0, 3.0);
        cell->face(f)->vertex(1) = Point<2>(1.0, 3.0);
      }
    }
  }

  print_mesh_info(triangulation, "grid-8.vtu");
```

I can open a PR to note that in the documentation.

**Comment by bangerth** [comment]
Thanks for working on this! If you don't mind, can you also make the code snippet above into a testcase that somehow shows the boundary ids? You probably don't even need to move the vertices for that.

**Comment by GrahamBenHarper** [comment]
Sure, I can do that. I'm building a library in the background and it's going slowly. :stuck_out_tongue:

**Comment by GrahamBenHarper** [comment]
@tjhei I'll link this to #8206 because it would have helped to have some of those images for exactly this scenario :stuck_out_tongue: 

I imagine it wouldn't be too hard to write a file that takes any 2d mesh and writes it to a `.eps` file and places the boundary ids exactly at `face(f)->center()` within the `.eps` file; however, drawing 3d meshes in a `.eps` with the boundary ids would be hard to read.

**Comment by tjhei** [comment]
> however, drawing 3d meshes in a `.eps` with the boundary ids would be hard to read.

agreed.

**Comment by bangerth** [comment]
On 1/30/20 9:49 AM, Graham Harper wrote:
> I imagine it wouldn't be too hard to write a file that takes any 2d mesh and 
> writes it to a |.eps| file and places the boundary ids exactly at 
> |face(f)->center()| within the |.eps| file;

Better yet with .svg format :-)

**Comment by GrahamBenHarper** [comment]
@bangerth good point! `.svg` files are a lot easier to read and write :)
