### ISSUE TITLE
[Step-20] Doxygen linking mechanism is inadequate when linking to different sections having the same heading name?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9460]
In the table of contents for Step-20, there are two sections with the same heading name

>1. Introduction
    - Linear solvers and preconditioners
2. The commented program
    - Linear solvers and preconditioners

Having read up to the `MixedLaplaceProblem::assemble_system` section in the commented code, I took a break and wanted to resume from the `Linear solvers and preconditioners` in the commented code. However, clicking this link in the TOC makes the page in the browser fly to the corresponding section name in the Introduction section! 

Assuming this is a bug in Doxygen, what would be the workaround in this kind of scenarios to help the reader with the navigation?

**Comment by masterleinad** [comment]
Choosing a slightly different section name?

**Comment by bangerth** [comment]
The script that generates the table of contents is not prepared to deal with sections of the same name. We should just use a different section name -- feel free to propose a patch!
