### ISSUE TITLE
CMake with external LAPACK on NERSC 

### ISSUE THREAD

**Issue by AntonErmakov** [dealii/dealii#9462]
Hello!

I am trying to configure deal.ii on NERSC supercomputer that comes with MKL version of LAPACK. Here is the cmake command I am using. 

`cmake -DCMAKE_INSTALL_PREFIX=/path/to/my/install -DDEAL_II_WITH_LAPACK=ON -DLAPACK_DIR=$MKLROOT/lib/intel64/ -DLAPACK_LIBRARIES=$MKLROOT/lib/intel64_lin/libmkl_lapack95_lp64.a  -DDEAL_II_LAPACK_WITH_MKL=ON ..`

I tried numerous combination of the above command: leaving out DDEAL_II_LAPACK_WITH_MKL=ON or leaving out LAPACK_DIR or LAPACK_LIBRARIES flags, but still get the same result:

> -- Performing Test LAPACK_SYMBOL_CHECK
> -- Performing Test LAPACK_SYMBOL_CHECK - Failed
> -- Could not find a sufficient BLAS/LAPACK installation: BLAS/LAPACK symbol check failed! Consult CMakeFiles/CMakeError.log for further information.
> -- Performing Test MKL_SYMBOL_CHECK
> -- Performing Test MKL_SYMBOL_CHECK - Failed
> -- Use other than Intel MKL implementation of BLAS/LAPACK (consult CMakeFiles/CMakeError.log for further information).
> -- DEAL_II_WITH_LAPACK has unmet external dependencies.
> CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):
> 
> 
>   Could not find the lapack library!
> 
>   Could not find a sufficient BLAS/LAPACK installation:
> 
>   BLAS/LAPACK symbol check failed! This usually means that your BLAS/LAPACK
>   installation is incomplete or the link line is broken.  Consult
> 
>     CMakeFiles/CMakeError.log
> 
>   for further information.
> 
>   Please ensure that a suitable lapack library is installed on your computer.
> 
>   If the library is not at a default location, either provide some hints for
>   autodetection,
> 
>       $ LAPACK_DIR="..." cmake <...>
>       $ cmake -DLAPACK_DIR="..." <...>
> 
>   or set the relevant variables by hand in ccmake.
> 
> Call Stack (most recent call first):
>   cmake/macros/macro_configure_feature.cmake:269 (FEATURE_ERROR_MESSAGE)
>   cmake/configure/configure_1_lapack.cmake:116 (CONFIGURE_FEATURE)
>   cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
>   CMakeLists.txt:124 (VERBOSE_INCLUDE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/global/homes/e/eai/temp/dealii-9.1.1/build/CMakeFiles/CMakeOutput.log".
> See also "/global/homes/e/eai/temp/dealii-9.1.1/build/CMakeFiles/CMakeError.log".

I wonder if anyone has tried to use deal.ii on NERSC and what is the correct way to cmake it?

Thank you.

**Comment by masterleinad** [comment]
Can you have a look into `CMakeFiles/CMakeError.log` to see why the checks `LAPACK_SYMBOL_CHECK` and `MKL_SYMBOL_CHECK` fail?

**Comment by AntonErmakov** [comment]
here it is: [CMakeError.log](https://github.com/dealii/dealii/files/4144860/CMakeError.log)

**Comment by tjhei** [comment]
I think you will need to specify libmkl_core and libmkl_sequential for BLAS and libmkl_intel_lp64 for LAPACK.

**Comment by AntonErmakov** [comment]
hmmm. Trying this cmake command:

`cmake -DCMAKE_INSTALL_PREFIX=~/my/path/ -DDEAL_II_WITH_LAPACK=ON -DBLAS_LIBRARIES="$MKLROOT/lib/intel64/libmkl_core.a;$MKLROOT/lib/intel64/libmkl_sequential.a" -DLAPACK_LIBRARIES="$MKLROOT/lib/intel64/libmkl_intel_lp64.a" ..`

leads to the the same result:

> -- Performing Test LAPACK_SYMBOL_CHECK
> -- Performing Test LAPACK_SYMBOL_CHECK - Failed
> -- Could not find a sufficient BLAS/LAPACK installation: BLAS/LAPACK symbol check failed! Consult CMakeFiles/CMakeError.log for further information.
> -- Performing Test MKL_SYMBOL_CHECK
> -- Performing Test MKL_SYMBOL_CHECK - Failed
> -- Use other than Intel MKL implementation of BLAS/LAPACK (consult CMakeFiles/CMakeError.log for further information).
> 

After starring at the CMakeError.log for a while, it seems that at the LAPACK_SYMBOL_CHECK step, cmake checks whether there is required functionality in the specified libraries and the lack thereof causes the problem.

**Comment by masterleinad** [comment]
So can you run the test manually yourself? Can you figure out the compiler flags you need?

**Comment by AntonErmakov** [comment]
The solution was actually very simple. All I needed to do is to specify to use the intel compilers:

`cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/ -DCMAKE_CXX_COMPILER="icpc" -DCMAKE_C_COMPILER="icc" ..`

With intel compilers on NERSC, cmake is able to find LAPACK and BLAS automatically.
