### ISSUE TITLE
TBB Version cannot be recognized correctly 

### ISSUE THREAD

**Issue by xiyuanbao** [dealii/dealii#9475]
I am using Centos 7 and the tbb-devel tbb from yum source is 4.1.9, older than 4.2. If I build latest [TBB](https://github.com/intel/tbb) from source and set up TBB_DIR TBB_INCLUDE_DIR correctly, deal.ii can find tbb path, but the reported version will be 0.1 since the TBB_VERSION_MAJOR is 2020 in ${TBB_INCLUDE_DIR}/tbb/tbb_stddef.h, while FindTBB.cmake is trying to pick only one digit:
```
IF(EXISTS ${TBB_INCLUDE_DIR}/tbb/tbb_stddef.h)
  FILE(STRINGS "${TBB_INCLUDE_DIR}/tbb/tbb_stddef.h" TBB_VERSION_MAJOR_STRING
    REGEX "#define.*TBB_VERSION_MAJOR")
  STRING(REGEX REPLACE "^.*TBB_VERSION_MAJOR.*([0-9]+).*" "\\1"
    TBB_VERSION_MAJOR "${TBB_VERSION_MAJOR_STRING}"
    )
  FILE(STRINGS "${TBB_INCLUDE_DIR}/tbb/tbb_stddef.h" TBB_VERSION_MINOR_STRING
    REGEX "#define.*TBB_VERSION_MINOR")
  STRING(REGEX REPLACE "^.*TBB_VERSION_MINOR.*([0-9]+).*" "\\1"
    TBB_VERSION_MINOR "${TBB_VERSION_MINOR_STRING}"
    )
  SET(TBB_VERSION
    "${TBB_VERSION_MAJOR}.${TBB_VERSION_MINOR}"
    )
ENDIF()
```

Can we modify it like this?
`STRING(REGEX REPLACE "^.*TBB_VERSION_MAJOR.*([0-9]+).*" "\\4"`

**Comment by masterleinad** [comment]
This was fixed in https://github.com/dealii/dealii/commit/80b13fe5a2eaefc77fa8c9266566fa8a2de91edf. If it still doesn't work correctly with the `develop` branch, feel free to reopen.
