### ISSUE TITLE
Poor error message from SparseMatrix::add with empty SparsityPattern

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#9479]
In this example I have forgetten to set up the sparsity pattern. This currently results in an address boundary error from `SparseMatrix::add`. 

I would fix it, but I'm not sure what the best thing to assert would be. Should we check that the pattern isn't empty when calling `SparseMatrix::reinit` or to check something locally in `SparseMatrix::add`?
```c++
#include <deal.II/base/types.h>

#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/sparsity_pattern.h>

#include <vector>

int
main()
{
  using namespace dealii;

  SparsityPattern pattern;
  // Forgot to set up the pattern here...

  SparseMatrix<double> sparse_matrix;
  sparse_matrix.reinit(pattern);

  std::vector<types::global_dof_index> dof_indices = {0};
  const unsigned int                   n_dofs      = dof_indices.size();
  FullMatrix<double>                   local_matrix(n_dofs, n_dofs);

  // Crashes when trying to add here.
  sparse_matrix.add(dof_indices, local_matrix);

  return 0;
}

```

**Comment by bangerth** [comment]
There should definitely be some kind of check in `add(...)` -- what is the error message you get here?

I think that it might be quite useful to *also* check in `reinit()`, but I don't see a way to do that: It is perfectly valid to have an empty sparsity pattern that would correspond to a zero block in the matrix.

**Comment by simonsticko** [comment]
Okey, after a bit of digging... When we reach line 639 in `sparse_matrix.templates.h` we have this
```c++
 size_type index = cols->rowstart[row];    
```
But `rowstart` is a nullptr because we haven't called `SparsityPatternBase::reinit` yet, so my example above just crashes with an address boundary error.

I think just adding an assert on `row` at the beginning of the function solves the problem, see #9484.
