### ISSUE TITLE
Max cell number limit may freeze grid refinement 

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#948]
When cell number exceed the required max_n_cells, current mechanism in refine_and_coarsen_fixed_number will do no grid refinement and just coarsen some cells to
reach the cell number limit. Consequently, in next grid refinement very little number of cells, or even none, will be refined or coarsened. Thus the grid refinement is frozen.

This is quite problematic when the solution is not steady.

The solution to this issue is already in my mind. PR will arrive soon.

**Comment by guidokanschat** [comment]
If you set `max_n_cells`, I assume you want to limit the cells. Which means you cannot refine. The only possible improvement I see is, that if you coarsen some cells, you can replace them. Otherwise, do not set a limit. Do I get something wrong? If not, I suggest to close the issue.

**Comment by QiaoLei-88** [comment]
I agree. I found no perfect solution for this issue and closed the PR. I just forgot to close this issue.
