### ISSUE TITLE
matrix_free/face_setup_01 segfaults

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9485]
This happens on two of my platforms.

**Comment by bangerth** [comment]
Backtrace:
```
(gdb) bt
#0  0x00005555555c5e5e in dealii::Utilities::MPI::Partitioner::size (this=0x0) at /home/bangerth/p/deal.II/1/dealii/include/deal.II/base/partitioner.h:781
#1  0x00005555555bbbff in main (argc=1, argv=0x7fffffffdca8) at /home/bangerth/p/deal.II/1/dealii/tests/matrix_free/face_setup_01.cc:85
```
Note that `this` is null...

**Comment by bangerth** [comment]
More specifically, in `main()` we have this:
```
  for (auto &p : matrix_free.get_dof_info().vector_partitioner_face_variants)
    deallog << "partitioner: size=" << p->size()
            << " local_size=" << p->local_size()
            << " n_ghosts=" << p->n_ghost_indices() << std::endl;
```
For one of the iterations, `p` is just a `nullptr`. This happens because:
```
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants.size()
$4 = 5
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants[0]
$5 = std::shared_ptr<const dealii::Utilities::MPI::Partitioner> (use count 5, weak count 0) = {get() = 0x555555806df0}
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants[1]
$6 = std::shared_ptr<const dealii::Utilities::MPI::Partitioner> (use count 5, weak count 0) = {get() = 0x555555806df0}
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants[2]
$7 = std::shared_ptr<const dealii::Utilities::MPI::Partitioner> (use count 5, weak count 0) = {get() = 0x555555806df0}
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants[3]
$8 = std::shared_ptr<const dealii::Utilities::MPI::Partitioner> (empty) = {get() = 0x0}
(gdb) p  matrix_free.get_dof_info(0).vector_partitioner_face_variants[4]
$9 = std::shared_ptr<const dealii::Utilities::MPI::Partitioner> (empty) = {get() = 0x0}
```
So it's an array of length 5, but the last two pointers are null.

That's about the extent to which I can help -- I have no clue what's actually happening in this code :-)

**Comment by peterrum** [comment]
@bangerth That my fault:

https://github.com/dealii/dealii/blob/e7eda002ec8833c85323bf85925edec95e3cd8d9/include/deal.II/matrix_free/matrix_free.templates.h#L1888-L1899

The forth and fifth `vector_partitioner_face_variants` are not set. They are only used for ECL and I did not think someone uses the way as done in the test.

**Comment by bangerth** [comment]
@peterrum  I'll let you fix this then. Is it documented what the five pointers are and that some may be null?

**Comment by kronbichler** [comment]
Correct, these tests fail on all platforms since we merged the additional partitioners last week in #9156. The problem could have been avoided if any of us had run `ctest -R matrix_free` locally before the merge, since the CI tests cannot cover all the library and this is a well-defined context, namely matrix-free functionality.
