### ISSUE TITLE
make indent fails with old git version

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9489]
On one machine with an ancient version of git (1.8.3.1), make indent doesn't do anything. I traced it back to https://github.com/dealii/dealii/blob/master/contrib/utilities/indent_common.sh#L310 which does not return any file. I assume this is because git did not support "--diff-filter=d" (the goal is to exclude deleted files).
Any suggestions on how to work around this? Maybe remove the diff-filter and ignore nonexisting files?

**Comment by GrahamBenHarper** [comment]
I don't know much about scripting, but shouldn't there be a way to take this result of this part
```
git ls-files --others --exclude-standard -- ${1};
    git diff --name-only $COMMON_ANCESTOR_WITH_MASTER -- ${1} )|
      sort -u
```
and then pass it to a `find` or `grep` to make sure each file exists?
