### ISSUE TITLE
Irrelevant references to Gmsh namespace in step-49

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#9491]
step-49 refers to the https://www.dealii.org/developer/doxygen/deal.II/namespaceGmsh.html namespace whenever 'Gmsh' appears in the text. I don't see how the dealii::Gmsh is related to the context of the discussions in step-49. 

Should there be a reference to the official Gmsh website instead?

**Comment by bangerth** [comment]
doxygen automatically links to the namespace. But we can escape the occurrence of the word by writing it as `%Gmsh`. Want to give this a try?

**Comment by agrayver** [comment]
See #9496
