### ISSUE TITLE
Copy the graph of modules from the new deal.II paper to the documentation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9538]
The current graph at https://dealii.org/developer/doxygen/deal.II/ is still from the 2007 paper. I think that the graph in the new paper is nicer and better, and we should copy it to the doc front page.

**Comment by peterrum** [comment]
@bangerth Any chance to also add `MatrixFree` to the graph ;) !?

**Comment by bangerth** [comment]
Sure! :-)

**Comment by bangerth** [comment]
@peterrum -- can you say where in the graph #9687 the matrix-free stuff would go?

**Comment by peterrum** [comment]
Closed by #9687.
