### ISSUE TITLE
[Step-6] mistake in default value of optional argument keep_constrained_dofs in DoFTools::make_sparsity_pattern()?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9546]
In step-6, we have

```
  DoFTools::make_sparsity_pattern(dof_handler,
                                  dsp,
                                  constraints,
                                  /*keep_constrained_dofs = */ false);
```

However, the default value of the argument `keep_constrained_dofs` as documented [here](https://dealii.org/developer/doxygen/deal.II/group__constraints.html#gad93530ee35c780e9ef7bc5e4856039df) is __`true`__. is this a typo?

I noticed this when doing a line-by-line comparison with step-26 (which directly builds off step-6). In step-26, we have
```
  DoFTools::make_sparsity_pattern(dof_handler,
                                  dsp,
                                  constraints,
                                  / *keep_constrained_dofs = * / true);
```

Clearly, only one of them (i.e. either step-6, or step-26/documentation) is correct, isn't it?

**Comment by peterrum** [comment]
```cpp
                                  /*keep_constrained_dofs = */ false);
```
Is just a comment to the user (so that he/she knows the purpose of that bool) and does not have any connection to the default value.

**Comment by krishnakumarg1984** [comment]
Ok, I understand. Sorry for the noise.
