### ISSUE TITLE
Several 64bit overflows in GridRefinement

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9547]
We use unsigned int for the global number of cells, which will overflow, see for example
https://github.com/dealii/dealii/blob/150f663dff987e9b0f25d82bd3f9a3ab47c5b8b8/include/deal.II/distributed/grid_refinement.h#L60

I am prepping patches to fix this.

**Comment by tjhei** [comment]
I can confirm that things work correctly now (test program ran with 10b+ cells on 2240 ranks). If you are curious: https://github.com/tjhei/step-refine-mesh-64bit/blob/master/README.md

**Comment by bangerth** [comment]
Yay!
