### ISSUE TITLE
DataOutBase needs to learn different names for axes

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#955]
If you use DataOutStack, for example, the x- and y-axis typically represent things like "distance" and "time". Yet, the various output generators (most specifically the gnuplot generator) still label these axes as "x" and "y". We should come up with a way to name axes based on user needs.

**Comment by bangerth** [comment]
(Specifically, this relates to the explanatory text at the top of gnuplot output files.)

**Comment by drwells** [comment]
Unless I am missing something else I believe this is closed by #2710.
