### ISSUE TITLE
incorrect text transformation of inline comments in tutorials

### ISSUE THREAD

**Issue by rezarastak** [dealii/dealii#9554]
It seems that the inline comments `/* comment */` are mistakenly transformed in the html version of the tutorials. For example, in steps 6 or 8, you can see this code:
```c++
DoFTools::make_sparsity_pattern(dof_handler,
                                dsp,
                                constraints,
                                / *keep_constrained_dofs = * / false);
```
Notice the incorrect space character between `/` and `*`.

**Comment by tjhei** [comment]
I have an idea how to fix...

**Comment by bangerth** [comment]
I remember that there was a reason for this. But I do not remember what that reason was :-(
