### ISSUE TITLE
Assert -> AssertThrow in release tests with FEEvaluation

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9563]
Due to #9539, a large number of matrix-free tests now fail:
https://cdash.43-1.org/viewTest.php?onlydelta&buildid=4538
This is because `FEEvaluation` holds some flags to check what the last operation was, which are only set in debug mode (for efficiency reasons). However, the `Assert` statements do not have the `#ifdef DEBUG` guard. It should be easy to go through the 5-10 places and add the flag. I won't be able to do it immediately so I open this for now before someone else stumbles upon the same problem.

**Comment by tjhei** [comment]
So the author of #9539 did not run the tests? ;-)

**Comment by masterleinad** [comment]
> So the author of #9539 did not run the tests? ;-)

It's a good indicator that these tests (and the code they check) behave significantly different from most of the library. Otherwise, I would have expected CI to fail for such a uniform change.

**Comment by tjhei** [comment]
> It's a good indicator that these tests (and the code they check) behave significantly different from most of the library. Otherwise, I would have expected CI to fail for such a uniform change.

I realized that my comment could be seen as snarky. Sorry, I did not mean to criticize you with that statement. I often do PRs without running all tests.
I should really figure out a way to expand the CI tests...

**Comment by kronbichler** [comment]
> It's a good indicator that these tests (and the code they check) behave significantly different from most of the library.

It's a combination of tracking some things only debug-only and the fact that the affected tests bring in the relevant class by a few local headers like `#include "matrix_vector_common.h` that are shared among 100 tests.
