### ISSUE TITLE
Improve documentation/asserts of MGTransferMatrixFree build() usage

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#9573]
When using the member function `` interpolate_to_mg()``, a prerequisite is to call the member function ``build()`` beforehand. This should be highlighted in the documentation, and should be checked also for all the other member functions. Further, meaningful asserts should be inserted into the code that give a hint that one has forgotten to call ``build()`` beforehand.

**Comment by peterrum** [comment]
I guess we could set in debug mode an internal bool `build_has_been_called` here:

https://github.com/dealii/dealii/blob/622eb76bc3a4f7b28ef7200390f4a4407247b5bf/source/multigrid/mg_transfer_matrix_free.cc#L95-L102

and assert it at different places (like `interpolate_to_mg()`) similarily as we do in `FE(Face)Evaluation`.

@kronbichler What do you think?

**Comment by nfehn** [comment]
I am not so familiar with the details of the implementation, but I think a ``bool`` should be avoided at any price as this is very often redundant information and therefore very error prone. It should at least not be done for reasons of computational efficiency in my opinion. I think the aim should be a member function ``build_has_been_called()`` that can extract the information from any other data structure of this class?

**Comment by kronbichler** [comment]
A simple check would be
```c++
  AssertDimension(sizes.size(), dof_handler.get_triangulation.n_levels());
```

**Comment by peterrum** [comment]
@kronbichler You mean:

```cpp
  Assert(sizes.size() == dof_handler.get_triangulation.n_levels(), 
         ExcMessage ("MGLevelGlobalTransfer::build() has not been called!"));
```

else the user still wouldn't know the actual reason, would he?

**Comment by kronbichler** [comment]
Yes, that would be a better message.
