### ISSUE TITLE
constexpr vs DEAL_II_CONSTEXPR

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9577]
What is the current logic of using ``constexpr`` directly versus ``DEAL_II_CONSTEXPR``? I know that we only enable it conditionally to work around bugs:
https://github.com/dealii/dealii/blob/5654f712d3e28297a5232a8ae5cfbf59b52749a7/cmake/checks/check_01_cxx_features.cmake#L764-L767

But I am confused that we use both:
```
$ grep DEAL_II_CONSTEXPR -r include/ source/ | wc -l
230
$ grep constexpr -r include/ source/ | wc -l
530
```
I would think using DEAL_II_CONSTEXPR everywhere would make sense. Thoughts?

**Comment by masterleinad** [comment]
We have some functions that we want to be `constexpr` regardless of if we have `C++14` or not because we are using them internally in a constexpr context.
`DEAL_II_CONSTEXPR` functions can only be used externally (unless called from other `DEAL_II_CONSTEXPR` functions). 

I see value in replacing `DEAL_II_CONSTEXPR` by `constexpr` as much as we can.

**Comment by tjhei** [comment]
Interesting, it probably would have been better to call it DEAL_II_CXX14_CONSTEXPR then.

> I see value in replacing `DEAL_II_CONSTEXPR` by `constexpr` as much as we can.

except that every time you replace one, you would have to check with all possible (and weird) compilers to check if it breaks somewhere (MSVC, Intel, etc.).

**Comment by masterleinad** [comment]
I should have said "using `constexpr` instead of `DEAL_II_CONSTEXPR` for new functions", but, yes, using either of them involves fighting with all the compilers we support. It's not like we are not used to that. :wink:

**Comment by rezarastak** [comment]
Hopefully, at some point we will require full `c++14` compatibility and the confusion of using `DEAL_II_CONSTEXPR` will be gone.

**Comment by drwells** [comment]
We support compilers that don't have full constexpr support - the definition of the macro is essentially whatever constexpr stuff we want to use that our oldest compilers cannot handle.
