### ISSUE TITLE
compile warning '-openmp-simd'

### ISSUE THREAD

**Issue by jaustermann** [dealii/dealii#958]
I compiled dealii (version 8.2.1) with Intel 13.0.0.20120731 on platform Linux x86_64 and got a warning related to '-openmp-simd' for every CXX object that was built. This is an example:

[ 77%] Building CXX object source/fe/CMakeFiles/obj_fe.release.dir/fe_tools_interpolate.cc.o
icpc: command line warning #10122: overriding '-openmp-simd' with '-oCMakeFiles/obj_fe.release.dir/fe_tools_interpolate.cc.o'

It still compiles and runs fine so far but I was wondering what this warning means and whether I should recompile with a different setting to avoid this. 
Thanks!!

**Comment by Rombur** [comment]
You get this warning because the flag -openmp-simd was introduced with Intel 13.1 Thus, the flag is ignored. The code will run fine but some operations will not be vectorized.

**Comment by bangerth** [comment]
Could we disable the flag for compilers that are older? A check such as this would probably do:
https://github.com/geodynamics/aspect/pull/516/files

**Comment by tjhei** [comment]
It is better to do a compilation check vs. hard-coding compiler versions. We do check using CHECK_CXX_COMPILER_FLAG but it doesn't detect this warning. Maybe add a  CHECK_CXX_SOURCE_COMPILES with a regex?

**Comment by bangerth** [comment]
That might work. We've had trouble in the past because some compilers just silently produce a warning but still return a zero error code. In any case, worth trying.

**Comment by Rombur** [comment]
We could also just get ride of the flag for Intel compiler. I think that @tjhei added a flag that disables vectorization because we have some tests that fail because of it.

**Comment by tjhei** [comment]
I thought openmp-simd works on intel 15? We can disable the check for <15, though. I just realized that the compiler warning mentioned above shows that the compiler confuses -openmp-simd with the -o option.

**Comment by Rombur** [comment]
Right now we always use -no-vec for the intel compiler. There is no check on the version.
