### ISSUE TITLE
VectorTools::interpolate_boundary_values()

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#9594]
If I understand it correctly, ``VectorTools::interpolate_boundary_values()`` does not assert that the number of components of the ``DoFHandler<dim>`` and the ``Function<dim>`` match. Are there reasons why this is not asserted?

At the same time ``Function<dim>`` provides a constructor with pre-initialized parameters. In my opinion, these two design choices are in conflict with each other (on the one hand not asserting and on the other hand providing default parameters, at least I spent quite some time to find a bug due to this subtlety).

**Comment by bangerth** [comment]
On 3/2/20 10:34 AM, Niklas Fehn wrote:
> If I understand it correctly, 
> |VectorTools::interpolate_boundary_values()| does not assert that the 
> number of components of the |DoFHandler<dim>| and the |Function<dim>| 
> match. Are there reasons why this is not asserted?

No good reasons. We should add such an assertion -- any patch as always 
gladly accepted!


> At the same time |Function<dim>| provides a constructor with 
> pre-initialized parameters. In my opinion, these two design choices are 
> in conflict with each other (on the one hand not asserting and on the 
> other hand providing default parameters, at least I spent quite some 
> time to find a bug due to this subtlety).

Yes, I would consider the missing assertion a bug.
