### ISSUE TITLE
CI: add a check that compiles in release mode

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9613]
Currently all testers run in debug mode, which means we don't catch warnings like #9609.  I need to think about if we want to add another configuration or change one of the existing ones.

**Comment by bangerth** [comment]
On 3/4/20 6:52 AM, Timo Heister wrote:
> Currently all testers run in debug mode, which means we don't catch warnings 
> like #9609 <https://github.com/dealii/dealii/issues/9609>. I need to think 
> about if we want to add another configuration or change one of the existing ones.

Change one of the existing ones. We don't seem to gain resources fast enough 
to have more and more checks running, and we should try to make the process of 
merging even slower.
