### ISSUE TITLE
Build failure with clang-4 due to step-69 / std::isnan

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9665]
Despite #9640, we still fail on the Clang-4.0.1 tester due to
```
examples/step-69/step-69.cc:2067:20: error: no matching function for call to 'isnan'
      AssertThrow(!std::isnan(tau_max) && !std::isinf(tau_max) && tau_max > 0.,
                   ^~~~~~~~~~
```
see here: https://cdash.43-1.org/viewBuildError.php?buildid=4935

I have tried on godbolt.org and `#include <cmath>` should make clang-4 happy to run `std::isnan`, but apparently there is something more to it in the tutorial. Any ideas?

**Comment by tamiko** [comment]
@kronbichler I'll log into the container and have a look by hand. This is also with the `libc++` standard library instead of `libstdc++` from GNU - and early versions had some funny issues.

**Comment by masterleinad** [comment]
Adding `load()` helps: https://godbolt.org/z/ZoJESa

**Comment by tamiko** [comment]
@masterleinad Jup. Already testing that as we speak.

**Comment by kronbichler** [comment]
I should have tested godbolt with `std::atomic` and not just double :smile:
