### ISSUE TITLE
Group cells for data locality in matrix-free setup

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9689]
While making benchmarks on #8319 in combination with #9656 I realized that our current scheme of assigning some cells with the need for data exchange to different groups is pretty bad for data locality. Besides the simplification from #9683, putting all children of a cell nearby and making sure they end up in the same SIMD array (if wide enough) should be done at the very least. It is especially profitable for the patch #9656 that now detects that extruded meshes have similar Jacobians; this only really works when the SIMD lanes and cells are kept together.

**Comment by masterleinad** [comment]
Do you still want to do this for the release?

**Comment by kronbichler** [comment]
I have hopes to do it, but I will see next Tuesday whether my hopes are realistic. I am always on the border of too optimistic.
