### ISSUE TITLE
Time values of write_vtu seems to be incorrect?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9722]
I am raising this issue based on my experience with step-52 tutorial which solves a time-dependent PDE (diffusion equation) using a direct solver on a 2D square mesh with zero Dirichelet BCs (at the left and right edges), and zero Neumann BCs (at the top and bottom edges). 

I think there is something wrong with how the time values of the solution are written by .vtu files.
Just to highlight the issue, for now let us focus on files produced by the backward-euler  and dopri solvers. For the backward Euler run, the tutorial produces __20__ files, named `solution-backward_euler-000.vtu` through `solution-backward_euler-200.vtu`.  For the Dopri run, the tutorial produces __2790__ files, named `solution-dopri-000.vtu` through `solution-dopri-2790.vtu`.   

However, the end time of the simulation (t_final) is actually __10 seconds__.   After loading the backward Euler results into Paraview, the animation control shows the time as 0-20 seconds, while the time-range for the Dopri results are shows as 0-279 seconds. They both are incorrect. Naturally, this incorrectness also happens when using a "time annotation" on the view port.  Furthermore, the non-integer continuous time is not shown at all. This renders the communication of the results over the actual simulation time impossible. 

The filename is clearly appended with the time-step number (at every 10th time-step). Since, it shows the time-step as 1/10th of the value of its corresponding filename, how is Paraview getting this `mod 10` calculation? i.e. how is the time-step encapsulated into the solution vector?  

I thought the 'solution' variable is just a standard Vector type which cannot really hold 'time' anywhere. But the real-requirement is that we must indeed inform 'time' to the .vtu file somehow.  Also, interestingly step-26 which is a very similar problem (using an iterative solver) does not suffer from this issue.

Is this a bug in __write_vtu()__?

**Comment by marcfehling** [comment]
You somehow need to add the information about the time or cycle during your simulation to your vtk files manually. Otherwise Paraview and Visit do not know from where to gather that information and will assign indicators to all files in their lexicographical order (if I'm correct).

I haven't tried this feature yet, but you can add [`VTKFlags`](https://www.dealii.org/current/doxygen/deal.II/structDataOutBase_1_1VtkFlags.html) to your `DataOut` object which will write out the corresponding information. The usage of this feature is for example demonstrated in [`step-23`](https://www.dealii.org/current/doxygen/deal.II/step_23.html#WaveEquationoutput_results).

Correct me if I'm wrong :)

**Comment by masterleinad** [comment]
Have a look at `DataOutBase::write_pvd_record`(https://www.dealii.org/developer/doxygen/deal.II/namespaceDataOutBase.html#a6f1c052ba49fd44cd8e3f35ba871aebd). That function allows to add information about the simulation time.

**Comment by masterleinad** [comment]
That function is also used in step-18.

**Comment by bangerth** [comment]
As others have pointed out, you seem to frequently assume that something is a bug without spending the time to investigate. That's not a useful approach.

Fortunately, it's easy to fix: #9754.

**Comment by krishnakumarg1984** [comment]
@bangerth We probably need to quickly reopen this again #9754 does not fix this for embedded Runge Kutta methods.

**Comment by krishnakumarg1984** [comment]
@marcfehling  While step-23 does indeed demonstrate the `vtkflags` feature, it is done in the context of using the zlib compression algorithm for faster plotting speeds and to optimise disk space. I am interested in how to get the running time information on the `.vtu` files.

**Comment by krishnakumarg1984** [comment]
@bangerth  I have worked on a patch myself and submitted a PR #9754.
