### ISSUE TITLE
Test matrix_free/matrix_vector_faces_28.debug fails

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9757]
As already mentioned in https://github.com/dealii/dealii/pull/9688#issue-391423160, the test fails for me on an Intel Broadwell server node.

The output I get is:
```
DEAL:2d::Degree of element: 1
DEAL:2d::Norm of difference:           4.87e-16
DEAL:2d::Norm of difference no update: 0.0157
DEAL:2d::Norm of difference w update:  0.000202
DEAL:2d::Degree of element: 2
DEAL:2d::Norm of difference:           1.92e-15
DEAL:2d::Norm of difference no update: 0.00672
DEAL:2d::Norm of difference w update:  2.50e-15
DEAL:3d::Degree of element: 1
DEAL:3d::Norm of difference:           1.88e-16
DEAL:3d::Norm of difference no update: 5.11e-05
DEAL:3d::Norm of difference w update:  1.88e-16
DEAL:3d::Degree of element: 2
DEAL:3d::Norm of difference:           1.06e-16
DEAL:3d::Norm of difference no update: 5.82e-05
DEAL:3d::Norm of difference w update:  1.06e-16
```

The expected output is:
```
DEAL:2d::Degree of element: 1
DEAL:2d::Norm of difference:           4.87e-16
DEAL:2d::Norm of difference no update: 0.0179
DEAL:2d::Norm of difference w update:  4.87e-16
DEAL:2d::Degree of element: 2
DEAL:2d::Norm of difference:           1.92e-15
DEAL:2d::Norm of difference no update: 0.00672
DEAL:2d::Norm of difference w update:  2.50e-15
DEAL:3d::Degree of element: 1
DEAL:3d::Norm of difference:           1.88e-16
DEAL:3d::Norm of difference no update: 5.11e-05
DEAL:3d::Norm of difference w update:  1.88e-16
DEAL:3d::Degree of element: 2
DEAL:3d::Norm of difference:           1.06e-16
DEAL:3d::Norm of difference no update: 5.82e-05
DEAL:3d::Norm of difference w update:  1.06e-16
```

The third and forth line do not match.

**Comment by kronbichler** [comment]
Is your system configured with `DEAL_II_WITH_THREADS=OFF`? The output produced on your system in the fourth line is clearly wrong - it should be in the range of roundoff `1e-16` but it is large, 0.0002. We need to find out what the reason could be; my best guess right now is that the cell similarity in `FEValues` underlying the reference result is broken.

**Comment by peterrum** [comment]
This is my configuration of deal.II:
```
cmake \
    -D DEAL_II_WITH_64BIT_INDICES="ON" \
    -D CMAKE_BUILD_TYPE="Debug" \
    -D CMAKE_CXX_COMPILER="mpic++" \
    -D CMAKE_CXX_FLAGS="-march=native -Wno-array-bounds" \
    -D DEAL_II_CXX_FLAGS_RELEASE="-O3" \
    -D CMAKE_C_COMPILER="mpicc" \
    -D DEAL_II_WITH_MPI="ON" \
    -D DEAL_II_WITH_P4EST="ON" \
    -D MPIEXEC_PREFLAGS="-bind-to none" \
    -D DEAL_II_WITH_LAPACK="ON" \
    -D DEAL_II_WITH_HDF5="OFF" \
    -D DEAL_II_FORCE_BUNDLED_BOOST="OFF" \
    -D DEAL_II_WITH_TRILINOS="ON" \
    -D DEAL_II_WITH_THREADS="OFF" \
    -D DEAL_II_COMPONENT_DOCUMENTATION="OFF" \
    -D DEAL_II_WITH_METIS:BOOL="ON" \
    ../dealii
```

BTW: On the gold nodes the problem does not appear.

**Comment by kronbichler** [comment]
I can confirm that the problem is related to `-D DEAL_II_WITH_THREADS="OFF"`.

> BTW: On the gold nodes the problem does not appear.

Are you sure it is the exact same configuration, in particular `DEAL_II_WITH_THREADS=OFF` and the same SIMD width? Xeon Broadwell and Xeon Gold should deliver the same result on the same binary.

**Comment by peterrum** [comment]
> Are you sure it is the exact same configuration, in particular DEAL_II_WITH_THREADS=OFF and the same SIMD width?

You are right. It was not the same configuration. With the same setup as above I also get the same problem on the gold nodes.

**Comment by kronbichler** [comment]
I have a solution. It was the cell similarity, giving a broken reference result with `MappingFEField`. I am working on a test right now.
