### ISSUE TITLE
Pull request #943 has side effects

### ISSUE THREAD

**Issue by guidokanschat** [dealii/dealii#976]
Pull request #943 copies the matrix elements from one triangle to the other.

This is fine, if you only assemble Laplace matrices. If not, it has side effects, if the previous matrix was non-symmetric.

I am not sure, but I guess adding both into M(i,j) and M(j,i) inside the fitst loop would fix it. Not sure though it has the same saving.

**Comment by bangerth** [comment]
Good point. Feel free to revert the original patch.

**Comment by bangerth** [comment]
@davydden ?

**Comment by davydden** [comment]
are there any user cases when one would like to add a local symmetric laplace matrix to the previous one which is not symmetric?
If this is indeed crucial, one could still split the loops into:
- adding to diagonal
- calculating upper triangle and adding to both upper and lower of the original matrix.
That would still be much faster than looping over all dofs. 
I clearly see the difference in performance when assembling Laplace matrices with order ~ 10-12.

**Comment by guidokanschat** [comment]
I use the local integrators to build my systems, adding several of them let's say, advection and diffusion.
