### ISSUE TITLE
Multigrid test failures

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9768]
After #9750 (?), we have some test failures in `mpi/multigrid_uniform` and `mpi/multigrid_adaptive`:
https://cdash.43-1.org/viewTest.php?onlydelta&buildid=5290
@masterleinad can you have a look?

**Comment by peterrum** [comment]
@kronbichler I have seen this issue yesterday also when I run the test suite. I think the test program behaves correctly but the output level has decreased. At the moment it outputs: 
```
DEAL::Cycle 0:
DEAL::   Number of active cells:       16
DEAL::Number of degrees of freedom: 25   L0: 4   L1: 9   L2: 25
DEAL::   Number of degrees of freedom: 25 (by level: 4, 9, 25)
DEAL:cg::Starting value 0.187500
DEAL:cg::Convergence step 5 value 1.65911e-17
```

while it used to output all v-cycle details.

**Comment by masterleinad** [comment]
Yes, I accidentally also deleted the (deprecated) call to `set_debug` here already. I will fix this in one way or the other likely today.
