### ISSUE TITLE
Merge DoFHandler and hp::DoFHandler

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9839]
The purpose of this issue is to collect the PRs related to merging `DoFHandler` and `hp::DoFHanlder` (as explained in https://github.com/dealii/dealii/pull/9760#issue-395116540). The first phase includes the introduction of an `(internal::)DoFHandlerBase`.

**Comment by peterrum** [comment]
I have closed the two PRs related to this issue for now (#9840 and #9760). I will open a new PR targeting the merge of `DoFHandler` with `hp::DoFHandler` after the release of 9.2.

A first implementation shows that merging `DoFHandler` and `hp::DoFHandler` could be possible without any major compatibility issues if the internal data structures are changed and merged. The current code can be found at https://github.com/peterrum/dealii/pull/3. All tests are passing. However, I still have to go through the whole code at least once again.

**Comment by bangerth** [comment]
I think that's the right approach -- let's wait until after 9.2.

If you have smaller pieces that only move code around in ways not visible to users (e.g., does not move public member functions), then I'd be happy to consider them separately now already.
