### ISSUE TITLE
Deprecate ParameterHandler::parse_input_...() functions to make them private in the long run?

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#9878]
I think it would make sense to reduce the interface to ``ParameterHandler`` by removing some of the ``parse_input()`` functions from the public interface, especially those with ending `_from_json()`, `from_xml()`.

**Comment by nfehn** [comment]
how about realizing this for the next release?

**Comment by drwells** [comment]
I don't think we should make this change. Most of the classes in the library have read functions for specific file formats, like `GridIn::read_vtk()` - we should be consistent with that style here. It's also nice to let callers specify a file format completely independent of the file extension (or whatever other criterion we would use).

What would be the advantage to removing these functions from the public interface?

**Comment by nfehn** [comment]
Yes, the only advantage would be to make the interface more lean. The unifying function came later and maybe the other public function would not have been written against the background that the unifying one would have existed before, but thats speculation. I see your point. Maybe you could then also close this issue if there are no plans in this direction for the future.

**Comment by drwells** [comment]
Lets leave this open for a little while longer in case other people have differing opinions.
