### ISSUE TITLE
tbb::task is deprecated

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#9901]
I just got the most recent (2020.2) version of TBB and I now get the following deprecation warnings:
```
/usr/include/tbb/task.h:21:139: note: #pragma message: TBB Warning: tbb/task.h is deprecated.
For details, please see Deprecated Features appendix in the TBB reference manual.
```
The manual doesn't state much other than acknowledging that this is deprecated. `tbb::task` (and `tbb::task_group`) are foundational to the way we implement multithreading so I really think we should address this in time for the release.

**Comment by tjhei** [comment]
This is weird. I can't find anything about this in https://www.threadingbuildingblocks.org/docs/help/index.htm#reference/appendices/deprecated_features.html

**Comment by bangerth** [comment]
Or here: https://software.intel.com/sites/default/files/managed/b2/d2/TBBRevamp.pdf

**Comment by tjhei** [comment]
I created https://github.com/oneapi-src/oneTBB/issues/243, we'll see what they say.

**Comment by drwells** [comment]
The manual I referred to is this one:

https://software.intel.com/en-us/node/851749

**Comment by bangerth** [comment]
Question: Can we find out whether TBB used C++11 facilities for tasks? The C++11 tasking facilities are actually much easier to use than the TBB ones and it would not be very difficult to use `std::async` and `std::future` to replace our calls to the TBB in `Threads::Task`. It might enable us to just get rid of all of that `TBB:task` stuff altogether.

I haven't done that yet because I did not want us to use both C++11 tasking and TBB tasking for fear that they both keep independent thread pools. But if, underneath, the TBB just calls the C++11 facilities anyway, then maybe there is no reason not to mix them...

**Comment by drwells** [comment]
I believe that our tentative plan is to not rewrite our interface this close to the release and instead add a symbol to remove the deprecation warnings - I'll put up a PR to do this.

**Comment by tjhei** [comment]
so we should just define ``TBB_SUPPRESS_DEPRECATED_MESSAGES`` for now.
see https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/include/tbb/internal/_deprecated_header_message_guard.h#L19

**Comment by bangerth** [comment]
`source/matrix_free/task_info.cc` is now the only file that still uses the TBB task interface.

**Comment by kronbichler** [comment]
I will try to port that to taskflow, but I won't manage to do so in the next three weeks. The functionality is not super high priority, so we could simply disable threading in the meantime if we want to move ahead and enable it again when I'm ready.

**Comment by bangerth** [comment]
I don't think we're in a particular hurry with this.

**Comment by drwells** [comment]
The original intent of me assigning this to myself was that I would find a TBB workaround. Since we went with a different solution (taskflow + C++14) I am going to unassign myself.

**Comment by bangerth** [comment]
`task_info.cc` remains to be converted. I tried to look at what we are doing there but then found this gem:
```
                  if (odds == evens)
```
That's at least a bit funny, whereas none of the TBB task interface actually is ;-)

**Comment by peterrum** [comment]
I guess if we drop taskflow for this issue has a higher priority now?

**Comment by bangerth** [comment]
Can we close this now? The only place where `tbb::task` is still used is in `source/matrix_free/task_info.cc`, and it is disabled for newer versions of TBB.
