### ISSUE TITLE
Check the usage of OutputStyle::XML and ::JSON in ParameterHandler

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9903]
As noted in https://github.com/dealii/dealii/issues/9888#issuecomment-613850600, the following lines:

https://github.com/dealii/dealii/blob/5637bcf9db09af419ea5bbb3c92e5b262fc603aa/source/base/parameter_handler.cc#L1331-L1332

should be:
```cpp
  // this function should not be necessary for XML or JSON output...
  Assert((style != XML) && (style != ShortXML) && 
         (style != JSON) && (style != ShortJSON), ExcInternalError());
```
or 
```cpp
  // this function should not be necessary for XML or JSON output...
  Assert(!((style & XML) || (style & JSON)), ExcInternalError());
```

**Comment by nfehn** [comment]
i guess this issue can also be closed now?
