### ISSUE TITLE
Doxygen shows template specializations

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9914]
Probably due to #9855, doxygen now seems to list template specializations of classes. Look for example at the GridGenerator page:
https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html
Here, you see `hyper_ball` not only for the templated case `dim` with documentation
https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#a533c4778cbc9bcbed365dcab42ca4418
but also the variants for `Triangulation<1>`, `Triangulation<2>`, `Triangulation<3>` without the documentation. Compare this to the last release where we only showed the templated part:
https://dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html
I think this is very confusing even though I know what to look for, so imagine how this appears to novices. Thoughts?

**Comment by tjhei** [comment]
This is not ideal. I can see two solutions:
a) disable HIDE_UNDOC_MEMBERS again
b) do not parse .cc files (see #9876)

**Comment by tjhei** [comment]
I think @bangerth enabled parsing of .cc files, maybe he has an idea why we should/should not merge #9876.

**Comment by kronbichler** [comment]
Anything we want to do here for the release? I think a page like [this](https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html) confuses users. Besides trying `HIDE_UNDOC_MEMBERS`, we could selectively add `#ifndef DOXYGEN`.

**Comment by tjhei** [comment]
I tried, but changing HIDE_UNDOC_MEMBERS back to YES doesn't work. Stuff is still there. :-(

**Comment by drwells** [comment]
I think the cure for #7730 is worse than the disease - unless we have a fix I believe it is preferable to revert #9855. Thoughts?

**Comment by tjhei** [comment]
or we disable .cc parsing and keep the current settings...

**Comment by bangerth** [comment]
I'd really like to keep the parsing of .cc files. Didn't someone (@masterleinad?) do a lot of work of explicitly hiding template specializations already? I think we should do the same here.

**Comment by masterleinad** [comment]
I was hiding everything in source files doxygen was complaining about I couldn't fix. The problem here is rather to find all the places we are thinking that are messed up. Of course, I still agree that hiding itself is OK.

**Comment by kronbichler** [comment]
I guess #10147 solves the problem at hand, which is the only place where I had the impression something needed to be done. I suggest we close this issue here and take subsequent topics we find on a case-by-case basis, given that the global settings seem to reflect the current consensus.
