### ISSUE TITLE
"libpthreads"?

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#9939]
It looks like cmake bombs on a request for "-lpthreads" which I have no idea which it wants why. Cmake logs attached.

[CMakeError.log](https://github.com/dealii/dealii/files/4515809/CMakeError.log)
[CMakeOutput.log](https://github.com/dealii/dealii/files/4515810/CMakeOutput.log)

**Comment by masterleinad** [comment]
Probably, the better place to ask your question (is there any here?) is [Google Groups](https://groups.google.com/forum/#!forum/dealii).
