### ISSUE TITLE
Improve docu of DataOut::add_data_vector()

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#9965]
A note could/should be added to the documentation mentioning that ghost values of the vector have to be updated, e.g.

@note When working in parallel, the vector to be written needs to be ghosted with read access to all degrees of freedom on the locally owned cells, see the step-40 or step-37 tutorial programs for details, i.e., it might be necessary to call vector.update_ghost_values().

**Comment by peterrum** [comment]
That might be useful indeed. It is already asserted but a note would be helpful, too! The question is which function should get the note. I don't think the function `add_data_vector()` is actually causing the problem, but `build_patches()` (since this is when the vectors are actually read). Maybe both functions should get the note?

**Comment by bangerth** [comment]
The error might currently come from `build_patches()`, but `add_data_vector()` is the one that people call with the wrong vector. I think that's the right place.

@nfehn -- you already have the right kind of text. Want to write a patch? Thanks in advance!

**Comment by nfehn** [comment]
@bangerth There are several functions (6x add_data_vector(), 2x add_mg_data_vector()). I am not so familiar with this code. Should I put the same text everywhere, or in a master-slave style with reference to master for the slaves, and which function would then be the master?

**Comment by kronbichler** [comment]
I would suggest to put the documentation to one function only. The central one which others are referring to is this one here:
https://www.dealii.org/current/doxygen/deal.II/classDataOut__DoFData.html#ace4b76e565ba0701c4d32c26075ed3b9
(The function taking a vector, a vector of strings with names, a vector "type" argument, and a vector of component interpretations).
