### ISSUE TITLE
Mesh loop assemble_boundary_faces uses empty data structures

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#9971]
I've attached a test where I'm just trying to compute the volume of a triangulation and the area of its boundary using `mesh_loop()`; something easily verifiable on a 1x1 domain. Volume integration seems to work fine. But when I do the boundary integral alone by specifying to `mesh_loop` that it must only `MeshWorker::assemble_boundary_faces`, then I do not get the expected value for the boundary integral (no, the total area of the boundary is not 3 in 2d or 3.5 in 3d!). I've checked that local integral is being computed in the `boundary_worker`, but where the problem seems to manifest itself is the `copier`. On some faces, the `CopyData` sent to the `copier` seems to be reset, so that sometimes `0` is accumulated into the destination. 

@luca-heltai, @tjhei Do you have any idea what might be going wrong here? I'm not 100% sure if this is a bug in the library as opposed to me misusing `mesh_loop`, so I'd be happy to be informed if there's an error in my own code.

[mesh_loop_integrals_01.cc.txt](https://github.com/dealii/dealii/files/4541968/mesh_loop_integrals_01.cc.txt)
[mesh_loop_integrals_01.output.txt](https://github.com/dealii/dealii/files/4541969/mesh_loop_integrals_01.output.txt)

**Comment by jppelteret** [comment]
OK, so I figured out my mistake. It is incorrect to call `copy_data=0` inside of a `boundary_worker`. If you arrive at a cell that has two or more faces on the cell, then the same `copy_data` is used on those faces. So resetting it somewhere along the way is clearly impermissible.

I propose that we remove [`CopyData::operator=`](https://dealii.org/developer/doxygen/deal.II/structMeshWorker_1_1CopyData.html#ade60931cf6448124c79f04016f471c5d), because I don't think that we use it internally (it looks like we use the copy constructor to generate a new `copy_data` from a `sample_copy_data`) so I don't think that it serves any real purpose. Any thought on this? I'll leave the issue open for now.

P.S. I was going to suggest that we could improve the documentation for `CopyData` to state that it must be copy constructible and is guaranteed to be reset internally by `mesh_loop`. However, it is indeed stated in `mesh_loop`'s documentation, but it was pushed right off the page because of the insanely long function signature that Doxygen seems to trip up on.

**Comment by tjhei** [comment]
> Any thought on this?

I will let @luca-heltai comment on this but I also don't see a reason to clear out a CopyData object.

**Comment by jppelteret** [comment]
If we do decide to remove it, should we deprecate the function or just get rid of it outright and add an incompatibility entry? I'm in favour of the latter, since this is potentially dangerous and could let to erroneous results if you do something stupid like I did.

**Comment by bangerth** [comment]
I remember that we had that discussion recently with @tjhei, but I don't remember which PR that was in -- maybe a new tutorial program (12?)?

In any case, the paragraph in the documentation of `mesh_loop()` got in there for precisely this reason: The `copier` is reset at the beginning of working on one cell, and is not reset (nor should be reset) between faces. I too thought that that was confusing, but I don't have a better option either.

The relevant documentation is here: https://github.com/dealii/dealii/blob/master/include/deal.II/meshworker/mesh_loop.h#L156-L165 Maybe we should add an example like yours to this piece of documentation, marking the line in question as a *bug*?

Resetting the copier object is here: https://github.com/dealii/dealii/blob/master/include/deal.II/meshworker/mesh_loop.h#L271

**Comment by bangerth** [comment]
Which function specifically do you refer to that you want to remove?

**Comment by jppelteret** [comment]
I propose that we remove [`CopyData::operator=`](https://dealii.org/developer/doxygen/deal.II/structMeshWorker_1_1CopyData.html#ade60931cf6448124c79f04016f471c5d).

**Comment by bangerth** [comment]
Oh, I had assumed that `CopyData` is a template argument type :-)

But that won't work:
https://github.com/dealii/dealii/blob/master/include/deal.II/meshworker/mesh_loop.h#L271

**Comment by jppelteret** [comment]
> The relevant documentation is here...

Yes, I see it somewhere there :-D

<img width="1671" alt="Screen Shot 2020-04-30 at 23 31 15" src="https://user-images.githubusercontent.com/10460610/80761440-dc621180-8b3a-11ea-8f34-b1c8e26ac0fb.png">

It was actually just bad luck. The critical sentence was just pushed off the page, so it didn't catch my attention when I was skimming through the docs.

**Comment by jppelteret** [comment]
@bangerth I think that we're getting mixed up. I was suggesting that we remove the one that takes in a `double` as an argument (mirroring `cell_matrix=0;`).
```
void MeshWorker::CopyData< n_matrices, n_vectors, n_dof_indices >::operator= ( const double number )  
```
But I can also see your point, that a user could in principle just use the copy constructor. Could we somehow these private and make `mesh_loop` a friend that may invoke the copy constructor?

**Comment by jppelteret** [comment]
> Maybe we should add an example like yours to this piece of documentation, marking the line in question as a bug?

Yes, I can do that.

**Comment by bangerth** [comment]
Oh, I missed that there are multiple. Yes, we can `=delete` the one that takes a double as argument. Or just remove it.

**Comment by masterleinad** [comment]
> But I can also see your point, that a user could in principle just use the copy constructor. Could we somehow these private and make `mesh_loop` a friend that may invoke the copy constructor?

You might also just be able to define some `copy_from` function as we do in other classes.

**Comment by jppelteret** [comment]
Thanks for the suggestion @masterleinad. The one drawback with that is that you can inherit from `CopyData` and then inject your own data structures into the class. We'd then have to make `copy_from` virtual and expect the user to write a proper copy function that invokes the base class's. Then again, I guess its much of the same with the copy constructor...

**Comment by bangerth** [comment]
On 4/30/20 4:14 PM, Daniel Arndt wrote:
>     But I can also see your point, that a user could in principle just use the
>     copy constructor. Could we somehow these private and make |mesh_loop| a
>     friend that may invoke the copy constructor?
> 
> You might also just be able to define some |copy_from| function as we do in 
> other classes.

That doesn't solve the problem. People might still be tempted to do something 
like 'copy_object.cell_matrix = 0'. The problem isn't going away by removing 
the operator.
