### ISSUE TITLE
Add quadrature_point_indices() to FeValuesBase

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#9972]
Mimicking `GeometryInfo<dim>::face_indices()`, we should have something like `FeValuesBase::quadrature_point_indices()` that allows us to write `for (const unsigned int q_point : fe_values.quadrature_point_indices())`.

**Comment by bangerth** [comment]
Ah yes, that would be nice!

I've been wondering for the past 11 years already why the standard does not overload `...` so that one can write
```
  for (const auto i : 0...fe_values.n_quadrature_points())
```
That would seem like a rather nice, idiomatic, way to write these loops these days...

**Comment by masterleinad** [comment]
@bangerth You can always write a proposal. :wink:
