### ISSUE TITLE
Add ranged based loops for local DoF indices to FEValuesBase

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#9988]
As an extension to #9987, should we have something like `FEValuesBase::dof_indices()` that allows us to write 
```
for (const unsigned int q_point : fe_values.quadrature_point_indices())
  for (const unsigned int I : fe_values.dof_indices())
    for (const unsigned int J : fe_values.dof_indices())
    {...}
```
? We may then also wish to consider some mechanism to get out the diagonal + upper/lower indices too. This would be useful for assembling symmetric systems. One implementation that I've thought of thus far would be to have three separate functions `dof_indices()`, `dof_indices_starting_at(idx)`, `dof_indices_ending_at(idx)`, to allow traversal like
```
for (const unsigned int q_point : fe_values.quadrature_point_indices())
  for (const unsigned int I : fe_values.dof_indices())
    for (const unsigned int J : fe_values.dof_indices_ending_at(I)) // build lower triangle + diag
    {...}
```

**Comment by bangerth** [comment]
I like it, but we should name the function `local_dof_indices()` to make clear that it's a local numbering, not the global indices.

**Comment by jppelteret** [comment]
Great! I've actually just finished putting this together and, after being reminded that `FEValuesBase` has `cell_dof_indices` as a static member, was going to propose the names `cell_dof_indices()`, `cell_dof_indices_starting_at()` and `cell_dof_indices_ending_at()`. Which would you prefer?

**Comment by jppelteret** [comment]
Nevermind -- I've thought about it a little and `local_dof_indices()` is the right choice. Thanks for the suggestion!
