### ISSUE TITLE
create_coupling_mass_matrix too slow

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#9989]
The test `non_matching/coupling_08.debug` regularly times out on some machines, like this one:
https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=5877
The test runs a ridiculously small problem with 125 and 729 dofs, so I think we should be able to reduce the work. What I don't like in the code is this part:
https://github.com/dealii/dealii/blob/ea67b44dc1891da7aab1648f6c6f71143f7c7803/source/non_matching/coupling.cc#L850-L870
That's four nested loops. I have not spent time on thinking through the dependencies of the loop, but my feeling suggests this should be doable with three nested loops. Anyone with an idea? The other thing that comes to mind to calm down the work in the 3D/3D case is to reduce the quadrature formula to only 2 points per direction rather than 3 in that particular test - but again, I have not looked into whether that is possible/necessary.

**Comment by tjhei** [comment]
> That's four nested loops.

and it is itself inside a loop of all matching cells.

I checked and unsurprisingly, it is the last step in the test that is slow (3min without load on the machine). I noticed that the line
https://github.com/dealii/dealii/blob/ea67b44dc1891da7aab1648f6c6f71143f7c7803/source/non_matching/coupling.cc#L857
is executed 2 million times for that.

> The other thing that comes to mind to calm down the work in the 3D/3D case is to reduce the quadrature formula to only 2 points per direction rather than 3 in that particular test -

.. and that can be combined with refining fewer times as well. I don't think this will render the test ineffective.

**Comment by drwells** [comment]
Fixed by #9992.

**Comment by kronbichler** [comment]
We have addressed the test, but I'm not sure if we have addressed the underlying issue of a high complexity. Is someone with insight into the code wanting to have thought?

**Comment by drwells** [comment]
Reducing the total number of global refinements and number of quadrature points should lower the total compute time by a factor of 12 so I assumed we could close this. Should we keep this open until we figure out if there is a better algorithm?

**Comment by drwells** [comment]
Lets keep it open :)
